### ISSUE TITLE
Office365 SMTP can't connect

### ISSUE THREAD

**Issue by GooGoVu** [PHPMailer/PHPMailer#1000]
Everything was working and it just stopped. Please help, the website is paralyzed.

Connection: opening to 40.97.128.18:587, timeout=300, options=array ()
Connection: opened
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "220 DM5PR12CA0012.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 28 Feb 2017 19:51:01 +0000"
SERVER -> CLIENT: 220 DM5PR12CA0012.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 28 Feb 2017 19:51:01 +0000
CLIENT -> SERVER: EHLO www.domain.com
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "250-DM5PR12CA0012.outlook.office365.com Hello [50.21.186.168]"
SMTP -> get_lines(): $data is "250-DM5PR12CA0012.outlook.office365.com Hello [50.21.186.168]"
SMTP -> get_lines(): $str is "250-SIZE 157286400"
SMTP -> get_lines(): $data is "250-DM5PR12CA0012.outlook.office365.com Hello [50.21.186.168]250-SIZE 157286400"
SMTP -> get_lines(): $str is "250-PIPELINING"
SMTP -> get_lines(): $data is "250-DM5PR12CA0012.outlook.office365.com Hello [50.21.186.168]250-SIZE 157286400250-PIPELINING"
SMTP -> get_lines(): $str is "250-DSN"
SMTP -> get_lines(): $data is "250-DM5PR12CA0012.outlook.office365.com Hello [50.21.186.168]250-SIZE 157286400250-PIPELINING250-DSN"
SMTP -> get_lines(): $str is "250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $data is "250-DM5PR12CA0012.outlook.office365.com Hello [50.21.186.168]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $str is "250-STARTTLS"
SMTP -> get_lines(): $data is "250-DM5PR12CA0012.outlook.office365.com Hello [50.21.186.168]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-STARTTLS"
SMTP -> get_lines(): $str is "250-8BITMIME"
SMTP -> get_lines(): $data is "250-DM5PR12CA0012.outlook.office365.com Hello [50.21.186.168]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-STARTTLS250-8BITMIME"
SMTP -> get_lines(): $str is "250-BINARYMIME"
SMTP -> get_lines(): $data is "250-DM5PR12CA0012.outlook.office365.com Hello [50.21.186.168]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-STARTTLS250-8BITMIME250-BINARYMIME"
SMTP -> get_lines(): $str is "250-CHUNKING"
SMTP -> get_lines(): $data is "250-DM5PR12CA0012.outlook.office365.com Hello [50.21.186.168]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-STARTTLS250-8BITMIME250-BINARYMIME250-CHUNKING"
SMTP -> get_lines(): $str is "250 SMTPUTF8"
SERVER -> CLIENT: 250-DM5PR12CA0012.outlook.office365.com Hello [50.21.186.168]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-STARTTLS250-8BITMIME250-BINARYMIME250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: STARTTLS
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "220 2.0.0 SMTP server ready"
SERVER -> CLIENT: 220 2.0.0 SMTP server ready

**Warning: stream_socket_enable_crypto(): Peer certificate CN=`outlook.com' did not match expected CN=`40.97.128.18' in /var/www/vhosts/localhost.localdomain/omodelstalent.com/pm/class.smtp.php on line 367**
SMTP Error: Could not connect to SMTP host.
CLIENT -> SERVER: QUIT
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is ""
SERVER -> CLIENT: 
SMTP ERROR: QUIT command failed: 
Connection: closed
SMTP Error: Could not connect to SMTP host.

Fatal error: Uncaught phpmailerException: SMTP Error: Could not connect to SMTP host. in /var/www/vhosts/localhost.localdomain/omodelstalent.com/pm/class.phpmailer.php:1678 Stack trace: #0 /var/www/vhosts/localhost.localdomain/omodelstalent.com/pm/class.phpmailer.php(1540): PHPMailer->smtpConnect(Array) #1 /var/www/vhosts/localhost.localdomain/omodelstalent.com/pm/class.phpmailer.php(1335): PHPMailer->smtpSend('Date: Tue, 28 F...', 'This is a multi...') #2 /var/www/vhosts/localhost.localdomain/omodelstalent.com/pm/class.phpmailer.php(1213): PHPMailer->postSend() #3 /var/www/vhosts/localhost.localdomain/omodelstalent.com/submit-upload2.php(98): PHPMailer->send() #4 {main} thrown in /var/www/vhosts/localhost.localdomain/omodelstalent.com/pm/class.phpmailer.php on line 1678

**Comment by Synchro** [comment]
Read what the error says:

> Peer certificate CN=outlook.com did not match expected CN=40.97.128.18

You've done something like:

    $mail->Host = gethostbyname('outlook.com');

or

    $mail->Host = '40.97.128.18';

Both of these will connect expecting to see a certificate in the name of the IP address, which will not match the `outlook com` name that actually is on the certificate. Do this instead:

    $mail->Host = 'smtp.outlook.com';

(Which I think is the correct host for sending via outlook - as I recall it has a multi-name certificate that covers this).

**Comment by GooGoVu** [comment]
None of the above options work.  If I don't use gethostbyname(), I get this error


Connection: opening to smtp.outlook.com:587, timeout=300, options=array ()
Connection: Failed to connect to server. Error number 2. "Error notice: stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known
Connection: Failed to connect to server. Error number 2. "Error notice: stream_socket_client(): unable to connect to smtp.outlook.com:587 (php_network_getaddresses: getaddrinfo failed: Name or service not known)
SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Name or service not known (0)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

Fatal error: Uncaught phpmailerException: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting in /var/www/vhosts/localhost.localdomain/omodelstalent.com/pm/class.phpmailer.php:1541 Stack trace: #0 /var/www/vhosts/localhost.localdomain/omodelstalent.com/pm/class.phpmailer.php(1335): PHPMailer->smtpSend('Date: Tue, 28 F...', 'This is a multi...') #1 /var/www/vhosts/localhost.localdomain/omodelstalent.com/pm/class.phpmailer.php(1213): PHPMailer->postSend() #2 /var/www/vhosts/localhost.localdomain/omodelstalent.com/submit-upload2.php(99): PHPMailer->send() #3 {main} thrown in /var/www/vhosts/localhost.localdomain/omodelstalent.com/pm/class.phpmailer.php on line 1541


When I switch to Amazon SMTP it works perfect. Did Microsoft make changes?

**Comment by Synchro** [comment]
Looks like your DNS is broken; fix that and it should work. Amazon isn't too hot on supporting IPv6; MS is better, but it looks like your ISP is somewhere in between.

**Comment by Synchro** [comment]
In the guide take a look at the section about `SMTPOptions` for certificate verification; it's a low-quality workaround (its a security downgrade), but it will solve your immediate problem.

**Comment by kapilsurolia** [comment]
I am not able to connect with $mail->Host = 'smtp.outlook.com';

Showing error. Please share how can i fix this error with PHPMailer class.

**Comment by Synchro** [comment]
Don't hijack closed issues. Read the thread, do what it says. It's probably not your PHP that's the problem, more likely your network or ISP.
