### ISSUE TITLE
SMTP protocol synchronization error (input sent without waiting for greeting)

### ISSUE THREAD

**Issue by Xake** [PHPMailer/PHPMailer#1003]
Seems to be the same as #517.

By adding sleep(5); as line 327 in smtp.class I can get the mail to work.
Please advice in how I can help debug this to get it fixed.
I use PHPMailer as a part of a cacti-1.0.5-install, and cannot send testmails due to this.

**Comment by Synchro** [comment]
Can you do what I suggested in #517 - set `SMTPDebug = 4`, and you should be able to see the connection result and the response obtained after it waits for server greeting on line 338, i.e. we want to see what is in `$announce`.

**Comment by Xake** [comment]
I'm trying to figure out where the debug infoprmation from when running from cacti lands....

**Comment by Xake** [comment]
Do you have a little cli-debug-version I can try with?

**Comment by Xake** [comment]
Was able to reproduce by creating a little cli version based on smtp.phps and setting the timeout to 5s like in the cacti code.
Is phpmailer supposed to act like this if timeout is set to a too short time?

**Comment by Synchro** [comment]
No - if the server does not respond within the timeout, the connect function will return false, and the connection will be dropped. It would help if you tried what I said above - we need to eliminate your server as the cause.

**Comment by Xake** [comment]
I tried it, it works fine as long as I do not set a to short timeout.

Timeout not set:

pehj01@gbg1-noc1:/var/www/cacti/include/phpmailer$ php test.phps
No log handling enabled - turning on stderr logging
 SERVER -&gt; CLIENT: 220 *****************************************************************************<br>
CLIENT -&gt; SERVER: EHLO gbg1-noc1<br>
SERVER -&gt; CLIENT: 250-withheld Hello gbg1-noc1 [192.168.5.23]250-SIZE 52428800250-8BITMIME250-PIPELINING250 XXXA<br>
CLIENT -&gt; SERVER: MAIL FROM:&lt;withheld@withheld&gt;<br>
SERVER -&gt; CLIENT: 250 OK<br>
CLIENT -&gt; SERVER: RCPT TO:&lt;withheld@withheld&gt;<br>
SERVER -&gt; CLIENT: 250 Accepted<br>
CLIENT -&gt; SERVER: DATA<br>
SERVER -&gt; CLIENT: 354 Enter message, ending with &quot;.&quot; on a line by itself<br>
CLIENT -&gt; SERVER: Date: Fri, 10 Mar 2017 16:48:30 +0100<br>
CLIENT -&gt; SERVER: To: John Doe &lt;withheld@withheld&gt;<br>
CLIENT -&gt; SERVER: From: First Last &lt;withheld@withheld&gt;<br>
CLIENT -&gt; SERVER: Subject: PHPMailer SMTP test<br>
CLIENT -&gt; SERVER: Message-ID: &lt;5c019f0dcf19dcef2aaa24fa7131245d@gbg1-noc1&gt;<br>
CLIENT -&gt; SERVER: X-Mailer: PHPMailer 5.2.22 (https://github.com/PHPMailer/PHPMailer)<br>
CLIENT -&gt; SERVER: MIME-Version: 1.0<br>
CLIENT -&gt; SERVER: Content-Type: multipart/alternative;<br>
CLIENT -&gt; SERVER:    boundary=&quot;b1_5c019f0dcf19dcef2aaa24fa7131245d&quot;<br>
CLIENT -&gt; SERVER: Content-Transfer-Encoding: 8bit<br>
CLIENT -&gt; SERVER: <br>
CLIENT -&gt; SERVER: This is a multi-part message in MIME format.<br>
CLIENT -&gt; SERVER: <br>
CLIENT -&gt; SERVER: --b1_5c019f0dcf19dcef2aaa24fa7131245d<br>
CLIENT -&gt; SERVER: Content-Type: text/plain; charset=us-ascii<br>
CLIENT -&gt; SERVER: <br>
CLIENT -&gt; SERVER: This is a plain-text message body<br>
CLIENT -&gt; SERVER: <br>
CLIENT -&gt; SERVER: <br>
CLIENT -&gt; SERVER: --b1_5c019f0dcf19dcef2aaa24fa7131245d<br>
CLIENT -&gt; SERVER: Content-Type: text/html; charset=us-ascii<br>
CLIENT -&gt; SERVER: <br>
CLIENT -&gt; SERVER: This is a plain-text message body<br>
CLIENT -&gt; SERVER: <br>
CLIENT -&gt; SERVER: <br>
CLIENT -&gt; SERVER: <br>
CLIENT -&gt; SERVER: --b1_5c019f0dcf19dcef2aaa24fa7131245d--<br>
CLIENT -&gt; SERVER: <br>
CLIENT -&gt; SERVER: .<br>
SERVER -&gt; CLIENT: 250 OK id=1cmMmR-0006np-MA<br>
CLIENT -&gt; SERVER: QUIT<br>
SERVER -&gt; CLIENT: 221 withheld closing connection<br>





###########
With timeout of 5 s:
pehj01@gbg1-noc1:/var/www/cacti/include/phpmailer$ php test.phps
No log handling enabled - turning on stderr logging
 SERVER -&gt; CLIENT: <br>
CLIENT -&gt; SERVER: EHLO gbg1-noc1<br>
SERVER -&gt; CLIENT: 554 SMTP synchronization error<br>
SMTP ERROR: EHLO command failed: 554 SMTP synchronization error<br>
CLIENT -&gt; SERVER: HELO gbg1-noc1<br>
SERVER -&gt; CLIENT: <br>
SMTP ERROR: HELO command failed: <br>
SMTP NOTICE: EOF caught while checking if connected<br>
The following From address failed: withheld@withheld : Called MAIL FROM without being connected,,,SMTP server error: Called MAIL FROM without being connected<br>
Mailer Error: The following From address failed: withheld@withheld : Called MAIL FROM without being connected,,,SMTP server error: Called MAIL FROM without being connectedSMTP server error: Called MAIL FROM without being connected

test.phps:
<?php
require './PHPMailerAutoload.php';
$mail = new PHPMailer;
$mail->Timeout = 5;
$mail->isSMTP();
$mail->SMTPDebug = 2;
$mail->Debugoutput = 'html';
$mail->Host = "83.255.238.66";
$mail->Port = 25;
$mail->SMTPAuth = false;
$mail->setFrom('cacti@itux.se', 'First Last');
$mail->addAddress('support@itux.se', 'John Doe');
$mail->Subject = 'PHPMailer SMTP test';
$mail->Body = 'This is a plain-text message body';
$mail->AltBody = 'This is a plain-text message body';
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}

**Comment by Synchro** [comment]
Look at the error output in the second test:

```
No log handling enabled - turning on stderr logging
SERVER -> CLIENT: 
CLIENT -> SERVER: EHLO gbg1-noc1
SERVER -> CLIENT: 554 SMTP synchronization error
```

(It would be clearer if you'd set SMTPDebug = 4 as I said)

This shows the server sending something (even an empty string) before the client does, i.e. the client is acting correctly.

**Comment by Xake** [comment]
Then how come  it works with a longer timout, and no empty "respons" is to
be seen?

pehj01@gbg1-noc1:/var/www/cacti/include/phpmailer$ php test.phps
No log handling enabled - turning on stderr logging
 Connection: opening to withheld:25, timeout=300, options=array ()<br>
Connection: opened<br>
SMTP -&gt; get_lines(): $data is &quot;&quot;<br>
SMTP -&gt; get_lines(): $str is  &quot;220
*****************************************************************************&quot;<br>
SERVER -&gt; CLIENT: 220
*****************************************************************************<br>
CLIENT -&gt; SERVER: EHLO gbg1-noc1<br>
SMTP -&gt; get_lines(): $data is &quot;&quot;<br>

**Comment by Synchro** [comment]
Er, that output shows an empty response?

**Comment by Xake** [comment]
Is it the "SMTP -&gt; get_lines(): $data is &quot;&quot;<br>" that is the empty repons?

**Comment by Synchro** [comment]
Yes. This is why I asked you to add those `var_dump` lines, so we can see exactly what it is sending, if anything.

**Comment by Synchro** [comment]
I'm also suspicious of something else: your error output doesn't include a link to the PHPMailer troubleshooting guide, which means you must be using an old version of PHPMailer. Please make sure you're using the latest.
