### ISSUE TITLE
Missing XOAUTH2 method on the server

### ISSUE THREAD

**Issue by usrb1n** [PHPMailer/PHPMailer#1004]
Hello,

This is the first time I create an issue on a GitHub project so please bear with me if I am not doing it correctly.

I am trying to configure the [GMail SMTP](https://wordpress.org/plugins/gmail-smtp/) Wordpress plugin in order to make Wordpress send the emails via Google Apps account.

I've created the app, generated oauth details and configured the plugin but when I try to send a test email I encounter the following error:

Auth method requested: XOAUTH2
Auth methods available on the server: PLAIN,LOGIN
SMTP Error: Could not authenticate.
CLIENT -> SERVER: QUIT
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "221 server closing connection"
SERVER -> CLIENT: 221 server closing connection
Connection: closed
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

I tried for the last 7 hours to find out how to configure the server so I can "enable" the support for XOAUTH without any success. 

I have updated my PHP version from 5.4 to 5.6 as I've read somewhere this might be the problem. Then somebody said this could be generated by an outdated version of OpenSSL but my server runs "OpenSSL 1.0.1e-fips 11 Feb 2013" which seems to be the latest version provided by RHEL and I am a bit afraid of just compiling a new version as it's out of RHEL's supported versions and it may break things.

Is it really OpenSSL version the issue here? How can I "enable" XOAUTH2 support for PHP mailer?

Some server details:

OS: CentOS 7
PHP version: 5.6.30
Running cPanel VHM version 62.0 build 16

I would appreciate some support and I understand that you won't provide support for 3rd party Wordpress plugins but this is generated directly from class.smtp.php on PHPMailer.

Thanks in advance for your support.

**Comment by Synchro** [comment]
You've not included enough debug output to tell, but I would guess that you are being redirected to a different server (probably your ISP's), and it doesn't offer XOAUTH2. Checking for this is covered in the guide.

**Comment by usrb1n** [comment]
Please apologize for that. Check bellow the full log:

Connection: opening to smtp.gmail.com:587, timeout=300, options=array ( 'ssl' => array ( 'verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true, ),)
Connection: opened
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "220-server ESMTP Exim 4.88 #1 Mon, 13 Mar 2017 18:32:08 +1100 "
SMTP -> get_lines(): $data is "220-server ESMTP Exim 4.88 #1 Mon, 13 Mar 2017 18:32:08 +1100 "
SMTP -> get_lines(): $str is "220-We do not authorize the use of this system to transport unsolicited, "
SMTP -> get_lines(): $data is "220-server ESMTP Exim 4.88 #1 Mon, 13 Mar 2017 18:32:08 +1100 220-We do not authorize the use of this system to transport unsolicited, "
SMTP -> get_lines(): $str is "220 and/or bulk e-mail."
SERVER -> CLIENT: 220-server ESMTP Exim 4.88 #1 Mon, 13 Mar 2017 18:32:08 +1100 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail.
CLIENT -> SERVER: EHLO mydomain.com
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "250-server Hello server.mydomain.com [my.ip.address]"
SMTP -> get_lines(): $data is "250-server Hello server.mydomain.com [my.ip.address]"
SMTP -> get_lines(): $str is "250-SIZE 52428800"
SMTP -> get_lines(): $data is "250-server Hello server.mydomain.com [my.ip.address]250-SIZE 52428800"
SMTP -> get_lines(): $str is "250-8BITMIME"
SMTP -> get_lines(): $data is "250-server Hello server.mydomain.com [my.ip.address]250-SIZE 52428800250-8BITMIME"
SMTP -> get_lines(): $str is "250-PIPELINING"
SMTP -> get_lines(): $data is "250-server Hello server.mydomain.com [my.ip.address]250-SIZE 52428800250-8BITMIME250-PIPELINING"
SMTP -> get_lines(): $str is "250-AUTH PLAIN LOGIN"
SMTP -> get_lines(): $data is "250-server Hello server.mydomain.com [my.ip.address]250-SIZE 52428800250-8BITMIME250-PIPELINING250-AUTH PLAIN LOGIN"
SMTP -> get_lines(): $str is "250-STARTTLS"
SMTP -> get_lines(): $data is "250-server Hello server.mydomain.com [my.ip.address]250-SIZE 52428800250-8BITMIME250-PIPELINING250-AUTH PLAIN LOGIN250-STARTTLS"
SMTP -> get_lines(): $str is "250 HELP"
SERVER -> CLIENT: 250-server Hello server.mydomain.com [my.ip.address]250-SIZE 52428800250-8BITMIME250-PIPELINING250-AUTH PLAIN LOGIN250-STARTTLS250 HELP
CLIENT -> SERVER: STARTTLS
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "220 TLS go ahead"
SERVER -> CLIENT: 220 TLS go ahead
CLIENT -> SERVER: EHLO mydomain.com
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "250-server Hello server.mydomain.com [my.ip.address]"
SMTP -> get_lines(): $data is "250-server Hello server.mydomain.com [my.ip.address]"
SMTP -> get_lines(): $str is "250-SIZE 52428800"
SMTP -> get_lines(): $data is "250-server Hello server.mydomain.com [my.ip.address]250-SIZE 52428800"
SMTP -> get_lines(): $str is "250-8BITMIME"
SMTP -> get_lines(): $data is "250-server Hello server.mydomain.com [my.ip.address]250-SIZE 52428800250-8BITMIME"
SMTP -> get_lines(): $str is "250-PIPELINING"
SMTP -> get_lines(): $data is "250-server Hello server.mydomain.com [my.ip.address]250-SIZE 52428800250-8BITMIME250-PIPELINING"
SMTP -> get_lines(): $str is "250-AUTH PLAIN LOGIN"
SMTP -> get_lines(): $data is "250-server Hello server.mydomain.com [my.ip.address]250-SIZE 52428800250-8BITMIME250-PIPELINING250-AUTH PLAIN LOGIN"
SMTP -> get_lines(): $str is "250 HELP"
SERVER -> CLIENT: 250-server Hello server.mydomain.com [my.ip.address]250-SIZE 52428800250-8BITMIME250-PIPELINING250-AUTH PLAIN LOGIN250 HELP
Auth method requested: XOAUTH2
Auth methods available on the server: PLAIN,LOGIN
SMTP Error: Could not authenticate.
CLIENT -> SERVER: QUIT
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "221 server closing connection"
SERVER -> CLIENT: 221 server closing connection
Connection: closed
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting


I've only replaced the my server name and IP address for security purposes. 
I am checking again the Troubleshooting guide.

**Comment by Synchro** [comment]
That's definitely what's happening. Google puts its name in the welcome banner, does not run exim, does not allow auth without TLS. I'm surprised you're not getting a mismatched certificate error.

**Comment by usrb1n** [comment]
Thank you very much for your help and valuable time! I will be trying to see where does this redirect happen and try to remove it.

I am closing this issue.

Thank you again!

**Comment by GNHenkin** [comment]
Were you ever able to avoid server redirection, if so how.  I have the same problem.

**Comment by Synchro** [comment]
It will be the ISP. It's unlikely you can prevent it happening.
