### ISSUE TITLE
SSL3_GET_SERVER_CERTIFICATE:certificate verify failed [Is it client side or server side]?

### ISSUE THREAD

**Issue by yu0307** [PHPMailer/PHPMailer#1005]
I got the reason why this is happening and if I disable the peer verification all will work out. 
My questions is,
-the SMTP server i'm connecting has wildcard SSL cert issued by Godaddy. Https: will work just fine.
-Why when I connect to the same server with 587/TLS, it's telling me the certification cannot be verified?
- Is the server not responding with the correct SSL cert? OR my client does not have the remote server's certificate installed locally?
-Server issue? or client issue?

Thank you

**Comment by Synchro** [comment]
It's a combination of client and server.  You request to connect to a named server, and it responds with a cert that should match the name. Look at the openssl command given in the troubleshooting guide. You may find that https and SMTP are using different certs.

**Comment by yu0307** [comment]
Thank you for your response, so if I have server Cert installed for SMTP service, Do i need to do anything at the client side to have it acknowledge the cert?

**Comment by Synchro** [comment]
When you connect using TLS, the server will automatically send a certificate to the client, which can then verify it. This is what the openssl command I mentioned shows.
