### ISSUE TITLE
Mailer Error: Could not instantiate mail function.

### ISSUE THREAD

**Issue by umesh-naik** [PHPMailer/PHPMailer#1006]
require 'PHPMailer-master/PHPMailerAutoload.php';
        $mail = new PHPMailer;
	$mail->isSendmail();
	
	$mail->setFrom('support@some.com', 'support');
	$mail->addAddress($_POST['email'], $_POST['name']);
	$mail->addReplyTo('support@some.com', 'Support');
	$mail->isHTML(true);

	$mail->Subject = 'Subject';
	$mail->Body = 'Body';
	$mail->AltBody = 'Dear '.$_POST['name'].', Thank you for your interest.';

	if(!$mail->send()) {
		echo "Opps! For some technical reasons we couldn't able to sent you an email. We will shortly get back to you with download details.";	
		echo "Mailer Error: " . $mail->ErrorInfo;
	} else {
		echo "Message has been sent";
	}

Suddenly I'm getting Mailer error. I'm  using PHP version 5.4. Please let me know if there is any issue in the above PHP code.

**Comment by Synchro** [comment]
The code looks OK, though it looks like it could be used as a spam gateway, and you're not checking the return value from `addAddress()`.

Why are you doing new development using PHP 5.4?

Why are you using `isSendmail()`?

**Comment by umesh-naik** [comment]
Thanks for your quick reply @Synchro . Return values are strings that I get from mysql db. And I was checking multiple options and some has written isSendmail() to instantiate.

**Comment by Synchro** [comment]
No I mean that when you say:

    $mail->addAddress($_POST['email'], $_POST['name']);

If `$_POST{'email']` is not a valid address, addAddress will return false, and you're not checking for that, so it will then fail to send.

Don't just use `isSendmail()` because somebody else did, use it because you have a specific reason to do so; if you don't, don't call it. The fastest and most flexible way to use PHPMailer is with SMTP to localhost. Base your code on the examples provided with PHPMailer.

**Comment by umesh-naik** [comment]
@Synchro I have cross checked the email address. Even though it wasn't working.

**Comment by umesh-naik** [comment]
@Synchro I have tried using SMTP too but no use. And this is the code:
`$mail = new PHPMailer;
	
	$mail->IsSMTP();
	$mail->SMTPDebug = 1;
	$mail->SMTPAuth = true;
	$mail->SMTPSecure = 'ssl';
	$mail->Host = "smtp.gmail.com";
	$mail->Port = 465; // or 587
	$mail->IsHTML(true);
	$mail->Username = "mygmailid";
	$mail->Password = "mygmailpwd";

	$mail->setFrom('support@some.com', 'support');
	$mail->addAddress('validEmail', 'Uma');
	$mail->addReplyTo('validEmail', 'Support');
	$mail->isHTML(true);

	$mail->Subject = 'Subject';
	$mail->Body = 'Body';
	$mail->AltBody = 'Dear Uma, Thank you for your interest.';


	if(!$mail->send()) {
		echo "Opps! For some technical reasons we couldn't able to sent you an email. We will shortly get back to you with download details.";	
		echo "Mailer Error: " . $mail->ErrorInfo;
	} else {
		echo "Message has been sent";
	}`

Has changes port too and SMTPSecure to tls too. Even that didn't work. The same (code pasted first) was working till 12th of this month.

**Comment by Synchro** [comment]
Why not base your code on the gmail example provided with PHPMailer? It also helps to read the docs that the error message links to  - if it doesn't provide a link, it means you're using an old, vulnerable version, so you should upgrade before you do anything else. Set `SMTPDebug = 3` to show more info about connection problems. All of this is covered in the guide, which is also linked from the readme, and the wiki link at the top of the page here on github.

**Comment by shubham588** [comment]
<?php

require "PHPMailer/PHPMailer/PHPMailerAutoload.php";;
require 'config.php';   //my database page

if(isset($_POST["email"])){


    $emailTo = $_POST["email"];

    $code = uniqid(true);

    $query = mysqli_query($conn, "INSERT INTO resetpassword(code, email) VALUES('$code','$emailTo')");
    if(!$query)
    {
      exit("Error");
    }
    // Instantiation and passing `true` enables exceptions
$mail = new PHPMailer(true);

try {
    //Server settings
   
//  $mail->isSMTP();                                            // Send using SMTP
    $mail->Host       = 'smtp.gmail.com';                    // Set the SMTP server to send through
    $mail->SMTPAuth   = true;                                   // Enable SMTP authentication
    $mail->Username   = 'team.zeesper@gmail.com';                     // SMTP username
    $mail->Password   = 'zeesper!2';                               // SMTP password
    $mail->SMTPSecure = 'ssl';                    // Enable TLS encryption; `PHPMailer::ENCRYPTION_SMTPS` also accepted
    $mail->Port       = 465;                                    // TCP port to connect to
    //or more succinctly:
    $mail->Host = 'ssl://smtp.gmail.com:465';
    //Recipients
    $mail->setFrom('team.zeesper@gmail.com', 'zeesper');
    $mail->addAddress($emailTo);     // Add a recipient
    $mail->addReplyTo('no-reply@gmail.com', 'no-reply');
    
    $url = "http://" . $_SERVER["HTTP_HOST"] . dirname($_SERVER["PHP_SELF"]) . "/resetpassword.php?code=$code";
     // Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = 'Your Password Reset Link';
    $mail->Body    = "<h1>You requested a password reset</h1><br>
                      click this <a href='$url'>LINK</a> to do so, If not then ignore this mail<br><br>Team zeesper";
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    $mail->send();
    echo "<script>window.open('massage.php','_self')</script>";
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}
exit();
}
?>

**Comment by Synchro** [comment]
Well, now it’s your turn to do a password reset since you just posted it in a public forum.
