### ISSUE TITLE
Include .htaccess files to protect optional directories in the repo

### ISSUE THREAD

**Issue by TacticalCode** [PHPMailer/PHPMailer#1007]
This might be a controversal one...
I'd really like to integrate this repository as a submodule in my web app, in order EASILY receive the latest updates and have them directly in the main repository.
The only problem is that the files in test/ don't belong on a production server...

For the sake of convenience, can we add a **Deny from all** .htaccess in the test dir? For automated, secure deployment using just git. And having secure defaults. </SellSellSell>

What do you think? Let me know if you need a PR.

**Comment by Synchro** [comment]
None of your submodules should be within your web root anyway, and if you use the recommended method of deploying PHPMailer using composer (which also deals with automatic updates), the test folder won't be there at all. `.htaccess` is a proprietary apache thing, but PHPMailer doesn't require a web server at all.
