### ISSUE TITLE
how to check  email is delivered or not 

### ISSUE THREAD

**Issue by gauravkumar1902** [PHPMailer/PHPMailer#1009]
<?php
/**
 * This example shows settings to use when sending via Google's Gmail servers.
 */
//SMTP needs accurate times, and the PHP time zone MUST be set
//This should be done in your php.ini, but this is how to do it if you don't have access to that
date_default_timezone_set('Etc/UTC');
       
       
require('phpmailer/PHPMailerAutoload.php');</br>
require('phpmailer/class.phpmailer.php');</br>
require('phpmailer/class.smtp.php');</br>
require('phpmailer/class.pop3.php');</br>
//Create a new PHPMailer instance</br>
$mail = new PHPMailer;</br>
//Tell PHPMailer to use SMTP</br>
$mail->isSMTP();</br>
//Enable SMTP debugging</br>
// 0 = off (for production use)</br>
// 1 = client messages</br>
// 2 = client and server messages</br>
$mail->SMTPDebug = 2;</br>
//Ask for HTML-friendly debug output</br>
$mail->Debugoutput = 'html';</br>
//Set the hostname of the mail server
$mail->Host = 'mail.informationtab.com';</br>
// use</br>
// $mail->Host = gethostbyname('smtp.gmail.com');</br>
// if your network does not support SMTP over IPv6</br>
//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission</br>
$mail->Port = 465;</br>
//Set the encryption system to use - ssl (deprecated) or tls</br>
$mail->SMTPSecure = 'ssl';</br>
//Whether to use SMTP authentication</br>
$mail->SMTPAuth = false;</br>
//Username to use for SMTP authentication - use full email address for gmail</br>
$mail->Username = "email_demo@informationtab.com";</br>
//Password to use for SMTP authentication</br>
$mail->Password = "xxxxxxxxx";</br>
//Set who the message is to be sent from</br>
$mail->setFrom('email_demo@informationtab.com', 'First Last');</br>
//Set an alternative reply-to address</br>
$mail->addReplyTo('email_demo@informationtab.com', 'First Last');</br>
//Set who the message is to be sent to</br>
$mail->addAddress('gaurav.kumar@knowledgeexcel.com', 'John Doe');</br>
//Set the subject line</br>
$mail->Subject = 'PHPMailer GMail SMTP test';</br>
//Read an HTML message body from an external file, convert referenced images to embedded,</br>
//convert HTML into a basic plain-text alternative body</br>
$mail->Body    = 'This is the HTML message body <b>in bold!</b>';</br>
//Replace the plain text body with one created manually</br>
$mail->AltBody = 'This is a plain-text message body';</br>
//Attach an image file</br>
//$mail->addAttachment('images/phpmailer_mini.png');</br>
//send the message, check for errors</br>
if (!$mail->send()) {</br>
    echo "Mailer Error: " . $mail->ErrorInfo;</br>
} else {</br>
    echo "Message sent!";</br>
}</br>

 ?>

**Comment by Synchro** [comment]
This code doesn't seem to have anything to do with your question? The only information you can get on a successful delivery is if the message was ultimately accepted by the intended recipient's mail server, and you did not then receive a bounce. All of that is outside PHPMailer's control.
