### ISSUE TITLE
UTF-8 html email

### ISSUE THREAD

**Issue by jmbelloteau** [PHPMailer/PHPMailer#1010]
Hello, 

I'm using PHPMailer to send html emails.
I use Twig template engine to parse _POST data.

I followed your documentation to enable UTF8 but I still received email with specials characters that haven't been decoded.

Here is my mailer class:

[Mailer Class based on PHPMailer](https://gist.github.com/jmbelloteau/5095afeada10946b1b304f31ab924029)

I maybe do something wrong? Any idea...

**Comment by r0073rr0r** [comment]
Try putting:
`header('Content-Type: text/html; charset=utf-8');`

**Comment by jmbelloteau** [comment]
Hello @r0073rr0r ,

Should I put `header('Content-Type: text/html; charset=utf-8');` on the email template or on index.php ?

**Comment by r0073rr0r** [comment]
Headers allways goes at first lines of code in index.php
But i thinks if you grab from MySQL you need to define names and charset.

**Comment by jmbelloteau** [comment]
I don't use MySQL, it's flatfile system. Let me try your solution on index.php then :)

**Comment by Synchro** [comment]
That header has no effect on email at all. You're already doing the only thing that PHPMailer requires for UTF-8 to work:

    $mail->CharSet = 'UTF-8';

You will need to do the MySQL names setting too. If it's still not looking correct, it means your handling of the data is not preserving the UTF-8 encoding. If you find that static template text is correct by dynamic data from mySQl is to, then you know where the problem is.

**Comment by Synchro** [comment]
If you're not using MySQL it suggests that your template file's encoding is incorrect.

**Comment by jmbelloteau** [comment]
Ok @Synchro, make sens, so the problem come probably from twig ?

**Comment by Synchro** [comment]
Perhaps - you'll probably need to tell twig it should be using UTF-8. It's quite easy to spot UTF-8 data if you hex-dump it - having it look correct isn't reliable as it might be showing you the right chars in the wrong charset.

**Comment by jmbelloteau** [comment]
Hum okay 😄 

Thanks for the hint, I'll make some tests

**Comment by jmbelloteau** [comment]
So... I've made a var_dump on **$content** witch is the email template rendered by Twig with **_$POST** data.

Here is the head of the response. As you can see the title contain the name from  **_$POST** data and accent are looking good.

Just after that I use this render template (**$content** ) as **PHPMailer Body** but I still see character like `&#233; ` in the email I receive.

```
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
  <title>New message from Élodie Bérégenre</title>
  <!--[if !mso]><!-- -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--<![endif]-->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
```

**Comment by r0073rr0r** [comment]
Try:

```
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>New message from Élodie Bérangère</title>
  <!--[if !mso]><!-- -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--<![endif]-->
```

According to [W3](https://www.w3.org/wiki/The_HTML_head_element#Stop_right_there.21_Inline_CSS_and_JavaScript_is_not_too_clever.21) tags should be:
Meta charset
Title
Meta name="descripition"
Meta name="keywords"
Stylesheet
JavaScript Files

Maybe HTML4 have problems, try changing to HTML5 instead.

I dont know what can else be a problem.

**Comment by Synchro** [comment]
Text like `&#233;` is HTML entity encoding, which allows you to embed non-ascii chars in ascii text. PHPMailer will have no effect on that. As I said, having it _look_ correct doesn't tell you much, you need to check the underlying data to be sure - for example é is `e9` in ISO-8859-1, but is `c3a9` in UTF-8 - you can't tell which your'e using without hex-dumping the text. Just because your source file _says_ it's UTF-8 doesn't mean it's true!

Seeing those Microsoft tags in your doctype is an extremely bad sign. Steer well clear of any HTML generated by Word, it's truly terrible. That said, the doctype you're using is already HTML5.

**Comment by jmbelloteau** [comment]
A little improvement

**wich _$POST =**

`c'est chiânt les accents ça fou le bordel évidement
`
**email look like this =**

`c&#39;est vraiment chiânt les accents ça fou le bordel évidement`

So quote (and maybe some others) doesn't work.

Does it help you to understand what could be the problem.

PS : Thanks for your help guys and sorry if I sound newby, coding is not my job.
I try my best to understand you.

**Comment by jmbelloteau** [comment]
About html email formating I'm using the very popular **MJML** framework witch is apparently the best.

**[MJML GITHUB](https://github.com/mjmlio/mjml)**

**Comment by jmbelloteau** [comment]
Found the solution
I add to use twig flag **raw** on each $_POST data in twig template.

from

`{{ postdata.firstname}}`

to

`{{ postdata.firstname|raw}}`

Thanks @Synchro and @r0073rr0r to show me the path... 🚶

😃

**Comment by Synchro** [comment]
Yes, that would explain the HTML entities - Twig escapes output by default. Be careful with raw option though - make sure you have validated/sanitized inputs before passing them to your template to be used unfiltered!

**Comment by jmbelloteau** [comment]
@Synchro yep, everything is validated and sanitized before template is parsed.
Thanks for the tips again ;)

**Comment by bahmanian** [comment]
Hello everyone
How to send an email via PHPMailer but instead of send as rendered html, user get a email with content of $message as a HTML file?

**Comment by Synchro** [comment]
When you send HTML email, the message body *is* an HTML file; it is rendered by the client.

**Comment by bahmanian** [comment]
Thanks for the answer. I found a solution to fix my problem.

**Comment by MarcusXavierr** [comment]
> That header has no effect on email at all. You're already doing the only thing that PHPMailer requires for UTF-8 to work:
> 
> ```
> $mail->CharSet = 'UTF-8';
> ```
> 
> You will need to do the MySQL names setting too. If it's still not looking correct, it means your handling of the data is not preserving the UTF-8 encoding. If you find that static template text is correct but dynamic data from MySQL is to, then you know where the problem is.

You saved my day
