### ISSUE TITLE
SMTP -> get_lines(): $str is "501-5.5.4 HELO/EHLO argument "PhpStorm 9.0.3" invalid, closing connection."

### ISSUE THREAD

**Issue by nildyan26** [PHPMailer/PHPMailer#1011]
I want to share my solution to this.
I modified the "HELO" message using this:
$mail->Helo = "HELO";
and it works like a charm!

**Comment by Synchro** [comment]
Thanks, this will show up in search results now!

It fails because the HELO string is expected to be a valid hostname (it's often checked using a reverse lookup), and PHPStorm's version string is not one.

**Comment by Synchro** [comment]
Reported as a [PHPStorm bug](https://youtrack.jetbrains.com/issue/WI-35547).
