### ISSUE TITLE
SMTP fwrite generates warnings not Exceptions

### ISSUE THREAD

**Issue by blaaat** [PHPMailer/PHPMailer#1012]
```
    public function client_send($data)
    {
        $this->edebug("CLIENT -> SERVER: $data", self::DEBUG_CLIENT);
        return fwrite($this->smtp_conn, $data);
    }
```

This code may throw warnings (in my case; incidental SSL warnings), these are not converted into phpmailerExceptions so I can catch them. 

Tried to convert these into Exceptions by using `error_get_last()`, but this function does not catch fwrite's warnings. (and is PHP 5.2+)

Maybe throwing a generic 'fwrite failed' exception?

**Comment by blaaat** [comment]
Same issue probably exists with POP3 connections.

**Comment by princeofnaxos** [comment]
I was also experiencing SMTP errors ('failed to authenticate') and found that no exceptions were caught. Did some digging into the scripts and found that 'throw $exc' in line 1218 of class.smtp.php doesn't do anything. The script seems to die (an 'echo __LINE__' after it is not executed.

Is this related to the above?

**Comment by Synchro** [comment]
You're referring to the PHPMailer class, not the SMTP class. Why would you expect any code after a `throw` to be run? Execution stops at that point, like for a `return`. Generally PHPMailer doesn't throw exceptions for everything, only major issues, so you should primarily rely on checking return values.

@blaaat Does the change I committed to the 6.0 branch deal with your issue?

**Comment by princeofnaxos** [comment]
Might be the case, but fact is that no exception is caught when I'm trying to send a message. No return values are received by $mail->send(), and the script simply dies there.

**Comment by Synchro** [comment]
Stack trace and error output please.

**Comment by blaaat** [comment]
@Synchro Yes; haven't had a chance to really test it with the SSL errors. but appears to work perfect. Thanks! 👍

**Comment by mparini2107** [comment]
I have the same issue, but it's not always.

Warning: fwrite(): SSL: Connection reset by peer in /home/betadb/public_html/gss/phpm/class.smtp.php on line 992

Warning: fwrite(): SSL operation failed with code 1. OpenSSL Error messages: error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry in /home/betadb/public_html/gss/phpm/class.smtp.php on line 992

**Comment by lewa** [comment]
@Synchro any chance the same set_error_handler() fix could be applied to PHPMailer 5.2?

**Comment by Synchro** [comment]
Well, you can do a PR if you like, but I'm really done with doing anything new for 5.2. I'll get around to releasing 6.0 very soon!

**Comment by lewa** [comment]
@Synchro since I'm not switching to 6.0 yet, you've got PR.
