### ISSUE TITLE
2017-03-27 10:11:41	SMTP ERROR: Failed to connect to server: Connection timed out (110) SMTP connect() failed. Mailer Error: SMTP connect() failed.

### ISSUE THREAD

**Issue by akbarsara** [PHPMailer/PHPMailer#1015]
<?php

require_once('PHPMailer/PHPMailer-5.2.8/class.phpmailer.php');
//include("class.smtp.php"); // optional, gets called from within class.phpmailer.php if not already loaded
require 'PHPMailer/PHPMailer-5.2.8/PHPMailerAutoload.php';

$mail = new PHPMailer(); // create a new object
$mail->IsSMTP(); // enable SMTP
$mail->SMTPDebug = 1; // debugging: 1 = errors and messages, 2 = messages only
$mail->SMTPAuth = true; // authentication enabled
$mail->SMTPSecure = 'ssl'; // secure transfer enabled REQUIRED for Gmail
$mail->Host = "smtp.gmail.com";
$mail->Port = 465; // or 587
$mail->IsHTML(true);
$mail->Username = "ata.helpline@gmail.com";
$mail->Password = "*********";
$mail->SetFrom("agartalatravekagency@gmail.com");
$mail->Subject = "Test";
$mail->Body = "hello";
$mail->AddAddress("ata.helpline@gmail.com");

 if(!$mail->Send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
 } else {
    echo "Message has been sent";
 }
 
 ?>

**Comment by Synchro** [comment]
https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
