### ISSUE TITLE
Issue while using from name

### ISSUE THREAD

**Issue by dheerajtiwari** [PHPMailer/PHPMailer#1018]
Hello,

I am sending so many mail at a time using this library. And issue is that some times from name get replaced with some other Name.
I am using from and from name same. Which is a email Id.

What could be the cause of problem.

**Comment by Synchro** [comment]
I can't tell without seeing your code.

**Comment by dheerajtiwari** [comment]
function smtpmailer($to, $from, $from_name, $subject, $body, $guser, $gpwd, $smtpsrvr, $content, $fname, $attach = 0, $bcc = '') {
    global $error;
    define('GUSER', $guser);
    define('GPWD', $gpwd);
    define('SMTPSERVER', $smtpsrvr);
    $mail = new PHPMailer();
    $mail->IsSMTP(); // enable SMTP
    $mail->SMTPDebug = 0;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->SMTPAuth = true;  // authentication enabled
    $mail->SMTPSecure = 'tls'; // secure transfer enabled REQUIRED for GMail
    if (SMTPSERVER == "smtp.gmail.com") {
        $mail->Port = 587;
    }
    
    $mail->Host = SMTPSERVER;
    $mail->Username = GUSER;
    $mail->Password = GPWD;
    
    $mail->SetFrom($from, $from_name);
    
    if ($bcc != '') {
        $mail->AddBCC($bcc, $bcc);
    }
    if ($attach == "1") {
        $mail->AddAttachment($content, $fname, 'base64', 'application/octet-stream');
    }
    $mail->Subject = $subject;
    $mail->Body = $body;
    $mail->IsHTML(true);
    $mail->AddAddress($to);
    $res = $mail->Send();
    
    var_dump($res);
    if (!$res) {
        $mail->smtpClose();
        return false;
    } else {
        $mail->smtpClose();
        return true;
    }
}`

In above code. $from and $from_name are having same value. like <abc@gmail.com>.
And we are calling this method in loop for multiple users with different parameters.

**Comment by Synchro** [comment]
This is covered in the PHPMailer documentation; Gmail does not allow you to set arbitrary from addresses. You can create fixed aliases in your gmail prefs that it will then permit, but you can't just send as any address.

**Comment by dheerajtiwari** [comment]
Ok. I got your point but from parameter is working file and from_name is replaced by some other emailID.

This is the mail i received.

> From: nileshmandlecha@gmail.com <sabooinvestments@gmail.com>
> Date: Friday, March 31, 2017
> Subject: Wishing you a Very Happy Birthday.
> To: m_yadaorao@yahoo.co.in

**Comment by dheerajtiwari** [comment]
Ok. I got your point but from parameter is working file and from_name is replaced by some other emailID.

This is the mail i received.

From: abc@gmail.com xyz@gmail.com
Date: Friday, March 31, 2017
Subject: Wishing you a Very Happy Birthday.
To: pqr@yahoo.co.in

**Comment by dheerajtiwari** [comment]
I am using From like this.
$from = abc@gmail.com
$from_name = abc@gmail.com
$mail->SetFrom($from, $from_name);

and from name is showing like xyz@gmail.com automatically.

**Comment by Synchro** [comment]
Gmail will use what you put in the `Username` property and will ignore what you put in the From header. In your code, whatever you set `$guser` to:

    define('GUSER', $guser);
