### ISSUE TITLE
Gmail example error

### ISSUE THREAD

**Issue by EddyVinck** [PHPMailer/PHPMailer#1021]
Hello.  I am trying to use PHPMailer with Gmail. For testing I put the example on a webserver which did not work even after trying to tweak some things. It looks like it can't connect to my account but the password and email are correct. Can you please help me?

SERVER -> CLIENT: 220 smtp.gmail.com ESMTP y107sm6782093wrc.35 - gsmtp
CLIENT -> SERVER: EHLO myWebserver
SERVER -> CLIENT: 250-smtp.gmail.com at your service, [5.206.215.179]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: STARTTLS
SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
CLIENT -> SERVER: EHLO myWebserver
SERVER -> CLIENT: 250-smtp.gmail.com at your service, [5.206.215.179]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: AUTH LOGIN
SERVER -> CLIENT: 334 VXNlcm5hbWU6
CLIENT -> SERVER: ZWRkeXZpbmNrOTVAZ21haWwuY29t
SERVER -> CLIENT: 334 UGFzc3dvcmQ6
CLIENT -> SERVER: RWRkeTM3ODQh
SERVER -> CLIENT: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbsl534-5.7.14 k364zTfomGixnHD6TU4uLvllmstPcXAGBxN84i2V1tESS5tUenfslE3jDf04MjL1xHNmVb534-5.7.14 zCU7Qt9Hw64ONmJ0eTmlyQm9Zo0Ye9chwyS6XP0JnetUZZg5yX_OvKaVckHOndRR63ATuj534-5.7.14 u14Vit6p7eAHMvVPfUOKc8XmE6STvupd2rof5xIokAHqnX1-cdCw3mcjxvbvo1MQG6KCOr534-5.7.14 Poj5FbB9tObjN4l5cjiGdSlL-sOfc> Please log in via your web browser and534-5.7.14 then try again.534-5.7.14 Learn more at534 5.7.14 https://support.google.com/mail/answer/78754 y107sm6782093wrc.35 - gsmtp
SMTP ERROR: Password command failed: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbsl534-5.7.14 k364zTfomGixnHD6TU4uLvllmstPcXAGBxN84i2V1tESS5tUenfslE3jDf04MjL1xHNmVb534-5.7.14 zCU7Qt9Hw64ONmJ0eTmlyQm9Zo0Ye9chwyS6XP0JnetUZZg5yX_OvKaVckHOndRR63ATuj534-5.7.14 u14Vit6p7eAHMvVPfUOKc8XmE6STvupd2rof5xIokAHqnX1-cdCw3mcjxvbvo1MQG6KCOr534-5.7.14 Poj5FbB9tObjN4l5cjiGdSlL-sOfc> Please log in via your web browser and534-5.7.14 then try again.534-5.7.14 Learn more at534 5.7.14 https://support.google.com/mail/answer/78754 y107sm6782093wrc.35 - gsmtp
SMTP Error: Could not authenticate.
CLIENT -> SERVER: QUIT
SERVER -> CLIENT: 221 2.0.0 closing connection y107sm6782093wrc.35 - gsmtp
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

```
<?php
/**
 * This example shows settings to use when sending via Google's Gmail servers.
 */
//SMTP needs accurate times, and the PHP time zone MUST be set
//This should be done in your php.ini, but this is how to do it if you don't have access to that
date_default_timezone_set('Etc/UTC');
require 'PHPMailer/PHPMailerAutoload.php';
//Create a new PHPMailer instance
$mail = new PHPMailer;
//Tell PHPMailer to use SMTP
$mail->isSMTP();
//Enable SMTP debugging
// 0 = off (for production use)
// 1 = client messages
// 2 = client and server messages
$mail->SMTPDebug = 2;
//Ask for HTML-friendly debug output
$mail->Debugoutput = 'html';
//Set the hostname of the mail server
$mail->Host = 'smtp.gmail.com';
// use
// $mail->Host = gethostbyname('smtp.gmail.com');
// if your network does not support SMTP over IPv6
//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
$mail->Port = 587;
//Set the encryption system to use - ssl (deprecated) or tls
$mail->SMTPSecure = 'tls';
//Whether to use SMTP authentication
$mail->SMTPAuth = true;
//Username to use for SMTP authentication - use full email address for gmail
$mail->Username = "my@email.com";
//Password to use for SMTP authentication
$mail->Password = "myPassword";
//Set who the message is to be sent from
$mail->setFrom('from@email.com', 'set From');
//Set an alternative reply-to address
$mail->addReplyTo('my@email.com', 'Reply to');
//Set who the message is to be sent to
$mail->addAddress('my@email.com', 'Add Address');
//Set the subject line
$mail->Subject = 'PHPMailer GMail SMTP test';
//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body
// $mail->msgHTML(file_get_contents('contents.html'), dirname(__FILE__));
//Replace the plain text body with one created manually
$mail->Body    = 'This is the HTML message body <b>in bold!</b>';
$mail->AltBody = 'This is a plain-text message body';
//Attach an image file
// $mail->addAttachment('images/phpmailer_mini.png');
//send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}
```

**Comment by Synchro** [comment]
Have you considered, perhaps, following the link that it tell you to that explains why you can't log in? Or reading the troubleshooting guide?
