### ISSUE TITLE
phpmailer is sending infinite mail

### ISSUE THREAD

**Issue by webmasterHPCR** [PHPMailer/PHPMailer#1024]
Hi,

I have a web application and i use phpmailer to send email within my application, since yestarday i got a serious problem cause i receive an infinite mail, i checked for help and i can't find out how to stop it.

Did anyone have an idea how to stop this mail sending?

may thanks for the help.

**Comment by Synchro** [comment]
I can't tell anything specific with so little information, but this will be a problem in your app or your mail server config. PHPMailer only sends one message at a time, so for it to send more, you must be asking it to do that in your app. Alternatively, you could have a mail loop - where an auto-responder replies to itself - and in that case it's nothing to do with PHPMailer or your app. I would recommend stopping your mail server and inspecting its logs and the headers of messages you're receiving.

**Comment by webmasterHPCR** [comment]
i have checked my code and the block where i send this email works perfectly with other emails which means that i have no problem with my code (and in this block i don't use any loop or recursive function), my app was using phpmailer 5.2.9, i have read that this version has some security updates but i don't know if my problem happens before with some version equal or different of this one i'm using.

Please tell me what kind of information you need and i will try te sent it to you.

many thanks for reply.

**Comment by Synchro** [comment]
You should upgrade immediately. That version has security holes and bugs. You have still not said exactly how it's sending multiple messages.
