### ISSUE TITLE
SMTP Error: Could not authenticate

### ISSUE THREAD

**Issue by luismiguelroliveira** [PHPMailer/PHPMailer#1025]
I'm trying to use PHPMail to sent email connection in a smtp with ntlm authentication.

`$mail = new PHPMailer;

	$mail->SMTPDebug = 2;                               

	$mail->SMTPOptions = array(
	    'ssl' => array(
	        'verify_peer' => false,
	        'verify_peer_name' => false,
	        'allow_self_signed' => true
	    )
	);
	$mail->isSMTP();                                     
	$mail->Host = "webmail.av.it.pt";
	$mail->SMTPAuth = true;
	$mail->SMTPSecure = false;   
	$mail->Port = 25;      
	$mail->AuthType = 'NTML';
	$mail->Username = username;
	$mail->Password = password`

But I always get this:

> 2017-04-13 10:33:55	SERVER -> CLIENT: 220 lecas.av.it.pt Microsoft ESMTP MAIL Service ready at Thu, 13 Apr 2017 11:33:53 +0100 
> 2017-04-13 10:33:55	CLIENT -> SERVER: EHLO sigest.av.it.pt 
> 2017-04-13 10:33:55	SERVER -> CLIENT: 250-lecas.av.it.pt Hello [192.168.86.40] 
> 250-SIZE 37748736 
> 250-PIPELINING 
> 250-DSN 
> 250-ENHANCEDSTATUSCODES 
> 250-STARTTLS 
> 250-X-ANONYMOUSTLS 
> 250-AUTH NTLM 
> 250-X-EXPS GSSAPI NTLM 
> 250-8BITMIME 
> 250-BINARYMIME 
> 250-CHUNKING 
> 250 XRDST 
> 2017-04-13 10:33:55	CLIENT -> SERVER: STARTTLS 
> 2017-04-13 10:33:55	SERVER -> CLIENT: 220 2.0.0 SMTP server ready 
> 2017-04-13 10:33:55	CLIENT -> SERVER: EHLO sigest.av.it.pt 
> 2017-04-13 10:33:55	SERVER -> CLIENT: 250-lecas.av.it.pt Hello [192.168.86.40] 
> 250-SIZE 37748736 
> 250-PIPELINING 
> 250-DSN 
> 250-ENHANCEDSTATUSCODES 
> 250-AUTH NTLM LOGIN 
> 250-X-EXPS GSSAPI NTLM 
> 250-8BITMIME 
> 250-BINARYMIME 
> 250-CHUNKING 
> 250 XRDST 
> 2017-04-13 10:33:55	SMTP Error: Could not authenticate. 
> 2017-04-13 10:33:55	CLIENT -> SERVER: QUIT 
> 2017-04-13 10:33:55	SERVER -> CLIENT: 221 2.0.0 Service closing transmission channel 
> 2017-04-13 10:33:55	SMTP connect() failed. 

Am I missing something?

**Comment by Synchro** [comment]
Two things: Typo:

    $mail->AuthType = 'NTML';

should be 

    $mail->AuthType = 'NTLM';

Secondly, the NTLM auth in PHPMailer has never actually worked, not least because it is missing files that [the NTLM library it uses](https://www.phpclasses.org/package/1888-PHP-Single-API-for-standard-authentication-mechanisms.html) depends on. It's been removed from 6.0 altogether, on the basis that there has never been a single report that it was broken in the 11 years it's been in PHPMailer! You are welcome to try to get it working, but it's considered dead here.

The server you are connecting to supports the `LOGIN` auth type, so I suggest you use that instead.

**Comment by luismiguelroliveira** [comment]
How do you know that supposts LOGIN auth type?

**Comment by Synchro** [comment]
Because it says so:

    250-AUTH NTLM LOGIN

**Comment by luismiguelroliveira** [comment]
With this i'm getting this now

```
	$mail->SMTPDebug = 2;

	$mail->isSMTP();
	$mail->Host = 'webmail.av.it.pt';
	$mail->SMTPAuth = true;
	$mail->Username = 'username';
	$mail->Password = 'password';
	$mail->SMTPSecure = 'tls';
	$mail->Port = 25;

	$mail->SMTPOptions = array(
	    'ssl' => array(
	        'verify_peer' => false,
	        'verify_peer_name' => false,
	        'allow_self_signed' => true
	    )
	);
```

> 2017-04-13 12:02:53	SERVER -> CLIENT: 535 5.7.3 Authentication unsuccessful 
> 2017-04-13 12:02:53	SMTP ERROR: Password command failed: 535 5.7.3 Authentication unsuccessful 
> 2017-04-13 12:02:53	SMTP Error: Could not authenticate. 

But password is correct.

**Comment by Synchro** [comment]
Why are you disabling SSL verification? It's probably causing it to hide that you're being redirected ago a different server. Did you check that the `Host` value you set matches what the server responds with, as the troubleshooting guide tells you to?

**Comment by luismiguelroliveira** [comment]
I enabled de SSL verification and now can't connect to smtp host.
And yes I set that it matches

**Comment by luismiguelroliveira** [comment]
How Can I connect without starttls command?

**Comment by Synchro** [comment]
You can set `SMTPSecure = false`, but it's really worth avoiding, much better to figure out *why* it's failing (and it would help if you posted the full output of that section of the SMTP debug output wth `SMTPDebug = 3`). The openssl commands shown in the troubleshooting guide can help you find out why it doesn't like your server's certificate - for example name mismatch, unknown CA, expired, self-signed etc.

**Comment by luismiguelroliveira** [comment]
`Connection: opening to webmail.av.it.pt:25, timeout=300, options=array ()
Connection: opened
SERVER -> CLIENT: 220 becas.av.it.pt Microsoft ESMTP MAIL Service ready at Thu, 13 Apr 2017 17:55:24 +0100
CLIENT -> SERVER: EHLO sigest.av.it.pt
SERVER -> CLIENT: 250-becas.av.it.pt Hello [192.168.86.40]250-SIZE 37748736250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-STARTTLS250-X-ANONYMOUSTLS250-AUTH NTLM250-X-EXPS GSSAPI NTLM250-8BITMIME250-BINARYMIME250-CHUNKING250 XRDST
CLIENT -> SERVER: STARTTLS
SERVER -> CLIENT: 220 2.0.0 SMTP server ready
Connection failed. Error #2: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed [C:\SIGEST\web_pre\data\PHPMailer\class.smtp.php line 370]
SMTP Error: Could not connect to SMTP host.
CLIENT -> SERVER: QUIT
SERVER -> CLIENT: 
SMTP ERROR: QUIT command failed: 
Connection: closed
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshootingv`

**Comment by Synchro** [comment]
It's like I said - the names don't match! You're asking to connect to `webmail.av.it.pt`, but it says that it's called `becas.av.it.pt`!

**Comment by luismiguelroliveira** [comment]
And it happens why? Sorry i'm noob here!

**Comment by Synchro** [comment]
Because the name you use to connect to needs to match the name that the mail server presents - if it doesn't it's either a mistake or forgery (wrong either way), which is why turning off verification is a bad idea. If you set your `Host` value to `becas.av.it.pt`, you may find it just works.

**Comment by luismiguelroliveira** [comment]
Chaging to becas.av.it.pt doesn't solve it. 


>  Connection: opening to becas.av.it.pt:25, timeout=300, options=array ()
> Connection: opened
> SERVER -> CLIENT: 220 becas.av.it.pt Microsoft ESMTP MAIL Service ready at Fri, 14 Apr 2017 10:53:17 +0100
> CLIENT -> SERVER: EHLO sigest.av.it.pt
> SERVER -> CLIENT: 250-becas.av.it.pt Hello [192.168.86.40]250-SIZE 37748736250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-STARTTLS250-X-ANONYMOUSTLS250-AUTH NTLM250-X-EXPS GSSAPI NTLM250-8BITMIME250-BINARYMIME250-CHUNKING250 XRDST
> CLIENT -> SERVER: STARTTLS
> SERVER -> CLIENT: 220 2.0.0 SMTP server ready
> Connection failed. Error #2: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed [C:\SIGEST\web_pre\data\PHPMailer\class.smtp.php line 370]
> SMTP Error: Could not connect to SMTP host.
> CLIENT -> SERVER: QUIT
> SERVER -> CLIENT: 
> SMTP ERROR: QUIT command failed: 
> Connection: closed

**Comment by Synchro** [comment]
That openssl command shows this:

```
CONNECTED(00000003)
depth=0 CN = becas
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = becas
verify error:num=21:unable to verify the first certificate
```

So, first of all it's a self-signed cert, which they really should not be using for a public service.

I extracted their certificate and info:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            10:cd:81:94:00:1a:a1:b4:4f:75:1f:7e:c8:9c:0d:3e
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: CN=lecas
        Validity
            Not Before: Mar  3 18:34:11 2016 GMT
            Not After : Mar  3 18:34:11 2021 GMT
        Subject: CN=lecas
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:b9:7c:a1:ad:4e:56:78:2b:28:19:68:18:68:8e:
                    ...
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Subject Alternative Name:
                DNS:lecas, DNS:lecas.av.it.pt
            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
    Signature Algorithm: sha1WithRSAEncryption
         2f:d7:e1:d0:6f:7c:fc:5a:ea:be:25:a1:3d:ed:bb:aa:0a:10:
         ...
```

Weirdly, this says the name is `lecas` rather than `becas` - it may be that they rotate SMTP connections between multiple servers with different names. Either way it doesn't match `webmail`, and self-signing isn't helping. Overall this mail server is very badly configured. I think your only way through this is to disable encryption and tell it to use LOGIN auth:

```
$mail->SMTPDebug = 2;

	$mail->isSMTP();
	$mail->Host = 'webmail.av.it.pt';
	$mail->SMTPAuth = true;
	$mail->AuthType = 'LOGIN';
	$mail->Username = 'username';
	$mail->Password = 'password';
	$mail->SMTPSecure = 'tls';
	$mail->Port = 25;

	$mail->SMTPOptions = array(
	    'ssl' => array(
	        'verify_peer' => false,
	        'verify_peer_name' => false,
	        'allow_self_signed' => true
	    )
	);
```

Even though you're suppressing all the verification here, it will at least encrypt your traffic. If it still fails to log in, then I think you need to take this up with your ISP, and ask them to fix their certificates while you're at it.
