### ISSUE TITLE
Ayuda

### ISSUE THREAD

**Issue by freddyariash** [PHPMailer/PHPMailer#1026]
Hola

Cuando utilice tu script me llego una notificación de Gmail que tenía un acceso desde Santiago de Chile desde http://198.136.48.154 y es un servidor activo.
![captura de pantalla 2017-04-15 17 37 39](https://cloud.githubusercontent.com/assets/7685371/25067225/67a52638-2202-11e7-8186-edd5c30c636a.png)

**Comment by nimbly2go** [comment]
The message you received is part of Google's security fabric and was likely generated when you either logged into the Gmail account or when you used the PHPMailer script to send email via Gmail's SMTP servers.

**Comment by Eternal-Infinity** [comment]
Also, next time it would be helpful if you write in english...
