### ISSUE TITLE
RSET failed

### ISSUE THREAD

**Issue by ivan-filho** [PHPMailer/PHPMailer#1027]
Hi, i've already read a lot of forums but nothing could help me. 

This is my config:

#
        $this->IsSMTP();
        $this->SMTPAuth = true;
        $this->SMTPDebug = 2;
        $this->CharSet = "UTF-8";
        $this->Port = 587;
        $this->Host = gethostbyname('smtp.googlemail.com'); //fix ipv6 problems
        $this->SMTPSecure = 'tls';

And this is debug:

SMTP -> FROM SERVER:220 smtp.googlemail.com ESMTP m62sm4902317qte.5 - gsmtp
SMTP -> FROM SERVER: 250-smtp.googlemail.com at your service, [189.61.226.25]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
SMTP -> FROM SERVER:220 2.0.0 Ready to start TLS
SMTP -> FROM SERVER:
SMTP -> ERROR: RSET failed: 
SMTP -> NOTICE:
EOF caught while checking if connected

Could you help me please?

**Comment by Synchro** [comment]
The problem is occurring before that RSET is issued - it's failing to start TLS, which is covered in the troubleshooting guide.

You're also using an old version of PHPMailer that has bugs and vulnerabilities, so get the latest, and base your code on the gmail example provided.

**Comment by ivan-filho** [comment]
I'm using the latest version of PHPMailer. I've tried everything in troubleshooting

**Comment by Synchro** [comment]
Your debug output includes strings like `SMTP -> FROM SERVER` - PHPMailer's debug output has not looked like that for at least a couple of years. More recent versions have more informative debug output surrounding TLS problems, especially if you set `SMTPDebug = 3`. If you had tried everything in troubleshooting you would know precisely why it's giving you this error - for example, what output do you get when you connect directing using openssl, using the command example given in the guide?

**Comment by ivan-filho** [comment]
Ok. I'm sorry, now it's working, it was a certification problema. Update the code and the:
