### ISSUE TITLE
No Failure Delivery Notice

### ISSUE THREAD

**Issue by vdanelia** [PHPMailer/PHPMailer#1028]
Hello friends...
I'm using php mailer (final version) it works sends the mail, but not sending Failure Delivery Notice if the wrong email address was specified ...

Here is My Code:

`require_once "scripts/mailer/PHPMailerAutoload.php";
                $mail = new PHPMailer();
                                             
                $mail->SMTPAuth = true;
                $mail->SMTPSecure = "tls";
                $mail->Host       = "smtp.gmail.com";
                $mail->Port       = 587; 
                $mail->Username = "mymail@gmail.com";
                $mail->Password = "mypassword";
                 
                $mail->From = "mymail@gmail.com";
                $mail->FromName = 'mywebsite.com';

                $mail->AddAddress($email);

	        	$mail->WordWrap = 80;
	        	$mail->IsHTML(true);
	        	$mail->Subject = 'Registration';
	        	$mail->Body    = $message;
	        	$mail->AltBody = $message;
	        	$mail->Send();`

What is the problem, how to fix it?
Thank you In Advanced...

(When used old version of the mailer it worked perfectly)

**Comment by Synchro** [comment]
I don't understand your question. You've got no error checking code in any of this, so you won't get any feedback when it doesn't work. Base your code on the gmail example provided. PHPMailer doesn't send DSNs, that's the mail server's job.

**Comment by vdanelia** [comment]
**Google Delivery Status Notification (Failure)** 

I have configured php mailer with gmail smtp.. for user registration... the registration system itself works perfectly.... when user is registered the phpmailer is sending the activation code to the user then user clicks the link and easily activates the account..

Now My Question: If user enters invalid email address on registration form i want to be informed by google Delivery Status Notification ..

When I was using PHPMailer - Version: 2.0.0 it did.... 
if user entered invalid mail i was getting the Google Delivery Status Notification message

**Comment by Synchro** [comment]
If a user enters a syntactically invalid email address then PHPMailer won't even attempt to send the message. If you try to send to a non-existent address (but syntactically valid) (and you're using SMTP), then PHPMailer will attempt to send. Whether it is bounced immediately or accepted and returned later depends on your mail route (e.g. whether you are using a relay or smarthost) - but either way, PHPMailer has nothing to do with the generation of DSNs - by definition they are created by the receiving (bouncing) server.
