### ISSUE TITLE
Customers are reporting the PDF attachment is corrupt

### ISSUE THREAD

**Issue by wilsonf1** [PHPMailer/PHPMailer#1029]
I am use a PHP2PDF converter which generates very simple PDF's for a customers order confirmation email. But so many of our customers are reporting that the PDF's are damaged/corrupt when they try to open the attachments. My code is so simple. Any idea where I might be going wrong? Details of the exact class version I am using is below my snippet:

```
		$email = new PHPMailer();
		$email->From      = 'customerservices@' . WEBSITE_DOMAIN;
		$email->FromName  = WEBSITE_COMPANY;
		$email->Subject   = WEBSITE_DOMAIN . " - Order Number: " . fullOrderNumber($this->sw_orders->OrderNumber);
		$email->Body      =  $emalHTML;
		$email->IsHTML(true);
		$email->AddAddress( $to );
		
		$email->AddAttachment( $_SERVER["DOCUMENT_ROOT"] . '/downloads/product/policywording.pdf' , 'policywording.pdf');
		
        $email->AddAttachment( $destination_dir . $destination_filename, $destination_filename);
		
		$email->Send();
		
		$email->clearAllRecipients();
		$email->clearAttachments();

```

This is at the top of class.phpmailer.php:

> /**
>  * PHPMailer - PHP email creation and transport class.
>  * PHP Version 5.0.0
>  * Version 5.2.7
>  * @package PHPMailer
>  * @link https://github.com/PHPMailer/PHPMailer/
>  * @author Marcus Bointon (coolbru) <phpmailer@synchromedia.co.uk>
>  * @author Jim Jagielski (jimjag) <jimjag@gmail.com>
>  * @author Andy Prevost (codeworxtech) <codeworxtech@users.sourceforge.net>
>  * @author Brent R. Matzelle (original founder)
>  * @copyright 2013 Marcus Bointon
>  * @copyright 2010 - 2012 Jim Jagielski
>  * @copyright 2004 - 2009 Andy Prevost
>  * @license http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License
>  * @note This program is distributed in the hope that it will be useful - WITHOUT
>  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
>  * FITNESS FOR A PARTICULAR PURPOSE.
>  */
>

**Comment by Synchro** [comment]
You are using a very old, buggy and vulnerable version of PHPMailer from 2013. The very first thing the support docs say is to make sure you're running the latest version.

You're not checking the return values of either call to `addAttachment`, nor does this code know if the files you're attaching are not corrupt already - all PHPMailer does is attach what you give it, so if you give is bad files, it will send bad files.
