### ISSUE TITLE
BUG on class.phpmailer.php ln: 842

### ISSUE THREAD

**Issue by RJ-DigiProMedia** [PHPMailer/PHPMailer#1031]
When Adding multiple recipients:
$mail->addAddress('recipient1@mail.com');
$mail->addAddress('recipient2@mail.com');
Only first gets email.
Fix: class.phpmailer.php ln: 842
Replace: array_push($this->$kind, array($address, $name));
By: array_push($this->**to**, array($address, $name));

**Comment by Synchro** [comment]
Nope. It works fine, you're using an old version of PHPMailer, and your fix would break other functionality.

```php
$mail = new PHPMailer;
$mail->addAddress('recipient1@mail.com');
$mail->addAddress('recipient2@mail.com');
var_dump($mail->getToAddresses());
```

Output:
```
array(2) {
  [0] =>
  array(2) {
    [0] =>
    string(19) "recipient1@mail.com"
    [1] =>
    string(0) ""
  }
  [1] =>
  array(2) {
    [0] =>
    string(19) "recipient2@mail.com"
    [1] =>
    string(0) ""
  }
}
```
