### ISSUE TITLE
Can i use this lib to send email sync by SMTP?

### ISSUE THREAD

**Issue by KomaBeyond** [PHPMailer/PHPMailer#1033]
Just like what i said in the title. Please help me, thanks~

**Comment by Synchro** [comment]
Yes. Look at the SMTP examples.

**Comment by KomaBeyond** [comment]
Sorry, it it not sync, it is async async async async.

**Comment by Synchro** [comment]
That's not really up to PHPMailer itself, it's how you use it. If you're just trying to make it return control to you faster, you're best off using SMTP to a local mail server - that will allow you to send a message very quickly, and then let your mail server asynchronously send the message on to its destination. Alternatively, trigger your message send via a database or queue system, then do the actual sending via a separate PHP process, using a daemon or cron config.

**Comment by KomaBeyond** [comment]
OK, thanks. I just want to make sure that whether i can do that. Thanks again~

**Comment by slince** [comment]
@Synchro  Hello, thanks to your answer;  If PHPmailer can work like nodejs, then we don't need to fork multiple processes to send mail; maybe we need a method like `$mailer->sendAsync() ` which return a promise like [Guzzle](http://docs.guzzlephp.org/en/stable/quickstart.html#async-requests);  
Maybe this feature can be implemented based on reactphp or amphp.

**Comment by Synchro** [comment]
At present PHP _doesn't_ work like node, and there are no (well, few) async operations available (i.e. no promises or ansync/await), but it can support concurrency using threads or multiple processes. These things are likely to appear in a later version of PHP (8.0, maybe 7.4), or alternatively you can look at solutions like [Swoole](https://www.swoole.co.uk) which adds proper async support, beyond what's available in ReactPHP. If anyone cares to implement support for that in PHPMailer, I await your PR!

Aside from that, promises wouldn't actually resolve this issue - ultimately your script isn't going to return until the SMTP conversation is complete; using promises doesn't alter that, even in nodejs. All the promise allows you to do is run other stuff while it's waiting - it still has to actually complete either way, just like Guzzle's promises do - if it's the only thing your'e waiting for, it doesn't actually make any difference that it's done asynchronously.

**Comment by slince** [comment]
> just like Guzzle's promises do - if it's the only thing you're waiting for, it doesn't actually make any difference that it's done asynchronously.

This allows you to send a large number of smtp requests simultaneously in one process instead of sending requests one by one, which is too inefficient when I need to send tens of thousands of messages.

>  At present PHP doesn't work like node, and there are no (well, few) async operations available

We can switch stream to non-blocking mode by [`stream_set_blocking`](https://www.php.net/manual/en/function.stream-set-blocking.php);  This allows us to create multiple smtp connections at the same time.

>  If anyone cares to implement support for that in PHPMailer, I await your PR!

I am sorry that this is the first time I use phpmailer. I don't know phpmailer too much. If I am familiar with phpmailer in the future, I will try submit a pr for this.

**Comment by Synchro** [comment]
I've not really felt that need - I send up to around 300 messages/sec (1 million/hour) using a multi-process approach using PHPMailer, which is fast enough for pretty much anything, especially when you consider that the submission speed generally has little to do with how fast messages will be sent onwards from your MTA. Most commercial receivers (especially Yahoo & gmail) impose severe limits on how many simultaneous connections you can use, and how many messages per connection, and messages per hour they will allow you to use - but MTAs are much better suited to large-scale throttling than an MUA like PHPMailer. Multiple connections are generally less efficient that using keepalive, though of course doing both is the most effective for throughput.

**Comment by slince** [comment]
>  I send up to around 300 messages/sec (1 million/hour) using a multi-process approach using PHPMailer

**Comment by slince** [comment]
>  I send up to around 300 messages/sec (1 million/hour) using a multi-process approach using PHPMailer

Hello, how many processes have you created for this,(1million/h)? whether it is a process created with `pcntl_fork` or `proc_open`? I also encountered a similar task now. 😢

**Comment by Synchro** [comment]
Usually about 12, using `pcntl_fork`. It helps that I'm using a *very* fast commercial email server based on qmail. It can probably handle up to about 8 million/hour, but I have other bottlenecks! As I said before though, the message generation and submission speed is largely academic above a certain rate - onward delivery will be much, much slower, for example if yahoo throttles you (returning 421-code responses) to 10 simultaneous connections and 1,000 messages/hour, it doesn't matter how fast your message generation is. As a result of this you also need a mail server that can throttle based on domain groups (e.g. yahoo.*), and I don't know of good solutions that do that for any open source mail server. If you don't follow their rules, you'll find that your deliveries just get worse and worse.
