### ISSUE TITLE
Use "google/auth" library instead of "league/oauth2-google" to authenticate gmail

### ISSUE THREAD

**Issue by hakimio** [PHPMailer/PHPMailer#1043]
Google has introduced [google-auth-library-php](https://github.com/google/google-auth-library-php) which does the same as "league/oauth2-google". A lot of other google PHP libraries now depend on "google/auth" and it would make a lot of sense for PHPMailer to switch to it too.

It would also require minimal code changes. Here is how I use it:
```PHP
use Google\Auth\OAuth2;

class GmailOAuth2
{
    private $userEmail;
    private $refreshToken;
    private $clientId;
    private $clientSecret;

    public function __construct($userEmail, $clientSecret, $clientId, $refreshToken)
    {
        $this->userEmail = $userEmail;
        $this->clientSecret = $clientSecret;
        $this->clientId = $clientId;
        $this->refreshToken = $refreshToken;
    }

    /**
     * GetOauth64
     *
     * encode the user email related to this request along with the token in base64
     * this is used for authentication, in the phpmailer smtp class
     *
     * @return string
     */
    public function getOauth64 ()
    {
        $client = new OAuth2([
            'clientId' => $this->clientId,
            'clientSecret' => $this->clientSecret,
            'refresh_token' => $this->refreshToken,
            'scope' => 'https://mail.google.com/',
            'tokenCredentialUri' => 'https://www.googleapis.com/oauth2/v4/token'
        ]);

        $client->fetchAuthToken();
        $token = $client->getAccessToken();

        return base64_encode("user=" . $this->userEmail . "\001auth=Bearer " . $token . "\001\001");
    }
}
```

```PHP
class PHPMailerOAuth extends \PHPMailerOAuth
{
    public function getOAUTHInstance()
    {
        if (!is_object($this->oauth))
        {
            $this->oauth = new GmailOAuth2(
                $this->oauthUserEmail,
                $this->oauthClientSecret,
                $this->oauthClientId,
                $this->oauthRefreshToken
            );
        }

        return $this->oauth;
    }
}
```

**Comment by ooxi** [comment]
The [google/auth](https://github.com/google/google-auth-library-php) popularity mostly seams to come from it's dependent [google/apiclient](https://packagist.org/packages/google/apiclient). I don't really see why we should switch (and possibly introduce bugs) unless league/oauth2-google becomes unmaintained or google/auth becomes the clear superior choice.

Nevertheless when initially integrating OAuth into PHPMailer I would have chosen google/auth over league/oauth2-google if it would have been available at that time.

**Comment by hakimio** [comment]
The thing is, if you are using other google libraries and PHPMailer, you'll have both dependencies: "league/oauth2-google" and "google/auth" which might not be desirable for a lot of projects.

Anyway, if the owner of the project disagrees, this issue can be closed.

**Comment by ooxi** [comment]
I most certainly see your point, but currently more libraries depend on league/oauth2-google google/auth (though much more people are downloading google/auth, most likely through google/apiclient).

In my opinion we should at least wait until the situation becomes more clear. In the long term google/auth will be likely the preferred choice.

**Comment by Synchro** [comment]
Frankly, no. The oauth support in 5.2 is really not much good. The league packages are well maintained, and if you look at what has been done in the 6.0 branch, you'll see that we make far more use of the league packages, which have built-in support for many other oauth providers beyond google. I don't see any advantage in switching to the google libs.

**Comment by Synchro** [comment]
Note that if you want to, you can use the google libs yourself - someone contributed [a guide in the wiki](https://github.com/PHPMailer/PHPMailer/wiki/Gmail-XOAUTH2-Using-Google-API-Client).

**Comment by hakimio** [comment]
The guide is for "google/apiclient", not "google/auth". Also, the guide is pretty terrible.
Anyway, if you look at the code I posted above, I am using "google/auth" in my code.

**Comment by Synchro** [comment]
Ah, ok. Well, feel free to build a better wiki article on how to use the google/auth libs.
