### ISSUE TITLE
PHPMailer signing a message: The message contents may have been altered.

### ISSUE THREAD

**Issue by nimbly2go** [PHPMailer/PHPMailer#1046]
# Problem description
After carefully running through the example at https://github.com/PHPMailer/PHPMailer/blob/master/examples/signed-mail.phps (using Comodo's high grade encryption from the signup link at https://secure.comodo.com/products/frontpage?area=SecureEmailCertificate), all three files generate without a problem (supplying an import password and a private password).

Messages are generated without a problem but in Outlook 2016 a "Digital signature invalid" warning appears in the form of an icon with the error: The message contents may have been altered.

# Code to reproduce
https://github.com/PHPMailer/PHPMailer/blob/master/examples/signed-mail.phps (replacing values to reflect the locations of the three generated files as well as the private key)

Running CentOS 7 using localhost to generate mail (not sending through a third party mail system).

Any ideas on what could be causing this to take place?

**Comment by nimbly2go** [comment]
As an additional note, this is running on PHP 5.3.29, CentOS 7

**Comment by Synchro** [comment]
Quite a lot of things have been cleaned up in the new 6.0 release; please retest with that and reopen if it's still an issue.

**Comment by idefixgallier** [comment]
Hey!
I still got this error with 6.17

Any hints to get the signing working with Outlook?
