### ISSUE TITLE
Subject with Emoji 

### ISSUE THREAD

**Issue by garethstar** [PHPMailer/PHPMailer#1048]
Sending a email with Emjoi in subject is not working

**Comment by Synchro** [comment]
Set `$mail->CharSet = 'UTF-8';`, make sure you actually give valid UTF-8 strings, and it will work fine.

**Comment by garethstar** [comment]
never mind
$subject = "I Love You ❤";
$updated_subject = "=?UTF-8?B?" . base64_encode($subject) . "?=";
