### ISSUE TITLE
PHPMailerLite project

### ISSUE THREAD

**Issue by halojoy** [PHPMailer/PHPMailer#1050]
Hello!

I am using PHPMailer.
The only issue I can find is the size of class.phpmailer.php.
It has more than 4000 lines!
I would wish it to be a lot smaller.

Here is my idea.
I suggest to you to make a good alternative from scratch.
It should only have the most used functions for sending mail.
I also suggest you call it PHPMailerLite.
Keep it simple!

Start it as a new project here at Github.

Have a nice day 
and I thank you for letting me use PHPMailer. For Free.

**Comment by Synchro** [comment]
Great idea – why don't you do that - there's a "fork" button in the top right to get you started.
