### ISSUE TITLE
Php mailer Add extra body

### ISSUE THREAD

**Issue by ashikkaiser** [PHPMailer/PHPMailer#1053]
Here the sample screenshot . 

![3cdba411e6f741e2b4778708f3274627](https://cloud.githubusercontent.com/assets/81561/26294881/2db571f8-3ec7-11e7-880a-3fb3f776159b.png)

How to add previous massage body 
Here is my current code

```php
$this->mail->SMTPDebug = 0;
$this->mail->isHTML();
$this->mail->isSMTP();
$this->mail->Host = $smtphost; 
$this->mail->Port = $smtpport; 
$this->mail->SMTPSecure = $smtpprotocol;
$this->mail->SMTPAuth = true;
		
$this->mail->Username = $username; 
$this->mail->Password = $password; 
$this->mail->From =  $senderemail; 
$this->mail->FromName = $sendername;
$this->mail->AddReplyTo($replyto);
$this->mail->addCustomHeader('In-Reply-To', $message_id);

$this->mail->addAddress($lead);
$this->mail->Subject = $subject;
$this->mail->Body = $body;
```

**Comment by Synchro** [comment]
This is down to convention in formatting the message body. Indent each level of conversation by preceding each line with `> `. This can be quite hit & miss with HTML bodies.. It is generally not a structural MIME matter. You're doing the right thing with the `In-Reply-To` header, though you should also look at the `References` header. There is no no fix for the fatuous, offensive content however.
