### ISSUE TITLE
GMail showing as unauthenticated - Confusion between cPanel/WHM and docs

### ISSUE THREAD

**Issue by schwim0341** [PHPMailer/PHPMailer#1055]
Hi there again!

I've read the docs as well as the GMail "help" page when you click on the unauthenticated mail icon and I'm not quite sure of my exact issue.

If I send mail from an account on this domain through GMail, I don't get the unauthenticated icon, only when it's mailed through PHP.

I'm using SMTP through phpmailer to send my mail and I'm using an account on the domain in question for mail.  I've used Google's postmaster tools to verify the domain and in cPanel, DKIM is enabled for the same domain. SPF shows as disabled but Google states that DKIM is preferred so I haven't enabled it.

Here's the headers of an example mail that shows as unauthenticated.  Do you perhaps see something in it that hints as to why my mail is unauthenticated?  From the cPanel forums, they insinuate that if the DKIM feature is turned on in the panel, the settings should not have to be dictated in PHPMailer.  Is that the case?

```
Delivered-To: schwim.dandy@gmail.com
Received: by 10.80.178.163 with SMTP id p32csp1773205edd;
        Mon, 22 May 2017 19:28:35 -0700 (PDT)
X-Received: by 10.223.174.200 with SMTP id y66mr16703396wrc.79.1495506514322;
        Mon, 22 May 2017 19:28:34 -0700 (PDT)
Authentication-Results: mx.google.com;
       spf=neutral (google.com: 23.235.195.139 is neither permitted nor denied by best guess record for domain of support@wheeltastic.com) smtp.mailfrom=support@wheeltastic.com
Received-SPF: neutral (google.com: 23.235.195.139 is neither permitted nor denied by best guess record for domain of support@wheeltastic.com) client-ip=23.235.195.139;
Received: by 10.28.213.7 with POP3 id m7mf25566593wmg.0;
        Mon, 22 May 2017 19:28:34 -0700 (PDT)
X-Gmail-Fetch-Info: jason@wheeltastic.com 10 mail.wheeltastic.com 110 jason@wheeltastic.com
Return-Path: <support@wheeltastic.com>
Delivered-To: jason@wheeltastic.com
Received: from vps12687.inmotionhosting.com by vps12687.inmotionhosting.com (Dovecot) with LMTP id SxnNMQieI1kLawAATqdRSQ for <jason@wheeltastic.com>; Mon, 22 May 2017 22:27:20 -0400
Return-path: <support@wheeltastic.com>
Envelope-to: jason@wheeltastic.com
Delivery-date: Mon, 22 May 2017 22:27:20 -0400
Received: from [23.235.195.139] (port=46230 helo=wheeltastic.com) by vps12687.inmotionhosting.com with esmtpsa (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256) (Exim 4.89) (envelope-from <support@wheeltastic.com>) id 1dCzXc-00077v-Ov for jason@wheeltastic.com; Mon, 22 May 2017 22:27:20 -0400
Date: Mon, 22 May 2017 21:27:20 -0500
To: Jason Studley <jason@wheeltastic.com>
From: "Wheeltastic.com" <support@wheeltastic.com>
Reply-To: "Wheeltastic.com" <support@wheeltastic.com>
Subject: Thank you for your order at Wheeltastic.com!
Message-ID: <e36e233b6e61d9b111223e18a4f7b216@wheeltastic.com>
X-Mailer: PHPMailer 5.2.23 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="b1_e36e233b6e61d9b111223e18a4f7b216"
Content-Transfer-Encoding: 8bit

--b1_e36e233b6e61d9b111223e18a4f7b216
Content-Type: text/plain; charset=us-ascii
```

Any thoughts on the matter would be very welcome!

**Comment by Synchro** [comment]
You should definitely configure SPF as well; it's complementary to DKIM. The two together enable you to use DMARC.

There's more to DKIM than sticking some records in DNS - you have to sign every outbound message - the example you posted has no signature. To do that, base your code on [this example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/DKIM.phps).
