### ISSUE TITLE
Unable to send mail using google cloud

### ISSUE THREAD

**Issue by kmaulik** [PHPMailer/PHPMailer#1056]
I trying to send mail using smtp via google cloud but unable to send it, It's working on my local but not on google cloud server. 

This Error Occur :
----------------------
220 smtp.gmail.com ESMTP j5sm415071iti.20 - gsmtp

hello: 250-smtp.gmail.com at your service, [35.184.170.69]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
Failed to authenticate password. Error: 534-5.7.14  Please log in via your web browser and
534-5.7.14 then try again.
534-5.7.14  Learn more at
534 5.7.14  https://support.google.com/mail/answer/78754 j5sm415071iti.20 - gsmtp

Unable to send email using PHP SMTP. Your server might not be configured to send mail using this method.
User-Agent: CodeIgniter
Date: Tue, 23 May 2017 05:09:58 +0000
From: "YourToothFairy.com" <vpa11@narola.email>
Return-Path: <vpa11@narola.email>
To: dhk@narola.email
Subject: =?utf-8?Q?=59=6F=75=72=54=6F=6F=74=68=46=61=69=72=79=2E=63=6F=6D=20=2D=20?= =?utf-8?Q?=46=6F=72=67=6F=74=20=50=61=73=73=77=6F=72=64=20=52=65=71=75=65?= =?utf-8?Q?=73=74?=
Reply-To: <vpa11@narola.email>
X-Sender: vpa11@narola.email
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: <5923c4261d729@narola.email>
Mime-Version: 1.0

Content-Type: multipart/alternative; boundary="B_ALT_5923c4261d773"

**Comment by Synchro** [comment]
Have you considered the possibility that the URL they give you in the error message might contain some clues?
