### ISSUE TITLE
Unable to send Emoji in subject

### ISSUE THREAD

**Issue by electronyxbazaar** [PHPMailer/PHPMailer#1057]
I'm using PHP Mailer to send with my script, but I'm unable to use Emojis in the subject.

Please resolve this I'm trying your since 2 days

**Comment by Synchro** [comment]
It works just fine - see the unit tests for working examples. Make sure your whole workflow is UTF-8 capable, and then set it as the charset in PHPMailer:

    $mail->CharSet = 'UTF-8';

**Comment by electronyxbazaar** [comment]
Kindly show an example
My script
require_once('class.phpmailer.php');
$mail = new PHPMailer(true); // the true param means it will throw exceptions on errors, which we need to catch
$mail->IsSMTP(true); // telling the class to use SMTP
$mail->IsHTML(true);
try {
\mail->Host = "ssl://server.com"; // SMTP server
$mail->SMTPDebug = 2; // enables SMTP debug information (for testing)
$mail->SMTPAuth = true; // enable SMTP authentication
\mail->Host = "ssl://server.com"; // sets the SMTP server
$mail->Port = 465; // set the SMTP port for the GMAIL server
\mail->Username = "mail@server.com"; // SMTP account username
$mail->Password = "abc@123"; // SMTP account password
\mail->AddReplyTo('mail@apnaprice.com', 'Server');
$mail->AddAddress("$email", "$firstname $lastname");
\mail->SetFrom('mail@server.com', 'Server');
\mail->AddReplyTo('mail@server.com', 'Server');
$mail->Subject = 'Get upto 61% OFF on Shoes 👟';
$mail->AltBody = 'To view the message, please use an HTML compatible email viewer!'; // optional - MsgHTML will create an alternate automatically
$mail->Body = " ";
$mail->Send();
echo "Message Sent to $email | Subject
\n";
} catch (phpmailerException $e) {
echo $e->errorMessage(); //Pretty error messages from PHPMailer
} catch (Exception $e) {
echo $e->getMessage(); //Boring error messages from anything else!
}

**Comment by Synchro** [comment]
You just need to add the line I gave you! What's with all the `\` in your code?

**Comment by Synchro** [comment]
Also, this code implies that you're using a very old version of PHPMailer, so I suggest you get the latest.
