### ISSUE TITLE
Failure problem

### ISSUE THREAD

**Issue by JohnZakaria** [PHPMailer/PHPMailer#1061]
hi guys i want to know how to make the following

1- i want failure mail to be different that from email coz now it goes to the from address
2- when i send email to wrong address info@abc.com it show for me that message has been sent but when i checked i found that the message sent is the failure message not the $to 

i assume to get a message that info@abc.com is not received because of failure and also sending failure email 

any idea please

**Comment by Synchro** [comment]
It's really unclear what you're saying. If you want bounces to go somewhere other than the `From` address, set the `Sender` property.

**Comment by JohnZakaria** [comment]
if i send an email to address: info@abc.com which is not a real mail 
1- i have mail from example@example.com but i want to get delivery failure into example2@example.com
2- i want to get a message in browser that mail  info@abc.com did not receive the message because of failure

**Comment by Synchro** [comment]
You can't tell immediately (because bounces happen asynchronously, and could take up to a week), but you would use these settings:

```
$mail->addAddress('info@abc.com');
$mail->From = 'example@example.com';
$mail->Sender = 'example2@example.com';
```

**Comment by JohnZakaria** [comment]
i am using $mail->setFrom("example@example.com", $display_name);

how to make failure mail?

i did not receive using $mail->Sender = 'example2@example.com';

**Comment by Synchro** [comment]
You will only receive bounces at that address when messages that fail *after* sending. If they fail immediately you should look at the return value from `send()`. It helps to look at the logs of your mail server, and what it shows when you set `$mail->SMTPDebug = 2;`.

**Comment by JohnZakaria** [comment]
dear Mr Synchro thanks for your help my question is when i put $mail->Sender = 'example2@example.com'; i did not receive failure mail on this address

**Comment by Synchro** [comment]
Read what I said.

**Comment by JohnZakaria** [comment]
ah ok i did not see this message ,, thanks alot
