### ISSUE TITLE
i need to help to add References in header 

### ISSUE THREAD

**Issue by ashikkaiser** [PHPMailer/PHPMailer#1062]
I need to help to doing this am new

![fdc05aefab2a4d4a93939bfb6415b5c4](https://cloud.githubusercontent.com/assets/81561/26557475/fce5f7d8-44a1-11e7-9a66-95ec36fd2577.png)

This is my current setting:

```php
$this->mail->isHTML();
$this->mail->isSMTP();
$this->mail->Host = $smtphost; 
$this->mail->Port = $smtpport; 
$this->mail->SMTPSecure = $smtpprotocol;
$this->mail->SMTPAuth = true;
$this->mail->Username = $username; 
$this->mail->Password = $password; 
$this->mail->From =  $uname; 
$this->mail->FromName = $sendername;
$this->mail->AddReplyTo($replyto);
$this->mail->addCustomHeader('In-Reply-To', $message_id);
$this->mail->addAddress($lead);
$this->mail->Subject = $subject;
$this->mail->Body= $body;
```

**Comment by Synchro** [comment]
PHPMailer's involvement extends only as far as being able to set the header, which you're doing the right way. As for what to put into a `References` header, read [this](https://cr.yp.to/immhf/thread.html), and many similar docs. In short, when you reply, append the previous `Message-ID` header value wrapped in `<>` to the end of the `References` header (you can see it being done in your example).

**Comment by ashikkaiser** [comment]
how can i do it http://prntscr.com/fdhe2m

**Comment by Synchro** [comment]
Quoting is also left up to you. It's easy with plain text, but much more difficult with HTML message bodies.

**Comment by ashikkaiser** [comment]
ok . one more thing . just tell me how  can i get  mail time 
![image](https://cloud.githubusercontent.com/assets/14245701/26557882/75e5b4a6-44c6-11e7-897d-94584d84b4bd.png)

not in  from there 
![image](https://cloud.githubusercontent.com/assets/14245701/26557901/94a1c54c-44c6-11e7-8e7f-382bf8a10b11.png)


if i use    $overview[0]->date    then its get  time from picture2 . but i need to Pic one 
or  if possible to change time format picture 2 is same as picture 1 . its also work for me .

Its need to add extra text in massage body like this 
![image](https://cloud.githubusercontent.com/assets/14245701/26557991/3dfc5c4c-44c7-11e7-9c8a-1d94b260a676.png)

**Comment by Synchro** [comment]
Uh, those two times are the same, just presented differently. 19:17 is the same time as 7:19pm. There are many PHP projects and extensions (try IMAP) that can help you parse a message and extract that date from the header. When you format it for output, use functions like `date()`.

**Comment by ashikkaiser** [comment]
can i chnage it from class.phpmiler.php
`public static function rfcDate()
    {
        // Set the time zone to whatever the default is to avoid 500 errors
        // Will default to UTC if it's not set properly in php.ini
        date_default_timezone_set(@date_default_timezone_get());
        return date('D, j M Y H:i:s O');`

**Comment by Synchro** [comment]
No, no need to touch that. Turn the inbound message date into a `Date` object in PHP, then render it in whatever format you like for the message body. You don't need to worry about the headers (normally they're not shown directly), and they need to be in a fixed format to be compliant with RFCs.
