### ISSUE TITLE
Class 'SMTP' not found in /var/www/html/emails/class.phpmailer.php:1291

### ISSUE THREAD

**Issue by younas-bangash** [PHPMailer/PHPMailer#1064]
```
require 'PHPMailerAutoload.php';
	if (class_exists('PHPMailer')) {
		$mail = new PHPMailer;
	}
	$mail->SMTPDebug  = 2; 
	$mail->isSMTP();
	$mail->Host = gethostbyname("tls://smtp.gmail.com"); 
	$mail->Port = 25;
	$mail->SMTPAuth = true; 
	$mail->setFrom('valid_email', 'Name');
	$mail->Username = 'valid_email';
	$mail->Password = 'valid_pwd';
	$mail->SMTPSecure = 'tls';
	$mail->FromName = 'Name';
	$mail->addAddress('valid_email');
	$mail->WordWrap = 70;
	$mail->isHTML(true);
	$mail->Subject = "subject";
	$mail->Body    = "message";
	$mail->AltBody = 'AltBody area';
	if(!$mail->send()) {
	}
```
and In the loaction /var/www/html/emails/ i put following files
```
class.phpmailer.php
PHPMailerAutoload.php
PHP Version : 7
```

Following Error I Face :

`Fatal error: Uncaught Error: Class 'SMTP' not found in /var/www/html/emails/class.phpmailer.php:1291 Stack trace: #0 /var/www/html/emails/class.phpmailer.php(1374): PHPMailer->getSMTPInstance() #1 /var/www/html/emails/class.phpmailer.php(1311): PHPMailer->smtpConnect(Array) #2 /var/www/html/emails/class.phpmailer.php(1156): PHPMailer->smtpSend('Date: Wed, 31 M...', 'This is a multi...') #3 /var/www/html/emails/class.phpmailer.php(1060): PHPMailer->postSend() #4 `

**Comment by Synchro** [comment]
So you didn't upload the SMTP class, and now you're surprised it can't find it? It might help if you read the readme file which tells you exactly which files you need.

**Comment by Synchro** [comment]
And you don't need that `class_exists` call - in fact it's not doing what you think it is as it will trigger autoloading automatically the way you're calling it. Don't just make stuff up and hope it works!

**Comment by younas-bangash** [comment]
Thanks @Synchro  for your reply I solved the issue
