### ISSUE TITLE
Mysterious SMTP despatch failures

### ISSUE THREAD

**Issue by mjoycemilburn** [PHPMailer/PHPMailer#1066]
I know there's always a reason for IT failure and so failures are never strictly random, but I have a PHP test script here that is driving me nuts because, while I'm not changing it , it sometimes works and sometimes doesn't. So something is changing somewhere else in the environment but I can't figure out what.

By "works" I mean that the script reports correct despatch (ie PHPMailer returns true) and my target addresses receive the test messages. By "fails" I mean the script reports correct despatch but the test messages are not received.

I've had a long conversation with my ISP support desk around the possibility that I'm exceeding their hourly despatch limit, but their advice is that if I'm triggering that then I should see "bounce-back" messages in my in-box on their server. There's nothing there. In any event my script only sends two messages and I've not been running it more than three or four times an hour.

Any advice on where I might look to get more information on this problem would be most welcome.

One thing I've noted is that when my script runs I receive either both messages or none.

The guts of the script are as follows:

require 'libs/PHPMailer/PHPMailerAutoload.php';
$mail = new PHPMailer;
$mail->setFrom('my server-based email address', 'Apparch Administrat0r');
$mail->addAddress('my personal email address', 'Martin Joyce');
$mail->Subject = 'Welcome to Appleby Archaeology';
$mail->isHTML(true);
$mail->Body = $membership_message;
$mail->SMTPDebug = 3;
if (!$mail->send()) {
    echo 'Message was not sent.';
    echo 'Mailer error: ' . $mail->ErrorInfo;
} else {
    echo 'Message has been sent.';
}

**Comment by Synchro** [comment]
Given that your PHP script itself is always succeeding, the problem must be further upstream; in short, you need to look at your mail server logs.

**Comment by mjoycemilburn** [comment]
Thanks Marcus. I've been doing quite a bit more work on this and I think I know what's been going on.

I'm new to this bit of the game and I hadn't appreciated that in the smtp world that, while you may send messages in a particular order, you can't expect to see them received in the same order.

This only became apparent to me when I started testing despatch of large blocks of mail. I sent a block of 20 with sequence numbers in their title.  Arrival was only vaguely sequential and I got very alarmed by the fact that the second message seemed to have been lost entirely.

Then fully 15 minutes later it arrived!

I now think that when I believed I'd lost messages they were in fact just delayed. Their subsequent arrival was then masked by other testing activity. 

Well - it's a theory. 

Just as a follow-up. My ISP seem to have access to my SMTP logs but I'm not sure that I can see them. Am I missing something here?

Regards, MJ

**Comment by Synchro** [comment]
Welcome to the weird world of email! You may not have access to mail server logs if you're on shared hosting. That's one of the downsides of not having full access to your server. There's not a lot you can do to diagnose problems like this that are one step removed from your scripts. Maybe ask your host for recent mail log output?

**Comment by mjoycemilburn** [comment]
Thanks synchro. My ISP has actually been very helpful over this one. At least I know now where to look.

Regards, MJ
