### ISSUE TITLE
works fine on xampp but not on production server

### ISSUE THREAD

**Issue by celleyes** [PHPMailer/PHPMailer#1067]
I am connected through gmail smtp setting. it works fine on xampp server but doesn't work on production server and don't receive even any verbose but simple php echo error 'Message could not be sent.'

spent hours but couldn't find any solution.

**Comment by Synchro** [comment]
All those hours and you didn't read the troubleshooting guide or try using the provided Gmail example. Your ISP probably blocks outbound SMTP.
