### ISSUE TITLE
SMTP connect() failed.

### ISSUE THREAD

**Issue by omer9464** [PHPMailer/PHPMailer#1069]
Hi. I am reveiving such an error when ı try to send mail. 

> 2017-06-06 08:49:32	Connection: opening to smtp.office365.com:587, timeout=300, options=array ( ) 2017-06-06 08:49:49	Connection failed. Error #2: stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known [/var/www/test/lib/mailer/class.smtp.php line 294] 2017-06-06 08:49:49	Connection failed. Error #2: stream_socket_client(): unable to connect to smtp.office365.com:587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) [/var/www/test/lib/mailer/class.smtp.php line 294] 2017-06-06 08:49:49	SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Name or service not known (0) 2017-06-06 08:49:49	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

``		$mail = new PHPMailer;
		$mail->SMTPDebug = 4;                   // Enable verbose debug output
		$mail->isSMTP();     
		$mail->SMTPSecure = 'tls';              // Set mailer to use SMTP
		$mail->SMTPAuth = true;                 // Enable SMTP authentication
		$mail->Host = 'smtp.office365.com';  	// Specify main and backup SMTP servers
		$mail->Username = 'test@test.com';      // SMTP username
		$mail->Password = 'test123';            // SMTP password
		$mail->Port = 587;
		$mail->SetLanguage("tr", "phpmailer/language");
		$mail->CharSet  ="utf-8";
		$mail->Encoding="base64";
		$mail->setFrom('test@test.com', 'test test');
		$mail->addAddress("test@test.com","testt");     // Add a recipient
		$mail->isHTML(true);                            // Set email format to HTML
		$mail->Subject = " test test test test...";
		$mail->Body    = $testresult;
		if(!$mail->send()) {
				echo "<div class='alert alert-warning' role='alert'>".$mail->ErrorInfo."</div>";
		}

**Comment by Synchro** [comment]
DNS lookups are broken on your server. Fix that and PHPMailer will be able to work.

**Comment by omer9464** [comment]
` $mail = new PHPMailer;
			$mail->SMTPDebug = 4; // Enable verbose debug output
			$mail->isSMTP();                                      // Set mailer to use SMTP
			$mail->Host = 'mail.test.com.tr';  // Specify main and backup SMTP servers
			$mail->SMTPAuth = true;                               // Enable SMTP authentication
			$mail->Username = 'web@test.com.tr';                 // SMTP username
			$mail->Password = 'test';                           // SMTP password
			$mail->SetLanguage("tr", "phpmailer/language");
			$mail->CharSet  ="utf-8";
			$mail->Encoding="base64";
			$mail->setFrom('web@test.com.tr', 'Web İletişim Formu');
			$mail->addAddress('test@pamukkale.com.tr', 'Musteri Iletimi');     // Add a recipient
			$mail->isHTML(true);                                  // Set email format to HTML
			$mail->Subject = "test test";
			$mail->Body    = " "  `

this work But i do not send when I make smtp.office365.com

**Comment by Synchro** [comment]
Is it perhaps that office365 access is blocked from Turkey? I know all kinds of things are getting blocked and I think they are implementing blocks like this using DNS. Check your DNS by using tools like `dig` and `host` on your server.

**Comment by omer9464** [comment]
Wrong entry dns address. My problem is solved. thank you.

**Comment by SidduPujari** [comment]
i am hosted one live website, & i am using phpmailserver to send mail from my website so it's working fine in localhost. but it's getting error in live website plz help me
error will be like this
2019-05-29 06:36:56 Connection: opening to siddupujari.epizy.com:587, timeout=300, options=array ()
2019-05-29 06:36:56 Connection failed. Error #2: stream_socket_client(): unable to connect to siddupujari.epizy.com:587 (Connection refused) [/home/vol1_2/epizy.com/epiz_23940175/htdocs/mail/class.smtp.php line 300]
2019-05-29 06:36:56 SMTP ERROR: Failed to connect to server: Connection refused (111)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
Please read the troubleshooting guide linked form the error. It's likely that your hosting provider (but not your local ISP) is blocking outbound SMTP. Refer to their documentation for how you are supposed to send mail from their network; either they won't let you, or you need to ask, or you must use their mail servers.

**Comment by SidduPujari** [comment]
okay bro, plz suggest how can i resolve that error

**Comment by Synchro** [comment]
I already did?

**Comment by SidduPujari** [comment]
okay bro thank you for reply

**Comment by vaibhaob** [comment]
Hii I am receiving this error
SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: No such host is known.  (0)SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
@vaibhaob That means one of two things: the hostname in your `Host` property is wrong, and is not the name of a server that exists, or your DNS system is broken.

**Comment by vaibhaob** [comment]
Thank You..!

**Comment by prakrishna2004** [comment]
SMTP -> ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution (0)

The following From address failed: example@gmail.com

Can any one help to resolve this issue?

**Comment by Synchro** [comment]
Yes: your DNS is broken.

**Comment by prakrishna2004** [comment]
This code is working on alfa.example.com
But same code is now working for beta.example.com

May i know what would be the issue?

**Comment by prakrishna2004** [comment]
Fixed it by adding mail host in /etc/hosts file.
Thank you everyone...

**Comment by Synchro** [comment]
That's not really a fix. If PHPMailer is failing because of that, other parts of your system will be too.
