### ISSUE TITLE
Troubleshooting Error

### ISSUE THREAD

**Issue by Abhi-nitw** [PHPMailer/PHPMailer#1070]
## **SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: No such host is known**

This is the full error_message shows in browser : 
 "2017-06-08 04:31:11	Connection: opening to ssl://mail.smtp2go.com:2525, timeout=300, options=array ( ) 2017-06-08 04:31:11	Connection failed. Error #2: stream_socket_client(): php_network_getaddresses: getaddrinfo failed: No such host is known. [C:\xampp\htdocs\photo_gallery\includes\PHPMailer\class.smtp.php line 292] 2017-06-08 04:31:11	Connection failed. Error #2: stream_socket_client(): unable to connect to ssl://mail.smtp2go.com:2525 (php_network_getaddresses: getaddrinfo failed: No such host is known. ) [C:\xampp\htdocs\photo_gallery\includes\PHPMailer\class.smtp.php line 292] 2017-06-08 04:31:11	SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: No such host is known. (0) 2017-06-08 04:31:11	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting Error"

## code : 
`IsSMTP(); $mail->Host = "mail.smtp2go.com"; //$mail->Host = "mail.gmail.com"; $mail->SMTPDebug = 4; $mail->Port = 2525; $mail->SMTPAuth = true; $mail->SMTPSecure = "ssl"; $mail->Username = "mypersonal_email@gmail.com"; $mail->Password = "mypassword"; $mail->SetFrom('s.singh.hbn@gmail.com', 'PRSPS'); $mail->MsgHTML($message); $mail->isHTML(true); $mail->From_name = $from_name; $mail->From = $from; $mail->AddAddress($to,$to_name); $mail->Subject = $subject; $mail->Body = $message; $result = $mail->send(); echo $result ? 'Sent' : 'Error'; ?>
`

**Comment by Synchro** [comment]
It means that your DNS is broken on your server. Fix that and PHPMailer will be able to work.

**Comment by Synchro** [comment]
Read the thread, don't just post blindly.

**Comment by muhamedRadwan** [comment]
are you have an article on how to fix DNS, Please?

**Comment by Synchro** [comment]
No, because it's nothing to do with PHPMailer, and it will be different in every operating system - so read the docs for your system, or search for answers.

**Comment by cybster** [comment]
Most web hosts block outgoing ports but never port 443. SMTP2GO can send mail on port 443. This works on pretty much all web servers. Also, using the SMTP2GO API instead pf PHPMailer is usually more reliable. [https://apidoc.smtp2go.com/documentation/#/README](url)

**Comment by Synchro** [comment]
This issue has nothing to do with outbound ports. Using an HTTP API will not help at all. If your DNS is broken, you will not be able to connect to that either.
