### ISSUE TITLE
E-mails are going into the SPAM 

### ISSUE THREAD

**Issue by worldsdream** [PHPMailer/PHPMailer#1075]
Hi,

I don't know why but e-mails are going into the SPAM. How can we fix this issue? I love phpmailer but please help me to get this working. What kind of information do you need to help me on this one?

Regards

**Comment by Synchro** [comment]
This isn't up to PHPMailer, it's more to do with your mail server IPs, DNS config and past sending reputation, which can take many months to build. There are many guides to tell you how to improve things, and PHPMailer will help you implement them, but you need to find what works for you.
