### ISSUE TITLE
SMTP/Office365/Hostgator

### ISSUE THREAD

**Issue by Shinideakon** [PHPMailer/PHPMailer#1080]
The file I have works on my little test server in the office, but when I upload it to hostgator, I get:

`2017-06-20 21:01:30	Connection: opening to smtp.office365.com:587, timeout=300, options=array ( ) 2017-06-20 21:01:30	Connection: Failed to connect to server. Error number 2. "Error notice: stream_socket_client(): unable to connect to smtp.office365.com:587 (An attempt was made to access a socket in a way forbidden by its access permissions. ) 2017-06-20 21:01:30	SMTP ERROR: Failed to connect to server: An attempt was made to access a socket in a way forbidden by its access permissions. (10013) 2017-06-20 21:01:30	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting 
Fatal error: Uncaught exception 'phpmailerException' with message 'SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting' in D:\InetPub\vhosts\instantinsoles.com\httpdocs\mail-tester\php-mailer\class.phpmailer.php:1490 Stack trace: #0 D:\InetPub\vhosts\instantinsoles.com\httpdocs\mail-tester\php-mailer\class.phpmailer.php(1326): PHPMailer->smtpSend('Date: Tue, 20 J...', 'This is a multi...') #1 D:\InetPub\vhosts\instantinsoles.com\httpdocs\mail-tester\php-mailer\class.phpmailer.php(1206): PHPMailer->postSend() #2 D:\InetPub\vhosts\instantinsoles.com\httpdocs\mail-tester\index.php(22): PHPMailer->send() #3 {main} thrown in D:\InetPub\vhosts\instantinsoles.com\httpdocs\mail-tester\php-mailer\class.phpmailer.php on line 1490`

The port is open, but I'm not sure if they are blocking other things. Thanks for any help

**Comment by Synchro** [comment]
This looks like a firewall issue. What happens if you telnet to port 587 from your hostgator server?
