### ISSUE TITLE
SMTP connect failed

### ISSUE THREAD

**Issue by ocvninfo** [PHPMailer/PHPMailer#1081]
My submit form on this domain https://spyassociates.com/
I used ajax to POST request to a cross domain https://themevale.net/tools/sendmail/ask-an-expert/
It's working correctly when i submit form.
But when i use another url http://blog.spyassociates.com/ask-an-expert/
And then when i submit form, I got this error message: 

> Connection: opening to smtp.gmail.com:587, timeout=300, options=array ()
> SMTP ERROR: Failed to connect to server: Connection refused (111)
> SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
> Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

Anyone tell me why?
Thanks

**Comment by Synchro** [comment]
You didn't give any information about these locations or the code you're running. It looks like wherever your code is running for the second URL, outbound SMTP is blocked, so read the troubleshooting guide it links to.
