### ISSUE TITLE
Messages received as junk on hotmail only,although it has passed SPF and DKIM checks. 

### ISSUE THREAD

**Issue by jaber9030** [PHPMailer/PHPMailer#1087]
Messages are sent from phpmailer is  received as junk only on hotmail,messages are passing spf and  dkim checks after i make the requested modifications. so email has SPF:pass and DKIM:pass header,i used this code:
 $mail = new PHPMailer(true);
     $mail->Host = 'smtp.office365.com'  ;
     $mail->Port       = 587;
     $mail->SMTPSecure = '';
     $mail->SMTPAuth   = true;
     $mail->Username = account;
     $mail->Password = password;
     $mail->SetFrom(account, 'SITE');
    $mail->Sender =account; ;
      $mail->addReplyTo(account;);
     $mail->SMTPDebug  = false;
     $mail->SingleTo = true ;
    $mail->DKIM_domain = domain;
    $mail->DKIM_private =$_SERVER['DOCUMENT_ROOT']."/dkim-private.pem";
    $mail->DKIM_selector = "mail";
    $mail->DKIM_passphrase = "";
    $mail->DKIM_identifier = $mail->From;
    $mail->XMailer   = ' ';
    foreach ($to as $email)
          {
              $mail->addAddress($email);
          }
      if(!is_null($cc))
      {
          foreach ($cc as $email)
          {
              $mail->addCC($email);
          }
      }
     $mail->Subject = $subject;
     $mail->IsHTML(true);
    $mail->MsgHTML($body);
     if(!$mail->send()) {
         //echo 'Message could not be sent.';
         echo 'Mailer Error: ' . $mail->ErrorInfo;
     } else {
         return true ;
     }
as you emails are hosted on office365 not on the same domain,so is that will be the problem?

**Comment by Synchro** [comment]
You're doing everything right, but unfortunately passing SPF and DKIM checks gives no guarantee that your messages won't be classified as spam. If there was an easy way to guarantee inbox placement, spammers would use it and render it useless. Check the headers of your received messages - they may contain some clue as to what they didn't like. It's common for messages from a new source to be classified as spam regardless, and it can take months of recipient engagement to make it to the inbox.
