### ISSUE TITLE
office 365 with phpMailer taking long time

### ISSUE THREAD

**Issue by addiega** [PHPMailer/PHPMailer#1097]
Hi All,

I am using phpmailer and my code as follows.

`<?php`
`require 'PHPMailer-master/PHPMailerAutoload.php';`

`$mail = new PHPMailer;`

`//$mail->SMTPDebug = 3;                               // Enable verbose debug output`

`$mail->isSMTP();                                      // Set mailer to use SMTP`
`$mail->Host = 'tls://smtp.office365.com:25';  // Specify main and backup SMTP servers`
`//$mail->Host = 'smtp.office365.com'; (this one not working for me. So i Used the above one)`
`$mail->SMTPAuth = true;                               // Enable SMTP authentication`
`$mail->Username = 'name@domain.in';                 // SMTP username`
`$mail->Password = 'pass007';                           // SMTP password`
`$mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted`
`$mail->Port = 25;                    // TCP port to connect to`
`//$mail->Port = 587; (used this port also, but no output)`
`$mail->setFrom('name@domain.in', 'Startup');`
`$mail->addAddress('name2@domain.in', 'User');     // Add a recipient`
`$mail->isHTML(true);                                  // Set email format to HTML`

`$mail->Subject = 'Get in Touch';`
`$mail->Body    = '<b>Full Name:</b> '.$_POST['fname'].'<br>';`
`$mail->Body.= '<b>Email:</b> '.$_POST['email'].'<br>';`
`$mail->Body.= '<b>Contact Number:</b> '.$_POST['contact'].'<br>';`
`if(!$mail->send()) {`
 `   echo 'Message could not be sent.';`
 `   echo 'Mailer Error: ' . $mail->ErrorInfo;`
`} else {`
 `   ?>`
    
`Thanks for reaching Us!! We will get back to you shortly!!`
`<script>`
 `   `
  `  setTimeout(function () {`
   `    window.location.href = "http://www.domain.com/";`
    `}, 2000);`
`</script>`
 `   <?php`
`}`
`$Mail->SmtpClose();`

`?>`
If I use `$mail->isMail();` the mail is received by the gmail, but not in the case of office 365. If I use the function `$mail->isSMTP();`  it will take long time and 524 error is coming. 

![image](https://user-images.githubusercontent.com/30289786/28364121-d636bba0-6ca0-11e7-83f2-06a149a7b3cb.png)

Interesting thing is I can receive  the mail. But I'm getting the above error.

Any other options please let me know.

Thanks,
Addiega.

**Comment by Synchro** [comment]
It's very unlikely that TLS on port 25 will work for outbound mail; use port 587 [like the office 365 docs suggest](https://support.office.com/en-gb/article/POP-and-IMAP-account-settings-cb41d2b8-98cb-4ab2-ad60-218349f37e2e?ui=en-US&rs=en-GB&ad=GB).
