### ISSUE TITLE
How to force the library to use Utf-8 as the default CharSet?

### ISSUE THREAD

**Issue by EgyptianM** [PHPMailer/PHPMailer#1098]
Hi,

I saw an issue and a PR asking to switch to UTF-8 as the default CharSet for the library but I see that you decided to stick to iso, but I need to force  utf-8 to be the default charset for the library so how can I do this?
I'm using RTL language on my site so it breaks in emails and shows special characters.

I'm a newbie in php so if you please tell me where to make changes exactly.

Best regards.

**Comment by Synchro** [comment]
There's no "forcing" required, just set it before you use it:

    $mail->CharSet = 'UTF-8';

If you want to have it do this all the time, just create a subclass that sets it by default and always use that subclass:

```php
class myPHPMailer extends PHPMailer
{
    public CharSet = 'UTF=8';
}
```

You should not edit the library files themselves as it will break your code when you update the library.
