### ISSUE TITLE
Sends Mail From Main Server But Not From Other Domains On Same Server

### ISSUE THREAD

**Issue by mwalker205** [PHPMailer/PHPMailer#1099]
I have a dedicated server that runs multiple domains, each with their own IP address.
www.main-domain.com 100.100.100.100
www.domain1.com 11.11.11.111
www.domain2.com 22.22.22.222
www.domain3.com 33.33.33.123

On the main domain, I have a back office app that can access each of the separate domains and databases. From there, I can send emails to clients from whichever domain I am currently logged in to. The following is the code I have that prepares and kicks off the email:

`$mail = new PHPMailer;
$mail->isSMTP();
$mail->Host = 'smtp.domain1.com';
$mail->SMTPAuth = true;
$mail->Username = 'domain1Username';
$mail->Password = 'domain1Password';
$mail->SMTPSecure = 'tls';
$mail->Port = 587;
$mail->addAddress(recipient@test.com);
$mail->setFrom(support@domain1.com);
$mail->addReplyTo(support@domain1.com);
$mail->isHTML(true);	
$mail->Subject = 'This is the subject';
$mail->Body    = 'This is the message.';
$mail->send();`

The values for Host, Username and Password are all dynamically set, based on whatever domain's database I am accessing at that time (domain1.com, domain2.com, domain3.com, etc).
When I send the email, it is successful and I get the following from SMTPDebug = 3:

> 2017-07-21 09:04:27 Connection: opening to smtp.domain1.com:587, timeout=300, options=array ( ) 2017-07-21 09:04:27 Connection: opened 2017-07-21 09:04:27 SERVER -> CLIENT: 220-name.main-domain.com ESMTP Exim 4.89 #1 Fri, 21 Jul 2017 05:04:27 -0400 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail. 2017-07-21 09:04:27 CLIENT -> SERVER: EHLO www.main-domain.com 2017-07-21 09:04:27 SERVER -> CLIENT: 250-name.main-domain.com Hello www.main-domain.com [22.22.22.222] 250-SIZE 52428800 250-8BITMIME 250-PIPELINING 250-AUTH PLAIN LOGIN 250-STARTTLS 250 HELP 2017-07-21 09:04:27 CLIENT -> SERVER: STARTTLS 2017-07-21 09:04:27 SERVER -> CLIENT: 220 TLS go ahead 2017-07-21 09:04:27 CLIENT -> SERVER: EHLO www.main-domain.com 2017-07-21 09:04:27 SERVER -> CLIENT: 250-name.main-domain.com Hello www.main-domain.com [22.22.22.222] 250-SIZE 52428800 250-8BITMIME 250-PIPELINING 250-AUTH PLAIN LOGIN 250 HELP 2017-07-21 09:04:27 CLIENT -> SERVER: AUTH LOGIN 2017-07-21 09:04:27 SERVER -> CLIENT: 334 V3KXzm5hbFU4 2017-07-21 09:04:27 CLIENT -> SERVER: b3KvyZ0ydEAxMNSefG5jb10= 2017-07-21 09:04:27 SERVER -> CLIENT: 334 UJEfc1djwiQ3 2017-07-21 09:04:27 CLIENT -> SERVER: bXExeRGdzwsNF2r 2017-07-21 09:04:27 SERVER -> CLIENT: 235 Authentication succeeded 2017-07-21 09:04:27 CLIENT -> SERVER: MAIL FROM: 2017-07-21 09:04:27 SERVER -> CLIENT: 250 OK 2017-07-21 09:04:27 CLIENT -> SERVER: RCPT TO: 2017-07-21 09:04:27 SERVER -> CLIENT: 250 Accepted 2017-07-21 09:04:27 CLIENT -> SERVER: DATA 2017-07-21 09:04:27 SERVER -> CLIENT: 354 Enter message, ending with "." on a line by itself 2017-07-21 09:04:27 

Now, if a user is on one of the domains, domain1.com for example, and they execute a function that kicks off an email, no email is sent and I get the following:

> 2017-07-21 08:02:46 Connection: opening to smtp.domain1.com:587, timeout=300, options=array ( ) 2017-07-21 08:02:46 Connection: opened 2017-07-21 08:02:46 SERVER -> CLIENT: 220-name.main-domain.com ESMTP Exim 4.89 #1 Fri, 21 Jul 2017 04:02:46 -0400 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail. 2017-07-21 08:02:46 CLIENT -> SERVER: EHLO www.domain1.com 2017-07-21 08:02:46 SERVER -> CLIENT: 250-name.main-domain.com Hello www.domain1.com [22.22.22.222] 250-SIZE 52428800 250-8BITMIME 250-PIPELINING 250-AUTH PLAIN LOGIN 250-STARTTLS 250 HELP 2017-07-21 08:02:46 CLIENT -> SERVER: STARTTLS 2017-07-21 08:02:46 SERVER -> CLIENT: 220 TLS go ahead 2017-07-21 08:02:46 CLIENT -> SERVER: EHLO www.domain1.com 2017-07-21 08:02:46 SERVER -> CLIENT: 250-name.main-domain.com Hello www.domain1.com [22.22.22.222] 250-SIZE 52428800 250-8BITMIME 250-PIPELINING 250-AUTH PLAIN LOGIN 250 HELP 2017-07-21 08:02:46 CLIENT -> SERVER: AUTH LOGIN 2017-07-21 08:02:46 SERVER -> CLIENT: 334 V3KXzm5hbFU4 2017-07-21 08:02:46 CLIENT -> SERVER: b3KvyZ0ydEAxMNSefG5jb10= 2017-07-21 08:02:46 SERVER -> CLIENT: 334 UJEfc1djwiQ3 2017-07-21 08:02:46 CLIENT -> SERVER: bXExeRGdzwsNF2r 2017-07-21 08:02:48 SERVER -> CLIENT: 535 Incorrect authentication data 2017-07-21 08:02:48 SMTP ERROR: Password command failed: 535 Incorrect authentication data 2017-07-21 08:02:48 SMTP Error: Could not authenticate. 2017-07-21 08:02:48 CLIENT -> SERVER: QUIT 2017-07-21 08:02:48 SERVER -> CLIENT: 221 name.main-domain.com closing connection 2017-07-21 08:02:48 Connection: closed 2017-07-21 08:02:48 SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting Message was not sent.Mailer error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting 

Any idea why it authenticates when kicked off from www.main-domain.com versus www.domain1.com? The Host, Username and Password values are all the same whether I kick off an email from the back office (www.main-domain.com, logged into the domain1 DB) or a customer does from the site (www.domain1.com). Only the client is different. The server is the same. In both instances, it is trying to open a connection to smtp.domain1.com. The username and password values are the same but is failing in one instance and successful in the other.

The code that kicks off the PHPMailer is in the same function that is called whether it's from the back office or website.

Is this an SPF record issue or other DNS setting? Or maybe a server setting?

**Comment by Synchro** [comment]
It's not SPF because you're not getting as far as sending. DNS problems would probably be causing connection failures or timeouts, but it could be reverse DNS setup. You're connecting from an IP, and it's normal for the server to do a reverse lookup on your IP and check that it matches what you say in EHLO - which is going to fail for whichever of your servers don't match. That said, I'd expect this to fail earlier in the process if that was the problem. I suggest checking what it says in your mail server logs, as it may show more detail, and if necessary, increase the mail server's log level to show more info.
