### ISSUE TITLE
Can i send sms from php mailer ?

### ISSUE THREAD

**Issue by HaliAlduhoky** [PHPMailer/PHPMailer#1100]
as i read in this post that i can send Sms messages, i just want to be sure it is possible to do that via phpMailer?

https://code.tutsplus.com/tutorials/how-to-send-text-messages-with-php--net-17693

Thanks

**Comment by Synchro** [comment]
You can, but only if the carrier you're sending to has an email to SMS gateway, and they are generally not reliable or consistent. You're better off using an SMS provider directly, such as Clickatell.

**Comment by HaliAlduhoky** [comment]
so how can i know if is SMS gateway or not ?
i will send messages to more than 10 carriers !!

**Comment by Synchro** [comment]
That's another facet of the problem - you need to know the gateway address for every carrier you want to use. As I said, it's not consistent or reliable.
