### ISSUE TITLE
SMTP connect() failed - only with one Username

### ISSUE THREAD

**Issue by energy6uk** [PHPMailer/PHPMailer#1101]
This is a bit of a strange one. I have around five email addresses on the same domain. For the sake of this, we'll say the domain is **blablabla.com**. I am using phpmailer for emails that are sent out by my scripts, and everything was working great until a few weeks ago when my site visitors started complaining they were not getting confirmation emails. I conducted some testing, and soon discovered this was only happening with one of the five email addresses, the other four are still working fine. For example, sales@blablabla.com, support@blablabla.com, orders@blablabla.com and unrouted@blablabla.com are all working fine, but codes@blablabla.com is throwing the **SMTP connect() failed** error. Here is an example of one of my scripts;

$email_from = "codes@blablabla.com";
$email_body = "Hi.<br><br>
This is just an example of a mail script I use.<br><br>
Regards<br><br>
Energy6uk";

$mail = new PHPMailer();
$mail->IsSMTP();
$mail->Host = "blablabla.com";
$mail->SMTPAuth = true;
$mail->Username = "codes@blablabla.com";
$mail->Password = "correctpassword";
$mail->Port = 465;
$mail->SMTPSecure = "ssl";
$mail->SetFrom($email_from);
$mail->AddReplyTo($email_from);
$mail->ReturnPath = $email_from;
$mail->Subject = "Example Email";
$mail->MsgHTML($email_body);
$mail->AddAddress("email@recipient.com");
$mail->send();

If I use the above script with any of the other four email addresses, emails are sent out without issue. The **SMTP connect() failed** error only occurs with the **codes@blablabla.com** email address. The username and password is 100% correct, and I have performed a mailbox permissions repair, but the issue persists. I even tried deleting the codes@blablabla.com account in cPanel and then adding it again, but the problem is still there. Also, it's worth noting that I have no issues sending mail from any of my five addresses using PEAR mail.

This has me stumped. I hope someone can shed some light on this.

BR

Des

**Comment by Synchro** [comment]
Set `$mail->SMTPDebug = 2;` and look at what it says; post the output here if it's not obvious what the problem is.

**Comment by energy6uk** [comment]
```
2017-07-22 10:17:04	SERVER -> CLIENT: 220-server.blablabla.com ESMTP Exim 4.89 #1 Sat, 22 Jul 2017 11:17:04 +0100 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail. 2017-07-22 10:17:04	CLIENT -> SERVER: EHLO www.blablabla.com
2017-07-22 10:17:04	SERVER -> CLIENT: 250-server.blablabla.com Hello www.blablabla.com [111.111.111.111] 250-SIZE 52428800 250-8BITMIME 250-PIPELINING 250-AUTH PLAIN LOGIN 250-STARTTLS 250 HELP
2017-07-22 10:17:04	CLIENT -> SERVER: STARTTLS
2017-07-22 10:17:04	SERVER -> CLIENT: 220 TLS go ahead
2017-07-22 10:17:04	CLIENT -> SERVER: EHLO www.blablabla.com
2017-07-22 10:17:04	SERVER -> CLIENT: 250-server.blablabla.com Hello www.blablabla.com [111.111.111.111] 250-SIZE 52428800 250-8BITMIME 250-PIPELINING 250-AUTH PLAIN LOGIN 250 HELP
2017-07-22 10:17:04	CLIENT -> SERVER: AUTH LOGIN
2017-07-22 10:17:04	SERVER -> CLIENT: 334 xxx
2017-07-22 10:17:04	CLIENT -> SERVER: xxx
2017-07-22 10:17:04     SERVER -> CLIENT: 334 xxx
2017-07-22 10:17:04	CLIENT -> SERVER: xxx
2017-07-22 10:17:06	SERVER -> CLIENT: 535 Incorrect authentication data
2017-07-22 10:17:06	SMTP ERROR: Password command failed: 535 Incorrect authentication data
2017-07-22 10:17:06	SMTP Error: Could not authenticate.
2017-07-22 10:17:06	CLIENT -> SERVER: QUIT
2017-07-22 10:17:06	SERVER -> CLIENT: 221 server.blablabla.com closing connection
2017-07-22 10:17:06	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
```

**Comment by Synchro** [comment]
Well, that's the server saying it doesn't like your id or password. Given it works with your other IDs, I'm inclined to believe it.

**Comment by energy6uk** [comment]
I wish it was that simple. The username and password are 100% correct, and the very same details were working fine for several years with phpmailer, until a few weeks ago. The same details are working fine with PEAR mail, just not with phpmailer.

**Comment by Synchro** [comment]
Without your actual credentials I can't test it. If you base64-decode the credentials in the SMTP transcript (that you edited out) you will be able to see what is actually being sent. Beyond that, if you're sending the right creds and the server is rejecting it, it's not the client script's problem.

**Comment by energy6uk** [comment]
Already tried the base64-decode, and the details are 100% correct. Also, if the server was rejecting it, surely it would reject the same using PEAR mail? As I said at the beginning, it's a strange one. Anyway, thanks for trying to help.

**Comment by Synchro** [comment]
You'll have to check the server logs to be sure - you can probably get PEAR mail to show you an SMTP transcript too, then you can compare them.

**Comment by energy6uk** [comment]
Just wanted to update. I've found the cause of the issue, but it's actually left me even more confused. **WHM** (WebHost Manager) has a feature called **CPHulk Brute Force Protection**, and one of the settings is **Username-Based Protection** whereby a username is blocked for a specific period of time after a specific number of failed login attempts. Mine is set to block for 240 minutes after 10 failed login attempts. My codes@blablabla.com email account had been blocked by CPHulk after numerous failed attempts at login (obviously by hackers or whatever). This is where it becomes confusing. Even though my codes@blablabla.com email account had been blocked by CPHulk, I was still able to send emails through that account using PEAR mail. So anyway, this isn't a PHPMailer issue. Thanks for your help.

**Comment by Synchro** [comment]
Is PEAR mail sending via the mail function? If so, it would not be using any auth.
