### ISSUE TITLE
Mail Delivery Subsystem

### ISSUE THREAD

**Issue by vdanelia** [PHPMailer/PHPMailer#1103]
Hello need some suggestion or help....
I'm using PHPMailer 5.2.22
Mailer works very well sending the mails (users are registered), but if user registers the mail incorrectly (if made typo) I want to be informed by gmail's (Mail Delivery Subsystem).
**for example:** if I send incorrect mail from gmail, Mail Delivery Subsystem returns the mail back with message "Address not found", but if i register that mail via PHPMailer the gmail not informing me nothing. And that mail is successfully registered to the system...

I remember that when used PHPMailer older version (2.x.x) It did this...
Here is how I've configured the Mailer... maybe I've something wrong or just need to add something.

```
$mail = new PHPMailer();
$mail->CharSet = 'UTF-8';                             
$email->IsSMTP();
$mail->SMTPAuth = true;                
$mail->SMTPSecure = "tls";
$mail->Host       = "smtp.gmail.com";
$mail->Port       = 587; 
$mail->Username = "somemail@gmail.com";
$mail->Password = "somepasss";
$mail->From = "somemail@gmail.com";
$mail->FromName = 'frommysite';
$mail->AddAddress($email);
$mail->WordWrap = 80;
$mail->IsHTML(true);
$mail->Subject = 'Registration';
$mail->Body    = $message;
$mail->AltBody = $message;
$mail->Send();

```
Thank you In Advanced....

**Comment by Synchro** [comment]
See my answer to #1104. To handle delivery errors properly, you should also implement a bounce handler, though that's not something that PHPMailer can help with.

**Comment by vdanelia** [comment]
Thank you for the reply..
Can you give me a good example... according to mine?
