### ISSUE TITLE
Sending Problems...

### ISSUE THREAD

**Issue by vdanelia** [PHPMailer/PHPMailer#1104]
I have a site where users are registering, but some users are complaining that they registered, but the activation link was not sent..
When checked the system for registered users i fund that activation links were not sent.... then I copied that mails from the system and send  the activation links manually to them via gmail.com.. Everyone got the mail without any problem.

So can you explain what happening, in some cases phpmailsender can't send the mail.... some users able to register, but others can't..

Please, Help! or suggest what to do...

Here is how I've configured the Mailer... maybe I've something wrong or just need to add something.

```php
$mail = new PHPMailer();
$mail->CharSet = 'UTF-8';                             
$email->IsSMTP();
$mail->SMTPAuth = true;                
$mail->SMTPSecure = "tls";
$mail->Host       = "smtp.gmail.com";
$mail->Port       = 587; 
$mail->Username = "somemail@gmail.com";
$mail->Password = "somepasss";
$mail->From = "somemail@gmail.com";
$mail->FromName = 'frommysite';
$mail->AddAddress($email);
$mail->WordWrap = 80;
$mail->IsHTML(true);
$mail->Subject = 'Registration';
$mail->Body    = $message;
$mail->AltBody = $message;
$mail->Send();
```

Thank you In Advanced....

**Comment by Synchro** [comment]
If you look at the examples provided with PHPMailer, you'll see that they all check for errors when sending, like this:

```php
if(!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message has been sent';
}
```
You can look at `ErrorInfo` to see what the problem is. You can also check for validity of the email address they provide by looking at the return value from `addAddress()`:

```php
if (!$mail->addAddress($email)) {
    echo 'Invalid email address';
    exit;
}
```

Base your code on the gmail example provided with PHPMailer - it looks like you've used a very old version.

**Comment by vdanelia** [comment]
Can you give me a good example... according to mine?

**Comment by Synchro** [comment]
Here's [a whole folder full of examples](https://github.com/PHPMailer/PHPMailer/tree/master/examples).

**Comment by vdanelia** [comment]
I upploaded the final version of the phpmailer and testing it...
very strange thing... when using 
$mail->isSMTP();

not working, but if i delete it working.....
very strange

**Comment by vdanelia** [comment]
I replaced with the new version of phpmailer, but the same thing.......
not sending to some mails..... :(

**Comment by Synchro** [comment]
I have no chance of telling you what's wrong from the information you've given. Please read the documentation.
