### ISSUE TITLE
GMAIL SMTP ERROR

### ISSUE THREAD

**Issue by Neuroforge** [PHPMailer/PHPMailer#1106]
Hello.....

I am using the example GMAIL from the examples folder.....

I have done the follow also....

1) Changed the email address to my own.
2) Changed the password to that of my Gmail account
3) Allowed less secure applications for my Gmail account
4) Removed the HTML body and the attached image in the example (do not want do not need).
5) Added $mail->Body = "This is a message";

> 
> 2017-07-25 09:02:08 SERVER -> CLIENT: 220 smtp.gmail.com ESMTP w7sm23591357pfw.25 - gsmtp
> 2017-07-25 09:02:08 CLIENT -> SERVER: EHLO localhost
> 2017-07-25 09:02:09 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [203.97.127.128]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
> 2017-07-25 09:02:09 CLIENT -> SERVER: STARTTLS
> 2017-07-25 09:02:09 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
> 2017-07-25 09:02:09 CLIENT -> SERVER: EHLO localhost
> 2017-07-25 09:02:10 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [203.97.127.128]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
> 2017-07-25 09:02:10 CLIENT -> SERVER: AUTH LOGIN
> 2017-07-25 09:02:10 SERVER -> CLIENT: 334 VXNlcm5hbWU6
> 2017-07-25 09:02:10 CLIENT -> SERVER: am9obi5tcmRhbmllbC5iZWxsQGdvb2dsZW1haWwuY29t
> 2017-07-25 09:02:10 SERVER -> CLIENT: 334 UGFzc3dvcmQ6
> 2017-07-25 09:02:10 CLIENT -> SERVER: U3RldmU2NTQzMjE=
> 2017-07-25 09:02:11 SERVER -> CLIENT: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbvX534-5.7.14 y8COdcevk7ob6MUpJe60gRqqLSj7x2MpuGd0OdVqLF6tiW9mb8DZGnOTOQTf0NzwqzkC6C534-5.7.14 tgnQI2ATDjddDYtISjY12HSxNb7AlSKnZPFi9-k5Urg5CYtEFUrQUBPYtp81qCQqa2qGiw534-5.7.14 vOeFWDPmNdeEnslpu4Zp7cVjMYZ7-V2qB9j1NR6SFbA9a7z45rNMxWjfUtAbGZKSRu9g7V534-5.7.14 rKKQLoYCmUb-A7JrpwWiJL4dbQGxs> Please log in via your web browser and534-5.7.14 then try again.534-5.7.14 Learn more at534 5.7.14 https://support.google.com/mail/answer/78754 w7sm23591357pfw.25 - gsmtp
> 2017-07-25 09:02:11 SMTP ERROR: Password command failed: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbvX534-5.7.14 y8COdcevk7ob6MUpJe60gRqqLSj7x2MpuGd0OdVqLF6tiW9mb8DZGnOTOQTf0NzwqzkC6C534-5.7.14 tgnQI2ATDjddDYtISjY12HSxNb7AlSKnZPFi9-k5Urg5CYtEFUrQUBPYtp81qCQqa2qGiw534-5.7.14 vOeFWDPmNdeEnslpu4Zp7cVjMYZ7-V2qB9j1NR6SFbA9a7z45rNMxWjfUtAbGZKSRu9g7V534-5.7.14 rKKQLoYCmUb-A7JrpwWiJL4dbQGxs> Please log in via your web browser and534-5.7.14 then try again.534-5.7.14 Learn more at534 5.7.14 https://support.google.com/mail/answer/78754 w7sm23591357pfw.25 - gsmtp
> SMTP Error: Could not authenticate.
> 2017-07-25 09:02:11 CLIENT -> SERVER: QUIT
> 2017-07-25 09:02:11 SERVER -> CLIENT: 221 2.0.0 closing connection w7sm23591357pfw.25 - gsmtp
> SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
> Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

Of the above output, this looks like the issue......

> 2017-07-25 09:02:11 SMTP ERROR: Password command failed: 534-5.7.14 

however i have checked and DOUBLE checked that the password is indeed correct.

If i put in the INCORRECT password the error changes to the following.....

2017-07-25 09:05:45 SMTP ERROR: Password command failed: 535-5.7.8 Username and Password not accepted. Learn more at535 5.7.8 https://support.google.com/mail/?p=BadCredentials l4sm25300835pgr.21 - gsmtp
SMTP Error: Could not authenticate.

So the details seem right and this is just being a pain.....

Any help here would be greatly appreciated..... I am frustrated and i hate PHP. I just want to make a contact form.... why is this so hard?

Regards,

Daniel

**Comment by Synchro** [comment]
Blaming PHP isn't going to help you if you can't be bothered to even read the error message right in front of you:

```
Please log in via your web browser and534-5.7.14 then try again.534-5.7.14 Learn more at534 5.7.14 https://support.google.com/mail/answer/78754 w7sm23591357pfw.25 - smtp
```

**Comment by Neuroforge** [comment]
Also, that didn't work. The error message is the same.

1) I logged out of GMAIL.
2) I logged back into GMAIL.
3) I attempted to call the PHP script again.

And also - https://support.google.com/mail/answer/78754 w7sm23591357pfw.25 cannot be found.

What is your next piece of advice?

Thanks.

**Comment by Synchro** [comment]
Contact gmail or check their docs - it's their policy that's keeping you out, not your script. You could try using OAuth rather than passwords, though make sure you use the [PHPMailer 6.0 branch](https://github.com/PHPMailer/PHPMailer/tree/6.0) for that, and read the project wiki. It's horribly complicated to set up (because it's OAuth), but has fewer constraints at gmail's end.

**Comment by Neuroforge** [comment]
Thank you for your help. I will post a resolution here if i find one.

**Comment by imlolman** [comment]
I have also done the same
Changed the email, password to mine
Allowed less secure applications for my Gmail account
Removed the HTML and $mail->Body = "This is a message";
**Still Getting Error** Using it in Laravel 5.4

> 2017-11-06 21:12:51 SERVER -> CLIENT: 220 smtp.gmail.com ESMTP h1sm23026103pgf.37 - gsmtp
> 2017-11-06 21:12:51 CLIENT -> SERVER: EHLO localhost
> 2017-11-06 21:12:52 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [47.247.13.31]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
> 2017-11-06 21:12:52 CLIENT -> SERVER: STARTTLS
> 2017-11-06 21:12:52 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
> 2017-11-06 21:12:52 CLIENT -> SERVER: EHLO localhost
> 2017-11-06 21:12:52 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [47.247.13.31]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
> 2017-11-06 21:12:52 CLIENT -> SERVER: AUTH LOGIN
> 2017-11-06 21:12:53 SERVER -> CLIENT: 334 VXNlcm5hbWU6
> 2017-11-06 21:12:53 CLIENT -> SERVER: emlwcHlmZWVkbXVtYmFpQGdtYWlsLmNvbQ==
> 2017-11-06 21:12:53 SERVER -> CLIENT: 334 UGFzc3dvcmQ6
> 2017-11-06 21:12:53 CLIENT -> SERVER: WmlwcHlQYXNzd29yZA==
> 2017-11-06 21:12:53 SERVER -> CLIENT: 534-5.7.9 Please log in with your web browser and then try again. Learn more at534 5.7.9 https://support.google.com/mail/?p=WebLoginRequired h1sm23026103pgf.37 - gsmtp
> 2017-11-06 21:12:53 SMTP ERROR: Password command failed: 534-5.7.9 Please log in with your web browser and then try again. Learn more at534 5.7.9 https://support.google.com/mail/?p=WebLoginRequired h1sm23026103pgf.37 - gsmtp
> SMTP Error: Could not authenticate.
> 2017-11-06 21:12:53 CLIENT -> SERVER: QUIT
> 2017-11-06 21:12:53 SERVER -> CLIENT: 221 2.0.0 closing connection h1sm23026103pgf.37 - gsmtp
> SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
> Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
Do what it says in the guide - do the display unlock captcha thing. This is a gmail problem, not a PHPMailer problem.
