### ISSUE TITLE
Mails not arriving on outlook

### ISSUE THREAD

**Issue by woeterman94** [PHPMailer/PHPMailer#1107]
I tried the normal sendmail() and the SMTP mailer , but my mails are not arriving on @outlook.com or @hotmail.com email addresses. 

It is working for gmail (and i think other email domains too...) but sending to outlook does not seem to work.

**Comment by Synchro** [comment]
You need to determine if your messages are not arriving or not being sent - there's a big difference. You also need to provide more detail - base your code on the examples provided, follow the troubleshooting guide, read your mail server logs.
