### ISSUE TITLE
Message Isn't Authenticated!

### ISSUE THREAD

**Issue by vdanelia** [PHPMailer/PHPMailer#1108]
I configured PHPMailer, now working properly sending mails... 
But I nociced a strange thing.. 
when I send mail from my website contact form (contact@mydomain.com) to a gmail there is the question mark next to the sender's name saying: (Message Isn't Authenticated).
if I send mail from gmail (contact@mydomain.com) it is Authenticated..

Do I need to add something ?

P.S. mydomain.com is authenticated in google postmasters

Thanks in advanced...

**Comment by Synchro** [comment]
I don't know - perhaps you should sign with DKIM?
