### ISSUE TITLE
Add multiple attachments in mail

### ISSUE THREAD

**Issue by infinity001** [PHPMailer/PHPMailer#1112]
Hello.

I try to integrate PHPMailer with PHPRunner to send mail with attachments. Sending mails works with values from fields, but if I use AddAttachment, it doesnt works. Here is example:

`
require ("./mail/PHPMailerAutoload.php");

$mail = new PHPMailer;

//$mail->SMTPDebug = 1;                               // Enable verbose debug output

$mail->isSMTP();                                      // Set mailer to use SMTP
$mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'test@gmail.com';                 // SMTP username
$mail->Password = 'pass';                           // SMTP password
$mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 587;                                    // TCP port to connect to
$mail->SMTPDebug = 0;

$mail->setFrom('test@gmail.com', 'Mailer');
$mail->addAddress('test@gmail.com', 'Joe User');     // Add a recipient
$mail->addAddress('test@gmail.com');               // Name is optional
$mail->addReplyTo('test@gmail.com', 'Information');
$mail->addCC('test@gmail.com');
$mail->addBCC('test@gmail.com');

$mail->isHTML(true);                                  // Set email format to HTML

while( $data = $button->getNextSelectedRecord() ) //get values from selected records on list

{ 

$fileArray = my_json_decode($values["Field that stores attachments"]);

$attachments = array();

$msg = "";

foreach($fileArray as $f)

{

  $attachments[] = array("path" => $f["name"]);

} 

$mail->Body    = '<b>Test:!</b></br>'
.'Name: '.$data['value_from_field'] .'</br>';

$mail->AddAttachment .=$attachments;

}

$mail->Subject = 'Here is the subject';

$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

 

// if error happened print a message on the web page

if(!$mail->send())

{

  $errmsg = "Error happened: <br>";

  $errmsg.= "File: " . $arr["errors"][0]["file"] . "<br>";

  $errmsg.= "Line: " . $arr["errors"][0]["line"] . "<br>";

  $errmsg.= "Description: " . $arr["errors"][0]["description"] . "<br>";

  $result["txt"] = $errmsg;

} 
else
{$result["txt"] = "Emails were sent.";

}

`

It sends mail but not attachment. For attachement, it only returns value "Array", not name of file that is/are attached

Thanks

**Comment by Synchro** [comment]
You're using `addAttachment` entirely wrong! It's a method that expects to be passed a string containing a path to a file. It's not a string property that you can append random stuff to. Take a look at the [send_file_upload example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/send_file_upload.phps) provided with PHPMailer, and read the docs on the `addAttachment` method (link to docs is on the project home page & readme file). Like this:

    $mail->addAttachment('/path/to/file');
