### ISSUE TITLE
Cannot send URL links

### ISSUE THREAD

**Issue by danydacosta** [PHPMailer/PHPMailer#1119]
Hello,

I'm sending emails as HTML using the `$mail->Body = $body`. `$body` contains about 350 rows of HTML code. ? have a problem with a `<a>` tag. It's a simple confirm link :

`<a style=\"color:#FFFFFF; text-decoration:none; font-family:Helvetica,Arial,sans-serif; font-size:20px; line-height:135%;\" href=\"https://confirm.php\">Confirmation</a>`

But when I try to send, PHPMailer give me this error:

`Mailer Error: SMTP Error: data not accepted.SMTP server error: DATA END command failed Detail: Spam message rejected SMTP code: 550`

After some hours trying to figuring out the problem, I found that it was the link inside the href parameter. If I remove him (`href=\"\"`), the email successfully sends.

Below is the script that I use in order to send emails using PHPMailer:

```
<?php
/**
 * This example shows sending a message using a local sendmail binary.
 */
date_default_timezone_set('Europe/Zurich');
require '../vendor/vendor/phpmailer/phpmailer/PHPMailerAutoload.php';
//Create a new PHPMailer instance
$mail = new PHPMailer();
//Tell PHPMailer to use SMTP
$mail->isSMTP();
$mail->Timeout = 60;
//Enable SMTP debugging
// 0 = off (for production use)
// 1 = client messages
// 2 = client and server messages
$mail->SMTPDebug = 2;
//Ask for HTML-friendly debug output
$mail->Debugoutput = 'html';
//Set the hostname of the mail server
$mail->Host = "mail.provider.ch";
//Set the SMTP port number - likely to be 25, 465 or 587
$mail->Port = 25;
//Whether to use SMTP authentication
$mail->SMTPAuth = true;
//Username to use for SMTP authentication
$mail->Username = "email@my-domain.ch";
//Password to use for SMTP authentication
$mail->Password = "pass";
//Set who the message is to be sent from
$mail->setFrom('email@my-domain.ch', 'Adresse-mail.ch validation');
//Set who the message is to be sent to
$email="another-email@my-domain.ch";
$mail->addAddress($email, 'Foo Bar');
//Set the subject line
$mail->Subject = 'Validation adresse-mail.ch';
//Below is the script where I set $body
include('mail_content.php');
$mail->CharSet = 'UTF-8';
$mail->IsHTML(true);
$mail->Body = $body;


//Send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}
?>

```

Am I missing something? I've been struggling since hours now...

**Comment by Synchro** [comment]
Your code looks fine. Your URL (`https://confirm.php`) looks like it might be malformed? Did you edit out the domain for this issue?

Assuming you did, first check if it's a general block on links. Build a very simple body that contains a link to somewhere obviously benign, like:

```html
<html>
<head><title>Title</title></head>
<body>
    <a href="https://google.com">Google</a>
</body>
</html>
```

If that works, you know there is not a general block on all links. If it doesn't work, complain to your ISP's support as that's a ridiculous restriction.

Next replace the link URL with one of your own. If that is rejected, you know that it's links to your particular site it doesn't like.

If that does work, replace all the links in your big template with the google link. If that works, you know that they don't like your content, not just your links.

Keep going like this until you figure out exactly what it doesn't like.

**Comment by danydacosta** [comment]
Indeed my URL was an example. It seems to be my HTML template as

```
<html>
<head><title>Title</title></head>
<body>
    <a href="https://google.com">Google</a>
</body>
</html>
```

works well. It's very weird. `href=\"https://google.com\"` is the only thing that give a `SMTP Error: data not accepted` exception.

**Comment by Synchro** [comment]
I suggest you contact your ISP - it's their filter that's doing this.
