### ISSUE TITLE
List-Unsubscribe unclosed tag in email

### ISSUE THREAD

**Issue by NaveNO** [PHPMailer/PHPMailer#1120]
Hi. I am having huge problems with PHPMailer, especially with List-Unsubscribe header. Here are my headers:
```
$mailer->AddCustomHeader("List-Unsubscribe: <mailto:support@rosresurs.net?subject=Unsubscribe>, <http://rosresurs.net/unsubscribe.php?email=$email>");
$mailer->AddCustomHeader("Precedence: bulk"); 
```

This is alright, until I get this in my email:

```
>
Precedence: bulk
MIME-Version: 1.0
Content-Type: multipart/alternative;
        boundary="b1_7a22aaca093016aea09bfb0be033055b"
Content-Transfer-Encoding: 8bit

This is a multi-part message in MIME format.

--b1_7a22aaca093016aea09bfb0be033055b
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Here is my test text of the email. Just nothing special yeyeye. Bye!
```

So as you can see there is like unclosed tag of something at the top of email body. As you see there is Precedence: bulk and before it there is List-Unsubscribe. So the problem is with it. How can I fix this? Thanks!

**Comment by Synchro** [comment]
Can you post the rest of the headers before that point? What is in `$email`?

**Comment by NaveNO** [comment]
The are no more custom headers in php script. $email contains actual email. Like example@gmail.com

**Comment by NaveNO** [comment]
Maybe some mysqli_escape_string may help? Or maybe some quotes are missing? Or it’s actual PHPMailer fault?

**Comment by Synchro** [comment]
I can't tell if you don't show me exactly what's there! FWIW, I use the same thing in PHPMailer and have no trouble. What context are you viewing this in? It's not normal for anything with an email header to be displayed in an HTML context, that is, an RFC822 message is not valid HTML.

**Comment by NaveNO** [comment]
I can upload email source and actual script to site, so you will see anything you need. Okay?

**Comment by Synchro** [comment]
Just post it here, change your email addresses in it.

**Comment by NaveNO** [comment]
Here is email source: (php script in next comment in 2 minutes):
Delivered-To: kildishov.vladislav@gmail.com
Received: by 10.80.139.1 with SMTP id l1csp2250868edl;
        Sat, 5 Aug 2017 11:58:38 -0700 (PDT)
X-Received: by 10.107.24.66 with SMTP id 63mr6444297ioy.111.1501959518024;
        Sat, 05 Aug 2017 11:58:38 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1501959517; cv=none;
        d=google.com; s=arc-20160816;
        b=ceh41eTpcfTOHCGFwBGhRtif8OlhcARXrLaDpL+eRuroyzOvpz3R0G9/qNPvITHRb2
         yhbQJVizJMhb2FfyN5bpWAigDMg6GiDyhlVRBFP6cWeRZngVP6dEd2t188m1iBMWg4+n
         z8qA+yucFt8BBNwxa8vyHDEHWaph4XZy4foN44OD3LurLItTnCImLPmSgA/vdZ+4lpIA
         fPjbhPRz3TArRlRdgMdz26kmNeFMi5QiO1e4nETIH8QhJv00dcGFkeWdr1AGUiF2c+ET
         bSZZM2z+P9NRk8ersUp0XXn6KqUJGD4VQhCm+dPIIgOYIYXK5+LOnsTdq1mxfAhodfHu
         FCYA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:message-id:reply-to:from:date:subject:to
         :dkim-signature:arc-authentication-results;
        bh=rjEHIxNcrw+8/39mek0BvpjNlQxQYXce0aGP2+soexQ=;
        b=fCEFmiGf70AAvbhZKbP8RQUK0Xcoj9C6erKtsvnkubIT76Bcir3aAsPNgpLWCkdgNV
         mz/Giv1IzGnUuBI8G8J4LpbZ969+Wt8BMVIqGN3jZOf/j4cpTo4ynaQ1NS6+eBcs2ki4
         +/0nfZ0rNWj2yNQR0RXv6Yxfc42DNAAAYrhddG4X5Q3gvVpBtnecIorJnHLY9rPoxjBT
         p3aG4QtNs91JhBshfZxwQ2dQAlrj/lAS1F2com+LAnko5cmHXAnk6DTqPE9c7LfnpV4x
         bekQQclN56D5twhU0qJ2XOUyifCO0M5/XuT1+u7ABwDWImZaHuaO+0ZEIxvqHlIv6czf
         nu3A==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@rosresurs.net header.b=CxM36SZj;
       spf=softfail (google.com: domain of transitioning team@rosresurs.net does not designate 2a01:4f8:120:61a9::2 as permitted sender) smtp.mailfrom=team@rosresurs.net;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=rosresurs.net
Return-Path: <team@rosresurs.net>
Received: from rosresurs.net ([2a01:4f8:120:61a9::2])
        by mx.google.com with ESMTPS id m34si4328296iod.388.2017.08.05.11.58.37
        for <kildishov.vladislav@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Sat, 05 Aug 2017 11:58:37 -0700 (PDT)
Received-SPF: softfail (google.com: domain of transitioning team@rosresurs.net does not designate 2a01:4f8:120:61a9::2 as permitted sender) client-ip=2a01:4f8:120:61a9::2;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@rosresurs.net header.b=CxM36SZj;
       spf=softfail (google.com: domain of transitioning team@rosresurs.net does not designate 2a01:4f8:120:61a9::2 as permitted sender) smtp.mailfrom=team@rosresurs.net;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=rosresurs.net
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed;
	d=rosresurs.net; s=mail; h=List-Unsubscribe:Message-ID:Reply-To:From:Date:
	Subject:To:Sender:Cc:MIME-Version:Content-Type:Content-Transfer-Encoding:
	Content-ID:Content-Description:Resent-Date:Resent-From:Resent-Sender:
	Resent-To:Resent-Cc:Resent-Message-ID:In-Reply-To:References:List-Id:
	List-Help:List-Subscribe:List-Post:List-Owner:List-Archive;
	bh=rjEHIxNcrw+8/39mek0BvpjNlQxQYXce0aGP2+soexQ=; b=CxM36SZjanvY5dQOyfrf47uo2s
	a9S3d++jCi+6VJ0D+T/TQXxKCBmUEBRlbq4T6VIxd7prqbt5K527yRNR8cdkc8cKQx/9yBb7E6pg/
	aNGqYjrC5Co6MqdmclQsJzsq9wPVgD88nG6jMaPMEVLNXzci7CmArPE69yyUqCZ8miQGTYzvsMJNe
	NOEPAOpf4S2xD4Tr53/67Wfxg275umBy5qFjqF0mtLDZxRul54KjTCibZUEYWFeVMifcClue5U5vr
	oeZ1TZg8nM27qq0FSussgwHlKnjertpTmi4SfsvXDvbegTdVK1+E5aqIE2NGg68Pfor7OuKUIFh9M
	uXH2dEZA==;
Received: from root by rosresurs.net with local (Exim 4.89)
	(envelope-from <team@rosresurs.net>)
	id 1de4HU-0008Pg-Ef
	for kildishov.vladislav@gmail.com; Sat, 05 Aug 2017 20:58:36 +0200
To: "Kildishov.vladislav" <kildishov.vladislav@gmail.com>
Subject: =?UTF-8?B?0JLQsNGBINC/0YDQuNCy0LXRgtGB0YLQstGD0LXRgiDQoNC+0YHRgNC10YE=?=  =?UTF-8?B?0YPRgNGBIQ==?=
X-PHP-Originating-Script: 0:class.phpmailer.php
Date: Sat, 5 Aug 2017 18:58:36 +0000
From: "Rosresurs1.ru" <team@rosresurs.net>
Reply-To: =?UTF-8?B?0KHQstGP0LfQsNGC0YzRgdGPINGBINC90LDQvNC4?= <reply@rosresurs.net>
Message-ID: <b24b5b0a93e2d4e71e73a210cd03fff8@rosresurs.net>
X-Priority: 3
List-Unsubscribe: <mailto:support@rosresurs.net?subject=Unsubscribe>, <http://rosresurs.net/unsubscribe.php?email=kildishov.vladislav@gmail.com

>
Precedence: bulk
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="b1_b24b5b0a93e2d4e71e73a210cd03fff8"
Content-Transfer-Encoding: 8bit

This is a multi-part message in MIME format.

--b1_b24b5b0a93e2d4e71e73a210cd03fff8
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit


Добрый день, строите дом? У нас есть кое-что для Вас !

Мы являемся официальными дилерами заводов-изготовителей автономных канализаций: Биодека, Эко-гранд и Юнилос Астра. Хотели бы предложить Вам сотрудничество и поработать с Вами в качестве надежных поставщиков и установщиков автономных канализаций BioDeka для Ваших объектов.
Специально для строительных компаний мы разработали систему мотивации для менеджеров по продажам, механика данной акции во вложении!
СУТЬ АКЦИИ: за каждую проданную станцию BioDeka с монтажом, менеджер получает денежное вознаграждение по результатам месяца из расчета: 1 станция = 3000 руб. 
Доп. мотивация по результатам квартала 3 мес.: ПУТЕВКА НА 2 человека на 5 дней в Тайланд, Италию, Испанию, и др. страны на выбор лучшему менеджеру!
 В случае Вашей заинтересованности в сотрудничестве и интересу к акции, мы бы могли обсудить ее условия вместе с Вами! 
Количество участников в акции «Личный зачет» ограниченно. Заявки на участие принимаются до 07 августа 2017. После этой даты, заявки на участие согласовываются со мной в индивидуальном порядке!

Группа компаний Росресурс
Малинин Евгений Валерьевич
Директор по снабжению строительных объектов
Rosresurs1.ru
БЦ «Мир», г. Санкт-Петербург, ул. Ефимова 4А, офис 416.
+7 812 915 26 64
+7 931 354 73 21


--b1_b24b5b0a93e2d4e71e73a210cd03fff8
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit


<html>
<head>
<title>Приветствуем!</title>
</head>
<body>
<h2>Добрый день, строите дом? У нас есть кое-что для Вас !</h2><br />
<p>Мы являемся официальными дилерами заводов-изготовителей автономных канализаций: Биодека, Эко-гранд и Юнилос Астра. Хотели бы предложить Вам сотрудничество и поработать с Вами в качестве надежных поставщиков и установщиков автономных канализаций BioDeka для Ваших объектов.<br />
Специально для строительных компаний мы разработали систему мотивации для менеджеров по продажам, механика данной акции во вложении!<br />
СУТЬ АКЦИИ: за каждую проданную станцию BioDeka с монтажом, менеджер получает денежное вознаграждение по результатам месяца из расчета: 1 станция = 3000 руб. <br />
Доп. мотивация по результатам квартала 3 мес.: ПУТЕВКА НА 2 человека на 5 дней в Тайланд, Италию, Испанию, и др. страны на выбор лучшему менеджеру!<br />
 В случае Вашей заинтересованности в сотрудничестве и интересу к акции, мы бы могли обсудить ее условия вместе с Вами! <br />
Количество участников в акции «Личный зачет» ограниченно. Заявки на участие принимаются до 07 августа 2017. После этой даты, заявки на участие согласовываются со мной в индивидуальном порядке!</p><br />
<p>Группа компаний Росресурс<br />
Малинин Евгений Валерьевич<br />
Директор по снабжению строительных объектов Rosresurs1.ru <br />
БЦ «Мир», г. Санкт-Петербург, ул. Ефимова 4А, офис 416.<br />
+7 812 915 26 64 <br />
+7 931 354 73 21 <br />
<br />
Администрация</p>
</body>
</html>

**Comment by NaveNO** [comment]
Php script(if you need mail text and html templates-write me):
<?php 

set_time_limit(0); 

require_once('config.php');
require_once('lib/MailClass.php');
require_once('etheme.php');

$mailer = new FreakMailer(true);
$mailer->CharSet = 'UTF-8';

$conn = new mysqli("localhost", "root", "lalalalala", "email1");

$sql = mysqli_query($conn, "SELECT email FROM email WHERE 1 && sent=''");

while($row = mysqli_fetch_object($sql))
{
	$promo = "строите дом? У нас есть кое-что для Вас";
	$email = $row->email;

	$humanname = explode("@", $email);
	$newhumanname = ucfirst($humanname[0]);

	$mailer->Subject  = 'Вас приветствует Росресурс!';
	$mailer->Body = str_replace('{PROMO}', $promo, $htmlBody);

	$mailer->IsHTML(true);
	$mailer->AltBody = str_replace('{PROMO}', $promo, $textBody);  

	$mailer->AddAddress($row->email, $newhumanname);
	$mailer->AddReplyTo($site['reply_email'], 'Связаться с нами');
	$mailer->AddCustomHeader("List-Unsubscribe: <mailto:support@rosresurs.net?subject=Unsubscribe>, <http://rosresurs.net/unsubscribe.php?email=$email>");
	$mailer->AddCustomHeader("Precedence: bulk");       
	$mailer->XMailer = ' ';

	if($mailer->Send()) {
		mysqli_query($conn,"UPDATE email SET sent='yes' WHERE email='$email'");
		echo "Письмо отправлено. Имя клиента: $newhumanname и email: $email\n";
	}
	else {
		echo "Письмо не отправлено! Причина: " . $mailer->ErrorInfo;
	}


	$mailer->clearAddresses();
	$mailer->clearCustomHeaders();
	$mailer->clearAttachments();

}


?>

**Comment by Synchro** [comment]
You have edited out the critical part!

    $mailer->AddCustomHeader("List-Unsubscribe: , ");

In your example message it looks like the email address you are appending to your unsubscribe URL contains line breaks. It's not a general problem with `addCustomHeader` because your `Precedence` header is not doing it. Try setting the value explicitly and compare the result:

    $mailer->AddCustomHeader("List-Unsubscribe: <mailto:support@rosresurs.net?subject=Unsubscribe>,<http://rosresurs.net/unsubscribe.php?email=kildishov.vladislav@gmail.com>');

If this produces a different result, then you the problem is with the contents of `$email`. Also note that when an email address is inserted arbitrarily in a header like this, it does not get validated, so I suggest you trim and validate it manually first, for example:

    $email = trim($email);
    if (PHPMailer::validateAddress($email)) {
        $mailer->AddCustomHeader(...

**Comment by NaveNO** [comment]
I decided to migrate from email in unsubscribe to tokens. Is it good idea?

**Comment by Synchro** [comment]
I prefer tokens because they can't be spoofed, but it shouldn't make any difference to the way this header is formatted.

**Comment by NaveNO** [comment]
![image](https://user-images.githubusercontent.com/13716167/29001216-8dccde14-7a8b-11e7-81ba-6258cc11b8b4.png)
This is a new variant. Will it work?

**Comment by Synchro** [comment]
Try it and see, no reason it shouldn't.

**Comment by NaveNO** [comment]
Yep, it worked. Thanks for fast response!
