### ISSUE TITLE
Support SVG images and multiple AddEmbeddedImages

### ISSUE THREAD

**Issue by gusbemacbe** [PHPMailer/PHPMailer#1121]
> @Synchro 
> While I'm here, there's nothing preventing you from adding any file type as an "embedded image", but whether it will be displayed well is entirely up the client app, not PHPMailer. You will need to specify a MIME type manually; I've just added the SVG MIME type to PHPMailer 6.0, and it is image/svg+xml.

```
$email->AddEmbeddedImage("imagens/icones/phpmailer.png", "phpmailer", "phpmailer.png");
$email->AddEmbeddedImage("imagens/icones/atom.png", "atom", "atom.png");
$email->AddEmbeddedImage("imagens/icones/materialize.png", "materialize", "materialize.png");
...
```
Is it wrong?

How do you do it, using SVG and MIME?

**Comment by Synchro** [comment]
Just the same way, but specify the MIME type:

    $email->AddEmbeddedImage("imagens/icones/logo.svg", "logo", "logo.svg", 'base64', 'image/svg+xml');

It's up to you to reference the `cid` in your HTML message body.

**Comment by gusbemacbe** [comment]
And is the multiple is wrong or right?

**Comment by Synchro** [comment]
Yes, they are all correct.

**Comment by gusbemacbe** [comment]
I still use PHPMailer 5. Do I need to update to 6?

So, I've just tested, the SVG files do not load. But it added attachments.

![screen shot 2017-08-07 at 09 58 22](https://user-images.githubusercontent.com/2257024/29027417-033209c4-7b57-11e7-8826-f9fde9541ed5.png)

```
$email->AddEmbeddedImage("imagens/icones/phpmailer.svg", "phpmailer", "phpmailer.svg", 'base64', 'image/svg+xml');
 $email->AddEmbeddedImage("imagens/icones/heart.svg", "heart2", "heart2.svg", 'base64', 'image/svg+xml');

...

  <img alt=\"heart\" 
       src=\"cid:heart2\" 
       style=\"height: 25px; padding-right: 5px\"
       title=\"Feito com meu coração\">,
...

   <a href=\"https://github.com/PHPMailer/PHPMailer\">
   <img alt=\"PHP Mailer\" 
        src=\"cid:phpmailer\" 
        style=\"height: 25px; padding-right: 5px\"
        title=\"PHP Mailer\">
   </a>
```

**Comment by Synchro** [comment]
Well as I said, whether SVGs are displayed depends on your mail client app. As far as I know, most do not render SVG, but see [this question](https://stackoverflow.com/questions/5681562/svg-image-not-showing-in-html-email) for more info - you may need to build it as an `object` tag as well.  Some email clients will display inline images as attachments as well as displaying them.

**Comment by gusbemacbe** [comment]
I decided to switch to JPEG or PNG, but it loaded only one of two images.

**Comment by Synchro** [comment]
iOS Mail is known to have bugs involving multiple attachments.

**Comment by codersaiful** [comment]
Same issue. I also added one more jpg image, but showing only one image in mail. what can I do?

**Comment by gusbemacbe** [comment]
It depends on browser and client mail you were testing.
