### ISSUE TITLE
how to remove “via” and server name when sending emails

### ISSUE THREAD

**Issue by vdanelia** [PHPMailer/PHPMailer#1122]
Hello please help..

when mail is sent by phpmailer the recipient sees "send via server / host name"
how to disable or remove this
(using gmail smtp)

Thank you in advanced

**Comment by Synchro** [comment]
You need to set up SPF, and ideally sign your messages with DKIM (which [PHPMailer can do](https://github.com/PHPMailer/PHPMailer/blob/master/examples/DKIM.phps)). See [Google's notes on the subject](https://support.google.com/mail/answer/1311182?hl=en).

**Comment by vdanelia** [comment]
Thanks 
I turned on mail authentication dkim in gmail admin... so have to wait 48 hours for dns refresh... and then will try this new config with dkim....
