### ISSUE TITLE
Message could not be sent. Mailer Error: Could not instantiate mail function

### ISSUE THREAD

**Issue by saimguptagkp** [PHPMailer/PHPMailer#1124]
this is my code
<?php 
require('PHPMailerAutoload.php');
//include('class.phpmailer.php');
//require("class.smtp.php");
	if (isset($_POST['send'])) {
		$name=$_POST['name'];
		$email=$_POST['email'];
		$phone=$_POST['phone'];
		$message=$_POST['message'];
	}
$mail = new PHPMailer;
//$mail->SMTPDebug = 3;

//$admin_email="proyotech@gmail.com";

$mail->setFrom($email, $name);
$mail->addAddress("svkdatt@gmail.com", 'Proyo Technologies');     // Add a recipient

$mail->addReplyTo($email, $name);

$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'this is subject part';
$mail->Body    = "<strong>".$name."</strong>"."<br>".$phone."<br>".$email."<br>".$message;
$mail->AltBody = 'nice job';

if(!$mail->send()) {
    echo 'Message could not be sent. ';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    header("Location: http://www.digitalseocompany.in/demo/index.php"); /* Redirect browser */
exit();
}

 ?>
and this is my result: Message could not be sent. Mailer Error: Could not instantiate mail function.
on server

**Comment by Synchro** [comment]
Please make sure you're running the latest version, base your code on the examples provided, and [read the documentation](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting) (which covers this exact error).
