### ISSUE TITLE
How to log all sent emails ?

### ISSUE THREAD

**Issue by rwrocket** [PHPMailer/PHPMailer#1128]
My emails are being sent but I seem to be missing any logging of emails sent to external gateway using PHPMailer

Can you assist on how I would setup logging for all emails sent from PHPMailer scripts.

**Comment by r0073rr0r** [comment]
if(!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
//put error in WS error.log
    error_log('Mailer Error: ' . $mail->ErrorInfo);
} else {
    echo 'Message has been sent';
    error_log('Message has been sent to '.$someVarThatDetermineRecipientAddr,'somefilewhereto.log');
}

**Comment by Synchro** [comment]
You can do that, but if you want SMTP-level logging, set `SMTPDebug = 2` and then look at what you can do with the [`Debugoutput` property](http://phpmailer.github.io/PHPMailer/classes/PHPMailer.html#property_Debugoutput): set it to a function that formats and logs the output however you like.
