### ISSUE TITLE
[5.2.7] Class SMTP not found 

### ISSUE THREAD

**Issue by M-Falken** [PHPMailer/PHPMailer#113]
Hi
just test the very last 5.2.7 (#112 included) and got the error:
PHP Fatal error:  Class 'SMTP' not found in ./lib/phpmailer/class.phpmailer.php on line 1147

But I have the PHPMailerAutoload.php on the directory, so I wonder what is wrong here, I've seen that now because of the autoload, the require class.smtp.php is gone so perhpas this is the issue.....some advice on this please ?

thanks
regards

**Comment by CoAmA** [comment]
I have the following code:
require("PHPMailer-master/PHPMailerAutoload.php");

$mail = new PHPMailer();

$mail->IsSMTP();  // telling the class to use SMTP
$mail->Host     = "mx.000webhost.com"; // SMTP server
$mail->SMTPDebug  = 1;
$mail->SMTPAuth  = true;$mail->SMTPSecure = "tls";
$mail->Username  = 'coama@manes-workshop.webatu.com';
$mail->Password  = 'bunica2';

$mail->From     = "coama@manes-workshop.webatu.com";
$mail->AddAddress("alexandrubogdan.iatan@gmail.com");

$mail->Subject  = "First PHPMailer Message";
$mail->Body     = "Hi! \n\n This is my first e-mail sent through PHPMailer.";

if(!$mail->Send()) {
  echo 'Mailer error: ' . $mail->ErrorInfo;
} else {
  echo 'Message has been sent.';
}

but it prints the error:
2015-02-13 04:51:33	CLIENT -> SERVER: EHLO manes-workshop.webatu.com 
2015-02-13 04:51:33	CLIENT -> SERVER: AUTH LOGIN 
2015-02-13 04:51:33	CLIENT -> SERVER: Y29hbWFAbWFuZXMtd29ya3Nob3Aud2ViYXR1LmNvbQ== 
2015-02-13 04:51:33	CLIENT -> SERVER: YnVuaWNhMg== 
2015-02-13 04:51:33	CLIENT -> SERVER: MAIL FROM: 
2015-02-13 04:51:33	CLIENT -> SERVER: RCPT TO: 
2015-02-13 04:51:33	SMTP ERROR: RCPT TO command failed: 554 5.7.1 : Relay access denied 
2015-02-13 04:51:33	CLIENT -> SERVER: QUIT 
2015-02-13 04:51:33	SMTP Error: The following recipients failed: alexandrubogdan.iatan@gmail.com

what am i doing wrong?

**Comment by Synchro** [comment]
* Use the latest PHPMailer - you're using an old version.
* Follow the example code provided with PHPMailer (use the gmail example) - your code is missing parts and it's easier to start with good code than point out your problem.
* Don't hijack threads.

**Comment by Markandeshwar** [comment]
Hi Synchro,
      I am using following code to send email... it is showing message sent but not receiving mail in inbox... other problem is after executing code i am getting email from gmail that your account has been  blocked because sign-in attempt... please do needful in resolving this issue...

<?php
	require_once('PHPMailer\PHPMailerAutoload.php');
	$mail = new PHPMailer();  // create a new object
	$mail->IsSMTP(); // enable SMTP
	$mail->SMTPDebug = 0;  // debugging: 1 = errors and messages, 2 = messages only
	$mail->SMTPAuth = true;  // authentication enabled
	$mail->SMTPSecure = 'ssl'; // secure transfer enabled REQUIRED for GMail
	$mail->Host = 'smtp.gmail.com';
	$mail->Port = 465; 
        $mail->Username = 'gmailid'; // i have written my gmail id as value
        $mail->Password = 'password'; // i have password of my mail id
	$mail->setFrom("x@x.com", "xyz");
	$mail->Subject = "test mail";
	$mail->Body = "hi";
	$mail->AddAddress("xyz@gmail.com");
	if(!$mail->Send()) {
		$error = 'Mail error: '.$mail->ErrorInfo; 
		echo "sent";
	} else {
		$error = 'Message sent!';
		echo $error;
	}
?>

Please suggest the solution for this if any....

**Comment by Synchro** [comment]
* Don't hijack threads
* Read the comments above
* Read the readme
* Use the gmail example provided

**Comment by meilmeili** [comment]
hello synchro, i have a problem. I using a PHPMailer-master. but my SMTP doesnt connect. here my syntax 


<?php
include('PHPmailer/class.phpmailer.php');
include ('PHPMailer/PHPMailerAutoload.php');
//phpinfo();
$mail = new PHPMailer();
//$mail->IsSMTP(); // telling the class to use SMTP
//$mail->Host = "localhost"; // SMTP server
//IsSMTP(); // send via SMTP
$mail->Host     = "ssl://re.domain.co.id"; // SMTP server RE
$mail->Mailer   = "smtp";
$mail->SMTPAuth = false; // turn on SMTP authentication
$mail->SMTPSecure = 'ssl';
$mail->Port=25;

$mail->Username = "admin@re.domain.co.id"; // 
$mail->Password = "*******"; // SMTP password
$webmaster_email = "admin@re.domain.co.id"; //Please don't Reply to this email ID
$email = "recipient @ domian.co.id"; // Recipients email ID
$name = "Meilidyaningtyas C.R"; // Recipient's name
$mail->From = $webmaster_email;
$mail->FromName = "Admin System Online";
$mail->AddAddress($email,$name);
$mail->AddReplyTo($webmaster_email,"namawebmaster");
$mail->WordWrap = 50; // set word wrap
$mail->AddAttachment("/var/tmp/file.tar.gz"); // attachment
$mail->AddAttachment("/tmp/image.jpg", "new.jpg"); // attachment
$mail->IsHTML(true); // send as HTML
$mail->Subject = "Ini adalah permohonan no. project";
$mail->Body = "Ini adalah email contoh. harap untuk tidak membalas pesan ini."; //HTML Body
$mail->AltBody = "This is the body when user views in plain text format"; //Text Body 
if(!$mail->Send())
{
echo "Mailer Error: " . $mail->ErrorInfo;
}
else
{
echo "Message has been sent";
}
?>


my problem is, fist, Fatal error: Class 'SMTP' not found in line 1149, then I solve it, and now I found Mailer Error: SMTP connect() failed. What should I do? please help me to solve this problem.

**Comment by Synchro** [comment]
Instead of posting the same questions over and over again, why don't you read the answers that are already here?

Just in case you bother to read this answer:

* Use the latest version of PHPMailer
* [Read the readme](https://github.com/PHPMailer/PHPMailer/blob/master/README.md) to see which files you need and where to put them
* Read [the docs](https://github.com/PHPMailer/PHPMailer/wiki)
* Base your code on [the examples provided](https://github.com/PHPMailer/PHPMailer/tree/master/examples), not old, broken code from elsewhere.

I'm locking this issue now - if you have a new question that is actually different to what has been covered here, open a new issue.
