### ISSUE TITLE
PHPMailer + Yahoo Account ? 

### ISSUE THREAD

**Issue by achourmeddeb** [PHPMailer/PHPMailer#1131]
Hi All, 
I use PHPmailer with a Yahoo account, I configured the script and yesterday it worked and I was able to send ten emails, this morning i cant sent any email ( issue with SMTP connection ) ,  then I wanted to access my box Yahoo via Yahoo site but I have a message that says the account no longer exists. I recreated another account email, and I tested the PHPmailer script, and the sender is successful for only once and after I can't send emails and the new account is no longer exists. Someone can tell me what happened?
Thanks,

**Comment by Synchro** [comment]
It sounds like this has nothing to do with PHPMailer - you should talk to Yahoo support.
