### ISSUE TITLE
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

### ISSUE THREAD

**Issue by kuldeep49291** [PHPMailer/PHPMailer#1132]
Hi Dear ! 
I'm kuldeep recently i have an issue in wordpress easy-wp-smtp plugin, After i fillup the all form when i send  the test mail, it shows me a error as like this SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

I have did trying to solving it, but this couldn't be solved.please giving me a solution about this issue soon.

**Comment by Synchro** [comment]
If you follow the link to the troubleshooting guide it will help you figure out where the problem is. It's most likely to be that outbound SMTP is blocked by your ISP.

**Comment by hasibkamal** [comment]
2018-01-24 14:45:44 Connection: opening to smtp.gmail.com:465, timeout=300, options=array ()
2018-01-24 14:45:45 Connection: opened
2018-01-24 14:45:55 SERVER -> CLIENT: 
2018-01-24 14:45:55 SMTP NOTICE: EOF caught while checking if connected
2018-01-24 14:45:55 Connection: closed
SMTP Error: Could not connect to SMTP host.
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Message could not be sent.Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
@hasibkamal The same thing applies to you. Reposting the same thing isn't going to help - you need to read the docs and do what they say. It's most likely your ISP blocks outbound SMTP.

**Comment by hasibkamal** [comment]
Thank synchro for your reply.
It's solved.

**Comment by baseloo** [comment]
@hasibkamal  how solved please ?
