### ISSUE TITLE
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

### ISSUE THREAD

**Issue by berkaygndzs** [PHPMailer/PHPMailer#1133]
Hello, I'm having issues with this and my debug output is 
`

2017-08-17 11:40:18	SERVER -> CLIENT: 220 smtp.gmail.com ESMTP s86sm2373162wma.10 - gsmtp
--
  | 2017-08-17 11:40:18	CLIENT -> SERVER: EHLO localhost
  | 2017-08-17 11:40:18	SERVER -> CLIENT: 250-smtp.gmail.com at your service, [88.227.66.252]
  | 250-SIZE 35882577
  | 250-8BITMIME
  | 250-STARTTLS
  | 250-ENHANCEDSTATUSCODES
  | 250-PIPELINING
  | 250-CHUNKING
  | 250 SMTPUTF8
  | 2017-08-17 11:40:18	CLIENT -> SERVER: STARTTLS
  | 2017-08-17 11:40:19	SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
  | 2017-08-17 11:40:19	CLIENT -> SERVER: EHLO localhost
  | 2017-08-17 11:40:19	SERVER -> CLIENT: 250-smtp.gmail.com at your service, [88.227.66.252]
  | 250-SIZE 35882577
  | 250-8BITMIME
  | 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
  | 250-ENHANCEDSTATUSCODES
  | 250-PIPELINING
  | 250-CHUNKING
  | 250 SMTPUTF8
  | 2017-08-17 11:40:19	CLIENT -> SERVER: AUTH LOGIN
  | 2017-08-17 11:40:19	SERVER -> CLIENT: 334 VXNlcm5hbWU6
  | 2017-08-17 11:40:19	CLIENT -> SERVER: YmJ5LmduZHpAZ21haWwuY29t
  | 2017-08-17 11:40:19	SERVER -> CLIENT: 334 UGFzc3dvcmQ6
  | 2017-08-17 11:40:19	CLIENT -> SERVER: MThNYXZpc3M=
  | 2017-08-17 11:40:19	SERVER -> CLIENT: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbuY
  | 534-5.7.14 0PBuRY4PaCidVzB2f3LAuC7JpYJHojwZtWJ9UrhsmdY_6Dzx8YCLM6p4dRRcjUa6Y9ncnh
  | 534-5.7.14 t5mUjeNacsoZf0ZrTnfAHcIJ2J63hDhJ-D0r-e6ESRt6Sssc9stLFQfNgWHTI7RZYUC1gG
  | 534-5.7.14 DYcv8B1akb2OQ9qheYNTZhABoxrytwjKct1Dj11tdOPuF75IUqUjuLTJONyXhFHmWEtt0G
  | 534-5.7.14 1hZ_qY5lEFVUkmSyuAAPVRHt6LJtY> Please log in via your web browser and
  | 534-5.7.14 then try again.
  | 534-5.7.14  Learn more at
  | 534 5.7.14  https://support.google.com/mail/answer/78754 s86sm2373162wma.10 - gsmtp
  | 2017-08-17 11:40:19	SMTP ERROR: Password command failed: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbuY
  | 534-5.7.14 0PBuRY4PaCidVzB2f3LAuC7JpYJHojwZtWJ9UrhsmdY_6Dzx8YCLM6p4dRRcjUa6Y9ncnh
  | 534-5.7.14 t5mUjeNacsoZf0ZrTnfAHcIJ2J63hDhJ-D0r-e6ESRt6Sssc9stLFQfNgWHTI7RZYUC1gG
  | 534-5.7.14 DYcv8B1akb2OQ9qheYNTZhABoxrytwjKct1Dj11tdOPuF75IUqUjuLTJONyXhFHmWEtt0G
  | 534-5.7.14 1hZ_qY5lEFVUkmSyuAAPVRHt6LJtY> Please log in via your web browser and
  | 534-5.7.14 then try again.
  | 534-5.7.14  Learn more at
  | 534 5.7.14  https://support.google.com/mail/answer/78754 s86sm2373162wma.10 - gsmtp
  | 2017-08-17 11:40:19	SMTP Error: Could not authenticate.
  | 2017-08-17 11:40:19	CLIENT -> SERVER: QUIT
  | 2017-08-17 11:40:19	SERVER -> CLIENT: 221 2.0.0 closing connection s86sm2373162wma.10 - gsmtp
  | 2017-08-17 11:40:19	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

`
Nothing is wrong with my credentials. My code looks like this: 
`
require_once('mail/PHPMailerAutoload.php');
$mail = new PHPMailer;
$mail->From = "from@yourdomain.com";
$mail->FromName = "Berkay Gündüz";
echo (extension_loaded('openssl')?'SSL loaded':'SSL not loaded')."\n"; 

$mail->isSMTP();                                      // Set mailer to use SMTP
$mail->Host = 'tls://smtp.gmail.com:587';
  // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                    
$mail->SMTPDebug = 2;
           // Enable SMTP authentication
$mail->Username = 'bby.gndz@gmail.com';                 // SMTP username
$mail->Password = 'mypassword(hidden atm)';                           // SMTP password
// $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
// $mail->Port = 587;               

if(isset($_POST['send'])){
	$to = $_POST['to'];
	$subject = $_POST['subject'];
	$text= $_POST['text'];
	$mail->addAddress($to); //Recipient name is optional

$mail->From = "from@yourdomain.com";
$mail->FromName = "Berkay Gündüz";
$mail->addAddress($to); //Recipient name is optional
$mail->isHTML(true);
$mail->Subject = $subject;
$mail->Body =  $text;
// $mail->AltBody = "This is the plain text version of the email content";
if(!$mail->send()) 
{
	$message['type'] = 'error';
    $message['msg'] =  "Mailer Error: " . $mail->ErrorInfo;
} 
else 
{$message['type'] = 'success';
    $message['msg'] =  "Message has been sent successfully";
}

	
} `

**Comment by Synchro** [comment]
This is a Gmail problem, nothing to do with your code or PHPMailer - you need to follow the link they provide and do what it says. There is more info in the PHPMailer troubleshooting guide that the error message links you to.

**Comment by devatahir30** [comment]
error in Sentrifugo_3.2
![capture2](https://user-images.githubusercontent.com/31231989/29549852-287331f4-8728-11e7-98d4-613592d7d0fb.JPG)


SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
Please don't post comments on closed, unrelated issues.

You have two mistakes in your config - you mistyped `tls` as `tsl`, and you should be using port 587 for TLS, not 465. Both of those things are covered in the troubleshooting guide that the error links to.

**Comment by hardikdiff** [comment]
Hiii
i got smtp failed connect error
this is my code

require 'PHPMailer/PHPMailerAutoload.php';
require 'PHPMailer/class.phpmailer.php';
function Sendmail($to, $subject, $message, $filename, $path){

/********* New Method ********/
$email = new PHPMailer;
$email->isSMTP();
$email->Host = 'mydomain.com';
$email->SMTPAuth = true;
$email->Username = "info@mydomain.com";
$email->Password = "**********";
$email->SMTPSecure = 'tls';
$email->Port = 465;
$email->Subject = $subject;
$email->setFrom('info@mydomain.com', $subject);
$email->addReplyTo('admin@mydomain.com', $subject);
$email->isHTML(true);

// Add a recipient
$email->AddAddress($to);
$email->Body = $message;
if($filename) $email->AddAttachment('/var/www/html'.$filename); // attachment
if(!$email->send()) {
print_r($email->ErrorInfo);
//return $email->ErrorInfo;
} else {
print_r('Mail Sent success');
//return 'Mail Sent';
}

}

can you help me please?

**Comment by vivekmehta2305** [comment]
<!DOCTYPE html>
<html>
<head>
	<title>My Domian - New Client Activation Form - Submit</title>
	<link rel="icon" sizes="144x144" type="image/png" href="assets/images/fav.png">
</head>
<body>
<?php
/**
 * This example shows settings to use when sending via Google's Gmail servers.
 */

if(!isset($_POST['brandName'])){
echo "Contact us at support@yourdomain.com 1";
die();
}

//SMTP needs accurate times, and the PHP time zone MUST be set
//This should be done in your php.ini, but this is how to do it if you don't have access to that
date_default_timezone_set('Etc/UTC');

require 'phpmailer/PHPMailerAutoload.php';

//Create a new PHPMailer instance
$mail = new PHPMailer();

//Tell PHPMailer to use SMTP
$mail->isSMTP();

//Enable SMTP debugging
// 0 = off (for production use)
// 1 = client messages
// 2 = client and server messages
$mail->SMTPDebug = 0;

//Ask for HTML-friendly debug output
$mail->Debugoutput = 'html';

//Set the hostname of the mail server
$mail->Host = 'smtp.gmail.com';
// use
// $mail->Host = gethostbyname('smtp.gmail.com');
// if your network does not support SMTP over IPv6

//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
$mail->Port = 587;

//Set the encryption system to use - ssl (deprecated) or tls
$mail->SMTPSecure = 'tls';

//Whether to use SMTP authentication
$mail->SMTPAuth = true;

//Username to use for SMTP authentication - use full email address for gmail
$mail->Username = "vivek@gmail.com";

//Password to use for SMTP authentication
$mail->Password = "reply-no";

//Set who the message is to be sent from
$mail->setFrom('no-reply@yourdomain.com', 'no-reply@yourdomain.com.com');

//Set an alternative reply-to address
//$mail->addReplyTo('replyto@example.com', 'First Last');

//Set who the message is to be sent to
$mail->addAddress('accounts@yourdomain.com', 'Your Domain - Accounts Department');
$mail->addAddress('support@yourdomain.com', 'your domain');
$mail->addAddress('operations@yourdomain.com', 'Your Domain - Operations');
$mail->addAddress('abcd@yourdomain.com', 'ABCDED');
$mail->addAddress('cdef@yourdomain.com', 'ABCD');

$mail->Subject = "ABCD - New Client Onboard - [".$_POST['brandName']."]";


$mail->Body= "<b>Brand Name:</b> ".$_POST['brandName']."<br><b>Company Name:</b> ".$_POST['companyName']."<br><b>Contact Person Name:</b> ".$_POST['contactPersonName']."<br><b>Contact No:</b> ".$_POST['contactNo']."<br><b>Secondary Contact No:</b> ".$_POST['secondarycontactNo']."<br><b>Email ID:</b> ".$_POST['emailID']."<br><b>Secondary Email ID:</b> ".$_POST['secondaryEmailID']."<br><b>Address:</b> ".$_POST['address']."<br><b>Sales Person:</b> ".$_POST['salesPerson']."<br><b>Package:</b> ".$_POST['package']."<br><b>Additional Platforms:</b> ".$_POST['additionalPlatforms']."<br><b>Payment received for how many plans:</b> ".$_POST['noOfPlans']."<br><b>Amount received for Paid Advertising -  Included in retainer i.e recurring:</b> ".$_POST['paidAdvertisingAmountincluded']."<br><b>Amount received for Paid Advertising - Non included in the retainer:</b> ".$_POST['paidAdvertisingAmountnonicluded']."<br><b>Bifurcation of Paid Marketing:</b> ".$_POST['bifurcationPaidMarketing']."<br><b>Agency Commission Percentage:</b> ".$_POST['commissionPercentage']."<br><b>Website:</b> ".$_POST['website']."<br><b>Facebook Page Link:</b> ".$_POST['facebookPageLink']."<br><b>Points by client:</b> ".$_POST['pointsbyclient']."<br><b>Any discussion on campaigns:</b> ".$_POST['anydiscussion']."<br><b>Any other remark:</b> ".$_POST['remark'];

//Replace the plain text body with one created manually
$mail->AltBody = 'This is a plain-text message body';


//send the message, check for errors
if (!$mail->send()) {
    echo "Something went wrong! Contact us at support@yourdomain.com";
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo "The information has been sent to the operations team.";
}
?>
</body>
</html>

i am Getting Error Something went wrong! Contact us at support@yourdomain.comMailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
So how about you do what it suggests and read the troubleshooting guide?

**Comment by satishnamagiri** [comment]
If you are using in localhost, 
remove semicolon ; in this line `extension=php_openssl.dll`  in your php.ini file.
OR
Disable your antivirus and try it. It worked for me

**Comment by Chaguala** [comment]
Hello! same one help me!

I'm trying to send mail using SMTP from my gmail using PHP buy a got this error :  Mailer Error: Could not instantiate mail function

**Comment by Synchro** [comment]
I found the problem: you didn't follow any of the links to the troubleshooting guide.
