### ISSUE TITLE
Message could not be sent.Mailer Error: SMTP connect() failed.

### ISSUE THREAD

**Issue by jvitoroc** [PHPMailer/PHPMailer#1135]
```
<?php

// Mudar Aqui

$email_envio = 'name@email.com'; // E-mail receptor
$email_pass = 'password'; // Senha do e-mail

$site_name = 'asdsds'; // Nome do Site
$site_url = 'sdsdsds'; // URL do Site

$host_smtp = 'smtp.gmail.com'; // HOST SMTP Ex: smtp.domain.com.br
$host_port = '465'; // Porta do Host

// Variáveis do Formulário
// Conteúdo do Formulário

// Não mudar a partir daqui

require ('../PHPMailer/PHPMailerAutoload.php');

$mail = new PHPMailer;
$mail->CharSet = 'UTF-8';

$mail->isSMTP();
$mail->Host = $host_smtp;
$mail->SMTPAuth = true;
$mail->Username = $email_envio;
$mail->Password = $email_pass;
$mail->Port = $host_port; 

$mail->From = "lopogax@gmail.com";

$mail->addAddress("lopogax@gmail.com");

$mail->FromName = 'Formulário de Contato';
$mail->AddReplyTo("lopogax@gmail.com", 'joao');

$mail->WordWrap = 70;

$mail->Subject = 'Formulário sd';

$mail->Body = "lopogax@gmail.com";

if(!$mail->send()) {
echo 'Message could not be sent.';
         echo 'Mailer Error: ' . $mail->ErrorInfo;
    } else {
    echo 'Message has been sent';
   }
?>
```
```

$("#sendEmail").on("submit", ()=>{
	$.ajax({
            type: "POST",
            url: "../email.php",
            success: function (data)
            {
                console.log(data);
            }
        });
	return false;
});
```

**Comment by Synchro** [comment]
Please read [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting).

**Comment by csandreas1** [comment]
what host are you using? I had the same problem

**Comment by jvitoroc** [comment]
https://www.000webhost.com/

**Comment by jvitoroc** [comment]
I solved the problem using: $mail->Host = 'tls://smtp.gmail.com:587';

**Comment by Synchro** [comment]
Those are equivalent to the settings that are suggested in [the gmail example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail.phps).

**Comment by poojakhatri** [comment]
$mail->IsSMTP();
instead of small i you have to write I

**Comment by Synchro** [comment]
@poojakhatri No, that makes no difference - PHP is case-sensitive for variables and properties, but not functions and methods, and it is `isSMTP` in the PHPMailer class.

**Comment by hardikdiff** [comment]
Hiii 
i got smtp failed connect error
this is my code 

require 'PHPMailer/PHPMailerAutoload.php';
require 'PHPMailer/class.phpmailer.php';
function Sendmail($to, $subject, $message, $filename, $path){

	/********* New Method ********/
	$email = new PHPMailer;
$email->isSMTP();
$email->Host = 'mydomain.com';
$email->SMTPAuth = true;
$email->Username   = "info@mydomain.com";
$email->Password   = "**********";
$email->SMTPSecure = 'tls';
$email->Port = 465;
$email->Subject   = $subject;
$email->setFrom('info@mydomain.com', $subject);
$email->addReplyTo('admin@mydomain.com', $subject);
$email->isHTML(true);

// Add a recipient
$email->AddAddress($to);
$email->Body = $message;
if($filename) $email->AddAttachment('/var/www/html'.$filename);      // attachment
	if(!$email->send()) {
           print_r($email->ErrorInfo);
			//return $email->ErrorInfo;
        } else {
           print_r('Mail Sent success');
           //return 'Mail Sent';
        }

}

can you help me please?

**Comment by Synchro** [comment]
Read the docs your error message links to. You’re trying to use `tls` mode on port 465, and you’re using an old version.

**Comment by pssshete** [comment]
<?php
require("phpmailer/class.phpmailer.php");
$otp=mt_rand(10000,99999);//enter Mobile numbers comma seperated
setcookie('otp',$otp);
//Create a new PHPMailer instance
$mail = new PHPMailer;


//Tell PHPMailer to use SMTP
$mail->IsSMTP();
$mail->SMTPOptions = array(
    'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )
);

//Set the hostname of the mail server
$mail->Host = 'smtp.gmail.com';
// use
// $mail->Host = gethostbyname('smtp.gmail.com');
// if your network does not support SMTP over IPv6

//Set the SMTP port number - 587 for authenticated TLS
$mail->Port = 587;

//Set the encryption system to use - ssl (deprecated) or tls
$mail->SMTPSecure = 'tls';

//Whether to use SMTP authentication
$mail->SMTPAuth = true;

//Username to use for SMTP authentication - use full email address for gmail
$mail->Username = "pranavshete0@gmail.com";

//Password to use for SMTP authentication
$mail->Password = "9422044501ps";

//Set who the message is to be sent from
$mail->setFrom('pranavshete0@gmail.com', 'First Last');

//Set an alternative reply-to address
$mail->addReplyTo('pranavshete97@gmail.com', 'First Last');

//Set who the message is to be sent to
$mail->addAddress('nandkishorswami0@gmail.com', 'Nandu Swami');
$mail->Body = "HI your otp is".$otp;
$mail->Send();
if(!$mail->send()) 
{
   echo "Mailer Error: " . $mail->ErrorInfo;
} 
else 
{
echo "Message has been sent successfully";
}


?>
Can You solve the error of above code???....Mailer Error: SMTP Connect() failed.

**Comment by phantomlordpt** [comment]
The answer from **@jvitoroc** helped me.
Changed from **$mail->Host = 'smtp.gmail.com';** to **$mail->Host = 'tls://smtp.gmail.com:587'** and removed **$mail->Port= 587;**

**Comment by Synchro** [comment]
This:

```php
$mail->Host = 'tls://smtp.gmail.com:587';
```

is exactly equivalent to:

```php
$mail->Host = 'smtp.gmail.com';
$mail->Port = 587;
$mail->SMTPSecure = 'tls';
```

**Comment by phantomlordpt** [comment]
Maybe I didn't have the SMTPSecure parameter. I don't have access to the code, it was from an intern that I was helping. But thanks for the reply

**Comment by discussion4all** [comment]
fgbhfhfffffffffffffffffffffffffffffffffffffffffffffffffffff

**Comment by anatmart** [comment]
remove or comment // this line

$mail->IsSMTP();

it's work.

**Comment by discussion4all** [comment]
Is it for me?
    On Tuesday, 16 July, 2019, 08:21:31 am IST, anatmart <notifications@github.com> wrote:  
 
 
remove or comment // this line

$mail->IsSMTP();

it's work.

**Comment by Synchro** [comment]
Removing that line means you are not using gmail's servers, and any messages you do manage to send that way will be marked as forgeries, so no, don't do that.

**Comment by virtiparekh** [comment]
i tried with all of the statement but it does not work can any one solve?

this is my code...........

<?php

	// $result="";
	if (isset($_POST['submit'])) {
		require 'phpmailer/PHPMailerAutoload.php';
		$mail = new PHPMailer;
		$mail->isSMTP();
		$mail->Host='smtp.gmail.com';
		$mail->Port=587;
		$mail->SMTPAuth=true;
		$mail->SMTPSecure='tls';
		$mail->Username='virtiparekh03@gmail.com';
		$mail->Password='**********';
		$mail->setFrom($_POST['email'],$_POST['name']);
		$mail->addAddress('voran721@gmail.com');
		$mail->addReplyTo($_POST['email'],$_POST['name']);

		$mail->isHTML(true);
		$mail->Subject='Form Submission:'.$_POST['subject'];
		$mail->Body='<h1 align=center>Name:'.$_POST['name'].'<br>Email:'.$_POST['email'].'<br>Message:'.$_POST['msg'].'</h1>';

		if (!$mail->send()) {

			// $result="Something went wrong.Please try again.";
			echo "unsuccessful";
		}
		else{
			
			// $result="Thanks ".$_POST['name']."for contacting us. We will get back to you soon";
			echo "successful";		
		}
	}

?>


<!DOCTYPE html>
<html>
<head>
	<title> Contact Form Design </title>
	<link rel="stylesheet" type="text/css" href="contact.css">
</head>
<body>
	<div class="contact-title">
			<h1>Contact Us</h1>
			<h2>We are always ready to serve you!</h2>
	</div>
	<div class="contact-form">
		<form id="contact-form" action="" method="POST">
		<input name="name" type="text" class="form-control" placeholder="Your Name" required>
		<br>
		<input name="email" type="email" class="form-control" placeholder="Your Email" required>
		<br>
		<input type="text" name="subject" class="form-control" placeholder="Your Subject" required>
		<br>
		<textarea name="msg" class="form-control" placeholder="Message" row="4" required></textarea><br>
		<input type="submit" class="form-control submit" value="SEND MESSAGE" name="submit">
	</form>
	
</div>
</body>
</html>

**Comment by Synchro** [comment]
You're forging the from address, and using an old version. Don't do that. Follow [the example contact form provided](https://github.com/PHPMailer/PHPMailer/blob/master/examples/contactform.phps). If you're having a connection problem, read the troubleshooting guide and the other things mentioned in this thread. Also, please don't post questions as comments on closed tickets, it's annoying for everyone else in the thread.

**Comment by virtiparekh** [comment]
sorry,but i m trying since last 3 4 days but its give me an error ...... i tried your code now it give me this error......

Fatal error: Uncaught Error: Class 'PHPMailer\PHPMailer\PHPMailer' not found

**Comment by Synchro** [comment]
Yes, so [read the readme](https://github.com/PHPMailer/PHPMailer/blob/master/README.md#installation--loading) that tells you how to install and load it. Version 6.0 is namespaced, so your code needs to take that into account.

**Comment by virtiparekh** [comment]
i just downloaded updated version 6.0 
now it showing me this error......

2019-09-16 17:10:40 SERVER -> CLIENT: 220 smtp.gmail.com ESMTP v32sm937099pga.38 - gsmtp
2019-09-16 17:10:40 CLIENT -> SERVER: EHLO localhost
2019-09-16 17:10:40 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [1.186.127.250]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250 SMTPUTF8
2019-09-16 17:10:40 CLIENT -> SERVER: STARTTLS
2019-09-16 17:10:41 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
SMTP Error: Could not connect to SMTP host.
2019-09-16 17:10:41 CLIENT -> SERVER: QUIT
2019-09-16 17:10:41 SERVER -> CLIENT:
2019-09-16 17:10:41 SMTP ERROR: QUIT command failed:
SMTP Error: Could not connect to SMTP host.
Message could not be sent. Mailer Error: SMTP Error: Could not connect to SMTP host.

**Comment by Synchro** [comment]
Right, so now you have it failing immediately after a STARTTLS command, something which is also [described in great detail in the guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#using-encryption). Please read before posting.

**Comment by virtiparekh** [comment]
i downloaded the CA certificates file but still it  gives me same error.....

**Comment by Synchro** [comment]
So maybe it is not a problem with CA certificates - use the tests in the guide to diagnose it.

**Comment by asthaf** [comment]
Invalid address:
SMTP ERROR: Failed to connect to server: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10060)
SMTP connect() failed.
SMTP connect() failed.Message could not be sent.Mailer Error: SMTP connect() failed.

**Comment by php717** [comment]
Hi
Im getting this error

Message could not be sent. Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

New up to dated script as you can see

Hosted on one.com
with email support

Please advise
```
if ($_POST) {
    $to_Email       = "mail@mail.com"; // Replace with recipient email address
    $subject        = 'Message from my website'; // Subject line for emails
     
    $host           = "send.one.com "; // Your SMTP server. For example, smtp.mail.example.com
    $username       = "mail@mail.com"; //For example, your.email@example.com
    $password       = "Password"; // Your password
    $SMTPSecure     = "ssl"; // For example, ssl or tls
    $port           = 465; // For example, 465
    
    
    //check if its an ajax request, exit if not
    if (!isset($_SERVER['HTTP_X_REQUESTED_WITH']) and strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) != 'xmlhttprequest') {
    
        //exit script outputting json data
        $output = json_encode(
        array(
            'type'=>'error',
            'text' => 'Request must come from Ajax'
        )
        );
        
        die($output);
    }
    
    //check $_POST vars are set, exit if any missing
    if (!isset($_POST["name"]) || !isset($_POST["email"]) || !isset($_POST["message"])) {
        $output = json_encode(array('type'=>'error', 'text' => 'Input fields are empty!'));
        die($output);
    }

    //Sanitize input data using PHP filter_var().
    $user_Name        = filter_var($_POST["name"], FILTER_SANITIZE_STRING);
    $user_Email       = filter_var($_POST["email"], FILTER_SANITIZE_EMAIL);
    $user_Message     = filter_var($_POST["message"], FILTER_SANITIZE_STRING);
    
    $user_Message = str_replace("\&#39;", "'", $user_Message);
    $user_Message = str_replace("&#39;", "'", $user_Message);
    
    //additional php validation
    if (strlen($user_Name)<4) { // If length is less than 4 it will throw an HTTP error.
        $output = json_encode(array('type'=>'error', 'text' => 'Name is too short or empty!'));
        die($output);
    }
    if (!filter_var($user_Email, FILTER_VALIDATE_EMAIL)) { //email validation
        $output = json_encode(array('type'=>'error', 'text' => 'Please enter a valid email!'));
        die($output);
    }
    if (strlen($user_Message)<5) { //check emtpy message
        $output = json_encode(array('type'=>'error', 'text' => 'Too short message! Please enter something.'));
        die($output);
    }
    
    //proceed with PHP email.
    //you have to upload class files "class.phpmailer.php" and "class.smtp.php"
    require 'PHPMailer/class.pop3.php';
    require 'PHPMailer/class.phpmailer.php';
    require 'PHPMailer/class.smtp.php';
 
    $mail = new PHPMailer();
     
    $mail->IsSMTP();
    $mail->SMTPAuth = true;
    
    $mail->Host = $host;
    $mail->Username = $username;
    $mail->Password = $password;
    $mail->SMTPSecure = $SMTPSecure;
    $mail->Port = $port;
    
     
    $mail->setFrom($username);
    $mail->addReplyTo($user_Email);
     
    $mail->AddAddress($to_Email);
    $mail->Subject = $subject;
    $mail->Body = $user_Message. "\r\n\n"  .'Name: '.$user_Name. "\r\n" .'Email: '.$user_Email;
    $mail->WordWrap = 200;
    $mail->IsHTML(false);

    if (!$mail->send()) {
        $output = json_encode(array('type'=>'error', 'text' => 'Message could not be sent. Mailer Error: ' . $mail->ErrorInfo));
        die($output);
    } else {
        $output = json_encode(array('type'=>'message', 'text' => 'Hi '.$user_Name .'! Thank you for your email'));
        die($output);
    }
}
?>
```

**Comment by php717** [comment]
same error  if i will replace  ssl to tls

**Comment by Synchro** [comment]
Please don't post unrelated comments on old, closed issues.

>    require 'PHPMailer/class.pop3.php';
    require 'PHPMailer/class.phpmailer.php';
    require 'PHPMailer/class.smtp.php';

This tells me that you're using an old version; upgrade. You've also based your code on an old example.

That's unlikely to fix your problem though – it looks like your hosting provider blocks outbound SMTP, so read the troubleshooting guide and ask your provider for support.
