### ISSUE TITLE
Add Reply To Issue

### ISSUE THREAD

**Issue by ashikkaiser** [PHPMailer/PHPMailer#1141]
Is it possible to make if add reply to is blank then stop sending email  via php mailer . i want to stop sending mail if reply to section is blank .

**Comment by Synchro** [comment]
Reply-to is optional anyway (because replies go to the From address by default), so this isn't really a PHPMailer question, it's about validating the data you're going to pass into it before you use it, for example:

```php
if (empty($emailaddress)) {
  exit("Email address missing");
} else {
  if (!$mail->addReplyTo($emailaddress)) {
    exit("Email address invalid");
  }
}
```
