### ISSUE TITLE
PHPMailer throwing error on php7

### ISSUE THREAD

**Issue by namangarg88** [PHPMailer/PHPMailer#1146]
Hi,

I am receiving errors after updating php from 5.3 to 7. We have Cloudflare free certificate installed on the server. Rest everything is working fine after up gradation. 
I was trying to debug it in different ways. Checked various logs:

**PHPMailer Current version is 5.2.10. while php updated to 7.0.22**
**After reading troubleshooting guide:** 
Added this code in 
```php
$mail->SMTPOptions = array(
    'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )
);
```
**CODE:**
```php
<?php
require("class.phpmailer.php");
require("PHPMailerAutoload.php");
$mail = new PHPMailer();
$mail->IsSMTP();
$mail->Host = "us2.smtp.mailhostbox.com";
$mail->SMTPDebug  = 2;
$mail->SMTPOptions = array(
    'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )
);
$mail->SMTPAuth = true;
$mail->SMTPSecure = "tls";
$mail->Port = 587;
$mail->Username = "operationteam@giftjaipur.com";
$mail->Password = "password";
$mail->From = "operationteam@giftjaipur.com";
$mail->FromName = "Test from Info";
$mail->AddAddress("namangarg88@gmail.com");
$mail->IsHTML(true);
$mail->Subject = "Test message from server";
$mail->Body = "Test Mail<b>in bold!</b>";
if(!$mail->Send())
{
echo "Message could not be sent. <p>";
echo "Mailer Error: " . $mail->ErrorInfo;
exit;
}
echo "Message has been sent";
?>
```
**Error Received:**
The following From address failed: operationteam@giftjaipur.com Message could not be sent.
Mailer Error: The following From address failed: operationteam@giftjaipur.com
SMTP server error: Security failure

Would be glad if you can help.

**Comment by namangarg88** [comment]
This is the error in log file:
PHP Warning:  stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /home/giftjaipur/public_html/class.smtp.php on line 197


Same error was coming earlier before applying the fix.

**Comment by Synchro** [comment]
Well this is exactly what the troubleshooting guide says it will do since PHP 5.6 changed the default to verifying certificates. While you can disable verification as you say, it's a really bad idea. A better solution is to connect to the mail server using its correct name, and then you will not have a name mismatch. If it's that the mail server is providing an invalid cert anyway, you need to fix your mail server.

**Comment by Kinjalchhaparwal** [comment]
require_once 'phpmailer/class.smtp.php';
              require_once 'phpmailer/PHPMailerAutoload.php';
             $mail = new PHPMailer();
              $mail->isSMTP();
            //  $mail->SMTPDebug = 0;
                $mail->SMTPSecure = 'tls';
                   $mail->Port = 587;
              $mail->Host = "smtp.gmail.com";
             $mail->SMTPAuth = true;
              $mail->IsHTML(true);
              $mail->Username = "abc@gmail.com";
              $mail->Password = "password";
              $mail->SetFrom('abc@gmail.com');
              $mail->Subject = "Confirm to Vrify";
            //  $mail->Body = "http://35.200.239.81/activation.php?key='".$confirm_code."'&username='".$email."'";
               $mail->Body = "KINJAL";
              $mail->AddAddress($email);
              $mail->addReplyTo($email, $user_name);
              if(!$mail->Send()) {
              echo "Mailer Error: " . $mail->ErrorInfo;
              } 
              else
               {
              echo "Message has been sent";
              }      
    I am using phpmailer function in windows 10 but it is not work i have tried ssl or tsl both with ports 465 and 587 or 25 but it is showing error
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in 
Mailer Error: SMTP connect() failed.

Please help me to resolve this issue.


Thanks in advance !!!

**Comment by Kinjalchhaparwal** [comment]
require_once 'phpmailer/class.smtp.php';
              require_once 'phpmailer/PHPMailerAutoload.php';
             $mail = new PHPMailer();
              $mail->isSMTP();
            //  $mail->SMTPDebug = 0;
                $mail->SMTPSecure = 'tls';
                   $mail->Port = 587;
              $mail->Host = "smtp.gmail.com";
             $mail->SMTPAuth = true;
              $mail->IsHTML(true);
              $mail->Username = "abc@gmail.com";
              $mail->Password = "password";
              $mail->SetFrom('abc@gmail.com');
              $mail->Subject = "Confirm to Vrify";
               $mail->Body = "KINJAL";
              $mail->AddAddress($email);
              $mail->addReplyTo($email, $user_name);
              if(!$mail->Send()) {
              echo "Mailer Error: " . $mail->ErrorInfo;
              } 
              else
               {
              echo "Message has been sent";
              }      
    I am using phpmailer for using mail function in windows 10 (xampp) but i am not able to send mail i have already tried ssl or tsl with ports 587 or 465 or 25 but it is showing error


Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Mailer Error: SMTP connect() failed.

Please help me to solve this issue. I am stucked in this from 2 days but i am not getting any solution. I have off firewaal and on less secure apps from my gmail account settings.



Thanks in advance!!!!

**Comment by Synchro** [comment]
Don’t hijack old, closed threads, especially when the exact problem you describe is covered extensively in documentation you’ve been pointed at several times.
