### ISSUE TITLE
Strange Thing on My Host

### ISSUE THREAD

**Issue by vdanelia** [PHPMailer/PHPMailer#1147]
Hello I noticed very strange thing when working with PHPMailer..

I Updated php Mailer to final version ..
when using : $mail->isSMTP(); mails not sent and the debug says nothing, but if I remove or comment //$mail->isSMTP(); it's sending..
What is the problem?

```php
$mail = new PHPMailer();
//$mail->isSMTP();
$mail->SMTPDebug = 2;
$mail->CharSet = 'UTF-8';                                
$mail->Host = 'smtp.gmail.com';
$mail->Port = 587;
$mail->SMTPSecure = 'tls';	
$mail->SMTPAuth = true;
$mail->Username = 'mymail@gmail.com';
$mail->Password = 'mypassword';
$mail->setFrom('mymail@gmail.com', 'mydomain');
$mail->FromName = $_POST['name'];
$mail->AddAddress(s('feedback2'));
$mail->WordWrap = 80;
$mail->IsHTML(true);
$mail->Subject = $_POST['subject']. " Contact Form";
$mail->Body    = $go;
$mail->AltBody = $go;
$mail->Send();
```

**Comment by Synchro** [comment]
If you comment out `isSMTP`, it will revert to its default which is sending via PHP's `mail()` function, which submits your message via a sendmail binary to your local mail server. This requires no network connectivity, and it's quite likely that your ISP blocks outbound SMTP. It doesn't help that you're not doing any error checking; base your code on the examples provided with PHPMailer and it will report errors correctly.

**Comment by vdanelia** [comment]
So Do I contact to hosting and tell not to block outbound SMTP, or let it be as it is? 
What is the best for me, please suggest

**Comment by vdanelia** [comment]
Hello it's me again..
Now I did some tests I enabled $mail->isSMTP(); and then enabled option in Google Less secure apps and worked.... so di I enable that option? (google warns me not to enable) what to do, please suggest...

Thank you in Advanced

**Comment by Synchro** [comment]
This is all covered in the troubleshooting guide. To get rid of that output, turn off debug output by setting `SMTPDebug = 0;`.

**Comment by vdanelia** [comment]
That's OK, but what about google warning about "Less secure apps"? without turning it on PHPMailer not working correctly,,,, If I enable it permanently, will I be secured? will i have security issues or problems?

I also checked your wiki about more secure method "Using Gmail with XOAUTH2" I have never used that technology before...

**Comment by Synchro** [comment]
This is covered in the guide and wiki. It's not really any less secure, and PHPMailer is working just fine. If you want to use it without the "less secure apps" setting, you need to follow that guide in the wiki and add the oauth packages to your project, because otherwise you will not have the required oauth support. It is horrifically complex and unpleasant to work with, but that's just how oauth is.

**Comment by vdanelia** [comment]
**Synchro** thank you very much for assistance, support and suggestions....
