### ISSUE TITLE
Make last_smtp_transaction_id available in callback somehow

### ISSUE THREAD

**Issue by deebuck** [PHPMailer/PHPMailer#1150]
This is a feature request. 
You are now capturing the last_smtp_transaction_id in SMTP, but it isn't available to me through the callback so I have to subclass PHPMailer and override the smtpSend method in order to get my hands on it so I can log it. 
I would be glad to write the code and offer it as a pull request, but without subclassing I think I'd have to add another parameter to doCallback, and that seems drastic, so I thought I'd just send a request and see what you say. 
One other point: in my override of smtpSend I gather the recipient results and defer invoking the callback until all the recipients are done, after smtp->data() is called, so I can obtain 
$this->smtp>getLastTransactionID() before invoking the callback for each recipient.

**Comment by Synchro** [comment]
This sounds reasonable. `doCallback` does have quite a lot of params already; it might be better to have a single additional param that's an assoc array that arbitrary extra data can be added to, so in this case you could supply `['smtp_transaction_id' => $id]` or similar. That would allow for future expansion without having to add yet more params.

As for accumulating results, I think that's less generally useful and so better suited to a subclass for your particular purpose. I subclass PHPMailer myself for things that I want to work differently, but are not generally useful. Actually I think I'd implement what you're doing in the subclass in the calling context instead - you know that you're sending a batch of messages, so I'd accumulate the callback results there and attach the transaction ID once you receive it with the last one.

So, with that in mind, PRs welcome!

**Comment by deebuck** [comment]
Thanks for getting back so quick.

I can see that an additional parameter to doCallback might be generally 
useful, but it won't be useful at all for smtp_transaction_id unless we 
actually obtain the smtp_transaction_id before the callback. The 
smtp_transaction_id is not available until after you have done the DATA 
command. As it is now, all the callback invocations are already done 
when you issue the DATA.

As a side benefit of changing the order, it you invoke the callbacks 
after doing the DATA, you have the option at least of informing the 
callback that the DATA transmission failed. Granted, right now if the 
DATA command fails you throw an exception, so it is a moot point. But I 
think a case could be made that (at least conceptually) it is an error 
to inform the callback that a message was sent when the data transfer 
might still fail.

Anyway, I am sending you a pull request, and you can have a look. I 
think when I described it I probably made it sound like a bigger deal 
than it is.

I had a devil of a time testing, till I finally realized that the set of 
smtp_transaction_id_patterns didn't find a match. I am using Amazon 
simple mail service for this customer, as her site is on an Amazon 
instance, and so she can get information about bounces and complaints. I 
had to add an smtp_transaction_id_pattern for Amazon for my tests to 
work, and so I left it in there. I have no clue why Amazon feels it is 
necessary to have a different format for the reply to the Data command!

**Comment by Synchro** [comment]
Good point!

There is no spec or requirement for servers to provide a transaction ID at all, and it's usually not something that is ever needed externally. It's not part of any RFC, so there's no surprise that those servers that do provide one, do so inconsistently.

**Comment by Synchro** [comment]
Closed via your PR in #1155
