### ISSUE TITLE
Long length setfrom ( domain address ) 

### ISSUE THREAD

**Issue by wfajriansyahh** [PHPMailer/PHPMailer#1152]
I set setFrom email, with 'admin@wildanfajriansyahdomainduadantidga.org' but error showing 
Invalid address:  (setFrom) admin@wildanfajriansyahdomainduadantidga.org ...
why?

**Comment by ooxi** [comment]
Please paste an error log

**Comment by Synchro** [comment]
I don't know what you're doing there but:

```php
$e = 'admin@wildanfajriansyahdomainduadantidga.org';
$mail = new PHPMailer;
var_dump($mail->setFrom($e));

bool(true)
```

**Comment by wfajriansyahh** [comment]
punyEncode..
how with this ? @wildanfajriansyahdomainsketigadankeduabersatukembali.org
?

**Comment by Synchro** [comment]
That doesn't need punyencode - it's all 7-bit ASCII characters.

**Comment by Synchro** [comment]
That domain is valid, however, `@wildanfajriansyahdomainsketigadankeduabersatukembaliblahblahblah.org` would not valid because it contains a name segment longer than 63 chars. PHPMailer reports both of these correctly.
