### ISSUE TITLE
Serialising and then later sending PHPMailer emails 

### ISSUE THREAD

**Issue by tomcon** [PHPMailer/PHPMailer#1153]
I've looked everywhere but have not found any way to serialise and then later send PHPMailer emails. 

This topic was useful but doesn't work when tried (see below) 
https://stackoverflow.com/questions/23212634/php-mailer-compile-and-store-message-for-later-sending

Is there any documentation or notes on this subject please?

Creating:
```
  
         $mail->preSend();
         $mimemessage = $mail->getSentMIMEMessage();
         $MessageID = $mail->getLastMessageID();

         $sfile = $msg->queuefolder . DIRECTORY_SEPARATOR . $msg->guid . '_' . $entityid . '.eml';
         CSL_Utils::StringToFile( $sfile, $mimemessage, 'a' );
```

Sending:
```

$eml = file_get_contents($filename); 
$mailer = new PHPMailer(true); 
$mailer = unserialize($eml); --> bombs here, ERROR: unserialize(): Error at offset 0
 ... 
$result = $mailer->postSend();
--

**Comment by Synchro** [comment]
You're misunderstanding what `unserialize` does; It does not magically decompile/parse an RFC822 message into a PHPMailer object. If you want to store an instantiated PHPMailer object, do so with `$string = serialize($mail)`, then unserialize with `$mail = unserialize($string)`. What that article suggests is not this at all though. I suggest storing the individual pieces of data you need to construct a new PHPMailer instance and send it, which is more reliable and efficient than serialization.

**Comment by Synchro** [comment]
Also, it would be much more effective to let a local mail server handle the queuing for you, since that's what it's designed to do.

**Comment by stutteringp0et** [comment]
PHPMailer isn't fault tolerant though.  Sure, it catches errors in send - but without a facility to store the message and retry later, it's up to the system to store the message parts prior to attempting to send them.

Additionally, many sites use message queues so sending emails don't take away from the user experience.

**Comment by Synchro** [comment]
That’s pretty much what I said. If you use a local mail server, sending is reliable and pretty instant. A mail server is no less reliable than some other queuing system, probably more so as all common mail servers are very mature and stable. For example I’ve found rabbitmq to be extremely fragile. Just use a mail server, it’s what they’re for.

**Comment by stutteringp0et** [comment]
Did you miss the "errors in send" part?  What if the mail server is offline?

It would be nice to retrieve the message and store it.....

Fortunately, that's not difficult to do after reading through the API.

    $header = $mailer->createHeader();
    $body = $mailer->createBody();

Once those two items are saved, they can be revived for later sending via any of the 3 Send() methods - which all take 2 arguments - $heading and $body.

**Comment by Synchro** [comment]
If you can’t depend on a *local* mail server (I.e. on the same server your script runs on) being up, equally you can’t depend on any other service either - database, queue or whatever. Since it’s trivial to create a new message on demand, storing an out of date one seems pointless, doesn’t gain anything. Using some other mechanism to store and resend a message is simply reinventing the wheel, and will be less stable and reliable than a mail server designed to do exactly that, so you end up back where I suggested.

**Comment by stutteringp0et** [comment]
Who runs a mail server on their web server?

**Comment by Synchro** [comment]
Pretty much everyone; even the most bare-bones server configs use local mail servers to send system notifications, and I'd contend the vast majority of servers are single all-in-one instances running everything anyway. You can say the same thing about *any* other service. There is no reason why you should consider a queue server, database server or any other service more stable, or any more or less likely to be available. So the sensible options are: you have some database source that represents messages that need to be sent. You can take the data from there and generate messages when you need to. If they are not sent directly to destination mail servers, or via a remote (likely slow & unreliable) relay, they should be submitted to a local mail server that will deal with queuing and redelivering the message. Rolling your own queueing system for email is reinventing the wheel and is pointless and inefficient.

**Comment by Synchro** [comment]
To clarify, I'm saying that this (what you proposed) is a poor design:

    db --> script --queue protocol--> queue --queue protocol--> script --smtp--> mail server

This is simpler, more reliable and requires much less code:

    db --> script --smtp--> local mail server --smtp--> remote mail server

For the most part in this route, you don't need to care what happens after delivery to a local mail server. The key point is it's using SMTP as the queuing protocol, and a mail server as the queue; no reinvention necessary.

**Comment by stutteringp0et** [comment]
You might consider that people using this class are asking for a feature - and they're asking here, on StackOverflow, and in various forums - it might be something they need for their environment.  I found the question asked in 6 different places.

**Comment by Synchro** [comment]
Well as you yourself pointed out, it can be done already using the existing transport functions (so nothing needs adding), but that doesn't make it a good design.
