### ISSUE TITLE
Does someone knows why PHPMailer not working with $mail->IsSMTP(); ?

### ISSUE THREAD

**Issue by Asahroki** [PHPMailer/PHPMailer#1154]
Is there anyone to help me and say why my PHPMailer is not working with "$mail->IsSMTP()"; while when I remove this line from my code it start to work very well.

I am using a php code using SMTP conection to send emails from my website contact form (you can see the code below). In orginal code there is line call "$mail->IsSMTP()" but the problem as this line exist on my code, there is an erro that SMTP can not connect. As soon as I remove the code works and emails send easilly.

Is there some one tell me why and how to solve the problem? or dose "$mail->IsSMTP()" important to be included in my code?  

When I send email from my website using code without "$mail->IsSMTP()" I am getting this orginal report of recived email on my email box:

--------------------------------------------------------------------------------
Delivered-To: xxx@xxx.xxx
Authentication-Results: mx.xxxxx;
spf=none (xxxx.com: 0.0.0.0 is neither permitted nor denied by domain of tig.boxsecured.com) smtp.mailfrom=xxxxx@tig.boxsecured.com
Return-Path: <xxxxx@tig.boxsecured.com>
Received: from cadetblue.maple.relay.mailchannels.net (cadetblue.maple.relay.mailchannels.net [0.0.0.0]) by mx.xxx with SMTPS id 1000007698; 
Received: from relay.mailchannels.net (localhost [127.0.0.1]) by relay.mailchannels.net (Postfix) with ESMTP id C8000099F4 for <xxx@xxx.xxx>; 
(Authenticated sender: hostingerinternationalltd) by relay.mailchannels.net (Postfix) with ESMTPA id 56805129871for <xxx@xxx.xxx>; 
Received: from tig.boxsecured.com ([UNAVAILABLE]. [172.20.63.14]) (using TLSv1.2 with cipher DHE-RSA-AES256-GCM-SHA) by 0.0.0.0:2500 (trex/5.9.14);
X-Sender-Id: xxxxxx|x-authuser|xxx@tig.boxsecured.com
X-MC-Relay: Neutral
X-MailChannels-Auth-Id: xxxxxxx
X-Shelf-Illegal: 3192ae434cerfj77796_2329863118
X-MC-Loop-Signature: 895051658208405812
To: xxx@xxx.xxx
Subject: Its a Test Its a Test Its a Test
X-PHP-Script: xxx.xxx/new/contact.php for 0.0.0.0
X-PHP-Filename: /public_html/new/contact.php REMOTE_ADDR: 0.0.0.0
From: Test Test <test@test.com>
Reply-To: test@test.com
Message-ID: <8d1e2c04cb0025a91575375d4891a@xxx.xx>
X-Mailer: PHPMailer 5.2.22 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Sender: <xxxxx@tig.boxsecured.com>
----------------------------------------------------------------------------------------

Code is working only when I remove "$mail->IsSMTP()", otherwise not working and you can see MY ORGINAL CODE THAT INCLUDE "$mail->IsSMTP() AND NOT WORKING":

require 'SMTP/phpmailerautoload.php';
function ValidateEmail($email)
{
   $pattern = '/^([0-9a-z]([-.\w]*[0-9a-z])*@(([0-9a-z])+([-\w]*[0-9a-z])*\.)+[a-z]{2,6})$/i';
   return preg_match($pattern, $email);
}
function RecursiveMkdir($path)
{
   if (!file_exists($path))
   {
      RecursiveMkdir(dirname($path));
      mkdir($path, 0777);
   }
}
if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['formid']) && $_POST['formid'] == 'contact')
{
   $mailto = 'xxx@xxx.xxx';
   $mailfrom = isset($_POST['email']) ? $_POST['email'] : $mailto;
   $subject = isset($_POST['subject']) ? $_POST['subject'] : $subject;
   $fname = isset($_POST['name']) ? $_POST['name'] : $fname;
   $message = '';
   
   $mail = new PHPMailer();
   **$mail->IsSMTP()**
   $mail->Host = 'smtp.example.com';
   $mail->Port = 587;
   $mail->SMTPAuth = true;
   $mail->Username = 'user@example.com';
   $mail->Password = 'pass';
   $mail->SMTPSecure = 'tls';
   $mail->Subject = stripslashes($subject);
   $mail->From = $mailfrom;
   $mail->FromName = $fname;
   $mailto_array = explode(",", $mailto);
   for ($i = 0; $i < count($mailto_array); $i++)
   {
      if(trim($mailto_array[$i]) != "")
      {
         $mail->AddAddress($mailto_array[$i], "");
      }
   }
   $mail->AddReplyTo($mailfrom);
   if (!ValidateEmail($mailfrom))
   {
      $error .= "The specified email address is invalid!\n<br>";
   }

--------------------------------------------------------------------

Thnks for any response and help.

**Comment by Synchro** [comment]
In the code you provided, there is no call to `send()`, so nothing will happen at all.

PHPMailer works fine with `isSMTP()` - but your server or the network it's on may not be configured correctly to allow it. If you don't call it, it sends using the PHP built-in mail() function instead, which submits to your local mail server via a shell call to a sendmail binary. You've not read the troubleshooting guide in the wiki that explains how to diagnose SMTP and connection issues.

You're forging the From address (as the docs tell you *not* to do), so don't do that. Look at the contact form example provided with PHPMailer for how to do it right.

You're using an old and vulnerable version of PHPMailer, so get the latest version.

**Comment by Asahroki** [comment]
Thanks for reply, Code includes send but as its a long code I didnt write all. I got what you want to say, but as you said if SMTP not called, PHP built-in mail() will be use instead. I have a question, I remove the line that call SMTP "isSMTP()" from my code, and then I changed my smtp conection password to a wrong value. when i tried to send email from my contact form I got message can not conect to smtp.

My question is, as you mention when not call smtp, HP built-in mail() function will be used instead, why when i try to send message i got error of smtp?

I hope I could explain well and you understand my mean.

**Comment by Asahroki** [comment]
here is full code:

require 'SMTP/phpmailerautoload.php';
function ValidateEmail($email)
{
   $pattern = '/^([0-9a-z]([-.\w]*[0-9a-z])*@(([0-9a-z])+([-\w]*[0-9a-z])*\.)+[a-z]{2,6})$/i';
   return preg_match($pattern, $email);
}
function RecursiveMkdir($path)
{
   if (!file_exists($path))
   {
      RecursiveMkdir(dirname($path));
      mkdir($path, 0777);
   }
}
if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['formid']) && $_POST['formid'] == 'contact')
{
   $mailto = 'xxx@xxx.xxx';
   $mailfrom = isset($_POST['email']) ? $_POST['email'] : $mailto;
   $subject = isset($_POST['subject']) ? $_POST['subject'] : $subject;
   $fname = isset($_POST['name']) ? $_POST['name'] : $fname;
   $message = '';
   $success_url = 'contact-result/Thanks_Contact.html';
   $error_url = 'contact-result/Error_contact.html';
   $error = '';
   $eol = "\n";
   $max_filesize = 74000*1024;
   $upload_folder = "upload_contact_form";
   $upload_folder = "https://" . $_SERVER['HTTP_HOST'] . dirname($_SERVER['SCRIPT_NAME'])."/".$upload_folder;

   $mail = new PHPMailer();
   $mail->Host = 'xxxx';
   $mail->Port = 587;
   $mail->SMTPAuth = true;
   $mail->Username = 'xxxxx';
   $mail->Password = 'xxxxxx';
   $mail->SMTPSecure = 'tls';
   $mail->Subject = stripslashes($subject);
   $mail->From = $mailfrom;
   $mail->FromName = $fname;
   $mailto_array = explode(",", $mailto);
   for ($i = 0; $i < count($mailto_array); $i++)
   {
      if(trim($mailto_array[$i]) != "")
      {
         $mail->AddAddress($mailto_array[$i], "");
      }
   }
   $mail->AddReplyTo($mailfrom);
   if (!ValidateEmail($mailfrom))
   {
      $error .= "The specified email address is invalid!\n<br>";
   }

   $prefix = rand(11, 99);

   $i = 0;
   while (list ($key, $val) = each ($_FILES))
   {
      if ($_FILES[$key]['name'] != "" and file_exists($_FILES[$key]['tmp_name']) and $_FILES[$key]['size'] > 0)
      {
         $upload_DstName[$i] = $prefix . "_" . str_replace(" ", "_", $_FILES[$key]['name']);
         $upload_SrcName[$i] = $_FILES[$key]['name'];
         $upload_Size[$i] = ($_FILES[$key]['size']);
         $upload_Temp[$i] = ($_FILES[$key]['tmp_name']);
         $upload_URL[$i] = "$upload_folder/$upload_DstName[$i]";
         $upload_FieldName[$i] = $key;
      }
      if ($upload_Size[$i] >= $max_filesize)
      {
         $error .= "The size of $key (file: $upload_SrcName[$i]) is bigger than the allowed " . $max_filesize/1024 . " Kbytes!\n";
      }
      $i++;
   }

   if (!empty($error))
   {
      $errorcode = file_get_contents($error_url);
      $replace = "##error##";
      $errorcode = str_replace($replace, $error, $errorcode);
      echo $errorcode;
      exit;
   }

   $uploadfolder = basename($upload_folder);
   for ($i = 0; $i < count($upload_DstName); $i++)
   {
      $uploadFile = $uploadfolder . "/" . $upload_DstName[$i];
      if (!is_dir(dirname($uploadFile)))
      {
         RecursiveMkdir(dirname($uploadFile));
      }
      move_uploaded_file($upload_Temp[$i] , $uploadFile);
      chmod($uploadFile, 0644);
      $name = "$" . $upload_FieldName[$i];
      $message = str_replace($name, $upload_URL[$i], $message);
   }

   $internalfields = array ("submit", "reset", "send", "filesize", "formid", "captcha_code", "recaptcha_challenge_field", "recaptcha_response_field", "g-recaptcha-response");
   $message .= $eol;
   $message .= "IP Address : ";
   $message .= $_SERVER['REMOTE_ADDR'];
   $message .= $eol;
   $logdata = '';
   foreach ($_POST as $key => $value)
   {
      if (!in_array(strtolower($key), $internalfields))
      {
         if (!is_array($value))
         {
            $message .= ucwords(str_replace("_", " ", $key)) . " : " . $value . $eol;
         }
         else
         {
            $message .= ucwords(str_replace("_", " ", $key)) . " : " . implode(",", $value) . $eol;
         }
      }
   }
   if (count($upload_SrcName) > 0)
   {
      $message .= "\nThe following files have been uploaded:\n";
      for ($i = 0; $i < count($upload_SrcName); $i++)
      {
         $message .= $upload_SrcName[$i] . ": " . $upload_URL[$i] . "\n";
      }
   }
   $mail->CharSet = 'utf-8';
   $mail->WordWrap = 80;
   $mail->Body = $message;
   if (!$mail->Send())
   {
      die('PHPMailer error: ' . $mail->ErrorInfo);
   }
   header('Location: '.$success_url);
   exit;
}

**Comment by Synchro** [comment]
`Username` and `Password`, `Host`, `Port` etc are **only** used if you call `isSMTP()`; when sending via mail(), you don't need a password, and it always sends through localhost, so they simply don't apply. I'd recommend looking at the send_file_upload example provided with PHPMailer as it makes a much simpler and safer job of handling user uploads than you have here.

Check the docs on [`mkdir`](http://php.net/mkdir); it already has a recursive option.

**Comment by Asahroki** [comment]
GREAT MAN, Thnks for help. your recomendation was really useful. 
Ill contact host service if there is any problem using PHPMailer or not on their server.
