### ISSUE TITLE
file upload issue

### ISSUE THREAD

**Issue by jochen1727** [PHPMailer/PHPMailer#1156]
Hi everybody, i ve an issue to send multiple files through phpmailer.
When i use phpmailer exemple in my website that work perfectly.
As fille button is ugly i install a plugin to handle file upload to my php page but when i send a mail it can't attach files from the plugin to phpmailer.
If someone already tried to use it, i asked questions on the plugin github but nothing solved my issue :'(
Thks
This plugin is here 
https://github.com/hayageek/jquery-upload-file/

My html code
```
<form action="mail.php" method="post" id="form" enctype="multipart/form-data">
<div id="fileuploader" name="userfile[]">Upload</div>

```
  
My javascript, (filename is the name of the button file), i have replace name by "userfile[]"  :

```
<script>
$(document).ready(function()
{
	$("#fileuploader").uploadFile({
	url:"mail.php",
	fileName:"userfile[]"
	});
});
</script>
```

My php 

```
for ($ct = 0; $ct < count($_FILES['userfile']['tmp_name']); $ct++) {
        $uploadfile = tempnam(sys_get_temp_dir(), hash('sha256', $_FILES['userfile']['name'][$ct]));
        $filename = $_FILES['userfile']['name'][$ct];
        if (move_uploaded_file($_FILES['userfile']['tmp_name'][$ct], $uploadfile)) {
            $mail->addAttachment($uploadfile, $filename);
        } else {
            $msg .= 'Failed to move file to ' . $uploadfile;
        }
    }
if(!$mail->send())
```

**Comment by Synchro** [comment]
It looks like your uploader only submits the file itself, no other params - is that what you expect? I'd recommend checking what your PHP script is actually receiving - try a `var_dump($_REQUEST)` to start with.
