### ISSUE TITLE
PhpMailer works for Yandex but not for Gmail

### ISSUE THREAD

**Issue by as4wd** [PHPMailer/PHPMailer#1158]
I have been running PhpMailer (using smtp.gmail.com as the host) for quite a while without an issue.  I have recently realized that it somehow stopped sending emails after Sept 05, 2017.

Today I have checked my test code and it did not work as well.
I was trying to find workarounds:
Found 2 workarounds:
1. It works with port:25 and TLS
2. smtp.yandex.com works with the same code port:587 and TLS

On the same server:
smtp.gmail.com with port 587 -- NOT WORKING
--------------------------
`<?php
/**
 * This example shows settings to use when sending via Google's Gmail servers.
 */
//SMTP needs accurate times, and the PHP time zone MUST be set
//This should be done in your php.ini, but this is how to do it if you don't have access to that
date_default_timezone_set('Etc/UTC');
require 'PHPMailerAutoload.php';
//Create a new PHPMailer instance
$mail = new PHPMailer;
//Tell PHPMailer to use SMTP
$mail->isSMTP();
//Enable SMTP debugging
// 0 = off (for production use)
// 1 = client messages
// 2 = client and server messages
$mail->SMTPDebug = 4;
//Ask for HTML-friendly debug output
$mail->Debugoutput = 'html';
//Set the hostname of the mail server
$mail->Host = 'smtp.gmail.com';
// use
//$mail->Host = gethostbyname('smtp.gmail.com');
// if your network does not support SMTP over IPv6
//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
$mail->Port = 587;
//Set the encryption system to use - ssl (deprecated) or tls
$mail->SMTPSecure = 'tls';
//Whether to use SMTP authentication
$mail->SMTPAuth = true;
//Username to use for SMTP authentication - use full email address for gmail
$mail->Username = "*******@thepresidenthotel.com";
//Password to use for SMTP authentication
$mail->Password = "************";
//Set who the message is to be sent from
$mail->setFrom('info@medyanova.com', 'Medya Nova');
//Set an alternative reply-to address
$mail->addReplyTo('info@medyanova.com', 'MedyaNova A.S.');
//Set who the message is to be sent to
$mail->addAddress('aslan@ozcakir.com', 'Aslan Ozcakir');
//Set the subject line
$mail->Subject = 'PHPMailer GMail SMTP test';
//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body
$mail->msgHTML('DENEME from: '.$mail->Username);
//Replace the plain text body with one created manually
$mail->AltBody = 'This is a plain-text message body';
//Attach an image file
//$mail->addAttachment('images/phpmailer_mini.png');
//send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}`
--------------------------
####OUTPUT#####
Connection: opening to smtp.gmail.com:587, t=300, opt=array ()
SMTP ERROR: Failed to connect to server: Network is unreachable (101)
SMTP connect() failed.
Mailer Error: SMTP connect() failed.
################
---------------------------
smtp.yandex.com port 587 -- WORKING FINE
---------------------------
`<?php
/**
 * This example shows settings to use when sending via YANDEX servers.
 */
//SMTP needs accurate times, and the PHP time zone MUST be set
//This should be done in your php.ini, but this is how to do it if you don't have access to that
date_default_timezone_set('Etc/UTC');
require 'PHPMailerAutoload.php';
//Create a new PHPMailer instance
$mail = new PHPMailer;
//Tell PHPMailer to use SMTP
$mail->isSMTP();
//Enable SMTP debugging
// 0 = off (for production use)
// 1 = client messages
// 2 = client and server messages
$mail->SMTPDebug = 4;
//Ask for HTML-friendly debug output
$mail->Debugoutput = 'html';
//Set the hostname of the mail server
$mail->Host = 'smtp.yandex.com';
// use
//$mail->Host = gethostbyname('smtp.gmail.com');
// if your network does not support SMTP over IPv6
//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
$mail->Port = 587;
//Set the encryption system to use - ssl (deprecated) or tls
$mail->SMTPSecure = 'tls';
//Whether to use SMTP authentication
$mail->SMTPAuth = true;
//Username to use for SMTP authentication - use full email address for gmail
$mail->Username = "*******@yandex.com";
//Password to use for SMTP authentication
$mail->Password = "*****************";
//Set who the message is to be sent from
$mail->setFrom('***********@yandex.com', 'MedyaNova');
//Set an alternative reply-to address
$mail->addReplyTo('info@medyanova.com', 'MedyaNova A.S.');
//Set who the message is to be sent to
$mail->addAddress('aslan@ozcakir.com', 'Aslan Ozcakir');
//Set the subject line
$mail->Subject = 'PHPMailer Yandex SMTP test';
//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body
$mail->msgHTML('DENEME from Yandex from: '.$mail->Username);
//Replace the plain text body with one created manually
$mail->AltBody = 'This is a plain-text message body';
//Attach an image file
//$mail->addAttachment('images/phpmailer_mini.png');
//send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}
`

---------------------------
####OUTPUT#####
Connection: opening to smtp.yandex.com:587, t=300, opt=array ()
Connection: opened
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "220 smtp2p.mail.yandex.net ESMTP (Want to use Yandex.Mail for your domain? Visit http://pdd.yandex.ru)"
SMTP -> get_lines(): $data is "220 smtp2p.mail.yandex.net ESMTP (Want to use Yandex.Mail for your domain? Visit http://pdd.yandex.ru)"
SERVER -> CLIENT: 220 smtp2p.mail.yandex.net ESMTP (Want to use Yandex.Mail for your domain? Visit http://pdd.yandex.ru)
CLIENT -> SERVER: EHLO testlin.medyanova.com
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "250-smtp2p.mail.yandex.net"
SMTP -> get_lines(): $data is "250-smtp2p.mail.yandex.net"
SMTP -> get_lines(): $data was "250-smtp2p.mail.yandex.net"
SMTP -> get_lines(): $str is "250-8BITMIME"
SMTP -> get_lines(): $data is "250-smtp2p.mail.yandex.net250-8BITMIME"
SMTP -> get_lines(): $data was "250-smtp2p.mail.yandex.net250-8BITMIME"
SMTP -> get_lines(): $str is "250-PIPELINING"
SMTP -> get_lines(): $data is "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING"
SMTP -> get_lines(): $data was "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING"
SMTP -> get_lines(): $str is "250-SIZE 42991616"
SMTP -> get_lines(): $data is "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616"
SMTP -> get_lines(): $data was "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616"
SMTP -> get_lines(): $str is "250-STARTTLS"
SMTP -> get_lines(): $data is "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616250-STARTTLS"
SMTP -> get_lines(): $data was "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616250-STARTTLS"
SMTP -> get_lines(): $str is "250-AUTH LOGIN PLAIN XOAUTH2"
SMTP -> get_lines(): $data is "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616250-STARTTLS250-AUTH LOGIN PLAIN XOAUTH2"
SMTP -> get_lines(): $data was "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616250-STARTTLS250-AUTH LOGIN PLAIN XOAUTH2"
SMTP -> get_lines(): $str is "250-DSN"
SMTP -> get_lines(): $data is "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616250-STARTTLS250-AUTH LOGIN PLAIN XOAUTH2250-DSN"
SMTP -> get_lines(): $data was "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616250-STARTTLS250-AUTH LOGIN PLAIN XOAUTH2250-DSN"
SMTP -> get_lines(): $str is "250 ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $data is "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616250-STARTTLS250-AUTH LOGIN PLAIN XOAUTH2250-DSN250 ENHANCEDSTATUSCODES"
SERVER -> CLIENT: 250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616250-STARTTLS250-AUTH LOGIN PLAIN XOAUTH2250-DSN250 ENHANCEDSTATUSCODES
CLIENT -> SERVER: STARTTLS
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "220 Go ahead"
SMTP -> get_lines(): $data is "220 Go ahead"
SERVER -> CLIENT: 220 Go ahead
CLIENT -> SERVER: EHLO testlin.medyanova.com
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "250-smtp2p.mail.yandex.net"
SMTP -> get_lines(): $data is "250-smtp2p.mail.yandex.net"
SMTP -> get_lines(): $data was "250-smtp2p.mail.yandex.net"
SMTP -> get_lines(): $str is "250-8BITMIME"
SMTP -> get_lines(): $data is "250-smtp2p.mail.yandex.net250-8BITMIME"
SMTP -> get_lines(): $data was "250-smtp2p.mail.yandex.net250-8BITMIME"
SMTP -> get_lines(): $str is "250-PIPELINING"
SMTP -> get_lines(): $data is "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING"
SMTP -> get_lines(): $data was "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING"
SMTP -> get_lines(): $str is "250-SIZE 42991616"
SMTP -> get_lines(): $data is "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616"
SMTP -> get_lines(): $data was "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616"
SMTP -> get_lines(): $str is "250-AUTH LOGIN PLAIN XOAUTH2"
SMTP -> get_lines(): $data is "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616250-AUTH LOGIN PLAIN XOAUTH2"
SMTP -> get_lines(): $data was "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616250-AUTH LOGIN PLAIN XOAUTH2"
SMTP -> get_lines(): $str is "250-DSN"
SMTP -> get_lines(): $data is "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616250-AUTH LOGIN PLAIN XOAUTH2250-DSN"
SMTP -> get_lines(): $data was "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616250-AUTH LOGIN PLAIN XOAUTH2250-DSN"
SMTP -> get_lines(): $str is "250 ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $data is "250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616250-AUTH LOGIN PLAIN XOAUTH2250-DSN250 ENHANCEDSTATUSCODES"
SERVER -> CLIENT: 250-smtp2p.mail.yandex.net250-8BITMIME250-PIPELINING250-SIZE 42991616250-AUTH LOGIN PLAIN XOAUTH2250-DSN250 ENHANCEDSTATUSCODES
Auth method requested: UNKNOWN
Auth methods available on the server: LOGIN,PLAIN,XOAUTH2
Auth method selected: LOGIN
CLIENT -> SERVER: AUTH LOGIN
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "334 VXNlcm5hbWU6"
SMTP -> get_lines(): $data is "334 VXNlcm5hbWU6"
SERVER -> CLIENT: 334 VXNlcm5hbWU6
CLIENT -> SERVER: cHJlc2lkZW50aG90ZWwzNEB5YW5kZXguY29t
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "334 UGFzc3dvcmQ6"
SMTP -> get_lines(): $data is "334 UGFzc3dvcmQ6"
SERVER -> CLIENT: 334 UGFzc3dvcmQ6
CLIENT -> SERVER: MTJ0aDM0ZXByZXNpZGVudA==
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "235 2.7.0 Authentication successful."
SMTP -> get_lines(): $data is "235 2.7.0 Authentication successful."
SERVER -> CLIENT: 235 2.7.0 Authentication successful.
CLIENT -> SERVER: MAIL FROM:<presidenthotel34@yandex.com>
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "250 2.1.0 <presidenthotel34@yandex.com> ok"
SMTP -> get_lines(): $data is "250 2.1.0 <presidenthotel34@yandex.com> ok"
SERVER -> CLIENT: 250 2.1.0 <presidenthotel34@yandex.com> ok
CLIENT -> SERVER: RCPT TO:<aslan@ozcakir.com>
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "250 2.1.5 <aslan@ozcakir.com> recipient ok"
SMTP -> get_lines(): $data is "250 2.1.5 <aslan@ozcakir.com> recipient ok"
SERVER -> CLIENT: 250 2.1.5 <aslan@ozcakir.com> recipient ok
CLIENT -> SERVER: DATA
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "354 Enter mail, end with "." on a line by itself"
SMTP -> get_lines(): $data is "354 Enter mail, end with "." on a line by itself"
SERVER -> CLIENT: 354 Enter mail, end with "." on a line by itself
CLIENT -> SERVER: Date: Wed, 13 Sep 2017 19:47:57 +0000
CLIENT -> SERVER: To: Aslan Ozcakir <aslan@ozcakir.com>
CLIENT -> SERVER: From: MedyaNova <presidenthotel34@yandex.com>
CLIENT -> SERVER: Reply-To: "MedyaNova A.S." <info@medyanova.com>
CLIENT -> SERVER: Subject: PHPMailer Yandex SMTP test
CLIENT -> SERVER: Message-ID: <984513000405f3eeccd78b5088affefb@testlin.medyanova.com>
CLIENT -> SERVER: X-Priority: 3
CLIENT -> SERVER: X-Mailer: PHPMailer 5.2.9 (https://github.com/PHPMailer/PHPMailer/)
CLIENT -> SERVER: MIME-Version: 1.0
CLIENT -> SERVER: Content-Type: multipart/alternative;
CLIENT -> SERVER: boundary="b1_984513000405f3eeccd78b5088affefb"
CLIENT -> SERVER: Content-Transfer-Encoding: 8bit
CLIENT -> SERVER: 
CLIENT -> SERVER: --b1_984513000405f3eeccd78b5088affefb
CLIENT -> SERVER: Content-Type: text/plain; charset=us-ascii
CLIENT -> SERVER: 
CLIENT -> SERVER: This is a plain-text message body
CLIENT -> SERVER: 
CLIENT -> SERVER: 
CLIENT -> SERVER: --b1_984513000405f3eeccd78b5088affefb
CLIENT -> SERVER: Content-Type: text/html; charset=us-ascii
CLIENT -> SERVER: 
CLIENT -> SERVER: DENEME from Yandex from: presidenthotel34@yandex.com
CLIENT -> SERVER: 
CLIENT -> SERVER: 
CLIENT -> SERVER: 
CLIENT -> SERVER: --b1_984513000405f3eeccd78b5088affefb--
CLIENT -> SERVER: 
CLIENT -> SERVER: .
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "250 2.0.0 Ok: queued on smtp2p.mail.yandex.net as 1505332078-wFryKs0bhH-lvb8vXCt"
SMTP -> get_lines(): $data is "250 2.0.0 Ok: queued on smtp2p.mail.yandex.net as 1505332078-wFryKs0bhH-lvb8vXCt"
SERVER -> CLIENT: 250 2.0.0 Ok: queued on smtp2p.mail.yandex.net as 1505332078-wFryKs0bhH-lvb8vXCt
CLIENT -> SERVER: QUIT
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "221 2.0.0 Closing connection."
SMTP -> get_lines(): $data is "221 2.0.0 Closing connection."
SERVER -> CLIENT: 221 2.0.0 Closing connection.
Connection: closed
Message sent!
################

Any ideas? suggestions?

Thanks,
Aslan

**Comment by Synchro** [comment]
This can only be a network issue since the code isn't changing. It's interesting that port 587 works to yandex, in that that must mean you don't have a complete block on that port. Something else must be blocking it. Since port 25 works and has exactly the same security as port 587 (they can both use STARTTLS), I'd go with that.

**Comment by as4wd** [comment]
@Synchro  Thanks for the prompt reply.
What do you suggest to troubleshoot this type of network connectivity issues.  This is a CENTOS 7.3 machine with WHM Cpanel and I have root access.
Best,
Aslan Ozcakir

**Comment by Synchro** [comment]
Look at the troubleshooting guide linked from the error. telnet is the obvious thing to try:

    telnet smtp.gmail.com 587

If that works, confirm with openssl:

    openssl s_client -starttls smtp -connect smtp.gmail.com:587
