### ISSUE TITLE
Message body empty

### ISSUE THREAD

**Issue by raphaelrosello** [PHPMailer/PHPMailer#1166]
# Description
I created a function to send an email and I'm getting the correct response and mail body. However, there are some times I couldn't figure out why I am getting **"Message body empty"** error, but during my second attempt/multiple attempts sending the same email, it works fine.

I checked other similar reported issues that deals with empty body
[this](https://stackoverflow.com/questions/13816571/phpmailer-mailer-error-message-body-empty)
 [this](https://stackoverflow.com/questions/6736899/phpmailer-sending-attachments-but-not-the-body)
#290 

I tried using the code below but nothing helped.
```
$this->mail->isHTML(true);
$this->mail->Body = $mailBody;
```

Also tried
`$this->mail->msgHTML($mailBody);`

# Code to reproduce
    $this->mail->isSMTP();
    $this->mail->SMTPDebug = 2;
    $this->mail->Debugoutput = 'html';
    $this->mail->Host = 'smtp.gmail.com';
    $this->mail->Port = '587';
    $this->mail->SMTPSecure = 'tls';
    $this->mail->SMTPAuth = true;
    $this->mail->Username = 'email@gmail.com';
    $this->mail->Password = 'password';
    $this->mail->AltBody = 'ALT BODY';
    $this->mail->CharSet = 'UTF-8';

    $this->mail->Subject = $data['subject'];
    $this->mail->setFrom("email@gmail.com", $data['sender']);
    $this->mail->addReplyTo("do-not-reply@gmail.com", $data['DO_NOT_REPLY']);
    $this->mail->addAddress($data['email'], $data['name']);

    ob_start();
    $base_path = "/storage/email/{$email}.php";
    include base_path().$base_path;
    $mailBody = ob_get_clean();

    $this->mail->isHTML(true);
    $this->mail->Body = $mailBody;
    echo $mailBody;

    if (!$this->mail->send()) {
      throw new \Exception('Message not sent. ' . $this->mail->ErrorInfo);
    }

# Expected behavior
- Email should be sent without "Message body empty" error

# Actual behavior
I tried sending the email twice
1st attempt:

- Email was not sent
- $mailBody was empty
- Message body empty error
- There was no debug output

2nd attempt
- Email was sent
- Mail body was displayed

**I'm using:** 
- PHP 5.6
- PHPMailer 6.0

**Comment by Synchro** [comment]
The most likely explanation is that `$mailBody` is empty. Can you demonstrate a case where `$mailBody` is not empty and you still get the error? [The code that checks it](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L1394) is *extremely* simple, so it's hard for it to go wrong.

`SMTPDebug` output is concerned with SMTP-level issues - this error occurs before it even attempts to open a connection. By default it will not send at all if `Body` is empty.

**Comment by raphaelrosello** [comment]
I'm sending a mail body by including a dynamic php file. 
`$email`  is just static filename string of the receipt passed from another function and I'm quite sure that it would not return empty

```
ob_start();
$base_path = "/storage/email/{$email}.php";
include base_path().$base_path;
$mailBody = ob_get_clean();
```

If it would also help, I'm using Lumen 5.3 and Beanstalkd driver for email queuing.

**Comment by Synchro** [comment]
Don't assume, check.

**Comment by rersheed** [comment]
I am this issue. I have some text in the body but it is still returning "Mailer Error: Message body empty". Please help me out
here is my code:
`
<?php
/**
 * This example shows making an SMTP connection without using authentication.
 */
// path to phpmailer classes
require 'src/Exception.php';
require 'src/PHPMailer.php';
require 'src/SMTP.php';

//Import the PHPMailer class into the global namespace
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

//SMTP needs accurate times, and the PHP time zone MUST be set
//This should be done in your php.ini, but this is how to do it if you don't have access to that
date_default_timezone_set('Etc/UTC');

//Create a new PHPMailer instance
$mail = new PHPMailer;
//Tell PHPMailer to use SMTP
$mail->isSMTP();
//Enable SMTP debugging
// SMTP::DEBUG_OFF = off (for production use)
// SMTP::DEBUG_CLIENT = client messages
// SMTP::DEBUG_SERVER = client and server messages
$mail->SMTPDebug = SMTP::DEBUG_SERVER;
//Set the hostname of the mail server
$mail->Host = 'localhost';
//Set the SMTP port number - likely to be 25, 465 or 587
$mail->Port = 587;
//We don't need to set this as it's the default value
//$mail->SMTPAuth = false;
//Set who the message is to be sent from
$mail->setFrom('info@phy***ss.com', 'First Last');
//Set an alternative reply-to address
$mail->addReplyTo('info@phy***ss.com', 'First Last');
//Set who the message is to be sent to
$mail->addAddress('re***ed@gmail.com', 'Mr X');
//Set the subject line
$mail->Subject = 'PHPMailer SMTP without auth test';

//Replace the plain text body with one created manually
$body = 'This is the HTML message body <b>in bold!</b>';
$altbody = 'This is the body in plain text for non-HTML mail clients';
$mail->Body    = $body;
$mail->AltBody = $altbody;
//Attach an image file
//send the message, check for errors
if (!$mail->send()) {
    echo 'Mailer Error: '. $mail->ErrorInfo;
} else {
    echo 'Message sent!';
}
`

**Comment by Synchro** [comment]
That code works perfectly for me, so there's something else going on in your system.
