### ISSUE TITLE
Where can I download the full set of PHPMailer  ?

### ISSUE THREAD

**Issue by CPYBusiness** [PHPMailer/PHPMailer#1167]
I tried to download the PHPMailer from below link: 
https://github.com/PHPMailer/PHPMailer
"Download ZIP"
https://github.com/PHPMailer/PHPMailer/archive/master.zip

But just some files only, it is not the full set of files.

Where can I download the full set of PHPMailer? In order I can upload them to the server directly.

**Comment by Synchro** [comment]
The tarball/zip only includes things that are needed to use it - so it's missing docs, tests and examples, none of which are needed for use or deployment.

**Comment by Synchro** [comment]
If you want the whole lot, do a git clone.
