### ISSUE TITLE
PHPMailer addStringAttachment causes error 500 for paypal ipn

### ISSUE THREAD

**Issue by carstengrimm** [PHPMailer/PHPMailer#1168]
It's a very individual matter but let's try this.

# I am using the latest version of phpmailer 6.0.1 via composer / php 7.1.7

I am running phpmailer on my localhost (testing via ngrok to expose) to send emails with pdf attachments on the fly which works for the most part, (some background info: which is somewhat creating an invoice mail + pdf attachment after a payment has been made with several gateways) 

i am actually using the same code for of the gateways, and while everything is 100% identical, it does not seem to work just for one payment method, which is paypal ipn. i don't want to bother with the IPN Script itself, because everything works flawless there. It'll send emails and everything works as expected **until** i add the following line: 

` $mail->addStringAttachment(file_get_contents($order->url().'/key'.url::paramSeparator().$data['token'].'/invoice'.url::paramSeparator().$order->hash()), $order->hash().'.pdf');`

Please note, on all other payment gateways i am using the very identical line of code and it does not produce any error there...

To sum the line up: 
this specific url is being called where it'll output a pdf (created on the fly) to the browser - calling the url manually does not produce any error either, same line work everywhere else.

While as i said phpmailer (without addstringattachment ) works - just when adding the attachment it won't. 

``` 
namespace Listener;
use PaypalIPN;
use PHPMailer\PHPMailer\PHPMailer;
// outside the return function call
// ...
// ... 


// ...
// we are, now inside a return function
// all used values are set.
$mail = new PHPMailer;
		$mail->CharSet = 'UTF-8';
		$mail->setFrom($site->email(),$site->author());
		$mail->addAddress($order->email());
		$mail->addReplyTo($site->email(),$site->author());
		$mail->Subject = $order->title();
		$mail->Body    = $body;
		// $mail->AltBody = $txtbody;
		$mail->isHTML(true);
		$mail->addStringAttachment(file_get_contents($order->url().'/key'.url::paramSeparator().$data['token'].'/invoice'.url::paramSeparator().$order->hash()), $order->hash().'.pdf');
		if(!$mail->send()) {
				echo 'Message could not be sent.';
				echo 'Mailer Error: ' . $mail->ErrorInfo;
		} else {

		}
```

Obviously unless i comment addstringattachment out, it won't reach the end.  So i basically have pin-pointed it towards this line cf code.

Since I can't access the IPN Script directly, other than the error 500 i can't really tell any further error messages. I have checked apache and php error logs and it does not display anything at all.

Is there something especially conflicting with addStringAttachment?

**Comment by Synchro** [comment]
No, there's nothing amiss with `addStringAttachment`.

You've got 6 function calls inside that `addStringAttachment` call -  so there's plenty to go wrong.
Separate it out - build the URL first and check that, if that's ok, do the HTTP request - then you have the response in hand, so you can write it to a file, echo it or whatever, then deal with emailing it afterwards.

You might want to look into something more controllable than `file_get_contents` as your HTTP client - take a look at Guzzle or pecl_http.
