### ISSUE TITLE
phpmailer send() hangs with gmail OAuth;

### ISSUE THREAD

**Issue by martinvivian** [PHPMailer/PHPMailer#1169]
Please help. I've been researching the issue all day 

# Problem description
Im trying to send an email via GMail. I believe I've successfully followed all of the instructions from
https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2 to a tee
Im using the code from gmail_xoauth.phps shown bellow
however, this is the debug output.... 

# Debug output
2017-09-20 06:54:33 SERVER -> CLIENT: 220 smtp.gmail.com ESMTP j14sm2863319pff.59 - gsmtp
2017-09-20 06:54:33 CLIENT -> SERVER: EHLO ****.********.com
2017-09-20 06:54:34 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [2407:e700:3:1::11]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
2017-09-20 06:54:34 CLIENT -> SERVER: STARTTLS
2017-09-20 06:54:34 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
2017-09-20 06:54:34 CLIENT -> SERVER: EHLO ****.********.com
2017-09-20 06:54:35 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [2407:e700:3:1::11]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8

# Problem description Cont
Thats ALL OF IT ...  IT STOPS THERE
my code includes 

```
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}
```
And neither of those echos are outputted. It's like the send command just hangs.....
The client is not sending the next command to the server....

# Code to reproduce
```
<?php

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\OAuth;

use League\OAuth2\Client\Provider\Google;

require 'vendor/autoload.php';

$email =  "*****@*****.***";
$clientId =  "**********************************.apps.googleusercontent.com";
$clientSecret = "******************************";
$refreshToken =  "*******************************************************************";


$mail = new PHPMailer;
$mail->isSMTP();
$mail->SMTPDebug = 2;
$mail->Host = 'smtp.gmail.com';
$mail->Port = 587;
$mail->SMTPSecure = 'tls';
$mail->SMTPAuth = true;
$mail->AuthType = 'XOAUTH2';
$provider = new Google(
    [
        'clientId' => $clientId,
        'clientSecret' => $clientSecret,
    ]
);
$mail->setOAuth(
    new OAuth(
        [
            'provider' => $provider,
            'clientId' => $clientId,
            'clientSecret' => $clientSecret,
            'refreshToken' => $refreshToken,
            'userName' => $email,
        ]
    )
);
$mail->setFrom($email, 'First Last');
$mail->addAddress('***************', 'Martin Vivian');
$mail->Subject = 'PHPMailer GMail XOAUTH2 SMTP test';
$mail->msgHTML("TEST");
$mail->AltBody = 'This is a plain-text message body';
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}
?>
```

**Comment by martinvivian** [comment]
Ive been burying deep into this problem. Maybe that will help someone tell me whats happening.
It hangs on
OAuth.php getToken() function.
which calls getAccessToken() from League\OAuth2\Client\Provider
```
    public function getAccessToken($grant, array $options = [])
    {
        $grant = $this->verifyGrant($grant);

        $params = [
            'client_id'     => $this->clientId,
            'client_secret' => $this->clientSecret,
            'redirect_uri'  => $this->redirectUri,
        ];
        $params   = $grant->prepareRequestParameters($params, $options);
        $request  = $this->getAccessTokenRequest($params);
        $response = $this->getParsedResponse($request);
        $prepared = $this->prepareAccessTokenResponse($response);
        $token    = $this->createAccessToken($prepared, $grant);
        return $token;
    }
```
that method calls getParsedResponse() which is where things seem to go bad....
```

    public function getParsedResponse(RequestInterface $request)
    {
        try {
            $response = $this->getResponse($request);
        } catch (BadResponseException $e) {
            $response = $e->getResponse();
        }

        $parsed = $this->parseResponse($response);

        $this->checkResponse($response, $parsed);

        return $parsed;
    }
```
The code hangs on   $this->checkResponse($response, $parsed);

SO I var_dump($parsed)  before that and got this...
`array(1) { ["error"]=> string(13) "invalid_grant" }`

Considering that I decided to var_dump($request) and got this
`object(GuzzleHttp\Psr7\Request)#22 (7) { ["method":"GuzzleHttp\Psr7\Request":private]=> string(4) "POST" ["requestTarget":"GuzzleHttp\Psr7\Request":private]=> NULL ["uri":"GuzzleHttp\Psr7\Request":private]=> object(GuzzleHttp\Psr7\Uri)#23 (7) { ["scheme":"GuzzleHttp\Psr7\Uri":private]=> string(5) "https" ["userInfo":"GuzzleHttp\Psr7\Uri":private]=> string(0) "" ["host":"GuzzleHttp\Psr7\Uri":private]=> string(19) "accounts.google.com" ["port":"GuzzleHttp\Psr7\Uri":private]=> NULL ["path":"GuzzleHttp\Psr7\Uri":private]=> string(15) "/o/oauth2/token" ["query":"GuzzleHttp\Psr7\Uri":private]=> string(0) "" ["fragment":"GuzzleHttp\Psr7\Uri":private]=> string(0) "" } ["headers":"GuzzleHttp\Psr7\Request":private]=> array(2) { ["Host"]=> array(1) { [0]=> string(19) "accounts.google.com" } ["content-type"]=> array(1) { [0]=> string(33) "application/x-www-form-urlencoded" } } ["headerNames":"GuzzleHttp\Psr7\Request":private]=> array(2) { ["content-type"]=> string(12) "content-type" ["host"]=> string(4) "Host" } ["protocol":"GuzzleHttp\Psr7\Request":private]=> string(3) "1.1" ["stream":"GuzzleHttp\Psr7\Request":private]=> object(GuzzleHttp\Psr7\Stream)#24 (7) { ["stream":"GuzzleHttp\Psr7\Stream":private]=> resource(51) of type (stream) ["size":"GuzzleHttp\Psr7\Stream":private]=> NULL ["seekable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["readable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["writable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["uri":"GuzzleHttp\Psr7\Stream":private]=> string(10) "php://temp" ["customMetadata":"GuzzleHttp\Psr7\Stream":private]=> array(0) { } } }`

I got lost again here, I dont know what is wrong here.... but maybe that helps someone else help me.

**Comment by Synchro** [comment]
Sounds like you have not provided the correct privileges to the token you created when you made it in your google config? I'm a bit surprised to see it doing HTTP requests during the SMTP connection - have you used the get_oauth_token script successfully?

**Comment by peter279k** [comment]
Hi @martinvivian, I have run this PHPMailer OAuth code successfully.
And I notice that your getting refresh token approach is weird....
I think your approach is not correct.
Please consider the ```get_oauth_token.php``` file and get the correct refresh token.
The ```get_oauth_token.php``` file is available [here](https://github.com/PHPMailer/PHPMailer/blob/master/get_oauth_token.php).

Thanks.
