### ISSUE TITLE
php mailer connection timed out when using for yahoo mail server

### ISSUE THREAD

**Issue by kushal4** [PHPMailer/PHPMailer#1171]
# Problem description
when trying to send mail from yahoo account i am getting error as SMTP -> ERROR: Failed to connect to server: Connection timed out (110) after sending all the credentials to the sender mail
# Code to reproduce
if ($_SERVER["REQUEST_METHOD"] == "POST") {
  //  $to = $_POST["to_snd"];
    //$subject = "My subject";
   // $txt = $_POST["text_snd"];
   // $headers = "From: sensennium.kushal4@gmail.com" . "\r\n" ;
   // if(mail($to,$subject,$txt,$headers))
       // print "Email successfully sent";
   //else
        //print "An error occured";
    //mail($to, $subject, $txt, $headers);
    //echo "snt succesfully  \n";
    $mail = new PHPMailer();
    $mail->IsSMTP();
    //$mail->SMTPAuth = true;
    $mail->Host = "smtp.yahoo.com";
    $mail->Port = 25;
    //$mail->SMTPSecure = 'ssl';
    $mail->SMTPDebug = 4;
    $mail->Username = "bhattacharya.kushal45@yahoo.com";
    $mail->Password = "05051993pom";
    $mail->SetFrom('name@yourdomain.com', 'Web App');
    $mail->Subject = "A Transactional Email From Web App";
    $body=$_POST["text_snd"];
    $address=$_POST["to_snd"];
    $name="kus45";
    $mail->MsgHTML($body);
    $mail->AddAddress($address, $name);
    if($mail->Send()) {
        echo "Message sent!";
    } else {
        echo "Mailer Error: " . $mail->ErrorInfo;
    }
}
# Debug output
SMTP -> ERROR: Failed to connect to server: Connection timed out (110)
<br />SMTP Error: Could not connect to SMTP host.
Mailer Error: SMTP Error: Could not connect to SMTP host.

**Comment by Synchro** [comment]
This is failing to connect at all, not after authentication. Your ISP is probably blocking outbound SMTP. This is covered in the guide in the wiki. I can see that you've based your code on an obsolete example, and that your'e using an old version of PHPMailer. Get the latest, and read the docs in the wiki and readme.

**Comment by kushal4** [comment]
ok thanks

**Comment by kushal4** [comment]
I am using it in ubuntu could you please guide me hoe to troubleshoot whether it is blocked or not
