### ISSUE TITLE
wiki update : SMTP connect() failed

### ISSUE THREAD

**Issue by darkworks** [PHPMailer/PHPMailer#1179]
Problem  : i was getting : SMTP connect() failed error from my php application 

solution :  so i followed this wiki link : https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting i followed and checked all possibilities mentioned in SMTP connect() failed section including DNS check , ping gmail ,telnet gmail it 587 , ports checks , gmail less secure option enabled etc all were ok i was getting still SMTP connect() failed then i fixed my problem like that 
-> i login to that gmail account from my PC
-> then i visited : https://accounts.google.com/UnlockCaptcha
it promoted me that captcha is unlocked now i can signin into gmail account from another device or application 
-> then i execute my php mail function on server and it bingoo it sent mail 

so request kindly   update : https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

thanks

**Comment by Synchro** [comment]
The "SMTP connect() failed" message appears *after* all the useful information about *why* it failed that is shown if you set `SMTPDebug = 2`. That usually includes gmail's "5.7.14 Please log in via your web browser" error message which is mentioned in the guide, which then provides a link to [google's support doc](https://support.google.com/mail/answer/7126229?visit_id=1-636421412719097435-3905978592&rd=2#cantsignin) on the subject, which includes that link. I'm averse to including that link directly as it's yet another thing to maintain, and it's something that google should be doing, not package maintainers, but I have added it anyway.

**Comment by Synchro** [comment]
BTW wikis are publicly editable.

**Comment by darkworks** [comment]
ok thanks for updating wiki ...
