### ISSUE TITLE
SMTP ERROR: Password command failed: 535 Incorrect authentication data

### ISSUE THREAD

**Issue by Sebaortiz** [PHPMailer/PHPMailer#1189]
Im trying to send an email via GMail with unsuccessfully results

## Debug output

> 2017-10-07 22:17:54 SERVER -> CLIENT: 220-srv18.benzahosting.cl ESMTP Exim 4.89 #1 Sat, 07 Oct 2017 19:17:54 -0300 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail.
> 2017-10-07 22:17:54 CLIENT -> SERVER: EHLO  myweb.com 
> 2017-10-07 22:17:54 SERVER -> CLIENT: 250-srv18.benzahosting.cl Hello myweb.com [131.72.236.68]250-SIZE 52428800250-8BITMIME250-PIPELINING250-AUTH PLAIN LOGIN250-STARTTLS250 HELP
> 2017-10-07 22:17:54 CLIENT -> SERVER: STARTTLS
> 2017-10-07 22:17:54 SERVER -> CLIENT: 220 TLS go ahead
> SMTP Error: Could not connect to SMTP host.
> 2017-10-07 22:17:54 CLIENT -> SERVER: QUIT
> 2017-10-07 22:17:54 SERVER -> CLIENT: 221 srv18.benzahosting.cl closing connection
> SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
> Message has been sent

## Code to reproduce

```
<?php
require 'src/PHPMailer.php';
require 'src/SMTP.php';
require 'src/Exception.php';
 if (isset($_POST['submit']))
$para = $_POST['email'];

$mail = new PHPMailer\PHPMailer\PHPMailer;                              // Passing `true` enables exceptions
try {
    $mail->SMTPDebug = 2;                                 // Enable verbose debug output
    $mail->isSMTP();                                      // Set mailer to use SMTP
    $mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
    $mail->Port = 587;                                    // TCP port to connect to    
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = "xxxx@gmail.com";                 // SMTP username
    $mail->Password = "xxxxxxxx";                           // SMTP password
    //Recipients
    $mail->setFrom('xxxx@gmail.com', 'Mailer');
    $mail->AddAddress("xxxx@gmail.com");
    $mail->FromName   = "Email Mailer"; 
    //Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = 'Email From web'; 
    $mail->Body='
     Email:  '.$_POST['email'].'<br />
    <br /><br /> 
		'; 
    $mail->send();
    echo 'Message has been sent';
} catch (Exception $e) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
}
}
?>
```

**Comment by Synchro** [comment]
This is a TLS failure, and it’s covered in the troubleshooting guide linked from the error message.

**Comment by Sebaortiz** [comment]
Hi Synchro, I checked this guide, but is not able to make it work

**Comment by R1c2rdo** [comment]
I had the same problem using Gmail and I solved it by downloading the cacert.pem certificate from the site https://curl.haxx.se/docs/caextract.html You should write in the php.ini file the  follows: 
extension = php_openssl.dll 
openssl.cafile = C:\ xampp\php\extras\ssl\cacert.pem 

It must be activated in the GMail account in the label: Access and security the option: Allow less secure apps access: ON

This solution is thanks to the matteobin user contribution of stackoverflow
