### ISSUE TITLE
why preg_replace() ?

### ISSUE THREAD

**Issue by AlexeyPrats** [PHPMailer/PHPMailer#1192]
hello
file **PHPMailer.php, function addOrEnqueueAnAddress()**
contains row (there's few actually): _`$name = trim(preg_replace('/[\r\n]+/', '', $name)); //Strip breaks and trim`_
But PHP.net says you have to use _`trim(str_replace(array("\r","\n"),'',$name));`_ instead because it's faster:
> If you don't need fancy replacing rules (like regular expressions), you should always use this function instead of preg_replace(). 
http://php.net/manual/en/function.str-replace.php

**Comment by Synchro** [comment]
It might be true in an academic sense, but it really doesn't make any practical difference. I did a quick benchmark and the difference for 500mb of data is around 0.05 sec - but where it's used at this in PHPMailer the typical data is rarely longer than 100 bytes, and doesn't require any replacement at all. A test of 3 lines of input data makes it 0.0002sec vs 0.00016 sec, i.e. this is a meaningless micro-optimisation - either implementation is fine. Make a PR if you can be bothered!
