### ISSUE TITLE
Mailserver breaks S/MIME signing by downgrading 8bit to 7bit encoding

### ISSUE THREAD

**Issue by Tibbel** [PHPMailer/PHPMailer#1195]
Hi,
i have detected some problems with different mail-servers in the internet with S/MIME signed emails.
The test mails are signed correct, but it seems that some mailserver change the content of the email by downgrading 8bit to 7bit encoding.

A diff of the original send mail body and the received mail bodys from different email provider points out, that mail encoding is changed by the mail server as followed:

Original mail body S/MIME signature is correct with 8bit encoding:
------9B379EF82EFCE29576534CA7E216CCEC
Content-Type: multipart/mixed;
	boundary="b1_RLepWzFJGDCcd9mOKAPGZURYxF9yZokvNCMZRm3C0E"
Content-Transfer-Encoding: 8bit

Changed mail body S/MIME signature is broken encoding is now 7bit:
------9B379EF82EFCE29576534CA7E216CCEC
Content-Type: multipart/mixed;
	boundary="b1_RLepWzFJGDCcd9mOKAPGZURYxF9yZokvNCMZRm3C0E"
Content-Transfer-Encoding: 7bit

No other changes are made in the mail body.
For testing i changed the global encoding to 7bit, and all received test mails arrived unchanged and are signed correct.

PHPMailer is 6.0.1
best regards

**Comment by Synchro** [comment]
Hm. That's odd. The automatic downgrade should only occur if the message contents is the same in a 7-bit encoding, i.e. the labelling as 8bit is actually wrong. I'm a bit surprised to see a CTE header there for 7bit, since 7bit is assumed by default, so it doesn't need to specify. Are you saying that your S/MIME encoded body contains 8-bit chars? Or I wonder if it's that the CTE header is included in the message signature, and the CTE change is made after signing - that sounds likely given your experiment.

**Comment by Tibbel** [comment]
Hi, no there are no 8bit chars.
i'm not sure but the downgrading in line 2440 is active and downgrades to 7bit

public function createBody()
Line 2440
        if ('8bit' == $bodyEncoding and !$this->has8bitChars($this->Body)) {


But i think there is no overall 7bit downgrade, because here 8bit is set.
The only point where $this->Encoding is assigend is here, but this line isn't executed

Line 2572
            default:
                // Catch case 'plain' and case '', applies to simple `text/plain` and `text/html` body content types
                //Reset the `Encoding` property in case we changed it for line length reasons
                echo $this->Encoding = $bodyEncoding;


here the overall encoding is set

public function getMailMIME()
line 2360 :
        if ('7bit' != $this->Encoding) {
            // RFC 2045 section 6.4 says multipart MIME parts may only use 7bit, 8bit or binary CTE
            if ($ismultipart) {
                if ('8bit' == $this->Encoding) {
                    echo $result .= $this->headerLine('Content-Transfer-Encoding', '8bit');
                }
                // The only remaining alternatives are quoted-printable and base64, which are both 7bit compatible
            } else {
                $result .= $this->headerLine('Content-Transfer-Encoding', $this->Encoding);
            }
        }


hope that helps

**Comment by Tibbel** [comment]
Hi,

this workaround solves the problem for me,
in public function createBody()
putting:
        if ($this->sign_key_file) {
            $body .= $this->getMailMIME() . static::$LE;
        }

after the downgrading and change the encoding
Line 2470:
        //If lines are too long, and we're not already using an encoding that will shorten them,
        //change to quoted-printable transfer encoding for the alt body part only
        if ('base64' != $altBodyEncoding and static::hasLineLongerThanMax($this->AltBody)) {
            $altBodyEncoding = 'quoted-printable';
        }

        if ( $this->Encoding != $bodyEncoding
            and $altBodyEncoding == $bodyEncoding
            and $this->Encoding == '8bit' )
        {
            $this->Encoding = $bodyEncoding;
        }

        if ($this->sign_key_file) {
            $body .= $this->getMailMIME() . static::$LE;
        }

I think the best is to get a second internal protected Encoding_intern variable
which can be updated for such cases

**Comment by Synchro** [comment]
Could you put that in a fork and make a PR please?

**Comment by Tibbel** [comment]
Sorry forgotten to use
 ./vendor/bin/php-cs-fixer fix
and have made also a change to the AltBody handling

**Comment by Synchro** [comment]
Are you going to make new PRs for these two things? I'm not sure why php-cs-fixer made such a mess of yours – when I run it locally on the current master it doesn't suggest any changes. It should produce readable output (and not change anything) if you run `./vendor/bin/php-cs-fixer --diff --dry-run --verbose fix`, and you should see it pick up the config in `.php_cs`. Maybe you ran it on a newer version of php-cs-fixer - PHPMailer only applies it with the lowest supported PHP version (5.5), which limits what version of php-cs-fixer can be used, so make sure you're using the require-dev packages from PHPMailer's composer and not some external version.

**Comment by Tibbel** [comment]
Yeah, i have just getting the right php-cs-fixer to work, than i create patches

**Comment by Tibbel** [comment]
Where is the best location to get the right version?

**Comment by Synchro** [comment]
You should just be able to do `composer install` in the PHPMailer folder. Then `./vendor/bin/php-cs-fixer` should be the right version.
