### ISSUE TITLE
Mail server breaks S/MIME signing by modifying mail body

### ISSUE THREAD

**Issue by Tibbel** [PHPMailer/PHPMailer#1197]
Hi and sorry for just opening a new issue.
But the german United Internet mail server software drives my crazy.

The problem the software just changes the mail body and S/MIME verifying fails.
Is this behaviour legal?

Original send and received UTF-8 body by an ordinary mail server:

```
This is an S/MIME signed message

------3D7CADC57711BA336066DF7BBE805EB3
Content-Type: multipart/mixed;
	boundary="b1_ahuFjTsscywd1feVcScZlyHnhWYAiJxDHwSuuXXrqrM"
Content-Transfer-Encoding: 8bit


This is a multi-part message in MIME format.
--b1_ahuFjTsscywd1feVcScZlyHnhWYAiJxDHwSuuXXrqrM
Content-Type: multipart/alternative;
	boundary="b2_ahuFjTsscywd1feVcScZlyHnhWYAiJxDHwSuuXXrqrM"

--b2_ahuFjTsscywd1feVcScZlyHnhWYAiJxDHwSuuXXrqrM
Content-Type: text/plain; charset=us-ascii

Test: oe ae ue sZ

--b2_ahuFjTsscywd1feVcScZlyHnhWYAiJxDHwSuuXXrqrM
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 8bit

Test: ö ä ü ß


--b2_ahuFjTsscywd1feVcScZlyHnhWYAiJxDHwSuuXXrqrM--
```

But the german United Internet mail server changes the body from
CTE 8bit to 7bit
and
CS: UTF-8 CTE: 8bit to CS: UTF-8 CTE: quoted-printable
and forwarded this message

This is an S/MIME signed message

```
------3D7CADC57711BA336066DF7BBE805EB3
Content-Type: multipart/mixed;
	boundary="b1_ahuFjTsscywd1feVcScZlyHnhWYAiJxDHwSuuXXrqrM"
Content-Transfer-Encoding: 7bit


This is a multi-part message in MIME format.
--b1_ahuFjTsscywd1feVcScZlyHnhWYAiJxDHwSuuXXrqrM
Content-Type: multipart/alternative;
	boundary="b2_ahuFjTsscywd1feVcScZlyHnhWYAiJxDHwSuuXXrqrM"

--b2_ahuFjTsscywd1feVcScZlyHnhWYAiJxDHwSuuXXrqrM
Content-Type: text/plain; charset=us-ascii

Test: oe ae ue sZ

--b2_ahuFjTsscywd1feVcScZlyHnhWYAiJxDHwSuuXXrqrM
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

Test: =C3=B6 =C3=A4 =C3=BC =C3=9F


--b2_ahuFjTsscywd1feVcScZlyHnhWYAiJxDHwSuuXXrqrM--
```

is there a header-field for preventing this
or something like that?

**Comment by Synchro** [comment]
That is fairly bad, but it may be because they have some ancient gateway that is not 8-bit safe, so they are converting your 8bit CTE part to something that is 7-bit safe, i.e. quoted-printable. I don't see any way around that from their point of view (if they are limited that way), but it should work for you if you specify quoted-printable as your encoding to start with, as then the message signature will not change. There is  probably an RFC all about exactly this...

**Comment by Synchro** [comment]
It occurred to me that the same problem may apply to DKIM too - I don't remember offhand if DKIM canonicalisation includes stripping/ignoring CTE.

**Comment by Tibbel** [comment]
okay thanks for your fast answer.
The solution is using the following for S/MIME signed/encrypted Messages:
    $mail->CharSet = 'utf-8';
    $mail->Encoding = 'quoted-printable';

@DKIM I'm going to just check this

**Comment by Tibbel** [comment]
Yes, if the body is changed by the mail server DKIM also failed.

**Comment by Tibbel** [comment]
For me this means using DKIM and/or S/MIME no 8bit encoding could by used,
because of mail servers with 8bit to 7bit downgrading

**Comment by Synchro** [comment]
I found a relevant [RFC section about S/MIME and CTE](https://tools.ietf.org/html/rfc5751#section-3.1.2) that basically says 8bit will only work if you know it will work 🙄

**Comment by Tibbel** [comment]
Just using 7bit encodings for S/MIME and DKIM seems to be the easiest and safest way.
I think a patch like this prevent others from this pitfall
```
if ( dkim== true || smime == true ) {
    $this->Encoding = 'quoted-printable';
}
```
