### ISSUE TITLE
PHPMailer class won't load

### ISSUE THREAD

**Issue by Gnurps** [PHPMailer/PHPMailer#1200]
PHPMailer won't create a new object using $mail = new PHPMailer(true); During installation using Composer, I got this message: 

> Cannot create cache directory /Users/myHome/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache

Is that the reason I cannot create an object?
My ~/.composer directory is owned by root. I had to use sudo when installing Composer. When I tried using sudo while installing PHPMailer, I got a warning to not run Composer as root:
> Do not run Composer as root/super user!

**Comment by Gnurps** [comment]
I should add that the bigger issue is that my production server has the same problem. Running on Windows Server 2012 R2, Composer install and PHPMailer install both ran okay. But my PHP script will not create a new PHPMailer object.

**Comment by Gnurps** [comment]
I fixed the root ownership issue using this command:

> sudo chown -R $USER $HOME/.composer
Then reinstalled PHPMailer with Composer into the project directory and did not get the cache error. But PHPMailer still will not load. Fails when trying to create the object.

**Comment by Synchro** [comment]
I can't tell anything without seeing your loading code. Are you loading `vendor/autoload.php`? Have you imported PHPMailer classes into your namespace with appropriate `use` directives?

**Comment by Gnurps** [comment]
When I have a "use" directive in my code, the page breaks; completely blank. I take it out and the pages loads again.

Excerpts from my code:

> require './vendor/autoload.php';
				$mail = new PHPMailer(true);
			try{	
				echo "made new mailer<br>"; (does not display; nothing happens after that point)
				$mail->IsSMTP();
				$mail->SMTPDebug = 2;
				$mail->Debugoutput = 'html';

				$mail->isHTML(false

**Comment by Synchro** [comment]
It won't work without `use` or explicit fully-qualified class names. `use` needs to be outside any function definition, at the top of your script. Base your code on the examples provided and load it how the readme says.

**Comment by Gnurps** [comment]
I thought the Composer autoload took care of the `use` and class names issues. From the ReadMe.md:

> Alternatively, **if you're not using composer**, copy the contents of the PHPMailer folder into one of the include_path directories specified in your PHP configuration and load each class file manually:
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

**Comment by Synchro** [comment]
No, composer only takes care of autoloading. Namespacing and aliasing is still up to you.

**Comment by Gnurps** [comment]
I added the two use directives and that made the page work. I now understand the problem. I was copying code successfully used on another site, but that site uses v.5.2 and this newer site uses 6.0, which requires the use directives. So you helped me, Mr. Synchro. Thanks.
