### ISSUE TITLE
I cant find v5.2.0-v5.2.3 in the release page

### ISSUE THREAD

**Issue by zqd233** [PHPMailer/PHPMailer#1201]
I wanna download v5.2.0 phpmailer version, but I found some version are not linked in release page, 
just like v5.2.0-v5.2.3, please fix it quickly, thanks !

**Comment by Synchro** [comment]
Why? There should be no compatibility issues with later 5.2 versions, and such old versions are just plain dangerous to deploy since they contain known vulnerabilities.

**Comment by zqd233** [comment]
haha, I am a security researcher, I can handle it, I need to download that code and study the vuln code, so please I  need that phpmailer verson.

**Comment by zqd233** [comment]
hey, bro, if misunderstand what i mean, complete no offence, I like phpmailer, I also give you a star, I just want to download that version, and make some security test. really apprecate your reply

**Comment by Synchro** [comment]
Fair enough! That release predates the move to github, and prior to that releases were not tagged at all, though I have previously added a few back in. I've now added tags (though not releases) for v5.2.0, v5.2.1, and v5.2.2.

**Comment by Synchro** [comment]
No offence taken, BTW - I do get people trying to deploy old versions every now and again!
