### ISSUE TITLE
How to add input field for mobile number

### ISSUE THREAD

**Issue by MuhammadBilalMughal** [PHPMailer/PHPMailer#1202]
Hello Dear,
I Need some help of you.
How to add input field for mobile number

**Comment by Synchro** [comment]
Sorry, this question is nothing to do with PHPMailer. Please refer to PHP and HTML documentation.

**Comment by MuhammadBilalMughal** [comment]
I need phone option in html contact form

**Comment by Synchro** [comment]
Here you go:

    <input type="phone" name="phone">

Time to read some docs for what to do next.

**Comment by MuhammadBilalMughal** [comment]
Thank you Synchro.
