### ISSUE TITLE
Always using tunnel to send email

### ISSUE THREAD

**Issue by hugo-lip** [PHPMailer/PHPMailer#1204]
# Problem description
I've use PHPMailer for a long time, and I've upgrade my webserver as my mailserver, and it fails always when sending mail, I've made the debug and the error was always could not connect to SMTP server. After read the troubleshooting and run all the tests described, I've checked my DNS, mail webserser and everything is ok.
Then i started to debug the code of the src files provided by you. And I saw that you always try to create a TLS session if the mailserver has the TLS option enabled. But this option is not reasonable if I use port 25 and set SMTPAuth to FALSE.

Another issue that i saw is that you try to authenticate even if the TLS was not established, and then you send the credentials in clear.

# Code to reproduce
file PHPMailer.php

ISSUE #1
line 1877:
Original: if ($this->SMTPAutoTLS and $sslext and $secure != 'ssl' and $this->smtp->getServerExt('STARTTLS')) {

Modified: if ($this->SMTPAutoTLS and $sslext and $secure != 'ssl' and $this->smtp->getServerExt('STARTTLS') and $this->SMTPAuth) {

ISSUE #2
The "if ($this->SMTPAuth)" of line 1887 should be included inside the "if ($tls)" statement of line 1880, so only try to send the credentials if tls is established, otherway the credentials will be sent even if the tunnel is not established.

**Comment by Synchro** [comment]
Many mail servers still only support authentication without encryption, so that's not a reasonable thing to insist on. It's not PHPMailer's job to dictate good practices in mail server config; it tries to do its best with what you've got. Unencrypted auth is common on private networks - for example GoDaddy does it for their own internal mail servers.

Using TLS without authentication is also entirely normal and reasonable - in fact it's almost always the case for final delivery steps now - gmail, hotmail, yahoo, etc all do it. If your mail server advertises TLS, then PHPMailer will try to use it, without being asked to, and STARTTLS can work just fine on port 25. If you don't want it to do that (for example if you have a badly configured mail server), turn off `SMTPAutoTLS`.

**Comment by hugo-lip** [comment]
Ok, I understand that that you have to setup the script for all kind of mail servers, but when I ask tls with authentication and for some reason the tls fails you are always sending the credentials no matter if tls was succeed. am i right or I read you code in a wrong way about the "if ($this->SMTPAuth)" of line 1887 outside the  "if ($tls)" statement of line 1880 ??

If i ask for tls and auth at the same time, you should only try the auth after the tls is established with success, otherwise you are sending my auth in clear.

Thanks very much for your help,
Hugo Gomes

**Comment by Synchro** [comment]
I don't see that it will do that:

```
                    if ($tls) {
                        if (!$this->smtp->startTLS()) {
                            throw new Exception($this->lang('connect_host'));
                        }
                        // We must resend EHLO after TLS negotiation
                        $this->smtp->hello($hello);
                    }
                    if ($this->SMTPAuth) {
```

If this tries and fails to STARTTLS, it will not get as far as the auth command - you can see that if initialising TLS fails, an exception is thrown which aborts the connection. Are you seeing some other behaviour? I am slightly suspicious of not bailing if either of the `hello` calls fail.

**Comment by hugo-lip** [comment]
At my mail log I see two "connect" so i was looking why do i  have 2 connects at the same time! 
I don't know exactly why, it can be some extra info of my maillog, i don't see any tries of authentication, so i suppose the exception is thrown.

postfix/smtpd[31618]: connect from myserver[x.x.x.x]
postfix/smtpd[31618]: SSL_accept error from myserver[x.x.x.x]: 0
postfix/smtpd[31618]: lost connection after STARTTLS from myserver[x.x.x.x]
postfix/smtpd[31618]: connect from myserver[x.x.x.x]
postfix/smtpd[31618]: disconnect from myserver[x.x.x.x]

My problem it can something with the certificates probably, i will investigate more my certificates.
But thank you very much for your answers.
Regards

**Comment by Synchro** [comment]
That looks like it's failing STARTTLS (probably easily diagnosed with openssl), but I'm not sure where the second connect comes from. How does it look from the client side with `SMTPDebug = 3`?
