### ISSUE TITLE
PHPMailer is slow, but with attachment is very FAST

### ISSUE THREAD

**Issue by jackdaniel9** [PHPMailer/PHPMailer#1206]
Hi,

When i send a email with PHPMailer, is very slow, but when i add attachment, PHPMailer is very fast and instantaneous. Am the only person who knows this mysterous problem ?

I use  :
$mail->isHTML(true);
$mail->isSMTP();
$mail->SMTPKeepAlive = true;
$mail->SMTPAuth = true;
$mail->SMTPSecure = "ssl";
$mail->SmtpClose();
$mail->Port...

and all other params

PHP 5.5

**Comment by Synchro** [comment]
Why are you calling `$mail->SmtpClose();`? That's entirely unnecessary - and will break keepalive.

As for your issue, I can't tell from this code, and I'd need to see the output with `SMTPDebug = 2`, as the bug template (which you ignored) requests.

**Comment by luciminea** [comment]
I got the same issue, the emails are being sent with considerable delays. Here's the original mail, received ina gmail acount. I should mention from the start, that is code is working on a xampp setup, but the email was sent trough a live server, as you can see.


Message ID | <xsGZ5BZOltcNVrlXbYmSpuYLfGnKmp3tHOXZwzehCPY@localhost>
-- | --
Fri, Nov 3, 2017 at 11:17 AM (**Delivered after 46 seconds**)
Adrian  Malanca Photography <no-reply@adrianmalancaphotography.com>Using  PHPMailer 6.0.1 (https://github.com/PHPMailer/PHPMailer)
Resetare parola <lucianminea@gmail.com>
Resetarea parolei pentru www.adrianmalancaphotography.com
NEUTRAL with IP 77.81.165.28 Learn more


Delivered-To: lucianminea@gmail.com
Received: by 10.129.87.129 with SMTP id l123csp1952542ywb;
        Fri, 3 Nov 2017 02:18:18 -0700 (PDT)
X-Google-Smtp-Source: ABhQp+TZDIAk/9W2u7pxGRLIolbk9VlctR/iG1PKEbDuTxnBTg0o7JUlLK0I5UvtDDU5WSFmkTR/
X-Received: by 10.223.187.79 with SMTP id x15mr5074282wrg.146.1509700698749;
        Fri, 03 Nov 2017 02:18:18 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1509700698; cv=none;
        d=google.com; s=arc-20160816;
        b=QRjmy6451O3dhfqV8F3Wa/Phvz3YmLJrRm70vfmj6P9l0yReWb/OmaIy9ZwYQ5uAmS
         Y7HA6x3fVO1cTqe2MHXVX4wVHoBbYKknwSK8CFfsx9XCZksa4WGhpZ/eSb+MCc5lODfB
         c9BthWHmorwjkFfqdMbg2U0334XAGtIHfwshdDPMGBDvKuJOwf/mWOjPI20+fwf8P4lp
         YBvKId3kOIk6mdsQzR8nIN8Ch6Ime5Tq1aRS6AuVSMilBnIA00Ijg4U+KTmVfByY9Tdi
         mox1rmC9xAaHzMAa+WFM1vHqMWb8s8bQqryG+ri4NBVhMiGJl3aDk+82aE6YG8SIZMmf
         12oA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=content-transfer-encoding:mime-version:message-id:subject:reply-to
         :from:to:date:arc-authentication-results;
        bh=vWmJbpibQr/uKWCBBe8zl16z6cFRnf5HVmsm6LksTGg=;
        b=uafxrYurIS4nLnZzLVPEpnfEkvSMlIsSxHNwGO4WetsFHXnEal9c/AU6bSHbkmIxkv
         djvvotl5NzAKbGQVpE21rIyMNqT3ix43JlrORzj/VjmgQpaESO/e/EK3h4gVWZkB5SgH
         MSv0pBZvLfrIBKkrncveRauMMpQKDBIB9JnoppbDI4TXNJJtWCl0/taySCTcRtxR7q/D
         PPxBq4Pr6fwdrPaHpPNo5uVd/bgiIP3jbpMM665YsIVV+yQk9KmvwqQkfXlVvLnavU7c
         owbPk8VipLAgEel/xVXGvKokIW6pA2h5vpXtnFfBSM2TJ2dTJ94K6ryC3VIlkTQRwVSg
         IKbg==
ARC-Authentication-Results: i=1; mx.google.com;
       spf=neutral (google.com: 77.81.165.28 is neither permitted nor denied by best guess record for domain of no-reply@adrianmalancaphotography.com) smtp.mailfrom=no-reply@adrianmalancaphotography.com
Return-Path: <no-reply@adrianmalancaphotography.com>
Received: from mail2.filter20.tlh.ro (mail2.filter20.tlh.ro. [77.81.165.28])
        by mx.google.com with ESMTPS id h19si3706247wrc.83.2017.11.03.02.18.18
        for <lucianminea@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 03 Nov 2017 02:18:18 -0700 (PDT)
Received-SPF: neutral (google.com: 77.81.165.28 is neither permitted nor denied by best guess record for domain of no-reply@adrianmalancaphotography.com) client-ip=77.81.165.28;
Authentication-Results: mx.google.com;
       spf=neutral (google.com: 77.81.165.28 is neither permitted nor denied by best guess record for domain of no-reply@adrianmalancaphotography.com) smtp.mailfrom=no-reply@adrianmalancaphotography.com
Received: from c13-96.tlh.ro ([185.171.184.96] helo=mlmediaweb.ro) by servermx02.tlh.ro with esmtpsa (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256) (Exim 4.89) (envelope-from <no-reply@adrianmalancaphotography.com>) id 1eAY7E-0002TK-Jp for lucianminea@gmail.com; Fri, 03 Nov 2017 11:18:17 +0200
Received: from [86.122.49.57] (port=51849 helo=localhost) by sha19.tlh.ro with esmtpsa (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128) (Exim 4.89) (envelope-from <no-reply@adrianmalancaphotography.com>) id 1eAY6Z-0004dW-2j for lucianminea@gmail.com; Fri, 03 Nov 2017 11:17:36 +0200
Date: Fri, 3 Nov 2017 11:17:32 +0200
To: Resetare parola <lucianminea@gmail.com>
From: Adrian Malanca Photography <no-reply@adrianmalancaphotography.com>
Reply-To: No-reply <no-reply@adrianmalancaphotography.com>
Subject: Resetarea parolei pentru www.adrianmalancaphotography.com
Message-ID: <xsGZ5BZOltcNVrlXbYmSpuYLfGnKmp3tHOXZwzehCPY@localhost>
X-Mailer: PHPMailer 6.0.1 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="b1_xsGZ5BZOltcNVrlXbYmSpuYLfGnKmp3tHOXZwzehCPY"
Content-Transfer-Encoding: 8bit
X-OutGoing-Spam-Status: No, score=-1.0
X-AuthUser: no-reply@adrianmalancaphotography.com
X-Originating-IP: 185.171.184.96
X-SpamExperts-Domain: tlh.ro
X-SpamExperts-Username: sha19
Authentication-Results: tlh.ro; auth=pass (login) smtp.auth=sha19@tlh.ro
X-SpamExperts-Outgoing-Class: ham
X-SpamExperts-Outgoing-Evidence: Combined (0.08)
X-Recommended-Action: accept
X-Filter-ID: EX5BVjFpneJeBchSMxfU5k6lHQIV3jcbKLy2ipUVq2MXv9krsgRhBn0ayn6qsUc79AcZyonSUEO9 Y3Gn3iqK0G+bROKuWrA+iZRIcxGcY42Cc3tmKVnlHaljmyHVaOApJODXbtOodkPED+RkHjVGH4fc CHYUH7L4L9SEgoSlEzJf/g81rzx9JZqGaqYbp7LuiQQdCxWzMyWt3ey6cI2WOjcoqxELZtOx3m7z PyksCH3u3kYrgIcf0nr9jTmeEqB4HlosV0u5yqqr+jM2QhmeoUVLjur0nmBMdbwLgWRyN5ihIxGY rpGiiCT4n4tuM4qq1cOifu4tzq7La2fQHLM3aWQhDUY/6ppFCQTOekne2xzCAXiLRwAzucVQJpGq E1PHzJJpy29T5GPauDkR8svuLz3dKxLhoxcmaInYbR5vlqEw7JHzBG2hKqDKQT39beDjeTS27a1r 0/l57bUKP3E48T4/J+l0CWMQke0frkiv2egBIkUL/j1Y48GvmeURQjjEgQeVX0cbgK0DlTzQSPMm 1FHawGPlzIkzwwik3MRn0lPxSlcpNbGCMIWyHSX8aQ+ZOIsZjmYNllieZxx8cJB/neRMyksc0Dx4 iQa9AzGuG3nTPpuFqUUQz+mM8JAD4ECWddPRFJXQZ1CInrDbq4/8JvvX9+BG02ZxXDmk8M78kLTX jDeGdhuSbPsoed9mo5GxAlfKOWDhPHt2hy5MGeqiwUh0KmZkXPKwWo7juk3JjQ3mX4RcoUeFrM8Q OjxymZiSfqb5R4VemuUI6bcEARsm0CMPU9SI2SO7nskF2pPKZ/Tl+30jPRYO1eVGeLkcIIkzmuaT DdMyfEP4pj2K6D/LfGiGa262uaGij8UCZ3XNWrHFxggxnCizXfsLOsXy4IOerKWvhFhwCtRMPPLB 2UFLkA==
X-Report-Abuse-To: spam@servermx01.tlh.ro

--b1_xsGZ5BZOltcNVrlXbYmSpuYLfGnKmp3tHOXZwzehCPY
Content-Type: text/plain; charset=us-ascii

Ati solicitat resetarea parolei pentru accesarea site-ului www.adrianmalancaphotography.com. Daca nu ati solicitat dvs. aceasta operatiune, va rugam sa ne contactati la admin@mlmediaweb.ro. Pentru a va reseta parola va rugam sa va autentificati la www.adrianmalancaphotography.com cu urmatoarele date de acces: Email: lucianminea@gmail.comParola: 7mh*cK/>K2Dupa autentificare, vi se va solicta crearea unei noi parole. Va multumim !

--b1_xsGZ5BZOltcNVrlXbYmSpuYLfGnKmp3tHOXZwzehCPY
Content-Type: text/html; charset=us-ascii

Ati solicitat resetarea parolei pentru accesarea site-ului www.adrianmalancaphotography.com. Daca nu ati solicitat dvs. aceasta operatiune, va rugam sa ne contactati la admin@mlmediaweb.ro. <br><br> Pentru a va reseta parola va rugam sa va autentificati la www.adrianmalancaphotography.com cu urmatoarele date de acces: <br><b>Email:</b> lucianminea@gmail.com<br><b>Parola:</b>7mh*cK/>K2<br><br>Dupa autentificare, vi se va solicta crearea unei noi parole. <br><br>Va multumim !


--b1_xsGZ5BZOltcNVrlXbYmSpuYLfGnKmp3tHOXZwzehCPY--

**Comment by Synchro** [comment]
I can't tell from this where the delays are (`SMTPDebug = 2` output would show that), but it's extremely common for SMTP to be slow, often deliberately so (see greetdelay). The SMTP spec allows response times as long as 10 _minutes_ per command, so a few seconds is normal. If you want to go consistently fast, run a local mail server and submit to it via SMTP to localhost, then the mail server will deal with the delays, not your PHP page scripts.

**Comment by luciminea** [comment]
I think is only slow from local XAMPP, from the live hosting is going very fast. Because of that, I won't mind the local delays. Thank you for your prompt response. The script is awesome, by the way, thank you ! 👍 🥇
