### ISSUE TITLE
I can't get PHPMailer working - i keep getting HTTP Error 500

### ISSUE THREAD

**Issue by kuijsbenjamin** [PHPMailer/PHPMailer#1207]
Hello fellow Github members,

I've been trying to get my PHPMailer working for over a day now reading a lot of forum posts but i can't figure out why it keeps returning an HTTP Error 500.

- I currently use PHPMailer-6.0.1.
- I've made sure GMail accepts apps with a low security level.
- I've used composer to install phpmailer with a positive result. (globally)
- I'm trying to send it running the code a MAMP localhost

MacBook-Air-van-Benjamin:~ benjaminkuijs$ composer require phpmailer/phpmailer
Using version ^6.0 for phpmailer/phpmailer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

Below you can find the index.php file that i've created to send the email - it is based on the Gmail example which is stated within the examples page.

Would someone please help me on this matter?

Your help would be really appreciated!

Kind regards, Benjamin

```php
<?php
//Import PHPMailer classes into the global namespace
use PHPMailer\PHPMailer\PHPMailer;

require '../vendor/autoload.php';
//Create a new PHPMailer instance
$mail = new PHPMailer;
//Tell PHPMailer to use SMTP
//$mail->isSMTP();
//Enable SMTP debugging
// 0 = off (for production use)
// 1 = client messages
// 2 = client and server messages
$mail->SMTPDebug = 2;
//Set the hostname of the mail server
$mail->Host = 'smtp.gmail.com';
// use
// $mail->Host = gethostbyname('smtp.gmail.com');
// if your network does not support SMTP over IPv6
//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
$mail->Port = 587;
//Set the encryption system to use - ssl (deprecated) or tls
$mail->SMTPSecure = 'tls';
//Whether to use SMTP authentication
$mail->SMTPAuth = true;
//Username to use for SMTP authentication - use full email address for gmail
$mail->Username = "test.format.website@gmail.com";
//Password to use for SMTP authentication
$mail->Password = "*******";
//Set who the message is to be sent from
$mail->setFrom('info@qubecargo.com', 'QUBE Cargo');
//Set an alternative reply-to address
$mail->addReplyTo('info@qubecargo.com', 'QUBE Cargo');
//Set who the message is to be sent to
$mail->addAddress('benjaminkuijs@hotmail.com', 'Benjamin Kuijs');
//Set the subject line
$mail->Subject = 'First email send using PHPMailer';
//Set email body
$mail->Body = 'This is the first test Body for the PHPMailer mail';
//send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}
```

**Comment by Synchro** [comment]
One obvious problem - you've commented out the call to `isSMTP`, so most of your config will do nothing at all. Beyond that, you just need to do normal PHP debugging - enable error output, check your web server logs - whatever you're doing wrong will be shown in there. Also please do not post code in PDFs.
