### ISSUE TITLE
gmail credentials too exposed

### ISSUE THREAD

**Issue by krystyna93** [PHPMailer/PHPMailer#1210]
A newbie question here, 
but what is a secure method of using PHPMailer and gmail, without having to expose my email and password in the SMTP?

**Comment by Synchro** [comment]
Pretty much all auth mechanisms for SMTP are not secure by themselves (including OAuth), but they can all be protected by using encryption on the connection, so just set `SMTPSecure = 'tls'` and your ID and pass will not be exposed.

**Comment by krystyna93** [comment]
Ah, well thank you for clarifying that up, that makes it much more clear
