### ISSUE TITLE
phpmailer invalid address (punyEncode) root@localhost

### ISSUE THREAD

**Issue by cschivaz** [PHPMailer/PHPMailer#1212]
I'm just try tp use but i got Error "invalid address (punyEncode) root@localhost"
$mail = new PHPMailer(true);
	try{
	$mail->IsHTML(true);
	$mail->IsSMTP();
	$mail->SMTPAuth = true;
	$mail->SMTPSecure = 'tls';
	$mail->Host = 'smtp.gmail.com';
	$mail->Port = 587; 
	$mail->Username = '********@gmail.com'; 
	$mail->Password = ' *** '; 
	$mail->SetFrom = ('test@gmail.com'); 
	$mail->Subject = 'Test sending mail'; 
	$mail->Body = 'My Body & <b>My Description</b>';
	$mail->AddAddress('testEmail@gmail.com');
	$mail->send(); 
	} catch (Exception $e) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
}

How can i solve this?

**Comment by fbonzon** [comment]
Did you copy this code from an example? If yes, please give the reference, so it can be fixed.

    $mail->SetFrom = ('test@gmail.com');

This is incorrect usage of ```SetFrom```. It is a method, but your code treats it as a variable. Replace with:

    $mail->SetFrom('test@gmail.com');

**Comment by cschivaz** [comment]
Thank you so much.

**Comment by dileepverma107** [comment]
<?php
// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'src/Exception.php';
require 'src/PHPMailer.php';
require 'src/SMTP.php';
require 'src/OAuth.php';
require 'src/POP3.php';


//Load Composer's autoloader
require 'vendor/autoload.php';

$mail = new PHPMailer();                              // Passing `true` enables exceptions
try {
    //Server settings
    $mail->SMTPDebug = 2;                                 // Enable verbose debug output
    $mail->IsSMTP();                              // send via SMTP
$mail->Host = "smtp.gmail.com";
$mail->SMTPAuth = true;                       // turn on SMTP authentication
$mail->Username = "dileepverma107@gmail.com";        // SMTP username
$mail->Password = "aci@#4321";               // SMTP password
$webmaster_email = "dileepverma107@gmail.com";       //Reply to this email ID
                // Recipients email ID
                              // Recipient's name
$mail->setFrom = $webmaster_email;

$mail->FromName = "My Name";
$mail->AddAddress("dileepverma107@gmail.com","Dileep");
$mail->AddReplyTo($webmaster_email,"My Name");
$mail->WordWrap = 50;                         // set word wrap
$mail->IsHTML(true);                          // send as HTML
$mail->Subject = "subject";
$mail->Body = "Hi,
This is the HTML BODY ";                      //HTML Body 
$mail->AltBody = "This is the body when user views in plain text format"; //Text Body 


    $mail->send();
    echo 'Message has been sent';
} catch (Exception $e) {
    echo 'Message could not be sent. Mailer Error: ', $mail->ErrorInfo;
}






Output:
Invalid address: (From): root@localhost
Message has been sent

how can fix it

**Comment by nightw0lv** [comment]
I would suggest you to change your password because I myself tempted to enter in your email and who knows what else ...

**Comment by dileepverma107** [comment]
Thanks for solve my issues

**Comment by istiyakaminsanto** [comment]
```
(<?php
// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require "vendor/autoload.php";

if(isset($_POST['name']) && isset($_POST['email']) && isset($_POST['message'])){
    $name = filter_var($_POST['name'], FILTER_SANITIZE_STRING);
    $email = $_POST['email'];
    $message = $_POST['message'];

    $mail = new PHPMailer(true);                          
    $mail->isSMTP();
    $mail->SMTPDebug = 2;
    $mail->Host = 'smtp.gmail.com';
    $mail->Port = 587;
    $mail->SMTPSecure = 'tls';
    $mail->SMTPAuth = true;
    $mail->Username = "moslemuddin6991@gmail.com";
    $mail->Password = "moslem420";
    $mail->setFrom = $email ;
    $mail->addAddress('istiyakaminsanto@gmail.com', 'Istiyak Amin');
    $mail->isHTML(true);                                  
    $mail->Subject = 'Got one new messege from your website';
    $mail->Body    = '<b>name: </b>' . $name . '<br>' . '<b>Email: </b>' . $email . '<br>' . '<b>Message: </b>' . $message;
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
    $mail->send();

    header('Location: ' . $_SERVER['HTTP_REFERER']);


} 

else header('location: http://istiyak.xyz/#contact');
)
```
**Invalid address: (From): root@localhost

Fatal error: Uncaught PHPMailer\PHPMailer\Exception: Invalid address: (From): root@localhost in /home/worldspo/istiyak.xyz/vendor/phpmailer/phpmailer/src/PHPMailer.php:1428 Stack trace: #0 /home/worldspo/istiyak.xyz/vendor/phpmailer/phpmailer/src/PHPMailer.php(1348): PHPMailer\PHPMailer\PHPMailer->preSend() #1 /home/worldspo/istiyak.xyz/sendMail.php(29): PHPMailer\PHPMailer\PHPMailer->send() #2 {main} thrown in /home/worldspo/istiyak.xyz/vendor/phpmailer/phpmailer/src/PHPMailer.php on line 1428**

**Comment by fbonzon** [comment]
1. You made the same mistake as the original poster. Read again this thread. You should write `    $mail->setFrom($email);`.
2. Remove your password from your code snippet.

**Comment by Mugna00** [comment]
![codicemail](https://user-images.githubusercontent.com/46057469/50373498-4205cb80-05e0-11e9-9636-07155f46fce6.png)
Invalid address: (From): root@localhost

**Comment by dileepverma107** [comment]
Pahele php mailer ki  Error sahi karle bhai

**Comment by mddas** [comment]
$mail->setFrom(yourgmail_adress@gmail.com);
or 
$mail->setFrom($webmaster_email);

this fix your error

**Comment by Qkarendaz** [comment]
// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

// Load Composer's autoloader
require 'vendor/autoload.php';

// Base files 
//require 'PHPMailer/src/Exception.php';
//require 'PHPMailer/src/PHPMailer.php';
//require 'PHPMailer/src/SMTP.php';

// create object of PHPMailer class with boolean parameter which sets/unsets exception.

$mail = new PHPMailer(true);                              

try {

    //server settings...
    $mail->SMTPDebug = 2;
    $mail->isSMTP(); // using SMTP protocol     
                                
    $mail->Host = 'smtp.gmail.com'; // SMTP host as gmail 
    $mail->SMTPAuth = true;  // enable smtp authentication                             
    $mail->Username = 'qkarendaz4real@gmail.com';  // sender email             
    $mail->Password = '09075928834'; // sender email  password                          
    $mail->SMTPSecure = 'tls';  // for encrypted connection                           
    $mail->Port = 587;   // port for SMTP     
    $mail->SMTPOptions = array(
                'ssl' => array(
                'verify_peer' => false,
                'verify_peer_name' => false,
                'allow_self_signed' => true
                )
    );

    //recipients..
    $mail->setFrom("no-reply@tutme.ml", "Tutme"); // sender's email and name
    $mail->addAddress($email, $firstname);  // receiver's email and name
    //$mail->addReplyTo('qkarendaz4real@gmail.com');
    //$mail->addCC('your@email.com');
    //$mail->addBCC('bbcyour@email.com'); // if add email recipeints will not no that a copy is send

    //contents..
    $mail->isHTML(true);
    $mail->Subject = 'Tutme Account Verification';
    $mail->Body    = $msg;
    //convert HTML into a basic plain-text alternative body..
    //$mail->msgHTML(file_get_contents('contents.html'), __DIR__);
    //$mail->AltBody    = "Every thing is possible in this world"; // for non-html mail clients.
    
    // Attachments
   // $mail->addAttachment("img.jpg);
    // $mail->addAttachment("img2.jpg, kkk.jpg);
    $mail->send();

	header("Location: thankyou.php");
}catch (Exception $e)
 {
  // handle error.
    echo "having some issues sending mail. Mailer Error: {$mail->ErrorInfo}";
}




then i get this error...
Invalid address: (to):

**Comment by Synchro** [comment]
This may come as a shock, but that error will be because your `to` address is invalid.

**Comment by Qkarendaz** [comment]
Thank you....  I have resolved the issue
