### ISSUE TITLE
why resend EHLO run twice?

### ISSUE THREAD

**Issue by SuperAmiibo** [PHPMailer/PHPMailer#1219]
i use tls, at the time startTLS, it will connect server failed, if comment out the 2nd EHLO, it work well

if ($this->smtp->connect($prefix . $host, $port, $this->Timeout, $options)) {
                try {
                    if ($this->Helo) {
                        $hello = $this->Helo;
                    } else {
                        $hello = $this->serverHostname();
                    }
                    **$this->smtp->hello($hello);**
                    //Automatically enable TLS encryption if:
                    // * it's not disabled
                    // * we have openssl extension
                    // * we are not already using SSL
                    // * the server offers STARTTLS
                    if ($this->SMTPAutoTLS and $sslext and $secure != 'ssl' and $this->smtp->getServerExt('STARTTLS')) {
                        $tls = true;
                    }
                    /*if ($tls) {
                        if (!$this->smtp->startTLS()) {
                            throw new Exception($this->lang('connect_host'));
                        }
                        // We must resend EHLO after TLS negotiation
                        **$this->smtp->hello($hello);**
                    }*/
                    if ($this->SMTPAuth) {
                        if (!$this->smtp->authenticate(
                            $this->Username,
                            $this->Password,
                            $this->AuthType,
                            $this->oauth
                        )
                        ) {
                            throw new Exception($this->lang('authenticate'));
                        }
                    }

**Comment by Synchro** [comment]
Sending EHLO a second time after TLS negotiation is a *requirement* of the ESMTP specification, which is why it says "We must resend EHLO after TLS negotiation" just before that second call to `hello()`. If your TLS config is broken, it *should* fail. Fix your broken server, don't change PHPMailer to live with it.
