### ISSUE TITLE
AuthType with PHPMailer 

### ISSUE THREAD

**Issue by peetervois** [PHPMailer/PHPMailer#1224]
# Problem description
With relation to PHPMailer version 5.2.25

I have special SMTP server that I do manage myself in order to verify mail transmissions e.t.c. And I had issue with PHPMailer. It was unable to authenticate. On SMTP server log I saw:
`gateway [192.168.2.1] did not issue MAIL/EXPN/VRFY/ETRN during connection to MSA`

While this was not pretty helpful, I have googled around and found after days of searching and head scratching a helpful token: [https://github.com/PHPMailer/PHPMailer/issues/841](https://github.com/PHPMailer/PHPMailer/issues/841)

My problem was that PHPMailer was selecting authentication type from available list:
`Auth methods available on the server: GSSAPI,DIGEST-MD5,CRAM-MD5,LOGIN,PLAIN`
to be  `CRAM-MD5` and failed.

I WILL SUGGEST

to add into troubleshooting chapter some information about which would be preferred authentication method for PHPMailer, how to configure it on sendmail and this great token of info about the

`$mailer->AuthType='LOGIN'`

I've got impression that if one login attempt failed, then next one was not used... this may be handy improvement.

**Comment by Synchro** [comment]
Authentication should be expected to work first time. The credentials remain the same for all the auth mechanisms PHPMailer supports (apart from XOAUTH2), so if a server advertises multiple methods, they should *all* work - if a password is wrong when using CRAM-MD5, it will also be wrong in PLAIN or LOGIN, so retrying with a different method is pointless. If you don't specify, PHPMailer chooses the most secure one it can, and CRAM-MD5 is significantly stronger than LOGIN or PLAIN. 

Now if there is a bug in an auth mechanism that stops it working (as you imply), that's a different matter.

**Comment by peetervois** [comment]
Thanks, then something must be stll wrong with the server I suppose. I am in situation where CRAM-MD5 fails but LOGIN succeeds. I will attach here some logs illustrating the CRAM-MD5 fail:
`
2: SERVER -> CLIENT: 250-arvuti.localdomain Hello gateway [192.168.2.1], pleased to meet you
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-8BITMIME
250-SIZE
250-DSN
250-AUTH GSSAPI DIGEST-MD5 CRAM-MD5 LOGIN PLAIN
250-DELIVERBY
250 HELP

4: Auth method requested: UNKNOWN
4: Auth methods available on the server: GSSAPI,DIGEST-MD5,CRAM-MD5,LOGIN,PLAIN
4: Auth method selected: CRAM-MD5
1: CLIENT -> SERVER: AUTH CRAM-MD5

4: SMTP -> get_lines(): $data is ""
4: SMTP -> get_lines(): $str is  "**HASHREMOVED**"
2: SERVER -> CLIENT: **HASHREMOVED**

1: CLIENT -> SERVER: **HASHREMOVED**

4: SMTP -> get_lines(): $data is ""
4: SMTP -> get_lines(): $str is  "535 5.7.0 authentication failed
"
2: SERVER -> CLIENT: 535 5.7.0 authentication failed

1: SMTP ERROR: Username command failed: 535 5.7.0 authentication failed

4: SMTP Error: Could not authenticate.
1: CLIENT -> SERVER: QUIT
`

**Comment by Synchro** [comment]
(You only need `SMTPDebug = 2` to see enough detail for this, 4 just adds noise).

[CRAM-MD5](https://en.wikipedia.org/wiki/CRAM-MD5) isn't too hard to work through manually (see [here](http://susam.in/blog/auth-cram-md5/)), so I can only suggest that you replicate the mechanism manually with your values to check it. The basic gist is that the server provides a random value (the hash in the `SERVER->CLIENT` bit), then the client hashes it along with the password (or a hash of it), a MAC operation, and sends the value to the server; the server checks to see if its own calculation using its copy of the password produces the same result. I can't check this as I don't have a server that uses CRAM-MD5.

**Comment by AbdealiJK** [comment]
I have the exact same issue - LOGIN works, CRAM-MD5 fails
