### ISSUE TITLE
Helper class to test connection

### ISSUE THREAD

**Issue by piernik** [PHPMailer/PHPMailer#1225]
I'm using 6.0
I have problem with testing connection.
`smtpConnect()` method tests only host and domain - it does not authenticate.

Your example https://github.com/PHPMailer/PHPMailer/blob/master/examples/smtp_check.phps is not compatibile to normal mailer settings:
```
$mailer->Host = '';
$mailer->Port = '';
$mailer->SMTPAuth = true;
$mailer->SMTPSecure = '';
$mailer->SMTPAutoTLS = false;
$mailer->Username = '';
$mailer->Password = '';
```

so it is not the same for testing and sending email - I thing it should.

Now to get *real* test I'm sending dummy mail to get real exceptions.
Can You provide method for propper tests?

**Comment by Synchro** [comment]
That *example* is there to show how to drive the SMTP class directly without PHPMailer acting as a wrapper. They are completely different classes with largely unrelated APIs, so there is no particular reason to drive them in the same way. PHPMailer *uses* SMTP, but PHPMailer is not *a subclass of* SMTP. It would be a simple exercise to wrap what's in that example in a function and call it using your PHPMailer settings.

`smtpConnect()` in the PHPMailer class *does* authenticate if you provide authentication details, so I don't see what you mean here.

**Comment by piernik** [comment]
You're right - `smtpConnect()` works as needed. I don't knwo why I though i does not authenticate.
Thanks for quick response.
