### ISSUE TITLE
$mail->CharSet = 'UTF-8' not working.

### ISSUE THREAD

**Issue by ledikari** [PHPMailer/PHPMailer#1233]
? I asked a question about sending an email with UTF-8 Issue, oddly it disappeared on the issue pages. Is it deleted? 

Anyways, I forgot the name of the guy who assisted me, and i tried modifying the Collate of the table to cater UTF-8, but after checking the encoding on PHP part is is then changed into ASCII.

**Comment by Synchro** [comment]
I closed it because it's not a PHPMailer problem, it's a general PHP + MySQL problem that's happening long before PHPMailer has any involvement. Solve your PHP + MySQL problem, and then PHPMailer will have valid data to work with.
