### ISSUE TITLE
PHPmailer working on own PC, page not loading on Server (1and1)

### ISSUE THREAD

**Issue by philippschiweck** [PHPMailer/PHPMailer#1234]
Hello,

I have a problem concerning PHPmailer on a 1and1 Server.
The following code works flawlessly when hosting it on my own PC, yet when on the 1and1 server, it doesn't work, the page doesn't even load, there are no debug messages (not even getting the echo 'test';)
The PHP file before this code does work, it creates a PDF file and stores it on the server.

This is the code:

	//Send Mail
	echo 'test';
	$mail = new PHPMailer(true);                              // Passing `true` enables exceptions
	echo 'test';
	try {
		//Server settings
		// $mail->SMTPOptions = array(
			// 'ssl' => array(
				// 'verify_peer' => false,
				// 'verify_peer_name' => false,
				// 'allow_self_signed' => true
			// )
		// );
		$mail->SMTPDebug = 3;                                 // Enable verbose debug output
		$mail->isSMTP();                                      // Set mailer to use SMTP
		$mail->Host = 'smtp.1und1.de';  	// Specify main and backup SMTP servers
		$mail->SMTPAuth = true;                               // Enable SMTP authentication
		//$mail->SMTPAuth = false;
		$mail->Username = '******';                 // SMTP username
		$mail->Password = '******'';                           // SMTP password
		$mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
		$mail->Port = 587;                                    // TCP port to connect to

		//Recipients
		$mail->setFrom('******'', 'Feedback');
		$mail->addAddress('******'');     // Add a recipient			
		$mail->AddBCC('******'');			// Name is optional

		//Attachments
		//$mail->addAttachment($newfilename);         // Add attachments

		//Content
		//$mail->isHTML(true);                                  // Set email format to HTML
		$mail->Subject = $name . '_'. $datum . '_' . 'Bug Report';
		$mail->Body    = 'Bug Report als Anhang.';
		$mail->AltBody = 'Bug Report als Anhang.';

		$mail->send();
		//echo 'Message has been sent';
	} catch (Exception $e) {
		echo 'Message could not be sent.';
		echo 'Mailer Error: ' . $mail->ErrorInfo;
	}

**Comment by Synchro** [comment]
If that echo is not appearing, the problem is before you start using PHPMailer. You need to narrow this down further - comment it all out, gradually uncomment it until it stops working, then you've found the point at which it fails, check your web server's log files for errors.

**Comment by Synchro** [comment]
Are you sure it's not waiting for a timeout? Does it show something if you leave it for 10 mins? Many ISPs block outbound SMTP, and that's the usual symptom.

**Comment by philippschiweck** [comment]
Commented the whole mailing part out, now its working flawlessly, the html after the mailing is being displayed correctly. Echo is being displayed as well.
I put an echo into the PDF creating part, not even that is being displayed when the mailing part is in the code.
I called 1and1, they called their internal tech department, asking them if they are blocking outgoing smtp, their response was that it's possible for them to do that, altought they are not.

**Comment by Synchro** [comment]
Don't just believe them - test it to make sure - as described in the troubleshooting guide. And I can see that you didn't wait long enough to establish if it was waiting for a timeout....

**Comment by philippschiweck** [comment]
You're right, I didn't wait long enough, thank you.
After waiting, the following line is displayed:

TestPDFtesttest2017-11-10 14:07:06 Connection: opening to smtp.1und1.de:587, timeout=300, options=array()

and nothing else.
The TestPDF is the first echo, the two following "test" can be seen in my code above.

**Comment by Synchro** [comment]
OK, so your server is being blocked from connecting to the mail server on port 587. Since your server and your mail server are on the same network perhaps try port 25, and you may not need auth either. If that doesn't work, you need to ask 1&1 support.
