### ISSUE TITLE
PHPmail take time to send main in PHP 5.6

### ISSUE THREAD

**Issue by sagarindia** [PHPMailer/PHPMailer#1235]
#806 
Dear Synchro, I have same issue. http://83.110.153.143:9009/login?reset this my site url this page use for reset password.
try here to use a wrong email address example; abcd@xys.com
it load within second because that time PHP mail function not call
but when you enter a correct email id as sagarindia2088@gmail.com it take time to load i start debugging for you. Please check and give me ans.
my PHP version is 5.6.15

**Comment by sagarindia** [comment]
anyone can help me regarding this issue

**Comment by Synchro** [comment]
If you don't read the docs, and don't provide sufficient information in a bug report (as you were asked to do when you created this request), there's nothing anyone can do to help you.

**Comment by sagarindia** [comment]
Dear Synchro, I give you all links when you access that links you got all bugs report because i enable debugging with value 2

**Comment by Synchro** [comment]
You made it sound as if this was something to do with PHPMailer. It's not. You're rejecting addresses if they are not in *your* database. This is obviously quite fast as it's a quick database query, and doesn't involve SMTP nor PHPMailer. Your actual question is how to make sending faster, and that is also discussed in the wiki and guide. Short version - send through a local mail server, not a remote one, and then it will be very fast.

**Comment by sagarindia** [comment]
Ya i am ussing PHP mailer

**Comment by sagarindia** [comment]
Ok i will try it with local server, If i have any issue after that i reply on this issue. Thanks for your suggestion.

**Comment by Synchro** [comment]
You are including PHPMailer in your code, but your check for whether it's an existing user does not involve SMTP - if it did you'd see debug output for that too.

I suggest you turn off debugging on public sites since it is currently displaying an easily decoded id and password.

**Comment by sagarindia** [comment]
Ok, i just enable it for you to debugging
