### ISSUE TITLE
Whats The Problem i hav tried many times. Help me . 

### ISSUE THREAD

**Issue by sikandar0308** [PHPMailer/PHPMailer#1236]
**# Error is** # Code is below
----------------------------------------------------------------------------------------------
_**<2017-11-12 06:44:52 SMTP ERROR: Failed to connect to server: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10060) 2017-11-12 06:44:52 SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting Mail Not >**_
------------------------------------------------------------------------------------------
`<?php
	//getting Data from Form
	$mail_to = $_POST['email'];
	$msg = $_POST['msg'];
	$subject = $_POST['subject'];
	 //Setting  up Sending mail
	require 'PHPMailer-master/PHPMailerAutoload.php';
	$email = new PHPMailer();
	$email ->IsSmtp();
	$email ->SMTPDebug = 1;
	$email ->SMTPAuth = true;
	$email ->SMTPSecure = 'tls';// or ssl on 465
	$email ->Host = "smtp.gmail.com";
	$email ->Port = 587; // or 465 on ssl
	$email ->IsHTML(true);
	$email ->Username = "xyz@gmail.com";
	$email ->Password = "*****";
	$email ->SetFrom("xyz@gmail.com");
	$email ->Subject = $subject;
	$email ->Body = $msg;
	$email ->AddAddress($mail_to);
	
	if(!$email->Send())
	{
		echo "Mail Not Sent";
	}
	else
	{
		"Mail Sent";
	}

?>`
------------------------------------------------------------

**Comment by peter279k** [comment]
Hi, do you use this [sample code](https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail.phps)?
The error code 10060 seems that it cannot receive the server respond.
And I remember that you have to make your account low secure via Google account management page.
Please see more details about [this](https://support.google.com/accounts/answer/6010255).
You can do this and try your code again.
Perhaps I will try your sample code at my available time.

Thanks.

**Comment by Synchro** [comment]
You're using an old version of PHPMailer, so update that first, and you based your code on a long-obsolete example. It would help if you read the docs that the error message points you at, and that the issue template asked you to look at before posting. You have a network problem, probably that your ISP blocks outbound SMTP.
