### ISSUE TITLE
PHPMailer keeps executing

### ISSUE THREAD

**Issue by Webotvorba** [PHPMailer/PHPMailer#1237]
# Problem description
Recently my web started to show 502/504 I have read here that it is mainly problem with ISP but I wanted to hear your opinion on this

I am sending emails by gmail + xoauth using basic example
The script will just keeps going... it wont end it is in kind of loop. I am using fcgi when I switch to FPM it runs ok but I have to use fcgi

# Code to reproduce

 ```
$this->mail = new PHPMailer(true);
        $this->load->config('email');



            $this->mail->isSMTP();

            $this->mail->Priority    = $this->config->item('priority');
            $this->mail->CharSet     = $this->config->item('charset');
            $this->mail->Encoding    = $this->config->item('encoding');
            $this->mail->Timeout     = 100;
            $this->mail->WordWrap    = $this->config->item('wrapchars');

            $this->mail->Host = 'smtp.gmail.com';
            $this->mail->Port = 587;
            $this->mail->SMTPSecure = 'tls';
            $this->mail->SMTPAuth = TRUE;
            $this->mail->AuthType = 'XOAUTH2';

            $email        = $this->config->item('smtp_user');
            $clientId     = $this->config->item('client_id');
            $clientSecret = $this->config->item('client_secret');
            $refreshToken = $this->config->item('refresh_token');

            $provider = new Google(
                [
                    'clientId'     => $clientId,
                    'clientSecret' => $clientSecret,
                ]
            );

            $this->mail->setOAuth(
                new OAuth(
                    [
                        'provider'     => $provider,
                        'clientId'     => $clientId,
                        'clientSecret' => $clientSecret,
                        'refreshToken' => $refreshToken,
                        'userName'     => $email,
                    ]
                )
            );

            $this->mail->SMTPDebug = 3;
            $this->mail->Debugoutput = 'html';

            //Recipients
            $this->mail->setFrom('info@prohormony.sk', 'Mailer');
            $this->mail->addAddress('tichon@webotvorba.sk', 'Joe User');     // Add a recipient

            //Content
            $this->mail->isHTML(true);                                  // Set email format to HTML
            $this->mail->Subject = 'Here is the subject';
            $this->mail->Body    = 'This is the HTML message body <b>in bold!</b>';
            $this->mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

            $this->mail->send();
            $this->mail->clearQueuedAddresses();
            $this->mail->clearAddresses();
            $this->mail->clearCCs();
            $this->mail->clearBCCs();
            $this->mail->clearReplyTos();
            $this->mail->clearAllRecipients();
            $this->mail->clearAttachments();
            $this->mail->clearCustomHeaders();
```
# Debug output
I have no debug since I get 504

**Comment by peter279k** [comment]
Hi, It seems that you're using the Nginx and this is the normal Nginx problem...
The status code 504 Gateway timeout happened because the max execution time need to be larger.
You can also refer this [post](https://www.scalescale.com/tips/nginx/504-gateway-time-out-using-nginx/#) to try to solve the problem.

Thanks.

**Comment by Webotvorba** [comment]
Yes I have nginx. But wont the sxript be running for long then? When I connect to other smtp from another hosting it is working. I mean I cant have people waiting 300 seconds after they submit order for example

**Comment by peter279k** [comment]
Ok, you may consider the message [queue](https://www.sitepoint.com/use-rabbitmq-php/) system.
You can let mail work add the queue so that you won't let people wait 300 seconds after submitting the order.

**Comment by Webotvorba** [comment]
I changed the execution time to 300 and it is working ok. Doesnt take long to proccess script. But I will create some queue system for bulk emails thanks for ideas

**Comment by Synchro** [comment]
Don't bother building your own queuing system for outbound email - just install a local mail server and send through that. It involves a 1-line change in your code and it will just work. This is what mail servers are designed to do.

**Comment by Webotvorba** [comment]
Could you send me any reference how I could do that using phpmailer and gmail? I dont quite understand how that could be achieved

**Comment by Synchro** [comment]
If you want to send through gmail *and* use a local mail server, you need to configure the local mail server to relay through gmail, [like this](http://mhawthorne.net/posts/postfix-configuring-gmail-as-relay.html). I would not ship an app that you expect to run on shared hosting that relies on gmail for email; many large ISPs block outbound SMTP altogether, and require you to relay through their own servers. This also means you can't use gmail from addresses because it would be blocked by gmail's SPF records.
