### ISSUE TITLE
Someone just used your password to try to sign in to your account. Google blocked them, but you should check what happened.

### ISSUE THREAD

**Issue by csandreas1** [PHPMailer/PHPMailer#1239]
I keep receiving this email from google very often when using my contact form to send emails for test. At locations Dublin, Ireland, UK , USA etc. My app is hosted via heroku at dropbox.

> Someone just used your password to try to sign in to your account. Google blocked them, but you should check what happened.

Do i have to worry from this? Why do i receive that?

**Comment by Synchro** [comment]
This may be related to the things that gmail users often run into when setting up auth. Gmail doesn't like seeing new ways of using your gmail account and imposes additional security when it sees one. I'd suggest logging into your gmail account through a normal web browser, and also visiting the [Display unlock CAPTCHA page](https://www.google.com/accounts/DisplayUnlockCaptcha) as described in the troubleshooting guide. You're probably logging errors on the sending side too.
