### ISSUE TITLE
Bad FSF address in License file

### ISSUE THREAD

**Issue by remicollet** [PHPMailer/PHPMailer#1243]
59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

Should be 

    51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

See https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt

Can you please refresh the LICENSE file in this repository

**Comment by Synchro** [comment]
Thanks for letting me know.
