### ISSUE TITLE
Abuse

### ISSUE THREAD

**Issue by keks24** [PHPMailer/PHPMailer#1245]
# Problem description
Your phpmailer was abused to send spam/phising mails

![abuse](https://user-images.githubusercontent.com/13721064/32893309-436b6a7c-cad9-11e7-96b5-f226f9a1c197.png)

[Vorfall: Fischer-BCL218 - Mitteilung von Barclaycard!.txt](https://github.com/PHPMailer/PHPMailer/files/1478650/Vorfall.Fischer-BCL218.-.Mitteilung.von.Barclaycard.txt)

**Comment by Synchro** [comment]
Yes, nothing we can do. The same applies to Outlook, gmail, Apple Mail etc.
