### ISSUE TITLE
New custom header is corrupted at word-wrap column

### ISSUE THREAD

**Issue by fabiodellaria** [PHPMailer/PHPMailer#1248]
Using the 6.0.1 when I add the following command:
$mail->addCustomHeader('List-Unsubscribe', 'https://www.mylongwebsitename.com/folder/action.php?do=action&id=12345678901234567890123456789012');

The result in the final raw message is this:

List-Unsubscribe: https://www.mylongwebsitename.com/folder/action.php?do=action&id=12345678901---SPACEHERE---234567890123456789012

---SPACEHERE--- IS A SINGLE SPACE CHAR!!!

**Comment by Synchro** [comment]
You need to be very careful about your inspection of headers like that. That line is too long for a single header, so it will be folded according to [RFC5322](https://tools.ietf.org/html/rfc5322#section-2.2.3), and I would expect it to appear like this in your raw message:

```
List-Unsubscribe:
 https://www.mylongwebsitename.com/folder/action.php?do=action&id=12345678901
 234567890123456789012
```

That kind of formatting is entirely correct, and the point it's breaking at is exactly where it's expected (78 chars). It is not adding a space in a correctly decoded header - it will be removed when it is unfolded, before it is used. I use this header with longer lines that this  and it works exactly as expected.
