### ISSUE TITLE
How to send mail using php locally

### ISSUE THREAD

**Issue by sharathsr** [PHPMailer/PHPMailer#1251]
Am using this code to send mail, but am facing error, please help me to fix the problem
Here is my code
![capture](https://user-images.githubusercontent.com/33855415/33056668-f0c9b26a-ceac-11e7-9baa-1b742a98eb7e.JPG)
Here is the errors
![capture1](https://user-images.githubusercontent.com/33855415/33056687-0661c09a-cead-11e7-84a6-2f3e99a406e6.JPG)

**Comment by Synchro** [comment]
Please read what the error message says, and read the troubleshooting guide the error links to, which tells you exactly how to deal with this gmail problem. I suggest you remove the error log image (and don't post text as images anyway) since it contains an easily decoded password.

**Comment by sharathsr** [comment]
Thank you for reply, this time i changed the code, here is the code
![github1](https://user-images.githubusercontent.com/33855415/33066115-6ae97116-ced0-11e7-9a4e-c008a4631482.JPG)
But am getting "Message could not be sent.Mailer Error: Could not instantiate mail function." like this, please give me the solution to resolve my problem.

**Comment by Synchro** [comment]
Read the guide - it means you don't have a local mail server configured. In this code, you're also using a very old version of PHPMailer; this is odd because you were using a newer version before.

**Comment by sharathsr** [comment]
Yes you are correct , i used older version of PHPMailer but when am using the newer version of PHPMailer, am getting error like this
![github2](https://user-images.githubusercontent.com/33855415/33067375-f88de698-ced3-11e7-9162-caed8262b8e6.JPG)

**Comment by Synchro** [comment]
That's because you didn't base your code on a provided example, and didn't read the docs/readme.

**Comment by sharathsr** [comment]
![capture](https://user-images.githubusercontent.com/33855415/33071133-5cba26c0-cee0-11e7-9ff0-84bdd4d0e7e8.JPG)
This is code is coded based on the procedures in docs, From this code am facing the errors like this
![capture1](https://user-images.githubusercontent.com/33855415/33071189-92e65bb0-cee0-11e7-85fc-f782a719e8cc.JPG)

**Comment by Synchro** [comment]
Seriously, **this exact error** is covered in [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting). It tells you exactly what to do to fix it. Please stop asking the same question - it won't change my answer or what you need to do.
