### ISSUE TITLE
No TLS Header with SMTP

### ISSUE THREAD

**Issue by kenITR** [PHPMailer/PHPMailer#1252]
phpMailer 5.2.23
isSMTP
SMTPSecure = 'tls'
I am connecting to smtp.sendgrid.net.
Everything works except there is no TLS header in the first hop from my server to sendgrid. (There are TLS headers on subsequent hops)
I can't find any info on this. My recipients are claiming that there is a break in the TLS security enroute.

**Comment by Synchro** [comment]
There's not enough info here. You need to show the rest of your config, a transcript of SMTP traffic (set `SMTPDebug = 2`) and the `Received` headers of a problem message. I recommend upgrading to PHPMailer 6.0 as well.

**Comment by kenITR** [comment]
I sent complete info via email reply, but here are relevant sections:
SMTP debug:[Tue Nov 21 23:32:29.760633 2017] [proxy_fcgi:error] [pid 4895] [client 146.115.73.156:34178] AH01071: Got error 'PHP message: SERVER -> CLIENT: 220 SG ESMTP service ready at ismtpd0006p1iad1.sendgrid.net\r\n\nPHP message: CLIENT -> SERVER: EHLO mydomain\r\n\nPHP message: SERVER -> CLIENT: 250-smtp.sendgrid.net\r\n250-8BITMIME\r\n250-PIPELINING\r\n250-SIZE 31457280\r\n250-STARTTLS\r\n250-AUTH PLAIN LOGIN\r\n250 AUTH=PLAIN LOGIN\r\n\nPHP message: CLIENT -> SERVER: STARTTLS\r\n\nPHP message: SERVER -> CLIENT: 220 Begin TLS negotiation now\r\n\nPHP message: CLIENT -> SERVER: EHLO mydomain\r\n\nPHP message: SERVER -> CLIENT: 250-smtp.sendgrid.net\r\n250-8BITMIME\r\n250-PIPELINING\r\n250-SIZE 31457280\r\n250-STARTTLS\r\n250-AUTH PLAIN LOGIN\r\n250 AUTH=PLAIN LOGIN\r\n\nPHP message: CLIENT -> SERVER: AUTH LOGIN\r\n\nPHP message: SERVER -> CLIENT: 334 VXNlcm5hbWU6\r\n\nPHP message: CLIENT -> SERVER: a2xvb21pc0BpdC1yZXNvdXJjZXMuY29t\r\n\nPHP message: SERVER -> CLIENT: 334 UGFzc3dvcmQ6\r\n\nPHP message: CLIENT -> SERVER: MTY0NlNlbmRHcmlk\r\n\nPHP message: SERVER -> CLIENT: 235 Authentication successful\r\n\nPHP message: CLIENT -> SERVER: MAIL FROM:\r\n\nPHP message: SERVER -> CLIENT: 250 Sender address accepted\r\n\nPHP message: CLIENT -> SERVER: RCPT TO:\r\n\nPHP message: SERVER -> CLIENT: 250 Recipient address accepted\r\n\nPHP message: CLIENT -> SERVER: RCPT TO:\r\n\nPHP message: SERVER -> CLIENT: 250 Recipient address accepted\r\n\nPHP message: CLIENT -> SERVER: DATA\r\n\nPHP message: SERVER -> CLIENT: 354 Continue\r\n\nPHP message: CLIENT -> SERVER: Date: Tue, 21 Nov 2017 23:32:29 -0500\r\n\nPHP message: CLIENT -> SERVER: To: myname@example.com, myname@gmail.com\r\n\nPH

header: Received: from mydomain.com (mail.netriplexboston.com [173.237.192.175]) by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id 8Q0vRrNKTWed5z5y9BLrUA Wed, 22 Nov 2017 04:32:29.754 +0000 (UTC)
Date: Wed, 22 Nov 2017 04:32:31 +0000 (UTC)

It appears that a TSL connection is being established, but no TLS is in the header.

**Comment by Synchro** [comment]
The `received` header is added by sendgrid, so I suggest asking them about it. You could try using `ssl` on port 465, see if it comes out any different.
