### ISSUE TITLE
SMTP Mailgun not received my emails

### ISSUE THREAD

**Issue by standus** [PHPMailer/PHPMailer#1253]
I am using SMTP setting of Mailgun provider. I sent cca 8000 email but they processed only 6500 emails. The have no informations about rest of 1500 emails. When I send it I have condition if($mailer->send()) {} and then I store mailing-id. 
How is possible that thy dont receive my rest emails?

**Comment by Synchro** [comment]
I don't know - ask them.

**Comment by standus** [comment]
I asked them, and as I wrote here they did not receive them.

**Comment by Synchro** [comment]
I assume they only provide an ID after successful submission, so those IDs should be traceable at their end. Look at using `$this->smtp->getLastTransactionID();` to get mailgun's IDs (not the same thing as your message IDs).

**Comment by standus** [comment]
After debug this line:
$smtp_transaction_id = $this->smtp->getLastTransactionID();
I found that my testing email has $smtp_transaction_id = false and at Mailgun log was registered my test email. 
By me this is not solution.

**Comment by standus** [comment]
In this function: protected function recordLastTransactionID()
I see $reply = "250 Great success\r\n"
but function always return false.
In $smtp_transaction_id_patterns is not regex pattern which matches this answer.
See https://www.greenend.org.uk/rjk/tech/smtpreplies.html#DATA

**Comment by standus** [comment]
And another thing is access to $smtp_transaction_id. 
Then protected function smtpSend($header, $body) always return true even if $smtp_transaction_id will be with fail code like now when it $smtp_transaction_id is always false. 
Looks like SMTP class not processing smtp result specification codes (mainly 250 -> success, rest codes -> not success). Like SMTP is not torn to the end.

**Comment by Synchro** [comment]
Ok, so Mailgun does not provide transaction IDs on message acceptance. It's not part of the SMTP specification - all that that asks for is that a successful DATA command returns `250` - anything after it is treated as a comment and will be ignored - and this is a feature that some services do make use of to provide a transaction ID. PHPMailer adheres exactly to this spec. Not matching a pattern in the transaction ID list is not any kind of error or problem, and it's entirely normal for it to be empty. Essentially, if mailgun accepts a message successfully, but then doesn't deliver it, it's a mailgun problem.

**Comment by standus** [comment]
OK, but when Mailgun will not send 250 code then sending is failed. In PHPMailser is not this condition.

**Comment by Synchro** [comment]
Don't be silly, [of course PHPMailer checks for that response code](https://github.com/PHPMailer/PHPMailer/blob/master/src/SMTP.php#L713) in the DATA command. It wouldn't work at all otherwise. If the end of data command responds with anything other than `250`, it's classed as an error and will be reported as such.
