### ISSUE TITLE
SMTP ERROR

### ISSUE THREAD

**Issue by maurohmartinez** [PHPMailer/PHPMailer#1255]
I have a problem trying to send emails using the SMTP class (I am using PHPMailer 5.2).
This is what I got:

2017-11-25 19:05:00 SMTP ERROR: Failed to connect to server: Network is unreachable (101)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

And this is my code (taken from one of the samples provided):

```php
date_default_timezone_set('Etc/UTC');

require 'PHPMailer-5.2-stable/PHPMailerAutoload.php';
$mail = new PHPMailer;
$mail->isSMTP();
$mail->SMTPDebug = 2;
$mail->Debugoutput = 'html';
$mail->Host = 'smtp.gmail.com';
$mail->Port = 587;
$mail->SMTPSecure = 'tls';
$mail->SMTPAuth = true;
$mail->Username = "mhmartinez.1986@gmail.com";
$mail->Password = "enigma9106";
$mail->setFrom('mhmartinez.1986@gmail.com', 'Mauro Martinez');
$mail->addReplyTo('mhmartinez.1986@gmail.com', 'Mauro Martinez');
$mail->addAddress('maurohmartinez@gmail.com', 'Mauro Martinez');
$mail->Subject = 'PHPMailer GMail SMTP test';
$mail->msgHTML(file_get_contents('PHPMailer-5.2-stable/examples/contents.html'), dirname(__FILE__));
$mail->AltBody = 'This is a plain-text message body';
$mail->addAttachment('PHPMailer-5.2-stable/examples/images/phpmailer_mini.png');
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}
```
I have asked my ISP (TMD), and they said they do not block the stmp outbound 587.
What am I missing? Why doesn't work?

I sincerely appreciate your help!

**Comment by Synchro** [comment]
Don't take their word for it - test it, as described in the troubleshooting guide - try `telnet smtp.gmail.com 587` - if that doesn't work from your server, they're blocking it.
BTW there no point in adding a reply-to header that's the same as your from address - it will just be ignored. I hope that's not your real password...

**Comment by dextel2** [comment]
And you're exposing your own password, I'd recommend to hide me it unless it's a dummy account?

**Comment by maurohmartinez** [comment]
Yes.. dummy account! But thanks anyway.

**Comment by hasangursoy** [comment]
Having same issue with latest WP and WP Mail SMTP. telnet is working fine.

**Comment by Synchro** [comment]
@hasangursoy Show your debug output with `SMTPDebug = 3`.

**Comment by hasangursoy** [comment]
```
2017-11-28 08:50:19	Connection: opening to smtp.gmail.com:587, timeout=300, options=array (
                   	                  )
2017-11-28 08:50:19	Connection: opened
2017-11-28 08:50:19	SERVER -> CLIENT: 220 smtp.gmail.com ESMTP 81sm8636027itl.20 - gsmtp
2017-11-28 08:50:19	CLIENT -> SERVER: EHLO intake.sellercloud.com
2017-11-28 08:50:19	SERVER -> CLIENT: 250-smtp.gmail.com at your service, [199.189.62.40]
                   	                  250-SIZE 35882577
                   	                  250-8BITMIME
                   	                  250-STARTTLS
                   	                  250-ENHANCEDSTATUSCODES
                   	                  250-PIPELINING
                   	                  250-CHUNKING
                   	                  250 SMTPUTF8
2017-11-28 08:50:19	CLIENT -> SERVER: STARTTLS
2017-11-28 08:50:19	SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
2017-11-28 08:50:20	SMTP Error: Could not connect to SMTP host.
2017-11-28 08:50:20	CLIENT -> SERVER: QUIT
2017-11-28 08:50:20	SERVER -> CLIENT: MIAJ����Ӫ�~5�7�����ul���ĥ�:�S&g�c|�Z�IuP��8e����0��v�
                   	                  l#�~m"b��V齸����J3�>��hW��ر�&hqK��4(��#�jIGE�8�kg���������n7�m%F?����G�ڨ/
                   	                  \M�@>�ߗY��R�3�VR�V�jt�vԺͨ��Q��U��꘷�����!�4��%������"H皱c*����^���E�ܺ)W�šZo��d�7�~!>�j��~�"$cg>!�|奴�Q,����k�|�&t����N�k�"�\��?�U���M`;�vt�)7
2017-11-28 08:50:20	SMTP ERROR: QUIT command failed: MIAJ����Ӫ�~5�7�����ul���ĥ�:�S&g�c|�Z�IuP��8e����0��v�
                   	                  l#�~m"b��V齸����J3�>��hW��ر�&hqK��4(��#�jIGE�8�kg���������n7�m%F?����G�ڨ/
                   	                  \M�@>�ߗY��R�3�VR�V�jt�vԺͨ��Q��U��꘷�����!�4��%������"H皱c*����^���E�ܺ)W�šZo��d�7�~!>�j��~�"$cg>!�|奴�Q,����k�|�&t����N�k�"�\��?�U���M`;�vt�)7
2017-11-28 08:50:20	Connection: closed
2017-11-28 08:50:20	SMTP Error: Could not connect to SMTP host.
```

**Comment by Synchro** [comment]
Right, so what you originally said is not true; you are not receiving an error that says "Failed to connect to server: Network is unreachable". You have a different TLS problem that is covered in the troubleshooting guide.

**Comment by hasangursoy** [comment]
Oh, sorry. Just saw the smtp connect failed and gmail part :). Is this line showing the resolved IP or the IP from which connection is made?

`smtp.gmail.com at your service, [199.189.62.40]`

**Comment by Synchro** [comment]
```
# host 199.189.62.40
40.62.189.199.in-addr.arpa domain name pointer 199-189-62-40.netfire.rip.
```

It belongs to Netfire, presumably your ISP.

**Comment by hasangursoy** [comment]
So it is showing the IP which smtp.gmail.com should resolve, and it is wrong. It seems it is DNS failure. But the weird thing is on same windows server asp.net is working fine with smtp.gmail.com and successfully sending emails. It also fails on my local Windows machine, same problem, wrong IP resolution.

**Comment by hasangursoy** [comment]
Soryy, and thank you. This solved my issue :) https://stackoverflow.com/a/28759959/259881

**Comment by douglasg14b** [comment]
Same issue here.

The above "fix" is pretty horrible. You're just ignoring potentially forged certs instead of ensuring whoever you're connecting to has a valid one.

**Comment by Synchro** [comment]
Indeed, and that's what the guide says. Th problem that's been coming up with gmail lately is **not** that the server is presenting an invalid cert, but that the client lacks the correct CA certs in order to validate it correctly. So it is a client-side issue, but one that can be fixed by updating the CA cert bundle, again, described in the guide.

**Comment by mananth310** [comment]
how to solve the following error


2019-03-08 10:07:45 Connection: opening to smtp.gmail.com:465, timeout=300, options=array ()
2019-03-08 10:07:46 Connection failed. Error #2: stream_socket_client(): unable to connect to smtp.gmail.com:465 (Network is unreachable) [/home/vcewacin/public_html/faculty1/phpmailer/class.smtp.php line 299]

**Comment by Synchro** [comment]
The clue is in the error message: network is unreachable. That means your ISP is blocking outbound SMTP. Nothing you can do about it from your code - talk to your ISP. This is covered in great detail in the troubleshooting guide linked from the error.
