### ISSUE TITLE
Suddenly SMTP connect() failed. 

### ISSUE THREAD

**Issue by AFwcxx** [PHPMailer/PHPMailer#1264]
# Problem description
It was all working fine, I'm hosting under IBM, they mentioned that they did a maintenance but will not affect. No code was changed and suddenly can't connect to google SMTP.
The https://myaccount.google.com/lesssecureapps is enabled.
I've tried using the same code in a different server and it works.. any idea how to tackle this?

# Code to reproduce
require_once('email/PHPMailerAutoload.php');

$mail = new PHPMailer(true);

$msg = "test";
$subject = "test";
$email = "someone@gmail.com";
$name = 'my name';

$body = $msg;

$mail->IsSMTP()
$mail->SMTPDebug  = 2;
$mail->SMTPAuth   = true;
$mail->SMTPSecure = "ssl";
$mail->Host       = "smtp.gmail.com";
$mail->Port       = 465;
$mail->Username   = "my username";
$mail->Password   = "my password";
$mail->isHTML(true);

$mail->SetFrom('someone@gmail.com', 'someone');

$mail->AddReplyTo("someone@gmail.com","someone");

$mail->Subject    = $subject;

$mail->addAddress($email, $name);

$mail->MsgHTML($body);

if(!$mail->Send()) {

    $error_msg = $mail->ErrorInfo;
    error_log(date('[Y-m-d H:i e] '). "Error message: $error_msg" . PHP_EOL, 3, LOG_FILE);
    error_log(date('[Y-m-d H:i e] '). "Error message: $transaction_id" . PHP_EOL, 3, LOG_FILE);

}

# Debug output
2017-12-05 04:41:47 Connection: opening to ssl://smtp.gmail.com:465, t=10, opt=array ( ) 2017-12-05 04:41:47 SMTP ERROR: Failed to connect to server: (0) 2017-12-05 04:41:47 SMTP connect() failed.

**Comment by AFwcxx** [comment]
Side note,

I did a ping via PHP in that server with:

$host = 'smtp.gmail.com'; 
$port = 465; 
$waitTimeoutInSeconds = 1; 
if($fp = fsockopen($host,$port,$errCode,$errStr,$waitTimeoutInSeconds)){   
   die('it works');
} else {
   die('nope');
} 
fclose($fp);


And "it works"..

**Comment by Synchro** [comment]
Any additional clues if you set `SMTPDebug = 3`, which will show more connection-related output?

**Comment by AFwcxx** [comment]
Sure did sir,
I did the openssl test as stated in my second reply above as well.

With SMTPDebug=3, I get as follow:

2017-12-05 07:19:55 Connection: opening to ssl://smtp.gmail.com:465, t=10, opt=array ( ) 2017-12-05 07:19:55 SMTP ERROR: Failed to connect to server: (0) 2017-12-05 07:19:55 SMTP connect() failed. 

And yes, I've gone through your troubleshooting document as well..

I did however tried this tool:
https://www.yougetsignal.com/tools/open-ports/

and found out that the port 465 is closed.

I've "allow" the port in the inbound and outbound rule in the firewall setting.
Still get the same result.

Any idea?

**Comment by Synchro** [comment]
No, **using openssl**, not just checking that the PHP extension exists, like this (from the guide):

    openssl s_client -starttls smtp -crlf -connect smtp.gmail.com:587

or

    openssl s_client -crlf -connect smtp.gmail.com:465

That port tester is pointless - you don't need port 465 (inbound) open on your own server, and if you check Gmail's port 465, the result is irrelevant because it's not checking from your own server.

**Comment by AFwcxx** [comment]
Is there another way to test this?
I can't install the openssl in the windows server

**Comment by Synchro** [comment]
Can you try `telnet smtp.gmail.com 465`, just to see if it connects? ([info for installing telnet](http://www.sysprobs.com/install-and-enable-telnet-in-windows-8-use-as-telnet-client)).

**Comment by AFwcxx** [comment]
Yeah. I got an empty blank screen. It means the connection is made right?

**Comment by Synchro** [comment]
I'd say not. This is what I get from a working connection (which times out and closes after a few seconds):

```
telnet smtp.gmail.com 465
Trying 64.233.166.109...
Connected to gmail-smtp-msa.l.google.com.
Escape character is '^]'.
Connection closed by foreign host.
```

**Comment by Synchro** [comment]
You can get the openssl binary for windows here: https://www.tbs-certificates.co.uk/FAQ/en/openssl-windows.html

**Comment by AFwcxx** [comment]
Ok. I got the telnet to connect to the smtp.gmail.com 456
Connected to gmail-smtp-msa.l.google.com

hmm..

**Comment by Synchro** [comment]
Looks like you have an SSL problem (which openssl would show) - I suggest trying `SMTPSecure = 'tls'` and `Port = 587` in PHPMailer as you'll get more feedback.

**Comment by AFwcxx** [comment]
I got this for the tls

2017-12-05 08:52:21 Connection: opening to smtp.gmail.com:587, t=10, opt=array ( ) 2017-12-05 08:52:21 SMTP ERROR: Failed to connect to server: An attempt was made to access a socket in a way forbidden by its access permissions. (10013) 2017-12-05 08:52:21 SMTP connect() failed.

**Comment by Synchro** [comment]
That looks like your firewall blocking it. [Info](https://answers.microsoft.com/en-us/ie/forum/ie10-windows_8/an-attempt-was-made-to-access-a-socket-in-a-way/4a955300-4cc6-4b2f-b426-6d6f07e4eddc)

**Comment by AFwcxx** [comment]
I've disabled the firewall and disabled the anti-virus.
Still same result.

**Comment by AFwcxx** [comment]
I got something back:

2017-12-05 09:11:06 Connection: opening to smtp.gmail.com:587, t=10, opt=array ( ) 2017-12-05 09:11:06 Connection: opened 2017-12-05 09:11:06 SERVER -> CLIENT: 220 smtp.gmail.com ESMTP 77sm28486357pfh.43 - gsmtp 2017-12-05 09:11:06 CLIENT -> SERVER: EHLO acev1.sgpmx.com 2017-12-05 09:11:06 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [161.202.188.20] 250-SIZE 35882577 250-8BITMIME 250-STARTTLS 250-ENHANCEDSTATUSCODES 250-PIPELINING 250-CHUNKING 250 SMTPUTF8 2017-12-05 09:11:06 CLIENT -> SERVER: STARTTLS 2017-12-05 09:11:07 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in C:\xampp\htdocs\sgpmx-ace-troy\email\class.smtp.php on line 299
2017-12-05 09:11:07 CLIENT -> SERVER: QUIT 2017-12-05 09:11:07 SERVER -> CLIENT: KGA�r+��"9��Z�Yr˿�!���ra��C�Z���KK����/b��Ǉ5!���s�� �f��~�s�� \�~l}�s���@Ċ��=$��T��5������a��<���W�t�5x-M_��_�Ѧ?hTߴI+��� ��F��8���yE%�s�l>��n��j��j[��`�du>!����[t� ѭڃv@���˯�>0�U]_����(�t!�N^����ۅ�~^�����{�w_x���h�'���Rz��&��P�h��?]�ش�ͺ6��6K��+�,B�Q�v�j�/�˅�sB$��k 2017-12-05 09:11:07 SMTP ERROR: QUIT command failed: KGA�r+��"9��Z�Yr˿�!���ra��C�Z���KK����/b��Ǉ5!���s�� �f��~�s�� \�~l}�s���@Ċ��=$��T��5������a��<���W�t�5x-M_��_�Ѧ?hTߴI+��� ��F��8���yE%�s�l>��n��j��j[��`�du>!����[t� ѭڃv@���˯�>0�U]_����(�t!�N^����ۅ�~^�����{�w_x���h�'���Rz��&��P�h��?]�ش�ͺ6��6K��+�,B�Q�v�j�/�˅�sB$��k 2017-12-05 09:11:07 Connection: closed 2017-12-05 09:11:07 SMTP connect() failed.

**Comment by AFwcxx** [comment]
I used this from the guide:

$mail->SMTPOptions = array(
    'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )
);

I set

$mail->SMTPSecure = "tls"; 
$mail->Port       = 587;
and
$mail->SMTPSecure = "ssl";
$mail->Port       = 465;

Both doesn't work.

**Comment by Synchro** [comment]
It's nothing to do with your certificate; that's not involved at all. The "certificate verify failed" message is unambiguous, and (since you're able to connect to gmail), is mostly likely because your CA certificates file is out of date. Running the openssl tests would tell you exactly why it's failing, but in the absence of those, you'll have to figure it out - there's nothing I can do. You're still using an old version of PHPMailer, so upgrading would be a good idea anyway.

**Comment by AFwcxx** [comment]
"CA certificates file is out of date"

Is that the SSLCertificateChainFile ?

**Comment by Synchro** [comment]
No. Openssl in your PHP installation will use an OS-supplied list of all root certificates that are used to validate TLS connections. This file is updated periodically via OS updates. In the case of `smtp.gmail.com`, the certificate is signed by `Google Internet Authority G3`, so when you connect, that certificate is looked up in your CA certs and used to verify the certificate - which in your case is failing. You can get [updates for the list from Microsoft](https://support.microsoft.com/en-us/help/931125/how-to-get-a-root-certificate-update-for-windows). You can also override PHP's CA certificate list and provide your own (often downloaded from [cURL](https://curl.haxx.se/docs/caextract.html)) which you can point at from [the `openssl.cafile` directive ](http://php.net/manual/en/openssl.configuration.php) in your php.ini.

**Comment by AFwcxx** [comment]
mate. thanks very much.

This part here saved my day
"You can also override PHP's CA certificate list and provide your own (often downloaded from cURL) which you can point at from the openssl.cafile directive in your php.ini."

you are my hero
