### ISSUE TITLE
The file you uploaded, PHPMailer-master.zip, contains a virus so the upload was canceled: SiteLock-PHP-FILEHACKER-md5-arfm.UNOFFICIAL FOUND

### ISSUE THREAD

**Issue by prafullwizorbit** [PHPMailer/PHPMailer#1265]
Hi
   while i upload zip of phpmailer to my server then its gives error like "The file you uploaded, PHPMailer-master.zip, contains a virus so the upload was canceled: SiteLock-PHP-FILEHACKER-md5-arfm.UNOFFICIAL FOUND" any suggestion please

Thanks

**Comment by Synchro** [comment]
If it's the download from here on github, it's a false positive. See scan results [here](https://www.virustotal.com/#/file/d2e542d7ff67a1ed7a6d667f6db2476dff82b2ddf4d0e7df466cdb54f5ed30e4/detection) and [here](http://quetvirus.vn/analyse_file.aspx?Arrmd5=0B2A5B47BD0B46EB7CBF43B531229539_0B9B8615F536F95EC22381707441FBE6_0BEBD0991F833D404EAE1F4169F12D03_13AC94E759A8BAEB4F8B6D186ED9A0B6_18049AFA12F6341A28464A8240547496_20589AE4FFE53E701190E19794731E82_211AA866A57987D38FDE2BD91A3D7D41_2343321D68A0F537731094D94CB018CE_23C2A5E0106B99D75238986559BB5FC6_288D90DC839FEBCB80F24EF24DD91A7B_2A9B439722F490AE350F7DBC25198D79_2F2B474F532AB2EE3D92395F3C5B0E0C_312E3D6B9B67338BDBE8CDCE5C911278_3B2BE0A69D0F145CCD7288D31131B043_3CD5D83DA61896F05AF3B0E3AFC4120F_4099EFCB36A6E5609D30D5498FA5C6FF_46DCD505D56A950198D9AA84385F94A2_47A1156689DD8D71488D19FEB4E2A957_48DD712CFB4932969171D7F49308CE8F_5202468726F825A4AC72E4E93FCA6D09_563DA4CA11458562B6E938BC7742248A_56D774311CAD93C3935F7E0BAE385C31_58A5B654F0322BA94713956E9FE2CBDE_60CF6CF5D5380E7573BED1F2039A6FB6_62EE650E737866D7B819D8F349DB92E6_632C0CAA936FA9575F6A089C84FFD2CC_648FF6F9AD54EAA5697D413B927A5005_6D3E9120D448E6E8200B94B6CE55DB58_70881D6B394785C9C85BFECA355C7E45_89150E124021D4814E1456EB6290F3F3_94100D2B2DC17AC67579A4499A13D9C2_95D8E64B4EA89CF7429053F2191B4C56_97DD1085D2495783B04790F9A6D5190F_982FFD225FDC01A3B80A3C1FEC2155A8_9B9D6B0EAF02FFEEBEDA377F6E47B8D9_A05AA8B2F630A31493922B24B4B93B2E_AB761BC79974A307B6D482F361C9A70A_AE3734760093B2251F9E2A79DADBB152_B2CA56AE4030B23DAD54FCD1770838BC_B562487C73F60E245D1A1671DC9C1573_BF6682EC14163A9FCD99E44DE2C6DAB2_C2AC8C3EA177248B481C66E5B4C6A463_C7BA3B001F45220F9AA7CD6E4101F58C_CFD27A7F91F0F4F2A4846CC10839DFD6_D33F3B2FACDEA271B3506D3946F80684_D3BF25210A06E7AB8B407F140D5D6612_DA14FFF5B9752F8A14BE805703FB5E50_DDBD3D779DA4C2A86964361665248B79_DDE630065BAD8DFEF600C47EECFCA2C2_E43A3661566D39F7F6094905C5FA142E_).

**Comment by prafullwizorbit** [comment]
![screenshot from 2017-12-05 14 16 58](https://user-images.githubusercontent.com/16131039/33597936-035dfa74-d9c7-11e7-9fab-8ba634ebdd91.png)

**Comment by Synchro** [comment]
Yes, that's why I included that second scan link from BKAV which shows it virus free. It's a false positive.

**Comment by prafullwizorbit** [comment]
ok thanks i am contacting my hosting provider
