### ISSUE TITLE
how can i use PHPMailer-6.0.2 in my website after download 

### ISSUE THREAD

**Issue by hardik1138** [PHPMailer/PHPMailer#1267]
how can i use PHPMailer-6.0.2 in my website contact as page after download....
This is my contact as page...
`<form action="" method="post" role="form" class="contactForm">`
	`     <div class="form-group">`
		`<input type="text" name="name" class="form-control input-text" id="name" placeholder="Your Name" title="Enter your name" required/>`
	       `<div class="validation"></div>`
	`</div>`
	`<div class="form-group">`
		`<input type="email" class="form-control input-text" name="email" id="email" placeholder="Your Email" required title="Enter your email"/>`
	        `<div class="validation"></div>`
	`</div>`
	`<div class="form-group">`
		`<input type="text" name="ph" class="form-control input-text" id="ph" placeholder="Mobile Number" title="Enter your mobile number" pattern="[0-9]{10}" maxlength="10" required/>`
		`<div class="validation"></div>`
	`</div>`
	`<div class="form-group">`
		`<textarea class="form-control input-text text-area" name="message" rows="5" placeholder="Message" title="Write something.." required></textarea>`
		`<div class="validation"></div>`
	`</div>`
		`<div class="text-center"><input type="submit" name="submit" value="Send Message" class="input-btn"></div>`
`</form>`

**Comment by Synchro** [comment]
Read the readme, look at the wiki for tutorials etc, base your code on the contact form example provided in the examples folder.
