### ISSUE TITLE
Issue with connectivity after submitting form via server side

### ISSUE THREAD

**Issue by GhostPolymer** [PHPMailer/PHPMailer#1268]
I am currently using the latest PHPMailer version.
Code is as follows: 

me/www Up Level Home

 123456789101112131415161718192021222324252627282930313233343536373839404142434445

<?php// Import PHPMailer classes into the global namespace// These must be at the top of your script, not inside a functionrequire 'src/PHPMailer.php';require 'src/SMTP.php'; //Load composer's autoloaderrequire 'vendor/autoload.php'; $mail = new PHPMailer(true); // Passing `true` enables exceptionstry { //Server settings $mail->SMTPDebug = 2; // Enable verbose debug output $mail->isSMTP(); // Set mailer to use SMTP $mail->Host = 'mail.hunterrafuse.dx.am'; // Specify main and backup SMTP servers $mail->SMTPAuth = true; // Enable SMTP authentication $mail->Username = 'hunterdeveloper@hunterrafuse.dx.am'; // SMTP username $mail->Password = '5T@comon69'; // SMTP password $mail->SMTPSecure = 'tls'; // Enable TLS encryption, `ssl` also accepted $mail->Port = 465; // TCP port to connect to //Recipients $mail->setFrom('from@example.com', 'Mailer'); $mail->addAddress('joe@example.net', 'Joe User'); // Add a recipient $mail->addAddress('ellen@example.com'); // Name is optional $mail->addReplyTo('info@example.com', 'Information'); $mail->addCC('cc@example.com'); $mail->addBCC('bcc@example.com'); //Attachments $mail->addAttachment('/var/tmp/file.tar.gz'); // Add attachments $mail->addAttachment('/tmp/image.jpg', 'new.jpg'); // Optional name //Content $mail->isHTML(true); // Set email format to HTML $mail->Subject = 'Here is the subject'; $mail->Body = 'This is the HTML message body <b>in bold!</b>'; $mail->AltBody = 'This is the body in plain text for non-HTML mail clients'; $mail->send(); echo 'Message has been sent';} catch (Exception $e) { echo 'Message could not be sent.'; echo 'Mailer Error: ' . $mail->ErrorInfo;}

And the error I receive after submitting the form is:

2017-12-06 12:25:30	SERVER -> CLIENT: 220 mail2.runhosting.com ESMTP 2017-12-06 12:25:30	CLIENT -> SERVER: EHLO hunterrafuse.dx.am 2017-12-06 12:25:30	SERVER -> CLIENT: 250-mail2.runhosting.com 250-PIPELINING 250-SIZE 200000000 250-ETRN 250-STARTTLS 250-AUTH CRAM-MD5 LOGIN PLAIN DIGEST-MD5 250-AUTH=CRAM-MD5 LOGIN PLAIN DIGEST-MD5 250-ENHANCEDSTATUSCODES 250-8BITMIME 250 DSN 2017-12-06 12:25:30	CLIENT -> SERVER: STARTTLS 2017-12-06 12:25:30	SERVER -> CLIENT: 220 2.0.0 Ready to start TLS 2017-12-06 12:25:30	SMTP Error: Could not connect to SMTP host. 2017-12-06 12:25:30	CLIENT -> SERVER: QUIT 2017-12-06 12:25:30	SERVER -> CLIENT: 2017-12-06 12:25:30	SMTP ERROR: QUIT command failed: 2017-12-06 12:25:30 SMTP Error: Could not connect to SMTP host. Message could not be sent.Mailer Error: SMTP Error: Could not connect to SMTP host.

**Comment by GhostPolymer** [comment]
This is the code: 
<?php
// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
require 'src/PHPMailer.php';
require 'src/SMTP.php';

//Load composer's autoloader
require 'vendor/autoload.php';

$mail = new PHPMailer(true);                              // Passing `true` enables exceptions
try {
    //Server settings
    $mail->SMTPDebug = 2;                                 // Enable verbose debug output
    $mail->isSMTP();                                      // Set mailer to use SMTP
    $mail->Host = 'mail.hunterrafuse.dx.am';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = 'hunterdeveloper@hunterrafuse.dx.am';                 // SMTP username
    $mail->Password = '5T@comon69';                           // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 465;                                    // TCP port to connect to

    //Recipients
    $mail->setFrom('from@example.com', 'Mailer');
    $mail->addAddress('joe@example.net', 'Joe User');     // Add a recipient
    $mail->addAddress('ellen@example.com');               // Name is optional
    $mail->addReplyTo('info@example.com', 'Information');
    $mail->addCC('cc@example.com');
    $mail->addBCC('bcc@example.com');

    //Attachments
    // $mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
    // $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name

    //Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = 'Here is the subject';
    $mail->Body    = 'This is the HTML message body <b>in bold!</b>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    $mail->send();
    echo 'Message has been sent';
} catch (Exception $e) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
}

**Comment by Synchro** [comment]
This combo won't work:

    $mail->SMTPSecure = 'tls';
    $mail->Port = 465;

Use:

    $mail->SMTPSecure = 'ssl';
    $mail->Port = 465;

or

    $mail->SMTPSecure = 'tls';
    $mail->Port = 587;

I suspect that's not your problem though - there has been a recent flurry of problems like this because some CA root certificates were apparently updated, see #1264, which is also covered in the troubleshooting guide.

**Comment by Synchro** [comment]
Also you're loading the classes wrong - look at what it says in the readme. You need to `use` the class names to import them into your namespace, and if you're using composer, you don't need to load PHPMailer's classes separately - composer's autoloader will deal with that.

**Comment by GhostPolymer** [comment]
I understand the composer code and what not and thanks for the timely feedback! For this website I am just not using composer. I know it's easier but I just didn't do composer from the start. Any way I can implement classes without the 'use'? I did, as you can see, use the 'require' instead.
Or would that not have an issue at all?

**Comment by Synchro** [comment]
Yes, you can not use `use` (confusing I know!) by using fully qualified class names (FQCNs) instead. This:
```php
use PHPMailer\PHPMailer\PHPMailer;
require 'path/to/src/PHPMailer.php';
$mail = new PHPMailer;
```
is functionally identical to:
```php
require 'path/to/src/PHPMailer.php';
$mail = new PHPMailer\PHPMailer\PHPMailer;
```
All the `use` does is alias the PHPMailer class out of its own namespace into your own (global) namespace.

**Comment by GhostPolymer** [comment]
Fatal error: Class 'PHPMailer\PHPMailer\Exception' not found in /srv/disk1/2526936/www/hunterrafuse.dx.am/src/PHPMailer.php on line 2761

Fixed everything, guess it's a minor encoding issue.

**Comment by Synchro** [comment]
You need to load that class, that's all:

    require 'src/Exception.php';

**Comment by GhostPolymer** [comment]
I'm trying to do what the other guy did in the post you mentioned, #1264 , but I created CA certs from windows and it's a range of different certs with diff names. I don't know exactly which one I would use. Any suggestions?

**Comment by Synchro** [comment]
You should use the whole file containing all the certs. You don't need to pick out specific ones.

**Comment by Synchro** [comment]
If you have multiple files, just `cat` them all together.

**Comment by GhostPolymer** [comment]
Okay I have an SSL and IP for the domain, so it is secured now but I am still having the same issue. I notice you stated that there was a list from cURL that I could download, a pem file? Do I upload that to my php.ini on my host site? still getting this nice error code here : 

2017-12-08 21:54:58 SERVER -> CLIENT: 220 mail2.runhosting.com ESMTP
2017-12-08 21:54:58 CLIENT -> SERVER: EHLO hunterrafuse.dx.am
2017-12-08 21:54:58 SERVER -> CLIENT: 250-mail2.runhosting.com250-PIPELINING250-SIZE 200000000250-ETRN250-STARTTLS250-AUTH CRAM-MD5 LOGIN PLAIN DIGEST-MD5250-AUTH=CRAM-MD5 LOGIN PLAIN DIGEST-MD5250-ENHANCEDSTATUSCODES250-8BITMIME250 DSN
2017-12-08 21:54:58 CLIENT -> SERVER: STARTTLS
2017-12-08 21:54:58 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
SMTP Error: Could not connect to SMTP host.
2017-12-08 21:54:58 CLIENT -> SERVER: QUIT
2017-12-08 21:54:58 SERVER -> CLIENT: 
2017-12-08 21:54:58 SMTP ERROR: QUIT command failed: 
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Message has been sent

**Comment by Synchro** [comment]
It's probably a PHP-level problem. Download the latest CA certificates from [curl](https://curl.haxx.se/docs/caextract.html) and point your PHP config at it via [`openssl.cafile`](http://php.net/manual/en/openssl.configuration.php). You can confirm what the problem is using the openssl test in the guide.

**Comment by GhostPolymer** [comment]
I do not know how to point my PHP config via openssl.cafile and the to test would be https://github.com/PHPMailer/PHPMailer/blob/master/test/PHPMailerLangTest.php ?

**Comment by Synchro** [comment]
No, the guide linked from the error message: https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting. The openssl test is run from a command line like this:

    openssl s_client -starttls smtp -crlf -connect mail.hunterrafuse.dx.am:587

The output from that will show the verification chain for your certificate.

You need to download the CA file from curl, save that somewhere on your server, set the path for it in the `openssl.cafile` option in your php.ini file. So it would be something like:

    openssl.cafile = /path/to/cafile.pem

**Comment by GhostPolymer** [comment]
So I pointed to the file in my php ini, still get:

2017-12-09 08:53:32 SMTP ERROR: Failed to connect to server: (0)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Message has been sent

on port 465 but port 465 shows in the cmd:
openssl s_client -starttls smtp -crlf -connect mail.hunterrafuse.dx.am:465
CONNECTED(00000210)

**Comment by GhostPolymer** [comment]
then this came up:

C:\Users\hunte>openssl s_client -starttls smtp -crlf -connect mail.hunterrafuse.dx.am:465
CONNECTED(00000210)
didn't find starttls in server response, trying anyway...
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 209 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1512809746
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---

**Comment by GhostPolymer** [comment]
got it to work, used this setup: 
```
<?php

//Import the PHPMailer class into the global namespace
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'src/Exception.php';
require 'src/PHPMailer.php';
require 'src/SMTP.php';
//Create a new PHPMailer instance
$mail = new PHPMailer(true);
//Set who the message is to be sent from
$mail->host = 'mail.hunterrafuse.dx.am';
$mail->SMTPSecure = 'ssl';
$mail->Port = 465;
$mail->setFrom('hunterdeveloper@hunterrafuse.dx.am', 'First Last');
//Set an alternative reply-to address
$mail->addReplyTo('replyto@example.com', 'First Last');
//Set who the message is to be sent to
$mail->addAddress('whoto@example.com', 'John Doe');
//Set the subject line
$mail->Subject = 'PHPMailer mail() test';
//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body

//Replace the plain text body with one created manually
$mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = 'Here is the subject';
    $mail->Body    = 'This is the HTML message body <b>in bold!</b>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
//send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}
?>
```

**Comment by GhostPolymer** [comment]
Sorry, updated it to this 
``
<?php

//Import the PHPMailer class into the global namespace
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'src/Exception.php';
require 'src/PHPMailer.php';
require 'src/SMTP.php';
//Create a new PHPMailer instance
$mail = new PHPMailer(true);
//Set who the message is to be sent from
$mail->Host = 'mail.hunterrafuse.dx.am';
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'hunterdeveloper@hunterrafuse.dx.am';                 // SMTP username
$mail->Password = 'NONYABUSINESS';                           // SMTP password
$mail->SMTPSecure = 'ssl';
$mail->Port = 465;
$mail->setFrom('hunterdeveloper@hunterrafuse.dx.am', 'First Last');
//Set an alternative reply-to address
$mail->addReplyTo('replyto@example.com', 'First Last');
//Set who the message is to be sent to
$mail->addAddress('hunterdeveloper@hunterrafuse.dx.am', 'Tech.hunter');
//Set the subject line
$mail->Subject = 'PHPMailer mail() test';
//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body

//Replace the plain text body with one created manually
$mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = 'Here is the subject';
    $mail->Body    = 'This is the HTML message body <b>in bold!</b>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
//send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}
?>

**Comment by GhostPolymer** [comment]
Thanks again! I really do appreciate your help!

**Comment by Synchro** [comment]
This command you posted won't work:

    openssl s_client -starttls smtp -crlf -connect mail.hunterrafuse.dx.am:465

You're asking it to use explicit TLS on a port expecting implicit. It works if you switch that to port 587. You can make it work on port 465 like this:

    openssl s_client -connect mail.hunterrafuse.dx.am:465
