### ISSUE TITLE
SMTP ERROR: Failed to connect to server

### ISSUE THREAD

**Issue by mcornes** [PHPMailer/PHPMailer#1270]
my gmail configuration is right and i have set up the phpmailer correctly but still i got this error 
(2017-12-07 09:56:13 SMTP ERROR: Failed to connect to server: (0)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Message could not be sent.Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting)

**Comment by ImpoZ** [comment]
I received the same error, but PHPmailer WAS working while on a site (Unix back-end) hosted from a the SAME provider as the Mail server (let's call it provider A). Once i switched the site hosting from provider A to GoDaddy, while keeping the my mail server, unaffected, with Provider A), I began receiving this exact error (below). And my friend was hammering my "send request" component on my site (running this PHPMailer) HOURS before i switched my site hosting from Provider A to GoDaddy.
running PHPMailer 5.2.15
Message could not be sent.Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
Read the troubleshooting guide, in particular what it says about GoDaddy. Also, update your PHPMailer; theres no reason to run an old version.

**Comment by rbenitezpagan** [comment]
I have the same problem.

Latest code...

2018-02-22 18:01:53 SMTP ERROR: Failed to connect to server: (0)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Message could not be sent. Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting 

That update completely broke my webapp

**Comment by Synchro** [comment]
Same problem, same solution...
