### ISSUE TITLE
Fatal error in while loop

### ISSUE THREAD

**Issue by sagarindia** [PHPMailer/PHPMailer#1272]
Dear support team,
                      when i call `sendmail($sendto,$subject,$message,$plainmessage,$attachments);` function without loop its work file but when i put it in my mysqli while loop it give these messages. Please help me 

**Warning:** Creating default object from empty value in D:\xampp\htdocs\cronjobs\mailclass.php on line 12
**Fatal error:** Call to undefined method stdClass::isSMTP() in D:\xampp\htdocs\cronjobs\mailclass.php on line 13

**Comment by Synchro** [comment]
This doesn't appear to have anything to do with PHPMailer.

**Comment by sagarindia** [comment]
can you give me any suggestion where it check
`if($stm->num_rows>0){
		include('inc/mailclass.php');
		$stm->bind_result($seo_name,$title,$description,$images,$post_date,$expire_on,$full_name,$email);
		while($stm->fetch()){	
            $images_array = array_filter(explode(',',$images));
            $mailimage = $images_array[0];
            $key=md5($post_date * $expire_on);
			$detail = strlen($description) > 50 ? substr($description,0,50)."..." : $description;
            ob_start();
            include "/email_templates/post_expired.php";
            $htmlmessage =  ob_get_contents();
            ob_end_clean();            
            sendmail($email,'Ad Expiry Notification',$htmlmessage,'',array());
		}
	}`

because it work fine it outside of loop

**Comment by Synchro** [comment]
This is still nothing to do with PHPMailer.
