### ISSUE TITLE
Remove X-Originating-IP & Received from header

### ISSUE THREAD

**Issue by drt420** [PHPMailer/PHPMailer#1278]
Hello
I want to remove below 2 entries from header as these are showing my server real ip address which can lead to massive ddos attack and security compromise. Pls suggest a way to remove below 2 fields.

```
Received: from abc.com (111.111.111.111)
X-Originating-IP: [111.111.111.111]
```
Regards

**Comment by Synchro** [comment]
These are not added by PHPMailer. They are not present in the original message at all, but are added by the *receiving* mail server.

**Comment by NiklasBr** [comment]
@drt420 It is very easy to find your email server's IP address for anyone who have your email domain. Your real domain is not abc.com, but [here's your example](https://mxtoolbox.com/SuperTool.aspx?action=mx%3aabc.com&run=toolpage), try it with your own domain.
