### ISSUE TITLE
Update documentation 

### ISSUE THREAD

**Issue by dknacht** [PHPMailer/PHPMailer#1279]
Hi!,
Beforehand I'd like to thank you for such an amazing project.
I'd like to know if you are interested in creating a multi-language wiki, it means, to give users the option to see the wiki, documentation and other important information (like examples) in other languages. 

I've seen that PHPMailer has many features that aren't used so often due to the lack of documentation and quality tutorials in other languages. 

I have already translated the readme and some of the wiki articles to Spanish and Esperanto, but i don't know where to post it so it can be accessible and easy to find; I think GitHub is the better place as is here where all the people comes to find all related to the project, but I am quite new to GitHub, so I don't know if there is an option to switch between languages in the documentation, and I wonder if it's practical to have them in a separated folder like 'wiki/es/SMTP-Debug'.

So, what do you think? is it practical to keep it here?, is it better to have it somewhere else and post here the links to it? what other options do we have?

Thanks in advance and best regards.

Dknacht.

**Comment by Synchro** [comment]
Thanks! Glad you like it. Support docs in other languages would be very welcome, but I'd say more of a priority (if you have time) would be making docs are up to date for version 6.0, for example I know the gmail oauth doc needs updating - this would avoid you translating docs that are out of date. I don't know if there is such an option either! I think you have to create duplicate wiki pages and just name them sensibly so that they get grouped together, and you could add links to each of the other language versions. I don't know if there's any structure available for wiki pages - I have seen some projects that have hundreds, and it becomes dependent on maintaining a contents page and searching. I don't want to put wiki content into the source project - I just removed all the static documentation for the 6.0 release!

**Comment by dknacht** [comment]
Hi!
Thanks for your answer!.
Yes! that makes a lot of sense, it's better to complete the documentation before translate it.
More than time, what difficults me on making new documentation is the knowledge about the project that I must have before starting, but yeah!, I'll get on it. Its going to take quite longer while I explore and understand all well enough to start, but I will.
If you want, give me a list of the features you know or suspect that require update or that are undocumented and I am going to check them in that order. By now I will start with the Gmail OauthX2 that you mentioned. 
(P.S. I think it's a good idea to have somewhere to post the state of the documentation, I mean, some TO-DO documentation list, that contains all pending things. For example: X needs documentation, Y needs update, Z needs review etc.)

Thanks again and best regards.

Dknacht.

**Comment by dknacht** [comment]
Hi!
I was checking the OAUTH X2 documentation and it seems that the current process is up and working.
The missing part would be add documentation for the other servers that are supported but don't have a doc related (like Yahoo and Microsoft).
Should I create a new document for each server?

**Comment by fuzzehbear** [comment]
Hi, I was just wondering if you need any help with the creation of a multi language wiki? I am billingual and can help to translate and create a chinese wiki. Will you be interested in that?

**Comment by Synchro** [comment]
Sounds great, go ahead. Probably the most useful thing to translate would be the troubleshooting guide, though it does change fairly frequently. The basic tutorial and the gmail oauth guide would be good too, but both need updating anyway.

**Comment by dknacht** [comment]
@Synchro , Do you remember that we had a doubt in how we were going to put the documentation in other languages in order to keep it organized?
Have you thought any ideas on it? I don't see if the wiki supports even folders.

P.S. about the topic of this threat, I am working on it. I just got a new work and now I have less time. Sorry for not showing any news :S.

**Comment by Synchro** [comment]
I don't know if there are better ways of organising the wiki, but there are only a few significant docs, so I don't see it getting too cluttered.

**Comment by dknacht** [comment]
Yes but, even if there are only 5 files, having 4 languages (let's say Spanish, English, Chinese and another one) adds up to 20 files. And as you can't group them maybe end up in a disorganized wiki. 
I've got two ideas:
1. Use the `docs` folder to keep the other languages docs or
2. Keep them in the same file in sections 

I'd go for the first one. But if you believe that it's ok to put all in the wiki if you want I upload the translation that I've made to Spanish and see how it goes.

**Comment by dknacht** [comment]
Hi!,
I posted in the GitHub wiki to see if someone could help us with this.
They gave me a great idea. 
I will test it and then implement it here.
https://github.community/t5/How-to-use-Git-and-GitHub/Folders-or-grouping-pages-in-GitHub-Wikis/m-p/7784

Best regards

**Comment by Synchro** [comment]
Nice one.
