### ISSUE TITLE
 864/5000 Problems sending emails: SMTP connect () failed.

### ISSUE THREAD

**Issue by Checoportela91** [PHPMailer/PHPMailer#1283]
810/5000
What a good afternoon

Since 03-12-2017 the phpMailer that I use does not send a message, just set it up as a basic HTML mail.
Move the following Debug:
2017-12-11 18:30:27 SMTP ERROR: Failed to connect to server: (0) 2017-12-11 18:30:27 SMTP connect () failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting SMTP connect () failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

The configuration is:
                 $ mail-> SMTPDebug = 2;
$ mail-> SMTPSecure = "ssl";
$ mail-> Host = 'smtp.gmail.com';
$ mail-> Port = 465;
$ mail-> isSMTP ();
$ mail-> SMTPAuth = true;

I have been using it for more than a year but from that date you have that problem, I thought it was my domain problem but I tried to send it from my personal Gmail account and I did not send it.

Any recommendation?

**Comment by Synchro** [comment]
Yes - read the troubleshooting guide linked from the error. This is most probably caused by a missing or out of date CA certificate, which is an OS / PHP problem, nothing to do with your script or PHPMailer specifically.

**Comment by Checoportela91** [comment]
Thank you.
Can you tell me where I can get the Gmail Certificate and in Xampp where it should be inserted? please

**Comment by Synchro** [comment]
Where to get the CA certs is in the guide (which I have just updated), but where to put it in XAMPP is not something I can help with.
