### ISSUE TITLE
Problem with IMAP office365 connection

### ISSUE THREAD

**Issue by TariGit** [PHPMailer/PHPMailer#1289]
# Problem description
Im trying to save message in sent folder of outlook.office365, but I have this error.
Thanks for help
# Code to reproduce
	$mailWeb = new PHPMailer();
	$mailWeb->IsSMTP(); // Uso SMTP
	$mailWeb->SMTPSecure = 'tls';
	$mailWeb->Host = "smtp.office365.com";
	$mailWeb->SMTPAuth = true;
	$mailWeb->Port = 587;
	$mailWeb->Username = "correo@example.es";
	$mailWeb->Password = "pass";
	$mailWeb->SetFrom("correo@example.es", "Nombres");
	$mailWeb->AddReplyTo("correo@example.es", "Nombres");
	$mailWeb->Subject = "Asunto";
	$mailWeb->AltBody = "Para ver correctamente este mensaje use la vista de HTML";
	$mailWeb->MsgHTML($body);
	$mailWeb->AddAddress($emailTo);
	$mailWeb->SMTPDebug = 1;
	if($mailWeb->Send()){
	    $mailcnf = "outlook.office365.com:993/imap/ssl/novalidate-cert";
	    $conn_str = "{".$mailcnf."}Sent_Items";
	    $mbox = imap_open($conn_str, $user, $pass)
	      or die("can't connect: " . imap_last_error());
	    $check = imap_mailboxmsginfo($mbox);
	    if ($check) {
	        echo "Mailbox: "  . $check->Mailbox . "<br />\n" ;
	    } else {
	        echo "imap_mailboxmsginfo() failed: " . imap_last_error() . "<br />\n";
	    }
	    $MIMEMessage = $mailWeb->getSentMIMEMessage();
	    $addemail = imap_append($mbox,$conn_str,$MIMEMessage)
	        or die("can't add: " . imap_last_error());
	    imap_close($mbox);		
	}
`
# Debug output
can't add: [TRYCREATE] Folder is not found.

**Comment by Synchro** [comment]
Looks like you don't have a folder called `Sent_Items`.

**Comment by TariGit** [comment]
thanks for help,
what is the default name folder for sent items, you Know?

**Comment by Synchro** [comment]
Sorry, no idea - I assume there's an IMAP command you can use to get a list of folders.

**Comment by TariGit** [comment]
okey, thanks
