### ISSUE TITLE
SMTP -> ERROR: RSET failed: Language string failed to load: tls

### ISSUE THREAD

**Issue by langaro** [PHPMailer/PHPMailer#1296]
Hello.
We're facing this error:

`<br />SMTP -> FROM SERVER:
<br />SMTP -> ERROR: RSET failed: 
<br />Language string failed to load: tls
Descrição do erro: Language string failed to load: tls<p>SMTP server error: </p>`

We've been searching it for hours, trying several approaches and so far nothing has come do work.

This is our code:
`$mail = new PHPMailer();
$mail->Mailer = "smtp";
$mail->IsHTML(true);
$mail->IsSMTP();
$mail->CharSet = "UTF-8";
$mail->SMTPSecure = "tls";
$mail->Host = $hostEmail;
$mail->Port = $portaEmail;
$mail->SMTPAuth = true;
$mail->Username = $usuarioEmail;
$mail->Password = $senhaEmail;
$mail->From = $emailRemetente;
$mail->FromName = $nomeRemetente;

$mail->AddAddress(trim($arrEmails[0]));

$mail->Subject = "Assunto";
$mail->Body = "Texto";

if (!$mail->Send()) {
    return "Descrição do erro: ".$mail->ErrorInfo;
} else {
    return "Sucesso";
}`

The server have ssl and runs over HTTPS.

Our debug result:
`SMTP -> get_lines(): $data was ""
<br />SMTP -> get_lines(): $str is "220 XXX.xxx.xxx.br Microsoft ESMTP MAIL Service ready at Tue, 19 Dec 2017 08:59:58 -0200
"
<br />SMTP -> get_lines(): $data is "220 XXX.xxx.xxx.br Microsoft ESMTP MAIL Service ready at Tue, 19 Dec 2017 08:59:58 -0200
"
<br />SMTP -> FROM SERVER:220 XXX.xxx.xxx.br Microsoft ESMTP MAIL Service ready at Tue, 19 Dec 2017 08:59:58 -0200

<br />SMTP -> get_lines(): $data was ""
<br />SMTP -> get_lines(): $str is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
"
<br />SMTP -> get_lines(): $data is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
"
<br />SMTP -> get_lines(): $data was "250-XXX.xxx.xxx.br Hello [x.x.x.x]
"
<br />SMTP -> get_lines(): $str is "250-SIZE
"
<br />SMTP -> get_lines(): $data is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
"
<br />SMTP -> get_lines(): $data was "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
"
<br />SMTP -> get_lines(): $str is "250-PIPELINING
"
<br />SMTP -> get_lines(): $data is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
"
<br />SMTP -> get_lines(): $data was "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
"
<br />SMTP -> get_lines(): $str is "250-DSN
"
<br />SMTP -> get_lines(): $data is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
"
<br />SMTP -> get_lines(): $data was "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
"
<br />SMTP -> get_lines(): $str is "250-ENHANCEDSTATUSCODES
"
<br />SMTP -> get_lines(): $data is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
"
<br />SMTP -> get_lines(): $data was "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
"
<br />SMTP -> get_lines(): $str is "250-STARTTLS
"
<br />SMTP -> get_lines(): $data is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
"
<br />SMTP -> get_lines(): $data was "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
"
<br />SMTP -> get_lines(): $str is "250-X-ANONYMOUSTLS
"
<br />SMTP -> get_lines(): $data is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
"
<br />SMTP -> get_lines(): $data was "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
"
<br />SMTP -> get_lines(): $str is "250-AUTH NTLM
"
<br />SMTP -> get_lines(): $data is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
"
<br />SMTP -> get_lines(): $data was "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
"
<br />SMTP -> get_lines(): $str is "250-X-EXPS GSSAPI NTLM
"
<br />SMTP -> get_lines(): $data is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
250-X-EXPS GSSAPI NTLM
"
<br />SMTP -> get_lines(): $data was "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
250-X-EXPS GSSAPI NTLM
"
<br />SMTP -> get_lines(): $str is "250-8BITMIME
"
<br />SMTP -> get_lines(): $data is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
"
<br />SMTP -> get_lines(): $data was "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
"
<br />SMTP -> get_lines(): $str is "250-BINARYMIME
"
<br />SMTP -> get_lines(): $data is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
"
<br />SMTP -> get_lines(): $data was "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
"
<br />SMTP -> get_lines(): $str is "250-CHUNKING
"
<br />SMTP -> get_lines(): $data is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
"
<br />SMTP -> get_lines(): $data was "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
"
<br />SMTP -> get_lines(): $str is "250-XEXCH50
"
<br />SMTP -> get_lines(): $data is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250-XEXCH50
"
<br />SMTP -> get_lines(): $data was "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250-XEXCH50
"
<br />SMTP -> get_lines(): $str is "250-XRDST
"
<br />SMTP -> get_lines(): $data is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250-XEXCH50
250-XRDST
"
<br />SMTP -> get_lines(): $data was "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250-XEXCH50
250-XRDST
"
<br />SMTP -> get_lines(): $str is "250 XSHADOW
"
<br />SMTP -> get_lines(): $data is "250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250-XEXCH50
250-XRDST
250 XSHADOW
"
<br />SMTP -> FROM SERVER: 250-XXX.xxx.xxx.br Hello [x.x.x.x]
250-SIZE
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250-XEXCH50
250-XRDST
250 XSHADOW

<br />SMTP -> get_lines(): $data was ""
<br />SMTP -> get_lines(): $str is "220 2.0.0 SMTP server ready
"
<br />SMTP -> get_lines(): $data is "220 2.0.0 SMTP server ready
"
<br />SMTP -> FROM SERVER:220 2.0.0 SMTP server ready

<br />SMTP -> FROM SERVER:
<br />SMTP -> ERROR: RSET failed: 
<br />Language string failed to load: tls
Descrição do erro: Language string failed to load: tls<p>SMTP server error: </p>`

Thanks

**Comment by Synchro** [comment]
You ignored the very first thing the issue template tells you to do - use the latest version. Beyond that, you're probably using an obsolete CA certificates file, which is covered extensively in the troubleshooting guide, which is also linked from the issue template.
