### ISSUE TITLE
Could not connect to SMTP host.

### ISSUE THREAD

**Issue by razasaleem** [PHPMailer/PHPMailer#1297]
# Problem description
i am using on laravel 5.5
# Code to reproduce
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
$mail = new PHPMailer(true);                             
        try {
            //Server settings
            $mail->SMTPDebug = 2;                                
            $mail->isSMTP();                                      
            $mail->Host = 'smtp.gmail.com';  
            $mail->SMTPAuth = true;                               
            $mail->Username = 'xxxxxxx@gmail.com';              
            $mail->Password = 'xxxxxxxxx';                           
            $mail->SMTPSecure = 'tls';                          
            $mail->Port = 587;                    

            //Recipients
            $mail->setFrom('bookings@xxxxxxx.co.uk', 'xxxxxxxxx');
            $mail->addAddress('xxxxxx@gmail.com');    
            $mail->addReplyTo('bookings@xxxxxx.co.uk', 'xxxxxxxxxxx');
           

            $mail->isHTML(true);                                  // Set email format to HTML
            $mail->Subject = 'Here is the subject';
            $mail->Body    = 'This is the HTML message body <b>in bold!</b>';
            $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

            $mail->send();
            echo 'Message has been sent';
        } catch (Exception $e) {
            echo 'Message could not be sent.';
            echo 'Mailer Error: ' . $mail->ErrorInfo;
        }
# Debug output
2017-12-19 12:26:12 SERVER -> CLIENT: 220 smtp.gmail.com ESMTP y1sm12628844edl.39 - gsmtp
2017-12-19 12:26:12 CLIENT -> SERVER: EHLO justsamosas.co.uk
2017-12-19 12:26:12 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [37.48.122.11]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
2017-12-19 12:26:12 CLIENT -> SERVER: STARTTLS
2017-12-19 12:26:12 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
SMTP Error: Could not connect to SMTP host.
2017-12-19 12:26:12 CLIENT -> SERVER: QUIT
2017-12-19 12:26:12 
2017-12-19 12:26:12 
SMTP Error: Could not connect to SMTP host.
Message could not be sent.Mailer Error: SMTP Error: Could not connect to SMTP host.

**Comment by Synchro** [comment]
You have a TLS problem. Read the troubleshooting guide about how to check and update your CA certificates. Next time, search before posting as this question has been answered many times.

**Comment by razasaleem** [comment]
how can i solve it?

**Comment by Synchro** [comment]
By reading the guide and doing what it says. Me retyping it here won't change anything.

**Comment by razasaleem** [comment]
@Synchro I have tried so many things but didnt able to sort it kindly help me out if you were there

**Comment by Synchro** [comment]
Really, every single thing I would use to diagnose your problem is in the guide. There is nothing I can write here that would be any different, so if you're not going to do what it says there, I doubt you'll do it if I say the same thing here either.
