### ISSUE TITLE
Missing dependency on the PHP "filter" extension

### ISSUE THREAD

**Issue by orlitzky** [PHPMailer/PHPMailer#1298]
In https://github.com/PHPMailer/PHPMailer/blob/9d9021ebc399f519b9bba9bb5cf18702fb5f4ac0/src/PHPMailer.php#L1252 the `filter_var` function is called, and that function is provided by the [PHP filter extension](http://php.net/manual/en/book.filter.php).

That extension should be required in https://github.com/PHPMailer/PHPMailer/blob/master/composer.json, right next to where "ctype" is.

**Comment by Synchro** [comment]
That's true, but the filter extension has been enabled by default since PHP 5.2. There are probably dozens of other extensions that are implicitly relied on too, but they're not listed for the same reason. Have you actually encountered an installation that doesn't include the filter ext? Ctype was specifically added because FreeBSD's PHP packages lack it. PRs welcome.

**Comment by orlitzky** [comment]
In Gentoo and its derivatives, it's easy to build PHP without any one particular extension. In theory, all packages require the extensions that they need, so if the package manager lets you disable an extension, then doing so should be cool. Using that reasoning, I just built myself a PHP that lacked _filter_, and noticed the omission.

I've already added the extra dependency to the Gentoo package, but anyone building PHP from source and using Composer should be able to shoot himself in the foot in the same way.

**Comment by orlitzky** [comment]
The PHP that I built has *only* filter and ctype enabled now, because all it does is run one contact form. If our web developer tells me that it doesn't work, I'll be happy to figure out which other (enabled by default) extensions are needed.

**Comment by Synchro** [comment]
OK, I'll leave this open then, will be happy to merge a PR when you've got a list.

**Comment by orlitzky** [comment]
The "openssl" extension is also needed for STARTTLS in SMTP. With that enabled, I was able to send via both SMTP and PHP's `mail()` function.

**Comment by orlitzky** [comment]
Actually, there are checks in place for most of the uses of OpenSSL. In the places where the extension is required but absent, an exception is thrown. I've opened https://github.com/PHPMailer/PHPMailer/issues/1300 for one case that I think was simply overlooked.

The "filter" functions are however still used unconditionally and unavoidably, so I think my initial report was correct that was should depend on the filter extension (PR incoming).
