### ISSUE TITLE
SMTPSecure checks don't account for SMTPAutoTLS

### ISSUE THREAD

**Issue by orlitzky** [PHPMailer/PHPMailer#1300]
There is a chunk of code in `PHPMailer.php` that is intended to throw an error if the user asks for SSL/TLS but doesn't have the OpenSSL extension installed:

```php
$secure = $this->SMTPSecure;
...
if ('tls' === $secure or 'ssl' === $secure) {
  if (!$sslext) {
    throw new Exception(...);
  }
}
```

However, that ignores the default behavior of `$SMTPAutoTLS = true;`. In particular, TLS will be used if the following test passes:

```php
if ($this->SMTPAutoTLS and $sslext and 'ssl' != $secure and $this->smtp->getServerExt('STARTTLS')) {
  $tls = true;
}
```

An exception might be appropriate in the latter case, too, if `$sslext` is false.

**Comment by orlitzky** [comment]
I made a ninja edit to that last sentence. Obviously the test won't pass if `$sslext` is false, but if it _is_ false, your expectations re: SMTPAutoTLS might be violated:

```php
    /**
     * Whether to enable TLS encryption automatically if a server supports it,
     * even if `SMTPSecure` is not set to 'tls'.
     * Be aware that in PHP >= 5.6 this requires that the server's certificates are valid.
     *
     * @var bool
     */
    public $SMTPAutoTLS = true;
```

**Comment by orlitzky** [comment]
To be specific, I think this line

```php
if ('tls' === $secure or 'ssl' === $secure) {
```

should be

```php
if ('tls' === $secure or 'ssl' === $secure or $this->SMTPAutoTLS) {
```

**Comment by Synchro** [comment]
No, we can't do that there because at that point we don't know if the server supports TLS or not. We don't want to raise an exception for a missing openssl extension if the user didn't request to use it (i.e. it's only *trying* to use it by virtue of auto TLS).
