### ISSUE TITLE
Incorrect header signing with DKIM

### ISSUE THREAD

**Issue by MarkMcCorrie** [PHPMailer/PHPMailer#1303]
I'm using PHPMailer with DKIM to send emails. It is successfully signing the body of the email, but not the header.

Setup:
PHP 7.1
PHPMailer ~6.0 - composer update done today
GoDaddy shared server

PHP code:

// Start of PHP code
$mail = new PHPMailer();
$mail->isSMTP();
$mail->Host = "localhost";
$mail->SMTPAuth = true;
$mail->Username = $username;
$mail->Password = $password;
$mail->SMTPSecure = "ssl";
$mail->Port = 465;
$mail->setFrom($email, $name);
$mail->addAddress($email_address, "");

// Setup DKIM
$mail->DKIM_domain = "letmein.org";
$mail->DKIM_private = $key_path;
$mail->DKIM_selector = "default";
$mail->DKIM_passphrase = "";
$mail->DKIM_identity = $mail->From;

// Send the email
$mail->isHTML(true);
$mail->Body = $html;
$mail->AltBody = "Plain text";
$mail->Subject = $subject;
$mail->send();

Gmail original message:
Delivered-To: letmeinrooms@gmail.com
Received: by 10.157.40.210 with SMTP id s76csp5935935ota;
        Mon, 25 Dec 2017 12:29:48 -0800 (PST)
X-Google-Smtp-Source: ACJfBotZ9N9joToAewtLA8avk623gOk/7og4UF3PwsLzSOHaKM8kAO5nQ8Mdfs+aMrNwKnTNnHuJ
X-Received: by 10.99.112.13 with SMTP id l13mr18964980pgc.157.1514233788664;
        Mon, 25 Dec 2017 12:29:48 -0800 (PST)
ARC-Seal: i=1; a=rsa-sha256; t=1514233788; cv=none;
        d=google.com; s=arc-20160816;
        b=u7jwUKfwUQILt+TeMp6/CHohdh+UNp+PIhDNHxzAhwglwN0fFvTKruFXlVIeQnRDiV
         +o9nCJjqhj3yKcRkL+9m6rkY1zKYlhtAMFyuqKhZsChSynmjYTmEa1Mk5nJwXPwB0ZJC
         WxK1twflSvC5BmNfvtQxeX+ElqrSRs7NOo+9ya73bB/ScTEGpKkSby+lXffe3TAi3H4A
         /nwLwvkqwdaeoxVTgkthOW4A5NPUU0gqg9D/Cw64rBs8RyATRXbYl3fXsPW7ygL8tzOX
         1SFZ4LOwAvVzcWhjMTYc4+geU2EKcMhizjs0wgD72Dt0uBJ/iR5hxnp0zAMG0hOcFzvU
         3FMg==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=dkim-signature:content-transfer-encoding:mime-version:message-id
         :subject:from:to:date:dkim-signature:arc-authentication-results;
        bh=WDkbaZ6CeaBbpdZO3DaX+ytUiW7AJMAQbfMK4WIOWOw=;
        b=Gs+0mH8C+wWMT9Gvu3UVUMIlE+VyJVU+Q/t0rZr2os26IBK3RK0NeaP3nwdQVLCxOX
         ZxEmLwXGvARECphpvVUymr6T3tqacQuUJNpyuE3B2jy1GqYh6vbIqUaG/d+jjMlnZXu0
         tSwv7hZUmhY/BfK2evSGR+7SQlNePhBVfa0PvMBZdC4KyoibfSVQN7XW5EO1T9LnzHF5
         6CZth0LAOWeGjnnP6wHIUd8PWXUknxr1adEnTKVnsrYeqrMjH0aviyBMPfYYS53/5nd/
         RpBtLZBahM0oOtoBMDZBTPwkum0KZUBU0f/yrzFrWplM45XOaohLtx0P3eKx3DfHuvYu
         LMXw==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=fail header.i=@letmein.org header.s=default header.b=JothSm7L;
       dkim=pass header.i=@letmein.org header.s=default header.b=Zc2QGL7J;
       spf=pass (google.com: domain of mark@letmein.org designates 188.121.43.194 as permitted sender) smtp.mailfrom=mark@letmein.org
Return-Path: <mark@letmein.org>
Received: from n1nlsmtp02.shr.prod.ams1.secureserver.net (n1nlsmtp02.prod.ams1.secureserver.net. [188.121.43.194])
        by mx.google.com with ESMTPS id 33si21736127ply.308.2017.12.25.12.29.48
        for <letmeinrooms@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Mon, 25 Dec 2017 12:29:48 -0800 (PST)
Received-SPF: pass (google.com: domain of mark@letmein.org designates 188.121.43.194 as permitted sender) client-ip=188.121.43.194;
Authentication-Results: mx.google.com;
       dkim=fail header.i=@letmein.org header.s=default header.b=JothSm7L;
       dkim=pass header.i=@letmein.org header.s=default header.b=Zc2QGL7J;
       spf=pass (google.com: domain of mark@letmein.org designates 188.121.43.194 as permitted sender) smtp.mailfrom=mark@letmein.org
Received: from n1plcpnl0106.prod.ams1.secureserver.net ([188.121.57.40]) by : HOSTING RELAY : with SMTP id TZMdewWS6jzE4TZMderJo3; Mon, 25 Dec 2017 13:28:47 -0700
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed; d=letmein.org ; s=default; h=Content-Transfer-Encoding:Content-Type:MIME-Version:Message-ID :Subject:From:To:Date:Sender:Reply-To:Cc:Content-ID:Content-Description: Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc:Resent-Message-ID: In-Reply-To:References:List-Id:List-Help:List-Unsubscribe:List-Subscribe: List-Post:List-Owner:List-Archive; bh=WDkbaZ6CeaBbpdZO3DaX+ytUiW7AJMAQbfMK4WIOWOw=; b=JothSm7Lm5P2IngbuOzcbmBVfJ QMAEt5XipU6ZMYqRm8gJtKWKc4/hpThE8avpDERjCkXvzV5ArMbAncYSmkVDGPpAO+KqadMQqaf5D P2CP7sNjtlBmFAIZ7HubeauxThzOULHBxhF9ogKp3afONvoMQrl1Y3z+jlkAIhzWD9GCv+fc+55Bl ip+KcrUwwf6sMTkxfUElCZ2ZrcBZtaQE/FEcbGOjuOresmNdiR5kM6hg98466ZX4EEiBUKYIPHVvO xzlCvrbk8niicq+ryRG55j63REzMaRb6vqpwIT1tZoyfwM9AlS74pECncEPb9TJXH+lgnjx+YkAhy cHdz4VMg==;
Received: from n1plcpnl0106.prod.ams1.secureserver.net ([188.121.57.40]:45004 helo=www.letmein.org) by n1plcpnl0106.prod.ams1.secureserver.net with esmtpsa (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128) (Exim 4.89) (envelope-from <mark@letmein.org>) id 1eTZMd-003HG8-FF for letmeinrooms@gmail.com; Mon, 25 Dec 2017 13:28:47 -0700
Date: Mon, 25 Dec 2017 20:28:42 +0000
To: letmeinrooms@gmail.com
From: Mark McCorrie <mark@letmein.org>
Subject: Test Email
Message-ID: <3byuAXu12j4qMjmJjeuwXD5deaEfwF1hmhUxJWfieCw@www.letmein.org>
X-Mailer: PHPMailer 6.0.2 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="b1_3byuAXu12j4qMjmJjeuwXD5deaEfwF1hmhUxJWfieCw"
Content-Transfer-Encoding: 8bit
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; l=421; s=default; t=1514233722; c=relaxed/simple; h=From:To:Date:Subject; d=letmein.org; i=mark@letmein.org; z=From:=20Mark=20McCorrie=20<mark@letmein.org> |To:=20letmeinrooms@gmail.com |Date:=20Mon,=2025=20Dec=202017=2020:28:42=20+0000 |Subject:=20Test=20Email; bh=WDkbaZ6CeaBbpdZO3DaX+ytUiW7AJMAQbfMK4WIOWOw=; b=Zc2QGL7JDUmTSXkUpC9jl3inB/5Kk/4Dg4vIC2cX23hbO2Beh+DX1yScwby6cja9PzBDiKO4CuD36RJZfoPs40G6Zm59kiceWB+5N8WuFlv1fHlW81H/fZmFqfKY90fAqAVipXmIRRvhDPa3EJ86BRSAz4Vy+aD3K9kanifzFgc=
X-AntiAbuse: This header was added to track abuse, please include it with any abuse report
X-AntiAbuse: Primary Hostname - n1plcpnl0106.prod.ams1.secureserver.net
X-AntiAbuse: Original Domain - gmail.com
X-AntiAbuse: Originator/Caller UID/GID - [47 12] / [47 12]
X-AntiAbuse: Sender Address Domain - letmein.org
X-Get-Message-Sender-Via: n1plcpnl0106.prod.ams1.secureserver.net: authenticated_id: mark@letmein.org
X-Authenticated-Sender: n1plcpnl0106.prod.ams1.secureserver.net: mark@letmein.org
X-Source: 
X-Source-Args: 
X-Source-Dir: 
X-CMAE-Envelope: MS4wfNhFSBp6b0roJYuGPaFanwG1bFvH2mHYa/x0KSHal++y01dMOyqJCTTdSr/NfOqclhYkFJRBuJVDMvCsbmo6xn7rmZAaJFsw7Pm+k/Twd8cMajWQZotQ FrNKgD+wQFnm/Wnu36op16HW170fpwXc+1LDgwejIf2M3NBzb9RLvoTiVPeIp1a+0jWHpGeAkg8vnbpOMBsFU0MQiM+kuiBR9V4=

--b1_3byuAXu12j4qMjmJjeuwXD5deaEfwF1hmhUxJWfieCw
Content-Type: text/plain; charset=us-ascii

Plain text

--b1_3byuAXu12j4qMjmJjeuwXD5deaEfwF1hmhUxJWfieCw
Content-Type: text/html; charset=us-ascii

<html><body>
<p>Hi Mark,</p>
<p>This is a test email to see if you are using DKIM correctly.</p></body></html>

--b1_3byuAXu12j4qMjmJjeuwXD5deaEfwF1hmhUxJWfieCw--

isnotspam check:

----------------------------------------------------------
DKIM check details:
----------------------------------------------------------

Result: fail
ID(s) verified: header.From=mark@letmein.org
Selector=default
domain=letmein.org

DomainKeys DNS Record=default._domainkey.letmein.org

----------------------------------------------------------
DKIM check details:
----------------------------------------------------------

Result: pass
ID(s) verified: header.From=mark@letmein.org
Selector=default
domain=letmein.org
DomainKeys DNS Record=default._domainkey.letmein.org

From mark@letmein.org Mon Dec 25 20:25:41 2017
Return-path: <mark@letmein.org>
X-Spam-Checker-Version: SpamAssassin 3.4.0 (2014-02-07) on
localhost.localdomain
X-Spam-Flag: YES
X-Spam-Level: ****
X-Spam-Report: 
* -0.0 RCVD_IN_DNSWL_NONE RBL: Sender listed at http://www.dnswl.org/, no
* trust
* [188.121.43.193 listed in list.dnswl.org]
* 3.5 BAYES_99 BODY: Bayes spam probability is 99 to 100%
* [score: 1.0000]
* -0.0 RCVD_IN_MSPIKE_H3 RBL: Good reputation (+3)
* [188.121.43.193 listed in wl.mailspike.net]
* -0.0 SPF_PASS SPF: sender matches SPF record
* 0.2 BAYES_999 BODY: Bayes spam probability is 99.9 to 100%
* [score: 1.0000]
* 0.1 HTML_MESSAGE BODY: HTML included in message
* 0.8 MPART_ALT_DIFF BODY: HTML and text parts are different
* -0.1 DKIM_VALID_AU Message has a valid DKIM or DK signature from author's
* domain
* 0.1 DKIM_SIGNED Message has a DKIM or DK signature, not necessarily
* valid
* -0.1 DKIM_VALID Message has at least one valid DKIM or DK signature
* -0.0 RCVD_IN_MSPIKE_WL Mailspike good senders
X-Spam-Status: Yes, hits=4.5 required=-20.0 tests=BAYES_99,BAYES_999,
DKIM_SIGNED,DKIM_VALID,DKIM_VALID_AU,HTML_MESSAGE,MPART_ALT_DIFF,
RCVD_IN_DNSWL_NONE,RCVD_IN_MSPIKE_H3,RCVD_IN_MSPIKE_WL,SPF_PASS autolearn=no
autolearn_force=no version=3.4.0
Envelope-to: ins-pph0xd5c@isnotspam.com
Delivery-date: Mon, 25 Dec 2017 20:25:41 +0000
Received: from n1nlsmtp03.shr.prod.ams1.secureserver.net ([188.121.43.193])
by localhost.localdomain with esmtp (Exim 4.84_2)
(envelope-from <mark@letmein.org>)
id 1eTZJc-000DUg-Sd
for ins-pph0xd5c@isnotspam.com; Mon, 25 Dec 2017 20:25:41 +0000
Received: from n1plcpnl0106.prod.ams1.secureserver.net ([188.121.57.40])
by : HOSTING RELAY : with SMTP
id TZIYeJ3ZFo71OTZIYer5Cv; Mon, 25 Dec 2017 13:24:34 -0700
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed; d=letmein.org
; s=default; h=Content-Transfer-Encoding:Content-Type:MIME-Version:Message-ID
:Subject:From:To:Date:Sender:Reply-To:Cc:Content-ID:Content-Description:
Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc:Resent-Message-ID:
In-Reply-To:References:List-Id:List-Help:List-Unsubscribe:List-Subscribe:
List-Post:List-Owner:List-Archive;
bh=VHJfoTD0vNdtPS93FdSU3JI6K29r+n7lRLO+Fwxq+7A=; b=aHlNGMM12Q1sbQ6AwvOfYXhc4b
SKXr3lkg2g9aainRhxCekL1ilCECSL00841gx0chOai1bZfv6AX807UWKjAz98lyo5zxvGHF5H7wb
KgYKbPVisYRQPIacuVlmAmG5p9KzCOLUByH96DcLUZTlD3fuEAi7b7bgLV/1DLzDUsKJAi0PCr1CS
BSlvWLxgs9bxYKGdHj1PcTiT+aixAHbsSHAMJtjKCfej69cwUdtEI8gueNPfx12ilKvZOyCvEwJcR
Kmjp/9u+ZV0pDIAX222cgsULohzNTe9MsQldUqfO+1vR4bjjZzr00e9Wx1rhJ6EvAS789YqfbabNr
5K9jyVAw==;
Received: from n1plcpnl0106.prod.ams1.secureserver.net ([188.121.57.40]:45389 helo=www.letmein.org)
by n1plcpnl0106.prod.ams1.secureserver.net with esmtpsa (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
(Exim 4.89)
(envelope-from <mark@letmein.org>)
id 1eTZIY-003FVN-9X
for ins-pph0xd5c@isnotspam.com; Mon, 25 Dec 2017 13:24:34 -0700
Date: Mon, 25 Dec 2017 20:24:29 +0000
To: ins-pph0xd5c@isnotspam.com
From: Mark McCorrie <mark@letmein.org>
Subject: Test Email
Message-ID: <DZgCXoErBeNf57IGureUwnMk3hA1VnDyIb2P7FyM6U@www.letmein.org>
X-Mailer: PHPMailer 6.0.2 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/alternative;
boundary="b1_DZgCXoErBeNf57IGureUwnMk3hA1VnDyIb2P7FyM6U"
Content-Transfer-Encoding: 8bit
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; l=418; s=default;
t=1514233469; c=relaxed/simple;
h=From:To:Date:Subject;
d=letmein.org; i=mark@letmein.org;
z=From:=20Mark=20McCorrie=20<mark@letmein.org>
|To:=20ins-pph0xd5c@isnotspam.com
|Date:=20Mon,=2025=20Dec=202017=2020:24:29=20+0000
|Subject:=20Test=20Email;
bh=VHJfoTD0vNdtPS93FdSU3JI6K29r+n7lRLO+Fwxq+7A=;
b=h8uE+0X47nb8hbwt44/moQII/gkstMLYVXIW1v7NAtRTdhQRfqGzwmTJ9eYVjNRdCdDTfcqhxjLjUJCw3L6iH0353tYZP3mu3wdoYYuMuKNa9hQTA7RLEBZHivKTB29WGoaIOZsgA40O4cLhqKzZMNtHLx6g4p8Ctm7Nh3Fp/E4=
X-AntiAbuse: This header was added to track abuse, please include it with any abuse report
X-AntiAbuse: Primary Hostname - n1plcpnl0106.prod.ams1.secureserver.net
X-AntiAbuse: Original Domain - isnotspam.com
X-AntiAbuse: Originator/Caller UID/GID - [47 12] / [47 12]
X-AntiAbuse: Sender Address Domain - letmein.org
X-Get-Message-Sender-Via: n1plcpnl0106.prod.ams1.secureserver.net: authenticated_id: mark@letmein.org
X-Authenticated-Sender: n1plcpnl0106.prod.ams1.secureserver.net: mark@letmein.org
X-Source: 
X-Source-Args: 
X-Source-Dir: 
X-CMAE-Envelope: MS4wfLdaXUnBpcIID+ZuEKLd34Kv/8fuGZ2IfSTzYpCZDkqQv55VZEMlVF5SITcFqn1c9Lq9PqjJMo0YxWfmsg7kbdpMh1sNHKUh3ZuDcWZd7rnkYNqeuvGH
eOSujnTv1rSfb/ZOycz2IlP03d2FMQByMLN0Ly+88qXqs4YpJzQiWRmrMBMYWfNbPZ5AfoOGp4GWlzv0kRtT3P/atIrXV6secr8=
X-DKIM-Status: fail (signature_incorrect)
X-DKIM-Status: pass (mark@letmein.org)
This is a multi-part message in MIME format.
--b1_DZgCXoErBeNf57IGureUwnMk3hA1VnDyIb2P7FyM6U
Content-Type: text/plain; charset=us-ascii

Plain text

--b1_DZgCXoErBeNf57IGureUwnMk3hA1VnDyIb2P7FyM6U
Content-Type: text/html; charset=us-ascii

<html><body>
<p>Hi Mark,</p>
<p>This is a test email to see if you are using DKIM correctly.</p></body></html>

--b1_DZgCXoErBeNf57IGureUwnMk3hA1VnDyIb2P7FyM6U--

Am I missing something, or is PHPMailer signing the body correctly, but messing up the headers?

**Comment by Synchro** [comment]
This doesn't make much sense - there is only one DKIM signature and it covers both headers and body, so if either are wrong it won't match.

There are some unreleased changes in the master branch relating to DKIM signatures, so you could give that a try anyway (using dev-master in composer).

**Comment by MarkMcCorrie** [comment]
Do you know why it says a DKIM passed and one failed? It looks like the headers are listed under one DKIM, and the body under another?

**Comment by Synchro** [comment]
You have two DKIM headers, which is valid but not that common - it may be that you're creating one with PHPMailer, and your mail server is adding another. I'd recommend going with your mail server (it will be faster), so see what happens if you don't sign with PHPMailer – you should still end up with one DKIM header.
