### ISSUE TITLE
DKIM body hash did not verify

### ISSUE THREAD

**Issue by Anorionil** [PHPMailer/PHPMailer#1307]
# Problem description
I've updated from 5.2.24 to the latest version of PHPMailer, and now Gmail tells me DKIM is incorrect. 

# Code to reproduce
```
//This should be the same as the domain of your From address
$mail->DKIM_domain = 'domain.com';
//Path to your private key file
$mail->DKIM_private = '..../dkim_private.pem';
//Set this to your own selector
$mail->DKIM_selector = 'mail';
//If your private key has a passphrase, set it here
$mail->DKIM_passphrase = '';
$mail->send();
```

# Debug output
Delivered-To: my_email@gmail.com
Received: by 10.100.144.72 with SMTP id y8csp726914pjd;
        Wed, 27 Dec 2017 04:40:54 -0800 (PST)
X-Google-Smtp-Source: ACJfBovYbzz51IQLk2PgyO7OMRkeIxJEAO6O+IpwWbEVMeDg6vW1gOysz5pISaPvyKDxyCYIRwaS
X-Received: by 10.223.139.16 with SMTP id n16mr22857434wra.84.1514378454606;
        Wed, 27 Dec 2017 04:40:54 -0800 (PST)
ARC-Seal: i=1; a=rsa-sha256; t=1514378454; cv=none;
        d=google.com; s=arc-20160816;
        b=krFIyyRZ6OUzNl2dQAxAE9svu+buKF7gCXwLBI/6FrHUkYKlTAKCwN9Sz8Wm/DbBI4
         ug8Fc2lt+nBklCi5oTPeE2UEE5yhFmDJfoP3SCgtgpGcpQoY7BeRcfwCF9p2E+Upg3R0
         Pjaxc7Tego0ZqXuZ8uQDU9E9Scc63w25q7kakhlJvYTSZOQ3YW2AOyXTZZDM76qIYTMj
         2GCfVbn6W/X9qsCXmvca4H8L3nELN1q1AwHndN+JzNQ9P7NORZhLK8QoCNb2/lSDIcuP
         IcdJVbLMr+IEOsPYun9YjH3fB6IDW7JQZGa8tCLLXqLB9nvrSviu9k7zy4H08Y2ERnSd
         gL1g==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=dkim-signature:mime-version:message-id:from:date:subject:to
         :arc-authentication-results;
        bh=CXb2+/K8hzVnoTsvboqUxdxqf2zd0oGlFp7Et4jxCn8=;
        b=vA60wfK1TXjkzVI4zcKrctWvw7NnBXcDdq45gHyRcuEOxmIf/C4CWDfP5/2dc9rhFm
         7ZnEAnlBGSMtMXiBgGV+T2S+csMKLw0samIe3/GfHC5zQp62u014g8PIr0oi9WVpDL92
         wn1wbJz/ya14IMmWSCKveeqR7Lgt/va7rBqNmS/RYg30a7f3yT08aZcY9pBAi8Y9ksRB
         NgGwXUdQ2aFgIofJ6Rjls9HYpMcqUmbj2VGJunyaoeSEp7IUjyGq7Ylqs/xPhaIgNRGg
         jV+NXLE3SZjpuN61ItmTSxiSv5f5oCxtO7fPZINryyVlkMQndEwK2OzV8KG7qMvvCYOQ
         h49Q==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=neutral (body hash did not verify) header.i=@domain.com header.s=mail header.b=Tg0IurnR;
       spf=pass (google.com: domain of noreply@domain.com designates 188.165.221.81 as permitted sender) smtp.mailfrom=noreply@domain.com;
       dmarc=pass (p=QUARANTINE sp=NONE dis=NONE) header.from=domain.com
Return-Path: <noreply@domain.com>
Received: from domain.com (domain.com. [188.165.221.81])
        by mx.google.com with ESMTPS id 76si13856222wmv.102.2017.12.27.04.40.54
        for <my_email@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Wed, 27 Dec 2017 04:40:54 -0800 (PST)
Received-SPF: pass (google.com: domain of noreply@domain.com designates 188.165.221.81 as permitted sender) client-ip=188.165.221.81;
Authentication-Results: mx.google.com;
       dkim=neutral (body hash did not verify) header.i=@domain.com header.s=mail header.b=Tg0IurnR;
       spf=pass (google.com: domain of noreply@domain.com designates 188.165.221.81 as permitted sender) smtp.mailfrom=noreply@domain.com;
       dmarc=pass (p=QUARANTINE sp=NONE dis=NONE) header.from=domain.com
Received: by domain.com (Postfix, from userid 10000) id 256F34E00A2; Wed, 27 Dec 2017 13:40:54 +0100 (CET)
To: my_email@gmail.com
Subject: BGO Test mail2
X-PHP-Originating-Script: 0:PHPMailer.php
Date: Wed, 27 Dec 2017 13:40:54 +0100
From: Board Game Online <noreply@domain.com>
Message-ID: <xwYc2FKzzihbjZmEpxNiOLjOm2lm3WMqJIKP5HtiiaI@www.domain.com>
X-Mailer: PHPMailer 6.0.2 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/html; charset=iso-8859-1
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; l=68; s=mail; t=1514378454; c=relaxed/simple; h=From:To:Date:Subject; d=domain.com; z=From:=20Board=20Game=20Online=20<noreply@domain.com> |To:=20my_email@gmail.com |Date:=20Wed,=2027=20Dec=202017=2013:40:54=20+0100 |Subject:=20BGO=20Test=20mail2; bh=SwEF1/e+vtQis72heIO6oKYjZlVOnusSaRi/jV3IvoE=; b=Tg0IurnRbGw5xKjdzFMICWTup/Kywo2TiI+WPyviCjcsx3f/9n3zKxK2loya2auVDsuWc1Zz57JcH3javAM/ozkHBVDKboV93XpiiqTsJSsGb5Z0eP9hGPybyWwr99kh3bVK0A7npTR29LC8sRDI4e9nMYTb4HSn/CZSJy1+uHGOgn1FHTgD22qYIqlwfErJqTOmW1gpMcH+foxOw57EHLdgDDpfvGbJP+ygu1RJB+xMEEdl0hs87KUUMgC8fNezYDVCnxx/NSROe8coXgHEeku41iMtlC4nlrlaw8z8gyt2qozCqjz90FYlbZRW+kG7aIpNkaklpc2eh5nesaxxlg==

<html><head></head><body>Hi,<br>Another small test...</body></html>

**Comment by Synchro** [comment]
When you say "the latest version", do you mean the current master branch, or the 6.0.2 release? 6.0.2 is the latest released version, but there are DKIM-related changes that have not yet been released. Please can you check using the master branch?

**Comment by Anorionil** [comment]
I'm using composer (with default settings) and according to the headers I'm using PHPMailer 6.0.2. Does that answer your question?

**Comment by Synchro** [comment]
Yes - it means you're using the release 6.0.2. Can you try changing your `composer.json` to say `dev-master` instead of `6.0.*`, or whatever you have there at the moment, for the PHPMailer package version, then run `composer update` and it will pull the latest dev version.

**Comment by Anorionil** [comment]
That fixes the issue! Any advice on how to proceed? Should I keep dev-master until there is a new release?

**Comment by Synchro** [comment]
That's good news! Yes - stick with dev-master for now. I'll aim to do a release next week, and I'll be sure to comment on this issue so you know when it's done.

**Comment by Synchro** [comment]
I've just tagged the 6.0.3 release which includes this fix.

**Comment by Marvin261** [comment]
**I also have the same problem. I used gmail for testing email connection with PHPMailer.

It does not display a signed email domain and display this message

dkim=neutral (body hash did not verify) header.i=@bookingwebapp.com header.s=oracle-ap-jerusalem-1-202306


But I fix the issue using a trim commands like PHP script $HtMLBodyMsg = trim($HtMLBodyMsg);
I do not use or modify composer.json or dev-master

Now it shows a signed email.**
