### ISSUE TITLE
SSL operation failed with code 1 !

### ISSUE THREAD

**Issue by miguelk5** [PHPMailer/PHPMailer#1309]
Please do not close this error , because i think is caused by PHPEmailer.

 Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in C:\xampp\htdocs\controller\Emailer\PHPMailer\class.smtp.php on line 338

Error details : https://i.imgur.com/sh9P6tA.jpg

-php emailer setup : 
    $mail=new PHPMailer();

    $mail->SMTPOptions = array(
        'ssl' => array(
            'verify_peer' => false,
            'verify_peer_name' => false,
            'allow_self_signed' => true
        )
    );

-php.ini : https://pastebin.com/6VgYHwFS

-vhost config : 

<VirtualHost *:443>
    ServerAdmin madocter@live.com
    DocumentRoot "/xampp/htdocs"
    ServerName lineage2-classic.net
    ServerAlias www.lineage2-classic.net
    ##ErrorLog "logs/dummy-host2.localhost-error.log"
    ##CustomLog "logs/dummy-host2.localhost-access.log" combined
    SSLEngine on
    SSLCertificateFile "conf/ssl.crt/lineage2classic.crt"
    SSLCertificateKeyFile "conf/ssl.key/lineage2classic.key"
</VirtualHost>

**Comment by Synchro** [comment]
No, it's really not *caused* by PHPMailer - that's just where the symptoms show up. It's caused by either the server presenting an invalid or expired certificate, or that the CA certificates you have installed in your OS (and thus used by PHP) are outdated and do not include the root certificate required to verify the certificate presented by the server. How to diagnose and remedy this is described [in the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#certificate-verification-failure).

It has nothing to do with the configuration of your vhost  - that's only used for HTTPS, not SMTP.

**Comment by sbhelper** [comment]
What worked for me (using Windows 10 and Apache with the included OpenSSL) was to create a gmail.crt file, like this:

1. openssl s_client -connect smtp.gmail.com:587 -starttls SMTP
   a. Copy the first cert (cert chain)
   b. Paste it to a text file
2. Download the root certificate as specified above the second certificate (I bolded what to look for)
   a. In my case, it showed: 1 s:/C=US/O=Google Trust Services/CN=Google Internet Authority G3
   i:/OU=**GlobalSign Root CA - R2**/O=GlobalSign/CN=GlobalSign
   b. I went here: https://support.globalsign.com/customer/portal/articles/1426602-globalsign-root-certificates
   c. Copied the base64 cert from R2 GlobalSign Root Certificate
   d. Pasted it to the bottom of the text file, below the cert chain
3. Save the text file and change the extension to .crt (ie. gmail.crt)


Then use this:
$mail->SMTPOptions = array(
            'ssl' => array(
                'verify_peer' => true,
                'verify_peer_name' => true,
                'allow_self_signed' => false,
                'cafile' => '[path-to-cert].crt'
            )
        );

I hope this helps at least one person.

**Comment by Synchro** [comment]
That will work, but it will only help for servers using that specific certificate. The guide suggests downloading the CA cert bundle from curl, and that download does include GlobalSign R2 certificate you pointed to, and that should also make sure that any other similar roots are updated too. You can use the SMTP options as you suggest, but I'd recommend fixing it using `openssl.cainfo` in your php.ini, as that will fix it for all uses of SSL in PHP, not just this specific instance with PHPMailer.
