### ISSUE TITLE
How to use undisclosed-recipients ?

### ISSUE THREAD

**Issue by krahamath** [PHPMailer/PHPMailer#1311]
I am trying to hide receptionist one from one using **To: undisclosed-recipients:;** but i am getting following error.

```
Invalid address: (to): To: undisclosed-recipients:;
Message could not be sent.Mailer Error: Invalid address: (to): To: undisclosed-recipients:;
```

**Code:**
   ```
 $mail->addAddress("To: undisclosed-recipients:;");
    $mail->setFrom('my@example.com', 'Example');
    $mail->addReplyTo('my@example.com', 'Example');

    foreach ($listOfMail as $mailName => $mailAddress) {
		$mailAddress = trim($mailAddress);
		if (!empty($mailAddress)) {
			$mail->addBCC($mailAddress, $mailName);
		}
	}
```

**Comment by Synchro** [comment]
PHPMailer takes care of this for you. Just add BCC addresses and do not set a To address, and it will add the "undisclosed recipients" group address (which is what it is) automatically.

**Comment by krahamath** [comment]
But i see "to address is empty in the mails" 
![toaddress-empty](https://user-images.githubusercontent.com/6831562/34409413-fb034c16-ebc9-11e7-9265-825def2c1a5f.png)

**Comment by Synchro** [comment]
Look at the raw message source - how it is presented in an email client will vary, and you don't have much control over that. You can see how PHPMailer handles it [in the source code](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L1430).
