### ISSUE TITLE
Problem with setting bounce email

### ISSUE THREAD

**Issue by NaveNO** [PHPMailer/PHPMailer#1312]
Hi. I am trying to set the bounce email in PHPMailer. I've read that setFrom() already sets Return-path header. But it is not. When I send email to Mail tester, it shows: Bounce address: apache@avect.ru. Where is it getting that "apache" from?...  Also I've tried to set Sender variable - no success. Help me please..
Using CentOS 7 with Exim on board. Latest PHPMailer. Here is some code:

```
$mail->setFrom($site['from_email'], $site['from_name']);   //$site['from_email'] = "dispatch@avect.ru"
$mail->addAddress($row['email']); 
$mail->addReplyTo($site['reply_email'], $site['reply_name']);   //Sets perfectly
$mail->addCC('cc@eavect.ru');  //Sets perfectly
$mail->addBCC('bcc@avect.ru');  //Sets perfectly
$mail->AddCustomHeader("Precedence: bulk");  //Sets perfectly  
$mail->XMailer = ' ';
$mail->isHTML(true);
$mail->Subject = $_POST['dispatch_name']; 
$mail->Body    = $htmlBody;
$mail->AltBody = $altBody;
$mail->send();

```
`

**Comment by NaveNO** [comment]
Problem solved: Exim refused to accept Sender header. You will need to tell Exim not to rewrite Sender by server user.

**Comment by Synchro** [comment]
> I've read that setFrom() already sets Return-path header.

I've no idea where you read that, but this is untrue. You can set the `Sender` *property* (not a header) in PHPMailer, which is used for the SMTP envelope sender. If you do not set it explicitly, the from address is used by default. It *does not* set a sender header, nor does it set a return-path header. The return-path header is added by the *receiving* server, and it is usually taken from whatever is used in the SMTP envelope sender. In short, the `Sender` property will usually end up in a return-path header in a received message, but it's not PHPMailer that puts it there, and you should not try to add it.

If you don't set a from address, PHPMailer will generate one from your current username (this is probably where "apache" comes from) and your server's host name. bear in mind that some services will not let you set an arbitrary from address (for example gmail), and will fall back to your user account name instead.
