### ISSUE TITLE
PHPMailer class not found with PHPAuth using Composer

### ISSUE THREAD

**Issue by qarizma** [PHPMailer/PHPMailer#1319]
Hello,

I'm trying to setup PHPAuth using Composer which uses PHPMailer for sending mails. I'm receiving the following error after installation using Composer:
`PHP Fatal error:  Uncaught Error: Class 'PHPMailer\PHPMailer\PHPMailer' not found in C:\Users\X\vendor\phpauth\phpauth\Auth.php:794`

The Auth.php file which is loaded by Composer contains:
```
namespace PHPAuth;
use ZxcvbnPhp\Zxcvbn;
use PHPMailer\PHPMailer\PHPMailer;

// skipped code
$mail = new PHPMailer;
```

I'm autoloading everything using:
`require __DIR__.'/vendor/autoload.php';`

I have been looking all over the internet for a while and I couldn't find a direction. The issue might not be directly linked to PHPMailer, however I would appreciate help regarding this error. I'm using PHP 7.2 on Windows.

Thanks! :)

**Comment by cameraki** [comment]
I am having the same issues with this. Did you find a solution?

**Comment by qarizma** [comment]
I stopped using Composer and simply include the required files, the easy way!

**Comment by Synchro** [comment]
Does PHPAuth depend on PHPMailer 6.0? If it's not been updated for that then the class is not namespaced and you'll get exactly that symptom. I find composer is easier for even a single dependency like PHPMailer, but when you have a project of any meaningful size, it becomes vital. Frameworks like Symfony and Laravel would be considerably worse without it.

**Comment by cameraki** [comment]
I applied [this fix](https://github.com/PHPAuth/PHPAuth/issues/281) (bottom of the page). But meant I had to actually edit the Auth.php file.

@Synchro it just requires anything above 5.2.
`"phpmailer/phpmailer": "^5.2"`

I have checked the version of the one I have (used composer to download this a few days ago) and its 5.2.26

**Comment by Synchro** [comment]
Well that makes sense - you can’t tell it you’re going to use PHPMailer’s namespaced class name and then use an old PHPMailer version that doesn’t support it, or vice versa.

**Comment by Synchro** [comment]
Note the meaning of your version string `^5.2` does not mean “5.2 and above”. It means >= 5.2.0 and < 6.0. See [composer docs](https://getcomposer.org/doc/articles/versions.md#next-significant-release-operators). I recommend using the namespace and changing the version match to `^6.0`, which will match all versions up to (but not including) 7.0.

**Comment by cameraki** [comment]
@Synchro I will try and require 6.0 and see if that fixes it and also submit this to PHP AUTH to be adjusted
