### ISSUE TITLE
How to Use Ipv6 for hostname

### ISSUE THREAD

**Issue by ashikkaiser** [PHPMailer/PHPMailer#1320]
hello . i  want to know how to add ipv6 adrs for hostname ,, or is it possible ??

**Comment by Synchro** [comment]
Sure. Just set it in the `Host` property using square brackets around the address:

    $mail->Host = ‘[2048:1234:...:1]’;

Obviously you also need your server to have a working IPv6 stack and address.

**Comment by ashikkaiser** [comment]
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting SMTP PROBLEM

**Comment by Synchro** [comment]
Well it won’t work then, unless you configure a 4-to-6 tunnel, which is outside PHPMailer’s control.
