### ISSUE TITLE
SMTP ERROR: Failed to connect to server: Connection timed out (110) SMTP connect() failed

### ISSUE THREAD

**Issue by bhaveshsrkaycg** [PHPMailer/PHPMailer#1326]
This is my code.

```
$mail = new PHPMailer;
$mail->isSMTP();
$mail->SMTPDebug = 2;
$mail->Debugoutput = 'html';
$mail->Host = "mail.domain.com";
$mail->Port = 25;
$mail->SMTPAuth = true;
$mail->Username = 'marketing@domain.com';
$mail->Password = "***********";
```

Following is my credentials :

Email:marketing@domain.com
Password:**********
Account Type – “POP”
Incoming and Outgoing Mail Server Details – “mail.domain.com”
Incoming Server – “110”
Outgoing Server – “25”

It gives me following error :

**SMTP ERROR: Failed to connect to server: Connection timed out (110)**

PHP mailer works well with my gmail smtp ssl authenticatoin.
But for client email host, it gives error.

Can you tell me what is the problem ?

**Comment by Synchro** [comment]
Sounds like you have the wrong mail server name, or your mail server is down. There's nothing PHPMailer can do about that.

**Comment by bhaveshsrkaycg** [comment]
Let me check. Thanks for taking interest in my problem and leading me in a right direction. 
Let you know, if anyother help required.

**Thanks** :)
