### ISSUE TITLE
Subject Encoding

### ISSUE THREAD

**Issue by sergeyklay** [PHPMailer/PHPMailer#133]
Hi!

I want to know any special settings needed for Subject consisting of the non-Latin characters? I am interested in UTF-8.

Of course I understand that need to set `$CharSet` value. I do this in my application, after creating a PHPMailer object:

``` php
        // Create phpmailer object
        $this->mail = new PHPMailer(true);

        // Set some defaults
        $this->mail->setFrom('sadhooklay@gmail.com',  'Gleez CMS');
        $this->mail->WordWrap = 70;
        $this->mail->CharSet  = 'UTF-8'; // the same as 'utf-8'
        $this->mail->XMailer  = 'Gleez CMS 0.10.5';
        $this->mail->setLanguage('ru');
        $this->mail->Debugoutput = 'error_log';
```

**Please see screenshot**

![mail_title_encoding](https://f.cloud.github.com/assets/1256298/1492630/0a5b44e8-47c3-11e3-931f-ee7f96c496df.png)

Mail body is displayed correctly (in Russian), but Subject - no.

**Mail header for this screenshot**

```
Return-Path: <sadhooklay@gmail.com>
Received: from cerber.homedomain ([213.87.143.240])
        by mx.google.com with ESMTPSA id ac2sm829046lbc.10.2013.11.06.15.52.11
        for <sadhooklay@gmail.com>
        (version=TLSv1.2 cipher=RC4-SHA bits=128/128);
        Wed, 06 Nov 2013 15:52:12 -0800 (PST)
Received: from www-data by cerber.homedomain with local (Exim 4.80)
    (envelope-from <sadhooklay@gmail.com>)
    id 1VeCtq-0001ha-2l
    for sadhooklay@gmail.com; Thu, 07 Nov 2013 03:52:38 +0400
To: Sergey <sadhooklay@gmail.com>
Subject: =?UTF-8?B?PT91dGYtOD9CP1IyeGxaWG9nUTAxVElDMGcw?=
 =?UTF-8?B?Si9SZ05DKzBMTFF0ZEdBMExyUXNDRFJnTkMxMExQUXVOR0IwWUxSZ05Ddz89?=
 =?UTF-8?B?CiA9P3V0Zi04P0I/MFliUXVOQyswTDNRdmRHTDBZVWcwTFRRc05DOTBMM1Jp?=
 =?UTF-8?B?OUdGSU5DMDBMdlJqeUJUWlhKblpYaz0/PQ==?=
X-PHP-Originating-Script: 1000:class.phpmailer.php
Date: Wed, 6 Nov 2013 23:52:37 +0000
From: Gleez CMS <sadhooklay@gmail.com>
Message-ID: <efa7137ed2786dce7636a98b8feb5e2a@gleez.lo>
X-Priority: 3
X-Mailer: Gleez CMS 0.10.5
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit
```

I sent mail using the localhost:
- Debian 7.2 (wheezy)
- Kernel 3.2.0-4-amd64
- Exim 4.80 (as /usr/sbin/sendmail)
- **PHPMailer** 5.2.7 (github master branch)

I use smarthost setting for Gmail

Locale:

```
LANG=ru_RU.utf8
LANGUAGE=
LC_CTYPE="ru_RU.utf8"
LC_NUMERIC="ru_RU.utf8"
LC_TIME="ru_RU.utf8"
LC_COLLATE="ru_RU.utf8"
LC_MONETARY="ru_RU.utf8"
LC_MESSAGES="ru_RU.utf8"
LC_PAPER="ru_RU.utf8"
LC_NAME="ru_RU.utf8"
LC_ADDRESS="ru_RU.utf8"
LC_TELEPHONE="ru_RU.utf8"
LC_MEASUREMENT="ru_RU.utf8"
LC_IDENTIFICATION="ru_RU.utf8"
LC_ALL=
```

Excuse me, I'm not sure what other information I should provide.

It seem to me this issue associated with the UTF-8 string which is divided into blocks of 78 bytes. Probably with short strings is no problem. I really have tried different methods of decoding/encoding the Subject (`mb_encode_mimeheader`, `utf_encode`, `base64_encode`, `strtolower($CharSet)` - any tricks that I could find on the google.) and not found solutions.

Another tip that will help you understand the cause of the issue: Subject consists of Latin and non-Latin characters. The first and last word in English (Latin), the rest - Russian words (Cyrillic).

Any ideas?

**Comment by xeredin** [comment]
> ```
> "=?utf-8?B?".base64_encode($subject)."?="
> ```

thank you "=?utf-8?B?".base64_encode($subject)."?=" it solved my problem

**Comment by jcaraly** [comment]
> > ```
> > "=?utf-8?B?".base64_encode($subject)."?="
> > ```
> 
> thank you "=?utf-8?B?".base64_encode($subject)."?=" it solved my problem

Thank you really much, after some times to look everywhere, that's solution work for me too !! 
(on PHPMailer - PHP email class  Version: 2.0.4) with php 7

**Comment by Synchro** [comment]
Please don't use that ancient version. I'm surprised it still works at all, but it also likely means you are vulnerable to several major security holes. Fix it properly and use the latest version.

**Comment by jcaraly** [comment]
> Please don't use that ancient version. I'm surprised it still works at all, but it also likely means you are vulnerable to several major security holes. Fix it properly and use the latest version.

Thank you for your reply, Yes I will purpose to update to my customer ! 
Installed more than 7 years ago and still work properly !

**Comment by galanta78** [comment]
Hello, I am having the same problem and I can't figure out what the solution actually is.  The problem appears in a forum installation, vanilla forums: https://open.vanillaforums.com/
The phpmailer class they were using was a bit out of date, I replaced it with the newest available. Though, I have extactly the same problem with @sergeyklay , mail body is ok, the subject is messy, something like this:

=?UTF-8?B?W86azr/Ouc69z4zPhM63z4TOsSDOn86jzpTOlV0gzpcgzpHOr8+EzrfPg86u?= =?UTF-8?B?IM6czq3Ou86/z4XPgiDOlc6zzrrPgc6vzrjOt866zrUg?

What else could I do? The non-latin language used there is Greek. Thanks.

**Comment by Synchro** [comment]
It's likely that the calling script is applying encoding before passing the value to PHPMailer, which then encodes what it's given in a way that preserves its original unnecessarily-encoded value.

**Comment by galanta78** [comment]
Indeed I found this inside an email class of the software:

```
public function subject($subject) {
        $this->PhpMailer->Subject = mb_encode_mimeheader($subject, $this->PhpMailer->CharSet);
        return $this;
    }
```

just for the subject. All the other parts are sent unencoded. I replaced the second part with just the value of $subject and it is ok. Thanks.

**Comment by Synchro** [comment]
Good – it would help if you could report that problem upstream so it gets fixed for all the others that use it, rather than having them all turn up here!

**Comment by galanta78** [comment]
Yes, of course I already did so :)

**Comment by chris001** [comment]
Still getting `utf-8` encoded subjects displaying in a php imap email client using `phpmailer` for sending email in 2023.  For an improved solution, what about scan the subject string for signs it's already encoded `utf-8`, and if so, skip double encoding it, just use the subject string as-is?

**Comment by Synchro** [comment]
That code isn't doing what you think it is. `mb_detect_encoding` detects binary character set encodings, not other encodings like the RFC2047 encoding used here or things like URL encoding or base64. The contents of `$str` is already valid ASCII, ISO-8859-1, and UTF-8, so it returns the first match from the options you provided, in this case UTF-8. You'll find that if you set `$str = 'abc'`, you get a false positive.
Anyway, it would be more appropriate to do that in the application layer, and to be thorough, this approach would need to be recursive to handle multiply-encoded subjects, all of which would also prevent you from mentioning incorrectly encoded subject lines in email subjects :)...

**Comment by chris001** [comment]
You're right, the code example isn't giving correct results.  Just to make this issue totally solved once and for all, I'd be satisfied with a simple approach, avoid double-encoding a subject that is already encoded.  PHPmailer could use a regex to `preg_match` for the pattern `"=?" charset "?" encoding (b or q) "?" encoded-text "?="` which would detect whether the subject is already [RFC2047 encoded](https://datatracker.ietf.org/doc/html/rfc2047), and also check it doesn't contain any other clear text, and if and only if this is the case, then encode the subject with RFC2047.

**Comment by Synchro** [comment]
Unfortunately that's an overly simplistic approach that would *not* solve the problem, and would cause other issues. RFC2047 is more subtle than that (e.g. you can mix multiple charsets in the same line, you should be able to have a subject line containing `=?` without issues), and it would likely cause unexpected problems and edge cases that I don't want to have to solve. I don't want PHPMailer to be in a position where it's second-guessing application-level concerns, which this is. If you don't want double-encoded subject lines, don't provide encoded subject lines.
