### ISSUE TITLE
SMTP ERROR: Failed to connect to server: Connection refused (111)

### ISSUE THREAD

**Issue by mk94mishra** [PHPMailer/PHPMailer#1340]
2018-01-24 20:07:12 SMTP ERROR: Failed to connect to server: Connection refused (111)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Not SentMailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
You already have the info you need.

**Comment by mk94mishra** [comment]
how to solve this problem??

**Comment by Synchro** [comment]
Here's a clue: https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

It's probably that your ISP is blocking outbound SMTP.

**Comment by halfer** [comment]
Try turning on SMTP debug and looking at the logs. Log level 2 is usually enough.
