### ISSUE TITLE
Automatically fix PHP errors on pull requests

### ISSUE THREAD

**Issue by tgrundmanis** [PHPMailer/PHPMailer#1342]
I run [Stickler-CI](https://stickler-ci.com/) which is a service aimed at improving code quality by simplifying code review by automating code feedback in pull requests. 

We just launched auto-fixing for PHP through pull request commits. As a PHP open source project, our service will save you time and brain power by automatically fixing style errors.

If you are interested in trying out our product, we can submit a pull request with the configuration file, but a maintainer will need to enable webhooks by logging into https://stickler-ci.com and enabling the webhook.

Thank you!

**Comment by halfer** [comment]
Cheeky, but I appreciate as a start-up owner, one has to try everything to gain traction. :wink:

I've no association with the project, other than as a user, but could you analyse some current/past PRs to show what sort of suggestions your product would make? If they are really good, maybe you'd get some bites.

**Comment by Synchro** [comment]
We've already got fairly tight phpcs config that's enforced on PRs, and also have [scrutinizer-ci](https://scrutinizer-ci.com/g/PHPMailer/PHPMailer/) configured, so it sounds like we already have quite a lot of the same stuff covered already. I'm not that big a fan of auto-fixing as I've seen it make too many mistakes. What advantages do you have over those?

**Comment by tgrundmanis** [comment]
I am cheeky, and persistent 😉. Let me get you some examples from my tech partner. Stay tuned!

**Comment by tgrundmanis** [comment]
Hello again!

I have an example of how our product works. Take a look at this PR thread:

https://github.com/cakephp/cakephp/pull/11645

If you dive deeper into the second commit, which has the fixes, you can see how it works in a more detailed fashion:

https://github.com/cakephp/cakephp/pull/11645/commits/c259c729778b76257cf1f71e02c989b46cf2f727

However, if your current service already performs these fixes, I am wondering if you have any other code quality issues that aren't being met by your current product. If so, we can discuss how we might be able to fill that gap 😊.

Cheers,

Tara
