### ISSUE TITLE
Same Configuration with Gmail Example but still not working

### ISSUE THREAD

**Issue by carlbinalla** [PHPMailer/PHPMailer#1344]
# Problem description
Even after checking with example [here](https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail.phps), I can't still send using Gmail in PHPMailer. See below for error

- **Check it's there at all** - true
- **Check it's a mail server** - true
- **Authentication failures** - correct username and password
- **Gmail, OAuth2 and "Allow less secure apps"** - enabled Two-Step Verification, and is using App Password
- **Using encryption** - true
- **Check you have the openssl extension** - enabled
- **Encryption flavours** - using **tls** and port **587**
- **Check it's a mail server** - true
- **Check it's a mail server** - true
- **Check it's a mail server** - true
- **Check it's a mail server** - true

# Code to reproduce
    $mail = new PHPMailer(true);
    try {
        $mail->IsSMTP(); 
        $mail->SMTPDebug  = 1;                     
        $mail->SMTPAuth   = true;                  
        $mail->SMTPSecure = "tls";                 
        $mail->Host       = gethostbyname('smtp.gmail.com');      
        $mail->Port       = 587;             
        $mail->AddAddress($email);
        $mail->Username="someEmail@gmail.com";  
        $mail->Password="appPassword";            
        $mail->SetFrom('someEmail@gmail.com','Some text');
        $mail->Subject    = $subject;
        $mail->MsgHTML($message);
        $mail->Send();
    } catch (Exception $e) {
        echo 'Message could not be sent. Mailer Error: ', $mail->ErrorInfo;
    }
# Debug output
>2018-01-26 08:38:54 CLIENT -> SERVER: EHLO localhost
2018-01-26 08:38:54 CLIENT -> SERVER: STARTTLS
SMTP Error: Could not connect to SMTP host.
2018-01-26 08:38:55 CLIENT -> SERVER: QUIT
2018-01-26 08:38:55 
SMTP Error: Could not connect to SMTP host.
Message could not be sent. Mailer Error: SMTP Error: Could not connect to SMTP host.

**Comment by Synchro** [comment]
It's not your code, it's your environment. You need to update your CA certificates. Exactly this problem is covered in detail in the troubleshooting guide.
