### ISSUE TITLE
Custom headers for boudary

### ISSUE THREAD

**Issue by Med-All** [PHPMailer/PHPMailer#1345]
Allow to add custom headers or update header parameter for each boundary.

Example:
I need to add/update

```
--b1_KyZbvbrSl55hdWoQf7uUOwdfF2oGjqnCyP6rqNmlA
Content-Type: text/plain; name="test.txt"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: attachment; filename=test.txt
```
to looks like

```
--b1_KyZbvbrSl55hdWoQf7uUOwdfF2oGjqnCyP6rqNmlA
Content-Type: text/plain; name="test.txt"; charset=utf-8
Content-Transfer-Encoding: quoted-printable
Content-Disposition: attachment; filename=test.txt
Content-ID: 20cca107-2625-49ce-9357-95254a59147f@127.0.0.1
```
so for the `Content-Type` header was added `charset` parameter and then added new header `Content-ID` for

`$mail->addStringAttachment($test, 'test.txt', 'quoted-printable');`

which will looks like:

```
$mail->addStringAttachment($test, 'test.txt',  #'quoted-printable');
$mail->getAttachmentByName('test.txt')->addCustomHeader('Content-ID',$uuid);
$mail->getAttachmentByName('test.txt')->setHeaderByName('Content-Type','text/plain; name="test.txt"; charset=utf-8');
```

**Comment by Synchro** [comment]
There isn't a provision to do that, however, you don't need it - quoted-printable transfer encoding is ASCII 7bit safe, so the default will work fine and it doesn't need an extra charset clause.

The `addStringEmbeddedImage` method lets you set a cid for the attachment which will set that header for you - you can ignore the "image" in the method name - it doesn't care what type of content you attach really.

**Comment by Med-All** [comment]
I have tried that method and it works fine for text containing attachments (or a string in my case) but when I will do something like

`$mail->addStringEmbeddedImage('sample.pdf', $uuid, 'sample.pdf', 'base64', '', 'attachment');`

result is not the same as

`$mail->addAttachment('sample.pdf');`

Should I stream `sample.pdf` first or just open it to stream and then pass that to the function?

**Comment by Med-All** [comment]
Never mind - `file_get_contents()` did the job. 

Thanks for you help. You can close that topic.
