### ISSUE TITLE
$cMail->Send(); returns FALSE but sent mail

### ISSUE THREAD

**Issue by Bert-de-Jong** [PHPMailer/PHPMailer#1346]
Intro
-----
Despite not having tested this with the most recent PHPMailer, I'm still giving this feedback (writing this bug report), just in case it's still relevant with recent versions. If it's a known issue that has already been fixed, obviously it's fine to close this ticket. I also think that Google indexing this issue might help fellow coders who use my version of PHPMailer and could run into the same issue in the future.

Issue
-----
With a _really_ large attachment and $Timeout on 10, $cMail->Send(); returns FALSE even though the recipient got the e-mail. (As a result, if code checks for the returned value and keeps trying failed mails, the recipient receives the really large e-mail over and over.) The server appears to return "Language string failed to load: data_not_accepted".

**Comment by Synchro** [comment]
The exact text of that error message tells me that you're using a **very** old version of PHPMailer, so I suggest updating and retrying.
