### ISSUE TITLE
Sending HTML-Emails with UTF-8 Encoded Body and Alt-Body

### ISSUE THREAD

**Issue by seehma** [PHPMailer/PHPMailer#1354]
Hi,
i have a problem with sending HTML and UTF-8 encoded E-mails with PHP-Mailer Version 6.0.3 and i hope one can help me here. I could not find anything about this issue on the web and also not here in the docs. It seems that the order of how i Enter a message into the AltBody and Body Properties makes a difference but i could not figure out why and how...
Let me know if some else information is needed
Thanks in advance
M.

# Problem description
I try sending an E-Mail with CharSet UTF-8 but i get only the Alt-Body encoded with UTF-8 the normal HTML-body ($mail->Body='test') comes encoded as ascii.

# Code to reproduce
```
date_default_timezone_set('Europe/Vienna');
$mail = new PHPMailer(true);   
$mail->setLanguage("de");  
// Server-Settings
$mail->IsSMTP();    
$mail->Host     = $SMTPServer;
$mail->SMTPAuth = true;
$mail->Username = $SMTPUsername;
$mail->Password = $SMTPPassword;
$mail->SMTPSecure = 'tls';
$mail->Port = 587;
$mail->From     = $emailAbsenderEmail;      
$mail->FromName = $emailAbsenderName;
$mail->AddAddress($emailEmpfaenger); 
$mail->AddCC($emailCC);
$mail->AddBCC($emailBCC);
$mail->AddAttachment($datei);
$mail->AddAttachment($dateiAGB);

$mail->IsHTML(true); 
$mail->Subject = $emailBetreff; 
$mail->AltBody = "HTML Emails not supported by your Client.";
$mail->Body = 'Test mit ÜmlÄuten Äber pässt;';
$mail->CharSet = 'UTF-8';     
$mail->Send();
```
# Debug output
This is a part of the E-Mails Source-Code (out of Thunderbird), and here you can see, the text/html part is not encoded with charset=UTF-8, but why?

Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

HTML Emails not supported by your Client.

Content-Type: text/html; charset=us-ascii

Test mit &Uuml;ml&Auml;uten &Auml;ber p&auml;sst;

**Comment by Synchro** [comment]
This is a bit strange, and it works fine in the unit tests.

I wondered if something was interfering with your debug output on github, so I looked at the source you posted and it looks like this:

```
Test mit &Uuml;ml&Auml;uten &Auml;ber p&auml;sst;
```

That explains why it's us-ascii - it's using HTML entities, not real UTF-8 chars, and so it really is 7-bit us-ascii and thus the headers are correct. PHPMailer doesn't convert anything to entities, so something else you're doing is responsible for that.

Your AltBody MIME structure is unexpected - your example contains no 8-bit chars, and so PHPMailer will normally downgrade it to ascii, 7bit CTE (as it's doing for your HTML part); not doing that is a minor RFC contravention.

**Comment by seehma** [comment]
Thanks for your reply.

Do i understand that right, that i only get UTF-8 encoded E-Mails when there are characters in the text, which require UTF-8? I did not think about this, because i thought when i set the CharSet Variable that PHPMailer is sending E-Mails always with UTF-8.

I will try that!

What you said about the alt body could be a problem of my example code. As i said i did not think about that PHPMailer is always setting the encoding to ASCII if there is no character which is requiring UTF-8 so i shortened the text of the AltBody, I have to see if there is a special tag in the longer version.

Thanks in Advance,

M.

**Comment by Synchro** [comment]
Yes. UTF-8 and all the ISO-8859 character sets are ASCII-compatible up to 7 bits, so if you only have 7bit chars in your content, having a charset other than us-ascii does nothing, and in fact adds text processing overhead, hence the recommendation to downgrade the content-type to 7bit us-ascii.

If you're using UTF-8, make sure that your script itself is using UTF-8.

**Comment by GokmenHakann** [comment]
i'm using Turkish language and i had this problem too so i used this 2 code and solve it 

```
$mail->SetLanguage("de", "phpmailer/language");
$mail->Encoding="base64";  //this code very important
```

**Comment by ZalemCitizen** [comment]
@GokmenHakann thanks, this does the trick.

I'm using PHPmailer within homemade implementation in a Wordpress theme / plugin, french language in subject and email
Charset utf-8 specified as header and as PHPmailer option.

When connecting to a basic SMTP server (OVH cloud provider), sending email to a recipient address configured on MS Exchange (Microsoft 365) : no charset issue 
Same system, same email, same recipient, but using Microsoft SMTP relay (no authentication, but server IP granted on Exchange) : UTF-8 issue on all accents

using 
```
$phpmailer->SetLanguage( "fr", "phpmailer/language" );
$phpmailer->Encoding = "base64"; 
```
get rid of encoding issue

**Comment by Synchro** [comment]
The language setting doesn't have anything to do with how messages are encoded. All it does is set the language used for error messages.

If base64 encoding is "fixing" your issue, it's because your UTF-8 encoding is messed up, and the base64 encoding is hiding it.

**Comment by ZalemCitizen** [comment]
You maybe right but how to explain a simple change of email provider is solving the issue ?
I'll do further test, there's surely an explanation in the message content

**Comment by GokmenHakann** [comment]
> @GokmenHakann thanks, this does the trick.
> 
> I'm using PHPmailer within homemade implementation in a Wordpress theme / plugin, french language in subject and email Charset utf-8 specified as header and as PHPmailer option.
> 
> When connecting to a basic SMTP server (OVH cloud provider), sending email to a recipient address configured on MS Exchange (Microsoft 365) : no charset issue Same system, same email, same recipient, but using Microsoft SMTP relay (no authentication, but server IP granted on Exchange) : UTF-8 issue on all accents
> 
> using
> 
> ```
> $phpmailer->SetLanguage( "fr", "phpmailer/language" );
> $phpmailer->Encoding = "base64"; 
> ```
> 
> get rid of encoding issue

You're welcome, I'm happy if I did any help
