### ISSUE TITLE
Content-Type: multipart/mixed;

### ISSUE THREAD

**Issue by ashikkaiser** [PHPMailer/PHPMailer#1355]
i want to set Content-Type: multipart/mixed; fixed  always email send  as mulipart/mixed

**Comment by Synchro** [comment]
PHPMailer will use `multipart/mixed` automatically where it's appropriate, typically where you have a single body part (i.e. just plain or HTML, not both) with attachments. If you use that pattern, that's the MIME structure you will get. What have you tried?

**Comment by ashikkaiser** [comment]
i tried . but its use when im sending with attachment . but  there is no attachment but content type multipart/mixed

MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="----=_Part_38430_1756052976.1518224052466"

------=_Part_38430_1756052976.1518224052466
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<html><head><title></title></head><body>
<p>Hey just saw that you responded to my ad lol who are you ? </p>

<p>you got pics?</p>
<div class="gmail_extra">On Fri Feb 09 19:51:56 EST 2018, Avinash <affiliateman123@gmail.com><span dir="ltr">&lt;<a style="color: #15c;" target="_blank" href="mailto:affiliateman123@gmail.com">affiliateman123@gmail.com</a>&gt;</span> wrote:<br><br><div dir="ltr">reply-01</div>
</div></body></html>
------=_Part_38430_1756052976.1518224052466--

**Comment by Synchro** [comment]
This output is not created by PHPMailer.
