### ISSUE TITLE
Simple contact form example outdated PHPMailerAutoload.php

### ISSUE THREAD

**Issue by ziuta** [PHPMailer/PHPMailer#1361]
# Problem description
I am newbie in php/phpmailer. I did everything according to the readme guidelines. Loaded latest version via composer, copied "Add simple form example" and used mine email addresses and hosts. 
What is probably obvious for you guys I had to replace 
`require '../PHPMailerAutoload.php'; `
with 
`require 'vendor/autoload.php';`

I also had to add
`use PHPMailer\PHPMailer\PHPMailer;`
Sadly it took me a longer while to figure it out, because it's mentioned few times here to use latest PHPMailer version and examples from this repository, so I was sure I did everythig correct. 
Shoulnd't this basic (and probably one of the most popular examples) be updated?

Cheers

**Comment by Synchro** [comment]
You’re quite right. Thanks for reporting. Want to submit a pull request to fix it?

**Comment by ziuta** [comment]
OK will do later!

**Comment by JakeCroz1** [comment]
There is no folder and file, vendor/autoload.php, located in PHPMailer directory. This is confusing...

**Comment by Synchro** [comment]
@jakecroz1 It can be confusing when you don’t read the readme which tells you where the vendor folder comes from, and how to load PHPMailer.
