### ISSUE TITLE
error smtp

### ISSUE THREAD

**Issue by mazwied** [PHPMailer/PHPMailer#1362]
I just try out this example https://www.askapache.com/php/phpfreaks-eric-rosebrocks-phpmailer-tutorial/, 
after update using this https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail.phps 
then become  like this 
`<?php
require_once($_SERVER['DOCUMENT_ROOT'].'/myapps/examples/email-verification/config.php');
require_once($_SERVER['DOCUMENT_ROOT'].'/lib/MailClass.inc');
$mailer = new FreakMailer();
$mailer->IsSMTP();
$mailer->SMTPDebug = 2;
$mailer->Mailer = 'smtp';
$mailer->Host = 'smtp.gmail.com';
$mailer->Port = 587;
$mailer->SMTPSecure = 'tsl';
$mailer->SMTPAuth = true; 
$mailer->Username   = 'mymail@gmail.com';  
$mailer->Password   = '12345'; 
$mailer->setFrom('mymail@gmail.com', 'From-ME');
$mailer->addReplyTo('mymail@gmail.com', 'ReplayTO-ME');
$mailer->AddAddress('mymail@gmail.com','ITS-ME');
$mailer->Subject = 'PHPMailer GMail SMTP test';
$mailer->Body = 'This is a test of my mail system!';
if(!$mailer->Send()){
    echo "Mailer Error: " . $mailer->ErrorInfo.'<br>';
}else{
    echo 'Mail sent!';
}
$mailer->ClearAddresses();
$mailer->ClearAttachments();
?>`

But error message produce  :
`SMTP -> FROM SERVER:220 smtp.gmail.com ESMTP p63sm61685830pfk.74 - gsmtp
SMTP -> FROM SERVER: 250-smtp.gmail.com at your service, [36.80.253.22] 250-SIZE 35882577 250-8BITMIME 250-STARTTLS 250-ENHANCEDSTATUSCODES 250-PIPELINING 250-CHUNKING 250 SMTPUTF8
SMTP -> ERROR: AUTH not accepted from server: 530 5.7.0 Must issue a STARTTLS command first. p63sm61685830pfk.74 - gsmtp
SMTP -> FROM SERVER:250 2.1.5 Flushed p63sm61685830pfk.74 - gsmtp
SMTP Error: Could not authenticate. Mailer Error: SMTP Error: Could not authenticate.`

Please,...can anybody fixed it, thanks anyway...
best regard

**Comment by mazwied** [comment]
sorry  i solve this problem after read and learn this https://github.com/PHPMailer/PHPMailer/issues/1106, and solve this issues like this 
![image](https://user-images.githubusercontent.com/16010856/36521872-db9c658c-17cb-11e8-95f8-29ba6d0c6c54.png)

**Comment by Synchro** [comment]
Your actual problem here was that you had `$mailer->SMTPSecure = 'tsl';` when it should be `$mailer->SMTPSecure = 'tls';`.
