### ISSUE TITLE
 check email go in inbox or spam or Bounced ?

### ISSUE THREAD

**Issue by younesyzd** [PHPMailer/PHPMailer#1366]
Hello 
is there an option to check the email if is go in inbox or spam or Bounced ?

**Comment by Synchro** [comment]
No. You need to use other methods for that.

Bounce handling can be facilitated by setting the `Sender` property in PHPMailer, then having some other script for handling bounces sent to that address (look up VERP addressing) - PHPMailer doesn't have anything to do with inbound messages.

Inbox/spam placement is not something you can detect at the point of sending, so you need to use other mechanisms for that, which are not part of PHPMailer, such as seed lists and mailbox monitors.

Some ISPs provide feedback loops that tell you when recipients report messages as spam, but again, that's not part of PHPMailer's area of responsibility.

Sorry it's not much help, but at least you now have some terms to search for...

**Comment by younesyzd** [comment]
Thank you very much .
