### ISSUE TITLE
imap_append 7KB size limit with Outlook 365

### ISSUE THREAD

**Issue by penncomm** [PHPMailer/PHPMailer#1368]
I have PHPMailer setup to use our Outlook365 server to send emails with attachments. It works great until the script, using imap_append, attempts to add the message to our "sent" folder. What I have discovered is that if the attachment is more than 7KB in size, it fails. Less than 7KB, it works. The recipient receives the attachment either way.

Any idea where this limitation is coming from and how I can increase it? 

I'm attaching the code block for saving the messages to the sent folder. 
```php
function save_mail($mail) {
global $config;
$MailHost = "{".$config->MailHost."/imap/ssl/novalidate-cert}Sent Items";
$path = $MailHost; 
if ($conn = imap_open($path, $config->MailUsername, $config->MailPassword)) {
    if (imap_append($conn, $path, $mail->getSentMIMEMessage())) {
        $result = true;
    } else {
        error_log("ERROR: Unable to save mail to 'Sent Items' folder.\n  - " . imap_last_error());
        $result = false;
    }
    imap_close($conn);
    return $result;
} else {
    error_log("ERROR: Unable to connect to IMAP server.");
    return false;
}
```

**Comment by Synchro** [comment]
Sorry, no idea. That code is only provided as an example - PHPMailer doesn't have anything to do with IMAP, and this sounds more like a service provider limitation than a client code problem anyway.
