### ISSUE TITLE
PHPMAILER INSTALLATION

### ISSUE THREAD

**Issue by lorddenning** [PHPMailer/PHPMailer#1371]
Would someone please help me on how to install the phpmailer using composer. I have been trying for days but I think I am not doing it right....

Am a starter and I need much help for a school project please!

**Comment by Synchro** [comment]
It's very straightforward. Install composer (see instructions on getcomposer.org), then run `composer require phpmailer/phpmailer` on a command line in your project folder. That will create a vendor folder and the `autoload.php` file that you need that is expected by all the code examples provided. That's it.

**Comment by Eternal-Infinity** [comment]
Also note that when you are at school and try to achieve this, you may be behind a proxy.
In that case, google "composer proxy", you may find something that helps you.
