### ISSUE TITLE
I don't understand what the 501 error represents, the mail server's fault or the code's fault

### ISSUE THREAD

**Issue by wl1508702360** [PHPMailer/PHPMailer#1372]
Hello, yesterday's test can still be sent, but today's test appears on the following chart error, what is the matter?

![image](https://user-images.githubusercontent.com/20127531/37193836-71cbc49a-23a6-11e8-9768-2dd24fe3ea07.png)
![image](https://user-images.githubusercontent.com/20127531/37193902-b7fea3ba-23a6-11e8-8cff-6d044d519b47.png)

code show as below:
![image](https://user-images.githubusercontent.com/20127531/37193986-0637f496-23a7-11e8-9e4b-167783906013.png)

**Comment by Eternal-Infinity** [comment]
If it is your real credentials you use, you should change them ASAP!

**Comment by wl1508702360** [comment]
@Eternal-Infinity The password is wrong

**Comment by wl1508702360** [comment]
Seen part of the source code, the phpMailer.php function smtpSend () under the code (as shown below) commented out, you can send, I would like to ask the following code commented out what can be the problem?
![image](https://user-images.githubusercontent.com/20127531/37195784-30bf5dfa-23af-11e8-94b6-a9f44ded74e8.png)

**Comment by Synchro** [comment]
PHP is case-sensitive for variable and property names, so:

    $mail->Charset = "utf-8";

Should be:

    $mail->CharSet = "utf-8";

That's likely to be the cause of your encoding issues.
