### ISSUE TITLE
email send but not displayed in the send list

### ISSUE THREAD

**Issue by lammh** [PHPMailer/PHPMailer#1374]
Hello,

email send and I received
but not displayed in the send list

**Comment by Synchro** [comment]
PHPMailer is only responsible for sending via SMTP. Placing the message in your *sent* mailbox is a separate operation usually done via IMAP - as such, this is outside PHPMailer's scope, but there is a basic example of doing this in [the gmail example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail.phps).
