### ISSUE TITLE
SMTP connect() failed

### ISSUE THREAD

**Issue by RubenMesia** [PHPMailer/PHPMailer#1376]
Hi!

Recently, I have troubles using PHPMailer library in a hosting named Bluehost. The oddest thing is that my test script was working weeks ago without problems. To discard functionality, I put this code and phpmailer library in 3 different hosts.

1. http://www.trip-peru.com/sistema/mailstore/mail-test.php **(ISSUE)**
2. http://www.viaje-peru.es/pepo/mail-test.php (WORKING)
3. http://www.more-grass.com/mailstore/mail-test.php (WORKING)

Every code has SMTPDebug option activated, with level 4 to check it out.

1. I tried using PHPMailer versions 5.2.8 and 5.2.26, none of them throws messages like "SMTP connect() failed". And there's something curious: it looks like the **port number** is changing everytime I'm trying to connect. Is that correct?
2. Working with version 5.2.8.
3. Working with version 5.2.26.

In all cases, I put this at the beginning of my code: **date_default_timezone_set("Etc/UTC");**

I'm still looking for a solution at this matter. Thanks in advance.

**Comment by Synchro** [comment]
You don't actually say what the problem is. What debug output do you get?

If you're sending via gmail it's quite likely you're running into problems with outdated CA certificates, which is OS-specific, and thus can vary across hosts.

You shouldn't be using any version of 5.2 anyway, especially not old ones; upgrade to 6.

**Comment by RubenMesia** [comment]
Hi!
Here's the output:

2018-03-13 17:21:10 Connection: opening to ssl://box810.bluehost.com:465, timeout=300, options=array ()
2018-03-13 17:21:10 Connection: opened
2018-03-13 17:21:10 SMTP -> get_lines(): $data is ""
2018-03-13 17:21:10 SMTP -> get_lines(): $str is "550-Message rejected because [66.147.244.110]:43985 is blacklisted see Blocked"
2018-03-13 17:21:10 SMTP -> get_lines(): $data is "550-Message rejected because [66.147.244.110]:43985 is blacklisted see Blocked"
2018-03-13 17:21:10 SMTP -> get_lines(): $str is "550 - Too many failed logins"
2018-03-13 17:21:10 SERVER -> CLIENT: 550-Message rejected because [66.147.244.110]:43985 is blacklisted see Blocked550 - Too many failed logins
2018-03-13 17:21:10 CLIENT -> SERVER: EHLO www.trip-peru.com
2018-03-13 17:21:10 SMTP -> get_lines(): $data is ""
2018-03-13 17:21:10 SMTP -> get_lines(): $str is ""
2018-03-13 17:21:10 SERVER -> CLIENT:
2018-03-13 17:21:10 SMTP ERROR: EHLO command failed:
2018-03-13 17:21:10 SMTP NOTICE: EOF caught while checking if connected
2018-03-13 17:21:10 Connection: closed
SMTP Error: Could not authenticate.
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

That's why I indicate that every sample has SMTPDebug option activated.

**Comment by Synchro** [comment]
When it says "Message rejected because [66.147.244.110]:43985 is blacklisted", that means they don't like your IP and are blocking you, and it also says "Too many failed logins", which suggests your id/password is wrong. You need to ask your ISP to unblock it.

**Comment by RubenMesia** [comment]
I asked my ISP, and there's no block report. I don't know what is the issue source: hosting or ISP. And why it didn't happen with the other samples?

**Comment by Synchro** [comment]
That block message is coming from the mail server you're connecting to, nowhere else. Bluehost is blocking that IP. The others are on different IPs that are not blocked.

**Comment by vinothkumarmohan** [comment]
Hi there,

    I have tried Office 365 with PHP Mailer to send emails, and I could not able to connect to the SMTP server. 
It is throwing the following errors.

SMTP -> ERROR: Failed to connect to server: Connection timed out (110)

**Comment by torressam333** [comment]
If you are using a gmail account you may need to adjust your security settings in order for the email to be passed and sent. Although, I don’t recommend making this a permanent change as it leaves your email vulnerable. You can use a pseudo email address that you have opened for testing purposes.

**Comment by vinothkumarmohan** [comment]
Hi,

I have checked with my host provider and they confirmed that none of the ports are blocking outbound SMTP. I have pasted my code below for your reference.

```
<?php
require_once '../class.phpmailer.php';
ini_set("display_errors", "1");
$mail = new PHPMailer(true);
$mail->isSMTP();
$mail->Host = 'smtp.office365.com';
$mail->AuthType = 'LOGIN';
$mail->Port = 465;
$mail->SMTPSecure = 'tls';
$mail->SMTPAuth = true;
$mail->Username = 'su***t@**o**to*.com';
$mail->Password = '************';
$mail->SetFrom('su***t@**o**to*.com', 'FromEmail');
$mail->addReplyTo('su***t@**o**to*.com', 'ReplyTo');
$mail->AddAddress("st*****.m@sa****ug*.com");
$mail->SMTPDebug = 4;
$mail->Debugoutput = "html";
$mail->IsHTML(true);
$mail->Subject = 'This is a test mail from Office 365';
$mail->Body = '<h1>PHP Script test:</h1> <br/> <p>No modification in core file.</p>';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
if (!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message has been sent';
}
?>
```

Also on side note, I am running this script with IP like below URL and not from the domain.

http://MY_IP_ADDRESS/PHPMailer/examples/office365.php

**Comment by Synchro** [comment]
It doesn’t matter how you run it. Don’t believe their support - **test it** using the openssl commands described in the guide.
