### ISSUE TITLE
could not instantiate mail function

### ISSUE THREAD

**Issue by Rara74** [PHPMailer/PHPMailer#1377]
This php mailer works great but it only works when I am using my own wifi hotspot. When I using company wifi it said that it could not instantiate mail function. Anyone can know what is the solution? Tq in advance. This is my code:

 $mail = new PHPMailer( );                              // Passing `true` enables exceptions

		//Server settings
		$mail->SMTPDebug = 2;                                 // Enable verbose debug output
		//$mail->isSMTP();                                      // Set mailer to use SMTP
		$mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
		$mail->SMTPAuth = true;                               // Enable SMTP authentication
		$mail->Username = 'systemeapps2017@gmail.com';                 // SMTP username
		$mail->Password = 'ain2017';                           // SMTP password
		$mail->SMTPSecure = 'ssl';                            // Enable TLS encryption, `ssl` also accepted
		$mail->Port = 465;                                    // TCP port to connect to

		//Recipients
		$mail->setFrom('systemeapps2017@gmail.com', 'Portal Internship');
		$mail->addAddress('masturamdanuar@gmail.com');     // Add a recipient
    

   

		//Content
		$mail->Subject = 'New Registration for Internship';
		$mail->Body    = "Name: ".$stud_name. "ID: ".$stud_id_num;
							
						 
    
		//send an email
		if ($mail->send())
			echo 'Message has been sent';
		else
			echo 'Message could not be sent.';

**Comment by Synchro** [comment]
Because you have commented out `isSMTP`, it's using the `mail()` function to send. If your local mail server is not configured correctly, PHP (and thus PHPMailer) cannot send, hence the error. This is covered in the troubleshooting guide and the PHP docs. I hope that's not your real password...

**Comment by SeyramWood** [comment]
How can I integrate this in my project

**Comment by Synchro** [comment]
Read the docs, use the examples.

**Comment by Rara74** [comment]
but when I open the commented out isSMTP I got  this error

![image](https://user-images.githubusercontent.com/37390811/37587263-cf2e3cda-2b99-11e8-94f4-0b08762a9e62.png)

**Comment by Synchro** [comment]
Well, you have a clear choice: either use to a server that doesn't reject your connections (or change to an ISP that doesn't block outbound SMTP, as many do), or configure your local mail server so that calls to `mail()` work. Either way PHPMailer will be able to work, but this problem is not *caused* by PHPMailer.
