### ISSUE TITLE
Mailer Error: SMTP connect() failed.

### ISSUE THREAD

**Issue by nitzii** [PHPMailer/PHPMailer#1379]
Need help with this, i'm very new to this email thing, need corrections

<!DOCTYPE HTML>
<html>
<head>
<meta charset="UTF-8">
<link rel="icon" href="img/spc_logo.png" type="image/x-icon" />
    <title>Southern Philippines College</title>
</head>
<body>
<?php
	if (!array_key_exists('Submitted',$_POST))
	{
?>
		Enter your email in the form below to have your password sent to you.
		<form method="post" action="reg.php">
		<input type="hidden" name="Submitted" value="true"><br>
		Email: <input type="text" name="To" size="25" required><br>
		<input type="submit" value="Send Password">
		</form>
<?php
	}
	else
	{
		$to = $_POST['To'];
		$db = new mysqli("localhost","southphi","neicha0014","southphi_dbalumni");
		if (mysqli_connect_errno())
		{
		  echo 'Cannot connect to database: ' . mysqli_connect_error();
		}
		else
		{
		 	$query = "SELECT password FROM tbl_users WHERE username = '$to'";
		  	$result = $db->query($query);
		  	$row=$result->fetch_assoc();
			$password = $row['Password'];
			
			require '/home/southphi/public_html/phpmailer/PHPMailerAutoload.php';
			
			$message = "Your password is <u>$password</u>.";

			$mail = new PHPMailer();
		
			$mail->isSMTP();
			$mail->SMTPAuth   = true;
			$mail->Host = 'tls://smtp.gmail.com:587';           
			$mail->Username   = "iamneitzche@gmail.com"; 
			$mail->Password   = "neicha0014";         
			$mail->SetFrom('iamneitzche@gmail.com', 'southphilcollegealumni');
			$mail->Subject    = "Information Updates";
		
		
		  	$mail->From = 'iamneitzche@gmail.com';
			$mail->FromName = 'Northwind Admin';
			$mail->AddAddress($to);
			$mail->AddBCC('iamneitzche@gmail.com'); 
			$mail->AddReplyTo('iamneitzche@gmail.com');
		
			$mail->IsHTML(true);
		
			$mail->Subject  = 'Password Reminder';
			$mail->Body = $message;
		
			if($mail->Send())
			{
				echo "Your password has been sent.";
			}
			else
			{
			 echo "We could not send your password.<br>";
			 echo "Mailer Error: " . $mail->ErrorInfo;
			 }
		}
	}
?>
</body>
</html>

**Comment by Synchro** [comment]
You’ve based your code on an obsolete example, and you’re using an old version of PHPMailer, so update both.

The troubleshooting guide shows you how to deal with connection problems- it’s usually ISPs blocking outbound SMTP.

You probably need to change your password, since you posted it here.

If you’re sending people their passwords in plain text, you’re doing passwords wrong. Look into functions like `password_hash` and read articles on paragonie.com.
