### ISSUE TITLE
PHPmailer bulk mailing issue - receiving multiple emails for users problem

### ISSUE THREAD

**Issue by graphicmist** [PHPMailer/PHPMailer#138]
I am using phpmailer 5.1 for my system. Havent upgraded it for a long time. There is a issue which is coming, may be you guys have any idea on this.

I am using php mailer to send bulk emails (12k in one go) using external SMTP relay(jangomail). The problem is that when i am using bulk mailing it is sending multiple mails to quite a fraction of users and normally for less numbers it is working fine. I am unable to figure out the problem and replicate the problem at my end to debug it. May be you guys have ideas. 
Basically my cron scheduler picks up emails from database and send them using the below code.

Hereby sharing my code:

Function for sending email:

``` php
function send_smtp_email_new($username, $password, $host, $port, $from_name, $from_email, $to, $subject, $email_body, $attachment, $reply_to = false)
{

include_once("class.phpmailer.php");

$mail = new PHPMailer();

$mail->IsSMTP();            
$mail->Host = $host;  
$mail->Port = $port;  
$mail->SMTPAuth = true;    
$mail->SMTPSecure = "ssl";
$mail->Username = $username;  
$mail->Password = $password; 
$mail->CharSet = 'UTF-8';
$mail->From = $from_email;
$mail->FromName = $from_name;
if (is_array($to)){
$mail->AddAddress($to[0]);    
for($i=1; $i < count($to);$i++)
{
$mail->AddBCC($to[$i]);
}
} else {
$mail->AddAddress($to);
}
if ($reply_to <> ""){
$mail->AddReplyTo($reply_to, "GiveCentral.org");
}
if ($attachment <> ""){
if (is_array($attachment)){
for($i=0; $i < count($attachment);$i++)
        {
$mail->AddAttachment($attachment[$i]);      

        }
} else {
$mail->AddAttachment($attachment); 
}
}
$mail->IsHTML(true); 

$mail->Subject = stripslashes($subject);
$mail->Body    = stripslashes($email_body);
$mail->AltBody = strip_tags($email_body);

if(!$mail->Send())
{
  return $mail->ErrorInfo;
} else {
    return "1";
}
}
```

and code for cron scheduler

``` php
<?php
set_time_limit(0);
date_default_timezone_set('America/Chicago');

$relayer=get_relay();

// Disable E_ALL warnings...
ini_set("error_reporting", E_ALL & ~E_NOTICE & ~E_DEPRECATED);

// select emails to be sent
global $database_nfconx;
global $nfconx;
mysql_select_db($database_nfconx, $nfconx);
$Yesterday = date( "Y-m-d", strtotime ("-2 day" ) ) ;
mysql_query("SET NAMES 'utf8'");

$query_rsnf = "SELECT * FROM email_log_bulk WHERE delivery_date >='".$Yesterday."' AND delivery_date<='".date('Y-m-d')."' AND delivery_status = '0' and total_attempts='0'
and email_body<>'' and email_body is not null
and to_email not in (select distinct email from unsubscribe_users where email is not null and email <>'') and to_email<>'' and to_email is not null
 LIMIT 0,5";
//echo $query_rsnf;
$rsnf = mysql_query($query_rsnf, $nfconx) or die(mysql_error());
$row_rsnf = mysql_fetch_assoc($rsnf);
$totalRows_rsnf = mysql_num_rows($rsnf);    

if ($totalRows_rsnf > 0) {

if($row_rsnf['message_id']<>'')
{
// Get attachments
$query_rsnf_attachment = "SELECT * FROM message_attachments WHERE message_id = '" . $row_rsnf['message_id'] . "'";
$rsnf_attachment = mysql_query($query_rsnf_attachment, $nfconx) or die(mysql_error());
$row_rsnf_attachment = mysql_fetch_assoc($rsnf_attachment);
$totalRows_rsnf_attachment = mysql_num_rows($rsnf_attachment);
$attachment_array = array();
if ($totalRows_rsnf_attachment > 0){
do {
$file_name = $NF_config['email_attachments'] . '/' .$row_rsnf['message_id'] . '/' . $row_rsnf_attachment['filename_attached'];
array_push($attachment_array, $file_name);
} while ($row_rsnf_attachment = mysql_fetch_assoc($rsnf_attachment));
}
}else{
$attachment_array="";
}

do {
    $relayer=get_relay();
    $new_total_attempts = $row_rsnf['total_attempts'] + 1;

    $edit_value = array(
"total_attempts"=>$new_total_attempts,
);
$edit_action =update_data("email_log_bulk",array_to_string_update($edit_value),"email_log_id='" . $row_rsnf['email_log_id'] . "'");
$edit_r=mysql_query($edit_action);

$mail_response = send_smtp_email_new($relayer[1],$relayer[2], $relayer[0],$relayer[3], $row_rsnf['from_name'], $row_rsnf['from_email'], $row_rsnf['to_email'], $row_rsnf['email_subject'], $row_rsnf['email_body'], $attachment_array, $row_rsnf['reply_to']);

$edit_value = array(
"relayer_info"=>$relayer[1],
);
$edit_action =update_data("email_log_bulk",array_to_string_update($edit_value),"email_log_id='" . $row_rsnf['email_log_id'] . "'");
$edit_r=mysql_query($edit_action);
if ($mail_response == "1"){

$edit_value = array(
"delivery_status"=>"1",
"datetime_sent"=>date('Y-m-d H:i:s'),
);
$edit_action =update_data("email_log_bulk",array_to_string_update($edit_value),"email_log_id='" . $row_rsnf['email_log_id'] . "'");
$edit_r=mysql_query($edit_action);

echo "Email - " . $row_rsnf['email_log_id'] . " - Sent<br>";
} else {
// set delivery_status = 0 and increment in total_attempts and set datetime_sent and mail_response

$edit_value = array(
"delivery_status"=>"0",
"datetime_sent"=>date('Y-m-d H:i:s'),
"mail_response"=>$mail_response,
);
$edit_action =update_data("email_log_bulk",array_to_string_update($edit_value),"email_log_id='" . $row_rsnf['email_log_id'] . "'");
$edit_r=mysql_query($edit_action);

echo "Email - " . $row_rsnf['email_log_id'] . " - Not Sent<br>";
}

} while ($row_rsnf = mysql_fetch_assoc($rsnf)); 


} else {
    echo "Nothing to do";
}
?>
<meta http-equiv="refresh" content="60">
```

**Comment by narangrishab** [comment]
Why don't you guys write a bulk email function? Using while/foreach loop takes a lot of time if the addresses are more than 100. 

Give us an alternate method which is fast and effective. 

Thanks,

**Comment by narangrishab** [comment]
<?php

include_once "../includes/globalFunctions.php";
include_once '../mail/PHPMailerAutoload.php';

class Mail
{

	private $emailaddresses = array();
	private $firstName = array();
	private $lastName = array();
	private $replyToMail;
	private $eid;
	private $countRows;
	private $replyToEmail;
	private $message;
	private $uid;

	function getDetails($mysqli)
	{
		//Using the eid and type of mail, pull in the details of the people
		$this->eid = filter_input(INPUT_POST, 'eid',FILTER_SANITIZE_NUMBER_INT);
		$this->replyToEmail = filter_input(INPUT_POST, 'replyToEmail',FILTER_SANITIZE_STRING);
		$this->message = filter_input(INPUT_POST,'message',FILTER_SANITIZE_SPECIAL_CHARS);
		$this->subject = filter_input(INPUT_POST,'subject', FILTER_SANITIZE_STRING);
		$this->uid = filter_input(INPUT_POST, 'uid',FILTER_SANITIZE_NUMBER_INT);

		//Pull the addresses and name of the people who are going to the event - From globalFunction class
		//$this->eid = 1;
		

		$getDetails = globalFunction::getDetailsOfAttendees($mysqli,$this->eid);

		if($getDetails == NULL)
			exit();
		else
		{
			$getDetails = json_decode($getDetails,true);
			$this->countRows = $getDetails['countRows'];
			$this->firstName = $getDetails['firstName'];
			$this->lastName = $getDetails['lastName'];
			$this->emailaddresses = $getDetails['email'];
		}

	} //end of getDetails

	function mailFunction($mysqli)
	{

			//SMTP needs accurate times, and the PHP time zone MUST be set
			//This should be done in your php.ini, but this is how to do it if you don't have access to that
			date_default_timezone_set('Etc/UTC');
			//Create a new PHPMailer instance

		
			$mail = new PHPMailer;

			//Tell PHPMailer to use SMTP
			$mail->isSMTP();

			//Enable SMTP debugging
			// 0 = off (for production use)
			// 1 = client messages
			// 2 = client and server messages
			$mail->SMTPDebug = 0;

			//Ask for HTML-friendly debug output
			//$mail->Debugoutput = 'html';

			//Set the hostname of the mail server
			$mail->Host = 'smtp.gmail.com';

			//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
			$mail->Port = 587;

			//Set the encryption system to use - ssl (deprecated) or tls
			$mail->SMTPSecure = 'tls';

			//Whether to use SMTP authentication
			$mail->SMTPAuth = true;

			
			//Username to use for SMTP authentication - use full email address for gmail
			$mail->Username = "test.eventsrack@gmail.com";


			//Password to use for SMTP authentication
			$mail->Password = "eventsRack123";
		
		
			for($i = 0 ; $i < $this->countRows ;  $i++ )
			{
			//Set who the message is to be sent from
			$mail->setFrom($this->replyToEmail, 'eventsRack');

			//Set an alternative reply-to address
			$mail->addReplyTo($this->replyToEmail, 'eventsRack Team');

			//To make sure user can see only their email addresses
			$mail->ClearAllRecipients();

			//Set who the message is to be sent to
			$mail->addAddress($this->emailaddresses[$i],$this->firstName[$i]);
			

			//get the uid of the emailaddress from globalFunctions 
			$uidSent  = array();
			$uidSent['$this->emailaddresses[$i]'] = globalFunction::getUIDByEmail($mysqli,$this->emailaddresses[$i]);

			$mail->IsHTML(true);
			//Set the subject line
			$mail->Subject = $this->subject;

			//Read an HTML message body from an external file, convert referenced images to embedded,
			//convert HTML into a basic plain-text alternative body
			//$mail->msgHTML(file_get_contents('contents.html'), dirname(__FILE__));
			$mail->Body = $this->message;
			//Replace the plain text body with one created manually
			$mail->AltBody = $this->message;


			$sent = array();

			//Attach an image file
			//$mail->addAttachment('images/phpmailer_mini.png');

			//send the message, check for errors
			if (!$mail->send()) {
			    echo "Mailer Error: " . $mail->ErrorInfo;
			     $sent[$this->emailaddresses[$i]]  = 0;
			} else {
			    echo "Message sent!";
			    $sent[$this->emailaddresses[$i]]  = 1;
			} 

		}//end of for

		$sql = $mysqli->prepare("INSERT INTO contactGuestEmails(eventId,userIdOfSender,toSenderId,message,isSent) VALUES (?,?,?,?,?)");
		$sql->bind_param("iiisi",$this->eid,$this->uid,);
			
		} //end of mail()

}//end of class

$mailObj = new mail;
$mailObj -> getDetails($mysqli);
$mailObj->mailFunction($mysqli);



I'm trying to send it as an HTML mail but the message doesn't convert into equivalent HTML. Please help!

**Comment by Synchro** [comment]
Because we know what we're doing and can read the docs.

**Comment by henrisman** [comment]
hi, please can someone teach me how to do send bulk emails to inbox, using php mailer. I will prefer a video tutorial. Thanks
