### ISSUE TITLE
donwload fail

### ISSUE THREAD

**Issue by abelnexus** [PHPMailer/PHPMailer#1382]
no descarga todos los archivos ni el composer y no se puede instalar :/

**Comment by soywod** [comment]
1. Could you speak in English ?
2. Could you give some logs ? Informations about the commands you tried ? Your environment ?

**Comment by abelnexus** [comment]
when install composer in cmd is freeze

**Comment by abelnexus** [comment]
it works now lol 
it took too long

**Comment by abelnexus** [comment]
SMTP Error: Could not authenticate.
2018-03-20 23:43:48 CLIENT -> SERVER: QUIT
2018-03-20 23:43:48 SERVER -> CLIENT: 221 2.0.0 closing connection j192sm862033vke.9 - gsmtp
SMTP Error: Could not authenticate.
Message could not be sent. Mailer Error: SMTP Error: Could not authenticate.
