### ISSUE TITLE
autoload.php not found

### ISSUE THREAD

**Issue by bieganskiandrew4213** [PHPMailer/PHPMailer#1393]
This line is causing the php to break:

//require '../vendor/autoload.php';

I can't seem to find 'autoload.php' anywhere in the project.

**Comment by ooxi** [comment]
Please take a look at the [documentation](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#loading-classes) :-)

**Comment by Synchro** [comment]
Thanks @ooxi
