### ISSUE TITLE
Allow duplicate addresses

### ISSUE THREAD

**Issue by fi5er** [PHPMailer/PHPMailer#1395]
We have some use cases where we need to compose emails that contain the same recipient email address multiple times. There is currently no way to bypass this restriction in PHPMailer, so I'm using a derived class. Unfortunately, I have to completely override both `addOrEnqueueAnAddress()` and `addAnAddress()` (about 85 lines combined), when the actual changes are only in 3 lines. This will make upgrading a little tricky.

Would you be interested in adopting such a feature in the main release? If so, I'll be happy to create a PR.

The proposed changes are a new public property named `$AllowDuplicateAddresses` which defaults to `false`, and a check for this property in the `array_key_exists()` lines in the methods mentioned above. The overall behavior would be unchanged unless a user explicitly sets `$AllowDuplicateAddresses`.

----

One use case for this is that we use PHPMailer to compose messages not for sending, but to store them in a user's "Drafts" IMAP folder. If one of the recipient addresses is unavailable in our database, a replacement address is used (for example "ADDRESS_MISSING@company.example.com"). The user needs to fix this before the email can be sent (the mail server will reject this address). Now if two or more addresses are missing in the same message, we run into the unique address problem.

Another use case is that our users are telling me that they want to make sure that everybody involved in a case is added as a recipient. This often includes several persons, and their parent company as a CC. In the case of small companies, the owner (person) often uses the same address as the company, but we currently cannot add them both.

A last (and probably minor) use case is that we simulate sending out emails during development, by replacing the actual addresses with a developer's address, which also only works if the address can be used more than once.

**Comment by fi5er** [comment]
After taking a closer look, it seems that the implementation has changed quite a bit. In earlier versions of PHPMailer, the `$all_recipients` array was used for the dupe check, but now `$RecipientsQueue` is used differently. I don't think what I'm looking for is feasible without more substantial changes.

I'm closing this now; please ignore.

**Comment by Synchro** [comment]
There’s no point in ever having duplicates in an actual sent message, but I’d say you could tweak your approach slightly to achieve what you need. I’d look at using address extensions such as `user+randomstring@example.com` for dev addresses, and use a similar pattern for those unknown addresses, rather than a single fixed address so they can be easily identified without being duplicates. HTH.
