### ISSUE TITLE
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

### ISSUE THREAD

**Issue by hardikdiff** [PHPMailer/PHPMailer#1396]
Hiii
i got SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting error
this is my code

require 'PHPMailer/PHPMailerAutoload.php';
require 'PHPMailer/class.phpmailer.php';
function Sendmail($to, $subject, $message, $filename, $path){

/********* New Method ********/
$email = new PHPMailer;
$email->isSMTP();
$email->Host = 'mydomain.com';
$email->SMTPAuth = true;
$email->Username = "info@mydomain.com";
$email->Password = "**********";
$email->SMTPSecure = 'tls';
$email->Port = 587;
$email->Subject = $subject;
$email->setFrom('info@mydomain.com', $subject);
$email->addReplyTo('admin@mydomain.com', $subject);
$email->isHTML(true);

// Add a recipient
$email->AddAddress($to);
$email->Body = $message;
if($filename) $email->AddAttachment('/var/www/html'.$filename); // attachment
if(!$email->send()) {
print_r($email->ErrorInfo);
//return $email->ErrorInfo;
} else {
print_r('Mail Sent success');
//return 'Mail Sent';
}

}

can you help me please?

**Comment by Synchro** [comment]
You’ve ignored the link to the docs and everything in the issue template, used an old version, not used a provided example, failed to search before posting a question that has been asked and answered many times before, all of which would have helped you.

**Comment by hardikdiff** [comment]
Hello sir,

but when i use hostname:smtp.gmail.com and i use gmail id & password at that time this script is executing and when i use for my website domain name in Host at that time i got this type of error

if i use to new version than can problem solve?

please give me some solution as soon as possible

**Comment by Synchro** [comment]
Use the guide to diagnose your problem. I can’t tell from your description, but everything I would try is in the guide.

**Comment by hardikdiff** [comment]
can you tell that how can i solve this issue in short words please.

thanks

**Comment by Synchro** [comment]
The error means that your script cannot connect to your SMTP server. There are many reasons why this might happen. I suggest starting again - get the latest version of PHPMailer, use one of the examples provided, modify it to match your own server. Set `$mail->SMTPDebug = 3;` so that it will show what's happening when you try to connect. All of this is in both the issue template (which you deleted) and the troubleshooting guide which your error message links to, so there's not much point in me typing the same thing here.

**Comment by justcoding903** [comment]
same error here

**Comment by justcoding903** [comment]
:(

**Comment by Synchro** [comment]
It's likely you have set `Port = 465` and `SMTPSecure = 'tls'`; that combination won't work, as the docs and examples all say.
