### ISSUE TITLE
File phpmailer.lang-hi.php has wrong characters enconding

### ISSUE THREAD

**Issue by ajlucena78** [PHPMailer/PHPMailer#1400]
File phpmailer.lang-hi.php has wrong characters enconding

**Comment by Synchro** [comment]
How so? It looks like correct UTF-8 to me, my editors display it no problem, though to be fair I don't read Hindi.

**Comment by ajlucena78** [comment]
![captura de pantalla de 2018-04-02 18-21-39](https://user-images.githubusercontent.com/20539929/38204509-7d05d980-36a3-11e8-88bd-585aaffcb776.png)

I see this, maybe my Firefox version does not support hindi characters. Others are fine.

**Comment by Synchro** [comment]
I suspect it's your OS rather than your browser; it's quite likely you don't have Hindi fonts.

**Comment by Synchro** [comment]
For reference, here's what I see: ![image](https://user-images.githubusercontent.com/81561/38204642-00ab720e-36a4-11e8-9ab6-dcf658a734e4.png)
