### ISSUE TITLE
Spam 

### ISSUE THREAD

**Issue by anshul0430** [PHPMailer/PHPMailer#1401]
My mails are going to spam after sending one or more time

**Comment by r0073rr0r** [comment]
Did you setup SPF, DKIM and DMARC ?
Can you give some debug logs?

**Comment by anshul0430** [comment]
i dont know what you do mean sir? how to stepup that

**Comment by anshul0430** [comment]
How can i setup SPF , dkim and dmarc ?

**Comment by Synchro** [comment]
That's far too broad a question for here, but there are plenty of resources to help you do that, so just [try a bit harder](http://lmgtfy.com/?q=How+can+i+setup+SPF+%2C+dkim+and+dmarc+%3F).

**Comment by anshul0430** [comment]
It is working but after sometime my emails are  going to spam in gmail.
