### ISSUE TITLE
SMTP connect()failed

### ISSUE THREAD

**Issue by AlkeshJaiswal** [PHPMailer/PHPMailer#1404]
I have this issue when trying to send mail:-
MailerError: SMTPconnect()failed.https: //github.com/PHPMailer/PHPMailer/wiki/Troubleshooting)

My code:-
$mail = new PHPMailer;    

				$mail->isSMTP();       
                                $mail->SMTPDebug = 2;                     
				$mail->Host = 'smtp.gmail.com';             
				$mail->SMTPAuth = true;                    
				$mail->Username = '******@gmail.com';          
				$mail->Password = '******';
				$mail->SMTPSecure = 'tls';      
				$mail->Port = 587;  
                
                $mail->From = '******@gmail.com';
                $mail->FromName = '****';                        
                
                $mail->addAddress($emailId,'******');  
                $mail->isHTML(true);  

                $bodyContent = '<p>This is your new password.<b>'.$userId.'</b></p>';

                $mail->Subject = 'Password Reset';
                $mail->Body    = $bodyContent;
                $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

                if(!$mail->send()) {
                    $message['type'] = 'error';
                    $message['msg'] =  "Mailer Error: " . $mail->ErrorInfo;
                    print_r($message);  die;
                } else {
                print_r($mail);die;
                    // return true;
				}

Debug error says:-
2018-04-0407: 20: 29SERVER-&gt;CLIENT: 220smtp.gmail.comESMTPf22sm9201915pff.146-gsmtp
2018-04-0407: 20: 29CLIENT-&gt;SERVER: EHLOlocalhost
2018-04-0407: 20: 29SERVER-&gt;CLIENT: 250-smtp.gmail.comatyourservice,
[
2405: 201: 3005: ffd3: c554: 70be: 492f: b765
]
250-SIZE35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250SMTPUTF8
2018-04-0407: 20: 29CLIENT-&gt;SERVER: STARTTLS
2018-04-0407: 20: 30SERVER-&gt;CLIENT: 2202.0.0ReadytostartTLS
SMTPError: CouldnotconnecttoSMTPhost.
2018-04-0407: 20: 30CLIENT-&gt;SERVER: QUIT 2018-04-0407: 20: 30SERVER-&gt;CLIENT:
2018-04-0407: 20: 30SMTPERROR: QUITcommandfailed: SMTPconnect()failed.https: //github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
You have a TLS problem - it's dropping your connection as soon as you send STARTTLS. This exact problem is described in detail in the troubleshooting guide that the error message links to.
