### ISSUE TITLE
Hide 'https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting' on exceptions

### ISSUE THREAD

**Issue by felipefreitasweb** [PHPMailer/PHPMailer#1407]
Hi,
I'm developing an interface where the client can enter SMTP data and send a test. Any error should be displayed to the client so that it resolves the problem.
But when an SMTP error occurs I get the message:

 **SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting** 

I would not like to show '**https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting**' to the client.
How can I solve this?

My code:

```
$mail = new PHPMailer;
$mail->isSMTP();
$mail->SMTPDebug = 0;
$mail->Host = $host;
$mail->Port = $port;
 $mail->SMTPAuth = true;
$mail->AuthType = $auth;
$mail->Username = $username;
$mail->Password = $password;
$mail->SMTPSecure = $security;
       
//Recipients
$mail->setFrom($email, 'Test');
$mail->addAddress($email_test);     // Add a recipient

 //Content
$mail->Subject = _i("Email Test");
$mail->Body    = _i('This is an e-mail test using custom SMTP');

if($mail->send()) {
           echo "Message has been sent!";
}else {
           echo $mail->ErrorInfo;
}
```
I would not like to display to the client links to phpmailer documentation.

Sorry for my English.

**Comment by r0073rr0r** [comment]
Can you please post and Debug logs for us to investigate where is problem?

**Comment by r0073rr0r** [comment]
But for debug errors you can print them $mail->ErrorInfo or save all Debug logs (you need to enable debug first) and parse only what you need from that.

**Comment by Synchro** [comment]
The only reason the PHPMailer error is being displayed is that you're displaying it with `echo $mail->ErrorInfo;` - you don't have to do that - you can catch/trap the error and process it before displaying anything.

It's very likely that what your users enter will be incorrect or non-functional (i.e. for whatever reasons they are even looking at testing an SMTP connection), so you need to be very hot on your error checking and input validation. I'd recommend enabling exceptions (pass `true` to the constructor, see code examples) as they provide slightly finer-grained errors that you don't get through `ErrorInfo`.

If you really want to only *test* SMTP connections and not necessarily send anything, I'd recommend using the SMTP class directly as that gives you much finer control, though you'll need to write more code. Take a look at [the SMTP connect example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/smtp_check.phps) provided in the examples folder.

**Comment by felipefreitasweb** [comment]
look my screen:

![image](https://user-images.githubusercontent.com/9322269/38312103-41f625f2-37f7-11e8-96a5-00f353079ffb.png)

I would not like to show 'https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting' to the client. 
It would be nice if you just showed: **SMTP connect() failed. ~~https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting~~**

**Comment by felipefreitasweb** [comment]
@Synchro  Firstly I used the SMTP test class, plus I encountered a problem (I think), when I test with login authentication and I type a wrong username, the class returns true. Only the error is displayed if the password is wrong.

**Comment by Synchro** [comment]
The auth call is [here](https://github.com/PHPMailer/PHPMailer/blob/master/examples/smtp_check.phps#L49); SMTP AUTH commands usually involve more than one round-trip, and you can't tell whether it's the ID or password that's wrong from the SMTP response. You will see what's happening if you enable debug output that might help you understand how it works. Bear in mind that's only an example - you can build whatever variations you need on that. The SMTP class is very low-level, just implementing individual SMTP verbs - it's up to you to drive it appropriately.

If the only problem you have is literally the display of the URL in the message, strip it out with a `str_replace`. The way you have set this up at the moment is not going to be very reliable - for example you're not taking into account connection timeouts, which can be up to 10 minutes.

**Comment by felipefreitasweb** [comment]
Thank you, I'll handle the message. :)

**Comment by IdaMonis** [comment]
usefull for me
