### ISSUE TITLE
Add JMAP support (as an alternative to IMAP + SMTP, and later to CardDAV/CalDAV)

### ISSUE THREAD

**Issue by marclaporte** [PHPMailer/PHPMailer#1408]
"JMAP is intended to be a new standard for email clients to connect to  
mail stores. It therefore intends to primarily replace IMAP + SMTP  
submission. It is also designed to be more generic such that it can be  
extended with contacts, calendars in the future (replacing  
CardDAV/CalDAV). It does not replace MTA-to-MTA SMTP transmission."

http://jmap.io/

You may wonder "Who uses or supports it?"

Cyrus IMAP and Apache James are the notable ones here:  
http://jmap.io/software.html
https://cyrusimap.org/imap/developer/jmap.html

OpenPaaS is an open source Entreprise Social Platform which is led by  
LINAGORA (which has more than 150 employees)
https://linagora.com/
http://www.open-paas.org

OpenPaaS is using Apache James. And you can see JMAP used in the code:
https://github.com/linagora/openpaas-esn/search?utf8=%E2%9C%93&q=jmap&type=

In this video: https://www.youtube.com/watch?v=2QZIi3EO6rQ , Benoit  
Tellier explains why they decided to invest in James and JMAP (among  
other things). LINAGORA has 5 full time employees which are devoted to  
the project.

Why LINAGORA picked JMAP:
https://medium.com/linagora-engineering/you-cant-do-imap-in-the-browser-can-you-208838b0ba17
https://medium.com/linagora-engineering/openpaas-newsletter-march-2018-c0a3e469e83e
https://medium.com/linagora-engineering/openpaas-is-out-773704eadfbc

FastMail started this initiative:
"JMAP is FastMail's protocol with the warts removed. We leverage  
existing standards like HTTP, JSON, and native push channels on  
platforms which have them - making it easy for developers to work with."
https://blog.fastmail.com/2017/12/08/fastmail-at-ietf/
https://blog.fastmail.com/2016/12/22/cyrus-development-and-release-plans/
https://blog.fastmail.com/2016/12/12/why-we-contribute/
https://blog.fastmail.com/2016/12/09/jmap-test-suite/
https://blog.fastmail.com/2015/12/23/the-jmap-momentum-builds/
https://blog.fastmail.com/2015/08/11/an-open-source-jmap-proxy-javascript-library-and-webmail-demo/
https://blog.fastmail.com/2014/12/23/jmap-a-better-way-to-email/

Roundcube Next also plans to support JMAP.
https://github.com/search?q=org%3Aroundcube-next+jmap&type=Code

Thanks!

**Comment by Synchro** [comment]
That looks nice, but it does appear to be primarily focused on replacing IMAP, which PHPMailer doesn't really touch. PHPMailer isn't very flexible when it comes to replacing transports (it has some serious legacy issues in that department!) - I see you opened similar tickets for other mail projects (SwiftMailer, Zend_Mail etc), and they would probably find it easier to implement. What I suspect all have in common is a need for a generic/reference PHP JMAP client class so they don't all have to start from scratch - much as PHPMailer adopted an existing standalone SMTP implementation, or how SwiftMailer uses Guzzle for HTTP. Undertaking that is a huge piece of work, so I'd suspect it's not going to happen without some kind of backing to provide sufficient resources - perhaps fastmail might do it. It looks like roundcube (being a web app) is avoiding the problem by using a JS JMAP implementation, which isn't practical for PHP-only envs. So, nice idea, but I can't even begin to take that on personally. PRs welcome of course.
