### ISSUE TITLE
invalid address 

### ISSUE THREAD

**Issue by ardi0106** [PHPMailer/PHPMailer#1409]
i have a problem, i got a error like : Invalid address: (From): $sender
                                                         Invalid address: (From): root@localhost
                                                         Message could not been sent.

this is script on my file 

<form method="post" enctype="multipart/form-data">
<p>
send to:
	<input type="text" name="receiver" />
	</p>
	
	<p>
	subject:
	<input type="text" name="subject" />
	</p>
	
	<p>
	message:
	<textarea name="message"> </textarea>
	</p>
	
	<p>
	select file:
	<input type="file" name="file" />
	</p>
	
	<input type="submit" name="submit" value="Send Mail" />
	</form>
	
	<?php 
	if (isset($_POST['submit'])){
	include_once 'PHPMailer\src\PHPMailer.php';
		//Load Composer's autoloader
		require 'vendor/autoload.php';
		
		
		$mail= new PHPMailer\PHPMailer\PHPMailer();
try{
    //Server settings
	$sender = 'ardi.64463@gmail.com';
    $mail->SMTPDebug = 2;                                 // Enable verbose debug output
    $mail->isSMTP();                                      // Set mailer to use SMTP
    $mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                                 // Enable SMTP authentication
    $mail->Username = '$sender';                 // SMTP username
    $mail->Password = '***********';                           // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 587;                                    // TCP port to connect to

    //Recipients
    $mail->SetFrom('$sender', 'Mailer');
   
    $mail->addAddress($_POST['receiver']);               // Name is optional
	$file_name = $_FILES['file']['name'];
	move_uploaded_file($_FILES['file']['tmp_name'], $file_name);
    //Attachments
    $mail->addAttachment($file_name);         // Add attachments

    //Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = $_POST["subject"];
    $mail->Body    = $_POST["message"];
}catch (Exception $e) {
    echo 'Message could not be sent. Mailer Error: ', $mail->ErrorInfo;
}
	
    if(!$mail->send()){
    echo "Message could not been sent";
 	}
	else{
	echo "Message has been sent";
}
	}	
	
	
	?>

pleas i need your help everybody,
thankyou so much,
God blessing you of all

**Comment by Synchro** [comment]
Don't use user-submitted address as a from address. It's forgery and will result in your messages being bounced or marked as spam. Put their address in a reply-to (using `addReplyTo()`), and put your own address in From. If you don't provide a from address, it will generate an address, which in your case comes out as root@localhost, which is not a valid address for sending on the public internet, so it's failing.

**Comment by Synchro** [comment]
Look at the contact form example in the examples folder.

**Comment by ardi0106** [comment]
i have been change and the error still same eror plus one 

Invalid address: (From): $sender
Invalid address: (Reply-To): $sender
Invalid address: (From): root@localhost
Message could not been sent

 //Server settings
	$sender = 'ardi.64463@gmail.com';
    $mail->SMTPDebug = 2;                                 // Enable verbose debug output
    $mail->isSMTP();                                      // Set mailer to use SMTP
    $mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                                 // Enable SMTP authentication
    $mail->Username = '$sender';                 // SMTP username
    $mail->Password = 'ardi010695';                           // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 587;                                    // TCP port to connect to

    //Recipients
    $mail->SetFrom('$sender', 'Mailer');
    $mail->addReplyTo('$sender', 'Information');
    $mail->addAddress($_POST['receiver']);               // Name is optional
	$file_name = $_FILES['file']['name'];
	move_uploaded_file($_FILES['file']['tmp_name'], $file_name);
    //Attachments
    $mail->addAttachment($file_name);         // Add attachments

    //Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = $_POST["subject"];
    $mail->Body    = $_POST["message"];

**Comment by ardi0106** [comment]
Invalid address: (From): $sender
Invalid address: (Reply-To): $sender
Invalid address: (From): root@localhost
Message could not been sent

//Server settings
	$sender = 'ardi.64463@gmail.com';
    $mail->SMTPDebug = 2;                                 // Enable verbose debug output
    $mail->isSMTP();                                      // Set mailer to use SMTP
    $mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                                 // Enable SMTP authentication
    $mail->Username = '$sender';                 // SMTP username
    $mail->Password = '********';                           // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 587;                                    // TCP port to connect to

    //Recipients
    $mail->SetFrom('$sender', 'Mailer');
    $mail->addReplyTo('$sender', 'Information');
    $mail->addAddress($_POST['receiver']);               // Name is optional
	$file_name = $_FILES['file']['name'];
	move_uploaded_file($_FILES['file']['tmp_name'], $file_name);
    //Attachments
    $mail->addAttachment($file_name);         // Add attachments

    //Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = $_POST["subject"];
    $mail->Body    = $_POST["message"];
}catch (Exception $e) {
    echo 'Message could not be sent. Mailer Error: ', $mail->ErrorInfo;
}
	
    if(!$mail->send()){
    echo "Message could not been sent";
 	}
	else{
	echo "Message has been sent";
}
	}	
	
	
	?>

**Comment by Synchro** [comment]
You are single-quoting `$sender`. That will stop it working.

**Comment by ardi0106** [comment]
ohh it works, thank you somuch, god blessing you @Synchro
