### ISSUE TITLE
Unsubscribe PHP Script

### ISSUE THREAD

**Issue by naveenkumarseo** [PHPMailer/PHPMailer#1411]
Hi Guys,

I am new to coding level. I need help regarding the PHP unsubscribes mailing script. 

I have Unsubscribe PHP Script however it used server mail function to send out the email, i want to do this by SMTP function as my server does not send outgoing emails. THus i wanted to use this script with smtp mailer.

Your help will be highly appreciated! This is an on click PHP mail function which redirects to a HTML page of unsubscribed successfully. 

Here is the code, i am attaching the file as well.
[1cu.zip](https://github.com/PHPMailer/PHPMailer/files/1911878/1cu.zip)

<?php

$SenderAddress = "test@test.com";

define('OCU_RELEASE', '1.1');
define('OCU_ERR', !empty($_GET['err']));

if (OCU_ERR) {
	error_reporting(E_ALL);
	ini_set('display_errors', 'On');
}
else {
	error_reporting(0);
}

if (basename(__FILE__) == '1cu.php') {
	die('For your safety: you should really change the name of this file');
}

if (!empty($_GET['test'])) {
    die("OK: ".OCU_RELEASE);
}

if (empty($_GET['l']) && empty($_GET['e'])) {
    die("OK");
}

$l = isset($_GET['l']) ? $_GET['l'] : '';
$e = isset($_GET['e']) ? $_GET['e'] : '';
$m = isset($_GET['m']) ? $_GET['m'] : '';

$l = OCU_Unencode($l);
$e = OCU_Unencode($e);

$to      = $l;
$subject = "Unsubscribe";
$message = "Unsubscribe $e";
$from	 = $e;
if ($SenderAddress != 'test'.'@'.'test'.'.com') {
	$from = $SenderAddress;
}

switch ($mode) {
    case "1":
        $headers = "X-UserMail: $e";
        break;
    case "2":
        $headers = "From: $from";
        break;
    default:
        $headers = "From: $from" . "\r\n" . "X-UserMail: $e";
}

if (mail($to, $subject, $message, $headers)) {
	Header("Location: removal.htm");
} else {
	die("There was an error processing your request; please manually send an email to $l with Unsubscribe as its subject");
}

exit;

function OCU_Unencode($data) {
	return base64_decode(strtr($data, '-_', '+/'));
}
?>

**Comment by ooxi** [comment]
Hi @naveenkumarseo,

thanks for your interest in PHPMailer! However a question like this is much more suitable for a discussion forum like [stackoverflow](https://stackoverflow.com/) since PHPMailer is concerned with sending mails, not managing mailing lists :-)

Kind regards
-- ooxi
