### ISSUE TITLE
SMTP connect() failed

### ISSUE THREAD

**Issue by kmchen13** [PHPMailer/PHPMailer#1415]
Hi, 

# Problem description
That simple script can' connect to my smtp server and whatever SMTPDebug value I give 1 to 4 error message is the same and never shows any server response.
Smtp server and sender script are on the same machine

# Code to reproduce
            $mail = new PHPMailer();
            $mail->SMTPDebug = 4;
            $mail->isHtml(true);
            $mail->IsSMTP();
            $mail->SMTPAuth = true; 
            $mail->Host = 'smtp.mon-voyage-a-cuba.com';
            $mail->Port = 587;
//             $mail->SMTPSecure = 'tls';
            $mail->SMTPSecure = false;
            $mail->SMTPAutoTLS = false;
            $mail->Username = "email"; // SMTP username
            $mail->Password = "pass"; // SMTP password
            $mail->Sender = $mail->From = $mail->FromName = $sender;
            $mail->Subject    = $subject;
            $mail->Body       = $body;
            $mail->addAddress($email);
            $send = $mail->Send();

# Debug output
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

 On mail.log server side:
Apr 16 19:52:02 ns1 postfix/submission/smtpd[24161]: connect from 87.98.160.188
Apr 16 19:52:02 ns1 postfix/submission/smtpd[24161]: disconnect from 87.98.160.188

**Comment by Synchro** [comment]
If it's on the same machine as your script, can you not use `$mail->Host = 'localhost'`?

Regardless, there's something wrong with your mail server, not your script.

**Comment by kmchen13** [comment]
Using "localhost" gives the same results.

What's wrong with my mail server ?

**Comment by Synchro** [comment]
It's not responding as a mail server should. If you telnet to it, do you get a response?

**Comment by kmchen13** [comment]
Thanks for notifying. server was down. Telnet works now on port 587

**Comment by kmchen13** [comment]
I fixed some issues and implemented a letsencrypt certificate for the mail server. Now thunderbird accepts conections without warnings but php still can't connect
What do you think ?

**Comment by Synchro** [comment]
Can you telnet to it from localhost?
