### ISSUE TITLE
Microsoft provider is not working for get_oauth_token.php

### ISSUE THREAD

**Issue by laurelBE** [PHPMailer/PHPMailer#1417]
Hi all, I am using get_oauth_token.php for getting refresh token, it works fine for Google but not working for microsoft or office 365.
I have registered app on https://apps.dev.microsoft.com , added client id, secret id, redirect URL.
It shows error as following
We're unable to complete your request
Microsoft account is experiencing technical problems. Please try again later. 

Url shows "https://login.live.com/err.srf?lc=1033#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.&state=f02e8d3eace9d70cce54539629701bd9"

Please help me

**Comment by laurelBE** [comment]
Yes is it working now, but refresh token retrieved is too much is in length, is that fine? 
Refresh Token: MCbCn7Wl4y42s6o4JjFWPPWLpzxTXHoA8bhbjlRtGFjQOjJMYzJB!FV3aWa5bJm55IixVDZt4f8cFrey4eXWshnpfP0fhP67yQ7fxYZv77qfMMF47vcrme8YzQpUwM8Dv4mTqoPRuxfQ0IqYallj3afCJiwOt!kjMHjuzvJy87UYlAlBPH3H5CYipOL!Lnhis0Tb0BZQ4y76iWHX2RgLXLs7pEHVmrJbz9v*QbSFXFhIdn2m2hk7MyMBZWIPao2lIVojVqMTL!eyZN3N8szczlyG2yIl3!fAn02zMtiWiCHXRkpbQGDrzyJ4lgcBF8M1pmAVotlcMDnApzFm21u7qM4Wbbpe6EL4wuw96aBihXcId

**Comment by Synchro** [comment]
I have no idea. I don't know of any particular limit on token length, and that one doesn't look too unreasonable. BTW, having posted that here you should probably generate a new one - it's meant to be a secret, like a password.
