### ISSUE TITLE
gmail_xoauth code for Exchange account

### ISSUE THREAD

**Issue by ltbe** [PHPMailer/PHPMailer#1418]
I am using gmail_aoauth for sending email from gmail account, which works perfectly.But i want to use same code for exchange account so i have changed host as 'smtp.office365.com' and provider as

''$provider = new Microsoft( 
    [
        'clientId' => $clientId,
        'clientSecret' => $clientSecret,
    ]
);" 

but it shows error as 
--
```
PHP Fatal error:  Uncaught League\OAuth2\Client\Provider\Exception\IdentityProviderException: Bad Request in C:\inetpub\wwwroot\bephpforTteam\New\PHPMailer-master\PHPMailer-master\vendor\stevenmaguire\oauth2-microsoft\src\Provider\Microsoft.php:79
Stack trace:
#0 C:\inetpub\wwwroot\bephpforTteam\New\PHPMailer-master\PHPMailer-master\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(613): Stevenmaguire\OAuth2\Client\Provider\Microsoft->checkResponse(Object(GuzzleHttp\Psr7\Response), Array)
#1 C:\inetpub\wwwroot\bephpforTteam\New\PHPMailer-master\PHPMailer-master\vendor\league\oauth2-client\src\Provider\AbstractProvider.php(528): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request))
#2 C:\inetpub\wwwroot\bephpforTteam\New\PHPMailer-master\PHPMailer-master\vendor\phpmailer\phpmailer\src\OAuth.php(114): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\RefreshToken), Array)
#3 C:\inetpub\wwwroot\bephpforTteam\New\PHPMailer-maste in C:\inetpub\wwwroot\bephpforTteam\New\PHPMailer-master\PHPMailer-master\vendor\stevenmaguire\oauth2-microsoft\src\Provider\Microsoft.php on line 79
```
help me

**Comment by Synchro** [comment]
Unfortunately I really don't know. This is one of the problems with OAuth - every provider is completely different, using different params with different meanings and values. I can only suggest you refer to Microsoft's docs on this, and also look at the docs for the `stevenmaguire/oauth2-microsoft` package.

**Comment by ltbe** [comment]
Thanks for reply but is it possible to make the gmail xauth code compatible with exchange account

**Comment by Synchro** [comment]
It is compatible in that it is run and operates in exactly the same way for Microsoft (or any other OAuth provider) as it does for Google. What differs is what parameters that Microsoft expects, which is not something I know about.
