### ISSUE TITLE
HTTP Error 404.0 - Not Found The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

### ISSUE THREAD

**Issue by ltbe** [PHPMailer/PHPMailer#1420]
I followed the tutorial, when i run it from laravel server, after microsoft login it gives error as

`"HTTP Error 404.0 - Not Found The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."`

and url shows as

`"http://localhost/authorize?code=M15e2e5fb-ebca-8e81-9006-1ddc95a9a322&state=344d58e3fb4cb92d386ceae1fa5796e0"`

please help me

**Comment by Synchro** [comment]
Your callback URL has to be one that is externally accessible - one on localhost is not. It's also up to you to configure that callback URL.
