### ISSUE TITLE
SMTP Error Relove

### ISSUE THREAD

**Issue by sanjayacloud** [PHPMailer/PHPMailer#1422]
Any one can help me to resolve this error?

**Comment by lukasmedia** [comment]
You will have to give us more information. If "Relove" is a SMTP relay service you have to ask them.

**Comment by sanjayacloud** [comment]
Which information do you need?

**Comment by Synchro** [comment]
An error message that makes sense would be a start, plus your code, you know, all the things that the issue template asked you for but you ignored...

**Comment by sanjayacloud** [comment]
config file:
`<?php defined('BASEPATH') OR exit('No direct script access allowed.');

$config['useragent']        = 'PHPMailer';              // Mail engine switcher: 'CodeIgniter' or 'PHPMailer'
$config['protocol']         = 'smtp';                   // 'mail', 'sendmail', or 'smtp'
$config['mailpath']         = '/usr/sbin/sendmail';
$config['smtp_host']        = 'mail.sghapps.tk';
$config['smtp_user']        = 'admin@sghapps.tk';
$config['smtp_pass']        = 'MyPassword';
$config['smtp_port']        = 465;
$config['smtp_timeout']     = 30;                       // (in seconds)
$config['smtp_crypto']      = '';                       // '' or 'tls' or 'ssl'
$config['smtp_debug']       = 3;                        // PHPMailer's SMTP debug info level: 0 = off, 1 = commands, 2 = commands and data, 3 = as 2 plus connection status, 4 = low level data output.
$config['debug_output']     = '';                       // PHPMailer's SMTP debug output: 'html', 'echo', 'error_log' or user defined function with parameter $str and $level. NULL or '' means 'echo' on CLI, 'html' otherwise.
$config['smtp_auto_tls']    = false;                     // Whether to enable TLS encryption automatically if a server supports it, even if `smtp_crypto` is not set to 'tls'.
$config['smtp_conn_options'] = array();                 // SMTP connection options, an array passed to the function stream_context_create() when connecting via SMTP.
$config['wordwrap']         = true;
$config['wrapchars']        = 76;
$config['mailtype']         = 'html';                   // 'text' or 'html'
$config['charset']          = null;                     // 'UTF-8', 'ISO-8859-15', ...; NULL (preferable) means config_item('charset'), i.e. the character set of the site.
$config['validate']         = true;
$config['priority']         = 3;                        // 1, 2, 3, 4, 5; on PHPMailer useragent NULL is a possible option, it means that X-priority header is not set at all, see https://github.com/PHPMailer/PHPMailer/issues/449
$config['crlf']             = "\n";                     // "\r\n" or "\n" or "\r"
$config['newline']          = "\n";                     // "\r\n" or "\n" or "\r"
$config['bcc_batch_mode']   = false;
$config['bcc_batch_size']   = 200;
$config['encoding']         = '8bit';                   // The body encoding. For CodeIgniter: '8bit' or '7bit'. For PHPMailer: '8bit', '7bit', 'binary', 'base64', or 'quoted-printable'.

// DKIM Signing
// See https://yomotherboard.com/how-to-setup-email-server-dkim-keys/
// See http://stackoverflow.com/questions/24463425/send-mail-in-phpmailer-using-dkim-keys
// See https://github.com/PHPMailer/PHPMailer/blob/v5.2.14/test/phpmailerTest.php#L1708
$config['dkim_domain']      = '';                       // DKIM signing domain name, for exmple 'example.com'.
$config['dkim_private']     = '';                       // DKIM private key, set as a file path.
$config['dkim_private_string'] = '';                    // DKIM private key, set directly from a string.
$config['dkim_selector']    = '';                       // DKIM selector.
$config['dkim_passphrase']  = '';                       // DKIM passphrase, used if your key is encrypted.
$config['dkim_identity']    = '';                       // DKIM Identity, usually the email address used as the source of the email.
`

Model:
`<?php

Class User_model extends CI_Model
{

    public function __construct()
    {
        parent::__construct();

    }

    public function all_forms()
    {

    }

    function get_location()
    {
        $query = $this->db->query("SELECT * FROM location");
        $result = $query->result();
        return $result;

    }

    function insert_data()
    {
        $now = date_default_timezone_set('Asia/Colombo'); // Set Time-Zone
        $now = date('Y-m-d H:i'); //Fomat Date and time
        $data["place"] = $this->input->post("place");
        $data["request_date"] = $this->input->post("request_date");
        $data["location_id"] = $this->input->post("location_id");
        $data["user"] = $this->session->userdata("ID");
        $data["request_by"] = $this->input->post("requested_by");
        $data["date"]= $now;
        $data["urgency"] = $this->input->post("urgency");
        $this->db->insert('requisition', $data);
        $config = Array(
            'protocol' => 'smtp',
            'smtp_host' => 'tls://mail.sghapps.tk',
            'smtp_port' => '465',
            'smpt_user' => 'admin@sghapps.tk',
            'smtp_pass' => '**MyPassword**',
        );

        $this->load->library('email', $config);
        $this->email->set_newline("\r\n");

        $this->email->from('admin@sghapps.tk', 'Sanjaya prasanna');
        $this->email->to('sanjayaprasanna20@gmail.com');
        // $this->email->cc('another@another-example.com');
        //$this->email->bcc('them@their-example.com');

        //Setup Email Body..
        $place = "<p style='color: darkorange'>Place</p>";
        $date = "<p style='color: darkorange'>Date</p>";
        $request_by = "<p style='color: darkorange'>Requested By</p>";
        $urgency = "<p style='color: darkorange'>Urgency</p>";
        $heading = "<h2 style='text-align: center; color: darkorange'>New Requisition has been arrived !</h2></br>";
        $time = "<p style='color: darkorange'>Requested Time</p>";
        $this->email->subject('Email Test');
        $this->email->message($heading.$place.$data['place'] = $this->input->post('place').'<br>'.$date.$data["request_date"] = $this->input->post("request_date").'<br>'.$request_by.$data["request_by"] = $this->input->post("requested_by").'<br>'.$urgency.$data["urgency"] = $this->input->post("urgency").'<br>'.$time.$data["date"]= $now);

        if($this->email->send())
        {
           // echo "Your Email Has Been Sent.";
        }
        else
        {
            show_error($this->email->print_debugger());
            echo "Your Request not sent. Try again later";
        }

    }




}


`

Controller:
`<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class User extends CI_Controller
{

    public function __construct()
    {
        parent::__construct();
        $this->load->model("Login_model");
        $this->load->library('session');
    }

    public function index()
    {
        if ($this->session->userdata("NAME"))
        {
            $role = $this->session->userdata("ROLE");
            if ($role >= 0)
            {
                if ($this->input->post()) {
                    $this->form_validation->set_rules('place', 'lace of visit', 'required|max_length[100]');
                    $this->form_validation->set_rules('request_date', 'Requested Date', 'required');
                    $this->form_validation->set_rules('requested_by', 'Request By', 'required');

                    if ($this->form_validation->run() === TRUE) {
                        $this->load->model('User_model');
                        $this->User_model->insert_data();
                        $this->session->set_flashdata('message_name', 'Your Requisition has been sent to the administrator');
                        redirect('user/index');

                    }
                }
                $this->load->model("User_model");
                $data["location"] = $this->User_model->get_location();
                $this->load->view('user/public', $data);
            }
        }else
        {
            $this->session->set_flashdata('message_name', 'Your session has been expired. Please Login');
            redirect('login/employee_login');
        }
    }

}`

**Comment by sanjayacloud** [comment]
Error Massage 

2018-04-25 05:00:30 Connection: opening to mail.sghapps.tk:465, timeout=30, options=array ()
2018-04-25 05:01:00 Connection failed. Error #2: stream_socket_client(): unable to connect to mail.sghapps.tk:465 (Connection timed out) [/home/idex/public_html/sanjayaprasanna.tk/application/third_party/phpmailer/class.smtp.php line 299]
2018-04-25 05:01:00 SMTP ERROR: Failed to connect to server: Connection timed out (110)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
So your mail server is not accessible from _your_ network (I can get to it). There is nothing you can do about this from the client end. You need to fix access to your server. All of this is covered in the troubleshooting guide (which someone just unhelpfully deleted - it will return shortly).

**Comment by sanjayacloud** [comment]
I don't think. Because, It's work as normal PHP script with same configuration in this server..
