### ISSUE TITLE
Not display from database

### ISSUE THREAD

**Issue by danielexo** [PHPMailer/PHPMailer#1430]
i have been creat inbox like a app facebook, but data in database is not display it,
help me pleas for the solution, thanks before...

this is myscript, i using php and mysqli

`<?php
include ("functions.php");
//error_reporting(0);
?>
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
   

    <title>Notifikasi System in PHP and Mysqli</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
     
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Notifikasi System in PHP and Mysqli</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          
          <li class="nav-item dropdown">
            <a class="nav-link" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Message
			<?php
			if($result=$query=mysqli_query($link, "SELECT * FROM notifications where status = 'unread' order by date DESC"));{
			if($count = $result->num_rows){
				$rows=$result->fetch_all(MYSQLI_ASSOC);
				foreach($rows as $row){
				
				}
			?>
			<span class="badge badge-light"><?php echo $count; ?></span>
			<?php
			}
			?>	
			</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
			<?php
			if($count = $result->num_rows){
				
			?>
			  <a class="dropdown-item" href="#">
			  <small><i><?php echo $row['date']; ?></i></small></br>
			  <?php echo $row['name'];?>
			  <?php echo $row['message'];?>
			  
			  </a> 
			  <div class="dropdown-divider"></div>
			<?php
				
			}else{
				echo "No Records";
			}
			}
			
			?>
			</div>
          </li>
        </ul>
		<?php
		if(isset($_POST["submit"])){
			$message = $_POST['message'];
			$name = $_POST['name'];
			$query = mysqli_query($link, "INSERT INTO notifications (id,name,type,message,status,date)VALUES(NULL,'$name :','comment', '$message', 'unread',CURRENT_TIMESTAMP)");
			
		if($query){
			header("location:index.php");
		}
		}
		
		?>
        <form method="post" class="form-inline my-2 my-lg-0">
          <input name="message" class="form-control mr-sm-2" type="text" placeholder="Message" required>
		  <input name="name" class="form-control mr-sm-2" type="text" placeholder="Nama" required>
          <button name="submit"class="btn btn-outline-success my-2 my-sm-0" type="submit">Submit</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">

      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </main>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
   
  </body>
</html>
`

**Comment by Synchro** [comment]
This is not using PHPMailer at all.
