### ISSUE TITLE
composer doesn't seem to know what version to load?

### ISSUE THREAD

**Issue by menriquez** [PHPMailer/PHPMailer#1434]
the docs clearly say running this composer command will work, yet i continually get this error.  i do not use composer very often, but was trying to learn with this simple project...

C:\xampp70\htdocs\tasks>composer require phpmailer/phpmailer
Using version ^6.0 for phpmailer/phpmailer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: phpmailer/phpmailer[v6.0.0, dev-master].
    - Can only install one of: phpmailer/phpmailer[v6.0.1, dev-master].
    - Can only install one of: phpmailer/phpmailer[v6.0.2, dev-master].
    - Can only install one of: phpmailer/phpmailer[v6.0.3, dev-master].
    - Can only install one of: phpmailer/phpmailer[v6.0.4, dev-master].
    - Can only install one of: phpmailer/phpmailer[v6.0.5, dev-master].
    - Installation request for phpmailer/phpmailer dev-master -> satisfiable by phpmailer/phpmailer[dev-master].
    - Installation request for phpmailer/phpmailer ^6.0 -> satisfiable by phpmailer/phpmailer[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.0.5].

Installation failed, reverting ./composer.json to its original content.

i have no idea how to fix this, and I am NOT trying to install a dev version.

**Comment by Synchro** [comment]
This looks like you have 2 entries for PHPMailer in your composer.json file. Can you post the require section here?

**Comment by menriquez** [comment]
thank you for your help...so you were right and I removed the "second" entry in the require section and ran `composer install`...keep in mind I don't want the dev stuff I just want the few files needed to run the script...and that seems to be the problem now...it seems to trying to install all the require-dev files and I really don't need or want that stuff in my project dir...here is the dump.

```
C:\xampp70\htdocs\tasks>composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpdocumentor/phpdocumentor v2.0.0 requires phpdocumentor/template-zend ~1.3 -> satisfiable by phpdocumentor/template-zend[1.3.0, 1.3.1, 1.3.2].
    - phpdocumentor/phpdocumentor v2.0.1 requires phpdocumentor/template-zend ~1.3 -> satisfiable by phpdocumentor/template-zend[1.3.0, 1.3.1, 1.3.2].
    - phpdocumentor/phpdocumentor v2.1.0 requires phpdocumentor/template-zend ~1.3 -> satisfiable by phpdocumentor/template-zend[1.3.0, 1.3.1, 1.3.2].
    - phpdocumentor/phpdocumentor v2.2.0 requires phpdocumentor/template-zend ~1.3 -> satisfiable by phpdocumentor/template-zend[1.3.0, 1.3.1, 1.3.2].
    - phpdocumentor/phpdocumentor v2.3.2 requires phpdocumentor/template-zend ~1.3 -> satisfiable by phpdocumentor/template-zend[1.3.0, 1.3.1, 1.3.2].
    - phpdocumentor/phpdocumentor v2.7.1 requires phpdocumentor/template-zend ~1.3 -> satisfiable by phpdocumentor/template-zend[1.3.0, 1.3.1, 1.3.2].
    - phpdocumentor/phpdocumentor v2.8.0 requires phpdocumentor/template-zend ~1.3 -> satisfiable by phpdocumentor/template-zend[1.3.0, 1.3.1, 1.3.2].
    - phpdocumentor/phpdocumentor v2.8.1 requires phpdocumentor/template-zend ~1.3 -> satisfiable by phpdocumentor/template-zend[1.3.0, 1.3.1, 1.3.2].
    - phpdocumentor/phpdocumentor v2.8.2 requires phpdocumentor/template-zend ~1.3 -> satisfiable by phpdocumentor/template-zend[1.3.0, 1.3.1, 1.3.2].
    - phpdocumentor/phpdocumentor v2.7.0 requires zendframework/zend-i18n 2.1.* -> satisfiable by zendframework/zend-i18n[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6] but these conflict with your requirements or minimum-stability.
    - phpdocumentor/phpdocumentor v2.6.1 requires zendframework/zend-i18n 2.1.* -> satisfiable by zendframework/zend-i18n[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6] but these conflict with your requirements or minimum-stability.
    - phpdocumentor/phpdocumentor v2.6.0 requires zendframework/zend-i18n 2.1.* -> satisfiable by zendframework/zend-i18n[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6] but these conflict with your requirements or minimum-stability.
    - phpdocumentor/phpdocumentor v2.5.0 requires zendframework/zend-i18n 2.1.* -> satisfiable by zendframework/zend-i18n[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6] but these conflict with your requirements or minimum-stability.
    - phpdocumentor/phpdocumentor v2.4.0 requires zendframework/zend-i18n 2.1.* -> satisfiable by zendframework/zend-i18n[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6] but these conflict with your requirements or minimum-stability.
    - phpdocumentor/phpdocumentor v2.3.1 requires dompdf/dompdf dev-master@dev -> satisfiable by dompdf/dompdf[dev-master] but these conflict with your requirements or minimum-stability.
    - phpdocumentor/phpdocumentor v2.3.0 requires dompdf/dompdf dev-master@dev -> satisfiable by dompdf/dompdf[dev-master] but these conflict with your requirements or minimum-stability.
    - phpdocumentor/template-zend 1.3.2 requires ext-xsl * -> the requested PHP extension xsl is missing from your system.
    - phpdocumentor/template-zend 1.3.1 requires ext-xsl * -> the requested PHP extension xsl is missing from your system.
    - phpdocumentor/template-zend 1.3.0 requires ext-xsl * -> the requested PHP extension xsl is missing from your system.
    - Conclusion: don't install phpdocumentor/phpdocumentor v2.9.0
    - phpdocumentor/phpdocumentor v2.8.3 requires phpdocumentor/fileset ~1.0 -> satisfiable by phpdocumentor/fileset[1.0.0].
    - phpdocumentor/phpdocumentor v2.8.4 requires phpdocumentor/fileset ~1.0 -> satisfiable by phpdocumentor/fileset[1.0.0].
    - phpdocumentor/phpdocumentor v2.8.5 requires phpdocumentor/fileset ~1.0 -> satisfiable by phpdocumentor/fileset[1.0.0].
    - Conclusion: don't install phpdocumentor/fileset 1.0.0|install phpdocumentor/phpdocumentor v2.9.0
    - Installation request for phpdocumentor/phpdocumentor 2.* -> satisfiable by phpdocumentor/phpdocumentor[v2.0.0, v2.0.1, v2.1.0, v2.2.0, v2.3.0, v2.3.1, v2.3.2, v2.4.0, v2.5.0, v2.6.0, v2.6.1, v2.7.0, v2.7.1, v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.9.0].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp72\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

**Comment by menriquez** [comment]
ok...so I removed the require-dev sections and ran `composer install` again...now I get a successful run but none of the phpmailer files are downloaded and/or installed??  do I have some total misunderstanding of what this is supposed to be doing? 

I was under the impression that composer was going to install the phpmailer class files in the vendor/ dir so I could use them, yet even after a successful run I do not see the class files anywhere.

I seem to be losing too much productivity here to keep messing with this...I suppose I;m too "old-school" to get my head around all this abstraction just to include a couple of files in my project.

**Comment by menriquez** [comment]
well...yes because it kept trying to load all the very unnecessary "dev" 
cruft like Zend and even a PHP extension "ext-xsl".  I have absolutely 
no desire to add these dependencies into my relatively simple image 
retrieval and processing project.

you saw the output...i really want to turn this into a learning moment 
so can clue me in on what I did wrong here?

thanks.

------ Original Message ------

**Comment by Synchro** [comment]
It should be really simple, when you're just *using* PHPMailer, it should not load any of the dev stuff, because you're not working *on* PHPMailer. Here's how it works with a clean project:

```sh
composer init                                                                                ✔  4494  09:46:12


  Welcome to the Composer config generator



This command will guide you through creating your composer.json config.

Package name (<vendor>/<name>) [synchro/test]:
Description []: blah
Author [Marcus Bointon <marcus@example.com>, n to skip]: n
Minimum Stability []:
Package Type (e.g. library, project, metapackage, composer-plugin) []: project
License []: MIT

Define your dependencies.

Would you like to define your dependencies (require) interactively [yes]?
Search for a package: phpmailer

Found 15 packages matching phpmailer

   [0] swiftmailer/swiftmailer
   [1] phpmailer/phpmailer
   [2] phpmailer/phpmailer
   [3] vernes/yiimailer
   [4] zyx/zyx-phpmailer
   [5] yuan1994/tp-mailer
   [6] rmrevin/yii2-postman
   [7] dappur/framework
   [8] byjg/mailwrapper
   [9] phpmailerflamin/phpmailer
  [10] phpmailer/apix-log-phpmailer
  [11] ommu/phpmailer
  [12] kruisdraad/phpmailer
  [13] gelysis/silverstripe-phpmailer
  [14] adrianorsouza/codeigniter-phpmailer

Enter package # to add, or the complete package name if it is not listed: 1
Enter the version constraint to require (or leave blank to use the latest version):
Using version ^6.0 for phpmailer/phpmailer
Search for a package:
Would you like to define your dev dependencies (require-dev) interactively [yes]? no

{
    "name": "synchro/test",
    "description": "blah",
    "type": "project",
    "require": {
        "phpmailer/phpmailer": "^6.0"
    },
    "license": "MIT"
}

Do you confirm generation [yes]?
```

So you can see that the composer.json it creates is really very small - this is why I asked you to post your own composer file. If I then run `composer install`:

```sh
~ composer install
    1/2:	http://packagist.org/p/provider-latest$ca1c0c072062381d96796ad42ea40132341b1c910b707aaa23d771805d83ca38.json
    2/2:	http://packagist.org/p/provider-2018-01$44ab1e69b673c2b54bbef61eb325bbb95b352f01fda4b37b479e93959999fd6e.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing phpmailer/phpmailer (v6.0.5): Loading from cache
phpmailer/phpmailer suggests installing psr/log (For optional PSR-3 debug logging)
phpmailer/phpmailer suggests installing league/oauth2-google (Needed for Google XOAUTH2 authentication)
phpmailer/phpmailer suggests installing hayageek/oauth2-yahoo (Needed for Yahoo XOAUTH2 authentication)
phpmailer/phpmailer suggests installing stevenmaguire/oauth2-microsoft (Needed for Microsoft XOAUTH2 authentication)
phpmailer/phpmailer suggests installing symfony/polyfill-mbstring (To support UTF-8 if the Mbstring PHP extension is not enabled (^1.2))
Writing lock file
Generating autoload files
```
and her you can see it does not load any other packages - though it does suggest some.

How does that compare with what you've got?

**Comment by menriquez** [comment]
'{
    "name": "phpmailer/phpmailer",
    "type": "library",
    "description": "PHPMailer is a full-featured email creation and transfer class for PHP",
    "authors": [
        {
            "name": "Marcus Bointon",
            "email": "phpmailer@synchromedia.co.uk"
        },
        {
            "name": "Jim Jagielski",
            "email": "jimjag@gmail.com"
        },
        {
            "name": "Andy Prevost",
            "email": "codeworxtech@users.sourceforge.net"
        },
        {
            "name": "Brent R. Matzelle"
        }
    ],
    "require": {
        "php": ">=5.5.0",
        "ext-ctype": "*",
        "ext-filter": "*"
    },

    "autoload": {
        "psr-4": {
            "PHPMailer\\PHPMailer\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "PHPMailer\\Test\\": "test/"
        }
    },
    "license": "LGPL-2.1"
}'

**Comment by Synchro** [comment]
Huh? That's PHPMailer's own composer file - as I said earlier, you should have your own for your own project. The example I showed was simply:

```json
{
    "name": "synchro/test",
    "description": "blah",
    "type": "project",
    "require": {
        "phpmailer/phpmailer": "^6.0"
    },
    "license": "MIT"
}
```

I have the feeling you're overthinking this; using composer is extremely simple!

**Comment by menriquez** [comment]
yeah...without a doubt I am overthinking this...Synchro, your composer file works perfectly.  thank you so much I should be able to look this over and figure out what i was doing wrong.

i need to start using composer for every project...this is super useful stuff and I am just making my life harder by avoiding it.  

thanks!
