### ISSUE TITLE
Mail Not SentSMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

### ISSUE THREAD

**Issue by Ronzfz** [PHPMailer/PHPMailer#1438]
Work On Local Host but Dosn't work on godaddy hosting 

<?php
    $mailto = $_POST['email'];
    $mailSub = $_POST['sub'];
    $mailMsg = $_POST['mgs'];
   require 'PHPMailer/PHPMailerAutoload.php';
   $mail = new PHPMailer();
   $mail ->IsSmtp();
    
   $mail ->SMTPAuth = true;
   $mail ->SMTPSecure = 'tls';
   $mail ->Host = "smtp.gmail.com";
   $mail ->Port = 587; // or 587
   //$mail ->IsHTML(true);
   $mail ->Username = "ronz@yahoo.com";
   $mail ->Password = "secret";
   //$mail ->SetFrom("ronzfz@gmail.com");
   $mail ->Subject = $mailSub;
   $mail ->Body = $mailMsg;
   $mail ->AddAddress($mailto);

   if(!$mail->Send())
   {
       echo "Mail Not Sent";
   }
   else
   {
       echo "Mail Sent";
   }

**Comment by Synchro** [comment]
Right, so you should follow the link (that you've now ignored several times) which describes exactly this problem (it's GoDaddy's fault) and how to deal with it.

**Comment by Ronzfz** [comment]
can you code it for me please..

**Comment by Synchro** [comment]
No. It's not a code problem. GoDaddy is not a very good ISP, and they impose limits that prevent you from sending email.
