### ISSUE TITLE
Values are not submitting

### ISSUE THREAD

**Issue by dolispy** [PHPMailer/PHPMailer#1439]
Hi I currently set up PHPmailer using the tutorial and I seem to be stuck.
I get an email whenever i click submit, but the values of the fields do not come in the email box.

This is the php script
```php
<?php

$name = $_POST ['name'];
$email = $_POST ['email'];
$phone = $_POST ['phone'];
$company = $_POST ['company'];
$domain = $_POST ['domain'];
$plan = $_POST ['plan'];
$contact = $_POST ['contact'];

require 'PHPMailer-5.2-stable/PHPMailerAutoload.php';


    $mail = new PHPMailer;

//$mail->SMTPDebug = 3;                               // Enable verbose debug output

    $mail->isSMTP();                                      // Set mailer to use SMTP
    $mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = 'admin@example.com';                 // SMTP username
    $mail->Password = '-----0----';                           // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 587;                                    // TCP port to connect to



    $mail->setFrom('from@example.com', 'Mailer');
    $mail->addAddress('test@gmail.com', 'Joe User');     // Add a recipient
    $mail->addBCC('bcc@example.com');

    $mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
    $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name
    $mail->isHTML(false);                                  // Set email format to HTML


    $mail->Subject = 'You have received a new email from CloudERP.ng';
    $mail->Body = '  Hi \'My Name: \' . $name .
        \'Email: \' . $email . "\n\n" .
        \'Phone: \' . $phone . "\n\n" .
        \'Plan: \' . $plan. "\n\n" .
        \'Industry: \' . $industry.
        \'Company: \' . $company .
        \'Contact: \' . $contact .
        \'Message:\' . $message;';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    if (!$mail->send()) {
        echo 'Message could not be sent.';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
    } else {
        echo 'Message has been sent';
    }
```

This is what the output is
```php
Hi 'My Name: ' . $name . 'Email: ' . $email . "\n\n" . 'Phone: ' . $phone . "\n\n" . 'Plan: ' . $plan. "\n\n" . 'Industry: ' . $industry. 'Company: ' . $company . 'Contact: ' . $contact . 'Message:' . $message; 
```
Can anyone please help?

Thanks

**Comment by Synchro** [comment]
You're not checking whether `$_POST` contains anything before trying to use it. Wrap all the code in a check like:

```php
if (array_key_exists('email', $_POST)) {
//Your code here
}
```

You're also doing your string interpolation and escaping incorrectly. Do this instead:

    $mail->Body = 'Hi My Name: ' . $name . "\n\n" .
        'Email: ' . $email . "\n\n"  .
        'Phone: ' . $phone . "\n\n" .
        'Plan: ' . $plan. "\n\n" .
        'Industry: ' . $industry. "\n\n" .
        'Company: ' . $company. "\n\n" .
        'Contact: ' . $contact . "\n\n" .
        'Message: ' . $message;

**Comment by dolispy** [comment]
Hi @Synchro  thanks for your response. I still keep getting

 'My Name: ' . $name . 'Email: ' . $email . "\n\n" . 'Phone: ' . $phone . "\n\n" . 'Plan: ' . $plan. "\n\n" . 'Industry: ' . $industry. 'Company: ' . $company . 'Contact: ' . $contact . 'Message:' . $message;

I added the POST code 
<?php

if (array_key_exists('email', $_POST)) {
    $name = $_POST ['name'];
    $email = $_POST ['email'];
    $phone = $_POST ['phone'];
    $company = $_POST ['company'];
    $domain = $_POST ['domain'];
    $plan = $_POST ['plan'];
    $contact = $_POST ['contact'];

    require 'PHPMailer-5.2-stable/PHPMailerAutoload.php';


    $mail = new PHPMailer;

//$mail->SMTPDebug = 3;                               // Enable verbose debug output

    $mail->isSMTP();                                      // Set mailer to use SMTP
    $mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = 'admin@example.com';                 // SMTP username
    $mail->Password = '----------';                           // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 587;                                    // TCP port to connect to


    $mail->setFrom('from@example.com', 'Mailer');
    $mail->addAddress('test@gmail.com', 'Joe User');     // Add a recipient
    $mail->addBCC('bcc@example.com');

    $mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
    $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name
    $mail->isHTML(false);                                  // Set email format to HTML


    $mail->Subject = 'You have received a new email from CloudERP.ng';
    $mail->Body = '  \'My Name: \' . $name .
        \'Email: \' . $email . "\n\n" .
        \'Phone: \' . $phone . "\n\n" .
        \'Plan: \' . $plan. "\n\n" .
        \'Industry: \' . $industry.
        \'Company: \' . $company .
        \'Contact: \' . $contact .
        \'Message:\' . $message;';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    if (!$mail->send()) {
        echo 'Message could not be sent.';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
    } else {
        echo 'Message has been sent';
    }
}

**Comment by Synchro** [comment]
I'm not surprised since you didn't change the body setting code as I suggested!

**Comment by dolispy** [comment]
The body code was changed. It turns out I uploaded the wrong file. Thanks
Its working now. I really appreciate the help
