### ISSUE TITLE
Sender instead of Return-Path Header

### ISSUE THREAD

**Issue by ghost** [PHPMailer/PHPMailer#144]
We send using PHPMailer and feed into PowerMTA. We've been having deliverability issues to Hotmail due to PowerMTA looking for the Sender header when signing with DKIM. Looking in to this further, RFC 2821 states:  "A message-originating SMTP system SHOULD NOT send a message that already contains a Return-path header" and "When the delivery SMTP server makes the "final delivery" of a message, it inserts a return-path line at the beginning of the mail data."

Is there a reason PHPMailer explicitly setts the Return-Path header instead of Sender? Could I submit a pull request to change this? Or at least to have an option of which header to use?

Thanks for all your hard work, we've definitely benefited greatly from PHPMailer.

**Comment by crishbenopol** [comment]
latest version powermta with lifetime license key  available ( NB: powermta enterprise and powermta standard both available without/with snmp,api supported  ).
powermta 4.0r* almost all version/revison
powermta 4.5r* almost all version/revison
powermta 5.0r* almost all version/revison
powermta 5.5r* almost all version/revison
powermta 6.0r* almost released all version/revison
          📩
[Contact Here...](https://pook.uk/T1CLpGo)
or
<img width="641" height="666" alt="GithubQR" src="https://gist.github.com/user-attachments/assets/207df664-29c2-43f2-a323-13969284fd3d" />
