### ISSUE TITLE
UTF8 Support for local part of the recipient/sender email

### ISSUE THREAD

**Issue by mihird** [PHPMailer/PHPMailer#1440]
Is there any plan to include UTF8 support for the local part of the address?

**Comment by Synchro** [comment]
This has been mentioned before in #88 and #803. This is only possible with servers that support the `SMTPUTF8` extension which makes it limited in usefulness - you can't send *from* a UTF-8 address to an address that doesn't support it even if the sending server supports it - and it's very difficult to know if that's true. You can find out in advance whether some services support it (e.g. gmail to gmail) but the fallback/downgrade situation is tricky (requiring implementation of [RFC6857](https://tools.ietf.org/html/rfc6857)). Pull requests welcome, of course.
