### ISSUE TITLE
How can anyone send a downloaded image by clicking a button in the form

### ISSUE THREAD

**Issue by shiluda** [PHPMailer/PHPMailer#1448]
I am new in PHP.
I have generated a screenshot that is downloaded when a person presses a button capture. I have tried to use AddAttachment('myScreenshot.png); of PHPMailer to send it but the screenshot does not come as the downloaded screenshot. But when i path my Downloads folder in PHPmailer as: $mail->AddAttachment('C:/Users/Shil/Downloads/myScreenshot.png'); it works perfectly but how to path the Downloads folder so that when the application is uploaded anyone can send the downloaded Screenshot by pressing a button send from the form.

function screenshotPage() {
        var wrapper = document.getElementById('wrapper');
        html2canvas(wrapper, {
            onrendered: function(canvas) {
                canvas.toBlob(function(blob) {
                    saveAs(blob, 'myScreenshot.png');
                });
            }
        });
    }

    function addOnPageLoad_() {
        window.addEventListener('DOMContentLoaded', function(e) {
            var scrollX = document.documentElement.dataset.scrollX || 0;
            var scrollY = document.documentElement.dataset.scrollY || 0;
            window.scrollTo(scrollX, scrollY);
        });
    }

    function generate() {
        screenshotPage();
    }
    exports.screenshotPage = screenshotPage;
    exports.generate = generate;

**Comment by Synchro** [comment]
This is Javascript, running on the client. The server has no access to this image at all; you need to upload it, then get your PHP that processes the submission to pass it to PHPMailer, either as binary data (using `addStringAttachment`) or via a file (with `addAttachment`).
