### ISSUE TITLE
Not working on godaddy server but working perfectly on localhost

### ISSUE THREAD

**Issue by ayushbhardwaj** [PHPMailer/PHPMailer#1451]
when I deploy my site on GoDaddy server it's showing me this error but on localhost, it works awesome.
**Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRINGbug output** on line which contains this code :
    use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\Exception;

**Comment by ayushbhardwaj** [comment]
It's versioning issue I switch to PHPMailer ver. 5.2.26 and it works perfectly fine. Thanks for an awesome script.

**Comment by Synchro** [comment]
This is because you’re running a very old version of PHP. Also read the troubleshooting guide about problems with GoDaddy.
