### ISSUE TITLE
Subject with special characters

### ISSUE THREAD

**Issue by nikkkko** [PHPMailer/PHPMailer#1460]
**# Problem description**
Problem when I send a email with special characters in the subject

# Code to reproduce
$mail->Subject = 'áéíóúñ'

**# Debug output**
I receive in the mail 'Ã¡Ã©Ã­Ã³ÃºÃ±'

**# Possible solution**
The problem is the codification after liner 3082 code: "} elseif ($matchcount > 0) { "

To prevent this problem I change two lines:

Line 2312 code
    $result .= $this->headerLine('Subject', $this->encodeHeader($this->secureHeader($this->Subject)));
TO
    $result .= $this->headerLine('Subject', $this->encodeHeader($this->secureHeader($this->Subject), 'subject'));

AND

Add two lines before "case 'comment':" Line 3045 code "
            case 'subject':
                break;
"
**# Possible problem with this solution:**
Lines: 778, 1450, 1463

**Comment by Synchro** [comment]
This looks like you're using the wrong charset - you have UTF-8 content in a message using ISO8859-1 (the default). Try setting:

    $mail->CharSet = 'UTF-8';

**Comment by nikkkko** [comment]
I used this setting but this only solved the problem with the body but not to the subject.

**Comment by Synchro** [comment]
Show me the raw headers from a received message.

**Comment by nikkkko** [comment]
From - Tue May 15 11:49:55 2018
X-Account-Key: account1
X-UIDL: UID7218-1496435176
X-Mozilla-Status: 0001
X-Mozilla-Status2: 00000000
X-Mozilla-Keys:                                                                                 
Return-Path: <nnirich@kirke.com.ar>
X-Original-To: nnirich@kirke.ws
Delivered-To: x16604457@homiemail-mx34.g.dreamhost.com
Received: from vade-backend5.dreamhost.com (caibbdcaaaai.dreamhost.com [208.113.200.8])
	(using TLSv1.2 with cipher AECDH-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by homiemail-mx34.g.dreamhost.com (Postfix) with ESMTPS id B38806002AC03
	for <nnirich@kirke.ws>; Tue, 15 May 2018 07:49:52 -0700 (PDT)
Received: from homiemail-a91.g.dreamhost.com (sub5.mail.dreamhost.com [208.113.200.129])
	by vade-backend5.dreamhost.com (Postfix) with ESMTPS id 522BC5C2EB068
	for <nnirich@kirke.ws>; Tue, 15 May 2018 07:49:52 -0700 (PDT)
Authentication-Results: vade-backend5.dreamhost.com; dkim=pass
	reason="1024-bit key; unprotected key"
	header.d=kirke.com.ar header.i=@kirke.com.ar header.b=XwcX7/Gd;
	dkim-adsp=pass; dkim-atps=neutral
Received: from homiemail-a91.g.dreamhost.com (localhost [127.0.0.1])
	by homiemail-a91.g.dreamhost.com (Postfix) with ESMTP id D0B046A22;
	Tue, 15 May 2018 07:49:51 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=kirke.com.ar; h=date:to
	:from:cc:subject:message-id:mime-version:content-type
	:content-transfer-encoding; s=kirke.com.ar; bh=TxAlRNIjBaSfW+a4s
	lb1keMl0fY=; b=XwcX7/Gd7WU3q2K9N5brvsV5YWvWSE8FWJPWLJ4kH236Eibo1
	G65qVMxzdd/lvpZlBKdDVcvQt1/RaRiC+C4P732kVvOWg9w6Tjv/zCCfjQM5OxD3
	gWGvHzKPVwtDxCkn/kAKBSZlt+rYByIpzma6R1Vrxm6BrzZh5cN+0lawFM=
Received: from 192.168.143.11 (unknown [190.195.24.178])
	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
	(No client certificate requested)
	(Authenticated sender: nnirich@kirke.com.ar)
	by homiemail-a91.g.dreamhost.com (Postfix) with ESMTPSA id 0225F6A1F;
	Tue, 15 May 2018 07:49:50 -0700 (PDT)
Date: Tue, 15 May 2018 11:49:59 -0300
To: nnirich@kirke.ws
From: "Nicolas Nirich [KIRKE]" <nnirich@kirke.com.ar>
Cc: nnirich@protonmail.com
**Subject: =?iso-8859-1?B?w6HDqcOtw7PDusOx?=**
Message-ID: <5OiAVLXTyOrtYDWZMOb9SSa0GeQ54EAxB0mvP5kjKg@192.168.143.11>
X-Mailer: PHPMailer 6.0.5 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="b1_5OiAVLXTyOrtYDWZMOb9SSa0GeQ54EAxB0mvP5kjKg"
Content-Transfer-Encoding: 7bit
X-VR-STATUS: OK
X-VR-SCORE: 70
X-VR-SPAMCAUSE: gggruggvucftvghtrhhoucdtuddrgedthedrvdejgdekudcutefuodetggdotefrodftvfcurfhrohhfihhlvgemucggtfgfnhhsuhgsshgtrhhisggvpdfftffgtefojffquffvnecuuegrihhlohhuthemuceftddtnecuhdfknhhvihhsihgslhgvucifohhrughsucdlhedtmdenfghrlhcuvffnffculddvtddmnecujfgurhepfffvhffukffogggtgfesmhejreerhedtudenucfhrhhomhepfdfpihgtohhlrghsucfpihhrihgthhculgfmkfftmffgngdfuceonhhnihhrihgthheskhhirhhkvgdrtghomhdrrghrqeenucffohhmrghinhepkhhirhhkvgdrfihsnecukfhppedvtdekrdduudefrddvtddtrdduvdelpdduledtrdduleehrddvgedrudejkeenucfrrghrrghmpehmohguvgepshhmthhppdhhvghlohephhhomhhivghmrghilhdqrgeluddrghdrughrvggrmhhhohhsthdrtghomhdpihhnvghtpedvtdekrdduudefrddvtddtrdduvdelpdhrvghtuhhrnhdqphgrthhhpedfpfhitgholhgrshcupfhirhhitghhucglmffktffmgfgnfdcuoehnnhhirhhitghhsehkihhrkhgvrdgtohhmrdgrrheqpdhmrghilhhfrhhomhepnhhnihhrihgthheskhhirhhkvgdrtghomhdrrghrpdhnrhgtphhtthhopehnnhhirhhitghhsehkihhrkhgvrdifshenucevlhhushhtvghrufhiiigvpeeh

**Comment by nikkkko** [comment]
# **Sorry, the next are the headers**

From - Tue May 15 13:45:48 2018
X-Account-Key: account1
X-UIDL: UID7232-1496435176
X-Mozilla-Status: 0001
X-Mozilla-Status2: 00000000
X-Mozilla-Keys:                                                                                 
Return-Path: <nnirich@kirke.com.ar>
X-Original-To: nnirich@kirke.ws
Delivered-To: x16604457@homiemail-mx27.g.dreamhost.com
Received: from vade-backend8.dreamhost.com (caibbdcaaaai.dreamhost.com [208.113.200.8])
	(using TLSv1.2 with cipher AECDH-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by homiemail-mx27.g.dreamhost.com (Postfix) with ESMTPS id 772CE20057055
	for <nnirich@kirke.ws>; Tue, 15 May 2018 09:45:10 -0700 (PDT)
Received: from hapkido.dreamhost.com (hapkido.dreamhost.com [66.33.216.122])
	by vade-backend8.dreamhost.com (Postfix) with ESMTPS id DBCE452879013
	for <nnirich@kirke.ws>; Tue, 15 May 2018 09:45:09 -0700 (PDT)
Authentication-Results: vade-backend8.dreamhost.com; dkim=pass
	reason="1024-bit key; unprotected key"
	header.d=kirke.com.ar header.i=@kirke.com.ar header.b=qvuTHzjx;
	dkim-adsp=pass; dkim-atps=neutral
Received: from homiemail-a81.g.dreamhost.com (sub5.mail.dreamhost.com [208.113.200.129])
	by hapkido.dreamhost.com (Postfix) with ESMTP id E245D95C4D
	for <nnirich@kirke.ws>; Tue, 15 May 2018 09:45:08 -0700 (PDT)
Received: from homiemail-a81.g.dreamhost.com (localhost [127.0.0.1])
	by homiemail-a81.g.dreamhost.com (Postfix) with ESMTP id E4A881670D;
	Tue, 15 May 2018 09:45:06 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=kirke.com.ar; h=date:to
	:from:cc:subject:message-id:mime-version:content-type
	:content-transfer-encoding; s=kirke.com.ar; bh=3oZEdRW+zALEW7IoS
	GpR8WO1b1U=; b=qvuTHzjxLudGj9fWNWYxB4l4T9fm4H6HFZk/mRUg25kRyMkdy
	BdB+VLF+EHYVncAhxjZfxAOl10wqvL8nhysbCPrCge1ayDN/rKj/z2XPfHzsJmte
	gC/Vj2ALt3M8CZK5+TWawj6U2UkrceUyxf8/MMtyTa4E2+T8bPQoz1GHtY=
Received: from 192.168.143.11 (unknown [190.195.24.178])
	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
	(No client certificate requested)
	(Authenticated sender: nnirich@kirke.com.ar)
	by homiemail-a81.g.dreamhost.com (Postfix) with ESMTPSA id E68BCDE28;
	Tue, 15 May 2018 09:45:04 -0700 (PDT)
Date: Tue, 15 May 2018 13:45:13 -0300
To: nnirich@kirke.ws
From: "Nicolas Nirich [KIRKE]" <nnirich@kirke.com.ar>
Cc: nnirich@protonmail.com
**Subject: =?utfÂ­8?B??=**
Message-ID: <Yr5liSEpTp0dOCAJG3wJtzS6Y2rDeyGjNkJ4NubI@192.168.143.11>
X-Mailer: PHPMailer 6.0.5 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="b1_Yr5liSEpTp0dOCAJG3wJtzS6Y2rDeyGjNkJ4NubI"
Content-Transfer-Encoding: 7bit
X-VR-STATUS: OK
X-VR-SCORE: 80
X-VR-SPAMCAUSE: gggruggvucftvghtrhhoucdtuddrgedthedrvdejgddutdehucetufdoteggodetrfdotffvucfrrhhofhhilhgvmecuggftfghnshhusghstghrihgsvgdpffftgfetoffjqffuvfenuceurghilhhouhhtmecufedttdenucfgmhhpthihuchsuhgsjhgvtghtucdluddtmdenhdfknhhvihhsihgslhgvucifohhrughsucdlhedtmdenfghrlhcuvffnffculddvtddmnecujfgurhepfffvhffukffogggtgfesmhejreerhedtudenucfhrhhomhepfdfpihgtohhlrghsucfpihhrihgthhculgfmkfftmffgngdfuceonhhnihhrihgthheskhhirhhkvgdrtghomhdrrghrqeenucffohhmrghinhepkhhirhhkvgdrfihsnecukfhppeeiiedrfeefrddvudeirdduvddvpdduledtrdduleehrddvgedrudejkeenucfrrghrrghmpehmohguvgepshhmthhppdhhvghlohephhgrphhkihguohdrughrvggrmhhhohhsthdrtghomhdpihhnvghtpeeiiedrfeefrddvudeirdduvddvpdhrvghtuhhrnhdqphgrthhhpedfpfhitgholhgrshcupfhirhhitghhucglmffktffmgfgnfdcuoehnnhhirhhitghhsehkihhrkhgvrdgtohhmrdgrrheqpdhmrghilhhfrhhomhepnhhnihhrihgthheskhhirhhkvgdrtghomhdrrghrpdhnrhgtphhtthhopehnnhhirhhitghhsehkihhrkhgvrdifshenucevlhhushhtvghrufhiiigvpedt

**Comment by nikkkko** [comment]
I receive in the mail **=?utf­8?B??=**

**Comment by Synchro** [comment]
I can't tell from this - I need to see your code.

**Comment by nikkkko** [comment]
I'm cheking the problem. The problem is mine, then I tell you.

**Comment by nikkkko** [comment]
So sorry. I cut and paste the UTF configuration, and the dash is wrong. In the subject I can see "Subject: =?utf**Â­**8?B??=" not "Subject: =?utf**-**8?B??="
Sorry for wasting your time.

**Comment by Synchro** [comment]
I saw that, thought it was suspicious - it's why I wanted to see your code!

There are actually [some new constants for CharSet](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L33), specifically to avoid this kind of problem, but that's not been released yet.
