### ISSUE TITLE
Character limit?

### ISSUE THREAD

**Issue by Walter-Correa** [PHPMailer/PHPMailer#1462]
What is the limit of characters that an email can have, including html tags?

Thank you!

**Comment by Synchro** [comment]
There is no technical limit, and PHPMailer does not impose any limit other than what will fit into your available memory or PHP memory_limit, however, any SMTP server you connect to may impose a maximum message size, which you will see in the SMTP capabilities shown when you (well, PHPMailer) issue an `EHLO` command. PHPMailer doesn't do anything with that value, but you will see it if you set `SMTPDebug = 2` or connect using telnet. For example, my own mail server says this:

```sh
# telnet mail.example.com 25                                                                                                                                           
Trying 51.15.x.x...
Connected to mail.example.com.
Escape character is '^]'.
220 mail.example.com ESMTP Hi, I'm a Mail-in-a-Box (Ubuntu/Postfix; see https://mailinabox.email/)
EHLO localhost
250-mail.example.com
250-PIPELINING
250-SIZE 134217728
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
```

The value given in the `SIZE` capability is 128 megabytes.

**Comment by marcnyc2001** [comment]
I found this post while researching a problem I was having myself and just found out that Gmail has a character limit of 10'000, so if you are doing your tests using a Gmail address that might be your issue... I now use `$mail->MsgHTML(substr($body,0,9000).' [...]');` to make sure I stay way below the Gmail limit...
