### ISSUE TITLE
Connection failed. Error #2

### ISSUE THREAD

**Issue by endhold** [PHPMailer/PHPMailer#1472]
hi! I know this question has been answered many times (Godaddy & smtp) but I have no idea to solve this.
FYI I am using Linux hosting with cpanel. 

```
<?php
// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

require_once 'PHPMailer/src/PHPMailer.php';
require_once 'PHPMailer/src/SMTP.php';

$mail = new PHPMailer(true); // Passing `true` enables exceptions
try {
    //Server settings
    $mail->SMTPDebug = 3; // Enable verbose debug output
    $mail->isSMTP(); // Set mailer to use SMTP
    $mail->Host = 'relay-hosting.secureserver.net'; // Specify main and backup SMTP servers
    $mail->SMTPAuth = false; // Enable SMTP authentication
    $mail->Username = ''; // SMTP username
    $mail->Password = ''; // SMTP password
    $mail->SMTPSecure = false; //'ssl'; //'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 25; //587;                                    // TCP port to connect to

    //Recipients
    $mail->setFrom('test@mydomain.com', 'no-name');
    $mail->addAddress('recipient@otherdomain.com', 'John Doe'); // Add a recipient

    //Content
    $mail->isHTML(true); // Set email format to HTML
    $mail->Subject = 'Here is the subject';
    $mail->Body = 'This is the HTML message body <b>in bold!</b>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    $mail->send();
    echo 'Message has been sent';
} catch (Exception $e) {
    echo 'Message could not be sent. Mailer Error: ', $mail->ErrorInfo;
}
```
```
Connection: opening to relay-hosting.secureserver.net:25, timeout=300, options=array()
Connection failed. Error #2: stream_socket_client(): unable to connect to relay-hosting.secureserver.net:25 (Connection refused)
SMTP ERROR: Failed to connect to server: Connection refused (111)
```

**Comment by Synchro** [comment]
As far as I know, you're doing everything right here if you want to use SMTP - I would ask GoDaddy support. Alternatively, I think that they provide a local mail server on shared hosting, so you could try using `isMail()` instead of `isSMTP()`. Alternatively, switch ISPs - scaleway are very cheap and you can get them to allow SMTP directly.

**Comment by slanden** [comment]
I've struggled with this and Godaddy support as well, and we use gmail also. I finally came across a post on SO with these options: `$mail->SMTPAutoTLS = false;` and `$mail->Host = 'localhost';`. Unfortunately, I accidentally exited out of the tab to that post so I cannot offer explanation or credit the poster :/

Here's a test script that works for me:
`<?php

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\OAuth;
use League\OAuth2\Client\Provider\Google;

//SMTP needs accurate times, and the PHP time zone MUST be set
//This should be done in your php.ini, but this is how to do it if you don't have access to that
date_default_timezone_set('America/Chicago'); // your timezone

require './vendor/autoload.php';

$mail = new PHPMailer;
$mail->isSMTP();
$mail->SMTPDebug = 3;
$mail->Host = 'localhost'; //'relay-hosting.secureserver.net' didn't work
$mail->Port = 25;
$mail->SMTPAuth = false;
$mail->SMTPSecure = false;
$mail->SMTPAutoTLS = false;


$mail->setFrom('test@mydomain.com', 'no-name'); // Add a sender
$mail->addAddress('recipient@otherdomain.com'); // Add a recipient
$mail->isHTML(true);                      // Set email format to HTML
$mail->Subject = 'Test Email';
$mail->Body    = 'Some <b>body</b>';
$mail->CharSet = 'utf-8';
$mail->AltBody = 'alt body';

//send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    //http_response_code(204);
}`

**Comment by Synchro** [comment]
Fairly likely I wrote that :) That is indeed a correct config for sending via a local mail server without using auth or encryption. It's probably SMTPAutoTLS that was causing a problem - if the server running on localhost offers STARTTLS, PHPMailer will try to use it - but it will always fail with a host name mismatch; this is why you can turn it off.

**Comment by slanden** [comment]
Oh good, then thanks for that haha. The only thing that is somewhat bothersome is that it takes a lot longer for emails to go through. Well, as opposed to not going through at all it's great but it does take a few minutes to show up in an inbox..

**Comment by ItsJustATypo** [comment]
The solution posted by Slanden worked for me, as well.

**Comment by MachinePereere** [comment]
> 
> 
> I've struggled with this and Godaddy support as well, and this is working using a gmail account as the `From` account. I finally came across a post on SO with these options: `$mail->SMTPAutoTLS = false;` and `$mail->Host = 'localhost';`. Unfortunately, I accidentally exited out of the tab to that post so I cannot offer explanation or credit the poster :/
> 
> Here's a test script that works for me:
> 
> ```
> isSMTP();
> $mail->SMTPDebug = 3;
> $mail->Host = 'localhost'; //'relay-hosting.secureserver.net' didn't work
> $mail->Port = 25;
> $mail->SMTPAuth = false;
> $mail->SMTPSecure = false;
> $mail->SMTPAutoTLS = false;
> 
> 
> $mail->setFrom('test@mydomain.com', 'no-name'); // Add a sender
> $mail->addAddress('recipient@otherdomain.com'); // Add a recipient
> $mail->isHTML(true);                      // Set email format to HTML
> $mail->Subject = 'Test Email';
> $mail->Body    = 'Some body';
> $mail->CharSet = 'utf-8';
> $mail->AltBody = 'alt body';
> 
> //send the message, check for errors
> if (!$mail->send()) {
>     echo "Mailer Error: " . $mail->ErrorInfo;
> } else {
>     //http_response_code(204);
> }
> ```

Thanks. Your approach worked and saved me a lot of time

**Comment by Kirti003Shukla** [comment]
> $mail->SMTPAutoTLS = false;

Had same issue with the GoDaddy server and applied the same. Thanks
