### ISSUE TITLE
PHPMailer don't work for IP type smtp.

### ISSUE THREAD

**Issue by codersaiful** [PHPMailer/PHPMailer#1474]
Actually I have developed a Responders by PHP for mail sending our customer. In that case, I have purchased smpt which like 111.22.3.44
But this smtp is not working to my Application, Even I tried at outside from my application only by Core PHPMailler. But it's not working.

Someone can say, SMTP info is not right, for your kind information, I have an another Software, where this IP type smtp is working.

Can anybody tell me, how can I solve this issue.
Thanks

**Comment by Synchro** [comment]
PHPMailer works fine to literal IPv4 (and IPv6) addresses. You should do it like this:

    $mail->Host = '111.22.3.44';

However, you will not be able to use encryption to that because it will not match a host name in a certificate. You would need to get a domain name point it at that IP, then get a cert for the domain.

**Comment by codersaiful** [comment]
I mean: Domain name is must. Right?
Because I also written 
`$mail->Host = '111.22.3.44';`
But not working.
By the way, Thanks a lot for your confirmation.

**Comment by Synchro** [comment]
You need to explain more what you mean by "not working". What does your SMTP debug output look like (with `SMTPDebug = 2`)?

**Comment by codersaiful** [comment]
Ok, I will explain more. Let me to find it. Actually I was working on my
office. Tomorrow I will explain more details.
Thanks
