### ISSUE TITLE
how to get info phpmailer get debug after send

### ISSUE THREAD

**Issue by radenvodka** [PHPMailer/PHPMailer#1487]
how to get info phpmailer get debug after send ?

**Comment by Synchro** [comment]
You enable debug output with `SMTPDebug`, generally 2 provides enough info unless you have connectivity problems. If you want to capture that output, [inject a closure into the `Debugoutput` property](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L359) that stores it somewhere you can get at it later, like this:

    $mail->Debugoutput = function($str, $level) {global $debug; $debug .= "debug level $level; message: $str";};

After you have called `send()`, the global variable `$debug` will contain all the debug output.
