### ISSUE TITLE
DKIM signature fail -> data too small

### ISSUE THREAD

**Issue by Seeryos** [PHPMailer/PHPMailer#1489]
Hi everyone,
It's been two days since I look for a solution without success. Before finishing totally bald, I would like to ask for your help.

**# Problem description**

I try to validate my email sent since the last version of phpmailer through the tool: dkimvalidator.com then mail-tester.com becomes paid from a certain number of mails per day.

On these two tools the problem is always the same: The DKIM signature fails.

And for good reason, when I analyze the message received since phpmailer I get:

`DKIM Signature

Message contains this DKIM Signature:
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; l=502; s=mail;
	t=1530774785; c=relaxed/simple;
	h=From:To:Date:Subject;
	d=app.mydomain.fr; i=support@app.mydomain.fr;
	z=From:=20mydomain=20
	|To:=20ur27t7OTfwKT53@dkimvalidator.com
	|Date:=20Thu,=205=20Jul=202018=2009:13:05=20+0200
	|Subject:=20Test=20;
	bh=yJWoFbV+po2vk6JAqEOEvi/+GxPIgLAYMtkBQVLgQJU=;
	b=

Signature Information:
v= Version:         1
a= Algorithm:       rsa-sha256
c= Method:          relaxed/simple
d= Domain:          app.mydomain.fr
s= Selector:        mail
q= Protocol:        dns/txt
bh=                 yJWoFbV+po2vk6JAqEOEvi/+GxPIgLAYMtkBQVLgQJU=
h= Signed Headers:  From:To:Date:Subject
b= Data:            
Public Key DNS Lookup

Building DNS Query for mail._domainkey.app.mydomain.fr
Retrieved this publickey from DNS: v=DKIM1; k=rsa; t=s; s=email; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDAYRSBjm+M/g483yCtwAuuKuCQwnLPLS3s0hfr6cASM8QaKS5V8tAXs2BrJvAUbuf7EIOKO8S/0HhVxpxT6aEO5vbh0U1nwp+rIzl/aPq+MC+7RBT+IHePbyxuzSfw3DRCOToFUi+fsYq1i0QjVJ2cBFR/BTTKk+4HzZfWfXrJ+QIDAQAB
Validating Signature

result = fail
Details: OpenSSL error: data too small for key size`

So, b field (data) is empty ! And I don't understand why. I enabled the openssl extension on my php configuration.

**# Code to reproduce**

My code : 

`

		$mail = new PHPMailer\PHPMailer\PHPMailer();
		$mail->Priority = 3;
		$mail->From = 'support@app.mydomain.fr';
		$mail->Sender = 'support@app.mydomain.fr';
		$mail->FromName = 'mydomain';
		$mail->DKIM_domain = 'app.mydomain.fr';
		$mail->DKIM_private = '/var/dkim/dkim.private';
		$mail->DKIM_selector = 'mail';
		$mail->DKIM_passphrase = '';
		$mail->DKIM_identity = $mail->From;
		$mail->Encoding = "base64";
		$mail->AddAddress('ur27t7OTfwKT53@dkimvalidator.com');
		$mail->Subject = 'Test';
		$mail->IsHTML(TRUE);
		$mail->CharSet = "text/html; charset=UTF-8;";
		$mail->Body = '<html><body><p>Message de test en html</p></body></html>';
		$mail->AltBody = "Message de test en HTML";
		$mail->Send();

`

Email is send like a charm but DKIM not valid. Thank you so much !

**Comment by Seeryos** [comment]
Hi again : 

I tried to regenerate my key using this commands : 

openssl genrsa -out private.key 1024
openssl rsa -in private.key -pubout -out public.key

But same problem ... 

result = fail
Details: OpenSSL error: data too small for key size

**Comment by Synchro** [comment]
I'm not sure exactly why this is failing for you, but you should definitely use 2048-bit DKIM keys, not 1024.

**Comment by Seeryos** [comment]
Ok thanks. I just generate a new 2048 private key. 
I ask me if my problem come from of the rights on my private file... 
-rw------- 1 root root 1679 juil. 12 11:57 private.key

The apache user is www-data.

What do you think about it ?

**Comment by Synchro** [comment]
If your PHP script is going to use the private key, it needs to be able to read it, and if it's running as www-data it won't be able to read that one. You can do that either by running your script as a different user (that can read the key), or alter the permissions on the private key so that the apache user can read it. The former approach is more secure.

**Comment by Seeryos** [comment]
It works !!! Thank you very much... 
Now, I have to correct a last error to pass my score to 10/10 :) 

`-1.274 | RDNS_NONE | Delivered to internal network by a host with no rDNS`
Google is my friend. 

Thank you again.

**Comment by Usernameisalreadytaken5** [comment]
**Same issue solved today after 2 years before postfix was add dkim**

in my case PHP was in chroot + Selinux and randomnumber generator was fucked UP by ssl 

> /chroot/dev/random and /chroot/dev/urandom => need generate random numbers 
> check for Selinux error:  cat /var/log/messages | grep "SELinux is preventing"


https://stackoverflow.com/a/57977815/979474
