### ISSUE TITLE
Read email sent from phpmailer on Android

### ISSUE THREAD

**Issue by alefraser** [PHPMailer/PHPMailer#1490]
Hi, i have some problem when i send a HTML email with phpmailer. When we try to read the email on a smartphone samsung the email are cut at the middle and we can't see nothing after.

I try the same thing on iphone and windows and is working well. Someone have idea for that ?

**Comment by Synchro** [comment]
I don't know, but I'd check this by building innocuous example content (with no complex layout styling) and gradually increasing its size until you find the issue. I would guess that it's more likely to be a styling issue than a content size problem, but for example I have seen iOS download half a message and then offer to download the rest later.
