### ISSUE TITLE
Dkim brokes when i add "message ID" in tag "h"

### ISSUE THREAD

**Issue by MaxLucky** [PHPMailer/PHPMailer#1491]
Dkim brokes when i add "message ID" in tag "h". I am using exim. In file i wrote $mail->MessageID = "";

Before:
![before](https://user-images.githubusercontent.com/81561/42417307-4b76ba44-8287-11e8-90a4-fb8a2f39a0cb.png)
After:
![after](https://user-images.githubusercontent.com/81561/42417310-4f17e89e-8287-11e8-87b6-b19d103c5f42.png)

what could be the problem?

**Comment by Synchro** [comment]
How are you adding to the h tag?

**Comment by MaxLucky** [comment]
PHPMailer.php

line 4022

**Comment by Synchro** [comment]
There's not enough to go on here. That line number is in the middle of finding MIME types. For debugging DKIM, I'd recommend using the master branch version which has some extra DKIM, see PR #1468 for further info.

**Comment by MaxLucky** [comment]
Сan you give more details? What exactly is necessary to write in my case?

**Comment by gwi-mmuths** [comment]
@MaxLucky you can check https://github.com/PHPMailer/PHPMailer/blob/master/examples/DKIM_sign.phps.

At the moment it's not possible to add message-id. Using current master supports adding custom header only.
