### ISSUE TITLE
Invalid address using PHPMailer!!!

### ISSUE THREAD

**Issue by kunalvirk** [PHPMailer/PHPMailer#1492]
Hey there,

I want to add email addresses via variable, it is giving me the following error :
`Uncaught PHPMailer\PHPMailer\Exception: Invalid address: (addAnAddress to):`
`PHPMailer\PHPMailer\Exception: Invalid address: (addAnAddress to)`
`Invalid address: (addAnAddress to): `

When assigning manually, it is working fine.

What I'm trying to do is I'm fetching some user's email address and want to send them mail from a dynamically set primary email id (which is also being fetched via db).

Can you please help me here?

Thanks in advance.

**Comment by Synchro** [comment]
Please show what's in the variable.

**Comment by kunalvirk** [comment]
My variables look something like this :

Storing my fetched emails in vars :
$email1 = "example@example.com";
$email2 = "example2@example.com";

then combining them in a variable like below :
`$to = $email1." , ";
$to .= $email2." , ";`

And now for addAddress I'm using the above like this: 
$addresses = explode(',', $to);                
foreach ($addresses as $address) {
$mail->addAddress($address);
}

Also, the setFrom is set like this:
$mail->setFrom($results->EmailId);

Thanks for the reply buddy 👍

**Comment by Synchro** [comment]
Don't assume it's right, check:

```php
$addresses = explode(',', $to);                
foreach ($addresses as $address) {
    var_dump($address, $mail->addAddress($address));
}
```

**Comment by kohgaywee2015** [comment]
Is your email really email or something I don't know.

**Comment by kohgaywee2015** [comment]
Also, could there be a blank end of array?

**Comment by kohgaywee2015** [comment]
for this,
$to = $email1." , "; $to .= $email2." , ";
it should become this,
$to = $email1." , "; $to .= $email2;

**Comment by alec-w** [comment]
@kohgaywee2015  is right. The code
`$to = $email1.","; $to .= $email2.",";
$addresses = explode(',', $to);`
will result in the last element of `$addresses` being an empty string.
Instead do
`$to = $email1 . ',';
$to .= $email2';
$addresses = explode(',', $to);`

**Comment by Hackinet** [comment]
Why hasn't this issue been closed yet??
