### ISSUE TITLE
First time installation with GoDaddy

### ISSUE THREAD

**Issue by shaunrc493** [PHPMailer/PHPMailer#1497]
Ok, I'll try that again.

I'm using GoDaddy's Ultimate Linux Hosting with cPanel after recently moving away from 000webhost. Now 000webhost allowed me to use very very basic PHP mail() functions to send emails like no tomorrow. I was blasting them out left right and centre until I hit the daily email limit. No errors, no spam, no problems!

Since moving to GoDaddy I haven't been able to send a single email using PHP. I've contacted GoDaddy about this and found that there was an issue with the MX entry, so we went ahead and fixed that. After waiting the required 48 hours I still wasn't able to send emails through PHP, so I've been trying all sorts of new things.

I've stumbled across this GitHub project a few times but I thought it was a little too much to add into the website to simply test small emails (troubleshooting whether the issue was my client/server/host). I've tried to install this project but honestly, I'm struggling.

I thought I was just getting the hang of web dev now that I've finished my Level 5 in Computer Technologies but for some reason I can't get my head around everything that needs doing to add this to an existing project, where and how to download each component, and get a simple testing script up and running.

Would anyone be able to help out with my problems? I know that there is a guide on how to install this project, which I've been through, but still not able to get things working.

**Comment by Synchro** [comment]
This is a GoDaddy documentation issue, not a PHPMailer problem. The problem is that GoDaddy blocks outbound SMTP to external hosts, so you must use either the PHP `mail()` function (which PHPMailer uses by default) which sends through a local mail server (i.e. on the machine your script is running on), which should be pre-configured if you're using shared hosting, *or* use SMTP to send via GoDaddy's internal SMTP servers *without auth or encryption*. As far as I'm aware, this config should work:

```php
$mail->isSMTP();
$mail->Host = 'relay.secureserver.net';
$mail->SMTPAuth = false;
$mail->SMTPSecure = false;
$mail->SMTPAutoTLS = false;
```

**Comment by shaunrc493** [comment]
Where about's is this going?

**Comment by Synchro** [comment]
With your other PHPMailer code - start with one of the examples, like the one in the readme, and change or add those lines.

**Comment by shaunrc493** [comment]
As per my opening post, I'm not able to install this project, so changing code is irrelevant at this point.

**Comment by Synchro** [comment]
Define "not able to install". If you can upload files, that's all there is to it.

**Comment by Synchro** [comment]
Have you considered reading the readme which tells you how to load files manually with or without composer? If you can't run composer on your host, run it locally, where it will generate the vendor folder and autoload script, then upload the whole lot. Download composer from [here](https://getcomposer.org).

**Comment by shaunrc493** [comment]
Yes I read through the README file several times to make sure I had everything right but I still wasn't able to get it to work.

So, as stated in the 'Minimal Installation',

"At the very least you will need src/PHPMailer.php."

Can I put this into the public_html and still call it from anywhere without any additional steps which haven't been mentioned?

**Comment by Synchro** [comment]
Yes. You can put it wherever you like, and then load it with a `require` to the path you put it in. If you're using SMTP (as I suggested above) you will also need the SMTP class, loaded in the same way. As soon as you get beyond loading 1 external class, it's simpler to use composer.
