### ISSUE TITLE
mail sending issue

### ISSUE THREAD

**Issue by balajibpa** [PHPMailer/PHPMailer#1500]
Final-Recipient: rfc822; admin@jarvisautomation.co.in
Action: failed
Status: 4.0.0
Diagnostic-Code: smtp; DNS Error: 1965958 DNS type 'mx' lookup of jarvisautomation.co.in responded with code NOERROR
 1965958 DNS type 'mx' lookup of jarvisautomation.co.in had no relevant answers.
 1965958 DNS type 'aaaa' lookup of jarvisautomation.co.in responded with code NOERROR
 1965958 DNS type 'aaaa' lookup of jarvisautomation.co.in had no relevant answers.
 1965958 DNS type 'a' lookup of jarvisautomation.co.in responded with code NOERROR
 1965958 DNS type 'a' lookup of jarvisautomation.co.in had no relevant answers.
Last-Attempt-Date: Wed, 18 Jul 2018 10:54:19 -0700 (PDT)

**Comment by Synchro** [comment]
Your DNS is broken. Fix it and your script will be able to work.

**Comment by balajibpa** [comment]
Adding mx to my nameserver(aws) is beeing the problem and now added and
problem is solved now
