### ISSUE TITLE
Unable to send Email, not sure why???

### ISSUE THREAD

**Issue by asinan007** [PHPMailer/PHPMailer#1502]
Hi,
I've been having this problem constantly every now and then. It says "blacklisted"/"blocked" but my service provider (hosting company) says its not blocked.
I have checked everything on my side and even on the scripting side. Below is the Error I receive, when i set $mail->SMTPDebug = 4.

> 2018-07-20 20:28:31 Connection: opening to ssl://box839.bluehost.com:465, timeout=300, options=array ()<br>
2018-07-20 20:28:31 Connection: opened<br>
2018-07-20 20:28:31 SMTP -&gt; get_lines(): $data is &quot;&quot;<br>
2018-07-20 20:28:31 SMTP -&gt; get_lines(): $str is  &quot;550-Message rejected because [66.147.244.139]:16741 is blacklisted see Blocked&quot;<br>
2018-07-20 20:28:31 SMTP -&gt; get_lines(): $data is &quot;550-Message rejected because [66.147.244.139]:16741 is blacklisted see Blocked&quot;<br>
2018-07-20 20:28:31 SMTP -&gt; get_lines(): $str is  &quot;550 - Too many failed logins&quot;<br>
2018-07-20 20:28:31 SERVER -&gt; CLIENT: 550-Message rejected because [66.147.244.139]:16741 is blacklisted see Blocked550 - Too many failed logins<br>
2018-07-20 20:28:31 CLIENT -&gt; SERVER: EHLO www.cruise-maldives.com<br>
2018-07-20 20:28:31 SMTP -&gt; get_lines(): $data is &quot;&quot;<br>
2018-07-20 20:28:31 SMTP -&gt; get_lines(): $str is  &quot;&quot;<br>
2018-07-20 20:28:31 SERVER -&gt; CLIENT: <br>
2018-07-20 20:28:31 SMTP ERROR: EHLO command failed: <br>
2018-07-20 20:28:31 SMTP NOTICE: EOF caught while checking if connected<br>
2018-07-20 20:28:31 Connection: closed<br>
SMTP Error: Could not authenticate.<br>
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting<br>

Below is my code;

`
                    //Create a new PHPMailer instance
                    $mail = new PHPMailer;

                    $mail->isSMTP();
                    $mail->SMTPDebug = 4;
                    $mail->Host = 'box839.bluehost.com';
                    $mail->SMTPAuth = true;
                    $mail->Username = $senderEmail;
                    $mail->Password = $sender_email_pass;
                    $mail->SMTPSecure = 'ssl';
                    $mail->Port = 465;

                    //Set who the message is to be sent from
                    $mail->setFrom($senderEmail, $senderName);
                    //Set an alternative reply-to address
                    $mail->addReplyTo($senderEmail, $senderName);
                    //Set who the message is to be sent to
                    $mail->addAddress($contact_email, $contact_name);
                    //Set the subject line
                    $mail->Subject = $emailSubject;
                    $mail->isHTML(true);                                  // Set email format to HTML
                    $mail->Body = $messageBodyToRequester;
                    $mail->send();`

Need Help on this URGENTLY.

**Comment by Synchro** [comment]
When it says:

> Message rejected because [66.147.244.139]:16741 is blacklisted see Blocked

That means it's blacklisted & blocked. Your ISP is wrong, and it's nothing to do with your script.

It's common for this to happen on shared hosting; you can end up with an IP that was previously used by a spammer, and appears in blacklists Solution: don't use crappy cheap hosting..

**Comment by asinan007** [comment]
Yeah I can understand that, but i could send mail to the same add via outlook or gmail. and i could ping to box839.bluehost.com as well... i am not sure if that is suppose to happen or not if its blocked. So how do i check if the IP is blacklisted or blocked, so i can show to the hosts that its blocked. AND how long does it take this block to be removed.

**Comment by Synchro** [comment]
It’s bluehost that is blocking 66.147.244.139. Mxtoolbox only checks a few public blacklists. How you get off their list, and which IPs are listed I have no idea about - it is not a PHPMailer issue - it is specific to your particular hosting, nothing to do with PHP.

**Comment by asinan007** [comment]
Also it worked well when i removed whole of this bunch
`$mail->isSMTP();
$mail->SMTPDebug = 4;
$mail->Host = 'box839.bluehost.com';
$mail->SMTPAuth = true;
$mail->Username = $senderEmail;
$mail->Password = $sender_email_pass;
$mail->SMTPSecure = 'ssl';
$mail->Port = 465;`

and replaced it with;
`$mail->Host = 'mail.cruise-maldives.com';`

And they still say its an scripting issue

**Comment by Synchro** [comment]
If you comment out isSMTP it means your Host value will be ignored, and you will be sending via your local mail server. This may just mean that your delivery gets blacklisted later on in the delivery chain, but again, the blacklist is not caused by your script.

Marcus
