### ISSUE TITLE
PHPMailer : 500 Internal Server Error, crashes on stream_socket_client

### ISSUE THREAD

**Issue by Waruj** [PHPMailer/PHPMailer#1505]
I want to send mail by using smtp. It works fine when I use in development site but after deploy to production site I got 500 internal Server Error.  

below is my code. 

`include('../phpmailer/PHPMailerAutoload.php');

$mail = new PHPMailer();

$mail->isSMTP();
$mail->SMTPDebug = 2;

$mail->From = 'webmaster@example.com';
$mail->FromName = 'example.com';
$mail->CharSet = 'UTF-8';

$mail->Host = 'mail.example.com';   
$mail->SMTPAuth = true;                     
$mail->Username = 'webmaster@example.com';               
$mail->Password = 'examplepassword';	
						
$mail->AddAddress("mymail@gmail.com");
$mail->Subject = "TEST SUBJECT";
$mail->Body = "TEST BODY";
$mail->IsHTML(true);
				
if($mail->Send()){
	echo json_encode(array("result"=>1,'msg'=>"Send Mail Success")); exit;
}else{
	echo json_encode(array("result"=>2,"msg"=>'CANNOT SEND MAIL '.$mail->ErrorInfo)); exit;
}
`
PHPMailer loads a while and then show 500 Internal Server Error.
After debugging, I found that it crashes in class.smtp.php on below line.

`$this->smtp_conn = @stream_socket_client(
                $host . ":" . $port,
                $errno,
                $errstr,
                $timeout,
                STREAM_CLIENT_CONNECT,
                $socket_context
 );`

I have searched for any solution but didn't find about this case. Could you please help me to find out what happen ?​ 

Thank you so much.

**Comment by Synchro** [comment]
It's timing out on your network connection, suggesting that your ISP is blocking outbound SMTP. Read the troubleshooting guide which tells you how to diagnose connection errors.
