### ISSUE TITLE
Facing issue with Recipients email showing on gmail

### ISSUE THREAD

**Issue by rescue1155** [PHPMailer/PHPMailer#1509]
Hi There,

I am facing an error with phpmailer 6.0.5, when i set the setFrom().

//Recipients
$mail->setFrom('info@domain.com', 'Testing Domain');

I have to show the sender: info@domain.com Instead its showing my real gmail address.

While in old versions, it was working perfectly. Could you please help me to setup this, So my real gmail email not show to others.

Thanks

**Comment by Synchro** [comment]
This is a gmail limitation. Gmail does not allow you to set arbitrary from addresses, though you can use predefined aliases in gmail settings. If you try to use arbitrary addresses, it will simply use your account address instead, as you're seeing.
