### ISSUE TITLE
    require '../vendor/autoload.php';

### ISSUE THREAD

**Issue by Theolodewijk** [PHPMailer/PHPMailer#1510]
Example please no vendor!

**Comment by Synchro** [comment]
Read the readme, which tells you which classes you need to load manually.

**Comment by Theolodewijk** [comment]
Okay a exaple well be nice!

**Comment by Theolodewijk** [comment]
Fatal error: Cannot declare class PHPMailer\PHPMailer\PHPMailer, because the name is already in use in /home/theolodewijk/domains/theolodewijk.nl/plugins/phpmailer/src/PHPMailer.php on line 31

function mailclass($from_name, $from_email, $to_name, $to_email, $mail_subject, $mail_message, $Priority) {
    # Email priority (1 = High, 3 = Normal, 5 = low)
    global $system_from_name, $system_from_email, $db, $remote_addr;

    require '../plugins/phpmailer/src/PHPMailer.php';
    require '../plugins/phpmailer/src/SMTP.php';

    $mail = new PHPMailer\PHPMailer\PHPMailer;

    $mail->AddReplyTo($from_email, $from_name);
    $mail->AddAddress($to_email, $to_name);
    $mail->SetFrom($system_from_email, $system_from_name);
    $mail->Priority = $Priority;
    $mail->Subject  = $mail_subject;
    $mail->AltBody  = "To view the message, please use an HTML compatible email viewer!";
    $mail->MsgHTML($mail_message);
    //$mail->Send();
    if (isset($_FILES['uploaded_file']) && $_FILES['uploaded_file']['error'] == UPLOAD_ERR_OK) {
        $mail->AddAttachment($_FILES['uploaded_file']['tmp_name'], $_FILES['uploaded_file']['name']);
    }

    if(!$mail->Send()) {
        $rapport = "Mailer Error: " . $mail->ErrorInfo;
    } else {
        $rapport = "Message sent!";
    }

    try {
        $sql = "INSERT INTO systeemmails (sender, receiver, remote_addr, subject, message, rapport) VALUES (:sender, :receiver, :remote_addr, :subject, :message, :rapport)";
        $sql = $db->prepare($sql);
        $sql->execute(array('sender' => $from_name.' <'.$from_email.'>', 'receiver' => $to_name.' <'.$to_email.'>', 'remote_addr' => $remote_addr, 'subject' => $mail_subject, 'message' => $mail_message, 'rapport' => $rapport));
    } catch(PDOException $e) {
        echo '<pre>';
        echo 'Regel: '.$e->getLine().'<br>';
        echo 'Bestand: '.$e->getFile().'<br>';
        echo 'Foutmelding: '.$e->getMessage();
        echo '</pre>';
    }
}

**Comment by Theolodewijk** [comment]
I see, in a function not possbale ? 

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

**Comment by Synchro** [comment]
No. `use` statements are always scoped to a file, and apply everywhere within that file, so it's normal to put them at the top, before any scripting or function definitions. Also remember that they are optional and effectively cosmetic - they just help to reduce the amount of code you have to write, so you can write `PHPMailer` instead of a fully-qualified `PHPMailer\PHPMailer\PHPMailer`. The point of namespacing is to remove ambiguity - so you can be clear that you want to use `PHPMailer\PHPMailer\PHPMailer` and not some other `Foo\Bar\PHPMailer` implementation that the name might clash with.

**Comment by Theolodewijk** [comment]
Thanks, is this corect? I have test it and for now it seems to work

`use PHPMailer\PHPMailer\PHPMailer;
#use PHPMailer\PHPMailer\Exception;

require '../plugins/phpmailer/src/PHPMailer.php';
#require '../plugins/phpmailer/src/SMTP.php';

function mailclass($from_name, $from_email, $to_name, $to_email, $mail_subject, $mail_message, $Priority) {
    # Email priority (1 = High, 3 = Normal, 5 = low)
    global $system_from_name, $system_from_email, $db, $remote_addr;

    //Create a new PHPMailer instance
    $mail = new PHPMailer;
    //Set who the message is to be sent from
    $mail->SetFrom($system_from_email, $system_from_name);
    //Set an alternative reply-to address
    $mail->AddReplyTo($from_email, $from_name);
    //Set who the message is to be sent to
    $mail->AddAddress($to_email, $to_name);
    // mail Priority
    $mail->Priority = $Priority;
    //Set the subject line
    $mail->Subject  = $mail_subject;
    //Read an HTML message body from an external file, convert referenced images to embedded,
    //convert HTML into a basic plain-text alternative body
    $mail->MsgHTML($mail_message);
    //Replace the plain text body with one created manually
    $mail->AltBody = 'This is a plain-text message body (To view the message, please use an HTML compatible email viewer!)';

    //send the message, check for errors
    if(!$mail->Send()) {
        $rapport = "Mailer Error: " . $mail->ErrorInfo;
    } else {
        $rapport = "Message sent!";
    }

    if (isset($_FILES['uploaded_file']) && $_FILES['uploaded_file']['error'] == UPLOAD_ERR_OK) {
        $mail->AddAttachment($_FILES['uploaded_file']['tmp_name'], $_FILES['uploaded_file']['name']);
    }


    try {
        $sql = "INSERT INTO systeemmails (sender, receiver, remote_addr, subject, message, rapport) VALUES (:sender, :receiver, :remote_addr, :subject, :message, :rapport)";
        $sql = $db->prepare($sql);
        $sql->execute(array('sender' => $from_name.' <'.$from_email.'>', 'receiver' => $to_name.' <'.$to_email.'>', 'remote_addr' => $remote_addr, 'subject' => $mail_subject, 'message' => $mail_message, 'rapport' => $rapport));
    } catch(PDOException $e) {
        echo '<pre>';
        echo 'Regel: '.$e->getLine().'<br>';
        echo 'Bestand: '.$e->getFile().'<br>';
        echo 'Foutmelding: '.$e->getMessage();
        echo '</pre>';
    }
}`

**Comment by Synchro** [comment]
That's mostly OK, though it still looks like you've based it on an obsolete example. Your method for adding an attachment is not safe; you need to apply `move_uploaded_file` or `is_uploaded_file`. See the  [send file upload example provided with PHPMailer](https://github.com/PHPMailer/PHPMailer/blob/master/examples/send_file_upload.phps) for how to do that correctly.

**Comment by Tejas-code-manager** [comment]
r

**Comment by Tejas-code-manager** [comment]
retf
