### ISSUE TITLE
Parse error: syntax error, unexpected 'use' (T_USE) in /home/theolodewijk/domains/theolodewijk.nl/conf/email.php on line 32

### ISSUE THREAD

**Issue by Theolodewijk** [PHPMailer/PHPMailer#1511]
Parse error: syntax error, unexpected 'use' (T_USE) in /home/***/domains/***/conf/email.php on line 32

**Comment by Theolodewijk** [comment]
![image](https://user-images.githubusercontent.com/9058326/43431312-8fb1ee8e-946d-11e8-82a5-ce4b8a3e65aa.png)

**Comment by Synchro** [comment]
The version of PHP you are running is too old to run the latest PHPMailer, which requires 5.5. Either downgrade to the old 5.2-stable branch, or preferably upgrade your PHP.

**Comment by Theolodewijk** [comment]
I am running PHP 7.1
