### ISSUE TITLE
Uncaught Error: Call to a member function addAddress() on null

### ISSUE THREAD

**Issue by Luberen** [PHPMailer/PHPMailer#1515]
```
$mail = new PHPMailer(true);
...
while ($buyerInfo = mysqli_fetch_array($sQryExec)) {
  $mail->addAddress("$buyerInfo[buyer_email]", "$buyerInfo[buyer_name]");
  ...
}
```
I put variables, that have data returned from database, to addAddress(), but PHPMailer throws error message "**Uncaught Error: Call to a member function addAddress() on null**".

There is no problem on database querying. How can I fix this?

**Comment by Synchro** [comment]
That's happening at the PHP level, not in PHPMailer - at some point between your creation of the PHPMailer instance and calling `addAddress`, `$mail` is being set to `null`, or going out of scope or something. You need to show the rest of your code.
