### ISSUE TITLE
How to view/set the user-agent?

### ISSUE THREAD

**Issue by khudvhfudgfjudfhdfhudfvhu** [PHPMailer/PHPMailer#1516]
So I've wasted countless hours searching, looking, asking and pulling my hair over this... I simply find no mention whatsoever of how you:

1. View the current User-Agent used by PHPMailer.
2. Set it to something else.

How is it done?!

**Comment by Synchro** [comment]
There is no common `User-Agent` header in email like there is in HTTP; I think you're mixing it up with the `X-Mailer` header, which you'll find in the docs and source code, and there is explicit support for it via the `XMailer` public property - see the source for its exact behaviour.
