### ISSUE TITLE
Extending with composer, but still get an error

### ISSUE THREAD

**Issue by Soetens** [PHPMailer/PHPMailer#1517]
`namespace VendurName\Email;

use \PHPMailer\PHPMailer\PHPMailer;
use \PHPMailer\PHPMailer\Exception;

class Email extends PHPMailer {  <-- line 17

    	public function __construct($exceptions, $body = '')
    	{

`

Error:
Fatal error: Class 'PHPMailer\PHPMailer\PHPMailer' not found in /var/www/vhosts/site.xyz/vendor/vendurname/email/src/Email.php on line 17

I'm probably missing something obvious, but what?

**Comment by Synchro** [comment]
Are you loading composer's autoloader before that? the `use` statement isn't enough to define the existence of the PHPMailer class, it just creates an alias.

**Comment by Soetens** [comment]
It was fixed by installing the 6.x version, the default composer 5.2 version does give the problems.

**Comment by Synchro** [comment]
Uh, the 5.2 branch doesn't have a namespace, but because you've told PHP to use the `PHPMailer\PHPMailer\PHPMailer` alias, it will never match the effective `\PHPMailer` class name that's used in 5.2.
