### ISSUE TITLE
Cannot declare class PHPMailer

### ISSUE THREAD

**Issue by artlemaks** [PHPMailer/PHPMailer#1523]
Hello,

I am getting an error while trying to use the PHPMailer class and I can't see why. I have taken the code from the Readme file that is included in the package. 

At the start of my file which is supposed to send the e-mail, I have the following lines:

`use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require './PHPMailer/src/PHPMailer.php';
require './PHPMailer/src/PHPMailer.php';
`

Then I have a function to generate a file that is to be attached to the e-mail. I wont post it here because that part works fine and there are no issues. Now, when trying to send the e-mail, my code looks like this:

`$bodytext = "Hello! Please find attached gross proift report from [site name] issues by [Username] on [date]. Please note, this e-mail was generated automatically. Please do not reply to this e-mail address.";
	//send e-mail with file 
	$email = new PHPMailer();
	$email->From      = 'no-reply@easycount.io';
	$email->FromName  = 'EasyCount';
	$email->Subject   = 'Gross Profit Report for {insert store name}';
	$email->Body      = $bodytext;
	$email->AddAddress( $email_address );

	$file_to_attach = "./tmp/Stock_Detail_".$current_date.".xls";

	$email->AddAttachment( $file_to_attach , 'GrossProfitReport.xls' );

return $email->Send();`

Unfortunately, this doesn't work. I am getting the following error:
`[Thu Aug 16 16:58:07.772448 2018] [cgi:error] [pid 41341] [client 86.42.180.192:58398] AH01215: PHP Fatal error:  Cannot declare class PHPMailer\\PHPMailer\\PHPMailer, because the name is already in use in /home/easycount/public_html/platformDev2/PHPMailer/src/PHPMailer.php on line 31: /usr/local/cpanel/cgi-sys/ea-php70, referer: https://easycount.io/platformDev2/myaccount.php
`
I have checked to see if other files might be using the PHPMailer function. I found another instance of it in old file system, removed it but no joy, still getting the same error. Where am I going wrong, as to me the code looks exact same as in the readme file.

**Comment by Synchro** [comment]
Uh, you’re requiring the PHPMailer class twice.
