### ISSUE TITLE
Problem using SMTP service

### ISSUE THREAD

**Issue by pwpx2** [PHPMailer/PHPMailer#1524]
Hi guys,
This is my 1st time using PHPMailer and i don't seem to make it work.
I've seen the examples and the tutorials and i've all blended them into this code for my registration page.

```
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require 'include/PHPMailer/src/Exception.php';
require 'include/PHPMailer/src/PHPMailer.php';
require 'include/PHPMailer/src/SMTP.php'; 
...................................................
snippet
 
 $mail = new PHPMailer;
 $mail->isSMTP();
$mail->SMTPDebug = 2;
 $mail->Host = 'smtp.xxxx.com';
$mail->SMTPAuth = true;
$mail->Username = 'xxxxx';
$mail->Password = 'xxxxxx';
$mail->SMTPSecure = 'tls';
$mail->Port = 687;
$mail->setFrom('xxxxxx', 'xxxxx');
$mail->addReplyTo('xxxxxx', 'xxxx');
$mail->addAddress($email);
$mail->Subject = "{$lang['takesignup_confirm']}";
$mail->isHTML(false);
$mail->Body = $body;
$mail->send();
 .................................
 snippet
?>
```

i cant see anything wrong in the logs, nothing is written about PHPMailer (if i could see i could debug the issue)
registration page is taking very long and eventually will give timeout
port 687 is open on my machine and on the smtp external server
using cloudflare
i've done a simple test page with default values only for this and its the same..page will give timeout

**Comment by Synchro** [comment]
The main problem is that when you "blended" them, you removed the error checking and error message output that the examples contain, and as a consequence you can't see what's going on. There's one obvious likely mistake - `Port = 687` should probably be `Port = 587`.

`SMTPDebug` often won't show much if your connection is failing altogether, and the most likely cause of that is either that wrong port number or that your hosting provider is blocking outbound SMTP, which is discussed in the troubleshooting guide.

**Comment by pwpx2** [comment]
fixed the issue.
