### ISSUE TITLE
DKIM + subject: DKIM-Result: fail (bad signature)

### ISSUE THREAD

**Issue by zdenekvecera** [PHPMailer/PHPMailer#1526]
Hello,

I'm sending an email with DKIM.

If I use this subject:

`Testt Aréna Komáaaa - rezervácie : a`

**DKIM is invalid**:

`DKIM-Result: fail (bad signature)`

If the colon (:) is at the end of the subject, **DKIM is valid**.

I used the version of PHPMailer from the current Master repository.

# Code to reproduce
```
$mail = new PHPMailer;
$mail->CharSet = "UTF-8";
$mail->setFrom('XXX', 'XXX');
$mail->addAddress('test-b724f17a@appmaildev.com', 'test-b724f17a@appmaildev.com');
$mail->Subject = 'Testt Aréna Komáaaa - rezervácie : a';
$mail->msgHTML('Ahoj');
$mail->AltBody = '';

//This should be the same as the domain of your From address
$mail->DKIM_domain = 'XXX';
//See the DKIM_gen_keys.phps script for making a key pair -
//here we assume you've already done that.
//Path to your private key:
$mail->DKIM_private = 'XXX';
//Set this to your own selector
$mail->DKIM_selector = 'XXX';
//Put your private key's passphrase in here if it has one
$mail->DKIM_passphrase = '';
//The identity you're signing as - usually your From address
$mail->DKIM_identity = $mail->From;
//Suppress listing signed header fields in signature, defaults to true for debugging purpose
$mail->DKIM_copyHeaderFields = false;
//Optionally you can add extra headers for signing to meet special requirements
$mail->DKIM_extraHeaders = ['List-Unsubscribe', 'List-Help'];

//When you send, the DKIM settings will be used to sign the message
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}
```

# Debug output
```
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; l=6; s=rezervacnisystemprolaserarenycz;
	t=1535087909; c=relaxed/simple;
	h=From:To:Date:Subject;
	d=laserarenakomarno.sk; i=neodpovedat@laserarenakomarno.sk;
	bh=w1BK14ne86WbcUFsEywJNsksGd+kc65zeiu1WFDKQeQ=;
	b=bTYKDDJWvVEQEk4TWcFBfx2yoMIxe/ZPl86gRcx2hjo+YOQ7ktVa7eK4NPMDzqTRWIWSfGIOS3n653G+3FOlO2mBV0QavtLjaFB4Dqijjw+COJLa/EFLQ0h1isycTB5nhPk9mNHXymf+/2zPgqfaLoz7JhzHPCwY2qIaMTQ5cQ0=
Signed-by: neodpovedat@laserarenakomarno.sk
Expected-Body-Hash: w1BK14ne86WbcUFsEywJNsksGd+kc65zeiu1WFDKQeQ=
Public-Key: v=DKIM1; h=sha256; t=s; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDsfkH3XCaYdKGoF3jTksbznv8GcFJVIfgsYX7+fVqNY4YzGkWURoL8ymT5hp4BISa6qU1gtmetekV9bGnTZkUSeDf64CWIj0kGZpLoBGRUydiWDJlnjtcycSa0ogER66JL+50t5C+ZpR/wJv+VR0HTzhpbeuHWQjkY7J5WV9w8AwIDAQAB;

DKIM-Result: fail (bad signature)
```

Report: 
[http://img.zdenekvecera.cz/report-b724f17a.txt](http://img.zdenekvecera.cz/report-b724f17a.txt)

**Comment by zdenekvecera** [comment]
My problem solved set STD_LINE_LENGTH = 255 (via `https://github.com/PHPMailer/PHPMailer/issues/1406#issuecomment-413933112`).

**Comment by zdenekvecera** [comment]
Hello, the problem is no longer. Webhosting updated some libraries on the server (I don't know what) and the problem disappeared. I am now set to STD_LINE_LENGTH = 76.

**Comment by oneprez** [comment]
Hello, I still have the same bug. I did 2 tests. The first with a short subject and the second with a longer subject. In the first case the DKIM signature is good and in the second test the DKIM signature is not good.
Below the test result on appmaildev.com:

DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; l=5626; s=2019011802;
	t=1553522308; c=relaxed/simple;
	h=From:To:Date:Subject;
	d=allprez.com; i=postmaster@allprez.com;
	bh=5RDb7EdDNTs4J0Gg8/eNLkSV0KV1ew8WJ11y+njU+tE=;
	b=AVNPD60QW4FxNzjMPPea8h4/Ym4fuGIRdc8CvsmQDGAO6/GZmOFfee/mYVjDysk7wZrzqxeWN+2ui7oCJkmd5ay15VVXf2Fq/hxkaZrXytYUnyonHlskAnSpzk+cPqt/YsSMw7GhM7QN/f/LK0L95MtAAExwgo4P04OICtu4V72xSaCRfUprygOjCYG95tUNcbA8ICxDDg6dOArzHXhXFOtRFwQ5Z4uZwnM/nRWpNKBFsZmILMwAGarNVjfuE58f54Sb+jbJOHFvzgAb3XiAvB7IKxbzS1KAM6kAO0Y1mvgkB4FZCgPV6/ZTKvVBwFvUXVIoC/5erfwQeyOW+/A93g==
Signed-by: postmaster@allprez.com
Expected-Body-Hash: 5RDb7EdDNTs4J0Gg8/eNLkSV0KV1ew8WJ11y+njU+tE=
Public-Key: v=DKIM1; h=sha256; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6OY4lmHyXzOQSBRa4GdYA68SY+Y+nTzli2q6zDMUE01zfRR8/PZBzcnQWSBOaQjliI8cFUt28BmCgImYLzqvlEpW8KNB3V+6ocHqXSZ7nQQ0AzPNJHqnFXHq6158JhbMk1bvcMxxR4sFvmoTp/rLOJwfntV3EDPSbpA9eqGLugPq/gxMa6QflpJRktH9A1SqJjaPj5oPy9zgYE/hz8YvOKr539IV9DbyIVYRGsx9bpi5n260nypDDikIKMCQ2NolqEddfXwfrZ7B7mdxIoGpHPXErD55NRTLIqUBI9BLWaV1QMNviEkfIZOLCt5BuNvBvlq4VK5CZk1f01ucbPtgzQIDAQAB;

DKIM-Result: fail (bad signature)
