### ISSUE TITLE
Send eml file

### ISSUE THREAD

**Issue by vjmartins** [PHPMailer/PHPMailer#1530]
Hi.
When I try to send an attachment - eml file - the message is sent however the received attachment is empty and the name is changed to something of the genre: filename.eml.eml. The extension is added automatically.

If you send a message with a pdf file I do not have any kind of problem.

It seems to be a PHPmailer error.

**Comment by vjmartins** [comment]
SMTP Debug

> 2018-08-28 10:28:40	CLIENT -> SERVER: 
2018-08-28 10:28:40	CLIENT -> SERVER: 
2018-08-28 10:28:40	CLIENT -> SERVER: --b2_1cff47715e718bb3bc5470718b4549ba-- 
2018-08-28 10:28:40	CLIENT -> SERVER: 
2018-08-28 10:28:40	CLIENT -> SERVER: --b1_1cff47715e718bb3bc5470718b4549ba 
2018-08-28 10:28:40	CLIENT -> SERVER: Content-Type: message/rfc822; name="1535451259176.eml" 
2018-08-28 10:28:40	CLIENT -> SERVER: Content-Transfer-Encoding: base64 
2018-08-28 10:28:40	CLIENT -> SERVER: Content-Disposition: attachment; filename=1535451259176.eml


I get a message with a MIME part like this:

> --_39226C9A-59A5-431D-9448-AB90857866E7_
> Content-Type: message/rfc822; name="1535451259176.eml.eml"
> Content-ID: ADE0C982B838894D9ADA79CC9AEEACDE@EURPRD10.PROD.OUTLOOK.COM
> Content-Transfer-Encoding: base64
> Content-Disposition: attachment; filename="1535451259176.eml.eml"
> 
> Q29udGVudC1UeXBlOiB0ZXh0L3BsYWluDQpNSU1FLVZlcnNpb246IDEuMA0KDQo=
> 
> --_39226C9A-59A5-431D-9448-AB90857866E7_--

VERSION = '6.0.5';

**Comment by Synchro** [comment]
OK, well that shows PHPMailer sending a correctly encoded message, but it looks like Outlook is corrupting it after receiving. I would expect this message to fail DKIM checks too. Are you sending it directly to outlook.com, or via some other server?

**Comment by vjmartins** [comment]
im using smtp.office365.com.

**Comment by Synchro** [comment]
One other way to test is to BCC to another non-MS address, such as gmail, and then compare the received messages (which should be identical apart from `received` + receiver-specific headers). This might give you some clues as to where exactly the corruption is occurring.

**Comment by vjmartins** [comment]
I use a gmail address in BCC.

MIME part from original recipient
> --_18B3B1F9-94C5-4D2C-ADE4-E2CE53F58681_
Content-Type: message/rfc822; name="1535452786283.eml.eml"
Content-ID: 1535452786283.eml
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="1535452786283.eml.eml"
Q29udGVudC1UeXBlOiB0ZXh0L3BsYWluDQpNSU1FLVZlcnNpb246IDEuMA0KDQo=
--_18B3B1F9-94C5-4D2C-ADE4-E2CE53F58681_--


MIME Part from gmail address
> --_58EAF677-58C5-4770-8258-1E4728BF08A0_
Content-Type: message/rfc822; name="1535452786283.eml"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="1535452786283.eml"
MIMEVersion10ContentTypetext/plaig==
--_58EAF677-58C5-4770-8258-1E4728BF08A0_--

**Comment by Synchro** [comment]
OK, so that proves that it's being done by Outlook, not PHPMailer. Not much I can do...

**Comment by vjmartins** [comment]
One last question: but why only happens with eml file and not with pdf?
