### ISSUE TITLE
SMTP connect Error 

### ISSUE THREAD

**Issue by nikhilmishra1998** [PHPMailer/PHPMailer#1535]
Hi,

i want to send email through my website but i got an issue that smtp connection is faile every time 
i had used the port tls 587 and ssl 465 but every time smtp connction failed please give me some idea to solve this issue 

code: 

```php
            require 'PHPMailer/PHPMailerAutoload.php';
                        $mail = new PHPMailer;
                        $name 			= $name;
			$InputEmail 	= $email;
			$InputContact 	= $_POST['number1'];
			$InputAddress 	= $_POST['city1'];
			$InputMessage 	= $_POST['message1']." is th message.";

			$mail->isSMTP();                                      // Set mailer to use SMTP
			//$mail->Host = 'bh-26.webhostbox.net';                       // Specify main and backup server
			$mail->SMTPDebug = 4;
			$mail->Host = 'mail.gmail.com';
			$mail->SMTPAuth = true;              // Enable SMTP authentication
			//$mail->SMTPSecure = false;                              
						   // SMTP password


			$mail->Username = 'blabla@gmail.com';              
			$mail->Password = 'xyz123@ddd';

			$mail->SMTPSecure = 'tls';                           
			$mail->Port = 587;                                    

			$mail->setFrom('blabla@gmail.com', 'bla');    
			$mail->addAddress('test@gmail.com','test');  

			$mail->WordWrap = 50;                                 // Set word wrap to 50 characters
			$mail->isHTML(true);                                  // Set email format to HTML

			$mail->Subject = 'User Details';
			$mail->Body    = '<table>'
					  .'<tr ><td width="150px">User Name: <b>'.$name.'</b></td></tr>'."\r\n"
					 .'<tr><td>User Email : <b><a href = \"#\">'.$InputEmail.'</a></b></td></tr>'."\r\n"
					 .'<tr><td>User Contact No. : <b>'.$InputContact.'</b></td></tr>'."\r\n"
					 .'<tr><td>User Message : <b>'.$InputMessage.'</b></td><tr>'."\r\n"
					 .'<tr><td>User Agent : <b>'.$user_agent.'</b></td></tr>'."\r\n"
					 .'</table>';
			if(!$mail->send()) {
			   echo 'Message could not be sent.';
			   echo 'Mailer Error: ' . $mail->ErrorInfo;
			   exit;
			}
			echo "Email Sent Successfully."; 
```

**Comment by Synchro** [comment]
@dextel2 You don't need parentheses when creating objects, and he's already got debug output enabled.

@nikhilmishra1998 You're using an old version of PHPMailer, and you've based your code on an obsolete example. Update to the latest version, and base your code on [the gmail example provided with PHPMailer](
https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail.php). your `Host` value doesn't look correct for gmail, so it may simply be that, but it could also be that your hosting provider blocks outbound SMTP, or that your CA certificates are outdated. Either way, read [the troubleshooting guide])
https://github.com/PHPMailer/PHPMailer/wiki/Troubleshootin)g which will tell you how to diagnose your problem.

**Comment by dextel2** [comment]
@Synchro Ahh... He's using legacy version, that's why no parenthesis..

**Comment by Synchro** [comment]
That makes no difference - PHP has never required parentheses for instance creation.

**Comment by nikhilmishra1998** [comment]
$mail = new PHPMailer() is not working.

same error is coming

**Comment by Synchro** [comment]
So read the guide I pointed you at. I'm not going to say anything different here.

**Comment by nikhilmishra1998** [comment]
i changed my codes with the new code but same problem is comming

**Comment by Synchro** [comment]
and what happened when you did what the guide says?

**Comment by nikhilmishra1998** [comment]
Error came that 

smtp connection failed

**Comment by nikhilmishra1998** [comment]
i am using this code:

require 'PHPMailer/PHPMailer.php';
require 'PHPMailer/Exception.php';
require 'PHPMailer/POP3.php';
require 'PHPMailer/SMTP.php';
$mail = new PHPMailer;
			//Tell PHPMailer to use SMTP
			$mail->isSMTP();
			//Enable SMTP debugging
			// 0 = off (for production use)
			// 1 = client messages
			// 2 = client and server messages
			$mail->SMTPDebug = 2;
			//Set the hostname of the mail server
			$mail->Host = 'mail.gmail.com';
			//Set the SMTP port number - likely to be 25, 465 or 587
			$mail->Port = 25;
			//Whether to use SMTP authentication
			$mail->SMTPAuth = true;
			$mail->Username = 'mail@gmail.com';                 // SMTP username
			$mail->Password = password';
			//Set who the message is to be sent from
			$mail->setFrom('mail@gmail.com', 'Mailer');
			$mail->addAddress('test@gmail.com', 'Joe User');  //Set who the message is to be sent to
			//$mail->addAddress('whoto@example.com', 'John Doe');
			//Set the subject line
			$mail->Subject = 'PHPMailer SMTP test';
			//Read an HTML message body from an external file, convert referenced images to embedded,
			//convert HTML into a basic plain-text alternative body
			$mail->msgHTML('<table>'
								  .'<tr ><td width="150px">User Name: <b>'.$name.'</b></td></tr>'."\r\n"
								 .'<tr><td>User Email : <b><a href = \"#\">'.$InputEmail.'</a></b></td></tr>'."\r\n"
								 .'<tr><td>User Contact No. : <b>'.$InputContact.'</b></td></tr>'."\r\n"
								 .'<tr><td>User Message : <b>'.$InputMessage.'</b></td><tr>'."\r\n"
								 //.'<tr><td>Referal :</td><td><b>'.$referal.'</b></td></tr>'
								 .'</table>');
			//Replace the plain text body with one created manually
			$mail->AltBody = 'This is a plain-text message body';
			//Attach an image file
			//$mail->addAttachment('images/phpmailer_mini.png');
			//send the message, check for errors
			if (!$mail->send()) {
				echo 'Mailer Error: ' . $mail->ErrorInfo;
			} else {
				echo 'Message sent!';
			}

**Comment by nikhilmishra1998** [comment]
Error is:
Uncaught Error: Class 'PHPMailer' not found in

**Comment by nikhilmishra1998** [comment]
i am using PHPMailer 6.0.2

**Comment by nikhilmishra1998** [comment]
but use statement is not working

**Comment by nikhilmishra1998** [comment]
Error is:
Failed to connect to server: php_network_getaddresses: getaddrinfo failed: No such host is known.
															2018-09-04 10:30:46 SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: No such host is known.  (0)<br>
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting<br>
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/TroubleshootingTrue

**Comment by Synchro** [comment]
No, that means that the `use` statements are working fine. You have a different problem which I covered in my very first response: you have the wrong `Host` value. Do what I said and use the gmail example provided.

**Comment by nikhilmishra1998** [comment]
but which link you provided me was occurring 404 error

**Comment by nikhilmishra1998** [comment]
please provide me a link through which i get some help

**Comment by Synchro** [comment]
Sorry, there was a letter missing from that URL, it should have been https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail.phps

Aside form that, read the troubleshooting guide.

**Comment by nikhilmishra1998** [comment]
now i am using this code 

`//Import PHPMailer classes into the global namespace
use PHPMailer\PHPMailer\PHPMailer;
require '../vendor/autoload.php';
//Create a new PHPMailer instance
$mail = new PHPMailer;
//Tell PHPMailer to use SMTP
$mail->isSMTP();
//Enable SMTP debugging
// 0 = off (for production use)
// 1 = client messages
// 2 = client and server messages
$mail->SMTPDebug = 2;
//Set the hostname of the mail server
$mail->Host = 'smtp.gmail.com';
// use
// $mail->Host = gethostbyname('smtp.gmail.com');
// if your network does not support SMTP over IPv6
//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
$mail->Port = 587;
//Set the encryption system to use - ssl (deprecated) or tls
$mail->SMTPSecure = 'tls';
//Whether to use SMTP authentication
$mail->SMTPAuth = true;
//Username to use for SMTP authentication - use full email address for gmail
$mail->Username = "username@gmail.com";
//Password to use for SMTP authentication
$mail->Password = "yourpassword";
//Set who the message is to be sent from
$mail->setFrom('from@example.com', 'First Last');
//Set an alternative reply-to address
$mail->addReplyTo('replyto@example.com', 'First Last');
//Set who the message is to be sent to
$mail->addAddress('whoto@example.com', 'John Doe');
//Set the subject line
$mail->Subject = 'PHPMailer GMail SMTP test';
//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body
$mail->msgHTML(file_get_contents('contents.html'), dirname(__FILE__));
//Replace the plain text body with one created manually
$mail->AltBody = 'This is a plain-text message body';
//Attach an image file
$mail->addAttachment('images/phpmailer_mini.png');
//send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
    //Section 2: IMAP
    //Uncomment these to save your message in the 'Sent Mail' folder.
    #if (save_mail($mail)) {
    #    echo "Message saved!";
    #}
}`

**Comment by nikhilmishra1998** [comment]
and comminng this error

**Comment by nikhilmishra1998** [comment]
2018-09-04 11:54:38 SERVER -&gt; CLIENT: 220 smtp.gmail.com ESMTP q62-v6sm32636786pfi.185 - gsmtp<br>
2018-09-04 11:54:38 CLIENT -&gt; SERVER: EHLO localhost<br>
2018-09-04 11:54:38 SERVER -&gt; CLIENT: 250-smtp.gmail.com at your service, [125.99.38.254]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250 SMTPUTF8<br>
2018-09-04 11:54:38 CLIENT -&gt; SERVER: STARTTLS<br>
2018-09-04 11:54:38 SERVER -&gt; CLIENT: 220 2.0.0 Ready to start TLS<br>
SMTP Error: Could not connect to SMTP host.<br>
2018-09-04 11:54:38 CLIENT -&gt; SERVER: QUIT<br>
2018-09-04 11:54:38 SERVER -&gt; CLIENT: <br>
2018-09-04 11:54:38 SMTP ERROR: QUIT command failed: <br>
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting<br>
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/TroubleshootingTrue

**Comment by Synchro** [comment]
This *exact* problem is described in the guide - it's most likely that your server has out of date CA certificates and you need to update them. Please read the docs, it's what they are there for.
