### ISSUE TITLE
If attachment is larger than 20 MB it is not getting send using Gmail

### ISSUE THREAD

**Issue by 2016sohail** [PHPMailer/PHPMailer#1538]
I have configured PHPMailer (v:5.2) in laravel (v:5.2) it is working fine but when we upload files more than 20MB the Gmail does not allow in the mail attachment it should be sent via Google Drive. How can I do that?

**Comment by Synchro** [comment]
Google drive will have some API that you can use to transfer files to it, and presumably they will end up with a URL which you could then email to someone. This is outside the scope of PHPMailer though.
