### ISSUE TITLE
Errors-To header

### ISSUE THREAD

**Issue by 5x3** [PHPMailer/PHPMailer#1541]
Is there any way to define "abuse master" e-mail address other than my own account e-mail?
RFC defines Errors-To: header, how to set it?
Or how to archive needed with any other way?
I need define mail where delivery errors would be considered promptly.
thanks.

**Comment by Synchro** [comment]
Bounces are normally sent to the return path. This is generated by the **receiving** server, not the sender, from the address used in the SMTP MAIL FROM command. This is not the same as the From header within the message.

By default PHPMailer sets the SMTP sender from the from address, but you can override it (for example to VERP addressing to improve you bounce handling) by setting the `Sender` property, which you'll find covered in the docs. For example you might do this:

    $mail->From = 'me@example.com';
    $mail->Sender = 'bounces@example.com';

Setting an Errors-to header can be done via the `addCustomHeader` method, but I don't recommend it as it's not normally used.
