### ISSUE TITLE
Your domain is not allowed in header  From" 

### ISSUE THREAD

**Issue by charliedaps1** [PHPMailer/PHPMailer#1545]
Hello,

I have this error on a youphptube script.

Do you have a track?

Thanks by advance for your help

**Comment by Synchro** [comment]
I don't know what a youphptube script  is, but this message usually means that you are trying to send a message through a server that does not host the domain you're sending from, or one that is not listed in the domain's SPF record. There's not enough information for me to tell any further.

**Comment by charliedaps1** [comment]
Hello,

Thank you for your help.

I will try to be simple.
The domain name is with a host and the mails too (it's a shared hosting)
The site is hosted on a VPS elsewhere (because the script requires a VPS)

I do not know much about VPS that's why I left the mails at the host.

There is just a record DNS A for the domain name to point to the VPS

Thanks for your help

**Comment by Synchro** [comment]
It sounds like you should ask your hosting provider what you need to do, since they are the ones operating the mail server.

**Comment by charliedaps1** [comment]
I contact them and I come back to you

**Comment by charliedaps1** [comment]
Some DNS changes and obviously it's better.

Thanks for your help
