### ISSUE TITLE
Not sending FromName in mail 

### ISSUE THREAD

**Issue by cskushwah** [PHPMailer/PHPMailer#1549]
Hi,

I am facing on different issue. Iam getting mail but  not getting FromName in mail. I have set the from address and name in method  setFrom('support@gmail.com', 'Chandan singh') and i got the mail but not showing the name 'Chandan singh' . it is showing 'support' in name.

PHP Version : 7.0.32 

OS : ubuntu0.16.04.1

X-Mailer: PHPMailer 6.0.5 

But when i run same code on local machine on. then getting mail and showing FromName 'Chandan singh' in my mail. My Machine configration

Php Version : 7.1.20

OS : ubuntu14.04.1

X-Mailer: PHPMailer 6.0.5

I am not able to findout root cause of it.

Kindly Help Me...

**Comment by Synchro** [comment]
Check the source of the delivered message - you will probably find that it is correct in there. Gmail, Apple Mail and others often ignore the from name and instead display the name used the first time the from address was encountered.

**Comment by cskushwah** [comment]
I am not getting then why  it is showing when i send it with local machine? 

CODE: 
        $this->phpMailer = new PHPMailer(true);                                      
        $this->phpMailer->isSMTP();                                      
        $this->phpMailer->Host = '';  
        $this->phpMailer->SMTPAuth = true;                             
        $this->phpMailer->Username = '';                 
        $this->phpMailer->Password = '';                           
        $this->phpMailer->SMTPSecure = 'tls';                          
        $this->phpMailer->Port = 587;    
        $this->phpMailer->isHTML(true);
        $this->phpMailer->setFrom('support@gmail', 'Chandan singh');
        $this->phpMailer->addReplyTo('support@gmail', 'Chandan singh');
        $this->phpMailer->addAddress($email); 
        $this->phpMailer->Body = $mailMessageArray['mailBody'];
        $this->phpMailer->Subject  = $mailMessageArray['subject'];
        $result = $this->phpMailer->send();

The this debug result from both code
DEBUG : 
2018-09-24 15:11:44 CLIENT -&gt; SERVER: From: Chandan singh &lt;support@gmail.com&gt;<br>

**Comment by Synchro** [comment]
That's exactly what I was saying - it's correct in the message content, but the email client chooses not to display it, and you have no control over that.
