### ISSUE TITLE
Using remote Sendmail without auth and via proxy

### ISSUE THREAD

**Issue by morespinach99** [PHPMailer/PHPMailer#1550]
# Problem description
We run a platform where the "From" has to be our customer's domain. So our customers have their servers running Sendmail, from which we're supposed to send email from the designated 'From' address. Which means, we need to compose body, attach files, assign headers etc, from our PHP code on our server, but the final 'sending' happens via the remote Sendmail. Our challenge: the Sendmail on the remote server has *not* enabled SMTP. It has merely whitelisted our IP. We run off a shared hosting service, so to give them a more fixed IP that they could whitelist, we use a proxy server. They have whitelisted this proxy server from that destination Sendmail server. Could you please advise how this could be done? 

# Code to reproduce
I'm asking for the code to achieve the above functionality. 

# Debug output
None

**Comment by Synchro** [comment]
There are a few ways you could deal with this, but all are below the PHP layer. You could set up a mail server that acts as a relay (effectively an SMTP-level proxy), though having different routing could be tricky - look at postfix's transport maps for that. Alternatively VPN to each location and select the right outbound server at send time.

A much easier route would be to not use shared hosting - get a proper server without outbound SMTP blocks, and configure SPF for each domain you send for to give permission to your server. That is much less complicated than what you're doing now.
