### ISSUE TITLE
Send file upload not working

### ISSUE THREAD

**Issue by precious8821** [PHPMailer/PHPMailer#1556]
I tried using the script example 'send file uploads' from php mailer's example code onto a website.  When I upload a file and then click onto submit, I do not receive any success message.  And, the email is not sent.  

Please let me know what might be causing this error.  I have composer installed, latest version of PHP, and I'm using AWS for my server.   I did try using a different form without an upload feature, and the email was able to send.  So I doubt its a problem with the SMTP, unless it is somehow preventing only attachments.

Any advice is appreciated.  Thank you!

**Comment by Synchro** [comment]
This is a generic PHP debugging question, so I'd recommend searching for that. What debugging attempts have you made? What does your web server's error log say? What happens if you enable display of PHP error messages?

**Comment by rafay987** [comment]
This Is a PHP configuration issue maybe increase max upload size and max execution time in php.ini

**Comment by Synchro** [comment]
It will be failing for some specific reason; better to find out what that is than just guessing.
