### ISSUE TITLE
PHPMailer - SMTP Error: Could not connect to SMTP host

### ISSUE THREAD

**Issue by Franciscobk** [PHPMailer/PHPMailer#1558]
Por favor!

-Eu preciso resolver este problema vejo que o meu código fonte está em condições. 
Eu tentei utilizar a porta 465, 25 e não deu certo. Também mudei o TSL para SSL e mesmo assim recebo o mesmo erro. O que devo fazer?
Quando tento enviar uma mensagem ao email de alguém recebo o seguinte erro:

2018-10-02 17:10:48 SERVER -> CLIENT: 
2018-10-02 17:10:48 SMTP NOTICE: EOF caught while checking if connected
SMTP Error: Could not connect to SMTP host.
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Erro ao enviar a mensagem

><?php 
	
	//Incluir o phpmailer
	require_once("PHPMailerAutoload.php");

	//Criar Instancia do phpmailer
	$mail = new PHPMailer();

	//Habilitar SMTP
	$mail->isSMTP();

	$mail->SMTPOptions = array(

		'tsl' => array('verify_peer' => false , 'verify_peer_name' =>false,
		'allow_self_signed' => true
	)

	);

	//Debug para informar. caso tiver algum erro
	$mail->SMTPDebug=2; //0-nada 1-msg cliente 2-msg cliente e servidor 3-tudo

	//Host
	$mail->Host = "smtp.gmail.com";

	//Tipo de proteção
	$mail->SMTPSecure = 'tls';

	//porta
	$mail-> Port = 465;

	//Autenticação
	$mail->SMTPAuth = true;

	//Detalhes da conta de email
	$mail->Username = 'afonsofrancisco24@gmail.com';
	$mail->Password = 'NomeDaMinhaAvoPortalHacker';

	//Detalhes do Email
	$mail->setFrom('afonsofrancisco24@gmail.com', 'Teste');
	$mail->addAddress('paulosanuca99@gmail.com');
	$mail->Subject = 'Email de teste GPA';
	$mail->Body = 'Olá Mundo';

	//Mensagem de confirmação de envio
	if ($mail->send()) {
		echo "Email enviado com sucesso!";
	}else{

		echo "Erro ao enviar a mensagem";
	}

?>

**Comment by Synchro** [comment]
Read this: https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#using-encryption
