### ISSUE TITLE
Subject line missing even though set by script

### ISSUE THREAD

**Issue by gthb1** [PHPMailer/PHPMailer#1562]
What could be the reason (or how to find out/debug) why suddenly PhpMailer does not send the subject line anymore (now empty)?
(Another mailer still does in the same environment with the same script, so one might assume it is to do with PhpMailer.)

**Comment by Synchro** [comment]
The most likely explanation is that you're not actually setting it - for example you might have code that says `$mail->Subject = $mysubject`, but `$mysubject` is empty. You need to show code to demonstrate this happening.

**Comment by gthb1** [comment]
Not sure how the 'not setting it' could happen, but that is more a lack of ideas ;)
What is known: the script working with PhpMailer or SwiftMailer is the same, and it happened before and after server update the same way (emails sent w/ PhpMlr do not have the subject line (only showing "(No Subject)", while w/ SwiftMlr they have it has set up). They only thing I can think of would be some database corruption. Not sure how to test it. Probably the state shortly before when the subject variable's value is handed over to the mailer?

**Comment by Synchro** [comment]
Yes, exactly. It's not hard to test - from my earlier example, you'd add this just before it:

    var_dump($mysubject);
    exit;

Better would be a to set a breakpoint in your IDE and inspect the variable in context.
