### ISSUE TITLE
phpmailer can't properly encode attachment's file name which contain cjk characters

### ISSUE THREAD

**Issue by gitsnippet** [PHPMailer/PHPMailer#1564]
Environment : debian9 + php7 + phpmailer6.0.5.    
Save the following file as `/var/www/html/send.php` ,change the `require` lines accoring to your system,rewrite password ,name,email, etc as yours in order to reproduce the case.
```
    <?php
        require('path/to/vendor/autoload.php');        
        require('path/to/PHPMailer/src/Exception.php');
        require('path/to/PHPMailer/src/PHPMailer.php');
        require('path/to/PHPMailer/src/SMTP.php');
        $mail = new PHPMailer\PHPMailer\PHPMailer();
        $mail->CharSet = 'UTF-8';
        $mail->IsSMTP(); 
        $mail->IsHTML(true);
        $mail->SMTPDebug = 1; 
        $mail->SMTPAuth = true;  
        $mail->SMTPSecure = 'ssl';  
        $mail->Host = "smtp.qq.com";
        $mail->Port = 465; 
        $mail->Username = "xxxx";
        $mail->Password = "xxxx";    
        $mail->SetFrom("xxxx@qq.com");
        $mail->Subject = "test title 测试主题";
        $mail->Body = "test body 测试内容";
        $mail->addAttachment("/tmp/问题");
        $mail->AddAddress("yyyy@yahoo.com");
        if(!$mail->Send()) {
        echo "Mailer Error: " . $mail->ErrorInfo;
        } else {
        echo "Message has been sent";
        }
    ?>
```
For the above file:
```
    file  /var/www/html/send.php
    /var/www/html/send.php: UTF-8 Unicode text
```
For the file `/tmp/问题`.
```
    file  /tmp/问题
    /tmp/问题: UTF-8 Unicode text, with no line terminators
    cat  /tmp/问题
    it is a test 测试
```
Type `127.0.0.1/send.php` in your browser,and open yahoo email.
https://i.stack.imgur.com/5TqNA.png

Donwload the file in yahoo email box ,and open it ,shows 

    it is a test 测试

It shows that :    
subject and body which contain cjk characters can show properly in receiver's email box;
attachment's file name which contain cjk characters can't show properly in receiver's email box.      
content in attachment which contain cjk characters can show properly in receiver's email box.      

How to fix it?

**Comment by gitsnippet** [comment]
$mail->CharSet = 'UTF-8';
        $mail->Encoding = "base64";

solved.

**Comment by Synchro** [comment]
I'm glad you found a fix, though I'm a little surprised. The `Encoding` value is not used for headers; headers have their own (different) encoding system, and PHPMailer selects between B (which is base64) and Q (which is quoted-printable) dynamically according to which will be shorter. `CharSet` *is* used in headers, but you had that set already.
