### ISSUE TITLE
Why  not write a  example for the latest  phpmailer version ?

### ISSUE THREAD

**Issue by gitsnippet** [PHPMailer/PHPMailer#1565]
In the manual here
https://github.com/PHPMailer/PHPMailer

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

//Load Composer's autoloader
require 'vendor/autoload.php';

$mail = new PHPMailer(true);  

I have verified that  `$mail = new PHPMailer(true);  ` can't work, the right format for phpmailer 6.0.5  is 

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

//Load Composer's autoloader
require '/path/to/vendor/autoload.php';
$mail = new PHPMailer\PHPMailer\PHPMailer(); 

Why not write a  example for the latest  phpmailer version ,or add a comment in the old example?

$mail = new PHPMailer\PHPMailer\PHPMailer();

**Comment by Synchro** [comment]
This is just wrong. The `use` statements import the namespaced PHPMailer class into the global scope, so you do not need to use a FQCN, and the examples are already correct.
