### ISSUE TITLE
namespace , FQCN and php shell

### ISSUE THREAD

**Issue by gitsnippet** [PHPMailer/PHPMailer#1566]
Save the follow as send.php,it can be executed with `php -f send.php` or `127.0.0.1/send.php`, no error info as output.   
```
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require_once('/to/path/vendor/autoload.php'); 
$mail = new PHPMailer();
?>
```
Open a php shell with `php -a`.
php > use PHPMailer\PHPMailer\PHPMailer;
php > use PHPMailer\PHPMailer\Exception;
php > require '/home/debian9/vendor/autoload.php';
php > $mail = new PHPMailer(true);
PHP Warning:  Uncaught Error: Class 'PHPMailer' not found in php shell code:1
Stack trace:
#0 {main}
  thrown in php shell code on line 1

Why `$mail = new PHPMailer(true);` can't execute in php shell?   
You must write `$mail = new PHPMailer\PHPMailer\PHPMailer();`  in php shell.

**Comment by Synchro** [comment]
I see what you mean, however, I think this is either a composer bug or a PHP shell issue/limitation, and not a PHPMailer problem, because set up like this, it works:

    mkdir test; cd test
    composer require PHPMailer/PHPMailer

edit test.php to:

```php
<?php
use PHPMailer\PHPMailer\PHPMailer;
require 'vendor/autoload.php';
$mail = new PHPMailer;
```

and run it with `php test.php` - no errors.

I tested it with another random namespaced class:

```php
composer require tuupola/base62
php -a
Interactive shell

php > use Tuupola\Base62;
php > require 'vendor/autoload.php';
php > $b = new Base62;
PHP Warning:  Uncaught Error: Class 'Base62' not found in php shell code:1
Stack trace:
#0 {main}
  thrown in php shell code on line 1

Warning: Uncaught Error: Class 'Base62' not found in php shell code:1
Stack trace:
#0 {main}
  thrown in php shell code on line 1
```

Same problem. So there is a bug/limitation, but it's not in PHPMailer.
