### ISSUE TITLE
SMTP Error

### ISSUE THREAD

**Issue by PerryGamerPT** [PHPMailer/PHPMailer#1570]
when i try send emails via gmail appends this error

2018-10-09 10:37:36 SERVER -> CLIENT: 220 smtp.gmail.com ESMTP j203-v6sm21164943wmd.46 - gsmtp
2018-10-09 10:37:36 CLIENT -> SERVER: EHLO 94.61.122.134
2018-10-09 10:37:36 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [94.61.122.134]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250 SMTPUTF8
2018-10-09 10:37:36 CLIENT -> SERVER: STARTTLS
2018-10-09 10:37:36 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
SMTP Error: Could not connect to SMTP host.
2018-10-09 10:37:36 CLIENT -> SERVER: QUIT
2018-10-09 10:37:36 SERVER -> CLIENT: 
2018-10-09 10:37:36 SMTP ERROR: QUIT command failed: 
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

my code:
use PHPMailer\PHPMailer\PHPMailer;
require 'vendor/autoload.php';
$mail = new PHPMailer;
$mail->isSMTP();
$mail->SMTPDebug = 2;
$mail->Host = 'smtp.gmail.com';
$mail->Port = 587;
$mail->SMTPSecure = 'tls';
$mail->SMTPAuth = true;
$mail->Username = "perrygamerptyt@gmail.com";
//Password to use for SMTP authentication
$mail->Password = "renatorato24";
//Set who the message is to be sent from
$mail->setFrom('from@example.com', 'First Last');
//Set an alternative reply-to address
$mail->addReplyTo('replyto@example.com', 'First Last');
//Set who the message is to be sent to
$mail->addAddress('garrano24@gmail.com', 'John Doe');
//Set the subject line
$mail->Subject = 'PHPMailer GMail SMTP test';
//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body
$mail->msgHTML("<html><body><p>ola</p><p>panados</p></body></html>");
//Replace the plain text body with one created manually
$mail->AltBody = 'This is a plain-text message body';
//send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";

}

**Comment by Synchro** [comment]
It's probably that your CA certificates are out of date as it's failing immediately after STARTTLS. You'll find this discussed in depth in the troubleshooting guide linked from the error message.
