### ISSUE TITLE
Using accent in french encoding problem ?

### ISSUE THREAD

**Issue by Rayman223** [PHPMailer/PHPMailer#1578]
Hello dear! 

I just download PHPMailer and start to test it.
I try the mail.php example.

# Problem description
It seem that `$mail->Subject` is not UTF-8. I manually type : 
`$mail->Subject = 'Votre récompense vous a été envoyée';`
and I received this : 
`Votre rÃ©compense vous a Ã©tÃ© envoyÃ©e`

What I missing ?
Thx a lot !

**Comment by Synchro** [comment]
You need to change `CharSet = ‘UTF-8’`, and ensure your data is in UTF-8, and that you have the mbstring extension.
