### ISSUE TITLE
5.2.4 vs 5.2.26 Could not connect to SMTP host.

### ISSUE THREAD

**Issue by woakazam** [PHPMailer/PHPMailer#1583]
first i tried v6.0.5 and Could not connect to SMTP host.
then i go to back 5.2.4 it works great.
then i tried 5.2.26 (Latest release of 5) and again Could not connect to SMTP host.

5.2.4 : Works Great
5.2.26 and 6.0.5 : Could not connect to SMTP host.

Any solution for 6.0.5 ?

**Comment by Synchro** [comment]
Enable debug output and run through the diagnostics as described in the troubleshooting guide. It's impossible to tell what's wrong from your description.

5.2.4 is very old and is actively dangerous as it contains some serious security holes.

**Comment by Synchro** [comment]
Are you sure that the PHPMailer version is absolutely the *only* thing you're changing? You're not running it on a different server, or with a different version of PHP?

It's failing immediately after issuing a STARTTLS command. This is covered in the troubleshooting guide; it's most likely that your CA certificates are outdated. The diagnostic steps in the guide will help diagnose and fix this, and other problems like it.

**Comment by woakazam** [comment]
Yes. Just different PHPMailer includes. Same PHP Codes (after try part). No outdated. Checked everywhere.

5.2.4 works, 6.0.5 not work. Interesting ...

**Comment by Synchro** [comment]
Well, it's definitely a TLS problem. What version of PHP are you running? The only way that it can fail at that stage is for the call to `stream_socket_enable_crypto` to fail, so I suggest setting a breakpoint in the `SMTP::errorHandler` method which will trigger when this happens, and you'll be able to inspect the context.

**Comment by woakazam** [comment]
stream_socket_enable_crypto return false. i guess about CA ...
now i use 6.0.5 with this codes;

```
$mail->SMTPOptions = array(
        'ssl' => array(
            'verify_peer' => false,
            'verify_peer_name' => false,
            'allow_self_signed' => true
        )
);
```
Thanx for help.

**Comment by Synchro** [comment]
That's not really a solution, it just tells you that your CA certificates are outdated. Update them as the guide tells you.
