### ISSUE TITLE
Can't use subclass for pgp encrytion

### ISSUE THREAD

**Issue by Gratusfr** [PHPMailer/PHPMailer#1584]
Hi, first I want to thank all contributors of this wonderful project.

After search, it seem pgp encryption is not a feature available (the idea is abandonned ?)
I tested the fork class.phpmailerpgp.php (https://github.com/ravisorg/PHPMailer/blob/openpgp/class.phpmailerpgp.php) but I cant use without fatal errors.

Index.php
`ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\PHPMailerPGP;

require 'PHPMailer/src/Exception.php';
require 'PHPMailer/src/PHPMailer.php';
require 'PHPMailer/src/phpmailerpgp.php';`

Indeed I get; " Fatal error: Class 'PHPMailer' not found in xxx/Contact/PHPMailer/src/phpmailerpgp.php on line 9"

When I add "namespace PHPMailer\PHPMailer;" in subclass, I get:  Fatal error: Uncaught Error: Call to undefined method PHPMailer\PHPMailer\PHPMailer::importKeyFile() in xxx/Contact/index.php:100 Stack trace: #0 {main} thrown in xxx/Contact/index.php on line 100

I'm not really familiar with PHP classes, so this question may seem dumb, I'm sorry.
I'm pretty sure is a small thing but hours passed on Google doen't help me.

Regards,

**Comment by Synchro** [comment]
Adding the namespace to the sub class is correct, but it looks like the way you call it from your `Contact/index.php` script is not. I suspect you have created an instance of PHPMailer instead of PHPMailerPGP, and so it's lacking the added methods. This PGP class could do with updating - it looks like it was built for the old 5.x branch.

**Comment by cracksalad** [comment]
> Adding the namespace to the sub class is correct, [...]
> 
> It's also not structured correctly - it should be pulling in PHPMailer as a dependency via composer so that all it needs to contain is its child class and not all the other stuff. 

I just did that in a fork of [ravisorg/PHPMailer](https://github.com/ravisorg/PHPMailer) right [here](https://github.com/cracksalad/PHPMailerPGP). Feel free to try it and please tell me, if it works for you!
