### ISSUE TITLE
PHPMailer/PHPMailerAutoload.php error on PHP VERSION 7.2.3

### ISSUE THREAD

**Issue by AchmadSyarippudin** [PHPMailer/PHPMailer#1590]
Showing error 

Message: __autoload() is deprecated, use spl_autoload_register() instead

Filename: PHPMailer/PHPMailerAutoload.php

Line Number: 46

**Comment by Synchro** [comment]
That's why the current version of PHPMailer doesn't do this, and the version that does is long deprecated.
