### ISSUE TITLE
connecting to a windows smtp server fails after connected

### ISSUE THREAD

**Issue by slloyd88** [PHPMailer/PHPMailer#1593]
We have an open relay SMTP server running windows that connects to office365.  our open relay is for internal use so it does not need authentication. Hence we use port 25.  I get the following when trying to use phpmailer.  I can physically telnet into the server and have confirmed it does work correctly. I can send fine when I telnet in and walk through the commands.

3: Connection: opening to 10.10.128.78:25, timeout=300, options=array()
3: Connection: opened
2: SERVER -> CLIENT: 
1: SMTP NOTICE: EOF caught while checking if connected
3: Connection: closed
3: The following From address failed: donotreply@{ourdomain}.com : Called MAIL FROM without being connected,,,SMTP server error: Called MAIL FROM without being connected

**Comment by Synchro** [comment]
That empty server-client response from your server is what’s doing it, though it’s not clear if that’s really happening or whether the connection is dropping immediately. A wireshark trace would reveal all. It may be a PHP config problem.

**Comment by slloyd88** [comment]
Ok, I am sure it is on the the windows SMTP side. Using the same PHP code I am able to connect and send with many other systems.  I will close but just thought you may want to know that there are windows SMTP servers out there that are causing issues.
