### ISSUE TITLE
SMTP ERROR: Failed to connect to server: Connection refused (111) SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

### ISSUE THREAD

**Issue by vaishnavhiren1993** [PHPMailer/PHPMailer#1599]
>  **##ERROR is**
> SMTP ERROR: Failed to connect to server: Connection refused (111)
> SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
> 
### **is is work on local host but once i run on godaddy server i can't and error shot . plz solve and sugges me**
>
> **## My Code HTML is **``<style type="text/css">
>     /*form*/
>     
>     label {
>         position: absolute;
>         -webkit-transform: translateY(6px);
>         transform: translateY(6px);
>         left: 13px;
>         color: rgb(0, 0, 0);
>         -webkit-transition: all 0.25s ease;
>         transition: all 0.25s ease;
>         pointer-events: none;
>         font-size: 19px;
>         font-family: "century gothic";
>     }
>     
>     label .req {
>         margin: 2px;
>         color: #b11a1a;
>     }
>     
>     label.active {
>         -webkit-transform: translateY(50px);
>         transform: translateY(50px);
>         left: 2px;
>         font-size: 14px;
>         top: -70px;
>     }
>     
>     label.active .req {
>         opacity: 1;
>     }
>     
>     label.highlight {
>         color: #000;
>     }
>     
>     input,
>     textarea {
>         font-size: 17px;
>         display: block;
>         width: 100%;
>         padding: 5px 10px;
>         background: none;
>         background-image: none;
>         border: 1px solid #a0b3b0;
>         color: #000;
>         border-radius: 0;
>         -webkit-transition: border-color .25s ease, box-shadow .25s ease;
>         transition: border-color .25s ease, box-shadow .25s ease;
>     }
>     
>     input:focus,
>     textarea:focus {
>         outline: 0;
>         border-color: #b11a1a;
>     }
>     
>     textarea {
>         border: 2px solid #a0b3b0;
>         resize: vertical;
>         height: 120px;
>     }
>     
>     .field-wrap {
>         position: relative;
>         margin-bottom: 30px;
>     }
>     
>     .top-row:after {
>         content: "";
>         display: table;
>         clear: both;
>     }
>     
>     .top-row>div {
>         float: left;
>         width: 48%;
>         margin-right: 4%;
>     }
>     
>     .top-row>div:last-child {
>         margin: 0;
>     }
>     
>     .button {
>         border: 0;
>         outline: none;
>         border-radius: 0;
>         padding: 10px 0;
>         font-size: 1rem;
>         font-weight: 600;
>         text-transform: uppercase;
>         letter-spacing: .1em;
>         background: #b11a1a;
>         color: #ffffff;
>         -webkit-transition: all 0.5s ease;
>         transition: all 0.5s ease;
>         -webkit-appearance: none;
>     }
>     
>     .button:hover,
>     .button:focus {
>         background: #9b1717;
>     }
>     
>     .button-block {
>         display: block;
>         width: 100%;
>     }
>     
>     .forgot {
>         margin-top: -20px;
>         text-align: right;
>     }
>     
>     .content {
>         padding-bottom: 0px;
>     }
>     
>     * {
>         font-family: 'Century Gothic' !important;
>     }
> </style>
> <div class="container" style="padding: 45px 20% 20px; ">
>     <h3 id="form-registration">Register and get more information</h3>
> 
> 
>     <br>
>     <form action="mail.php" method="POST" id="form">
>         <input type="email" id="email" name="owneremail" maxlength="30" placeholder="enter email address to get user data " style="margin-bottom:30px">
>         <div class="top-row">
>             <div class="field-wrap">
>                 <label class="active highlight">
>                 First Name<span class="req">*</span>
>               </label>
>                 <input type="text" pattern="[a-zA-Z]{3,30}" id="fname" name="fname" maxlength="30">
>             </div>
> 
>             <div class="field-wrap">
>                 <label class="active highlight">
>                 Last Name<span class="req">*</span>
>               </label>
>                 <input type="text" pattern="[a-zA-Z]{3,30}" id="lname" name="lname" maxlength="30">
>             </div>
>         </div>
> 
>         <div class="field-wrap">
>             <label class="active highlight">
>               Company name<span class="req">*</span>
>             </label>
>             <input type="text" class="half" name="company" id="cname">
>         </div>
> 
>         <div class="top-row">
>             <div class="field-wrap">
>                 <label class="active highlight">
>                 City<span class="req">*</span>
>               </label>
>                 <input type="text" pattern="[a-zA-Z]{3,20}" name="city" id="city">
>             </div>
> 
>             <div class="field-wrap">
>                 <label class="active highlight">
>                 State/Province<span class="req">*</span>
>               </label>
>                 <input type="text" pattern="[a-zA-Z]{3,20}" name="state" id="province">
>             </div>
>         </div>
> 
>         <div class="top-row">
>             <div class="field-wrap">
>                 <label class="active highlight">
>                  Email Address<span class="req">*</span>
>                </label>
>                 <input type="email" required="required" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" name="email" id="memail">
>             </div>
> 
>             <div class="field-wrap">
>                 <label class="active highlight">
>                 Phone<span class="req">*</span>
>               </label>
>                 <input type="number" autocomplete="on" pattern="[0-9]{10,15}" name="phone" id="mobile">
>             </div>
>         </div>
> 
>         <div class="field-wrap">
>             <label class="active highlight">
>               Website<span class="req">*</span>
>             </label>
>             <input type="text" class="half" pattern="[a-zA-Z._-%^]" name="website" id="website" value="">
>         </div>
> 
>         <div class="field-wrap">
>             <label class="active highlight">
>               Queries
>             </label>
>             <textarea name="queries" autocomplete="off"></textarea>
>         </div>
>         <button type="submit" value="Submit" name="Submit" class="button button-block">Send</button>
> 
>     </form>
> </div>
> 
> ### **My PHP Code is**
>    /*form*/
> <?php
> use PHPMailer\PHPMailer\PHPMailer;
> require("PHPMailer-master/src/PHPMailer.php");
> require("PHPMailer-master/src/SMTP.php");
> require("PHPMailer-master/src/Exception.php");
> //require 'vendor/autoload.php';
> if(isset($_POST['Submit'])) {
> //fatch data from form
> //fatch data from form
> $fname = $_POST['fname'];
> $lname = $_POST['lname'];
> $company = $_POST['company'];
> $city = $_POST['city'];
> $state = $_POST['state'];
> $email_to = $_POST['email'];
> $phone = $_POST['phone'];
> $website = $_POST['website'];
> $queries = $_POST['queries'];
> 
> $mail = new PHPMailer(true);
> $mail->SMTPDebug = 3;
> $mail->Debugoutput = 'html';
> $mail->isSMTP();
> $mail->Host = 'ssl://smtp.gmail.com';
> $mail->SMTPAuth = true;
> $mail->Username = 'useremailaddress@gmail.com';
> $mail->Password = 'userpassword';
> $mail->SMTPSecure = 'ssl';
> $mail->Port = 465;
> $mail->isHTML(true);
> $mail->From = 'useremailaddress@gmail.com';
> $mail->FromName = 'this is test';
> $mail->addAddress($email_to);
> $mail->WordWrap = 50;
> $mail->isHTML(true);
> $mail->Subject = 'ASK FOR A DEMO';
> $mail->Body    = 'hello';
> if(!$mail->send()) {
>     echo 'Message could not be sent.';
>     echo 'Mailer Error: ' . $mail->ErrorInfo;
> } else {
>     echo 'Message has been sent';
>     echo "<script>alert('".$email_to." thank you!');</script>";
> }
> }
> ?>
> <h3>hello</h3>
>

_Originally posted by @vaishnavhiren1993 in https://github.com/PHPMailer/PHPMailer/issue_comments#issuecomment-439312041_

**Comment by Synchro** [comment]
You see that link to the troubleshooting guide? Click it, and read what it says about GoDaddy.
