### ISSUE TITLE
I saw the problem with phpmailer seance 2016 ,

### ISSUE THREAD

**Issue by vaishnavhiren1993** [PHPMailer/PHPMailer#1602]
i spend my 4 day but still not working .
i tried lot's of samples but its not working .
so please  share send email code .
any method any code just give me .
i am very afraid 

every time i change something there are different errors.
but commanly i saw this error

**2018-11-19 12:10:33 SMTP ERROR: Failed to connect to server: No connection could be made because the target machine actively refused it. (10061)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

Fatal error: Uncaught PHPMailer\PHPMailer\Exception: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting in C:\xampp\htdocs\email\PHPMailer-master\src\PHPMailer.php:1775 Stack trace: #0 C:\xampp\htdocs\email\PHPMailer-master\src\PHPMailer.php(1516): PHPMailer\PHPMailer\PHPMailer->smtpSend('Date: Mon, 19 N...', 'hello\r\n') #1 C:\xampp\htdocs\email\PHPMailer-master\src\PHPMailer.php(1352): PHPMailer\PHPMailer\PHPMailer->postSend() #2 C:\xampp\htdocs\email\mail3.php(33): PHPMailer\PHPMailer\PHPMailer->send() #3 {main} thrown in C:\xampp\htdocs\email\PHPMailer-master\src\PHPMailer.php on line 1775**

_Originally posted by @vaishnavhiren1993 in https://github.com/PHPMailer/PHPMailer/issue_comments#issuecomment-439873679_

**Comment by Synchro** [comment]
The error message tells you the problem:

> No connection could be made because the target machine actively refused it

Your mail server does not want to talk to you, so you probably have the wrong hostname or port number.

**Comment by vaishnavhiren1993** [comment]
thank you for replay me 

I talk with GoDaddy agents . they said there is scriping error but I can't able to find what is error !
@Synchro can you hep me out of this issue ?

**Comment by Synchro** [comment]
How can I tell you the error in your code without seeing your code? Please post it.
