### ISSUE TITLE
Opening problems

### ISSUE THREAD

**Issue by ddmo** [PHPMailer/PHPMailer#1603]
# Problem description
Hi, in my Laravel application, I can't send any email with phpmailer...

# Code to reproduce
in my controller (called by an ajax call), I've:

    $mail = new PHPMailer\PHPMailer();
    $mail->IsSMTP();
    
    $mail->SMTPDebug = 3;
    $mail->Debugoutput = function($str, $level) {
        file_put_contents('php_error.log', gmdate('Y-m-d H:i:s'). "\t$level\t$str\n", FILE_APPEND | LOCK_EX);
    };

    $mail->SMTPAuth = true;
    $mail->SMTPSecure = 'tsl';
    $mail->SMTPOptions = array(
      'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
      )
    );
    $mail->Timeout = '60';
    $mail->Host = gethostbyname('smtps.****.it');
    $mail->Port = 587;
    $mail->Username = '******';
    $mail->Password = '******';
    $mail->AddAddress('test@pec.it');
    $mail->AddReplyTo("test@pec.it", "Do not reply");
    $mail->SetFrom('test@pec.it', 'Email');
    $mail->IsHTML(true);
    $mail->Subject = "aaa";
    $mail->Body = "<h1>aaa</h1>";
    if(!$mail->Send()){
      error_log('Mailer error: ' . $mail->ErrorInfo);
    } else {
      error_log('Mailer ok');
    }
`

# Debug output
I get only: 
`Connection: opening to 95.110.223.11:587, timeout=60, options=array (
  'ssl' => 
  array (
    'verify_peer' => false,
    'verify_peer_name' => false,
    'allow_self_signed' => true,
  ),
)
`

without any error... any idea?

**Comment by Synchro** [comment]
There is no such value as `tsl` for `SMTPSecure`. It should be `tls` or `ssl`.

I can tell that you've based your code on a very old and obsolete example, so make sure you're using the latest version and bases your code on an up to date example.

**Comment by Synchro** [comment]
Also this:

    $mail = new PHPMailer\PHPMailer();

should be either:

    $mail = new PHPMailer;

if you imported the PHPMailer classes into your namespace (as the docs show), or you could use the FQCN:

    $mail = new PHPMailer\PHPMailer\PHPMailer;
