### ISSUE TITLE
Custom MAIL FROM Domain with Amazon SES

### ISSUE THREAD

**Issue by dertin** [PHPMailer/PHPMailer#1605]
Hi.

I'm using AWS SES to send via PHPMailer from my web server.

In AWS SES configure "[MAIL FROM Domain](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/mail-from.html)" with a custom subdomain, in my case it was "mail.tufiesta.com.uy"

I have everything configured correctly on Router 53.

MX
mail.tufiesta.com.uy
10 feedback-smtp.us-east-1.amazonses.com
 
TXT - SPF
mail.tufiesta.com.uy
"v = spf1 include: amazonses.com ~ all"

And I keep the MX and SPF records for the domain "tufiesta.com.uy"

MX
tufiesta.com.uy
10 inbound-smtp.us-east-1.amazonaws.com.

TXT - SPF
tufiesta.com.uy
"v = spf1 include: amazonses.com ~ all"

And finally, have the following records:

TXT - DMARC
_dmarc.tufiesta.com.uy.
"v = DMARC1; p = quarantine; pct = 100; fo = 1"

CNAME x 3 - DKIM (tufiesta.com.uy, mail.tufiesta.com.uy, amazonses.com)
xxxxx._domainkey.tufiesta.com.uy.
"xxxxxxxxxxxxxxxxxxxxxxxxxxx"

Now my doubt.

When I send an email from [AWS Workmail](https://aws.amazon.com/workmail/), the email validates SPF and DKIM for the custom domain "mail.tufiesta.com.uy"

`Received-SPF: pass (google.com: domain of 010001673d74b9d5-5eed20aa-ec41-41cd-b9b4-788ab010421b-000000@mail.tufiesta.com.uy designates 54.240.11.80 as permitted sender) client-ip = 54.240.11.80; ` the same for DKIM ...

But when I send from my web server with PHPMailer validates for the domain "amazonses.com"

`Received-SPF: pass (google.com: domain of 010001673db39bf0-fccdb476-eba1-450b-89df-41fb8f6aec10-000000@amazonses.com designates 54.240.8.42 as permitted sender) client-ip = 54.240.8.42;`  the same for DKIM ...

In PHPMailer, configure the normal shown in this guide:
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-using-smtp-php.html

Can you help me understand this? 
Thank you

**Comment by Synchro** [comment]
I don't see the confusion - it's different because you're sending from a different server that has a different name?

Are you setting the `Sender` property? if you don't do that, it may be figuring out the host name from PHP defaults, which is what is used as the SMTP envelope sender, but you can specify it explicitly:

    $mail->Sender = 'user@mail.tufiesta.com.uy';
