### ISSUE TITLE
Cross Emails 

### ISSUE THREAD

**Issue by DanielZambranoC** [PHPMailer/PHPMailer#1606]
I'm having a curious problem, I'm sending messages to different recipients using a foreach.

The first while to 1@abc.com 
Body: Hi 1!
The second while a 2@abc.com
Body: Hi 2!

The first post arrives well.

The second email arrives at 1@abc.com and 2@abc.com

What could be going on? I've already checked and the instructions run separately.

I execute in each foreach the call to the function to send mail, and it is only used 1 time:

mail->addAddress($mail)

For each shipment, I have logs and I can see how it runs only 2 times

Mail #1 arrives at 1@abc.com and #2 arrives at 1@abc.com, 2@abc.com

**Comment by Synchro** [comment]
The clue is in the name; `addAddresd` **adds** an address to the recipient list, it does not *set* the recipients. Call `clearAddresses` between your sends. See the mailing list example for how to do that.

**Comment by DanielZambranoC** [comment]
I did what you told me, went to the [example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps) and identified 
mail->clearAddresses();

However, it didn't work, and I got it on the internet:

Mail->clearAllRecipients();

But it didn't work either.

**Comment by Synchro** [comment]
Please show the rest of your code.

**Comment by Synchro** [comment]
$mail->addAddress($mail); 

This makes no sense.

It looks like you have edited out the bits that matter. What are you really passing into addaddress? What is in $ccl?

**Comment by DanielZambranoC** [comment]
> ```
> $mail->addAddress($mail); 
> ```
> This makes no sense.
> 
> It looks like you have edited out the bits that matter. What are you really passing into addaddress? What is in $ccl?

Sorry, I didn't realize that I used the same variable in this setting, but there they are happening in every iteration:

**1@abc.com
2@abc.com**

The string that contains the email address to which the notification should arrive, is only 1 address that is used in each iteration.

**$cc1** is a fixed account in gmail where I send a copy of the sent mail.

I do 2 logs of sent mail, one per database and one in gmail.

**Comment by Synchro** [comment]
Fine, but I can’t help with code if you don’t show it. Where is PHPMailer instanciated? When you say iterate, that suggests a loop. Don’t make me guess what you’re doing!

**Comment by DanielZambranoC** [comment]
Thanks for your time, I will give you all the info you need

```
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require 'vendor/autoload.php';
$class_mail = new PHPMailer(true);  
$class_mail->CharSet = 'UTF-8';

function sendMail(params) {                      
        global $class_mail;
	$mail->isSMTP();
	$mail->Debugoutput = 'html';
	$mail->Host = $smtp;
	$mail->SMTPAuth = true;
	$mail->SMTPKeepAlive = true;
	$mail->Username = $user;
	$mail->Password = $pass;
	$mail->SMTPSecure = 'tls';
	$mail->SMTPSecure = false;
	$mail->Port = 587;
	$mail->setFrom('noreplyemail', 'XXX');
	$mail->addAddress('user thats going to be notified');   
	$mail->addBCC("log_email@gmail.com');
	$mail->isHTML(true);    
        $text = 'Body';
	$mail->Subject = "Subject"
	$body = $text;
	$mail->Body    = $body;

	if(!$mail->send()) {
	    logs()
	}
	$mail->clearAddresses();
        $mail->clearAttachments();

}
```

For each notification sendMail function is executed, and yes, I meant loop.

Sending emails works perfect, I haven't had any problem with that, except now that I'm implementing a reminder system that is mixing my emails.

Your first response fits the problem, except that this function is not properly cleaning the previous address.

**Comment by Synchro** [comment]
You're still editing so much out of your code it's incomprehensible. `function sendMail(params) {` is not even valid PHP, and you're hiding what the params are, there is no looping in your code, so there is no way that the code you have shown can behave as you are describing.

**Comment by DanielZambranoC** [comment]
> You're still editing so much out of your code it's incomprehensible. `function sendMail(params) {` is not even valid PHP, and you're hiding what the params are, there is no looping in your code, so there is no way that the code you have shown can behave as you are describing.

This is the definition of the function, then I query all the people who must be notified, for each result the function must be executed waiting for the mail and the name.

each loop has 1 different mail

```
$persons = QUERY_CALL

		foreach ($persons as $i => $p) {


			$mailE = mailRecordatorio(email,name,datetime,message);

			if($mailE) {
				log
			} 
		}
```

First: 1@abc.com
Second: 2@abc.com

As you might have guessed, it seems that it remains in memory, for the second loop 1@abc.com does not disappear.

I haven't tested if this can be a chain reaction, if I keep incorporating mails, the most probable is that in the third loop the first 2 mails will be incorporated to the sent mail, and so on.

**Comment by DanielZambranoC** [comment]
Took the example I and got the same result

```
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

$mail = new PHPMailer;
$mail->isSMTP();
$mail->Host = 'xxx';
$mail->SMTPAuth = true;
$mail->SMTPKeepAlive = true; // SMTP connection will not close after each email sent, reduces SMTP overhead
$mail->Port = 587;
$mail->SMTPSecure = 'tls';
$mail->Username = 'xxx';
$mail->Password = 'xxx';
$mail->setFrom('xxx', 'List manager');
$mail->Subject = "PHPMailer Simple database mailing list test".rand();
$mail->AltBody = 'To view the message, please use an HTML compatible email viewer!';

$a = dbExec($sX,$pX);

if(count($a)>0) {

	foreach ($a as $r) {

		$p = dbExec($sqlp,$paramsp);

		if(count($p)<1) return false;

		foreach ($p as $i => $p) {

            $mail->msgHTML("Hi!!! $nombre");

            $mail->addAddress($email,$name); 
			if($mail->send()) { 

				log()
			}
		}

		if($error===false) {
			log
		}
		echo "<br/>";
		// Clear all addresses and attachments for next loop
        $mail->clearAddresses();
        $mail->clearAttachments();

	}


}
```

There is a bug with clearAddresses(), hope you can flag it
