### ISSUE TITLE
SMTP connexion error if debug = 0 but not for debug = 2  

### ISSUE THREAD

**Issue by MedShake** [PHPMailer/PHPMailer#1609]
Hello

A very particular behavior encountered with PHPMailer 6.0.5 and 6.0.6 using it via an SMTP.
If I place $mail->SMTPDebug = 0; then the mail is systematically disqualified for sending: connection error.
If I place $mail->SMTPDebug = 2; then the mail always leaves without any problem!
This makes the diagnotic quite difficult !

Here is the script : https://github.com/MedShake/MedShakeEHR-base/blob/master/controlers/patient/actions/inc-action-sendMail-apicrypt.php 

Thank you for your ideas and this script!

B.

**Comment by Synchro** [comment]
Hm. That is tricky!

The debug functions are always called; the `SMTPDebug` setting only determines whether it is displayed or not. What does `ErrorInfo` show when it fails? I'd recommend injecting your own debug output handler (see [the comment for Debugoutput](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L359) to see how to do that).
