### ISSUE TITLE
getLastTransactionID() 

### ISSUE THREAD

**Issue by DonGraham80** [PHPMailer/PHPMailer#1615]
This doesn't provide the correct information to have a userful transaction ID
SMTP.php line 161 $smtp_transaction_id_patterns
        'Microsoft_ESMTP' => '/[0-9]{3} 2.[\d].0 (.*)@(?:.*) Queued mail for delivery/',

I believe an better solution would be 
        'Microsoft_ESMTP' => '/[0-9]{3} 2.[\d].0 .* (\[.*\]) Queued mail for delivery/',

Which will output 
[InternalId=146042404404644, Hostname=YOUR HOST NAME WILL APPEAR HERE]

**Comment by Synchro** [comment]
The Microsoft pattern is actually pretty pointless because all that MS does is repeat your message ID back to you, rather than providing a remote transaction ID like the other supported providers do, so breaking it out further doesn't give you anything you don't already know.
