### ISSUE TITLE
Corporate mail does not arrive

### ISSUE THREAD

**Issue by diegoferia** [PHPMailer/PHPMailer#1620]
Joomla 3.8
mail server: PHPMailer
Template: Rochettheme
Hosting: Godaddy
Dominio: Google
Email: G-Suite
URL:tradelca.com

I come here trying to find a diagnose a problem we have with our corporate emails. That is, what is the source of the error?

We have a website hosted on a Godaddy server, with **Google domain and corporate emails contracted with the Gmail Suite**.  Also a Rockettheme template. The emails are sent from a Contact Form of the Joomla core.

**The problem: The corporate emails of the management@company.com form do not reach their destination.**

- The emails of the form xxxxxx@gmail.com or xxxxx@hotmail.com, have no problems, they arrive at their destination.
- Corporate emails in other environments (outside the Joomla work correctly).
- I made a copy of the site and installed it elsewhere in a test site of the same provider Goodady and there, the PHPmail mail service works perfectly, both for contacts with corporate accounts, as for those who have gmail accounts and / or hotmail. (With joomla updated to version 3.9).
- Goddady says that the Mx are well configured and that since the postal service is external, the problem is not theirs. The guys in the Gmail suite still do not respond. In the forum rockettheme inform that the problem is not the template.
- We have tried without success all the mail services that the Joomla offers in its global configuration.

When sending a message with PHPMailer, the message "sent message" appears, but it does not work for the corporate email accounts. What is the problem?

Thank you very much for your help

**Comment by Synchro** [comment]
This sounds like you have a mail server problem. Once you have successfully submitted a message, PHPMailer's involvement ends. It sounds like you're delivering to your mail server successfully, but then your mail server is failing to deliver the message. You need to check your mail server's logs to find out what's happened to the messages. Bear in mind that GoDaddy has a long history of being *extremely* bad for sending email, as mentioned in the troubleshooting guide.

**Comment by diegoferia** [comment]
Thanks for answering. A final question to clarify.
When you say "You must check the records on your mail server to know what happened to the messages.", It refers to the hosting provider (Godaddy) or the mail service provider (G-suite google). Thank you.

**Comment by Synchro** [comment]
Whoever is responsible for the mail server you send through (whatever is in your `Host` property in PHPMailer). Given that GoDaddy blocks external outbound SMTP, you're likely to be using their servers, in which case you may be out of luck on getting access to logs - but that's the joy of GoDaddy...
