### ISSUE TITLE
Mail is not getting send with blank body

### ISSUE THREAD

**Issue by laurelBE** [PHPMailer/PHPMailer#1622]
Hello,
My mail is getting sent with regular text in body, but when i am giving blank to body field it is not sending and shows error as 

> Message body empty

My code is as below

`
$mail->Subject = $subject;

$mail->WordWrap   = 80;
 
$mail->MsgHTML($body);
$mail->IsHTML(true);

if(!$mail->Send())
	echo $mail->ErrorInfo;

else 
{
echo "Mail Sent";

}`

Please help me

**Comment by Synchro** [comment]
It's a safety net. Most don't want to send empty messages as it's more likely to be an error than intentional, but you can turn off that protection with:

    $mail->AllowEmpty = true;

Code is [here](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L421).
