### ISSUE TITLE
reply button at the bottom

### ISSUE THREAD

**Issue by Vozdr** [PHPMailer/PHPMailer#1625]
Hi!
When I sent test mail to gmail e-mail, on the bottom of letter has ben 3 buttons: "It works!", "Got it!" and
"Success!". But when I send normal letter - answer buttons are not present. How I can add this buttons to letter?
![default](https://user-images.githubusercontent.com/45648715/50338292-b5063800-0535-11e9-9054-eefa32d57967.png)

**Comment by Synchro** [comment]
This sounds like a gmail-specific feature determined by what you put in your message body, which PHPMailer doesn't concern itself with - it just sends whatever you give it.
