### ISSUE TITLE
PHPMailer not function

### ISSUE THREAD

**Issue by Mugna00** [PHPMailer/PHPMailer#1626]
<?php 
	use PHPMailer\PHPMailer\PHPMailer;
	use PHPMailer\PHPMailer\Exception;
	use PHPMailer\PHPMailer\SMTP;
	require 'vendor\autoload.php';
	require "PHPMailer\src\PHPMailer.php";
	require "PHPMailer\src\Exception.php";
	require "PHPMailer\src\SMTP.php";
	$mail=new PHPMailer();
	$mail->Mailer = 'smtp';
	$mail->isSMTP();
	$mail->Host = "smtp.gmail.com";
	$mail->Port=587;
	$mail->SMTPAuth = true;
	$mail->SMTPSecure="ssl";
	$mail->Username="...@gmail.com";
	$mail->Password="secret";
	$mail->addAddress("...@gmail.com");
	$mail->Subject = 'subject';
	$mail->Body = 'body';
	try
	{
		$app=$mail->send(true);
		if($app)
		{
			echo "Inviata";
		}
		else
		{
			echo "Non Inviata";
		}
	}
	catch (Exception $e)
	{
		echo '<script>pop("mail non  Inviata");</script>';
	   echo $e->errorMessage();
	}
	catch (\Exception $e)
	{
		echo '<script>pop("mail non Inviata");</script>';
	   echo $e->getMessage();
	}
	
?>

**Comment by Synchro** [comment]
Read the troubleshooting guide. I can’t tell what your issue is from what you posted.
