### ISSUE TITLE
PHPMailer not function

### ISSUE THREAD

**Issue by Mugna00** [PHPMailer/PHPMailer#1627]
![codicemail](https://user-images.githubusercontent.com/46057469/50373514-82fde000-05e0-11e9-9985-d513f333bc85.png)
Invalid address: (From): root@localhost

**Comment by Mugna00** [comment]
I do not understand where the problem is

**Comment by Synchro** [comment]
`setFrom` is a method, not a property, so you need to call it like this:

    $mail->setFrom('lorenzomugnai43@gmail.com');
