### ISSUE TITLE
PHPMailer working in localhost but not working in my server

### ISSUE THREAD

**Issue by sonnyR** [PHPMailer/PHPMailer#1628]
I'm trying to send a mail that is contents html to some person. This code works fine on Wamp (localhost with smtp.gmail.com)  but doesn't work on server (always I have the message Mail Not Sent). What am I doing wrong?

<?php

    $mailto = $_POST['email'];
	$name = $_POST['first_name'];

  require_once 'PHPMailer-master/PHPMailerAutoload.php';
   $mail = new PHPMailer();
   $mail ->IsSmtp();
   $mail ->SMTPDebug = 0;
   $mail ->SMTPAuth = true;
   $mail ->SMTPSecure = 'ssl';
  //$mail ->Host = "smtp.gmail.com";
  $mail ->Host = "securesmtp.t-online.de";
   $mail ->Port = 465; // or 587
   $mail ->IsHTML(true);
   $mail ->Username = "xxx@gmail.com";
   $mail ->Password = "xxx";
   $mail ->SetFrom("xxx@gmail.com");
   $mail ->Subject = 'Code';
   $mail ->Body = 'Hi  <b>'.$name.', </b> 
   Thank you.<br>
';
   $mail ->AddAddress($mailto);

   if(!$mail->Send())
   {
     echo "Mail Not Sent";

   }
   else
   {
       echo "Email Sent Successfully";

   }

?>

**Comment by Synchro** [comment]
Read the troubleshooting guide - your hosting provider is probably blocking outbound SMTP.

**Comment by sonnyR** [comment]
@Synchro ,not the outbound  SMTP protocol is not blocked because I have an email address with the same configuration and I can send and receive emails there is no problem.
![capture](https://user-images.githubusercontent.com/33217157/50470086-911c7980-09af-11e9-91fc-3e6e6a2f8197.PNG)

**Comment by Synchro** [comment]
That’s not what it shows; It shows that your *local computer* does not block SMTP, which is nothing to do with whether *your server* does. Do the tests in the guide.

**Comment by sonnyR** [comment]
@Synchro, I tested the examples located in the guide. I always have this error.
![error](https://user-images.githubusercontent.com/33217157/50477932-d7cd9c00-09ce-11e9-9b96-ec65416f06da.PNG)
This is the first time I use PHPmailer on my server,I am asking you to help me to solve this problem

**Comment by Synchro** [comment]
Read the guide again. Many of the tests do not use PHP. Error 500 means you need to look at your server’s error log. I can’t magically solve this for you unless you do what I ask.

**Comment by sonnyR** [comment]
@Synchro okay thank you so much.

**Comment by sonnyR** [comment]
I replaced issmtp () with ismail () and it works fine.

**Comment by Synchro** [comment]
Be aware that that isn’t actually solving your problem, just avoiding it.
