### ISSUE TITLE
stream_select warning FD_SETSIZE

### ISSUE THREAD

**Issue by PDFCoder** [PHPMailer/PHPMailer#1631]
We run into a problem on our live server (debian, PHP 7.1) with phpmailer 6.0.6 – everything has been working fine there with version 5.2.x.

If we try to send an email (can even be a simple text, or the smtp_check of the sample files!) we get a php warning and the server is running into a timeout:

PHP Warning:  stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.
It is set to 1024, but you have descriptors numbered at least as high as 1314.
 --enable-fd-setsize=2048 is recommended, but you may want to set it
to equal the maximum number of open files supported by your system,
in order to avoid seeing this error again at a later date. in /home/www/xxx/phpmailer/src/SMTP.php on line 1125

Our hoster won't recompile PHP, so the suggested solution won't work.

We made some futher tests and found out, that the stream_select if condition in line 1125 didn't exist in phpmailer 5.2.x. If we delete this condition, everythings seems to work fine again (as far as we could test it now; with bigger mails, attachments).

if (!stream_select($selR, $selW, $selW, $this->Timelimit)) { …

If we set the timelimit of the function to a small value (like 3 seconds) the server loops a warning to the error log until the script is terminated:
PHP Warning:  stream_select(): No stream arrays were passed in /home/www/xxx/phpmailer/src/SMTP.php

So what is the idea behind the stream_select condition? Is there a fix to this problem?

On other servers/accounts (same setup) the problem does not appear …!? Any idea?

**Comment by Synchro** [comment]
This doesn't require recompiling PHP, but it does require being able to alter runtime file descriptor limits, usually via sysctl, which you may also not have access to, but your ISP may be able to alter that. The origin of this use of stream select is [here](https://github.com/PHPMailer/PHPMailer/issues/604). You can see that it replaced a simpler timeout mechanism that failed in other ways. You could create a child class and override that usage (e.g. by reverting to the old implementation) as a workaround, but be aware that doing that may create other problems elsewhere.

**Comment by dpeca** [comment]
Very interesting thing is that:
- When PHP is running on Apache (mod_php) - bug occur
- When PHP is running on PHP-FPM - there is no bug
- When PHP is running from SSH console - there is no bug

Tested on the same machine.
Debian9, php packages from sury.org

**Comment by dpeca** [comment]
And, btw, in sysctl.conf we have
`fs.file-max = 200000`
And in limits.conf we have
```
* soft     nofile         200000
* hard     nofile         200000
```

So file descriptors ar not limited at all...

**Comment by dpeca** [comment]
Btw, solution that @PDFCoder found (to comment `if (!stream_select`) solved a problem.

**Comment by Synchro** [comment]
I'd recommend double-checking what the apache user's file limits actually are, for example run `sudo -u www-data bash` and then `ulimit -n`. IME it's common to find large global settings, but then to find that individual processes/users have the default 1024 handle limit.

**Comment by chriscroome** [comment]
I've come across this issue and it doesn't appear to depend on the user that is running Apache and their files limits, it also doesn't appear to depend on PHP, Apache and OpenSSL being recompiled to support more than 1024 file descriptors, I have [tried to address this by re-building Debian packages](https://deb.webarch.net/), this [Plesk guide](https://docs.plesk.com/en-US/onyx/advanced-administration-guide-linux/enhancing-performance/increasing-the-number-of-domains-that-plesk-can-serve.68766/) suggests that `libc-client2002edebian` also needs rebuilding, this is now the [libc-client2007e package](https://packages.debian.org/stretch/libc-client2007e) and it provides the `uw-imap` library, I couldn't get this to recompile, could this be where the problem lies?

**Comment by dpeca** [comment]
@Synchro 

```
root@server:~# sudo -u www-data bash
www-data@server:/root$ ulimit -n
200000

```

**Comment by Synchro** [comment]
OK, so it's not that. Can you see if your PHP is built with its own FD limit, as @PDFCoder mentioned?

**Comment by dpeca** [comment]
I'm pretty sure we would have much larger issues if ulimit is 1024...

@Synchro 
How I can check it?

**Comment by chriscroome** [comment]
This is how I checked the `enable-fd-setsize` variable on Debian Stretch:

```bash
apt install -y php-dev
php-config --configure-options | sed 's/\s\+/\n/g' | grep enable-fd-setsize
```

But having it set to a value higher than 1024 doesn't actually appear to help&hellip;

**Comment by dpeca** [comment]
I got just empty output with it, @chriscroome

**Comment by dpeca** [comment]
```
# php-config7.0 --configure-options
--includedir=/usr/include --mandir=/usr/share/man --infodir=/usr/share/info --disable-silent-rules --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --enable-cli --disable-cgi --disable-phpdbg --with-config-file-path=/etc/php/7.0/cli --with-config-file-scan-dir=/etc/php/7.0/cli/conf.d --build=x86_64-linux-gnu --host=x86_64-linux-gnu --config-cache --cache-file=/build/php7.0-7.0.33/config.cache --libdir=${prefix}/lib/php --libexecdir=${prefix}/lib/php --datadir=${prefix}/share/php/7.0 --program-suffix=7.0 --sysconfdir=/etc --localstatedir=/var --mandir=/usr/share/man --disable-all --disable-debug --disable-rpath --disable-static --with-pic --with-layout=GNU --without-pear --enable-filter --with-openssl=yes --with-pcre-regex=/usr --enable-hash --with-mhash=/usr --enable-libxml --enable-session --with-system-tzdata --with-zlib=/usr --with-zlib-dir=/usr --enable-dtrace --enable-pcntl --with-libedit=shared,/usr build_alias=x86_64-linux-gnu host_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/build/php7.0-7.0.33=. -fstack-protector-strong -Wformat -Werror=format-security -O2 -Wall -pedantic -fsigned-char -fno-strict-aliasing -g

```

**Comment by chriscroome** [comment]
Empty output means it has the default of 1024 as far as I could work out.

**Comment by chriscroome** [comment]
I you have a dev / test Stretch server feel free to try the debs I built which are available here https://deb.webarch.net/ they have `--enable-fd-setsize 2048` but server running them still hit the limit, it appears to make no difference&hellip;

**Comment by Synchro** [comment]
I'm not sure at what point the limit is applied - for example if it's per-process and you're running under a non-threaded SAPI like mod_php, you're less likely to run into it than if you're using a threaded single process like PHP-FPM.

I'd also expect that if you're running into a limit like this, it's likely to occur in at least slightly random random places, rather than consistently the same place. It would be useful to get someone with PHP internals knowledge on this.

**Comment by dpeca** [comment]
Both Apache (with mod_php) and PHP-FPM are configured to switch to user - so it's not www-data for sure.
For Apache i'm using mod_ruid2 to switch user...
I'm testing PHPMailer as user that only runs that phpmailer test script.

And as I previously said, there is no issues if script is run through PHP-FPM.
Hard to believe that mod_ruid2 is not doing proper user switching... I'm running 50 servers with mod_ruid2, everything works fine with switching-to-user functionality... 

But again, I expect pretty much issues if scripts reach ulimits... but we don't have any issues, even we hosts 200 sites on that server.
This is the first time to see error abozr FD_SETSIZE...

**Comment by chriscroome** [comment]
I'm using [Apache 2 ITK MPM](http://mpm-itk.sesse.net/), it is [in Debian](https://packages.debian.org/stretch/libapache2-mpm-itk), I haven't come across mod_ruid2 before, I see that this is also [in Debian](https://packages.debian.org/stretch/libapache2-mod-ruid2), I guess they do more-or-less that same thing&hellip;

**Comment by eldy** [comment]
Same trouble here on ubuntu 18.04, apache2 and thousands of virtual hosts using with mpm_itk.
The limit is reached only when using phpmailer. A lot of other application using other email library are working correctly. 
Note that the trouble occurs when doing an action as simple as sending 1 email and only 1 email from 1 instance. It is strange than the library needs to open so many files, just to send 1 email.
Never mind, I confirm that solution of @PDFCoder found (to comment if (!stream_select) solved the problem on our side too.

**Comment by Synchro** [comment]
It's not the library opening "so many" files. It's the library opening  _1_ file, and PHP not having enough file descriptors available to let it happen.

**Comment by mj-mehdizadeh** [comment]
this was helped me
https://bugs.php.net/bug.php?id=37025

**Comment by benjamin-lieser** [comment]
The problem is caused because of a `stream_select()` call in PHPMailer. The select syscall is discouraged because of the limitations: https://man7.org/linux/man-pages/man2/select.2.html . As long as php uses the select syscall to implement the stream_select() function this will be a problem.
In PHPMailer we do not need the full functionality because it's just waiting on one socket.
Is there a reason why against a simple blocking socket with `socket_set_block` and `socket_read`?
Right now this makes version 6 unusable in some environments. And also makes it slower in case the FD_SETSIZE is high enough.

**Comment by Synchro** [comment]
I don't know the internals implications of the stream_select, but I do recall that it was introduced in PHPMailer to avoid a different bug in #604.

If you have a better and more reliable way to implement this, PRs are welcome.

**Comment by kylex** [comment]
We're also running up against this issue, and would love to see a solution that doesn't involve having to recompile PHP.

**Comment by Synchro** [comment]
As mentioned [earlier in this thread](https://github.com/PHPMailer/PHPMailer/issues/1631#issuecomment-451954108), you can revert to the old behaviour (complete with its accompanying, but different bugs) by providing your own child class that overrides just the `get_lines` method, and how you do that is shown in [this doc](https://github.com/PHPMailer/PHPMailer/wiki/Overriding-the-SMTP-class).

**Comment by benjamin-lieser** [comment]
> As mentioned [earlier in this thread](https://github.com/PHPMailer/PHPMailer/issues/1631#issuecomment-451954108), you can revert to the old behaviour (complete with its accompanying, but different bugs) by providing your own child class that overrides just the `get_lines` method, and how you do that is shown in [this doc](https://github.com/PHPMailer/PHPMailer/wiki/Overriding-the-SMTP-class).

Are we sure the old version is still buggy, because it was correct php, but there were problems in the php implementation, which might have been fixed.
It's hard to produce something which works in all cases, because we have to build on a really subpar php implementation around the io systemcalls

**Comment by Synchro** [comment]
Could be, but I don't know enough about PHP internals to judge. It could do with someone who actually knows rather than guessing. Also remember we still maintain compatibility back to PHP 5.5.
