### ISSUE TITLE
How can we add custom headers  and UTF-8 support ?

### ISSUE THREAD

**Issue by flik** [PHPMailer/PHPMailer#1633]
# Problem description
I want to add customer headers and UTF-8 support for multi-languages

# Code to reproduce

# Debug output

**Comment by Synchro** [comment]
Both are built-in.

Enable UTF-8 (note you need the `mbstring` PHP extension, which is why it's not enabled by default):

    $mail->CharSet = 'utf-8';

To set a custom header:

    $mail->addCustomHeader('MyCustomHeader', 'my custom value');

**Comment by flik** [comment]
thanks
