### ISSUE TITLE
Mailer Error: SMTP connect() failed, but only SOMETIMES

### ISSUE THREAD

**Issue by skyale** [PHPMailer/PHPMailer#1635]
# Problem description

Hi, I have this problem, but only SOMETIMES, so everything is correct (settings and so on) but once a day (more or less) I get:

2019-01-16 14:38:23 SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Name or service not known (0)

I read that it can be a host problem, but I'm using email-smtp.eu-west-1.amazonaws.com so I think that it's ok.

My server is in a server farm, and it works like a charm.

I send only single emails, to existing email addresses.

I'm using the latest version of PHPMailer.

Here the details:

# Code to reproduce

<?php
namespace MyProject;
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require 'PHPMailer-master/src/Exception.php';
require 'PHPMailer-master/src/PHPMailer.php';
require 'PHPMailer-master/src/SMTP.php';

$mail = new PHPMailer;

$mail->IsSMTP();                                      // Set mailer to use SMTP
$mail->Host = 'email-smtp.eu-west-1.amazonaws.com';  // Specify main and backup server
$mail->Port = 587; // la porta che dobbiamo utilizzare
//Set the encryption system to use - ssl (deprecated) or tls
$mail->SMTPSecure = 'tls';
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'xxxx';                            // SMTP username
$mail->Password = 'xxx';                           // SMTP password
//$mail->SMTPSecure = 'ssl';                            // Enable encryption, 'ssl' also accepted
$mail->CharSet = "UTF-8";

$mail->From = 'xxx';
$mail->FromName = 'xxx';
$mail->AddAddress('xxx');               // Name is optional

$mail->WordWrap = 50;                                 // Set word wrap to 50 characters

$mail->Subject = 'Invio verifica parametri SMTP';
$mail->Body    = 'testo del messaggio';
$mail->IsHTML(true);                                  // Set email format to HTML

// Converto il testo HTML in Plain Text (per evitare penalizzazione da SpamAssassin / mail-tester.com)
require_once('src/Html2Text.php');
$messaggio_plain_text_1 = new \Html2Text\Html2Text($messaggio);
$messaggio_plain_text = $messaggio_plain_text_1->getText();
$mail->AltBody = $messaggio_plain_text;

// Before the send
$smtpLogs = [];
$mail->SMTPDebug = 2;
$mail->Debugoutput = 'logHandler';

if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
    $codice_errore = $mail->ErrorInfo;
    $errore = "email NON INVIATA!!! ".$codice_errore;
    // Se c'è un errore, setto da_controllare a 1 (e dopo aver controllato lo aggiorno a 0), altrimenti a 0:
    $da_controllare = 1;
} else {
    echo "Message sent!";
    $errore = "email inviata";
    // Se c'è un errore, setto da_controllare a 1 (e dopo aver controllato lo aggiorno a 0), altrimenti a 0:
    $da_controllare = 0;
}

// After the send
print_r($mail->ErrorInfo);
printLogs($smtpLogs);

function logHandler($log, $level)
{
    global $smtpLogs;

    $smtpLogs[] = trim($log);
}

function printLogs(array $logs)
{
    echo implode(" --- ", $logs);
}

?>

# Debug output

2019-01-16 14:38:23 SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Name or service not known (0) 2019-01-16 14:38:23 SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/TroubleshootingSMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by aalfiann** [comment]
`php_network_getaddresses: getaddrinfo failed: Name or service not known`

means DNS have problem to communicate to your server.

**Comment by Synchro** [comment]
Yep, this is a problem with DNS config on your server, not your code or PHPMailer.
