### ISSUE TITLE
PHPMailer not sending

### ISSUE THREAD

**Issue by Wouterkaas** [PHPMailer/PHPMailer#1638]
Hello, i coded a php file with paypal ipn listener, when i remove the follow code of php mailer it works fine and it gets verified, but when i put it back it doesnt work, but i need to send an email to the customer. I have PHPMailer version 5.2 and i have 2 step verification off in gmail and i have unauthorized apps turned on. Here is the code, Please help me because i am struggeling with this for over 3 months now and it is slowing down the process of starting my company.

```php
require 'PHPMailerAutoload.php';

$mail = new PHPMailer;
$mail->Host = "smtp.gmail.com";
$mail->isSMTP();
$mail->SMTPAuth = true;
$mail->Username = "evolvingdesk@gmail.com";
$mail->Password = "password";
$mail->SMTPSecure = "ssl";
$mail->Port = 465;
$mail->Subject = "Je aankoop bij Evolvingdesk";
$mail->Body = "Goede morgen!";
$mail->setFrom('evolvingdesk@gmail.com', 'Evolvingdesk');
$mail->addAdress('boogwout@gmail.com');
$mail->send();
```

**Comment by Synchro** [comment]
There is not enough information to go on here. Please read the troubleshooting guide. Update to the latest version and base your code on the examples provided - part of the reason that you don't know what's wrong is that you're not doing any error checking.

**Comment by Wouterkaas** [comment]
I can't because i cant go to the page only paypal can

**Comment by Synchro** [comment]
That makes no sense at all. The code you posted has nothing to do with paypal.
