### ISSUE TITLE
$mail->AddAttachment - Could not access file:

### ISSUE THREAD

**Issue by hermabritz** [PHPMailer/PHPMailer#1645]
# Problem description
 
I am trying to add a .pdf attachment to my mail, but the attachment don't get send. I log the error message for the attachment in my db and i get the error message "Could not access file:". The rest of the email is sending without a glitch. So  essence the mail does get send but without the attachment.

# Code to reproduce

```php
<?php
    
    //Import PHPMailer classes into the global namespace
    use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\SMTP;
    use PHPMailer\PHPMailer\Exception;

    require 'PHPMailer.php';
    require 'SMTP.php';
    require 'Exception.php';  

    session_start();

    include("connection.php"); 

    $query = "SELECT * FROM `emailLog` WHERE `emailStatus` = 'unsent'";

    $resultEmailLog = mysqli_query($link, $query);
    
    if (mysqli_num_rows($resultEmailLog) != 0) {         
        
        while ($rowEmailLog = mysqli_fetch_assoc($resultEmailLog)) { 
            
            //Create a new PHPMailer instance
            $mail = new PHPMailer;

            //Tell PHPMailer to use SMTP
            $mail->isSMTP();
            
            //Enable SMTP debugging
            // 0 = off (for production use)
            // 1 = client messages
            // 2 = client and server messages
            $mail->SMTPDebug = 0;
            
            //Set the hostname of the mail server
            $mail->Host = 'mail.petpa.co.za';
            // use
            // $mail->Host = gethostbyname('smtp.gmail.com');
            // if your network does not support SMTP over IPv6

            //Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
            $mail->Port = 465;

            //Set the encryption system to use - ssl (deprecated) or tls
            $mail->SMTPSecure = 'ssl';

            //Whether to use SMTP authentication
            $mail->SMTPAuth = true;

            //Username to use for SMTP authentication - use full email address for gmail
            $mail->Username = "admin@petpa.co.za";

            //Password to use for SMTP authentication
            $mail->Password = "Admin2018!";

            //1 & 2
            $mail->addAddress($rowEmailLog["sendAddress"], $rowEmailLog["sendUser"]);                //To Address
            $mail->addAddress($rowEmailLog["copyAddress"], $rowEmailLog["copyUsername"]);
            
            $mail->setFrom($rowEmailLog["fromAddress"], $rowEmailLog["fromUser"]);    //From Address
            //$mail->addReplyTo($sendAddress, $sendUsername);           //Reply Address
            $mail->Subject = $rowEmailLog["emailSubject"];     
            


            //Attachments

            if ($rowEmailLog["emailType"] == "Welcome") {

                $my_path = "attachments/userprofilemanual.pdf";

                

                if (!$mail->AddAttachment($my_path)) {
    
                    //$mail->ErrorInfo;

                    $query = "UPDATE `emailLog` SET `emailStatus` = '".$mail->ErrorInfo."' WHERE `emailLogID` = '".$rowEmailLog["emailLogID"]."' LIMIT 1";

                    mysqli_query($link, $query);

                    
                }


                

    
            }

            

            //Replace the plain text body with one created manually
            $mail->isHTML(true); 
            //$mail->Body    = $sendBod;
            //$mail->AltBody = $sendBod;

            $mail->MsgHTML($rowEmailLog["emailMessage"]);

            //$mail->AltBody(strip_tags($message));
            

            //send the message, check for errors
            if (!$mail->send()) {
                echo "Mailer Error: " . $mail->ErrorInfo;

                $query = "UPDATE `emailLog` SET `emailStatus` = '".$mail->ErrorInfo."' WHERE `emailLogID` = '".$rowEmailLog["emailLogID"]."' LIMIT 1";

                mysqli_query($link, $query);

               

            } else {

                echo "Message sent!";

                $query = "UPDATE `emailLog` SET `emailStatus` = 'send' WHERE `emailLogID` = '".$rowEmailLog["emailLogID"]."' LIMIT 1";

                mysqli_query($link, $query);

            }



        }

    } else {

        echo "No Message to sent!";

    }

?>
```

What might be the reason for this?

**Comment by Synchro** [comment]
There are many reasons why you might not be able to access the file, but the most likely are that the file does not exist, you've got the path wrong, or you don't have permission to read it. If you don't want to send without the attachment, then don't call `send` if the call to `addAttachment` returns false - at the moment you're logging the error and carrying on.

**Comment by hermabritz** [comment]
Hi,

Thanks for the feedback.

I have made double sure the file does exist and i have copied the file name  from the server directly to make sure there isn't a spelling mistake. I have given the folder as well as the file Read, Write, and Execute permission, but still no luck.

Don't know if it will have an effect but i am hosting the cite through cpanel.

**Comment by Synchro** [comment]
If you do `ls -al /path/to/file` in your shell, it will show you what user and group it's owned by, and what permissions they, (and everybody else) have. You might also want to check your logs for SELinux or apparmor access contraventions on where you web server or PHP service can access. I've no idea what cpanel might do.

**Comment by hermabritz** [comment]
Hi Syncro,

It seems the problem only occurs when i run the php file as a cronjob via cpanel. If i run the file "manually" it send the mails with attachments.

It seems that the cronjob is running the file as a cronjob user and that cronjob user do not have permission to access the attachments.

I edited my cronjob command from the php processor to wget-q to execute the web address of the file rather than processing the php file locally on linux. This of course cause made my php file run under the correct user who does have permission to the attachments.

Thanks for looking into it in any way. Problem solved.

**Comment by heysushil** [comment]
Hi, I'm using latest phpmailer file and it just ok until i used with core php but when I moved codeigniter then the code working perfectly but the attachment file not sending with mail and showing this message on debug == add attachment could not access file
I tried mainy ways but still didn't get the attachment file. How provide this access

**Comment by Synchro** [comment]
You need to set correct permissions and ownership on the files you're trying to attach. What that is depends on your system, not your PHPMailer code.

**Comment by heysushil** [comment]
Yap, Synchro, Got that the problem was on php.ini file but still am confused about it. Question is why on core php everything worked and why on Codeigniter it just not. Is this because of Codeigniters own email library or something else.

**Comment by Synchro** [comment]
Unless you're running the same code as the same user on the same server, it will be your environment. Double check owners, permissions, paths.
