### ISSUE TITLE
filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated

### ISSUE THREAD

**Issue by ortreum** [PHPMailer/PHPMailer#1647]
PHP 7.3.1 throws deprication error:

PHP Fatal error:  Uncaught ErrorException: filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated in /var/www/clients/client1/web2/subdomain/api/ddd/vendor/phpmailer/phpmailer/src/PHPMailer.php:3599
Stack trace:
#0 [internal function]: common\PHPError->handle(8192, 'filter_var(): e...', '/var/www/client...', 3599, Array)
#1 /var/www/clients/client1/web2/subdomain/api/ddd/vendor/phpmailer/phpmailer/src/PHPMailer.php(3599): filter_var('http://abcde', 273, 131072)
#2 /var/www/clients/client1/web2/subdomain/api/ddd/vendor/phpmailer/phpmailer/src/PHPMailer.php(3565): PHPMailer\PHPMailer\PHPMailer::isValidHost('abcde')
#3 /var/www/clients/client1/web2/subdomain/api/ddd/vendor/phpmailer/phpmailer/src/PHPMailer.php(2304): PHPMailer\PHPMailer\PHPMailer->serverHostname()
#4 /var/www/clients/client1/web2/subdomain/api/ddd/vendor/phpmailer/phpmailer/src/PHPMailer.php(1421): PHPMailer\PHPMailer\PHPMailer->createHeader()
#5 /var/www/clients/client1/web2/subdomain/api/ddd/vendor/phpmailer/phpm in /var/www/clients/client1/web2/subdomain/api/ddd/vendor/phpmailer/phpmailer/src/PHPMailer.php on line 3599

**Comment by Synchro** [comment]
This was fixed long ago.

**Comment by ortreum** [comment]
I only get the version of 2018-03-27 with npm even after deleting phpmailer ... but thx for pointing me on this problem.

**Comment by Synchro** [comment]
npm? Not composer?
