### ISSUE TITLE
Could not connect to SMTP host.

### ISSUE THREAD

**Issue by bitnetcoin** [PHPMailer/PHPMailer#1648]
# Problem description
SMTP Error: Could not connect to SMTP host.
Message could not be sent.Mailer Error: SMTP Error: Could not connect to SMTP host.
# Code to reproduce
it says unable to connect php SMTP server But in actual php mailer send email excluding gmail smtp.
the code and library works exactly perfect. but it return unable to connect to smtp server for gmail
 please give me some solution.
thank you .

**Comment by Synchro** [comment]
Please read the docs you were pointed at.
