### ISSUE TITLE
Typo in variable name in DKIM_Add in src/PHPMailer.php, potential for unexpected state

### ISSUE THREAD

**Issue by eurozerozero** [PHPMailer/PHPMailer#1654]
# Problem description

First post on GitHub... hello all.

I noticed that there are two typos of a variable name in DKIM_Add in src/PHPMailer.php on lines 4338 and 4339 which, I assume, could lead to an unexpected state.  On both lines, the variable $current is written as $$current:

https://github.com/PHPMailer/PHPMailer/blob/0c41a36d4508d470e376498c1c0c527aa36a2d59/src/PHPMailer.php#L4338
https://github.com/PHPMailer/PHPMailer/blob/0c41a36d4508d470e376498c1c0c527aa36a2d59/src/PHPMailer.php#L4339

**Comment by Synchro** [comment]
Welcome to github. Sorry to say that's not a typo, it's intentional - it's a [variable variable](http://php.net/manual/en/language.variables.variable.php).

**Comment by eurozerozero** [comment]
Ah!  Great!  (and that now makes the routine make sense)  Thank you!
