### ISSUE TITLE
Duplicate “To: undisclosed-recipients”

### ISSUE THREAD

**Issue by robGuess** [PHPMailer/PHPMailer#1656]
Looking at version 6.0.7. In function createHeader() “To: undisclosed-recipients” is added if both $this→to and $this→cc are empty.  So if a mail contains neither to addresses nor cc addresses as would be the case when the message is being forwarded bcc with original to/cc addresses in a custom header then  createHeader() will add “To: undisclosed-recipients. This then results in the mail being bounced with the error message “550 Messages should have one or no To headers, not 2.”

This scenario occurs when creating a custom mail forwarding process which splits a group email address and sends it bcc to the individual members of the group. Here the original group email address will be added as a custom header (along with any other non group recipients of the mail) so that each of the individual group members can reply to all the original recipients of the message without PHPMailer sending a duplicate message to all the non group members.

This can be fixed by using the following code in here and in preSend where the same thing happens for mail transport only.
		// ### To stop duplicate To: headers in email ###
		$addUndisclosed = true;
		foreach ($this->CustomHeader as $header){
			if($header[0] == 'To'){ $addUndisclosed = false; }
		}
		if($addUndisclosed){
			$result .= $this->headerLine('To', 'undisclosed-recipients:;');
		}

sample code to create issue where ‘group@company.co’ is the group email address being expanded into individual members (‘group.member1@home.co’, ‘Group Member 1’) etc.
$mail = new PHPMailer();
$mail->IsSMTP();
$mail->Host = 'proXXX.hostpapa.com';
$mail->SMTPAuth	= true;  
$mail->Port		= 587;
$mail->Username	= ######
$mail->Password	= ######
$mail->AddReplyTo(‘sender@source.co’, ‘sender Name’);
$mail->SetFrom(‘sender@source.co’, ‘sender Name’);
$mail->Sender = ‘sender@source.co’;
$mail->Subject =’Duplicate To header’;

$mail->addCustomHeader(‘To’, ‘group@company.co’);
$mail->Body = ‘<html><body>Body text</body></html>;
$mail->AltBody = ‘Body text’;
$mail->isHTML(true);
$mail->addBCC(‘group.member1@home.co’, ‘Group Member 1’);
$mail->addBCC(‘group.member2@home.co’, ‘Group Member 2’);
//Add DKIM Signature
$mail->Send();

email that had been bounced (addresses modified)
Return-path: <devtest@xxx.co.uk>
Received: from proXXX.hostpapa.com ([64.34.75.143]:42780)
	by proXXX.hostpapa.com with esmtpsa (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.91)
	(envelope-from <devtest@xxx.co.uk>)
	id 1gsoAR-002AGe-3x
	for robinx@sb.co; Sun, 10 Feb 2019 12:25:03 +0000
Date: Sun, 10 Feb 2019 12:25:02 +0000
To: undisclosed-recipients:;
From: "devtest (Originally from robin)" <devtest@xxx.co.uk>
Reply-To: "devtest (Originally from robin)" <devtest@xxx.co.uk>
Subject: Fwd: checking mail delivery
Message-ID: <5a13fead9f39a7320fe3bd13ac6eae64@proXXX.hostpapa.com>
X-Mailer: POG Mail Queue
To: devtest <devtest@xxx.co.uk>
References: <73b8f675-0f5f-f692-9038-5200c1bf89dc@sb.co>
In-Reply-To: <73b8f675-0f5f-f692-9038-5200c1bf89dc@sb.co>
List-Unsubscribe: <https://xxx.co.uk/details/myAccount.php>
X-Listid: 25649
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; l=72; s=phpmailer;
	t=1549801502; c=relaxed/simple;
	h=From:To:Date:Subject;
	d=pog-cssa.co.uk; i=devtest@xxx.co.uk;
	z=From:=20"devtest=20(Originally=20from=20robin)"=20<devtest@xxx.co.uk>
	|To:=20devtest=20<devtest@xxx.co.uk>
	|Date:=20Sun,=2010=20Feb=202019=2012:25:02=20+0000
	|Subject:=20Fwd:=20checking=20mail=20delivery;
	bh=pB8Yvwttd/bzcNx5Z1rE/wkRcoCo+j4++tF6SoV/Plw=;
	b=FUFn9j5scKLXEDHh6JKq5FPY8eTmOj5/qenQlmEj7XsXhtxgWUIpXAfXtt7RUW9MF2GtMwRQ0TpF+udhNuvEyMu97Zi+sgMICWe9LmFzW6YJmzDXDpCndoWtsp3KaNWfc2W1r+5OrbK832e2gcjouapgFKU7Of136gwP8FBxHao=
X-OutGoing-Spam-Status: No, score=-0.1

Hi

This is to check that the mail is delivered correctly

Robin

**Comment by Synchro** [comment]
Could you turn this into a PR please?

**Comment by Synchro** [comment]
I'm not entirely clear why this is a PHPMailer issue. If you want the group address to appear in the to header, set it as the to address - that way you won't have a duplicate. If you just want to control where replies go, use a reply-to header - it's what it's for.

**Comment by robGuess** [comment]
Marcus

If as you suggest, the group address is set as a To address, then 
PHPMailer will send the message to that address but the message has 
already been sent to that address. It is the Mail forward for that 
address that is being processed and sent to PHPMailer. I can handle that 
in the code however when the To or CC includes other addresses than the 
group address, then the problem occurs because in that case PHPMailer 
would send the mail (which has already been sent to the non group 
members) a second time. I can not see a way of including the non group 
addresses as either To or CC without PHPMailer actually sending the 
message to those addresses without putting them in the header.

Robin

**Comment by Synchro** [comment]
Surely if you don't want messages to be sent to those addresses, don't add them to the To list?
Is it that you want the message to be sent to a set of recipients which is different from the sum of to, cc & bcc? If so, that's not something you can control through message headers; it requires intervention at the SMTP level and provision of some alternative/separate source of the list of recipients.

**Comment by robGuess** [comment]
You say that to achieve what is needed, and alternative list of 
recipients is required fort he SMTP server. Surely that is what the To: 
and CC: headers are. When a message is sent out by a client then each 
SMTP server receives a copy of the To: and Cc headers but only forwards 
them to the destination. If you try and replicate this behaviour using 
PHPMailer by including To:/CC: headers to show the original group 
destination then PHPMailer adds the incorrect duplicate To: header for 
undisclosed recipients but does not flag this as an error. The SMTP 
server then rejects the message as invalid because it has more than one 
To: header. It is this error that I am trying to stop.

As an example sender@domain1.com sends message to recipient1@domain2.com 
and group1@domain3.com. Then forwarder for group1@domain3.com sends the 
message using PHPMailer to member1@domain4.com and member2@domain5.com. 
Member1 and member2 also need to know that the original message went to 
recipient1 so that when they click reply to all, recipient1 is included 
in list of recipients.  Unless you add a To: header how can you format 
the message to member1 and member2 which enables this with out sending 
the message a second time to recipient1?

Robin

**Comment by Synchro** [comment]
No, that's not what they are for. The message and how it is conveyed are entirely independent things - it's entirely possible for an SMTP server to send a message to an address not listed in headers, and the reverse - not sending it to an address that is listed. While it's normal for these recipients to be the same, it's not necessarily the case. This is where the difference in roles lies between mail user agent (MUA, like PHPMailer, Outlook, Apple Mail, etc) and mail transport agent (postfix, exchange, sendmail, etc).

I would put what you are describing firmly in MUA territory; your original message will be sent to the server, and it will forward the original message unmodified to the (invisible) group recipients *without altering the To or CC addresses within the message*. You would run into exactly the same problem if you tried to do this in Outlook, because Outlook is an MUA like PHPMailer is. On balance, you're using the wrong tool for the job here.

You *can* achieve this using PHPMailer, but like I said before, it would involve overriding what addresses are submitted at the SMTP level, not within the message headers, and it's not something it will do out of the box.
