### ISSUE TITLE
French Accents into phpmailer 5.2.20

### ISSUE THREAD

**Issue by david20240** [PHPMailer/PHPMailer#1666]
Hi Synchro,
I work as a French City Hall webmaster and we have a trouble receiving emails with french accents.
I went everywhere on your Github phpmailer and I have done what you explained like:
-$mail->CharSet = 'utf-8';
-All the html datas pages are in utf8
-mbstring is on
And nothing is OK the accents are not OK and when there is accents in the body message, the message body is empty ;-)
All the other parameters like subject, name, email, checkboxes and radios are fine.
I use phpmailer 5.2.20 and I cannot change to 6.0.6 as I will have to modify the whole City Hall website ;-)
```
<?php
session_start();

include("php/abcdefghikjl/PHPMailerAutoload.php");

$to = 'commune@domain.fr';

if(isset($_POST['emailSent'])) {

```
$subject = utf8_decode($_POST[‘subject’]);

if (strtolower($_POST["captcha"]) == strtolower($_SESSION['captcha']['code'])) {

	$name = $_POST['name'];
	$email = $_POST['email'];
    $message = $_POST['message'];
    $message = utf8_decode($message);

	// Step 3 - Configure the fields list that you want to receive on the email.
	$fields = array(
		0 => array(
			'text' => 'Nom',
			'val' => $_POST['name']
		),
		1 => array(
			'text' => 'Adresse Email',
			'val' => $_POST['email']
		),
		2 => array(
			'text' => 'Message',
			'val' => $_POST['message']
		),
        3 => array(
	        'text' => 'Objet de ce Message',
	        'val' => $_POST['select']
        ),
		4 => array(
			'text' => '-Raisons de votre Demande',
			'val' => implode($_POST['checkboxes'], ", ")
		),
		5 => array(
			'text' => '-Qui souhaitez-vous Rencontrer',
			'val' => $_POST['radios']
		)
	);

	$message = "";

	foreach($fields as $field) {
		$message .= $field['text'].":  " . htmlspecialchars($field['val'], ENT_QUOTES) . "<br>\n";
	}

	$mail = new PHPMailer;
    $mail->isHTML(true);
    $mail->CharSet = 'utf-8';

	//$mail->IsSMTP();                                      // Set mailer to use SMTP
	//$mail->SMTPDebug = 0;                                 // Debug Mode

	$mail->Host = 'mail.domain.fr';				  // Specify main and backup server
	$mail->SMTPAuth = true;                             // Enable SMTP authentication
	$mail->Username = 'noreply@domain.fr';               // SMTP username
	$mail->Password = 'secretpassword';                         // SMTP password
	$mail->SMTPSecure = 'tls';                          // Enable encryption, 'ssl' also accepted
	$mail->Port = 587;   								  // TCP port to connect to

	$mail->From = $email;
	$mail->FromName = $_POST['name'];
	$mail->AddAddress($to);
	$mail->AddReplyTo($email, $name);

	$mail->IsHTML(true);
 

	$mail->Subject = $subject;
	$mail->Body    = $message;
    

	

	if($mail->Send()) {
		$arrResult = array('response'=> 'success');
	} else {
		$arrResult = array('response'=> 'error', 'error'=> $mail->ErrorInfo);
	}

} else {

	$arrResult['response'] = 'captchaError';

}
```
}
```
?>`And my message input is:`
Message
`<textarea maxlength="1000" data-msg-required="Merci de saisir votre Message" rows="5" class="form-control" name="message" id="message" required></textarea>`

Please, can you help do solving this accent troubles as users are complaining to the City Hall and I do not know what to answer
I really thank you as I am deadly lost into these french accents ;-)
David`

**Comment by Synchro** [comment]
I answered this [here](https://github.com/PHPMailer/PHPMailer/issues/279#issuecomment-465088976).
