### ISSUE TITLE
phpmailer fails when longer email address used in To address

### ISSUE THREAD

**Issue by korangu** [PHPMailer/PHPMailer#1670]
debug log.

`2019-02-24 08:17:59     Invalid address:  (to): reply+023ad546fffa67a9db1596d3a0600b5881d44cefcc20abc092cf000000011889ff0f92a169ce18a9e2c0@reply.github.com
You must provide at least one recipient email address.`

`reply+023ad546fffa67a9db1596d3a0600b5881d44cefcc20abc092cf000000011889ff0f92a169ce18a9e2c0@reply.github.com`
  this address is valid ?

**Comment by korangu** [comment]
@Synchro

**Comment by korangu** [comment]
i am using the latest version of phpmailer , grabed this copy from master branch. but i also tested with old versions none seem to work. :|

**Comment by Synchro** [comment]
Yes, you have run into the fact that GitHub uses addresses that are invalid. I suggest you override the validation method so that you can allow them.

**Comment by korangu** [comment]
@Synchro `$mail->validator = function ($addr){return true;};`

i tried like this but still have problem. am i lost?

**Comment by korangu** [comment]
hmm

**Comment by korangu** [comment]
ok i fixed with $mail::$validator = function ($addr){return true;};

**Comment by Synchro** [comment]
That will work, though be aware that you’re effectively turning off address validation, though that may not be a problem for your situation. Also bear in mind that if you’re sending emails from github addresses when you are not using their mail servers, it’s forgery and will probably result in your messages being spam-filtered or bounced due to SPF failures.

**Comment by korangu** [comment]
addresses are validated before passed to phpmailer so its not a problem for me. 🙄 i am not sending mail from github address just sending to address the one used to reply to issues comments.
