### ISSUE TITLE
Settings for ionos / 1&1

### ISSUE THREAD

**Issue by 8i11y** [PHPMailer/PHPMailer#1672]
For all who try to set up PHPMailer with smtp on ionos / 1&1, here are the settings that will work:

Host: smtp.ionos.de
Port: 25
Encryption: None or TLS
Authentication: true

-------------------------------------------------------------------------------------------------------------------

Hope I could help ;)

**Comment by Brumonti** [comment]
Thanks for the ionos/ 1und1 tipp. Saved me a ton of headaches!

**Comment by dasl-** [comment]
Recently i started getting errors. Previously I was using: smtp.1and1.com / port 25 / tls. I had to update it to use: smtp.ionos.com / 587 / tls.
