### ISSUE TITLE
Message could not be sent.Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

### ISSUE THREAD

**Issue by ErfanImmortal** [PHPMailer/PHPMailer#1674]
i have problem with PHPmailer and get
Message could not be sent.Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
# Debug output
```
<?php

// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'PHPmailer/src/Exception.php';
require 'PHPmailer/src/PHPMailer.php';
require 'PHPmailer/src/SMTP.php';
$mail = new PHPMailer;                              // Passing `true` enables exceptions


    //Server settings
	$mail->isSMTP();                                      // Set mailer to use SMTP
	$mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = 'arzaangift@gmail.com';                 // SMTP username
    $mail->Password = '**********';                           // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 587;                                    // TCP port to connect to
    //Recipients
    $mail->setFrom('admin@marveliptv.com', 'Marvel IPTV');
    $mail->addAddress('karyab13052@gmail.com');     // Add a recipient
    $mail->addReplyTo('marvelteam.sup@gmail.com');
    //Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = 'Salam' ;

	$mailContent = '
<h2>Eri</h2>
<p>Eri</p>
<p>Eri</p>';

    $mail->Body    = $mailContent ;
    $mail->send();

if(!$mail->send()){
    echo 'Message could not be sent.';
    echo 'Error: '. $mail->ErrorInfo;
}else{
	echo 'Message has been sent';
}	

?>
```

**Comment by Synchro** [comment]
Please follow the link to the troubleshooting guide in the error message which gives details of how to diagnose this exact problem.

**Comment by ErfanImmortal** [comment]
2019-02-28 12:00:46 Connection: opening to smtp.gmail.com:587, timeout=300, options=array()
2019-02-28 12:00:47 Connection failed. Error #2: stream_socket_client(): unable to connect to smtp.gmail.com:587 (Network is unreachable) [/home/marvemhc/public_html/lab2/PHPmailer/src/SMTP.php line 327]
2019-02-28 12:00:47 SMTP ERROR: Failed to connect to server: Network is unreachable (101)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2019-02-28 12:00:47 Connection: opening to smtp.gmail.com:587, timeout=300, options=array()
2019-02-28 12:00:48 Connection failed. Error #2: stream_socket_client(): unable to connect to smtp.gmail.com:587 (Network is unreachable) [/home/marvemhc/public_html/lab2/PHPmailer/src/SMTP.php line 327]
2019-02-28 12:00:48 SMTP ERROR: Failed to connect to server: Network is unreachable (101)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Message could not be sent.Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

> 
> 
> Please follow the link to the troubleshooting guide in the error message which gives details of how to diagnose this exact problem.

**Comment by ErfanImmortal** [comment]
if i disable this line , email will be send
"//$mail->isSMTP();                                      // Set mailer to use SMTP"

**Comment by Synchro** [comment]
That means you're not using SMTP. It looks like your ISP blocks you from using outbound SMTP, which is exactly what the guide says. When it says "network is unreachable" , it means it can't reach your network *for sending via SMTP*. Bear in mind that while sending may "work", you're likely to run into problems because you're forging your from address.

**Comment by ErfanImmortal** [comment]
So i solve my previous problem
but i have new problem
if get this error
Invalid address: (to):
Message could not be sent.Error: You must provide at least one recipient email address.

i have form.html with this code

```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>Send Email</title>
<link rel="stylesheet" type="text/css" href="main.css">	
<script  src="http://jqueryjs.googlecode.com/files/jquery-1.3.2.min.js"></script>
	<!--[if IE]><script>
	$(document).ready(function() { 
$("#form_wrap").addClass('hide');
})
</script><![endif]-->
</head>
<body>
	<div id="wrap">
		<div id='form_wrap'>
			<form action="submit.php" method="post">
				<p>Send Email</p>
				<label for="email">Email </label>
				<input type="text" name="emailphp" value="" id="emailphp" />	
				<label for="subject">Subject </label>
				<input type="text" name="subjectphp" value="" id="subjectphp" />
				<label for="message">Your Message : </label>
				<textarea  name="messagephp" value="Your Message" id="messagephp" ></textarea>				
				<input type="submit" name ="submit" value="Now, Send!" />
			</form>
		</div>
	</div>
</body>
</html>
```

and i have "submit.php" too

`
<?php

// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'PHPmailer/src/Exception.php';
require 'PHPmailer/src/PHPMailer.php';
require 'PHPmailer/src/SMTP.php';
$mail = new PHPMailer;                              // Passing `true` enables exceptions

if (isset($_POST['submit'])) {
    $emailinp = $_POST['email'];
    $subjectinp = $_POST['subject'];
    $messageinp = $_POST['message'];
}

    //Server settings
	$mail->SMTPDebug = 4; 
	$mail->isSMTP();                                      // Set mailer to use SMTP
	$mail->Host = 'server119.web-hosting.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = 'admin@marviiii.com';                 // SMTP username
    $mail->Password = '*******';                           // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 587;                                    // TCP port to connect to
    //Recipients
    $mail->setFrom('admin@marviiii.com', 'Mari');
    $mail->addAddress($emailinp); 
    $mail->addReplyTo('marviiii@gmail.com');
    //Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = $subjectinp ;

	$mailContent = '
<h2>Eri</h2>
<p>Eri</p>
<p>Eri</p>';

    $mail->Body    = $mailContent ;

if(!$mail->send()){
    echo 'Message could not be sent.';
    echo 'Error: '. $mail->ErrorInfo;
}else{
	echo 'Message has been sent';
}	

?>
`

**Comment by ErfanImmortal** [comment]
```
<?php

// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'PHPmailer/src/Exception.php';
require 'PHPmailer/src/PHPMailer.php';
require 'PHPmailer/src/SMTP.php';
$mail = new PHPMailer;                              // Passing `true` enables exceptions

if (isset($_POST['submit'])) {
    $emailinp = $_POST['email'];
    $subjectinp = $_POST['subject'];
    $messageinp = $_POST['message'];
}

    //Server settings
	$mail->SMTPDebug = 4; 
	$mail->isSMTP();                                      // Set mailer to use SMTP
	$mail->Host = 'server.web-hosting.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = 'admin@marii.com';                 // SMTP username
    $mail->Password = '********';                           // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 587;                                    // TCP port to connect to
    //Recipients
    $mail->setFrom('admin@marii.com', 'Mariii');
    $mail->addAddress($emailinp); 
    $mail->addReplyTo('test@gmail.com');
    //Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = $subjectinp ;

	$mailContent = '
<h2>Eri</h2>
<p>Eri</p>
<p>Eri</p>';

    $mail->Body    = $mailContent ;

if(!$mail->send()){
    echo 'Message could not be sent.';
    echo 'Error: '. $mail->ErrorInfo;
}else{
	echo 'Message has been sent';
}	

?>
```

**Comment by Synchro** [comment]
You're only using the `submit` check to set variables - you're still trying to send anyway, even if it's not a submission. You've also got no error checking on the `addAddress` call, in case someone submits an invalid address (it returns false if the address is bad).

**Comment by ErfanImmortal** [comment]
> 
> 
> You're only using the `submit` check to set variables - you're still trying to send anyway, even if it's not a submission. You've also got no error checking on the `addAddress` call, in case someone submits an invalid address (it returns false if the address is bad).

thanks
solved
my next problem is smtp with send grid
how can i send email with sendgrid smtp?

**Comment by Synchro** [comment]
It should be a matter of changing the `Host`, `Username` and `Password` properties - but read their docs.

**Comment by ap1437** [comment]
I'm getting this error 

SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
This may come as a bit of a surprise, but you might want to click that link and read what it says?

**Comment by bannedbook** [comment]
remove thie line:
`$mail->isSMTP();  `
will working. 
Otherwise, smpt connect timed out
