### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by teo1978** [PHPMailer/PHPMailer#1676]
https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#php-56-certificate-verification-failure

Where it says:
> You can run [some diagnostic tests](https://ssl-tools.net/mailservers) which will tell you whether the problem is at your end (if the tests pass) or the mail server's.

the link is broken

**Comment by Synchro** [comment]
You know you can edit the wiki yourself? Thanks for the notification - I changed it to https://www.checktls.com, which does actually work.

**Comment by teo1978** [comment]
>  You know you can edit the wiki yourself?

Yes, thanks. I would have if I had known the alternative (I was tempted to edit it just to add "broken link" or something, hoping that somebody would be notified of the change, but it seemed rude)
