### ISSUE TITLE
Using composer with 6.0.7 package not possible

### ISSUE THREAD

**Issue by osworx** [PHPMailer/PHPMailer#1678]
# Problem description
Latest 6.0.7 downloadable package contain already a composer.json file.
Therefore using composer is not possible.

# Code to reproduce
Try to use composer require phpmailer/phpmailer in 6.0.7 package

# Debug output
Many errors ..

**Comment by Synchro** [comment]
I think you've missed how composer works. All packages you depend upon have a composer.json file - it's how composer can tell what dependencies it needs. It does not clash with your own project's composer.json file

**Comment by osworx** [comment]
Sorry, closed it therefore .. should sleep mpore.
