### ISSUE TITLE
Cant send mail to my domain

### ISSUE THREAD

**Issue by dravick10** [PHPMailer/PHPMailer#1679]
Hi,

Im sending mail with phpmailer, my domain is something like def3.com.

`$mail->addAddress('blablabla@hotmail.com');
$mail->addAddress('abc@def3.com');`

I receive the mail on hotmail, but not on my own domain email adress.

Any advice ?

**Comment by Synchro** [comment]
Check your spam folder, enable debug output when sending to see if your message is accepted by your mail server (assuming you're sending via SMTP), or look at your mail server's logs.
