### ISSUE TITLE
SMTP Error related

### ISSUE THREAD

**Issue by as33ms** [PHPMailer/PHPMailer#168]
Hi there, 

First of all, definitely this is not a BUG in PHPMailer and so, I apologize for creating an issue here (i am doing this only for a quick support since googling around hasnt helped me much)

I am using PHPMailer for sending emails from our google apps account and it works absolutely fine from my localhost. When I have put the same code on our server, I get this error: 

SMTP -> ERROR: Password not accepted from server: 535-5.7.8 Username and Password not accepted. Learn more at\r\n535 5.7.8 http://support.google.com/mail/bin/answer.py?answer=14257 da3sm5735847pbc.30 - gsmtp\r\n\r\n<br />

I have tried repeated times to unblock captcha (from my localhost). But everytime sending emails is failing. 

Yes, I can access smtp.gmail.com from my server (i tried using telnet for both, 465 and 587 ports). 

Can anyone please point me to a potential solution? 

An additional information: my server is hosted on digital ocean in their amsterdam pool but geolocation still shows it to be in russian federation. Could this be the problem??

**Comment by priyankakhamga** [comment]
The reason to get error in console is that you have to allow less secure apps on.

https://myaccount.google.com/lesssecureapps?utm_source=google-account&utm_medium=web

**Comment by MoseBlack** [comment]
Thank you

**Comment by MoseBlack** [comment]
@priyankakhamga  thank you

**Comment by Synchro** [comment]
If you read [the docs on this](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#gmail-oauth2-and-allow-less-secure-apps), you'll see that you only need to enable "less secure apps" if you're not using XOAUTH2 authentication, and how to set that up (it's not pretty!) is described [here](https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2).

**Comment by Prajaktatrimbake** [comment]
same error
