### ISSUE TITLE
Mailer Error: Message body empty when message non html !

### ISSUE THREAD

**Issue by GioMBG** [PHPMailer/PHPMailer#1681]
hi ALL,
I need to send simple text NON html mails with attachments but I receive :
Mailer Error: Message body empty,
of course I don't want send body message is NON html so I should set only AltBody
$mail->AltBody = ($AltBody);
I've try also : 
$mail->msgHTML(FALSE); not work
// $mail->msgHTML(FALSE); not sent any msgHTML, not work
suggestions ?
thx

**Comment by Synchro** [comment]
Wrong assumptions. Use of `AltBody` does not imply plain text. `msgHTML` is used for setting HTML and plain text message bodies at the same time, not to enable or disable HTML. PHPMailer sends plain-text messages by default, so all you need to do is:

    $mail->Body = 'Plain text body';

**Comment by Synchro** [comment]
For the record, `msgHTML($html)` is a convenience wrapper that is roughly equivalent to:

```php
$mail->isHTML(true);
$mail->Body = $html;
$mail->AltBody = strip_tags($html);
```

and it also does some automatic rewriting of image URLs and conversion of data URLs. It's all optional though - if you want full control, do all these things manually.
