### ISSUE TITLE
escapeshellcmd﻿() 

### ISSUE THREAD

**Issue by oitsuki** [PHPMailer/PHPMailer#1685]
hello,
With some hoster, a problem appears with phpmailer
13-Mar-2019 16:43:18 Europe/London] PHP Warning: ` escapeshellcmd﻿()` has been disabled for security reasons in /home/.......PHPMailer-master/vendor/phpmailer/phpmailer/src/PHPMailer.php on line 1632

phpmailer version : 6.0.7

I use in function the configuration 
`$this->phpMail->IsSMTP();` // for smtp configuration
or 
` $this->phpMail->isSendmail();` // for sendmail configuration

By default the application is on sendmail

my code 

```
 if (EMAIL_TRANSPORT == 'smtp' || EMAIL_TRANSPORT == 'gmail') {

        $this->phpMail->IsSMTP();

        $this->phpMail->Port = EMAIL_SMTP_PORT;

        if (EMAIL_SMTP_SECURE !== 'no') {
          $this->phpMail->SMTPSecure = EMAIL_SMTP_SECURE;
        }

        $this->phpMail->Host = EMAIL_SMTP_HOSTS;
        $this->phpMail->SMTPAuth = EMAIL_SMTP_AUTHENTICATION;
        $this->phpMail->Username = EMAIL_SMTP_USER;
        $this->phpMail->Password = EMAIL_SMTP_PASSWORD;

      } else {
        $this->phpMail->isSendmail();
      }
```

thank you.

**Comment by Synchro** [comment]
Just because you have sendmail doesn’t mean you need to have to use isSendmail - both mail and SMTP transports will work.

The best solution is to use SMTP to localhost.

**Comment by oitsuki** [comment]
what do you recommend on this line :  $this->phpMail->isSendmail();
because it's not on computer, but on  a server. And linux use sendmail, not stmp.

**Comment by Synchro** [comment]
As I said, sendmail is just a binary, and it’s also an SMTP server. All a local sendmail binary does is open a synchronous SMTP connection to localhost, so it’s faster and safer to do that from PHPMailer.
