### ISSUE TITLE
Support PHP 7.2

### ISSUE THREAD

**Issue by guiigaspar** [PHPMailer/PHPMailer#1686]
I'm trying to use PHPMailer in php 7.2 but it does not work.

1) I created a project to send and email with PHPMailer.
2) Perform an installation of a Web server running PHP 7.0 and another running PHP 7.2
3) I copied exactly the same project on both servers.
4) Result:

PHP 7.0
![image](https://user-images.githubusercontent.com/28517560/54384614-6ae3ad00-4673-11e9-994e-6d114fe13957.png)

PHP 7.2
![image](https://user-images.githubusercontent.com/28517560/54384646-7cc55000-4673-11e9-9bea-99bd9b3c92ec.png)

It's exactly the same code and the same settings, just changing the PHP version.

Is there any particularity with PHP 7.2 or does the API have no support for it?

Note: I am using Windows + Xampp environment.

**Comment by Synchro** [comment]
It’s not a PHP problem, it’s an OS problem. Your CA certificate bundle is out of date, so it’s unable to verify the certificate from the mail server. This is discussed extensively in the troubleshooting guide.
