### ISSUE TITLE
Email HTML Mode Does Not Work

### ISSUE THREAD

**Issue by StoreHD18** [PHPMailer/PHPMailer#1689]
When HTML mode is enabled the message does not arrive in the user's email.

    $mail->isHTML(true);       <<< THIS
 
But when it is disabled the email arrives for the user, but it is all unconfigured, since I disabled the format of HTML email.

   $mail->isHTML(false);       <<< I switch to false

**Comment by Synchro** [comment]
Something doesn't like your HTML content. I can't tell what because you did not provide the code, nor did you try any of the steps described in both the issue template (which you deleted) and the troubleshooting guide.

**Comment by r0073rr0r** [comment]
Also use https://www.mail-tester.com/ to test your HTML email, maybe its triggered as spam...
