### ISSUE TITLE
Sender is not orverwritten by a second setFrom

### ISSUE THREAD

**Issue by XzenTorXz** [PHPMailer/PHPMailer#1695]
Is it intended that the Sender is not updated if setFrom is called twice ?

https://github.com/PHPMailer/PHPMailer/blob/fc8c727f38d11c78f087c8942198964b7234adf8/src/PHPMailer.php#L1204

**Comment by Synchro** [comment]
I think that's reasonable behaviour; I'd say calling `setFrom` more than once is a bug in the calling code. I always set `Sender` explicitly, and you would not want `setFrom` to overwrite an already-set `Sender` in that case either.

**Comment by XzenTorXz** [comment]
isn't thats what the `auto `flag is for, or atleast it should be set to default false so the default behaviour is more understandable ? 
We use it so we have a default From and only if the user specify another User it is set again

**Comment by Synchro** [comment]
Changing the default sense of the `auto` flag would be a BC break so I don't want to change that; avoiding that also makes it harder to move what it does to send time, so a better fix will have to wait. For your application, the safe approach would be to always set `$auto` to `false` and set `Sender` explicitly in your own code. You could do that in a subclass so you don't have to remember to do it.
