### ISSUE TITLE
Is XOAUTH2 For Gmail Affected by Godaddy's restrictions?

### ISSUE THREAD

**Issue by xeon826** [PHPMailer/PHPMailer#1696]
```
2019-03-25 23:41:17 SMTP ERROR: Failed to connect to server: Network is unreachable (101)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Message could not be sent. Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
```
I get this error message using XOAUTH2 for Gmail on the remote server. The website is hosted on one domain where they don't have these restrictions but the nameservers and DNS records are with GoDaddy. I'm just wanting to know if GoDaddy's restrictions on outbound emails would affect my applications ability to send email with XOAUTH2 using Gmail or if there's a problem with my configuration in the Google API. I added the correct javascript origins and authorized domains, as far as I know. 

It's worth noting that the server it's hosted on sends mail from a HELO. The HELO looks like host.domain.com and so I can't add it as an authorized origin in the Google API but I doubt this is relevant, just throwing it out there. I also wanted to point out that the DKIM and SPF records are missing from GoDaddy, I added them today and they should propagate by tomorrow hopefully, but would any of these things be the cause? It works just fine on localhost.

```
$mail = new PHPMailer(true);
        try {
            $mail->SMTPDebug = 2;
            $mail->isSMTP();
            $mail->Host = 'smtp.gmail.com';
            $mail->Port = 587;
            $mail->SMTPSecure = 'tls';
            $mail->SMTPAuth = true;
            $mail->AuthType = 'XOAUTH2';
            $email = 'user@host.com';
            $clientId = 'clientId';
            $clientSecret = 'clientSecret';
            $refreshToken = 'refreshToken';
            $provider = new Google(
                [
                    'clientId' => $clientId,
                    'clientSecret' => $clientSecret,
                ]
            );
            $mail->setOAuth(
                new OAuth(
                    [
                        'provider' => $provider,
                        'clientId' => $clientId,
                        'clientSecret' => $clientSecret,
                        'refreshToken' => $refreshToken,
                        'userName' => $email,
                    ]
                )
            );
            $mail->setFrom($email, 'Website Name');
            $mail->addAddress($to, $name);
            $mail->CharSet = 'utf-8';
            $mail->Subject = $subject;
            $mail->Body    = $email_message;
            $mail->AltBody = $email_message;
            if ($is_estimate) {
              $mpdf = new Mpdf();
              $mpdf->WriteHtml($email_message);
              $pdf = $mpdf->Output('file_name.pdf', 'S');
              $mail->addStringAttachment($pdf, 'file_name.pdf');
            }
            $mail->send();
            echo 'Message has been sent';
        } catch (Exception $e) {
            echo 'Message could not be sent. Mailer Error: ', $mail->ErrorInfo;
        }

```

**Comment by Synchro** [comment]
Yes, this is down to GoDaddy blocking outbound SMTP - your code is not getting as far as even attempting authentication. You can't send fr a gmail address using GoDaddy at all because that would require you to forge the from address and you will fail SPF, DKIM and DMARC checks.

Your local connection has no such restrictions, which is why it works. Move away from GoDaddy and things will improve.
