### ISSUE TITLE
Absent envelope from for $Mailer = mail

### ISSUE THREAD

**Issue by pirios** [PHPMailer/PHPMailer#1700]
`$Sender` field works only in SMTP or sendmail mode, why? Google returns bad result in DMARC. If return-path/envelope-from does not match the sender. You need to modify the script so that `-f` param is also valid for standard mail() mode/function. My hosting provider doesn't allow me to set the `ini_set('sendmail_from')`. Thanks.

Required command: `mail($to, $subject, $body, $headers, "-f $sender");`

If I do not use the PHPMailer class and define my parameters and content manually via `mail()`, the result is positive in all (SPF = PASS, DMARC = PASS).

**Comment by Synchro** [comment]
The `-f` option *is* set by PHPMailer when using `mail`, and it uses the `Sender` property, so I’m not sure where the difference is coming from. However, SMTP to localhost is faster, safer, more reliable, and easier to debug, so use that instead.

**Comment by Synchro** [comment]
See [here](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L105), [here](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L1574), and [here](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L1710).

**Comment by pirios** [comment]
Thanks. But the use of SMTP connection is slower than direct `mail()` function. Each new mail notification must always be connected and waiting for SMTP response on the server. That's the problem. But it only applies to the first connection - for bulk mailing it works perfectly but not for single notification at another time. I can see that for the notifications I only have to use standard `mail()` function and PHPMailer class for bulk mailing. This is probably the only solution for me.

**Comment by Synchro** [comment]
Are you aware that the mail function simply opens a synchronous SMTP connection to localhost using a sendmail binary? It does the same as PHPMailer, just with more overhead.

**Comment by pirios** [comment]
Of course. Only that server responds more slowly with PHPMailer. Only the first function call. I do not know. It's probably a hosting problem. Thank you for your comments. I wouldn't do it if I didn't start having DMARC problems. For years I worked without the need for the `-f` option.

**Comment by Synchro** [comment]
When using mail(), it doesn't support many SMTP commands, for example it will not attempt to use TLS, and doesn't support authentication, which means it may involve fewer round-trips. if you make sure those options are disabled (`SMTPAuth = false`, `SMTPAutoTLS = false`, `SMTPSecure = false`) it might make the connection faster over SMTP.

When you say "responds slowly", how slowly is that? You should be able to submit a single message to localhost using SMTP in tens of milliseconds; I know that with keepalive I can do over 200 messages per second on a moderate server. Can you provide a debug log showing the timings? Does the mail server's log show any further details?
