### ISSUE TITLE
SMTP connect() failed.

### ISSUE THREAD

**Issue by fahadmehar** [PHPMailer/PHPMailer#1701]
Why I am having issue with this ? 
SMTP ERROR: Failed to connect to server:  (0)SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
As I put all correct SMTP Server?

**Comment by Synchro** [comment]
Probably because you didn't [search first](https://stackoverflow.com/search?q=SMTP+connect%28%29+failed) or follow that link to the troubleshooting guide which would help you find out why. The most common reason is that your hosting provider blocks outbound SMTP.
