### ISSUE TITLE
No support for AMP4Email

### ISSUE THREAD

**Issue by hiburn8** [PHPMailer/PHPMailer#1702]
PHPMailer doesnt have any way to control the MIME structure of the email, so its not possible to add arbitrary MIME sections like 'text/x-amp-html'. While i dont really like Google's attempt to tighten their grip on the content of people's emails, I think PHPMailer should add support for AMP-emails as AMP4email as PHPMailer is basically the driver for a lot of the mailing-list industry, and AMP is the cool new thing.

**Comment by NiklasBr** [comment]
For precisely this reason I think it should *not* be added :) If we don't like that Google tightens its grip, why should we help them?

It's easy enough to extend the base PHPMailer class and add your own custom/proprietary mail mime constant:
```php
class AMPMailer extends PHPMailer
{
...
        const CONTENT_TYPE_X_AMP = 'text/x-amp-html';
...

**Comment by Synchro** [comment]
Indeed. AMP on the web is dying out and I've no particular desire to follow Google's lead, after all they have inflicted upon us with gmail. Pull requests welcome of course.

In the longer term, I'd really like to get rid of all the preset MIME structure stuff as it's a right mess, and that would make implementing things like this easier. I'd really like to implement support for SMTPUTF8 as I do not know of any implementations of that for PHP at all.

**Comment by tiwarishikesh** [comment]
Create a  public $AMP_Body class PHPMailer

```
public function createBody(){
...
          case '*':
         $body .= static::$LE;
                if(!empty($this->AMP_Body)){
                    $body .= '--'.$this->boundary[1].static::$LE;
                    $body .= 'Content-Type: '.static::CONTENT_TYPE_AMP_HTML.'; charset='.static::CHARSET_UTF8.static::$LE;
                    $body .= $this->encodeString($this->AMP_Body, $bodyEncoding);
                    $body .= static::$LE;
                }
                $body .= $this->getBoundary($this->boundary[1], $bodyCharSet, 
                static::CONTENT_TYPE_TEXT_HTML, $bodyEncoding);
                $body .= $this->encodeString($this->Body, $bodyEncoding);

...
}
```

**Comment by jab1000** [comment]
While I am not a fan of gmail/google, I think it would be crazy to not have an option for this.   As a B2C company, approximately 45% of our users have gmail and implementing AMP-emails is the number 1 priority for us!  We are all about simplifying "interactions" for our users with more advanced email functionality as truly a win-win IMHO.  No less, I will give credit to gmail.... our email issues are about 1% with them in contrast to Yahoo/Bellsouth/Hotmail which WAY is too much.

**Comment by esafwan** [comment]
> For precisely this reason I think it should _not_ be added :) If we don't like that Google tightens its grip, why should we help them?
> 
> It's easy enough to extend the base PHPMailer class and add your own custom/proprietary mail mime constant:
> 
> ```
> class AMPMailer extends PHPMailer
> {
> ...
>         const CONTENT_TYPE_X_AMP = 'text/x-amp-html';
> ...
> ```

I understand the precaution we are taking here and the concern of one company tightening their grip on something as essential & critical as email. However, I think there are some points to consider. 

1. AMP is an open standard and is high level of adoption. 
2. AMP for email is already supported by every major email readers including Gmail, Outlook and Yahoo.
3. AWS SES & Sendgrid already support AMP Email. 
4. Many companies & products like Pinterest, OYO, Booking.com, Google Group etc have already started rolling out AMP support.

We like it or not. AMP is going to be one of the standard format for email used along with HTML. All big players and leading products will implement it. Open-source projects as ours not supporting it will only make it inaccessible for the smaller players and developers. 

I personally think, PHPMailer should add support for AMP Emails.

**Comment by Synchro** [comment]
I'm very happy for you. I look forward to your PR.
