### ISSUE TITLE
пишу переменую php в код html, не выводит 

### ISSUE THREAD

**Issue by finitrop** [PHPMailer/PHPMailer#1707]
<div class="nav-profile-text">
                <p class="mb-1 text-black"><?php echo "$username"; ?></p>
              </div>

**Comment by blackcrack** [comment]
да как по русски?
Вы должны обязательно написать на английском, а также показать путь
Интернет язык просто не русский .. и ни один русский не изобрел интернет...

so 
speak English ! i am an German and i do it too.. since 20 years ...

**Comment by Synchro** [comment]
Sorry, I can't read that.
