### ISSUE TITLE
Having Issues sending mail with PHP Mailer 

### ISSUE THREAD

**Issue by opeyemi1311** [PHPMailer/PHPMailer#1710]
I am trying to send mail using php mailer but keep getting error message even after supplying proper values.

Take a look at my code 
require("PHPMailer/PHPMailerAutoload.php");
$mail = new PHPMailer();
$mail->IsSMTP();
$mail->Host = "mail.ridtalk.net"; // Enter your host here
$mail->SMTPAuth = true;
$mail->Username = "info@ridtalk.net"; // Enter your email here
$mail->Password = "Cheapcalls1"; //Enter your password here
$mail->Port = 25;
$mail->IsHTML(true);
$mail->From = "info@ridtalk.net";
$mail->FromName = "Ridtalk";
$mail->Sender = $fromserver; // indicates ReturnPath header
$mail->Subject = $subject;
$mail->Body = $body;
$mail->AddAddress($email_to);
if(!$mail->Send()){
echo "Mailer Error: " . $mail->ErrorInfo;
}else{
echo "<div class='error'>
<p>An email has been sent to you with instructions on how to reset your password.</p>
</div><br /><br /><br />";
	}
   }
}else{
?>

<?php } ?>
The error message is this 

Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
Please read the troubleshooting guide you were pointed at, and update to the latest version like the issue template told you to. It's most likely that your hosting provider is blocking outbound SMTP.

**Comment by opeyemi1311** [comment]
> Please read the troubleshooting guide you were pointed at, and update to the latest version like the issue template told you to. It's most likely that your hosting provider is blocking outbound SMTP.

ok. Thank you
