### ISSUE TITLE
PHP mailer is not working for CWP ( control web panel ) email setup.

### ISSUE THREAD

**Issue by siddharth-ethinos** [PHPMailer/PHPMailer#1715]
I used below code for sending mail using SMTP host of CWP panel.

Below mail setting showed in CWP Cpanel.

Secure SSL/TLS Settings
--
Username: Your Email Address
Incoming Server: server.we3.in
IMAP Port: 993
POP3 Port: 995
Outgoing Server: server.we3.in
SMTP Port: 465

    $mail->SMTPDebug = 2;                                       // Enable verbose debug output
    $mail->isSMTP();                                            // Set mailer to use SMTP
    $mail->Host = 'server.we3.in';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = 'info@srirangapankajam.in';      // SMTP username
    $mail->Password = 'password';                           // SMTP password
    $mail->SMTPSecure = 'ssl';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 465;                           // TCP port to connect to
    $mail->setFrom('siddharthundare@gmail.com', 'Testing');
    $mail->addAddress('siddharthundare@gmail.com');     // Add a recipient
    $mail->isHTML(true); 

# Problem description

I am trying to send mail through PHP mailer using CWP (Control Web Panel) host setting.

I created new email id ( info@srirangapankajam.in ) & password.

But not able to send mail using above settings.

# Code to reproduce

# Debug output

2019-04-26 13:47:14 SMTP ERROR: Failed to connect to server: (0)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Message could not be sent. Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
It sounds like your hosting provider is blocking outbound SMTP. See the troubleshooting guide for how to diagnose that. They will usually provide some other way of sending emails (e.g. via their own servers), but you would need to ask them about that.
