### ISSUE TITLE
Minimal Mods for PHP/Apache2

### ISSUE THREAD

**Issue by IIPoliII** [PHPMailer/PHPMailer#1718]
Hello,

I am trying to get this class to work on my hosting server with a basic MAMP installation it works so i am guessing it's probably because of the modules that need to be enabled.

I use PHP-FPM for http 2. And i use apache2 normally and php 7.3. 

Any ideas of what i should activate to make it work.

My website goes trought cloudflare

Thanks for your help

**Comment by Synchro** [comment]
It doesn't matter what web server you're using - it will even work without one, but you do need some modules enabled in your php config, and those are listed in [the `composer.json` file](https://github.com/PHPMailer/PHPMailer/blob/master/composer.json#L22). Note that this list does not include `mbstring` and `openssl` as strictly speaking they are optional, but it will limit what you can do if you don't have them.
