### ISSUE TITLE
Variable casting issue?

### ISSUE THREAD

**Issue by andreamoro** [PHPMailer/PHPMailer#1720]
Please check these things before submitting your issue:

# Problem description
Have been storing some variables to dictate the behaviour of the mail script so that they can be common to multiple parts of the project. But in doing so the script fails to execute, like it's ignoring the variables.

# Code to reproduce
My config file looks like 

```
define('MAILER_SECURE', 'false'); # tls, ssl
define('MAILER_SMTPAUTOTLS', 'false');
define('MAILER_SMTPAUTH', 'false');

```
And in the PHPMailer invocation I do something 

```
    $mail->SMTPAuth = MAILER_SMTPAUTH; // Enable SMTP authentication
    $mail->SMTPSecure = MAILER_SECURE; // Enable TLS encryption, `ssl` also accepted
    $mail->SMTPAutoTLS = MAILER_SMTPAUTOTLS;
```

As soon as the above variable are hardcoded to false in the script, everything works fine. I tried also to cast the variables to either string or boolean without success. It does make any sense.

# Debug output
The error message i got is the following when failing.

Message could not be sent. Mailer Error: SMTP Error: Could not connect to SMTP host.

**Comment by Synchro** [comment]
Are you sure that they are defined at the point where you're using them? If you `echo` them, do you get the expected values? Have you tried using a debugger and inspecting their values at the point they are used?

That SMTP error isn't much use without answering the above questions.

**Comment by jmwebservices** [comment]
A quick look at the source code indicates that `$mail->SMTPSecure` expects one of three _string_ values ( `''`, `'ssl'`, `'tls'` ) while ` $mail->SMTPAuth` and `$mail->SMTPAutoTLS` expect _boolean_ values. All three of your constants are defined with the _string_ value of `'false'`. When casting the string `'false'` to a boolean, PHP converts it to `true`.

Try the following:
```
define('MAILER_SECURE', ''); # tls, ssl
define('MAILER_SMTPAUTOTLS', false);
define('MAILER_SMTPAUTH', false);
```

**Comment by andreamoro** [comment]
Thanx. I forgot to update the thread, but that's how I ended up solving.
I was just fixing some issue from an existing app.
