### ISSUE TITLE
spl_autoload_register - am i being thick?

### ISSUE THREAD

**Issue by Latro666** [PHPMailer/PHPMailer#1721]
Have a very basic autoloader (not using composer on this system) 

```
spl_autoload_register(function ($className) {
$ds = DIRECTORY_SEPARATOR;    
$dir = $_SERVER['DOCUMENT_ROOT'];

if($className == 'PHPMailer'){
    require_once $dir . '/includes/PHPMailer/src/PHPMailer.php';
    require_once $dir  . '/includes/PHPMailer/src/SMTP.php';
    require_once $dir  . '/includes/PHPMailer/src/Exception.php';
}else{
    $className = str_replace('\\', $ds, $className);
    $file = "{$dir}{$ds}{$className}.php";
    if (is_readable($file)) require_once $file;
}
}
```

Now a simple class:

```
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

class Email{
	public function __construct($setup)
	{
		$this->email = new PHPMailer();
...
```

Envoke an object of that class and it errors with:
`Fatal error: Uncaught Error: Class 'PHPMailer\PHPMailer\PHPMailer' not found in `

If i take those requires and pop them outside of the autoloader e.g. the top of the file the autoloader is in then there is no issue with this class. 

Other libraries like HTMLPurifier seem to autoload fine like this (come to think of it though HP has an autoloader include), am i missing something and PHPMailer requires a more sophisticated autoloader?

**Comment by Synchro** [comment]
There’s nothing special about loading PHPMailer’s classes. I suggest checking that your autoloader code is actually being run, as the symptom you describe suggests it’s not.

**Comment by Latro666** [comment]
Ah yea worked it out its the autoloader not picking up on the namespace (its very basic) should be:

`if($className == 'PHPMailer\PHPMailer\PHPMailer'){ `

not

`if($className == 'PHPMailer'){ `

As the class is actually requesting the class by its relative name! - so i was being thick :D
