### ISSUE TITLE
not working twice on same site.

### ISSUE THREAD

**Issue by theyush** [PHPMailer/PHPMailer#1725]
# Problem description
using phpmailer twice on a single site and in one side I'm receiving mails but on another page same code is being used I am getting null pop up and success message in form but not receiving any mail.

$mail->isSMTP();                                            // Set mailer to use SMTP
    $mail->Host       = 'localhost'
   //$mail->SMTPAuth   = true;                                   // Enable SMTP authentication
   //$mail->Username   = 'user@example.com';                     // SMTP username
    //$mail->Password   = 'secret';                               // SMTP password
    //$mail->SMTPSecure = 'tls';                                  // Enable TLS encryption, `ssl` also accepted
    $mail->Port       = 25;
    $mail->setFrom('from@example.com', 'Mailer');

**Comment by isset1988** [comment]
Wrap the code in a function and call it as many times you want.
