### ISSUE TITLE
When Cloudflare is enabled we get an error

### ISSUE THREAD

**Issue by Avther** [PHPMailer/PHPMailer#1726]
Hello, whenever we enable Cloudflare on our site, emails being sent get this error
![image](https://user-images.githubusercontent.com/81561/57999845-23482a00-7ad7-11e9-90e7-b0783e24baad.png)

But when we disable it, everything works perfectly fine. What can I do to prevent this error? Thanks.

**Comment by Synchro** [comment]
Sorry, I have no idea. I don't know what switching your site to Cloudflare implies, and you have not provided any information on what you did, nor the results of your debugging attempts. I can only refer you to the troubleshooting guide linked form the error message - go through the tests described in there to diagnose your problem.
