### ISSUE TITLE
connect() error

### ISSUE THREAD

**Issue by DSArtyFixLife** [PHPMailer/PHPMailer#1744]
Hello, this never happened to me before, dont ask me to read wiki, because actually this is little bit different. Everything worked just fine before, today when I tried to use PHPMailer this happened:

Error message:
2019-05-28 13:54:03	SMTP ERROR: Failed to connect to server: (0) 2019-05-28 13:54:03	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

Code:
```php
  require("phpmailer/PHPMailerAutoload.php");
  $mail = new PHPMailer;
  $mail->IsSMTP();
  $mail->SMTPDebug = 1;
  $mail->SMTPAuth = true;
  $mail->SMTPSecure = 'ssl';
  $mail->Host = "smtp.gmail.com";
  $mail->Port = 465;
  $mail->IsHTML(true);
  $mail->Username = "####@gmail.com";
  $mail->Password = "######";
  $mail->SetFrom("####@gmail.com");
  $mail->Subject = "Hello PHPMailer";
  $mail->Body = "This is my first PHPMailer message";
  $mail->AddAddress("#####@gmail.com");
  if(!$mail->Send()){
      echo "Mailer Error: " . $mail->ErrorInfo;
  }else{
      echo "Message has been sent";
  }
```

Edit: Should I try to redownloads PHPMailer? I have downloaded from composer in February (2019) I think. // Tried it, nothing good

**Comment by DSArtyFixLife** [comment]
Well, this seems like an error from side of Gmail

**Comment by Synchro** [comment]
1. You're running an old version
2. You've based your code on a very old example
3. Your debug output level will not show you anything from the server side
4. You're trying to test in ways that are ineffective (smtp.gmail.com is not a web server)
5. You've not tried (or at least not reported) the tests that would allow you to diagnose your problem

**All** of these things are described in the wiki, along with gmail-specific issues that are identical to what you're describing. Perhaps you should consider giving it a try?

**Comment by DSArtyFixLife** [comment]
Since I cant find new example can you send me one?

**Comment by Synchro** [comment]
https://github.com/PHPMailer/PHPMailer/tree/master/examples

**Comment by DSArtyFixLife** [comment]
Just was there, gmails are the same, I dont see difference

**Comment by Synchro** [comment]
They are *similar*, but pretty much every single line has differences. There's nothing specifically wrong with using an old example, but it's usually indicative of using an old version, which you are.

Now would be a good time to try some of the tests described in the wiki: pasting them here isn't going to change what they say...

**Comment by DSArtyFixLife** [comment]
2019-05-28 14:54:46 SERVER -> CLIENT: 220 smtp.gmail.com ESMTP v10sm3451189wml.27 - gsmtp
2019-05-28 14:54:46 CLIENT -> SERVER: EHLO localhost
2019-05-28 14:54:46 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [78.99.110.219]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250 SMTPUTF8
2019-05-28 14:54:46 CLIENT -> SERVER: STARTTLS
2019-05-28 14:54:46 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
SMTP Error: Could not connect to SMTP host.
2019-05-28 14:54:47 CLIENT -> SERVER: QUIT
2019-05-28 14:54:47 SERVER -> CLIENT: 
2019-05-28 14:54:47 SMTP ERROR: QUIT command failed:

**Comment by DSArtyFixLife** [comment]
So actually even using new code sent the message to hell

**Comment by DSArtyFixLife** [comment]
@Synchro

**Comment by Synchro** [comment]
Now you have a visible symptom that is **exactly** [as described in the wiki](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#certificate-verification-failure), where it says:

> In an SMTP transcript this will typically be shown as trying to send a STARTTLS command immediately followed by a QUIT command.

Given that this is gmail, the most likely explanation is that your CA certificate bundle is out of date (which is nothing to do with PHPMailer), again as described in the wiki, along with [instructions for how to solve it](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#updating-ca-certificates).
