### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by jippy89** [PHPMailer/PHPMailer#1745]
# Problem description
I'm trying to just use PHPMailer as it is, via 
```php
DEFINE ("PHPMailer",htmlspecialchars($_SERVER["DOCUMENT_ROOT"])."/PHPMailer/src/");

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require PHPMailer.'Exception.php';
require PHPMailer.'PHPMailer.php';

// codes..
```

However I keep having this error

> Fatal error: Uncaught Error: Class 'PHPMailer\PHPMailer\SMTP' not found in C:\xampp\htdocs\PHPMailer\src\PHPMailer.php:1759 Stack trace: #0 C:\xampp\htdocs\PHPMailer\src\PHPMailer.php(1884): PHPMailer\PHPMailer\PHPMailer->getSMTPInstance() #1 C:\xampp\htdocs\PHPMailer\src\PHPMailer.php(1797): PHPMailer\PHPMailer\PHPMailer->smtpConnect(Array) #2 C:\xampp\htdocs\PHPMailer\src\PHPMailer.php(1539): PHPMailer\PHPMailer\PHPMailer->smtpSend('Date: Wed, 29 M...', 'This is a multi...') #3 C:\xampp\htdocs\PHPMailer\src\PHPMailer.php(1375): PHPMailer\PHPMailer\PHPMailer->postSend() #4 C:\xampp\htdocs\Monitoring\api\email\sendEmailWarningWebService.php(43): PHPMailer\PHPMailer\PHPMailer->send() #5 {main} thrown in C:\xampp\htdocs\PHPMailer\src\PHPMailer.php on line 1759

At first I thought that it was just losing dependency however when I add `require PHPMailer.'SMTP.php';` after `require PHPMailer.'PHPMailer.php';` it makes the browser loads until it reach around 30 seconds and outputs a timeout message.

> Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\PHPMailer\src\SMTP.php on line 1146

I'm using XAMPP, I tried downloading composer but it seems that _it only adds more problem,_
```
$ composer require phpmailer/phpmailer
    1/5:        http://repo.packagist.org/p/provider-2013$cd042ea733b25b43b0c718f351cc7f80084a84f9cb7ff5b1b295610db5ec6575.json
    2/5:        http://repo.packagist.org/p/provider-2018-10$7717358e88f88e467e9b0bb02a74b19da4096d7f28b40b19082c10c93ef9c676.json
    3/5:        http://repo.packagist.org/p/provider-2019-04$6dbe872de042915d983a308a1bf76c2074b679b985afe8fe609a0ae7f7456bcf.json
    4/5:        http://repo.packagist.org/p/provider-latest$77ad25f7172cbb4eff50c76ace9d5ca5c39f6a0969d7230c2e51105e13f41304.json
    5/5:        http://repo.packagist.org/p/provider-2018-07$c7f1ed7b2932758fe3edde1bd78588c6e943682710c7408fb7ace6b4f33eec83.json
    Finished: success: 5, skipped: 0, failure: 0, total: 5
Using version ^6.0 for phpmailer/phpmailer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package phpmailer/phpmailer No version set (parsed as 1.0.0) is satisfiable by phpmailer/phpmailer[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.
```
I'm really new to this composer thing, I only follow instruction and I had no idea what happens.

**Comment by Synchro** [comment]
That is strange. [This note](http://www.queryadmin.com/1557/composer-no-version-set-parsed-1-0-0-satisfiable/) suggests that you need set a version property for your own project, which seems a little odd, but worth a try.

You could also try cleaning up your composer setup:

    composer dumpautoload
    composer clearcache
    composer install

When you're using composer, you don't need to do all that messing with defines and loading classes individually, just use composer's autoloader:

    require 'vendor/autoload.php';

That way classes will be lazy-loaded on demand.

**Comment by jippy89** [comment]
Hello @Synchro, just tried your last solution
```
rm composer.json
composer init
composer require phpmailer/phpmailer
```
Then I changed my code to
```
	use PHPMailer\PHPMailer\PHPMailer;
	use PHPMailer\PHPMailer\Exception;

	require_once 'vendor/autoload.php';
```
But it seems that I still get this result (Yes I changed my directory)
> Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\Monitoring\api\email\vendor\phpmailer\phpmailer\src\SMTP.php on line 1125

**Comment by jippy89** [comment]
Ah, I solved it, it turns out that I was using the wrong SSL in the wrong port.
Thanks @Synchro for your help!
