### ISSUE TITLE
getSentMIMEMessage(), missing setSentMIMEMessage()?

### ISSUE THREAD

**Issue by fu-hsi** [PHPMailer/PHPMailer#1750]
Hi.
I have MIME message from: `$mail->getSentMIMEMessage ()` stored in database.
How can I send it now?

Thanks.

**Comment by Synchro** [comment]
With PHPMailer, you don't. There isn't a way to submit a fully-constructed message. The way to do it is to store the individual parameters (to, from, subject, body, etc), and then reconstruct the message when you want to send it. `getSentMIMEMessage` is useful for things like keeping archived copies of sent messages, uploading it to IMAP stores, passing it through spam filters, etc.

**Comment by fu-hsi** [comment]
Message contains attachments too and storing them separately is it is problematic...
But I understand. There is third party libraries for parsing MIME messages.
Thanks.

**Comment by Synchro** [comment]
You can do the same thing with attachments - stick them in binary fields in your DB and feed them to `addStringAttachment` when reconstructing your messages.
