### ISSUE TITLE
SMTP connect issue - fsockopen() has been disabled for security reasons

### ISSUE THREAD

**Issue by Donekulda** [PHPMailer/PHPMailer#1751]
# Problem description
Hey there i have this issue i cant for some reason connect to my SMTP server even thou im connecting. Sorry this isnt very good description. I hope someone knows how to fix this or atleast knows whats wrong ,because i dont underestand this bug very much.
Im using newest version of PHPMailer.
And my php version is 7.3.6.

Thanks in advance to whoever knows something about this.

# Code to reproduce
`<?php         
  $title = "Test";
  require_once "./header.php";
  
  $mail = new PHPMailer\PHPMailer\PHPMailer();
  
  $heslo = "8asdkjhadF";
  $nick = "Kulda";
  $email = "mikulda@hotmail.cz";
  $jmeno = "Mikuláš";
  $prijmeni = "Staněk";
  
  try {
            //Server settings
            $mail->charSet = "UTF-8";
            $mail->setLanguage('cs', '../plugins/PHPMailer/language/');
        
            //Recipients
            $mail->setFrom('noreply@aeko.cz', 'NoReply');
            $mail->addAddress($email, $jmeno." ".$prijmeni);       
        
            // Content
            $mail->isHTML(true);                                  // Set email format to HTML
            $mail->Subject = 'Přihlašovací údaje';
            $mail->Body    = "<html>Zdravím,<br />Zde jsou vaše přihlašovací údaje k spotreba.aeko.cz\n Nick:<strong> ".$nick."</strong>\nHeslo: <strong>".$heslo."</strong>\nDěkuji za přečtení.\n Tohle je automatická zpráva tak na ni prosím vás neodpovídejte, děkuji.</html>";;
            $mail->AltBody = "Zdravím,\nZde jsou vaše přihlašovací údaje k spotreba.aeko.cz\n Nick: ".$nick."\nHeslo: ".$heslo."\nDěkuji za přečtení.\n Tohle je automatická zpráva tak na ni prosím vás neodpovídejte, děkuji.";
        
            // SMTP parametrs
            $mail->isSMTP();
   
            /* SMTP server address. */
            $mail->Host = 'mail.vas-hosting.cz';
            
            $mail->SMTPDebug = 4;

            /* Use SMTP authentication. */
            $mail->SMTPAuth = TRUE;
   
            /* Set the encryption system. */
            $mail->SMTPSecure = "ssl";
   
            /* SMTP authentication username. */
            $mail->Username = 'spotreba@solarnivyroba.cz';
   
            /* SMTP authentication password. */
            $mail->Password = 'mypass';
   
            /* Set the SMTP port. */
            $mail->Port = 465;
            
            $mail->send();
            echo 'Message has been sent';
          } catch (Exception $e) {
            echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
          }
?>`
# Debug output
2019-06-04 15:18:40 Connection: opening to ssl://mail.vas-hosting.cz:465, timeout=300, options=array()
2019-06-04 15:18:40 Connection: stream_socket_client not available, falling back to fsockopen
2019-06-04 15:18:40 Connection failed. Error #2: fsockopen() has been disabled for security reasons [/www/hosting/solarnivyroba.cz/spotreba/plugins/PHPMailer/src/SMTP.php line 337]
2019-06-04 15:18:40 SMTP ERROR: Failed to connect to server: (0)
SMTP Connect() selhal. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Message has been sent

**Comment by Synchro** [comment]
This is down to your hosting provider - they have blocked your ability to use some critical PHP functions, and that's preventing PHP from working. If you use the `mail()` transport (by not calling `$mail->isSMTP();`, which I wouldn't normally recommend) it will not use that function, but you will need to find out how your hosting provider expects you to send email - if it does at all - it may be something you have to ask for.
