### ISSUE TITLE
Confusion between filename and extension in addStringAttachment

### ISSUE THREAD

**Issue by utilmind** [PHPMailer/PHPMailer#1753]
Hello! There is confusion between $filename and $extension in `addStringAttachment` method.

I guess correct order of values in $attachment array should be following:
```
                1 => static::mb_pathinfo($filename, PATHINFO_EXTENSION),
                2 => $filename,

```

Or maybe I don't completely understanding the purpose of these paramters, but #2 should be certainly not an extension. It should be a full file name. Otherwise recipient receives files which names are only extensions.

**Comment by utilmind** [comment]
Or maybe there should be PATHINFO_BASENAME instead of PATHINFO_EXTENSION? This could make sense.

**Comment by MbICJIb** [comment]
I've got the same issue
In my copy I just replace `2 => static::mb_pathinfo($filename, PATHINFO_EXTENSION),` with `2 => $filename`. For my purposes it works fine.
I found out, that it cames with that [commit](https://github.com/PHPMailer/PHPMailer/commit/7932f2de8c8a3fa05c03c9c97d2dd9dccd332ab7#diff-b8a39960af06fac82a262a74d42e3a02).

**Comment by Synchro** [comment]
You are quite correct - fixed in master now. Thanks for reporting.
