### ISSUE TITLE
Error Class PHPMailer

### ISSUE THREAD

**Issue by Fernanda0404** [PHPMailer/PHPMailer#1754]
Hi 

I have a error in the class phpmailer in the line		

$mail = new PHPMailer(true); 

And shows this error

Fatal error: Class 'PHPMailer\PHPMailer\PHPMailer' not found in E:\XAMP\htdocs\mas\modulos\mod_tickets\funcion_asignar_interno.php on line 77

thanks!

**Comment by Synchro** [comment]
This will be because you have either not loaded composer’s autoloader, or you have not loaded the classes manually before trying to create an instance.
