### ISSUE TITLE
Warning: Declaration of PHPMailer::edebug($str) should be compatible with

### ISSUE THREAD

**Issue by Smokietr** [PHPMailer/PHPMailer#1755]
I integrate it into my own software. But this way I get an error and the mail is not going. Also the error doesn't hit the screen.

> Warning: Declaration of PHPMailer::edebug($str) should be compatible with SMTP::edebug($str, $level = 0) in Oto\system\PHPMailer.php on line 31

> Warning: Declaration of PHPMailer::setError($msg) should be compatible with SMTP::setError($message, $detail = '', $smtp_code = '', $smtp_code_ex = '') in Oto\system\PHPMailer.php on line 31

the php version I use: 7.0.3 and 7.3.1

```php
    use PHPMailer;
    use OXYN\Config;

    class Mail extends PHPMailer {

    public function __construct($exceptions = true){
        $this->SMTPdebug = Config::Get('SMTP/Debug'); // 2
        // Hata seviyesi
        $this->Host = Config::Get('SMTP/Host'); // Host
        $this->SMTPOptions = array(
            'ssl' => array(
                'verify_peer' => false,
                'verify_peer_name' => false,
                'allow_self_signed' => true
            )
        );
        // SMTP Sunucusu
        $this->Username = Config::Get('SMTP/Username'); // User
        // SMTP Kullanıcısı
        $this->Password =  Config::Get('SMTP/Password'); // Pass
        // SMTP Şifresi
        $this->Port =  Config::Get('SMTP/Port'); // Port
        // SMTP Portu
        $this->SMTPAuth = true;

        $this->SMTPSecure = Config::Get('SMTP/Secure'); // TLS
        // SMTP Şifreleme
        $this->isSMTP();

        parent::__construct($exceptions);
       }
     
    public function sendMail($from, $subject, $body)
    {
       $this->setFrom($from);
       $this->addAddress(Config::get('SMTP/Username')); // User
       $this->Subject = $subject;
       $this->Body = $body;
       $this->isHTML(true);
        return $this->send();
     }
}
```

**Comment by Synchro** [comment]
First of all I can see that you're not using the current version, so I suggest you upgrade. Those incompatibility errors sound like you have extended the wrong class or something? They don't need to be compatible because they are not called by the same things.

Why are you disabling certificate verification?

**Comment by Smokietr** [comment]
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in C:\wamp64\www\TSTOto\system\SMTP.php on line 369

I get this error when I turn on certificate validation. I'll update and return again.

**Comment by Smokietr** [comment]
After updating it worked properly. Thanks
