### ISSUE TITLE
Email not formatting correctly when send to a school email

### ISSUE THREAD

**Issue by zhiyizha** [PHPMailer/PHPMailer#1757]
I am send emails to user upon request using amazon ses with the following to edit my email

		`$mail = new PHPMailer(true);
		try {
			$mail->isSMTP();

			$mail->setFrom('no-reply@zhcoupon.com', 'zhcoupon');

			$mail->addAddress($email, $name);

			$mail->Username = 'some username';

			$mail->Password = 'some password';

			$mail->addCustomHeader('some header');
							
			$mail->Host = 'email-smtp.us-east-1.amazonaws.com';
							
			$mail->Subject = 'some subject';
						
			$mail->Body = 'some html body';		

			 $mail->addCustomHeader("List-Unsubscribe", ''.$email.' <https://example.com/unsubscribe.php>');

			$mail->SMTPAuth = true;

			$mail->SMTPSecure = 'tls';

			$mail->Port = 587;

			$mail->isHTML(true);

			$mail->AltBody = "some alt body.";					
							
			$mail->send();
	
			}
			catch (phpmailerException $e) {
				echo "some error";
			}
			catch (Exception $e) {
				echo "some error";
			}
`using this format, sending to my personal email and other's with @gmail.com works as expected 
However, when sending to .edu email, the following shows up.

some header: 
List-Unsubscribe: example@example.edu, <http://example.com/unsubscribe.php>
MIME-Version: 1.0
Content-Type: multipart/alternative;
        boundary="b1_4zQsulQkgdQmJfUfw163KYkqzRwb6g3j6vKc2eLxM34"
Content-Transfer-Encoding: 8bit
X-SES-Outgoing: 2019.06.08-54.240.8.94
Feedback-ID: 1.us-east-1.MuSzbW82lszsy8Qs2hlK+dxHbeKHAMTLkrFDoa4K6AI=:AmazonSES

This is a multi-part message in MIME format.
--b1_4zQsulQkgdQmJfUfw163KYkqzRwb6g3j6vKc2eLxM34
Content-Type: text/plain; charset=us-ascii

some header
--b1_4zQsulQkgdQmJfUfw163KYkqzRwb6g3j6vKc2eLxM34
Content-Type: text/html; charset=us-ascii

some html body

--b1_4zQsulQkgdQmJfUfw163KYkqzRwb6g3j6vKc2eLxM34--
`

**Comment by Synchro** [comment]
Can you clarify what you think is wrong here? I can see that the header is ending up in the body, which is probably because you’re providing an invalid value.

**Comment by zhiyizha** [comment]
my best guess is that the .edu server requires some special headers that i need to add in order for the email to format properly. I have no clue as to why this happen beyond that

**Comment by Synchro** [comment]
Not sure if it's a placeholder issue, but I don't think header names can contain spaces, and your example lacks a value. PHPMailer does not enforce this, so do you see any difference if you say:

    $mail->addCustomHeader('some-header', 'some value');

Otherwise I think you'll have to post your real content.

**Comment by babuhacker** [comment]
i have a doubt.
$mail->Username   = "xxxxx@gmail.com";  // GMAIL username
$mail->Password   = "********";            // GMAIL password

it will steal my gmail username and password.
why we give gmail password.
what should i do.
