### ISSUE TITLE
$mail->addCustomHeader() after Dkim objects

### ISSUE THREAD

**Issue by felloz** [PHPMailer/PHPMailer#1758]
I have a mail systems and i decided to migrate mail_socket to phpmailer because i need to install dkim certificates to my sites, everything was good but I need to send some custom text to the header to process some stadistics from mailer daemon failure but when i try to add that text trougth the function `$mail->addCustomHeader` the dkim signature its sended out the header, what can i do?

This is the original mail text 

Delivered-To: serranol82@gmail.com
Received: by 2002:a2e:92d0:0:0:0:0:0 with SMTP id k16csp6522150ljh;
        Wed, 12 Jun 2019 13:59:29 -0700 (PDT)
X-Google-Smtp-Source: APXvYqzC2iF/gatSDPdJafgnmR7VCt+v6xJiEI/6I5pdotpX3zuLDOFFl7vvlEx5Tr/p8k+xR3oq
X-Received: by 2002:a1f:1d57:: with SMTP id d84mr15025496vkd.47.1560373168832;
        Wed, 12 Jun 2019 13:59:28 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1560373168; cv=none;
        d=google.com; s=arc-20160816;
        b=SCQYE/URLhUui52kkf13rHmKmHQwr2cHib5kTvjVHVRstOYAAlmUBSYiKO14pXv0Rw
         DDDDYn9asV3qma0yyGJNrDiuHslJjZxbUdSGymVYAcjQu1aceq3jkjdo0LcsBKg+MFdh
         qo31xYcdFj3jNNIoHuCyueGUCWWPN2Y5hiMl3HJf+kSJEbmC//2qyX7hvjXWrSLV+gSZ
         ptMkidlK330lOGHAH8ZaVvPzzJTk4YAzWRgb03MwHhD5GN8PXJWna4wvlrQ/HySYXH7A
         nfLHn4d6jIIRwBvNFAKluQIu0qL5kNbkUWJ2vt8f0s6XHByI/EFwNGP39H7yicBRB4lf
         wgSw==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=mime-version:list-unsubscribe:reply-to:errors-to:sender:message-id
         :subject:reply-to:from:to:date;
        bh=Eu6auoJRmtr5vkX0Ya4wIxvomShQ1rBFdfK/LB1gL/I=;
        b=yRsKa7thQbz+0nNbkRwv8OyREFW9e6sT3IKm8gq+ej1canF7qBw59shBghtvkrdv8p
         fwmzjiWEScthBhynjBRvKnfe20QcE82sPr4vU+HyI8vwxeSJUuSRoKLuKcvt/1r5lutN
         gxHMdpKESGZuJ1Fl7h5D0CHkU1QrfTyh+OIzF4ER2Iu5P3MgK/ujb55HIcvRNlMrxOdZ
         Iy5lGv8rMslqkpqTP7ovEZaa7g9/Uu2Tzi2aK+iuBuSPB8pbnl0Rh/8Ha+BJmWmg6d8B
         StEgWsCGj8wnXsnfRHAHltxVKtO7DJ+/P2+Mpw8ceCX7cEpbadfFqhvwaAyr6vLmi/Ki
         JFqw==
ARC-Authentication-Results: i=1; mx.google.com;
       spf=pass (google.com: domain of soporteexpo@radarsystems.net designates 149.56.27.37 as permitted sender) smtp.mailfrom=soporteexpo@radarsystems.net
Return-Path: <soporteexpo@radarsystems.net>
Received: from mailovh.radarsystems.net (mailovh.radarsystems.net. [149.56.27.37])
        by mx.google.com with ESMTPS id 10si456545vkw.9.2019.06.12.13.59.28
        for <serranol82@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Wed, 12 Jun 2019 13:59:28 -0700 (PDT)
Received-SPF: pass (google.com: domain of soporteexpo@radarsystems.net designates 149.56.27.37 as permitted sender) client-ip=149.56.27.37;
Authentication-Results: mx.google.com;
       spf=pass (google.com: domain of soporteexpo@radarsystems.net designates 149.56.27.37 as permitted sender) smtp.mailfrom=soporteexpo@radarsystems.net
Received: from localhost (localhost.localdomain [127.0.0.1]) by mailovh.radarsystems.net (Postfix) with ESMTPS id 5D8D3DE227E for <serranol82@gmail.com>; Wed, 12 Jun 2019 16:59:24 -0400 (-04)
Date: Wed, 12 Jun 2019 16:59:24 -0400
To: Luis Serrano <serranol82@gmail.com>
From: Expomarketing Technology Media <expomarketing@expomarketing.biz>
Reply-To: soporte@expomarketing.biz
Subject: Se han asignado valores para arriba
Message-ID: <9rAemAocMVYjVyBid8GnTDEBEpjRMc9Kwc3qN6zHvk@localhost>
X-Mailer: RadarSystems 2.5 (https://www.radarsystems.net/)
**Sender: Expomarketing Technology Media <expomarketing@expomarketing.biz>
Errors-To: soporteexpo@radarsystems.net
Reply-To: soporte@expomarketing.biz
List-unsubscribe: <mailto:soporteexpo@radarsystems.net?subject=unsubscribe>,<https://radarsystems.net/aa/?accion=frmremover&A=796&ID=serranol82@gmail.com&L=37952&C=180275>
X-RSidusuario: 94744
X-RS-idadmin: 796
X-RS-idcamp: 180275
X-RS-idlist: 37952
MIME-Version: 1.0
X-Priority: 3
Content-Type: multipart/alternative; boundary="e284d286e23fd04a39668f7274074e26"**

--e284d286e23fd04a39668f7274074e26
This is a multi-part message in MIME format.: 
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
**DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; l=1832; s=default; t=1560373164; c=relaxed/simple; h=From:To:Date:Subject; d=radarsystems.net; i=soporteexpo@radarsystems.net; z=From:=20Expomarketing=20Technology=20Media=20<expomarketing@expomarketing.biz> |To:=20Luis=20Serrano=20<serranol82@gmail.com> |Date:=20Wed,=2012=20Jun=202019=2016:59:24=20-0400 |Subject:=20Se=20han=20asignado=20valores=20para=20arriba; bh=jZNXh7MQVbQzgM1MAvxwM/MNpjGt07jihKkQzTflNrg=; b=SwxdOBSqew8Vq5isR4Ygo+axQJ3Lyac1KgJtUOjDptKjlXA6hd9eyXKzUwCOMgv7pjzUz4bRpaWbj+Q2C5d0sDGrfmHAyi4riBSX4AeQhCEq8za+/8npZifF7IYZOFWXisJhXwLOFYB+BM8DkECb9npEHytjfe/hxJeoMSQJnHQ=**

<table width="600" align="center"><tr><td
align="top"><p>Los valores del DKIM han sido
modificados</p>
</td></tr></table>
<img
src="https://www.radarsystems.net/aa/w.php?A=796&L=37952&C=180275&ID=serranol82@gmail.com"
width="1" height="1">
<table width="600" border="0" cellspacing="0"
cellpadding="3" align="center">  <tr>     <td
colspan="3"><br><hr align="center" width="95%"
size="1" noshade></td>  </tr><tr>      <td
colspan="3" width="100%" valign="top"
align="center"><font
face="Verdana,Geneva,Arial,Helvetica,sans-serif"
size="1"><a
href="https://radarsystems.net/aa/?accion=frmremover&A=796&ID=serranol82@gmail.com&L=37952&C=180275">Remover</a>
| <a
href="https://radarsystems.net/a_a/?accion=frmreenviar&A=796&ID=serranol82@gmail.com&L=37952&C=180275"><b>Reenviar
a un amigo</b></a> | <a
href="https://radarsystems.net/site/privacidad.htm"
target="_blank">Pol&iacute;ticas de
privacidad</a></font></td></tr><tr><td
width="20%"><a
href="mailto:abuse@radarsystems.net"><img
src="https://radarsystems.net/images/no_span.gif"
border="0"></a></td><td width="60%"
align="center"><br><font face="verdana" size="1"
style="font-size:11px;"><b>Expomarketing
Technology Media C.A</b></font><br><font
face="verdana" size="1"
style="font-size:11px;">Rif: 
J-30659169-9</font><br><font face="verdana"
size="1" style="font-size:10px;">Av. Libertador,
Edif. Multicentro Empresarial del Este, Torre
Miranda, Piso 6, of. 67- 68,  Caracas -
Venezuela<br>Tel&eacute;fonos:  +58-212-263
8460<br>Fax: </font></td> <td  width="20%"
align="right"><font
face="Verdana,Geneva,Arial,Helvetica,sans-serif"
size="1">Monitoreado por: </font><br> <a
href="https://www.expomarketing.biz/"
target="_blank"><img
src="https://www.radarsystems.net/image/radar_logo.gif"
border="0" alt=""></a></td>  </tr></table>`

I set as bolder the text that im talking to you, im sorry for my english

The php mailer code

```
$mail->EmailSystems = $from_sist;
	$mail->From     = $from_email;
	$mail->Sender   = $from_sist;
	$mail->FromName = $from_name;
	$mail->AddReplyTo($from_contacto, "");
	//$mail->Priority = $mail_prioridad;
	$mail->DKIM_domain = 'radarsystems.net';
	$mail->DKIM_private = '../include/default';
	$mail->DKIM_selector = 'default';
	$mail->DKIM_passphrase = '';
	$mail->DKIM_identity = $from_sist;
	$mail->AddAddress($to, $to_name);
	$mail->Subject  =  $subj;
	$mail->addCustomHeader($head);
	$mail->Body  = $body;
	$mail->IsHTML(true);
```

And the $head code:

```php
$header .= "Sender: ".$from_name." <".$from_email.">\r\n";
						$header .= "Errors-To: ".$from_emailsistema."\r\n";
						$header .= "Reply-To: ".$from_contacto."\r\n";
						$header .= "List-unsubscribe: <mailto:".$from_emailsistema."?subject=unsubscribe>,<https://radarsystems.net/aa/?accion=frmremover&A=".$id_admin."&ID=".$uemail."&L=".$idlista."&C=".$id_campana.">\r\n";
						$header .= "X-RSidusuario: ".$uid_usuario."\r\n";
						$header .= "X-RS-idadmin: ".$id_admin."\r\n";
						$header .= "X-RS-idcamp: ".$id_campana."\r\n";
						$header .= "X-RS-idlist: ".$idlista."\r\n";
						$header .= "MIME-Version: 1.0\r\n";
						$header .= "X-Priority: ".$priority."\r\n";

						$header .= "Content-Type: multipart/alternative;\n";
						$header .= "\tboundary=\"$boundary\"\r\n\r\n";

						$header .= "This is a multi-part message in MIME format.\n";
```

**Comment by Synchro** [comment]
You're going in the wrong direction here. PHPMailer already does most of this for you, and by trying to override bits of what it does you're likely to break things. DKIM headers need to be in the top-level part of a message, not in the headers of a sub-element. Take a look at [the DKIM signing example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/DKIM_sign.phps) for how to do DKIM. Look at the headers of a typical message generated by PHPMailer, and don't add headers that it does for you, such as `MIME-Version` and boundaries. You should also not set a `Sender` header; there is  `Sender` *property*, but that is for setting the SMTP envelope sender, not for adding a header.

For all the other headers, such as `list-unsubscribe`, `addCustomHeader()` will work fine; just don't try to do structural changes by setting headers.
