### ISSUE TITLE
Sending email twice given up on it

### ISSUE THREAD

**Issue by on3php** [PHPMailer/PHPMailer#1760]
I installed without composor the PHPMailer latest version

Each time i send a email to client (with or without invoice attached it sends it twice
her is my code

i'm given up after 3 days of searching

`session_start();
ob_start();

require("connect.php");
require('fetch_company_details.inc.php');

$SentTestTo = $_COOKIE['sendtestto'];

$result3 = mysql_query("SELECT * FROM email_settings WHERE email_settings_id = '1'") or die ("Error: " . mysql_error());
if (mysql_num_rows($result3) == 1) {
	$subrow = mysql_fetch_assoc($result3);
	
	$SMTPHost = $subrow['email_settings_Host'];	
	$SMTPUser = $subrow['email_settings_useremail'];	
	$SMTPPsw = base64_decode($subrow['email_settings_password']);	
	$SMTPProtol = $subrow['email_settings_secru'];	
	$SMTPPort = $subrow['email_settings_port'];			
}

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'PHPMailer/Exception.php';
require 'PHPMailer/PHPMailer.php';
require 'PHPMailer/SMTP.php';

// Instantiation and passing `true` enables exceptions
$mail = new Mailer(true);

/* Server settings */
	
// Set mailer to use SMTP
$mail->isSMTP();
// Enable SMTP authentication
$mail->SMTPAuth = true;
// Enable verbose debug output
$mail->SMTPDebug = 2;
// Specify main and backup SMTP servers
$mail->Host = $SMTPHost;
// SMTP username
$mail->Username = $SMTPUser;
// SMTP password
$mail->Password = $SMTPPsw;
 //Enable TLS encryption, `ssl` also accepted
$mail->SMTPSecure = $SMTPProtol;
//$mail->SMTPSecure = 'ssl'; $mail->Port = 465;
// TCP port to connect to
$mail->Port = $SMTPPort;
	
$mail->CharSet = 'UTF-8';

/* Open the try/catch block. */
try {
	//////////////////////////// Send from ////////////////////////////
	$mail->setFrom($companyemail, $companyname);
	$mail->addReplyTo($companyemail, $companyname);
	
	//////////////////////////// Recipients ////////////////////////////
	$mail->addAddress($SentTestTo, 'Test email');	
	
	//$mail->addCC('cc@example.com');
	//$mail->addBCC('marc.huyghebaert@gmail.com');

	///////////////////////////// Content
	// Set email format to HTML
	$mail->Subject = 'Here is the test email from '.$companyemail;
	$mail->Body    = 'This is the HTML message body <b>in bold!</b>';
	$mail->isHTML(true);
	$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

	$mail->send();
			
	echo 'Message to client has been sent';	
	
} catch (Exception $e) {
    echo "Message could not be sent info:<p>{$mail->ErrorInfo}";
}
`

**Comment by Synchro** [comment]
This doesn’t create a PHPMailer instance:

    $mail = new Mailer(true);

That should say `PHPMailer`.

To diagnose the second message, first establish whether you are receiving two copies of the same message, or two separate messages. One simple way to do that is to append a random number to the subject line:

    $mail->Subject = 'Here is the test email from '.$companyemail. rand(0,1000000);

Now you can tell what’s happening; if your two messages have the same number, you are receiving two copies of the same message; if they are different, your script is being run twice.

This latter explanation is the most likely - it’s quite common for browser plugins to cause repeated POST requests. So check that and get back to me.

**Comment by on3php** [comment]
OK made tge change dot PHPMailer
seems to be working now even with bcc included

what i left out is that i used Mailer is because of this extra class

`class Mailer extends \PHPMailer\PHPmailer\PHPMailer {
    // Save email to a folder (via IMAP)
    // This function will open an IMAP stream using the email credentials previously specified, and will save the email to a specified folder. Parameter is the folder name (ie, Sent)
	//If nothing was specified it will be saved in the inbox.
    
	// it(s not warking !!!!!
	public function copyToFolder($folderPath = null) {
        $message = $this->MIMEHeader . $this->MIMEBody;
        $path = (isset($folderPath) && !is_null($folderPath) ? ".".$folderPath : ""); // Location to save the email
        $imapStream = imap_open("{".$this->Host."}".$path,$this->Username,$this->Password);
        imap_append($imapStream,"{".$this->Host."}".$path, $message);
        imap_close($imapStream);
    }	
}

however this class is not working still looking to solve that problem - but YES without this class it seems to working fine`

**Comment by Synchro** [comment]
OK, well you need to deal with your own code there. One thing, instead of this:

    $message = $this->MIMEHeader . $this->MIMEBody;

do this:

    $message = $this->getSentMIMEMessage();

For reference, see [the IMAP upload function in the gmail example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail.phps#L86).
