### ISSUE TITLE
Question: Is it possible to set the ports for autotls?

### ISSUE THREAD

**Issue by skerbis** [PHPMailer/PHPMailer#1765]
PHPMailer crashes when set to autotls and tries to connect on some hosters. Where do I set the possible ports for autotls?

**Comment by Synchro** [comment]
No, it doesn't crash; it may have a connection failure, but that's probably appropriate in the circumstances.

There are no ports for auto-TLS; it has nothing to do with ports.

The most common reason for problems with auto-TLS is if you connect to a server on `localhost` that advertises `STARTTLS` - that combination can never work.

Deal with that situation by setting:

    $mail->SMTPAutoTLS = false;

There are other circumstances where auto-TLS can be problematic, for example if your server has an expired or invalid certificate, but again, that's appropriate behaviour - attempting to send through a server with broken security should not be permitted by default.

**Comment by skerbis** [comment]
Thx ok, i thought I've had a problem with a port. Now I recognized it was an timeout issue. The default timeout of 300 sec was too high. This caused a crash when trying to connect to a smtp-server which is not available. Setting the timeout to 30 sec helped me.
