### ISSUE TITLE
Raw Mail 

### ISSUE THREAD

**Issue by WindowsNT** [PHPMailer/PHPMailer#1766]
Hello.

PHPMailer  is excellent. I can't find a feature needed though.
Can I pass the full body to PHPMailer and have it send it as is? I can generate my own headers, encryption, etc.

Something like 

`        $mail = new PHPMailer(true);
         $mail->SetRawBody($b);
         $mail->send();
`

**Comment by Synchro** [comment]
No, PHPMailer doesn't do this. You can drive the SMTP class yourself (though it's not that simple). If you want to save a message and send it later, save the component parts and regenerate the message. If you already have a complete message, you would need to use a MIME parser to dismantle it first.
