### ISSUE TITLE
why say php_errors file showing Unable to load dynamic library "php_imagick.dll" when install

### ISSUE THREAD

**Issue by pacozha** [PHPMailer/PHPMailer#1767]
why in php_errors file showing       Unable to load dynamic library 
'c:\php\ext\php_imagick.dll'  can not find this module
'c:\php\ext\php_oci8_12c.dll' can not find this module
c:\php\ext\php_pdflib.dll' can not find this module
'c:\php\ext\php_smtp.dll'  can not find this module
'c:\php\ext\php_extname.dll' can not find this module

i have checked loading in php.ini file. all loaded not “;”
above 5 dll files exist in c:\php\ext\ directory.

**Comment by Synchro** [comment]
This doesn't have anything to do with PHPMailer. Presumably it can't find these files because either they are not in the expected locations, or they are but PHP dos not have permission to load them.

**Comment by pacozha** [comment]
PHPMailer no need php_imagick.dll  php_oci812c.dll php_pdflib.dll php_smtp.dll php_extname.dll to support.
Right?

**Comment by Synchro** [comment]
No, it doesn't need any of those.

**Comment by pacozha** [comment]
How to Know PHPMailer Working under Magento 2.0.6

**Comment by Synchro** [comment]
Sorry, I don't know; you'd need to ask Magento people about that

**Comment by pacozha** [comment]
OK.... 
Bye the way ? May i know How PHPMailer to instead of  php mail()

**Comment by Synchro** [comment]
Yes - read the readme, base your code on the examples provided.
