### ISSUE TITLE
Bug show test send mail

### ISSUE THREAD

**Issue by ngothoai** [PHPMailer/PHPMailer#1768]
Hello, When I clicked tab Test Email, And I test send mail. It is shown bug SMTP ERROR: Failed to connect to server: Connection timed out (110)SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting Let me know, What is bug? And, How do i fix ? Thanks you very much!

**Comment by Synchro** [comment]
Follow the tests in the troubleshooting guide linked from the error message. This type of error usually indicates that you have the wrong port number, or that your hosting provider is blocking outbound SMTP; so it’s not a bug.
