### ISSUE TITLE
SMTP Error

### ISSUE THREAD

**Issue by chika94** [PHPMailer/PHPMailer#1769]
Hello guys, so I have been using phpmailer() for sometime now, and I started having this issues recently. On user registration, phpmailer() send an authentication email to user email. But I get this error

SMTP -> FROM SERVER:220-server261.web-hosting.com ESMTP Exim 4.92 #2 Wed, 03 Jul 2019 10:26:43 -0400 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail.
SMTP -> FROM SERVER: 250-server261.web-hosting.com Hello x2forexoption.com [198.54.125.157] 250-SIZE 52428800 250-8BITMIME 250-PIPELINING 250-AUTH PLAIN LOGIN 250 HELP
SMTP -> FROM SERVER:250 OK
SMTP -> FROM SERVER:250 Accepted
SMTP -> FROM SERVER:354 Enter message, ending with "." on a line by itself
SMTP -> FROM SERVER:
SMTP -> ERROR: DATA not accepted from server:
SMTP Error: Data not accepted.

What do I do?

**Comment by Synchro** [comment]
Did you remove some of this output? It seems incomplete, only has server-side messages.

**Comment by chika94** [comment]
Well that's the debug error I got... The issue has been resolved already.
Thanks

**Comment by patriceandala** [comment]
How did you fix that issue?

**Comment by enabla** [comment]
How did you solve it? It is also giving me a head ache!

**Comment by enabla** [comment]
Guys, I have solved this issue. 
I had an error on the HOST ServerName and also I had not installed an SSL

**Comment by Synchro** [comment]
That's good, but you don't need a certificate on your own server to be able to connect to an SMTP server that uses TLS.

**Comment by enabla** [comment]
Year, TLS is even more secure than SSL. I have switched to it and used port 587
