### ISSUE TITLE
How to remove PHPList in from line address

### ISSUE THREAD

**Issue by govardhankankanala** [PHPMailer/PHPMailer#1771]
After receiving the mail, When click on show original it showing phplist( Using PHPMailer 5.2.5 (https://github.com/Synchro/PHPMailer/)) in from line. How to remove this.

Message ID | <551544038c661610c1527da21a344e0a@84.16.226.150>
-- | --
Thu, Jul 4, 2019 at 11:00 PM (Delivered after 0 seconds)
"support@myvehiclecredit.info" <support@myvehiclecredit.info> Using PHPMailer 5.2.5 (https://github.com/Synchro/PHPMailer/)

Hello
PASS with IP 178.162.211.246 Learn more
'PASS' with domain myvehiclecredit.info Learn more
'PASS' Learn more

**Comment by Synchro** [comment]
It's not clear exactly how this appears in your headers, but this sounds like it is being set by PHPList issue rather than PHPMailer. Also it looks like you're using a very old version of PHPList, so I suggest you upgrade as PHPMailer 5.2.5 is vulnerable to attack and contains many bugs..
