### ISSUE TITLE
AddEmbeddedImage Problems

### ISSUE THREAD

**Issue by Damien2k9** [PHPMailer/PHPMailer#1772]
Hi!!!

I'm creating a mass mailing system for a store using PHPMailer. I'm just having trouble uploading images in the body of the email.

I have 4 email accounts for testing. 2 Gmails, 1 Outlook and one in my hosting. In one of the Gmail accounts everything works perfectly fine. In the other, the image does not appear. In the Outlook account the image does not appear and shows me an icon as if it were not finding the image in the folder. And the last one also does not appear anything.

Here is the code I did:

```
try{
    $email = $mysql->where('send', 0)->get('cliente');

    // Configutração Server Google Acount RCH - Itaipu
    $mail->IsSMTP();
    $mail->CharSet = 'UTF-8';
    $mail->Host = "smtp.gmail.com";
    $mail->SMTPSecure = "tls";
    $mail->Port = 587;
    $mail->SMTPAuth = true;
    $mail->SMTPKeepAlive = true;
    $mail->Username = EMP_EMAIL;
    $mail->Password = EMP_PASS;
    $mail->From = EMP_EMAIL;
    $mail->FromName = EMP_NAME;
    $mail->WordWrap = 50;
    $mail->IsHTML = true;
    $mail->Subject = NEWS_SUBJECT;

    // Pedido de Confirmação de leitura do E-mail enviado
    // Verificar como enviar para um pag php para alterar DB
    // $mail->AddCustomHeader("MIME-Version: 1.0" . "\r\n");
    // $mail->AddCustomHeader("Content-type: text/html; charset=iso-8859-1" . "\r\n");
    $mail->AddCustomHeader("X-MSMail-Priority: 1");
    $mail->AddCustomHeader("Priority: 1");
    $mail->AddCustomHeader("Return-Receipt-To: EMP_EMAIL");
    $mail->AddCustomHeader("X-Confirm-Reading-To: EMP_EMAIL");
    $mail->AddCustomHeader("Disposition-Notification-To: EMP_EMAIL");
    $mail->ConfirmReadingTo = EMP_EMAIL;

    $imgPath = "\images\Progressiva_Itaipu.jpg";
    $cid = md5($imgPath);
    $mail->AddEmbeddedImage($imgPath,$cid,'Progressiva_Itaipu.jpg');

    $message = "<html>";
    $message .= "<body>";
    $message .= "<div>";
    $message .= "<img src='$cid'>";
    $message .= "</div>";
    $message .= "</body>";
    $message .= "</html>";

    $mail->msgHTML($message)
  
    $mail->AltBody = NEWS_TXTMSG;

    for ($i=0; $i < $mysql->num_rows(); $i++) { 
        $mail->addAddress($email[$i]['Email'], sentenceCase($email[$i]['Nome']));

        if(!$mail->send()) {
            echo "Mailer Error (" . str_replace("@", "&#64;", $$email[$i]['Email']) . ")" . $mail->ErrorInfo . '<br />';
        } else {
            echo "Message sent to: " . $email[$i]['Nome'] . '(' . str_replace("@", "&#64;", $email[$i]['Email']) . ')<br />';

            try{
                $mysql->where('ID', $email[$i]['ID'])->update('cliente', array('send' => '1'));
            } catch(Exception $e) {
                echo 'Caught exeception: ', $e->getMessage();
            }
        }
        // Limpa todos os E-mail e anexospara o próximo loop
        $mail->clearAddresses();
        $mail->clearAttachments();
    }
} catch(phpmailerException $e){
    echo $e->errorMessage();
} catch(Exception $e){
    echo $e->getMessage();
}
```
I have already researched in several places and here also to find a solution and I can not solve the question. Can you help me?

Thx

**Comment by Synchro** [comment]
You’re doing quite a few things that PHPMailer does for you. `msgHTML` can automatically import relative image paths into embedded images, and auto-generates cids and alters URLs to match. Look at the code to see how that works.

In your example link you have missed off the `cid` protocol so clients won’t know how to treat them. Do it like this:

    $message .= "<img src='cid:$cid'>";

**Comment by Damien2k9** [comment]
WOW!!!

Thanks, I'll test here and tell you if everything worked

**Comment by Damien2k9** [comment]
Hi Sunchro

You say that "msgHTML can automatically import relative image paths to embedded images and automatically generates cids and changes URLs for matching". How can I apply this? Are there any examples you can study?

**Comment by Synchro** [comment]
You would write your template using standard relative paths to images, like this:

    <img src="images/image.png">

and call `msgHTML` telling it where to find the images:

    $mail->msgHTML($template, __DIR__);

(in this case it would look for your images in the `images` folder in the same location as your script). It will generate `cid` values for the images and replace the URLs in the image tags, as appropriate.

**Comment by prasenjeetp** [comment]
So happy to learn this. It makes things a lot simpler, with the same template being pushed on the webpage and also to the email.
