### ISSUE TITLE
PHPMailer handling latin characters on form post

### ISSUE THREAD

**Issue by inglesuniversal** [PHPMailer/PHPMailer#1774]
Hi, your script works wonderfully for utf-8 charset but for latin accented character, they are coming into my test email inbox in a non-readable way.

on the php form I am using this...

`<form action="sendmail_mini.php" accept-charset="iso-8859-1" method="post">`

Is there a better way to handle this charset or encoding it into utf-8?

Your help is greatly appreciated.

Regards

Latest version of your script installed on AWS LAMP bitnami server php5.4

**Comment by Synchro** [comment]
Use UTF-8 everywhere, for example make sure your page is delivered using a UTF-8 charset HTTP header, use a UTF-8 charset meta tag in your HTML, and make sure your scripts, database, and editors are all set to use UTF-8. As soon as you start mixing charsets, you're asking for trouble, as you're finding. So do this:

    <form action="sendmail_mini.php" accept-charset="UTF-8" method="post">

and in your PHPMailer code:

    $mail->CharSet = 'utf-8';

Also, nobody should be using PHP 5.4 now; It's long out of support. Use at least PHP 7.2.
