### ISSUE TITLE
You must provide at least one recipient email address.

### ISSUE THREAD

**Issue by bilalawanit15** [PHPMailer/PHPMailer#1775]
PHPMailer was working for me but for the last few days I am not receiving emails. I am displaying error message on front end and I am getting this error using `$mail->ErrorInfo`

You must provide at least one recipient email address.

I did not change any thing in my code and suddenly it started to happen. I am using 
`$mail->addAddress($_REQUEST['email']); `
to add email address. Any suggestion regarding this will be much appreciated.

**Comment by Synchro** [comment]
You will get this error if what is submitted in `$_REQUEST['email']` is not a valid address. You can check it by looking at the return value from `addAddress`:

```php
if (!$mail->addAddress($_REQUEST['email'])) {
    die('You must provide a valid email address');
}
```

That said, what you're doing here is a bad idea anyway. Don't send email to recipients provided by a form field; if you include *any* other content from them, you have built a spam gateway. Send email from yourself, to yourself, and use the submitter's address as a reply-to address. See [the contact form example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/contactform.phps) for how to do this.

**Comment by bilalawanit15** [comment]
Thank you for your response. But I have tried to add email address in this way as well but I was getting the same error. So I think this is happening because of something else.

`address = "whoto@otherdomain.com";
$mail->AddAddress($address, "John Doe");`

**Comment by Synchro** [comment]
Well you've not provided any other code, so I can't tell.
