### ISSUE TITLE
trim expects parameter 1 to be string, boolean given

### ISSUE THREAD

**Issue by aminnairi** [PHPMailer/PHPMailer#1778]
# Problem description

Unable to send mail using OVH's pro mail from time to time.

# Explaination

[substr()](https://www.php.net/manual/en/function.substr.php) can sometimes return a boolean.
[trim()](https://www.php.net/manual/en/function.trim.php) expects parameter 1 to be a string.

There is no checking made on the return type of substr() leading to the error in the issue title.

The `HELO` discovery's messages from OVH have empty response some times.

# Working fix

In the file `SMTP.php` at line `779`:

```diff
- $s = trim(substr($s, 4));
+ $s = trim(substr(empty($s) ? "250-" : $s, 4));
```

**Comment by Synchro** [comment]
Wow, that's a broken server! Have you reported it to them?

I'm not sure that assuming a `250` response is a great idea though, especially if you expect it to be the definitive response, in which case it would have a trailing space which is removed by the trim, rather than the `-`.

**Comment by aminnairi** [comment]
Yes, I put that value here as a todo because this honestly goes way beyond my area of knowledge. But I figured I cannot control what the server will answer me but I can control how to treat the response. I think assuming a default value or handling the case where `substr` will return `FALSE` would be a good idea for futur proofing the process. What do you think?

**Comment by Synchro** [comment]
I quite agree that it should trap the missing output and avoid the trim error. I'm not sure what to do about the default behaviour though - while it might act as a workaround for OVH, if that was done generally it might break other servers that behave correctly but have network issues that *should* be reported as errors. It may be better to document it and suggest putting it in a subclass if you run into that problem.
