### ISSUE TITLE
Add text to PHP mail

### ISSUE THREAD

**Issue by joseandjm1** [PHPMailer/PHPMailer#1782]
Hi

I use php for send mail from opencart, i need add text on mail in footer.. how can i do it?
Thanks so much

$mail->msgHTML(html_entity_decode(trim($this->request->post['message']), ENT_QUOTES, 'UTF-8'))     "text go here with <br> lines"

**Comment by Synchro** [comment]
This is two separate things. First set the `Body` and `AltBody` using `msgHTML()`:

    $mail->msgHTML(html_entity_decode(trim($this->request->post['message']), ENT_QUOTES, 'UTF-8'));

Then add on whatever text you want:

    $mail->Body .= "text go here with 
lines";

You may find that it's more convenient to combine the two:

    $mail->msgHTML(html_entity_decode(trim($this->request->post['message']), ENT_QUOTES, 'UTF-8'). "text go here with 
lines");

**Comment by joseandjm1** [comment]
Thanks so much @Synchro

> 
> 
> This is two separate things. First set the `Body` and `AltBody` using `msgHTML()`:
> 
> ```
> $mail->msgHTML(html_entity_decode(trim($this->request->post['message']), ENT_QUOTES, 'UTF-8'));
> ```
> 
> Then add on whatever text you want:
> 
> ```
> $mail->Body .= "text go here with 
> ```
> 
> lines";
> 
> You may find that it's more convenient to combine the two:
> 
> ```
> $mail->msgHTML(html_entity_decode(trim($this->request->post['message']), ENT_QUOTES, 'UTF-8'). "text go here with 
> ```
> 
> lines");
