### ISSUE TITLE
PHP Mailer sending speed is very slow

### ISSUE THREAD

**Issue by arfan-hostingshouse** [PHPMailer/PHPMailer#1783]
Hello I am using PHP mailer for sending emails. It's speed only 2000 emails per minute. After Every 500 email sending i am making connection for 
` $mail->SMTPKeepAlive = true;`
I am using Linux system 16GB RAM 
How i can increase my speed upto 10k+ per minute with 1 connection? 
Log for How much time 1 email take to send?
Thanks

**Comment by Synchro** [comment]
That's already quite fast. On my own system I can do about 5 times that but with multiple connections. Have you done the things mentioned in [the wiki article on sending to lists](https://github.com/PHPMailer/PHPMailer/wiki/Sending-to-lists) and followed [the mailing list example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps)? Keepalive is one important thing, but the other big factor is how much you have inside your sending loop (which I'd need to see). Another important consideration is where your mail server is - you want it to be either on localhost or on your local network - and whether it is configured/designed for high performance (most free mail servers are not).

To diagnose where your bottlenecks are within your code, I would use xdebug to profile it (it's like having *very* fine-grained logging) and view it in qcachegrind. Outside your code, look at local CPU, disk, and network utilisation.

That said, all this is doing is delivering to your local mail server - onward delivery to final destinations is subject to many things that are outside your control - for example Yahoo limits you to a very small number of simultaneous connections and messages/hour that you can send, so fast message generation is not necessarily what's slowing down your deliveries. To deal with that properly requires that your mail server supports domain group throttling, and that's a relatively rare feature.
