### ISSUE TITLE
Regarding slow delivery of emails

### ISSUE THREAD

**Issue by ravindch2005** [PHPMailer/PHPMailer#1786]
We are using GMAIL's "Gsuite for education" as out email server. While sending message it takes too much time like for sending emails to 10 IDs it takes time 1-2 minutes. What might be the reason, is there any particular reason that I should keep in mind? Code is given here 

                     $nits_rec[$x] = new PHPMailer(true);
                        $nits_rec[$x]->isSMTP();
                        $nits_rec[$x]->SMTPAuth = "true";
                       // $nits_rec[$x]->SMTPDebug = 2;
                        $nits_rec[$x]->IsHTML(true);
                        $nits_rec[$x]->SMTPAuth = true;
                        $nits_rec[$x]->SMTPSecure = 'tls';
                        $nits_rec[$x]->Host     = "smtp.gmail.com"; 
                        $nits_rec[$x]->Port = 587;
			$nits_rec[$x]->SMTPKeepAlive = true;
                        $nits_rec[$x]->Mailer   = "smtp";
                        $nits_rec[$x]->Priority = '1';
                        $nits_rec[$x]->AltBody = "Reply to this email if you are seeing this kind of mail.";

                        $nits_rec[$x]->Username = $email_list[$x][0]; //to change email id from sending
                        $nits_rec[$x]->Password = $email_list[$x][1]; //its password
                        $nits_rec[$x]->From     = $email_list[$x][0]; 
                        $nits_rec[$x]->FromName = "NIT Raipur";
                        $nits_rec[$x]->AddReplyTo($row['email'],"NIT Raipur Information");
                        $nits_rec[$x]->Body = $body;
                        $nits_rec[$x]->Subject = $sub;

	             $nits_rec[$x]->AddAddress($to, $fn); // Variables contain address coming from db
                     if(!$nits_rec[$x]->send())
				{
                                         echo "Error";
                                 }
                     else
                                {
                                       echo "Sent";
                                }
                     $nits_rec[$x]->ClearAddresses();
}
catch (Exception $e) 
{
    echo 'Message could not be sent. Mailer Error: ', $mail->ErrorInfo;
}

**Comment by Synchro** [comment]
This is odd code. Why are you creating a new instance and putting it in an array every time? That's very wasteful, and means that keepalive can't work, so every message will incur authentication overhead, which is probably the main reason it's slow for you. Follow [the mailing list example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps) for how to do this correctly.

The other thing that would make this go much faster is if you send via a local mail server.

**Comment by ravindch2005** [comment]
Thanks for your reply. Reason behind using array is that Gmail has the constraint on sending the emails. We are unable to send more than 1000 emails per day using one email so we have created an array of email-ids and sending the emails using them. What I have sent is a part of the complete code only. I have also tried one email-id as sender(without creating array)  and checked for the same. In that case also it is taking too long.

**Comment by Synchro** [comment]
That's fine, except you are creating a new instance for each *message*, not each connection / batch of messages, and you can re-use a single instance of PHPMailer across *all* your connections. You can close an SMTP connection (that you had previously opened in keepalive mode) manually using `$mail->smtpClose();`; doing that will allow you to change authentication settings and reconnect for each batch.

Overall though it sounds like you need to set up your own mail server or use an external sending API; gmail really isn't meant for this.
