### ISSUE TITLE
phpmailer sendmail bcc

### ISSUE THREAD

**Issue by rajan77** [PHPMailer/PHPMailer#1787]
Hello

If I use sendmail option in PHPmailer, how do I add bcc? do I have to use it in the header?
I tried mail->addBCC etc but always got errors

If so, how please?

Many thanks

**Comment by Synchro** [comment]
`addBCC()` is the right way to do it - what errors are you seeing?

**Comment by rajan77** [comment]
I did an RTFM later... and I found addBCC(string  $address, string  $name = '')

And it works fine, thanks!

I prefer Sendmail over SMTP. The SMTp settings are screwed up by my blessed hosting provider

**Comment by Synchro** [comment]
It's faster (and safer) to use SMTP to localhost than to invoke a local sendmail binary - have a read of [the sending to lists wiki article](https://github.com/PHPMailer/PHPMailer/wiki/Sending-to-lists).
