### ISSUE TITLE
PHP7.3.0+Deprecate  FILTER_FLAG_SCHEME_REQUIRED

### ISSUE THREAD

**Issue by PoppinRubo** [PHPMailer/PHPMailer#1788]
PHP 7.3+ fail in send
filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated

**Comment by Synchro** [comment]
Update to a recent version; this was removed [ages ago](https://github.com/PHPMailer/PHPMailer/commit/8f558ec0535c1fc348fd8c2c3c80de55dbc1f94d), and please search before you post new issues as this same issue has now been opened [4 times](https://github.com/PHPMailer/PHPMailer/search?q=FILTER_FLAG_SCHEME_REQUIRED&type=Issues).
