### ISSUE TITLE
Error with php_network_getaddresses

### ISSUE THREAD

**Issue by vsachin** [PHPMailer/PHPMailer#179]
Uncaught exception 'ErrorException' with message 'stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known' in /home/arvind/Projects/collab_website/web/social/PHPMailer/class.smtp.php:218
Stack trace:

This error shows up while using your library. Can i know what exactly is causing this?

**Comment by blackvvine** [comment]
Hi, I'm on linux and I have the very same problem. Do I have to change anything in php.ini ?
Why isn't this mentioned in the installation tutorial at main github page?

**Comment by Synchro** [comment]
It's not mentioned because most people don't have the problem, but it is covered in great depth in the documentation that the readme links to.

**Comment by vpilotto** [comment]
> I see there was no answer from vsachin.
What you need to do is enable "extension=php_openssl.dll" in your PHP.INI
(either by removing comment in front of it, or by adding the new line with this content, in "extensions" section)
Then, of course, restart Apache.

Thanks

**Comment by Sathiesh** [comment]
I am getting  errors like below

**Comment by Sathiesh** [comment]
I am getting errors like below while using PHPMailer and am using php 7.0. Actually my mailing process worked good but I just restart my system and connect it  again it shows an error likes below,    <br />                                                                                   Connection: opening to smtp.gmail.com:587, timeout=300, options=array ()
Connection failed. Error #2: stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known [/var/www/html/email/PHPMailerMaster/class.smtp.php line 292]
Connection failed. Error #2: stream_socket_client(): unable to connect to smtp.gmail.com:587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) [/var/www/html/email/PHPMailerMaster/class.smtp.php line 292]
SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Name or service not known (0)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting<br />I  enabled "extension=php_openssl.dll" in my PHP.INI <br /> Kindly help me to resolve it

**Comment by Synchro** [comment]
When it says "name or service not known", it means your DNS config is broken, like the troubleshooting guide says.

**Comment by Sathiesh** [comment]
Yeah DNS config broken means that I have enable php_openssl.dll extension in my PHP.INI right? or any other solution having
Please help me solve it

**Comment by Synchro** [comment]
No. DNS has nothing to to with SSL.

**Comment by Sathiesh** [comment]
Oh right. then how to solve that issue?

**Comment by Sathiesh** [comment]
@Synchro am waiting for your response

**Comment by Sathiesh** [comment]
@Synchro I tested all the commands which are given in troubleshoot guide, everything works perfect but the mail doesn't sent
Kindly help me

**Comment by Synchro** [comment]
Check your DNS and PHP config, search for solutions and fix it like everyone else does. This is not a PHPMailer problem.
