### ISSUE TITLE
double white spaces in subject with Outlook

### ISSUE THREAD

**Issue by wergio** [PHPMailer/PHPMailer#1791]
I noticed a strange behaviour in mail recieved by Outlook clients: double white spaces appear where should be only one, approximately where the subject header "folds". this doesn't happen with other clients (thunderbird, gmail, etc)

I think I tracked down the problem to this piece of code:

https://github.com/PHPMailer/PHPMailer/blob/db4de4eb0028a06880f66db5a7e7ebacc57c1513/src/PHPMailer.php#L1403-L1404

what's the purpose of this? on linux machine it forces the use of \n (instead of \r\n ) for folding mail headers, but I think it's not compliant to RFC, so generating the problem...

removing that row of code makes all working flawlessly for me

**Comment by Synchro** [comment]
The reason for that is that the PHP `mail()` function expects local-format line breaks, regardless of the RFC; when you pass in `\n` breaks, it will convert them to `\r\n` before sending.

Generally the PHP mail function is buggy, unsafe, and unpredictable (as you're seeing), so I'd recommend avoiding it - SMTP to localhost is both faster and safer - and it means that this code is not run.

**Comment by wergio** [comment]
From php mail() docs: https://www.php.net/manual/en/function.mail.php

>     Multiple extra headers should be separated with a CRLF (\r\n)

>     Note: If messages are not received, try using a LF (\n) only. Some Unix mail transfer agents (most notably » qmail) replace LF by CRLF automatically (which leads to doubling CR if CRLF is used). This should be a last resort, as it does not comply with » RFC 2822.

IMHO the "last resort" solution should not be the default behaviour. the best solution could be detecting the buggy MTA and setting "\n" only in that case, but i don't know if it's possibile

**Comment by Synchro** [comment]
I don't think it's possible to detect what the MTA is doing because it's hidden behind the `mail()` function. Also PHPMailer used to not use `PHP_EOL` like this, and that also caused problems (because these "buggy" MTAs are very common), which led to a major changes to make line break formatting much more consistent in the 6.0 release. It's yet another reason not to use `mail()`, as if you needed any more. In the mean time, use SMTP to localhost as it's better in pretty much every way, and does not suffer this problem at all.

**Comment by Synchro** [comment]
See also these notes on the mail function, all of which show using `LF` as a solution to various problems: [1](https://www.php.net/manual/en/function.mail.php#121027), [2](https://www.php.net/manual/en/function.mail.php#59773), [3](https://www.php.net/manual/en/function.mail.php#121028), [4](https://www.php.net/manual/en/function.mail.php#111797), [5](https://www.php.net/manual/en/function.mail.php#40204)

**Comment by wergio** [comment]
ok I will switch to SMTP, seems the best solutions, thanks
