### ISSUE TITLE
Semicolon in From not quoted

### ISSUE THREAD

**Issue by blaaat** [PHPMailer/PHPMailer#1793]
Please check these things before submitting your issue:

# Problem description

When using a semicolon in the From name, the name in the from header should be quoted according to [rfc822] (https://www.w3.org/Protocols/rfc822/3_Lexical.html#z2)

> specials    =  "(" / ")" / "<" / ">" / "@"  ; Must be in quoted-
            /  "," / ";" / ":" / "\" / <">  ;  string, to use
            /  "." / "[" / "]"              ;  within a word.

Currently this is not happening; resulting in addresses that are not parseable by `mailparse_rfc822_parse_addresses`

Did not test; but same issue might exist in other header fields.

# Code to reproduce
$phpMailer->setFrom('test@test.com', 'Test: hi é', false);

# Debug output

**Comment by Synchro** [comment]
I can't make this misbehave as you describe. Quoting in headers is handled [here](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L3110). The pattern there does *not* include `:`, meaning that the value should end up quoted, which it does. If I use `Test: hi` as the from name, I get this in the sent message:

    From: "Test: hi" <test@test.com>

which quotes it as expected. If I add in a non-ascii char `Test: hi é'`, the encoding changes, and so does the output:

    From: =?utf-8?Q?Test=3A_hi_=C3=A9?= <test@test.com>

Here the `:` has been Q-encoded as `=3A`, so the resulting string no longer contains a literal `:` and thus no longer requires quoting.

**Comment by blaaat** [comment]
I see, sorry! Thanks for the help
