### ISSUE TITLE
phpMailer is too slow ( like 5 mails in 5 minutes) in following coding while sending messages using 10 email ids of gmail

### ISSUE THREAD

**Issue by ravindch2005** [PHPMailer/PHPMailer#1796]
<body >

<script language="Javascript" type="text/javascript" src="js/js1.js">
 </script>
<script language="Javascript" type="text/javascript" src="js/js2.js">
 </script>
<script language="Javascript" type="text/javascript" src="js/jswin.js">
 </script>
<link rel="stylesheet" type="text/css" href="css/table.css" />
<?php
set_time_limit(36000);
session_start();
include 'connect.php';
include 'functions.php';
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require 'vendor/autoload.php';
 
ignore_user_abort(true);

//include '../ldap/connect_ldap.php';
//if(!isset($_SESSION['user_id']) || !($_SESSION['user_type']=='clerk') )
if(!isset($_SESSION['user_id']))
{
	echo "Not authorized. Please login as authorized user1 ";
}
else
{
$bywhome=$_SESSION['user_id'];
         
/* File puploading Coding*/
if(isset($_FILES['file']))
{

        $file=$_FILES['file'];
//file properties
$file_name= $file['name'];
if($file_name!="")
{
$file_tmp= $file['tmp_name'];
$file_size= $file['size'];
$file_error=$file['error'];
//file extension
$file_ext=explode('.',$file_name);
$file_ext=strtolower(end($file_ext));
$allowed= array('jpg','jpeg','doc','docx','pdf');
 if(!in_array($file_ext,$allowed))
	{ 
		die('Format not supported.  <br><INPUT TYPE=button VALUE=Back onClick=history.go(-1);>');
	}
  if($file_error===0) 
         { if($file_size>=10485760)
                 {
		   die('File having size more than 10MB not allowed.  <br><INPUT TYPE=button VALUE=Back onClick=history.go(-1);>');
                 }
         }
         else
         {
                echo "maximum size is 10 mb";
         }
}
}

$email_list = array
  (
  array("xxx1@gmail.com","xxx1"),
  array("xxx2@gmail.com","xxx2!"),
  array("xxx3@gmail.com","xxx3!"),
  array("xxx4@example.com","xxx4!"),
  array("xxx5@example.com","xxx5!"),
  array("xxx6@example.com","xxx6!"),
  array("xxx7@example.com","xxx7!"),
  array("xxx8@example.com","xxx8!"),
  array("xxx9@example.com","xxx9!"),
  array("xxx10@example.com","xxx10"),
  );

// GET the data of POST array which consists email-ids of the students
$fname=$_POST["name"];
$stu_check1=explode(';',$_POST["stu_check1"]);
$msg=strip_tags($_POST["mailmsg"]);
$msgsub=trim(strip_tags(mysqli_real_escape_string($conn,$_POST["msgsub"])));
$mob=$_POST["mob"];
$email=$_POST["email"];
$query="select * from account where roll_no='".$_SESSION['user_id']."'";
$result=mysqli_query($conn, $query);
$row=mysqli_fetch_assoc($result);

$msg=$msg."<br><br><br><br>This message is sent by ".$row['fname']." ".$row['lname']."<br> Department: ".$row['dept']." <br>Email-ID: ".$row['email'];

$sub=$msgsub;
$body=$msg;
$msgtype="ldap";

try
{

    
//Get the number of records
	$cnt = count($email);
	 
	$t=(int)($cnt / 10); // Divide them in multipple of 10s
	//echo $t;
	$r=$cnt%10; // Get the remainer which would be less than 10
	$c=0;  // Initialize a variable which would hold the number of email recepients in future 
$nits_rec=array(); // Create an array that would be used to send the emails

//Initialize 10 emailer objects 
for($x=0; $x<10; $x++) 
	{

		 if($c==$cnt)
			break;
			//smtp set paramenters
///////////////////////////////////

                        $nits_rec[$x] = new PHPMailer(true);

                        $nits_rec[$x]->isSMTP();
                        $nits_rec[$x]->SMTPAuth = "true";
                       // $nits_rec[$x]->SMTPDebug = 2;
                        $nits_rec[$x]->IsHTML(true);
                        $nits_rec[$x]->SMTPAuth = true;
                        $nits_rec[$x]->SMTPSecure = 'tls';
                        $nits_rec[$x]->Host     = "smtp.gmail.com"; // HOST SMTP OUT ADDRESS
                        $nits_rec[$x]->Port = 587;
						$nits_rec[$x]->SMTPKeepAlive = true;
                        $nits_rec[$x]->Mailer   = "smtp";
                        $nits_rec[$x]->Priority = '1';
                        $nits_rec[$x]->AltBody = "Reply to this email if you are seeing this kind of mail.";

                        $nits_rec[$x]->Username = $email_list[$x][0]; //to change email id from sending
                        $nits_rec[$x]->Password = $email_list[$x][1]; //its password
                        $nits_rec[$x]->From     = $email_list[$x][0]; 
                        $nits_rec[$x]->FromName = "Information Tech Dept";
                        $nits_rec[$x]->AddReplyTo($row['email'],"Infor Tech Dept");
                        $nits_rec[$x]->Body = $body;
                        $nits_rec[$x]->Subject = $sub;

                 		if($file_name!="")
						{
							$nits_rec[$x]->AddAttachment($file_tmp, $file_name);
						}
						$c++;
        }                	

 // Following is the coding to send the emails to IDs which are remaing as remainder of 10
	 
$c=0; 
for($x=0; $x<10; $x++)
	{
		 if($c==$cnt)
			break;
		for ($i=0; $i< $t ;$i++)
		{
		        if($stu_check1[$c])
        		{
				$fn=trim(strip_tags(mysqli_real_escape_string($conn,$fname[$c])));
				$e=trim(strip_tags(mysqli_real_escape_string($conn,$email[$c])));
				$to=$e;
   				$nits_rec[$x]->AddAddress($to, $fn);
				echo $c." ".$to;
   				if(!$nits_rec[$x]->send())
   				{
                                	echo "Email Not Sent to ".$to. "<br>";

  				}
				else
				{
 
					echo "Message sent to : ".$to. "<br>";
				}
 
			}
				$c++;

		}//Inner For Loop
		$nits_rec[$x]->ClearAddresses();
	}// Outer For Loop
 
	if($c<$cnt)
		{	$x--;
		                for ($i=$c; $i< $cnt; $i++)
		                {
		                	//echo "Hello3";
        	        	        if($stu_check1[$i])
                	        	{
//                        	        $c++;
                                	$fn=trim(strip_tags(mysqli_real_escape_string($conn,$fname[$i])));
	                                //$m=trim(strip_tags(mysqli_real_escape_string($conn,$mob[$i])));
	                                $e=trim(strip_tags(mysqli_real_escape_string($conn,$email[$i])));
	                                $to=$e;
	                                $nits_rec[$x]->AddAddress($to,$fn);
				echo $c."testtt ".$to;
	                    			if(!$nits_rec[$x]->send())
									{
  											echo "Email Not Sent to ".$to. "<br>";

  									}
									else
									{
 											echo "Message sent to : ".$to. "<br>";
									}

								$nits_rec[$x]->ClearAddresses();
                 	        	}

                		}
		}

	  
} //Try Closed

catch (Exception $e) 
{
    echo 'Message could not be sent. Mailer Error: ', $mail->ErrorInfo;
}

}
?>

<br><INPUT TYPE=button VALUE=Back onClick=history.go(-1)>

**Comment by Synchro** [comment]
Please [read the docs on sending to lists](https://github.com/PHPMailer/PHPMailer/wiki/Sending-to-lists) and base your code on [the mailing list example provided](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps).
