### ISSUE TITLE
Want to send emails continuously ignoring  of wrong email-id

### ISSUE THREAD

**Issue by ravindch2005** [PHPMailer/PHPMailer#1797]
Using AddAddress() function I am adding a list of recipients and then sending emails to them using Send() function. If the address of any recipient is wrong like xyz@gmail.coom then the control throws an error and the process of sending message to the recipients is terminated. I want to send the messages to remaining email-ids ignoring the wrong email-id encountered in the middle of the process. Is there any solution for this? Please help me. Thanks

**Comment by ooxi** [comment]
Are you sending one mail per address or one mail containing multiple addresses?

**Comment by Synchro** [comment]
Basically, catch the errors and continue your sending loop.

Check the return value from `addAddress()`, which will return false if the address is invalid, and don't even attempt to send to that recipient.

In your sending loop (see [the mailing list example provided](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps) for how to do this efficiently), enable exceptions (pass `true` to the constructor), wrap your call to `send()` in a try/catch block; that will let you know there is an error, and you can continue trying to send to the next recipient (you may need to call `$mail->smtp->reset()` after an error to resync the SMTP connection).

**Comment by Synchro** [comment]
I have just expanded the mailing list example to incorporate more error checking

**Comment by ravindch2005** [comment]
> Basically, catch the errors and continue your sending loop.
> 
> Check the return value from `addAddress()`, which will return false if the address is invalid, and don't even attempt to send to that recipient.
> 
> In your sending loop (see [the mailing list example provided](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps) for how to do this efficiently), enable exceptions (pass `true` to the constructor), wrap your call to `send()` in a try/catch block; that will let you know there is an error, and you can continue trying to send to the next recipient (you may need to call `$mail->smtp->reset()` after an error to resync the SMTP connection).

**Comment by ravindch2005** [comment]
Actually in your  "mailing list example" You are sending one email at a time. I had used that solution but it was taking too long to send the emails to all the members. So I am adding all the addresses once and sending them using only one call of send() function. In this scenario if any address is wrong exception is thrown and the process terminates. Is there any solution for this scenario.
Regards

**Comment by ravindch2005** [comment]
> Are you sending one mail per address or one mail containing multiple addresses?

One email to multiple addresses.

**Comment by ravindch2005** [comment]
> I have just expanded the mailing list example to incorporate more error checking



> Basically, catch the errors and continue your sending loop.
> 
> Check the return value from `addAddress()`, which will return false if the address is invalid, and don't even attempt to send to that recipient.
> 
> In your sending loop (see [the mailing list example provided](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps) for how to do this efficiently), enable exceptions (pass `true` to the constructor), wrap your call to `send()` in a try/catch block; that will let you know there is an error, and you can continue trying to send to the next recipient (you may need to call `$mail->smtp->reset()` after an error to resync the SMTP connection).

Actually in your "mailing list example" You are sending one email at a time. I had used that solution but it was taking too long to send the emails to all the members. So I am adding all the addresses once and sending them using only one call of send() function. In this scenario if any address is wrong exception is thrown and the process terminates. Is there any solution for this scenario.
Regards

**Comment by Synchro** [comment]
It was probably taking longer because you were not using keepalive. I can send up to about 250 messages *per second* using this approach; it's not slow.

If you have one address out of many that fail to send (note not that are invalid in the first place), the send continues, [as you can see in the code](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L1812), but you will still get an error at the end, from which you can find out which addresses failed.
