### ISSUE TITLE
Phpmailer Downloaded from Composer, spam

### ISSUE THREAD

**Issue by jeanmunevar** [PHPMailer/PHPMailer#1800]
Guys, I downloaded phmailer with composer, everything went okay until I received a mail from my smtp provider telling me that my email is sending spam, I searched the emails and he was right, many emails were sent to thousand domains. is possible that the library I downloaded with composer is hacked? is there a way to fix it?

**Comment by Synchro** [comment]
It's most likely to be a problem in how you are using PHPMailer rather than in the library itself. Can you show the code you're using it with?

**Comment by jeanmunevar** [comment]
Sure, 
`<?php
require './vendor/autoload.php';
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require './vendor/phpmailer/phpmailer/src/Exception.php';
require './vendor/phpmailer/phpmailer/src/PHPMailer.php';
require './vendor/phpmailer/phpmailer/src/SMTP.php';
//
$nombre_fichero = "./archivos/req/notis.txt";
$gestor = fopen($nombre_fichero, "r");
$contenido = fread($gestor, filesize($nombre_fichero));
$array =explode("\n", $contenido , filesize($nombre_fichero));
$datosEnArray2 = array();
$mensajes=[];
//Fecha servidor
//$fecha = new DateTime();
//$fecha->setDate(2019, 05, 31);
foreach($array as $primerArray){
    $datosEnArray = explode(';', $primerArray);
    array_push($datosEnArray2, $datosEnArray);
}

function save_mail($mail) {
   
    $path = "{mail.servercom.co:993/imap/ssl/novalidate-cert}INBOX.Sent";
    //Tell your server to open an IMAP connection using the same username and password as you used for SMTP
    $imapStream = imap_open($path, $mail->Username, $mail->Password);
    $result = imap_append($imapStream, $path, $mail->getSentMIMEMessage());
    imap_close($imapStream);
    return $result;
}
$cont=0;
$tam=sizeof($datosEnArray2);
while($tam > $cont){
    foreach ($datosEnArray2 as $index => $columna) {
//    echo sizeof($datosEnArray2)."\n";
        //$numeroLetras =  NumeroALetras::convertir($numeroLetras, 'pesos');
        $cont=$cont+1;
        try {
            $mail = new PHPMailer();
            //Configuracion del servidor de correo
            $mail->SMTPDebug = 0;                                       // Habilita o deshabilita el debug
            $mail->isSMTP();                                            // Usar protocolo smtp
            $mail->CharSet = 'UTF-8';
            $mail->Encoding = 'base64';
            $mail->Host       = 'server';  //              especifica el servidor smtp
            $mail->SMTPAuth   = true;                                   // habilita autenticacion
            $mail->Username   = '';                     // SMTP usuario
            $mail->Password   = '';// SMTP contraseña
            $mail->SMTPSecure = 'ssl';                                  // SSl y TSL encriptacion
            $mail->Port       = ;                                    // puerto a conectar
            //remitentes
            $mail->setFrom('', utf8_decode('Notificacion de empresas morosas'));
            //Receptores
            // Name is optional
            $mail->addAddress($columna[18], $columna[1]);
            if ($columna[19]!== null){
                $mail->addAddress($columna[19], $columna[1]);
            }
            //Cuerpo del mensaje
            $message = 'some html'
            // Content
            $mail->isHTML(true);                                  // Set email format to HTML
            $mail->Subject = utf8_decode($columna[8]);// Asunto del email
            $mail->Body    = $message;
            $mail->AltBody = $message;
            if($mail->send()){
                $save_result = save_mail($mail);
                if (!$save_result) {
                    array_push($mensajes,[
                        'estado' => 'Error',
                        'mensaje' => 'Error guardando correo en enviados Nit: '.$columna[3]
                    ]);
                }
                echo $cont." Correo enviado del nit: ".$columna[3]."\n";
            }
        }
        catch (Exception $e) {
            array_push($mensajes,[
                'estado' => 'Error',
                'mensaje' => "Email no se pudo enviar por el error: {$mail->ErrorInfo}"." Del nit: ".$columna[3]
            ]);
        }
    }
}
echo json_encode($mensajes, true);`

**Comment by Synchro** [comment]
Hm. Nothing interesting there, unless you have something that allows access to the `$nombre_fichero` file, and something different going into `$mail->Body`. Any other uses? If you look at your web server logs I expect you'll find lots of hits on some URL that's being abused for this. None of the PHPMailer library files do anything at all by themselves, and they don't read anything from input sources (`$_POST` etc).
