### ISSUE TITLE
Composer dev installation hang

### ISSUE THREAD

**Issue by Synchro** [PHPMailer/PHPMailer#1801]
The Travis-CI process for PHPMailer is currently having some issues. I had to switch the php-cs-fixer stage from PHP 5.5 to 5.6 because Travis no longer seems to support 5.5, and this has led to [a can of worms](https://travis-ci.org/PHPMailer/PHPMailer/jobs/567114638).

php-cs-fixer is now suggesting some rather strange options by default - in particular `yoda_style`, and `native_function_invocation` options - and it would be helpful if someone could figure out how to get rid of those.

A second, but related, problem is that the composer `require-dev` config currently results in a hang on install or update. It seems that current versions of php-cs-fixer and phpdocumentor have some kind of conflict, resulting in an infinite loop in composer. This means that I can't even test fixes for the first problem!

So, if anyone has some time and ideas for how to fix the composer and php-cs configs, it would be very helpful.

**Comment by x011** [comment]
!month and no help? Great support from devs, this project is probably dead, no wonder when it uses syntax like:

use PHPMailer\PHPMailer\PHPMailer; How dumb can this be?

**Comment by Synchro** [comment]
Perhaps you shouldn't go around insulting people just because you don't understand namespacing? You also failed to read the readme which explains exactly why that class ends up with that FQCN. You also failed to notice that I am the maintainer, and also the one that created this issue.

Either submit a PR, or go away.

**Comment by janek109** [comment]
@Synchro Hey, seam to no problem with php 5.6.30 with composer installation

➜  PHPMailer git:(master) php /usr/local/bin/composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 82 installs, 0 updates, 0 removals
  - Installing phpdocumentor/reflection-docblock (2.0.5): Downloading (100%)
  - Installing nikic/php-parser (v1.4.1): Downloading (100%)
  - Installing psr/log (1.1.0): Downloading (100%)
  - Installing phpdocumentor/reflection (3.0.1): Downloading (100%)
  - Installing symfony/finder (v2.8.50): Downloading (100%)
  - Installing phpdocumentor/fileset (1.0.0): Downloading (100%)
  - Installing phpdocumentor/graphviz (1.0.4): Downloading (100%)
  - Installing zendframework/zend-stdlib (2.7.7): Downloading (100%)
  - Installing zendframework/zend-hydrator (1.1.0): Downloading (100%)
  - Installing zendframework/zend-filter (2.9.2): Downloading (100%)
  - Installing psr/container (1.0.0): Downloading (100%)
  - Installing container-interop/container-interop (1.2.0): Downloading (100%)
  - Installing zendframework/zend-servicemanager (2.7.11): Downloading (100%)
  - Installing zendframework/zend-eventmanager (3.0.1): Downloading (100%)
  - Installing zendframework/zend-cache (2.7.2): Downloading (100%)
  - Installing zendframework/zend-json (2.6.1): Downloading (100%)
  - Installing zendframework/zend-serializer (2.7.2): Downloading (100%)
  - Installing zendframework/zend-i18n (2.7.3): Downloading (100%)
  - Installing zendframework/zend-config (2.6.0): Downloading (100%)
  - Installing kherge/version (1.0.1): Downloading (100%)
  - Installing seld/jsonlint (1.7.1): Downloading (100%)
  - Installing justinrainbow/json-schema (1.6.1): Downloading (100%)
  - Installing herrera-io/json (1.0.3): Downloading (100%)
  - Installing herrera-io/phar-update (1.0.3): Downloading (100%)
  - Installing doctrine/instantiator (1.0.5): Downloading (100%)
  - Installing doctrine/lexer (1.0.2): Downloading (100%)
  - Installing doctrine/annotations (v1.2.7): Downloading (100%)
  - Installing phpoption/phpoption (1.5.0): Downloading (100%)
  - Installing phpcollection/phpcollection (0.5.0): Downloading (100%)
  - Installing jms/parser-lib (1.0.0): Downloading (100%)
  - Installing jms/metadata (1.7.0): Downloading (100%)
  - Installing jms/serializer (1.14.0): Downloading (100%)
  - Installing symfony/filesystem (v3.0.9): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.12.0): Downloading (100%)
  - Installing symfony/config (v2.8.50): Downloading (100%)
  - Installing symfony/stopwatch (v2.8.50): Downloading (100%)
  - Installing symfony/event-dispatcher (v2.8.50): Downloading (100%)
  - Installing zetacomponents/base (1.9.1): Downloading (100%)
  - Installing zetacomponents/document (1.3.1): Downloading (100%)
  - Installing symfony/process (v2.8.50): Downloading (100%)
  - Installing erusev/parsedown (1.7.3): Downloading (100%)
  - Installing twig/twig (v1.42.3): Downloading (100%)
  - Installing monolog/monolog (1.24.0): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.12.0): Downloading (100%)
  - Installing symfony/debug (v3.0.9): Downloading (100%)
  - Installing symfony/console (v2.8.50): Downloading (100%)
  - Installing symfony/translation (v3.0.9): Downloading (100%)
  - Installing symfony/validator (v2.8.50): Downloading (100%)
  - Installing pimple/pimple (v1.1.1): Downloading (100%)
  - Installing cilex/console-service-provider (1.0.0): Downloading (100%)
  - Installing cilex/cilex (1.1.0): Downloading (100%)
  - Installing phpdocumentor/phpdocumentor (v2.9.0): Downloading (100%)
  - Installing symfony/polyfill-php72 (v1.12.0): Downloading (100%)
  - Installing paragonie/random_compat (v2.0.18): Downloading (100%)
  - Installing symfony/polyfill-php70 (v1.12.0): Downloading (100%)
  - Installing ircmaxell/password-compat (v1.0.4): Downloading (100%)
  - Installing symfony/polyfill-php55 (v1.12.0): Downloading (100%)
  - Installing symfony/polyfill-php54 (v1.12.0): Downloading (100%)
  - Installing symfony/options-resolver (v3.4.31): Downloading (100%)
  - Installing sebastian/diff (1.4.3): Downloading (100%)
  - Installing composer/xdebug-handler (1.3.3): Downloading (100%)
  - Installing composer/semver (1.5.0): Downloading (100%)
  - Installing friendsofphp/php-cs-fixer (v2.2.20): Downloading (100%)
  - Installing myclabs/deep-copy (1.7.0): Downloading (100%)
  - Installing sebastian/version (2.0.1): Downloading (100%)
  - Installing sebastian/resource-operations (1.0.0): Downloading (100%)
  - Installing sebastian/recursion-context (2.0.0): Downloading (100%)
  - Installing sebastian/object-enumerator (2.0.1): Downloading (100%)
  - Installing sebastian/global-state (1.1.1): Downloading (100%)
  - Installing sebastian/exporter (2.0.0): Downloading (100%)
  - Installing sebastian/environment (2.0.0): Downloading (100%)
  - Installing sebastian/comparator (1.2.4): Downloading (100%)
  - Installing symfony/yaml (v3.3.18): Downloading (100%)
  - Installing phpspec/prophecy (1.8.1): Downloading (100%)
  - Installing phpunit/php-text-template (1.2.1): Downloading (100%)
  - Installing phpunit/phpunit-mock-objects (3.4.4): Downloading (100%)
  - Installing phpunit/php-timer (1.0.9): Downloading (100%)
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (100%)
  - Installing phpunit/php-token-stream (1.4.12): Downloading (100%)
  - Installing phpunit/php-file-iterator (1.4.5): Downloading (100%)
  - Installing phpunit/php-code-coverage (4.0.8): Downloading (100%)
  - Installing phpunit/phpunit (5.7.27): Downloading (100%)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
zendframework/zend-filter suggests installing psr/http-factory-implementation (psr/http-factory-implementation, for creating file upload instances when consuming PSR-7 in file upload filters)
zendframework/zend-filter suggests installing zendframework/zend-crypt (Zend\Crypt component, for encryption filters)
zendframework/zend-filter suggests installing zendframework/zend-uri (Zend\Uri component, for the UriNormalize filter)
zendframework/zend-servicemanager suggests installing ocramius/proxy-manager (ProxyManager 0.5.* to handle lazy initialization of services)
zendframework/zend-servicemanager suggests installing zendframework/zend-di (Zend\Di component)
zendframework/zend-cache suggests installing zendframework/zend-session (Zend\Session component)
zendframework/zend-cache suggests installing ext-apc (APC or compatible extension, to use the APC storage adapter)
zendframework/zend-cache suggests installing ext-apcu (APCU >= 5.1.0, to use the APCu storage adapter)
zendframework/zend-cache suggests installing ext-memcache (Memcache >= 2.0.0 to use the Memcache storage adapter)
zendframework/zend-cache suggests installing ext-memcached (Memcached >= 1.0.0 to use the Memcached storage adapter)
zendframework/zend-cache suggests installing ext-mongo (Mongo, to use MongoDb storage adapter)
zendframework/zend-cache suggests installing ext-wincache (WinCache, to use the WinCache storage adapter)
zendframework/zend-cache suggests installing ext-xcache (XCache, to use the XCache storage adapter)
zendframework/zend-cache suggests installing mongofill/mongofill (Alternative to ext-mongo - a pure PHP implementation designed as a drop in replacement)
zendframework/zend-json suggests installing zendframework/zend-http (Zend\Http component, required to use Zend\Json\Server)
zendframework/zend-json suggests installing zendframework/zend-server (Zend\Server component, required to use Zend\Json\Server)
zendframework/zend-json suggests installing zendframework/zendxml (To support Zend\Json\Json::fromXml() usage)
zendframework/zend-serializer suggests installing zendframework/zend-math ((^2.6) To support Python Pickle serialization)
zendframework/zend-i18n suggests installing zendframework/zend-validator (You should install this package to use the provided validators)
zendframework/zend-i18n suggests installing zendframework/zend-view (You should install this package to use the provided view helpers)
zendframework/zend-i18n suggests installing zendframework/zend-i18n-resources (Translation resources)
jms/serializer suggests installing doctrine/collections (Required if you like to use doctrine collection types as ArrayCollection.)
jms/serializer suggests installing doctrine/cache (Required if you like to use cache functionality.)
symfony/event-dispatcher suggests installing symfony/dependency-injection
symfony/event-dispatcher suggests installing symfony/http-kernel
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
symfony/validator suggests installing doctrine/cache (For using the default cached annotation reader and metadata cache.)
symfony/validator suggests installing symfony/http-foundation
symfony/validator suggests installing symfony/intl
symfony/validator suggests installing egulias/email-validator (Strict (RFC compliant) email validation)
symfony/validator suggests installing symfony/property-access (For using the 2.4 Validator API)
symfony/validator suggests installing symfony/expression-language (For using the 2.4 Expression validator)
phpdocumentor/phpdocumentor suggests installing ext-twig (Enabling the twig extension improves the generation of twig based templates.)
phpdocumentor/phpdocumentor suggests installing ext-xslcache (Enabling the XSLCache extension improves the generation of xml based templates.)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
friendsofphp/php-cs-fixer suggests installing php-cs-fixer/phpunit-constraint-isidenticalstring (For IsIdenticalString constraint.)
friendsofphp/php-cs-fixer suggests installing php-cs-fixer/phpunit-constraint-xmlmatchesxsd (For XmlMatchesXsd constraint.)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Package kherge/version is abandoned, you should avoid using it. No replacement was suggested.
Package herrera-io/json is abandoned, you should avoid using it. Use kherge/json instead.
Package herrera-io/phar-update is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
➜  PHPMailer git:(master) php -v
PHP 5.6.40 (cli) (built: Apr 23 2019 11:14:34)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by janek109** [comment]
The same with php-cs-fixer:

PHPMailer git:(master) php vendor/bin/php-cs-fixer --diff --dry-run --verbose fix
Loaded config default from "/Users/jszewczak/php-projects/PHPMailer/.php_cs".
..........
Legend: ?-unknown, I-invalid file syntax, file ignored, S-Skipped, .-no changes, F-fixed, E-error

Checked all files in 20.249 seconds, 30.000 MB memory used

**Comment by Synchro** [comment]
Indeed - it runs locally for me too. I think it may be a Travis-CI environment issue, and that's usually very tedious to debug!

**Comment by Synchro** [comment]
Yay! Fixed!
