### ISSUE TITLE
How to create local mail server for sending the emails if we are using the external mail server of gmail (Gsuite)

### ISSUE THREAD

**Issue by ravindch2005** [PHPMailer/PHPMailer#1804]
We are using G-Suite services for our domains email service. I want to send bulk emails using the phpmailer. At present I am using the same approach as given in https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps  . To Maximising performance I want to create a **local send only mail** server (using postfix in Ubuntu machine) as stated in https://github.com/PHPMailer/PHPMailer/wiki/Sending-to-lists. 
Can anybody please explain how would I use the phpmailer with postfix and gmail account's credentials. 
If any article/example is available it will be better for me to configure.
Thanks in anticipation

**Comment by Synchro** [comment]
What you’re looking for is called “relaying”, so search for that. Postfix definitely does it, but you’ll need to read their docs on it.

**Comment by ravindch2005** [comment]
> What you’re looking for is called “relaying”, so search for that. Postfix definitely does it, but you’ll need to read their docs on it.

Thanks for your reply. I have configured postfix. It is working fine. How can I use phpMailer with it. 
Is any such example available? Please reply.

**Comment by Synchro** [comment]
Just call `isSMTP()` and the other default settings should be fine. You don’t have to do anything special from PHPMailer.

**Comment by ravindch2005** [comment]
Please suggest me if I should write like this or what should I write in
following parameters after I have configured postfix
    $mail->isSMTP();                                      // Set mailer to
use SMTP
    $mail->Host = 'localhost';  // Specify main and backup SMTP servers
   // $mail->SMTPAuth = true;                               // Enable SMTP
authentication
    $mail->Username = 'info1@xxxx.com';                 // SMTP username
    $mail->Password = 'xxxxxxx!';                           // SMTP password
  //  $mail->SMTPSecure = 'tls';                            // Enable TLS
encryption, `ssl` also accepted
    $mail->Port = 25;
 $mail->setFrom('info1@xxxx.com', 'Mailer');

Above code is not working
Thank You

**Comment by Synchro** [comment]
Like I said, you don’t have to set any of those things. Host is localhost, port is 25, no auth, no encryption, all by default. If that doesn’t work, you have not set up postfix correctly- and for that the default config will usually work. Test your postfix *before* trying to use PHPMailer with it.
