### ISSUE TITLE
isPermittedPath prevents addEmbeddedImage to add S3 files

### ISSUE THREAD

**Issue by chadetov** [PHPMailer/PHPMailer#1809]
In an auto-scaling group, EC2 instances use S3 to put and get back file objects. In PHPMailer there is a check "isPermittedPath" when using "addEmbeddedImage". This checks prevents remote image files to be embedded into emails. I think developers must take into account that we need the ability to embed S3 objects into emails.

**Comment by Synchro** [comment]
No, this is deliberate. PHP is not an HTTP client. Use some other mechanism to fetch the files, then load them into PHPMailer. You can of course subclass and override the method to do what you want directly.
