### ISSUE TITLE
Why does it works if I disable use()

### ISSUE THREAD

**Issue by waqaspuri** [PHPMailer/PHPMailer#1810]
Am able to send mail through phpmailer as it is installed in many websites of my customer, am not good in PHP but can figure out troubles with some research, therefore, as the following code returns error : 
```

**use PHPMailer\PHPMailer\PHPMailer;**
require '../vendor/autoload.php';
$mail = new PHPMailer;


```
What it works greatly if I comment the following line : 

`use PHPMailer\PHPMailer\PHPMailer;`

It is glad to know why does it happens i can understand there would be some things missing my end but would like to know the issue what exactly that is happending -WITH AND WITHOUT difference.

**Comment by Synchro** [comment]
The `use` statement is used for [namespacing](https://www.php.net/namespaces). The fact that it’s not working for you means you are using a very old version of PHP, and you need to upgrade.

**Comment by waqaspuri** [comment]
Which version is recommended?

**Comment by Synchro** [comment]
Always use the latest if you can - currently 7.3 - but PHPMailer 6.0 will work back to PHP 5.5, though that’s no longer supported and you should not be using a version that old.
