### ISSUE TITLE
Insert a signature block in an HTML email

### ISSUE THREAD

**Issue by lorenzo80** [PHPMailer/PHPMailer#1812]
Is it possible to insert a canonical signature block in an HTML email?
Dash dash space \n like always: https://en.wikipedia.org/wiki/Signature_block

It looks like that HTML emails always have the line preceded by a tag so the output is similar to this one (from Google):
`<br>-- =20`

So while it appears like a regular prefix, no client actually recognizes it and acts accordingly - I mean cutting it when replying.
Is there something that I've to specify? Everything else works fine and it's basically as for the exaples:
```
	$mail->CharSet = "UTF-8"; # Tried changing it, no effect
	$mail->Encoding = "16bit"; # Tried changing it, no effect 
	$mail->isSMTP();
	$mail->isHTML(TRUE);
```

**Comment by Synchro** [comment]
I don’t know if any way of denoting a signature in an HTML message - I don’t know that there is any normative standard that defines it either, and I don’t think I’ve ever seen an email client do it, so I think you’re out of luck. PHPMailer doesn’t care what’s in the message body.
