### ISSUE TITLE
Email is sent twice

### ISSUE THREAD

**Issue by 3dsoft** [PHPMailer/PHPMailer#1813]
```
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require_once('./PHPMailer/src/Exception.php');
require_once('./PHPMailer/src/PHPMailer.php');
require_once('./PHPMailer/src/SMTP.php');

$mail = new PHPMailer();

try 
{
    $mail->isSMTP();
    $mail->Host="smtp.naver.com";
    $mail->SMTPAuth = true;
    $mail->Port = 587;
    $mail->SMTPSecure = 'tls';
    $mail->Username = "test@naver.com";
    $mail->Password = "password";
    $mail->CharSet = "UTF-8";
    $mail->IsHtml = true;
    $mail->SetFrom("test@naver.com");
    $mail->AddAddress("target@domain.com");
    $mail->Subject = "Test Mail";            

    // $mail->Body = $_POST['message'];     // The email only be sent once.
    // $mail->Body = "Test Email";          // Problem : The email only be twice !!!

    $mail->AltBody = "this is altbody.";
    $mail->Send();
} 
catch(phpmailerException $e)
{
    echo $e->errorMessage();
} 
catch(exception $e)
{
    echo $e->getMessage();
}
?>
```

Entering a string in $mail->body will send the same email twice.

$mail->Body = "Test Email";

Entering a $_POST['message'] variable in $mail->body, it be send only once.

$mail->Body = $_POST['message']; 

Please tell me what is wrong.

**Comment by Synchro** [comment]
The script is only sending once, so It's most likely that your script is being run twice, i.e. it's the context your script is running in, not the script itself. You can confirm this by appending a random number to the subject line like this:

    $mail->Subject = 'Test Mail ' . rand();

I you see two different numbers, the script is being run twice. If you see the same number, the script is being run once and sending two messages. Repeat posts are often caused by browser plugins.

One likely cause: you're always sending even if `$_POST['message']` is not set, so check it before you send by wrapping your whole script in an if:

    if (isset($_POST['message'])) {...

**Comment by 3dsoft** [comment]
Thank you very much !!!!

By using rand (), I saw that the title has a different number. 

```
$mail->Subject = 'Test Mail ' . rand();
```


So I solved it as below.

```
<?php
if(!isset($_POST['message'])) exit;  // or redirect('...');
```

**Comment by BhoiDanny** [comment]
`<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require_once('./PHPMailer/src/Exception.php');
require_once('./PHPMailer/src/PHPMailer.php');
require_once('./PHPMailer/src/SMTP.php');

$mail = new PHPMailer();

try 
{
    $mail->isSMTP();
    $mail->Host="smtp.naver.com";
    $mail->SMTPAuth = true;
    $mail->Port = 587;
    $mail->SMTPSecure = 'tls';
    $mail->Username = "test@naver.com";
    $mail->Password = "password";
    $mail->CharSet = "UTF-8";
    $mail->IsHtml = true;
    $mail->SetFrom("test@naver.com");
    $mail->AddAddress("target@domain.com");
    $mail->Subject = "Test Mail";            

    // $mail->Body = $_POST['message'];     // The email only be sent once.
    // $mail->Body = "Test Email";          // Problem : The email only be twice !!!

    $mail->AltBody = "this is altbody.";
    if($mail->Send()){
       echo "Message sent successfully!";
    } else {
      echo "Message failed to send!";
    }
} 
catch(phpmailerException $e)
{
    echo $e->errorMessage();
} 
catch(exception $e)
{
    echo $e->getMessage();
}
?>`
You don't really need to send the email before you check if its true, you can just pass the $mail->send() in the if() statement

**Comment by Synchro** [comment]
The exception handlers in that script will never be used because you are not enabling exceptions. Pass `true` to the constructor to enable them.
