### ISSUE TITLE
Smtp Won't work Office365

### ISSUE THREAD

**Issue by pepijndik** [PHPMailer/PHPMailer#1814]
This is my code.
I have in the same directory 
the PHPMailer and the Smtp.php And Exception.php
Everything has the right permissions so they can be used.
but when I try Send a Email Nothing happends ????

Can some one tell me what I am doing wrong??
Used the Gmail example tried different version for the PHPMailer
Right Now I am using version 6.

```php
<?php
/**
 * This example shows settings to use when sending via Google's Gmail servers.
 * This uses traditional id & password authentication - look at the gmail_xoauth.phps
 * example to see how to use XOAUTH2.
 * The IMAP section shows how to save this message to the 'Sent Mail' folder using IMAP commands.
 */
//Import PHPMailer classes into the global namespace
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\SMTP;
require 'PHPMailer.php';
require 'SMTP.php';

//Create a new PHPMailer instance
$mail = new PHPMailer(true);
//Tell PHPMailer to use SMTP
$mail->isSMTP();
//Enable SMTP debugging
// 0 = off (for production use)
// 1 = client messages
// 2 = client and server messages
$mail->SMTPDebug = 2;
//Set the hostname of the mail server
//$mail->Host = 'smtp.office365.com';
// use
 $mail->Host = gethostbyname('smtp.office365.com');
// if your network does not support SMTP over IPv6
//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
$mail->Port = 587;
//Set the encryption system to use - ssl (deprecated) or tls
$mail->SMTPSecure = 'tls';
//Whether to use SMTP authentication
$mail->SMTPAuth = true;
//Username to use for SMTP authentication - use full email address for gmail
$mail->Username = "sales@test";
//Password to use for SMTP authentication
$mail->Password = "test";
//Set who the message is to be sent from
$mail->setFrom('from@example.com', 'First Last');
//Set an alternative reply-to address
$mail->addReplyTo('pepijn@pdik.nl', 'First Last');
//Set who the message is to be sent to
$mail->addAddress('info@pdik.nl', 'pdik');
//Set the subject line
$mail->Subject = 'PHPMailer GMail SMTP test';
//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body
//$mail->msgHTML(file_get_contents('contents.html'), __DIR__);
//Replace the plain text body with one created manually
$mail->AltBody = 'This is a plain-text message body';
//Attach an image file
//$mail->addAttachment('images/phpmailer_mini.png');
//send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
  
}
```

**Comment by ooxi** [comment]
Please use [Markdown](https://guides.github.com/features/mastering-markdown/) formatting, your code looks like an unreadable wall of text.

---

Please enable debugging and provide a log excerpt. Be sure to mask credentials.

**Comment by pepijndik** [comment]
> Please use [Markdown](https://guides.github.com/features/mastering-markdown/) formatting, your code looks like an unreadable wall of text.
> 
> Please enable debugging and provide a log excerpt. Be sure to mask credentials.

Done :D sorry used the wrong  way to markdown code

**Comment by Synchro** [comment]
What happened when you tried the tests in the troubleshooting guide? Can you post debug output with `SMTPDebug = 3`? The fact that you've used `gethostbyname` suggests that your hosting provider may not be very good.

**Comment by pepijndik** [comment]
> What happened when you tried the tests in the troubleshooting guide? Can you post debug output with `SMTPDebug = 3`? The fact that you've used `gethostbyname` suggests that your hosting provider may not be very good.

the weird thing is that I see Nothing when I try to Debug...
I tried the Test in the Troubleshooting guide but that din't work for me.
and I used gethostbyname because I thought maybe that would work.
My Mail hosting is on. Office365 (business)

**Comment by pepijndik** [comment]
Got it Working,
Thanks for the reply
