### ISSUE TITLE
PHPMailer under wxPHP 5.6 for win64 gets false timeout (60 secs). Does work on wxPHP 5.4 for win32

### ISSUE THREAD

**Issue by Luxnews** [PHPMailer/PHPMailer#1817]
Hi all, the title says it all: 
  PHPMailer under wxPHP 5.6 for win64 gets false timeout (60 secs). Does work, instead, on wxPHP 5.4 for win32 (under Windows 10 - v.1803).
I was trying since 10 days to make PHPMailer 6.0.7 to work and it always gave me a nonsense timeout (**immediately** a timeout of a supposed 60 secs limit) at the instruction:
--- cut here---
```
            if (!stream_select($selR, $selW, $selW, $this->Timelimit)) {
                $this->edebug(
                    'SMTP -> get_lines(): timed-out (' . $this->Timeout . ' sec)',
                    self::DEBUG_LOWLEVEL
                );
                break;
            }
```
--- cut here---
of the line 1125 of SMTP.php module.

The same identical code works **perfectly** under the win32 version (although only PHP 5.4). So there is something wrong under PHP 5.6 win64, that prevents `stream_select($selR, $selW, $selW, $this->Timelimit))` to work properly.

I know it's ***not*** a PHPMailer problem, but I thought it might be useful for others that, like me, were getting mad about PHPMailer **apparently not working...** because (probably) of some wrong php windows compile/linkage/implementation trouble that prevents some instructions/timeout to work as intended.

# Debug output (of the win64 wxPHP not working implementation)

--- cut here---
2019-08-24 15:40:28     Connection: opening to smtp.gmail.com:587, timeout=60, options=array (
                                            'ssl' =>
                                            array (
                                              'verify_peer' => true,
                                              'verify_peer_name' => true,
                                              'allow_self_signed' => true,
                                            ),
                                          )
2019-08-24 15:40:28     Connection: opened
PHP Warning:  stream_select(): unable to select [0]: No error (max_fd=1324) in C:\DATA\PortableApps\SQL-DataBase\DATA-DB\PHPMailer\PHPMailer\SMTP.php on line 1125

Warning: stream_select(): unable to select [0]: No error (max_fd=1324) in C:\DATA\PortableApps\SQL-DataBase\DATA-DB\PHPMailer\PHPMailer\SMTP.php on line 1125
2019-08-24 15:40:28     SMTP -> get_lines(): timed-out (60 sec)
2019-08-24 15:40:28     SERVER -> CLIENT:
2019-08-24 15:40:28     CLIENT -> SERVER: EHLO DESKTOP-I3Q43KA
PHP Warning:  stream_select(): unable to select [0]: No error (max_fd=1324) in C:\DATA\PortableApps\SQL-DataBase\DATA-DB\PHPMailer\PHPMailer\SMTP.php on line 1125

Warning: stream_select(): unable to select [0]: No error (max_fd=1324) in C:\DATA\PortableApps\SQL-DataBase\DATA-DB\PHPMailer\PHPMailer\SMTP.php on line 1125
2019-08-24 15:40:28     SMTP -> get_lines(): timed-out (60 sec)
2019-08-24 15:40:28     SERVER -> CLIENT:
2019-08-24 15:40:28     SMTP ERROR: EHLO command failed:
2019-08-24 15:40:28     CLIENT -> SERVER: HELO DESKTOP-I3Q43KA
PHP Warning:  stream_select(): unable to select [0]: No error (max_fd=1324) in C:\DATA\PortableApps\SQL-DataBase\DATA-DB\PHPMailer\PHPMailer\SMTP.php on line 1125

Thanks for great PHPMailer code!
Luca

**Comment by Synchro** [comment]
Is there any particular reason you're using such an old version of PHP? What happens if you use 7.3?

**Comment by Synchro** [comment]
Ah, I see - wxPHP appears to be a defunct project and has not been updated for 3 years...

**Comment by Luxnews** [comment]
Yes Synchro, you got it... and that's very sad as in a probable future I could be compel to redevelop my actual client (only) application (for a doctor) into Phyton, which I'm not very fond of :-(
There is a porting of wxPHP for php7 but who knows if it will ever see the light?
Thanks anyway!
Luca
P.S. PHP 5.4 is still a great language, just a bit old and "clunky" ;-)
