### ISSUE TITLE
array_key_exists() with objects

### ISSUE THREAD

**Issue by labby** [PHPMailer/PHPMailer#1818]
Only a small hint:
don't know if you got that
**array_key_exists() with objects**
is deprecated in PHP 7.4.

Thanks for all the good work.

**Comment by Synchro** [comment]
Where are you seeing this? Can you provide references?

**Comment by labby** [comment]
yepp :-)
https://wiki.php.net/rfc/deprecations_php_7_4

**Comment by Synchro** [comment]
No, I mean in PHPMailer code!

**Comment by labby** [comment]
oh no, I didn't check if you use it with objects, I just noticed that you use array_key_exists() as I checked our own cms code (where we also use phpmailer as a lib).
