### ISSUE TITLE
Messages go to spam folder when a link is included in the body

### ISSUE THREAD

**Issue by AstonGemmy** [PHPMailer/PHPMailer#1820]
Hello author, I am using PHPMailer to send emails on my site and it's working perfectly but emails go to spam folder when hyperlinks are included in the mail body. 

I could really use a help from you on this. Thanks.

**Comment by NiklasBr** [comment]
What does https://www.mail-tester.com/ say if you send a test email with a hyperlink?

**Comment by Synchro** [comment]
You can ensure you're using strong settings for SPF, DKIM, and DMARC, establish a sending reputation (can take years), have matching reverse DNS, don't switch IPs or domains, never send spam, always use double-opt-in, never link to malware sites (nearly all of which is outside PHPMailer's scope), and spam filters can still put your messages in the spam folder. Most spam filters are entirely arbitrary, have no recourse, no notification mechanism, and no standards (See gmail for an example).

If you're lucky, a received message might contain headers that say why a message failed the spam filter, but even then it's likely there's nothing you can do unless it's something you should have been doing anyway, like SPF.

Please excuse the pessimism; I'm just speaking from experience!

**Comment by AstonGemmy** [comment]
Okay. I'll consider this and try a fix.

Thank you.

**Comment by Synchro** [comment]
I wrote [a guide on spam filtering issues](https://github.com/PHPMailer/PHPMailer/wiki/Improving-delivery-rates,-avoiding-spam-filters) in the wiki.

**Comment by Autolinkcraft** [comment]
About this, i saw a video on youtube where a guy added some tags in-between the href and url and it started working just fine (INBOX). does anyone know how to do this. I cant find the youtube video.
