### ISSUE TITLE
Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in C:\wamp64\www\...    PHPMailerAutoload.php on line 45

### ISSUE THREAD

**Issue by Utkarsh-nit** [PHPMailer/PHPMailer#1829]
i am using 5.2 stable version of phpmailer so the email sending process is working fine but the error is coming which i mentioned in title.

**Comment by Synchro** [comment]
This means you're using a new enough version of PHP that deprecates this function - but that also means that you are running a recent enough version to run PHPMailer 6, so the solution to this issue is to update; 5.2 is only for those stuck on old PHP versions.
