### ISSUE TITLE
To name and email is missing in gmail

### ISSUE THREAD

**Issue by udayankoliya** [PHPMailer/PHPMailer#1830]
When i send the email via SMTP  in the Receiver mailbox  the to name  show blank 
here you can see the screenshot

![](https://i.imgur.com/K80J3kn.png)

also when i goes in sender mailbox send tab all email goes to via Bcc Not as Regular Email 
even i don't used any bcc email can you help to solve out this problem

![](https://i.imgur.com/5FFYeJ1.png)
 Here You can find  my code 
   `use PHPMailer\PHPMailer\PHPMailer;
   use PHPMailer\PHPMailer\Exception;
   require 'PHPMailer/Exception.php';
  require 'PHPMailer/PHPMailer.php';
   require 'PHPMailer/SMTP.php';
 
    $mail = new PHPMailer;

    $mail->isSMTP();

    $mail->SMTPSecure = 'ssl';

    //$mail->SMTPDebug = 2;

    //or ty this setting (worked on XAMPP and WAMP):
    $mail->Host = 'smtp.gmail.com';

	$mail->Port = 465;
   
    $mail->SMTPAuth = true;

	$mail->Username = 'udayakoliya@gmail.com';

	$mail->Password = 'xxvxdthfghjhgjg';

    $mail->SingleTo = true;
    //if you want to send a same email to multiple users.multiple emails will be sent one-by-one

    $mail->setFrom('udayakoliya@gmail.com', 'Uday Akoliya');

    $bulkEmails = array('patelchintan787@gmail.com');
    //$mail->addAddress($email);

    $subject="Email Template Test";
    
    $mail->Subject = $subject;

    
   

    foreach ($bulkEmails as  $value) {
        $mail->addAddress($value, 'Patel Chintan');
    }
    
    $mail->clearBCCs();
    $mail->clearReplyTos();
    //$mail->ClearAllRecipients();

    $mail->msgHTML(file_get_contents('template.html'), __DIR__);

    $mail->AltBody = 'This is a plain-text message body';

    if($mail->send()){
        echo "success";
    }
    else{
        echo "error</br>";
        echo "Mailer Error: " . $mail->ErrorInfo;
    }`

**Comment by Synchro** [comment]
Please show your code and debug output with `SMTPDebug = 2`.

**Comment by udayankoliya** [comment]
> Please show your code and debug output with `SMTPDebug = 2`.

**Comment by udayankoliya** [comment]
> Please show your code and debug output with `SMTPDebug = 2`.

**Comment by caugner** [comment]
Note that `PHPMailer::$SingleTo` is deprecated since Version 6:

https://github.com/PHPMailer/PHPMailer/blob/b8e6a92d418db01dfef4ef637c5aa9e9b14261f8/changelog.md#L118
