### ISSUE TITLE
Pleae clarify about "vendor/autoload.php" existence

### ISSUE THREAD

**Issue by brandlumin** [PHPMailer/PHPMailer#1834]
Dear Sir, I've been struggling with this for a year or so for a simple reason -- Where is "vendor/autoload.php"?

Please help!?!

**Comment by NiklasBr** [comment]
See: https://github.com/PHPMailer/PHPMailer#installation--loading

**Comment by brandlumin** [comment]
Got it.. Thanks gentleman.. Somehow I had missed that reading ..I owe you big for your clarification. Thanks again.
