### ISSUE TITLE
Can't disable X-Mailer header

### ISSUE THREAD

**Issue by bhall7** [PHPMailer/PHPMailer#184]
I can't disable the X-Mailer header nor clear it. When I instantiate a new PHPMailer object , I even tried setting the XMailer header to `''`, but PHPMailer still includes this header in all emails sent.

```
$mail = new PHPMailer(true);
$mail->XMailer    = ''; 
```

Is there an easy way to disable this header field?

See also https://code.google.com/a/apache-extras.org/p/phpmailer/issues/detail?id=66

**Comment by gaecom** [comment]
if ($this->XMailer == '') {
            $result .= $this->headerLine(
                'X-Mailer',
                'PHPMailer ' . $this->Version . ' (https://github.com/PHPMailer/PHPMailer)'
  );
you cant leave  $mail->XMailer empty,you should assign value.such as $this->XMailer='Microsoft Mailer';

**Comment by Synchro** [comment]
@gaecom what? XMailer is never left empty, though it may be removed altogether, as all `X`-prefixed headers can.

**Comment by rajeevacj** [comment]
Use `$mail->xmailer = '0'`

**Comment by Zafpyr** [comment]
$mail->XMailer = '(;-_-) Nothing to see here';
