### ISSUE TITLE
How get "to" email from PHPMailer instance

### ISSUE THREAD

**Issue by Kamoba** [PHPMailer/PHPMailer#1851]
Using a smtp (WP Mail SMTP) who use PHPMailer  in WordPress i try to retreive the destination email before the email is sent.

<code>function verification_befor_send_email( $phpmailer ) {	</code>
<code>	//print_r( $phpmailer->{'to'} );</code>
<code>	//print_r( $phpmailer->getValue('to') );</code>
<code>	print_r( $phpmailer );</code>
<code>	die();</code>
<code>}</code>
<code>add_action( 'phpmailer_init', 'verification_befor_send_email' );</code>

////////// Result ////////////
.....
["to":protected]=> array(1) { [0]=> array(2) { [0]=> string(28) "virtualuser@mydomain.ca" [1]=> string(0) "" } } 
.....
/////////////////////////////

i can't access to the value of ["to":protected] because it's protected, so i'm wondering if do we have a getter function for this purpose?
I'm trying to filter some e-mails.

**Comment by Synchro** [comment]
You should do your filtering *before* you add them as to addresses (also note that `addAddress()` will return false if the address is not valid, so you don't need to do your own validation, just check the return value).

You can get the list of to addresses by calling [`$mail->getToAddresses();`](http://phpmailer.github.io/PHPMailer/classes/PHPMailer.PHPMailer.PHPMailer.html#method_getToAddresses).

**Comment by Kamoba** [comment]
it's automatic email so I can't do filtering, that's why I wanted to check before sending it. 
I'll try this $mail->getToAddresses(); it should make me happy.
Thank you.
