### ISSUE TITLE
No valid error code on timeout

### ISSUE THREAD

**Issue by clarkk** [PHPMailer/PHPMailer#1852]
If you run phpmailer in a infinite loop with a keep alive connection you don't get a valid error code back if the connection time out

It would be great if it was also possible somehow to keep the connection alive so the connection can idle for some time

**Comment by clarkk** [comment]
Or maybe a feature to re-establish the connection if it was lost

**Comment by Synchro** [comment]
You can issue the SMTP `NOOP` (no operation) command to keep a keepalive connection open, and that's [supported in PHPMailer](https://github.com/PHPMailer/PHPMailer/blob/master/src/SMTP.php#L1008).

Generally speaking though, tying up connections to the mail server isn't really something you should be doing normally; The main purpose of keepalive is to increase throughput when sending multiple messages, not to reduce latency for the second message (it makes no difference to the first). If you want tor educe latency, the best approach is to run a local mail server (which doesn't require encryption or authentication) - that will have a much bigger effect than using keepalive on a remote, authenticated server.

**Comment by Synchro** [comment]
I'd also like to see how the timeouts are failing for you - they are tested in the test suite and don't seem to have any problems there.

**Comment by clarkk** [comment]
If you start phpmailer with keep-alive and send a mail and wait until the SMTP timeout is exceeded until you send a mail again you get no errorcode except `MAIL FROM command failed` or something

**Comment by clarkk** [comment]
I nice feature was to re-establish the connection if it timeout...

**Comment by Synchro** [comment]
Again, I'm not seeing a use case here. What's the context? What do you hope to gain by doing this? It can't be during a web page submission because PHP is torn down after every request, and web timeouts are much shorter than SMTP ones.

**Comment by clarkk** [comment]
It's for a mail queue system

You would never setup your own local SMTP server because it takes too much maintenance.. You want to reach most inboxes so you use a larger povider

**Comment by Synchro** [comment]
Pretty much all external email providers impose a limit on the number of messages you can send during a single SMTP session (500 or 1k is a common limit), so long-term sessions are pointless. The right approach is to open a connection when you need it, send the batch of messages, then close it. Tying up resources unnecessarily is wasteful. In fact I'd recommend that you use a local mail server as a relay even if you are using an external email provider, as it provides greater local throughput and is more resilient against network and 3P service outages - nobody wants to implement a mail queue in PHP when mail servers do it so much better.

I say this as someone who runs a large-scale email marketing system sending abut 650,000 messages/hour using PHPMailer.
