### ISSUE TITLE
Stuck SMTP connect() failed

### ISSUE THREAD

**Issue by joewilson27** [PHPMailer/PHPMailer#1856]
Hei there...
I am stuckd with this code...
I am using simple phpmailer library in Ubuntu 16.04.6 LTS.

This is my simple code:

```
require_once("php_mailer/class.phpmailer.php"); // load library phpmailer

$sendmail = new PHPMailer();
$sendmail->IsSMTP(); // enable SMTP
$sendmail->SMTPAuth = true; 
$sendmail->SMTPSecure = 'ssl'; 
$sendmail->Host = "10.66.3.18"; // host from another server, using zimbra
$sendmail->Port = 465; // or 587
$sendmail->Username = "noreply@xxx";
$sendmail->Password = "xxx";

$usermail = "example@email.com";

$sendmail->setFrom("noreply@xxx","noreply@xxx"); 
$sendmail->addReplyTo("noreply@xxx","noreply@xxx");
$sendmail->addAddress($usermail,$usermail); 

$message = "This is body message";

$sendmail->Subject = "This is Title Subject"; 
$sendmail->Body=$message; 
$sendmail->isHTML(true);

if(!$sendmail->Send()) {
	echo $sendmail->ErrorInfo;;				  
}else{ 
  	echo "Successful";
}
```

when I executed this simple code... 
the smpt connect failed...

Is there something wrong in my setting phpmailer?

**Comment by FirdousBhat** [comment]
Can u try like this,
$sendmail->SMTPAuth = false;
$sendmail->SMTPSecure = null;

**Comment by joewilson27** [comment]
> Can u try like this,
> $sendmail->SMTPAuth = false;
> $sendmail->SMTPSecure = null;

hi FirdousBhat..
I changed the settings with your suggestion and I added $sendmail->SMTPDebug = 1; 
then now error appeared is :

2019-10-03 10:02:10     CLIENT -> SERVER: EHLO BG-EVouche-DEV
2019-10-03 10:02:10     SMTP ERROR: EHLO command failed:
2019-10-03 10:02:10     SMTP NOTICE: EOF caught while checking if connected
The following From address failed: noreply@xxx: Called MAIL FROM without being connected

**Comment by Synchro** [comment]
Firstly, you're using an obsolete, unsupported version, so upgrade.

You can't use TLS/SSL without using a host *name*, as a certificate will never match a literal IP address. `SMTPDebug = 1` won't tell you anything useful; set it to 2 or 3. All this is mentioned in [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting).

**Comment by joewilson27** [comment]
@Synchro 

is newest phpmailer support PHP 5.6.40 ?
