### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by vandaanggi** [PHPMailer/PHPMailer#1861]
this my message error :

Fatal error: Uncaught Error: Class 'PHPMailer\PHPMailer\Exception' not found in D:\newxampp\htdocs\wow\PHPMailer\PHPMailer.php:1793 Stack trace: #0 D:\newxampp\htdocs\wow\PHPMailer\PHPMailer.php(1591): PHPMailer\PHPMailer\PHPMailer->mailSend('Date: Wed, 9 Oc...', '+6285785905504\r...') #1 D:\newxampp\htdocs\wow\PHPMailer\PHPMailer.php(1423): PHPMailer\PHPMailer\PHPMailer->postSend() #2 D:\newxampp\htdocs\wow\page-contact.php(21): PHPMailer\PHPMailer\PHPMailer->send() #3 {main} thrown in D:\newxampp\htdocs\wow\PHPMailer\PHPMailer.php on line 1793

endthis my code 

<?php 
    $msg = "";
    use PHPMailer\PHPMailer\PHPMailer;
    include_once "PHPMailer/PHPMailer.php";

**Comment by Synchro** [comment]
This is [covered in the readme](https://github.com/PHPMailer/PHPMailer/blob/master/README.md#installation--loading).
