### ISSUE TITLE
Could not instantiate mail function.

### ISSUE THREAD

**Issue by vandaanggi** [PHPMailer/PHPMailer#1862]
```php
<?php 
    $msg = "";
    use PHPMailer\PHPMailer\PHPMailer;

    include_once "PHPMailer/PHPMailer.php";
    include_once "PHPMailer/Exception.php";
    include_once "PHPMailer/SMTP.php";


    if (isset($_POST['submit'])) {
        $name = $_POST['name'];
        $phone = $_POST['phone'];
        $email = $_POST['email'];
        $message = $_POST['message'];

        
        $mail = new PHPMailer();
        
        //smtp
        $mail->Host = "smtp.gmail.com";
        //$mail->isSMTP();
        $mail->SMTPAuth = true;
        $mail->Username = "leadsgxxxx@gmail.com";
        $mail->Password = "T3kn0xxxx";
        $mail->SMTPSecure = "ssl";
        $mail->Port = 465;

        $mail->addAddress('info@txxxxx.com');
        $mail->setFrom($email);
        $mail->Subject = $name;
        $mail->isHTML(TRUE);
        $mail->Body = $phone; $message;

        if($mail->send())
            $msg = "your email has been sent, thankyou";
        else
            //$msg = "please try again";
            echo $mail->ErrorInfo;

    }

?>
```

**Comment by Synchro** [comment]
You're setting up SMTP, but then eciding not to use it. If you want to use SMTP, uncomment the call to `isSMTP`.

The error itself means that you don't have a local mail server configured, as [the troubleshooting guide tells you](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#could-not-instantiate-mail-function).

If those are your real credentials in the script, you need to change your password now.

**Comment by vandaanggi** [comment]
> You're setting up SMTP, but then deciding not to use it, so it's falling back to the default `mail()` transport. If you want to use SMTP, uncomment the call to `isSMTP`.
> 
> The error itself means that you don't have a local mail server configured, as [the troubleshooting guide tells you](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#could-not-instantiate-mail-function).
> 
> If those are your real credentials in the script, you need to change your password now.

if  "$mail->isSMTP();" not comment will be error like "SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting"

why when I added this script "$mail->SMTPDebug = SMTP::DEBUG_SERVER;" 
 error like "2019-10-09 06:34:00 SMTP ERROR: Failed to connect to server: No connection could be made because the target machine actively refused it. (10061)" ????

**Comment by NiklasBr** [comment]
It says it right there: *because the target machine actively refused it* in other words the SMTP server does not want your connection.

**Comment by Synchro** [comment]
Read more of the guide - it tells you how to diagnose problem like these. It's likely that your ISP blocks outbound SMTP, for example if your'e using GoDaddy.
