### ISSUE TITLE
Memory size exhausted issue when sending more than 2mb file as attachment

### ISSUE THREAD

**Issue by ashwini-bhat7744** [PHPMailer/PHPMailer#1863]
I am using PHPMailer version 6.* and PHP 7. When I  attach a file which is more than 2 mb and try to send an email, it is giving following error (Before I was using lower version of PHPMailer with PHP5. It was working fine in this case.)

**PHP Fatal error:  Allowed memory size of 20971520 bytes exhausted (tried to allocate 18840168 bytes) in /var/www/html/email/classes/PHPMailer/PHPMailer.php on line 3027**

I have increased memory limit and execution time in php.ini but issue remains same.

**Comment by Synchro** [comment]
Encoding attachments is indeed quite memory-hungry. I can only recommend setting it higher, say 64M or 128M.

**Comment by ashwini-bhat7744** [comment]
I have already increased memory allocation to 128M and also increased execution time to 120s. But it throws same error.
