### ISSUE TITLE
how to have dir='rtl' in html version?

### ISSUE THREAD

**Issue by nimasdj** [PHPMailer/PHPMailer#1867]
How to have dir='rtl' for html version? Any built-in ability? or I should create a full html body myself to have dir='rtl' and for alternative body, use strip html?

**Comment by Synchro** [comment]
PHPMailer doesn't do anything with the content - it's all up to you. I suggest you build an HTML message with appropriate RTL markup and put that in `Body` and give it a try. I don't think there's anything in headers that is relevant to text direction.

**Comment by nimasdj** [comment]
Thanks, for subject we use 
`'=?UTF-8?B?'.base64_encode($subj).'?=';`
to have our language properly visible in subject line.
but then no alternative email will be made of this email (I learnt it from gmail that it has no 'Show Original' option to see the full body), as only body has two methods one for html one for non-html, I suggest you consider to add an alternative subject method for non-html emails. The same methods for $to name and $from name. Would consider to implement?

**Comment by Synchro** [comment]
Uh, don't do that. PHPMailer encodes the subject for you. Do this:

    $mail->CharSet = PHPMailer::CHARSET_UTF8;
    $mail->Subject = $subj;

You can't do alternate subject headers, nor _to_ or _from_ names; that option simply doesn't exist in email.
