### ISSUE TITLE
How to include comma in setFrom $name ?

### ISSUE THREAD

**Issue by kilvroch** [PHPMailer/PHPMailer#1869]
setFrom() works fine on Linux as long as the $name does not include a comma.
it works when running on Windows 10 
I am sorry but I do not know this editor and line breaks are driving me nuts there should be oen after each semi colon

this does not work (the email disappears into the ether on Linux)
` $ShowName = 'Colne, Nelson & DCS';
$mail->setFrom('admin@showcatalogue.co.uk', "$ShowName");`

this works when I remove the comma
`$ShowName = str_replace(',','',$ShowName);    
$mail->setFrom('admin@showcatalogue.co.uk', "$ShowName");`

Someone on StackOverflow suggested replacing the comma with &comma;
`        $ShowName = str_replace(',','&comma;',$ShowName);    
        $mail->setFrom('admin@showcatalogue.co.uk', "$ShowName");`

That generated a 'from' name: `Colne&comma;Nelson & DCS`

**Comment by Synchro** [comment]
HTML entities won't help because an email subject line is not in an HTML context - email clients won't render HTML in places like that.

Using your example code results in a `From` header like this:

    From: "Colne, Nelson & DCS" <admin@showcatalogue.co.uk>

As you can see, it's quoted, and is correctly formatted. In my tests addresses like that are sent, delivered, and rendered as expected, so I suspect the problem is elsewhere. If you set `$mail->SMTPDebug = 2` and then send a message like this, is the message accepted? If you look in your mail server logs, can you see what happens to it after that?

**Comment by kilvroch** [comment]
fighting with this, the solution for me turned out to be specifically setting the SMTP values. 
For emails without commas in the '$name', I did not need to specifically set the SMTP security info. 
my guess is that it must be a security thingy with my ISP.

this worked:
`require 'vendor/autoload.php';
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
$ShowName = 'Colne, Nelson & DCS';

$OrderId = '12345';

$Subject = "test Entry no. $OrderId - For $ShowName";

$mail = new PHPMailer();

$mail->SMTPDebug = 2; //Alternative to above constant
$mail->isSMTP();  // tell the class to use SMTP                                 // set email format to HTML
$mail->SMTPAuth   = true;                // enable SMTP authentication
$mail->Port       = 2025;                // set the SMTP port
$mail->Host       = "my.server.host";    // SMTP server
$mail->Username   = "my.username";       // SMTP account username
$mail->Password   = "mypassword";        // SMTP account password    
$mail->IsHTML(true);                     // set email format to HTML
$ShowName = 'Colne, Nelson & DCS';

$mail->setFrom('admin@showcatalogue.co.uk', "$ShowName");
$mail->AddAddress("admin@showcatalogue.co.uk","ShowCat Webmaster");

$mail->Subject  =  $Subject;
$mail->Body     =  'test message';
$errmsg = '';
if(!$mail->Send()) {
   $errmsg = "Message was not sent <br />";
   $errmsg .= "Mailer Error: " . $mail->ErrorInfo;
	   echo 'Mailer Error2: '.$mail->ErrorInfo.'<br/>';
	   echo 'errmsg1: '.$errmsg.'<br/>';
	return false;
}
`
