### ISSUE TITLE
Mail without body

### ISSUE THREAD

**Issue by jys673** [PHPMailer/PHPMailer#1871]
Version 6.1.1 seems to generate emails with empty body. All else are working fine. Reverting to 6.0.5 solved the problem. (6.0.5) zip attached.
[PHPMailer-master (4).zip](https://github.com/PHPMailer/PHPMailer/files/3757783/PHPMailer-master.4.zip)

**Comment by Synchro** [comment]
I need to see your code and evidence of this. Giving me an old copy of the library doesn't tell me anything.

**Comment by jys673** [comment]
Thanks for replying!

Sure. We use your code to teach "full stack" coding at Temple University.

Here is the code (register.php):
======================================================
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\SMTP;

require '../PHPMailer-master/src/Exception.php';
require '../PHPMailer-master/src/PHPMailer.php';
require '../PHPMailer-master/src/SMTP.php';

    $FirstName=$_GET["FirstName"];
    $LastName=$_GET["LastName"];
    $Email=$_GET["Email"];
print "FN=$FirstName LN=$LastName <br>";
print "Email=$Email <br>";
print date('Y-m-d h:i:s');
$con = mysqli_connect(SERVER,USER,PASSWORD,DATABASE);
if (!$con) {
$_SESSION["Message"]="Database Connection Failure: ".mysqli_error($con);
$_SESSION["RegState"] = -1;
header("location:../index.php");
exit();
}
print "Connect success <br>";
$Acode = rand();
$Rdatetime = date("Y-m-d h:i:s");
$query = "INSERT INTO Visitors (Email, FirstName,LastName,Rdatetime, Acode)
VALUES ('$Email','$FirstName','$LastName','$Rdatetime','$Acode');";
$result = mysqli_query($con, $query);
print "Finished query <br>";
if ($result) {
// Build authentication email
$mail= new PHPMailer(true);
try {
$mail->SMTPDebug = 2;
$mail->IsSMTP();
$mail->Host="smtp.gmail.com";
$mail->SMTPAuth=true;
$mail->Username="cis105223053238@gmail.com"; // Do NOT change
$mail->Password = 'XXXXXXXX'; // Do NOT change
$mail->SMTPSecure = "ssl";
$mail->Port=465;
$mail->SMTPKeepAlive = true;
$mail->Mailer = "smtp";
$mail->setFrom("class@temple.edu", "CIS5015 Student"); // Change to your
email and name
$mail->addReplyTo("shi@temple.edu","Justin Y. Shi"); // Change to your
email and name
print "After setting up mail from and reply <br>";
$msg = "Please click link to complete registration:
http://cis-linux2.temple.edu/~shi/5015/final/php/authenticate.php?Email=$Email&Acode=$Acode
";
$mail->addAddress($Email,"$FirstName $LastName");
$mail->Subject = "Welcome";
$mail->Body = $msg;
$mail->send();
} catch (phpmailerException $e) {
$_SESSION["Message"] = "Mailer error: ".$e->errorMessage();
$_SESSION["RegState"] = -4;
print "Mail send failed: ".$e->errorMessage;
header("location:../index.php");
exit();
}

$_SESSION["RegState"] = 2;
$_SESSION["Message"] = "Registration success. Email sent.";
header("Location:../index.php");
exit();
}
$_SESSION["RegState"]=1;
$_SESSION["Message"] = "Registration Query Failure: ".mysqli_error($con);
header("Location:../index.php");
exit();
?>
==========================================================
Here is the screenshot of the messages with no body (v.6.1.1) and with body
(v. 6.0.5)

[image: image.png]

The tests were done yesterday. The three McCaffery's messages have no body
(the latest PHPMailer). I then tested gmail directly to see if gmail server
is working. It did. Then I recovered to 6.0.5. The problem disappeared (the
Makayla's messages).

===================================================================
Please let me know if you need anything else.

Thanks for calling back!

Justin

**Comment by Synchro** [comment]
The commits I pushed just earlier should fix this - please try it from the master branch. I think this is the same problem as in #1871.

**Comment by jys673** [comment]
Will do. Thanks!

Justin
