### ISSUE TITLE
Inconsistent Content-ID and cid cause inline image not to be displayed

### ISSUE THREAD

**Issue by pureven** [PHPMailer/PHPMailer#1875]
Part of the log content:

<div><span id="_FoxCURSOR"></span><br></div>
<div>
    <div class="FoxDiv20150120133337620321" id="FMOriginalContent">
        <div style="background:#f2f2f2;padding:40px 3px;">
            <div style="width:100%;background:#fff;border-style:solid;border-width:1px;border-color:#eaeaea #cccccc #a6a6a6;border-radius:4px;box-shadow:0 2px 2px #cdcdcd;margin:0 auto;">
                <img src="cid:795d06e8bc682357053989e82ad6de968370faf18c70fe89bbd9e2007e0ed2c6@phpmailer.0" alt=""
                     style="display:block;margin:20px 0 15px 50px;">
                <div style="padding:30px 55px 40px;min-height:300px;border-top:1px solid #efefef;">
                    <p style="color:#121214;font-size:14px;">hello!</p>
                    <p style="font-size:14px;color:#434144;margin:5px 0;">&nbsp;</p>
                    <p style="font-size:14px;color:#434144;"> information2 Team! </p>
                </div>
            </div>
        </div>
    </div>
</div>

--b2_iyTDnFin0nxPNa6c9PMO6oQLvhLta79fKcHRIJULU
Content-Type: image/png; name="embed0"
Content-Transfer-Encoding: base64
Content-ID: <=?us-ascii?Q?795d06e8bc682357053989e82ad6de968370faf18c70fe89bbd9e2007e0e?=
 =?us-ascii?Q?d2c6@phpmailer.0?=>
Content-Disposition: inline; filename=embed0
……………

=================================================

Line 3025： $mime[] = sprintf('Content-ID: <%s>%s', $cid, static::$LE); will be solved

**Comment by pureven** [comment]
<img src="cid:795d06e8bc682357053989e82ad6de968370faf18c70fe89bbd9e2007e0ed2c6@phpmailer.0" alt=""
                     style="display:block;margin:20px 0 15px 50px;">

**Comment by pureven** [comment]
<img src="cid:795d06e8bc682357053989e82ad6de968370faf18c70fe89bbd9e2007e0ed2c6@phpmailer.0" alt="" style="display:block;margin:20px 0 15px 50px;">

**Comment by Synchro** [comment]
No it won’t solve it because non-ascii characters used as content IDs will break it. Also, please try with the master branch because that has changes related to this.

**Comment by pureven** [comment]
thanks
