### ISSUE TITLE
Failes to msgHTML svg

### ISSUE THREAD

**Issue by JE4GLE** [PHPMailer/PHPMailer#1877]
The msgHTML failes to parse svg tags with the attribute `enable-background="new 0 0 300 100"`.
It throws the following error:

> Could not access file: [PATH censored]/new 0 0 300 100

**Comment by Synchro** [comment]
I can see how that would happen - please try the version in master.

**Comment by inogo** [comment]
@Synchro i've tried the latest version and got problem with formatting <img> tag.

You could see it with this assert in testEmbeddedImage case:

```
        $this->assertContains(
            '<img src="cid:bb229a48bee31f5d54ca12dc9bd960c6@phpmailer.0">',
            $this->Mail->getSentMIMEMessage(),
            'Embedded image tag incorrect.'
        );
```

Expected result: `<img src="cid:bb229a48bee31f5d54ca12dc9bd960c6@phpmailer.0">`
Actual: `<imgsrc="cid:bb229a48bee31f5d54ca12dc9bd960c6@phpmailer.0">`

**Comment by Synchro** [comment]
Ah, of course the pattern ends up consuming that space when it does the replacement - I changed it to a negative lookbehind assertion to ignore attributes that have a hyphen before the `background` or `src` words we're looking for. Please give it anther try.

**Comment by inogo** [comment]
It works, thanks for the quick fix!
