### ISSUE TITLE
兼容 >php7.0

### ISSUE THREAD

**Issue by jackbon8** [PHPMailer/PHPMailer#1879]
# Problem description
PHP 7.2开始不主张使用function __autoload(){}来自动加载类文件。
__autoload() been DEPRECATED as of PHP 7.2.0. Relying on this feature is highly discouraged.
请使用spl_autoload_register($callable)来替代__autoload()自动加载函数。其中参数$callable是一个自定义函数。自定义函数的参数为需要加载的类。其他用法和使用__autoload()自动加载函数一样。
spl_autoload_register()可以注册多个自动加载函数，而使用自动加载函数__autoload()自动加载类时只能写一个__autoload()函数。
Discuz!使用传统的__autoload()来自动加载类文件，在PHP 7.2中运行需要改为spl_autoload_register()。
# Code to reproduce
function __autoload($classname)
    {
        PHPMailerAutoload($classname);
    }
# Debug output
spl_autoload_register('PHPMailerAutoload');

**Comment by jackbon8** [comment]
PHPMailerAutoload.php 文件中的   45行到48行 改成
`spl_autoload_register('PHPMailerAutoload');`

**Comment by Synchro** [comment]
That’s because you’re using an old version; that function call does not exist in 6.0 and later.
