### ISSUE TITLE
phpmailer does not read greek letters

### ISSUE THREAD

**Issue by tak78** [PHPMailer/PHPMailer#1884]
Hi,
 i need help with the emails, i update the phpmailer, all files are utf-8 , but the emails comes like this when i use greek letters in fields name and message Î±Î³Î¿Ï�Î¹Î¹Î¹Î¹Î¹Î¹Î¹Î¹!!!!Î¿Ï…Î¿Ï…Î¿Ï…Î¿Ï…,, 
any suggestions?
Thanks in advance

<?php header('Content-Type: text/html; charset=utf-8');
       
$field_name = $_POST['cf_name'];
$field_email = $_POST['cf_email'];
$field_message = $_POST['cf_message'];

$mail_to = 'yourmail';
$subject = 'Message from a site visitor '.$field_name;

$body_message = 'From: '.$field_name."\n";
$body_message .= 'E-mail: '.$field_email."\n";
$body_message .= 'Message: '.$field_message;

$headers = 'From: '.$field_email."\r\n";
$headers .= 'Reply-To: '.$field_email."\r\n"
$mail->setLanguage('el', '/optional/path/to/language/directory/');
$mail_status = mail($mail_to,'=?UTF-8?B?' . base64_encode($arr['subject']) . '?=',$subject, $body_message, $headers);

if ($mail_status) { ?>
	<script language="javascript" type="text/javascript">
		alert('Thank you for the message. We will contact you shortly.');
		window.location = 'contact_page.html';
	</script>
<?php
}
else { ?>
	<script language="javascript" type="text/javascript">
		alert('Message failed. Please, send an email to gordon@template-help.com');
		window.location = 'contact_page.html';
	</script>
<?php
}
?>

**Comment by Synchro** [comment]
You are using PHP’s `mail` function, not PHPMailer, so I suggest you switch to using it, and set the `CharSet` property to `utf-8`.

**Comment by tak78** [comment]
Hi Synchro,
 i dont know mutch about php, can you tell me exactly what i have to change  in my code.
Thanks in advance

**Comment by Synchro** [comment]
First you need to load the PHPMailer libraries (I recommend learning how to use composer if you've not done so already), then write a script to use it: Start with the example provided in the readme.

**Comment by tak78** [comment]
i have downloaded the phpmailer and the composer from your site and thats why my contact form is working perfectly in english.
thanks

**Comment by Synchro** [comment]
If it's having trouble with non-ASCII characters, make sure you set:

    $mail->CharSet = 'utf-8';

in your mail script, and then ensure that **all** your scripts, content, and databases use UTF-8 too.

**Comment by tak78** [comment]
i am  having trouble with Greek characters, all my scripts are 'utf-8', but i read that 'utf-8' was
CHARSET_ISO88591 and thats why the greek is probleme. Because the Phpmailer has script with iso-8859-1 and greek are 8859-7.
PHPMailer.php
<?php
/**
 * PHPMailer - PHP email creation and transport class.
 * PHP Version 5.5.
 *
 * @see https://github.com/PHPMailer/PHPMailer/ The PHPMailer GitHub project
 *
 * @author    Marcus Bointon (Synchro/coolbru) <phpmailer@synchromedia.co.uk>
 * @author    Jim Jagielski (jimjag) <jimjag@gmail.com>
 * @author    Andy Prevost (codeworxtech) <codeworxtech@users.sourceforge.net>
 * @author    Brent R. Matzelle (original founder)
 * @copyright 2012 - 2019 Marcus Bointon
 * @copyright 2010 - 2012 Jim Jagielski
 * @copyright 2004 - 2009 Andy Prevost
 * @license   http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License
 * @note      This program is distributed in the hope that it will be useful - WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.
 */

namespace PHPMailer\PHPMailer;

/**
 * PHPMailer - PHP email creation and transport class.
 *
 * @author Marcus Bointon (Synchro/coolbru) <phpmailer@synchromedia.co.uk>
 * @author Jim Jagielski (jimjag) <jimjag@gmail.com>
 * @author Andy Prevost (codeworxtech) <codeworxtech@users.sourceforge.net>
 * @author Brent R. Matzelle (original founder)
 */
class PHPMailer
{
    const CHARSET_ASCII = 'us-ascii';
    const CHARSET_ISO88591 = 'iso-8859-1';
    const CHARSET_UTF8 = 'utf-8';

    const CONTENT_TYPE_PLAINTEXT = 'text/plain';
    const CONTENT_TYPE_TEXT_CALENDAR = 'text/calendar';
    const CONTENT_TYPE_TEXT_HTML = 'text/html';
    const CONTENT_TYPE_MULTIPART_ALTERNATIVE = 'multipart/alternative';
    const CONTENT_TYPE_MULTIPART_MIXED = 'multipart/mixed';
    const CONTENT_TYPE_MULTIPART_RELATED = 'multipart/related';

my contact.php with the change you suggest 
<?php 
       
$field_name = $_POST['cf_name'];
$field_email = $_POST['cf_email'];
$field_message = $_POST['cf_message'];

$mail_to = 'yourmail';
$subject = 'Message from a site visitor '.$field_name;

$body_message = 'From: '.$field_name."\n";
$body_message .= 'E-mail: '.$field_email."\n";
$body_message .= 'Message: '.$field_message;

$headers = 'From: '.$field_email."\r\n";
$headers .= 'Reply-To: '.$field_email."\r\n"
$mail->CharSet = 'utf-8';
$mail->setLanguage('el', '/optional/path/to/language/directory/');
$mail_status = mail($mail_to,'=?UTF-8?B?' . base64_encode($arr['subject']) . '?=',$subject, $body_message, $headers);

if ($mail_status) { ?>
	<script language="javascript" type="text/javascript">
		alert('Thank you for the message. We will contact you shortly.');
		window.location = 'contact_page.html';
	</script>
<?php
}
else { ?>
	<script language="javascript" type="text/javascript">
		alert('Message failed. Please, send an email to gordon@template-help.com');
		window.location = 'contact_page.html';
	</script>
<?php
}
?>

Thanks for your time again

**Comment by Synchro** [comment]
You're still using PHP's `mail` function, not PHPMailer. Base your script on the example in the readme, and **do not** call `mail()` yourself, i.e. delete this line:

    $mail_status = mail($mail_to,'=?UTF-8?B?' . base64_encode($arr['subject']) . '?=',$subject, $body_message, $headers);

**Comment by tak78** [comment]
ok, i want to pay someone, really!!!
I am trying a week to solve this. Apparantly need more knowledge and i can t understand what i need to do.
Thanks for everything.

**Comment by Synchro** [comment]
At the moment you seem to be sticking random bits of code together - get the example code working (from the readme or in the examples folder), then adapt it from there. Read the readme for how to use PHPMailer in general, and the examples for doing specific things.
