### ISSUE TITLE
How to use PHPMailer and xampp on a host

### ISSUE THREAD

**Issue by Eiromplays** [PHPMailer/PHPMailer#1886]
Hello, I have gotten it to work locally on my pc, but what would I do if I want to send mails from a host? Thanks
Here is the message I get:
Mailer Error: The following From address failed: mymail : MAIL FROM command failed,Authentication Required. Learn more at https://support.google.com/mail/?p=WantAuthError o189sm20117163wmo.23 - gsmtp ,530,5.5.1SMTP server error: MAIL FROM command failed Detail: Authentication Required. Learn more at https://support.google.com/mail/?p=WantAuthError o189sm20117163wmo.23 - gsmtp SMTP code: 530 Additional SMTP info: 5.5.1SMTP server error: MAIL FROM command failed Detail: Authentication Required. Learn more at https://support.google.com/mail/?p=WantAuthError o189sm20117163wmo.23 - gsmtp SMTP code: 530 Additional SMTP info: 5.5.1
This is new to me so any help is appreaciated, sorry if it is a stupid question.

**Comment by Synchro** [comment]
First, read that error message; it tells you something useful. Next read the troubleshooting guide which tells you how to deal with this exact problem.
