### ISSUE TITLE
Cannot get v6.1.1 via Composer

### ISSUE THREAD

**Issue by asos-francesca** [PHPMailer/PHPMailer#1887]
I have been using a legacy version of PHPMailer so wanted to upgrade to 6.1.1 - I installed Composer and used it to download what I thought was the latest version:

https://packagist.org/packages/phpmailer/phpmailer

I ran:

`composer require phpmailer/phpmailer`

The installed version reports as `5.2.27`. Even after running `composer upgrade` I simply get "Nothing to install or update"

Where can I source 6.1.1?

**Comment by NiklasBr** [comment]
Run `composer why-not phpmailer/phpmailer 6.1` (or  `composer why-not -r -t phpmailer/phpmailer 6.1` for some more info). What response does it give you?

**Comment by asos-francesca** [comment]
Looks like my PHP version is out of date. Thanks for the tip to check.
