### ISSUE TITLE
PHPMailer not connecting to Office365

### ISSUE THREAD

**Issue by jfha73** [PHPMailer/PHPMailer#189]
Hey guys,

I'm trying to connect to Office365 using the settings given by outlook.office365.com:

Server: smtp.office365.com
Port: 587
Security: TLS

I tried that but when I use TLS it doesn't connect and when I use STARTTLS I get a Couldn't authenticate.

I know for sure I'm using the correct Username=>Email and Password, but I can't get it to connect.

For more information when I have to use a local non secure, no login needed server it works, but when I try a TLS it doesn't.

Any ideas?

Thanks.

**Comment by sujithayur** [comment]
open php.ini file and check  php_openssl.dll is enabled,

if not found add this line

    extension=php_openssl.dll

**Comment by DouglasTonini** [comment]
RESOLVIDO!

Utilizando classe padrão de envio PHPMailer_5.2.1/class.phpmailer.php


Exemplo:

<?php
require("PHPMailer_5.2.1/class.phpmailer.php");

$mail             = new PHPMailer();

$mail->IsSMTP(); // telling the class to use SMTP
$mail->Host       = "smtp.office365.com"; // SMTP server
$mail->SMTPDebug  = 2;                     // enables SMTP debug information (for testing)
                                           // 1 = errors and messages
                                           // 2 = messages only
$mail->SMTPAuth   = true;                  // enable SMTP authentication
$mail->SMTPSecure = "tls";                 // sets the prefix to the servier
$mail->Host       = "smtp.office365.com";      // sets GMAIL as the SMTP server
$mail->Port       = 587;                   // set the SMTP port for the OUTLOOK 465 server
$mail->Username   = "seuemail@dominio.com.br";  // OUTLOOK 465 username
$mail->Password   = "sua senha";            // OUTLOOK 465  password

$mail->SetFrom('seuemail@dominio.com.br', 'First Last');

$mail->AddReplyTo("seuemail@dominio.com.br","First Last");

$mail->Subject    = "PHPMailer Test Subject via smtp (OUTLOOK 465), basic";

$mail->AltBody    = "To view the message, please use an HTML compatible email viewer!"; // optional, comment out and test

$body = 'teste';

$mail->MsgHTML($body);

$address = "seuemail@dominio.com.br";
$mail->AddAddress($address, "NOME");

if(!$mail->Send()) {
  echo "Mailer Error: " . $mail->ErrorInfo;
} else {
  echo "Message sent!";
}

?>

**Comment by lucianobonfim** [comment]
for me don´t work.
i am using 5.2.23 version but the same error

2017-05-21 05:36:41	Connection: opening to smtp.office365.com:587, timeout=300, options=array ( ) 
2017-05-21 05:36:41	Connection: opened 
2017-05-21 05:36:41	SERVER -> CLIENT: 220 DM5PR17CA0038.outlook.office365.com Microsoft ESMTP MAIL Service ready at Sun, 21 May 2017 05:36:41 +0000 
2017-05-21 05:36:41	CLIENT -> SERVER: EHLO www.strategypartners.com.br 
2017-05-21 05:36:41	SERVER -> CLIENT: 250-DM5PR17CA0038.outlook.office365.com Hello [13.65.45.30] 250-SIZE 157286400 250-PIPELINING 250-DSN 250-ENHANCEDSTATUSCODES 250-STARTTLS 250-8BITMIME 250-BINARYMIME 250 CHUNKING 
2017-05-21 05:36:41	CLIENT -> SERVER: STARTTLS 
2017-05-21 05:36:41	SERVER -> CLIENT: 220 2.0.0 SMTP server ready
2017-05-21 05:36:41	CLIENT -> SERVER: EHLO www.strategypartners.com.br 
2017-05-21 05:36:41	SERVER -> CLIENT: 250-DM5PR17CA0038.outlook.office365.com Hello [13.65.45.30] 250-SIZE 157286400 250-PIPELINING 250-DSN 250-ENHANCEDSTATUSCODES 250-AUTH LOGIN 250-8BITMIME 250-BINARYMIME 250 CHUNKING 
2017-05-21 05:36:41	CLIENT -> SERVER: AUTH LOGIN 
2017-05-21 05:36:41	SERVER -> CLIENT: 334 VXNlcm5hbWU6 
2017-05-21 05:36:41	CLIENT -> SERVER: Y29udGF0b0BzdHJhdGVneXBhcnRuZXJzLmNvbS5icg== 
2017-05-21 05:36:41	SERVER -> CLIENT: 334 UGFzc3dvcmQ6 
2017-05-21 05:36:41	CLIENT -> SERVER: UEBzc3cwcmQh 
2017-05-21 05:36:51	SERVER -> CLIENT: 535 5.7.3 Authentication unsuccessful [DM5PR17CA0038.namprd17.prod.outlook.com] 
2017-05-21 05:36:51	SMTP ERROR: Password command failed: 535 5.7.3 Authentication unsuccessful [DM5PR17CA0038.namprd17.prod.outlook.com] 
2017-05-21 05:36:51	SMTP Error: Could not authenticate. 
2017-05-21 05:36:51	CLIENT -> SERVER: QUIT 
2017-05-21 05:36:51	SERVER -> CLIENT: 221 2.0.0 Service closing transmission channel 
2017-05-21 05:36:51	Connection: closed 
2017-05-21 05:36:51	SMTP Error: Could not authenticate.

**Comment by lucianobonfim** [comment]
Any ideas?

Thanks.

**Comment by Synchro** [comment]
Yes, you've got the wrong username or password. Please don't hijack old, closed tickets. Also, your password was easily decoded from that transcript, so you should change your password.

**Comment by DouglasTonini** [comment]
Verifique se a conta (email de autenticação) foi criada corretamente.. Parece bobagem, mas as vezes é um pequeno descuido.  

https://login.microsoftonline.com   e  veja se sua caixa postal está ativa.

**Comment by lucianobonfim** [comment]
Sim.

 

Foi criada e esta funcionando normalmente pelo portal.

Já enviei emails de teste via oultook e funcionou

**Comment by DouglasTonini** [comment]
Tente usar esta classe:  https://github.com/jbroadway/php-mail-test/tree/master/PHPMailer_5.2.1

**Comment by lucianobonfim** [comment]
Estou usando a mais recente deles 5.2.3 e não funciona... essa ai é de 5 anos atrás... não vai funfar !!

**Comment by DouglasTonini** [comment]
Ai que ta.. funcionou comigo!  Precisa confiar.  Faça um teste meu caro.


2017-05-22 14:49 GMT-03:00 LUCIANO BONFIM DE AZEVEDO <
notifications@github.com>:

**Comment by lucianobonfim** [comment]
Mas vc esta usando smtp.office365.com ou um outro servidor de smtp?!

**Comment by lucianobonfim** [comment]
Não funcionou... o office365 preciso de criptografia TLS e nessa versão mais antiga nem tinha implementação disso ainda...

 

Na versão nova não ta funfando direito...

 

Eu vou fazer o envio via asp.net que eu já fiz pra outros clientes com office365 e funcionou... é que esse site está em PHP

 

Obrigado!

 

 

 

Atenciosamente,



Luciano Bonfim de Azevedo

www.bonfim.com.br <http://www.bonfim.com.br/> 

Luciano@bonfim.com.br <mailto:Luciano@bonfim.com.br> 

www.linkedin.com/in/lucianobonfim <http://www.linkedin.com/in/lucianobonfim> 

Celular/whatsApp: (21) 99222-2030 

Skype: lucianobonfim

 

Avenida das Américas, 18.000

Sala 321 bloco B | Rio de Janeiro – RJ

CEP: 22790-704

**Comment by DouglasTonini** [comment]
Passa seu email. Vou te passar a classe que uso. Estou usando Office 365
com envio autenticado com PHP.

Em 22 de mai de 2017 17:03, "LUCIANO BONFIM DE AZEVEDO" <
notifications@github.com> escreveu:

**Comment by lucianobonfim** [comment]
luciano@bonfim.com.br

**Comment by DouglasTonini** [comment]
Segue arquivos de envio autenticado PHP COM OFFICE 365.   Aguardo seu
parecer!

http://nwddesign.com.br/envio_autenticado_com_office_365/envio_com_office_365_douglas_tonini.zip

Att:  DOUGLAS TONINI   -   NWDSISTEMAS.com.br   - Lajeado / RS
www.nwdsistemas.com.br    www.nwddesign.com.br


Em 22 de maio de 2017 18:16, LUCIANO BONFIM DE AZEVEDO <
notifications@github.com> escreveu:

**Comment by lucianobonfim** [comment]
Continua dando erro aqui... estranho!

**Comment by DouglasTonini** [comment]
manda seu arquivo por email..vou estar aqui.


2017-05-22 20:35 GMT-03:00 LUCIANO BONFIM DE AZEVEDO <
notifications@github.com>:

**Comment by kazakbala** [comment]
I had same problem with Microsoft Exchange with TLS. 
Try to auth without domain name.
I just changed
` $mail->Username = 'user@domain.tdl';`
to
` $mail->Username = 'user';`

**Comment by imManish** [comment]
i am having same issue with sending email through office365 smtp

$mail = new PHPMailer();   
    $mail->CharSet = 'UTF-8';   
    $mail->isSMTP();   
    $mail->SMTPDebug = 2;   
    $mail->Host = "smtp.office365.com";   
    $mail->Port = 587;   
    $mail->SMTPSecure = 'tls';   
    $mail->SMTPAuth = true;   
    $mail->Username = "user@domain.com";   
    $mail->Password = "*******"; 
    
    $ppbuzzyuser_email=$_POST['buzzyuser_email'];
    $mail->FromName = 'Invitation for Certefied';
    $mail->addAddress($ppbuzzyuser_email);            
    $mail->Subject = 'Do not reply on this message.';
    
    $mail->Body   = '<div style="background:#eee; width:551px; height:277px; margin:0 auto;">
      <h3  style="text-align:center; color:#2f4050; font-size:22px; padding-top:60px;">Dear '.$ppbuzzyuser_email.'</h3>
      <p style="text-align:center; color:#2f4050; font-size:17px; margin-top:0px;">Your Employer <strong>'.$session_buzzyuser_company.'</strong> requests for you to join CertEfied. CertEfied is '.$session_buzzyuser_company.'&#39;s compliance software program, that helps you and '.$session_buzzyuser_company.' store employee licences and qualifications quickly and easily. </p>
      <p style="text-align:center; color:#2f4050; font-size:17px; margin-top:0px;">
        CertEfied is able to store your qualifications within your own individual profile for free. This will allow you to share your professional qualifications or licences with '.$session_buzzyuser_company.' quickly and easily. Just simply upload all qualifications your employer requires access to and have CertEfied look after automatically synchronising it to your employer’s profile.
      </p>
      <p style="text-align:center; color:#2f4050; font-size:17px; margin-top:0px;">
      If you undertake work with more than one employer who requires access to your credentials, you may add yourself / request to be added to their CertEfied company profile. No need to re register twice!
      </p>
      <p style="text-align:center; color:#2f4050; font-size:17px; margin-top:0px;">
      If you wish to sign up using this link <a  href="'.$buzzysiteurl.'/index.php?company-invite='.$session_user_id.'">Register here</a> this means you will be automatically be connected to '.$session_buzzyuser_company.' so you can start uploading your qualifications and licences for you and your employer right away. This helps you to remain safe and compliant at work.
      </p>
      Regards
      <p style="text-align:center; color:#2f4050; font-size:17px; margin-top:0px;">
      The CertEfied Team
      </p>
    </div>';

  $mail->AltBody = 'Hello user, You are now member of Certefied community. ';    
  if(!$mail->send()) {
  echo 'Message could not be sent.';
  echo 'Mailer Error: ' . $mail->ErrorInfo;
  } else {
    echo 'Message sent successfully.';
 }
 exit;
	  	header('Location: '.$link_prefix.'page.php?user-id='.$session_user_id.'&invite-sent=true');	
   }

Anyone can help me on this?

**Comment by DouglasTonini** [comment]
OLÁ!   Tenta colcar porta :  PORT: 465


2018-09-11 18:11 GMT-03:00 imManish <notifications@github.com>:

**Comment by jaimemtzag** [comment]
I made it work,  doing the next steps:

1) Use de Phpmailer version 5.2 - PHPMailer-5.2-stable
2) Open the example  - ssl_options.php   /  fill with your office365 acount and pwd
3) Use the next configuration, and it works - because it  avoid checking a certificate SSL - :

$mail->Host = 'smtp.office365.com';
$mail->Port = 587;
$mail->SMTPSecure = 'tls';

$mail->SMTPOptions = array (
    'ssl' => array(
        'verify_peer'  => false,
		'verify_peer_name' => false,
        'allow_self_signed' => true            
    )
);
