### ISSUE TITLE
smtp_check.phps

### ISSUE THREAD

**Issue by maltboy** [PHPMailer/PHPMailer#1892]
hi,
When I was using smtp check.phps, I found that I could not verify port 465. Can you help me?

**Comment by Synchro** [comment]
That means that either your mail server doesn’t support SMTPS on port 465, or your hosting provider blocks outbound SMTP. It’s up to you to find and use the correct settings for your own configuration.

**Comment by maltboy** [comment]
I can send mail via port 465 and SSL, but I can't verify it via smtp check.phps method via smtp.

Here is my try code：

    public function smtpChecking()
    {

        $host  = 'smtp.gmail.com';
        $email  = 'maltoseactress@gmail.com';
        $password  = 'knwtnkioaqvrdajg';
        $port  = '465';
        date_default_timezone_set('PRC');
        $smtp = new SMTP();
        $smtp->do_debug = SMTP::DEBUG_CONNECTION;
        try {
            if (!$smtp->connect($host, $port)) {
                throw new Exception('Connect failed');
            }
            if (!$smtp->hello(gethostname())) {
                throw new Exception('EHLO failed: ' . $smtp->getError()['error']);
            }
            $e = $smtp->getServerExtList();
            if (is_array($e) && array_key_exists('STARTTLS', $e)) {
                $tlsok = $smtp->startTLS();
                if (!$tlsok) {
                    throw new Exception('Failed to start encryption: ' . $smtp->getError()['error']);
                }
                if (!$smtp->hello(gethostname())) {
                    throw new Exception('EHLO (2) failed: ' . $smtp->getError()['error']);
                }
                $e = $smtp->getServerExtList();
            }
            if (is_array($e) && array_key_exists('AUTH', $e)) {
                if ($smtp->authenticate($email, $password)) {
                    echo 'Connected ok!';
                } else {
                    throw new Exception('Authentication failed: ' . $smtp->getError()['error']);
                }
            }
        } catch (Exception $e) {
            echo 'SMTP error: ' . $e->getMessage(), "\n";
        }
        $smtp->quit();
    }
