### ISSUE TITLE
smtp_check.phps

### ISSUE THREAD

**Issue by maltboy** [PHPMailer/PHPMailer#1893]
我可以通过端口465和SSL发送邮件，但无法通过smtp的smtp check.phps方法验证邮件。

这是我的尝试代码：

public function smtpChecking()
{

    $host  = 'smtp.gmail.com';
    $email  = 'maltoseactress@gmail.com';
    $password  = 'knwtnkioaqvrdajg';
    $port  = '465';
    date_default_timezone_set('PRC');
    $smtp = new SMTP();
    $smtp->do_debug = SMTP::DEBUG_CONNECTION;
    try {
        if (!$smtp->connect($host, $port)) {
            throw new Exception('Connect failed');
        }
        if (!$smtp->hello(gethostname())) {
            throw new Exception('EHLO failed: ' . $smtp->getError()['error']);
        }
        $e = $smtp->getServerExtList();
        if (is_array($e) && array_key_exists('STARTTLS', $e)) {
            $tlsok = $smtp->startTLS();
            if (!$tlsok) {
                throw new Exception('Failed to start encryption: ' . $smtp->getError()['error']);
            }
            if (!$smtp->hello(gethostname())) {
                throw new Exception('EHLO (2) failed: ' . $smtp->getError()['error']);
            }
            $e = $smtp->getServerExtList();
        }
        if (is_array($e) && array_key_exists('AUTH', $e)) {
            if ($smtp->authenticate($email, $password)) {
                echo 'Connected ok!';
            } else {
                throw new Exception('Authentication failed: ' . $smtp->getError()['error']);
            }
        }
    } catch (Exception $e) {
        echo 'SMTP error: ' . $e->getMessage(), "\n";
    }
    $smtp->quit();
}

**Comment by Synchro** [comment]
What does your debug output say?

**Comment by Synchro** [comment]
That looks like a connection failure of some kind - it's not even getting as far as sending you a welcome banner, so your code isn't getting a chance to do anything. I suggest using the tests described in the troubleshooting guide to diagnose issues with your network.

**Comment by maltboy** [comment]
> That looks like a connection failure of some kind - it's not even getting as far as sending you a welcome banner, so your code isn't getting a chance to do anything. I suggest using the tests described in the troubleshooting guide to diagnose issues with your network.

The problem I am facing now should be, the problem of SSL certificate, how should I solve it?

**Comment by maltboy** [comment]
> That looks like a connection failure of some kind - it's not even getting as far as sending you a welcome banner, so your code isn't getting a chance to do anything. I suggest using the tests described in the troubleshooting guide to diagnose issues with your network.

"ssl" => array(
            "verify_peer" => false,
            "verify_peer_name" => false,
            "allow_self_signed" => true
        )
Does it matter? Please read the question again. Thank you

**Comment by maltboy** [comment]
> That looks like a connection failure of some kind - it's not even getting as far as sending you a welcome banner, so your code isn't getting a chance to do anything. I suggest using the tests described in the troubleshooting guide to diagnose issues with your network.

This is the latest debug output:

![1](https://user-images.githubusercontent.com/57748904/69207965-d54ad680-0b8c-11ea-8fc6-f6b52fbaee1a.png)

![2](https://user-images.githubusercontent.com/57748904/69208098-49857a00-0b8d-11ea-80ba-043ccf636d9d.png)

**Comment by Synchro** [comment]
The connection is timing out after 30 seconds, which makes it sound like your network blocks outbound SMTP. Trying `SMTPSecure = 'tls'` and `Port = 587` may provide additional feedback, but will likely fail too. All this is covered in the guide.

Never disable certificate verification unless you have a very specific reason for doing so and you understand its implications.

**Comment by maltboy** [comment]
> The connection is timing out after 30 seconds, which makes it sound like your network blocks outbound SMTP. Trying `SMTPSecure = 'tls'` and `Port = 587` may provide additional feedback, but will likely fail too. All this is covered in the guide.
> 
> Never disable certificate verification unless you have a very specific reason for doing so and you understand its implications.



587 and tls can pass verification. Only 465 and ssl will fail.
Can you try to use this method with 465 and ssl? Please tell me the test results.

**Comment by Synchro** [comment]
There's no point in me trying it - it's not my network thats the problem. If port 587 works for you, use that.

**Comment by maltboy** [comment]
ok!

thanks for your help.
