### ISSUE TITLE
Cron cant execute PHPMailer

### ISSUE THREAD

**Issue by PiklioBezGashti** [PHPMailer/PHPMailer#1894]
im trying to run phpmailer via cron but for some reason only the part for token update is executed after that nothing is executed BUT if i run it via browser everything work fine . Any reason why this happen ?

    require_once(dirname(__DIR__)."/test/mail/PHPMailer.php");
    require_once(dirname(__DIR__)."/test/mail/SMTP.php");
    require_once(dirname(__DIR__)."/test/mail/Exception.php");
    require_once(dirname(__DIR__)."/test/db/conn.php");

    use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\SMTP;
    use PHPMailer\PHPMailer\Exception;

      $sql = "SELECT * FROM customers WHERE mail_status = 0 LIMIT 100";

      $results = $conn->query($sql);

      while ($row = $results->fetch_assoc()) {

       $salt = rand(5, 20);
       $token = sha1($salt . sha1($salt . sha1(rand(5, 20))));
       $insert = "UPDATE customers SET token = '" . $token . "' WHERE id = '" . (int)$row['id'] . "'";
       $conn->query($insert);

      }

      $mail = new PHPMailer(true);
      $mail->CharSet = "UTF-8";
      $mail->isSMTP();
      $mail->Host = 'example.com';
      $mail->SMTPAuth = true;
      $mail->SMTPKeepAlive = true;
      $mail->Port = 25;
      $mail->Username = 'example@example.com';
      $mail->Password = 'example';
      $mail->setFrom('example@example.com', 'example');
      $mail->isHTML(true);
      $mail->Subject = 'example';
      $mail->AltBody = 'example';
      $mail->AddEmbeddedImage('image/3.jpg', 'logo', '3.jpg');

      $result = $conn->query($sql);

      foreach ($result as $row) {

    $encoded_user_id = base64_encode($row['id']);
    $link = "http://www.example.com/test/unsubscribe.php?id=". $encoded_user_id ."&token=".$row['token'];
    $body = file_get_contents('contents.html');
    $body .= '<div><a style="text-decoration: none;color:#38aa20;" href="'.$link.'">unsubscribe</a></div>';
    $mail->msgHTML($body);
      try {
          $mail->addAddress($row['email']);
      } catch (Exception $e) {
          echo 'Invalid address skipped: ' . htmlspecialchars($row['email']) . '<br>';
          continue;
      }
      try {
          $mail->send();

          echo 'Message sent to :' . htmlspecialchars($row['email']) . '<br>';

          $update = "UPDATE customers SET mail_status = 1 WHERE id= '" . (int)$row['id']  . "'";
          $conn->query($update);

      } catch (Exception $e) {
          echo 'Mailer Error (' . htmlspecialchars($row['email']) . ') ' . $mail->ErrorInfo . '<br>';
          $mail->smtp->reset();
      }
      $mail->clearAddresses();
      }

      $conn->close();

**Comment by Synchro** [comment]
What does your debug output say?

**Comment by PiklioBezGashti** [comment]
@Synchro  at cPanel error log is nothing record as error

**Comment by PiklioBezGashti** [comment]
problem is here $mail->AddEmbeddedImage('image/3.jpg', 'logo', '3.jpg'); isnt set the full path to the image directory

**Comment by Synchro** [comment]
Glad you fixed it. This is why error checking is always a good idea - `addEmbeddedImage` returns false if it fails to read the file, so don't just assume that it works.
