### ISSUE TITLE
End of script output before headers

### ISSUE THREAD

**Issue by Serob** [PHPMailer/PHPMailer#1900]
# Problem description
I am trying to test some mail services such as sendinblue or sendgrid using SMTP connection. I have created a test php file, which uses my sendinblue.com or sendgrid.com credentials to send one email message, and it works fine on my local Windows machine, but when I upload it to the
hosting,  it gives the following error on request:
**End of script output before headers**
Similar script works fine, when I connect to smtp server directly.

# Code to reproduce
```
<?php
use PHPMailer\PHPMailer\PHPMailer;

require 'PHPMailer/src/Exception.php';
require 'PHPMailer/src/PHPMailer.php';
require 'PHPMailer/src/SMTP.php';

$mail = new PHPMailer(true);								
$mail->CharSet = 'UTF-8';
$mail->Encoding = 'base64';

//Server settings
$mail->SMTPDebug = 2;									
$mail->isSMTP();										
$mail->Host = 'smtp-relay.sendinblue.com'; 						
$mail->SMTPAuth = true;									
$mail->Username = 'serob45@mail.ru';			//My SendInBlue or SendGrid username		
$mail->Password = '';						
$mail->SMTPSecure = 'tls';							
$mail->Port = '587';	

$mail->setFrom('serob45@mail.ru', 'Serob');
$mail->addAddress('test@gmail.com');
$mail->Subject = 'Test Subject from gmail';
$mail->isHTML(true);
$mail->Body = 'Hello dear Serob';

$success=$mail->send();
```

# Debug output
End of script output before headers: mail_test.php

**Comment by Synchro** [comment]
Your script produces no output at all - is it meant to?

**Comment by Serob** [comment]
> Your script produces no output at all - is it meant to?

I just wanted to show the main PHPMailer part. 
In fact it ends with the following lines, but it doesn't change anything:
```
if (!$success) {
    echo error_get_last()['message'];
} else {
	echo 'email sent';
}
```

**Comment by Synchro** [comment]
Check the headers of your response (e.g. with `curl -I`) - does it include a content-type header? From a little searching, it seems this could be a web server config or environment issue.

**Comment by Serob** [comment]
content-type is  text/html, as my web-hosting (Strato) returns the following html page on this error:
![image](https://user-images.githubusercontent.com/10531198/69341389-f55cc180-0c82-11ea-9f43-7db6c663de9e.png)

**Comment by mail2bapi** [comment]
What PHP version are you using in your local system and in hosting server?
