### ISSUE TITLE
Warning: require(vendor/autoload.php): failed to open stream

### ISSUE THREAD

**Issue by yeasherarafath** [PHPMailer/PHPMailer#1904]
When I am trying to Fetch the token it's showing 
**Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /**********/htdocs/vendor/phpmailer/phpmailer/get_oauth_token.php on line 63**

**Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/pear/') in ****/htdocs/vendor/phpmailer/phpmailer/get_oauth_token.php on line 63**

**Comment by Synchro** [comment]
It's because you did not add it to your project using composer. Please read the readme which tells you how to install PHPMailer.

**Comment by Synchro** [comment]
Actually that may be wrong - but you will need to copy that file to the root of your project and edit it with your config settings before it's usable.

**Comment by yeasherarafath** [comment]
Please tell me how to do this

**Comment by Synchro** [comment]
You need me to tell you how to copy a file from one place to another and then edit it?

**Comment by yeasherarafath** [comment]
I didn't tell you that. I told you how to edit according to my config setting and which setting?

**Comment by yeasherarafath** [comment]
![image](https://user-images.githubusercontent.com/50262277/69379202-3502c800-0cda-11ea-96b6-7ffd98249ff7.png)

Now it's working..... Thank You for your respond 👍

**Comment by winardidesign** [comment]
@yeasherarafath I have the same problem, where did you put the require('vendor/autoload.php) ?

**Comment by NiklasBr** [comment]
@winardidesign Put it on top of the primary PHP file (e.g. bootstrap file or index file) where you need it, see documentation: https://github.com/PHPMailer/PHPMailer#installation--loading

Be sure to follow the link to Composer if you are unsure.

**Comment by yeasherarafath** [comment]
@winardidesign Still now facing  same problem?
