### ISSUE TITLE
Missing content in body if i attached a pdf

### ISSUE THREAD

**Issue by Dawa89** [PHPMailer/PHPMailer#1906]
Hi i have a problem with the AddAttachment function and i hope that you can help me.
If i attached a pdf file i get the attachment but the mailbody is empty. When i comment out the line for the attachment i get the mailbody. 

How can i send the mailbody and the pdf file?

`
$mail= new \PHPMailer\PHPMailer\PHPMailer();
//MAIL SENDEN
$mail->IsSMTP();
$mail->Host     = $smtp_host; 
$mail->SMTPDebug = 1;  
$mail->Port = $smtp_port; // TLS only
$mail->SMTPSecure = 'tls'; // ssl is depracated
$mail->SMTPAuth = true;
$mail->Username = $smtp_username;
$mail->Password = $smtp_passwort;

$mail->Subject = $betreff;
$mail->IsHTML(true);

//$mail->MsgHTML($body);
$mail->From     = $absender;
$mail->FromName = $absendername;
$mail->AddReplyTo($antwort_an_email);

$mail->AddCustomHeader( "Return-receipt-to: ".$absender );
$mail->AddCustomHeader( "Disposition-Notification-To: ".$absender );
$mail->Sender     = $fehlerpostfach;
$mail->CharSet  =  "utf-8"; // btw. den charset, mit dem du arbeitest
$mail->AddAddress($empfaenger_email);
$mail->AddAttachment($pdf, $pdfname, 'base64', 'application/pdf');
$mail->Body = $body; // Das was du vermailen möchtest HTML-Format
$mail->AltBody = $AltBody;
if (!$mail->send()) {
  echo 'Mailer Error: '. $mail->ErrorInfo;
} else {
   echo 'Message sent!';
}
`

**Comment by Dawa89** [comment]
Problem is solved. It s a Bug in the current PHPMailer version.

**Comment by Synchro** [comment]
If it's an outstanding bug, how is this solved?

**Comment by Dawa89** [comment]
Im using an older release now. Exactly i user version 6.0.6 now. You can find it here https://github.com/PHPMailer/PHPMailer/releases
