### ISSUE TITLE
Default validation fails with umlaut in name part

### ISSUE THREAD

**Issue by JayQ1982** [PHPMailer/PHPMailer#1907]
Validation of "testümläüt@domain.tld" fails when i use default $patternselect value "php".

This could be fixed in validateAddress()-method by changing

`return (bool) filter_var($address, FILTER_VALIDATE_EMAIL);`
to
`return (bool) filter_var($address, FILTER_VALIDATE_EMAIL, FILTER_FLAG_EMAIL_UNICODE);`

**Comment by Synchro** [comment]
That's because Unicode in the local part is not valid unless you support [RFC6531](https://tools.ietf.org/html/rfc6531), which PHPMailer does not (yet), and it involves a lot more than changing address validation; it's also dependent on the server you connect to supporting it.
