### ISSUE TITLE
Fatal error: Uncaught Error: Class 'PHPMailer' not found in 

### ISSUE THREAD

**Issue by Brunowfs54** [PHPMailer/PHPMailer#1908]
Fatal error: Uncaught Error: Class 'PHPMailer' not found in.

I used it for the composer and I can't send the email.
Maybe it can be a simple thing, I'm a beginner, sorry for any trouble.
If you can help me thank you.

**Comment by Synchro** [comment]
This will be because you are missing `use` statements at the top of your script. Read the readme and examples that show how to load PHPMailer classes.
