### ISSUE TITLE
Duplicate emails being sent with a single ->Send() call

### ISSUE THREAD

**Issue by ktoonsez** [PHPMailer/PHPMailer#1915]
Running version 6.1.4 on Windows Server 2019 with IIS 10.0.

Here is the code:

		$mail = new PHPMailer(true); // create a new object
		$mail->IsSMTP(); // enable SMTP
		$mail->SMTPDebug = 0; // debugging: 1 = errors and messages, 2 = messages only
		$mail->SMTPAuth = true; // authentication enabled
		//$mail->SingleTo = true; //will send mail to each email address individually
		$mail->CharSet = "UTF-8";
		$mail->SMTPSecure = 'ssl'; // secure transfer enabled REQUIRED for Gmail
		$mail->Host = "smtp.gmail.com";
		$mail->Port = 465; // or 587
		$mail->IsHTML(true);
		$mail->Username = 'user';
		$mail->Password = 'pass';
		$mail->SetFrom('abcd@gmail.com', 'Site admin');
		$mail->Subject = "Shared scorecard from ";
		$mail->Body = $emailbdy;
		
                $emailto = 'efgh@gmail.com';
		$emailto = str_replace(',', ';', $emailto);
		$tags = explode(';' , $emailto);
		foreach($tags as $i =>$key) {
			$mail->AddAddress(trim($key));
			$cnt += 1;
		}

		if($mail->Send()) {
			$response["status"] = 0;
			$response["message"] = "Email sent - " . $cnt;
		} else {
			$response["status"] = 3;
			$response["message"] = "Mailer failed: " . $mail->ErrorInfo;
		}
		//$mail->ClearAllRecipients();
		//$mail->ClearAddresses();

So I execute the code above and the pattern seems to be about every hour or so it will send the email to the recipient twice.  I have found many posts on various help sites but none of the answers suggested work for me.   I have tried setting $mail->SingleTo = true, calling $mail->ClearAllRecipients(), setting $mail->CharSet = "UTF-8", and calling $mail->ClearAddresses() as some sites have suggested, nothing works.  Hope someone has seen this and found the fix.  Even added a variable $cnt to make sure it was only calling AddAddress() once and it is only calling it once with the email address example from above.   The function finishes without any errors.

Thanks

**Comment by Synchro** [comment]
It's not the script. It will be because your script is being run more than once, sending a single message each time. Figure out if and how that's happening by adding logging, appending a random number to the subject line, then look at how this script is being triggered.

**Comment by fumagally** [comment]
Hi @ktoonsez , @Synchro !

I have same problem!

My code to test send mail is it:

`use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

class Mail
{
    public static function sendEmail($subject, $to)
    {
        $config = \App\Model\ConfigModel::loadConfig();
        
            $mail = new PHPMailer();
            $mail->SMTPDebug = SMTP::DEBUG_OFF;
            $mail->isSMTP();
            $mail->Host = $config['smtp_host'];
            $mail->SMTPAuth = true;
            $mail->Username = $config['smtp_login'];
            $mail->Password = $config['smtp_pass'];
            $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
            $mail->Port = $config['smtp_port'];
            
            $mail->setFrom($config['smtp_login']);
            
            $mail->AddAddress($to);

            $mail->isHTML(true);

            echo "Test call duplicate: ".rand()." ################<br>";

            $mail->Subject = $subject.rand();
            
            $mail->Body = 'test';
            
            $mail->send();
            echo 'ok';
            exit;
    }
}`

And call is:

`Mail::enviarEmail('Test!!! Rand: ', 'suporte@isolucoesweb.com.br');`

The resulto is: `Test call duplicate: 1258187430 ################
ok`

But in my mail receive duplicate like this:

![image](https://user-images.githubusercontent.com/3512770/112688133-30629c80-8e57-11eb-8246-6dea65029e1d.png)

does anyone have a solution for this?
