### ISSUE TITLE
Install PHPMailer centrally and make it available to different websites

### ISSUE THREAD

**Issue by mehargags** [PHPMailer/PHPMailer#1916]
Hi,
This is rather a query and not a bug report, so kindly excuse.
Also, I'm not a developer, but rather a sysadmin so I may sound a bit off from usual dev approach.

I have a client who is into bigtime marketing. They have microsites, landing pages ... like hundreds of them, which host lead generation html forms. Now I was wondering if there is a way that I can install PHPMailer centrally on a server and then create different "SMTP routes" . So group one can send mail through one SMTP, others with other and so on. However, what I want is NOT to include PHPmailer library for each site, rather the html form submits to this centrally available PHPMailer script (which has the specific SMTP for the group). Is this possible in some way ?

Please also see that websites are hosted under different Linux users, isolated from each other.

Is there a way to make PHPMailer as a PHP extension or a kind of "Global Class" that is accessible throughout the server ?

Thanks

**Comment by Synchro** [comment]
You could put it in a central location (e.g. `/usr/share/php`) that is then added to your global PHP `include_path` directive so that all your scripts can find it. You may find that your system package manager has support for it already, [as it does in Debian](https://packages.debian.org/buster/libphp-phpmailer), and that will achieve much the same thing. Doing that means that you only need one installation of PHPMailer, but it still means that every script will need to customise its use of it. You could work around that by moving such details into external config file that a single central script picks up for each site, but that's not a great saving.

**Comment by mehargags** [comment]
Many thanks for the fast reply... Yes indeed, `libphp-phpmailer` is what I needed. I tried and it works wonderfully. 👍 

Now the second part, as I would **NOT** want a submit.php for each site, can I make a few submit scripts like: _sendgrid.php, SES.php, postmark.php_ with their respective SMTP credentials and then call them "centrally" from the html form's 'action' attribute ?

This would enable me to keep only HTML files in the site folders without any PHP scripts... which is what I'm trying to achieve. 

Thanks alot.

**Comment by Synchro** [comment]
The only "configuration-free" way I can think of for doing that is to map things through the URL of the hosting domain. In your central script you could then do things like set the from address with:

    $mail->setFrom('contact@' . $_SERVER['SERVER_NAME']);

(though be aware of spoofing that).

Alternatively you could maintain a database of the sites you're hosting and use the incoming hostname to look up their settings.

Overall this is a long way outside the scope of PHPMailer itself though.

**Comment by mehargags** [comment]
Well, I'm stuck at where to place the first SMTP send script... 
if I place it in /usr/share/php/libphp-phpmailer/submit.php and give this static path in action attribute of my form located at /home/domain.com/public_html/form.html, it gives a 404 upon submission.

I'm also using basedir protection, so that also plays a role here.

I understand this may not directly be a problem inside PHPmailer scope... rather a generalised perception.
I'm sure there must some way to define submit.php file globally server-wide.
