### ISSUE TITLE
Password variable name security error

### ISSUE THREAD

**Issue by msankar1991** [PHPMailer/PHPMailer#1920]
While analysis code from SonarQube tool got below security error with it.
```
phpmailer/src/PHPMailer.php
'password' detected in this variable name, review this potentially hardcoded credential.
Vulnerability
```
<img width="863" alt="phpmailer" src="https://user-images.githubusercontent.com/8719413/70989285-5a240400-20e9-11ea-8de9-70da0504befb.png">

**Comment by Synchro** [comment]
This is not a security issue as it's not a hardcoded password; it's a default empty value on a property. How you *set* that property may represent an issue (ideally from env vars), but that's outside PHPMailer's scope.
