### ISSUE TITLE
AddBCC problem with multiple email adress

### ISSUE THREAD

**Issue by Azirk** [PHPMailer/PHPMailer#1922]
Hello,

I'm trying to use PhpMailer, and I want to use it to send newsletter.
However, when I want to send this massive emails, I try to use 'addBCC' to permitt user to hide their email adress. I'm using a while function to add multiple BCC, like this :
($rep is the result of user database)
	while($rep = $req->fetch()){
		$email->addBCC($rep['mail']);
	}

But when I'm sending the email, I just get this message : 

Fatal error: Uncaught PHPMailer\PHPMailer\Exception: Could not instantiate mail function. in /htdocs/PHPMailer/src/PHPMailer.php:1791 Stack trace: #0 /htdocs/PHPMailer/src/PHPMailer.php(1589): PHPMailer\PHPMailer\PHPMailer->mailSend('Date: Sun, 22 D...', '<p>Bonjour,</p>...') #1 /htdocs/PHPMailer/src/PHPMailer.php(1423): PHPMailer\PHPMailer\PHPMailer->postSend() #2 /htdocs/requetes/email-general.php(15): PHPMailer\PHPMailer\PHPMailer->send() #3 {main} thrown in /htdocs/PHPMailer/src/PHPMailer.php on line 1791

Thanks for helping and sorry for my english.

Azirk

**Comment by Synchro** [comment]
It's nothing to do with your use of BCC, it's that you don't have a local mail server. Please [read the docs on this](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#could-not-instantiate-mail-function).

**Comment by Azirk** [comment]
Hello!

But if I remove my addBCC, the mail is sent

**Comment by Synchro** [comment]
That is odd - does it work if you send through SMTP to localhost? Add `$mail->isSMTP();` to try that. You can see the server's response by setting `$mail->SMTPDebug = 2;`.

**Comment by Azirk** [comment]
Okay, I did isSMTP and I started the debug. But now, I have a new error!
2019-12-23 14:33:40 SERVER -> CLIENT: 450 4.7.1 Client host rejected: cannot find your reverse hostname, [185.98.131.141]
2019-12-23 14:33:40 SMTP ERROR: MAIL FROM command failed: 450 4.7.1 Client host rejected: cannot find your reverse hostname, [185.98.131.141]
The following From address failed: diffusion@railclubmodelsat.fr : MAIL FROM command failed,Client host rejected: cannot find your reverse hostname, [185.98.131.141],450,4.7.1SMTP server error: MAIL FROM command failed Detail: Client host rejected: cannot find your reverse hostname, [185.98.131.141] SMTP code: 450 Additional SMTP info: 4.7.1

**Comment by Synchro** [comment]
You need to set a reverse IP hostname. When a mail server receives a connection from you, it does a reverse lookup of your IP address; the name it receives should match the forward address. At present you don't have a reverse entry at all - you should either be able to configure it through your hosting provider's control panel, or ask them to set it for you.

**Comment by Azirk** [comment]
Thanks. I will do this and I come for news when it's okay.

**Comment by Azirk** [comment]
It's working! Thanks for helping
