### ISSUE TITLE
encodeFile() does not throw when exceptions are enabled

### ISSUE THREAD

**Issue by compwright** [PHPMailer/PHPMailer#1924]
# Problem description

**Expected behavior:**

When exceptions are enabled in PHPMailer 6.1 and a bad file is attached, the exception `File Error: Could not open file: /mnt/tmp/file-does-not-exist.pdf` should be thrown.

**Actual behavior:**

The exception `Message body empty` is thrown.

# Code to reproduce

```php
$mailer = new PHPMailer(true); // enable exceptions
// ...
$mailer->AddAttachment('/mnt/tmp/file-does-not-exist.pdf', 'xyz.pdf');
$mailer->send();
```

**Comment by Synchro** [comment]
This isn’t really what PHPMailer’s exceptions are for. `addAttachment` returns `false` if it fails for any reason, so check that instead.
