### ISSUE TITLE
Mailing with gmail account

### ISSUE THREAD

**Issue by dani160715** [PHPMailer/PHPMailer#1925]
I have a system that sends an email to a mailing list, the system is configured with phpmailer and the account is gmail.
My problem is that sometimes it sends me some emails correctly and suddenly it gives SMTP error.

This is the code:

```php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
$mail = new PHPMailer;
$mail->isSMTP();
$mail->SMTPDebug = SMTP::DEBUG_SERVER;
$mail->Host = 'smtp.gmail.com';
$mail->Port = 587;
$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
$mail->SMTPAuth = true;
$mail->Username = 'example@gmail.com';
$mail->Password = 'XXXXX';
$mail->setFrom('example@gmail.com');
$mail->Subject = 'Test';

while($row = mysqli_fetch_assoc($res))
{
    $email = $row['email'];

    $mail->AltBody = 'Example';

    $mail->addAddress($email);

    if (!$mail->send())
    {
        echo 'Mailer Error: '. $mail->ErrorInfo;
    } 
    else 
    {
        echo 'Message sent!';
    }
}
```

At first it does not work sending only 1 email, but after a while it worked, without changing any of the programming, then I tried to send the whole list and over 50 emails failed again.

I don't know why this happens

**Comment by Synchro** [comment]
What’s the error?

**Comment by dani160715** [comment]
My problem is that sometimes it sends me some emails correctly and suddenly it gives SMTP error.

**Comment by Synchro** [comment]
What error? Show the output with `SMTPDebug = 1`.

**Comment by adabsmith** [comment]
most times SMTPs get limits... try getting a SMTP with bigger limits

**Comment by Jamesvasanth21** [comment]
i get this error
Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in C:\inetpub\wwwroot\DD\phpmailer\PHPMailerAutoload.php on line 45.
Please help as soon as possible

**Comment by Synchro** [comment]
@Jamesvasanth21 you're using an old version; update. And search before you post. And please don't post random questions on unrelated threads.

**Comment by Jamesvasanth21** [comment]
i am using stable version 5.2 i am posting in this because i am also facing problem during gmail smtp process. i thought this was the tread for gmail errors.

**Comment by Synchro** [comment]
@dani160715 You're not clearing the recipient list inside your loop, so finding 50 recipients in your database will result in it sending 1,275 messages! That's probably why it's working to start with and then dying. Take a look at [the mailing list example provided](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps) for how to do it right, in particular the use of `clearAddresses()`.

**Comment by Synchro** [comment]
@Jamesvasanth21 [As the readme says](https://github.com/PHPMailer/PHPMailer#legacy-versions), 5.2 is no longer supported; use 6.x, and you don't have a gmail error, you have a PHP error. Use 6.x. There is no such thing as a "gmail thread" here, but if you **search before you post**, you would have found your question had been [asked and answered before](https://github.com/PHPMailer/PHPMailer/search?q=spl_autoload_register&type=Issues).
