### ISSUE TITLE
Oauth Save_mail function ?

### ISSUE THREAD

**Issue by haiderpro** [PHPMailer/PHPMailer#1927]
There is following function in normal Gmail sending code / example namely gmail.phps file which is very useful:
`function save_mail($mail)
{
    //You can change 'Sent Mail' to any other folder or tag
    $path = '{imap.gmail.com:993/imap/ssl}[Gmail]/Sent Mail';
    //Tell your server to open an IMAP connection using the same username and password as you used for SMTP
    $imapStream = imap_open($path, $mail->Username, $mail->Password);
    $result = imap_append($imapStream, $path, $mail->getSentMIMEMessage());
    imap_close($imapStream);
    return $result;
}`

I want to replicate this function for the code present in gmail_xoauth.phps so that I can do the same thing with Gmail oauth2 authentication when PHPMailer complete sending of email just like the code in gmail.phps file is doing. Is this possible ? Can you please provide the code or give a clue about how to do this at my own ?

Thank you very much in advance for your help / cooperation.

**Comment by Synchro** [comment]
Sorry, this is really outside PHPMailer’s scope.

That said, the docs provided for setting up OAuth for SMTP should work for IMAP too, but you will need to refer to gmail docs for more info. There is probably an IMAP package that can help - search packagist.
