### ISSUE TITLE
Problems connecting with host on AWS SES

### ISSUE THREAD

**Issue by envisiagroup** [PHPMailer/PHPMailer#1933]
Greetings! We're having an issue with our script. It seems to be timing out after a while and throws the following below:
`2020-01-03 16:16:57 SERVER -> CLIENT:
2020-01-03 16:16:57 SMTP ERROR: EHLO command failed:
2020-01-03 16:16:57 CLIENT -> SERVER: HELO www.domain.com
Warning: stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE. It is set to 1024, but you have descriptors numbered at least as high as 1358. --enable-fd-setsize=2048 is recommended, but you may want to set it to equal the maximum number of open files supported by your system, in order to avoid seeing this error again at a later date. in /vendor/phpmailer/phpmailer/src/SMTP.php on line 1169`

`2020-01-03 16:21:57 SERVER -> CLIENT:
2020-01-03 16:21:57 SMTP ERROR: HELO command failed:
2020-01-03 16:21:57 CLIENT -> SERVER: STARTTLS
Warning: stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE. It is set to 1024, but you have descriptors numbered at least as high as 1358. --enable-fd-setsize=2048 is recommended, but you may want to set it to equal the maximum number of open files supported by your system, in order to avoid seeing this error again at a later date. in /vendor/phpmailer/phpmailer/src/SMTP.php on line 1169`

`2020-01-03 16:26:57 SERVER -> CLIENT:
2020-01-03 16:26:57 SMTP ERROR: STARTTLS command failed:
SMTP Error: Could not connect to SMTP host.
2020-01-03 16:26:57 CLIENT -> SERVER: QUIT
Warning: stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE. It is set to 1024, but you have descriptors numbered at least as high as 1358. --enable-fd-setsize=2048 is recommended, but you may want to set it to equal the maximum number of open files supported by your system, in order to avoid seeing this error again at a later date. in /vendor/phpmailer/phpmailer/src/SMTP.php on line 1169`

`2020-01-03 16:31:57 SERVER -> CLIENT:
2020-01-03 16:31:57 SMTP ERROR: QUIT command failed:
SMTP Error: Could not connect to SMTP host.
Email not sent. SMTP Error: Could not connect to SMTP host.`

We are using AWS SES smtp to send emails.

Thanks

**Comment by XL-2000** [comment]
> Warning: stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE

Your problem is not with PHPMailer, but either with your hosting or other parts of scripts running outside / besides PHPMailer.

The description of the warning is pretty explainatory ;)

**Comment by Synchro** [comment]
Yep. This issue has also been covered here before, so please search before you post.

**Comment by envisiagroup** [comment]
That's fine and all, but it seems like the script requires a system modification and doesn't make it very portable or compatible with distributions that do not have this open file limit modification in place. We're using a standard Ubuntu 18.04 server installation with Apache and PHP FPM (PHP 7.2).

**Comment by Synchro** [comment]
It's not down to PHPMailer, it's down to how you're using PHP overall. PHPMailer consumes very few resources (it will typically try to use only 3-4 file descriptors), but if you have none available, there's nothing that any script can do to fix your system.
