### ISSUE TITLE
 Fatal error: Uncaught Error: Class 'SMTP' not found in C:\xampp\htdocs\btvenha\PHPMailer\class.phpmailer.php:1291 Stack trace: #0 C:\xampp\htdocs\btvenha\PHPMailer\class.phpmailer.php(1374): PHPMailer->getSMTPInstance() #1 C:\xampp\htdocs\btvenha\PHPMailer\class.phpmailer.php(1311): PHPMailer->smtpConnect(Array) #2 C:\xampp\htdocs\btvenha\PHPMailer\class.phpmailer.php(1156): PHPMailer->smtpSend('Date: Tue, 14 J...', 'Thank you\n') #3 C:\xampp\htdocs\btvenha\PHPMailer\class.phpmailer.php(1060): PHPMailer->postSend() #4 C:\xampp\htdocs\btvenha\mail.php(22): PHPMailer->send() #5 C:\xampp\htdocs\btvenha\dtb.php(52): sendMail('vnhi13580@gmail...', 'Thank you', 'VIET NAM') #6 {main} thrown in C:\xampp\htdocs\btvenha\PHPMailer\class.phpmailer.php on line 1291

### ISSUE THREAD

**Issue by nhivo24** [PHPMailer/PHPMailer#1940]
<?php
//require 'PHPMailer/PHPMailerAutoload.php';
require 'PHPMailer/class.phpmailer.php';
//require 'PHPMailer/class.smtp.php';
function sendMail($mailTo, $bodyContent, $mailSubject) {
$mail = new PHPMailer(); 
$mail->IsSMTP();
$mail->SMTPAuth = true; 
$mail->SMTPSecure = 'ssl'; 
$mail->Host = "smtp.gmail.com";
$mail->Port = 587;
//$mail->SMTPAutoTLS = false; 
$mail->IsHTML(true);
$mail->Username = "vothinhi2410@gmail.com";
$mail->Password = "";
$mail->SetFrom("vothinhi2410@gmail.com");
$mail->Subject =$mailSubject ;
$mail->Body = $bodyContent;
$mail->AddAddress($mailTo);
$mail->SMTPDebug = 1;
if(!$mail->Send()) {
echo "Mailer Error: " . $mail->ErrorInfo;
} else {
}
}
?>

**Comment by DiemenDesign** [comment]
If I pasted all that in a title in an issue, I would expect the issue to be simply deleted and ignored.

**Comment by Synchro** [comment]
Quite!

@nhivo24 Please read the readme on [how to load PHPMailer](https://github.com/PHPMailer/PHPMailer#installation--loading), and update to the latest version; you're using a very old one.
