### ISSUE TITLE
Not sending to non traditional TLD's

### ISSUE THREAD

**Issue by DiemenDesign** [PHPMailer/PHPMailer#1941]
# Problem description
Not able to send to newer domains, such as .design or .farm, but works fine with traditional domains such as .com, .net and so on. There's no errors that I can find anywhere, and I couldn't find similar issues, unless I'm using the wrong wording. I'm hoping there's a simple fix like a switch to allow all. I am using the latest version, downloaded and test with the last hour.

# Code to reproduce
My code works fine to traditional domains, so it's not a script error.

# Debug output
There's no output that I could find, the mail just never arrives.

**Comment by Synchro** [comment]
Without specific examples or debug output, I can't reproduce this; enable debug output by setting `SMTPDebug = 2` to show the SMTP transcript. PHPMailer uses PHP's default email validator, and that has no problem with addresses like `user@site.design`.

**Comment by DiemenDesign** [comment]
Ah, I should go through more of phpmailers docs, didn't know about that settings. Thanks.

**Comment by DiemenDesign** [comment]
After a little faffing around, I discovered, sending from my localhost development system the emails don't get through and I'm still not seeing errors. Sending from my website contact form which uses phpmailer to the domains (https://diemen.design/) works fine, so it must be something with my development box, which is strange that traditional TLD's work fine, just not the new extensions.

**Comment by Synchro** [comment]
Like I said, use SMTP and look at the debug output. If the messages are accepted by your local mail server but you're still not receiving them, then any problems with onward delivery will appear in your mail server's logs.

**Comment by DiemenDesign** [comment]
Thanks for the heads up.

**Comment by DiemenDesign** [comment]
I found that issue, using my domains email on my localhost machine for testing, the server blocks outside instances from connecting. If I use another service that doesn't block connecting from outside of it's own localhost then sending to any domain TLD works without issue. Thanks for your help @Synchro
