### ISSUE TITLE
Message could not be sent. Mailer Error: SMTP Error: Could not authenticate.

### ISSUE THREAD

**Issue by TelvioSheldon** [PHPMailer/PHPMailer#1943]
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'vendor/autoload.php';

$mail = new PHPMailer(true);

try {
    $mail->SMTPDebug = 2;
    $mail->isSMTP();
    $mail->Host       = 'mail.wtb.co.mz';
    $mail->SMTPAuth   = true;
    $mail->Username   = 'xxxxxxxx';
    $mail->Password   = 'xxxxxxxxxx';
    $mail->SMTPSecure = 'tsl';
    $mail->Port       = 465;
    $mail->setFrom(xxxx'); //same as username
![w](https://user-images.githubusercontent.com/57064616/72619381-c93d8400-3945-11ea-99ca-df722ac91994.png)

    $mail->addAddress('crackeddcode20@gmail.com');
    $mail->isHTML(true);
    $mail->Subject = 'Subject';
    $mail->Body    = 'HTML message body in <b>bold</b> ';
    $mail->AltBody = 'Body in plain text for non-HTML mail clients';
    $mail->send();

    echo "Mail has been sent successfully!";
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}
![w](https://user-images.githubusercontent.com/57064616/72619274-985d4f00-3945-11ea-8e9a-8b5024e2877b.png)

**Comment by TelvioSheldon** [comment]
Can you help me with this bug?
My password, host and username matches the ones from the server

**Comment by XL-2000** [comment]
> $mail->SMTPSecure = 'tsl';

should be **'tls'**

Also check your port, this is hosting specific, and yours might be correct, but 587 is often used as it is somewhat the default, so check it also

**Comment by TelvioSheldon** [comment]
### I get this error whenever I change my port to 587
2020-01-17 17:35:28 SERVER -> CLIENT: 220-srv2.mozdomains.com ESMTP Exim 4.92 #2 Fri, 17 Jan 2020 19:34:00 +0200 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail.
2020-01-17 17:35:28 CLIENT -> SERVER: EHLO localhost
2020-01-17 17:35:28 SERVER -> CLIENT: 250-srv2.mozdomains.com Hello localhost [197.218.64.233]250-SIZE 52428800250-8BITMIME250-PIPELINING250-AUTH PLAIN LOGIN250-STARTTLS250 HELP
2020-01-17 17:35:28 CLIENT -> SERVER: STARTTLS
2020-01-17 17:35:28 SERVER -> CLIENT: 220 TLS go ahead
SMTP Error: Could not connect to SMTP host.
2020-01-17 17:35:29 CLIENT -> SERVER: QUIT
2020-01-17 17:35:29 SERVER -> CLIENT:
2020-01-17 17:35:29 SMTP ERROR: QUIT command failed:
SMTP Error: Could not connect to SMTP host.
Message could not be sent. Mailer Error: SMTP Error: Could not connect to SMTP host.

**Comment by XL-2000** [comment]
OK, so stick to the old port you used, and use 'tls' you should be fine

**Comment by Synchro** [comment]
All this is covered in [the docs that your error message pointed you at](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#using-encryption). Your script is failing immediately after `STARTTLS`, which the docs cover [here](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#certificate-verification-failure).
