### ISSUE TITLE
6.1.4 is adding ?us-ascii? to the subject field

### ISSUE THREAD

**Issue by ramblerswebs** [PHPMailer/PHPMailer#1949]
#Problem description
  I don't know if this is a bug or not, I have just upgraded to 6.1.4 from 6.0.2
  All works fine until I look at the emails I receive
  All is fine until I look at the header and the subject field

Instead of the subject line in the header looking like - 
Subject: WebMonitor: ramblers-webs.org.uk  Change Report (1106)
It looks like -
```
Subject: =?us-ascii?Q?WebMonitor:_ramblers-webs.org.uk__Change_Report?=  =?us-ascii?Q?_(7)?= 
```
This would not matter except I scan these emails and this code does not look for 
`?us-ascii?Q?WebMonitor` just WebMonitor

The question/bug is: should the encoding be in the subject field or not.
I use the default encoding settings and only use normal alpha numeric chars plus special chars like ( ):-

# Code to reproduce
The code sending the emails is at https://github.com/ramblerswebs/webmonitor/blob/master/hashscan.php
If this is a bug I can try to set up a stand alone code for you.

Any help gratefully received.

**Comment by ramblerswebs** [comment]
I have done some work on this and find that it depends on the length of the subject text .
The code below produces a header with the encoding specified for the subject.

So a subject ="WebMonitor: ramblers-webs.org.uk  Change Report (2)"
produces a header of 
Subject: =?us-ascii?Q?WebMonitor:_ramblers-webs.org.uk__Change_Report?=  =?us-ascii?Q?_(2)?=
If I change the subject to
subject = "Test email: derbyramblers.org.uk" 
then the header looks like
Subject: Test email: derbyramblers.org.uk

Am I missing something as I don't see any logic as to why it does this.

Any help gratefully received.

Code
<?php

$domain = "derbyramblers.org.uk ";
require 'classes/phpmailer/src/PHPMailer.php';
require 'classes/phpmailer/src/SMTP.php';
require 'classes/phpmailer/src/Exception.php';
date_default_timezone_set('Europe/London');

//Create a new PHPMailer instance
$mailer = new PHPMailer\PHPMailer\PHPMailer;

$mailer->setFrom("admin@" . $domain, $domain);
$mailer->addReplyTo("sitestatus@" . $domain, $domain);
$email = ["chris@cevsystems.co.uk", "admin@ramblers-webs.org.uk"];
if (is_array($email)) {
    foreach ($email as $value) {
        $mailer->addAddress($value, 'Web Master');
    }
} else {
    $mailer->addAddress($email, 'Web Master');
}
$mailer->isHTML(true);
$mailer->Subject = "WebMonitor: ramblers-webs.org.uk  Change Report (2)" ;
$mailer->msgHTML("<p><small>You are receiving this email because we believe you are one of the web masters for this domain.</small></p>
<p><small>If this is not correct or you are changing your email address or a new web master is taking over, then please raise a support ticket</small></p>
<p><small><a href='mailto:support@ramblers-websites.zendesk.com?Subject=ramblers-webs.org.uk' target='_blank'>support@ramblers-websites.zendesk.com</a></small></p><hr/>
<p>Report of changes to domain <b>ramblers-webs.org.uk</b></p>
<p>Scanning directory - /home/sites/3a/a/a2d7cbf275 and its sub directories</p>
<p>Excluding the following directories</p><ul>
<li>public_html/backups01/data/</li>
<li>public_html/www*/tmp/</li>
<li>public_html/www*/logs/</li>
<li>public_html/www*/administrator/logs/</li>
<li>public_html/www*/cache/</li>
<li>public_html/www*/media/plg_jchoptimize/cache/</li>
<li>public_html/www*/administrator/cache/</li>
<li>public_html/www*/administrator/components/com_akeeba/backup/</li>
<li>public_html/maphelp*/tmp/</li>
<li>public_html/maphelp*/logs/</li>
<li>public_html/maphelp*/administrator/logs/</li>
<li>public_html/maphelp*/cache/</li>
<li>public_html/maphelp*/media/plg_jchoptimize/cache/</li>
<li>public_html/maphelp*/administrator/cache/</li>
<li>public_html/maphelp*/administrator/components/com_akeeba/backup/</li>
</ul>
<p>File types being ignored</p><ul><li>
log</li></ul>
<p>Last tested 2020-01-23 01:36:28</p>
<p>Last email sent 2020-01-23 01:36:28.</p>
<p>Total number of files scanned 41408</p>
<p>Total size of files: 331,485,092 bytes</p>
<p> </p>
<p>File structure has changed:-</p><ul>
<li>     NEW files:0</li>
<li>     CHANGED files:2</li>
<li>     DELETED files:0</li></ul>
<p> </p>
<p>PLEASE review the changes, if you expected these changes then ignore this email</p>
<p>This email should also go to Administrators who may also review the changes</p>
<p>If you have any concerns that your site has been hacked then please raise a Support Issue</p>
<p> </p>
<p>     CHANGED files</p>
<ul>
    <li>public_html/backups01/classes/email.php</li>
    <li>public_html/backups01/classes/functions.php</li>
</ul>
<p> </p>
<p> </p>
<p>PHP version: 7.3.13  Web Monitor version: 5.4.4</p>
<p>---------------------------------</p>");

if (!$mailer->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mailer->ErrorInfo;
} else {
    echo'Message has been sent';
}

**Comment by Synchro** [comment]
What you're seeing is RFC2047 encoding. The encoding should be transparent, in that it should only be visible when you view the source of a message, not when it's rendered in an email client. This gets applied to long lines especially when using the PHP `mail()` function, because it can corrupt headers over 65 characters long. If you switch to sending via SMTP to localhost (just add a call to `$mailer->isSMTP()`), it can use a much longer limit (and is also faster and safer).

**Comment by f-liva** [comment]
This anomaly still occurs. Check these cases:

Using subject **IMA - GATTINONI TRAVEL NETWORK : Intestazione** (45 chars) everything works fine.

`Subject: IMA - GATTINONI TRAVEL NETWORK : Intestazione`

Using subject **IMA - GATTINONI TRAVEL NETWORK : Intestazione file** (50 chars) it breaks (empty subject).

`Subject: =?us-ascii?Q?IMA_-_GATTINONI_TRAVEL_NETWORK_:_Intestazione_f?=  =?us-ascii?Q?ile?=`

Why this happens? How to avoid the break?

**Comment by Synchro** [comment]
See my previous answer. The encoding is valid, but it seems some clients don't understand it. You should be able to work around it by switching to SMTP to localhost.

**Comment by f-liva** [comment]
I'm on SMTP.

Any way to restore the old behavior for this thing?

**Comment by Synchro** [comment]
No. It's there because the old behaviour was broken by the bugs in the mail function. SMTP won't do this until your subject is 900+ chars, so I don't believe you're using it.

**Comment by unix-dude** [comment]
Just use SMTP, really? Bit overkill for my liking. RFC5321 explicitly specifies CRLF as the line terminator and PHPMailer will allow you to send non RFC compliant messages apparently (It's a feature, not a bug!). 

You can work around this by setting this in your php.ini:

sendmail_path = '/usr/bin/dos2unix -u|/usr/sbin/sendmail -t -i'

dos2unix will make the message RFC5321 compliant by dealing with any incorrect line terminators.

Make sure you have the package installed the provides the dos2unix binary, it's normally called dos2unix or unix2dos.

**Comment by Synchro** [comment]
> Just use SMTP, really? Bit overkill for my liking. RFC5321 explicitly specifies CRLF as the line terminator and PHPMailer will allow you to send non RFC compliant messages apparently (It's a feature, not a bug!).

As I said, this is a PHP and Linux problem that PHPMailer has to cope with, not a PHPMailer problem. If you send mail with CRLF breaks to a linux sendmail client that doesn't expect it (what you're asking for), it will fail or make a mess. You can use additional tools to deal with that (as you suggest), but getting people to understand why they are needed, or figure out how to get root privs to install packages on their shared server are a whole load more difficult than just making PHPMailer deal with it, as it does.

And as I said, it's also faster and safer.
