### ISSUE TITLE
upgrading PHPMailer from old version ?

### ISSUE THREAD

**Issue by Keorl** [PHPMailer/PHPMailer#1950]
Hi,
I have an old php5.3 project with a 2014 version of PHPMailer.
It simply has a PHPMailer folder with 4 simple php files (class.phpmailer, class.pop3, class.smtp and PHPMailerAutoload).
I need to upgrade the project to work in php7.3, so I'm also upgrading libraries.
Here are my 2 questions
1) I see that newer version of PHPMailer relies on a thing called composer, to make things more complicated than they should be. Is there any way to make it work like my current version, by just having a few php files in a lib directory and using a require ? I was hoping to just replace my lib/phpmailer folder content like I already did successfully with several other libraries. Maybe if I just take the content of the "src" folder of version 6.1.4 (I see 5 php files) and require them all in a new PHPMailerAutoload.php ?

2) I know I should check the changelog but I'm 5 years behind so finding the breaking changes would be a pain. Is there any breaking changes over this period ? Btw, my project only uses a few functions of phpmail : new PHPMailer, setting charset/from/fromanem/addreplyto/addaddress/ishtml/subject/addembeddedimage/msghtml, and send().

thanks :)

**Comment by nightw0lv** [comment]
there is a guide on main page.
you can still download the files and use the src path to include those 3 files and use it (examples are on main page again), composer is very much the best solution for me so far... easy to keep updated my project and manage all my includes into one line it worth to make a research about it and use it.

**Comment by Synchro** [comment]
This is an incredibly lazy question. All you ask is answered in the readme, with further details in the upgrading guide, at the top level of the repo.
