### ISSUE TITLE
internal server error and set_ini doesn't help

### ISSUE THREAD

**Issue by Amosss** [PHPMailer/PHPMailer#1951]
Hi

I'm trying to use phpmailer with outlook's smtp and I keep getting internal server error.
I added `ini_set('display_errors', '1');` but then I get a "success message" from the process even though the email was not sent.

I downloaded the phpmailer folder and used the following code
```
<?php
ini_set('display_errors', '1'); <<<< adding this -> success message, nothing sent, removing this, internal server error
use phpmailer\PHPMailer;
use phpmailer\Exception;

require 'phpmailer/Exception.php';
require 'phpmailer/PHPMailer.php';
require 'phpmailer/SMTP.php';

// Check for empty fields
if(empty($_POST['name'])  		||
   empty($_POST['email']) 		||
   empty($_POST['message'])	||
   !filter_var($_POST['email'],FILTER_VALIDATE_EMAIL))
   {
	echo "No arguments Provided!";
	return false;
   }
	
$name = $_POST['name'];
$email_address = $_POST['email'];
$message = $_POST['message'];
	
// Create the email and send the message
$to = '***'; 
$email_subject = 'Website Contact Form:  $name';
$email_body = '***';
$headers = 'From: $email_address\n'; 
$headers .= 'Reply-To: $email_address\n';
$headers .= 'Subject: $email_subject';	

$mail = new PHPMailer(true);
$mail->IsSMTP();
$mail->CharSet = 'UTF-8';
$mail->Host = 'smtp.live.com';
$mail->SMTPAuth= true;
$mail->Port = 587;
$mail->Username= '***';
$mail->Password= '***';
$mail->SMTPSecure = 'tls';
$mail->From = $email_address;
$mail->FromName= $name;
$mail->isHTML(true);
$mail->Subject = $email_subject;
$mail->Body = $email_body;
$mail->addAddress($to);
$mail->send();
return true;			
?>
```

What am I missing?
Thanks

**Comment by Synchro** [comment]
Two things: Your import of namespaced classes (the `use` statements) is incorrect, and will not match the namespace actually used by the PHPMailer classes. Secondly, you have no error checking at all, so not surprisingly you won't know when errors occur. Rather than pointing out what's wrong here, it will be far quicker if you start again by adapting one of the examples provided, which does not make these mistakes.

**Comment by Amosss** [comment]
The above was taken from here
```
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'path/to/PHPMailer/src/Exception.php';
require 'path/to/PHPMailer/src/PHPMailer.php';
require 'path/to/PHPMailer/src/SMTP.php';
```

and was adapted to my need but the fact I don't see what the error is, prevents me from understanding what am I doing wrong. You wrote "you have no error checking at all, so not surprisingly you won't know when errors occur." - what do you mean by that? I was hoping that once something fails, the set_ini will tell me what failed, it doesn't.

**Comment by Synchro** [comment]
You may have taken it from there, but you changed it to values that won't work. Namespace imports are nothing to do with paths. Changing this:

    use PHPMailer\PHPMailer\PHPMailer;

to

    use phpmailer\PHPMailer;

will simply break, causing an undefined class error when you try to create an instance of PHPMailer. Don't do that!

You have set PHPMailer to throw exceptions on error (by passing `true` to the constructor), but you have not wrapped it in a try/catch block, and you're not displaying any error values, so all you'll get is an uncaught exception error. However, it will never get that far because of the crash caused by the earlier namespace problem.

Really, start again with the example from the readme, or one of the others.

**Comment by Amosss** [comment]
I changed it to 
```
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
```
now it takes a bit more time and then throws the internal server error.

**Comment by Amosss** [comment]
I'm calling it through js so I was hoping the error clause will catch it
```
            $.ajax({
                url: "././mail/contact_me.php",
                type: "POST",
                data: {
                    name: name,
                    email: email,
                    message: message
                },
                cache: false,
                success: function() {
                    // Success message
                    $('#success').html("<div class='alert alert-success'>");
                    $('#success > .alert-success').html("<button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;")
                        .append("</button>");
                    $('#success > .alert-success')
                        .append("<strong>Your message has been sent. </strong>");
                    $('#success > .alert-success')
                        .append('</div>');

                    //clear all fields
                    $('#contactForm').trigger("reset");
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    // Fail message
                    $('#success').html("<div class='alert alert-danger'>");
                    $('#success > .alert-danger').html("<button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;")
                        .append("</button>");
                    $('#success > .alert-danger').append("<strong>Sorry " + firstName + ", there was an error: " + textStatus + ": " + errorThrown + ". Please try again later!");
                    $('#success > .alert-danger').append('</div>');
                    //clear all fields
                    $('#contactForm').trigger("reset");
                },

```
but it catches "internal server error"
Also I tried
```
if(!$mail->Send()) {
  echo "Mailer Error: " . $mail->ErrorInfo;
} else {
  echo "Message sent!";
}
```
but nothing

**Comment by Synchro** [comment]
Don't mix your error handling approaches. You're asking it to throw exceptions, then checking the return value in that if statement - but that will never get a chance to output the error message because of the exception thrown within `send`, and you'll be left with an uncaught exception.

Do you see why I suggested starting again? All the examples do this right!

**Comment by Amosss** [comment]
That were 2 different tries.

At first I didn't have try catch because I thought js will catch it, but it didn't.
So I went with your approach of if(!$mail->Send()) ... but still nothing...
I'm not mixing anything, I try each approach separately but no matter what I do, I get internal server error instead of the error itself.

**Comment by Synchro** [comment]
You can't catch exceptions across languages! You can't throw an exception in PHP and catch it in JS! Do **ONE** of the following:

* Enable exceptions by passing `true` to the constructor, then wrap your code in a try/catch block.
* Do not enable exceptions, and instead check the return value from the `send()` method.

To trigger jQuery's error response, you should get your script to return an appropriate HTTP response code, such as 400, if sending fails, and include the `ErrorInfo` value in the response so that you can see what the problem is.

Otherwise, if you ever see an "internal error" response, the error messages will be in your web server's error log.

**Comment by Amosss** [comment]
Well, I tried both, separately.

Even though I removed `ini_set('display_errors', '1');` both trials gave back "success" even though the email was not sent.

 I checked my server's log, nothing appears there.

My question is what is the problem with my code? Why do I have an error in the first place?

**Comment by Synchro** [comment]
Debug your PHP separately from your javascript; it just makes it hard to see what's going on otherwise. For example, as it stands you can't tell if the message was not sent or not received - they are quite separate things. Make it work in PHP by itself to start with, then connect it to your JS.

Your code has numerous basic errors in, many of which I've pointed out, and you could have avoided all of this simply by doing what I said to start with and starting again with a known-good example that is free of these problems. Correcting every little mistake is a waste of time when a better starting point is available.

**Comment by Amosss** [comment]
You stumbled into an open door :) I already did that

<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'phpmailer/Exception.php';
require 'phpmailer/PHPMailer.php';
require 'phpmailer/SMTP.php';

$mail = new PHPMailer();
$mail->IsSMTP();
$mail->CharSet = 'UTF-8';
$mail->Host = 'smtp.live.com';
$mail->SMTPAuth= true;
$mail->Port = 587;
$mail->Username= '***';
$mail->Password= '***';
$mail->SMTPSecure = 'tls';
$mail->From = $_POST['email'];
$mail->FromName= $_POST['name'];
$mail->isHTML(true);
$mail->Subject = 'Website Contact Form:  $name';
$mail->Body = '***';
$mail->addAddress('***');
$mail->Send();
return true;			
?>

I received "success" but the message was not sent.
I know it was not sent because I don't see it in sent items folder of the account from which I sent such emails (like I do see the email sent from Java).

**Comment by Amosss** [comment]
ok
`$mail = new PHPMailer(true);` -> throws error (no try catch) internal server error
`$mail = new PHPMailer();` -> does not throw error but also does not send.

It looks like something bad is happening inside phpmailer itself or by me passing one of the paramters above.

**Comment by Amosss** [comment]
Found it by debugging inside the js itself in the browser... problem is with the login information I sent, Thanks

**Comment by Amosss** [comment]
Funny, I did the following
```
$mail = new PHPMailer();
$mail->IsSMTP();
$mail->CharSet = 'UTF-8';
$mail->Host = 'smtp.live.com';
$mail->SMTPAuth= true;
$mail->Port = 587;
$mail->Username= '***';
$mail->Password= '***';
$mail->SMTPSecure = 'tls';
$mail->addReplyTo($_POST['email']);
$mail->From = '***';
$mail->FromName= $_POST['name'];
$mail->isHTML(true);
$mail->Subject = 'Website Contact Form: '.$_POST['name'];
$mail->Body = '***';
$mail->addAddress(***);
try{
if (!$mail->Send()) echo json_encode('error:'.$mail->ErrorInfo); << the below came from here
else echo json_encode('blah');
} catch (phpmailerException $e) {
  echo $e->errorMessage(); //Pretty error messages from PHPMailer
} catch (Exception $e) {
  echo $e->getMessage(); //Boring error messages from anything else!
}

```
and got the following eror
`\"error:SMTP connect() failed. https:\\/\\/github.com\\/PHPMailer\\/PHPMailer\\/wiki\\/Troubleshooting\""`

Why does it want to connect to this repo?

**Comment by Amosss** [comment]
After changing some things, for example `$mail->SMTPSecure = 'tls';` to come right after `$mail->SMTPAuth= true;` the response looks good.

Until then I received exceptions (see below) as expected. Once I fixed the above and some other things, I started receiving success1 (see below) as expected... but... the email is not sent.

```
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\EXCEPTION;

require 'phpmailer/PHPMailer.php';
require 'phpmailer/SMTP.php';
require 'phpmailer/Exception.php';

$mail = new PHPMailer(true);
$mail->CharSet = 'UTF-8';
$mail->Username= '***';
$mail->Password= '***';
$mail->From = '***';
$mail->AddReplyTo($_POST['email'],$_POST['name']);
$mail->isHTML(true);
$mail->Subject = 'Website Contact Form: '.$_POST['name'];
$mail->Body = '***';
$mail->addAddress(***);

$mail->Host = 'smtp.live.com';
$mail->Port = 587;
$mail->SMTPAuth= true;
$mail->SMTPSecure = 'tls';

try{
if (!$mail->Send()) echo json_encode('send1:'.$mail->ErrorInfo);
else echo json_encode('success1');
} catch (phpmailerException $e) {
  echo 'phpmail except1: '.$e->errorMessage(); 
} catch (Exception $e) {
  echo 'exception1: '.$e->getMessage(); 
}
?>
```

As long as I got exceptions, it was expected that I won't get the email but now everything seems intact and still nothing... what am I missing?

**Comment by Synchro** [comment]
You're making the same mistakes again, mixing up your error handling. All you need to do is exactly what I said at the start - go back to one of the provided examples and insert your settings. I can't really help you if you persist in making the same mistakes over and over again, going against the advice you're being given.

> I know it was not sent because I don't see it in sent items folder of the account from which I sent such emails (like I do see the email sent from Java).

This is not true. Whether messages appear in your sent folder is completely separate from whether they were sent or not. Some servers will automatically place a copy in your sent folder, but many do not and require you to put it there as a separate operation - gmail is one example of a service that acts that way, as you can see in the gmail script example provided with PHPMailer.

If your script is getting to the "success1" point, your message is being submitted successfully to the mail server - you can watch it in action by setting `$mail->SMTPDebug = 2`. That still doesn't not mean that it will arrive - though don't forget to check your spam folder.

**Comment by Amosss** [comment]
I have a similar code in Java (using javax) sitting in the same server (vps), using the same settings and I do see the email in the sent items and I do receive the email (not in spam).

It was "by accident" that I stumbled upon a post saying that `$mail->SMTPSecure = 'tls';` must come directly after `$mail->SMTPAuth= true;` . I saw it nowhere else. Only then, I got "success1" response from my code. I was hoping that it will be enough but apparently, something else is happening behind the scenes.

If it wouldn't have worked from my Java code, I'd say something is wrong with the server but it doesn't work ONLY with the php code, thus I wonder what can be wrong here.

**Comment by Synchro** [comment]
No, it does not make any difference what order you set those properties in. If you don't do what I suggest, then I can't help you.

**Comment by Amosss** [comment]
But I did what you suggestes, I started from scratch, fixed all the errors, went line by line to see what was causing those "internal server errors" until I disposed them all and received "success".

Tell me how am I not following your suggestion?

**Comment by Synchro** [comment]
Because you have *not* started again using an example - you've got a bunch of mistakes that are not in the examples. The last code you posted has nonsensical error handling that includes chunks of code from a very old version of PHPMailer, plus random changes like `use PHPMailer\PHPMailer\EXCEPTION;` - PHP is case sensitive in some places!

Try this, adapted from the example in the readme (insert your own settings):

```php
<?php
// Import PHPMailer classes into the global namespace
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\SMTP;

require 'phpmailer/PHPMailer.php';
require 'phpmailer/SMTP.php';
require 'phpmailer/Exception.php';

// Instantiation and passing `true` enables exceptions
$mail = new PHPMailer(true);

try {
    //Server settings
    $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      // Enable verbose debug output
    $mail->isSMTP();                                            // Send using SMTP
    $mail->Host       = 'smtp.live.com';                    // Set the SMTP server to send through
    $mail->SMTPAuth   = true;                                   // Enable SMTP authentication
    $mail->Username   = '***';                     // SMTP username
    $mail->Password   = '***';                               // SMTP password
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS; 
    $mail->Port       = 587;                                    // TCP port to connect to

    //Recipients
    $mail->addReplyTo($_POST['email'], $_POST['name']);
    $mail->addAddress(***);

    // Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = 'Website Contact Form: '.$_POST['name'];
    $mail->Body    = '***';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    $mail->send();
    echo 'Message has been sent';
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}
```

Don't try testing that via JS, just test the PHP by itself. This should display debug output of the SMTP transcript.

**Comment by Amosss** [comment]
Works,
```
use PHPMailer\PHPMailer\SMTP;
$mail->isSMTP(); 
```
were missing... they were removed as part of my add/remove lines to check what is causing the error... once I got no error, I thought it is not needed. Thanks and sorry for the troubles.
