### ISSUE TITLE
PHPMailer creates html with Content-ID references that many MUAs don't recognize.

### ISSUE THREAD

**Issue by msapiro** [PHPMailer/PHPMailer#1955]
# Problem description
PHPMailer creates an HTML message with embedded image references like

<img src="cid:85d06102a59862e3af98226ebaacf7dfcc86f20a2dd9b31c125b8b9dab559b1c@phpmailer.0" ...
# Code to reproduce
```
<?php
$mail = new PHPMailer();
$mail->isSendmail();  // use system MTA
$mail->XMailer = 'GPC BearMail'; // default is phpMailer version
$mail->msgHTML($body,$prependDir);

$body is html with an img tag referencing a file in $prependDir
```
# Debug output

The cid is generated at https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L4001 using a sha256 hash. Then /https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L3073 makes the Content-ID header in the MIME part containing the image and in doing so calls encodeHeader which determines that the header is long enough to require RFC 2047 encoding and folding. This RFC 2047 encoded header value is not matched with the cid reference by many MUAs including Mozilla Thunderbird, AOL web mail, Hotmail web mail and Comcast web mail.

It is really the MUAs that are at fault, not PHPMailer, but given their numbers and that fact that they probably won't be fixed soon, I think changing https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L4001 to use a shorter sha1 hash to avoid the issue is appropriate.

**Comment by msapiro** [comment]
Sorry for the noise. I was basing this on 6.1.1. I upgraded to 6.1.4 and the issue is fixed there.

**Comment by Synchro** [comment]
Ok. BTW, I recommend *not* using `isSendmail()`. All it does is open a synchronous SMTP connection to localhost, but it’s slower and less safe than using SMTP from PHPMailer directly.

**Comment by msapiro** [comment]
@Synchro Thank you for the suggestion, but if I understand correctly, doing direct SMTP from PHPMailer would bypass the local MTA which does things like DKIM sign the mail, and that would be undesirable.

**Comment by Synchro** [comment]
No, it wouldn't bypass it at all. If you call `isSMTP()` and don't change any other settings, it submits to localhost on port 25 with no auth and no encryption (that can't work to localhost anyway), which is exactly what both sendmail and the PHP mail() function do, just less efficiently. If your local mail server is set up to do DKIM signing, then this should work just fine.

**Comment by msapiro** [comment]
@Synchro Thank you for the clarification. Your input is much appreciated.
