### ISSUE TITLE
Connection failed. Error #2

### ISSUE THREAD

**Issue by KobeNorris** [PHPMailer/PHPMailer#1956]
Hi ! I have looked through the similar issues and trouble shooting guideline but still cannot solve this problem. 

I am testing my code on XAMPP on a windows labtop:

Error message:
-----
2020-02-02 17:52:04 Connection: opening to smtp.163.com:587, timeout=300, options=array()

2020-02-02 17:53:49 Connection failed. Error #2: stream_socket_client(): unable to connect to smtp.163.com:587 (FAILED TO CONNECT TO SERVER: A CONNECTION ATTEMPT FAILED BECAUSE THE CONNECTED PARTY DID NOT PROPERLY RESPOND AFTER A PERIOD OF TIME, OR ESTABLISHED CONNECTION FAILED BECAUSE CONNECTED HOST HAS FAILED TO RESPOND) [C:\xampp\htdocs\team35_project\vendor\phpmailer\phpmailer\src\SMTP.php line 344]

2020-02-02 17:53:49 SMTP ERROR: Failed to connect to server: FAILED TO CONNECT TO SERVER: A CONNECTION ATTEMPT FAILED BECAUSE THE CONNECTED PARTY DID NOT PROPERLY RESPOND AFTER A PERIOD OF TIME, OR ESTABLISHED CONNECTION FAILED BECAUSE CONNECTED HOST HAS FAILED TO RESPOND. (10060)

SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
MAIL HAS BEEN SENT SUCCESSFULLY

**Comment by KobeNorris** [comment]
This is the templated I have followed, just replaced the email addresses and password

Template
----
<?php

require "../../vendor/autoload.php";

$robo = 'myEmail@163.com';

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;


$developmentMode = false;
$mailer = new PHPMailer($developmentMode);

try {
    $mailer->SMTPDebug = 3;

    $mailer->isSMTP();

    if ($developmentMode) {
    $mailer->SMTPOptions = [
        'ssl'=> [
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
        ]
    ];
    }


    $mailer->Host = 'smtp.163.com';
    $mailer->SMTPAuth = true;
    $mailer->Username = 'myEmail@163.com';
    $mailer->Password = 'password';
    $mailer->SMTPSecure = 'tls'; //'tls'
    // $mailer->SMTPAutoTLS = false;
    $mailer->Port = 587; //587, 465, 25, 2525 have been tested

    $mailer->setFrom('myEmail@163.com', 'Sender');
    $mailer->addAddress('yourEmail@gmail.com', 'Recipient');

    //Content
    $mailer->isHTML(true); // Set email format to HTML
    $mailer->Subject = 'Here is the subject';
    $mailer->Body = 'This is the HTML message body <b>in bold!</b>';
    $mailer->AltBody = 'This is the body in plain text for non-HTML mail clients';

    $mailer->send();
    // $mailer->ClearAllRecipients();
    echo "MAIL HAS BEEN SENT SUCCESSFULLY";

} catch (Exception $e) {
    echo "EMAIL SENDING FAILED. INFO: " . $mailer->ErrorInfo;
}

**Comment by NiklasBr** [comment]
> FAILED TO CONNECT TO SERVER

Your local server (XAMPP) cannot reach the server smtp.163.com (or it is not responding on that address/port). Make sure you have configured your development environment to properly allow connections to the external internet and make sure it can resolve DNS.

Also, see [this page](http://help.163.com/09/1223/14/5R7P3QI100753VB8.html) for settings.

**Comment by KobeNorris** [comment]
Thank you sir, I will check it out.

**Comment by Fiwi1265** [comment]
Have you tried putting this on?
`require 'dir/PHPMailer.php';`
`require 'dir/Exception.php';`
`require 'dir/SMTP.php';`
