### ISSUE TITLE
List of possible error codes?

### ISSUE THREAD

**Issue by hagenbuch** [PHPMailer/PHPMailer#1957]
After trying to find a list of possible return codes that are not 0 from PHPMailer, I have to ask this question: 

Is there a list somewhere, containing all or at least the most common error codes?

I don't need translations, I'll have to provide that myself.

BTW I'd be happy to translate those error codes into German right away if this list exists.

Cheers
Andreas

**Comment by Synchro** [comment]
There isn't such a list - I think what you're asking for is what's discussed in #1579, which has been open for a while. There are numerous error *messages* that are codified and mapped into the translations available in [the language folder](https://github.com/PHPMailer/PHPMailer/tree/master/language). Does that help?

**Comment by hagenbuch** [comment]
Definitely, many thanks! I hope I can find the numeric definitions of the variable indices.. e.g. what message is mapped to which returncode.

**Comment by Synchro** [comment]
There are no numeric ones, but if you search for all occurrences of `lang(`, you'll see all the places that errors are thrown or saved, so for example authentication errors will have an identifier of `authenticate`, connection errors use `connect_host`, and so on - all the array keys you'll see in the language files.

**Comment by hagenbuch** [comment]
Great, thanks!
