### ISSUE TITLE
PHPMailer version 6

### ISSUE THREAD

**Issue by lap666** [PHPMailer/PHPMailer#1958]
Hi,

When I use version 6 I can't embedded the pictures in the mail message.
To have the picture in an attachment is not a problem.

```php
$mail->isHTML(true);         
$mail->AddEmbeddedImage("pictures/mail.jpg","testImage","test.jpg");	
$mailer="This is a message.";
$mailer.='<img src="cid:testImage">'; // or <img src=\'cid:testImage\'>'
$mail->Body=$mailer; 
```
The mail is send with a broken link.
What do i wrong ??

In version 5.1 no problem

Kind regards,

**Comment by Synchro** [comment]
Does the call to `addEmbeddedImage()` return `true`?

**Comment by lap666** [comment]
Hi,

How can I find out of the `addEmbeddedImage()` return `true`.
When I use  `$mail->SMTPDebug = 2; ` there is no message.

Kind regards,

**Comment by Synchro** [comment]
var_dump($mail->AddEmbeddedImage("pictures/mail.jpg","testImage","test.jpg"));

**Comment by lap666** [comment]
Hi,

bool(false)

Kind regards,

**Comment by Synchro** [comment]
OK, that tells you that it's not working because PHPMailer can't read your file, either because you have the wrong path, the file doesn't exist, or it doesn't have appropriate permissions or ownership for PHPMailer to be able to read it.

**Comment by lap666** [comment]
Hi,

I have use the 5.2 version and everything works.
Thanks for the information.

Kind regards,

**Comment by Synchro** [comment]
On the same file system on the same server?

**Comment by lap666** [comment]
Hi,

Version 6 and version 5.2 dont works.
_Version 5.1_ works all tested the same server

**Comment by Synchro** [comment]
Try using an absolute path to the image, like `/var/www/mysite/pictures/mail.jpg` to be completely sure you're looking for the same file.

**Comment by lap666** [comment]
Hi,

I have use the same script on the same server with the same link to the file.

Version 5.1 works
require_once("PHPMailer-5.2/class.phpmailer.php");
require_once('PHPMailer-5.2/PHPMailerAutoload.php');

Version 5.2 works (same priority)
require_once("phpmailer_v5.1/class.phpmailer.php");
require_once('phpmailer_v5.1/PHPMailerAutoload.php');

Version 6 broking link
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require 'PHPMailer/src/Exception.php';
require 'PHPMailer/src/PHPMailer.php';
require 'PHPMailer/src/SMTP.php';

Kind regards,

**Comment by Synchro** [comment]
What happens if you do this:

    var_dump($mail->AddEmbeddedImage("pictures/mail.jpg","testImage","test.jpg"), $mail->ErrorInfo);

**Comment by lap666** [comment]
bool(true) string(0) "" Message has been sent

**Comment by Synchro** [comment]
So where is the problem? Can you show the differences between delivered messages?

**Comment by lap666** [comment]
Hi,

I have test all over again and found something.

Outlook 2019 mac.
It doens't work.

![Schermafbeelding 2020-02-14 om 19 39 09](https://user-images.githubusercontent.com/15615974/74558404-8c73a580-4f62-11ea-99f4-c9c40a0b1709.png)

Mail catalina.
It works :)

Kind regards,
 
<img width="397" alt="Schermafbeelding 2020-02-14 om 19 39 53" src="https://user-images.githubusercontent.com/15615974/74558477-a90fdd80-4f62-11ea-9106-8c80f06e9732.png">

**Comment by Synchro** [comment]
Can you please attach a complete received message to this issue from each of these versions. I can't tell anything from looking at pictures of this – I need to see the actual messages.

**Comment by lap666** [comment]
Hi, 

It don't support .eml files

Kind regards,
