### ISSUE TITLE
SSL certificate is not verified

### ISSUE THREAD

**Issue by tosiara** [PHPMailer/PHPMailer#196]
I run example with SMTP auth and SSL enabled:

  require 'PHPMailerAutoload.php';
  $mail = new PHPMailer;
  $mail->isSMTP();
  $mail->Host = $smtpsrv;
  $mail->SMTPAuth = true;
  $mail->Username = $smtpuser;
  $mail->Password = $smtppass;
  $mail->SMTPSecure = 'ssl';
  $mail->Port = 465;
  $mail->SMTPDebug = 2;
  if(!$mail->send())

No matter which hostname I specify in $smtpsrv - mail is always sent successfully. It can be IP address, DNS alias or arbitrary name from /etc/hosts. Same happens for TLS. The server certificate is never verified. And I found no way to force PHPMailer to verify and reject server certificate. As a result SSL encryption is useless and user credentials can be stolen by MITM attack.

Please provide a way to verify server certificate using OpenSSL cert store (like postfix does). There was similar report in the past: https://github.com/PHPMailer/PHPMailer/issues/100

**Comment by sergeevabc** [comment]
Gents, could you be so kind and explain plainly how to get rid of error like this?
``` Warning: stream_socket_enable_crypto(): Peer certificate CN=`*.blabla.com' did not match expected CN=`smtp.blabla.net' in class.smtp.php on line 339
SMTP Error: Could not connect to SMTP host.```
It seems some magic line like ``` $mail->$options['ssl']['verify_peer'] = false; ``` is required, right?

**Comment by Synchro** [comment]
Well that will work but it's the 'wrong' way! You can do this by subclassing SMTP at the moment (see the help wiki), but the right solution is not to use a broken SSL cert! FWIW I think @AdamWill's solution is preferable to this one.

**Comment by sergeevabc** [comment]
SSL certificate will be updated soon, till then I’ve to use a broken one, that’s all mess about.
[Intermediate solution][1] is applied, yet another error ```SMTP Error: Could not authenticate``` is here.
Password is correct though, and ```SMTPDebug = 4``` gives no additional details.

**Comment by Synchro** [comment]
The stream options can now be set via the `SMTPOptions` property introduced recently, and will be in the 5.2.10 release.
