### ISSUE TITLE
PHPMailer 6.1.4 throws wrong exceptions

### ISSUE THREAD

**Issue by mkor** [PHPMailer/PHPMailer#1960]
Hi,
I had some issues with PHPMailer complaining that the message body was empty, despite it clearly not being the case.
After some wrestling with my code, I finally jumped into the PHPMailer code and noticed that when something goes wrong during the building of the body, for instance with a missing attachment, the body is emptied and the final error returned will be an erroneous "empty body" (because Body wasn't empty but emptied).

# How to reproduce
If I add PHPMailer.php and add the following on line 3799: `echo "setError(): $msg<br>\n";`
I can see the following output:

> setError(): File Error: Could not open file: /private/var/tmp/deliverynoteda49bU
> setError(): Message body empty
> setError(): Message body empty

And all I did is:
1) attach file /private/var/tmp/deliverynoteda49bU
2) `unlink('/private/var/tmp/deliverynoteda49bU');`
3) `$PHPMailer->send();`

I would expect the FIRST error to be returned, NOT the last one added.

**Comment by Synchro** [comment]
Indeed, the in-flight `$body` variable gets emptied as a result of the missing file; `Body` is not touched. I think the right fix for this is to throw an exception in [`encodeFile`](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L3149) if exceptions are enabled. I'm not certain of the best fix without exceptions though.

**Comment by Synchro** [comment]
This should be fixed indirectly by the commit I just pushed - it throws errors when the missing file is spotted, so it will never get far enough to trigger the empty body issue. Please give it a try.
