### ISSUE TITLE
Halo I tried out the stable 5 version with a youtube tutorial

### ISSUE THREAD

**Issue by AgnesWer** [PHPMailer/PHPMailer#1961]
Halo I am hosting on Fastcomet.com

I tried out this youtube tutorial:

https://www.youtube.com/watch?v=37tSrPc983s&

From This phpmailer version I only use 3 php documents:

class.phpmailer.php
class.smtp.php
PHPMailerAutoload.php

But the reason I get an error when uploading is
this line : $mail->SMTPAuth=true; FastComet is sending this error: PHP Parse error:  syntax error, unexpected '$mail' (T_VARIABLE) in /home/creati46/public_html/index.php on line 10

Is ist because php version on fastcomet is newer than 7 and the php mailer I used is 5?

I am new to developing websites. I already know how to use css, html and javascript documents. I just wantet a tutorial to create a simple contact form sending emails to for example gmail account with tls or ssl security, smtp.....

I do not need css design for the moment. I just know any website can't exist without contact form functioning. So I start with this one. I really do not want any composers or extra code because I want to understand the code!!! So I used the simpliest php mailer... maybe wrong?

How can I use the modern php mailer for a contact form How does the index.html and index.php have to look like? How do I connect to index.php from my index.html side? and so on?
Can somebody provide me with a tutorial with no extra code but with ssl /tls and secure version???

An here is the code: 

`<?php 

$result="";
if(isset($_POST['submit'])){
  require 'phpmailer/PHPMailerAutoload.php';
  $mail = new PHPMailer;

  $mail->Host='smtp.gmail.com';
  $mail->Port=587;
  $mail->SMTPAuth=true;
  $mail->SMTPSecure='tls';
  $mail->Username='ragnedah@gmail.com';
  $mail->Password='678Target';

  $mail->setFrom($_POST['email'],$_POST['name']);
  $mail->addAddress('ragnedah@gmail.com');
  $mail->addReplyTo($_POST['email'],$_POST['name']);

  $mail->isHTML(true);
  $mail->Subject='Form Submission: '.$_POST['subject'];
  $mail->Body='<h1 align=center>Name :'.$_POST['name'].'<br>Email: '.$_POST['email'].'<br>Message: '.$_POST['msg'].'</h1>';

  if(!$mail->send()){
    $result="Error. Please try again";
  } else {
    $result="Thank you for you message".$_POST['name']." It has been sent and we will get back to you.";
  }
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="author" content="Sahil Kumar">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Contact Form Bootstrap</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
</head>

<body class="bg-dark">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-4 mt-5 bg-light rounded">
        <h1 class="text-center font-weight-bold text-primary">Contact Us</h1>
        <hr class="bg-light">
        <h5 class="text-center text-success"><?= $result; ?></h5>
        <form action="" method="post" id="form-box" class="p-2">
          <div class="form-group input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" name="name" class="form-control" placeholder="Enter your name" required>
          </div>
          <div class="form-group input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-envelope"></i></span>
            </div>
            <input type="email" name="email" class="form-control" placeholder="Enter your email" required>
          </div>
          <div class="form-group input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-at"></i></span>
            </div>
            <input type="text" name="subject" class="form-control" placeholder="Enter subject" required>
          </div>
          <div class="form-group input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-comment-alt"></i></span>
            </div>
            <textarea name="msg" id="msg" class="form-control" placeholder="Write your message" cols="30" rows="4" required></textarea>
          </div>
          <div class="form-group">
            <input type="submit" name="submit" id="submit" class="btn btn-primary btn-block" value="Send">
          </div>
        </form>
      </div>
    </div>
  </div>
</body>

</html>`

**Comment by AgnesWer** [comment]
Ah now the form is loading there was instead in ANOTHER line a missing $ because I wrote § by accident in front of mail....

But I head to reaload everythinig. Lets see now.

**Comment by AgnesWer** [comment]
Now the form functions.

How can I do the whole thing without bootstrap and just put my own design in the contact form?

**Comment by mail2bapi** [comment]
Build a simple html form and post the values to the PHP script.

**Comment by AgnesWer** [comment]
1. Build a simple html form. Okay. 
2. Post values to the php script? What do you mean by that?
The php code above I can copy/remake no problem. But I have 2 problems:

making my own contactform (deleting this bootstrap thing from the code)
- moving the client from index.HTML to index.php

Suggestions?

**Comment by mail2bapi** [comment]
- Create contact.php file
- Add your html form and adding contact.php in action attribute of form
- copy the above PHP to contact.php and past it at top of the page.

**Comment by Synchro** [comment]
1. Don't use PHPMailer 5.2 any more. Use the latest version.
2. Look the examples provided, especially [the contact form](https://github.com/PHPMailer/PHPMailer/blob/master/examples/contactform.phps).

**Comment by AgnesWer** [comment]
Thank you both for the tips.

As far as I can see now the newer version of php mailer does explain some code but not telling in wich index.html or index.php or configuration.php I have to put it. It is talking about a configuration.php wich is not included in the download files.

From The Tutorial I only learned to make an index.php and put the html code for the contacform also in there.

Now how do I start?
I am really new to this. Also the tutorial to the old version php does not explain this.

So I create an index.php right? There I put all the code explained in the newer version of php site? Right? And under the code I put the htmll code for my contacform ... right?

And How Do I create a php configuration file?

Please not I do not want to use composer. I would be very thankfull if somebody could put the steps in here with code. TLS or SSL I want to use. I want to sent the messages from my hosting site to my gmail account. 
I think tls has to be used. And the port I know.

So please explain:
what file to create first? Index.php or configuration.php?
What code do I put in index.php and in the configuration.php?
(I will also create index.html, the main page and make a button there wich leads to index.php(i will rename it contactform.php though, so it will not be called index.php). 

Thanks!

**Comment by Synchro** [comment]
PHPMailer cannot tell you where to put your code. Every project can use it in a completely different way; PHPMailer is a library that does what other code tells it to, but that other code is not part of PHPMailer - it's *your* code. Think of it like a light bulb - it's up to you to provide something to plug it into, supply electricity, and control it with a switch; it does nothing by itself. I have no idea what configuration file you're talking about – there is no such thing in PHPMailer. If it's mentioned in some Youtube thing, it's part of whatever code that is talking about, not PHPMailer.

There are plenty of examples provided with PHPMailer, all of which demonstrate correct TLS config - try starting with the one in the readme, and look in the examples folder for more, especially the gmail one, since that's what you are trying to do.

If you're starting out in PHP, the single best thing you can do is learn how to use composer. Not doing so means you're going out of your way to make building apps more difficult.

**Comment by AgnesWer** [comment]
Yes I understood fully that php mailer does nothiing by itself. That is why I asked the questions. No the configuration.php is mentioned in the description of how to use php mailer. So I do not know where to put the code.

I really just want answers to my questions.

I create index.html. There I put a button to contactform.php.

In the contactform.php I put the code from the tutorial above, and also the html code for my contactform. I use the names values as needed.

But How do I now load phpmailer without composer(I really want to start without composer). I really want all the stuff tls and gmail smtp (i alredy know the details) and auth2 for gmail....

Can somebody just put the code in herek for each document? For the moment no css needed!

**Comment by AgnesWer** [comment]
I can start a new issue asking for such a tutorial?

**Comment by AgnesWer** [comment]
Alternatively, if you're not using Composer, copy the contents of the PHPMailer folder into one of the include_path directories specified in your PHP configuration and load each class file manually:

<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'path/to/PHPMailer/src/Exception.php';
require 'path/to/PHPMailer/src/PHPMailer.php';
require 'path/to/PHPMailer/src/SMTP.php';

**Comment by AgnesWer** [comment]
> 

<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'path/to/PHPMailer/src/Exception.php';
require 'path/to/PHPMailer/src/PHPMailer.php';
require 'path/to/PHPMailer/src/SMTP.php';

**Comment by AgnesWer** [comment]
`
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'path/to/PHPMailer/src/Exception.php';
require 'path/to/PHPMailer/src/PHPMailer.php';
require 'path/to/PHPMailer/src/SMTP.php';`

**Comment by Synchro** [comment]
Yes - to load classes manually, without composer, you need to do exactly what that says. What the youtube thing says is nothing to do with what happens here - if the tutorial is any good they will provide a git repository where you can get the code from. If not, find another one that does.
