### ISSUE TITLE
Ask for tutorial for beginners for the new version of phpmailer without composer

### ISSUE THREAD

**Issue by AgnesWer** [PHPMailer/PHPMailer#1963]
Halo I am hosting on Fastcomet.com

I tried out this youtube tutorial:

https://www.youtube.com/watch?v=37tSrPc983s&

From This phpmailer version I only use 3 php documents:

class.phpmailer.php
class.smtp.php
PHPMailerAutoload.php

YOU CAN SEE THE CODE ON THE END OF THIS COMMENT.

Question:

How do I use this newer php mailer now? 

1. I want to install it without composer, this is really important for me
2. I am new to this coding thing

1a. I start an index.hmtl and put a button there for the contactform.php to load. Right?
2a. In the contactform.php I put the code for php that is mentiond if you look at the bottom of this comment. And also put there a simple html inside for my contactform (without this bootstrap thing).

Please provide me with steps code for each document index.html, contactform.php and if needed configuration.php. These three documents I will create myself. Please provide me with a full comment like a tutorial.

I do really not want to use composer. I am learning right now everything myself.
I really want to send this from my hosting site to a gmail account.
I would like to use smtp, tls(for gmail) and auth2 authentification for gmail. I know how to put these options securities off in my gmail account and I know the port and the smtp gmail. I just need the scripts/codes for each document.

Thanks! 
 
PS: NO IT IS NOT EXPLAINED IN THE DESCRIPTION OF THE NEW PHP MAILER WICH DOCUMENTS TO CREATE AND WHERE TO PUT THE CODES AND HOW. 

I have sublime text, does not matter.... wich texteditor to use. I am familiar with that allready. 

An here is the code: 

`<?php 

$result="";
if(isset($_POST['submit'])){
  require 'phpmailer/PHPMailerAutoload.php';
  $mail = new PHPMailer;

  $mail->Host='smtp.gmail.com';
  $mail->Port=587;
  $mail->SMTPAuth=true;
  $mail->SMTPSecure='tls';
  $mail->Username='ragnedah@gmail.com';
  $mail->Password='678Target';

  $mail->setFrom($_POST['email'],$_POST['name']);
  $mail->addAddress('ragnedah@gmail.com');
  $mail->addReplyTo($_POST['email'],$_POST['name']);

  $mail->isHTML(true);
  $mail->Subject='Form Submission: '.$_POST['subject'];
  $mail->Body='<h1 align=center>Name :'.$_POST['name'].'<br>Email: '.$_POST['email'].'<br>Message: '.$_POST['msg'].'</h1>';

  if(!$mail->send()){
    $result="Error. Please try again";
  } else {
    $result="Thank you for you message".$_POST['name']." It has been sent and we will get back to you.";
  }
}
?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="author" content="Sahil Kumar">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Contact Form Bootstrap</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
</head>

<body class="bg-dark">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-4 mt-5 bg-light rounded">
        <h1 class="text-center font-weight-bold text-primary">Contact Us</h1>
        <hr class="bg-light">
        <h5 class="text-center text-success"><?= $result; ?></h5>
        <form action="" method="post" id="form-box" class="p-2">
          <div class="form-group input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" name="name" class="form-control" placeholder="Enter your name" required>
          </div>
          <div class="form-group input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-envelope"></i></span>
            </div>
            <input type="email" name="email" class="form-control" placeholder="Enter your email" required>
          </div>
          <div class="form-group input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-at"></i></span>
            </div>
            <input type="text" name="subject" class="form-control" placeholder="Enter subject" required>
          </div>
          <div class="form-group input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-comment-alt"></i></span>
            </div>
            <textarea name="msg" id="msg" class="form-control" placeholder="Write your message" cols="30" rows="4" required></textarea>
          </div>
          <div class="form-group">
            <input type="submit" name="submit" id="submit" class="btn btn-primary btn-block" value="Send">
          </div>
        </form>
      </div>
    </div>
  </div>
</body>

</html>`

**Comment by Synchro** [comment]
> PS: NO IT IS NOT EXPLAINED IN THE DESCRIPTION OF THE NEW PHP MAILER WICH DOCUMENTS TO CREATE AND WHERE TO PUT THE CODES AND HOW

As I said in #1961, this is not up to PHPMailer. There are many examples that show how to use PHPMailer - **you** need to adapt one for **your** specific situation. You have all the information you need. Having me paste the same information in here is not going to change the information. If you don't know how to do it, pay someone who does to do it for you.

**Comment by AgnesWer** [comment]
`<html>`

**Comment by AgnesWer** [comment]
@Synchro 


it is a simple question where to put the code lines in the description of the new PHPMailer, and how... wich enable installing without composer. 

Why should somebody not being able to help me, where is the problem?

**Comment by Synchro** [comment]
Because this exact information is already in the readme. Put the PHPMailer files wherever you like, load them with `require`. That's it.

**Comment by AgnesWer** [comment]
As you see that is what I did, but the page does not load.

**Comment by Synchro** [comment]
https://stackoverflow.com/search?q=how+to+debug+PHP

**Comment by AgnesWer** [comment]
Thank you very much for the link and the patience. I found on stockoverflow that somebody hat the same issue with http error 500. There was a server problem with the host. I hope this is simply a server problem but I will check your links out. Thank you very much.
