### ISSUE TITLE
DKIM uses length field while discouraged by RFC

### ISSUE THREAD

**Issue by KlaasBonnema** [PHPMailer/PHPMailer#1964]
PHPMailer 6.1.4 always includes the length field l= in a DKIM key. RFC 5672 section 3.5 discourages using the length field because it opens possible attack vectors. Since it is an optional field anyway it should be left out of the DKIM key.

**Comment by Synchro** [comment]
That sounds reasonable. Care to make a PR?

**Comment by KlaasBonnema** [comment]
Marcus,

What's a PR?

Klaas

________________________________
Van: Marcus Bointon <notifications@github.com>
Verzonden: vrijdag 14 februari 2020 15:59
Aan: PHPMailer/PHPMailer <PHPMailer@noreply.github.com>
CC: KlaasBonnema <kljbonnema@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [PHPMailer/PHPMailer] DKIM uses length field while discouraged by RFC (#1964)


That sounds reasonable. Care to make a PR?

**Comment by Synchro** [comment]
Ah, you're new here! A PR is a pull request – fork the project, make the changes necessary to implement what you propose (ideally with accompanying tests), then request that it be merged back into this project. It sounds like you know what you're doing with DKIM - please take a look at [my DKIM validator project](https://github.com/PHPMailer/DKIMValidator) too.

**Comment by KlaasBonnema** [comment]
I'll have to look into that. My immediate issue is with static::$LE and DKIM. It blocks migration to PHPMailer. I currently use DKIM Validator plugin in Thunderbird and check-auth@validator.port25.com for DKIM validations. Is a PR for one issue only or could I combine several issues?

**Comment by Synchro** [comment]
Generally it's a good idea to keep them separate as it keeps things on-topic for each one.
