### ISSUE TITLE
PHP syntax errors and warnings

### ISSUE THREAD

**Issue by KlaasBonnema** [PHPMailer/PHPMailer#1968]
The PHPMailer PHP code flags several syntax errors and warnings. The warnings will become fatal with the next major PHP version.

PHPMailer.php
encodeHeader() - warning Variable $matches is undefined - add: $matches=array();
msgHTML() -  warning Variable $images is undefined - add: $images=array();
  -  warning Variable $match is undefined - add: $match=array();
DKIM_Sign() - warning Variable $signature is undefined - add: $signature="";
424      * @var string|callable|\Psr\Log\LoggerInterface
Error - \Psr\Log\LoggerInterface cannot be resolved to a type
886         if ($this->Debugoutput instanceof \Psr\Log\LoggerInterface) {
Error - Loggerinterface cannot be resolved to a type

SMTP.php
recordLastTransactionID() - warning Variable $matches is undefined - add: $matches=array();
140      * @var string|callable|\Psr\Log\LoggerInterface
Error - \Psr\Log\LoggerInterface cannot be resolved to a type
259         if ($this->Debugoutput instanceof \Psr\Log\LoggerInterface) {
Error - Loggerinterface cannot be resolved to a type

POP3.php
connect()  - warning Variable $errno is undefined - add: $errno=0;
   - warning Variable $errstr is undefined - add: $errstr="";

OAuth.php
23 use League\OAuth2\Client\Grant\RefreshToken;
use League\OAuth2\Client\Provider\AbstractProvider;
use League\OAuth2\Client\Token\AccessToken;
Error - These three imports cannot be resolved to a type.
40      * @var AbstractProvider - Error - cannot be resolved to a type
47      * @var AccessToken - Error - cannot be resolved to a type
98     * @return RefreshToken - Error - cannot be resolved to a type
102         return new RefreshToken();  - Error - cannot be resolved to a type
108      * @return AccessToken - Error - cannot be resolved to a type

**Comment by Synchro** [comment]
I don't know what static analyser you're using, but these are all false positives. *All* of those undefined variables are passed by reference, which defines them, so they don't need to be declared. I've declared them anyway just to make your analyser shut up!

All of those unresolved types are fully expected and certainly will not be fatal. If you are using those classes, they will be defined and you'll be able to use them - whether they exist is entirely down to your environment and composer config, not the scripts using them.

**Comment by KlaasBonnema** [comment]
The errors and warnings are flagged by Eclipse PDT. 
False positives means that you can miss the true positives. A library that signals at the top level that there are errors somewhere inside does not give a cosy feeling.

https://github.com/php/php-src/blob/master/UPGRADING#L20
PHP 8 upgrade notes:
Attempting to read an undefined variable will now throw an error exception.
This applies to preg_match() using undeclared $matches.

**Comment by Synchro** [comment]
The `$match` parameter to `preg_match` does *not* attempt to read an undefined variable. It *sets* an undefined variable that is passed by reference. What's more, undefined variables are still not going to be fatal in 8.0, they are just upgraded to warnings. You also misquoted the upgrade notes; it says:

> A number of notices have been converted into warnings:
> 
>    * Attempting to read an undefined variable.

In this case the false positive is caused by bad tooling, not the script, so I'd agree - it doesn't inspire confidence in the tools.

It's also easy to test:
```sh
./sapi/cli/php -v && cat t.php && ./sapi/cli/php t.php
PHP 8.0.0-dev (cli) (built: Feb 17 2020 10:50:58) ( ZTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
<?php
ini_set('display_errors', true);
preg_match('@^(?:http://)?([^/]+)@i',
    "http://www.php.net/index.html", $matches);
$host = $matches[1];
echo "$host\n";
www.php.net
```
No errors, no warnings, no info.
