### ISSUE TITLE
Don't know how to use PHPMailer with a Gmail service account

### ISSUE THREAD

**Issue by xgretsch** [PHPMailer/PHPMailer#1972]
Because Google are requiring OAuth2 for Gmail, I am updating the integration of my system, which permits my software to send and receive emails on behalf of users via their company Gmail accounts.

I've successfully handled the receive side using the Gmail API, having set up a Service Account as described in their advice for Server to Server Gmail calls (https://developers.google.com/identity/protocols/OAuth2ServiceAccount).

I'm now trying to add the send side. I use PHPMailer, so I've upgraded my version to 6.x and looked at this document: https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2.

The trouble is, I can't see how to plumb in the credentials provided by the service account. PHPMailerOAuth expects to see the usual OAuth2 client id, client secret and refresh token, whereas the Service Account does not provide me with a client secret or refresh token - rather, it gives me a private key and a token URI.

Is there a way round this? Is there something in the Gmail API that will turn the service account credentials into a client secret and refresh token, or is there some different instruction I can give to the PHPMailerOAuth class?

**Comment by Synchro** [comment]
I think it's the latter – you need to ask the google APIs for those tokens – but you'll need to refer to google for how to do that.

**Comment by imclean557** [comment]
Even though it is server to server communication, what you're effectively developing @xgretsch is a client application.

The user who is sending email can set up API credentials here:  https://console.cloud.google.com/apis/credentials

See also: 

- https://cloud.google.com/docs/authentication/
- https://cloud.google.com/docs/authentication/end-user

**Comment by xgretsch** [comment]
Thanks for the advice, Ian, but I'm not sure that "effectively" is the right word. Yes, it could be done as a client application, asking my users to set up their own credentials and refresh them if needed because a token has expired. But it's easier in operational terms to avoid this by using the service API. So what I've ended up doing is to use PHPMailer only as far as the stage of creating the raw email content, and then use the Gmail API to actually send the message.

**Comment by imclean557** [comment]
Sorry, the expression may not have come across well. By "effectively" I meant "in effect" or "actually".

It sounds like PHPMailer may not be right tool for the job, as you've discovered.  I suspect the Gmail API doesn't involve you using any email protocols, which is what PHPMailer is for.
