### ISSUE TITLE
6.1.4: New line in header breaks e-mail

### ISSUE THREAD

**Issue by blaaat** [PHPMailer/PHPMailer#1984]
# Problem description

`$phpMailer->addCustomHeader('X-test', 'aaa' . PHP_EOL . 'aa');
`

If a new-line is added to a custom header (how invalid it may be). E-mail output is corrupted because a double CRLF is introduced since 6.1.4. 

This is of course invalid usage of the header, but I think it might be better to throw an exception or encode the header. Resolving a possible header injection issue at the same time. 

# Code to reproduce

# Debug output

**Comment by Synchro** [comment]
Thanks, that is fixed in master now
