### ISSUE TITLE
Code error in mailing_list example

### ISSUE THREAD

**Issue by cburkitt** [PHPMailer/PHPMailer#1990]
Hi

In the mailing_list.php example, lines 69-71, is the following code:

//Reset the connection to abort sending this message
//The loop will continue trying to send to the rest of the list
`$mail->smtp->reset();`

This caused a fatal error in my script:
*Cannot access protected property PHPMailer::$smtp*

I looked at the PHPMailer.php code and the `$smtp` property is indeed protected, so I don't see how this reset can work.

The reset was only triggered because an exception was thrown when running `$mail->send()` but that was a server issue that is now fixed.

Have I missed something here? My PHP is not bad, but not brilliant either!

Thanks,

Charles

**Comment by Synchro** [comment]
You are absolutely correct - fixed in master!

**Comment by cburkitt** [comment]
Thank you!
