### ISSUE TITLE
send email with shared mailbox

### ISSUE THREAD

**Issue by redha-ax2lan** [PHPMailer/PHPMailer#2006]
Hello
After a lot of trying it was impossible to send an email to a shared mailbox using an authenticated email address. So I wanted to ask you if a method was available for this kind of method.
Thank you for your help, have a good day !

**Comment by LamaYouzghatli** [comment]
Can I send an email using shared mailbox?

**Comment by Synchro** [comment]
That's up to your mail server, not within PHPMailer's control.
