### ISSUE TITLE
Fix typo in PHPMailer class DKIM_Add function array autoSignHeaders

### ISSUE THREAD

**Issue by 095tim-wmesulam** [PHPMailer/PHPMailer#2007]
Typo (`'nessage-id'`) in array `autoSignHeaders` of [`PHPMailer` class](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php) in `DKIM_Add` function.
[rfc6376](https://tools.ietf.org/html/rfc6376) defines no such field as `'nessage-id'` is it meant to be `'message-id'`.

```php
//Always sign these headers without being asked
//Recommended list from https://tools.ietf.org/html/rfc6376#section-5.4.1
$autoSignHeaders = [
    'from',
    'to',
    'cc',
    'date',
    'subject',
    'reply-to',
    /**
     *  what are we upto here: 'nessage-id' or 'message-id'
     *  rfc6376 defines no such field as 'nessage-id'
     */
    'nessage-id',
    'content-type',
    'mime-version',
    'x-mailer',
];
```

**Comment by Synchro** [comment]
Yep, it was a typo introduced during recent changes in DKIM handling. Thanks.
