### ISSUE TITLE
SSL authentication with client certificate

### ISSUE THREAD

**Issue by pawp81** [PHPMailer/PHPMailer#2011]
#1827 Problem description
I want my PHPMailer client to present certificate to the server it connects to. The server is instructed to allow open relaying from my PHPMailer client if certain certificate is presented. I have generated .pem file and save it to the local drive. I am running PHPMailer version 6.1.1 on IIS
# Code to reproduce
	use PHPMailer\PHPMailer\PHPMailer;
	use PHPMailer\PHPMailer\Exception;
	use PHPMailer\PHPMailer\SMTP;
	require 'C:\Program Files\PHP\v7.3\PHPMailer\src\Exception.php';
	require 'C:\Program Files\PHP\v7.3\PHPMailer\src\PHPMailer.php';
	require 'C:\Program Files\PHP\v7.3\PHPMailer\src\SMTP.php';
$mail = new PHPMailer(TRUE);
$mail->SMTPDebug = SMTP::DEBUG_CONNECTION;
$mail->isSMTP();
$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
$mail->Host = 'remote.server.com';
$mail->SMTPOptions = array(
		'ssl' => [
        'verify_peer' => false,
        'local_cert' => 'C:\\Program Files\\PHP\\v7.3\\PHPMailer\\src\\oatpme.pem',
			],
		);
# Debug output
The site just keeps spinning. It doesn't send an email. After a while I am getting an error:
500 - Internal server error.
There is a problem with the resource you are looking for, and it cannot be displayed.
In PHP logs I can find:
[13-Mar-2020 07:40:15 Europe/Dublin] PHP Fatal error:  Maximum execution time of 300 seconds exceeded in C:\Program Files\PHP\v7.3\PHPMailer\src\SMTP.php on line 1304
line 1304 in SMTP php is: $notice = 'Connection failed.';
Below complete function:
    protected function errorHandler($errno, $errmsg, $errfile = '', $errline = 0)
    {
        $notice = 'Connection failed.';
        $this->setError(
            $notice,
            $errmsg,
            (string) $errno
        );
        $this->edebug(
            "$notice Error #$errno: $errmsg [$errfile line $errline]",
            self::DEBUG_CONNECTION
        );
    }

**Comment by Synchro** [comment]
I really don't know about doing this. Do you have any working examples of other code using this approach?

It seems odd to combine a relatively high security approach of client certs with disabling verification.

**Comment by pawp81** [comment]
I guess you are referring to 'verify_peer' => false, ? 
If i change it to true the behavior is the same.
I don't have running code. Though I found similar topic here and used it as a reference:
https://stackoverflow.com/questions/45453980/connect-to-smtp-server-with-client-certificate-without-password-from-php-scrip

**Comment by Synchro** [comment]
This sounds like you have a problem earlier on in your connection – it doesn't seem like it's getting as far as actually presenting your client certificate. You're not setting `Port`, so it will connect to port 25 by default, which means it will need to use SMTP+STARTTLS, which is what you have set, but before it gets that far it will still need to connect and request an encrypted connection – but you're never reaching that point, so I'd suspect you have some upstream firewall blocking outbound SMTP.

**Comment by pawp81** [comment]
Thx. I can telnet fine on port 25 to the remote.server.com

**Comment by Synchro** [comment]
Hm, so you're not getting any debug output at all from PHPMailer? You should at least get a "connecting to", even if it can't connect.

**Comment by pawp81** [comment]
This is what I have in smtp.log:
```
2020-10-09 07:56:24	3	Connection: opening to remote.server.com:25, timeout=300, options=array (
  'ssl' => 
  array (
    'verify_peer' => true,
    'local_cert' => 'C:\\Program Files\\PHP\\v7.3\\PHPMailer\\src\\oatpme.pem',
  ),
)
2020-10-09 07:56:24	3	Connection: opened
2020-10-09 07:56:24	2	SERVER -> CLIENT: 220 remote.server.com Microsoft ESMTP MAIL Service ready at Fri, 9 Oct 2020 07:56:23 +0000
2020-10-09 07:56:24	1	CLIENT -> SERVER: EHLO mailer.mydomain.com
2020-10-09 07:56:24	2	SERVER -> CLIENT: 250-remote.server.com Hello [137.xxx.206.xxx]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
2020-10-09 07:56:24	1	CLIENT -> SERVER: STARTTLS
2020-10-09 07:56:24	2	SERVER -> CLIENT: 220 2.0.0 SMTP server ready

```

**Comment by Synchro** [comment]
And it stops there? That's odd – it shows that STARTTLS works correctly. That `220` response is sent over an encrypted connection; PHPMailer should be issuing a second `EHLO` command at that point. Can you see exactly where it's hanging up in the code?

**Comment by pawp81** [comment]
According to PHP error logs it failes in SMTP.php on line 1304:
`[09-Oct-2020 09:08:31 Europe/Dublin] PHP Fatal error:  Maximum execution time of 300 seconds exceeded in C:\Program Files\PHP\v7.3\PHPMailer\src\SMTP.php on line 1304`

Linek 1304 in SMTP.php is:
    `    $notice = 'Connection failed.';`

**Comment by Synchro** [comment]
That's where it ends up in the error handler, which doesn't tell us how it got there. Also those line numbers don't line up with the current code – are you using an old version?

**Comment by pawp81** [comment]
I updated to the latest version still the same.
I tried also with .cer base64 encoded ceritficate format still no luck

**Comment by Synchro** [comment]
It's really difficult to see what's going here. Can you try testing using `openssl s_client`? That will provide much more detailed feedback. It should be something like:

    openssl s_client -key key.pem -cert cert.pem -starttls smtp -connect mail.example.com:587

Because this is using TLS directly, it eliminates PHP and your script from the equation – if it doesn't work there, you will know it won't work in PHP either.

**Comment by pawp81** [comment]
Looks like something is wrong with my .pem file that contains both private key and certificate.
I am getting following error int SMTP debug log:
`2020-11-05 14:57:22	3	Connection failed. Error #2: stream_socket_enable_crypto(): Unable to set private key file `C:\Program Files\PHP\v7.3\PHPMailer\src\oatpme.pem'`

I created .pem file by converting .pfx to .pem format:

`openssl pkcs12 -in _oatpme.pfx -out oatpme.pem -node`s

**Comment by Synchro** [comment]
If that puts your key and cert in the same file, you can split them manually, then try using them with the `openssl` command I posted earlier.

**Comment by pawp81** [comment]
Running this command allowed to generate proper .pem file and looks like I can send email over SSL
`openssl pkcs12 -in keyname.pfx -out keyname.pem -nodes -clcerts`

Though I am not sure if there is any evidence that my mailer is authenticating using SSL cert in the logs: 
```
2020-11-05 15:38:51	1	CLIENT -> SERVER: STARTTLS
2020-11-05 15:38:51	2	SERVER -> CLIENT: 220 2.0.0 SMTP server ready
2020-11-05 15:38:51	1	CLIENT -> SERVER: EHLO mail.mydomain.com
2020-11-05 15:38:51	2	SERVER -> CLIENT: 250-AM5EUR03FT027.mail.protection.outlook.com Hello [123.123.123.123]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
2020-11-05 15:38:51	1	CLIENT -> SERVER: MAIL FROM:<someone@mydomain.com>
2020-11-05 15:38:51	2	SERVER -> CLIENT: 250 2.1.0 Sender OK
2020-11-05 15:38:51	1	CLIENT -> SERVER: RCPT TO:<john.doe@contoso.com>
2020-11-05 15:38:52	2	SERVER -> CLIENT: 250 2.1.5 Recipient OK
2020-11-05 15:38:52	1	CLIENT -> SERVER: DATA
```

**Comment by Synchro** [comment]
Well one bit of evidence is that it's is not asking for authentication, presumably (hopefully!) because you're already authenticated by the client cert. You should be able to confirm that by telling it not to use the cert and have it fail.

**Comment by pawp81** [comment]
Yes. Everything works now as expected. Thank you!
