### ISSUE TITLE
Reply-To problem

### ISSUE THREAD

**Issue by halojoy** [PHPMailer/PHPMailer#2012]
I added a Reply-To adress and name in the PHPMailer class:

**protected $ReplyTo = ['theemail@some.com', 'Sender name'];**

But it simply doesn't work.
The result in email was:
```
a <t>, n <S>
```
where a address and n stands for name obviously.
And displayed is the first letter in both address and name.

**Comment by Synchro** [comment]
That's not the right way to use it. Do this using your PHPMailer instance:

    $mail->addReplyTo('theemail@some.com', 'Sender name');

**Comment by halojoy** [comment]
Thanks.
Yes, used that way it will work.
