### ISSUE TITLE
Problem with EML attachments

### ISSUE THREAD

**Issue by ikarol** [PHPMailer/PHPMailer#2014]
# Problem description
Currently(PhpMailer 6) both addAttachment and addStringAttachment methods handle .eml attachments incorrectly(considering that all optional arguments use default values).
It produces garbage like this(notice Message from Unknown to Unknown):
![Annotation 2020-03-18 135607](https://user-images.githubusercontent.com/16179864/76953782-51c5aa00-6920-11ea-86c8-a75b51de1d92.png)

The same problem exists in Swift Mailer(https://github.com/swiftmailer/swiftmailer/issues/258).
As you can see from the comments, there are multiple known solutions:
1) Use application/octet-stream MIME with default base64 encoding
2) Use text/rfc822 MIME with default base64 encoding

The root cause from PhpMailer side is dynamic MIME identification logic that uses message/rfc822 type. Previously(in PhpMailer 5) it used application/octet-stream as default MIME type and it worked fine.

Though it's possible to use either workaround by manually specifying MIME and encoding types in addAttachment(addStringAttachment) methods.
I think that it should be handled by the library automatically, otherwise it will make client code more boilerplate.
# Code to reproduce
```
$m = new \PHPMailer\PHPMailer\PHPMailer();
// configuration
$m->addAddress("example.com");
$m->Subject = 'test email';
$m->Body = 'test';
$m->addAttachment("example1.eml"); // will produce garbage
$m->addStringAttachment("eml data", "example2.eml"); // will produce garbage
$m->send();
```

**Comment by Synchro** [comment]
It sounds like the right way to handle this would be to automate the assignment of encodings. `message/rfc822` is the correct MIME type for an embedded message, and it _shouldn't_ have a problem with non-binary (i.e. not base64) encodings - if it does then that's a separate problem. Forcing base64 encoding might make it work, but it's not the correct way to fix it. It would be more interesting to see what exactly is causing the problem with the current mechanism.

**Comment by Synchro** [comment]
I've just done some experiments with this using 6.1.5, and `.eml` attachments work fine as both base64 and as 8bit.

**Comment by ikarol** [comment]
@Synchro I've sent you message to your personal mailbox with example emails(containing .eml attachments)

**Comment by ikarol** [comment]
As was discussed in the private conversation with @Synchro, current approach(base64 + message/rfc822) for eml files will produce message that couldn't be parsed correctly by multiple well known email clients(Mozilla Thunderbird, IBM Notes).

Though, there are multiple workarounds for this, where you have to specify(or ensure) MIME type and encoding mechanism:

1) 8bit(or 7bit) encoding + message/rfc822 MIME(some clients(IBM Notes) may interpret message as embedded and won't provide it for download in "attachments" section)
2) base64 encoding + application/octet-stream MIME

**Comment by Synchro** [comment]
Also bear in mind that you can't generalise about this - if an embedded message contains binary content, but the message you're embedding it in does not support it, there is no choice but to use a base64 CTE for the embedded message, which is why it's *always* a valid option that should be supported by clients. Have you reported this mishandling to the respective client app creators?

Again, `application/octet-stream` is a way of saying "I have no idea what this data is"; this MIME type will typically always render as an attachment, but will also guarantee that the attachment will bypass any client's handling of the true format of the attachment; for example if you attach an `image/png` file marked as an `application/octet-stream`, it will usually not (and *should not*, because content type sniffing is a common attack vector) be rendered by the client.

**Comment by vielhuber** [comment]
Is there a workaround when you want to send an eml file with phpmailer? Or is the result of this conversation that it is currently not possible?

**Comment by Synchro** [comment]
There is nothing preventing you from sending.eml attachments with PHPMailer, and it does so correctly. Unfortunately some email clients parse these messages incorrectly, which isn't PHPMailer's fault. You can set the MIME type yourself, but probably the easiest and most reliable way around this is to wrap the message, such as by zipping it.

**Comment by vielhuber** [comment]
Thanks for your explanation.

> You can set the MIME type yourself

Just to clarify:
Is this done with: `addAttachment('file.eml', '', 'message/rfc822')`?

**Comment by Synchro** [comment]
That's the MIME type it will get assigned automatically from the filename mapping, so will make no difference. You can override it with:

    addAttachment('file.eml', '', 'application/octet-stream')
