### ISSUE TITLE
PHPMailer works on Local, but not in hosting (getting 400 error)

### ISSUE THREAD

**Issue by RizwanASMB** [PHPMailer/PHPMailer#2019]
Hi Configured the PHPMailer and as per given wiki page 

(https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2)

everything works fine when i did on localhost but when i hosted this iam getting the error msg as follows :

400. That’s an error.

Error: invalid_request

Invalid parameter value for redirect_uri: Missing authority: https://

I cross checked the authorized url more than 10times , its configured good as per myknowledge.

eg: https://domainname/phpmailer/get_oauth_token.php - Not working

eg: https://domainname/phpmailer/testmail.php - Not working

eg: http://localhost/phpmailer/get_oauth_token.php - working fine

eg: http://localhost/phpmailer/testmail.php-  working fine

It would be very greatful , if you could guide me to resolve this .

Thanks in advance!

**Comment by Synchro** [comment]
I really have no idea about this, but clearly the difference is between your environments, not your scripts.

**Comment by RizwanASMB** [comment]
Hi @Synchro 

Thanks for quick response and I am able to get email with following script :

`<?php
/**
 * This example shows how to send via Google's Gmail servers using XOAUTH2 authentication.
 */


//Import PHPMailer classes into the global namespace
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\OAuth;
// Alias the League Google OAuth2 provider class
use League\OAuth2\Client\Provider\Google;


require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ .'/src/PHPMailer.php';
require_once __DIR__ .'/OAuth.php';
require_once __DIR__ .'/src/SMTP.php';
require_once __DIR__ .'/src/Exception.php'; 
require_once __DIR__ .'/google_oauth/vendor/league/oauth2-client/src/Provider/Google.php';


//Create a new PHPMailer instance
$mail = new PHPMailer;

//Tell PHPMailer to use SMTP
$mail->isSMTP();
$mail->SMTPDebug = 2;

//Set the hostname of the mail server
$mail->Host = 'smtp.gmail.com';
//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
$mail->Port = 587;
//Set the encryption mechanism to use - STARTTLS or SMTPS
$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
//Whether to use SMTP authentication
$mail->SMTPAuth = true;
//Set AuthType to use XOAUTH2
$mail->AuthType = 'XOAUTH2';
//Fill in authentication details here
//Either the gmail account owner, or the user that gave consent
$email = 'demo@myorg.com';
$clientId = 'XXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com';
$clientSecret = 'XXXXXXXXXXXXXXXXXXXXXXYQ';
//Obtained by configuring and running get_oauth_token.php
//after setting up an app in Google Developer Console.
$refreshToken = 'XXXXXXXXXXXXXXXXXXXXXXXDK2No6sCCcHlCbg';
//Create a new OAuth2 provider instance
$provider = new Google(
    [
        'clientId' => $clientId,
        'clientSecret' => $clientSecret,
    ]
);
//Pass the OAuth provider instance to PHPMailer
$mail->setOAuth(
    new OAuth(
        [
            'provider' => $provider,
            'clientId' => $clientId,
            'clientSecret' => $clientSecret,
            'refreshToken' => $refreshToken,
            'userName' => $email,
        ]
    )
);
//Set who the message is to be sent from
//For gmail, this generally needs to be the same as the user you logged in as
$mail->setFrom($email, 'Demo');
//Set who the message is to be sent to
$mail->addAddress('test@gmail.com', 'Rizwan Shaik');
//Set the subject line
$mail->Subject = 'PHPMailer GMail XOAUTH2 SMTP test';
//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body
$mail->CharSet = 'utf-8';
$mail->Body    = "This is the HTML message body <b>in bold!</b>";
//Replace the plain text body with one created manually
$mail->AltBody = 'This is a plain-text message body';
//Attach an image file
$mail->addAttachment('images/phpmailer.png','phpmailer.png');

//send the message, check for errors
if (!$mail->send()) {
    echo 'Mailer Error: '. $mail->ErrorInfo;
} else {
    echo 'Message sent!';
}`

its working fine,but everytime its asking to authentication with SignPage of gmail, how can we prevent auto-login , with login I need to send email

if any possibilities, Please guide me

Thanks

**Comment by Synchro** [comment]
Without the SMTP transcript I can only guess, but gmail is known to dislike new login origins, regardless of whether they are valid or not, so you probably need to go through the processes mentioned in [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#gmail-oauth2-and-allow-less-secure-apps).

**Comment by tse1218** [comment]
did you solve the problem? i got the same issue and don't know how to do.
