### ISSUE TITLE
 Can email attachments be sent by streaming

### ISSUE THREAD

**Issue by hanyudanei** [PHPMailer/PHPMailer#2021]
Hello, I'd like to ask you a question, is it necessary to upload the attachment to the server first and then send it through the server address? Can you send the attachment by streaming, without reading the file from the server. Read the file stream to send, maybe my expression is not clear, I don't know if I understand. Thank you.

**Comment by Synchro** [comment]
No. Email messages have to originate in one place - you can't pull bits from elsewhere (especially on a client that you don't have control over). On the server you can send strings in memory as attachments with PHPMailer - this is commonly done for things like PDF generation, but by the time you receive a POST request with attached files in PHP, PHP has already stored the uploaded files on disk. You can of course save an attachments somewhere else and link to it from the message, but I don't think that's what you're asking for.
