### ISSUE TITLE
Gmail store all mails sent with SMTP

### ISSUE THREAD

**Issue by Tkd-Alex** [PHPMailer/PHPMailer#2022]
Hi, I've followed this code to implement a mail-sender with GMail.
https://github.com/PHPMailer/PHPMailer/blob/c9e4d921d4c555cd4913ca87810dd5adc096ab1c/examples/gmail.phps

All works fine, but I've see that the emails sent with PHPMailer are store in my Sent folder. It's possibile to avoid? obv I've not copied the save_mail($mail) function.

![image](https://user-images.githubusercontent.com/14061593/77776480-5db31980-704e-11ea-9e18-6179587cf5ec.png)

**Comment by Synchro** [comment]
Whether outgoing servers automatically put copies in your sent box is up to the server, so you'd need to find out whether it's possible to disable that within gmail settings. I don't think you can control it from outside, other than by moving messages around with IMAP as in that save_mail example. The fact that script exists suggests that others don't see what you're seeing!

**Comment by Tkd-Alex** [comment]
I've already search on-line, there is no such option on gmail :(

**Comment by Synchro** [comment]
I think you're stuck then - or switch to a service that lets you control this. Gmail is no good for speed or volume anyway.
