### ISSUE TITLE
Back to index

### ISSUE THREAD

**Issue by devandroidrion** [PHPMailer/PHPMailer#2024]
How do I return to index.html after entering an e-mail message?

if (!$mail->send()) {
 echo "Mailer Error: " . $mail->ErrorInfo;
} else {
 echo "Message sent!";
}

**Comment by NiklasBr** [comment]
Your question has nothing to do with PHPMailer, but to answer it anyway, on this line: 

> `echo "Message sent!";`

You can instead use the [header()](https://www.php.net/manual/en/function.header.php) function to redirect anywhere you want.

**Comment by devandroidrion** [comment]
thanks.
