### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by gweinfurther** [PHPMailer/PHPMailer#2025]
I can find no documentation. There's nothing in the wiki or the API documentation.  What exists are circular references, e.g., "go *here* for the documentation, and *here* says to go *there* for documentation.

Examples are good, but they do not offer a complete picture of everything that is possible.

**Comment by Synchro** [comment]
I don't know what you mean. The readme is a good starting point, the generated API documentation covers every single property and method, the example code shows how to use them, and the wiki contains tutorials, an extensive troubleshooting information, and focused articles on specific subjects. I don't know what else you're looking for, but you're very welcome to write whatever it is and submit a PR.
