### ISSUE TITLE
PHPMailer won't connect to my SMTP server.

### ISSUE THREAD

**Issue by LielAmar** [PHPMailer/PHPMailer#2026]
So, I used https://www.smtper.net/ to test my SMTP server and it works perfectly.
I get a success message and receive the mail in my inboxes.

When I try to get the same result with PHPMailer, it just seems to refuse to work.

These are my settings: http://prntscr.com/ruy4o7, getting this: http://prntscr.com/ruy53v
This is my code:
` 
   $mail = new PHPMailer(true);

    try {
      //Server settings
      $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      // Enable verbose debug output
      $mail->isSMTP();
      $mail->Host = '******.ovh.net';
      $mail->SMTPAuth = true;
      $mail->SMTPAutoTLS = true;
      $mail->Username = 'liel@lielamar.com';
      $mail->Password = '*******';
      $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
      $mail->Port = 465;

      //Recipients
      $mail->setFrom('noreply@lielamar.com', 'Liel Amar');
      $mail->addAddress($email, $name);
      $mail->addReplyTo('noreply@lielamar.com', 'Liel Amar');
      $mail->addCC('liel@lielamar.com');
      $mail->addBCC('liel@lielamar.com');

      // Content
      $mail->isHTML(true);                                  // Set email format to HTML
      $mail->Subject = $subject;
      $mail->Body = $message;
      $mail->AltBody = $message;

      $mail->send();
      echo 'Sent :)';
    } catch (Exception $e) {
      echo 'An error occurred. Please try again later.';
    }`

and the problem is:
1. I'm not getting any email
2. I'm not getting an error as well. Seems like my PHP file (I'm using AJAX) is blank.

When I'm trying to use:
```
$mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
$mail->Port = 465;
```
I'm getting the following error: 2020-04-07 19:33:20 SMTP ERROR: Failed to connect to server: (0)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
which is impossible because the credentials are 100% correct.
I check the Troubleshooting page and tried to disable the firewall & add different variables such as SMTPAutoTLS and nothing works.

**Comment by Synchro** [comment]
It’s not impossible at all - the error says that it can’t connect at all, so it’s not getting as far as trying to authenticate. The guide has many suggestions for how you can diagnose problems like this; it’s most likely that your hosting provider is blocking outbound SMTP, though as it’s OVH, they may lift the block if you ask them.

**Comment by Fiwi1265** [comment]
Try to fit this here

**Comment by Fiwi1265** [comment]
Try to fit this here

` $mail->SMTPDebug = SMTP::DEBUG_SERVER;
  $mail->SMTPSecure = **PHPMailer::ENCRYPTION_SMTPS;`

For this

` $mail->SMTPDebug =0;
  $mail->SMTPSecure = 'tls';`

**Comment by Andreadjk** [comment]
Yes it is possible, i have the same problem. everything is correct but it dont work
