### ISSUE TITLE
SMTP connect() failed - SMTP ERROR: Failed to connect to server: Connection refused (111)

### ISSUE THREAD

**Issue by BibinFrancis** [PHPMailer/PHPMailer#2027]
SMTP connection failure error shows when sending mails. The hosing server is go-daddy. If it is server blocking the SMTP;  Using their mail server instead of 'smtp.gmail.com' shall solve the issue?

The following is my code.

`<?php
    use PHPMailer\PHPMailer\PHPMailer;

    if (isset($_POST['submit']) && isset($_POST['email'])) {
        $name=$_POST["name"];
        $email=$_POST["email"];
        $code=$_POST["code"];
        $phone=$_POST["phone"];
        $subject=$_POST["subject"];
        $meesage=$_POST["msg"];
        $target_dir = "uploads/";
        $target_file = $target_dir . basename($_FILES["file"]["name"]);
        $imageFileType = strtolower(pathinfo($target_file,PATHINFO_EXTENSION));
        if($imageFileType != "pdf" && $imageFileType != "doc" && $imageFileType != "txt")
        {
            ?>
            <script>
                alert("Sorry, only pdf, doc & txt files are allowed.");
                window.location="index.php"
            </script>
            <?php
        }
    move_uploaded_file($_FILES["file"]["tmp_name"], $target_file);

        require_once "PHPMailer/PHPMailer.php";
        require_once "PHPMailer/SMTP.php";
        require_once "PHPMailer/Exception.php";

        $mail = new PHPMailer();

        //SMTP Settings
        $mail->isSMTP();
        $mail->SMTPDebug = 4;
        $mail->Host = "smtp.gmail.com";
        $mail->SMTPAuth = true;
        $mail->Username = "something@gmail.com";
        $mail->Password = '************';
        $mail->Port = 587; //465
        $mail->SMTPSecure = "tls"; //ssl

        //Email Settings
        $mail->isHTML(true);
        $mail->setFrom($email, $name);
	    $mail->AddReplyTo($email, $name);
	    $mail->addAddress('something@something.com');
        $mail->Subject = $subject;
        $message = "<!DOCTYPE html>
		<html>
		<head>
			<title></title>
		</head>
		<body>
			<table>
				<tr>
					<th>Name</th>
					<td>".$name."</td>
				</tr>
				<tr>
					<th>Email</th>
					<td>".$email."</td>
				</tr>
				<tr>
					<th>Mobile</th>
					<td>".$code." ".$phone."</td>
				</tr>
				<tr>
					<th>Message</th>
					<td>".$meesage."</td>
				</tr>
			</table>
		</body>
		</html>";

	$mail->Body = $message;

        if ($mail->send()) {
            $status = "success";
            $response = "Email is sent!";
        } else {
            $status = "failed";
            $response = "Something is wrong: <br><br>" . $mail->ErrorInfo;
        }
        echo "$status";
    }
?>

`

this is the debug report which i get in return

2020-04-08 04:01:58 Connection: opening to smtp.gmail.com:587, timeout=300, options=array()
2020-04-08 04:02:09 Connection failed. Error #2: stream_socket_client(): unable to connect to smtp.gmail.com:587 (Connection refused) [/home/uegjoq3hkajh/public_html/beta/PHPMailer/SMTP.php line 349]
2020-04-08 04:02:09 SMTP ERROR: Failed to connect to server: Connection refused (111)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
failed

**Comment by Synchro** [comment]
Please read the troubleshooting guide the error points to. It’s most likely that your hosting provider is blocking outbound SMTP.
