### ISSUE TITLE
Guide is outdated (Using-Gmail-with-XOAUTH2)

### ISSUE THREAD

**Issue by cmdstar** [PHPMailer/PHPMailer#2030]
The guide [Using Gmail with OAuth2](https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2) is from over 2 years ago and seems to be outdated.

Near the start of the guide, where it says **When the project has been created, click the APIs & auth menu, then select the APIs submenu.**, this differs from what I see in my google developer console.

Is there still an APIs & Auth menu?

What do I need to do to get this working?

**Comment by Synchro** [comment]
I don't know. I recommend you find out and then update the guide.

**Comment by cmdstar** [comment]
I updated the guide, but the image I added is broken in the guide.

This is the image I tried to add:

https://imgur.com/TmIE7cR

**Comment by Synchro** [comment]
Thanks - I added that image. You can't do it interactively on the page, you have to clone the wiki repo and add it manually.
