### ISSUE TITLE
umlauts will not shown correctly

### ISSUE THREAD

**Issue by Ghost108** [PHPMailer/PHPMailer#2033]
Hello together,

I am sending a mail with phpmailer and a text like this:

`This is a text with umlauts: ö ä ü`

The result will be:

`This is a text with umlauts: Ã¶ Ã¤ Ã¼ `

Where is my fault?

**Comment by Synchro** [comment]
Set the character set to UTF-8 (it defaults to ISO-8859-1):

    $mail->CharSet = PHPMailer::CHARSET_UTF8;

Then make sure sure all your content (including script files) uses UTF-8.

**Comment by Ghost108** [comment]
It works!
Perfect !
Thanks 👍
