### ISSUE TITLE
Problem with DKIM - Does it fail silently?

### ISSUE THREAD

**Issue by skipper570** [PHPMailer/PHPMailer#2038]
Hi,

I am trying to use DKIM for sending out mails to an SMTP server of OVH.
I am using the following code:

```
    $send_mail->DKIM_domain = 'mydomain.com';
    $send_mail->DKIM_private = '/home/certificates/mydomain.com.priv';
    $send_mail->DKIM_selector = 'april2020.phpmailer';
    $send_mail->DKIM_passphrase = '';
    $send_mail->DKIM_identity = $send_mail->From;
```

I am checking the mails with gmail but they do not have a valid DKIM signature. But I also do not get any error/exception in php. Also if I change the path to my private key to an invalid path I do not get an error or exception instead the mail is just send without DKIM.

Is this the intended behaviour to fail silently? How do I know then if the DKIM settings are working for me?

Thank you!

**Comment by Synchro** [comment]
The decision whether to try to sign happens [here](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L1552), and indeed it does fail silently if you fail any of those checks. Seems like a good opportunity for a PR.

**Comment by dcorazolla** [comment]
I send a PR changing the condition structure for this issue. Trowing an exception if file not found or path not permitted.

```
if (!static::isPermittedPath($this->DKIM_private)
    || !file_exists($this->DKIM_private))
{
    throw new Exception($this->lang('file_open') . $this->DKIM_private, self::STOP_CRITICAL);
}
```
