### ISSUE TITLE
Monitoring sent mails by php mailer

### ISSUE THREAD

**Issue by mahmoodn** [PHPMailer/PHPMailer#2039]
I would like to know how can I implement something to answer the following questions:
1- How can I increment a "sent" email when php mailer is called by a program, here 
Moodle?
2- How can I redirect an SMTP error (when php mailer fails due to any reason) to somewhere else, e.g. something for alerting the user.

**Comment by XL-2000** [comment]
in both cases, you can wrap the actual sending
 `if (!$mail->send()) { ... }`
And log, store in db, execute error handlers, whatever
