### ISSUE TITLE
Message could not be sent.Mailer Error: SMTP connect() failed

### ISSUE THREAD

**Issue by kaweendras** [PHPMailer/PHPMailer#2040]
Hello, This happens today. It was working fine a week ago. I haven't touched the code. But now when I try to send a mail it gives me this **Error Message could not be sent.Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting**. I've tried using isMail(); and SSL at port 486 but still gives me the same error. Thank you!

`           $mail = new PHPMailer;

            //$mail->SMTPDebug = 3;                               // Enable verbose debug output

            $mail->isSMTP();                                      // Set mailer to use SMTP
            $mail->Host = 'smtp.gmail.com';                        // Specify main and backup SMTP servers
            $mail->SMTPAuth = true;                               // Enable SMTP authentication
            $mail->Username = 'jeewa.education.mailer@gmail.com';                 // SMTP username
            $mail->Password = '';                           // SMTP password
            $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
            $mail->Port = 587;                                    // TCP port to connect to
            $mail->setFrom('no-reply@mail.lk', 'mail');
            $mail->addAddress($_POST["email"]);     // Add a recipient
                            
            $mail->isHTML(true);                                  // Set email format to HTML

            $mail->Subject = 'New Account Created';
            $mail->Body    = 'String';
            $mail->AltBody = 'String';

            if(!$mail->send()) {
                                
                 echo 'Message could not be sent.';
                 echo 'Mailer Error: ' . $mail->ErrorInfo;
                   }else {
                        echo 'Message sent.';
                    
                   }

`

**Comment by Synchro** [comment]
Do what it says in the troubleshooting guide the error message points you at. It's likely that:

* Your hosting provider has started blocking outbound SMTP
* Gmail has decided it doesn't like your logins

Setting `SMTPDebug = 3` will reveal what's going on.
