### ISSUE TITLE
Hotmail css style not working like gmail

### ISSUE THREAD

**Issue by madsongr** [PHPMailer/PHPMailer#2041]
Hi, I'm creating some body message with inline styled components. It works great in Gmail but in Hotmail `<a>` tag is not getting style correctly:

`$txt .= '<a href="' . $link . '" target="_blank" style="padding: 10px 15px; color: #ffffff; background-color: #008e97; text-decoration: none;">Download link</a>';
`

I have already changed quotes/double quotes but it does not work too. Gmail it's all great, rendering it so fine. In Hotmail the `<a>` style is applied to the next line component.

**Comment by Synchro** [comment]
Sorry, this has nothing to do with PHPMailer, which simply delivers whatever you put in `Body`. 

Email clients vary enormously, and most of them are terrible for HTML and CSS standards support – much like the web was 20 years ago. Gmail, Hotmail, and Outlook are especially awful, and you should not expect anything to look the same across them without a huge amount of effort. There are services that can help you, such as Email on Acid and Litmus, and many email content experts (EmailMonks, @JenCapstraw on Twitter) that can help you deal with these kind of problems.
