### ISSUE TITLE
Integrate with google-api-php-client

### ISSUE THREAD

**Issue by sadashivdalvi** [PHPMailer/PHPMailer#2048]
I see that we are using OAuth and we have the phpLeague library, but I am already using [Google Api PHP Client](https://github.com/googleapis/google-api-php-client) and I think we can have a wrapper which supports the google api php client as well.

I can work on this just want to know all of your thoughts

Thanks,
Sadashiv.

**Comment by Synchro** [comment]
There is already [an article about doing exactly this in the wiki](https://github.com/PHPMailer/PHPMailer/wiki/Gmail-XOAUTH2-Using-Google-API-Client). If you have any updates or improvements to that, go ahead and edit it; it's entirely open.

**Comment by sadashivdalvi** [comment]
Thanks for the update, I missed that. 

Thanks,
Sadashiv.
