### ISSUE TITLE
PHPMailer doesn't work on BlueHost.

### ISSUE THREAD

**Issue by Brian1111** [PHPMailer/PHPMailer#2055]
PHPMailer works well on GoDaddy and on my localhost; however, it doesn't work on Bluehost.  I have tried everything.  At the beginning PHPMailer did partially work, i.e., it sent an email and I could activate the account, but I couldn't login.  However, now it just shows a blank page or it shows a waiting sign.   When it did partially work the `$mail->SMTPDebug  = SMTP::DEBUG_SERVER;  `  gave  a  detailed report; however, I couldn't see any error in it.  Now the browser simply shows a blank page or a waiting sign.  Bluehost error_log file shows: 
`PHP Fatal error:  Uncaught Error: Class 'SMTP' not found in/home4/username/public_html/vendor_email.php:23`

Here is my code:

`use PHPMailer\PHPMailer\PHPMailer;`
`//use PHPMailer\PHPMailer\SMTP;`
`use PHPMailer\PHPMailer\Exception;`

   ` // Load Composer's autoloader`
   ` require './vendor/autoload.php';`
    `//require './classes/Config.php';`

`function send_email($email=null, $subject=null, $message=null, $header=null) {`

`$mail = new PHPMailer(true);`

`try {`

`//Server Settings`
   ` $mail->SMTPDebug  = SMTP::DEBUG_SERVER; ` 
    `$mail->isSMTP(); `                                           
    `$mail->SMTPAuth   = true;   `                  
   ` $mail->SMTPAutoTLS = true;   `
    `$mail->SMTPSecure = 'tls'; ` 
   ` $mail->Host       = 'mail.mywebsite.com'; `
    `$mail->Port       = ' 465'; `
    `$mail->Username   = 'autoreply@mywebsite.com';   `                 
   ` $mail->Password   = 'secret'; `

  ` //Recipients`
  `  $mail->setFrom('autoreply@mywebsite.com');`
    `$mail->addAddress($email);` 

   ` // Content`
  `  $mail->isHTML(true);       `                         
   ` $mail->Subject = $subject;`
    `$mail->Body    = $message; `

 `$mail->send();`
 `echo 'Message has been sent';`
  `} catch (Exception $e) {`
` echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";`
`}`
`}`

I varied this code to multiple settings similar to what is posted on Stackoverflow, YouTube, and to my settings at GoDaddy.  Also, I reinstalled composer and updated PHPMailer from 6.0 to the latest version 6.5; however, nothing works.

**Comment by Brian1111** [comment]
if I don't comment out these:
`use PHPMailer\PHPMailer\SMTP;`
`use PHPMailer\PHPMailer\Exception;`
And use this:
`$mail->SMTPSecure = 'ssl'; `

I  get the following error:
`2020-05-23 20:25:42 SMTP ERROR: Failed to connect to server: (0)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Message could not be sent. Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting`

However, if I use `tsl` instead of `ssl`,   or comment out `//use PHPMailer\PHPMailer\SMTP;`
`//use PHPMailer\PHPMailer\Exception;`,  on the browser I get a blank page or waiting sign where it is eventually gets timed out.

**Comment by Synchro** [comment]
That code has multiple problems, all covered in the troubleshooting guide. Read what it says about encryption settings. `Port` is an integer, not a string, and definitely not one with a leading space.

A white page simply means a fatal PHP error (as expected from the changes you made), and the details will be in the web server’s error log.

**Comment by Brian1111** [comment]
I  changed `Port` to integer.  It did fix many things; now I can see error messages on screen.  But on Bluehost after I fill the registration form, it stays on the same file, i.e., `mywebsite.com/register.php`  But on GoDaddy and on my localhost it goes to `mywebsite.com/message.php`   So `redirect("message.php");` function, which is inside the registration function and comes after successful filling out the registration form, is completely ignored in Bluehost.  I don't know what causes this.  There is no error message on the browser, and Bluehost error_log file is all about session.  

Could you see any other error in my code beside `Port`?   Is Bluehost a good hosting site?  How about if I deploy my code to cloud hosting such as AWS or Digital Ocean?

**Comment by Brian1111** [comment]
I could activate my account in the database, but I cannot login.  This doesn't make sense.   So these two things doesn't makes sense: (1) Bluehost ignores some of my code, and (2) I cannot log into my website even though I could activate the account.

**Comment by Brian1111** [comment]
For your info this is my code now:

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

// Load Composer's autoloader
require './vendor/autoload.php';
require './classes/Config.php';

function send_email($email=null, $subject=null, $message=null, $header=null) {

$mail = new PHPMailer(true);

try {

//Server Settings
    //$mail->SMTPDebug  = SMTP::DEBUG_SERVER;
    $mail->isSMTP();                                            
    $mail->SMTPAuth   = true;                     
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
    $mail->Host       = Config::SMTP_HOST; 
    $mail->Port       = Config::SMTP_PORT;
    $mail->Username   = Config::SMTP_USER;                     
    $mail->Password   = Config::SMTP_PASSWORD;
    $mail->SMTPAutoTLS = false;

**Comment by Synchro** [comment]
You seem to be trying random, unrelated things rather than taking any kind of methodical approach – for example why are you messing with `SMTPAutoTLS`? Cut things back to basics, do the tests from the troubleshooting guide, such as testing your environment outside PHP (telnet, `openssl s_client`, etc), enable PHP debug output (`ini_set('display_errors', true)`).

It's fairly likely that your hosting provider blocks outbound SMTP, and those tests will diagnose that straight away.

**Comment by Brian1111** [comment]
I could fix it.  The problem was with  `$mail->SMTPAutoTLS=false;`.  After I removed it, it fixed everything.  Thanks!

**Comment by Synchro** [comment]
There's still a lot that's nonsensical. `SMTPAutoTLS` may override `SMTPSecure`, but only if `Port` is 25 or 587. `PHPMailer::ENCRYPTION_SMTPS` will only work on `Port` 465, and then `SMTPAutoTLS` doesn't have any effect. I can't tell what you were doing because you didn't include the values for your config options.

**Comment by Brian1111** [comment]
This is how my server settings looks now.  I just noticed that my Port was in string by mistake.  Despite this it did work:

    $mail->isSMTP();                                            
    $mail->SMTPAuth = true;                     
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
    $mail->Host =  'mail.mywebsite.com';
    $mail->Port = 465;
    $mail->Username = 'autoreply@mywebsite.com';                   
    $mail->Password = 'secret';

**Comment by Synchro** [comment]
Those settings look fine.
