### ISSUE TITLE
Network is unreachable (smtp.office365.com)

### ISSUE THREAD

**Issue by scottiericho** [PHPMailer/PHPMailer#2056]
I'm unable to connect to smtp.office365.com via my web server which is an Amazon EC2 instance.

The instance is able to telnet smtp.office365.com on port 587 with no issues. Additionally, I am able to use PHPMailer to send emails via websites on this EC2 instance by sending emails via my own mail server on another EC2 instance. But just not able to connect to 365.

The error logged is:

2020-05-25 02:35:25 Connection: opening to smtp.office365.com:587, timeout=300, options=array()
2020-05-25 02:35:30 Connection failed. Error #2: stream_socket_client(): unable to connect to smtp.office365.com:587 (Network is unreachable) [/home/abico/public_html/libs/PHPMailer/SMTP.php line 321]
2020-05-25 02:35:30 SMTP ERROR: Failed to connect to server: Network is unreachable (101)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

And my config code is as follows:

    $mail = new PHPMailer\PHPMailer\PHPMailer();
    $mail->isSMTP();
    $mail->SMTPDebug = 4;
    $mail->SMTPSecure = "tls";
    $mail->Host = "smtp.office365.com";
    $mail->Port = "587";
    $mail->SMTPAuth = true;
    $mail->Username = "no-reply@domain.com";
    $mail->Password = "12345678";
    $mail->setFrom(SMTP_EMAIL, SMTP_NAME);
    $mail->addReplyTo(SMTP_REPLYTO, SMTP_REPLYTONAME);
    $mail->addAddress($recipient);
    $mail->Subject = $subject;
    $mail->isHTML(true);
    $mail->Body = $message;

**Comment by Synchro** [comment]
That is a bit odd, but one obvious error is that `Port` should be an integer, not a string.

**Comment by scottiericho** [comment]
Hey thanks for the reply!

Yeah I tried that too.

String, integer, it works on every other setup I have tried, including gmail and my own mail servers. Just not office365 :(

**Comment by Synchro** [comment]
This has to be an environment or network issue – there's nothing PHP can do if it can't reach your network. Perhaps check SELinux / AppArmor config?

**Comment by faaktap** [comment]
Got this error when sending from a sudomain.
