### ISSUE TITLE
PHPMailer Office 365

### ISSUE THREAD

**Issue by balvicar** [PHPMailer/PHPMailer#2057]
Hi, I am using PHP mailer and having issue sending out form from the website.
I am using Office 365 and have placed all the right credentials and setting, but it is not sending email out.
It is giving error, but I can not see what it is really. all was working fine when using email when it was set on cPanel. I am using cPanel for the script and have spf for the domain too.

Could someone help please.

Thank in Advance

**Comment by Synchro** [comment]
Rather than ignoring and deleting the information in the issue template, please can you read it and do what it says?
