### ISSUE TITLE
phpmailer breaking DKIM

### ISSUE THREAD

**Issue by rocksfrow** [PHPMailer/PHPMailer#206]
When using the most recent source, or the latest release from this repo, DKIM validation is broken on any emails sent with the PHPMailer class.

DKIM is configured at system level, so I don't/shouldn't need to use any of PHPMailer's DKIM signing features, and I am not.

I confirmed sending messages directly through SMTP, and also using another library like swiftmailer the messages do not have broken DKIM.

**Comment by jcav2** [comment]
Thanks rocksfrow, the bug is still open with Postfix 2.9.6 so the solution is:

$mail->Encoding = '7bit', and the message will pass DKIM.

Thanks !!!

**Comment by jcav2** [comment]
@rocksfrow  and @Synchro 

I have multiple domains in my server, with multiple dkim, when sending without encoding to a hotmail account the source code is:

Authentication-Results: hotmail.com; spf=pass (sender IP is XXX.XXX.XXX.XXX; identity alignment result is pass and alignment mode is relaxed) smtp.mailfrom=info@mydomain.com; dkim=temperror (identity alignment result is pass and alignment mode is relaxed) header.d=mydomain.com; x-hmca=pass header.id=info@mydomain.com

When i put  $mail->Encoding = '7bit'

the source code of email is:

Authentication-Results: hotmail.com; spf=pass (sender IP is XXX.XXX.XXX.XXX; identity alignment result is pass and alignment mode is relaxed) smtp.mailfrom=info@mydomain.com; dkim=pass (identity alignment result is pass and alignment mode is relaxed) header.d=mydomain.com; x-hmca=pass header.id=info@mydomain.com

All my emails to hotmail goes to spam but my spf and dkim are valid.

I am using last code from githug, phpmailer version 5.2.14
Thanks for your comments !!!

**Comment by rocksfrow** [comment]
@jcav2 i'm not sure what you're asking. The second authentication result is valid once you have 7bit set (spf=pass, dkim=pass).

**Comment by rocksfrow** [comment]
@jcav2 thanks for the update!
