### ISSUE TITLE
Sending two subsequent e-mails fails

### ISSUE THREAD

**Issue by bounlu** [PHPMailer/PHPMailer#2067]
Hi,

I have the latest code, wrapped into a function `send_mail` and it works fine. The problem arises when `send_mail` function is called twice from within another function as below:

```
function send_mail($email, $message, $subject) {
    bla bla bla
}

function job_done() {
    bla bla bla

    send_mail($email1, $message1, $subject1);
    return send_mail($email2, $message2, $subject2);
}

job_done();
```

The first e-mail is sent, the second one fails. If I comment out the first one, the second one is sent. It seems `send_mail` function behaves as a return itself and exits.

I also thought this could be Gmail-related issue which blocks sending 2 e-mails within microseconds and added `sleep(10)` between the two `send_mail` function calls, but it didn't help.

Is this the expected behavior or a bug? How to send two subsequent e-mails from the same function in the above case?

---

Have you tried [CSI NGS Portal](https://csibioinfo.nus.edu.sg/csingsportal) yet?

**Comment by XL-2000** [comment]
What does the PHPMailer debugger say? What happens when you put in some logging / debugging in your own code? 
In general: sending subsequent emails works perfectly fine with PHPMailer, I use it to send batches of 100s of mails without any problem.

**Comment by Synchro** [comment]
You've missed out the critical code that's inside send_mail. If you do something like `require 'src/PHPMailer.php';`, inside there, it will cause a fatal error the second time it's called.

**Comment by bounlu** [comment]
Here is the `send_mail` function (a.k.a. 'bla bla bla'):

```
function send_mail($email, $message, $subject)
	{
		$database = new Database();

		require('/lib/mailer/class.phpmailer.php');
		require('/lib/mailer/class.smtp.php');
		$mail = new PHPMailer();
		$mail->IsSMTP();
		$mail->SMTPDebug	= 0;
		$mail->SMTPAuth		= true;
		$mail->SMTPSecure	= "tls";
		$mail->Port		= 587;
		$mail->Host		= "smtp.gmail.com";
		$mail->Username		= "xxxl@gmail.com";
		$mail->Password		= $database->db_password;
		$mail->Subject		= $subject;
		$mail->MsgHTML($message);		
		$mail->AddAddress($email);
		$mail->SetFrom("xxx@gmail.com", "CNP");
		$mail->AddReplyTo("xxx@gmail.com", "CNP");
		$mail->Send();
	}
```

So yes I do call `require` within the function and it's the problem. Why does that break the code second time it's called? Should I use `require_once` instead?

---

Have you tried [CSI NGS Portal](https://csibioinfo.nus.edu.sg/csingsportal) yet?

**Comment by Synchro** [comment]
`require` loads the file every time the code is run, and because the file it loads defines a class, you end up with a duplicate declaration the second time. Yes, changing to `require_once` would solve your immediate problem, but it's inefficient, and a far better approach would be to learn how to use [composer](https://getcomposer.org).

**Comment by bounlu** [comment]
Great, thanks for the explanation and the suggestion. I will do the needful.
