### ISSUE TITLE
Use of PHP's Built-In Function is_readable() Beginning in 6.1.5 Release Results in Erroneous Read Failure for UNC File Paths

### ISSUE THREAD

**Issue by broberts-mrmc** [PHPMailer/PHPMailer#2069]
In the 6.1.5 release, use of PHP's built-in function `is_readable()` (https://www.php.net/manual/en/function.is-readable.php) was added to the `addAttachment()`, `encodeFile()` and possibly others.

This prevents reading UNC file paths in PHP 7.4.7 on Windows, at least, though I've encountered similar issues in earlier PHP releases.  The build-in PHP function `is_readable()` incorrectly reports whether a given UNC file path is readable (i.e. returns `(bool) false`) even when the referenced file is readable by other built-in PHP functions such as `file_get_contents()`, etc.

https://github.com/PHPMailer/PHPMailer/blob/a8bf068f64a580302026e484ee29511f661b2ad3/src/PHPMailer.php#L2964

https://github.com/PHPMailer/PHPMailer/blob/a8bf068f64a580302026e484ee29511f661b2ad3/src/PHPMailer.php#L3149

https://github.com/PHPMailer/PHPMailer/blob/a8bf068f64a580302026e484ee29511f661b2ad3/src/PHPMailer.php#L3152

**Comment by Synchro** [comment]
Why would you not classify this as a PHP on Windows bug?

**Comment by broberts-mrmc** [comment]
@Synchro,

Thanks for the prompt response. I would classify it as both a PHP on Windows bug (more below) but, also considering the existing [buggy] _behavior_ of the PHP built-in function(s), potentially also a bug in packages using the affected function(s) since [IMO] a workaround is possible to preserve functionality for UNC file paths (more on workaround below).

Regarding it being PHP on Windows bug, there are a number of open PHP bug reports pertaining to `is_readable()` and, based on these, the issue appears to affect several PHP releases and runtime platforms:

- https://bugs.php.net/search.php?cmd=display&search_for=is_readable&x=0&y=0

A few examples:

- https://bugs.php.net/bug.php?id=62199 (PHP 7.2.11, Linux)
- https://bugs.php.net/bug.php?id=69834 (PHP 5.6.10, Windows 7)
- https://bugs.php.net/bug.php?id=68926 (PHP 5.6, Windows 8)
- https://bugs.php.net/bug.php?id=70467 (PHP 5.6.13, Windows Server 2012)
- https://bugs.php.net/bug.php?id=73543 (PHP 7.0.13, Windows 10)

I believe built-in PHP function `is_writable()` has similar [buggy] behavior with UNC file paths.

Regard a workaround, I've encountered similar issues with another package used as a file system/persistence abstraction layer, which also provides an method of user-land extension using an "adapter pattern", so I created a "Local" file system adapter (https://github.com/thephpleague/flysystem/pull/1093) that I use in place of the one shipped with the package.

In this adapter, this UNC-path behavior of `is_readable()` is addressed using the following approach:

1. Attempt to detect whether (or not) the input file path is a UNC path
2. If the input file path is a UNC path, use PHP built-in function `file_exists()` to perform the input file path _accessibility check_ rather than `is_readable()`, otherwise use `is_readable()`.

Example here: https://github.com/thephpleague/flysystem/pull/1093/commits/1400fb38864c953e22e906abf2d5ff627fba48a4

**Comment by Synchro** [comment]
I've added a proposed fix for this, which also makes the path checking mechanism more consistent by moving it into a static method. It makes the assumption that UNC paths will always start with `\\`, which seems to be what Flysystem does, and handles the checks in the same way. Please give it a go.

**Comment by broberts-mrmc** [comment]
In my last correspondence with the author of the Flysystem package/project (https://github.com/thephpleague/flysystem/pull/1093), he indicated that any workaround(s) should be implemented in a custom adapter created by package users.

Did that change? Was it addressed directly by Flysystem? If so, I missed that.  Any additional information would be helpful.

**Comment by Synchro** [comment]
I'm not using Flysystem, but we share the same problem. I implemented the same thing as you wrote in [the link you posted](https://github.com/thephpleague/flysystem/commit/1400fb38864c953e22e906abf2d5ff627fba48a4), but I see that while it's a commit in the Flysystem project, it appears somehow orphaned (an abandoned PR?).

Anyway, code that does the same thing you wrote is now in the PHPMailer master branch. I don't have a Windows setup or anything that uses UNC paths to test on, so could you give it a try?

**Comment by broberts-mrmc** [comment]
I will give it a test and let you know.

That’s correct. The project lead/maintainer for Flysystem declined to merge the pull request I submitted (https://github.com/thephpleague/flysystem/pull/1093) indicating any workaround(s) ought be implemented in a custom adapter created by package users.

Ben Roberts
IT Development Manager
Martin Resource Management Corporation
Martin Midstream Partners L.P. (NASDAQ: MMLP)
903-983-5191 // OFFICE
903-988-3891 // FAX
ben.roberts@martinmlp.com<mailto:ben.roberts@martinmlp.com>

CONFIDENTIALITY NOTICE: The information contained in this electronic mail transmission (and/or the accompanying documents) is confidential and may be subject to the attorney-client privilege, may be privileged work product or may otherwise be proprietary information.  This information is intended solely for the exclusive use of the addressee(s).  If you are not the intended recipient, you are hereby notified that possession, disclosure, copying, distribution or the taking of any action in reliance on the contents of this transmission is unauthorized and strictly prohibited.  If you have received this transmission in error, please immediately notify me by telephone (at the number above) to arrange for the return or destruction of this transmission.

**Comment by Synchro** [comment]
To be fair it's Flysystem's job to implement things in an abstract way, however, PHPMailer is much more concrete and straightforward (which has its own issues), so I have no issues with incorporating this change directly! This issue has also come up in the past (#500), but as you can see it has come back to haunt us! Hopefully it's fixed this time, and it's better to have refactored the check into a method so it's more consistent.

**Comment by broberts-mrmc** [comment]
Sure, I respect the stance taken by Flysystem's project lead/maintainer, and it makes sense (i.e. is reasonable), in my opinion, especially given the entire premise of the project is to provide an abstraction layer and supports extensibility using the adapter pattern.

**Comment by broberts-mrmc** [comment]
It appears your fix is in that branch (only) at this point, correct? No release/tag as yet? 

Branch: https://github.com/PHPMailer/PHPMailer/commit/e2e07a355ee8ff36aba21d0242c5950c56e4c6f9

We include PHPMailer as a Composer-managed dependency, so I think I'll have to create a branch (on our end) so we can "hack things up" a little to incorporate this copy of the source (instead of the Composer-managed, autoloaded release we have now), possibly with a direct Git clone or something and test with it on one of our non-production server instances.

I'll keep you posted. I hope to have some results for you later today.

**Comment by broberts-mrmc** [comment]
Looks like Composer can handle "requiring" branches: https://getcomposer.org/doc/articles/aliases.md#why-aliases-, so may be a little easier than I was thinking.

**Comment by Synchro** [comment]
Is this working for you?

**Comment by broberts-mrmc** [comment]
This is still on my to-do list. I apologize.

I should have some test result for you this week.

**Comment by broberts-mrmc** [comment]
Marcus: I tested your commit (https://github.com/PHPMailer/PHPMailer/commit/e2e07a355ee8ff36aba21d0242c5950c56e4c6f9) on one of non-prod. instances and the issue I reported with attaching files specified using a UNC path appears to be resolved.

**Comment by broberts-mrmc** [comment]
Marcus: Might this get merged soon and, if so, make it into the next minor/patch release? If so, when might that take place?

**Comment by Synchro** [comment]
Yes, there's quite a lot of WIP that's built up lately, and I've been sort of waiting for your confirmation here, so I'll tag a release tomorrow.

**Comment by broberts-mrmc** [comment]
Thanks!

**Comment by Synchro** [comment]
I've just tagged a new release including this change. Have a good weekend!

**Comment by broberts-mrmc** [comment]
Thanks, Marcus! Likewise!
