### ISSUE TITLE
Sir i am getting error,  Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

### ISSUE THREAD

**Issue by Biswaranjana** [PHPMailer/PHPMailer#2073]
// Instantiation and passing `true` enables exceptions
	$mail = new PHPMailer(true);

	try {
	    //Server settings
	   // $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      // Enable verbose debug output
	   //$mail->SMTPDebug = 2;
	    $mail->isSMTP();                                            // Send using SMTP
	    $mail->Host       = ' smtp.gmail.com';                    // Set the SMTP server to send through
	   //$mail ->Host =' localhost';
	    $mail->SMTPAuth   = true;                                   // Enable SMTP authentication
	    $mail->Username   = 'biswaranjannaik@gmail.com';                     // SMTP username
	    $mail->Password   = 'password';                               // SMTP password
	    $mail->SMTPSecure = 'ssl';         // Enable TLS encryption; `PHPMailer::ENCRYPTION_SMTPS` encouraged
	    $mail->Port       = 465;                                    // TCP port to connect to, use 465 for `PHPMailer::ENCRYPTION_SMTPS` above

	    //Recipients
	    $mail->setFrom('biswaranjannaik@gmail.com');
	    $mail->addAddress($emailTo);     // Add a recipient
	    $mail->addReplyTo('biswaranjannaik@gmail.com', 'No reply');
	   
	   /*
	    // Attachments
	    $mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
	    $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name
	`*/```

Please guide me.

**Comment by XL-2000** [comment]
What does the debug logging say? This indicates PHPMailer is unable to connect to your smtp server. Logging should indicate where this problem lies, and please consult the wiki page

**Comment by NiklasBr** [comment]
Did you try https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting?

**Comment by Biswaranjana** [comment]
> What does the debug logging say? This indicates PHPMailer is unable to connect to your smtp server. Logging should indicate where this problem lies, and please consult the wiki page

````
sir, these are the debug report that are showing

2020-06-23 14:54:46 SMTP ERROR: Failed to connect to server: Connection refused (111)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Message could not be sent. Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Biswaranjana** [comment]
> Did you try https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting?

``
i have visited there but did not get any related query. please guide me to get it. thanks

**Comment by Synchro** [comment]
This is your problem:

> Connection refused

Your network is blocking access to that SMTP server, probably because your hosting provider blocks outbound SMTP altogether. [This exact issue](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#smtp-error-could-not-connect-to-smtp-host) is described in detail in the guide, along with instructions for diagnosing it further. It has *nothing* to do with PHPMailer, and everything to do with your hosting provider, so **ask them**.
