### ISSUE TITLE
Unable to catch error - Seek your guidance please

### ISSUE THREAD

**Issue by vinner0** [PHPMailer/PHPMailer#2079]
I am using PHP 5.6 and PHPMailer 6.1.6.
I am unable to capture the Error with my own error message. I have purposely keyed in a wrong email address with a / in it. I want to see it error out, and echo the error. I expect to see "Mailer Error" + the actual error. But I keep getting the error with a date, time, and Invalid Email Address, like "020-07-06 15:05:01	Invalid address:  (to): vp@gmil.com / vp".

Why is the words "Mailer Error: " not coming out displayed.
Also, after an invalid email address, the script seems to die. In my real script, I loop so it can go and process another email, but it stops after it encounters the first error.

Any suggestions are welcome. Thanks.

```

<?php

require_once "vendor/autoload.php";

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;


//PHPMailer Object
$mail = new PHPMailer(true); //Argument true in constructor enables exceptions

//    $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      // Enable verbose debug output
	$mail->SMTPDebug = 4;
    $mail->isSMTP();                                            // Send using SMTP
    $mail->Host       = "actual ip address hidden";                                 // Set the SMTP server to send through
    $mail->SMTPAuth   = false;                                   // Enable SMTP authentication
    $mail->Port       = 25;                                    // TCP port to connect to, use 465 for `PHPMailer::ENCRYPTION_SMTPS` above
$mail->SMTPSecure = false;
$mail->SMTPAutoTLS = false;

//From email address and name
$mail->From = "email@email.com.sg";
$mail->FromName = "My Name";

//To address and name
$mail->addAddress("ve@gmaip.com / vp");

//Send HTML or Plain Text email
$mail->isHTML(true);

$mail->Subject = "Subject Text";
$mail->Body = "<i>Mail body in HTML</i>";
$mail->AltBody = "This is the plain text version of the email content";

try {
    $mail->send();
    echo "Message has been sent successfully";
} catch (Exception $e) {
    echo "Mailer Error: " . $mail->ErrorInfo;
}
?>

```

**Comment by Synchro** [comment]
Looking at the code related to this, I can see that the check for address validity happens [here](https://github.com/PHPMailer/PHPMailer/blob/8d50b49c2d05389cf2d850e9e3ee3f8c8ef87438/src/PHPMailer.php#L1136), and it should throw an exception if you have exceptions enabled, which you do. I'd recommend checking the return value of `addAddress()` to see what's happening.

**Comment by 04wakeup** [comment]
Same here, I also can't catch the error and internal 500 error occurred then can't proceed any more. I wanted to display the proper error message but couldn't. Anybody has solved?

**Comment by Synchro** [comment]
As I said, don't wait for the send, check the address earlier, as in:

```php
if (!$mail->addAddress("ve@gmaip.com / vp")) {
    echo 'Invalid email address';
    exit;
}
```

The timestamp on the error output is due to the formatting of debug output, which is purely informative, not the same as a return value. Don't rely on parsing debug output.

A failure like this will not cause a 500 error, that will be something else – as always when debugging *any* PHP script, check your web servers's error log.
