### ISSUE TITLE
Using SSL in POP3.

### ISSUE THREAD

**Issue by salvatore-esposito** [PHPMailer/PHPMailer#2081]
Is it possible? I read the code but it seems that isn't possibile setting SSL in static method popBeforeSmtp. To connect a Google account it needs to manage ssl otherwise  a bool(false) is back after a timeout.

This is the error: "Server -> Client: &lt;pre&gt;Server reported an error: &lt;/pre&gt;Client -> Server: QUIT"

And I attached a little code example.

![pop](https://user-images.githubusercontent.com/26521604/87207748-fd01d100-c30c-11ea-8515-a3de91bd724d.JPG)

**Comment by blackcrack** [comment]
```
code
```
and
<details>  

```
code
```  

</details>  

best

**Comment by Synchro** [comment]
Why are you trying to use POP-before SMTP with google? Almost nobody supports this any more; it was popular at ISPs and in academia in the 1990s, long before POP3 had SSL support, but SMTP has gained far better forms of authentication since then. Are you sure you need to use this?

**Comment by salvatore-esposito** [comment]
@Synchro I read the code and in the POP3 class it looks the only way to create an instance to work with POP prot. Maybe I lost some details because there's no trace of POP in the other classes.

**Comment by blackcrack** [comment]
well, it's nice to have some possibility also, if this need, it is there.. (and imho disturbs nobody if is supported and the code is into)

**Comment by salvatore-esposito** [comment]
I tried this too:

`$pop3 = new POP3;
echo $pop3->connect('pop.gmail.com',995,60);
`

To see if I can connect but nothing

I used xdebug to figure out what was wrong:

> TRACE START [2020-07-11 07:06:50]
>     0.0076     394736     -> PHPMailer\PHPMailer\POP3->connect($host = 'pop.gmail.com', $port = 995, $tval = 60) /home/vagrant/shared/pop3/index.php:9
>     0.0078     395112       -> set_error_handler(array (0 => class PHPMailer\PHPMailer\POP3 { public $do_debug = 0; public $host = NULL; public $port = NULL; public $tval = NULL; public $username = NULL; public $password = NULL; protected $pop_conn = NULL; protected $connected = FALSE; protected $errors = array (...) }, 1 => 'catchWarning')) /home/vagrant/shared/pop3/vendor/phpmailer/phpmailer/src/POP3.php:226
>     0.0079     395808        >=> NULL
>     0.0080     395856       -> fsockopen('pop.gmail.com', 995, 0, '', 60) /home/vagrant/shared/pop3/vendor/phpmailer/phpmailer/src/POP3.php:240
>     0.0616     396280        >=> resource(9) of type (stream)
>     0.0618     396280       -> restore_error_handler() /home/vagrant/shared/pop3/vendor/phpmailer/phpmailer/src/POP3.php:243
>     0.0620     395904        >=> TRUE
>     0.0622     395904       -> stream_set_timeout(resource(9) of type (stream), 60, 0) /home/vagrant/shared/pop3/vendor/phpmailer/phpmailer/src/POP3.php:256
>     0.0624     395904        >=> TRUE
>     0.0626     395904       -> PHPMailer\PHPMailer\POP3->getResponse($size = ???) /home/vagrant/shared/pop3/vendor/phpmailer/phpmailer/src/POP3.php:259
>     0.0628     395904         -> fgets(resource(9) of type (stream), 128) /home/vagrant/shared/pop3/vendor/phpmailer/phpmailer/src/POP3.php:331
>    10.1116     404096          >=> FALSE
>    10.1122     404096        >=> FALSE
>    10.1127     404096       -> PHPMailer\PHPMailer\POP3->checkResponse($string = FALSE) /home/vagrant/shared/pop3/vendor/phpmailer/phpmailer/src/POP3.php:261
>    10.1132     404096         -> strpos(FALSE, '+OK') /home/vagrant/shared/pop3/vendor/phpmailer/phpmailer/src/POP3.php:369
>    10.1137     404096          >=> FALSE
>    10.1141     404096         -> PHPMailer\PHPMailer\POP3->setError($error = 'Server reported an error: ') /home/vagrant/shared/pop3/vendor/phpmailer/phpmailer/src/POP3.php:370
>    10.1146     404472        >=> FALSE
>    10.1151     404424      >=> FALSE
>    10.1154     404424     -> xdebug_stop_trace() /home/vagrant/shared/pop3/index.php:10
>    10.1156     404456
> TRACE END   [2020-07-11 07:07:00]

It seems it's not able to connect, maybe for SSL.

**Comment by Synchro** [comment]
You still have not said what you're trying to do. The POP class provided with PHPMailer is very limited; it's not a general POP implementation, and it definitely won't work with gmail because they don't support pop-before-SMTP.
