### ISSUE TITLE
There is no requirement for a warning about the presence of a loaded ctype module

### ISSUE THREAD

**Issue by IlyaIndigo** [PHPMailer/PHPMailer#2084]
In PHPMailer.php, line 1730 "if (!ctype_alnum($c) && strpos('@_-.', $c) === false) {" uses the ctype_alnum() function.
To use the ctype_ * functions, you need a loaded ctype module in PHP.
In PHP for Windows, it is always loaded by default, but in other operating systems it may not be loaded.
The situation is aggravated by the fact that nowhere in the description of the library is it indicated that it requires the ctype module and does not check its presence when the library is connected, which leads to an error that is not immediately visible.

It is necessary either to rewrite this line without using the ctype functions, or when connecting the library, check for the presence of the loaded ctype module refusing to work in its absence.

**Comment by Synchro** [comment]
It's [declared in the `composer.json` file](https://github.com/PHPMailer/PHPMailer/blob/master/composer.json#L30) – it won't even install if you don't have the ctype extension enabled:

```json
    "require": {
        "php": ">=5.5.0",
        "ext-ctype": "*",
        "ext-filter": "*"
    },
```

**Comment by IlyaIndigo** [comment]
And if I do not use composer, but just take the source code from here?
This does not solve the problem!

**Comment by Synchro** [comment]
If you're not using composer, you're already going out of your way to make things more difficult for yourself, so I don't have much sympathy. If you're loading things manually, you can load the polyfill manually too.
