### ISSUE TITLE
Iam not able to reach the SMTP Server Need Help

### ISSUE THREAD

**Issue by Dietrich11** [PHPMailer/PHPMailer#2087]
Using Wordpress  WP SMTP 

https://i.imgur.com/5BWAyMc.png Using those settings from my mail inbox

My site is builed like someone is filling out the form and sending it everysthing into my Mail inbox.

But the Server is not able to connect i need help

**Comment by Synchro** [comment]
When you create an issue on here, there is an issue template that gives you advice and asks you important questions whose answers are needed in order to help you. You deleted it all and posted a vague description with no details or any information about your problem.
