### ISSUE TITLE
The description for Event ID 2 from source PHP-7.4.5 cannot be found

### ISSUE THREAD

**Issue by vespino** [PHPMailer/PHPMailer#2089]
Not a real bug but I recently moved to another server and moved my PHP logs to the Windows event viewer. Since, I have been getting these information events:

"The description for Event ID 2 from source PHP-7.4.5 cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer."

These occur when using PHPMailer which by itself works fine, so I don't see reason for alarm.

Is there a way to disable these events?

**Comment by Synchro** [comment]
I have no idea what this is, and you've not provided enough detail to tell what's going on here, but it sounds more like a PHP problem rather than a PHPMailer problem.

**Comment by XL-2000** [comment]
As you can read at Microsoft, it might a misconfiguration of PHP on a Windows operated server. 
It has nothing to do with PHPMailer itself, that is simply the "caller" of the configuration which triggers the event.

That said, Windows Event console tend to overflow with "issues" which are not issues...
So if everything works fine, I would let it be... and if you have nother more important to do with your time, check your PHP configuration, and check for a more detailed description in the event detail

**Comment by vespino** [comment]
Thanks, think I'll revert to a log file on the server instead of the event viewer. The events thrown include user data (name, email) which I don't like having spread everywhere, that is why I was hoping to find a solution. Seeing this only occurs with PHPMailer I thought it might be some error caused by it.
