### ISSUE TITLE
Troubleshooting documentation

### ISSUE THREAD

**Issue by hemnathmouli** [PHPMailer/PHPMailer#2090]
The latest version doesn't have the appropriate information - https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
However the old commits have the good documentations - https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting/25b3368432a937ade1e590cdd989dd88f728c85f

Not sure if this was a mistake.

**Comment by sanzeeb3** [comment]
That being a publicly editable page, somebody edited.

**Comment by hemnathmouli** [comment]
Thanks for clarifying! @Synchro restored it.
