### ISSUE TITLE
List Unsubscribe

### ISSUE THREAD

**Issue by heydanish** [PHPMailer/PHPMailer#2092]
Hi
I am trying to have list unsubscribe working in gmail with Phpmailer addCustomHeader. it is showing in raw message but not in inbox
kindly guide me in detail plz i am new to it. I have Passed SPF,DKIM,DMARC, 
using godaddy Cpanel Emails and Php Mailer

**Comment by XL-2000** [comment]
Since it is in the raw message, PHPMailer is working fine.
This problem is a know one: the link is only created for senders with a high and trustworthy reputation. This is so, because generating an unsubscribe link in a SPAM email will give the spammer a signal the email is actively used (instead of dead), increasing the amount of SPAM. Thus, only vetted senders can use this option.
The official Google statement being:

> This only works for some senders right now. We're actively encouraging senders to support auto-unsubscribe — we think 100% should. We won't provide the unsubscribe option on messages from spammers: we can't trust that they'll actually unsubscribe you, and they might even send you more spam. So you'll only see the unsubscribe option for senders that we're pretty sure are not spammers and will actually honor your unsubscribe request. We're being pretty conservative about which senders to trust in the beginning; over time, we hope to offer the ability to unsubscribe from more email.

**Comment by Synchro** [comment]
For the unsubscribe link to be shown in popular mail clients, what @XL-2000 said is true, but you also need to implement [the `list-unsubscribe-post` header](https://certified-senders.org/wp-content/uploads/2017/07/CSA_one-click_list-unsubscribe.pdf); `list-unsubscribe` alone is not enough.

**Comment by heydanish** [comment]
Can u please explain with a example how to do this

**Comment by Synchro** [comment]
Please read the article I linked you to, it does exactly that.

**Comment by heydanish** [comment]
I mean with add custom header what will be the right syntax.

**Comment by Synchro** [comment]
The same as you're already doing for list-unsubscribe:

    $mail->addCustomHeader('List-Unsubscribe-Post', 'List-Unsubscribe=One-Click');

You also need to make sure that your unsubscribe page knows what to do with a POST request, though that's not a PHPMailer concern.
