### ISSUE TITLE
Can this be sent asynchronously?

### ISSUE THREAD

**Issue by liushuo1** [PHPMailer/PHPMailer#2093]
Can this be sent asynchronously?

**Comment by XL-2000** [comment]
Please read https://stackoverflow.com/questions/32743260/send-email-asynchronously-via-phpmailer and @Synchro comment

**Comment by Synchro** [comment]
Also read the advice in [this wiki article](https://github.com/PHPMailer/PHPMailer/wiki/Sending-to-lists) as it deals with performance explicitly. Sending via a local mail server will complete in a few milliseconds.
