### ISSUE TITLE
Issue with SMTP Connect.

### ISSUE THREAD

**Issue by jacobnoah** [PHPMailer/PHPMailer#2097]
I have been using PHPMailer for quite some time and I love the ease of use. I have recently started a company and with my software platform have been using PHPMailer in conjunction with GoDaddy. Everything was working great until out of nowhere the mail service stopped working. I have tried everything I can think of but I believe the cPanel admin host is blocking my emails for some reason. Has anyone had this issue before?
<img width="1673" alt="Screen Shot 2020-07-27 at 1 45 58 PM" src="https://user-images.githubusercontent.com/6580052/88573935-843e8c80-d00f-11ea-8a04-b6f62019c0aa.png">

**Comment by Synchro** [comment]
Please read the notes on [sending through GoDaddy](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#smtp-error-could-not-connect-to-smtp-host) and [configuring the cpanel firewall for GoDaddy](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#firewall-redirection) in the troubleshooting guide you were already given links to.
