### ISSUE TITLE
Could not connect to SMTP Host

### ISSUE THREAD

**Issue by Jaos291** [PHPMailer/PHPMailer#2102]
Hi, I'm having some troubles with my phpmailer, like a month ago I could send e-mails without any problem, but today I wanted to do some tests again and suddenly I can't, this is the part of my code that sends the e-mail, also I attached the debug:
$mail = new PHPMailer;

        //Tell PHPMailer to use SMTP
        $mail->isSMTP();

        //Enable SMTP debugging
        // SMTP::DEBUG_OFF = off (for production use)
        // SMTP::DEBUG_CLIENT = client messages
        // SMTP::DEBUG_SERVER = client and server messages
        $mail->SMTPDebug = SMTP::DEBUG_SERVER;

        //Set the hostname of the mail server
        $mail->Host = 'smtp.gmail.com';
        // use
        // $mail->Host = gethostbyname('smtp.gmail.com');
        // if your network does not support SMTP over IPv6

        //Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
        $mail->Port = 587;

        //Set the encryption mechanism to use - STARTTLS or SMTPS
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;

        //Whether to use SMTP authentication
        $mail->SMTPAuth = true;
.
.
.
.
        $mail->send();
//not attaching the body and user and password and etc.
Not really sure whats the problem

![Sin título](https://user-images.githubusercontent.com/60899021/89590301-2c710400-d80d-11ea-8f2e-d8e25118b7c3.png)

**Comment by Synchro** [comment]
Please read the issue template before posting. In this case your exact problem (`STARTTLS` followed by `QUIT`) is described [in the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#certificate-verification-failure) you've been pointed at twice. Most likely your CA bundle is outdated.
