### ISSUE TITLE
duplicate Header Content (Subject and To)

### ISSUE THREAD

**Issue by ks-edv** [PHPMailer/PHPMailer#2104]
I got the error with duplicate Header entries (To and subject) in 6.1.6 and 6.1.7 with php 7.3 and 7.4, for example:

**To: recipient@domain.tld
Subject: Text Subject**
Date: Mon, 10 Aug 2020 10:44:03 +0200
**To: recipient@domain.tld**
From: XXXXX <sender@domain.tld>
**Subject: Text Subject**
Message-ID: <dQ0D9AlAgq9vCmBtKxOzAfAAipHjUTFU6M5lRYqLG4@localhost>
X-Mailer: PHPMailer 6.1.7 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/mixed;
 boundary="b1_dQ0D9AlAgq9vCmBtKxOzAfAAipHjUTFU6M5lRYqLG4"
Content-Transfer-Encoding: 8bit

This is a multi-part message in MIME format.

--b1_dQ0D9AlAgq9vCmBtKxOzAfAAipHjUTFU6M5lRYqLG4
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

This in xampp for Windows and under Debian with php 7.3. There are no errors in Debug with Xdebug on Windows, but in the mailoutput. 

```
 $mail = new phpmailer();
    $mail->SMTPDebug = 2;
    $mail->ContentType = 'text/html; charset=utf-8';


    $mail->isSMTP();
   $mail->SetLanguage ("de", $_SERVER["DOCUMENT_ROOT"]."/phpmailer/language/");
    $mail->Host  = localhost;

 $mail->Mailer="smtp";
   $mail->CharSet = 'UTF-8';

	 $mail->From = $vorgang_db->f("BEARBEITEREMAIL");
	 $mail->FromName = $vorgang_db->f("BEARBEITERNAME");
	 $mail->ReturnPath = $vorgang_db->f("BEARBEITEREMAIL");

	 $mail->Sender = $vorgang_db->f("BEARBEITEREMAIL");
	 $mail->SetFrom($vorgang_db->f("BEARBEITEREMAIL"),$vorgang_db->f("BEARBEITERNAME"));
	 //   $mail->AddAddress($vorgang_db->f("EMAIL"));
      $mail->AddAddress(utf8_encode($kunden_db->f("EMAIL1")));


	 $mail->Subject = "Text Subject: M-".$vorgang_db->f("VORGANGSNUMMER");
    $mail->Body = $message;

   $mail->AddAttachment($filenameangebotmerge,sprintf('FILENAME_%s.pdf',$vorgang_db->f("VORGANGSNUMMER")));
    $mail->send();
 


```

**Comment by Synchro** [comment]
I'm not sure what your'e doing here, but you have some things in your code that are not valid PHP syntax, so I'm surprised this works at all. Lots of other mistakes:

  * The class name is `PHPMailer`, not `phpmailer`; there's no indication that you're importing namespace names correctly.
  * Don't set `Mailer` yourself; `isSMTP()` does that for you.
  * `$mail->Host = localhost;` needs quoting.
  * Don't set `ContentType` for HTML like that, and do not include the charset in there; PHPMailer creates this for you if you call `$mail->isHTML();`.
  * Don't apply `utf8_encode()` to anything; all your code and data should already be in UTF-8, and email addressed can't (directly) contain UTF-8 anyway.
  * Don't set `Sender` if it's the same as your `From` address; it will do nothing.
  * There is no `ReturnPath` property, and you shouldn't be attempting to set one anyway as it's an RFC contravention.
  * You have no error checking _at all_.

You're really best off starting with the code examples provided with PHPMailer; they don't contain any of these mistakes.

Can you show the SMTP transcript?
