### ISSUE TITLE
Error Handling from HELL

### ISSUE THREAD

**Issue by wmclaxton** [PHPMailer/PHPMailer#2106]
What could possibly justify [this type of error handling](https://drive.google.com/open?id=1C3VgohcTO3d4-NwGDP5UQSOvy2CCNbXW), sending deprecation warnings to the screen and not notifying the administrator by email?  PHPMailer does what if not send mails?  I'm disgusted.  People talk about AI overtaking jobs and yet we have this kind of stupidity hampering basic productivity in the software engineering world.

Unless we've fixed it, you can also see the error [on our homepage](https://nextid.com/).

**Comment by wmclaxton** [comment]
It is resolved by my freelancer.  There was an auto update of WP which failed.  Could not even log in.

**Comment by Synchro** [comment]
It's not PHPMailer that's generating the output you're seeing, but Wordpress 5.5. Wordpress in production should be [configured not to display deprecation notices or other error and debug output](https://www.greengeeks.com/tutorials/article/disable-wordpress-php-error-messages/), but that has precisely nothing to do with PHPMailer.

**Comment by wmclaxton** [comment]
Thank you for the recommendation.  I will make the suggested change in 
the wp-config.php file.

Bill Claxton (wmclaxton@gmail.com)
