### ISSUE TITLE
msgHTML method throws exception if empty src or background attributed in $message

### ISSUE THREAD

**Issue by evrpress** [PHPMailer/PHPMailer#2107]
# Problem description

Whenever PHPMailer should embed images by using the msgHTML like

`mail->msgHTML( $message, $basepath );`

it will throw an Exception `Could not access file: [$basePath]` whenever the `$message` contains either `background=""` or `src=""`

# Code to reproduce

```
$message = '<img src="img/valid.jpg"><img src="">';
$basepath = '/var/www/path/to/my/images/';

$mail = new PHPMailer(true);
...
$mail->msgHTML($message, $basepath);
$mail->Send(); ==> throws Exception

```

# Debug output

```
Could not access file: [$basePath]
```

# Possible Solution

Check the `$url` variable in the `msgHTML` method for being empty (around line 4010 in PHPMailer.php):

```
if( empty( $url ) {
    continue;
}
```

**Comment by Synchro** [comment]
I don't think that failing silently is a great solution (there are some other places where PHPMailer does this, and it's generally been considered a bug). The bug here is really in the content that's supplied rather than the handling of it. Exceptions can be caught.

**Comment by evrpress** [comment]
Imo it shouldn't fail as an empty attribute isn't wrong. The script just tries to embed something which isn't there. Maybe we should change the regex in [this line](https://github.com/PHPMailer/PHPMailer/blob/e7acd3d92fa02728c51bf64b90615bffc84815f0/src/PHPMailer.php#L4009) and use a **+** instead of a **\***

```
preg_match_all('/(?<!-)(src|background)=["\'](.*)["\']/Ui', $message, $images);
```

to
```
preg_match_all('/(?<!-)(src|background)=["\'](.+)["\']/Ui', $message, $images);
```

**Comment by Synchro** [comment]
A missing or empty src attribute *is* wrong; it's [a requirement of the HTML spec](https://html.spec.whatwg.org/#the-img-element), which says:

> The src attribute must be present, and must contain a valid non-empty URL potentially surrounded by spaces referencing a non-interactive, optionally animated, image resource that is neither paged nor scripted.

Why would you want to allow an empty value provide given that you have no way to dynamically populate it in an email context, and that it will result in a client-side rendering error?

**Comment by evrpress** [comment]
Thanks for bringing this to my attention!
