### ISSUE TITLE
Using $mail->AddBCC('example@mail.com');

### ISSUE THREAD

**Issue by chome4** [PHPMailer/PHPMailer#2111]
I'm a bit confused. When a form is presented and the 'BCC' field is filled-in, shouldn't the above line of code have NO email in it? I want the user to add his/her own email to which the bcc can be sent.

I have a copy of the standard 'email' field where I want bcc to be:

`<input name="email" type="email" placeholder="bcc">`

Can someone put me right on this?

**Comment by Synchro** [comment]
If you leave it blank, it won't BCC anyone! Pass in the submitted field, from `$_REQUEST['email']`. 

That said, I suspect you're doing this a bit wrong. Take a look at the contact form example in the examples folder for how to handle a contact form properly.

**Comment by chome4** [comment]
> 
> 
> If you leave it blank, it won't BCC anyone! Pass in the submitted field, from `$_REQUEST['email']`.
> 
> That said, I suspect you're doing this a bit wrong. Take a look at the contact form example in the examples folder for how to handle a contact form properly.

OK thanks. Willdo....
