### ISSUE TITLE
Double encoding issue in subject line with utf-8 and us-ascii

### ISSUE THREAD

**Issue by chvillanuevap** [PHPMailer/PHPMailer#2115]
# Problem description:

I recently upgraded my WordPress website to version 5.5. WP 5.5 ships with PHPMailer 6.1.6. I have a plugin that uses the function `wp_mail` to send a test email. I encode the subject line for my email with UTF-8. For example: "Boldermail 2.0 is Now Available!" becomes `=?UTF-8?B?Qm9sZGVybWFpbCAyLjAgaXMgTm93IEF2YWlsYWJsZSE=?=`. The problem is that when I receive the email, the subject line has been encoded again with US-ASCII as: `=?us-ascii?Q?=3D=3FUTF-8=3FB=3FQm9sZGVybWFpbCAyLjAgaXMgTm93I?=  =?us-ascii?Q?EF2YWlsYWJsZSE=3D=3F=3D?=` 

Is this a bug or is it expected behavior? I read issue #1949. I want to avoid using SMTP. Is there a way to work around this?

# Code to reproduce

Set the subject line in PHPMailer to `=?UTF-8?B?Qm9sZGVybWFpbCAyLjAgaXMgTm93IEF2YWlsYWJsZSE=?=`.

`$phpmailer->Subject = '=?UTF-8?B?Qm9sZGVybWFpbCAyLjAgaXMgTm93IEF2YWlsYWJsZSE=?=';`

# Debug output

```
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8
Date: Tue, 18 Aug 2020 21:29:04 +0000
From: Hernan Villanueva <hernan@boldermail.com>
List-Unsubscribe: =?us-ascii?Q?<https://dev.boldermail.com/unsubscribe-success?= =?us-ascii?Q?.php=3Fc=3D1597786144>?=
MIME-Version: 1.0
Message-ID: <TiEmU2QzV27CWIZafTHzQj0DzHZL6jLoUs5wVxjDQ@boldermail.local>
Received: from localhost by mailhog.example (MailHog)
          id YRQUk3IUkezGOxxlgbMh9k_lsIinl_IgmkqCvkWcZes=@mailhog.example; Tue, 18 Aug 2020 15:29:04 -0600
Reply-To: hernan@boldermail.com
Return-Path: <chvillanuevap@MacBook-Pro-chvillanuevap.local>
Subject: =?us-ascii?Q?=3D=3FUTF-8=3FB=3FQm9sZGVybWFpbCAyLjAgaXMgTm93I?=  =?us-ascii?Q?EF2YWlsYWJsZSE=3D=3F=3D?=
To: chvillanuevap@gmail.com
X-Mailer: PHPMailer 6.1.6 (https://github.com/PHPMailer/PHPMailer)
X-PHP-Originating-Script: 501:PHPMailer.php
```

**Comment by Synchro** [comment]
Why would you do that? PHPMailer takes care of encoding for you; you don't need to (and shouldn't) do it yourself. That's kind of the point of using it!

As #1949 says, the `mail()` function has a history of doing bad things, and this intentional RFC2047 encoding is the only transparent way of avoiding corrupting headers (specifically, it allows you to fold lines without adding spaces when they are unfolded), and because mail clients know all about it (the approach PHPMailer uses was taken straight from Apple Mail), it should only be visible in the raw message source, not a rendered message. `mail()` should be avoided, not least because it has some unsolvable security issues and it's slow. If you can use SMTP, do so; `mail()` should be considered a last resort.

As it happens, your subject line is short enough that it will probably not get any encoding applied at all, since it's all ASCII anyway.

**Comment by chvillanuevap** [comment]
Maybe I'm doing something wrong, but if I don't encode the subject line as UTF-8 then any emojis in the text are displayed as square boxes in Outlook 2007. For example, "😀 Hello" displays in Outlook as:

![image](https://user-images.githubusercontent.com/3827771/90578063-8e235d80-e17f-11ea-8415-4868564aba95.png)

However, if I use `=?UTF-8?...` in the subject line the emojis at least show up as text. For example, "Hello😃😄😁😆" displays as:

![image](https://user-images.githubusercontent.com/3827771/90578049-8499f580-e17f-11ea-823a-63024191099e.png)

The issue is also that once the subject line gets encoded as UTF-8, it has over 65 characters, so it triggers the US-ASCII encoding.

**Comment by XL-2000** [comment]
hzve you tried `$encodedutf8subject = mb_encode_mimeheader($unencodedsubject,"UTF-8"); `before setting it?

**Comment by Synchro** [comment]
I just did a test with your example subject line, and it works as expected:

    $mail->Subject = 'Hello😃😄😁😆';
    $mail->CharSet = 'utf-8';

In received message:

    Subject: =?UTF-8?B?SGVsbG/wn5iD8J+YhPCfmIHwn5iG?=

Screen shot in email client:

![image](https://user-images.githubusercontent.com/81561/90738973-d0a78000-e2ce-11ea-9125-3c9a40df8d64.png)

**Comment by Synchro** [comment]
I also tried with a much longer one:

```php
$mail->Subject = 'Hello😃😄😁😆Hello😃😄😁😆Hello😃😄😁😆Hello😃😄😁😆Hello😃😄😁😆Hello😃😄😁😆Hello😃😄😁😆';
```
which encodes correctly into multiple folded lines:

```
Subject: =?UTF-8?B?SGVsbG/wn5iD8J+YhPCfmIHwn5iGSGVsbG/wn5iD8J+YhPCfmIHwn5iGSGU=?=
 =?UTF-8?B?bGxv8J+Yg/CfmITwn5iB8J+YhkhlbGxv8J+Yg/CfmITwn5iB8J+YhkhlbGw=?=
 =?UTF-8?B?b/CfmIPwn5iE8J+YgfCfmIZIZWxsb/CfmIPwn5iE8J+YgfCfmIZIZWxsbw==?=
 =?UTF-8?B?8J+Yg/CfmITwn5iB8J+Yhg==?=
```
and also renders correctly:

![image](https://user-images.githubusercontent.com/81561/90740548-3eec4280-e2cf-11ea-98ba-2f93bbc2ad62.png)

**Comment by chvillanuevap** [comment]
You are absolutely right. I think I got confused when using WordPress < 5.5. I'm sorry for the trouble!
