### ISSUE TITLE
Allow <> als valid Return-Path:

### ISSUE THREAD

**Issue by manitu-opensource** [PHPMailer/PHPMailer#2121]
Sometimes it's useful and needed to have a 

`Return-Path: <>`

header in a mail.

Setting `<>` as `PHPMailer->Sender` is **NOT** possible due to the

`self::isShellSafe()`

check.

We understand the need to catch params that would be passed via Shell, but when using `mail` mode as sending, PHPMailer just passes the parameteres to PHP's mail() function which should be safe to use.

To prevent security issues for the very vast majority of users we suggest to use

`$this->isShellSafe()`

(instead of `self::`) to be able to derive a class from PHPMailer which overrides the check at our own risk.

**Comment by fHYeemRLTX** [comment]
Adding it as a custom header using _addCustomHeader_ works for me using isSendmail(), isMail() and isSMTP():

```
require 'SMTP.php';
require 'PHPMailer.php';
$email = new PHPMailer\PHPMailer\PHPMailer();
$email->SMTPDebug = 2;
#$email->isSendmail();
#$email->isMail();
$email->isSMTP();
$email->Host = '127.0.0.1';
$email->Port = 25;
$email->From = 'sender@test.localdomain';
$email->addAddress('recipient@test.localdomain');
$email->Subject = 'Sending email';
$email->Body = 'This the body';
$email->addCustomHeader('Return-Path', '<>');
$email->Send();
```

**Comment by Synchro** [comment]
I'm glad that works for you, but I'm be **very** suspicious of what you're doing here. You should never be sending *new* messages with a return-path header; it's a direct RFC contravention to do so. The return path header should only ever be added by a *receiving* server, and the address used in it is copied from the SMTP envelope sender, which may be `<>` if the message is a bounce. If you're doing this in PHPMailer, it means you're pretending to be a receiver, and that makes it sound like you're writing a mail server in PHP, which is probably a very bad idea.
