### ISSUE TITLE
Can not send an attached file when fopen is disabled.

### ISSUE THREAD

**Issue by WolverineNa** [PHPMailer/PHPMailer#2122]
Hi, 

I have used PHPMailer for 10 years. It is so good, thanks for the creators and teams.
But, now my server need to disable "fopen" in PHP which is affected "file_get_contents" in PHPmailer 6.1.6.
I try CURL  instead of "file_get_contents". 
Every thing is Okay, sending text, but an attach file cannot be sent.
This is my CURL that I use instead of "file_get_contents":

function file_get_contents_curl($url) {
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_AUTOREFERER, TRUE);
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, TRUE);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);       
    $data = curl_exec($ch);
    curl_close($ch);
    return $data;
}

The problem is in a PHPMailer.php, function encodeFile @ line 3143 ($file_buffer = file_get_contents($path);).
How do I send a file with out "file_get_contents";
Please help me, I try to fix this for a month.

Thank you in advance.
Na.

**Comment by Synchro** [comment]
My main recommendation here would be to switch to a hosting provider that provides a proper PHP config.

Failing that, you can retrieve files any way that you can (curl is fine), but if you can't read or write local files directly at all, it all needs to happen in memory, and PHPMailer provides the `addStringAttachment()` method to allow you to do just that, so you can follow your above code with:

    $mail->addStringAttachment(file_get_contents_curl($url), 'myimage.jpg');

and it should all work out. Bear in mind though that you need to be a bit more careful than I suggest here - you need to do some error checking of the response in case the fetch fails before handing the result to PHPMailer.

**Comment by WolverineNa** [comment]
Thanks Synchro,
I tried your code, but no luck.
`$mail->addStringAttachment(file_get_contents_curl($url), 'myimage.jpg');`
The message is sent (no error), text and file, but an attached files that show in Gmail cannot open.
The attached file in gmail show its name but 0 byte and cannot open (attachfile.jpg)

Please help me.

**Comment by Synchro** [comment]
Fix one bug at a time. First of all try this:

    $mail->addStringAttachment('test', 'test.txt');

That should result in a text file attachment containing the word `test`. If that works you know that attachments work in general.

Now test your retrieval process.

    header('Content-type: image/jpeg');
    echo file_get_contents($url);

That should display your image in your browser.

Only try to send after knowing for sure that both of these are working correctly, at which point you can join them together.
