### ISSUE TITLE
PHP Mailer returning empty refresh token on server but working fine on Local host

### ISSUE THREAD

**Issue by manashsharma20** [PHPMailer/PHPMailer#2126]
![refresh](https://user-images.githubusercontent.com/31251836/92002823-e94b7780-ed5d-11ea-95ac-a58121578846.png)

I am trying to use Oauth with gmail to send emails from a contact form in a website. I need to generate refresh token for which I used get_oauth_token.php. When I tested it on my local machine it works fineand generates a token. But on the webserver I get an empty refresh token. Any help would be appreciated.

**Comment by decomplexity** [comment]
Try revoking the refresh token via the Google account's permissions screen . Then run the server version of get_oauth_token.php again and reauthorise the permissions. Google won't reissue a refresh token unless the old one is revoked or has expired - you just get an empty token.

**Comment by Synchro** [comment]
That's useful info, @decomplexity. I will add it to the wiki article.

**Comment by majana1** [comment]
sfs
