### ISSUE TITLE
communication stops in middle of message for higher amount of data

### ISSUE THREAD

**Issue by shokarta** [PHPMailer/PHPMailer#2127]
Dear all,

i was initialy asking on stakoverflow for whatever im doing wrong:
[https://stackoverflow.com/questions/63700729/php-strange-behaviour-on-if-statement-when-sending-email-via-phpmailer-having-o](https://stackoverflow.com/questions/63700729/php-strange-behaviour-on-if-statement-when-sending-email-via-phpmailer-having-o)

Here is the latest code im testing which is still not working:
```
<?php

	use PHPMailer\PHPMailer\Exception;
	use PHPMailer\PHPMailer\PHPMailer;
	use PHPMailer\PHPMailer\SMTP;

	require_once 'apps/PHPMailer/src/Exception.php';
	require_once 'apps/PHPMailer/src/PHPMailer.php';
	require_once 'apps/PHPMailer/src/SMTP.php';

	include_once('apps/HTMLDOMParser/simple_html_dom.php');

	require_once("../db.php");

	$time_start = microtime(true);

	function clear($var) {
		$var = NULL;
		unset($var);
	}

	// Time when emails were sent last time
	$result_laststamp = $conn->prepare("SELECT sent FROM nl_campaigns_emails ORDER BY sent DESC LIMIT 1", array(PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL));
	$result_laststamp->execute();
	if($result_laststamp->rowCount() > 0) {
		while($row_laststamp = $result_laststamp->fetch(PDO::FETCH_ASSOC)) {

			// data for first qeued campaign
			$result_campaign = $conn->prepare("SELECT id,name,text,amount,period,smtp,user FROM nl_campaigns WHERE status='1' ORDER BY id ASC LIMIT 1", array(PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL));
			$result_campaign->execute();
			if($result_campaign->rowCount() > 0) {

				while($row_campaign = $result_campaign->fetch(PDO::FETCH_ASSOC)) {

					// SMTP Data
					if($row_campaign['smtp']==1 && $row_campaign['user']>0) {

						$result_smtp = $conn->prepare("SELECT * FROM admin_logins WHERE id=:id LIMIT 1", array(PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL));
						$result_smtp->execute(array(":id"=>$row_campaign['user']));
						if($result_smtp->rowCount() > 0) {

							while($row_smtp = $result_smtp->fetch(PDO::FETCH_ASSOC)) {

								// Check if now is the time to send new queue of emails
								if($row_laststamp['sent'] < (time()-($row_campaign['period']*3600))) {

									// Prepare for sending
									$result_emails = $conn->prepare("SELECT id,email FROM nl_campaigns_emails WHERE (id_campaign=:id_campaign AND sent='0') ORDER BY id ASC LIMIT ".$row_campaign['amount'], array(PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL));
									$result_emails->execute(array(":id_campaign"=>$row_campaign['id']));
									if($result_emails->rowCount() > 0) {

										// Prepare the email
										$mail = new PHPMailer(true);
										$mail->CharSet = 'UTF-8';									// UTF8 Encoding
										$mail->Encoding = 'base64';									// Needs to be set with UTF8
										$mail->SMTPDebug = SMTP::DEBUG_SERVER;						// Enable verbose debug output
										$mail->isSMTP();                                            // Send using SMTP
										$mail->Host       = "smtp.forpsi.com";                 // Set the SMTP server to send through
										$mail->SMTPAuth   = true;                                   // Enable SMTP authentication
										$mail->SMTPKeepAlive = true; // SMTP connection will not close after each email sent, reduces SMTP overhead
										$mail->Username   = "noreply@somedomain.cz";                     // SMTP username
										$mail->Password   = "Testheslo123";                // SMTP password
										$mail->SMTPSecure = "tls";
										$mail->Port       = 587;                 // TCP port to connect to, use 465 for `PHPMailer::ENCRYPTION_SMTPS` above
										$mail->isHTML(true);                                  // Set email format to HTML
										$mail->Subject = $row_campaign['name'];
										$mail->setFrom($row_smtp['email'], 'somedomain');
										$mail->addReplyTo('info@somedomain.cz', 'somedomain');
										$mail->Sender = 'noreply@somedomain.cz';

										// YOUTUBE LINK
										$text = new simple_html_dom();
										$text->load($row_campaign['text']);
										foreach($text->find('iframe') as $element) {
											$youtubeid = substr($element->src, strrpos($element->src, "/")+1);
											// Create image instances
											$video = imagecreatefromjpeg('https://img.youtube.com/vi/'.$youtubeid.'/maxresdefault.jpg');
											$button = imagecreatefrompng('../images/youtube_play.png');
											$video = imagescale($video, $element->width, $element->height);
											$button = imagescale($button, imagesx($video)/7.5);

											imagecopy($video, $button, imagesx($video)/2-imagesx($button)/2, imagesy($video)/2-imagesy($button)/2, 0, 0, imagesx($button), imagesy($button));

											// Output and free from memory
											imagejpeg($video, "../images/campaigns/videos/".$youtubeid.".jpg", 95);
											imagedestroy($video);
											imagedestroy($button);
											unset($video);
											unset($button);

											$element->outertext = '<a href="https://www.youtube.com/watch?v='.$youtubeid.'" target="_blank"><img src="http://www.somedomain.cz/images/campaigns/videos/'.$youtubeid.'.jpg" width="'.$element->width.'" height="'.$element->height.'"></a>';
										}
										$modified_text = (string)$text;
										$text->clear();
										clear($text);

										// Array for email counter
										$array_email_ids = array();

										while($row_emails = $result_emails->fetch(PDO::FETCH_ASSOC)) {

											try {

												// Recipient
												$mail->addAddress($row_emails['email']);

												// Attachments
												//$mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
											    //$mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name

												$bottom_text  = "<p align=center style=\"font-size:11px; font-family:Arial; color:#8b8b8b;\">Tento email byl odeslán na adresu <a href=\"mailto:".$row_emails['email']."\">".$row_emails['email']."</a>.<br>";
												$bottom_text .= "Odesilatelem je <a href=\"http://www.somedomain.cz\">somedomain</a> - Máma která ví..., <a href=\"mailto:".$row_smtp['email']."\">".$row_smtp['email']."</a>. Tento e-mail je podle zákona obchodním sdělením.<br>";
												$bottom_text .= "Z odběru se můžete <a href=\"http://www.somedomain.cz/unsubscribe.php?email=".$row_emails['id']."\">odhlásit</a>.</p>";
												$bottom_text .= "<img src=\"http://www.somedomain.cz/view.php?id_campaign=".$row_campaign['id']."&id_email=".$row_emails['id']."\" style=\"visibility: hidden;\">";

												// URL LINK FOR CLICKER ANALYZER
												$doc = new simple_html_dom();
												$doc->load($modified_text);
												foreach ($doc->find('a') as $a) {
													$a->href = 'http://www.somedomain.cz/clicker.php?id_campaign='.$row_campaign["id"].'&id_email='.$row_emails["id"].'&url='.urlencode($a->href);
												}
												$modified_text2 = (string)$doc;
												$doc->clear(); 
												clear($doc);

												// Content
												$mail->Body    = $modified_text2.$bottom_text;
												$mail->AltBody = strip_tags($modified_text2);

												// MessageID
												$data = array(
													'campaign_id' => str_pad($row_campaign['id'], 6, '0', STR_PAD_LEFT),
													'email_id' => str_pad($row_emails['id'], 11, '0', STR_PAD_LEFT),
													'sent' => time(),
												);
												$messageId = '<'.base64_encode(json_encode($data)).'@www.somedomain.cz>';
												$mail->MessageID = $messageId;
												$mail->addCustomHeader('In-Reply-To', $messageId);
												clear($data);

												// SEND Email
												if($mail->send()) {
													// UPDATE the "sent" stamp
													$update = $conn->prepare("UPDATE nl_campaigns_emails SET sent=:sent WHERE id=:id");
													try { $update->execute(array(":id"=>$row_emails['id'], ":sent"=>time())); }
													catch(Exception $error) { die($error->getMessage()); }
													clear($update);

													// ADD sent email to array
													array_push($array_email_ids, $row_emails['id']);
												}

												// CLEAR data
												$mail->clearAddresses();
												$mail->clearAttachments();
											}
											catch (Exception $e) {
												echo "Error sending emails: {$mail->ErrorInfo}";
												die();
											}
										}
										clear($result_emails);

										// CHECK IF STATUS COULD BE CLOSED
										$result_emails_sent = $conn->prepare("SELECT id FROM nl_campaigns_emails WHERE (id_campaign=:id_campaign AND sent='0') ORDER BY id", array(PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL));
										$result_emails_sent->execute(array(":id_campaign"=>$row_campaign['id']));
										if($result_emails_sent->rowCount() == 0) {
											$update = $conn->prepare("UPDATE nl_campaigns SET status=:status WHERE id=:id");
											try { $update->execute(array(":status"=>3, ":id"=>$row_campaign['id'])); }
											catch(Exception $error) { die($error->getMessage()); }
											clear($update);
										}
										clear($result_emails_sent);

										// Print the result
										echo "Sent ".count($array_email_ids)." emails.</div>";
									}
									$mail->SmtpClose();
									clear($mail);
								}
								else {
									echo "Next email queue will be able to send: ".date("j.n.Y H:i:s", $row_laststamp['sent']+($row_campaign['period']*3600));
								}
							}

						}
						else { echo "Error resolving SMTP"; }
						clear($result_smtp);
					}

				}
				clear($result_campaign);
			}
			else {
				echo "No campaign is running";
			}
		}
	}
	clear($result_laststamp);
	clear($conn);

//debug
echo 'Usage End: ' . (memory_get_usage(true) / 1024 / 1024) . ' MB<br>';
echo 'Peak End: ' . (memory_get_peak_usage(true) / 1024 / 1024) . ' MB<br>';
$time_end = microtime(true);
$execution_time = $time_end - $time_start;
echo 'Total Execution Time:'.$execution_time.' seconds';

?>
```
however i thing is not my mistake but a bug...

basicaly, when im sending message one by one in a loop (in the loop i just clearRecipients, set new body and send), using te debug mode, i see the communication stops in the middle (not even the line is finished) and there is no reasponce from the server.
The last line of communication looks:
17:06:40 CLIENT -> SERVER: NTI1MjUyNTNGaWRfY2FtcGFpZ24lMjUyNTI1MjUyNTI1MjUyNTI1MjUyNTI1MjUyNTI1MjU

I have saved the all debug into a text file which is 13MB, can provide in private (dont want to have it in public because of private data). But it wont help much, i can see im having responce from each sent mail which is just fine, but im trying to send 200emails at once, and it always stops around 65th mail...

It is not an issue of execiton time as this takes around 10sec (php is set to 120s) same for memory, limit is 256MB and i tried to debug each loop and seeing max is 24MB...
 - however when i remove the line $mail->send() then everything works as it should (however emails are not set). And this memory debug can be done only if i dont send emails (line with $mail->send() is removed)...

can it be that sending is eating SOOO much memory?
can it be that im being blocked by server for uploading too much data?
 - i guess when 65 emails sends around 13MB, and im sending 200 emails which would be 40MB is not that much, right?

**Comment by XL-2000** [comment]
Why not, instead of having this complex construction, prepare your data and PHPMailer instance once, and then create a single loop to send your emails from based on the data you prepared. As it is now, it is almost impossible to debug and many things can go wrong unrelated tot PHPMailer.
Also, your hosting provider mught not be accepting any more mails or connections because of security and anti-spam settings. This you should check as well...
I have some small sites running where only 10 emails per minute are permitted (just as an example)

**Comment by Synchro** [comment]
This does sound like a problem at the server end. Rate limits are often poorly or inefficiently enforced, and it looks like the server is dropping your connection, doesn't look like a client (i.e. PHPMailer) problem. This isn't something we see elsewhere, and I personally have no trouble sending 200 messages *per second* to my mail server. While your host may have a message count limit, it may also have a connection count/rate limit; keepalive will help with that. Yahoo does this a lot.

PHPMailer isn't very memory efficient (especially with attachments), but it doesn't look like you would be hitting those kind of limits. Definitely try using keepalive though.

**Comment by shokarta** [comment]
Dear all,
Of course I did try SMTPKeepAlive = true; which made no difference...
The SMTP host is claiming he has the limits of:
```
250 mails / minute
1000 mails / hour
20000 mails / day
```
when i reach the limit I should receive this errornote:
```5.1.0 piWs1j0010jifNx01iWsdh policy violation, see https://support.xxxx.com/```
but im not getting any responce, the PHP server stops talking to SMTP server! because the message is cutted in the middle by PHP server, not getting disconnected by SMTP server (i guess)...
So at the moment I still would be probably investigating why php server stops talking, because of phpmailer script?

**Comment by Synchro** [comment]
You can't just set keepalive on, you need to restructure your code to reuse the instance to make it work, and you have not done that in the code you posted. Enabling keepalive while creating a new instance achieves nothing at all, as it will close the connection every time around the loop.

The code that sends data to the server is literally [this one line](https://github.com/PHPMailer/PHPMailer/blob/master/src/SMTP.php#L1096). If that fails or hangs up, it's either that the server dropped the connection (in which case I expect you should get a timeout error, but you may have to wait minutes), or that your whole PHP installation is borked.

**Comment by shokarta** [comment]
I know that..
Im sorry for not showing updated code...
anyway I have updated my initial post here to see the latest code...
I think its quite easy to see how it works and whats happening...

**Comment by Synchro** [comment]
It's still wrong. You are creating the PHPMailer instance *inside* your loops. `$mail = new PHPMailer(true);` and all unchanging config (e.g. `SMTPKeepalive`, `Host`, `isSMTP()`, etc) should be _before_ any of the loops. Base it on [the mailing list example provided with PHPMailer](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps).

**Comment by shokarta** [comment]
to be honest, logicaly it doesnt make sence because each (exept for last one) i just LIMIT 1 loop, therefore it wont loop at all.
However I have moved it out of the loop scoop above everything, now it works fine and it sends 200 emails with no issue at all.
Thank you all for the great support even when I dont understand why being this inside the loop (with limit 1) makes any diference, but it did!
i guess this can be closed... maybe futher investigated why this happens on limit 1 loop, but it works fine now...

**Comment by Synchro** [comment]
It's because every time you create a new PHPMailer instance in that `$mail` variable, the old one gets destroyed, and when it gets destroyed, it drops the SMTP connection and you have to reconnect and authenticate all over again. If you create and re-use one instance and enable keepalive, it only has to create the instance once, and the connection stays open until all your messages are sent. The only thing to look out for is that some servers have a limit of how many messages you can send during a single SMTP session, so you might need to keep count and close and reopen the connection occasionally.
