### ISSUE TITLE
$mail->addBCC alters recipients in To

### ISSUE THREAD

**Issue by Hk1020** [PHPMailer/PHPMailer#2129]
# Problem description

If I add `$mail->addBCC($to)` before `$mail->addAddress($to)` the `$to` recipient is removed from the `to` field. If I `$mail->addAddress($to)` before `$mail->addBCC($to)` then `$to` is left in the `to` field. I'd expect `to` to be left alone in both cases.

# Code to reproduce
```
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

$mail = new PHPMailer;

$mail->From = 'from@example.com';
$to1 = "joe@user.org";
$to2 = "user2@joe.org";
$mail->addBCC($to1); // this removes $to1 from To:
$mail->addAddress($to1);
$mail->addAddress($to2);

$mail->Subject = 'Here is the subject';
$mail->Body    = 'This is the message body';

// for debugging:
$mail->preSend();
$smessage = $mail->getSentMIMEMessage();
echo $smessage;
```

# Debug output
```
Date: Wed, 2 Sep 2020 23:02:50 +0200
From: Root User <from@example.com>
Bcc: joe@user.org
Message-ID: <y6EjmwhPF1dsJfPyk3LYRgEvD91csZLutNsBdonGx4@orion>
X-Mailer: PHPMailer 6.1.7 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/plain; charset=iso-8859-1
To: user2@joe.org
Subject: Here is the subject

This is the message body
```

# Correct behavior:

# Code to reproduce
```
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

$mail = new PHPMailer;

$mail->From = 'from@example.com';
$to1 = "joe@user.org";
$to2 = "user2@joe.org";
$mail->addAddress($to1);
$mail->addAddress($to2);
$mail->addBCC($to1); // now To: is left alone

$mail->Subject = 'Here is the subject';
$mail->Body    = 'This is the message body';

// for debugging:
$mail->preSend();
$smessage = $mail->getSentMIMEMessage();
echo $smessage;
```
# Output

```
Date: Wed, 2 Sep 2020 23:03:35 +0200
From: Root User <from@example.com>
Message-ID: <FfcgmXZAUQ5Op8jC35ya65ackQxCR99IdFEa5gSpRM4@orion>
X-Mailer: PHPMailer 6.1.7 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/plain; charset=iso-8859-1
To: joe@user.org, user2@joe.org
Subject: Here is the subject

This is the message body
```

**Comment by XL-2000** [comment]
Sending an email both AND and as a (blind) copy is equal to mail duplication, which is prevented for you by PHPMailer.
Also, there is no reason to send a copy blind, when it is already know your are sending it plainly.
The way I see it, is a feature, not a bug.

**Comment by Synchro** [comment]
There is something amiss here, but it's definitely more feature than bug. Any address should only appear once across all of to, cc, and bcc.

**Comment by Hk1020** [comment]
> Sending an email both AND and as a (blind) copy is equal to mail duplication, which is prevented for you by PHPMailer.

That’s fine.

> Also, there is no reason to send a copy blind, when it is already know your are sending it plainly.

True but depending on how you create the mail it might be rather cumbersome to prevent. Requires additional logic. 

> The way I see it, is a feature, not a bug.

But then why different behavior for the cases I sent? They should have the same outcome.

Further it’s not ok to remove anything from the To line as the removed entry would not receive a reply to the mail sent. I definitely see this as a bug.

**Comment by Synchro** [comment]
> Further it’s not ok to remove anything from the To line as the removed entry would not receive a reply to the mail sent. I definitely see this as a bug.

I don't agree there. PHPMailer should do what you tell it to. Adding a BCC address that you want replies to go to makes no sense – that would be a bug in your calling code, not PHPMailer.

**Comment by Hk1020** [comment]
> > Further it’s not ok to remove anything from the To line as the removed entry would not receive a reply to the mail sent. I definitely see this as a bug.
> 
> I don't agree there. PHPMailer should do what you tell it to. 

But it doesn’t. I add a recipient to To and PHPMailer removes it. I want it to be there no matter if bcc or not. And certainly not sometimes there sometimes not as my examples demonstrate. 

> Adding a BCC address that you want replies to go to makes no sense

That’s not what I wrote.

**Comment by Synchro** [comment]
I did say "There is something amiss here", however, you should *never* have an address used more than once. If you add a To address, and then add the same address as BCC, it should remove it from the To list.

**Comment by Synchro** [comment]
Looking at the code, it does the latter, and documents it as such:

```php
    /**
     * Add a "To" address.
     *
     * @param string $address The email address to send to
     * @param string $name
     *
     * @throws Exception
     *
     * @return bool true on success, false if address already used or invalid in some way
     */
    public function addAddress($address, $name = '')
    {
        return $this->addOrEnqueueAnAddress('to', $address, $name);
    }
```

and it works exactly as expected:

```php
$mail->addAddress($to1);
$mail->addAddress($to2);
$mail->addBCC($to1);
var_dump($mail->getToAddresses(), $mail->getBccAddresses());
```
```
array(2) {
  [0] =>
  array(2) {
    [0] =>
    string(12) "joe@user.org"
    [1] =>
    string(0) ""
  }
  [1] =>
  array(2) {
    [0] =>
    string(13) "user2@joe.org"
    [1] =>
    string(0) ""
  }
}
array(0) {
}
```

Reordering:

```php
$mail->addBCC($to1);
$mail->addAddress($to1);
$mail->addAddress($to2);
var_dump($mail->getToAddresses(), $mail->getBccAddresses());
```
```
array(1) {
  [0] =>
  array(2) {
    [0] =>
    string(13) "user2@joe.org"
    [1] =>
    string(0) ""
  }
}
array(1) {
  [0] =>
  array(2) {
    [0] =>
    string(12) "joe@user.org"
    [1] =>
    string(0) ""
  }
}
```

So in fact there is no bug here at all, it's working exactly as intended and expected. You just need to work on checking your return values.

**Comment by Hk1020** [comment]
Sorry don’t have time for a detailed reply. But something you wrote isn’t true. My workaround is to add bcc after all tos and nothing gets removed. There are also no duplicates in this case. Please think this over again.

**Comment by Synchro** [comment]
I used your own example code to demonstrate that this does not occur. Your original code makes a false statement:

```php
$mail->addBCC($to1); // this removes $to1 from To:
$mail->addAddress($to1);
$mail->addAddress($to2);
```

That `addBCC` does NOT "remove" anything from the To list, because at the point it's called there are no To addresses to remove. What it *does* do is cause the first call to `addAddress` to fail for the reason stated, but your'e not seeing that because you're not checking return values. Doing it in the reverse order behaves the same: your `addBCC` call is silently failing and you're unaware of it – but there is no visible difference in the resulting message because of the way that BCC works, so you're under the false impression that it's doing something different. There is no bug here.

**Comment by Hk1020** [comment]
> 
> 
> I used your own example code to demonstrate that this does not occur. There _is_ a duplicate – you are using `$to1` for both To and BCC. Your original code makes a false statement:
> 
> ```
> $mail->addBCC($to1); // this removes $to1 from To:
> $mail->addAddress($to1); //<-- this call will fail
> $mail->addAddress($to2);
> ```
> 
> That `addBCC` does NOT "remove" anything from the To list, because at the point it's called there are no To addresses to remove. 

Yes, I see this now.

>What it _does_ do is cause the first call to `addAddress` to fail for the reason stated, but you're not seeing that because you're not checking return values. Doing it in the reverse order behaves the same: your `addBCC` call is silently failing and you're unaware of it – but there is no visible difference in the resulting message because of the way that BCC works, so you're under the false impression that it's doing something different.

Well, the resulting message header **is** different. But not who receives the mail.

>There is no bug here.

Yes, I agree now. Just a little surprising behavior. And I guess the same is true with `addCC`, i.e., the first successfull addition of an address anywhere (To, Cc, Bcc) will cause any subsequent addition of the same address to any such field fail.

**Comment by Synchro** [comment]
> Well, the resulting message header is different. But not who receives the mail.

In the second example that's not true. When the two `addAddress` calls work, the To header will contain those two addresses. The failure of the `addBCC` call will make no difference to the headers because BCC addresses don't appear in headers.

I don't see how it's surprising - What would you expect to happen if you provide the same address for both to and BCC? As far as I can see I would want either first or last to "win" (and PHPMailer chooses the former); anything that allows both to succeed is nonsensical.

Regardless, the moral is to check return values! You should be doing that anyway because these calls will also fail if the addresses are invalid, not only if they are duplicates.

**Comment by Hk1020** [comment]
> 
> 
> > Well, the resulting message header is different. But not who receives the mail.
> 
> In the second example that's not true. When the two `addAddress` calls work, the To header will contain those two addresses. The failure of the `addBCC` call will make no difference to the headers because BCC addresses don't appear in headers.

This is correct as `addBCC` is concerned but if I add `addBCC` before `addAddress` I'll end up with a different To header.

> 
> I don't see how it's surprising - What would you expect to happen if you provide the same address for both to and BCC? As far as I can see I would want either first or last to "win" (and PHPMailer chooses the former); anything that allows both to succeed is nonsensical.

I'd expect an exception but then I am not really a php programmer (return codes are ok of course). And one could argue there should be an option to allow to add just anything there is whether it makes sense or not. But I am not suggesting to add such a "feature". The way it works is fine.

> 
> Regardless, the moral is to check return values! You should be doing that anyway because these calls will also fail if the addresses are invalid, not only if they are duplicates.

That is of course a good suggestion.
