### ISSUE TITLE
Amazon SES signature version 4

### ISSUE THREAD

**Issue by tima1605** [PHPMailer/PHPMailer#2133]
Hi, how to customize signatures version 4 for Amazon Simple Email Service in PHPMailer?

**Comment by Synchro** [comment]
I don't know what you mean by "signature" here.

**Comment by tima1605** [comment]
I mean this https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html
To enhance the security of Amazon SES customers, beginning October 1, 2020, support for Signature Version 3 will be turned off (deprecated) in Amazon SES, and only Signature Version 4 will be supported going forward.
I use PHPMailer. How to customize signatures version 4 for Amazon SES?

**Comment by Synchro** [comment]
Those are for AWS HTTP APIs; PHPMailer doesn't do HTTP at all, only SMTP, so it really doesn't apply. You can still use PHPMailer to generate a message, but it's up to you to submit that over their HTTP API using whatever authentication system they require.

**Comment by tima1605** [comment]
I have PHPMailer configured and running with Amazon SES.
Don't need to change anything?

**Comment by Synchro** [comment]
Not that I can see, unless they are somehow using those new signatures via XOAUTH2 – you'll need to refer to their docs.

**Comment by tima1605** [comment]
Thank you!

**Comment by kapyaar** [comment]
For those coming across this, what you need to do is login to AWS SES, create new credentials (which will automatically be configured to use Sig V4), and then use this smtp username and password in the phpmailer smtp request. This should do the job.
