### ISSUE TITLE
preg_match() expects parameter 2 to be string, array given in D:\xampp\htdocs\Loans4YouFinal\vendor\phpmailer\phpmailer\src\PHPMailer.php on line 1749

### ISSUE THREAD

**Issue by iSarcasmxD** [PHPMailer/PHPMailer#2140]
I have been using phpmailer for about a month now. But today out of no where I was given the above error on submitting my form. It was working perfectly until today. What must have gone wrong Please help. This error is delaying my submission to the client. I cannot find a solution for it.

Yes I have included the following code inside of the phpmailer section.

This is the snippet where I am getting an error
````
if (empty($_POST["name"])) {
            $errors[] = "*Name cannot be empty";
        }
        else 
        {
            $name = test_input($_POST["name"]);
            
                if (!preg_match("/^[a-zA-Z-' ]*$/",$name)) 
                {
                    $errors[] = "*Only letters and white spaces are allowed in Name";
                }
            
        }
````
This is the test_input() function .
````
function test_input($data) 
        {
            $data = trim($data);
            $data = stripslashes($data);
            $data = htmlspecialchars($data);
            return $data;
        }
````

This is my input field in the form
````
<input id="name" name="name" type="text" placeholder="Name" class="form-control input-md" maxlength="30" required>
````

This is the code I added recently which started to give the error. I have added 5 similar snippets recently with just a differnce in the file names for different file uploads.
````
if (array_key_exists('month', $_FILES))
            {
                 foreach ($_FILES["month"]["name"] as $k => $v) 
                 {
                    $mail->addAttachment( $_FILES["month"]["tmp_name"][$k], $_FILES["month"]["name"][$k] );
                 }                
            }
````
These are the 2 lines of error I am getting on my browser & are repeated 4 times.

Warning: preg_match() expects parameter 2 to be string, array given in D:\xampp\htdocs\Loans4YouFinal\vendor\phpmailer\phpmailer\src\PHPMailer.php on line 1749

Notice: Array to string conversion in D:\xampp\htdocs\Loans4YouFinal\vendor\phpmailer\phpmailer\src\PHPMailer.php on line 2968

**Comment by Synchro** [comment]
The code you posted isn't in PHPMailer, and doesn't call PHPMailer?

If that error is coming from your own code, it would have to be happening inside `test_input()`, which you've not posted.

Otherwise, please post the rest of your code.

Line 1749 is around the `isPermittedPath` method, so presumably it's ending up with a path in there, but that doesn't have anything to do with the code you posted?

**Comment by iSarcasmxD** [comment]
@Synchro Please check the question again I have updated it with the function. 
The code is inside phpmailer with all the requires necessities. 
And I wasn't getting an error up until now about line 1749 and the code I posted hasn't changed  from when it was working.
It is just today I suddenly got this error when I added an addAttachment if you like i'll post that snippet to.
Thank you.

**Comment by Synchro** [comment]
Uh, yes! `addAttachment` calls `isPermittedPath`, so that is extremely relevant! I can't diagnose code I can't see!

**Comment by iSarcasmxD** [comment]
@Synchro  I have updated the question please check. Thanks for the help, means a Lot.

**Comment by Synchro** [comment]
This is unsafe code – please read [the PHP docs on how to do file uploads safely](https://www.php.net/manual/en/features.file-upload.php). Specifically you need to be sure to pass content from `$_FILES` through `move_uploaded_file` or `is_uploaded file`. [The send file upload example provided with PHPMailer](https://github.com/PHPMailer/PHPMailer/blob/master/examples/send_file_upload.phps) demonstrates how to do this.

In your code, the `$path` you're passing in to `addAttachment` is in `$_FILES["month"]["tmp_name"][$k]`, which is immediately passed into `isPermittedPath` inside the method. This is an array rather than a string, which is what's causing the error. So you need to check carefully what path you're actually passing in, but only after you have applied `move_uploaded_file` to validate your input.

**Comment by iSarcasmxD** [comment]
@Synchro  I am not saving the file uploaded by the user to any file storage on my machine. Rather I'm directly sending it as an attachment in email to the admin. So, do I need to pass the content through `move_uploaded_file` or ` is_uploaded file` ? If yes can you drop a code snippet on how to do it securely because when I referred to the documentation earlier and tried to do it that way I only got some garbage characters instead of an image in the attachment. Appreciate the help man, Thanks a lot.

**Comment by iSarcasmxD** [comment]
@Synchro I really need your help and if you feel like helping me & make my file uploads secure I have posted a similar question on stack exchange. You can have a look and answer there or here. Since you are the only guy contributing to security in phpmailer, I would really appreciate your help. As I stated in the previous comment I tried the documentation method but I get some garbage characters in the attachment.(I know this is too much to ask for, but I really need some guidance here!)

**Comment by Synchro** [comment]
Break your problem down into smaller pieces, debug one thing at a time. There are two steps here:

1. Upload a file
2. Attach a file to an email

These are _completely_ independent things – you could upload the file and just save it, or email a file you already have. So solve them separately. Before you try to email a file, make sure you _have_ the file to email – if your upload isn't working right, getting the email working isn't going to help.

When you receive a POST request that includes uploaded files, they are already uploaded, they are already saved on disk on your server, and they each have a path, so the upload does **not** go directly from the form to PHPMailer. Where the files are and what they are called is in the `$_FILES` array, but this is potentially untrustworthy, so the safe thing to do is validate them with either of the two functions I mentioned. From the example:

    $uploadfile = tempnam(sys_get_temp_dir(), hash('sha256', $_FILES['userfile']['name']));
    if (move_uploaded_file($_FILES['userfile']['tmp_name'], $uploadfile)) {

Filenames can be an attack route, so it's a important not to trust them, so here I use the user-provided filename to generate a hash (which is also a safe filename), and combine it with the location of the system's temp directory to form a complete, and safe path. That's just a path though, and the file is not there yet, so I pass it to `move_uploaded_file`, which moves it to the new path, but *only if it is also a valid upload*. If it is valid and the move succeeds, we know that it's safe to use that path, and we can pass it to `addAttachment`, which happens a few lines later, inside the `if` statement. There are many other ways of making a safe path, that's just one I chose. There's [an example in the PHP docs](http://php.net/manual/en/features.file-upload.php#114004) that is much more thorough than this.

One issue with this way of generating the temp path is that it loses the original file's extension, which can mean it ends up with a generic `application/octet-stream` MIME type. PHPMailer tries to guess the MIME type from the file extension, but you can set it explicitly yourself if you prefer via [the `$type` parameter to `addAttachment`](http://phpmailer.github.io/PHPMailer/classes/PHPMailer.PHPMailer.PHPMailer.html#method_addAttachment).
You could extract the extension from the original filename and use that – PHPMailer has a static method to do just that called `filenameToType`.

You might also want to use the original filename as the attachment name, even though it's different to the path that we generated. Putting those things together:

    $mail->addAttachment(
        $uploadfile,
        $_FILES['userfile']['name'],
        PHPMailer::ENCODING_BASE64,
        PHPMailer::filenameToType($_FILES['userfile']['name'])
    );

If you're still having trouble, try starting from the other end – take the upload example and alter it to fit your form.

**Comment by iSarcasmxD** [comment]
@Synchro Thank you for such a clear and thorough explanation. Will definitely be able to implement it now. Thank you for your time and effort!
