### ISSUE TITLE
Getting sometimes below error from phpmailer 5.1 version when sending bulk emails to  postfix email server

### ISSUE THREAD

**Issue by akshayguru** [PHPMailer/PHPMailer#2141]
Phpmailer error logs:

Language string failed to load: tls<p>SMTP server error: </p>

postfix logs 

35232:Sep 25 22:06:51 mailserver postfix/smtpd[29749]: SSL_accept error from unknown[x.x.x.x]: Connection reset by peer
35233:Sep 25 22:06:51 mailserver postfix/smtpd[29749]: lost connection after STARTTLS from unknown[x.x.x.x]
35234:Sep 25 22:06:51 mailserver postfix/smtpd[29749]: disconnect from unknown[x.x.x.x]
35235:Sep 25 22:06:51 mailserver postfix/smtpd[29749]: connect from unknown[x.x.x.x]
35236:Sep 25 22:06:51 mailserver postfix/smtpd[29749]: improper command pipelining after EHLO from unknown[x.x.x.x]: HELO sendy.musthweb.ca\r\n
35237:Sep 25 22:06:51 mailserver postfix/smtpd[29706]: warning: TLS library problem: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:340:
35238:Sep 25 22:06:51 mailserver postfix/smtpd[29608]: SSL_accept error from unknown[x.x.x.x]: -1
35239:Sep 25 22:06:51 mailserver postfix/smtpd[29706]: lost connection after STARTTLS from unknown[x.x.x.x]
35240:Sep 25 22:06:51 mailserver postfix/smtpd[29706]: disconnect from unknown[x.x.x.x]
35241:Sep 25 22:06:51 mailserver postfix/smtpd[29589]: SSL_accept error from unknown[x.x.x.x]: -1
35242:Sep 25 22:06:51 mailserver postfix/smtpd[29589]: warning: TLS library problem: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:340:
35243:Sep 25 22:06:51 mailserver postfix/smtpd[29589]: lost connection after STARTTLS from unknown[x.x.x.x]
35244:Sep 25 22:06:51 mailserver postfix/smtpd[29589]: disconnect from unknown[x.x.x.x]
35245:Sep 25 22:06:51 mailserver postfix/smtpd[29608]: warning: TLS library problem: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:340:s

**Comment by akshayguru** [comment]
Below are phpmailer smtpdebug logs 

SMTP -> FROM SERVER:220 mailserver

<br />SMTP -> FROM SERVER: 250-mailserver
250-PIPELINING
250-SIZE 26214400
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN

<br />SMTP -> FROM SERVER:220 2.0.0 Ready to start TLS

<br />SMTP -> FROM SERVER: 250-mailserver
250-PIPELINING
250-SIZE 26214400
250-ETRN
250-AUTH PLAIN LOGIN
250-AUTH=PLAIN LOGIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN

<br />SMTP -> FROM SERVER:250 2.1.0 Ok

<br />SMTP -> FROM SERVER:250 2.1.5 Ok

<br />SMTP -> FROM SERVER:354 End data with <CR><LF>.<CR><LF>

<br />SMTP -> FROM SERVER:250 2.0.0 Ok: queued as 200E340804

**Comment by Synchro** [comment]
This was fixed many years ago. Oddly enough, bugs in old versions get fixed in later versions — upgrade.

**Comment by akshayguru** [comment]
Do i need to use latest version 6.1.0  .I am currently running php 5.5

**Comment by Sweepr** [comment]
> 
> 
> Do i need to use latest version phpmailer 6.1.0 .I am currently running php 5.5

Same answer applies here i guess.. upgrade..  PHP 7.4.9 has been released beginning of this month.

**Comment by akshayguru** [comment]
@Sweepr Does stable branch has the fix for the above mentioned tls issue 
https://github.com/PHPMailer/PHPMailer/tree/5.2-stable
OR
Will it be mandatory to use PHPmailer  6.1.7

**Comment by Sweepr** [comment]
> 
> 
> @Sweepr Does stable branch has the fix for the above mentioned tls issue
> https://github.com/PHPMailer/PHPMailer/tree/5.2-stable
> OR
> Will it be mandatory to use PHPmailer 6.1.7

I think from Version 5.2.23 , but for security sake upgrade to 6.1.7

**Comment by akshayguru** [comment]
@Sweepr @Synchro  thanks

**Comment by Synchro** [comment]
Yes, this should be fixed in the stable branch, but even that is very old now - there's no reason not to use 6.1.7, even though you're using PHP 5.5 (the oldest version supported by 6.1). Be aware that [PHP 5.5 has been out of support for over 4 years](https://www.php.net/eol.php), so you really should upgrade, from both a security and performance standpoint.
