### ISSUE TITLE
Check email Delivery Status Notification (Failure)

### ISSUE THREAD

**Issue by salaNguyen** [PHPMailer/PHPMailer#2142]
Hope everyone help!
Check email did not exist when mail was sent.
Delivery Status Notification (Failure)
What is the result.

Thanks all,

**Comment by Synchro** [comment]
If an address doesn't exist, sending will usually fail immediately, during the send. If it doesn't fail then, you'll need to process the bounce (DSN), which is a separate problem that is not something that PHPMailer deals with.

**Comment by salaNguyen** [comment]
thanks
