### ISSUE TITLE
Question: How to know if PHPMailer is sending TLS 1.2?

### ISSUE THREAD

**Issue by CorneliousJD** [PHPMailer/PHPMailer#2143]
So sorry to submit this here. I do not know where else to ask this question.

I have two different contact forms using PHPMailer to send mail via TLS.
The SMTP service we are using is turning off TLS 1.0 and 1.1 support in Jan 2021, so I need to verify we are sending with TLS 1.2 or not.

I've setup a PHP script that tells me that my PHP instance on my web server supports TLS 1.3 already.
I'm having trouble finding logs of messages sent with PHPMailer though to know if it's actually sending with 1.2 or not.

Two different forms are using two different verions (I did not develop them, freelance developers did a while back).

One is v 5.2.13 and the other is v 6.0.1
Right now with them everything works as it should, and I know they are using TLS, I just do not know which VERSION of TLS they are sending out with.

How can I tell/validate this?

Thank you in advance!

**Comment by Synchro** [comment]
It's down to the version of openssl you have installed with your PHP runtime – run `php -i` or call `phpinfo()` to find the version. TLSv1.3 was added in OpenSSL 1.1.1 in 2018, so look for that, but 1.2 has been around for many years before that – check openssl release notes for the specific version you have (quite likely some flavour of 1.0.2, which is very common, and supports TLSv1.2).

If you run [testssl.sh](https://testssl.sh) from your server (which you can use to test both https and SMTP), it will usually use the same library as your PHP does.

If you send a message using your PHP runtime and PHPMailer, the received headers will usually tell you what encryption it used. For example the notification I got from GitHub for you creating this issue contained this `Received` header:

```
Received: from out-28.smtp.github.com (out-28.smtp.github.com [192.30.252.211])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by mail.example.com (Postfix) with ESMTPS id F00C9605F1
	for <marcus@example.com>; Tue, 29 Sep 2020 19:29:56 +0000 (UTC)
```

Both of the PHPMailer versions you list are now quite old and contain known security vulnerabilities, so I strongly recommend you upgrade.

**Comment by CorneliousJD** [comment]
@Synchro  I'm using OpenSSL/1.1.1g (April 21, 2020), and PHP is currently version 7.1 (I know this is depricated as well, updating it further breaks the mail forms from working sadly).

The above would tell me that I should be working with TLS 1.2 just fine, howerver when I send a message via our SMTP server (which is MailGun) I get the following.

`Received: from webserver (webserveraddress
[ip.address]) by smtp-out-n04.prod.us-west-2.postgun.com with SMTP id
5f738ebe19fe605f2539256e (version=**TLS1**,
cipher=TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA); Tue, 29 Sep 2020 19:45:02 GMT
`

While every other aspect of the process referecnes TLS1_2 in the headers. 
Does this mean PHPMailer is sending out TLS 1.0?

**Comment by CorneliousJD** [comment]
I'm going to assume that yest hat means TLS1.0 because when I test another form (the one using PHPMailer 6.0.1 it actually shows TLS1.3 as the version... Interesting.

I'd like to find a way to hotfix my 5.2.13 version until I can get someone to totally re-write everything.

**Comment by CorneliousJD** [comment]
I repalced it with 5.2.25 and it now shows TLS 1.3 when sending to my test @gmail.com address.

Received: from webserver (hwebserveraddress [ip.address]) by smtp-out-n01.prod.us-east-1.postgun.com with SMTP id 5f7398b5f38f205ebcf6ab91 (version=**TLS1.3**, cipher=TLS_AES_128_GCM_SHA256); Tue, 29 Sep 2020 20:27:33 GMT

I've also updated the 6.0.1 version to 6.1.7 wihtout any breaking changes, so I should be good now - as that shows 1.3 as well.

I think I should be all set now :) Thank you for pointing me to the headers to verify. Glad to see 5.2.25 for whatever reason fixed the 1.0 issue and made it send with 1.3 now. I should be good!

**Comment by Synchro** [comment]
Glad that worked out! 6.0 to 6.1 should be fine; the main difference from 5.2 is how you load it; the API is essentially unchanged.

**Comment by CorneliousJD** [comment]
> Glad that worked out! 6.0 to 6.1 should be fine; the main difference from 5.2 is how you load it; the API is essentially unchanged.

Thanks, I'm glad it's all working too. I'm NOT a developer, especially a PHP one ;) So I'm glad I was able to get this sorted out.
I don't think I'll be able to easily make the switch from 5.2 to 6.1 without hiring someone to do so as it's an already existing code that processes the PHPMailer to send the mail, so I'm not comfortable modifying that myself.
