### ISSUE TITLE
Trying to install PHPMailer

### ISSUE THREAD

**Issue by christhompson07** [PHPMailer/PHPMailer#2146]
Received the message "Use the `composer fund` command to find out more!"

Went to https://github.com/sponsors/synchro and signed up to fund but the install still fails. There's no info on how to indicate you've funded.

HELP!!!

**Comment by Sweepr** [comment]
https://www.wikihow.com/Install-PHPMailer

**Comment by christhompson07** [comment]
That doesn't address my issue... I did run composer require phpmailer/phpmailer and received the message...

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!

**Comment by Sweepr** [comment]
@christhompson07 you didn't mention any issue you just screamed HELP!!!

**Comment by christhompson07** [comment]
I clearly stated

Received the message "Use the composer fund command to find out more!"

Went to https://github.com/sponsors/synchro and signed up to fund but the install still fails. There's no info on how to indicate you've funded.

**Comment by Sweepr** [comment]
"Use the composer fund command to find out more!" That's not an error,.. 

Step 6: 

![image](https://user-images.githubusercontent.com/2857865/94710213-dde07180-0346-11eb-9b76-bda786ed4c74.png)

**Comment by christhompson07** [comment]
I ran composer require phpmailer/phpmailer and received this message...

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
1 package you are using is looking for funding.
Use the composer fund command to find out more!

I ran composer fund and received this message

The following packages were found in your dependencies which publish funding information:

phpmailer
  phpmailer
    https://github.com/sponsors/synchro

Please consider following these links and sponsoring the work of package authors!
Thank you!

I went to https://github.com/sponsors/synchro and funded the project but received no information how how to install phpmailer and bypass the funding message.

I ran php -m and phpmailer is not installed.

**Comment by christhompson07** [comment]
Then why is phpmailer not listed in installed packages for php?

[ec2-user@ip-172-31-40-107 ~]$ php -m
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
readline
Reflection
session
sockets
SPL
sqlite3
standard
tokenizer
zip
zlib

**Comment by Sweepr** [comment]
phpmailer is installed in the vendor folder in your project, it has nothing todo with php module's

**Comment by Sweepr** [comment]
@christhompson07  Try running `composer show phpmailer/phpmailer` inside you project folder.

**Comment by Sweepr** [comment]
I think @Synchro will be very happy you sponsored the project, but this isn't mandatory nor does it help in any way installing phpmailer b.t.w.

**Comment by christhompson07** [comment]
Thank you

**Comment by Synchro** [comment]
I am indeed very happy, thank you very much for sponsoring 😍, but sponsoring has no direct effect on how composer behaves! Composer can't tell whether you are funding a project when you install, so it can't know not to show the funding message.

As @Sweepr said, `php -m` shows compiled in or dynamically loaded PHP modules (usually written in C), not external packages (written in PHP).

The way that you can tell that it's working is when you try to create an instance of PHPMailer, i.e. this code run from your project root should work (it will do nothing) if you've done it correctly:

```php
<?php
use PHPMailer\PHPMailer\PHPMailer;
require './vendor/autoload.php`;
$mail = new PHPMailer();
```

If you get no errors from that, you know that composer is working correctly, and you and use it to install and load any other libraries you might need.
