### ISSUE TITLE
PHPMailer doesn't send emails, but PHP code is working clearly.

### ISSUE THREAD

**Issue by KostLinux** [PHPMailer/PHPMailer#2156]
When i use PHPMailer, this code shows me, that mail was sent successfully, but when i look to my mailbox, it's empty ( also spam folder). I thought the problem was in my mail server, but mail server is working, when i send mail from gmail accounts.
When i send via PHPMailer - mailbox is empty.
```
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require_once "vendor/autoload.php";

//PHPMailer Object
$mail = new PHPMailer(true); //Argument true in constructor enables exceptions

//From email address and name
$mail->From = "my.real.mail@gmail.com";
$mail->FromName = "my real mail";

//To address and name
$mail->addAddress("info@company.domain", "INFO");
$mail->addAddress("myanother.realmail@gmail.com");

//Send HTML or Plain Text email
$mail->isHTML(true);

$mail->Subject = "Subject Text";
$mail->Body = "<i>Mail body in HTML</i>";
$mail->AltBody = "This is the plain text version of the email content";

try {
    $mail->send();
    echo "Message has been sent successfully";
} catch (Exception $e) {
    echo "Mailer Error: " . $mail->ErrorInfo;
}
```

**Comment by Himyu** [comment]
Hey,
I think I got the same problem not long ago, in the end, it turned out, the mail or the login was blocked by Google.
Look in your Google account security area, if there is a notice for login via a less secure app turn on the Option for less secure apps, in the Google account settings.

**Comment by KostLinux** [comment]
Closing issue. I did it with another algoritm and got worked. The problem was, that i tried to send from email that doesn't exist. Now i did something like that: info sends to info and created form in JS.
