### ISSUE TITLE
"received" header

### ISSUE THREAD

**Issue by xstar13** [PHPMailer/PHPMailer#2173]
the sender ip printed to headers:

![](https://i.imgur.com/Ns1nXn2.jpeg)

**Comment by XL-2000** [comment]
What is your question?
If security / privacy is on your mind: IP adresses (and corresponding domains) are public data and used for handling your email, so it should be there...

**Comment by Synchro** [comment]
This is added by the receiver, and you have no control over it as a sender. It's not something you can avoid.
