### ISSUE TITLE
No exception on duplicate recipient address in different fields.

### ISSUE THREAD

**Issue by thgrendel** [PHPMailer/PHPMailer#2176]
# Problem description

If you add a recipient address twice in different fields (e.g. To: and Bcc:) the function addAnAddress returns false but does not raise an exception if $this->exception is set. This leads to returning false with no error message. All other error conditions
will raise exceptions. It would be nice to have an exception here to catch that without having to seek out every usage of the code.

**Comment by Synchro** [comment]
That's a major BC break, and there are many other situations that also do not raise exceptions. Also, having to wrap every other line in a try/catch results in much less readable code, very awkward flow. The effect is also harmless – if you don't check the return value, the message is still sent to exactly the addresses you intended it to; Adding addresses to both To and CC makes no sense to start with.
