### ISSUE TITLE
php mailer is not sending mail to yandexmail,gmail,hotmail systems. but mail is sending to 10 miniute email system

### ISSUE THREAD

**Issue by cybermete** [PHPMailer/PHPMailer#2177]
$mail = new PHPMailer();

        //SMTP Settings
       # $mail->isSMTP();

(when $mail->isSMTP(); active i am getting error.)

There are websites in internet the form of 10 miniute e-mails(like : https://10minutemail.com/), the email is send to 10 miniute e-mails but whenever I try to send e-mails to systems such as yandex and gmail, it does not come in any way (I getting a message as sent. "echo "Email is sent!";" 

sir, i am gonna be insane

        $mail->SMTPDebug  = 2;
        $mail->Host = "smtp.yandex.com";
        $mail->SMTPAuth = true;
        $mail->CharSet = 'UTF-8';
        $mail->Username = "admin@x.com";
        $mail->Password = 'x';
        $mail->Port = 465;
        $mail->SMTPSecure = "ssl"; 

        //Email Settings

        $mail->isHTML(true);
        $mail->setFrom("admin@x.com",$language_translate["mailbot"]);
        $mail->addAddress($uye_eposta);
        $mail->addAddress('x@hotmail.com');
        $mail->addAddress('x@gmail.com');
        $mail->addAddress('admin@x.com');
        $mail->addReplyTo('admin@x.com', 'Adınız');
        $mail->Sender = "admin@x.com";
        $mail->addCustomHeader('X-custom-header', 'custom-value');
        $mail->Subject = "x.com ".$language_translate["mailverify"];
        $mail->Body = "
editing..
düzenleniyor...

please click here hey : </br></br> <a href='https://www.x.com/validation.php?mail=$uye_eposta&code=$token'>click</a>
";

        if ($mail->send()) {
            $status = "success";
            echo "Email is sent!";
        } else {
            $status = "failed";
         echo   "Something is wrong: <br><br>" . $mail->ErrorInfo;
        }

**Comment by Synchro** [comment]
If you disable SMTP sending, you'll get no SMTP debug output. You say "am getting error", but I can't help if you don't show what the errors are.

**Comment by XL-2000** [comment]
Please provide the debug output! Without any detailed input it is hard to guess...
Also, please check if you are using the correct port number (it could be 587 instead of 465)

**Comment by cybermete** [comment]
when i am disable smtp 
e-mail sending to 10 miniute email systems but it's not coming to gmail,hotmail system 

so the port is 465 is working. but i am gonna try for you 587 or not. now

i am gonna active smtp and then i will show you what it's coming as error.

**Comment by cybermete** [comment]
i tried 465 and 587 port 
the ports is working you can try 465 and 587 email sending to 10 miniute email systems. but not sending to hotmail-gmail..

now i am trying "smtp active"


        $mail->isSMTP();

        $mail->SMTPDebug  = 2;

![Unti1241241241412tled](https://user-images.githubusercontent.com/47780057/96836929-53bf9080-144e-11eb-9786-cc5f27ec475a.png)

**Comment by cybermete** [comment]
$mail->isSMTP();

    $mail->SMTPDebug  = 1;


![Screenshot_2](https://user-images.githubusercontent.com/47780057/96837211-b9138180-144e-11eb-8b4c-a0663bac152a.png)

**Comment by Synchro** [comment]
You can only use `ssl` mode with port 465, and `tls` mode with port 587. For debugging, I recommend using `tls` mode, and set `SMTPDebug = 3`.

**Comment by cybermete** [comment]
$mail->isSMTP();
        $mail->SMTPDebug  = 3;
        $mail->Port = 587; 
        $mail->SMTPSecure = "tls";


![Screenshot_3](https://user-images.githubusercontent.com/47780057/96837934-d6951b00-144f-11eb-8d5e-46cdf06891e7.png)

**Comment by Synchro** [comment]
Right, so your server's hosting provider is blocking outbound SMTP. They probably provide an alternative means of sending email (e.g. via their own servers), or may remove the SMTP block if you ask – but this is down to them, not your script or PHPMailer. This is also covered in the troubleshooting guide that's linked from all your error messages.

**Comment by cybermete** [comment]
hello dear human.


the host provider has opened the smtp block.

but 

i am still getting error ;

                                            $mail = new PHPMailer();
                                          #  IsSMTP(); böyle bir class yok dedi haliyle göremedi.. attığın siteden copy paste yaptık.
                                            $mail->isSMTP();
                                            $mail->SMTPDebug = 3; // hata ayiklama: 1 = hata ve mesaj, 2 = sadece mesaj
                                            $mail->SMTPAuth = true;
                                            $mail->SMTPAutoTLS = true;
                                            $mail->SMTPSecure = 'tls'; // Güvenli baglanti icin ssl normal baglanti icin tls
                                            $mail->Host = "smtp.yandex.com"; // Mail sunucusuna ismi
                                            $mail->Port = 587; // Guvenli baglanti icin 465 Normal baglanti icin 587
                                            $mail->IsHTML(true);
                                            $mail->SetLanguage("tr", "phpmailer/language");
                                            $mail->CharSet ="utf-8";
                                            $mail->Username = "admin@x.com"; // Mail adresimizin kullanicı adi
                                            $mail->Password = "x"; // Mail adresimizin sifresi
                                            $mail->SetFrom("admin@x.com", "Isim"); // Mail attigimizda gorulecek ismimiz
                                            $mail->addAddress('xxxn@hotmail.com'); // Maili gonderecegimiz kisi yani alici
                                            $mail->Subject = "Mesaj Basligi"; // Konu basligi
                                            $mail->Body = "Mesaj icerigi"; // Mailin icerigi
                                            if(!$mail->Send()){
                                                echo " HATAMIZ BURADA...           HEY: ".$mail->ErrorInfo;
                                            } else {
                                                echo "Mesaj gonderildi";
                                            }

![image](https://user-images.githubusercontent.com/47780057/96880743-36a6b400-1486-11eb-93e5-b0a5bf410a7d.png)

**Comment by cybermete** [comment]
I've been feeling stupid for 3-4 days
taking the same a lot of mistakes.

![image](https://user-images.githubusercontent.com/47780057/96881386-e419c780-1486-11eb-8650-d5721bc3eed3.png)


i tried a lot of combinasion&test

:(

**Comment by Synchro** [comment]
It still looks like your connections are being blocked. I suggest you try using the tests described in the troubleshooting guide, such as using telnet or openssl to check connections; This will eliminate PHP as a source of your problem.

**Comment by cybermete** [comment]
$mail = new PHPMailer();
                                          #  IsSMTP(); böyle bir class yok dedi haliyle göremedi.. attığın siteden copy paste yaptık.
                                            $mail->isSMTP();
                                            $mail->SMTPDebug = 3; // hata ayiklama: 1 = hata ve mesaj, 2 = sadece mesaj
                                            $mail->SMTPAuth = true;
                                            $mail->SMTPAutoTLS = true;
                                            $mail->SMTPSecure = 'tls'; // Güvenli baglanti icin ssl normal baglanti icin tls
                                            $mail->Host = "smtp.yandex.com"; // Mail sunucusuna ismi
                                            $mail->Port = 587; // Guvenli baglanti icin 465 Normal baglanti icin 587
                                            $mail->IsHTML(true);
                                            $mail->SetLanguage("tr", "phpmailer/language");
                                            $mail->CharSet ="utf-8";
                                            $mail->Username = "admin@cscodep.com"; // Mail adresimizin kullanicı adi
                                            $mail->Password = "5369823506"; // Mail adresimizin sifresi
                                            $mail->SetFrom("admin@cscodep.com", "Isim"); // Mail attigimizda gorulecek ismimiz
                                            $mail->addAddress('remzimeteyukmen@hotmail.com'); // Maili gonderecegimiz kisi yani alici
                                            $mail->Subject = "Mesaj Basligi"; // Konu basligi
                                            $mail->Body = "Mesaj icerigi"; // Mailin icerigi
                                            if(!$mail->Send()){
                                                echo " HATAMIZ BURADA...           HEY: ".$mail->ErrorInfo;
                                            } else {
                                                echo "Mesaj gonderildi";
                                            }
                                            echo '</br>';
                                            echo '</br>';
                                            echo (extension_loaded('openssl') ? 'SSL loaded' : 'SSL not loaded') . "\n";
i have not access for telnet
openssl;
SSL LOADED: 
![image](https://user-images.githubusercontent.com/47780057/96892203-167cf200-1492-11eb-88eb-e734442ad57d.png)

**Comment by cybermete** [comment]
echo (extension_loaded('openssl') ? 'SSL loaded' : 'SSL not loaded') . "\n";
i have not access for telnet 

openssl
ssl loaded

![image](https://user-images.githubusercontent.com/47780057/96892365-41674600-1492-11eb-8987-8eda8936bec1.png)

**Comment by Synchro** [comment]
I mean [start here](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#smtp-error-could-not-connect-to-smtp-host). If your host is blocking SMTP (and it still looks like they are), nothing that you do in your script will make any difference. You could try seeing if you can connect to other servers, such as `smtp.gmail.com` (it doesn't matter if you don't have an account, you just want to see if it will connect at all).

Read the PHPMailer docs I've pointed you at, read your hosting provider's docs, report this issue to them. Beyond that there's nothing I can do.

**Comment by cybermete** [comment]
![image](https://user-images.githubusercontent.com/47780057/96893526-758f3680-1493-11eb-9437-abd31ec1ba6b.png)
Thanks for your time.
i am gonna stay at contact with hosting provider.

all best,
From Turkey 
Remzi Mete

**Comment by cybermete** [comment]
The problem is about the hosting company. 

They are blocking smtp and then they said to me.
go to sendpulse and then you will get smtp you will use in there.

i did everything dkim,spf settings vs..... 

but the problem is SAME!

i mean : 

if you are gonna do a project  DON 'T BUY CHEAP HOSTİNG.

i was paying 30TL per year 
30 TL / 3.69 $ 
 DON'T DO THİS. idk abroad companies 
but in turkey almost every hosting companies they are BAD!

i am 16 years old.
if was i have money. 
if i mean if i could i would. for donate to you :) 

thanks for everything.
All best,
Remzi Mete
