### ISSUE TITLE
Fix Travis no longer reporting on PRs

### ISSUE THREAD

**Issue by jrfnl** [PHPMailer/PHPMailer#2179]
It looks like Travis is slowly closing down their old interface. I have seen a number of repos running into issues with Travis not reporting back on branches/pull requests anymore and by the looks of it, this repo is affected as well.

Based on my experiences with other repos, this is what needs to happen:

> How to get TravisCI working again if it's currently not reporting:
> 1. On GitHub/ repo Settings: Remove the Webhook integration.
> 2. On GitHub/ marketplace: Install the Travis GH App
> 3. On travis-ci.com: sign up for the migrations beta for the organisation
> 4. On travis-ci.com: migrate all relevant repos
> 5. For PRs without status: force push problem PRs (no change needed in the content of the PR)
> 6. Once a first build has finished under the new system, change the protected branches to require "Travis CI - Pull Request" and un-require "continuous integration"

Source: https://twitter.com/jrf_nl/status/1255854838597984262

**Comment by Synchro** [comment]
I've done 1-4 successfully.
For 5, PRs are not in repos I control, so how can I force-push them?
For 6, I don't think I have any protected branches, and I've not seen those settings – so do I need to do anything here?

**Comment by jrfnl** [comment]
> For 5, PRs are not in repos I control, so how can I force-push them?

In most cases, PR branches are open for maintainers of the original repo to edit, so you can check them out and push back to them: 

![image](https://user-images.githubusercontent.com/663378/97217190-2dd81a00-17c7-11eb-8d51-13c50cf41773.png)


> For 6, I don't think I have any protected branches, and I've not seen those settings – so do I need to do anything here?

If you don't have protected branches, you can skip that step, though you _may_ want to set it up anyway - "Settings" -> "Branches" in the GH repo.

**Comment by Synchro** [comment]
Oh, I've never noticed that before, from either end!

**Comment by Synchro** [comment]
Is this working for you now?

**Comment by jrfnl** [comment]
@Synchro We won't know until a new PR has been pulled ;-)

**Comment by jrfnl** [comment]
Just saw #2186, which does show a status, so I guess it's working.

**Comment by Synchro** [comment]
Cool.
