### ISSUE TITLE
Line length in wrapText function

### ISSUE THREAD

**Issue by CharlesGi** [PHPMailer/PHPMailer#2187]
phpmailer version 6.1.8
public function wrapText:
line 2290: 
$buf .= ' ' . $part;
Here an extra space is added.
line 2291:
$message .= $buf . sprintf('=%s', static::$LE);
Here an extra "=" is added.

So why on line 2280: $len = $space_left;

It should be $len = $space_left-2;

On line 2251:
$soft_break = sprintf(' =%s', static::$LE);
Why added a space in soft break?

**Comment by Synchro** [comment]
The space is added because all spaces are removed when the line has `explode` applied to it earlier. The `=` are only inserted when `$qp_mode` is true, when it does quoted-printable encoding, encodes using `=`, for example `=09` is a tab character. Offhand I'm not sure about the space before the soft break `=`, but if you can write a failing test or otherwise demonstrate incorrect output, that would show whether it's wrong or not.

**Comment by CharlesGi** [comment]
I wrote a simple test:

<?php 
include 'wrap.php';

$s = 'abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
$s .= 'abcdefghijklmnopqrstuvwxyz 0123456789 ABCDEFGHIJKLMNOPQRSTUVWXYZ';
$s .= 'abc defghijklmnopqrstuvwxyz 0123456789 ABC DEFGHIJKLMNOPQRSTUVWXYZ';
$output = wrapText($s, 76, $qp_mode = true);
file_put_contents('wrap3.txt', $output);
?>
The first line of wrap3.txt is:
abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmn=<CRLF>
Which is 80 characters, not 76+<CRLF> = 78 characters.
So the function wrapText is buggy.
[wrap.php.txt](https://github.com/PHPMailer/PHPMailer/files/5497398/wrap.php.txt)

**Comment by CharlesGi** [comment]
include 'wrap.php';

$s = 'abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
$s .= 'abcdefghijklmnopqrstuvwxyz 0123456789 ABCDEFGHIJKLMNOPQRSTUVWXYZ';
$s .= 'abc defghijklmnopqrstuvwxyz 0123456789 ABC DEFGHIJKLMNOPQRSTUVWXYZ';
$output = wrapText($s, 76, $qp_mode = true);
file_put_contents('wrap3.txt', $output);

**Comment by CharlesGi** [comment]
CRLF was striped from my comments.
outout first line was 76+2+CRLF=80 characters. expected 76+CRLF = 78 characters.

**Comment by Synchro** [comment]
I can't reproduce that. It breaks the text at 76 chars as requested, then adds the quoted-printable soft line break, giving 79 chars in total. Pulling out the code like that and changing it is really unhelpful, when all you had to do was:

    $mail = new PHPMailer(true);
    $s = 'abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz 0123456789 ABCDEFGHIJKLMNOPQRSTUVWXYZabc defghijklmnopqrstuvwxyz 0123456789 ABC DEFGHIJKLMNOPQRSTUVWXYZ';
    $output = $mail->wrapText($s, 76, $qp_mode = true);
    file_put_contents('wrap3.txt', $output);

I also wonder why you're using this at all, especially with quoted-printable, since PHPMailer uses it internally for that.

**Comment by CharlesGi** [comment]
I am sorry Synchro, I did not think twice.
But Line 2277 is confusing:
$space_left = $length - strlen($buf) - $crlflen;
My understanding is: $space_left = $length - strlen($buf) - 2;
$crlflen ===2 is a coincidence.
I think softbreak "=" should be included in $length. So giving 79 chars in total might not be right.

Thank you very much for your great contribution to phpmailer.

**Comment by CharlesGi** [comment]
[function-wrapText.txt](https://github.com/PHPMailer/PHPMailer/files/5498798/function-wrapText.txt)

Dear Synchro:
Can you please check the attached file. I suspect that somebody(hacker) has tampled with the code.  From line 2248 to line2336. This function simply cannot get job done, for $qp_mode = false.
Charles

**Comment by CharlesGi** [comment]
when $qp_mode = false, (1)it will strip one space at end of each line. (2)one line is 77 characters with two spaces at the end, one space is stripped, three spaces continuously. (3) It will not cut word.
[wrap3.txt](https://github.com/PHPMailer/PHPMailer/files/5498966/wrap3.txt)

input is:
$s = 'abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNO   PQRSTUVWXYZ';//56
$s .= 'abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
$s .= 'abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
$s .= 'abc defghijklmnopqrstuvwxyz   0123456789  ABC   DEFGHIJKLMNOPQRSTUVWXYZ';
$s .= $s;

$output = wrapText($s, 76, $qp_mode = false);

**Comment by CharlesGi** [comment]
I was wrong. I know now why $soft_break = sprintf(' =%s', static::$LE);
because the words are exploded and we need to assemble one space back to the end of the line.
