### ISSUE TITLE
Please add the `Exception` inside Mail class file.

### ISSUE THREAD

**Issue by ttodua** [PHPMailer/PHPMailer#2193]
We have been used the portable phpmailer in the past (which was only 1 file). After new version, it caused us to change our plugin's structures too (as till date we used 1 file in main folder, now we have to create separate folder for just phpmailer). However, the most only thing that I don't like, is the separated Exception class. It would have been good, if the Core (because "->send()" function throws exception from mail class) made a check, if there exists `PHPMailer\Exception` class, then use that, if it doesnt exist (is not loaded) then use the regular Exception, and thus we could avoid having a separate file for just Exception.
Exceptions is the native functionality for any programming language by its nature, and would be nice if we could have PHPMailer one file without needed separate file for just 10-lines exception class. The way I describe,  it will be optional and both party will be happy.

**Comment by Synchro** [comment]
PHPMailer uses the same approach as thousands of other PHP packages, and I'm not going to change this just to suit your narrow use case. While the PHPMailer Exception class is a simple subclass of the base Exception class, it is semantically different and adds significant value. It also sounds like you're not using composer, and these kind of problems are a result of not doing so.

**Comment by ttodua** [comment]
Yes, we didnt user composer for PhpMailer, because it just didn't necessitate it as it was one file. I haven't required to change anything, just to have a simple "exception" function in main class, which would just do `if (class_exists("PHPMailer\Exception") ` then use it, otherwise use native php-exception. 
would have been good, as I saw there were other people who didnt user composer too.

regards anyway with decision. tnx.

**Comment by Synchro** [comment]
That would be a BC break, heading in the wrong direction. PHPMailer has used an exception subclass since 2008, and a separate exception class file since 2015. It sounds like you must be using some very old versions of PHPMailer, which I really wouldn't advise.
