### ISSUE TITLE
connect with proxy

### ISSUE THREAD

**Issue by xstar13** [PHPMailer/PHPMailer#2197]
please i need connect phpmailer to my company proxy before send with smtp, you will save very of my time if introduce any method or library, i am searching about it about 2weeks

**Comment by Synchro** [comment]
Are you sure about that? SMTP doesn't really proxy very well; relaying is much preferred, and PHPMailer works just fine with that. It doesn't have anything to do with your web proxy config requirements.

**Comment by xstar13** [comment]
i used some vpns to check how it work and its ok but i need my company proxy, please i dont knw much about relaying, can do it with a proxy ?

**Comment by xstar13** [comment]
also i have another question, when i set proxy on system or tcp connections it not work for connect to smtps 587, is it why it do connection as udp ?

**Comment by Synchro** [comment]
a) You can't do SMTPS on port 587; you need port 465 for that.
b) It doesn't use UDP.

Relaying is very simple - it's just an SMTP server between you and the ultimate sending server, so instead of going:

    script -> mail server

it goes

    script -> relay mail server -> mail server

If your company has a proxy server for web traffic, they probably have a mail relay too. Ask them about it. It might be better to describe *why* you're trying to do this.

**Comment by xstar13** [comment]
thanks about relay server description, but about first answer do you mean when i use proxy i should connect to 465 ?

**Comment by Synchro** [comment]
It depends on your server. SMTPS is a specific thing - it means you're talking SMTP over implicit TLS, usually on port 465. If your server supports that, use it.

**Comment by xstar13** [comment]
can i use curl instead of fsockopen or stream_socket_client ?

**Comment by Synchro** [comment]
No. curl is an HTTP client, it's no use for SMTP. To talk a raw protocol (like SMTP) over TCP you need fsockopen or stream_socket_client.

**Comment by xstar13** [comment]
now am thinking better to config dedicated server for http api. thanks

**Comment by xstar13** [comment]
i am doing something like social media and about 10ip will be enough for start

**Comment by Synchro** [comment]
This doesn't sound like it has anything to do with PHPMailer.
