### ISSUE TITLE
SetFrom address is not working

### ISSUE THREAD

**Issue by kaushalshriyan** [PHPMailer/PHPMailer#2206]
Hi,

I have set from address as non-prod@mail.develop.yodlee.com in the SMTP settings of Drupal admin dashboard using Gmail SMTP servers. when I receive the email I receive it from mulesoftdevportal@datakiu.com and not non-prod@mail.develop.yodlee.com. In the headers, I see the below information. 

From: Mulesoft Developer Portal <mulesoftdevportal@datakiu.com>
X-Google-Original-From: Mulesoft Developer Portal <non-prod@mail.develop.yodlee.com>

Is there a way to set From address as non-prod@mail.develop.yodlee.com?

The SMTP connection and the mail sending is working fine, except the script is not using the "SetFrom" $email variable for the sender's mail, but instead the "Username" email.

$mail = new PHPMailer;

    $mail->isSMTP();                                   
    $mail->Host = 'smtp.gmail.com';                     
    $mail->SMTPAuth = true;                            
    $mail->Username = 'USERNAME(MY EMAIL)';      
    $mail->Password = 'PASSWORD';                    
    $mail->SMTPSecure = 'tls';                        
    $mail->Port = 587;

    $mail->isHTML(true);

    $mail->SetFrom($email,$name);
    $mail->addAddress($email_received);                 

    $mail->Subject = $subject;
    $mail->Body = $user_msg;

Please suggest.

**Comment by Synchro** [comment]
This is a gmail limitation - you can't send from arbitrary addresses, only the account user name, or any aliases preset within the account. If you try to do it, gmail simply changes the from address to the account owner, as you're seeing.
