### ISSUE TITLE
Undefined function

### ISSUE THREAD

**Issue by sbn111** [PHPMailer/PHPMailer#2208]
//Load PHPMailer library
        $this->load->library('phpmailer_lib');
        
        //PHPMailer object
        $mail = $this->phpmailer_lib->load();

The above code is working in codeignitor 3. But not working in codeignitor 4.

What I need to use instead of the above?

Thank you

**Comment by hexageek1337** [comment]
Codeigniter 4 Load Library will work with call namespace, example

$this->phpmailer = new \App\Libraries\PHPMailer(); **or** $phpmailer  = new \App\Libraries\PHPMailer();

insert code to one controller want use PHPMailer or BaseController for all your controller. But CI 4 already have library for email https://codeigniter.com/user_guide/libraries/email.html

**Comment by sbn111** [comment]
> 
> 
> Codeigniter 4 Load Library will work with call namespace, example
> 
> $this->phpmailer = new \App\Libraries\PHPMailer(); **or** $phpmailer = new \App\Libraries\PHPMailer();
> 
> insert code to one controller want use PHPMailer or BaseController for all your controller. But CI 4 already have library for email https://codeigniter.com/user_guide/libraries/email.html

Thank you for your answer
