### ISSUE TITLE
How to Get debug log in string and show in div 

### ISSUE THREAD

**Issue by arfan-hostingshouse** [PHPMailer/PHPMailer#2210]
![image](https://user-images.githubusercontent.com/50193175/101148946-13078980-3640-11eb-9c5b-9f41031815c8.png)

**Comment by Synchro** [comment]
Most of the default options output debug information directly, however, you can inject your own debug output handler, store it, and make available in some other way, for example by wrapping it in additional HTML tags. You can inject your handler into the [`Debugoutput` property](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L404), and have it do what you like:

    $mail->Debugoutput = function($str, $level) {
        echo "debug level $level; message: $str";
        //Whatever other code you want here
    };
