### ISSUE TITLE
Error codes on connection are not handled

### ISSUE THREAD

**Issue by Synchro** [PHPMailer/PHPMailer#2211]
# Problem description

When connecting to a server, PHPMailer's SMTP class [assumes the connection is successful if it returns anything](https://github.com/PHPMailer/PHPMailer/blob/master/src/SMTP.php#L347), but this is not always the case. The server can return something other than a `220` welcome banner, such as a `554` error, or a `421` deferral, like:

    2020-12-04 11:27:10 SERVER -> CLIENT: 421 4.7.0 Try again later, closing connection.

# Code to reproduce
Connect to any server that fails to start an SMTP session. Unfortunately this is difficult to do reliably given a lack of SMTP testing severs that can generate error codes on demand.

**Comment by Bilel69500** [comment]
This is your ip adress banned ?do not send too fast do not send more than 50 emails at once

**Comment by Synchro** [comment]
_Why_ this happens doesn't matter. This issue is reporting the fact that if it does happen, it's not handled correctly.
