### ISSUE TITLE
Error PHPMailerSend rspam

### ISSUE THREAD

**Issue by Walter250599** [PHPMailer/PHPMailer#2212]
When the mail is sent it does not arrive completely and only sees the spam from the cpanel, all the configuration is correct but at the moment it sends and in others it does not.

SMTP error from remote mail server after end of data:
550 This message was classified as rSPAM

**Comment by XL-2000** [comment]
Emails regarded as spam is outside control of PHPMailer usually...
Content, signing (DKIM) blacklisting etc are the likely parameters to cause spam mark. You should check those, there are numerous good free online tools to check for spam reports (the "why" of the spam marking), I like to use spamcheck.postmarkapp.com

**Comment by Synchro** [comment]
Also check [the docs on avoiding spam folders](https://github.com/PHPMailer/PHPMailer/wiki/Improving-delivery-rates,-avoiding-spam-filters).
