### ISSUE TITLE
GetLastMessageID() return no value

### ISSUE THREAD

**Issue by TorakikiSan** [PHPMailer/PHPMailer#2214]
My code:

```
  public function send_mail($OBJ, $FROM, $TO) {

    $this->STATE=array("error" => false,
                       "msg" => "");
    $this->SENT=array();

    $mail=new PHPMailer(true);
    $mail->isSMTP();
    $mail->SMTPDebug = SMTP::DEBUG_OFF;
    $mail->Host = "smtp.gmail.com";
    $mail->Port = 587;
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
    $mail->SMTPAuth = true;
    $mail->Username = "username@gmail.com";
    $mail->Password = "password";
    $mail->setFrom($FROM["mail"], $FROM["name"]);
    $mail->Subject=$OBJ;

    foreach($TO as $CONTACT) {
      $mail->addAddress($CONTACT["mail"], $CONTACT["name"]);
      $mail->msgHTML($CONTACT["text"]);
      if(!$mail->send()) {
        $this->STATE["error"]=true;
        $this->STATE["msg"]=$mail->ErrorInfo;
        break;
       }
      else {
        $this->SENT[]=array("from" => array("name" => $FROM["name"], "mail" => $FROM["mail"]),
                            "obj" => $OBJ,
                            "to" =>  array("name" => $CONTACT["name"], "mail" => $CONTACT["mail"]),
                            "message_id" => $mail->GetLastMessageID(),
                            "data" => date("d/m/Y"),
                            "udate" => mktime(date("H"), date("i"), date("s"), date("n"), date("j"), date("Y")));
       }

      $mail->clearAddresses();
      $mail->clearAttachments();

     }

   if(!$this->STATE["error"])
     $this->STATE["msg"]="Message(s) sent!";

  }

```
The mails are sent correctly, but if I print the SENT array, all the fields have the correct values except "message_id" which is always empty.

Any hint?

**Comment by Synchro** [comment]
The `lastMessageID` property is set [here](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L2460), so I'm not sure why you're not seeing it. If you `var_dump($mail)` after `send()`, can you see if it is set?

**Comment by XL-2000** [comment]
There is no such method "$mail->GetLastMessageID()", please check your casing: use a lowercase G for Get

**Comment by TorakikiSan** [comment]
> 
> 
> There is no such method "$mail->GetLastMessageID()", please check your casing: use a lowercase "g" for Get ("$mail->getLastMessageID()")

In this page is upper

https://hotexamples.com/examples/-/PHPMailer/GetLastMessageID/php-phpmailer-getlastmessageid-method-examples.html

in this is lower

https://phpmailer.github.io/PHPMailer/classes/PHPMailer.PHPMailer.PHPMailer.html

Maybe wor in boths case?

**Comment by TorakikiSan** [comment]
> 
> 
> The `lastMessageID` property is set [here](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L2460), so I'm not sure why you're not seeing it. If you `var_dump($mail)` after `send()`, can you see if it is set?

I rewrite the function and now seem work! Thank's to all

**Comment by Synchro** [comment]
Glad you fixed it, but it should come as no surprise that [the code itself](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L1282) is what sets the rules. The github docs are generated from the source, so they will be correct too. Note that the function names in that example are almost all wrong; It could be that they it was based on a very old version of PHPMailer.
