### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by urograndis** [PHPMailer/PHPMailer#2215]
I want your suggestion about below error log in phpmailer script to read smtp.gmail.com. After to do more possible tests. I am using VM Instance GCP, Centos 7, Apache 2.4 and PHP 7.
2020-12-06 09:56:04 Connection: opening to smtp.gmail.com:587, timeout=300, options=array()
2020-12-06 09:56:04 Connection failed. Error #2: stream_socket_client(): unable to connect to smtp.gmail.com:587 (Permission denied) [/var/www/html/vendor/phpmailer/phpmailer/src/SMTP.php line 375]
2020-12-06 09:56:04 SMTP ERROR: Failed to connect to server: Permission denied (13)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Message could not be sent. Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
My email is marcelo@sisflora.com.br.
Regards, thanks.

**Comment by XL-2000** [comment]
What steps did you take from the troubleshooting docs? How about posting your code to see how the connection is set up?
A lot of information can already be found here on github, looking at previous issues and docs. Chances of you hitting a brand new issue here are very slim

**Comment by Synchro** [comment]
I suspect that this will be caused by your local PHP configuration that may not be allowed to create socket connections. Are you on shared hosting?

**Comment by Bilel69500** [comment]
hello try the port 465 with ssl

**Comment by urograndis** [comment]
In phpinfo() returning "Sockets Support enable".
--

**Comment by Bilel69500** [comment]
extension=php_openssl.dll  extension_dir=ext on php.ini uncomment this

**Comment by Synchro** [comment]
This is quite likely to be caused by SELinux. Looking in the log file (probably in `/var/log/audit/audit.log`) may tell you more.
