### ISSUE TITLE
PHP 8.0 support: mbstring.func_overload directive has been removed

### ISSUE THREAD

**Issue by lkppo** [PHPMailer/PHPMailer#2216]
Hello,

Function mailPassthru() use mbstring.func_overload directive which have been removed by PHP 8.0.

Regards,

**Comment by Synchro** [comment]
The way that is used is fine. The call to `ini_set` will return false if the directive doesn't exist, and it will act as if that directive was turned off. It's needed in other PHP versions, but because it fails-safe, there is no need to wrap it in a version check. Nothing needs fixing here.
