### ISSUE TITLE
Add safe session

### ISSUE THREAD

**Issue by imithu** [PHPMailer/PHPMailer#2219]
kindly look at  this line-
https://github.com/PHPMailer/PHPMailer/blob/e78f71aa678c413c414f6d32e923993abba1de97/get_oauth_token.php#L63

the session is starting directly.

it will create problem if the session is already created. i have faced this problem in laravel.

so, kindy add this lines of code
```
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}
```
new code desc:
if session is started previously then no need to start the session again.

Thanks.

**Comment by Bilel69500** [comment]
try <?php
    if(!isset($_SESSION)) 
    { 
        session_start(); 
    } 
?> or session destroy

**Comment by Bilel69500** [comment]
try  `<?php
    if(!isset($_SESSION)) 
    { 
        session_start(); 
    } 
?>` or a session destroy

**Comment by Synchro** [comment]
That's really not necessary. This a simple example, not some big app, and `session_start` tales care of both situations of starting a new session *or* resuming an existing one, which is exactly the behaviour we want in this script. From [the docs](https://www.php.net/session_start):

> session_start() creates a session or resumes the current one based on a session identifier passed via a GET or POST request, or passed via a cookie.
