### ISSUE TITLE
error send pdf attachment

### ISSUE THREAD

**Issue by Walter250599** [PHPMailer/PHPMailer#2220]
Good evening, when I send the mail through phpmailer, I get an error when I place the attached pdf, I get the following
![image](https://user-images.githubusercontent.com/54049467/101845316-5d937500-3b1c-11eb-816f-28af6ac4d901.png)
code: 
$mail->addAttachment($_FILES['archivo']['tmp_name'], 'nuevoarchivo.pdf');

**Comment by Generalbubu** [comment]
Please can i get a good attachment code in html
    On Thursday, December 10, 2020, 04:19:13 PM PST, Walter Alfredo <notifications@github.com> wrote:  
 
 


Good evening, when I send the mail through phpmailer, I get an error when I place the attached pdf, I get the following

code:
$mail->addAttachment($_FILES['archivo']['tmp_name'], 'nuevoarchivo.pdf');

**Comment by Synchro** [comment]
This is not a PHPMailer issue, it's that you are not handling the upload correctly and have no error checking. Please refer to [the PHP documentation](https://www.php.net/manual/en/features.file-upload.php) on how to do that, and also follow [the file upload example provided with PHPMailer](https://github.com/PHPMailer/PHPMailer/blob/master/examples/send_file_upload.phps).
