### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by TheEighthContinent** [PHPMailer/PHPMailer#2224]
Don't know why, but when I request a password recovery it gives me a page of code instead of sending me a recovery link.

**Comment by Synchro** [comment]
PHPMailer doesn't provide password recovery, though you can use it as part of that process. If you have written a script, you probably have debug output enabled (set (`$mail->SMTPDebug = 0;`), but otherwise I can't guess without seeing your code or the output.

**Comment by TheEighthContinent** [comment]
So its not my code or website. The glitch revealed that they were using
your github code, and so I gambled that you might fix it faster than them.
-Aharon T.

**Comment by Synchro** [comment]
It is your code? PHPMailer by itself does literally nothing except occupy disk space.

**Comment by TheEighthContinent** [comment]
ok. I see what you mean now. I'm new to programming, and still trying to
figure out what does what, in terms of code.
-Aharon T.
