### ISSUE TITLE
email is not sent at my webpage

### ISSUE THREAD

**Issue by fullstact69** [PHPMailer/PHPMailer#2228]
I have used PHPMailer to send email at my webpage. At php version 5, It was worked. 
But at PHP version 7.2, it doesn't work.
I have been using these codes to send email : 
 

        $mail = new PHPMailer();
        $mail->SMTPAuth = true;
        $mail->CharSet = "UTF-8";
        $mail->Username = 'username';
        $mail->Password = 'password';
        $mail->Host = 'host';
        $mail->IsHTML(true);
        $mail->setFrom('from email', 'from name');
        $mail->SMTPDebug = 2;
        $mail->SMTPSecure = 'ssl';
        $mail->Port = 465;
        $mail->Subject = $subject['title'];
        $mail->Body = $subject['content'];
        $mail->addAddress($subject['email'], $subject['email']);
        $mail->send();

How can I resolve it to work as well?

**Comment by Synchro** [comment]
What you have looks functional, however, you've got no error checking, no debug output, so you have no way to tell what's going wrong. Please look at the examples provided for how to deal with that, and then you might get some feedback about it.
