### ISSUE TITLE
SMTP Host stuck loading

### ISSUE THREAD

**Issue by Buginator359** [PHPMailer/PHPMailer#2232]
Hi,

i'm using this code:
```php
<?php 
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

require 'vendor/autoload.php';

$message = "Testmessage";

$mail = new PHPMailer(false);

$mail->SMTPDebug = 0;
$mail->isSMTP();
$mail->Host       = 'mail.gmx.net';
$mail->SMTPAuth   = true;
$mail->Username   = 'testmail@gmx.net';
$mail->Password   = 'secretPassword';
$mail->SMTPSecure = 'ssl';
$mail->Port       = 465;

$mail->setFrom('testmail@gmx.net', 'Testmail');
$mail->addAddress('to@gmx.net');
$mail->Subject = "Samplesubject";
$mail->Body    = $message;
$mail->send();
```

The Problem is that my page does not stop loding. Any suggestions why?
If i use the same code with another SMTP-Host, it works without problems.

already tried port 465 with SSL and 487 with TLS. Both dont work for me.

SMTP-Data for gmx.net:
https://hilfe.gmx.net/pop-imap/pop3/serverdaten.html

Thanks for your help.

Regards

**Comment by XL-2000** [comment]
Did you try debugging? What does the debug output say? There is not much to go on here

**Comment by Synchro** [comment]
You've got no debug output, and no error handling. Not surprisingly this means you can't tell what's going wrong.

"Stuck loading" sounds like entirely normal SMTP client behaviour if it can't contact the SMTP server, which would suggest that wherever your script is running from cannot access the server. The tests described in the troubleshooting guide will diagnose this. The docs you linked to specify SMTP+STARTTLS (`tls` mode in PHPMailer) on port 587, which doesn't match what you said you have tried. I don't know if that what's really in your code or just a typo in your question.
