### ISSUE TITLE
smtp accept exception (SSL_accept - error:00000001:lib(0):func(0):reason(1))

### ISSUE THREAD

**Issue by hsALeGe** [PHPMailer/PHPMailer#2234]
I use the winmail mail mail server. When I use phpmailer to send mail, it has this error. smtp accept exception (SSL_ accept -  error:00000001 :lib(0):func(0):reason(1))。 The website and mail server are in the same server. How can I solve this problem

**Comment by Synchro** [comment]
You'll need to refer to the docs on your mail server. This doesn't have anything to do with PHPMailer that I can see.
