### ISSUE TITLE
fgets(): SSL operation failed with code 1.

### ISSUE THREAD

**Issue by clarkk** [PHPMailer/PHPMailer#2237]
Once in a while I get this error

```fgets(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number /var/www/php/repo/mail/phpmailer/SMTP.php(1258)```

I use phpmailer with keepalive where it run in a continuously loop

In the beginning I allowed self signed certs, but have now switched to a trusted cert. I thought that was the problem, but the issue consists

Sometimes it happens a couple of times within an hour but sometimes it can take a couple of hours before the warning

```
public function init(bool $debug=false): self{
	$this->SMTPDebug 		= $debug ? \PHPMailer\PHPMailer\SMTP::DEBUG_SERVER : 0; // \PHPMailer\PHPMailer\SMTP::DEBUG_CONNECTION;
	$this->isSMTP();
	
	$this->SMTPAuth 		= true;
	$this->SMTPSecure 		= self::ENCRYPTION_STARTTLS;
	$this->SMTPAutoTLS 		= false;
	$this->SMTPKeepAlive 	= true;
	
	$this->CharSet 		= self::CHARSET_UTF8;
	$this->AllowEmpty 	= true;
	
	$this->AuthType 	= 'PLAIN';
	$this->Host 		= self::$host;
	$this->Port 		= self::$port;
	$this->Username 	= self::$user;
	$this->Password 	= self::$pass;
	
	return $this;
}
```

**Comment by Synchro** [comment]
PHPMailer is subject to your local PHP and TLS config here - it's just calling `fgets` on an existing connection. Are you sending continuously, or are you keeping the connection open while doing nothing? I'd guess that you may be hitting some kind of timeout in TLS.

**Comment by clarkk** [comment]
I use the ping method to keep the connection open every 60 secs

**Comment by clarkk** [comment]
I mean the `noop` operation

**Comment by Synchro** [comment]
I don't think I'd bother? If you're not sending very often, you're really not gaining anything. Keepalive only really helps when you're sending large volumes. Alternatively, reopen the connection every hour using the same mechanism you use for `noop`.

**Comment by clarkk** [comment]
The service is restarting every 999th secend (17 mins) and is only opening a connection if there are mails in the queue :)

**Comment by Synchro** [comment]
It's really unclear what's going here – it still sounds like some kind of TLS timeout issue. There are several SMTP-level timeouts at 10 minutes, so perhaps lower your restart time to below that. I wouldn't hold a connection open to a remote server like that though. The best way to send is to relay through a local mail server and have it deal with timeouts, queues etc, it's what they are good at.
