### ISSUE TITLE
Convert data URIs into embedded images in msgHTML fails

### ISSUE THREAD

**Issue by HeuvelTop** [PHPMailer/PHPMailer#2238]
# Problem description
Sending using msgHTML with an inline image does not move the image to attachment anymore.
I have recently upgraded from version 6.0.7 to 6.2.0

# Code to reproduce
 The regex for finding the image data has changed. In line 4043 of PHPMailer.php

From: '/(src|background)=["\'](.*)["\']/Ui' in version 6.0.7

To: '/(?<!-)(src|background)=["\'](.*)["\']/Ui' in version 6.2.0

# Debug output
Inline images send to for example GMail create unreadable mails on the receiving end. 
As a workaround I have remove the negative lookbehind (?<!-)

**Comment by Synchro** [comment]
That non-capturing lookbehind is to ignore svg attributes like `enable-background` (see #1877), and it should work fine with "normal `img` tags, for example this works as expected:

    <img src="someurl">

Do you have an example of an HTML tag that this fails to match?

**Comment by HeuvelTop** [comment]
Thanks for responding. I agree. But it doesn't match the following snippet of a html body:
```
<p class="western" align="center">&nbsp;</p>
<p class="western" align="center"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAf4AAAKoCAIAAAAZMgoFAAAgAElEQVR4AZy8Z3AcWXotOD93Y2NfhKS3ISlWZvVGdvSkp9GO0XSTMOW9h/c0oGtPsrunfbN7THtv6Jumm54g6AEUyqEA0HuYslmVld5neQfUxs0EixySPdJsxIkvLm5mFbLSnPvdc76bP4gw+ShbiLKFGFeM8yVIKENCOSFW5MbDMc4XIKGYEEvJdDkllmGhlOSLCa4A80WYLyIcAMreg9wjb5Vjki8m+SIkAMTFe4iJxZhYjoiLEbEmIybU6ojztTogvgbxtSQHYoxdiD4K9Z0fbIi1+KMQZisyIlw1wlWj/EKUX5hLL9zI164Wazfytdu52lymFhbBIcXv/ndwAAI42vl0bS6zOJdZjInVuPAHAGKL/3XEuGJUOjz5IO+Pj/xRcbEWFhbCw
.....
m5b5mSY0hAfypIB+WFHD7/Q7+P++NRFdntC8Cuw5YEyPj+9uuUhwAeSnjIC+p9yKy66l/0OvCuDy/POz/mVwj94Lzs6Znlon8m/YPEhwxyH4U20L/TedG0FPBaVROaloKezxzoI/dZgQ8xngfR//kZY9EPwn+J6O8b2cZHbPLVlKrxZqsQfQxvbK9v7WwmK7d3xbOr/FHk7eS6GrooH38D6ZBqj8w01DEAAAAASUVORK5CYII=" alt="" />&nbsp;</p>
```

When print_r( $images):
`Array ( [0] => Array ( ) [1] => Array ( ) [2] => Array ( ) )`

So what happens here?

**Comment by XL-2000** [comment]
It must be in your image data itself or surrounding message data. And your did not post the whole lot... 
If you run your example against the isolated regex it works fine.

```
$message = 'lorem ipsum <p class="western" align="center">&nbsp;</p><p class="western" align="center"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAf4AAAKoCAIAAAAZMgoFAAAgAElEQVR4AZy8Z3AcWXotOD93Y2NfhKS3ISlWZvVGdvSkp9GO0XSTMOW9h/c0oGtPsrunfbN7THtv6Jumm54g6AEUyqEA0HuYslmVld5neQfUxs0EixySPdJsxIkvLm5mFbLSnPvdc76bP4gw+ShbiLKFGFeM8yVIKENCOSFW5MbDMc4XIKGYEEvJdDkllmGhlOSLCa4A80WYLyIcAMreg9wjb5Vjki8m+SIkAMTFe4iJxZhYjoiLEbEmIybU6ojztTogvgbxtSQHYoxdiD4K9Z0fbIi1+KMQZisyIlw1wlWj/EKUX5hLL9zI164Wazfytdu52lymFhbBIcXv/ndwAAI42vl0bS6zOJdZjInVuPAHAGKL/3XEuGJUOjz5IO+Pj/xRcbEWFhbCwm5b5mSY0hAfypIB+WFHD7/Q7+P++NRFdntC8Cuw5YEyPj+9uuUhwAeSnjIC+p9yKy66l/0OvCuDy/POz/mVwj94Lzs6Znlon8m/YPEhwxyH4U20L/TedG0FPBaVROaloKezxzoI/dZgQ8xngfR//kZY9EPwn+J6O8b2cZHbPLVlKrxZqsQfQxvbK9v7WwmK7d3xbOr/FHk7eS6GrooH38D6ZBqj8w01DEAAAAASUVORK5CYII=" alt="" />&nbsp;</p> lorem ipsum';
        preg_match_all('/(?<!-)(src|background)=["\'](.*)["\']/Ui', $message, $images);
        print_r($images);

```
results in:

```
Array
(
    [0] => Array
        (
            [0] => src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAf4AAAKoCAIAAAAZMgoFAAAgAElEQVR4AZy8Z3AcWXotOD93Y2NfhKS3ISlWZvVGdvSkp9GO0XSTMOW9h/c0oGtPsrunfbN7THtv6Jumm54g6AEUyqEA0HuYslmVld5neQfUxs0EixySPdJsxIkvLm5mFbLSnPvdc76bP4gw+ShbiLKFGFeM8yVIKENCOSFW5MbDMc4XIKGYEEvJdDkllmGhlOSLCa4A80WYLyIcAMreg9wjb5Vjki8m+SIkAMTFe4iJxZhYjoiLEbEmIybU6ojztTogvgbxtSQHYoxdiD4K9Z0fbIi1+KMQZisyIlw1wlWj/EKUX5hLL9zI164Wazfytdu52lymFhbBIcXv/ndwAAI42vl0bS6zOJdZjInVuPAHAGKL/3XEuGJUOjz5IO+Pj/xRcbEWFhbCwm5b5mSY0hAfypIB+WFHD7/Q7+P++NRFdntC8Cuw5YEyPj+9uuUhwAeSnjIC+p9yKy66l/0OvCuDy/POz/mVwj94Lzs6Znlon8m/YPEhwxyH4U20L/TedG0FPBaVROaloKezxzoI/dZgQ8xngfR//kZY9EPwn+J6O8b2cZHbPLVlKrxZqsQfQxvbK9v7WwmK7d3xbOr/FHk7eS6GrooH38D6ZBqj8w01DEAAAAASUVORK5CYII="
        )

    [1] => Array
        (
            [0] => src
        )

    [2] => Array
        (
            [0] => data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAf4AAAKoCAIAAAAZMgoFAAAgAElEQVR4AZy8Z3AcWXotOD93Y2NfhKS3ISlWZvVGdvSkp9GO0XSTMOW9h/c0oGtPsrunfbN7THtv6Jumm54g6AEUyqEA0HuYslmVld5neQfUxs0EixySPdJsxIkvLm5mFbLSnPvdc76bP4gw+ShbiLKFGFeM8yVIKENCOSFW5MbDMc4XIKGYEEvJdDkllmGhlOSLCa4A80WYLyIcAMreg9wjb5Vjki8m+SIkAMTFe4iJxZhYjoiLEbEmIybU6ojztTogvgbxtSQHYoxdiD4K9Z0fbIi1+KMQZisyIlw1wlWj/EKUX5hLL9zI164Wazfytdu52lymFhbBIcXv/ndwAAI42vl0bS6zOJdZjInVuPAHAGKL/3XEuGJUOjz5IO+Pj/xRcbEWFhbCwm5b5mSY0hAfypIB+WFHD7/Q7+P++NRFdntC8Cuw5YEyPj+9uuUhwAeSnjIC+p9yKy66l/0OvCuDy/POz/mVwj94Lzs6Znlon8m/YPEhwxyH4U20L/TedG0FPBaVROaloKezxzoI/dZgQ8xngfR//kZY9EPwn+J6O8b2cZHbPLVlKrxZqsQfQxvbK9v7WwmK7d3xbOr/FHk7eS6GrooH38D6ZBqj8w01DEAAAAASUVORK5CYII=
        )

)
```

**Comment by Synchro** [comment]
I don't think anything to do with the expression you originally posted; that recognises your image URLs just fine. Further on in the same function there is additional support for inline `data` URLs, which it converts to embedded attachments. `data` URLs are generally less compatible than embedded attachments, which is why PHPMailer applies the conversion. This has been in place since 5.2.9 back in 2014, so I'm not clear what the difference is you're seeing here.  If you don't want it it to convert those URLs, don't use `msgHTML`.

**Comment by HeuvelTop** [comment]
I tried another image. And that was processed without problems.

**Comment by HeuvelTop** [comment]
How can I upload the whole  email body text with the inline picture here.

**Comment by Synchro** [comment]
Well, `msgHTML` is specifically and intentionally designed to convert `data` URLs into embedded attachments, so if you don't want it to do that, don't call it. You can do everything that it does, but with more control, by doing it however you like manually. Use embedded images directly using `addEmbeddedImage`, which you can reference in your HTML via the `cid` values you can supply.

I think you're just using the wrong tool (`msgHTML`) for the job here.

**Comment by HeuvelTop** [comment]
I am using msgHTML for many months and for several 100s of e-mails and it has always done what I expected: convert inline images to attachments. Apart from this one incident that I first wrongly assumed went wrong because of the upgrade to 6.2.0. I am still not understanding why this one image is different.

**Comment by Synchro** [comment]
OK, that wasn't clear. Perhaps post the contents of a message body you're trying to use in a [gist](https://gist.github.com) so that we can take a look at it?
