### ISSUE TITLE
AJAX with .fetch not working on examples/contactform-ajax.php

### ISSUE THREAD

**Issue by da-kicks-87** [PHPMailer/PHPMailer#2239]
Hello,

I am trying the get the form to respond to the submissions and display the confirmation message without page reload. I am using the example from **examples/contactform-ajax.php**

I'm pretty new to using AJAX with fetch and promises. To my understanding they are meant to replace AJAX with XMLHttpRequest Object. 

The console error message tells me **Uncaught (in promise) TypeError: error.json is not a function at ..**

Which is in this JS function where it does the .catch

 ```
 function email(data) {
      const message = document.getElementById("status-message")
      fetch("", {
          method: "POST",
          body: data,
          headers: {
             'X-Requested-With' : 'XMLHttpRequest'
          }
      })
          .then(response => response.json())
          .then(response => {message.innerHTML = response.message})


          .catch(error => {
              error.json().then(response => {
                  message.innerHTML = response.message
              })
          })
  }
```

Has anyone came across this problem ? Is there a solution?

**Comment by Synchro** [comment]
JS isn't really my thing, but I'd recommend setting a breakpoint on that line to see exactly what is in `error`.

**Comment by XL-2000** [comment]
The "error" object is a type Response object. It does (indeed) not have a .json function. you can retrieve the body of the response and call the json function.
For specifications; see [https://developer.mozilla.org/en-US/docs/Web/API/Response/error](https://developer.mozilla.org/en-US/docs/Web/API/Response/error)

**Comment by Synchro** [comment]
From the report though, I'd assume that while it's *meant* to be a `Response` object, in this case it isn't for some reason? I'd guess it's maybe null or something? Perhaps it's in a old browser that doesn't understand `fetch`?

**Comment by da-kicks-87** [comment]
I was able to get it to work by converting the fetch to XMLHttpRequest object. Then call PHP code as separate file as the "url" with xhr.open("POST", url, true). This way i can return a clean response  with var jsonData = JSON.parse(xhr.response);

The response would hold whatever or not the email was sent and messages etc.... From there I'm able to output the response message to my webpage with JS. 

The JS would look  like this in case anyone is curious. Process spinner icon on submit is optional, as well as CSS classes.

`var contactForm = document.getElementById("contact-form");

          contactForm.addEventListener("submit", function(event) {

              event.preventDefault();

              var xhr = new XMLHttpRequest();
              var url = "../src/inc/mail-config.php";
              xhr.open("POST", url, true);

              var statusMessage = document.querySelector("#status-message");

              statusMessage.classList.add("alert","alert-warning");

              statusMessage.innerHTML = "Processing... <div class='spinner-border ml-4' role='status'><span class='sr-only'>Processing...</span></div>";

              xhr.onload  = function () {
                  if (xhr.status === 200) {

                      var jsonData = JSON.parse(xhr.response);

                       var statusMessage = document.querySelector("#status-message");

                       statusMessage.innerHTML = jsonData.message;

                       if (jsonData.status=true) {
                         statusMessage.classList.remove("alert-warning");
                         statusMessage.classList.add("alert","alert-primary");
                       }
                       else if (jsonData.status=false) {
                         statusMessage.classList.remove("alert-warning");
                         statusMessage.classList.add("alert","alert-danger");
                       }

                  }
              };

              var data = new FormData(contactForm);

              xhr.send(data);

          });`

**Comment by Synchro** [comment]
If fetch isn't working, it suggests you're using a very [old browser](https://caniuse.com/fetch).

**Comment by Maxortega19** [comment]
I have the exactly same issue using this example, but at first I could send mail to Gmail using OAuth but now I have this error:
![image](https://user-images.githubusercontent.com/62458476/123208209-0ab85400-d495-11eb-9e83-1b59573d4b2b.png)
