### ISSUE TITLE
Documentation - clearing all addresses in mailing list example

### ISSUE THREAD

**Issue by rickhellewell** [PHPMailer/PHPMailer#2247]
In the mailing list example (in documentation), it says to clear addresses with:
```

    //Clear all addresses  for the next iteration
    $mail->clearAddresses();
```

This will only clear the 'to' address. You may want to clear ALL addresses instead, or the recipients will get multiple emails. (The number they get depends on where they are in the loop of recipients.) This affected my first mailings, when I was setting only BCC recipients. Each BCC recipient was getting multiple emails.

This should be changed to
```

    //Clear all recipients (to/cc/bcc) for the next iteration
    $mail->clearAllRecipients();
```

**Comment by Synchro** [comment]
That doesn't make a lot of sense. There are two basic ways of sending a message to lots of people: one message to each, or BCC a single message. So if you're in a loop, it's very unlikely you should need to use BCC in the first place. If you're looping over your list and BCCing to each, I'd say that's nonsensical; all the overhead with none of the benefit.

**Comment by rickhellewell** [comment]
Well, I wanted to make sure that the messages used BCC. And using clearAddresses didn't clear out the BCCs, so the recipients were getting multiple messages.
Maybe not the proper way to loop through the mailing list, but the docs are not clear that using clearAddress will only clear the 'to' email. 
Even though I did it in a strange way, the docs should still clarify the use of those two options.

**Comment by Synchro** [comment]
[The docs](http://phpmailer.github.io/PHPMailer/classes/PHPMailer.PHPMailer.PHPMailer.html#method_clearAddresses) explicitly say that `clearAddresses` clears To addresses.
