### ISSUE TITLE
help me to sorve this issues

### ISSUE THREAD

**Issue by willyblord** [PHPMailer/PHPMailer#2248]
2021-01-17 17:40:59 SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Name or service not known (0)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Message has been sent

**Comment by Synchro** [comment]
That means that either the mail server you're trying to connect to doesn't exist, or your DNS service is broken. This is covered in the troubleshooting guide.
