### ISSUE TITLE
Exchange Online connection failure with isSMTP() set

### ISSUE THREAD

**Issue by VidarParry** [PHPMailer/PHPMailer#2250]
Hi everyone,
I have found that a connection to an Exchange Online SMTP service which include the isSMTP() parameter always returns "SMTP connect() failed" message. If I remove isSMTP() it seems to work fine.

1. Is it OK to run without isSMTP()?
2. Not sure whether this is a bug or a feature, but is worthy of wider publication. 

This seems to be different to the issue described in the troubleshooting guide.

Many thanks!
Cheers...Steve
My code is:
```
    try {
        //Server settings
        //Enable SMTP debugging
        $email->SMTPDebug = 4;
        $email->Debugoutput = function($str, $level) {echo "debug level $level; message: $str";};
        $email->Debugoutput = 'error_log';


        $email->isSMTP(); // Set mailer to use SMTP //******* if this is left in with Exchange online PHPMailer throws a connection failure
        $email->CharSet = 'UTF-8';  //not important
        $email->Host = 'smtp.office365.com'; // Specify main and backup SMTP servers
        $email->SMTPAuth = true; // Enable SMTP authentication
        $email->SMTPSecure = 'tls'; 
        $email->Port = 587; // TCP port to connect to
        
        //Authentication
        $email->Username = 'my@email.com'; // SMTP username
        $email->Password = 'mypassword'; // SMTP password 


        //Recipients
        $email->SetFrom('my@email.com', 'Me');
        $email->addReplyto('my@email.com', 'Me');
        
        $email->AddAddress($vms_email);//Derived from database
    
        // Content
        $email->isHTML(true); 
        $email->Subject   = $mailsubject;
        $email->Body      = $messagebody;
        $email->AltBody = 'This email can only be viewed in HTML.';

       // Attachement 
       $email->addAttachment('upload/file.pdf');

        //Send the email
        $email->send();
        elog('Mail Sent Successfully ' . ' ' . $mailsubject);
        echo('Mail Sent'); //tell Browser javascript OK
    
        
    } catch (Exception $e) {
        elog('Mail not sent ' . $email->ErrorInfo . ' ' . $mailsubject);
        header('HTTP/1.1 500 Internal Server Error');
        die($_POST['authentic'] . 'Error sending email . Subject: ' . $mailsubject . '. Mailer Error: ' . $email->ErrorInfo);
            return false;
    }

```

**Comment by Synchro** [comment]
This is *exactly* what is described in the troubleshooting guide. If you don't call `isSMTP`, *you are not using SMTP at all*, but sending through PHP's `mail()` function. That means you are submitting to a local mail server, which may deliver your message via a completely different route, as properties like `Host` play no part in it. There's also no guarantee that it will work this way either – just because you are able to submit to a local server does not mean that your message can be delivered any better, it will just fail at a later point that has worse visibility. If your hosting provider blocks outbound SMTP, it will fail equally well whether you send directly via SMTP, or through mail to a local server.

**Comment by VidarParry** [comment]
Thank you Synchro.
The troubleshooting guide refers to the SMTP AUTH setting for Exchange online, and it resulting in Authentication unsuccessful. I am getting a different error -  SMTP connect() failed:
[20-Jan-2021 18:32:42 UTC] Connection: opening to smtp.office365.com:587, timeout=300, options=array()
[20-Jan-2021 18:32:46 UTC] Connection failed. Error #2: stream_socket_client(): unable to connect to smtp.office365.com:587 (Network is unreachable) [/home/samfords/public_html/wp-content/themes/u-design-child/PHPMailer/src/SMTP.php line 379]
[20-Jan-2021 18:32:46 UTC] SMTP ERROR: Failed to connect to server: Network is unreachable (101)
[20-Jan-2021 18:32:46 UTC] SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

I had, however, checked the setting and Authenticated SMTP is is enabled for this account. 

Myself, my hosting provider tech support and Microsoft Technical Support have spent a lot of time trying to resolve this problem. We have verified that a secure connection to the smtp.office365.com server on port 587 can be made from the server that hosts my script (and domain):
[root@au06 ~]# openssl s_client -starttls smtp -connect smtp.office365.com:587
CONNECTED(00000003)

The local mail server for my domain has been disabled (and now doesn't respond to ping so is not visible) and only one MX record exist that points to the Microsoft exchange online servers. So I have no idea what other mail server it can be using and SMTPDebug gives no additional information other than as stated above.

If running without isSMTP() isn't the solution, please can you suggest what may be causing the connection failure, and/or what can I do to further investigate this.

Many thanks.
Cheers
...Steve

**Comment by decomplexity** [comment]
https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-july-update/ba-p/1530163 is worth a read if you haven't already. Although this link concerns authentication rather than connection, it sounds as if SMTP is being blocked at the protocol level.

**Comment by Synchro** [comment]
This is the interesting thing in the debug output:

>Network is unreachable

Given that it works from a command-line, it suggests your server may not allow outbound SMTP *from PHP* (or your web server, if you're using mod_php in apache). This is most likely to be caused by things like SELinux or AppArmor; there's a section in the guide about this. If you're on a Windows server, I'm not the one to ask what might block that.

As for your local mail server, I mean local as in running on the same machine as your script, not on some nearby server that has a separate IP. Try `telnet localhost 25`. If sending via the mail function works, ther has to b a server somewhere – it's not magic! Also check what's in your php.ini regarding mail settings – it may give some clues what's set up to send mail from your PHP installation. Also see if there's anything in a mail server log file, usually somewhere like `/var/log/mail.log`.

**Comment by VidarParry** [comment]
Thanks again Synchro.

The server is running Apache - I've asked my web-hoster to give me SSH access so I can hopefully get a bit closer to the cause. Very frustrating!  Nothing in php.ini and no mail server log found.

I will get back to you when I find the cause of this issue. it may be something you have already documented or it might be something new:-)

Cheers
...Steve

**Comment by Synchro** [comment]
[7.2 is now out of support](https://www.php.net/supported-versions) so should be updated, certainly not be used in a new deployment.

So what *is* in your php.ini for mail config? If the `mail()` function works, you *must* have something in there.

**Comment by VidarParry** [comment]
I only have two php.ini files - one in the home directory and one in the public_html.  They both have the similar content:
```
display_errors = Off
max_execution_time = 300
max_input_time = 60
max_input_vars = 1000
memory_limit = 256M
post_max_size = 8M
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/ea-php72"
upload_max_filesize = 3M
zlib.output_compression = Off
```


and

```
asp_tags = Off
display_errors = On
max_execution_time = 300
max_input_time = 60
max_input_vars = 1000
memory_limit = 256M
post_max_size = 64M
session.gc_maxlifetime = 1440
session.save_path = "/tmp"
upload_max_filesize = 64M
zlib.output_compression = Off
```
I'll upgrade to php7.4 - just need to arrange a test window to make sure the rest of the production scripts still work!

Thanks again.

Cheers
...Steve

**Comment by Synchro** [comment]
Those are your own separate php.ini overrides, not the central php.ini that contains all the other directives. Run `php -i` on a  command line, or `phpinfo()` via a browser and it will tell you where all your other php.ini files are and also show you all the settings.

**Comment by VidarParry** [comment]
Ah:-) Sorry - I'm not a server expert (probably not an expert at anything much these days:-))

Hosting provider gets:
```
[root@au06 ~]# getsebool httpd_can_sendmail
getsebool:  SELinux is disabled
[root@au06 ~]# getsebool httpd_can_network_connect
getsebool:  SELinux is disabled
```
so as the server is running cPanel/WHM, SELinux has to remain disabled.

We can't run "telnet localhost 25" as telnet doesn't exist on the server (gives telnet: command not found).

I have set up a test page to run the failing script and to see the error log, and I'm happy to send you the failing script file as well (all via PM I suggest).

From the php -i, I've extracted the following relating to mail, so you are of course right:-). Sorry, I don't know enough about this to know whether these may interfere or influence my smtp problem. There was no mention of SMTP in the php -i output.

core
mail.add_x_header => Off => Off
mail.force_extra_parameters => no value => no value
mail.log => no value => no value

standard
Path to sendmail => /usr/sbin/sendmail -t -i

Environment
MAIL => /var/spool/mail/samfords

PHP Variables
$_SERVER['MAIL'] => /var/spool/mail/samfords
$_ENV['MAIL'] => /var/spool/mail/samfords

Thank you for any advice - I don't know what else to try!

Cheers
...Steve

**Comment by Synchro** [comment]
That path to sendmail is the default, but it would be interesting to know if it works. You can hit it directly like this (where message.eml is a raw email message in a text file):

    /usr/sbin/sendmail user@example.com < message.eml

It's easier if you have the `mailutils` package installed as that includes a `mail` client app that you can call like this:

    echo "My message" | mail -s subject user@example.com

You can look at running processes and see if you have a mail server running, for example (looking for postfix):

```sh
$ ps aux | grep postf
postfix  27277  0.0  0.0  73820  5348 ?        S    08:12   0:00 pickup -l -t unix -u -c
postfix  29295  0.0  0.1  98148 10724 ?        S    08:22   0:00 smtpd -n smtp -t inet -u -c -o stress= -s 2
postfix  29296  0.0  0.0  73820  5272 ?        S    08:22   0:00 anvil -l -t unix -u -c
postfix  29299  0.0  0.0  79300  6548 ?        S    08:22   0:00 trivial-rewrite -n rewrite -t unix -u -c
postfix  29300  0.0  0.0  79400  7000 ?        S    08:22   0:00 cleanup -z -t unix -u -c
postfix  29301  0.0  0.0  90184  6776 ?        S    08:22   0:00 lmtp -t unix -u -c
root     31842  0.0  0.0  67388  4236 ?        Ss   03:12   0:00 /usr/lib/postfix/sbin/master -w
postfix  31844  0.0  0.0  73948  5732 ?        S    03:12   0:00 qmgr -l -t unix -u
postfix  31952  0.0  0.1  87876  8620 ?        S    03:12   0:00 tlsmgr -l -t unix -u -c
```

If you have `aptitude` installed, you can search for installed packages that provide a particular service, for example:

```sh
# aptitude search '~i~Pmail-transport-agent'
i   postfix                                                                                              - High-performance mail transport agent
```

Telnet is indeed often not installed, but there are other tools you can use that probably – I have added info about using `curl` and `nc` to the guide.

**Comment by VidarParry** [comment]
Thanks again.
Calling direct sendmail resulted in nothing - no delivery and no message.

ps aux | grep postf gave just: 
samfords 1185536  0.0  0.0   9092   672 pts/0    S+   11:58   0:00 grep --color=auto postf

Although I'm not sure how this helps with my trying to get SMTP in my PHPScript to work.

I've since tried updating to PHP 7.5 and also ran the script on a different domain (albeit on the same server) with the same result. unfortunately I don't have access to a domain on a different server.

Anything else I can do to 'prove' the server is (or isn't) causing the issue?

Thank you - really appreciate your expertise and knowledge.

Cheers...Steve

**Comment by Synchro** [comment]
OK, so you're not running postfix, but you could be running something else like exim. If you telnet/curl/nc to localhost port 25, it might respond with the name of the server software. You're right though that if you're using SMTP to a remote server from PHPMailer, it doesn't matter what's configured locally.

In your earlier `openssl` example, it says `CONNECTED`, but then has no other output. Is it that there was no more output, or that you just didn't show it?

So far I don't really think I'm convinced that you don't have a network block on outbound SMTP.

**Comment by VidarParry** [comment]
Hi Synchro,
The great news is that the problem has been fixed, and it wasn't PHPMailer (which you knew anyway!).

My hosting provider fixed it a few days ago and I have been trying to get the details of what they did so I could share with you and others reading this and having the same problem. (Thus the delay in responding to you.)

The best I could get out of them was "I don't know exactly what was done (it was done by the data centre techs), but it was a security setting on the server (as opposed to your individual account) that was adjusted. It's not unusual for new versions of server operating systems to change the way they work, to improve security or to fix bugs."

Hope this helps. Thank you again for your great support and advice.

Cheers
...Steve
