### ISSUE TITLE
PHPMailer signing a message: The message contents may have been altered. 

### ISSUE THREAD

**Issue by idefixgallier** [PHPMailer/PHPMailer#2252]
Hey,

following the Issue: #1046 , i still have the issue with 6.17 and Outlook.
Any hints how to get this working?
(Wrong content type maybe or something?)

Kind regards,
Martin

**Comment by Synchro** [comment]
Not really, no. If it's critical, I recommend going with something that makes a better job of S/MIME signing, perhaps SwiftMailer.
