### ISSUE TITLE
Getting Error: PHP Deprecated:  __autoload() is deprecated, use spl_autoload_register() instead ....

### ISSUE THREAD

**Issue by Hissan147** [PHPMailer/PHPMailer#2253]
I am getting this in my error log file:
PHP Deprecated:  __autoload() is deprecated, use spl_autoload_register() instead in /home/onlinsha/public_html/class/PHPMailerAutoload.php

**Comment by Synchro** [comment]
It's because you're using an old version. Update to the current version that does not contain this code.

**Comment by Hissan147** [comment]
Meanwhile, I am using a 5.2-stable one. So I've to use code from the master branch, right?

**Comment by Synchro** [comment]
Use [the released versions](https://github.com/PHPMailer/PHPMailer/releases); master is not guaranteed to work. The best way to keep your versions up to date is to use composer, as the readme suggests.
