### ISSUE TITLE
i can't send email using php mailer smtp failed to connect

### ISSUE THREAD

**Issue by sosi-bit** [PHPMailer/PHPMailer#2255]
2021-01-27 13:06:46 SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: No such host is known. (0)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Message could not be sent. Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
 i try to send using   $mail->Host  = 'smtp.gmail.com'; 
$mail->SMTPSecure = 'ssl';      
    $mail->Port       = 587;

**Comment by Synchro** [comment]
This is the same question as you just posted in #2254, and the answer is the same: your DNS is broken.

You have a second problem in that you're trying to use `SMTPSecure = 'ssl'` with `Port = 587`. As the guide says, that combination will not work: use `ssl` mode on port 465, or `tls` mode on port 25 or 587. Base your code on the gmail example provided in the examples folder.

**Comment by sosi-bit** [comment]
thanks!!!
