### ISSUE TITLE
Cannot modify header information - headers already sent by ...phpmailer/src/SMTP.php:282

### ISSUE THREAD

**Issue by Asmitta-01** [PHPMailer/PHPMailer#2258]
I used the XOAUTH2 for gmail to send my mail but i got the error message:

> Warning: Cannot modify header information - headers already sent by (output started at C:\Users\kjkj\Documents\ProjetCrypt\vendor\phpmailer\phpmailer\src\SMTP.php:282) in C:\Users\kjkj\Documents\ProjetCrypt\sendMail.php on line 68

The good thing is that the line 68 is execute when the mail successfully gone:
```
               if (!$mail->send()) {
			echo 'Mailer Error: '.$mail->ErrorInfo;
			//header("Location: contact.php?msgsent=false");
		}
		else {
			header("Location: contact.php?msgsent=true"); //line 68
		}
```
But why this error and how do i fix it?

**Comment by Synchro** [comment]
Do you have debug output enabled? *Something* is producing output before your `header` call.

**Comment by Asmitta-01** [comment]
It is okay, thanks for the reply. I followed this link :[]( https://stackoverflow.com/a/8028987/13808068) and i replace the line 68 by `echo '<script> location.replace("http://127.0.0.1:8080/edsa-ProjetCrypt/contact.php?msgsent=true"); </script>';` and is working fine. I had prefer header but seems it is not possible...

**Comment by Asmitta-01** [comment]
> Do you have debug output enabled? _Something_ is producing output before your `header` call.

For your question, it is no. In the script i just do the necessary to send the mail without printing anything. I have a `session_start()` at the beginning but removing didn't solve the problem. I found the solution so it is okay, thanks again
