### ISSUE TITLE
PHPMailer can't be found

### ISSUE THREAD

**Issue by ItsWidee** [PHPMailer/PHPMailer#2259]
# Problem description
Hello,
I install today PHPMailer and I try the example code on the documentation. Unfortunately, when I try it, an error appeared saying that PHPMailer can't be found. 
I'm using WAMP64 and PHPMailer has been installed using Composer.
MailDev is catching the mails in port 1025.
You can find a screenshot of my project folder.
The file is `mail-2.php`

![xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx](https://user-images.githubusercontent.com/51414313/106353161-d3c88280-62e8-11eb-8d41-cec1594f95d8.PNG)

# Code to reproduce

It is the example code

```php
<?php
// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

// Load Composer's autoloader
require 'vendor/autoload.php';

// Instantiation and passing `true` enables exceptions
$mail = new PHPMailer(true);

try {
    //Server settings
    $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      // Enable verbose debug output
    $mail->isSMTP();                                            // Send using SMTP
    $mail->Host       = 'smtp.example.com';                    // Set the SMTP server to send through
    $mail->SMTPAuth   = true;                                   // Enable SMTP authentication
    $mail->Username   = 'user@example.com';                     // SMTP username
    $mail->Password   = 'secret';                               // SMTP password
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;         // Enable TLS encryption; `PHPMailer::ENCRYPTION_SMTPS` encouraged
    $mail->Port       = 1025;                                    // TCP port to connect to, use 465 for `PHPMailer::ENCRYPTION_SMTPS` above

    //Recipients
    $mail->setFrom('from@example.com', 'Mailer');
    $mail->addAddress('joe@example.net', 'Joe User');     // Add a recipient
    $mail->addAddress('ellen@example.com');               // Name is optional
    $mail->addReplyTo('info@example.com', 'Information');
    $mail->addCC('cc@example.com');
    $mail->addBCC('bcc@example.com');

    // Attachments
    $mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
    $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name

    // Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = 'Here is the subject';
    $mail->Body    = 'This is the HTML message body <b>in bold!</b>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    $mail->send();
    echo 'Message has been sent';
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}
```

# Debug output
` Fatal error: Uncaught Error: Class 'PHPMailer\PHPMailer\PHPMailer' not found in D:\wamp64\www\tests\mail-2.php:12 Stack trace: #0 {main} thrown in D:\wamp64\www\tests\mail-2.php on line 12`

**Comment by Synchro** [comment]
Can you see a PHPMailer folder inside your vendor folder? If not, run composer install again.

**Comment by ItsWidee** [comment]
Yes, I can see the phpmailer folder.

![image](https://user-images.githubusercontent.com/51414313/106359721-bf9a7a80-6314-11eb-8247-8028a6087a80.png)

**Comment by Synchro** [comment]
That looks right. Maybe run `composer dump-autoload` to make it rebuild the autoloader.

**Comment by ItsWidee** [comment]
Unfortunately, I have the same error when I do this command

**Comment by Synchro** [comment]
That's very strange, but does sound like a composer problem. Maybe delete the `vendor` folder, the `composer.lock` file and run `composer install` again?

**Comment by ItsWidee** [comment]
I delete both of them, I just keep the `composer.phar` and `composer.json` but I have the same error...

**Comment by Synchro** [comment]
There's something strange going on here! Are you sure you're loading the correct `autoload.php`, for example if your current working directory is not where you think it is (e.g. if you run `mail-2.php` from somewhere else)? You should be able to force it by changing this:

    require __DIR__ . '/vendor/autoload.php';

Also go and look at the autoload files themselves – you should be able to see the mapping for the PHPMailer classes composer creates.

**Comment by ItsWidee** [comment]
Do it put the `__DIR__` or I change it ?

**Comment by Synchro** [comment]
Use it as I typed it – `__DIR__` is a built-in constant that contains the path to the folder of the current php file.

**Comment by ItsWidee** [comment]
I try to do what you're saying, but the error persists

**Comment by Synchro** [comment]
I can only guess that there is something wrong with your whole installation. Set a breakpoint (or generate debug output manually) inside the autoloader and see why it's failing to find the package. After installation there should be an entry for PHPMailer in `vendor/composer/autoload_psr4.php` pointing at the `/phpmailer/phpmailer/src` folder.

**Comment by ItsWidee** [comment]
I am really sorry @Synchro but I'm not a real expert in PHP, I am pretty new in this world. So, breakpoint is for me an absolute unknown word...

**Comment by Synchro** [comment]
I'm not in a position to diagnose it so I can't tell you what's wrong or fix it, but you can work around it by loading the classes manually, for example using:

    require './vendor/phpmailer/phpmailer/src/PHPMailer.php';
    require './vendor/phpmailer/phpmailer/src/SMTP.php';
    require './vendor/phpmailer/phpmailer/src/Exception.php';

**Comment by Luco009** [comment]
the error i got  require(): Failed opening required 'banking/PHPMailer-master/src/PHPMailerAutoload.php' (include_path='.:/usr/local/php74/pear') in /home/customer

**Comment by Synchro** [comment]
You're trying to load a very old version of PHPMailer on a version of PHP that's no longer being supported. The file `PHPMailerAutoload.php` no longer exists in PHPMailer. Please [read the readme on how to load PHPMailer](https://github.com/PHPMailer/PHPMailer#installation--loading).

**Comment by Luco009** [comment]
i am using PHP 7.4.33 on siteground

**Comment by pk-kissdevs** [comment]
You could also very likely have a path problem in your app. Check the patch to vendor/autoload such as in Constants.php file, or the relevant location based on your setup/framework.

**Comment by ap-mcleod** [comment]
Even with PHP v8.2, this problem presented itself to me and the solution was related to the Namespace:

Changing fro:

$mail = new PHPMailer; 

To this:

$mail = new PHPMailer\PHPMailer\PHPMailer; 

Hope this helps someone else experiencing a similar issue.

**Comment by Synchro** [comment]
Anyone running into this after upgrading from 5.2 will hopefully learn this by reading [the docs on upgrading](https://github.com/PHPMailer/PHPMailer/blob/master/UPGRADING.md).
