### ISSUE TITLE
function parseAddresses() doesnt decode `name`

### ISSUE THREAD

**Issue by stimorol-ice** [PHPMailer/PHPMailer#2266]
# Problem description

Function parseAddresses() doesn't decode names. Please add mb_decode_mimeheader()

# Code to reproduce

I've got to use modified function in wrapper class with added mb_decode_mimeheader() function:

```
public static function parseAddresses($addrstr, $useimap = true)

...
                    if (static::validateAddress($email)) {
                        $addresses[] = [
                            'name' => trim(str_replace(['"', "'"], '', mb_decode_mimeheader($name))),
                            'address' => $email,
                        ];
                    }
...
}
```
# Debug output
In native call:

["To"]=>
    array(1) {
      [0]=>
      array(2) {
        ["name"]=>
        string(68) "=?utf-8?B?0KLQuNC/0L7Qs9GA0LDRhNC40Y8g0L3QsCDQodCy0LjQsdC70L7QstC+?="
        ["address"]=>
        string(24) "print-sviblovo@yandex.ru"
      }

How it's got to be:

["To"]=>
    array(1) {
      [0]=>
      array(2) {
        ["name"]=>
        string(42) "Типография на Свиблово"
        ["address"]=>
        string(24) "print-sviblovo@yandex.ru"
      }

**Comment by Synchro** [comment]
I will need to wrap this in a check for the mbstring extension as it can't work without it, but it's not a *required* extension for PHPMailer otherwise.
