### ISSUE TITLE
PHPMailer Documentation - error 

### ISSUE THREAD

**Issue by ltdeta** [PHPMailer/PHPMailer#2268]
The link "available online" on [PHPMailer Documentation](https://github.com/PHPMailer/PHPMailer/tree/master/docs#phpmailer-documentation) 
redirects to a web page that does not work properly

**Comment by Synchro** [comment]
It's not especially pretty, but it works fine for me. How exactly does it "not work properly"?

**Comment by stephencamilo** [comment]
The site https://phpmailer.github.io/PHPMailer/ is working, the design looks broken, but it is just not very harmonious.
It is a design issue.
