### ISSUE TITLE
prevent smtp_connect_failed wiki link

### ISSUE THREAD

**Issue by ltdeta** [PHPMailer/PHPMailer#2270]
Is there a way to prevent attaching the url "https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting" to the error 'smtp_connect_failed'. 
For the developer the link is interesting for his customers rather not.

**Comment by Synchro** [comment]
No. You can remove it yourself, but you're better off dealing with the error and displaying your own error message.
