### ISSUE TITLE
PHPMailer using CloudFlare

### ISSUE THREAD

**Issue by enterv0id** [PHPMailer/PHPMailer#2273]
Hi, 

My problem is, that I'm using CloudFlare DNS so the origin server IP hidden from website visitors. But when I'm sending out activation emails through gmail using PHPMailer, my origin server IP is exposed in email header
```
Received: from *********.com ([**origin-server-ip**])
        by smtp.gmail.com with ESMTPSA id y29sm1630909edl.91.2021.02.24.05.03.35
        for <*********@gmail.com>
```

Is there any solution to avoid this?
Thank you in advance

**Comment by Synchro** [comment]
Not that I'm aware of. That header is added by gmail, so perhaps send through/via a different smarthost.

**Comment by Antonio-Rango** [comment]
It is possible to fix.
