### ISSUE TITLE
Got escapeshellcmd() warning

### ISSUE THREAD

**Issue by abolfazl-moeini** [PHPMailer/PHPMailer#2281]
in latest version WordPress (5.7) and PHPMailer (6.3.0) I've got the following message while sending a WordPress comment which is related to send an email via PHPMailer.

Warning: escapeshellcmd() has been disabled for security reasons in wp-includes/PHPMailer/PHPMailer.php on line 1779

Debug backtrace:

array(12) {
	[0]=>
	array(5) {
	["file"]=>
	string(65) "wp-includes/PHPMailer/PHPMailer.php"
	["line"]=>
	int(1874)
	["function"]=>
	string(11) "isShellSafe"
	["class"]=>
	string(29) "PHPMailer\PHPMailer\PHPMailer"
	["type"]=>
	string(2) "::"
	}
	[1]=>
	array(5) {
	["file"]=>
	string(65) "wp-includes/PHPMailer/PHPMailer.php"
	["line"]=>
	int(1635)
	["function"]=>
	string(8) "mailSend"
	["class"]=>
	string(29) "PHPMailer\PHPMailer\PHPMailer"
	["type"]=>
	string(2) "->"
	}
	[2]=>
	array(5) {
	["file"]=>
	string(65) "wp-includes/PHPMailer/PHPMailer.php"
	["line"]=>
	int(1466)
	["function"]=>
	string(8) "postSend"
	["class"]=>
	string(29) "PHPMailer\PHPMailer\PHPMailer"
	["type"]=>
	string(2) "->"
	}
	[3]=>
	array(5) {
	["file"]=>
	string(55) "wp-includes/pluggable.php"
	["line"]=>
	int(531)
	["function"]=>
	string(4) "send"
	["class"]=>
	string(29) "PHPMailer\PHPMailer\PHPMailer"
	["type"]=>
	string(2) "->"
	}
}

**Comment by Synchro** [comment]
This is to do with your local PHP configuration, not PHPMailer or WordPress. Disabling this function is a very silly thing to do as it invites not using it in situations that could create a major security hole.
