### ISSUE TITLE
2021-03-19 15:10:53 SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: No such host is known. (0) SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting Message could not be sent. Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

### ISSUE THREAD

**Issue by kaden-tech** [PHPMailer/PHPMailer#2287]
I have an account with google. (Like most people.)
I put my info in the code.

`<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require 'PHPMailer/PHPMailer/src/Exception.php';
require 'PHPMailer/PHPMailer/src/PHPMailer.php';
require 'PHPMailer/PHPMailer/src/SMTP.php';
// Instantiation and passing [ICODE]true[/ICODE] enables exceptions
$mail = new PHPMailer(true);
try {
    //Server settings
    $mail->SMTPDebug = 2;                                       // Enable verbose debug output
    $mail->isSMTP();                                            // Set mailer to use SMTP
    $mail->Host       = 'smpt.gmail.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth   = true;                                   // Enable SMTP authentication
    $mail->Username   = 'kadenskinner@gmail.com';                     // SMTP username
    $mail->Password   = 'MYPASSWORD';                               // SMTP password
    $mail->SMTPSecure = 'tls';                                  // Enable TLS encryption, [ICODE]ssl[/ICODE] also accepted
    $mail->Port       = 587;                                    // TCP port to connect to
    //Recipients
    $mail->setFrom('kadenskinner@gmail.com', 'Mailer');
    $mail->addAddress('justinkskinner@gmail.com', 'Recipients');     // Add a recipient
    //$mail->addAddress('');
    $mail->addReplyTo('kadenskinner@gmail.com', 'Mailer');
    //$mail->addCC('');
    //$mail->addBCC('');
    // Attachments
    //$mail->addAttachment('');         // Add attachments
    //$mail->addAttachment('');
    // Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = 'Here is the subject';
    $mail->Body    = 'This is the HTML message body <b>in bold!</b>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
    $mail->send();
    echo 'Message has been sent';
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}`

I have done nothing else. Why do I get the error?

I have less secure apps on.

**Comment by sanzeeb3** [comment]
Formatting for readability:

```
<?php use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require 'PHPMailer/PHPMailer/src/Exception.php';
require 'PHPMailer/PHPMailer/src/PHPMailer.php';
require 'PHPMailer/PHPMailer/src/SMTP.php'; // Instantiation and passing [ICODE]true[/ICODE] enables exceptions
$mail = new PHPMailer(true);
try
{ //Server settings
    $mail->SMTPDebug = 2; // Enable verbose debug output
    $mail->isSMTP(); // Set mailer to use SMTP
    $mail->Host = 'smpt.gmail.com'; // Specify main and backup SMTP servers
    $mail->SMTPAuth = true; // Enable SMTP authentication
    $mail->Username = 'kadenskinner@gmail.com'; // SMTP username
    $mail->Password = 'MYPASSWORD'; // SMTP password
    $mail->SMTPSecure = 'tls'; // Enable TLS encryption, [ICODE]ssl[/ICODE] also accepted
    $mail->Port = 587; // TCP port to connect to //Recipients
    $mail->setFrom('kadenskinner@gmail.com', 'Mailer');
    $mail->addAddress('justinkskinner@gmail.com', 'Recipients'); // Add a recipient
    $mail->addAddress('');
    $mail->addReplyTo('kadenskinner@gmail.com', 'Mailer');
    $mail->addCC('');
    $mail->addBCC(''); // Attachments
    $mail->addAttachment(''); // Add attachments
    $mail->addAttachment(''); // Content
    $mail->isHTML(true); // Set email format to HTML
    $mail->Subject = 'Here is the subject';
    $mail->Body = 'This is the HTML message body <b>in bold!</b>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
    $mail->send();
    echo 'Message has been sent';
}
catch(Exception $e)
{
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}


```

**Comment by sanzeeb3** [comment]
Probably because you've empty receipent email address:   

> $mail->addAddress('');

**Comment by kaden-tech** [comment]
I cleaned up the code.
Go to https://stackoverflow.com/questions/66710606/why-do-i-get-this-error-with-phpmailer-when-trying-to-send-an-email?
for the updated code.

**Comment by Synchro** [comment]
It's a typo:

    $mail->Host = 'smpt.gmail.com';

should be:

     $mail->Host = 'smtp.gmail.com';

**Comment by kaden-tech** [comment]
ok

**Comment by kaden-tech** [comment]
I still get an error.

**Comment by Synchro** [comment]
First rule of debugging: read the error message:

> Username and Password not accepted. Learn more at https://support.google.com/mail/?p=BadCredentials
