### ISSUE TITLE
Consider changing wiki edit permissions

### ISSUE THREAD

**Issue by opr** [PHPMailer/PHPMailer#2290]
Hi, I recently followed the link to the troubleshooting documentation (https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting) and found that it had been edited.

Offending commit: https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting/6585cd883ed7b52fc4302159ad527668fa871eed

My commit reverting this: https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting/7143df43992f52351ef48e51fc32f8239d83c0b6

For people unfamiliar with GitHub and the revision system this would be a confusing revision to land on since it contains no troubleshooting information.

Unsure if this has been discussed before, I couldn't see anything on it after a cursory search so feel free to close if you have already thought about this.

Thanks!

**Comment by Synchro** [comment]
Well yes it would be confusing! This has happened in the past, and this time it looks like it was just someone with no idea what they were doing. What's more annoying is that I don't receive any notification when the wiki is changed, so I have no idea when it's been vandalised or damaged like this. I have altered permissions on the wiki, which a shame really.
