### ISSUE TITLE
HTML tags in text, mail preview in Thunderbird

### ISSUE THREAD

**Issue by vol-and** [PHPMailer/PHPMailer#2294]
Hi there,
I got a problem, that a user sees HTML tags in mail preview in Thunderbird, for example `<br />`. And also sees characters instead of `öäü` letters. But if user opens this mail, he sees as it meant to be - without any html tags and with proper `äüö` letters.  

Is it a known bug? What should I check?

                $body = '<html lang="de">Hallo ' . $_SESSION['name'] . ', <br/><br/>
                               .....................
                               ......................';
                $body .= $footer;     // 'text + </html>'
                $mail->setFrom($from->mail, $from->name);
                $mail->addAddress($array['v1'][11]);
                $mail->addReplyTo($reply->mail, $reply->name);
                $mail->addEmbeddedImage(LOGO, 'logo_image', 'Logo.png', 'base64', 'image/png');
                sendMail($mail, $subject, $body);

                function sendMail($mail, $subject, $body)
                {
                    $mail->isHTML(true);
                    $mail->Subject = utf8_decode($subject);
                    $body = utf8_decode($body);
                    $mail->Body = $body;
                    $mail->AltBody = nl2br(Html2Text::convert($body));
                
                    $mail->send();
                    $mail->ClearAddresses();
                }

**Comment by Synchro** [comment]
It's your code doing this:

    $mail->Subject = utf8_decode($subject);
    $body = utf8_decode($body);
    $mail->Body = $body;

Don't do that, you're just breaking things. Do this:

    $mail->CharSet = 'UTF-8';
    $mail->Subject = $subject;
    $mail->Body = $body;

i.e. don't do any of those calls to utf8_decode, let PHPMailer handle UTF-8 natively.

Your are getting `br` tags because you're asking it to add them! Don't do this:

    $mail->AltBody = nl2br(Html2Text::convert($body));

Do this:

    $mail->AltBody = Html2Text::convert($body);
