### ISSUE TITLE
Duplicate mail send bug

### ISSUE THREAD

**Issue by fumagally** [PHPMailer/PHPMailer#2296]
My code to test send mail is it:

`class Mail{

    public static function sendEmail($subject, $to)
    {
        $config = \App\Model\ConfigModel::loadConfig();
        $mail = new PHPMailer();
        $mail->SMTPDebug = SMTP::DEBUG_OFF;
        $mail->isSMTP();
        $mail->Host = $config['smtp_host'];
        $mail->SMTPAuth = true;
        $mail->Username = $config['smtp_login'];
        $mail->Password = $config['smtp_pass'];
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
        $mail->Port = $config['smtp_port'];
        $mail->setFrom($config['smtp_login']);
        $mail->AddAddress($to);
        $mail->isHTML(true);
        echo "Test call duplicate: ".rand()." ################<br>";
        $mail->Subject = $subject.rand();
        $mail->Body = 'test';
        $mail->send();
        echo 'ok';
        exit;
    }
}`

And call is:

`Mail::sendEmail('Test!!! Rand: ', 'mymail@mymail.com');`

The result is: 
`Test call duplicate: 1258187430 ################
ok`

But in my mail receive duplicate like this:

![image](https://user-images.githubusercontent.com/3512770/112688133-30629c80-8e57-11eb-8246-6dea65029e1d.png)

does anyone have a solution for this?

**Comment by fumagally** [comment]
Hi... I've tested in production server and it's ok... in localhost with wampserver the error persist.

**Comment by Synchro** [comment]
[As the docs say](https://github.com/PHPMailer/PHPMailer/wiki/Diagnosing-email-sending-twice-(or-more)), there are several reasons this can happen, but none of them are controlled or caused by PHPMailer. As you're getting two different numbers, it means your script is being run twice. You'll need to figure out what's causing that.

**Comment by fumagally** [comment]
no.. in my debug the script not run twice, only one. the same code executed in localhost and production server... in localhost generate a duplicate mail.

**Comment by Synchro** [comment]
Seriously, your script is being run twice. Check your logs, put in some extra debug output. You might *think* you're running your script once, but it's running twice, and the cause will be something *outside* your script.
