### ISSUE TITLE
Issue with mailSend function in PHPMailer.php

### ISSUE THREAD

**Issue by chadquilter** [PHPMailer/PHPMailer#2301]
Hello, If I am missing anything apologies (maybe this is wordpress issue not adjusting to PHPMailer) but it looks like there might be an issue with a condition in the mailSend function on line 1864 (or there about's). The first condition to set the Sender attribute:

        if ('' === $this->Sender) {
            $this->Sender = $this->From;
        }

Will not trigger the below checks to add the "-f" flag to the start of the sender string, which will cause the mailer to fail should your MTA require a valid from sender. (copied logic below for context)...in fact it looks like the below will never run if Sender is empty and From is defined never adding the -f option. 

        if (empty($this->Sender) && !empty(ini_get('sendmail_from'))) {
            //PHP config has a sender address we can use
            $this->Sender = ini_get('sendmail_from');
        }

        if (!empty($this->Sender) && static::validateAddress($this->Sender)) {
            if (self::isShellSafe($this->Sender)) {
                $params = sprintf('-f%s', $this->Sender);
            }
            $old_from = ini_get('sendmail_from');
            ini_set('sendmail_from', $this->Sender);
        }

Thanks, sorry again if I am missing something.

**Comment by Synchro** [comment]
Are you referring to #2298? Most of that code is gone now.

**Comment by chadquilter** [comment]
Yea, this was exactly my issue. Many thanks! I should have done a search in closed bugs!
