### ISSUE TITLE
Identify the addresses that generated an error

### ISSUE THREAD

**Issue by nicolomonili** [PHPMailer/PHPMailer#2304]
As in [this](https://github.com/PHPMailer/PHPMailer#a-simple-example) example, an email to be sent to multiple recipients. 

How can you easily identify which addresses have generated an error (from `catch (Exception $e) {}` ) in this case (for example because the recipient address does not exist) ?

There is `$mail->ErrorInfo` yes, but the addresses that generated an error are found within other text describing the error.

An example, email sent to 3 addresses, 2 of which do not exist and have generated an error.

`"SMTP Error: The following recipients failed: email@fake1.it: The mail server could not deliver mail to\r\nemail@fake1.it.  The account or domain may\r\nnot exist, they may be blacklisted, or missing the proper dns entries.\r\nemail@fake2.it: The mail server could not deliver mail to\r\nemail@fake2.it.  The account or domain may\r\nnot exist, they may be blacklisted, or missing the proper dns entries.\r\n"`

I should extract the various addresses from the text error, but it's not a very maintainable solution.

**Comment by Synchro** [comment]
There is a little-used feature in PHPMailer that may be useful for this: callbacks. You can inject a function into `$mail->action_function`, and it will be called for *each* recipient within a single SMTP send. Be aware that it will be called for successful as well as unsuccessful addresses, but which it is is given in the first param `isSent`. The callback will be called for each recipient, and those will happen *before* an exception is thrown, which doesn't happen until all recipients have been processed.

Something like (untested):

```php
$mail->action_function = function ($isSent, $to, $cc, $bcc, $subject, $body, $from, $extra) {
    if (!$isSent) {
        echo "problem sending to $to";
    }
}
```

**Comment by nicolomonili** [comment]
This seems to be a **great solution**.
I will test it shortly, thank you very much!

**Comment by nicolomonili** [comment]
The solution works!
Thank you
