### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by SparkyAPI** [PHPMailer/PHPMailer#2313]
Hello. Im using Apache2 and wanna send some mails. But when i write "new PHPMailer()", i get an error, that the function would be undefined and the whole functions of PHPMailer wont work.

The code:
https://prnt.sc/11blkvv

Error:
https://prnt.sc/11bm6wu

The folder where PHPMailer is:
https://prnt.sc/11bllmd

**Comment by XL-2000** [comment]
Without any in-depth views on your code, I see two things wrong here....
1. You declare "use" before "require", in other words, you try to use something before it is there... switch these around
2. "new PHPMailer" does not assign the PHPMailer to a variable to use. I think it should be something like "$phpmailer = new PHPMailer;"

**Comment by Synchro** [comment]
I can't see any of those screen shots. Please post code and error messages as text, not images. Please make sure you've read [the instructions on how to load PHPMailer](https://github.com/PHPMailer/PHPMailer#installation--loading).

**Comment by Synchro** [comment]
`use` is fine before `require`. They define local aliases, and have no relation to files or loaded classes – until you create instances of them, which can happen much later.

**Comment by SparkyAPI** [comment]
> Without any in-depth views on your code, I see some things wrong here....
> 
> 1. You declare "use" before "require", in other words, you try to use something before it is there... switch these around
> 2. "new PHPMailer" does not assign the PHPMailer to a variable to use. I think it should be something like "$phpmailer = new PHPMailer;"
> 3. Your require path should be something like '../PHPMailer...' or '$_SERVER['DOCUMENT_ROOT'].'/PHPMailer...' or whatever

What do you mean with step 3? Where should i put the PHPMailer Folder in?

**Comment by SparkyAPI** [comment]
> `use` is fine before `require`. They define local aliases, and have no relation to files or loaded classes – until you create instances of them, which can happen much later.

It still wont work...

**Comment by Synchro** [comment]
You shouldn't. Learn how to use composer and it will worry about that for you.

**Comment by SparkyAPI** [comment]
> `use` is fine before `require`. They define local aliases, and have no relation to files or loaded classes – until you create instances of them, which can happen much later.

`<?php
    require 'PHPMailer/src/Exception.php';
    require 'PHPMailer/src/PHPMailer.php';
    require 'PHPMailer/src/SMTP.php';

    use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\Exception;

    $phpmailer = new PHPMailer;
?>`

**Comment by Synchro** [comment]
It will work, but convention, and all the PHPMailer docs and examples, put `use` statements first. I suggest you base your code on the examples provided.

If your `require`s don't work, check that you are using the correct paths to wherever you put your PHPMailer files. You've not posted your error messages so I have no idea what's going wrong for you.

**Comment by SparkyAPI** [comment]
> It will work, but convention, and all the PHPMailer docs and examples, put `use` statements first. I suggest you base your code on the examples provided.
> 
> If your `require`s don't work, check that you are using the correct paths to wherever you put your PHPMailer files. You've not posted your error messages so I have no idea what's going wrong for you.

If i load the page, the whole page wont work. My INDEX is iin test and the PHPMailer is in test/PHPMailer/src/

**Comment by Synchro** [comment]
Any fatal error messages will be in your web sever's error log. If you're writing PHP, you need to know where that is.

**Comment by Synchro** [comment]
You could try adding this to the beginning of your script, *before* the requires:

```php
ini_set('display_errors', true);
error_reporting(E_ALL);
```
But be sure to remove them in production.

**Comment by SparkyAPI** [comment]
> You could try adding this to the beginning of your script, _before_ the requires:
> 
> ```
> ini_set('display_errors', true);
> error_reporting(E_ALL);
> ```
> 
> But be sure to remove them in production.

`Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/team/test/index.php on line 11

Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/team/test/index.php on line 11`

**Comment by SparkyAPI** [comment]
Fatal error: Uncaught Error: Class 'PHPMailer\PHPMailer\PHPMailer' not found in /var/www/html/team/test/index.php:13 Stack trace: #0 {main} thrown in /var/www/html/team/test/index.php on line 13

**Comment by SparkyAPI** [comment]
> You could try adding this to the beginning of your script, _before_ the requires:
> 
> ```
> ini_set('display_errors', true);
> error_reporting(E_ALL);
> ```
> 
> But be sure to remove them in production.

Fatal error: Uncaught Error: Class 'PHPMailer\PHPMailer\PHPMailer' not found in /var/www/html/team/test/index.php:13 Stack trace: #0 {main} thrown in /var/www/html/team/test/index.php on line 13

**Comment by Synchro** [comment]
Please post your actual code.

**Comment by SparkyAPI** [comment]
> Please post your actual code.

Now, the site is loading... and loading...

`<?php
ini_set('display_errors', true);
error_reporting(E_ALL);
   //Import PHPMailer classes into the global namespace
   //These must be at the top of your script, not inside a function
   require 'PHPMailer/src/Exception.php';
   require 'PHPMailer/src/PHPMailer.php';
   require 'PHPMailer/src/SMTP.php';

   use PHPMailer\PHPMailer\PHPMailer;
   use PHPMailer\PHPMailer\SMTP;
   use PHPMailer\PHPMailer\Exception;
   
   //Load Composer's autoloader
   
  
?>
<!DOCTYPE html>
<html lang="de">

<head>
    <title>PHP SMPT Mailer</title>
</head>

<body>
<?php
     //Instantiation and passing `true` enables exceptions
   $mail = new PHPMailer(true);
   
   try {
       //Server settings
       $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      //Enable verbose debug output
       $mail->isSMTP();                                            //Send using SMTP
       $mail->Host       = 'smtp.google.com';                     //Set the SMTP server to send through
       $mail->SMTPAuth   = true;                                   //Enable SMTP authentication
       $mail->Username   = 'network@sparkysky.de';                     //SMTP username
       $mail->Password   = 'gbnitmegbubqmbsm';                               //SMTP password
       $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;         //Enable TLS encryption; `PHPMailer::ENCRYPTION_SMTPS` encouraged
       $mail->Port       = 587;                                    //TCP port to connect to, use 465 for `PHPMailer::ENCRYPTION_SMTPS` above
   
       //Recipients
       $mail->setFrom('network@sparkysky.de', 'Mailer');
       $mail->addAddress('Robin-Landsrath@web.de', 'Joe User');     //Add a recipient
       $mail->addAddress('rksnndkand@gmail.com');               //Name is optional
   
       //Attachments
       //$mail->addAttachment('/var/tmp/file.tar.gz');         //Add attachments
      // $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    //Optional name
   
       //Content
       $mail->isHTML(true);                                  //Set email format to HTML
       $mail->Subject = 'Here is the subject';
       $mail->Body    = 'This is the HTML message body <b>in bold!</b>';
       $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
   
       $mail->send();
       echo 'Message has been sent';
   } catch (Exception $e) {
       echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
   }
    
   ?>
   <form method="POST" action="index.php">
        <button type="submit" name="submit">COOOL</button>
    </form>
</body>

</html>`

**Comment by Synchro** [comment]
This code will attempt to send a message every time you load the page. If your hosting provider blocks outbound SMTP (as many do), you will likely have to wait for SMTP's 10-minute timeout period to expire before the script will continue. This is addressed in the troubleshooting guide, including tests to help you diagnose it. Setting `$mail->SMTPDebug = SMTP::DEBUG_CONNECTION;` may make this more apparent.

**Comment by SparkyAPI** [comment]
> This code will attempt to send a message every time you load the page. If your hosting provider blocks outbound SMTP (as many do), you will likely have to wait for SMTP's 10-minute timeout period to expire before the script will continue. This is addressed in the troubleshooting guide, including tests to help you diagnose it. Setting `$mail->SMTPDebug = SMTP::DEBUG_CONNECTION;` may make this more apparent.

I built a little form now with executing the mail stuff. But the site is still loading the whooooole time

**Comment by SparkyAPI** [comment]
And now after removing SMTPDebug i've got that error:
`Message could not be sent. Mailer Error: SMTP Error: Could not authenticate.
`

**Comment by Synchro** [comment]
Sigh. The same SMTPDebug output that would show you what's happening... Re-enable it and post the output here.

**Comment by SparkyAPI** [comment]
> Sigh. The same SMTPDebug output that would show you what's happening... Re-enable it and post the output here.

Bro now im not getting an error, but i dont receive the email

**Comment by Synchro** [comment]
Show the debug output. It will show you the SMTP transaction whether it's successful or not.

**Comment by SparkyAPI** [comment]
> Show the debug output. It will show you the SMTP transaction whether it's successful or not.

SMTP::DEBUG_CONNECTION right?

**Comment by SparkyAPI** [comment]
> Show the debug output. It will show you the SMTP transaction whether it's successful or not.

Yeah, invalid user or password. Im at yandex

**Comment by Synchro** [comment]
I don't know how many times I need to say this, but **POST YOUR DEBUG OUTPUT**.

**Comment by SparkyAPI** [comment]
> I don't know how many times I need to say this, but **POST YOUR DEBUG OUTPUT**.

First, thank you for your help bro. Im from germany okay xD

The output:
`2021-04-13 09:27:59 Connection: opening to smtp.google.com:25, timeout=300, options=array()
2021-04-13 09:27:59 Connection: opened
2021-04-13 09:27:59 SERVER -> CLIENT: 220 mx.google.com ESMTP f7si14528561wrx.322 - gsmtp
2021-04-13 09:27:59 CLIENT -> SERVER: EHLO sparkysky.de
2021-04-13 09:27:59 SERVER -> CLIENT: 250-mx.google.com at your service, [45.146.252.194]250-SIZE 157286400250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
2021-04-13 09:27:59 CLIENT -> SERVER: STARTTLS
2021-04-13 09:27:59 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
2021-04-13 09:27:59 CLIENT -> SERVER: EHLO sparkysky.de
2021-04-13 09:27:59 SERVER -> CLIENT: 250-mx.google.com at your service, [45.146.252.194]250-SIZE 157286400250-8BITMIME250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
SMTP Error: Could not authenticate.
2021-04-13 09:27:59 CLIENT -> SERVER: QUIT
2021-04-13 09:27:59 SERVER -> CLIENT: 221 2.0.0 closing connection f7si14528561wrx.322 - gsmtp
2021-04-13 09:27:59 Connection: closed
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting`

**Comment by Synchro** [comment]
You are connecting to the wrong server to send through gmail (though you said you're sending through Yandex??). As in the gmail example provided, it should be:

    $mail->Host = 'smtp.gmail.com';

**Comment by SparkyAPI** [comment]
> You are connecting to the wrong server to send through gmail (though you said you're sending through Yandex??). As in the gmail example provided, it should be:
> 
> ```
> $mail->Host = 'smtp.gmail.com';
> ```

Oops bro im sorry im using gmail in this example i sent you.

**Comment by Synchro** [comment]
You're connecting to the wrong port – should be 587, as per your script. Looks like gmail doesn't offer authentication on port 25, which is as expected.

**Comment by SparkyAPI** [comment]
> 587

If im adding the variable Port, is the whole site on loading and loading and loading xD

**Comment by SparkyAPI** [comment]
My current Code:
`$mail = new PHPMailer();

try {
  //Server settings
  $mail->isSMTP();                                            //Send using SMTP
  $mail->Host = "smtp.google.com";                     //Set the SMTP server to send through
  $mail->SMTPAuth = true;                                   //Enable SMTP authentication
  $mail->Username = "network@sparkysky.de";                     //SMTP username
  $mail->Password = "lhzmpysygifhvnzk";                               //SMTP password
  $mail->Port = 587;

  $mail->setFrom("network@sparkysky.de", "SparkySky.de");
  $mail->addAddress("Robin-Landsrath@web.de", "Robin");

  $mail->Subject = "Test";
  $mail->Body = "Wenn das geht bin ich ein Gott!";

  if($mail->send()){
    echo "Versendet";
  }else{
      echo "Fehler!".$mail->ErrorInfo;
  }
} catch (Exception $e) {
  echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}`

**Comment by Synchro** [comment]
So we are back to your host blocking it. Read their docs, see what they have to say about outbound SMTP. You could try:

    $mail->Port = 465;
    $mail->SMTPSecure = 'ssl';

though it's likely you'll have the same result.

**Comment by SparkyAPI** [comment]
> So we are back to your host blocking it. Read their docs, see what they have to say about outbound SMTP. You could try:
> 
> ```
> $mail->Port = 465;
> $mail->SMTPSecure = 'ssl';
> ```
> 
> though it's likely you'll have the same result.

So i have to contact my host?

**Comment by Synchro** [comment]
Yes, or at least read their docs. This is usually a pretty common question, so they should document it.

**Comment by SparkyAPI** [comment]
> Yes, or at least read their docs. This is usually a pretty common question, so they should document it.

My host said that they're not blocking ports

**Comment by Synchro** [comment]
So do the tests to confirm that. They are all in the troubleshooting guide. You're not the first to have this kind of hosting problem.

**Comment by SparkyAPI** [comment]
> So do the tests to confirm that. They are all in the troubleshooting guide. You're not the first to have this kind of hosting problem.

Im trying to use "iptables -A INPUT -p udp --dport 587 -j ACCEPT" now.

**Comment by Synchro** [comment]
You are very, very unlikely to need to do that. It's very rare for cheap hosting to do any kind of egress blocking. Also SMTP uses TCP, not UDP. *Find* your problem before trying to fix it. Changing random things is unlikely to help, and if you do accidentally fix it, you won't know how or why.

**Comment by SparkyAPI** [comment]
> You are very, very unlikely to need to do that. It's very rare for cheap hosting to do any kind of egress blocking from within instances (their blocks will be implemented upstream, at the network level). Also SMTP uses TCP, not UDP. _Find_ your problem before trying to fix it. Changing random things is unlikely to help, and if you do accidentally fix it, you won't know how or why.

Now i've got this error:
`SSL loaded 2021-04-13 12:00:38 Connection: opening to ssl://smtp.google.com:25, timeout=300, options=array()
2021-04-13 12:00:38 Connection failed. Error #2: stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:error:1408F10B:SSL routines:ssl3_get_record:wrong version number [/var/www/html/team/test/PHPMailer/src/SMTP.php line 387]
2021-04-13 12:00:38 Connection failed. Error #2: stream_socket_client(): Failed to enable crypto [/var/www/html/team/test/PHPMailer/src/SMTP.php line 387]
2021-04-13 12:00:38 Connection failed. Error #2: stream_socket_client(): unable to connect to ssl://smtp.google.com:25 (Unknown error) [/var/www/html/team/test/PHPMailer/src/SMTP.php line 387]
2021-04-13 12:00:38 SMTP ERROR: Failed to connect to server: (0)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Fehler!SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting`

**Comment by Synchro** [comment]
This is exactly what I mean by "changing random things". `SMTPSecure = 'ssl'` to port 25 will never work. That is why the guide tells you exactly that, and that none of the examples use that combination. If `telnet` to a port doesn't connect, `openssl` to the same port will not work either, and nor will anything from PHP.
