### ISSUE TITLE
Update Wiki for XOAUTH2

### ISSUE THREAD

**Issue by fakhamatia** [PHPMailer/PHPMailer#2318]
Hi
I wanted to use XOAUTH2 , but I faild to configure API and credentials because the google page is very different from [Wiki page](https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail_xoauth.phps).
please update the Wiki page with new images and instructions

**Comment by Synchro** [comment]
It sounds like you're in an excellent position to contribute by updating it yourself so that others can benefit. That's what open-source is all about.

**Comment by fakhamatia** [comment]
If I could have been doing. 
I don't get a lot of this kind of authentication.
And worse than all weak English.
