### ISSUE TITLE
Having issues with Google reCapcha invalid 

### ISSUE THREAD

**Issue by aleare-design** [PHPMailer/PHPMailer#2324]
Hello, 
I'm having issues with Google reCapcha verification with a contact form using PHPmailer. When the form is completed and the check in "I'm not a robot" is ok, press SEND and this message appears: **"reCaptcha is not Valid! Please try again.".** I've tried with reloading, change navigator to latest version, delete historial, and nothing works. 
This is the message in the Google reCapcha admin panel: "We have detected that your website does not verify reCAPTCHA solutions. These verifications are necessary for the service to function properly on your website. You can get more information on our developer website".
Furthermore, I've set the `allow_url_fopen = on` for testing, but still doesn't work.
Does anyone firgure out what's going on, and what's the best solution?
Thank you,

Alejandra

**Comment by Synchro** [comment]
Sorry but this really has nothing to do with PHPMailer. You need to do everything the recaptcha docs tell you. It doesn't make any difference what other code you're running, so I recommend you comment out your email code and concentrate your attention on recaptcha. Once you have that working, then worry about your email code.
