### ISSUE TITLE
Amp4Email support - Google's 2 cents to next-gen emails

### ISSUE THREAD

**Issue by slavino** [PHPMailer/PHPMailer#2329]
https://github.com/PHPMailer/PHPMailer/blob/0acc57db14c444fe25f479583da74ac675c0c161/src/PHPMailer.php#L945

Details here: https://github.com/ikkez/f3-mailer/issues/4

https://amp.dev/documentation/guides-and-tutorials/contribute/integrate-amphtml-email/?referrer=ampproject.org

**Comment by Synchro** [comment]
Not going to happen. AMP for both web and email is a cynical attempt by google to push everyone into using their proprietary protocols, and in the many years it's been available it has proved only that it takes traffic and attention *away* from those who use it, and as a result it's becoming much less popular. If you really want it, you can implement it yourself by setting content types manually and/or subclassing, I don't think you need any underlying changes in PHPMailer.

**Comment by slavino** [comment]
You must be right - it's just like Google's cynical OS called Android... Who on Earth would ever use it?

**Comment by Synchro** [comment]
As I said, PHPMailer doesn't do anything to stop you using it, it's just not going to go out of its way to help you use it. AMP is simply terrible technology. If Google really wanted to do something of benefit to the world of email, they could start by making gmail good.
