### ISSUE TITLE
sender envelope causing errors

### ISSUE THREAD

**Issue by notverygoodat** [PHPMailer/PHPMailer#2330]
I am trying to add a sender envelope so that it will not just send the email from my regular email address (it seems to be defaulting to the username I used for authentication)
I was following the advice given [here ](https://stackoverflow.com/questions/13918999/how-to-change-envelope-sender-address-using-phpmailer)
but it continues to give me 
PHP Fatal error:  Uncaught Error: Attempt to assign property "Sender" on null
which is untrue because I am setting it to
    $pMail ->Sender='newaddress@domain.com';
    $pMail->setFrom('oldaddress@domain.com', 'Name', FALSE);

**Comment by Synchro** [comment]
You're confusing two issues here. Firstly, setting something other than your auth address as the envelope sender is not permitted by many senders, for example gmail doesn't allow this, and it will usually revert to using the address you authenticate with. Whether this happens is outside PHPMailer's control.

The error you're getting doesn't say that there is no `Sender` property, it's saying that you do not have a PHPMailer instance to set it on; it's `$pMail` that is the problem, not the `Sender` property. It suggests you are not saying `$pMail = new PHPMailer();` earlier in your script.
