### ISSUE TITLE
ADD Imagens into body of message

### ISSUE THREAD

**Issue by carcleo** [PHPMailer/PHPMailer#2332]
How ADD Imagens into body of message whay that all navigators can see it?

For example: Gmail, Bol, etc...

Way above its not works to Gmail, but it works to BOL fine

<img src="URL_TO_IMAGE">

**Comment by XL-2000** [comment]
please post your code and debug output

**Comment by Synchro** [comment]
There is no way to guarantee that someone can see your images. All major email clients block linked images by default, and embedded images are very inefficient, and are more likely to be blocked due to content or size restrictions. Your best bet is to keep your layouts minimal and make sure they are meaningful and legible without images, and provide a link to a web version that doesn't suffer the limitations of email.

**Comment by carcleo** [comment]
My CODE:

```
<?php
  
  namespace src\support;

  use PHPMailer\PHPMailer\PHPMailer;

  class SendMail {
      
    public function __construct() {}
        
    public function sender($email)  {

      $sendToName     = $email["name"];
      $sendToEmail    = $email["email"];
       
        
      // DADOS FICTÍCIOS
      $serverName     = 'Titulo do site';
      $serverEmail    = 'contato@site.com.br';
      $serverPassword = 'senha';
      
      $senderName     = $serverName;
      $senderEmail    = $serverEmail;
      $sunject        = contactsSubjects($email["subject"]);
      $what           = $email["what"];
      $message        = $email["message"];

      $messageConcatenated = 
      "<img style='width: 300px' src='" . assets("imgs/logo.png") . "'><br />
       <h1>Formulário gerado via website</h1>
       <h2>Por favor, não responda esse e-mail!</h2>
       Sua mensagem com o assunto: <b>" . $sunject . "</b/><br />
       E mensagem como abaixo<br />
       <b>" . $message . "</b><br />
       Foi recebida!<br /><br />
       <h2>Por favor, aguarde nossa resposta e obrigado por falar conosco!</h2>";
            
                

      $mail = new PHPMailer();
       
      $mail->IsSMTP();
      $mail->IsHTML(true);
      $mail->SMTPAuth  = true;
      $mail->CharSet   = 'UTF-8';
      $mail->Host      = 'smtp.'.substr(strstr($serverEmail, '@'), 1);
      $mail->Port      = '587';
      $mail->Username  = $serverEmail;
      $mail->Password  = $serverPassword;
      $mail->From      = $senderEmail;
      $mail->FromName  = utf8_decode($senderName);
      $mail->Subject   = utf8_decode($sunject);
      $mail->Body      = $messageConcatenated; 
      $mail->AddAddress($sendToEmail,utf8_decode($sendToName));

      return 
            $mail->Send()
                    ? array("success"=>1,"errors"=>"0K")
                    : array("success"=>0,"errors"=>$mail->ErrorInfo); 
      
    }   
      
  }

?>
```

**Comment by carcleo** [comment]
the output, in the Gmail, its a link altered this value. But, in the BOL, it works fine

**Comment by 2624292255** [comment]
请问一下为什么我找不到AddAttachment这个方法，导致发送不了附件

**Comment by 2624292255** [comment]
请问一下，为什么我没有AddAttachment这个方法，导致发送不了附件

**Comment by 2624292255** [comment]
Excuse me, why can't I send attachments because I don't have addattachment

**Comment by Synchro** [comment]
@2624292255 I don't understand your question, and it doesn't seem to have anything to do with this thread.

**Comment by 2624292255** [comment]
> @2624292255我不明白你的问题，它似乎与这个线程没有任何关系。



Unable to transfer attachment

**Comment by Synchro** [comment]
That's not a PHPMailer error message, and I can't tell you anything about it without code and debug output.

**Comment by 2624292255** [comment]
> 这不是 PHPMailer 错误消息，如果没有代码和调试输出，我无法告诉您任何有关它的信息。

Class file has no function to send attachments

**Comment by 2624292255** [comment]
> > 这不是 PHPMailer 错误消息，如果没有代码和调试输出，我无法告诉您任何有关它的信息。
> 
> class文件没有发送附件的功能

Where is the attachments function？

**Comment by Synchro** [comment]
[Right here](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L3064). If you don't have that, you need to get a fresh copy of PHPMailer. Like I said, if you don't post your code or error output, I can't help.

**Comment by 2624292255** [comment]
> [就在这里](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L3064)。如果没有，则需要获取 PHPMailer 的新副本。就像我说的，如果你不发布你的代码或错误输出，我无能为力。

`public function send_mail($tomail, $name, $subject = '', $body = '', $attachment = null) {
		$mail = new PHPMailer();           //实例化PHPMailer对象
		$mail->CharSet = 'UTF-8';           //设定邮件编码，默认ISO-8859-1，如果发中文此项必须设置，否则乱码
		$mail->IsSMTP();                    // 设定使用SMTP服务
		$mail->SMTPDebug = 0;               // SMTP调试功能 0=关闭 1 = 错误和消息 2 = 消息
		$mail->SMTPAuth = true;             // 启用 SMTP 验证功能
		$mail->SMTPSecure = 'ssl';          // 使用安全协议
		$mail->Host = "smtp.qq.com"; // SMTP 服务器
		$mail->Port = 465;                  // SMTP服务器的端口号
		$mail->Username = "5@qq.com";    // SMTP服务器用户名
		$mail->Password = "rqfcdhfj";     // SMTP服务器密码
		$mail->SetFrom('5@qq.com', '留学');
		$replyEmail = '';                   //留空则为发件人EMAIL
		$replyName = '';                    //回复名称（留空则为发件人名称）
		$mail->AddReplyTo($replyEmail, $replyName);
		$mail->Subject = $subject;
		$mail->MsgHTML($body);
		$mail->AddAddress($tomail, $name);
		if($attachment) { // 添加附件
			if(is_string($attachment)){
			is_file($attachment) && $this->AddAttachment($attachment);
		}
		else if(is_array($attachment)){
			foreach ($attachment as $file) {
				is_file($file) && $this->AddAttachment($file);
			}
		}
		}
		$mail -> IsHTML(true);
		return $mail->Send() ? true : $mail->ErrorInfo;
	}
	public function ceshi(){
		$toemail='62772@qq.com';
        $name='华';
        $subject='开卡通知';
        $content='恭喜你，开卡成功。';
		$attachment = DS.'email'.DS.'logo_touming.png';
		$path = str_replace(DS,"/",$attachment);
		
        $this->send_mail($toemail,$name,$subject,$content,$path);
	}`

**Comment by 2624292255** [comment]
> [就在这里](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L3064)。如果没有，则需要获取 PHPMailer 的新副本。就像我说的，如果你不发布你的代码或错误输出，我无能为力。

![微信图片_20210608144435](https://user-images.githubusercontent.com/46675676/121136597-6a451b80-c868-11eb-9e68-f3564bc10512.png)

**Comment by Synchro** [comment]
You're not checking the return value from the calls to `addAttachment`, so you can't tell if they are working or not. Don't use single-line constructs unnecessarily, it just makes your code harder to read and test. Try this:

```php
if ($attachment) { // 添加附件
    if (is_string($attachment)) {
        if (is_file($attachment) && !$this->AddAttachment($attachment)) {
            echo 'File attachment failed.';
        }
    } elseif (is_array($attachment)) {
        foreach ($attachment as $file) {
            if (is_file($file) && !$this->AddAttachment($file)) {
                echo 'File attachment failed.';
            }
        }
    }
}
```

Please don't post code as images; learn to use markdown fences.

Also, since you're calling `msgHtml`, you don't need to call `isHtml'. From the style of your code, it looks like you have based it on an example from a very old version of PHPMailer, so make sure you're using the latest version.

**Comment by 2624292255** [comment]
> 您没有检查对 的调用的返回值`addAttachment`，因此您无法判断它们是否正常工作。不要不必要地使用单行结构，它只会使您的代码更难阅读和测试。试试这个：
> 
> ```
> if ( $ attachment ) { // 添加附件
>     if ( is_string ( $ attachment )) {
>          if ( is_file ( $ attachment ) && ! $ this -> AddAttachment ( $ attachment )) {
>              echo  '文件附件失败。' ;
>         }
>     } elseif ( is_array ( $ attachment )) {
>          foreach ( $ attachment  as  $ file ) {
>              if ( is_file ( $ file ) && ! $ this -> AddAttachment ( $ file )) {
>                  echo  '文件附件失败。' ;
>             }
>         }
>     }
> }
> ```
> 
> 请不要将代码发布为图片；学习使用降价围栏。
> 
> 此外，由于您正在调用`msgHtml`，因此您无需调用`isHtml'。从您的代码风格来看，您似乎是基于一个非常旧版本的 PHPMailer 的示例，因此请确保您使用的是最新版本。
Thank you very much，Maybe I found the reason，Object operation error，

**Comment by 2624292255** [comment]
> > 您检查一下对的调用的返回值`addAttachment`，因此您无法判断它们是否正常工作。不要使用本地使用单行结构，它可以使您的代码更难阅读和测试。
> > ```
> > if ( $ attachment ) { // 添加附件
> >     if ( is_string ( $ attachment )) {
> >          if ( is_file ( $ attachment ) && ! $ this -> AddAttachment ( $ attachment )) {
> >              echo  '文件附件失败。' ;
> >         }
> >     } elseif ( is_array ( $ attachment )) {
> >          foreach ( $ attachment  as  $ file ) {
> >              if ( is_file ( $ file ) && ! $ this -> AddAttachment ( $ file )) {
> >                  echo  '文件附件失败。' ;
> >             }
> >         }
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请不要将代码发布为图片；学习使用降价围栏。
> > 此外，由于您正在调用`msgHtml`，因此您不需要调用`isHtml'。从您的代码风格来看，您似乎是基于一个非常旧版本的 PHPMailer 的示例，因此请确保您使用的是最新版本。
> > 非常感谢，也许我找到了原因，对象操作错误，

if ( $ attachment ) { // 添加附件
    if ( is_string ( $ attachment )) {
         if ( is_file ( $ attachment ) && ! $ this -> AddAttachment ( $ attachment )) {
             echo  '文件附件失败。' ;
        }
    } elseif ( is_array ( $ attachment )) {
         foreach ( $ attachment  as  $ file ) {
             if ( is_file ( $ file ) && ! $ this -> AddAttachment ( $ file )) {
                 echo  '文件附件失败。' ;
            }
        }
    }
}
dump($mail->AddAttachment($attachment)) == ‘false’;

**Comment by Synchro** [comment]
See what I said about `$this` vs `$mail` above; you're still looking at the wrong object.

**Comment by 2624292255** [comment]
> 看看我上面说的`$this`vs `$mail`；你仍然看错了对象。

I've changed everything to $mail
Still not

**Comment by Synchro** [comment]
So check permissions and ownership of the files. If it's saying it can't read the files, it's because it can't read the files!

**Comment by 2624292255** [comment]
> 因此，请检查文件的路径、权限和所有权。如果说它无法读取文件，那是因为它无法读取文件！

Can send mail, but you can't receive attachments
There is no problem with permissions

**Comment by 2624292255** [comment]
> 使用`SMTPDebug = 2`;显示调试输出 如果附件正在发送，您将能够看到它们。

![微信图片_20210608153812](https://user-images.githubusercontent.com/46675676/121143654-dd05c500-c86f-11eb-8707-9d2333f48762.png)

**Comment by 2624292255** [comment]
> > 使用`SMTPDebug = 2`；显示调试输出如果附件正在发送，您将能够看到它们。
> 
> ![微信图片_20210608153812](https://user-images.githubusercontent.com/46675676/121143654-dd05c500-c86f-11eb-8707-9d2333f48762.png)

![微信图片_20210608154018](https://user-images.githubusercontent.com/46675676/121143972-29510500-c870-11eb-9911-c7a47dacbee5.png)

**Comment by Synchro** [comment]
Well, yes, that's [exactly as documented](http://phpmailer.github.io/PHPMailer/classes/PHPMailer.PHPMailer.PHPMailer.html#method_addAttachment). PHPMailer is (deliberately) not an HTTP client, and `addAttachment` will not accept URLs. If you want to send a remote file, fetch it first, then give it to PHPMailer, for example with:

    $mail->addStringAttachment('file.txt', file_get_contents($url));

Fetching the file is *your* responsibility, not PHPMailer's.

**Comment by 2624292255** [comment]
> Well, yes, that's [exactly as documented](http://phpmailer.github.io/PHPMailer/classes/PHPMailer.PHPMailer.PHPMailer.html#method_addAttachment). PHPMailer is (deliberately) not an HTTP client, and `addAttachment` will not accept URLs. If you want to send a remote file, fetch it first, then give it to PHPMailer, for example with:
> 
> ```
> $mail->addStringAttachment('file.txt', file_get_contents($url));
> ```
> 
> Fetching the file is _your_ responsibility, not PHPMailer's.

Still no, I'm stupid
![微信图片_20210608161656](https://user-images.githubusercontent.com/46675676/121149639-6a97e380-c875-11eb-90e1-a021f81de6ed.png)
![微信图片_20210608161700](https://user-images.githubusercontent.com/46675676/121149644-6b307a00-c875-11eb-8a49-0f9095e2364a.png)

**Comment by Synchro** [comment]
That wasn't my point, use it on each item individually - you are concatenating them first which means you can't see their values, because `false . 'string' looks the same as `'string'`. Do this instead:

```php
$data = file_get_contents($url);
$att = $mail->addStringAttachment('file.txt', $data);
var_dump($data, $att);
```

**Comment by Synchro** [comment]
Oops, just realised I have [the arguments](http://phpmailer.github.io/PHPMailer/classes/PHPMailer.PHPMailer.PHPMailer.html#method_addStringAttachment) in the wrong order. It should be:

    $att = $mail->addStringAttachment($data, 'file.txt');

**Comment by 2624292255** [comment]
> 糟糕，刚刚意识到我[的参数](http://phpmailer.github.io/PHPMailer/classes/PHPMailer.PHPMailer.PHPMailer.html#method_addStringAttachment)顺序错误。它应该是：
> 
> ```
> $att = $mail->addStringAttachment($data, 'file.txt');
> ```

![微信图片_20210608165403](https://user-images.githubusercontent.com/46675676/121155579-805bd780-c87a-11eb-99a1-818963580e5e.png)
addStringAttachment()
something the matter

**Comment by 2624292255** [comment]
> 糟糕，刚刚意识到我[的参数](http://phpmailer.github.io/PHPMailer/classes/PHPMailer.PHPMailer.PHPMailer.html#method_addStringAttachment)顺序错误。它应该是：
> 
> ```
> $att = $mail->addStringAttachment($data, 'file.txt');
> ```

![微信图片_20210608165656](https://user-images.githubusercontent.com/46675676/121155943-d892d980-c87a-11eb-9f13-5335196e84d8.png)

**Comment by Synchro** [comment]
That says you are getting `null` returned from `addStringAttachment`, which should only ever return a `bool`. Are you using the latest version of PHPMailer? It might be useful to check what is in `$attachment` too:

    var_dump($attachment, $data, $att);

**Comment by 2624292255** [comment]
> 这表示您正在从`null`返回`addStringAttachment`，它应该只返回 a `bool`。您使用的是最新版本的 PHPMailer 吗？检查内容也可能很有用`$attachment`：
> 
> ```
> var_dump($attachment, $data, $att);
> ```

6.0.1版本
![微信图片_20210608170907](https://user-images.githubusercontent.com/46675676/121158124-b39f6600-c87c-11eb-96c2-b4a0095d080e.png)

**Comment by 2624292255** [comment]
> 您应该运行 6.4.1。始终运行最新版本的所有内容。
> 
> 当我运行此代码时：
> 
> ```
> $附件= 'https://www.ikaiyin.com/email/123.txt' ;
> $ data = file_get_contents ( $ attachment );
> $ att = $ mail -> addStringAttachment ( $ data , 'file.txt' );
> var_dump ( $ attachment , $ data , $ att );
> ```
> 
> 我得到：
> 
> ```
> string(37) "https://www.ikaiyin.com/email/123.txt"
> string(18) "我是文件内容"
> bool(true)
> ```

oh my god。。。。Can I have a copy of the link？

**Comment by Synchro** [comment]
To PHPMailer? You're already [on the site](https://github.com/PHPMailer/PHPMailer)!

**Comment by 2624292255** [comment]
> 到PHPMailer？您已经[在网站上](https://github.com/PHPMailer/PHPMailer)！

This is not the latest one

**Comment by Synchro** [comment]
Yes it is

**Comment by 2624292255** [comment]
> 是的

OKOKOKOK、THANK YOU VERY MUCH
