### ISSUE TITLE
Skip sending emails to invalid adresses

### ISSUE THREAD

**Issue by bluesky40** [PHPMailer/PHPMailer#2333]
I'm trying to send emails via PHPMailer and it's working pretty fine. There's just one problem and I do not know how to fix it. There is the possibility, that I might need to try to send emails to an invalid address due to a non existing domain. It's fine that those emails won't be sent as the domain doesn't exist. When I try to, I get an error message and PHPMailer stops and will also not continue sending emails to other (valid) addresses. Is there any way to kind of skip those invalid emails and force PHPMailer to continue without showing error messages?

```
Error messages:

Fatal error: Uncaught PHPMailer\PHPMailer\Exception: SMTP Error: The following recipients failed: erika@dummyverein.de: Domain does not exist: 'dummyverein.de' in...

SERVER -> CLIENT: 521 5.1.2 Domain does not exist: 'dummyverein.de'

SMTP ERROR: RCPT TO command failed: 521 5.1.2 Domain does not exist: 'dummyverein.de'
```

Code:

```
$mail = new PHPMailer(true);
$mail->CharSet = 'utf-8';  
$mail->isSMTP();
$mail->isHTML(true);
$mail->Host = 'smtp.strato.de';
$mail->Port = 587;
$mail->SMTPAuth = true;
$mail->Username = 'xxxx';
$mail->Password = 'xxxx';
$mail->SMTPSecure = 'tls';
$mail->SMTPDebug = 2;            // set to 2 to get error messages for now 
$mail->MailerDebug = false;
$mail->setFrom($absender, $name);
$mail->addAddress($to);
$mail->Subject = $subject;
         
$mail->Body = $message_other_player;

$mail->send();
```

Source: https://stackoverflow.com/questions/61831042/phpmailer-skip-sending-emails-to-invalid-adresses

**Comment by Synchro** [comment]
No, and I don't see this as unreasonable behaviour by PHPMailer. You're asking PHPMailer to make a value judgement about whether an error is important or not, and it simply doesn't have the capacity to do that. The right way to handle this is to trap the error, remove the problematic recipient, and send again. That way the decision and process for dealing with errors like this is yours, not PHPMailer's.

Doing DNS lookups on domains in advance might help a bit, but in the example you use it's the DNS lookup by the *receiving* server that counts, and you have no control over that. Second question, how do you end up with non-existent domains in the first place? Subsequent to that, why are you mailing multiple addresses, some of which may be at non-existent domains, at the same time? These things should be handled further upstream, before you reach this point.

Separately, you're enabling exceptions but have no exception handling, hence your uncaught exception. There is no such property as `MailerDebug`; if you want debug output, set `SMTPDebug` to 2 or 3.

**Comment by bluesky40** [comment]
Another example:

I have a registration form that sends an activation email to users, after submitting the form to the database.

if the user enters an email address such as: a@a.com in the form, **my script will stop** and shows server error to user.

P.s: I do not care if the user enters the correct email or not. Because I want the user to be able to register without the correct email address!

**Comment by Synchro** [comment]
Well as I said, you are asking PHPMailer to throw exceptions, but you have no code to deal with them when they happen, so it's up to you to fix this. There are plenty of examples provided to show you how.

**Comment by bluesky40** [comment]
My problem was solved with `try ... catch`

```
$mail=new PHPMailer(true);
try {
$mail->CharSet = 'utf-8';  
$mail->isSMTP();
$mail->isHTML(true);
$mail->Host = 'smtp.strato.de';
$mail->Port = 587;
$mail->SMTPAuth = true;
$mail->Username = 'xxxx';
$mail->Password = 'xxxx';
$mail->SMTPSecure = 'tls';
$mail->SMTPDebug = 0;
$mail->MailerDebug = false;
$mail->setFrom($absender, $name);
$mail->addAddress($to);
$mail->Subject = $subject;
$mail->Body = $message_other_player;
}

$mail->send();
      // echo 'Message has been sent';
   } catch (Exception $e) {
     //  echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
   }
```
