### ISSUE TITLE
How do I style what comes to an e-mail from a form on a website?

### ISSUE THREAD

**Issue by KostiantynKondratiuk** [PHPMailer/PHPMailer#2336]
Hi! The text is from a form that comes to the electronic mail is small and I want to increase its size. How can I do that?
I tried writing in sendmail.php file in different ways:

<style>
    .form-php {
        font-size: 40px;
      }
    </style>';

Or like this:

$body.= '<style>
    .form-php {
        font-size: 40px;
      }
    </style>';

Or like this:

$_POST.= '<style>
    
        font-size: 40px;
     
    </style>';

But it doesn’t work.
Please write how to do it properly. If you can with an example. Thank you!

**Comment by Synchro** [comment]
If you're just sending contact info to yourself you're probably best off using plain text and relying on your email client to punch the size.

Beyond that, inline styles are what you need, not style tags. Try this:

    <p style="font-size: 40px">hello</p>

Other approaches are likely to be filtered out or ignored, but test across email clients as they vary a lot. Outlook and gmail are especially bad.

**Comment by KostiantynKondratiuk** [comment]
> If you're just sending contact info to yourself you're probably best off using plain text and relying on your email client to punch the size.
> 
> Beyond that, inline styles are what you need, not style tags. Try this:
> 
> ```
> <p style="font-size: 40px">hello</p>
> ```
> 
> Other approaches are likely to be filtered out or ignored, but test across email clients as they vary a lot. Outlook and gmail are especially bad.

**Comment by KostiantynKondratiuk** [comment]
It’s working, thank you!
