### ISSUE TITLE
Question No mails in sent folder

### ISSUE THREAD

**Issue by psander247** [PHPMailer/PHPMailer#2337]
Hello 
I´m new to PHPMailer. I manged to send emails with it just fine. But when I login to my mail account at my provider I can´t see any messages in the sent folder which were sent by phpMailer

Is this normal or is there a setting I´m missing?

Thank you

**Comment by Synchro** [comment]
No, this is normal. You can configure an outbound mail server to automatically save sent messages, but it's usually left up to the client. The normal way to do it is to upload the message via IMAP. Take a look at the gmail example provided with PHPMailer for [a basic example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail.phps#L88) (its out of scope for PHPMailer, but useful to know).
