### ISSUE TITLE
Keep the timeout minimal.

### ISSUE THREAD

**Issue by vijay94** [PHPMailer/PHPMailer#2341]
Recently i set up moodle which internally used phpmailer to send mails. In moodle they are not setting the timeout so it takes the default value of 300. Which results in php-fpm to be blocked for sometime if connection cant be established. So it will be good to have default timeout as low as possible. I will also raise a bug to set timeout in moodle.

**Comment by Synchro** [comment]
Nope. Those timeouts are part of the SMTP spec, and you should not change them. The right way to deal with this is to install a local mail server and use it as a relay. This will be much, much faster for your apps, more reliable, and not break any SMTP RFCs.
