### ISSUE TITLE
Get Sent Email Address

### ISSUE THREAD

**Issue by mastenwap** [PHPMailer/PHPMailer#2342]
Hello,

i have a problem with send email, can i get logger in sent email ? i want to see all address in success send.
maybe i can get a json output.
because if i check one by one its very wasted my time, i send 500 email every day.

thanks for your help

**Comment by Synchro** [comment]
You *should* be sending messages one by one. I do that when sending over 500 messages *per second*. Beyond that, you can generate a log of your SMTP traffic by injecting your own handler into [the `Debutoutput` property](http://phpmailer.github.io/PHPMailer/classes/PHPMailer.PHPMailer.PHPMailer.html#property_Debugoutput), which you can use to generate JSON or whatever other format you want.
