### ISSUE TITLE
Having issues with PHPMailer and Afrihost

### ISSUE THREAD

**Issue by MartinDeBeer** [PHPMailer/PHPMailer#2343]
So when I first started using PHPMailer I got it to work and now that my website is launched the emails don't want to work. I don't know if it's a problem with my code or with the server, but at first it stopped sending attachments, then it stopped sending emails. I have 2 separate email pages. The one works with attachments as well and the other doesn't us them. I started getting errors like an hour ago.
My code for the page that doesn't use attachments: 
`use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\Exception;

    require 'PHPMailer/Exception.php';
    require 'PHPMailer/PHPMailer.php';
    require 'PHPMailer/SMTP.php';

    // Start the session and connect to db
    session_start();
    include('connectDB.php');

    if(isset($_SESSION['emailAddress'])){
        $firstName = $_SESSION['firstName'];
        $lastName = $_SESSION['lastName'];
        $emailAddress = $_SESSION['emailAddress'];
        $cellNumber = $_SESSION['cell'];
        $idNumber = $_SESSION['userID'];
        $age = $_SESSION['age'];
        $gender = $_SESSION['gender'];
    }
    else {
        $firstName = $_POST['firstName'];
        $lastName = $_POST['lastName'];
        $emailAddress = $_POST['emailAddress'];
        $cellNumber = $_POST['cellNumber'];
        $idNumber = $_POST['userID'];
        $age = $_POST['age'];
        $gender = $_POST['gender'];
    }

    $mail = new PHPMailer();

    try {
        //Server settings
        $mail->SMTPDebug = 2;
        $mail->isSMTP();
        $mail->Host  = 'mail.advicebot.co.za';
        $mail->SMTPAuth   = true;
        $mail->Username   = 'no-reply@advicebot.co.za';
        $mail->Password   = 'MySuperSecretPassword';
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;         
        $mail->Port = 465;                                    
        $mail->SMTPSecure = 'ssl';

        //Recipients
        $mail->setFrom('no-reply@advicebot.co.za', 'No Reply');
        $mail->addAddress('admin@advicebot.co.za');

        //Content
        $mail->isHTML();
        // Single Need Will / Life Cover / Disability
        if(isset($_POST['submitInfo'])){
            if(isset($_SESSION['will'])){
                $tmp = 'Will and Testament';
            }else if(isset($_SESSION['lifeCover'])){
                $tmp = 'Life Cover';
            }else if(isset($_SESSION['disability'])){
                $tmp = 'Trauma and Disability';
            }
            $mail->Subject = 'Single Need - ' . $tmp . ' of ' . $firstName . ' ' . $lastName;
            $mail->Body = '
            <table>
            <tr>
            <td>First Name: </td>
            <td>' . $firstName . '</td>
            </tr>
            <tr>
            <td>Last Name: </td>
            <td>' . $lastName . '</td>
            </tr>
            <tr>
            <td>ID Number: </td>
            <td>' . $idNumber . '</td>
            </tr>
            <tr>
            <td>Cellphone Number: </td>
            <td>' . $cellNumber . '</td>
            </tr>
            <tr>
            <td>Email Address: </td>
            <td>' . $emailAddress . '</td>
            </tr>
            </table>
            ';
        }
        // Astute Permission Form
        if(isset($_POST['permission'])){
            $mail -> Subject = 'Astute Permission form of ' . $firstName . ' ' . $lastName;
            $mail -> Body = '
            <table>
            <tr>
            <td>First Name: </td>
            <td>' . $firstName . '</td>
            </tr>
            <tr>
            <td>Last Name: </td>
            <td>' . $lastName . '</td>
            </tr>
            <tr>
            <td>ID Number: </td>
            <td>' . $idNumber . '</td>
            </tr>
            <tr>
            <td>Email Address: </td>
            <td>' . $emailAddress . '</td>
            </tr>
            </table>
            <h3>I acknowledge the following:</h3>
            <ol>
                <li>Appropriate financial advice can only be furnished after full and proper disclosure of relevant financial and private information about the client</li>
                <li>
                Such information is furthermore required to:
                <ol>
                    <li>Determine my financial situation, financial product experience and financial needs and objectives</li>
                    <li>Acquire, maintain and service any financial product or to render related intermediary services.</li>
                </ol>
                </li>
                <li>
                Such information may include any information relating to, or interest in:
                <ol>
                    <li>Long-term insurance</li>
                    <li>Collective investment schemes</li>
                    <li>Pension funds</li>
                    <li>Any other financial product or service</li>
                </ol>
                </li>
                <li>
                My/our interest will be best served for stated purpose if any and all such information is provided by:
                <ol>
                    <li>The Financial Services Exchange (Pty) Ltd, trading as Astute, or any other institution providing a mechanism for the transmission of such information, or</li>
                    <li>any other authorized financial services provider</li>
                </ol>
                </li>
            </ol>
            <p>I/we herewith give consent to the Financial Service Provider and / or his / her / its authorized user(s) below to obtain such information through Astute.</p>
            <table>
                <tr>
                    <td>Financial Service Provider</td>
                    <td>Joroy0082CC</td>
                </tr>
                <tr>
                    <td>FSP License Number</td>
                    <td>27368</td>
                </tr>
                <tr>
                    <td>Authorized user</td>
                    <td>A. Bosch (Key person)</td>
                </tr>
            </table>
            <p>I/we confirm that the Financial Service Provider and / or his / her / its authorized user(s) will be acting on my/our behalf and I/we hereby waive any right to privacy only for the stated purpose. All information so obtained must be treated as confidential by the Financial Service Provider and / or his / her / its authorized user(s) and may not be made public in any way without my/our written consent.</p>

            <p>This consent to obtain information will remain effective until cancelled by me/us in writing, or, </p>

            <p>This consent shall remain valid for a period of <b>6 months</b> from the date of my signature</p>';
            if(isset($_POST['spouseFirst'])){
                $spouseFirst = $_POST['spouseFirst'];
                $spouseLast = $_POST['spouseLast'];
                $spouseID = $_POST['spouseId'];
                $mail -> Body = '
                <table>
                <tr>
                <td>First Name: </td>
                <td>' . $firstName . '</td>
                </tr>
                <tr>
                <td>Last Name: </td>
                <td>' . $lastName . '</td>
                </tr>
                <tr>
                <td>ID Number: </td>
                <td>' . $idNumber . '</td>
                </tr>
                <tr>
                <td>Email Address: </td>
                <td>' . $emailAddress . '</td>
                </tr>
                <td>First Name: </td>
                <td>' . $spouseFirst . '</td>
                </tr>
                <tr>
                <td>Last Name: </td>
                <td>' . $spouseLast . '</td>
                </tr>
                <tr>
                <td>ID Number: </td>
                <td>' . $spouseID . '</td>
                </tr>
                </table>
                <h3>I acknowledge the following:</h3>
            <ol>
                <li>Appropriate financial advice can only be furnished after full and proper disclosure of relevant financial and private information about the client</li>
                <li>
                Such information is furthermore required to:
                <ol>
                    <li>Determine my financial situation, financial product experience and financial needs and objectives</li>
                    <li>Acquire, maintain and service any financial product or to render related intermediary services.</li>
                </ol>
                </li>
                <li>
                Such information may include any information relating to, or interest in:
                <ol>
                    <li>Long-term insurance</li>
                    <li>Collective investment schemes</li>
                    <li>Pension funds</li>
                    <li>Any other financial product or service</li>
                </ol>
                </li>
                <li>
                My/our interest will be best served for stated purpose if any and all such information is provided by:
                <ol>
                    <li>The Financial Services Exchange (Pty) Ltd, trading as Astute, or any other institution providing a mechanism for the transmission of such information, or</li>
                    <li>any other authorized financial services provider</li>
                </ol>
                </li>
            </ol>
            <p>I/we herewith give consent to the Financial Service Provider and / or his / her / its authorized user(s) below to obtain such information through Astute.</p>
            <table>
                <tr>
                    <td>Financial Service Provider</td>
                    <td>Joroy0082CC</td>
                </tr>
                <tr>
                    <td>FSP License Number</td>
                    <td>27368</td>
                </tr>
                <tr>
                    <td>Authorized user</td>
                    <td>A. Bosch (Key person)</td>
                </tr>
            </table>
            <p>I/we confirm that the Financial Service Provider and / or his / her / its authorized user(s) will be acting on my/our behalf and I/we hereby waive any right to privacy only for the stated purpose. All information so obtained must be treated as confidential by the Financial Service Provider and / or his / her / its authorized user(s) and may not be made public in any way without my/our written consent.</p>

            <p>This consent to obtain information will remain effective until cancelled by me/us in writing, or, </p>

            <p>This consent shall remain valid for a period of <b>6 months</b> from the date of my signature</p>';
            }
            
        }
        // Single Need - Retirement / Savings
        if(isset($_POST['submitReport'])){
            $employment = $_POST['employment'];
            $maritalStatus = $_POST['maritalStatus'];
            $lumpSum = $_POST['lumpSum'];
            $saving = $_POST['saving'];
            $future = $_POST['future'];
            $marketDrop = $_POST['marketDrop'];
            $guaranteedOrPotential = $_POST['guaranteedOrPotential'];
            $settle = $_POST['settle'];
            $score = $_POST['score'];
            if(isset($_SESSION['savings'])){
                $mail -> Subject = "Single Need Savings Report of " . $firstName . ' ' . $surname;
            } else if(isset($_SESSION['retirement'])){
                $mail -> Subject = "Single Need Retirement Report of " . $firstName . ' ' . $surname;
            }
            $mail -> Body = "
            <table>
            <th>Question</th>
            <th>Answer</th>
            <tr>
            <td>What is your first name?</td>
            <td>" . $firstName . "</td>
            </tr>
            <tr>
            <td>What is your last name?</td>
            <td>" . $lastName . "</td>
            </tr>
            <tr>
            <td>What is your email address?</td>
            <td>" . $emailAddress . "</td>
            </tr>
            <tr>
            <td>Please input your ID Number</td>
            <td>" . $idNumber . "</td>
            </tr>
            <tr>
            <td>Your age is:</td>
            <td>" . $age . "</td>
            </tr>
            <tr>
            <td>Your gender is:</td>
            <td>" . $gender . "</td>
            </tr>
            <tr>
            <td>Are you self-employed or a salary worker?</td>
            <td>"  . $employment . "</td>
            </tr>
            <tr>
            <td>Marital Status:</td>
            <td>"  . $maritalStatus . "</td>
            </tr>
            <tr>
            <td>Do you have a lump sum to invest?</td>
            <td>"  . $lumpSum . "</td>
            </tr>
            <tr>
            <td>Do you intend to save a monthly amount?</td>
            <td>"  . $saving . "</td>
            </tr>
            <tr>
            <td>How do you feel about your financial future?</td>
            <td>"  . $future . "</td>
            </tr>
            <tr>
            <td>The market dropped quickly and your portfolio value dropped by -20%. What would you do?</td>
            <td>"  . $marketDrop . "</td>
            </tr>
            <tr>
            <td>Would you settle for a guaranteed return of between 5% or a potential return of 0% and 15%?</td>
            <td>"  . $guaranteedOrPotential . "</td>
            </tr>
            <tr>
            <td>Would you settle for a potential return of between 5% and 10% or a potential return of between -10% and 25%?</td>
            <td>"  . $settle . "</td>
            </tr>
            <tr>
            <td>Your score: </td>
            <td>"  . $score . "</td>
            </tr>
            </table>";
        }
        // Full Report Post
        if(isset($_POST['fullReport'])){
            $autoID = $_SESSION['autoID'];
            $select = "select * from report where userID = '$autoID' and reportID=(select max(reportID) from report)";
            $result = mysqli_query($conn, $select);
            $row = mysqli_fetch_assoc($result);

            // Life Cover
            $death = $row['deathCover'];
            if(isset($_POST['lifeYesNo'])) $deathYesNo = $_POST['lifeYesNo'];
            if(isset($_POST['lifeAmount'])) $lifeAmount = $_POST['lifeAmount'];
            if(isset($_POST['lifeAmountNeeded'])) $lifeAmountNeeded = $_POST['lifeAmountNeeded'];
            if(isset($_POST['lifeAmountDiff'])) $lifeAmountDiff = $_POST['lifeAmountDiff'];
            // Disability And Trauma
            $disability = $row['disability'];
            if(isset($_POST['disabilityYesNo'])) $disabilityYesNo = $_POST['disabilityYesNo'];
            if(isset($_POST['traumaAmount'])) $traumaAmount = $_POST['traumaAmount'];
            if(isset($_POST['traumaAmountNeeded'])) $traumaAmountNeeded = $_POST['traumaAmountNeeded'];
            if(isset($_POST['traumaAmountDiff'])) $traumaAmountDiff = $_POST['traumaAmountDiff'];
            // Savings
            $savings = $row['savings'];
            if(isset($_POST['savingsYesNo'])) $savingsYesNo = $_POST['savingsYesNo'];
            if(isset($_POST['riskProfile'])) $riskProfile = $_POST['riskProfile'];
            // Retirement
            $retirement = $row['retirement'];
            if(isset($_POST['retirementYesNo'])) $retirementYesNo = $_POST['retirementYesNo'];
            // Will
            $will = $row['will'];
            if(isset($_POST['willYesNo'])) $willYesNo = $_POST['willYesNo'];
            // Short Term
            $shortTerm = $row['shortTerm'];
            if(isset($_POST['shortTermYesNo'])) $shortTermYesNo = $_POST['shortTermYesNo'];
            if(isset($_POST['schedule'])) $schedule = $_POST['schedule'];
            $mail -> Subject = "Full report of " . $firstName . ' ' . $lastName;
            $mail -> Body = '
            <table>
            <tr>
            <td>First Name: </td>
            <td>' . $firstName . '</td>
            </tr>
            <tr>
            <td>Last Name: </td>
            <td> ' . $lastName . '</td>
            </tr>
            <tr>
            <td>Email Address: </td>
            <td>' . $emailAddress . '</td>
            </tr>
            <tr>
            <td>ID number: </td>
            <td>' . $idNumber . '</td>
            </tr>
            <tr>
            <td>Age:</td>
            <td>' . $age . '</td>
            </tr>
            <tr>
            <td>Gender: </td>
            <td>' . $gender . '</td>
            </tr>
            </table>
            <table>
            <th></th>
            <th></th>
            <th>Covered or Not</th>
            <th>Existing Cover</th>
            <th>Ideal Amount</th>
            <th>Difference</th>
            <tr>
                <td>Death: </td>
                <td><progress value="' . $death .'" max="65"></progress></td>
                <td>' . $deathYesNo . '</td>
                <td>' . $lifeAmount . '</td>
                <td>' . $lifeAmountNeeded . '</td>
                <td>' . $lifeAmountDiff . '</td>
            </tr>
            <tr>
                <td>Disability: </td>
                <td><progress value="' . $disability .'" max="65"></progress></td>
                <td>' . $disabilityYesNo . '</td>
                <td>' . $traumaAmount . '</td>
                <td>' . $traumaAmountNeeded . '</td>
                <td>' . $traumaAmountDiff . '</td>
            </tr>
            <tr>
                <td>Savings: </td>
                <td><progress value="' . $savings .'" max="65"></progress></td>
                <td>' . $savingsYesNo . '</td>
                <td>' . $riskProfile . '</td>
            </tr>
            <tr>
                    <td>Retirement: </td>
                    <td><progress value="' . $retirement .'" max="65"></progress></td>
                    <td>' . $retirementYesNo .'</td>
            </tr>
            <tr>
                <td>Will:</td>
                <td> ' . $will .' </td>
                <td class="reportAnswer" name="willYesNo" id="willYesNo" >I don\'t have a will</td>
            </tr>
            <tr>
                <td>Short Term: </td>
                <td>' . $shortTerm . ' </td>
                <td>' . $shortTermYesNo .'</td>
                <td>' . $schedule . '</td>
            </tr>
            </table>
            ';  
        }
    $mail->AltBody = 'Single Need';

    $mail->send();
    echo 'Message has been sent';

    } catch (Exception $e) {
        echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
    }    
?>`
The error I get with this one is:
2021-05-23 14:20:46 SERVER -> CLIENT: 220-nikka.aserv.co.za ESMTP Exim 4.94.2 #2 Sun, 23 May 2021 16:20:46 +0200 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail.
2021-05-23 14:20:46 CLIENT -> SERVER: EHLO localhost
2021-05-23 14:20:46 SERVER -> CLIENT: 250-nikka.aserv.co.za Hello 8ta-249-2-249.telkomadsl.co.za [102.249.2.249]250-SIZE 52428800250-8BITMIME250-PIPELINING250-PIPE_CONNECT250-AUTH PLAIN LOGIN250 HELP
2021-05-23 14:20:46 CLIENT -> SERVER: AUTH LOGIN
2021-05-23 14:20:46 SERVER -> CLIENT: 334 VXNlcm5hbWU6
2021-05-23 14:20:46 CLIENT -> SERVER: [credentials hidden]
2021-05-23 14:20:46 SERVER -> CLIENT: 334 UGFzc3dvcmQ6
2021-05-23 14:20:46 CLIENT -> SERVER: [credentials hidden]
2021-05-23 14:20:47 SERVER -> CLIENT: 235 Authentication succeeded
2021-05-23 14:20:47 CLIENT -> SERVER: MAIL FROM:<no-reply@advicebot.co.za>
2021-05-23 14:20:47 SERVER -> CLIENT: 250 OK
2021-05-23 14:20:47 CLIENT -> SERVER: RCPT TO:<admin@advicebot.co.za>
2021-05-23 14:20:47 SERVER -> CLIENT: 250 Accepted
2021-05-23 14:20:47 CLIENT -> SERVER: DATA
2021-05-23 14:20:47 SERVER -> CLIENT: 354 Enter message, ending with "." on a line by itself
and a bunch of other stuff

The code that does use attachments: 
`<?php

  use PHPMailer\PHPMailer\PHPMailer;
  use PHPMailer\PHPMailer\Exception;

  require 'PHPMailer/Exception.php';
  require 'PHPMailer/PHPMailer.php';
  require 'PHPMailer/SMTP.php';

    session_start();
    include('connectDB.php');
    if(isset($_SESSION['emailAddress'])){
      $userId = $_SESSION['autoID'];
      $select = "SELECT * FROM users WHERE autoID = '$userId'";
      $result = mysqli_query($conn, $select);
      $row = mysqli_fetch_array($result);
      $firstName = $row['firstName'];
      $lastName = $row['lastName'];
      $emailAddress = $row['emailAddress'];
    } else {
      $firstName = $_POST['firstName'];
      $lastName = $_POST['lastName'];
      $emailAddress = $_POST['emailAddress'];
      $idNumber = $_POST['idNumber'];
      $cellNumber = $_POST['cellNumber'];
    }
    function mailToCustomer($emailAddress){
      $subject = 'Thank you for using AdviceBot';
      $customerMsg = "
      <html>
      <head>
      <title>HTML email</title>
      </head>
      <body>
      <p>Thank you for using AdviceBot. Someone will be in contact with you soon to answer your query.</p>
      </body>
      </html>
      ";
      $headers = "MIME-Version: 1.0" . "\r\n";
      $headers .= "Content-type: text/html; charset=UTF-8" . "\r\n";
      $headers .= "From: No Reply<no-reply@advicebot.co.za>" . "\r\n";
      mail($emailAddress, $subject, $customerMsg, $headers);

  }

  echo $_FILES['schedule']['name'];
    echo getcwd();
    $newFile = $firstName . "schedule.pdf";

    $filename = $_FILES["schedule"]["name"];
    $_FILES["schedule"]["name"] = $newFile;    
    $target_dir = "upload/";
    $target_file = $target_dir . basename($_FILES["schedule"]["name"]);
    $uploadOk = 1;
    $imageFileType = strtolower(pathinfo($target_file,PATHINFO_EXTENSION));

    // Check if file already exists
    if (file_exists($target_file)) {
      echo "Sorry, file already exists.";
      $uploadOk = 0;
    }

    // Allow certain file formats
    if($imageFileType != "pdf" ) {
      echo "Sorry, only pdf files are allowed.";
      $uploadOk = 0;
    }

    // Check if $uploadOk is set to 0 by an error
    if ($uploadOk == 0) {
      echo "Sorry, your file was not uploaded.";
    // if everything is ok, try to upload file
    } else {
      if (move_uploaded_file($_FILES["schedule"]["tmp_name"], "../upload/" . $newFile)) {
        $filename = htmlspecialchars( basename( $_FILES["schedule"]["name"]));

        echo "The file ". $filename . " has been uploaded.";
        // header('location: autoMail.php');
      } else {
        echo "Sorry, there was an error uploading your file.";
      }
    }
    

    
    $file = "../upload/" . $newFile;

    $mail = new PHPMailer();

    try {
    //Server settings
    $mail->SMTPDebug = 2;
    $mail->isSMTP();
    $mail->Host       = 'mail.advicebot.co.za';                     
    $mail->SMTPAuth   = true;                                  
    $mail->Username   = 'no-reply@advicebot.co.za';                    
    $mail->Password   = 'MySuperSecretPassword';                              
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;         
    $mail->Port       = 465;                                    
    $mail->SMTPSecure = 'ssl';

    //Recipients
    $mail->setFrom('no-reply@advicebot.co.za', 'No Reply');
    $mail->addAddress('admin@advicebot.co.za');

    //Attachments
    $mail->addAttachment($file);

    //Content
    $mail->isHTML(true);
    if(isset($_SESSION['emailAddress'])){
      $mail->Subject = 'Short Term Schedule of ' . $firstName. ' ' . $lastName;
      $mail->Body    = 'Please see attached the Short Term Schedule of ' . $firstName . ' ' . $lastName;
    } else {
      $mail->Subject = 'Single Need - Short Term Schedule of ' . $firstName. ' ' . $lastName;
      $mail->Body = '
        <table>
          <tr>
          <td>First Name: </td>
          <td>' . $firstName . '</td>
          </tr>
          <tr>
          <td>Last Name: </td>
          <td>' . $lastName . '</td>
          </tr>
          <tr>
          <td>ID Number: </td>
          <td>' . $idNumber . '</td>
          </tr>
          <tr>
          <td>Cellphone Number: </td>
          <td>' . $cellNumber . '</td>
          </tr>
          <tr>
          <td>Email Address: </td>
          <td>' . $emailAddress . '</td>
          </tr>
        </table>
      ';
    }
    $mail->AltBody = 'Please see attached schedule';

    $mail->send();
    echo 'Message has been sent';
    unlink($file);
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}
?>` 

Same error

**Comment by Synchro** [comment]
There is no error here. You are just showing debug output. I can see that you're using the wrong encryption mode for port 465 but nothing otherwise.
Generally this code is quite a mess, and it's completely excessive for a bug report.

**Comment by MartinDeBeer** [comment]
> There is no error here. You are just showing debug output. I can see that you're using the wrong encryption mode for port 465 but nothing otherwise.
> Generally this code is quite a mess, and it's completely excessive for a bug report.

Ok, I get that it's just debug output, but the emails aren't working and they were working. Could it be a problem with my hosting provider??
And you said my code is a mess, what specifically is wrong with it??

**Comment by Synchro** [comment]
I wondered why your code was working at all, then I realised that you are setting S<MTPSecure twice:

        $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;         
        $mail->Port = 465;                                    
        $mail->SMTPSecure = 'ssl';

If you're using Port 465, the second one is correct.

The code is actually fine – it was mainly that is is monstrously long for a report like this and mostly unreadable on my phone. Despite the great length, you managed to cut off the only part of the debug output that might matter ("and a bunch of other stuff"): the end of the DATA command.

You have no errors, there is nothing visible wrong here. If you showed the response to the DATA command, or any error output we might be able to do something, but as it stands there is nothing apparently wrong at all.

**Comment by MartinDeBeer** [comment]
> I wondered why your code was working at all, then I realised that you are setting S<MTPSecure twice:
> 
> ```
>     $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;         
>     $mail->Port = 465;                                    
>     $mail->SMTPSecure = 'ssl';
> ```
> 
> If you're using Port 465, the second one is correct, which is why it works. You can delete the first one.
> 
> The code is actually fine – it was mainly that is is monstrously long for a report like this and mostly unreadable on my phone. Despite the great length, you managed to cut off the only part of the debug output that might matter ("and a bunch of other stuff"): the end of the DATA command.
> 
> You have no errors, there is nothing visible wrong here. If you showed the response to the DATA command, or any error output we might be able to do something, but as it stands there is nothing apparently wrong at all.

Ohhhh, I didn't even realize that both say SMTPSecure, now I feel stupid haha.. But I figured it out last night after reading your comment. Turns out the issue is with Afrihost and I also refactored my code a bit.. Just to be clear, you know that what I sent was 2 different pages, right??

**Comment by Synchro** [comment]
It doesn't matter how many pages you have, if you have no error messages, there's nothing to diagnose!

Regarding which `SMTPSecure` mode to use, that's covered [in the docs](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#encryption-flavours).
