### ISSUE TITLE
Overloaded receivers during loop passes

### ISSUE THREAD

**Issue by RSheetz** [PHPMailer/PHPMailer#2346]
# Problem description
I am using XAMP on a Windows 10 virtual machine .
My problem has occurred while programming automated mails.

The general function of my script are (Automated reminders):
Get data from a database and send it to the recipients. 

Unfortunately the recipients are overloaded and the email still goes to others which should not be possible.
Despite some tests and error analysis I can't find the error or can say to a large extent that my script works as it should. From this I conclude that something is wrong with PHPMailer.

Unfortunately one error does not appear that might help me.

Maybe you can help me further.

Best regards RSheetz

# Code to reproduce

[Mails_Alt.pdf](https://github.com/PHPMailer/PHPMailer/files/6560777/Mails_Alt.pdf)

# Debug output

Does not exist

**Comment by Synchro** [comment]
Please don't post code in PDFs, include it in the issue directly.

This is a very straightforward issue. Your loop calls `addAddress`, which **adds** a new recipient to the current instance. It does **replace** any that are already there, so each time round your loop, you are adding a new recipient, but also keeping all the previous ones. You need to call `$mail->clearAddresses();` at the end of your loop, just as [the mailing list example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps#L76) shows. Your sending will also go faster if you set `SMTPKeepAlive = true`, and the other measures mentioned in [the wiki article on sending to lists](https://github.com/PHPMailer/PHPMailer/wiki/Sending-to-lists).
