### ISSUE TITLE
PHPMailer doesn't send email to HOTMAIL account

### ISSUE THREAD

**Issue by termarco** [PHPMailer/PHPMailer#238]
Hi,
the plugin doesn't send email to the hotmail account and no errors are showed.

Why? What is the matter?

PHPMailer sends emails to other account without problems.

Thanks in advance.

**Comment by danilosantosdev** [comment]
I'm having the same problem. The outlook.com don't receive my e-mails.

**Comment by Muneem** [comment]
i am also having same problem. Does any one find solution?

**Comment by Muneem** [comment]
why this issue is closed as i dont see any solution to this problem?

**Comment by Arnaud69** [comment]
Closed since May 2014 !

**Comment by Synchro** [comment]
It's closed because it's not PHPMailer's problem.
