### ISSUE TITLE
ElasticEmail works with mail() but should I use SMTP?

### ISSUE THREAD

**Issue by JimNayzium** [PHPMailer/PHPMailer#2390]
My host company told me that ElasticEmail services (after I set up all the proper DKIM and DMARC and SPIF etc.. TXT files at the registrar delivers mail with extremely high NON-spam rate. Is there anything inherently better about using SMTP over just php $this->mail->send() without the isSMTP being true? 

I have had great success in test runs so far with very fewlanding even in the promotional tabs of gmail. I was just curious if I should force the SMTP to be the way to go or not?

**Comment by Synchro** [comment]
It makes no difference. You can send through exactly the same channel/server as `mail()` using SMTP. SMTP is however faster and safer.
