### ISSUE TITLE
PHP mailer doesn't send the email

### ISSUE THREAD

**Issue by Kolombooo** [PHPMailer/PHPMailer#2426]
Greetings,

i ran into an issue and i really don't know how to solve it. I tried to make simple PHP mailer code:
```php
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require '../mailer/phpmail/src/Exception.php';
require '../mailer/phpmail/src/PHPMailer.php';
require '../mailer/phpmail/src/SMTP.php';

$mail->SMTPDebug = SMTP::DEBUG_SERVER;                      //Enable verbose debug output
$mail->isSMTP();                                            //Send using SMTP
$mail->Host       = 'smtp.seznam.cz';                       //Set the SMTP server to send through
$mail->SMTPAuth   = true;                                   //Enable SMTP authentication
$mail->Username   = 'nabory@blazeplay.eu';                  //SMTP username
$mail->Password   = 'Owdkj898';                             //SMTP password
$mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;            //Enable implicit TLS encryption
$mail->Port       = 465;                                    //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS

$mail->setFrom('naboryservice@blazeplay.eu', 'Služba BlazePlay náborů');
$mail->addAddress('tvkolombooo@gmail.com');     //Add a recipient

$mail->isHTML(true);                                  //Set email format to HTML
$mail->Subject = 'Nový nábor';
$mail->Body    = '<p><b>Upozornění o novém vyplnění náboru</b></p><p>Byl vyplněn nový nábor. Prosím zkontrolujte databázi</p>';
$mail->AltBody = 'Byl vyplněn nový nábor. Prosím zkontrolujte databázi';

$mail->send();
echo 'Zpráva byla odeslána';
} catch (Exception $e) {
echo "Nastala chyb u odesílání zprávy: {$mail->ErrorInfo}";
}
```
But it does not work. It shows just a blank page and no email is recived. Could you please help me?

Thanks,

**Comment by Synchro** [comment]
You're missing a very basic thing: you are not creating a PHPMailer instance, so running `$mail->SMTPDebug =...` will cause a fatal error, and a blank page. Add:

    $mail = new PHPMailer();

before that line.

**Comment by Kolombooo** [comment]
Ok,
i did what you said but still it shows just a blank page. It doesn't evenr show the echo function at the very bottom.

`<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require '../mailer/phpmail/src/Exception.php';
require '../mailer/phpmail/src/PHPMailer.php';
require '../mailer/phpmail/src/SMTP.php';

$mail = new PHPMailer();                                    //Enable verbose debug output
$mail->SMTPDebug = SMTP::DEBUG_SERVER;
$mail->isSMTP();                                            //Send using SMTP
$mail->Host       = 'smtp.seznam.cz';                       //Set the SMTP server to send through
$mail->SMTPAuth   = true;                                   //Enable SMTP authentication
$mail->Username   = 'nabory@blazeplay.eu';                  //SMTP username
$mail->Password   = 'Owdkj898';                             //SMTP password
$mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;            //Enable implicit TLS encryption
$mail->Port       = 465;                                    //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS

$mail->setFrom('naboryservice@blazeplay.eu', 'Služba BlazePlay náborů');
$mail->addAddress('tvkolombooo@gmail.com');     //Add a recipient

$mail->isHTML(true);                                  //Set email format to HTML
$mail->Subject = 'Nový nábor';
$mail->Body    = '<p><b>Upozornění o novém vyplnění náboru</b></p><p>Byl vyplněn nový nábor. Prosím zkontrolujte databázi</p>';
$mail->AltBody = 'Byl vyplněn nový nábor. Prosím zkontrolujte databázi';

$mail->send();
echo 'Zpráva byla odeslána';
} catch (Exception $e) {
echo "Nastala chyb u odesílání zprávy: {$mail->ErrorInfo}";
}
echo "test";`

**Comment by Synchro** [comment]
You need to do some [basic debugging here](https://code-boxx.com/how-to-debug-php-code/). It's most likely that your `require` paths are wrong or inaccessible (so the script will stop before it gets as far as your `echo`), but checking your error log would be a start.
