### ISSUE TITLE
Suggestion: Optional elimination of timeout for continuous applications

### ISSUE THREAD

**Issue by David263** [PHPMailer/PHPMailer#2455]
I have an Ajax PHPMailer application that runs repeatedly on my local Windows server. A problem happened for the first time today after I awakened my computer from sleep in the morning.

Because my computer was sleeping, it determined that a long amount of time had passed during script execution. I do have a `set_time_limit(0);` call in my main program that eliminates most instances of this resumption problem, but this error condition was captured today by PHPMailer code.

The specific code is in SMTP.php (I see no version number) around line 436 where some code detects a `set_time_limit(0);` statement.

The code can't look in my application, so it just looks inside PHPMailer and sees the standard 30 second timeout, so it raises an error which stops my application.

So I'm working around this by adding a `set_time_limit(0);` statement to the top of SMTP.php. I presume that this will work but haven't tested it as yet.

My proposal is for you to add an option, by default disabled, that would execute a `set_time_limit(0);` statement in the context of PHPMailer, so continuous applications are possible in Windows without modification of your code. I'm not sure how your code currently works under Linux, but this new option shouldn't break anything there, of course.

**Comment by Synchro** [comment]
The SMTP standards have various timeouts that are a necessary part of the SMTP specification. In your example, changing the time limit in your script would indeed avoid that immediate problem, however, it's pointless because the server at the other end of the connection will be using the same standard timeout values, so you will gain nothing by doing this. The SMTP timeouts have little to do with your application's timeouts (so long as your app's timeouts are longer), nor do they have any effect on whether your script will keep running. I have scripts using SMTP that stay running for weeks. The specific instance you point at is the timeout that applies to opening a new connection to an SMTP server, so at this point you have no context to lose; If a connection drops, reopen a new connection.

**Comment by David263** [comment]
That sounds reasonable. Since I have an interface function between my continuous app and PHPMailer (mostly to apply defaults for each argument), I can put the logic into that function. Can you give me an example of the programming required, or at least how to detect the error and what error to look for as a condition for retrying the mailing? I'm not familiar with email error handling.

Note: in the case I mentioned here, I did not get an error returned by any PHPMailer function. Instead, there was a PHP timeout inside PHPMailer that crashed the application. Should I use try/catch to intercept the PHP timeout, or something else?

**Comment by Synchro** [comment]
Keep your messages in a DB or queue and mark them as sent as you do so successfully. If one fails for an SMTP-related reason, retry it later. If it fails for some other reason (e.g. no valid recipients), cancel the send and store an error somewhere. This kind of thing is outside PHPMailer's scope though, it only deals with the low-level sending part. Addressing and attachment errors can be trapped before trying to send (so pay attention to return values from methods like `addAddress`, `addAttachment`), leaving you with everything that is likely to need a retry.

**Comment by David263** [comment]
It is easy for you to say that this problem is outside of the scope of PHPMailer. But PHPMailer is not returning an error code for me to detect. Here is a summary of my code:

`$mail = new PHPMailer(true);
try {
...
		$mail->send();
		}
	catch (Exception $e) {
		Err("Email could not be sent. PHPMailer Error: {$mail->ErrorInfo}");
		return false;
`

The call to Err is never reached, so PHPMailer is not informing me of the failure due to PHP execution timeout. Is my code incorrect?

And, as I said, adding `set_time_limit(0);` at the top of the SMTP.php file seems to fix the problem. This morning my app resumed automatically. So all I am asking for is to add an option to execute this statement. To clarify, I want the app to be continuous., so PHPMailer must report this timeout at least. Tracking whether emails have been sent is not the problem.

**Comment by Synchro** [comment]
I think that's a PHP effect - a timeout like that isn't like a normal error, it's an instantaneous thing, pulling the plug, and I don't think the code ever gets a chance to continue.
