### ISSUE TITLE
Cannot send the confirmation email

### ISSUE THREAD

**Issue by david0003** [PHPMailer/PHPMailer#2456]
Here is a transcript of the error message:
SMTP Error: Could not authenticate.
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Connection: opening to ssl://box.bodyhealth.today:465, timeout=60, options=array ( 'ssl' => array ( 'verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true, ),)
Connection: opened
SMTP INBOUND: "220-node1.inspacehosting.com ESMTP Exim 4.94 #2 Tue, 20 Jul 2021 23:45:58 +0530"
SMTP INBOUND: "220-We do not authorize the use of this system to transport unsolicited,"
SMTP INBOUND: "220 and/or bulk e-mail."
SERVER -> CLIENT: 220-node1.inspacehosting.com ESMTP Exim 4.94 #2 Tue, 20 Jul 2021 23:45:58 +0530 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail.
CLIENT -> SERVER: EHLO insend.in
SMTP INBOUND: "250-node1.inspacehosting.com Hello insend.in [144.91.76.191]"
SMTP INBOUND: "250-SIZE 52428800"
SMTP INBOUND: "250-8BITMIME"
SMTP INBOUND: "250-PIPELINING"
SMTP INBOUND: "250-X_PIPE_CONNECT"
SMTP INBOUND: "250-AUTH PLAIN LOGIN"
SMTP INBOUND: "250 HELP"
SERVER -> CLIENT: 250-node1.inspacehosting.com Hello insend.in [144.91.76.191]250-SIZE 52428800250-8BITMIME250-PIPELINING250-X_PIPE_CONNECT250-AUTH PLAIN LOGIN250 HELP
Auth method requested: UNSPECIFIED
Auth methods available on the server: PLAIN,LOGIN
Requested auth method not available:
Auth method selected: LOGIN
CLIENT -> SERVER: AUTH LOGIN
SMTP INBOUND: "334 VXNlcm5hbWU6"
SERVER -> CLIENT: 334 VXNlcm5hbWU6
CLIENT -> SERVER: [credentials hidden]
SMTP INBOUND: "334 UGFzc3dvcmQ6"
SERVER -> CLIENT: 334 UGFzc3dvcmQ6
SMTP INBOUND: "535 Incorrect authentication data"
SERVER -> CLIENT: 535 Incorrect authentication data
SMTP ERROR: Password command failed: 535 Incorrect authentication data
CLIENT -> SERVER: QUIT
SMTP INBOUND: "221 node1.inspacehosting.com closing connection"
SERVER -> CLIENT: 221 node1.inspacehosting.com closing connection
Connection: closed

**Comment by Synchro** [comment]
Well, you're doing something silly. This tells me that you've disabled TLS verification:

    options=array ( 'ssl' => array ( 'verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true, )

You're asking it to connect to `box.bodyhealth.today`, but it's actually connecting to `node1.inspacehosting.com`, so the domain doesn't match and TLS verification will fail, as it should. TLS verification failing *was telling you there was a problem*, but you overrode it anyway. This server isn't the one you asked to connect to, so it probably has no idea who you are, and can't authenticate you. Meanwhile, you just gave away your credentials to an unknown server. It's most likely that it's your hosting provider redirecting traffic, but TLS is there to prevent man-in-the-middle attacks like this.

You need to figure out why you are being connected to this server, find out if you can prevent it by reading the docs from your hosting provider.

[This exact problem](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#certificate-verification-failure) is described in the troubleshooting guide. This is also why the source code and example warn that you should not disable verification.
