### ISSUE TITLE
PHPMailer not working in MAMP 6

### ISSUE THREAD

**Issue by EmilyChews** [PHPMailer/PHPMailer#2462]
Hi

I upgraded to MAMP 6 recently and PHPMailer has stopped working. I initially thought this was a PHP issues so rolled back to 7.1 which didn't make a difference. I also set it up to work with MailTrap in case it was an issue with the external mail server I was using.  Do you know of any issues on this front?

I also upgraded to the latest version of PHPMailer in case this was an issue (version 6.5).

I've sent a ticket to MAMP but have heard nothing and wondered if this was known issue with the new version or if there is work around?

The error report I get when using it on MAMP 6 with MailTrap as the SMTP is:

```
2021-08-03 01:13:51 SERVER -> CLIENT: 220 smtp.mailtrap.io ESMTP ready
2021-08-03 01:13:51 CLIENT -> SERVER: EHLO localhost
2021-08-03 01:13:52 SERVER -> CLIENT: 250-smtp.mailtrap.io250-SIZE 5242880250-PIPELINING250-ENHANCEDSTATUSCODES250-8BITMIME250-DSN250-AUTH PLAIN LOGIN CRAM-MD5250 STARTTLS
2021-08-03 01:13:52 CLIENT -> SERVER: STARTTLS
2021-08-03 01:13:52 SERVER -> CLIENT: 220 2.0.0 Start TLS
SMTP Error: Could not connect to SMTP host.
2021-08-03 01:13:52 CLIENT -> SERVER: QUIT
2021-08-03 01:13:52
2021-08-03 01:13:52
SMTP Error: Could not connect to SMTP host.
Message could not be sent. Mailer Error: SMTP Error: Could not connect to SMTP host.
```

Screenshot may be easier to read:

![Screenshot 2021-08-03 at 02 28 23](https://user-images.githubusercontent.com/22753439/127943522-dc67b389-b2fe-4bc6-ab86-61c22bdafb88.png)

**Comment by EmilyChews** [comment]
Screenshot may be easier to read.

![Screenshot 2021-08-03 at 02 28 23](https://user-images.githubusercontent.com/22753439/127943434-3b782d15-5559-4abe-bd7d-876bb78db63d.png)

**Comment by Synchro** [comment]
The symptom you have is starttls immediately followed by quit, which suggests your CA certificate bundle is outdated. This exact scenario is discussed in great detail in the troubleshooting guide.

**Comment by EmilyChews** [comment]
Thanks Synchro
