### ISSUE TITLE
[enhancement request] add support for custom php mail() $additional_params

### ISSUE THREAD

**Issue by atesin** [PHPMailer/PHPMailer#2464]
hi, thanks for this excelent library, seems very powerful and useful, i am new to it and just trying to understand it

first the question --> could you please add support for php mail() function "custom" additional parameters?

i am using wordpress, i started to dig, trying to enable or add this feature and discovered that is more related to you, so here i am

details:
i have my own linux web server with some websites on it (my homepage, personal projects, some friends websites, etc.) that need to send mails sometimes with different smtp accounts, headers and settings ... i already dealt with dns, auth and all that stuff

so i setup ssmtp with multiple config files.... to get work i wrote a custom "sendmail.sh" wrapper that gets a "mail profile name" as parameter, selects the right config file and calls ssmtp with it .... many other cool things could be done this way also (for windows, msmtp can be used)

then i set this script as sendmail bin in php.ini... all my php pages that sends mail (account activation, password recover/change,, important messages, etc.) pass the "mail profile name" as a mail() parameter.... it works me flawlessly from decades

now i need to start a new and better website and learn how to....  i choose wordpress because is likely the most popular, easy and best website creation tool, but lacks this feature (mybb supports setting mail() parameters in admin panel by default).... so i start to search configurations, documentation, browse the code, and then i realized this function is up to you.....

so in the meanwhile as i need to get this to work soon and i am not so skilled in proramming, i decided to just add my additional sendmail parameter harcoded in phpmailer sources [function mailSend($header, $body)] and request/suggest you (or beg) for adding his function :)

**Comment by Synchro** [comment]
There are already two ways you can do this with PHPMailer. You can use the `isSendmail()` transport, which allows you to provide your own command line, with full control, however I'd recommend that you use `isSMTP()` to localhost as it offers better customisation and it's also safer and faster than either sendmail or `mail()` approaches.

**Comment by atesin** [comment]
yes i know about direct smtp, i configured in my script like that... but i want to pass trought it to select multi profiles, log, queue, security, quotas and other things i installed... in the meanwhile i still can modify sources until is not so elegant

my request is unrelated with direct smtp (that everybody talks)... instead is about adding custom $additional_params for **PHP MAIL()** function... this is a state-of-the-art library, but currently lacks this feature

**Comment by Synchro** [comment]
You don't need to touch mail() if you use sendmail. You can build a command line that contains whatever you'd like, including the exact equivalent of the extra params feature of mail().
In most mail servers you control extra features (for example named queues or DKIM selectors) using custom headers, not command line params.

**Comment by atesin** [comment]
understood....  but with this do you mean "sendmail" mode is a reason for NOT to add php mail additional params support?... it can be added anyway, right? (more options for more people)... do you think is a good idea and will make phpmailer even better?

i already have php working this way... don't would be a lot easier to just specify a parameter instead skip it and configure another whole operation mode?... i think is still easier to modify a couple lines in sources

thanks for your kindly comments

**Comment by Synchro** [comment]
No. The PHP mail() function is slow, unsafe, and difficult to configure and debug, and as a result I don't want to do anything to encourage its use.

**Comment by atesin** [comment]
that was the response
thanks
