### ISSUE TITLE
PHPMailer works fine, but in a foreach loop, it only sends 1 mail and stops then, why? thanks for help

### ISSUE THREAD

**Issue by ArtOfWorkSwitzerland** [PHPMailer/PHPMailer#2467]
Hello folks. 

[file.zip](https://github.com/PHPMailer/PHPMailer/files/6977135/file.zip)
I am new here, so be merciful with me :-) I write and speak usually German. So if somebody can help me out in Deutsch, it would be great. If not, I will try it in English of course and I appreciate every help. Thank you to write as comprehensible as possible 😊

I use PHPMailer since today and I have the following problem, that I make a foreach loop and in this loop, PHPMailer should send actually 12 emails with different body content to myself as a reminder. It’s for a Cron Job, which every day is launched. 
The PHP script check the MySQL Database if the date is passed, and if yes, it sends me an email with the necessary content and info for me.

Till today I just worked with mail() from PHP and it works fine. But as soon as there are more then 10 e-mails in 5 seconds, my provider blocks it because there is no proper SMTP authentication. For that I change today to PHPMailer (I never worked with it before) and install it correctly with the classes (PHPMailer, SMTP, Exception) and the three required lines (PHPMailer/src/Exception.php, PHPMailer/src/PHPMailer.php, PHPMailer/src/SMTP.php).

Of course I made the config and everything works now great. I made a test and I received correctly an email, passing by this SMTP authentication and PHPMailer script to send the e-mail ($mail->send();)

But, and that’s my problem now:
Till now with the simply mail() function from PHP, I received at the end 12 e-mails, because there are 12 entries in the database as reminder for me, so I should receive 12 e-mails. But with this PHPMailer that I use now, he stops after 1 mail and doesn’t continue. 

I have no idea what I can make and it is like that it stops the script after the mail->send function. 
At the end I always delete the content (mail = “”) and here it should pass to the second mail, third mail, etc. to send me 12 mails at the end. But I only receive one.

It would be great if somebody could help me out. I try on the following attached file to show you everything as easy as possible. Maybe someone find the problem, why it stops.

Thank you.

Best Regards from Switzerland,
Fabrice

**Comment by Synchro** [comment]
Grüezi Fabrice! It's better to include your code directly in your question, or link to it in a github gist if you can. Downloading an opening a zip file is potentially dangerous.

There's one thing that will kill your script the second time around the loop: you have `require` statements inside the loop. If you load a class definition more than once, it will cause a fatal error the second time as the class is already defined. This is one good reason to learn to use composer, but you can fix it for now by moving your `require` lines to the top of your script, along with the `use` lines, outside the loop.

You also have no error checking, so you will have trouble if everything doesn't go perfectly.

I recommend you base your code on [the mailing list example provided](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps) as it avoids problems like this.

**Comment by ArtOfWorkSwitzerland** [comment]
I have seen that it works, if I put every code in one file. I had an include in my loop with the beginning code of "$mail = new PHPMailer();"

that brings an error and it doesn't work. If I put all together, it works now. But it would be nicer to have the construction of the email only written once in a file and include it then at the right place to use it.

**Comment by Synchro** [comment]
That is essentially what the mailing list example does. If you want to send the same message body to everyone, set it before the loop.
