### ISSUE TITLE
Name not decoded

### ISSUE THREAD

**Issue by campbell-m** [PHPMailer/PHPMailer#2470]
If I run the code below, the first name is decoded but the second isn't.   I don't know whether the problem is that the addresses haven't been encoded properly by addrFormat() or not decoded properly by parseAddresses().   Putting debug output in parseAddresses() it seems that the test `preg_match('/^=\?.*\?=$/', $name)` is failing for the second address.

For this test to work the imap extension should be disabled and the mbstring extension enabled.

~~~php
<?php

use PHPMailer\PHPMailer\PHPMailer;

require_once "./lib/PHPMailer/src/PHPMailer.php";

if (function_exists('imap_rfc822_parse_adrlist') || 
    !function_exists('mb_decode_mimeheader'))
{
  die("This test needs the imap extension disabled and the mbstring extension enabled.");
}
    
$email = "abc@xyz.com";
$names = array(
  "Abcdefgh ijklmñ",
  "Abcdefgh Ijklmñ 會議室預約系統"
);

$mailer = new PHPMailer();

foreach ($names as $name)
{
  $address = $mailer->addrFormat(array($email, $name));
  $parsed = PHPMailer::parseAddresses($address);
  var_dump($parsed);
}
~~~

The output I get is

~~~text
array(1) { [0]=> array(2) { ["name"]=> string(16) "Abcdefgh_ijklmñ" ["address"]=> string(11) "abc@xyz.com" } } array(1) { [0]=> array(2) { ["name"]=> string(89) "=?iso-8859-1?B?QWJjZGVmZ2ggSWprbG3DsSDmnIPorbDlrqTpoJDntITn?= =?iso-8859-1?B?s7vntbE=?=" ["address"]=> string(11) "abc@xyz.com" } }
~~~

See also https://github.com/PHPMailer/PHPMailer/issues/2471.

**Comment by Synchro** [comment]
I figured out where the problem is with that. The second name ends up long enough to be folded onto multiple lines, and the expression doesn't match multi-line addresses. Will fix this shortly.
