### ISSUE TITLE
Name incorrectly decoded

### ISSUE THREAD

**Issue by campbell-m** [PHPMailer/PHPMailer#2471]
If I run the code below, the first name is decoded incorrectly: it has an underscore instead of a space.  I don't know whether the problem is that it was encoded incorrectly or decoded incorectly.

For this test to work the imap extension should be disabled and the mbstring extension enabled.

~~~php
<?php

use PHPMailer\PHPMailer\PHPMailer;

require_once "./lib/PHPMailer/src/PHPMailer.php";

if (function_exists('imap_rfc822_parse_adrlist') || 
    !function_exists('mb_decode_mimeheader'))
{
  die("This test needs the imap extension disabled and the mbstring extension enabled.");
}
    
$email = "abc@xyz.com";
$names = array(
  "Abcdefgh ijklmñ",
  "Abcdefgh Ijklmñ 會議室預約系統"
);

$mailer = new PHPMailer();

foreach ($names as $name)
{
  $address = $mailer->addrFormat(array($email, $name));
  $parsed = PHPMailer::parseAddresses($address);
  var_dump($parsed);
}
~~~

The output I get is

~~~text
array(1) { [0]=> array(2) { ["name"]=> string(16) "Abcdefgh_ijklmñ" ["address"]=> string(11) "abc@xyz.com" } } array(1) { [0]=> array(2) { ["name"]=> string(89) "=?iso-8859-1?B?QWJjZGVmZ2ggSWprbG3DsSDmnIPorbDlrqTpoJDntITn?= =?iso-8859-1?B?s7vntbE=?=" ["address"]=> string(11) "abc@xyz.com" } }
~~~

See also https://github.com/PHPMailer/PHPMailer/issues/2470.

**Comment by Synchro** [comment]
The *formatting* is correct, because [`_` is treated as a space in RFC2047-encoded text](https://datatracker.ietf.org/doc/html/rfc2047#section-4.2), however, the _decoding_ is apparently unaware of this. I would call that a bug in `mb_decode_mimeheader`, but I will add a workaround for it.

**Comment by campbell-m** [comment]
Many thanks.
