### ISSUE TITLE
Email addresses containing Bengali characters rejected as invalid

### ISSUE THREAD

**Issue by neilt1700** [PHPMailer/PHPMailer#2474]
Attempting to send an email to an address using Bengali characters, such as বিড়াল@বিড়াল.example.org produces an email address validation error as follows:

Invalid address:  (to): বিড়াল@xn--15bvt3bkd.example.org

This error occurs in PHPMailer 6.5.1 however it did not occur in a previous version I had - 6.1.5

**Comment by Synchro** [comment]
PHPMailer does not yet support SMTPUTF8, so non-ASCII characters in the local part (before the @) will not work.
