### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by nastimch** [PHPMailer/PHPMailer#2477]
Hello bro i have sender php that use your scripts but he make it paid not free 
i want some trick for crack it i get one but not work with smtp 
can you help me !
[w3ll.zip](https://github.com/PHPMailer/PHPMailer/files/7032637/w3ll.zip)

**Comment by Synchro** [comment]
If it does something you value, pay for it. I'm not in the business of undermining other people's livelihoods.

**Comment by nastimch** [comment]
and i need feature that when put smtp send list txt not from db 
and i want use proxy random in sender ex  send 10 mail then change ip sender (ip of localhost )

**Comment by Synchro** [comment]
I'm very happy for you.

**Comment by Synchro** [comment]
PHPMailer is a low-level library. It helps people send one message at a time. If you want to write a system that does more complicated things, like send to lists, you need a different product. One example is PHPList, which uses PHPMailer to do exactly that. I'm not going to write one for you, and higher-level services are not PHPMailer's concern.

**Comment by nastimch** [comment]
oh okay bro but i buy some sender php priv8 i show in folder use your php repostry like phpmailerautoload and other 2 files 
i want update them my be get new features like encrypt name sender or change proxy of sender random .. 

![Untitled](https://user-images.githubusercontent.com/89400362/130466470-2f78ea66-078d-443c-a451-9221383f8ee7.png)

**Comment by Synchro** [comment]
You're using a very old version, and it's likely that the script that is using those files will need updating before it will work with the current version. If you want to try, you can get the latest files [right here on github](https://github.com/PHPMailer/PHPMailer). There is no such thing as encrypting the sender name, and switching proxies is not up to PHPMailer. FWIW, this all sounds extremely suspicious.

**Comment by nastimch** [comment]
i want just replace those 3 files  with new one class.smtp and class phpmailer and autload 
how do that

**Comment by Synchro** [comment]
Those files no longer exist in PHPMailer. There are new equivalents, but the script they are used from will not work with them without other changes. Even then, just changing these files won't get you the features you're asking for anyway. If you want help updating your script, you'll need to ask whoever wrote it, not me.

**Comment by nastimch** [comment]
oh okay bro i replace 2 still just phpmailerautoloader where get it 
how generate it with composer

**Comment by Synchro** [comment]
You can't. That file no longer exists in PHPMailer. It was replaced by composer, which you can use to generate an `autoload.php` file, however, all this will require changing the script that calls it - just dropping in some other file isn't going to work.

**Comment by nastimch** [comment]
whitch command generate it i do this commant but don't get autload script 

![Untitled](https://user-images.githubusercontent.com/89400362/130474591-21e848f9-d063-4c5c-b223-c4a2b5331737.png)

**Comment by Synchro** [comment]
You need to fix your PHP installation (install the openssl extension) before any of this will work. You will need openssl for PHPMailer anyway, not just for composer.

**Comment by nastimch** [comment]
oh okay can you give me command whitch install openssl extension for phpmailer !
