### ISSUE TITLE
Mail reaching spam rather than inbox

### ISSUE THREAD

**Issue by mado-bohsali** [PHPMailer/PHPMailer#2479]
Upon using the below settings, the email drops into the Spam/Junk folder rather than inbox. Please advise
$mail->SMTPDebug = SMTP::DEBUG_SERVER;                      //Enable verbose debug output
  $mail->isSMTP();                                            //Send using SMTP
  $mail->Host       = 'smtp.gmail.com';                     //Set the SMTP server to send through

  $mail->Username   = '2suits123@gmail.com';                     //SMTP username
  $mail->Password   = '******';                               //SMTP password
  $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;            //Enable implicit TLS encryption
  $mail->SMTPAuth = true;
  $mail->SMTPAutoTLS = false;
  $mail->Port = 465;
  $mail->setFrom('2suits123@gmail.com', '2 Suits');

**Comment by Synchro** [comment]
Please read [the docs on avoiding spam folders](https://github.com/PHPMailer/PHPMailer/wiki/Improving-delivery-rates,-avoiding-spam-filters). Short version: there is no way to guarantee staying out of spam folders; gmail is particularly prone to misclassification.
