### ISSUE TITLE
Godaddy SMTP Settings

### ISSUE THREAD

**Issue by mado-bohsali** [PHPMailer/PHPMailer#2480]
How can I properly configure go daddy SMTP settings in PHP?

**Comment by XL-2000** [comment]
Both PHPMailer and GoDadday have well documented this. Did you google this already or use the internal search? If that was not sufficient, what specific help do you still need?

**Comment by Synchro** [comment]
[See docs](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#godaddy).

**Comment by mado-bohsali** [comment]
I tried to do in Flutter:
outlook.office365.com
email
password
port 587 and it worked

**Comment by Synchro** [comment]
If it's in Flutter, it's not running on GoDaddy, and office365.com is not on GoDaddy either, so if you've solved a problem, it's nothing to do with GoDaddy!
