### ISSUE TITLE
SMTPKeepAlive is ignored when Mailer is destructed

### ISSUE THREAD

**Issue by elektronaut1024** [PHPMailer/PHPMailer#2483]
When sending multiple Mails in one request, SMTPKeepAlive is a nice Option, but the SMTP connection is closed when the Mailer-Instance is destructed (PHP calls destruct as soon as the last reference to the object is gone)

I managed to work around this issue by using setSMTPConnection to a new, unconnected Connection so that the old connection remains open even when the Mailer-Object is destructed.

```
$mailer->send();
//Make sure that SMTP Connection is not destroyed after usage (mailer->__destruct closes connection)
$newMailer = new Mailer();
$mailer->setSMTPInstance($newMailer->getSMTPInstance());

```

This is my very simple solution, which requires changing the library though.
```
 /**
     * Destructor.
     */
    public function __destruct()
    {
        //Close any open SMTP connection nicely
        if ( !$this->SMTPKeepAlive ) $this->smtpClose();
    }
```

Would you consider this solution?

**Comment by Synchro** [comment]
No, that won't work property because you've lost the handle to the connection, which is kept inside the instance, and you've also lost the tracking of the connection state. If you want to use keepalive, *don't destroy the instance*. There are numerous ways you can do that, such as by putting the PHPMailer instance into a static property so it doesn't get destroyed across calls that would otherwise destroy and recreate it. Bear in mind that your entire PHP run will be torn down after your script finishes anyway (unless it's a long-running process), and keepalive is typically not needed (or beneficial) for more than a few seconds at a time.

**Comment by elektronaut1024** [comment]
Well...i ran into the issue because my Hoster does not allow more than 50 Connections within a few seconds and started blocking me. So I was rather confused when even though I had SMTPKeepAlive enabled the connections were closed the next time.

I am keeping a reference of the SMTP Object of the first connection until I have sent all my mails, but I drop all references on my Mailer-Objects. I assumed that is the proper way since there is a getSMTPConnection() and setSMTPConnection()...

Both of my solutions solved my problem. I figured that keeping Mailer-Instances when all I need is the SMTP-Instance is kind of wasteful?

**Comment by elektronaut1024** [comment]
Also I was not sure wether i could reuse the Mailer-Instance since I am setting various Mail specific data (From, Subject, Body, etc) without risking leaking that data to the next Mail. I felt it was cleaner only to reuse the SMTP Connection, since that is what I am after...

**Comment by Synchro** [comment]
If you can keep the instance of the SMTP connection, then you can keep the PHPMailer instance in the same way. It's really not wasteful in any way that matters – we are talking a few hundred bytes of memory to keep it around, and it saves a lot of setup each time you re-use it, plus a bunch of network traffic. The SMTP instance does not maintain its state (the SMTP class is very dumb); that's handled in the PHPMailer class.

Injecting an open SMTP connection into a new instance of PHPMailer is absolutely undefined territory. There are no guarantees that anything will work as expected if you do that.

You can clear any properties you like after `send()` – look at methods like `clearAddresses()` – to make sure it's safe. I can't imagine that you are sending new messages without explicitly setting subject and body each time anyway. This isn't really any different to what a typical mailing list script does.

**Comment by elektronaut1024** [comment]
Alright, you know best, of course. Thanks for the feedback and your work!

**Comment by elektronaut1024** [comment]
So...this is what I need to reset?

```
$mailer->clearAddresses();
$mailer->clearBCCs();
$mailer->clearCCs();
$mailer->clearCustomHeaders();
$mailer->clearReplyTos();
$mailer->clearAttachments();
$mailer->Subject = '';
$mailer->Body = '';
```

There's no method to unset the Sender and From properly? This seems really dangerous way of sending multiple Mails...especially, if they vary in content. Some might have Attachments while others don't. If I do not reset the Attachments, the next Mail will contain the attachments of the previous one...just saying.

**Comment by Synchro** [comment]
You can set `Sender`, `From`, and `FromName` just like you can for `Body` and `Subject`. There is a shortcut for addresses: `clearAllRecipients()` clears all of To, CC and BCC addresses. It's not dangerous, it's exactly the behaviour that's wanted for most mailing list-type applications, where the majority of properties are shared across multiple messages. I do this with Smartmessages.net, sending up to about 600,000 messages per hour, and it works fine. Whether you need to clear all of those things depends on whether you're setting them in the first place.

It also strikes me that this is another good example of something to put in a subclass – add a `reset` method to clear all those things and call it between messages.

**Comment by elektronaut1024** [comment]
It's alright. It's your work, after all!;) I guess my use-case is just a little different (My Mails vary a lot, because I do nightly automatic processing and there are a lot of different kind of mails that I need to send one after the other)

...so...warranty is off if I use setSMTPConnection() instead?;)

**Comment by Synchro** [comment]
Yep, don't do that.

You really don't need everything to in a package to be a perfect fit for your app; this is exactly why we have the ability to subclass. With a subclass you can get a class that does precisely what you need it to do, that's entirely specific to you, while not requiring any changes in the upstream package, and not breaking your ability to update dependencies. Here you go:

```php
use PHPMailer\PHPMailer\PHPMailer;

class myMailer extends PHPMailer
{
    public function reset()
    {
        $this->clearAllRecipients();
        $this->clearCustomHeaders();
        $this->clearReplyTos();
        $this->clearAttachments();
        $this->Subject = '';
        $this->Body = '';
        $this->Sender = '';
        $this->From = '';
        $this->FromName = '';
    }
}
```

**Comment by elektronaut1024** [comment]
Alright. I will do it like that then;) Thanks again.
