### ISSUE TITLE
This is a multi-part message in MIME format.

### ISSUE THREAD

**Issue by balaig7** [PHPMailer/PHPMailer#2491]
In mail it shows a message "This is a multi-part message in MIME format" and raw html tags are show in mail. I try isHTML(true) and  send my html contents by msgHTML($message) but it always shows "This is a multi-part message in MIME format" message in mail

**Comment by Synchro** [comment]
Please show your code and the raw message (replace real email addresses please)

**Comment by balaig7** [comment]
<?php
$adminContent='<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="x-apple-disable-message-reformatting">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  
    <style type="text/css"> 
.confirm{
    display:block;
padding:12px 35px;
line-height:120%;
margin-top: 9px;
    margin-bottom: 9px;
    padding: 12px 35px;
    line-height: 120%;
    box-sizing: border-box;
    display: inline-block;
    font-family: "Open Sans",sans-serif;
    text-decoration: none;
    -webkit-text-size-adjust: none;
    text-align: center;
    color: #FFFFFF;
    background-color: #2196f3;
    border-radius: 2px;
    -webkit-border-radius: 2px;
    -moz-border-radius: 2px;
    width: auto;
    max-width: 100%;
    overflow-wrap: break-word;
    word-break: break-word;
    word-wrap: break-word;
}
.text-white{
    color:#ffffff;
}
@media only screen and (min-width: 620px) {
  .u-row {
    width: 600px !important;
  }
  .u-row .u-col {
    vertical-align: top;
  }

  .u-row .u-col-100 {
    width: 600px !important;
  }

}

@media (max-width: 620px) {
  .u-row-container {
    max-width: 100% !important;
    padding-left: 0px !important;
    padding-right: 0px !important;
  }
  .u-row .u-col {
    min-width: 320px !important;
    max-width: 100% !important;
    display: block !important;
  }
  .u-row {
    width: calc(100% - 40px) !important;
  }
  .u-col {
    width: 100% !important;
  }
  .u-col > div {
    margin: 0 auto;
  }
}

</style>
  
  

<link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet" type="text/css"><link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap" rel="stylesheet" type="text/css"><link href="https://fonts.googleapis.com/css?family=Raleway:400,700&display=swap" rel="stylesheet" type="text/css">

</head>

<body class="clean-body" style="margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #e7e7e7;color: #000000">
  <table style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #e7e7e7;width:100%" cellpadding="0" cellspacing="0">
  <tbody>
  <tr style="vertical-align: top">
    <td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top">
    

<div class="u-row-container" style="padding: 0px;background-color: transparent">
  <div class="u-row" style="Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #2196f3;">
    <div style="border-collapse: collapse;display: table;width: 100%;background-color: transparent;">
      
<div class="u-col u-col-100" style="max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;">
  <div style="width: 100% !important;">
  <div style="padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;">
  
<table id="u_content_image_1" style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:25px 10px 15px;font-family:"Open Sans",sans-serif;" align="left">
        
<table width="100%" cellpadding="0" cellspacing="0" border="0">
  <tr>
    <td style="padding: 20px;"  align="center">
      
      <img align="center" border="0" src="https://byachtservices.com/img/60xNxlogo.png.pagespeed.ic.DoZYXvnupu.webp" alt="Logo" title="Logo" style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border-radius:50%;border: none;height: auto;float: none;width: 15%;max-width: 179.8px;" width="179.8" class="v-src-width v-src-max-width"/>
      
    </td>
  </tr>
</table>

      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:"Open Sans",sans-serif;" align="left">
        
  <table height="0px" align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
    <tbody>
      <tr style="vertical-align: top">
        <td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
          <span>&#160;</span>
        </td>
      </tr>
    </tbody>
  </table>

      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:"Open Sans",sans-serif;" align="center">
        
  <h2 class="text-white" style="margin: 0px; color: #ffffff!important; line-height: 140%; text-align: center; word-wrap: break-word; font-weight: normal; font-family: "Raleway",sans-serif; font-size: 20px;">
    <strong>New User Created</strong>
  </h2>

      </td>
    </tr>
  </tbody>
</table>

  </div>
  </div>
</div>
    </div>
  </div>
</div>



<div class="u-row-container" style="padding: 0px;background-color: transparent">
  <div class="u-row" style="Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;">
    <div style="border-collapse: collapse;display: table;width: 100%;background-color: transparent;">
      
<div class="u-col u-col-100" style="max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;">
  <div style="width: 100% !important;">
  <div style="padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;">
  
<table style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:30px 10px 30px 20px;font-family:"Open Sans",sans-serif;" align="left">
        
  

      </td>
    </tr>
  </tbody>
</table>

  </div>
  </div>
</div>
    </div>
  </div>
</div>



<div class="u-row-container" style="padding: 0px;background-color: transparent">
  <div class="u-row" style="Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f7f6f4;">
    <div style="border-collapse: collapse;display: table;width: 100%;background-color: transparent;">
      
<div class="u-col u-col-100" style="max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;">
  <div style="width: 100% !important;">
  <div style="padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;">
  
<table style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:25px 10px 0px 20px;font-family:"Open Sans",sans-serif;" align="left">
        
  <div style="line-height: 140%; text-align: left; word-wrap: break-word;">
    <p style="font-size: 14px; line-height: 140%;padding-left:15px"><span style="font-family: Lato, sans-serif; font-size: 14px; line-height: 19.6px;"><strong><span style="font-size: 18px; line-height: 25.2px; color: #236fa1;">USER DETAILS</span></strong></span></p>
  </div>

      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:5px 10px 10px 20px;font-family:"Open Sans",sans-serif;" align="left">
        
  <table height="0px" align="left" border="0" cellpadding="0" cellspacing="0" width="22%" style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
    <tbody>
      <tr style="vertical-align: top">
        <td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
          <span>&#160;</span>
        </td>
      </tr>
    </tbody>
  </table>

      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:10px 10px 10px 20px;font-family:"Open Sans",sans-serif;" align="left">
        
  <div style="color: #333333; line-height: 140%; text-align: left; word-wrap: break-word;">
    <p style="font-size: 14px; line-height: 140%;padding-left: 15px"><strong>Name&nbsp; &nbsp; &nbsp; &nbsp;: </strong> <span style="color: #828080; font-size: 14px; line-height: 19.6px;">'.$first_name."".$last_name.'</span></p>
  </div>

      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:5px 10px 10px 20px;font-family:"Open Sans",sans-serif;" align="left">
        
  <div style="color: #333333; line-height: 140%; text-align: left; word-wrap: break-word;">
    <p style="font-size: 14px; line-height: 140%;padding-left: 15px"><strong>Email&nbsp; &nbsp; &nbsp; &nbsp; : </strong>&nbsp;<span style="color: #828080; font-size: 14px; line-height: 19.6px;">'.$email_address.'</span></p>
  </div>

      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:5px 10px 10px 20px;font-family:"Open Sans",sans-serif;" align="left">
        
  <div style="color: #333333; line-height: 140%; text-align: left; word-wrap: break-word;">
    <p style="font-size: 14px; line-height: 140%;padding-left: 15px"><strong>Website&nbsp; &nbsp;: </strong>&nbsp;<span style="color: #828080; font-size: 14px; line-height: 19.6px;"><a href="https://byachtservices.com">https://byachtservices.com</a></span></p>
  </div>

      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:5px 10px 10px 20px;font-family:"Open Sans",sans-serif;" align="left">
        
  <div style="color: #333333; line-height: 140%; text-align: left; word-wrap: break-word;">
    <p style="font-size: 14px; line-height: 140%;padding-left: 15px"><strong>Phone&nbsp; &nbsp; &nbsp; : </strong>&nbsp;<span style="color: #828080; font-size: 14px; line-height: 19.6px;">'.$phone_no.'</span></p>
  </div>

      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:5px 10px 10px 20px;font-family:"Open Sans",sans-serif;" align="left">
        
  <div style="color: #333333; line-height: 140%; text-align: left; word-wrap: break-word;">
    <p style="font-size: 14px; line-height: 140%;padding-left: 15px"><strong>Address&nbsp; &nbsp;: </strong>&nbsp;<span style="color: #828080; font-size: 14px; line-height: 19.6px;">'.$address.'</span></p>
  </div>

      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:5px 10px 10px 20px;font-family:"Open Sans",sans-serif;" align="left">
        
  <div style="color: #333333; line-height: 140%; text-align: left; word-wrap: break-word;">
    <p style="font-size: 14px; line-height: 140%;padding-left:15px"><strong>City&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : </strong>&nbsp;<span style="color: #828080; font-size: 14px; line-height: 19.6px;">'.$city.'</span></p>
  </div>

      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:5px 10px 10px 20px;font-family:"Open Sans",sans-serif;" align="left">
        
  <div style="color: #333333; line-height: 140%; text-align: left; word-wrap: break-word;">
    <p style="font-size: 14px; line-height: 140%;padding-left:15px"><strong>State&nbsp; &nbsp; &nbsp; &nbsp;: </strong>&nbsp;<span style="color: #828080; font-size: 14px; line-height: 19.6px;">'.$state.'</span></p>
  </div>

      </td>
    </tr>
  </tbody>
</table>

</div>
  </div>
</div>
    </div>
  </div>
</div>



<div class="u-row-container" style="padding: 0px;background-color: transparent">
  <div class="u-row" style="Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #ffffff;">
    <div style="border-collapse: collapse;display: table;width: 100%;background-color: transparent;">
      
<div class="u-col u-col-100" style="max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;">
  <div style="width: 100% !important;">
  <div style="padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;">
  
<table style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:10px 10px 30px;font-family:"Open Sans",sans-serif;" align="left">
        


      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:"Open Sans",sans-serif;" align="left">
        
  <table height="0px" align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 2px solid #939391;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
    <tbody>
      <tr style="vertical-align: top">
        <td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
          <span>&#160;</span>
        </td>
      </tr>
    </tbody>
  </table>

      </td>
    </tr>
  </tbody>
</table>

<table style="font-family:"Open Sans",sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
  <tbody>
    <tr>
      <td style="overflow-wrap:break-word;word-break:break-word;padding:0px 10px 20px;font-family:"Open Sans",sans-serif;" align="left">
        
  <div style="color: #828080; line-height: 140%; text-align: center; word-wrap: break-word;">
    <p style="font-size: 14px; line-height: 140%;">&copy;'.date('Y').' BONAVENTURE YACHT SERVICES. All Rights Reserved.</p>

  </div>

      </td>
    </tr>
  </tbody>
</table>

  </div>
  </div>
</div>
    </div>
  </div>
</div>


    </td>
  </tr>
  </tbody>
  </table>
</body>

</html>
';
$mail->isHTML(true);
 $mail->msgHTML($adminContent);
?>

**Comment by Synchro** [comment]
Where's the rest of it?

**Comment by balaig7** [comment]
<?php
require('../../phpmailer/class.phpmailer.php');
    require('../../phpmailer/class.smtp.php');
    $mail = new PHPMailer;

$adminContent='<html> 
                                <head> 
                                    <title>Test</title> 
                                </head> 
                                <body> 
                                    <table cellspacing="0" style="border: 2px dashed #FB4314; width: 100%;"> 
                                        <tr> 
                                            <th>Name:</th><td>'.$first_name.'  '.$last_name.'</td> 
                                        </tr> 
                                        <tr style="background-color: #e0e0e0;"> 
                                            <th>Email:</th><td>'.$email_address.'</td> 
                                        </tr> 
                                         
                                        <tr style="background-color: #e0e0e0;"> 
                                            <th>Phone:</th><td>'.$phone_no.'</td> 
                                        </tr>
                                        <tr> 
                                            <th>Address:</th><td>'.$address.'</td> 
                                        </tr>
                                        <tr style="background-color: #e0e0e0;"> 
                                            <th>City:</th><td>'.$city.'</td> 
                                        </tr>
                                        <tr style="background-color: #e0e0e0;"> 
                                            <th>State:</th><td>'.$state.'</td> 
                                        </tr>
                                    </table> 
                                </body> 
                                </html>';


$mail->setFrom("admin@test.com", "test.com");
                                   
                                    $mail->addAddress('test@gmail.com', 'test');

                                   $mail->Subject = "New User Registration";
                                   $mail->isHTML(true);

                                    $mail->msgHTML($adminContent);



                                   if($mail->Send()) {
echo "mail sent";
}

?>

**Comment by Synchro** [comment]
You're using an ancient version of PHPMailer, so before you do anything else, update.

**Comment by balaig7** [comment]
1 week before it works no issues are found. but currently this sent a message as raw html in mail

**Comment by Synchro** [comment]
You're already here! https://github.com/PHPMailer/PHPMailer

**Comment by balaig7** [comment]
where is the file require 'vendor/autoload.php';

**Comment by Synchro** [comment]
Please read [the docs on how to load PHPMailer](https://github.com/PHPMailer/PHPMailer#installation--loading).

**Comment by balaig7** [comment]
I update my php mailer to latest one. It's working. Thank you for your reply
