### ISSUE TITLE
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting{"teststat":"1","unable":1}

### ISSUE THREAD

**Issue by birdman8282** [PHPMailer/PHPMailer#2496]
### Discussed in https://github.com/PHPMailer/PHPMailer/discussions/2469

<div type='discussions-op-text'>

<sup>Originally posted by **Manisha221197** August 13, 2021</sup>
Hello all,
I'm getting this error on live server (namecheap)
The phpmailer working on localhost but when uploading into server and booking any service on our website we are getting the smtp error.
Please help us to solve this error.</div>

**Comment by birdman8282** [comment]
Hello,
I am receiving this error when setting up a new account in mailengine and wpmailersmtp during the testing of outgoing emails.  Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting{"teststat":"1","unable":1}

**Comment by birdman8282** [comment]
Hello,
I am receiving this error when setting up a new account in mailengine and wpmailersmtp during the testing of outgoing emails. Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting{"teststat":"1","unable":1}

**Comment by Synchro** [comment]
Please follow the link and read what it says.
