### ISSUE TITLE
Weird behavior

### ISSUE THREAD

**Issue by unpococloco** [PHPMailer/PHPMailer#2499]
### Discussed in https://github.com/PHPMailer/PHPMailer/discussions/2498

<div type='discussions-op-text'>

<sup>Originally posted by **unpococloco** September 15, 2021</sup>
when using the old version of PHPMailer for PHP 5.x, I've always had the **require()** and **use** namespace statements contained in a config file required at the top of every page.  This is what these statements look like in the config file:

```
require_once( CLASSES . "PHPMailer/src/PHPMailer.php" 	); // PHPMailer framework object
require_once( CLASSES . "PHPMailer/src/Exception.php" 	); // PHPMailer framework exceptions object
require_once( CLASSES . "PHPMailer/src/SMTP.php" 	); // PHPMailer framework SMTP object

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

```
Since updating to your newest version, I have isolated the following behavior:

When I put the **use** statements in my config file, I get a error stating 
 _"The class _file_ _ /home/lcudev/master/_globals/classes/PHPMailer.inc_ cannot be found."_ 
That error message is triggered by my own autoloader code whenever it fails to find an object class.

Yet when I move the **use** statements to the calling page and place them underneath the **require()** statement loading the aforementioned config page as shown below, everything works perfectly.
```
 
	require_once( "../_globals/_config.inc" );

	use PHPMailer\PHPMailer\PHPMailer;
	use PHPMailer\PHPMailer\SMTP;
	use PHPMailer\PHPMailer\Exception;


```
What's up with that and how can I fix it?

PHP 7.3.30
PHPMailer 6.5.0
Linux server</div>

**Comment by Synchro** [comment]
This simply won't work. `use` statements are *local* aliases that apply *only* to the file they appear in. If you put them in an external file that's imported, it will act like they aren't there. Read [the docs on namespace imports](https://www.php.net/manual/en/language.namespaces.importing.php).
