### ISSUE TITLE
Where can I find version 2.2.1?

### ISSUE THREAD

**Issue by HS79** [PHPMailer/PHPMailer#250]
I am looking for previous versions of phpmailer, namely version 2.2.1.

**Comment by wundo** [comment]
(Drupal's SMTP module maintainer here)

Please notice that Drupal 6 is also an old (but not so buggy) version of Drupal ;)

**Comment by joshbrw** [comment]
4 years on and having to deal with legacy code - this tag saved my bacon! Thank you! 🥓
