### ISSUE TITLE
500 internal server error  with yandex mail and composer validate error

### ISSUE THREAD

**Issue by Ahmeddh** [PHPMailer/PHPMailer#2503]
I'm getting a 500 internal server error when trying to send an email using PHPMailer, I tried running the composer validate on the server and I got this error :

name: The property name is required 
description: The property description is required No license specified, it is 

apache log shows the following error:
[Tue Sep 21 04:36:52.540006 2021] [php7:warn] [pid 23533] [client SOME IP:44312] PHP Warning:  Use of undefined constant \xe2\x80\x98direct\xe2\x80\x99 - assumed '\xe2\x80\x98di$

I'm using yandex as my mail server

Here is my PHP code 
```php
 <?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

require '../vendor/autoload.php';

/*
 *  CONFIGURE EVERYTHING HERE
 */
$mail = new PHPMailer();

// Settings
$mail->IsSMTP();
// $mail->CharSet = 'UTF-8';

$mail->Host       = "smtp.yandex.com";    // SMTP server example
$mail->SMTPDebug = SMTP::DEBUG_SERVER;
$mail->SMTPAuth   = true;                  // enable SMTP authentication
$mail->Port       = 465;                                    //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`
$mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;            //Enable implicit TLS encryption
$mail->Username   = "mail@yandex-domain.com";            // SMTP account username example
$mail->Password   = "my password";            // SMTP account password example



// an email address that will receive the email with the output of the form
//Recipients
$mail->$_POST['email'] ;
$mail->addAddress('mail@yandex-domain.com', 'First Last');     //Add a recipient
$mail->addAddress('mail2@yandex-domain.com', 'First Last');               //Name is optional
$mail->setFrom($_POST['email']);

//Content
$mail->isHTML(true);                                  //Set email format to HTML
$mail->Subject = $_POST['name'];
$mail->Body    = $_POST['message'] ;
// $mail->msgHTML(file_get_contents('contents.html'), __DIR__);
$mail->AltBody = $_POST['message'] ;

/*
 *  LET'S DO THE SENDING
 */

if (!$mail->send()) {
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message sent!';
    //Section 2: IMAP
    //Uncomment these to save your message in the 'Sent Mail' folder.
    #if (save_mail($mail)) {
    #    echo "Message saved!";
    #}
}
```

My HTML form code

```html
<form id="contact-form" class="form" method="post" action="contact.php" data-toggle="vanftizetor">
                                    <div class="messages"></div>
                                    <div class="input__wrap controls">
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <input id="form_name" type="text" name="name" placeholder="Type your name"
                                                        required="required" data-error="name is required.">
                                                    <div class="help-block with-errors"></div>
                                                </div>
                                            </div>

                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <input id="form_email" type="email" name="email" placeholder="Type your Email Address"
                                                        required="required" data-error="Valid email is required.">
                                                    <div class="help-block with-errors"></div>
                                                </div>
                                            </div>

                                            <div class="col-lg-12">
                                                <div class="form-group">
                                                    <textarea id="form_message" class="form-control" name="message"
                                                        placeholder="Tell us about you and the world" required="required"
                                                        data-error="Please,leave us a message."></textarea>
                                                    <div class="help-block with-errors"></div>
                                                </div>
                                            </div>

                                            <div class="col-12 text-center">
                                                <div data-dsn-grid="parallax">
                                                    <input type="submit">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
```

please advice!

**Comment by Synchro** [comment]
I'm not seeing any composer validation errors when using PHPMailer in projects. Please show the exact output that `composer validate` gives you.
Any time you have a 500 error, check your web server's error log, or *temporarily* enable error display in PHP.

**Comment by Synchro** [comment]
Oh, this makes no sense at all:

    $mail->$_POST['email'] ;

I've no idea what you're trying to do there, but not doing it would be a good idea!

**Comment by Ahmeddh** [comment]
yes I have commented that line and the error still exist, composer validate gives the following output:

./composer.json is valid for simple usage with composer but has
strict errors that make it unable to be published as a package:
See https://getcomposer.org/doc/04-schema.md for details on the schema
name : The property name is required
description : The property description is required

here is the apache error log:
[Tue Sep 21 06:43:03.126210 2021] [php7:warn] [pid 26269] [client IP:PORT] PHP Warning:  Use of undefined constant \xe2\x80\x98FS_METHOD\xe2\x80\x99 - assumed '\xe2\x80\x98FS$

and this is my composer.lock code:
`{
    "_readme": [
        "This file locks the dependencies of your project to a known state",
        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies",
        "This file is @generated automatically"
    ],
    "content-hash": "90bbf95869b4e88bf0dc5022e708a458",
    "packages": [
        {
            "name": "phpmailer/phpmailer",
            "version": "v6.5.1",
            "source": {
                "type": "git",
                "url": "https://github.com/PHPMailer/PHPMailer.git",
                "reference": "dd803df5ad7492e1b40637f7ebd258fee5ca7355"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/PHPMailer/PHPMailer/zipball/dd803df5ad7492e1b40637f7ebd258fee5ca7355",
                "reference": "dd803df5ad7492e1b40637f7ebd258fee5ca7355",
                "shasum": ""
            },
            "require": {
                "ext-ctype": "*",
                "ext-filter": "*",
                "ext-hash": "*",
                "php": ">=5.5.0"
            },
            "require-dev": {
                "dealerdirect/phpcodesniffer-composer-installer": "^0.7.0",
                "doctrine/annotations": "^1.2",
                "php-parallel-lint/php-console-highlighter": "^0.5.0",
                "php-parallel-lint/php-parallel-lint": "^1.3",
                "phpcompatibility/php-compatibility": "^9.3.5",
                "roave/security-advisories": "dev-latest",
                "squizlabs/php_codesniffer": "^3.6.0",
                "yoast/phpunit-polyfills": "^1.0.0"
            },
            "suggest": {
                "ext-mbstring": "Needed to send email in multibyte encoding charset or decode encoded addresses",
                "hayageek/oauth2-yahoo": "Needed for Yahoo XOAUTH2 authentication",
                "league/oauth2-google": "Needed for Google XOAUTH2 authentication",
                "psr/log": "For optional PSR-3 debug logging",
                "stevenmaguire/oauth2-microsoft": "Needed for Microsoft XOAUTH2 authentication",
                "symfony/polyfill-mbstring": "To support UTF-8 if the Mbstring PHP extension is not enabled (^1.2)"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "PHPMailer\\PHPMailer\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "LGPL-2.1-only"
            ],
            "authors": [
                {
                    "name": "Marcus Bointon",
                    "email": "phpmailer@synchromedia.co.uk"
                },
                {
                    "name": "Jim Jagielski",
                    "email": "jimjag@gmail.com"
                },
                {
                    "name": "Andy Prevost",
                    "email": "codeworxtech@users.sourceforge.net"
                },
                {
                    "name": "Brent R. Matzelle"
                }
            ],
            "description": "PHPMailer is a full-featured email creation and transfer class for PHP",
            "support": {
                "issues": "https://github.com/PHPMailer/PHPMailer/issues",
                "source": "https://github.com/PHPMailer/PHPMailer/tree/v6.5.1"
            },
            "funding": [
                {
                    "url": "https://github.com/Synchro",
                    "type": "github"
                }
            ],
            "time": "2021-08-18T09:14:16+00:00"
        }
    ],
    "packages-dev": [],
    "aliases": [],
    "minimum-stability": "stable",
    "stability-flags": [],
    "prefer-stable": false,
    "prefer-lowest": false,
    "platform": [],
    "platform-dev": [],
    "plugin-api-version": "2.1.0"
}
`

**Comment by Ahmeddh** [comment]
@Synchro please advice, 
sorry couldn’t format the json here, composer validate output below
<img width="851" alt="Screen Shot 2021-09-21 at 9 41 05 AM" src="https://user-images.githubusercontent.com/12083118/134131319-38e2e444-9757-4aaf-b617-bfa11171db52.png">

**Comment by Synchro** [comment]
This will be a problem with your `composer,json` file, nothing to do with PHPMailer.

`PHP Warning: Use of undefined constant \xe2\x80\x98FS_METHOD\xe2\x80\x99 - assumed '\xe2\x80\x98FS$`; that string (or anything like it) does not appear in PHPMailer. Your problem is somewhere else.

**Comment by Ahmeddh** [comment]
So I need to add name, & description inside the require {}?
`{
    "require": {
        "phpmailer/phpmailer": "^6.5"
    }
}
`

**Comment by Synchro** [comment]
Yes. If you do `composer init` when starting a project, composer will set all that up for you.

**Comment by Ahmeddh** [comment]
this fixes the composer validate error but still the form gives internal 500 error, apache error log has change to
`
[Tue Sep 21 08:08:52.177275 2021] [php7:warn] [pid 27463] [client IP:PORT] PHP Warning:  require(../vendor/autoload.php): failed to open stream: No such file or directory in /$

[Tue Sep 21 08:08:52.177338 2021] [php7:error] [pid 27463] [client IP:PORT] PHP Fatal error:  require(): Failed opening required '../vendor/autoload.php' (include_path='.:/usr$
`

sorry to bug here but I'm a PHP neewbie

**Comment by Ahmeddh** [comment]
Updated my autoload.php path with no luck
`require __DIR__ . '/vendor/autoload.php';
`

**Comment by Ahmeddh** [comment]
@Synchro here is the new error on the PHP file, I think its related to the autoload path, which make the PHPMailer config not fo
<img width="1052" alt="Screen Shot 2021-09-21 at 10 30 25 AM" src="https://user-images.githubusercontent.com/12083118/134138834-b020d6d8-3fa6-47c0-8ff8-a8c93f339bef.png">
und

**Comment by Synchro** [comment]
Have you actually installed PHPMailer with composer? Is there a `phpmailer` folder in your `vendor` folder?

**Comment by Ahmeddh** [comment]
yes

**Comment by Ahmeddh** [comment]
@Synchro any idea why the error says "PHPMailer\PHPMailer\PHPMailer" three times instead of two
 
Uncaught Error: Class 'PHPMailer\PHPMailer\PHPMailer' not found in /var/www/nftize.us/contact.php:10
Stack trace:

**Comment by Synchro** [comment]
That's the correct fully-qualified class name (FQCN). That error means one of two things: either you're not using the correct FQCN (which you are), or the autoloader can't find a class matching that name. If you're running composer locally and then uploading, ensure you are uploading the vendor folder too.

**Comment by Ahmeddh** [comment]
Yes, seems like the vendor folder was copied without the PHPMailer for some reason, I copied it and did composer init and followed the interactive conf, but still have some error when I do composer install related to minimum-stability version

  Problem 1
    - The requested package phpmailer/phpmailer No version set (parsed as 1.0.0) is satisfiable by phpmailer/phpmailer[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

I used stable, then tried dev, and rc without luck

**Comment by Synchro** [comment]
Nooo! You've copied PHPMailer's own composer.json file. You should have your own for your project. It should look something like this:

```json
{
    "name": "synchro/xx",
    "description": "My cool project",
    "authors": [
        {
            "name": "Me",
            "email": "me@example.com"
        }
    ],
    "require": {
        "phpmailer/phpmailer": "^6.5"
    }
}
```

This says "I want to use PHPMailer in my project", whereas what you have is more "I want to build a new version of PHPMailer".

**Comment by Ahmeddh** [comment]
Solved!, Sorry for wasting your time
appreciate the support and the patience, much respect!
