### ISSUE TITLE
Symbol is declared but not used

### ISSUE THREAD

**Issue by KamallWest** [PHPMailer/PHPMailer#2507]
Symbol 'Exception' is declared but not used
Symbol 'SMTP' is declared but not used

what do i have to do to fix this

this is my code:

```
<?php

require 'PHPMailer/src/PHPMailer.php';
require 'PHPMailer/src/SMTP.php';
require 'PHPMailer/src/Exception.php';

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

$mail = new PHPMailer(true);

$mail->isSMTP();

$mail->Host = 'smtp.@gmail.com';

$mail->SMTPAuth = 'true';

$mail->SMTPSecure = 'tls';

$mail->Port = '587';

$mail->Username = 'from@example.com';

$mail->Password = 'pwd';

$mail->Subject = 'Test email';

$mail->setFrom('no-reply@example.com');

$mail->isHTML(true);

$mail->Body = '';

$mail->addAddress('for@example.com');

if ( $mail->Send() ) {
      echo 'Email is sent';
} else {
    echo 'Error';
}

$mail->smtpClose();

**Comment by Synchro** [comment]
Delete these two lines (which are harmless, so I don't know why your tool is flagging them):

```
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;
```

**Comment by KamallWest** [comment]
> 
> 
> Delete these two lines (which are harmless, so I don't know why your tool is flagging them):
> 
> ```
> use PHPMailer\PHPMailer\SMTP;
> use PHPMailer\PHPMailer\Exception;
> ```

now i get this error message:
PHPMailer\PHPMailer\PHPMailer->send() #2 {main} thrown in C:\xampp\htdocs\myproject\src\frontend\PHPMailer\src\PHPMailer.php on line 1574

**Comment by Synchro** [comment]
You've not shown the rest of the error, so I can't tell what's wrong. Generally speaking you have no error checking in your script, so you're not going to know when things are not working. Look at the examples provided for how to do it right.

**Comment by KamallWest** [comment]
> 
> 
> You've not shown the rest of the error, so I can't tell what's wrong. Generally speaking you have no error checking in your script, so you're not going to know when things are not working. Look at the examples provided for how to do it right.
> 
> Also you don't need to call `smtpClose()`; that happens automatically when the PHPMailer instance goes out of scope.

sorry this is the whole error message:
Fatal error: Uncaught PHPMailer\PHPMailer\Exception: Message body empty in C:\xampp\htdocs\projectm\src\frontend\PHPMailer\src\PHPMailer.php:1574 Stack trace: #0 C:\xampp\htdocs\projectm\src\frontend\PHPMailer\src\PHPMailer.php(1482): PHPMailer\PHPMailer\PHPMailer->preSend() #1 C:\xampp\htdocs\projectm\src\frontend\forgotpwd.php(35): PHPMailer\PHPMailer\PHPMailer->send() #2 {main} thrown in C:\xampp\htdocs\projectm\src\frontend\PHPMailer\src\PHPMailer.php on line 1574

also i removed the ```smtpClose(); at the end

**Comment by Synchro** [comment]
Perhaps the bit of the error message that says:

> Message body empty

Might give you a clue?

There is a setting to allow sending an empty message, but it is simpler to provide a message body.

**Comment by KamallWest** [comment]
now i get this error:


Fatal error: Uncaught PHPMailer\PHPMailer\Exception: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting in C:\xampp\htdocs\projectm\src\frontend\PHPMailer\src\PHPMailer.php:1971 Stack trace: #0 C:\xampp\htdocs\projectm\src\frontend\PHPMailer\src\PHPMailer.php(1648): PHPMailer\PHPMailer\PHPMailer->smtpSend('Date: Wed, 22 S...', 'This is a body ...') #1 C:\xampp\htdocs\projectm\src\frontend\PHPMailer\src\PHPMailer.php(1486): PHPMailer\PHPMailer\PHPMailer->postSend() #2 C:\xampp\htdocs\projectm\src\frontend\forgotpwd.php(35): PHPMailer\PHPMailer\PHPMailer->send() #3 {main} thrown in C:\xampp\htdocs\projectm\src\frontend\PHPMailer\src\PHPMailer.php on line 1971

**Comment by Synchro** [comment]
Right, so now go read the troubleshooting guide. It's likely that your hosting provider is blocking outbound SMTP, and there's no way to fix that from your script.

**Comment by KamallWest** [comment]
I think it doesnt work because i have php version 8.0.9

**Comment by KamallWest** [comment]
on my localhost port 4343

**Comment by KamallWest** [comment]
you mean hotmail or gmail? Or else i don't know if i even have a mail server

**Comment by Synchro** [comment]
There is this obvious typo which won't be helping:

    $mail->Host = 'smtp.@gmail.com';

**Comment by KamallWest** [comment]
when i try to go to the site (in this case the file is called PHPMailer.php) it just keeps loading in an infinite loop

**Comment by Synchro** [comment]
If you have `$mail->Host = 'localhost';`, it expects you to be running a mail server on your computer. If you are not running one, it will not be able to connect, and will take a while to time out, probably 10 mins.

That port number makes little sense, though you are free to run a mail server on any port you like. It should also be an integer, not a string, usually `25`, `465` or `587`.

Going back to using gmail, it will not work with a hotmail username, nor will it allow you to use a hotmail `from` address...

**Comment by KamallWest** [comment]
The port number is used to connect to my localhost so have to go to localhost:4343 link to see my project folders. As of the mail server i dont know how to run or set one up.

**Comment by Synchro** [comment]
That's what I suspected. That port is not the port of your local web server, it's the port of the remote mail server you are connecting to. Set `Host = 'smtp.gmail.com`, `Port = 465`, and use your gmail credentials in `Username` and `Password`. It might be a good idea to start over using the gmail example in the examples folder.

**Comment by Synchro** [comment]
I don't know. It's your network!

**Comment by KamallWest** [comment]
I opened the port 465 on my router and it still doesnt work?

**Comment by Synchro** [comment]
Opening ports on your router would normally only apply to *inbound* traffic; it's normal for all outbound traffic to be allowed by default, especially in home devices. If you can't open a connection to `smtp.gmail.com` on port 465, it's likely to be your internet service provider blocking it. Ask them.
