### ISSUE TITLE
[hint] rspam detects PHPMailer by fixed boundary prefixes

### ISSUE THREAD

**Issue by tobwen** [PHPMailer/PHPMailer#2511]
# Problem description
_rspam_ actively detects _PHPMailer_ by the fixed boundary prefixes and gives a bad rating: `AUTOGEN_PHP_SPAMMY(1.00)[];`

# Analysis
While message IDs are unique IDs, the boundary prefixes are fixed values (_presets_):
https://github.com/PHPMailer/PHPMailer/blob/be98d62e365a657a175c9fcf49f3914c6d8ec0ad/src/PHPMailer.php#L2757-L2759

That's where _rspam_ detects _PHPMailer_:
https://github.com/rspamd/rspamd/blob/00175f9b9ba2376de8969d72a734004838afc53c/rules/regexp/compromised_hosts.lua#L5-L15

# Workaround
Manually change `b1, b2, b3` to anything else.

# Future work
I think it makes sense to make the boundary prefix changeable as a variable. This way the user can assign it randomly. If the variable is not set by the user, it can fall back to default to ensure backward compatibility.

I could try to create a PR for this.

**Comment by Synchro** [comment]
Hm. I'm not too keen on doing this; it's spammy arms-race behaviour! We already have *so many* properties. If anything it might be cleaner to break out the boundary setting into a protected method that you could then override to substitute your own.

**Comment by tobwen** [comment]
But then you'd need to break out all three.

Why not three random prefixes? Like
``` php
$this->boundary[1] = substr($this->generateId(), 0, 3) . $this->uniqueid;
$this->boundary[2] = substr($this->generateId(), 0, 3) . $this->uniqueid;
$this->boundary[3] = substr($this->generateId(), 0, 3) . $this->uniqueid;
```

Maybe this is cheaper, since it doesn't need to be cryptographic safe:
``` php
substr(md5(uniqid(mt_rand(), true)), 0, 3)
```

**Comment by Synchro** [comment]
That's really messy and runs considerably more code – `generateId` is used for the message ID as well as the boundary, for consistency, so it shouldn't be called more than once. Every modern IDE will flag uses of md5 (and mt_rand), regardless of whether it is really problematic, which just makes for support issues. I was thinking more like:

```php
protected function setBoundaries()
{
        $this->boundary[1] = 'b1_' . $this->uniqueid;
        $this->boundary[2] = 'b2_' . $this->uniqueid;
        $this->boundary[3] = 'b3_' . $this->uniqueid;
}
```
Then you can just override it in a subclass and set them to whatever you like.

**Comment by Cr0aten** [comment]
I would love to see this broken out into a separate method so it can be overridden in a subclass.  I currently just change it manually in the code directly, but it would make it much easier to override it in a subclass and not have to worry about updating for ever PHPMailer update.  Not a big deal either way, but would certainly make it more convenient.
