### ISSUE TITLE
OAuth Interface

### ISSUE THREAD

**Issue by pdscopes** [PHPMailer/PHPMailer#2523]
To start off, being able to use OAuth with PHPMailer is really great and implemented so that it is simple to use.

# Problem description
PHPMailer is currently unable to integrate easily with other OAuth libraries without extending the `\PHPMailer\PHPMailer\OAuth` class. This is slightly problematic having the protected class properties.

# Solution
Add an interface that `\PHPMailer\PHPMailer\OAuth` implements which specifies it's only public function `getOauth64`. Then the `\PHPMailer\PHPMailer\PHPMailer::setOAuth` function would accept instances of the interface. e.g.:

```php

interface OAuthTokenProvider
{
    /**
     * Generate a base64-encoded OAuth token ensuring that the access token has not expired.
     * The string to be base 64 encoded should be in the form:
     * "user=<user_email_address>\001auth=Bearer <access_token>\001\001"
     *
     * @return string
     */
    public function getOauth64():
}
```

```php
/**
 * OAuth - OAuth2 authentication wrapper class.
 * Uses the oauth2-client package from the League of Extraordinary Packages.
 *
 * @see     http://oauth2-client.thephpleague.com
 *
 * @author  Marcus Bointon (Synchro/coolbru) <phpmailer@synchromedia.co.uk>
 */
class OAuth implements OAuthTokenProvider
{
     // implementation goes here
}
```

```php
/**
 * PHPMailer - PHP email creation and transport class.
 *
 * @author Marcus Bointon (Synchro/coolbru) <phpmailer@synchromedia.co.uk>
 * @author Jim Jagielski (jimjag) <jimjag@gmail.com>
 * @author Andy Prevost (codeworxtech) <codeworxtech@users.sourceforge.net>
 * @author Brent R. Matzelle (original founder)
 */
class PHPMailer
{
    // The rest of the code goes here

    /**
     * An implementation of the PHPMailer OAuthTokenProvider interface.
     *
     * @var OAuthTokenProvider
     */
    protected $oauth;

    // The rest of the code goes here

    /**
     * Get the OAuthTokenProvider instance.
     *
     * @return OAuthTokenProvider
     */
    public function getOAuth()
    {
        return $this->oauth;
    }

    /**
     * Set an OAuthTokenProvider instance.
     */
    public function setOAuth(OAuthTokenProvider $oauth)
    {
        $this->oauth = $oauth;
    }
}
```

**Comment by pdscopes** [comment]
Is there anything I can do to help this and the associated PR (#2524) get approved?

**Comment by Synchro** [comment]
Hi, sorry for not getting back to you on this sooner.

The wiki articles are not part of the main repo, and I've re-enabled editing on them so you can add those details in yourself. My main observation there is when you say "download its details in json", perhaps give more detail about where you have to do that, possibly with some screen shots?

I will merge this (if I don't spot anything else) and release it as a 6.8 "feature" release, given that it introduces new functionality but has no BC breaks.

**Comment by pdscopes** [comment]
Don't worry about it, thank you so much for creating/maintaining this library. I will update the Wiki ASAP.

**Comment by pdscopes** [comment]
@Synchro, you'll now find that I've updated https://github.com/PHPMailer/PHPMailer/wiki/Gmail-XOAUTH2-Using-Google-API-Client to include my new guide (with added screenshots).

**Comment by Synchro** [comment]
That's great, thank you very much. It's really quite different to the old system, and a lot easier, so it might be better to move it into a separate document, or delete the old one because it's set up for an obsolete version.

**Comment by ablov** [comment]
I'm sorry if I'm just stupid, but... this code is not working. 

First. The _$tokenPath_ variable is not defined.

        // Set the token path
        $this->tokenPath = _$tokenPath_;

Maybe it should be _$tokenFile_ from public function __construct($oauthUserEmail, $credentialsFile, _$tokenFile_)

Second. _STDIN_ is not defined anywhere. Am I right that the part of code
            printf("Open the following link in your browser:\n%s\n", $authUrl);
            print 'Enter verification code: ';
            $authCode = trim(fgets(STDIN));

Is it used just as example of some console script? Could you please explain how to use it?

**Comment by Synchro** [comment]
`STDIN` is a predefined name for "standard input" and is provided by [PHP's streams interface](https://www.php.net/manual/en/wrappers.php.php).

**Comment by pdscopes** [comment]
@ablov, you are correct the constructor should be `$tokenPath` and not `$tokenFile`. I've updated that both on here and the wiki.
