### ISSUE TITLE
Using PHPMailer on php5.6

### ISSUE THREAD

**Issue by jjshaw** [PHPMailer/PHPMailer#2529]
To get this to work, I had to change (lines 1700 & 1887)

from
  `      if (empty($this->Sender) && !empty(ini_get('sendmail_from'))) {`

to

```
 $sendmail_from_value=ini_get('sendmail_from');
        if (empty($this->Sender) && !empty($sendmail_from_value)) {
```

to avoid error message:
```
PHP Fatal error:  Can't use function return value in write context in /var/www/vhosts/.../includes/PHPMailer/PHPMailer.php on line 1700
```

**Comment by jjshaw** [comment]
> You should be thinking about upgrading your PHP though... 5.6 is long out of support and represents an increasing risk.

Thanks - yes - it is in progress at the moment. Big job!

**Comment by Sebijk** [comment]
Seems, that is a generel PHP 5.x issue, i made already a merge request with the same fix on september: https://github.com/PHPMailer/PHPMailer/pull/2513
