### ISSUE TITLE
PHPMailer() Error

### ISSUE THREAD

**Issue by TrucksLOG** [PHPMailer/PHPMailer#2553]
i have an error in my Mailer. 
i include the 
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require 'PHPMailer/src/Exception.php';
require 'PHPMailer/src/PHPMailer.php';
require 'PHPMailer/src/SMTP.php';

and my website is down.
the problem is the require 'PHPMailer/src/PHPMailer.php';
when i remove them, the site works
and in my functions i became the error
[{
	"resource": "/c:/Users/edvbl/Vue Versuch/Root_SEITE/inc/functions.php",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": "1009",
	"severity": 8,
	"message": "Undefined type 'PHPMailer'.",
	"source": "intelephense",
	"startLineNumber": 183,
	"startColumn": 15,
	"endLineNumber": 183,
	"endColumn": 24
}]

**Comment by Synchro** [comment]
That means you either do not have PHPMailer installed, or you're trying to load it from the wrong place. I suggest you learn to use composer.

**Comment by Synchro** [comment]
Actually that's not quite the right diagnosis. The "Undefined type 'PHPMailer'." suggests a possible namespacing / typing problem in your own code, so please post that.

**Comment by TrucksLOG** [comment]
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

require "PHPMailer/src/PHPMailer.php";
require "PHPMailer/src/SMTP.php";

$mail = new PHPMailer(true);

**Comment by TrucksLOG** [comment]
![image](https://user-images.githubusercontent.com/79003919/140602962-03984944-7db9-4ebd-bf73-2bb657945fed.png)
FTP

**Comment by TrucksLOG** [comment]
![image](https://user-images.githubusercontent.com/79003919/140602967-304be02b-c6dc-4d91-9b9a-0170630c36df.png)

**Comment by TrucksLOG** [comment]
![image](https://user-images.githubusercontent.com/79003919/140603027-e3e1fdb8-2253-4638-8bb7-bb337ccbe62d.png)

**Comment by Synchro** [comment]
There's nothing wrong with that code. I would be looking at the context (the snippet you posted is clearly not more than 183 lines long) and issues with the tool you're using.

**Comment by TrucksLOG** [comment]
At the moment i cannot send any mails with the normal php mail function. can it be because of that?

**Comment by TrucksLOG** [comment]
[06-Nov-2021 09:21:52 Europe/Berlin] PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in C:\inetpub\vhosts\truckslog.de\httpdocs\PHPMailer\src\PHPMailer.php on line 32

**Comment by TrucksLOG** [comment]
![image](https://user-images.githubusercontent.com/79003919/140603210-be3d694a-dc51-41de-b21a-9307013e3fe3.png)

**Comment by Synchro** [comment]
You posted a screen shot showing `static class PHPMailer`; I don't know where you got that, but it's not original PHPMailer. You should never need to touch library code. Again, you should be using composer.

If `mail()` doesn't work, then PHPMailer (by default) won't work either, since it uses `mail()` internally by default. If you're using SMTP, then you don't need `mail()` to work.
