### ISSUE TITLE
OAuth2 Gmail consent screen scopes

### ISSUE THREAD

**Issue by atlet** [PHPMailer/PHPMailer#2555]
Hi,

I'm getting "Google hasn’t verified this app", but the application is verified. I think the problem is with wrong scopes. Which one I need to setup?

For now I have those:
![image](https://user-images.githubusercontent.com/1223162/140883697-4191cf56-3505-4734-ad65-acf18fbe5b23.png)

Tnx.

**Comment by Synchro** [comment]
I have no idea, you'll need to refer to google's docs. I'd also suspect that verification doesn't have anything to do with scopes.
