### ISSUE TITLE
FastCgiModule | Error Code: 0xc0000409

### ISSUE THREAD

**Issue by Cerberus-Zer0** [PHPMailer/PHPMailer#2559]
I seem to be receiving a 500 error in relation to the FastCGIModule on IIS.
Using latest version of PHPMailer from GitHub.

What is strange is that **the email sends successfully** but I receive the error after.

**Environment:**
Server 2022 (21H2)
IIS 10.0
PHP 8.0

**Error Information:**
HTTP Error 500.0 - Internal Server Error
C:\PHP\php80\php-cgi.exe - The FastCGI process exited unexpectedly

**Detailed Error Information:**
Module: FastCgiModule
Notification: ExecuteRequestHandler
Handler: PHP_via_FastCGI
Error code: 0xc0000409

**Testing:**
Looks like the error is happening on $mail->send();
If I break before it's successful, after it errors.
Repeating this process deeper it looks to error in this code:

[PHPMailer.php]
```php
protected function edebug($str)
    {
        if ($this->SMTPDebug <= 0) {
            return;
        }
        //Is this a PSR-3 logger?
        if ($this->Debugoutput instanceof \Psr\Log\LoggerInterface) {  // <<< This line
```

**Mailer Code:**
```php
<?php
	use PHPMailer\PHPMailer\PHPMailer;
	use PHPMailer\PHPMailer\Exception;
	use PHPMailer\PHPMailer\SMTP;

	function SendEmail($emailTo, $emailCC, $emailFrom, $emailReply, $emailSubject, $emailBody, $emailAttachment) {

		//Load Composer's autoloader
		require BASEPATH . "/vendor/autoload.php";

		$mail = new PHPMailer(true);

		try {
			//Server settings
			$mail->SMTPDebug = SMTP::DEBUG_SERVER; 
			$mail->isSMTP(); 
			$mail->Host              = 'smtp.gmail.com'; 
			$mail->SMTPAuth     = true;
			$mail->Username     = 'my email'; 
			$mail->Password      = 'my password'; 
			$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;  
			$mail->Port               = 587;                  
		
			//Recipients
			$mail->setFrom($emailFrom, "PA");
			$mail->addAddress($emailTo);
			$mail->addReplyTo($emailReply);
			if (isset($emailCC) && $emailCC != "") {
				if (strpos($emailCC, ',') !== false) {
					$emailCCMulti = explode(",", $emailCC);
					for ($i=0; isset($emailCCMulti[$i]); $i++) {
						$mail->addCC($emailCCMulti[$i]);
					}
				} else {
					$mail->addCC($emailCC);
				}
			}	
	
			//Content
			$mail->isHTML(true); 
			$mail->Subject = $emailSubject;
			$mail->Body     = $emailBody;		
			$mail->send();
			echo 'Message has been sent';
			exit;

		} catch (Exception $e) {
			echo "Message could not be sent. Mailer Error({$e}): {$mail->ErrorInfo}";
			$file = '../error-log.txt';
			$addError = date('Y-m-d h:i:s') . " mailer.php " . " - " . $mail->ErrorInfo;
			file_put_contents($file, $addError, FILE_APPEND | LOCK_EX);
		}
	}
?>
```

**Comment by Synchro** [comment]
Any time you get an error 500, look in your web server's error log for details. Without that info I can't really guess what's happening here. I'm assuming you're using latest PHPMailer and a supported PHP version (preferably 8.0).

If there is an error when sending, it's likely that this line will cause problems:

    echo "Message could not be sent. Mailer Error({$e}): {$mail->ErrorInfo}";

because `$e` is not readily expressed as a string; use `$e->getMessage()` instead.

Also, because you have a `require` *inside* this function, calling it twice will generate a fatal error.

**Comment by Cerberus-Zer0** [comment]
Thanks for your answer.
Yes I am using the latest PHPMailer and PHP 8.0.11

I have checked your 2 suggestions and it does not seem to be causing the error. Referenced `$e->getMessage()` and moved the `require` out of the function, also updated to `require_once`

If you are referring to the log files located at:
_C:\inetpub\logs\LogFiles\W3SVC1_

I am receiving the following log entry when the page is trying to load:
_2021-11-17 08:46:41 192.168.0.7 POST /forgot-password - 80 - 192.168.0.62 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:94.0)+Gecko/20100101+Firefox/94.0 http://blue/forgot-password 500 0 3221226505 6405_

**Comment by Synchro** [comment]
That log entry is from your access log, not your error log. The key thing in there is that it's causing a `500` error, and there will be more details in the error log.

**Comment by Cerberus-Zer0** [comment]
I seem to be receiving this error in Windows Event Viewer.

**Error:**
Faulting application name: php-cgi.exe, version: 8.0.11.0, time stamp: 0x614a2401
Faulting module name: ucrtbase.dll, version: 10.0.20348.1, time stamp: 0xdacb234c
Exception code: 0xc0000409
Fault offset: 0x000000000007ca9e
Faulting process id: 0x194
Faulting application start time: 0x01d7df7a28470cb6
Faulting application path: C:\PHP\php80\php-cgi.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: bc325410-fd77-4fa2-af02-017d24788d95
Faulting package full name: 
Faulting package-relative application ID: 

**Information:**
Fault bucket 1574851472715128085, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: php-cgi.exe
P2: 8.0.11.0
P3: 614a2401
P4: ucrtbase.dll
P5: 10.0.20348.1
P6: dacb234c
P7: 000000000007ca9e
P8: c0000409
P9: 0000000000000007
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4675886e-cbae-49f3-a944-8888bc5dff38.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5925eaea-b6fb-40f1-864c-d74581ecf6b3.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8e74783f-8d11-4815-8741-f4eba2770544.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c4b830dd-a456-4f4a-b071-9d6fe6286038.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.1b6f51b1-79eb-4d42-abd7-a65e311f5b59.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_php-cgi.exe_f49015f140e719354ec2f254f329354cad5c94e5_469547d1_5795696a-6ef4-4849-a38c-b25b85832f0f

Analysis symbol: 
Rechecking for solution: 0
Report Id: bc325410-fd77-4fa2-af02-017d24788d95
Report Status: 268435456
Hashed bucket: 7b5d7823e1643bbf75daff120d2f9d15
Cab Guid: 0

**Comment by Synchro** [comment]
OK, that's an actual PHP crash. Have you looked it up in the PHP bug tracker, like [this](https://bugs.php.net/search.php?cmd=display&search_for=ucrtbase.dll&x=0&y=0) ?

**Comment by Cerberus-Zer0** [comment]
Well I've looked through the bug tracker but there is nothing directly related that I can see.

I managed to dive in and found the offending code to be the startTLS() fuction in SMTP.php, specifically this line 
```
$crypto_ok = stream_socket_enable_crypto(
            $this->smtp_conn,
            true,
            $crypto_method
);
```

I think it's strange that the email sends successfully and then it tries to open the TLS connection and crashes?

**Comment by Synchro** [comment]
That sounds unlikely because starttls has to happen before sending. Can you set `$mail->SMTPDebug = 3` and add the output to this issue?

**Comment by Cerberus-Zer0** [comment]
2021-11-30 01:22:55 Connection: opening to smtp.gmail.com:587, timeout=300, options=array()
2021-11-30 01:22:55 Connection: opened
2021-11-30 01:22:56 SERVER -> CLIENT: 220 smtp.gmail.com ESMTP s9sm5614430pfk.198 - gsmtp
2021-11-30 01:22:56 CLIENT -> SERVER: EHLO blue
2021-11-30 01:22:56 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [103.46.212.131]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
2021-11-30 01:22:56 CLIENT -> SERVER: STARTTLS
2021-11-30 01:22:56 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
***STOP***
2021-11-30 01:22:56 CLIENT -> SERVER: QUIT
2021-11-30 01:22:57 SERVER -> CLIENT:
2021-11-30 01:22:57 SMTP ERROR: QUIT command failed:
2021-11-30 01:22:57 Connection: closed

I think this is what you are after??
The ***STOP*** is me echoing and exit() is called else I just get a 500 error.
I am calling exit() right before this line in SMTP.php
$crypto_ok = stream_socket_enable_crypto(...

**Comment by Synchro** [comment]
Yes, that's what i wanted to see. It is happening before sending – it's the STARTTLS command that's triggering the crash. I expect you would see similar results if you set `SMTPSecure = 'ssl'` and `Port = 465`, though you'll get less feedback from that. As you've seen, PHPMailer is just calling the `stream_socket_enable_crypto` function which is what it's meant to do. I would look at reinstalling PHP, openssl, and the PHP openssl extension.

**Comment by Cerberus-Zer0** [comment]
Is there a specific way I am meant to reinstall those components?
I have actually tested with PHP 7.4, 8.0 and 8.1 and all of them fail the same way so I'm not sure reinstalling will do anything.

**Comment by Synchro** [comment]
I really don't know when it comes to Windows. It would not surprise me if all those versions were sharing the same openssl library. I suspect that any PHP code that calls that function will fail in the same way in your installation; this isn't a PHPMailer problem, just where the symptom is showing up.

**Comment by Cerberus-Zer0** [comment]
That's ok it looks like it may just be easier to throw it onto a Linux server.
Thanks for your help.
