### ISSUE TITLE
Web form fails...

### ISSUE THREAD

**Issue by llsnndlldkm** [PHPMailer/PHPMailer#2569]
I'm trying to mail a single files through a web form. I use the code from /examples/send_multiple_file_upload.phps  to no avail. Instead the following error is returned:

Fatal error: Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in /var/www/home/includes/PHPMailer/src/PHPMailer.php:4494 Stack trace: #0 /var/www/home/includes/PHPMailer/src/PHPMailer.php(4494): preg_match('#^(.*?)[\\\\/]*((...', Array, Array) #1 /var/www/home/mailer.php(127): PHPMailer\PHPMailer\PHPMailer::mb_pathinfo(Array, 4) #2 {main} thrown in /var/www/home/includes/PHPMailer/src/PHPMailer.php on line 4494

This is dragging on for a while no, today I've installed 6.1.3 of oh-mailer.

**Comment by llsnndlldkm** [comment]
The error above is in PHP 8.0.12... When scaling up to 8.1, I get:

Fatal error: Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given in /var/www/mpiece/htdocs/mpiece-workspace/includes/PHPMailer/src/PHPMailer.php:4494 Stack trace: #0 /var/www/mpiece/htdocs/mpiece-workspace/includes/PHPMailer/src/PHPMailer.php(4494): preg_match('#^(.*?)[\\\\/]*((...', Array, Array) #1 /var/www/mpiece/htdocs/mailer.php(127): PHPMailer\PHPMailer\PHPMailer::mb_pathinfo(Array, 4) #2 {main} thrown in /var/www/mpiece/htdocs/mpiece-workspace/includes/PHPMailer/src/PHPMailer.php on line 4494

**Comment by llsnndlldkm** [comment]
When scaling down to 7.4.25, I get:

Warning: preg_match() expects parameter 2 to be string, array given in /var/www/mpiece/htdocs/mpiece-workspace/includes/PHPMailer/src/PHPMailer.php on line 4494

**Comment by llsnndlldkm** [comment]
I'm using unaltered code (except for the file upload name) from the send_multiple_file_upload.phps example.

**Comment by XL-2000** [comment]
Unaltered would be odd, since configured values in the example are hardcoded and need to be replaced.
Te problem is almost surely in your alteration, so for any help, you need to post all your code here

**Comment by Synchro** [comment]
Could be a bug in the example script. That error will happen if the `$path` parameter to `mb_pathinfo` is an array, and when it's called from the multiple file example it passes `$_FILES['userfile']['name']`, which may indeed be an array when there are multiple files. See what happens if you change the line that says:

        $ext = PHPMailer::mb_pathinfo($_FILES['userfile']['name'], PATHINFO_EXTENSION);

to

        $ext = PHPMailer::mb_pathinfo($_FILES['userfile']['name'][$ct], PATHINFO_EXTENSION);

**Comment by llsnndlldkm** [comment]
My man, this worked like a charm! Thank you so much!

**Comment by Synchro** [comment]
Thanks for the report!
