### ISSUE TITLE
$this->smtp->error info is overwritten after SMTP connect fail, useful error msg discarded

### ISSUE THREAD

**Issue by neekfenwick** [PHPMailer/PHPMailer#2570]
# Problem description

PHPMailer 6.5.3.

When I accidentally mistype the host or port number, the useful error message that is created gets discarded from the ErrorInfo data before PHPMailer returns from Send().

The sequence of events is:

- Create PHPMailer instance with Host = 'mistaken-smtp.gmail.com', everything else normal and try to send an email.
- smtpConnect() calls $this->smtp->connect
- in class.smtp.php the connect() function sets a custom errorHandler: set_error_handler(array($this, 'errorHandler'));
- The call to fsockopen() fails because of the mistyped hostname
- errorHandler is invoked, calls $this->setError($notice, $errno, $errmsg) with a useful errMsg "stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known"
- Because the connection failed, getSMTPConnection() then calls setError itself (line 414), overwriting the error object set by the errorHandler but still has some useful information about what caused the connection failure, and returns false.
- Because $this->smtp->connect returned false, PHPMailer.smtpConnect skips the workhorse body of the function and skips to line 1727 where it calls $this->smtp->close() and will return false.
- The call to $this->smtp->close causes the smtp class to complete wipe out its error object with $this->setError(''); .. it's here that any useful error messages get completely lost.
- Because smtpConnect() returned false, PHPMailer.smtpSend throws a phpmailerException on line 1558 which is caught in postSend() on line 1352 and PHPMailer.setError is called with the exception's message, which by now is a rather unuseful "SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting"
- PHPMailer.setError does try to inspect $this->smtp->getError() on line 3273 instead of using the plain $msg passed in, but because the close() earlier wiped out the error details in the smtp object, PHPMailer.setError simply sets ErrorInfo to the unhelpful error string from the exception.

# Code to reproduce

```php
<?php
require('vendor/autoload.php');
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

$mail = new PHPMailer();
$mailerErrors = [];
$mail->Debugoutput = function ($str, $level) use (&$mailerErrors) {
    $mailerErrors[] = [ 'str' => $str, 'level' => $level ];
};
$mail->SMTPDebug = 3;

$mail->IsSMTP();
$mail->SMTPAuth = true;
$mail->SMTPSecure = 'tls';
$mail->Host = 'mistaken-gmail.com'; // Deliberately incorrect domain name
$mail->Port = 587;
$mail->Username ='user@gmail.com';
$mail->Password = 'secretsauce';

$mail->SetFrom('fromaddress@us.com', 'Sender');
$mail->AddAddress('recipient@them.com', 'Recipient');
$mail->Subject = 'Does not matter';
$mail->Body = 'Does not matter';

if (!$mail->Send()) {

    echo "Send errored leaving:\n";
    echo "ErrorInfo: " . $mail->ErrorInfo . "\n";
    if (count($mailerErrors) > 0) {
        echo "Captured debugoutput: \n - " . join("\n - ", array_map(function ($errInfo) {
            return "[{$errInfo['level']}] \"{$errInfo['str']}\"";
        }, $mailerErrors)) . "\n";
    }

    } else {
    echo "Send returned truthy.\n";
}
```
# Debug output

```
Send errored leaving:
ErrorInfo: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Captured debugoutput: 
 - [3] "Connection: opening to mistaken-gmail.com:587, timeout=300, options=array()"
 - [3] "Connection failed. Error #2: stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known [/home/neek/workspace/premierrange2/htdocs/vendor/phpmailer/phpmailer/src/SMTP.php line 388]"
 - [3] "Connection failed. Error #2: stream_socket_client(): unable to connect to mistaken-gmail.com:587 (php_network_getaddresses: getaddrinfo failed: Name or service not known) [/home/neek/workspace/premierrange2/htdocs/vendor/phpmailer/phpmailer/src/SMTP.php line 388]"
 - [1] "SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Name or service not known (0)"
 - [3] "SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting"
```

# Discussion

I see that the useful error was emitted via debugOutput but this is not clearly categorized for software to realise as "the useful message to report" about the failure.  level '1' just means it's a Client level log entry, the others are level 3 'Debug'.

Code using PHPMailer should be able to inspect it's data after Send() has returned and easily retrieve a detailed error message describing what the error was, unconcerned with more trivial connection state logging.

Can the way SMTP class's close() method is called be altered, or the error state handling be adjusted, to retain its error?  For example as mentioned above the PHPMailer setError() function tries to inspect $this->smtp->getError():

```
    protected function setError($msg)
    {
        ++$this->error_count;
        if ('smtp' === $this->Mailer && null !== $this->smtp) {
            $lasterror = $this->smtp->getError();
            if (!empty($lasterror['error'])) {
                $msg .= $this->lang('smtp_error') . $lasterror['error'];
```

But because by this time the SMTP class's $error member has been wiped, $lasterror['error'] is an empty string and cannot be used.

For example, remove the call to setError in SMTP.close():

```
SMTP.php:

    public function close()
    {
        $this->setError(''); /* Remove me? */
```

Commenting out that line results in different output from the above test script:

```
Send errored leaving:

    ErrorInfo: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/TroubleshootingSMTP server error: Failed to connect to server Additional SMTP info: php_network_getaddresses: getaddrinfo failed: Name or service not known
```

**Comment by Synchro** [comment]
Fixed by #2787
