### ISSUE TITLE
Syntax error in PHPMailer.php in version 6.5.3

### ISSUE THREAD

**Issue by barbmc** [PHPMailer/PHPMailer#2571]
I just upgraded from version 5.2.23 of PHPmailer to version 6.5.3 on my local server running PHP 5.6 (which was workng perfectly) because I was getting escape characters in front of single and double quotes in emails sent from my prod server using the same PHPmailer version and PHP 7.2. I thought this might fix the issue.

The new version works fine on my local server but not on prod. Eventually I noticed this error in my prod PHP error log.

"[29-Nov-2021 07:22:08 America/New_York] PHP Parse error:  syntax error, unexpected '[' in /home/barbwool/public_html/includes/PHPMailer/src/PHPMailer.php on line 167"

I didn't use Composer to install, just installed manually from the zip.

I can send my code if you need it, but as I say it works fine on my local server.

**Comment by Synchro** [comment]
Are you sure about the PHP version on your server? That error sounds suspiciously like what you would get if you ran it on PHP 5.3. Run `phpinfo()` in the same context to be sure.

**Comment by barbmc** [comment]
You're right  it's PHP Version 5.3.29, got 7.2 from the info on the cpanel, sorry.

So, what version should I be using, and will that fix my problem with escaped quotes in emails from that server?

**Comment by barbmc** [comment]
Maybe I should upgrade PHP to 5.6 to match my local server instead?

**Comment by Synchro** [comment]
Well, [as of yesterday, PHP 7.4 is unsupported](https://www.php.net/supported-versions), and 8.1 has been released, so you should be running at least 8.0. You should not be doing any new development on 5.6.

Without more detail I can't say where your escaping problem is coming from.

**Comment by barbmc** [comment]
It's definitely not new development :)

Thanks so much for your help & patience. I'll have a play and a think.

**Comment by david09098** [comment]
> It's definitely not new development :)
> 
> Thanks so much for your help & patience. I'll have a play and a think.

Bro, please are you on Telegram or ICQ here is my ID i need your help relly bad
ICQ: @lesstalk.com
SKYPE: hnrjona
TELEGRAM: @knowledgepays

Please bro i beg of yiyu add me. Thanks
