### ISSUE TITLE
GMail sends me an error

### ISSUE THREAD

**Issue by SparkyAPI** [PHPMailer/PHPMailer#2598]
Hello,

when i try to send an email, i'll get an error sended by gmail.

The error-mail oft them include the following context:
554 5.7.1 <support@sparkysky.de>: Relay access denied

My Code:
`try {
                $body = "test";
		$mail = new PHPMailer(true);
		//Server settings
		$mail->isSMTP(); 
		$mail->Host       = 'smtp.gmail.com'; 
		$mail->SMTPAuth   = true;
		$mail->Username   = 'SparkySky11@gmail.com';   
		$mail->Password   = '';
		$mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS; 
		$mail->Port       = 465;    
		$mail->CharSet   = 'UTF-8';
		$mail->Encoding  = 'base64';
	
		//Recipients
		$mail->setFrom('SparkySky11@gmail.com', 'SparkySky.de');
		$mail->addAddress($mail_adress);
		$mail->addAddress("Network@SparkySky.de");
		$mail->addReplyTo("Management@SparkySky.de");
		//Add a recipient
	
	
		//Content
		$mail->isHTML(true);                           
		$mail->Subject = "Deine Support-Anfrage";
		$mail->Body = $html;
	
		$mail->send();
	} catch (Exception $e) {
		echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
	}`

Thanks for the help

**Comment by Synchro** [comment]
I'm suspicious of your connection. "Relay access denied" usually means you've not authenticated properly. Could you set `SMTPDebug = 3` and post the output?

**Comment by XL-2000** [comment]
Debug should provide more details indeed.
Wild guess, with only the above code to go on...
You try to authenticate with user "parkySky11@gmail.com" but the relay error is for "support@sparkysky.de"
Those seem to be different users and there you could encounter your authentication problems
