### ISSUE TITLE
Failed to send longer email

### ISSUE THREAD

**Issue by rslenshub** [PHPMailer/PHPMailer#2599]
I am using phpmailer to send email via SMTP. 
It was working fine for the first year.
Suddenly one day it has started to failed, after going through some test, i found out that it is only failing on longer content email.
After i restarted the php server it is able to send out the longer content email again until around a month later, it is started to failed again but the problem goes away after the server restarted.
Until recently, the server need to restart every week in order for the email to send out without failure.
I have tried to upgrade the phpmailer to version 6.5.2. The problem still persist.
The exact same email will be able to send out after restarting the php server.
I tried to point to different SMTP service, it seems to have the same behavior.
I can see from the debug log that after sending "." to indicate the end of data sending, phpmailer wait for around 20 seconds and error out. This behavior stayed the same regardless of which version of phpmailer i use.

Now, i have to restart the server every 3 days in order for the longer email to be able to send out.

Please let me know if more information is needed to check what is the issue.

# Code to reproduce
	$phpmailer = new PHPMailer();
	$phpmailer->IsSMTP();
	$phpmailer->IsHTML(true);
	$phpmailer->BounceEmail = 'bounce@' . $MAILER_DOMAIN;
	$phpmailer->addReplyTo('donotreply@' . $MAILER_DOMAIN, 'DoNotReply');
	$phpmailer->Sender = $sender;
	$phpmailer->setFrom($sender , $sender_name);
	$phpmailer->AddCustomHeader("Return-Path: admin@" . $MAILER_DOMAIN);
	//$this->Helo = $MAILER_DOMAIN;
	$phpmailer->SMTPAuth = true;
	$phpmailer->Host = $host;
	$phpmailer->Port = $port;
	$phpmailer->Username = $user;
	$phpmailer->Password = $pass;
	$phpmailer->Subject = $subject;
	$phpmailer->msgHTML($body);
	$phpmailer->SMTPDebug = 2;
	foreach($to AS $email_addr){
		$phpmailer->AddAddress($email_addr);
	}
	$ok = $phpmailer->Send();
	var_dump($ok);

# Debug output
### Error case:

----AFTER CONNECTION OK----

2022-01-06 02:01:17 SMTP INBOUND: "250 2.1.5 Recipient OK"
2022-01-06 02:01:17 SERVER -> CLIENT: 250 2.1.5 Recipient OK
2022-01-06 02:01:17 CLIENT -> SERVER: DATA
2022-01-06 02:01:17 SMTP INBOUND: "354 Start mail input; end with <CRLF>.<CRLF>"
2022-01-06 02:01:17 SERVER -> CLIENT: 354 Start mail input; end with <CRLF>.<CRLF>
2022-01-06 02:01:17 CLIENT -> SERVER: Date: Thu, 6 Jan 2022 02:01:15 +0000

----SENDING VERY LONG EMAIL CONTENT OVER HERE-----

2022-01-06 02:01:17 CLIENT -> SERVER:
2022-01-06 02:01:17 CLIENT -> SERVER: --b1_sxphHvbLKDJudEnI72ShDxLhkjvJrSSsE3bKsssi42Q--
2022-01-06 02:01:17 CLIENT -> SERVER:
2022-01-06 02:01:17 CLIENT -> SERVER: .
**2022-01-06 02:01:36 SMTP INBOUND: ""
2022-01-06 02:01:36 SERVER -> CLIENT:**
2022-01-06 02:01:36 SMTP ERROR: DATA END command failed:
SMTP Error: data not accepted.
2022-01-06 02:01:36 SMTP NOTICE: EOF caught while checking if connected
2022-01-06 02:01:36 Connection: closed

string(72) "SMTP Error: data not accepted.SMTP server error: DATA END command failed"

### Success Case
When sending out shorter messages it will be successful. Successful sending looks like below:
2022-01-06 01:04:28 CLIENT -> SERVER:
2022-01-06 01:04:28 CLIENT -> SERVER: --b1_D2lAxpFGaljjVZZbLe38evPd0mIlkCBLnKxJDNsw--
2022-01-06 01:04:28 CLIENT -> SERVER:
2022-01-06 01:04:28 CLIENT -> SERVER: .
2022-01-06 01:04:28 SMTP INBOUND: "250 2.6.0 <D2lAxpFGaljjVZZbLe38evPd0mIlkCBLnKxJDNsw@XXXXXX> [InternalId=996432413492, Hostname=EXG16MAIL11.XXXX.XXXX.com] 1867 bytes in 0.429, 4.246 KB/sec Queued mail for delivery"
2022-01-06 01:04:28 SERVER -> CLIENT: 250 2.6.0 <D2lAxpFGaljjVZZbLe38evPd0mIlkCBLnKxJDNsw@XXXXXX> [InternalId=996432413492, Hostname=EXG16MAIL11.XXXX.XXXX.com] 1867 bytes in 0.429, 4.246 KB/sec Queued mail for delivery
2022-01-06 01:04:28 CLIENT -> SERVER: QUIT
2022-01-06 01:04:28 SMTP INBOUND: "221 2.0.0 Service closing transmission channel"
2022-01-06 01:04:28 SERVER -> CLIENT: 221 2.0.0 Service closing transmission channel
2022-01-06 01:04:28 Connection: closed

**Comment by XL-2000** [comment]
I have never experienced this. How "long" are your emails (wordcount / linecount) and how large (size in bytes) are those emails?
This might well be  a server limitation instead of a PHPMailer issue

**Comment by Synchro** [comment]
See my reply to your [same question in discussions](https://github.com/PHPMailer/PHPMailer/discussions/2600).

One small thing; don't do this, it's an RFC contravention:

    $phpmailer->AddCustomHeader("Return-Path: admin@" . $MAILER_DOMAIN);

Do this instead:

    $phpmailer->Sender = 'admin@' . $MAILER_DOMAIN;

**Comment by rslenshub** [comment]
Initially around 36k characters. I output it into a file and zip it then send as attachment and it is around 1.51kb attachment.
When i changed to the attachment approach, it is able to send out for few weeks then it comes to the situation that even attachment can't be sending out.
Noted on the sender, but don't think that is the main issue.

**Comment by rslenshub** [comment]
Initiated a test using telnet. Putting the content output from phpmailer on those CLIENT -> SERVER: lines.
It is able to send out the long email successfully. Actually not that long, total is 18737 bytes in 36.642, 0.499KB/sec. Queued mail for delivery.
Sending via php still failing, so only have issue sending via php.

**Comment by Synchro** [comment]
> When i changed to the attachment approach, it is able to send out for few weeks then it comes to the situation that even attachment can't be sending out.

That makes it sounds like there are limitations being imposed on you by the server. PHPMailer simply doesn't have a mechanism to do anything like this. Generally if you're having connectivity or performance problems sending email directly, the best solution is not to do that: configure a local mail server and relay through it. It will do a far better job handling intermittent/slow/rate-limited connections than anything PHP can do.

**Comment by rslenshub** [comment]
Hi Synchro, thanks a lot for your helps and advice. I have finally able to resolved the issue.
I am using wireshark to trace the network flow between my application server and the SMTP server and found out that it is because of the IP-Sec encryption between the 2 server that is causing the issue. By limiting the MTU to 1400, now all email able to send out successfully. There is nothing wrong with the phpmailer package. Thanks again for all your helps.

I have put in the details of my tracing and resolving steps as reference in case anyone else that is encountering the same issue.
https://tech--about.blogspot.com/2022/02/smtp-mail-sending-failure-connection.html

Thanks again for all your helps and finally i am having a sounds sleep now.
