### ISSUE TITLE
SCRAM-SHA-1(-PLUS) + SCRAM-SHA-256(-PLUS) + SCRAM-SHA-512(-PLUS) + SCRAM-SHA3-512(-PLUS) supports

### ISSUE THREAD

**Issue by Neustradamus** [PHPMailer/PHPMailer#2602]
Dear @PHPMailer team,

In first, I wish you a Happy New Year!

Can you add supports of :
- SCRAM-SHA-1
- SCRAM-SHA-1-PLUS
- SCRAM-SHA-256
- SCRAM-SHA-256-PLUS
- SCRAM-SHA-512
- SCRAM-SHA-512-PLUS
- SCRAM-SHA3-512
- SCRAM-SHA3-512-PLUS

You can add too:
- SCRAM-SHA-224
- SCRAM-SHA-224-PLUS
- SCRAM-SHA-384
- SCRAM-SHA-384-PLUS

"When using the SASL SCRAM mechanism, the SCRAM-SHA-256-PLUS variant SHOULD be preferred over the SCRAM-SHA-256 variant, and SHA-256 variants [RFC7677] SHOULD be preferred over SHA-1 variants [RFC5802]".

- SCRAM-SHA-1(-PLUS):
-- https://tools.ietf.org/html/rfc5802
-- https://tools.ietf.org/html/rfc6120

- SCRAM-SHA-256(-PLUS):
-- https://tools.ietf.org/html/rfc7677 since 2015-11-02
-- https://tools.ietf.org/html/rfc8600 since 2019-06-21: https://mailarchive.ietf.org/arch/msg/ietf-announce/suJMmeMhuAOmGn_PJYgX5Vm8lNA

- SCRAM-SHA-512(-PLUS):
-- https://tools.ietf.org/html/draft-melnikov-scram-sha-512

- SCRAM-SHA3-512(-PLUS):
-- https://tools.ietf.org/html/draft-melnikov-scram-sha3-512

https://xmpp.org/extensions/inbox/hash-recommendations.html

-PLUS variants:
- RFC5056: On the Use of Channel Bindings to Secure Channels: https://tools.ietf.org/html/rfc5056
- RFC5929: Channel Bindings for TLS: https://tools.ietf.org/html/rfc5929
- Channel-Binding Types: https://www.iana.org/assignments/channel-binding-types/channel-binding-types.xhtml
- Channel Bindings for SCRAM over TLS 1.3: https://tools.ietf.org/html/draft-whited-tls-channel-bindings-for-tls13 -> https://tools.ietf.org/html/draft-ietf-kitten-tls-channel-bindings-for-tls13

IMAP:
- RFC9051: Internet Message Access Protocol (IMAP) - Version 4rev2: https://tools.ietf.org/html/rfc9051

LDAP:
- RFC5803: Lightweight Directory Access Protocol (LDAP) Schema for Storing Salted: Challenge Response Authentication Mechanism (SCRAM) Secrets: https://tools.ietf.org/html/rfc5803

HTTP:
- RFC7804: Salted Challenge Response HTTP Authentication Mechanism: https://tools.ietf.org/html/rfc7804

2FA:
- Extensions to Salted Challenge Response (SCRAM) for 2 factor authentication: https://tools.ietf.org/html/draft-melnikov-scram-2fa

IANA:
- Simple Authentication and Security Layer (SASL) Mechanisms: https://www.iana.org/assignments/sasl-mechanisms/sasl-mechanisms.xhtml

Linked to:
- https://github.com/scram-xmpp/info/issues/1

**Comment by Synchro** [comment]
Without any explanation of why anyone might want this, or if there is any useful support for it in the wild, I'm not going out of my way to do anything with this. PRs welcome of course.

**Comment by Neustradamus** [comment]
@Synchro: Sorry for the delay!

About "Mail", without libs, etc.:
From https://github.com/scram-xmpp/info/issues/1.

SCRAM-SHA-1 and SCRAM-SHA-256:
- SquirelMail (Webmail): https://github.com/RealityRipple/squirrelmail
- mpop (POP3 client): https://marlam.de/mpop/
- msmtp (SMTP client): https://marlam.de/msmtp/
- Exim (Mail server): https://bugs.exim.org/show_bug.cgi?id=2349 // Exim uses GNU SASL
- Dovecot 2.3.10 (Mail server): https://doc.dovecot.org/configuration_manual/authentication/password_schemes/ + https://dovecot.org/pipermail/dovecot-news/2020-March/000432.html
- Postfix with Dovecot SASL: https://postfix.org/
- PostfixAdmin with Postfix and Dovecot SASL: https://github.com/postfixadmin

SCRAM-SHA-1, SCRAM-SHA-256, SCRAM-SHA-512:
- SnappyMail (Webmail) : https://github.com/the-djmaze/snappymail + https://snappymail.eu/
- DataEnter CryptoFilter - The S/MIME Gateway: https://www.dataenter.com/beta/cryptofilter.htm
- DataEnter POPBeamer - The Mail Collector: https://www.dataenter.com/beta/popbeamer.htm
- DataEnter SMTPBeamer - The Mail Server: https://www.dataenter.com/beta/smtpbeamer.htm
- DataEnter XWall - The Mail Filter: https://www.dataenter.com/beta/xwall.htm

SCRAM-SHA-1(-PLUS), SCRAM-SHA-256(-PLUS), SCRAM-SHA-512(-PLUS):
- MimeKit: https://github.com/jstedfast/MailKit + http://www.mimekit.net/docs/html/Introduction.htm
- MailKit: https://github.com/jstedfast/MailKit + http://www.mimekit.net/docs/html/Introduction.htm

SCRAM-SHA-1(-PLUS), SCRAM-SHA-224(-PLUS), SCRAM-SHA-256(-PLUS), SCRAM-SHA-384(-PLUS), SCRAM-SHA-512(-PLUS):
- Cyrus SASL + Cyrus IMAP (Mail server): https://www.cyrusimap.org/sasl/sasl/authentication_mechanisms.html
- Postfix with Cyrus SASL: https://postfix.org/
- PostfixAdmin with Postfix and Cyrus SASL: https://github.com/postfixadmin
- Mutt (Mail client) with Cyrus SASL: http://mutt.org/
- NeoMutt (Mail client): https://neomutt.org/

SCRAM-SHA-1:
- Claws Mail (Mail client): IMAP only: https://www.claws-mail.org/
- Dovecot: https://doc.dovecot.org/configuration_manual/authentication/password_schemes/ (Dovecot 2.3.10 has SCRAM-SHA-1 and SCRAM-SHA-256)
- Postfix with Dovecot SASL: https://postfix.org/
- PostfixAdmin with Postfix and Dovecot SASL: https://github.com/postfixadmin

**Comment by Neustradamus** [comment]
@Synchro: Any progress?

On more, Dovecot 2.4.0 has now SCRAM-SHA-1-PLUS/SCRAM-SHA-256-PLUS in more SCRAM-SHA-1/SCRAM-SHA-256 supports.

All details here:
- https://github.com/scram-sasl/info/issues/1

About PHP, PEAR Auth_SASL/Auth_SASL2 and Net_SMTP has SCRAM supports.

cc: @schengawegga.
