### ISSUE TITLE
mail only works on the local server

### ISSUE THREAD

**Issue by Xazgl** [PHPMailer/PHPMailer#2613]
Does Phpmailer send emails from a local server, but it does not work on the domain server.It turns out that I am sending messages to everyone in xampp, and it is impossible to log in on the server when trying to send enter image description here.There are no special characters in the password, I gave permission to the mail, because all letters come on the local server
my controller with phpmiler :

public function send(ToRequest $request) {

        $name = $request->name;
        $phone = $request->phone;
        $phoneAndName=$name.'  '.$phone;

        $mail = new PHPMailer(true);
        $mail->SMTPDebug = 0;
        $mail->isSMTP();
        $mail->Host = env('EMAIL_HOST');
        $mail->SMTPAuth = 'true';
        $mail->Username = env('EMAIL_USERNAME');
        $mail->Password = env('email_password');
        $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
        $mail->Port = 587;
        $mail->setFrom('emailyandex.ru.','text');
        $mail->addAddress('emailyandex.ru');
        $mail->isHTML(true);
        $mail->CharSet="UTF-8";
        $mail->Subject = 'subject';
        $mail-> Body = $phoneAndName;
       $result =  $mail->send();
       if($result) {
           echo 'good;
       }else{
           echo'error';
       }
my env on server and local -server

```
APP_NAME=Laravel
APP_ENV=local
APP_KEY=key
APP_DEBUG=true
APP_URL= domen 

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=root
DB_PASSWORD=


BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DRIVER=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST= smtp.yandex.ru
MAIL_PORT=465
MAIL_USERNAME = email@yandex.ru
MAIL_PASSWORD =  password
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

EMAIL_HOST= smtp.yandex.ru
EMAIL_PORT=465
EMAIL_USERNAME=email@yandex.ru
EMAIL_PASSWORD= password](url)
```

**Comment by Synchro** [comment]
Can you post the debug output with `SMTPDebug = 3`?
Local va server issues are usually caused by your hosting provider blocking outbound SMTP, so read the troubleshooting guide about that.

**Comment by Xazgl** [comment]
> Можете ли вы опубликовать результаты отладки с `SMTPDebug = 3`помощью ? Проблемы с локальным сервером va обычно возникают из-за того, что ваш хостинг-провайдер блокирует исходящий SMTP, поэтому прочитайте руководство по устранению неполадок об этом.

on the contrary, I have apache running locally. After that, I upload the project to the hosting and there it does not pass authorization when sending

**Comment by Xazgl** [comment]
> Can you post the debug output with `SMTPDebug = 3`? Local va server issues are usually caused by your hosting provider blocking outbound SMTP, so read the troubleshooting guide about that.

on the contrary, I have apache running locally. After that, I upload the project to the hosting and there it does not pass authorization when sending

**Comment by Synchro** [comment]
Please read what I said and follow the troubleshooting guide. Your local environment and your server's environment are very different things with very different constraints. That it runs locally has little bearing on whether it will work on your server.

**Comment by Xazgl** [comment]
> Пожалуйста, прочитайте то, что я сказал, и следуйте руководству по устранению неполадок. Ваша локальная среда и среда вашего сервера - это очень разные вещи с очень разными ограничениями. То, что он работает локально, мало влияет на то, будет ли он работать на вашем сервере.
https://disk.yandex.ru/i/myvgOlKypEeLyA

**Comment by Synchro** [comment]
I spotted a simple bug:

    $mail->SMTPAuth = 'true';

That's a string containing the word "true", not a boolean `true` value. It should be `$mail->SMTPAuth = true;`.

There are two different formats defined for the `LOGIN` auth mechanism, and it may be that the mail server doesn't support the one that PHPMailer uses (though it should support both), so try using a different `AuthType` that doesn't have that problem:

    $mail->AuthType = 'PLAIN';
