### ISSUE TITLE
PHP fatal error when mailbox is full

### ISSUE THREAD

**Issue by toxpal** [PHPMailer/PHPMailer#2614]
I don't know if this is expected behavior, but sometimes I get PHP fatal error in my server error log and 500 HTTP error in browser when sending emails via PHPMailer. The error is:

`PHP Fatal error:  Uncaught PHPMailer\PHPMailer\Exception: SMTP Error: The following recipients failed: email@address.com: Mailbox is full / Blocks limit exceeded / Inode limit exceeded
 in /home/username/public_html/vendor/phpmailer/phpmailer/src/PHPMailer.php:2044`

The PHP code is:

```
$mail=new PHPMailer(true);
$mail->CharSet="UTF-8";
$mail->isSMTP();
$mail->SMTPDebug=SMTP::DEBUG_OFF;
$mail->Host=$SMTP_ADDRESS;
$mail->Port=$SMTP_PORT;
$mail->SMTPSecure=PHPMailer::ENCRYPTION_STARTTLS;
$mail->SMTPAuth=true;
$mail->Username=$SMTP_USERNAME;
$mail->Password=customDecrypt($SMTP_PASSWORD, ENCRYPTION_KEY);
$mail->setFrom($EMAIL_FROM_ADDRESS, $EMAIL_FROM_NAME);
$mail->addAddress($recipient_email, $recipient_name);
$mail->Subject=$email_subject;
$mail->Body=$email_text;
$mail->send();
```

Is this fatal error (when mailbox is possibly full) a bug or is it expected behavior? If this is normal, how do I change it, so script doesn't stop working because of fatal error just because someone's mailbox is full?

**Comment by XL-2000** [comment]
PHPMailer needs a correctly running SMTP server (and connection) and handover the emails for sending.
Any problems with the SMTP connection (misconfiguration, authorization, limiting etc) is outide the grasps and scope of PHPMailer.
Any problems outside the scope of PHPMailer should be handled explicitly by you.

Have you tried something like:

`
if (!$mail->send()) {
        $error = $mail->ErrorInfo;
        $raw    = $mail->getSentMIMEMessage();
      } else {
        // ALL IS OK
      }
`

**Comment by toxpal** [comment]
Yes, I realize that SMTP connection is my responsibility. What I want to say is that 99% of emails are sent perfectly using SMTP (we send 100+ of them daily), but just sometimes script fails because of error I described above. As a result, I don't think it's a problem with SMTP configuration?

Yes, I tried `if (!$mail->send())...` but it works the same way - sometimes script is terminated because of PHP fatal error and the same message (mailbox is full) is displayed in error log.

**Comment by Synchro** [comment]
Well that's a pretty straightforward bug in your script: you are asking PHPMailer to throw exceptions (by passing `true` to the constructor), but then you have no try/catch block around your code, so you end up with a fatal uncaught exception. Catch the exception and the problem goes away.
