### ISSUE TITLE
PHPMailer doesn't add different attachments with the same name/type.

### ISSUE THREAD

**Issue by vladimir-vv** [PHPMailer/PHPMailer#2615]
Greetings,
Thank you for your work!

We have discovered an issue.
For example user has a screenshot. Then he modify it and save into another folder with the same name. And he wants to send by email both of them.

PHPMailer will add only first attachment.
I guess this is because of these lines in PHPMailer.php file :
```php
                $inclhash = hash('sha256', serialize($attachment));
                if (in_array($inclhash, $incl, true)) {
                    continue;
                }
```
Can you do something with it?

**Comment by XL-2000** [comment]
Regardless of the technical aspect... From a user (receiver) perspective: what will happen if you have 2 attachments with the same name in one email and the sender says "you can see this in screenshot.jpg"? How would this ambiguous situation be desirable or even workable?

**Comment by vladimir-vv** [comment]
Yes, I use addStringAttachment()
```php
$mail->addStringAttachment($_t['Body'], $_file['description'], 'base64', $_file['mimetype']);
```
where $_t['Body'] I'm getting from AWS S3 and this is a GuzzleHttp\Psr7\Stream object which doesn't have __serialize() implementation
Everything clear now.

So I see 2 ways how to solve it:
1) read whole attachment and pass it to phpmailer
2) use wrapper class with hash string (AWS S3 returns ETag for instance) which can be passed in __serialize() method

I didn't make a test but I think that in first case script will consume more memory then in second

May be phpmailer should check string type and if case we have object put message into error_log or something else. What do you think?

**Comment by XL-2000** [comment]
> May be phpmailer should check string type and in case we have object put message into error_log or something else. What do you think?

Why do you think PHPMailer should handle non-critical cases which are in the control and responsibility of the developer calling/using it?

**Comment by Synchro** [comment]
I think 3 is your best option, and it's very simple to implement. In general PHPMailer is a bit too memory heavy anyway, so I don't really want to do things like get a hash of the string content in order to tell things apart, when it's much more straightforward to control the filename – you know ahead of time whether these things are different, whereas PHPMailer would have to figure it out, which is wasteful.
