### ISSUE TITLE
Not getting the vendor/autoload.php files when installing with composer

### ISSUE THREAD

**Issue by pcon2009** [PHPMailer/PHPMailer#2618]
Sorry if this is the wrong place to ask, but when I follow the instructions to install via composer, everything appears to work as it should, but I don't get the vendor/autoload.php file. To be clear, I get the following in the terminal when installing:

`composer require phpmailer/phpmailer
Using version ^6.5 for phpmailer/phpmailer
./composer.json has been updated
Running composer update phpmailer/phpmailer
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking phpmailer/phpmailer (v6.5.3)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing phpmailer/phpmailer (v6.5.3): Extracting archive
5 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!`

It seems like that is doing what it should, but I can't find any new files or anything. I've searched my computer for them, even, but I can't figure out what I am doing wrong. I tried removing and reinstalling through composer, but still nothing. I don't want to add the files manually, because I am not experienced enough and feel like that will probably just create more issues, but I am willing to do that if it is simpler that I think. Anyone willing to help me out here?

**Comment by Synchro** [comment]
Can you show what you *do* have? Do you have a composer.lock file? Is there a vendor folder?

**Comment by pcon2009** [comment]
I get a composer.lock file in my Documents folder. I can't seem to find a vendor folder at all - not entirely sure where it is supposed to be in the first place, but it definitely isn't where my PHP files expect it to be.

**Comment by Synchro** [comment]
You'd normally run composer while you're in the root directory of your project, and it will create composer.lock and the vender folder in there.

**Comment by pcon2009** [comment]
> Are you in the right folder when you run it?

I was not. This solved my issue. I guess I didn't realize I had to be in the specific folder when I ran composer. I am very new to all this so I really appreciate the help! It's always the little things that trip me up. I just did a "cd" in powershell to get to the right directory first, then ran composer and things are working now! Maybe there should be a note on the main info page that mentions double checking this for noobs like me?

**Comment by Synchro** [comment]
It's because while composer is typically installed so that it's accessible anywhere in your system, you actually use it per-project, and every project can have a different set of requirements in its own composer.json file. You *can* install packages globally, but this is usually only used for system-wide tools that can be used across multiple projects, such as static analysis tools like phpcs or phpstan.

**Comment by BlasioGodi** [comment]
Benefited from this as well. Realized later that I had no clue what I was doing. Thanks.

**Comment by Dolphn** [comment]
Same thing here, two years later. Maybe the could pack this information, to run this command `composer require phpmailer/phpmailer` inside the needed directory more clearly on top of the guide. Thanks a lot!

**Comment by Synchro** [comment]
> Same thing here, two years later. Maybe the could pack this information, to run this command `composer require phpmailer/phpmailer` inside the needed directory more clearly on top of the guide. Thanks a lot!

This is literally [one of the very first things in the readme](https://github.com/PHPMailer/PHPMailer#installation--loading). I can't read it for you!
