### ISSUE TITLE
Users without WEB.de mailhoster wont receive emails.

### ISSUE THREAD

**Issue by SparkyAPI** [PHPMailer/PHPMailer#2621]
Hello,

users without a @web.de mail wont receive a mail.  So users with a @gmail.com mail-adress or another stuff dont get it. Its neither in the spam nor in the normal folder.

What can I do to change this?

**Comment by saschi123** [comment]
Aktiviere einfach den Debug Modus und sende an eine Gmail Adresse. Die Ausgabe wird dir sicher weiter helfen. Wahrscheinlich wird deine Sendermail geblockt:

https://github.com/PHPMailer/PHPMailer/wiki/SMTP-Debugging

**Comment by Synchro** [comment]
I've seen deliveries to `web.de` domains fail when you don't have a reverse DNS entry that matches your HELO name. Get your hosting provider to set that correctly and it will probably help deliveries there and in other places too. See [the docs on this](https://github.com/PHPMailer/PHPMailer/wiki/Improving-delivery-rates,-avoiding-spam-filters#mismatched-reverse-dns-for-your-mail-server).
