### ISSUE TITLE
Mail will not send, no error message is displayed

### ISSUE THREAD

**Issue by trebr** [PHPMailer/PHPMailer#2626]
`<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'PHPMailer-master/src/Exception.php';
require 'PHPMailer-master/src/PHPMailer.php';
require 'PHPMailer-master/src/SMTP.php';

// I installed using the zip file, so I am not using autoloader

$mail = new PHPMailer;
$mail->isSMTP(); 
$mail->Host = "smtp.office365.com";
$mail->SMTPDebug = 3; 
$mail->Port = 587; 
$mail->SMTPSecure = 'tls'; 
$mail->SMTPAuth = true;
$mail->Username = "[ my Exchange email address ]";
$mail->Password = "[ my Exchange password ]";
$mail->setFrom("[  my Exchange email address ]", "[ my name ]");
$mail->addAddress("[ recipient email ]", " [ recipient name ]");
$mail->Subject = 'PHPMailer SMTP test';
$mail->msgHTML("test body");
$mail->AltBody = 'HTML messaging not supported';
if(!$mail->send()){
    echo "Mailer Error: " . $mail->ErrorInfo;
}else{
    echo "Message sent!";
}
?>`

The only output is:

> 2022-02-08 14:36:21 Connection: opening to smtp.office365.com:587, timeout=300, options=array()

There is no other output whatsover.

Other notes:

- I am using PHPMailer version 6.5.3
- I checked my outgoing SMTP connection from my local server at https://testconnectivity.microsoft.com/tests/exchange and no errors were reported.
- The exchange account I am sending from does not have multifactor authentication enabled, so I do not need to use an app password.
- I checked the login details for my email address.
- I was using this code without issue until last Friday.

**Comment by Synchro** [comment]
This looks like a straightforward SMTP block by your hosting provider, who can change their policies at any time. It's not possible to use those Microsoft tools to troubleshoot your *outbound* connection; you can test using the advice in the PHPMailer troubleshooting guide though, using telnet and openssl.

**Comment by trebr** [comment]
> 

I should have made it clear that I was raising two issues:
1. a potential issue with the SMTP (which you've addressed, so thank you for that)
2. the fact no errors were reported

If I set
    $mail->SMTPDebug
to either 1 or 2 there is no output at all. If I set it to 3, I only get the output quoted in my issue: the email does not send yet no error is reported.

https://github.com/PHPMailer/PHPMailer/issues/2570 also reported an issue with error reporting. I thought it would be useful to draw my issue to the developers' attention.

Thanks again for the information in your reply, I will look into the SMTP issue further.

**Comment by Synchro** [comment]
You will only get output with SMTPDebug 1 and 2 if it can actually establish an SMTP connection, and it's not getting that far. Level 3 shows the connection information which precedes that.

Yes, I do need to pay some attention to #2570, as it makes  good point! However, if your hosting provider has decided to block outbound SMTP, it won't help.
