### ISSUE TITLE
Getting "Relay access denied" error while using isSMTP()

### ISSUE THREAD

**Issue by sonalnaidu** [PHPMailer/PHPMailer#2627]
Code:
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

require_once(dirname(__DIR__).'/www/server/PHPMailer-master/src/Exception.php');
require_once(dirname(__DIR__).'/www/server/PHPMailer-master/src/PHPMailer.php');
require_once(dirname(__DIR__).'/www/server/PHPMailer-master/src/SMTP.php');

$mail = new PHPMailer();
try {
    //Server settings
    $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      //Enable verbose debug output
    $mail->isSMTP();                         //Send using SMTP
    $mail->SMTPDebug = 2;
    $mail->SMTPSecure ='tls';
    $mail->Host       = 'sail.1rp.in';                     //Set the SMTP server to send through
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
    $mail->SMTPAuth = false;
    $mail->SMTPAutoTLS = false;
    $mail->DKIM_domain = 'sail.1rp.in';
   $mail->SMTPOptions = array(
    'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )
);
    
    $mail->DKIM_private = 'dkim_private.pem';
    $mail->DKIM_selector = 'phpmailer';
    $mail->DKIM_passphrase = '';
    $mail->DKIM_identity = $mail->From;
    $mail->DKIM_copyHeaderFields = false;

$mail->Username   = 'sonal@sail.1rp.in';                     //SMTP username
    $mail->Password   = 'Sxxxxx';                               //SMTP password
    $mail->Port       = 587;                                  //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`

    //Recipients
    $mail->setFrom('sonal@sail.1rp.in', 'Sonal');
    $mail->addAddress('sxxxx@gmail.com', 'Sonal R');     //Add a recipient
  

  

    //Content
    $mail->isHTML(true);                                  //Set email format to HTML
    $mail->Subject = ' OTP Verification';
    $mail->Body    = 'Your DEMO Id is1234';
  

 
    $mail->action_function = 'callbackAction';
    $mail->send();
    echo 'Message has been sent'.$mail->ErrorInfo;
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}

?>

------------------------------------------------------------------------------------
Demo Output:

Message will go2022-02-08 17:46:31	SERVER -> CLIENT: 220 sail.1rp.in ESMTP Postfix (Ubuntu)
2022-02-08 17:46:31	CLIENT -> SERVER: EHLO sail.1rp.in
2022-02-08 17:46:31	SERVER -> CLIENT: 250-sail.1rp.in
                   	                  250-PIPELINING
                   	                  250-SIZE 102400000
                   	                  250-VRFY
                   	                  250-ETRN
                   	                  250-STARTTLS
                   	                  250-ENHANCEDSTATUSCODES
                   	                  250-8BITMIME
                   	                  250-DSN
                   	                  250-SMTPUTF8
                   	                  250 CHUNKING
2022-02-08 17:46:31	CLIENT -> SERVER: STARTTLS
2022-02-08 17:46:31	SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
2022-02-08 17:46:31	CLIENT -> SERVER: EHLO snmail.1rp.in
2022-02-08 17:46:31	SERVER -> CLIENT: 250-snmail.1rp.in
                   	                  250-PIPELINING
                   	                  250-SIZE 102400000
                   	                  250-VRFY
                   	                  250-ETRN
                   	                  250-AUTH PLAIN LOGIN
                   	                  250-ENHANCEDSTATUSCODES
                   	                  250-8BITMIME
                   	                  250-DSN
                   	                  250-SMTPUTF8
                   	                  250 CHUNKING
2022-02-08 17:46:31	CLIENT -> SERVER: MAIL FROM:<sonal@sail.1rp.in>
2022-02-08 17:46:31	SERVER -> CLIENT: 250 2.1.0 Ok
2022-02-08 17:46:31	CLIENT -> SERVER: RCPT TO:<sxxxx@gmail.com>
2022-02-08 17:46:31	SERVER -> CLIENT: 554 5.7.1 <sxxxx@gmail.com>: Relay access denied
2022-02-08 17:46:31	SMTP ERROR: RCPT TO command failed: 554 5.7.1 <sxxxx@gmail.com>: Relay access denied
2022-02-08 17:46:31	CLIENT -> SERVER: QUIT
2022-02-08 17:46:31	SERVER -> CLIENT: 221 2.0.0 Bye
2022-02-08 17:46:31	SMTP Error: The following recipients failed: sxxxx@gmail.com: <sxxxx@gmail.com>: Relay access denied
Message has been sentSMTP Error: The following recipients failed: sxxxx@gmail.com: <sxxxx@gmail.com>: Relay access denied

**Comment by Synchro** [comment]
It's because you're doing this:

    $mail->SMTPAuth = false;

Most mail servers (that are not spam gateways) will not allow you to send email without authenticating first, and you turned authentication off, so it doesn't know who you are, and so complains that you do not have permission to relay through that server.

**Comment by Synchro** [comment]
Also, don't turn off TLS certificate verification; fix the underlying problem instead, as discussed in the troubleshooting guide.

**Comment by sonalnaidu** [comment]
Thanks a lot! This worked for me

> It's because you're doing this:
> 
> ```
> $mail->SMTPAuth = false;
> ```
> 
> Most mail servers (that are not spam gateways) will not allow you to send email without authenticating first, and you turned authentication off, so it doesn't know who you are, and so complains that you do not have permission to relay through that server.
