### ISSUE TITLE
Password is correct. But PHPMailer (maybe it's related to php) couldn't send email.

### ISSUE THREAD

**Issue by Nyamkhuub** [PHPMailer/PHPMailer#2628]
# Problem description
Password is correct. But PHPMailer (maybe it's related to php) couldn't send email.
PHP version: 5.6.40
Supported TLS version: 1.2 (I checked my server php)

# Code to reproduce
                                 $mail = new PHPMailer();
				$mail->IsSMTP();		   // set mailer to use SMTP
				$mail->Host = 'smtp.office365.com';  // specify main and backup server
				$mail->SMTPSecure = 'tls';
				$mail->SMTPAuth = true;  // turn on SMTP authentication
				$mail->Username = $this->container->getParameter('MAIL_USERNAME');  // SMTP username
				$mail->Password = $this->container->getParameter('MAIL_PASSWORD'); // SMTP password
				$mail->From = $this->container->getParameter('MAIL_USERNAME');
				$mail->FromName = $this->container->getParameter('MAIL_FROM');
				$mail->SingleTo = true;
				$mail->Timeout = 600;
				$mail->Port = 587;

				foreach ($checkMailList as $address) {
					$mail->AddAddress($address);
				}
				$mail->WordWrap = 350;		 // set word wrap to 50 characters
				$mail->IsHTML(true);		// set email format to HTML
				$mail->CharSet = 'UTF-8';		 // set email format to HTML
				$mail->Subject = $title;
				$mail->Body = LibraryBundle::setMailHeaderFooter($mailContent);
				$mail->AltBody = "";
				$mail->SMTPDebug = 2;

# Debug output

SMTP -> FROM SERVER:220 HKAPR04CA0008.outlook.office365.com Microsoft ESMTP MAIL Service ready at Wed, 9 Feb 2022 06:34:23 +0000

<br />SMTP -> FROM SERVER: 250-HKAPR04CA0008.outlook.office365.com Hello [43.231.114.89]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8

<br />SMTP -> FROM SERVER:220 2.0.0 SMTP server ready

<br />SMTP -> FROM SERVER: 250-HKAPR04CA0008.outlook.office365.com Hello [43.231.114.89]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH LOGIN XOAUTH2
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8

<br />SMTP -> ERROR: Password not accepted from server: 421 4.7.66 TLS 1.0 and 1.1 are not supported. Please upgrade/update your client to support TLS 1.2. Visit https://aka.ms/smtp_auth_tls. [HKAPR04CA0008.apcprd04.prod.outlook.com]

**Comment by XL-2000** [comment]
If you are running PHP 5.6, you absolutely need to upgrade!!! Also, what version of PHPMailer are you running? 
Next to that; the SMTP response gives clear indication that TLS 1.2 in NOT used for this instance

**Comment by Synchro** [comment]
Yes, the solution here is to upgrade your PHP. It's unclear whether your PHP binary has support for 1.2, because PHP 5.6 can definitely use that, but it may be that you have an outdated openssl library with it. This is likely if you're running a distro like Red Hat.
