### ISSUE TITLE
Need Mail Delivery Logs/ Processing Logs in Callback URL/Webhook

### ISSUE THREAD

**Issue by sonalnaidu** [PHPMailer/PHPMailer#2631]
------------------------------------------------------------------------------------------------
 
---------------------------------------------------------------------------------------
I need the Delivery status & intermediate update like this(available in syslog when I use isMail() )
 -

Feb  9 23:37:16 snmail postfix/pickup[3050067]: D2B6B81955: uid=0 from=<sxxx@sil.1p.in>
Feb  9 23:37:16 snmail postfix/cleanup[3051060]: D2B6B81955: message-id=<QW4IYhexVQ8xgcQtCtuhXmSb4BBLbnTyM@sil.1p.in>
Feb  9 23:37:16 snmail postfix/qmgr[387025]: D2B6B81955: from=<sxxx@sil.1p.in>, size=678, nrcpt=1 (queue active)
Feb  9 23:37:22 snmail postfix/smtp[3051062]: D2B6B81955: to=<sol@2fc.in>, relay=mx.zoho.com[204.141.43.44]:25, delay=5.2, delays=0.04/0.02/2.8/2.3, dsn=2.0.0, status=sent (250 Message received)
Feb  9 23:37:22 snmail postfix/qmgr[387025]: D2B6B81955: removed

To be given as an API response or via some way to be sent to a callback URL.
IsMail() or IsSMTP() eirther option works.

**Comment by Synchro** [comment]
You could enable debug output and intercept it by injecting a callable into `Debugoutput`, as [the source describes](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L404). What you do with the output is up to you.

**Comment by Synchro** [comment]
Those log lines are in your mail server's log, to which PHPMailer has no access because it's at the receiving end. You would need to configure either a new log service that pipes log output into a script, or give a script access to this log file, but either way this is beyond what PHPMailer is for.
