### ISSUE TITLE
SMTP ERROR: Failed to connect to server: Connection timed out (110)SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

### ISSUE THREAD

**Issue by bvttle** [PHPMailer/PHPMailer#2634]
I've tried to configure SMTP on my site, however I'm getting this issue:
SMTP ERROR: Failed to connect to server: Connection timed out (110)SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

What does this mean, and how can I fix this?

**Comment by Synchro** [comment]
As the guide says, it probably means that your hosting provider blocks outbound SMTP. You should read their documentation to see if they require you to use their servers or something, or ask them to unblock SMTP for you.
