### ISSUE TITLE
SMTP server on Docker php website

### ISSUE THREAD

**Issue by NeliswaDS** [PHPMailer/PHPMailer#2636]
Hi may you please assist me , I have the below code. When I run it with localhost (Xampp)  it send the email but when i run it inside docker image i get this  error :
2022-02-17 10:59:37 Connection: opening to smtp.office365.com:587, timeout=300, options=array ( ) 2022-02-17 10:59:37 Connection: opened 2022-02-17 10:59:47 SMTP -> get_lines(): $data is "" 2022-02-17 10:59:47 SMTP -> get_lines(): $str is "" 2022-02-17 10:59:47 SERVER -> CLIENT: 2022-02-17 10:59:47 SMTP NOTICE: EOF caught while checking if connected 2022-02-17 10:59:47 Connection: closed 2022-02-17 10:59:47 SMTP Error: Could not connect to SMTP host. 2022-02-17 10:59:47 SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting Mail failed**********

 code:
$mail = new PHPMailer;
            $mail->isSMTP();
            $mail->Host = 'smtp.office365.com';
            $mail->Port = 587;
            $mail->SMTPDebug = 4;
            $mail->SMTPSecure ="tls";
            $mail->SMTPAuth = true;
            $mail->CharSet = "UTF-8";
            $mail->Username = "aaaaa@company.com";
            $mail->Password = "*******";

           
            $mail->addAddress($email);

            $mail->isHTML(true);

            $mail->Subject = "Password Reset Code";
            $message = "Your password reset code is $code";

            $mail->msgHTML($message);

           
            if ($mail->send()) {
                $info = "We've sent a password reset OTP to your email - $email";
                $_SESSION['info'] = $info;
                $_SESSION['email'] = $email;
                header('location: confirm code');
                exit();
            } else {
                $errors['otp-error'] = "Failed while sending code!";
            }
        } else {
            $errors['db-error'] = "Something went wrong!";
        }
    } else {
        $errors['email'] = "This email address does not exist!";
    }
}

**Comment by Synchro** [comment]
This is probably because your docker container is not allowing outbound SMTP connections. You'll need to add that to your docker config to allow that – but don't ask me how!

**Comment by Synchro** [comment]
"Exposing" a port suggests you're using in for inbound connections; ensure that you're allowing outbound connections too, and that the network is bridging correctly out of the container. You'll need to refer to docker documentation, I have no idea what you need to do.
