### ISSUE TITLE
Error or Misleading text in example 

### ISSUE THREAD

**Issue by Elijha** [PHPMailer/PHPMailer#2638]
In the "A Simple Example" example the following line 

$mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;            //Enable implicit TLS encryption

Should be this line if you mean to use a TLS

$mail->SMTPSecure = PHPMailer::**ENCRYPTION_STARTTLS**;

The comment on the initial line is a bit misleading and does not actually work for TLS connection ie allow connections to Microsoft 365 SMTP which requires a TLS connection.  Discovering this took me some time to work out as I took that comment at face value and focused on other settings thinking this was not wrong.

**Comment by Synchro** [comment]
The options are called SMTPS and SMTP+STARTTLS because those are the exact terms used in the RFCs. They are **both** implemented using TLS, because SSL no longer exists.
