### ISSUE TITLE
Please help me  

### ISSUE THREAD

**Issue by Tramadolofficial** [PHPMailer/PHPMailer#2644]
Please help my php mailer can’t send mail to two or more bcc emails or email list I have been working on it for hours trying to fix it and I’m not doing it the right way. How can I make it to accept email list in email form with , . For email my users. Response: Invalid address: (bcc): Felix.okitipi@gmail.com,he.sn@gmail.com

PHPMailer\PHPMailer\Exception Object ( [message:protected] => Invalid address: (bcc): Felix.okitipi@gmail.com, he.sn@gmail.com[string:Exception:private] => [code:protected] => 0 

My users in my website  mailing list in .txt file up to 1500
here is my code 

  // Add cc to header if there is a value in either
    if (!empty($cc)) {
        $mail->addCC($cc);
    }
    // Add bcc to header if there is a value
    if (!empty($bcc)) {
        $mail->addBCC('$bcc, ', ');

**Comment by Synchro** [comment]
Single quoted strings in PHP don't do interpolation. Do this:

    if (!empty($bcc)) {
        $mail->addBCC($bcc);
    }

For this to work, `$bcc` should only contain a single email address, so if you have a comma-delimited list, do this:

    foreach(explode(',', $bcc) as $addr) {
        $mail->addBCC($addr);
    }

**Comment by Tramadolofficial** [comment]
Please check if I did it right 


    // Add cc to header if there is a value in either
    if (!empty($cc)) {
        $mail->addCC($cc);
    }
    // Add bcc to header if there is a value
    if (!empty($bcc)) {
    $mail->addBCC($bcc);
}
       
    
        foreach(explode(',', $bcc) as $addr) {
    $mail->addBCC($addr);
}

**Comment by Tramadolofficial** [comment]
Or 
    // Add cc to header if there is a value in either
    if (!empty($cc)) {
        $mail->addCC($cc);
    }
    // Add bcc to header if there is a value
    foreach(explode(',', $bcc) as $addr) {
    $mail->addBCC($addr);
}

**Comment by Tramadolofficial** [comment]
It worked I love you

**Comment by Tramadolofficial** [comment]
Thank you

**Comment by Tramadolofficial** [comment]
I appreciate

**Comment by Tramadolofficial** [comment]
Why is to required in other to send bcc email?

**Comment by Synchro** [comment]
It's not. If you only use BCC, To will be auto-populated with an empty group named (by convention) `undisclosed recipients`, because historically some email systems don't like not having a To address.

**Comment by Tramadolofficial** [comment]
Please i need your help this is my code for to 

//Recipients
    $mail->setFrom($fromEmail, $fromName);
    $mail->addAddress($toEmail);
    
    // Add cc to header if there is a value in either
    if (!empty($cc)) {
        $mail->addCC($cc);
    }
    // Add bcc to header if there is a value
    if (!empty($bcc)) { 
    foreach(explode(',', $bcc) as $addr) {
    $mail->addBCC($addr);
}
    

but this is the response print_r(PHPMailer\PHPMailer\Exception: Invalid address: (to): in 

 PHPMailer\PHPMailer\PHPMailer->addAddress('') #2 {main});

**Comment by Tramadolofficial** [comment]
it keeps saying to is required

**Comment by Synchro** [comment]
Please show the actual error message.

**Comment by Tramadolofficial** [comment]
ok

**Comment by Tramadolofficial** [comment]
print_r(PHPMailer\PHPMailer\Exception: Invalid address: (to): in /home/servyxda/requiredverification.com/sendmail/xnetgroup/PHPMailer/PHPMailer.php:1004 Stack trace: #0 /home/servyxda/requiredverification.com/sendmail/xnetgroup/PHPMailer/PHPMailer.php(934): PHPMailer\PHPMailer\PHPMailer->addOrEnqueueAnAddress('to', '', '') #1 /home/servyxda/requiredverification.com/sendmail/xnetgroup/mailer.php(94): PHPMailer\PHPMailer\PHPMailer->addAddress('') #2 {main});

**Comment by Synchro** [comment]
Can you show your code? It looks like you're somehow setting an invalid to address.

**Comment by Tramadolofficial** [comment]
sure i can do you need the form code?

**Comment by Synchro** [comment]
Just the PHP code, not your form

**Comment by Tramadolofficial** [comment]
ok

**Comment by Tramadolofficial** [comment]
<?php
// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

//Load composer's autoloader
require 'vendor/autoload.php';


  //send email



              require_once "PHPMailer/PHPMailer.php";
              require_once 'PHPMailer/Exception.php';
              
     //PHPMailer Object
        $mail = new PHPMailer;

// Turn this off when debugging and devloping
//error_reporting(0);

// Mail values
$fromName        =  trim($_POST["fromName"]);
$fromEmail       =  trim($_POST["fromEmail"]);
$toEmail         =  trim($_POST["toEmail"]);
$cc              =  trim($_POST["cc"]);
$bcc             =  trim($_POST["bcc"]);
$subjectLine     =  trim($_POST["subjectLine"]);

// Message Values
$richMessageText =  $_POST["richMessageText"];
$rawMessageText  =  $_POST["rawMessageText"];
$message         =  "";
$messageErrorSet = false;

$mail->DebugOutput = function ($str, $level) {
  file_put_contents(
    '/error/error.txt',
    date('Y-m-d H:i:s') . "\t" . $str,
    FILE_APPEND | LOCK_EX
  );
};

// Attatchment
$path            = "uploads/";
$path            = $path . basename( $_FILES['attachment']['name']);
$fileTempName    = $_FILES['attachment']['tmp_name'];
$fileUploaded    = 0; // 0 = no upload, 1 = upload success, 2 = upload failure
$attatchError    = "";

// File attacher + error handler
if (!empty($fileTempName)) { //checks to see if a file was attatched
    // Attempt to upload file
    if(move_uploaded_file($fileTempName, $path)) {
        $fileUploaded = 1; // success
    } else {
        $fileUploaded = 2; // failure
        $attatchError = "Your message was not sent. There was an error uploading your attachment. Make sure that your php.ini file within your web server allows for file uploads, and that it allows for the upload size of your attatched file. Check out <a href='https://mediatemple.net/community/products/dv/204403894/how-can-i-edit-the-php.ini-file'>this guide</a> to make changes to the php.ini file.";
    }
}

// Store the right message body as the $message var
// If value exists for ritch text but not raw sore rich message text as $message
if(!empty($richMessageText) && empty($rawMessageText)) {
    $message = $richMessageText;
}
// If value exists for raw text but not ritch store raw message text as $message
elseif (empty($richMessageText) && !empty($rawMessageText)) {
    $message = $rawMessageText;
// If values exist for both then throw an error and update the error text
} elseif (!empty($richMessageText) && empty(!$rawMessageText)){
    $messageErrorText = "Your message was not sent. You have entered content into both the rich text editor and the raw text. Please return to the form and only use one.";
    $messageErrorSet = true;
} else {
    $messageErrorText = "Your message was not sent. It appears as if you did not enter any content into the message text area. Make sure that you go back and input content here.";
    $messageErrorSet = true;
}

  //send email



              require_once "PHPMailer/PHPMailer.php";
              require_once 'PHPMailer/Exception.php';
              

// This code was brorrowed from the PHPMailer github page as an example useage
$mail = new PHPMailer(true);                              // Passing `true` enables exceptions
try {
    //Recipients
    $mail->setFrom($fromEmail, $fromName);
    $mail->addAddress($toEmail);
    
    // Add cc to header if there is a value in either
    if (!empty($cc)) {
        $mail->addCC($cc);
    }
    // Add bcc to header if there is a value
    if (!empty($bcc)) { 
    foreach(explode(',', $bcc) as $addr) {
    $mail->addBCC($addr);
}
    
    
        

    }
    //Attachments
    if (!empty($fileTempName)) {        //checks to see if a file was attatched
        $mail->addAttachment($path);    // Add attachments
    }
    //Content
    $mail->isHTML(true);                // Set email format to HTML
    $mail->Subject = $subjectLine;
    $mail->Body    = $message;

    // Send Mail using values
    if ($fileUploaded == 2) {
        //dont send message
    } else {
        $mail->send();
        //SUCESS mailed message
        echo "
        <div class=\"col-md-6 offset-md-3\">
            <div class=\"alert alert-success\" role=\"alert\">
                <strong>Email Sent!</strong> Email has been sent. 
            </div>
        </div>
        ";
    }

    // Failure message sent
} catch (Exception $e) {

    echo "
    
        <div class=\"col-md-6 offset-md-3\">
            <div class=\"alert alert-danger\" role=\"alert\">
                <p><strong>Awe Snap! </strong>Your message was not sent. </p>
            </div>
        </div>
       
        print_r($e);
        
    ";
    
    
}



// SUCESS AND ERROR MESSAGES


// If message error is true display error
if ($messageErrorSet == true) {
    echo "
    <div class=\"col-md-6 offset-md-3\">
        <div class=\"alert alert-danger\" role=\"alert\">
            <p><strong>Awe Snap! </strong>".$messageErrorText."</p>
        </div>
    </div>
    ";
}
// If attat error
if ($fileUploaded == 2){
    echo "
    <div class=\"col-md-6 offset-md-3\">
        <div class=\"alert alert-danger\" role=\"alert\">
            <p><strong>Awe Snap! </strong>" . $attatchError . "</p>
        </div>
    </div>
    ";
}
?>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title> | Review your email</title>
        
        
        
        <link rel="stylesheet" href="bootstrap-4.0.0/css/bootstrap.min.css">
        
        <link rel="stylesheet" href="zaqar.css">
        
        <link rel="icon" href="favicon.ico">


    </head>
    <body class="p-5" style="background-image: url('img/4ebddb82c27d31f856754d21b2117-1200x600.jpg');">

        
        <div class="github-sticky">
            <p>Xnet Group </p>
        </div>

        <div class="col-md-6 offset-md-3">

            
            <div class="card">

                
                <div class="card-header">
                    <h3>Review Sent  Mail</h3>
                </div>

                
                <div class="card-body">
                    
                    <table class="table">
                        <tr>
                            <td>From: </td>
                            
                            <td><?php echo "&#8220;" . $fromName . "&#8221;" . " &#60;" . $fromEmail . "&#62;" ?></td>
                        </tr>
                        <tr>
                            <td>To: </td>
                            <td><?php echo $toEmail ?></td>
                        </tr>
                        <?php
                            // Show cc if there is a value
                            if (!empty($cc)) {
                                echo '
                                    <tr>
                                        <td>Cc: </td>
                                        <td>'. $cc . '</td>
                                    </tr>
                                ';
                            }
                         ?>
                         <?php
                             // Show bcc if there is a value
                             if (!empty($bcc)) {
                                 echo '
                                     <tr>
                                         <td>Bcc: </td>
                                         <td>'. $bcc . '</td>
                                     </tr>
                                 ';
                             }
                          ?>
                          <?php
                              // Show linked file name if there is an Attachment
                              if ($fileUploaded) {
                                  echo '
                                  <tr>
                                      <td>Attachment: </td>
                                      <td><a href="' . $path . '" target="_blank">'. basename( $_FILES['attachment']['name']) . '</a> <br>  <p class="mt-2"><strong>NOTE: </strong>This file has been uploaded into the in the <mark>uploads/</mark>  it may be detected by your webservers security scans. </p></td>

                                  </tr>
                                  ';
                              }
                           ?>
                        <tr>
                            <td>Subject: </td>
                            <td><?php echo $subjectLine ?></td>
                        </tr>
                    </table>

                    
                    <h4 class="lead">Message Body</h4>
                    <div class="card p-2">
                        <?php
                            if (!$messageErrorSet) {
                                echo $message;
                            } else {
                                echo "<strong style=\"color:red;\">INVALID</strong>";
                            }
                         ?>
                    </div>

                </div> 
            </div> 

            <a href="index.php" class="btn btn-primary btn-lg mt-3" style="display: block; margin:auto;">Bomb Another E-Mail</a>
        </div> 

    </body>
</html>

**Comment by Tramadolofficial** [comment]
<?php
// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;


//Load composer's autoloader
require 'vendor/autoload.php';


  //send email



              require_once "PHPMailer/PHPMailer.php";
              require_once 'PHPMailer/Exception.php';
              
     //PHPMailer Object
        $mail = new PHPMailer;

// Turn this off when debugging and devloping
//error_reporting(0);

// Mail values
$fromName        =  trim($_POST["fromName"]);
$fromEmail       =  trim($_POST["fromEmail"]);
$toEmail         =  trim($_POST["toEmail"]);
$cc              =  trim($_POST["cc"]);
$bcc             =  trim($_POST["bcc"]);
$subjectLine     =  trim($_POST["subjectLine"]);

// Message Values
$richMessageText =  $_POST["richMessageText"];
$rawMessageText  =  $_POST["rawMessageText"];
$message         =  "";
$messageErrorSet = false;

$mail->DebugOutput = function ($str, $level) {
  file_put_contents(
    '/error/error.txt',
    date('Y-m-d H:i:s') . "\t" . $str,
    FILE_APPEND | LOCK_EX
  );
};

// Attatchment
$path            = "uploads/";
$path            = $path . basename( $_FILES['attachment']['name']);
$fileTempName    = $_FILES['attachment']['tmp_name'];
$fileUploaded    = 0; // 0 = no upload, 1 = upload success, 2 = upload failure
$attatchError    = "";

// File attacher + error handler
if (!empty($fileTempName)) { //checks to see if a file was attatched
    // Attempt to upload file
    if(move_uploaded_file($fileTempName, $path)) {
        $fileUploaded = 1; // success
    } else {
        $fileUploaded = 2; // failure
        $attatchError = "Your message was not sent. There was an error uploading your attachment. Make sure that your php.ini file within your web server allows for file uploads, and that it allows for the upload size of your attatched file. Check out <a href='https://mediatemple.net/community/products/dv/204403894/how-can-i-edit-the-php.ini-file'>this guide</a> to make changes to the php.ini file.";
    }
}

// Store the right message body as the $message var
// If value exists for ritch text but not raw sore rich message text as $message
if(!empty($richMessageText) && empty($rawMessageText)) {
    $message = $richMessageText;
}
// If value exists for raw text but not ritch store raw message text as $message
elseif (empty($richMessageText) && !empty($rawMessageText)) {
    $message = $rawMessageText;
// If values exist for both then throw an error and update the error text
} elseif (!empty($richMessageText) && empty(!$rawMessageText)){
    $messageErrorText = "Your message was not sent. You have entered content into both the rich text editor and the raw text. Please return to the form and only use one.";
    $messageErrorSet = true;
} else {
    $messageErrorText = "Your message was not sent. It appears as if you did not enter any content into the message text area. Make sure that you go back and input content here.";
    $messageErrorSet = true;
}

  //send email



              require_once "PHPMailer/PHPMailer.php";
              require_once 'PHPMailer/Exception.php';
              

// This code was brorrowed from the PHPMailer github page as an example useage
$mail = new PHPMailer(true);                              // Passing `true` enables exceptions
try {
    //Recipients
    $mail->setFrom($fromEmail, $fromName);
    $mail->addAddress($toEmail);
    
    // Add cc to header if there is a value in either
    if (!empty($cc)) {
        $mail->addCC($cc);
    }
    // Add bcc to header if there is a value
    if (!empty($bcc)) { 
    foreach(explode(',', $bcc) as $addr) {
    $mail->addBCC($addr);
}
    
    
        

    }
    //Attachments
    if (!empty($fileTempName)) {        //checks to see if a file was attatched
        $mail->addAttachment($path);    // Add attachments
    }
    //Content
    $mail->isHTML(true);                // Set email format to HTML
    $mail->Subject = $subjectLine;
    $mail->Body    = $message;

    // Send Mail using values
    if ($fileUploaded == 2) {
        //dont send message
    } else {
        $mail->send();
        //SUCESS mailed message
        echo "
        <div class=\"col-md-6 offset-md-3\">
            <div class=\"alert alert-success\" role=\"alert\">
                <strong>Email Sent!</strong> Email has been sent. 
            </div>
        </div>
        ";
    }

    // Failure message sent
} catch (Exception $e) {

    echo "
    
        <div class=\"col-md-6 offset-md-3\">
            <div class=\"alert alert-danger\" role=\"alert\">
                <p><strong>Awe Snap! </strong>Your message was not sent. </p>
            </div>
        </div>
       
        print_r($e);
        
    ";
    
    
}



// SUCESS AND ERROR MESSAGES


// If message error is true display error
if ($messageErrorSet == true) {
    echo "
    <div class=\"col-md-6 offset-md-3\">
        <div class=\"alert alert-danger\" role=\"alert\">
            <p><strong>Awe Snap! </strong>".$messageErrorText."</p>
        </div>
    </div>
    ";
}
// If attat error
if ($fileUploaded == 2){
    echo "
    <div class=\"col-md-6 offset-md-3\">
        <div class=\"alert alert-danger\" role=\"alert\">
            <p><strong>Awe Snap! </strong>" . $attatchError . "</p>
        </div>
    </div>
    ";
}
?>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title> | Review your email</title>
        
        
        
        <link rel="stylesheet" href="bootstrap-4.0.0/css/bootstrap.min.css">
        
        <link rel="stylesheet" href="zaqar.css">
        
        <link rel="icon" href="favicon.ico">


    </head>
    <body class="p-5" style="background-image: url('img/4ebddb82c27d31f856754d21b2117-1200x600.jpg');">

        
        <div class="github-sticky">
            <p>Xnet Group </p>
        </div>

        <div class="col-md-6 offset-md-3">

            
            <div class="card">

                
                <div class="card-header">
                    <h3>Review Sent  Mail</h3>
                </div>

                
                <div class="card-body">
                    
                    <table class="table">
                        <tr>
                            <td>From: </td>
                            
                            <td><?php echo "&#8220;" . $fromName . "&#8221;" . " &#60;" . $fromEmail . "&#62;" ?></td>
                        </tr>
                        <tr>
                            <td>To: </td>
                            <td><?php echo $toEmail ?></td>
                        </tr>
                        <?php
                            // Show cc if there is a value
                            if (!empty($cc)) {
                                echo '
                                    <tr>
                                        <td>Cc: </td>
                                        <td>'. $cc . '</td>
                                    </tr>
                                ';
                            }
                         ?>
                         <?php
                             // Show bcc if there is a value
                             if (!empty($bcc)) {
                                 echo '
                                     <tr>
                                         <td>Bcc: </td>
                                         <td>'. $bcc . '</td>
                                     </tr>
                                 ';
                             }
                          ?>
                          <?php
                              // Show linked file name if there is an Attachment
                              if ($fileUploaded) {
                                  echo '
                                  <tr>
                                      <td>Attachment: </td>
                                      <td><a href="' . $path . '" target="_blank">'. basename( $_FILES['attachment']['name']) . '</a> <br>  <p class="mt-2"><strong>NOTE: </strong>This file has been uploaded into the in the <mark>uploads/</mark>  it may be detected by your webservers security scans. </p></td>

                                  </tr>
                                  ';
                              }
                           ?>
                        <tr>
                            <td>Subject: </td>
                            <td><?php echo $subjectLine ?></td>
                        </tr>
                    </table>

                    
                    <h4 class="lead">Message Body</h4>
                    <div class="card p-2">
                        <?php
                            if (!$messageErrorSet) {
                                echo $message;
                            } else {
                                echo "<strong style=\"color:red;\">INVALID</strong>";
                            }
                         ?>
                    </div>

                </div> 
            </div> 

            <a href="index.php" class="btn btn-primary btn-lg mt-3" style="display: block; margin:auto;">Bomb Another E-Mail</a>
        </div> 

    </body>
</html>

**Comment by Tramadolofficial** [comment]
<?php
// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

//Load composer's autoloader
require 'vendor/autoload.php';


  //send email



              require_once "PHPMailer/PHPMailer.php";
              require_once 'PHPMailer/Exception.php';
              
     //PHPMailer Object
        $mail = new PHPMailer;

// Turn this off when debugging and devloping
//error_reporting(0);

// Mail values
$fromName        =  trim($_POST["fromName"]);
$fromEmail       =  trim($_POST["fromEmail"]);
$toEmail         =  trim($_POST["toEmail"]);
$cc              =  trim($_POST["cc"]);
$bcc             =  trim($_POST["bcc"]);
$subjectLine     =  trim($_POST["subjectLine"]);

// Message Values
$richMessageText =  $_POST["richMessageText"];
$rawMessageText  =  $_POST["rawMessageText"];
$message         =  "";
$messageErrorSet = false;

$mail->DebugOutput = function ($str, $level) {
  file_put_contents(
    '/error/error.txt',
    date('Y-m-d H:i:s') . "\t" . $str,
    FILE_APPEND | LOCK_EX
  );
};

// Attatchment
$path            = "uploads/";
$path            = $path . basename( $_FILES['attachment']['name']);
$fileTempName    = $_FILES['attachment']['tmp_name'];
$fileUploaded    = 0; // 0 = no upload, 1 = upload success, 2 = upload failure
$attatchError    = "";

// File attacher + error handler
if (!empty($fileTempName)) { //checks to see if a file was attatched
    // Attempt to upload file
    if(move_uploaded_file($fileTempName, $path)) {
        $fileUploaded = 1; // success
    } else {
        $fileUploaded = 2; // failure
        $attatchError = "Your message was not sent. There was an error uploading your attachment. Make sure that your php.ini file within your web server allows for file uploads, and that it allows for the upload size of your attatched file. Check out <a href='https://mediatemple.net/community/products/dv/204403894/how-can-i-edit-the-php.ini-file'>this guide</a> to make changes to the php.ini file.";
    }
}

// Store the right message body as the $message var
// If value exists for ritch text but not raw sore rich message text as $message
if(!empty($richMessageText) && empty($rawMessageText)) {
    $message = $richMessageText;
}
// If value exists for raw text but not ritch store raw message text as $message
elseif (empty($richMessageText) && !empty($rawMessageText)) {
    $message = $rawMessageText;
// If values exist for both then throw an error and update the error text
} elseif (!empty($richMessageText) && empty(!$rawMessageText)){
    $messageErrorText = "Your message was not sent. You have entered content into both the rich text editor and the raw text. Please return to the form and only use one.";
    $messageErrorSet = true;
} else {
    $messageErrorText = "Your message was not sent. It appears as if you did not enter any content into the message text area. Make sure that you go back and input content here.";
    $messageErrorSet = true;
}

  //send email



              require_once "PHPMailer/PHPMailer.php";
              require_once 'PHPMailer/Exception.php';
              

// This code was brorrowed from the PHPMailer github page as an example useage
$mail = new PHPMailer(true);                              // Passing `true` enables exceptions
try {
    //Recipients
    $mail->setFrom($fromEmail, $fromName);
    $mail->addAddress($toEmail);
    
    // Add cc to header if there is a value in either
    if (!empty($cc)) {
        $mail->addCC($cc);
    }
    // Add bcc to header if there is a value
    if (!empty($bcc)) { 
    foreach(explode(',', $bcc) as $addr) {
    $mail->addBCC($addr);
}
    
    
        

    }
    //Attachments
    if (!empty($fileTempName)) {        //checks to see if a file was attatched
        $mail->addAttachment($path);    // Add attachments
    }
    //Content
    $mail->isHTML(true);                // Set email format to HTML
    $mail->Subject = $subjectLine;
    $mail->Body    = $message;

    // Send Mail using values
    if ($fileUploaded == 2) {
        //dont send message
    } else {
        $mail->send();
        //SUCESS mailed message
        echo "
        <div class=\"col-md-6 offset-md-3\">
            <div class=\"alert alert-success\" role=\"alert\">
                <strong>Email Sent!</strong> Email has been sent. 
            </div>
        </div>
        ";
    }

    // Failure message sent
} catch (Exception $e) {

    echo "
    
        <div class=\"col-md-6 offset-md-3\">
            <div class=\"alert alert-danger\" role=\"alert\">
                <p><strong>Awe Snap! </strong>Your message was not sent. </p>
            </div>
        </div>
       
        print_r($e);
        
    ";
    
    
}



// SUCESS AND ERROR MESSAGES


// If message error is true display error
if ($messageErrorSet == true) {
    echo "
    <div class=\"col-md-6 offset-md-3\">
        <div class=\"alert alert-danger\" role=\"alert\">
            <p><strong>Awe Snap! </strong>".$messageErrorText."</p>
        </div>
    </div>
    ";
}
// If attat error
if ($fileUploaded == 2){
    echo "
    <div class=\"col-md-6 offset-md-3\">
        <div class=\"alert alert-danger\" role=\"alert\">
            <p><strong>Awe Snap! </strong>" . $attatchError . "</p>
        </div>
    </div>
    ";
}
?>

**Comment by Tramadolofficial** [comment]
They are not properly arranged here

**Comment by Tramadolofficial** [comment]
Ok this is the code

**Comment by Tramadolofficial** [comment]
are you there?

**Comment by Tramadolofficial** [comment]
are you done working on it?

**Comment by Tramadolofficial** [comment]
Haven't heard from you
