### ISSUE TITLE
Retrieve MessageID from PHPMailer server response

### ISSUE THREAD

**Issue by Avics-Jasper** [PHPMailer/PHPMailer#2650]
Hi,

I'm trying to retrieve the MessageID of all emails that are being sent. This way, we can confirm that the message has been delivered or opened by the recipient using our mailing partner's Webhook system.

Right now, this is my code:

```php
<?php
require_once('mailing/vendor/autoload.php');

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

$mail = new PHPMailer(true);
$mail->SMTPDebug = true;
$mail->isSMTP();
$mail->Host       = 'smtp.mailersend.net';
$mail->SMTPAuth   = true;
$mail->Username   = 'user@domain.com';
$mail->Password   = 'pwd';
$mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
$mail->Port       = 587;
$mail->SMTPSecure = "tls";

//Recipients
$mail->setFrom('sender@domain.com', 'User name');
$mail->addAddress('recipient@domain.com', 'Recipient name');

//Content
$mail->isHTML(true);
$mail->Subject = 'subject';
$mail->Body    = '<h1>HTML body</h1>';
$mail->AltBody = 'Txt body';

$mail->send();
```

When I run the code mentioned above with SMTPDebug on, it returns this (only pasted the last part of the response):

```
2022-03-16 19:58:36 CLIENT -> SERVER: 
2022-03-16 19:58:36 CLIENT -> SERVER: .
2022-03-16 19:58:37 SMTP INBOUND: "250 Message queued as 6232416d01542d6b321d000d"
2022-03-16 19:58:37 SERVER -> CLIENT: 250 Message queued as 6232416d01542d6b321d000d
2022-03-16 19:58:37 CLIENT -> SERVER: QUIT
2022-03-16 19:58:37 SMTP INBOUND: "221 Bye"
2022-03-16 19:58:37 SERVER -> CLIENT: 221 Bye
```

As you can see, the ID that I need is next to `250 Message queued as`.

Is there a way to extract this ID from the debug logging? Or even better: is there a native way to extract this from the output?

**Comment by Synchro** [comment]
That ID is not part of the SMTP spec, so it's implemented inconsistently. There is already code in PHPMailer to extract such IDs from numerous different mail servers using [these patterns](https://github.com/PHPMailer/PHPMailer/blob/master/src/SMTP.php#L174). After calling `send()` successfully on your PHPMailer instance, you can call `$mail->getSMTPInstance()->getLastTransactionID()` to get that ID.

However, none of those patterns match the output used on the server you're accessing.

There are two ways around that:
1. Create a subclass of the SMTP class, add the pattern, and inject an instance of it into PHPMailer using the `setSMTPInstance` method.
2. Create a PR with the pattern and get it added to PHPMailer.

A suitable pattern would be:

            'you mail server type' => '/[\d]{3} Message queued as (.*)^/',

Do you know what kind of mail server this is? It will usually say so at the beginning of debug output, just after it connects.
