### ISSUE TITLE
tls error :(

### ISSUE THREAD

**Issue by jezdimsivefiatu** [PHPMailer/PHPMailer#2652]
2022-03-19 04:37:18 SERVER -> CLIENT: 220 mail.inovation.tk ESMTP Postfix (@@DISTRO@@)
2022-03-19 04:37:18 CLIENT -> SERVER: EHLO theprosperous.tk
2022-03-19 04:37:18 SERVER -> CLIENT: 250-mail.inovation.tk250-PIPELINING250-SIZE 52428800250-VRFY250-ETRN250-STARTTLS250-AUTH PLAIN LOGIN250-AUTH=PLAIN LOGIN250-ENHANCEDSTATUSCODES250-8BITMIME250-DSN250-SMTPUTF8250 CHUNKING
2022-03-19 04:37:18 CLIENT -> SERVER: STARTTLS
2022-03-19 04:37:18 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
SMTP Error: Could not connect to SMTP host.
2022-03-19 04:37:18 CLIENT -> SERVER: QUIT
2022-03-19 04:37:18
2022-03-19 04:37:18
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

//Config : 

```
<?php
require_once "vendor/autoload.php"; //PHPMailer Object 
use PHPMailer\PHPMailer\PHPMailer;

if (isset($_GET['email'])) {
  if (isset($_GET['remove_token'])) {
    $email = $_GET['email'];
    $remove_token = $_GET['remove_token'];
    $mail = new PHPMailer;
    $mail->SMTPDebug = 2;
    $mail->isSMTP();
    $mail->Host = "localhost";
    $mail->SMTPSecure = 'tls';
    $mail->SMTPAuth = true;
    $mail->Port = 25;
    $mail->Username     = "info@theprosperous.tk";
    $mail->Password = "password";
    $mail->From = "info@theprosperous.tk";
    $mail->FromName = "The Prosperous";
    $mail->addAddress($email);
    $mail->isHTML(true);
    $mail->Subject = "You are now subscribed!";
    $mail->Body = 'Large HTML CODE'
```

//I have multiple domains on postfix //with roundcube is all alright and working, anyone have a advice how to fix it ?

**Comment by BinRoq** [comment]
-

**Comment by Synchro** [comment]
Using TLS to localhost generally won't work because the certificate name will not match. Disable TLS with ‘SMTPSecure = false‘, and also set ‘SMTPAutoTLS = false‘.

**Comment by jezdimsivefiatu** [comment]
i want tls lol

**Comment by Synchro** [comment]
Well hard luck; you can't have TLS to localhost, and there's no advantage in having it anyway.

**Comment by jezdimsivefiatu** [comment]
so i wonder how it works roundcube mail lol

**Comment by Synchro** [comment]
Simple - it doesn't use TLS.
