### ISSUE TITLE
Is it possible to see with this library all the emails in the inbox with their replies?

### ISSUE THREAD

**Issue by alexv96** [PHPMailer/PHPMailer#2655]
Hello query, I'm trying to implement the mailbox on my platform, without resorting to google apis and microsoft graph as customers we have generally occupy cheap hosting, then I'm looking for a solution on how to implement it on the platform and I wondered if this library could be given that, or from what I've read only serves to send mails, greetings.

**Comment by Synchro** [comment]
Indeed PHPMailer is only concerned with sending, not mailboxes. You need to look at IMAP classes for handling that. See the PHPMailer gmail example for a very minimal demo of using IMAP.
