### ISSUE TITLE
Can't connect smtp.gmail.com on VPS provider, but seems to pass troubleshooting tests?

### ISSUE THREAD

**Issue by F4T4LERROR** [PHPMailer/PHPMailer#2659]
Hello All,

I wrote a very basic test mail script to send mail via our Google Workspace account dedicated for outgoing website emails.  The account has two-factor authentication enabled and I've specified a custom app password.  I've included that code below, however when I copy that file and the PHPMailer library to other hosts, the test runs successfully.  **I'm only having trouble on our new VPS host.**

The host I'm using is called LiquidWeb, where we're using a VPSHosting package running Linux CentOS7 64-bit with 2GB of RAM and fully managed via Plesk. Getting the following error when executing the script from this provider:
```
2022-03-31 06:34:59 Connection: opening to ssl://smtp.gmail.com:465, timeout=300, options=array()
2022-03-31 06:35:00 Connection failed. Error #2: stream_socket_client(): unable to connect to ssl://smtp.gmail.com:465 (Network is unreachable)
2022-03-31 06:35:00 SMTP ERROR: Failed to connect to server: Network is unreachable (101)
```

### I attempted to follow the troubleshooting steps listed [here](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting), and got the following output:

**telnet smtp.gmail.com 587**
Note: This appears to work correctly, but I've never gotten PHPMailer to work using smtp.gmail.com over port 587 with STARTTLS
```
Trying 142.251.6.109...
Connected to smtp.gmail.com.
Escape character is '^]'.
220 smtp.gmail.com ESMTP e18-20020a5d85d2000000b00649254a855fsm11711452ios.26 - gsmtp
```

**telnet smtp.gmail.com 465**
Note: The troubleshooting guide states "_If it produces no output or something that doesn't start with 220, then either your server is down or you've got the wrong server._", and as you can see this doesn't start with 220 and gmail doesn't work with 587 (at least for me, on any server).  **IS this my issue??**
```
Trying 172.253.112.108...
Connected to smtp.gmail.com.
Escape character is '^]'.
```

**openssl s_client -crlf -starttls smtp -CAfile /etc/ssl/ca-cert.pem -connect smtp.gmail.com:587**
When I run this I cannot file the ca-cert.pem file.  The only entity in ssl directory is another directory called "certs" which has only .crt files within.  The command still executes and the end result is:
```
Start Time: 1648710243
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
250 SMTPUTF8
```

**netstat -tunlp**
note: I changed the numeric server IP address to "server_ip" in the below output and it appears 465 is listening, though I don't know if this is enough to rule that out.
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 server_ip:80         0.0.0.0:*               LISTEN      6618/nginx: worker
tcp        0      0 0.0.0.0:8880            0.0.0.0:*               LISTEN      7526/sw-cp-server:
tcp        0      0 0.0.0.0:465             0.0.0.0:*               LISTEN      83389/master
tcp        0      0 server_ip:53         0.0.0.0:*               LISTEN      823/named
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      823/named
tcp        0      0 127.0.0.1:3030          0.0.0.0:*               LISTEN      66416/grafana-serve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      54854/sshd
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      61250/smtpd
tcp        0      0 127.0.0.1:953           0.0.0.0:*               LISTEN      823/named
tcp        0      0 127.0.0.1:12346         0.0.0.0:*               LISTEN      83389/master
tcp        0      0 server_ip:443        0.0.0.0:*               LISTEN      6618/nginx: worker
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      7526/sw-cp-server:
tcp        0      0 0.0.0.0:4190            0.0.0.0:*               LISTEN      74662/dovecot
tcp        0      0 127.0.0.1:12768         0.0.0.0:*               LISTEN      22146/psa-pc-remote
tcp        0      0 0.0.0.0:993             0.0.0.0:*               LISTEN      74662/dovecot
tcp        0      0 0.0.0.0:995             0.0.0.0:*               LISTEN      74662/dovecot
tcp        0      0 0.0.0.0:587             0.0.0.0:*               LISTEN      83389/master
tcp        0      0 0.0.0.0:110             0.0.0.0:*               LISTEN      74662/dovecot
tcp        0      0 0.0.0.0:143             0.0.0.0:*               LISTEN      74662/dovecot
```

I also disabled the server's firewall and verified with the host no AV software is running.  Does anyone have any suggestions with regards to what I can try next?  I've also opened a ticket with the host and am hoping they can assist as well, but thought perhaps someone here might have a suggestion I could try.  

### Test code I'm using:
```
session_start();
date_default_timezone_set('America/Chicago');

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

require 'php/phpmailer/6.6/Exception.php';
require 'php/phpmailer/6.6/PHPMailer.php';
require 'php/phpmailer/6.6/SMTP.php';

$m = new PHPMailer();
$m->SMTPSecure    = PHPMailer::ENCRYPTION_SMTPS;
$m->SMTPDebug    = 4;
$m->isSMTP();
$m->SMTPAutoTLS  = false;
$m->Host 		= 'smtp.gmail.com';
$m->Port       	        = 465;
$m->SMTPAuth   	= true;	
$m->Username 	= 'email';
$m->Password 	= 'password';
$m->Subject 	        = 'Direct test message';
$m->AltBody 	        = 'To view the message, please use an HTML compatible email viewer!';
$m->addAddress('my_email_address', 'Contact Form Submission');
$m->addReplyTo('reply_to_address', 'My Name');
$m->setFrom('google_workspace_address', 'Contact Form');
$m->msgHTML('Test message');

if($m->Send()) {
	echo 'Message sent!'; 
} else {
	echo 'Mailer Error: ' . $m->ErrorInfo; 
}

```

**Comment by Synchro** [comment]
It's most likely that your hosting provider is blocking outbound SMTP.

telnet to port 465 won't do anything (well, it might connect and then do nothing) because it is not a plain-text protocol on that port. You need to use openssl to test that: `openssl s_client -connect smtp.gmail.com:465`. Netstat only tells you what ports are listening on your own machine, not at the remote end, and your firewall will usually have no bearing on that either. Sanity check – you need to run these commands from your server, not your local machine. It's also possible that your PHP instance uses a different openssl library than the system one, and it may have a different location for the CA cert bundle, however, I don't think you have a CA cert problem because your connection is not getting as far as that.

**Comment by F4T4LERROR** [comment]
>Netstat only tells you what ports are listening on your own machine, not at the remote end, and your firewall will usually have no bearing on that either. Sanity check – you need to run these commands from your server, not your local machine.

First off, thanks a lot of replying so quickly, I really appreciate it.  I am not an expert with troubleshooting Linux, SMTP, or using SSH, so please bear with me.  

Regarding my telnet tests, I'm SSH-ing into the remote server using putty, then running the commands from there.  I am assuming that means I'm running those tests on the remote end, but again, I don't typically interact with SSH.  If this sounds like I'm doing something incorrectly, please let me know.  I had to install telnet while connected via SSH to run that command, using `yum install telnet telnet-server -y` , so hopefully I did that correctly.

> telnet to port 465 won't do anything (well, it might connect and then do nothing) because it is not a plain-text protocol on that port. You need to use openssl to test that: `openssl s_client -connect smtp.gmail.com:465`.

I ran this, and got the following output.  I've truncated it significantly, but didn't see anything in the output that indicated an error:

**openssl s_client -connect smtp.gmail.com:465**
```
CONNECTED(00000003)
depth=3 C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA
verify return:1
depth=2 C = US, O = Google Trust Services LLC, CN = GTS Root R1
verify return:1
depth=1 C = US, O = Google Trust Services LLC, CN = GTS CA 1C3
verify return:1
depth=0 CN = smtp.gmail.com
verify return:1

Start Time: 1648714771
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
220 smtp.gmail.com ESMTP u11-20020a056e02080b00b002c87d5830cbsm10321825ilm.40 - gsmtp
```

If there is anything you think I can try please let me know.  Like you said, I've tried checking this with Google as well, but of course they see nothing since nothing is leaving the remote server where I'm running the script.

**Comment by F4T4LERROR** [comment]
First off, thank you again @Synchro for your help.

Heard back from the host and I'm honestly not even sure what this means, but here is their reply: `I think I found the issue when I saw how csf didn't have 465 allowed through TCP`.

They fixed that, and it's now working.  So for anyone using **LiquidWeb hosting**, please make a note of this.
