### ISSUE TITLE
Sending mail with variable

### ISSUE THREAD

**Issue by toolost9** [PHPMailer/PHPMailer#2670]
# Problem description
Hi guys, i'm new with PHPMailer and i'm trying to send an email to a variable. The mailing list changes according to the customer, the fixed part would be the "to" and the variable part "customer1", "customer2" etc.
# Code to reproduce
    $toCustomer1 = "customer1@gmail.com";
    $mail->addAddress('$to' . 'customer1');
# Debug output
![image](https://user-images.githubusercontent.com/87522813/163705372-3e1def4d-868e-4a87-84d8-3d028113e785.png)

Any suggestion?

**Comment by XL-2000** [comment]
This is a rookie mistake, remove the single quotes in your second line around $to, since this will return the name of the variable, where as without the quotes, simply using $to will pass the value.
