### ISSUE TITLE
Characters Format - New Line

### ISSUE THREAD

**Issue by malmalakh** [PHPMailer/PHPMailer#2671]
Hello everyone,
I am testing PHPMailer.. I noticed when sending a simple text email, the code will not accept multi paragraphs, it combines all paragraphs as one.  And when sending message as html, it is not accepting multi code lines, the sending should combine all codes in one
I am storing all sent messages using mysql database using UTF-8 character set.

Please advise.

**Comment by Synchro** [comment]
I can't tell what you're doing wrong without seeing your code.

**Comment by malmalakh** [comment]
Hellow @Synchro .. my code is as follows

    // PHPMailer classes into the global namespace
    use PHPMailer\PHPMailer\PHPMailer; 
    use PHPMailer\PHPMailer\Exception;
    // Base files 
    require 'PHPMailer/src/Exception.php';
    require 'PHPMailer/src/PHPMailer.php';
    require 'PHPMailer/src/SMTP.php';

                $mail = new PHPMailer();                              
                $mail->isSMTP(); // using SMTP protocol                                     
                $mail->Host = 'mail.myserver.com'; // SMTP host as gmail 
                $mail->SMTPAuth = true;  // enable smtp authentication                             
                $mail->Username = 'myemail@myserver.com';  // sender gmail host              
                $mail->Password = 'password'; // sender gmail host password                          
                $mail->SMTPSecure = 'ssl';  // for encrypted connection                           
                $mail->Port = 465;   // port for SMTP     
                $mail->setFrom('myemail@myserver.com', $h5["name"]); // sender's email and name
                $mail->addAddress($row_outmsg["tonum"], $row_outmsg["tonum"]);  // receiver's email and name
                $mail->CharSet = 'UTF-8';
                $mail->isHTML(true);
                $mail->Subject = $row_outmsg["subject"];
                $mail->Body    = $row_outmsg["body"];
                $mail->AltBody = $row_outmsg["body"];
                $mail->send();

appreciating your help

**Comment by Synchro** [comment]
Well, you're asking it to use a dual-format plain-text + HTML, but then using the same content for both, which makes little sense. If you just want a simple plain-text message (which will preserve line breaks), do this:

    $mail->isHTML(false);
    $mail->Body = $row_outmsg["body"];

HTML does not preserve line breaks or other white space. If you have a plain-text body you want to keep line breaks in, do this:

    $mail->Body = nl2br($row_outmsg["body"]);
    $mail->AltBody = $row_outmsg["body"];

however, tis is really a bit pointless - it's much more sensible to use a simple plain-text message in the first place than saying the same thing twice.
