### ISSUE TITLE
Using NON-SSL connection

### ISSUE THREAD

**Issue by malmalakh** [PHPMailer/PHPMailer#2673]
hello ..
in case that i do not want to use the ssl connection (port 465), and I what to use a non secure connection over port 26..
what to disable ?

                $mail->isSMTP(true);
                $mail->SMTPSecure = 'ssl';                      
                $mail->Port = 465;

**Comment by Synchro** [comment]
Like this:

    $mail->isSMTP(true);
    $mail->SMTPSecure = false;
    $mail->Port = 26;
    $mail->SMTPAutoTLS = false;

though you should not be using an unencrypted connection to anything but localhost.
