### ISSUE TITLE
Correct way to set a bounce email address

### ISSUE THREAD

**Issue by ppetree** [PHPMailer/PHPMailer#2676]
I have a rather old but very robust bounce handler that I need to implement on a new project and while I'm at it I'm getting away from writing my own mail() handlers and migrating to PHPMailer. So far, so good.

The issue I have is setting the correct address for bouncebacks. I've looked through a number of closed issues on here to find a something that tells me how to set the email address but nada.

The sender is "donotreply@domain.com" and if someone were to reply to this it just gives a standard "this address is unmonitored if you want to blah blah blah..." but for the actual bounces (hard and soft) I have the address "bounce@domain.com" which is piped to my script.

This was my last attempt ([based on an issue from 2018](https://github.com/PHPMailer/PHPMailer/issues/1561)):
```
  $email->SetFrom($email_from, 'Domain Invitation');
  $email->Sender = "bounce@domain.com";
  $email->AddAddress( $email_to ); 
```

How do I set this correctly?

Thanks!

**Comment by Synchro** [comment]
This is the right way:

    $email->Sender = "bounce@domain.com";

The from address only affects the From in the "From" header, and `addAddress` adds addresses to the To header that will also be used by SMTP `RCPT TO` commands, along with CC and BCC addresses. If you set `SMTPDebug = 2` in your script, you will see the whole SMTP conversation, which should include a line near the start that says something like:

    MAIL FROM <bounce@domain.com>

You may also see errors or comments from the server in response to that. Bounces will go to that address, assuming that your mail server accepts it (for example gmail will not if it's not the same as your account address / username).

**Comment by ppetree** [comment]
That's what I did but it's not showing up anywhere in the received email headers and when I use a known bad address I get nothing back.

**Comment by Synchro** [comment]
Please show your SMTP transcript so we can see what's happening.

**Comment by ppetree** [comment]
Got it! Thanks!
