### ISSUE TITLE
DKIM signature fail

### ISSUE THREAD

**Issue by redsector72** [PHPMailer/PHPMailer#2680]
Hello there,
I'm trying to implement DKIM in PHPmailer version 6.6.0 under php 7.4.29

I use port25.com to test for the signature and I always receive DKIM check: fail 
"The message was signed and the signature or signatures were  acceptable to the ADMD, but they failed the verification test(s)."

Google dkim works for the domain, so I'm confident I understand how to set up DNS records and perform the test.

I've created a dns record to match with an additional public key I've created on the server using this php script:

`$privatekeyfile = 'private.key.auto';
$publickeyfile  = 'public.key.auto';
$passphrase     = 'passphrase';

// Prepare files
if (file_exists($privatekeyfile)) { unlink($privatekeyfile); }
if (file_exists($publickeyfile))  { unlink($publickeyfile); }
// Generate 2048-bit RSA key with an SHA256 digest
$pk = openssl_pkey_new(
    [
        'digest_alg' => 'sha256',
        'private_key_bits' => 2048,
        'private_key_type' => OPENSSL_KEYTYPE_RSA,
    ]
);
// Export and Save private key
openssl_pkey_export_to_file($pk, $privatekeyfile, $passphrase);
// Save public key
$publickey = openssl_pkey_get_details($pk);
$publickey = $publickey['key'];
file_put_contents($publickeyfile, $publickey);`

and I use this configuration to send a test email:

`#!/usr/bin/php
<?php 
			$corpo = "test";
			require("Exception.php");
            require("PHPMailer.php");
            require("SMTP.php");
      		use PHPMailer\PHPMailer\PHPMailer;
            use PHPMailer\PHPMailer\SMTP;
            use PHPMailer\PHPMailer\Exception;
            $mail = new PHPMailer();
            $mail->SMTPAuth = true; // turn on SMTP authentication
            $mail->SMTPSecure = "tls";
            $mail->Host = "smtp.gmail.com";
            $mail->Port = 587;
            $mail->Username = "username"; // SMTP username
            $mail->Password = "password"; // SMTP password
            $mail->From = "user@mydomain.com";
            $mail->FromName = "Mailer";
            $mail->AddAddress( "check-auth@verifier.port25.com" );
            $mail->CharSet = "UTF-8";
            $mail->Encoding = "base64";
            $mail->DKIM_domain = "mydomain.com";
            $mail->DKIM_private = "fullpathto/private.key.auto"; // Make sure to protect the key from being publicly accessible!
            $mail->DKIM_selector = "local";//name of record is local._domainkey
            $mail->DKIM_passphrase = "passphrase";
            $mail->DKIM_identity = $mail->From;
			$mail->DKIM_copyHeaderFields = false;
            $mail->Subject = "Test";
            $mail->Body = $corpo;
            if (!$mail->send()) {
			    echo 'Mailer Error: '. $mail->ErrorInfo;
			} else {
			    echo 'Message sent!\n';
			}
            ?>`

If there is a simpler setup to test I'll can give it a try.

**Comment by XL-2000** [comment]
what does your debug log state?

**Comment by redsector72** [comment]
I see regular transaction.

DKIM part is:                    Content-Type: text/plain; charset=UTF-8
                   	                  Content-Transfer-Encoding: base64
                   	                  DKIM-Signature: v=1; d=mydomain.com; s=local;
                   	                   a=rsa-sha256; q=dns/txt; t=1652387405; c=relaxed/simple;
                   	                   h=Date:From:Message-ID:X-Mailer:MIME-Version:Content-Type:To:Subject;
                   	                   i=senderemailaddress;
                   	                   bh=X4ZuiCEyLJE2QK+UgrjOIqnS1iuSdVqOOHAFEeDRZZ8=;
                   	                   b=sOIxU6yxL4ZihQOHrjmmJN81Z7avWu8ikejGx6jbXqXKgAL/mz0pg4aESdkQ5LNzFmNE1GY/E
                   	                   VNfZ35Qiu3ijI9b9siEWO1CMwuhTyrMQbePJxK7JxxAsjmPaF72t+JSVDROBbkyYnPOlmAbc3
                   	                   6KYxhzyYMRAsMwl3qSYgFM8ci8uox1l35Uh7gp/jPDQhGDrCAiCCzIU7KkO6HJFvY0IqAb+3d
                   	                   0aUT3oUfFLN3Tcf670IHGHpd6hXWgzUVZc+FTbh1IZXeBASHa0k5J7ho49CLjEkNXQGtbAR+d
                   	                   s4WZm5u7Bww8pEd9Ax6LCzY1ZH08pt03xDFa3pEIvTETsUGl+A==

**Comment by redsector72** [comment]
Ok, I found the issue with me.
If google is already configured to create a DKIM, you don't need to add DKIM parameters when you use PHPMailer.
the server calculates DKIM for you.

hope this help people following old tutorials and guides.

**Comment by Synchro** [comment]
Glad you figured something out! Yes, this is the preferred way of doing DKIM signing. It is also possible for a message to contain multiple DKIM signatures signing at different levels.
