### ISSUE TITLE
Problem with XOAuth2 (provider field)

### ISSUE THREAD

**Issue by DamienBuchet** [PHPMailer/PHPMailer#2697]
Hi, 

I've tried to implement the XOAuth2, as Google disabled the usual way. I followed all the steps, got the cliend id, the client secret and the refresh token. Then I used the template given in gmail_xoauth.phps and completed it with my own information and pathes. 
Once done, I tried it, and got a 500 Internal Server Error. I added JS alerts to see where it was blocking, and it looks like it's a problem when calling the $provider variable, as I get the first alert, but not the second one.

![image](https://user-images.githubusercontent.com/60095199/173039354-22bc3d6e-ddb7-42ab-bdc8-90f0b5f17c5b.png)

I also tried an alert with the $clientId var, and it showed correctly, as the first alert, then the 500 error, but when I replace it with the $provider var, I get the 500 error directly, so I think it comes from this, but I don't see what's wrong, all packages are correctly called, the Phpmailer ones and the League OAuth one.

https://user-images.githubusercontent.com/60095199/173040253-a90146fb-612e-4301-be08-d064e867c299.mp4

The SMTPDebug is enabled, but doesn't show anything, so I don't really know what to do.

If someone has an idea, thanks by advance

**Comment by Synchro** [comment]
Any time you get a 500 error, details will appear in your web server's error log, so go look in there. By default, you can't simply `echo` an object, so even trying to display it will cause a fatal error. Mixing JS and PHP while debugging is a recipe for disaster, so stick to just PHP, use things like `var_dump($provider)` instead of a JS alert.

I've assumed that you have the necessary `use` statements in your script.

**Comment by DamienBuchet** [comment]
I totally forgot about the var_dump, but it looks correct, I don't know how it's supposed to be.

![image](https://user-images.githubusercontent.com/60095199/173044771-f413f760-84c2-4f5a-9911-7e14991afb03.png)

I guess I'll have to wait, logs aren't available within the next day on the host.

**Comment by Synchro** [comment]
That does look ok. If you can't get to logs, you might be able to force visibility of errors by setting:

    ini_set('display_errors', true);

**but remember to remove that once you've tracked down the problem!**

**Comment by DamienBuchet** [comment]
Well... It didn't display anything, so I guess I'll really have to wait.
Thank you for what you already did to help me, I'll come back tomorrow if the logs didn't help

**Comment by DamienBuchet** [comment]
I forgot it was the week-end. 
Anyway, I think I'll have to give up, I looked at the logs, and there is still no errors.
