### ISSUE TITLE
PHPMailer on Outlook Exchange

### ISSUE THREAD

**Issue by robertomz** [PHPMailer/PHPMailer#2699]
Hi, when I send emails to outlook exchange (a mail of a company: example@example.com) it sents correctly, but when I send a mail to @gmail or @outlook / @hotmail it's sent to spam, but I don't want it to be deliveried on spam. How can I fix that?

**Comment by Synchro** [comment]
Please [read the docs on this](https://github.com/PHPMailer/PHPMailer/wiki/Improving-delivery-rates,-avoiding-spam-filters).
