### ISSUE TITLE
SMTP connect() failed.

### ISSUE THREAD

**Issue by nileshcool** [PHPMailer/PHPMailer#270]
Hi,
I am using the gmail smtp server (smtp.gmail.com), with my gmail (free) username and password but each time I am getting the following error

```
2014-08-31 17:13:00 Connection: opening to ssl://smtp.gmail.com:465, t=10, opt=array ( )
2014-08-31 17:13:00 SMTP ERROR: Failed to connect to server: Permission denied (13)
2014-08-31 17:13:00 SMTP connect() failed. array(1) { [0]=> string(46) "SMTP connect() failed.
```

I have tried with both tls (port=587), and ssl (port=465), but got the same error

**Comment by Ali3nKill3r** [comment]
Try to remove the $mail->IsSMTP();
It's already declared in $mail->SMTPAuth=true;

**Comment by Synchro** [comment]
No, don't do that. Setting `SMTPAuth = true` will do nothing unless you also call `isSMTP()`.

**Comment by cony69** [comment]
It's an incredibly, but I remove $mail->IsSMTP(); and all work fine

**Comment by Synchro** [comment]
This is like saying that a broken light bulb works perfectly when it's switched off.

**Comment by DonaldKellett** [comment]
Just a simple question relating to SMTP and PHPMailer.

Is it true that if you comment out the ```$mail->isSMTP()``` function, PHPMailer ignores all the ```$mail->Username```, ```$mail->Password``` authentication and just defaults to using the PHP ```mail()``` function?

I currently use GoDaddy as my website hosting platform (which I believe is what someone else was referring to when he/she said "s***** hosting company") and when I tried to use Gmail SMTP authentication via PHPMailer, it did not work (apparently the SMTP request never left the GoDaddy servers).  Once I commented out the ```$mail->isSMTP()```, sending emails was like 10x faster and the problem disappeared.  **However, I also noticed that the ```$mail->SMTPDebug``` no longer worked and that I could finally alter the "From" email address which I could not alter when using ```$mail->isSMTP()```.**

**Comment by Synchro** [comment]
Yes, and it's all entirely logical.

SMTP-related settings are only applicable when using SMTP, including `Username`, `Password`, `Host`, `Port`, `SMTPAuth`, `SMTPSecure`, `SMTPDebug` and others.

GoDaddy blocks outbound mail connections (to gmail and everywhere else), so you need to use GoDaddy's own mail servers, which may include localhost. Obviously your gmail login attempts will not work on GoDaddy's servers, though it's a good way of telling them your gmail password if your'e not paying attention. This is also why you should not disable SSL verification.

It's faster because you're not trying to connect to somewhere that's blocked, not because it's a faster sending mechanism. As I said, the most effective way to send is via SMTP to localhost (or a nearby smarthost), which avoids all the issues you've mentioned.

The from address limitation is a gmail restriction, nothing to do with PHPMailer nor GoDaddy.

**Comment by 21accel** [comment]
Hi, I have an error for connecting to SMTP...
The error said 

> 2016-03-16 03:06:40 Connection: opening to ssl://smtp.gmail.com:465, timeout=600, options=array ( )
>  2016-03-16 03:06:40 SMTP ERROR: Failed to connect to server: (0)
> 2016-03-16 03:06:40 SMTP connect() failed.

I've tried with this setting using Codeigniter : 
`$config['useragent']        = 'PHPMailer';              // Mail engine switcher: 'CodeIgniter' or 'PHPMailer'
$config['protocol']         = 'smtp';                   // 'mail', 'sendmail', or 'smtp'
$config['mailpath']         = '/usr/sbin/sendmail';
$config['smtp_host']        = 'smtp.gmail.com';
$config['smtp_user']        = 'my_email@gmail.com';
$config['smtp_pass']        = 'my_password';
$config['smtp_port']        = 465;
$config['smtp_timeout']     = 600;                        // (in seconds)
$config['smtp_crypto']      = 'ssl';                       // '' or 'tls' or 'ssl'
$config['smtp_debug']       = 3;                        // PHPMailer's SMTP debug info level: 0 = off, 1 = commands, 2 = commands and data, 3 = as 2 plus connection status, 4 = low level data output.
$config['wordwrap']         = true;
$config['wrapchars']        = 76;
$config['mailtype']         = 'html';                   // 'text' or 'html'
$config['charset']          = null;                     // 'UTF-8', 'ISO-8859-15', ...; NULL (preferable) means config_item('charset'), i.e. the character set of the site.
$config['validate']         = true;
$config['priority']         = 4;                        // 1, 2, 3, 4, 5; on PHPMailer useragent NULL is a possible option, it means that X-priority header is not set at all, see https://github.com/PHPMailer/PHPMailer/issues/449
$config['crlf']             = "\n";                     // "\r\n" or "\n" or "\r"
$config['newline']          = "\n";                     // "\r\n" or "\n" or "\r"
$config['bcc_batch_mode']   = false;
$config['bcc_batch_size']   = 200;
$config['encoding']         = '8bit';                   // The body encoding. For CodeIgniter: '8bit' or '7bit'. For PHPMailer: '8bit', '7bit', 'binary', 'base64', or 'quoted-printable'.`

And I'm using local server using XAMPP...
How can i fix the error?

**Comment by Synchro** [comment]
@21accel You need to use the latest PHPMailer, and [read the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting). Plese don't hijack unrelated tickets.

**Comment by 21accel** [comment]
Yes I had use the latest version that I just downloaded some days ago...
And thanks after I read the troubleshooting guide, now I have a conclusion for my problem, that I don't have any access right into gmail SMTP.
By the way, what do you mean with "Please don't hijack unrelated tickets"?

**Comment by Synchro** [comment]
You can't have been using a recent version - all releases in the last year or so include a link to the troubleshooting guide in error output, and yours did not show that.

This was hijacking because you posted your query on a closed ticket that had a completely different symptom than you were seeing.

**Comment by dickrex** [comment]
From the http-side, how can I get som informaion from SMTPDebug? I have PHPMailer on a standrad web-hotel without consol access, just ftp.

**Comment by Synchro** [comment]
If you set SMTPDebug to anything > 0 (2 is probably what you need), it will output an SMTP transcript to standard output, so it will just appear as normal page output. It's worth disabling any redirects after sending or you may not get to see the output.

**Comment by dickrex** [comment]
OK, but if I would like to have the output to a variable like I can do with `$error = $mail->ErrorInfo;` is it possible?

**Comment by Synchro** [comment]
Sure, just inject your own callable for the `Debugoutput` property, like this:

    $mail->Debugoutput = function($str, $level) {$GLOBALS['error'] .= $str;};

That way all the debug output will accumulate in the `$errors` global variable for you to do what you like with.

**Comment by dickrex** [comment]
Thank You!!!

**Comment by dickrex** [comment]
But.... To get the Deugoutput, shall I do like this:
`$error = $mail->Debugoutput = function($str, $level) {$GLOBALS['error'] .= $str;};`

**Comment by dickrex** [comment]
OK, forget the last post...

**Comment by dickrex** [comment]
At most I get this:
```
Connection: opening to mailout.one.com:25, timeout=300, options=array (
)SMTP ERROR: Failed to connect to server: Connection timed out (110)SMTP connect()
```
And this must be before the password and everyting else that can go wrong I suppose?

**Comment by Synchro** [comment]
Just looks like your mail server is dead:

```
telnet mailout.one.com 25
Trying 10.246.18.1...
telnet: connect to address 10.246.18.1: Connection refused
telnet: Unable to connect to remote host
```

**Comment by Synchro** [comment]
Actually that IP address is not internet-accessible because it's in [the RFC1918 range](https://tools.ietf.org/html/rfc1918#section-3), so it's impossible to connect to it unless you're on the same netrwork already.

**Comment by dickrex** [comment]
Well, I have my web space at their (one.com) server, so I am at the same network in some way even if I have my own domain.

**Comment by Synchro** [comment]
Does your server have a `10.x.x.x` ip address? Either way, it's refusing connections or timing out, so it's not looking good for your mail server. I suggest you contact their support, read their docs.

**Comment by dickrex** [comment]
one.com is a big actor, and I don't thing they kan have a mail-server down for several hours. But I've sent a mail to their support.

**Comment by dickrex** [comment]
But it was like you said :-) The server was down and now it's working just fine.

**Comment by Hagenzone** [comment]
Hi dickrex,
I've been searching and trying now for several hours to find the correct settings for PHPMailer on one.com but nothing seems to work. Both, mail and website run on one.com so I think its just a matter of misconfiguration.

Also I dont get any error if it comes to $mail->send (not even with SMTPDebug = 4, no timeout just loading and waiting).

I would really appreciate it if you could post your settings or help otherwise. Thank you!

**Comment by Msz900** [comment]
Hi @Hagenzone  Please use the below config, as it works for me, and i am also using it.

require 'PHPMailer-master/class.phpmailer.php';
require 'PHPMailer-master/PHPMailerAutoload.php';


$mail = new PHPMailer();
    $mail->isSMTP(true);     // telling the class to use SMTP
    $mail->SMTPOptions = array(
        'ssl' => array(
            'verify_peer' => false,
            'verify_peer_name' => false,
            'allow_self_signed' => true
        )
    );


    $mail->SMTPSecure = 'tls';
    $mail->Host = 'tls://smtp.gmail.com';
    $mail->Port = 587;
    $mail->SMTPAuth = true;
    $mail->Username = "your Email address"; // SMTP username
    $mail->Password = "your Email password here"; // SMTP password
                                    // TCP port to connect to
  // $mail->SMTPDebug = 1;
    $mail->setFrom('your Email address');
    $mail->AddAddress("user/client email address");

$mail->Subject = "some text, what ever you want";
$mail->Body = "Email info/message here. ";
$mail->WordWrap = 70;

    $mail->Send();

Hope it will help you....

**Comment by Hagenzone** [comment]
Hi @Msz900,

thank you for posting your code. Unfortunately this code does not work. I suppose its because your configuration is for gmail, not for one.com which seems to need a slightly more different config.

But thank you anyway!

**Comment by Synchro** [comment]
@Msz900 Do not post incorrect, obsolete, unsafe code. It doens't help anyone, especially when it doesn't address the problems of the original poster.

**Comment by StudioJunkyard** [comment]
@Synchro excatly, GitHub isn't StackOverflow, lol.

**Comment by Hagenzone** [comment]
The one.com-support helped me out. Here is the configuration that worked for me:

smtp: true
smtpauth: true
host: send.one.com
username, password,
smtpsecure: ssl,
port: 465

Hope this one can help somebody.

**Comment by darkworks** [comment]
for gmail you must turn on access to 3rd party apps

https://www.google.com/settings/security/lesssecureapps    // turn it on

**Comment by Synchro** [comment]
@darkworks don't post incorrect and irrelevant comments please. It is not a requirement to enable less secure apps in gmail, and the OP isn't using gmail anyway.

**Comment by AmaliDeveloper** [comment]
You can get the solution for send mail using phpmailer Here [Link](https://youtu.be/Edx7pPcPfs8)

**Comment by mqasim1990** [comment]
I just found the way to Get out this Bug ....... just go to your google account that you put in 

$mail->username = 'email';

Login to the account and just go to Google Less Secure apps and turn in ON

I tried a lot of method but could not find any helpful method but finally i got above one which i mentioned .....

**Comment by Synchro** [comment]
@mqasim1990 - that "fix" is mentioned and described in detail above, and is covered in the PHPMailer docs, which are linked to from the error message you got. Don't hijack year-old tickets to add duplicate and misleading information.
