### ISSUE TITLE
addOrEnqueueAnAddress  setFrom

### ISSUE THREAD

**Issue by ZhangChengLin** [PHPMailer/PHPMailer#2718]
https://github.com/PHPMailer/PHPMailer/blob/9400f305a898f194caff5521f64e5dfa926626f3/src/PHPMailer.php#L1068
https://github.com/PHPMailer/PHPMailer/blob/2f4b684353d89b232e392bf6270261bbc52f315f/src/PHPMailer.php#L1289

https://github.com/PHPMailer/PHPMailer/blob/9400f305a898f194caff5521f64e5dfa926626f3/src/PHPMailer.php#L1076

---
addAddress
addCC
addBCC
addReplyTo
addOrEnqueueAnAddress 
---
setFrom
---

Why is addOrEnqueueAnAddress not applied to setFrom function? And only use 'to', 'cc', 'bcc', 'ReplyTo' these four.
The logic inside is a bit close.

**Comment by XL-2000** [comment]
Since TO, CC, BCC, REPLYTO allows multiple entries, whereas FROM only one entry
