### ISSUE TITLE
problemi invio di email a SMTP con PHPMailer OVH

### ISSUE THREAD

**Issue by AndrewTech21** [PHPMailer/PHPMailer#2730]
# Problem description
Salve, ho un gestionale scritto in php. Non riesco a configurare l'indirizzo email booking@onebus.it per l'invio dei messaggi di posta.
# Code to reproduce
SMTP -> get_lines(): $str is "220 ex4.mail.ovh.net Microsoft ESMTP MAIL Service ready at Tue, 12 Jul 2022 09:28:42 +0200 "
SMTP -> get_lines(): $data is "220 ex4.mail.ovh.net Microsoft ESMTP MAIL Service ready at Tue, 12 Jul 2022 09:28:42 +0200 "
SMTP -> FROM SERVER:220 ex4.mail.ovh.net Microsoft ESMTP MAIL Service ready at Tue, 12 Jul 2022 09:28:42 +0200
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "250-ex4.mail.ovh.net Hello [18.159.203.68] "
SMTP -> get_lines(): $data is "250-ex4.mail.ovh.net Hello [18.159.203.68] "
SMTP -> get_lines(): $data was "250-ex4.mail.ovh.net Hello [18.159.203.68] "
SMTP -> get_lines(): $str is "250-SIZE 104857600 "
SMTP -> get_lines(): $data is "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 "
SMTP -> get_lines(): $data was "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 "
SMTP -> get_lines(): $str is "250-PIPELINING "
SMTP -> get_lines(): $data is "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING "
SMTP -> get_lines(): $data was "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING "
SMTP -> get_lines(): $str is "250-DSN "
SMTP -> get_lines(): $data is "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING 250-DSN "
SMTP -> get_lines(): $data was "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING 250-DSN "
SMTP -> get_lines(): $str is "250-ENHANCEDSTATUSCODES "
SMTP -> get_lines(): $data is "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING 250-DSN 250-ENHANCEDSTATUSCODES "
SMTP -> get_lines(): $data was "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING 250-DSN 250-ENHANCEDSTATUSCODES "
SMTP -> get_lines(): $str is "250-STARTTLS "
SMTP -> get_lines(): $data is "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING 250-DSN 250-ENHANCEDSTATUSCODES 250-STARTTLS "
SMTP -> get_lines(): $data was "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING 250-DSN 250-ENHANCEDSTATUSCODES 250-STARTTLS "
SMTP -> get_lines(): $str is "250-AUTH GSSAPI NTLM "
SMTP -> get_lines(): $data is "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING 250-DSN 250-ENHANCEDSTATUSCODES 250-STARTTLS 250-AUTH GSSAPI NTLM "
SMTP -> get_lines(): $data was "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING 250-DSN 250-ENHANCEDSTATUSCODES 250-STARTTLS 250-AUTH GSSAPI NTLM "
SMTP -> get_lines(): $str is "250-8BITMIME "
SMTP -> get_lines(): $data is "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING 250-DSN 250-ENHANCEDSTATUSCODES 250-STARTTLS 250-AUTH GSSAPI NTLM 250-8BITMIME "
SMTP -> get_lines(): $data was "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING 250-DSN 250-ENHANCEDSTATUSCODES 250-STARTTLS 250-AUTH GSSAPI NTLM 250-8BITMIME "
SMTP -> get_lines(): $str is "250-BINARYMIME "
SMTP -> get_lines(): $data is "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING 250-DSN 250-ENHANCEDSTATUSCODES 250-STARTTLS 250-AUTH GSSAPI NTLM 250-8BITMIME 250-BINARYMIME "
SMTP -> get_lines(): $data was "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING 250-DSN 250-ENHANCEDSTATUSCODES 250-STARTTLS 250-AUTH GSSAPI NTLM 250-8BITMIME 250-BINARYMIME "
SMTP -> get_lines(): $str is "250 CHUNKING "
SMTP -> get_lines(): $data is "250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING 250-DSN 250-ENHANCEDSTATUSCODES 250-STARTTLS 250-AUTH GSSAPI NTLM 250-8BITMIME 250-BINARYMIME 250 CHUNKING "
SMTP -> FROM SERVER: 250-ex4.mail.ovh.net Hello [18.159.203.68] 250-SIZE 104857600 250-PIPELINING 250-DSN 250-ENHANCEDSTATUSCODES 250-STARTTLS 250-AUTH GSSAPI NTLM 250-8BITMIME 250-BINARYMIME 250 CHUNKING
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "504 5.7.4 Unrecognized authentication type "
SMTP -> get_lines(): $data is "504 5.7.4 Unrecognized authentication type "
SMTP -> ERROR: AUTH not accepted from server: 504 5.7.4 Unrecognized authentication type
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "250 2.0.0 Resetting "
SMTP -> get_lines(): $data is "250 2.0.0 Resetting "
SMTP -> FROM SERVER:250 2.0.0 Resetting
SMTP Error: Could not authenticate. bool(false)
# Debug output

**Comment by Synchro** [comment]
This server only offers NTLM or GSSAPI authentication methods. PHPMailer doesn't support either of them. You'll need to use a different client library or a different server.
