### ISSUE TITLE
auth method doc is misleading

### ISSUE THREAD

**Issue by lkppo** [PHPMailer/PHPMailer#2732]
# Problem description

The docstring say in PHPMAILER.php:

```php
    /**
     * SMTP auth type.
     * Options are CRAM-MD5, LOGIN, PLAIN, XOAUTH2, attempted in that order if not specified.
     *
     * @var string
     */
    public $AuthType = '';
```

This is ambiguous. I had previously understood that each authentication method is tried, in the order indicated, until one of them works. But after reading the code of SMTP->authenticate(), it is clear that among the methods announced by the server, the best one also supported by PHPMailer is chosen and tried only once.

I was tricked by a lying server which claims to support CRAM-MD5 but refuses authentication with this method.

# Solution?

Can you correct the documentation to disambiguate it please?

**Comment by Synchro** [comment]
How about "If not specified, the first one from that list that the server supports will be selected."?

**Comment by lkppo** [comment]
All right!
