### ISSUE TITLE
Unable to receive email after change of IP address in Cacti monitoring server.

### ISSUE THREAD

**Issue by cutehameed** [PHPMailer/PHPMailer#2737]
I am using Cacti as monitoring server and it was working fine unless i changed server IP. After change of ip, it stop sending emails. It is giving error

![cacti error](https://user-images.githubusercontent.com/34865973/180835952-39e83e54-9fa6-4feb-9598-d2219f3d3ea5.JPG)

**Comment by Synchro** [comment]
Please follow the link it gives you and do what it says to diagnose this issue as this has come up many times before. It's most likely that your hosting provider is blocking outbound SMTP from your new IP.

**Comment by cutehameed** [comment]
@Synchro Apologies, i posted here after getting no results. I am newbie so kindly guide me.

**Comment by Synchro** [comment]
https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#smtp-error-could-not-connect-to-smtp-host
