### ISSUE TITLE
DKIM signature has a wrong body hash when sending via a specific SMTP server

### ISSUE THREAD

**Issue by fdumortier** [PHPMailer/PHPMailer#2739]
# Problem description
When sending DKIM-signed mails through a specific SMTP server from my OVH hoster with my credentials, the received body hash is wrong, while it's OK with 2 other SMTP servers. I checked it via Gmail and mail-tester.com. Any idea what causes this?
# Code to reproduce
Too risky to give you this possibility here. Send me a personal message and I'll provide you with the URL to reproduce this issue.
# Debug output
Gmail : "body hash did not verify"

**Comment by Synchro** [comment]
The most likely explanation is that the mail server you're sending through is altering your message, which will cause the DKIM validation to fail. I suggest you grab an exact copy of the message as sent from debug output (or by calling `getSentMIMEMessage()`), and then compare it (use a diff tool) to what turns up at the receiving end.

**Comment by fdumortier** [comment]
> The most likely explanation is that the mail server you're sending through is altering your message, which will cause the DKIM validation to fail. I suggest you grab an exact copy of the message as sent from debug output (or by calling `getSentMIMEMessage()`), and then compare it (use a diff tool) to what turns up at the receiving end.

Indeed, may thanks: the SMTP server I used to send the mail altered the "Message-ID: " value. I don't know why.

I read discussion #1965 and understand that including "Message-ID:" to the DKIM fields is "the recommended set straight from RFC6376."

But why not let it to the programmer like me to choose which fields to include/remove?

**Comment by Synchro** [comment]
It would be a nice-to-have feature, but at this point I don't really want to touch the DKIM code! DKIM is really difficult to test, which is why I set about writing a DKIM validator, but that has stalled as I was finding that too difficult, even though it's got quite a long way. PRs welcome!
