### ISSUE TITLE
Servidor SMTP Webmail

### ISSUE THREAD

**Issue by rudybatero95** [PHPMailer/PHPMailer#2744]
2022-08-08 22:25:15 SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Host desconocido. (0) 2022-08-08 22:25:15 SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting 

function enviarEmail($email, $nombre, $asunto, $cuerpo){
		
		require_once '../PHPMailer/PHPMailerAutoload.php';
		
		$mail = new PHPMailer();

		$mail->SMTPDebug = 2;
		$mail->isSMTP();
		$mail->Host = 'smtp.ayrmulti.com'; //Modificar
		$mail->SMTPAuth = true;
		$mail->Username = 'sopor@ayrmulti.com'; //Modificar
		$mail->Password = 'clave'; //Modificar
		$mail->SMTPSecure = 'tls'; //Modificar
		$mail->Port = 465; //Modificar
		
		
		$mail->setFrom('sopor@ayrmulti.com','Juan Perez'); //Modificar
		$mail->addAddress($email, $nombre);
		
		$mail->IsHTML(true);
		$mail->Subject = $asunto;
		$mail->Body    = $cuerpo;
		
		if($mail->send())
		return true;
		else
		return false;
	}

help me!

**Comment by Synchro** [comment]
It means either the hostname for your mail server is wrong, or you have a DNS problem. Fix those and PHPMailer will be able to work.
