### ISSUE TITLE
Is there a PHPMailer forum available?

### ISSUE THREAD

**Issue by PolishedStaple** [PHPMailer/PHPMailer#275]
I realize this is the place for posting bugs, but I wasn't able to find any official PHPMailer forums online to ask questions about implementation, etc.   Please advise.

Thanks!

**Comment by timlab55** [comment]
I'm very new to phpmailer and to php so please bear with me.   I would like to phpmailer to send me a message that someone has just left a comment for me, but also, I would like to have phpmailer send them a message thanking them for sending it.  How can I do that?
