### ISSUE TITLE
BCCs are not being sent.

### ISSUE THREAD

**Issue by dqhendricks** [PHPMailer/PHPMailer#2758]
# Description

I have set up PHPMailer and can send emails successfully. When I use addBCC( $address ) or addCustomHeader( 'BCC', $address ) however, nothing gets sent to the BCC address. The message still reaches the To address. I am using a linux server, with PHP 5.6.

# Code to reproduce

Using SMTP and HTML:

$mail->addBCC( 'dustin@dustinhendricks.com' );

OR

$mail->addCustomHeader( 'BCC', 'dustin@dustinhendricks.com' );

# Debug output

No errors or debug output.

**Comment by XL-2000** [comment]
So many questions....
Which version of PHPMailer are you using?
Why in the worlds name are you using an ancient PHP version? You should absolutely upgrade!
Why are you using "addCustomHeader" to add a BCC header? This is absolutely WRONG...
Where is the rest of your code?
What does the log or debug say?

**Comment by dqhendricks** [comment]
- I am using the latest version of PHPMailer-master downloaded yesterday.
- I read that this version is compatible with PHP 5.6. Is there something else I should check to see if it is compatible?
- I am using 5.6 due to some legacy code on the same server. I wish I could upgrade.
- addCustomerHeader() was a suggestion from stackoverflow, where someone claimed addBCC() only works for Win32 SMTP, and that they had to use a work around using addCustomHeader() to get BCC to work with PHPMailer. I tried both and neither worked however.
- There were no errors or debug info. The mail sent. Just no BCCs added.
- Here's my code. It's pretty much copy paste from this repository's examples. $bcc is an array of plain email addresses and I verified that the addBCC() is in fact being reached when the code runs with a proper address.

```
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require_once 'PHPMailer-master/src/Exception.php';
require_once 'PHPMailer-master/src/PHPMailer.php';
require_once 'PHPMailer-master/src/SMTP.php';

class EmailManager {
	protected $from_email = 'no-reply@dustinhendricks.com';
	protected $from_password = '[mypassword]';
	protected $from_name = 'Writing Group App';
	
	function emailHTML( $to, $subject, $message, $reply_to = null, $bcc = null ) {
		$this->email( true, $to, $subject, $message, $reply_to, $bcc );
	}
	
	function emailText( $to, $subject, $message, $reply_to = null, $bcc = null ) {
		$this->email( false, $to, $subject, $message, $reply_to, $bcc );
	}
	
	function email( $isHTML, $to, $subject, $message, $reply_to = null, $bcc = null ) {
		try {
			// server settings
			$mail = new PHPMailer( true );
			$mail->isSMTP();
			$mail->Host = 'writinggroupapp.com';
			$mail->SMTPAuth = true;
			$mail->Username = $this->from_email;
			$mail->Password = $this->from_password;
			$mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
			$mail->Port = 465;
			// to/from settings
			$mail->setFrom( $this->from_email, $this->from_name );
			$mail->addAddress( $to );
			if ( $reply_to ) $mail->addReplyTo( $reply_to );
			//if ( $bcc ) $mail->addCustomHeader( 'BCC', implode( ',', $bcc ) ); // work around doesn't seem to work either
			if ( $bcc ) {
				foreach ( $bcc as $address ) {
					$mail->addBCC( $address ); // apparently only works on win32 mail servers?
				}
			}
			// attachments
			//$mail->addAttachment('/var/tmp/file.tar.gz');
			// content
			if ( $isHTML ) $mail->isHTML( true );
			$mail->Subject = $subject;
			$mail->Body = $message;
			if ( $isHTML ) $mail->AltBody = strip_tags( $message );
			// send
			$mail->send();
		} catch ( Exception $e ) {
			echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
		}
	}
}
```

**Comment by dqhendricks** [comment]
Seems to be an issue with the mail server and not PHPMailer. Sorry for the trouble.
