### ISSUE TITLE
The term composer not recognised 

### ISSUE THREAD

**Issue by vikdaguru** [PHPMailer/PHPMailer#2768]
composer : The term 'composer' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again.      
At line:1 char:1
+ composer require phpmailer/phpmailer
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (composer:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Synchro** [comment]
You need to [install composer](https://getcomposer.org) first, just like you install PHP to run PHPMailer too. It's nothing to do with PHPMailer otherwise.
