### ISSUE TITLE
Add gmail XOAUTH2  with access_token

### ISSUE THREAD

**Issue by suzukazehr** [PHPMailer/PHPMailer#2769]
Can you add feature Gmail XOAUTH2 with access token?
Access token expires in short time, it is safe, while refresh token (OAuth2 provider) is not so, it is not suitable for some environments.
Thank!

**Comment by Synchro** [comment]
This is entirely up to the OAuth library that you use with PHPMailer, not PHPMailer itself. Consult their documentation for how to use a refresh token to get an access token. PHPMailer will just use what you give it.
