### ISSUE TITLE
Documentation improvement: How to use Microsoft OAuth with PHPMailer 

### ISSUE THREAD

**Issue by Synchro** [PHPMailer/PHPMailer#2788]
Now that Microsoft have discontinued their support for simple username/password authentication, many people are trying to switch to use XOAUTH2 instead. Unfortunately this appears to be a complete nightmare, as discussed in #2747, #2116, #1959, #1901, etc. A wiki article detailing how to set it up would be much appreciated by many of PHPMailer's users.

**Comment by greew** [comment]
Here we go!

https://github.com/PHPMailer/PHPMailer/wiki/Microsoft-Azure-and-XOAUTH2-setup-guide

I'll have a Pull Request in a few minutes with additions for get_oauth_token.php and an azure example file :)

**Comment by Synchro** [comment]
Thanks for all your effort on this. Hopefully Microsoft will make it easier and more reliable at some point, but until then...

**Comment by wayzz1992** [comment]
Anyone else having problems with GuzzleHttp :
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://login.microsoftonline.com/tenant-id/oauth2/v2.0/token

I am trying to get the RefreshToken on my Local machine before testing on a dev environment. Using same code as the example.
$token = $provider->getAccessToken(
        'authorization_code',
        [
            'code' => $_GET['code']
        ]
    );
