### ISSUE TITLE
Duplicate "to" header

### ISSUE THREAD

**Issue by xsuchy09** [PHPMailer/PHPMailer#2789]
# Problem description
PhpMailer is sending emails with duplicate "to" header when email is sent just with bcc without to.

# Code to reproduce
Any use of PhpMailer used with bcc without to. PhpMailer 5.x, 6.x.

# Debug output
In source of emails is "to" header twice.
Response from gmail:
```
*HIDDEN*: host aspmx.l.google.com[142.250.27.27] said:
This duplicate header is against RFC and gmail is rejecting them:
550-5.7.1 [*HIDDEN*] Our system has detected that this message is not
RFC 550-5.7.1 5322 compliant: duplicate headers. To reduce the amount of
spam sent 550-5.7.1 to Gmail, this message has been blocked. Please review
550 5.7.1 RFC 5322 specifications for more information.
```
# Solution
Don't add "to" header in createHeader function when to is not set (undisclosed-recipients:; is added). Add this in mailSend function. Or reject this email with error that receiver has to be set.

**Comment by Synchro** [comment]
Oh, ignore that, I see what you mean...

**Comment by lysfanger** [comment]
When testing with version 6.6 I can not reproduce, could you add more steps to reproduce?

**Comment by xsuchy09** [comment]
I just test it and it was fixed in 6.6.4 with https://github.com/PHPMailer/PHPMailer/blob/v6.6.4/src/PHPMailer.php#L1899-L1901. Any previous version is affected. So it can be closed.

**Comment by xsuchy09** [comment]
PhpMailer 5.x:
```
To:
Subject: Test Subject
Date: Thu, 6 Oct 2022 21:09:58 +0200
To: undisclosed-recipients:;
From: Root User <root@localhost>
Bcc: ..., ...
Message-ID: <03a779c9d35163851813089b9bf723c9@d4fea30da43c>
X-Mailer: PHPMailer 5.2.28 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/plain; charset=iso-8859-1

Test Body


```

**Comment by Synchro** [comment]
5.x is no longer supported, so I'm not worried about that!

**Comment by xsuchy09** [comment]
Yes. Just for info, it was fixed by condition in createHeader:
v5: https://github.com/PHPMailer/PHPMailer/blob/acba50393dd03da69a50226c139722af8b153b11/class.phpmailer.php#L2060-L2066
v6: https://github.com/PHPMailer/PHPMailer/blob/a94fdebaea6bd17f51be0c2373ab80d3d681269b/src/PHPMailer.php#L2602-L2612

So undisclosed-recipients:; is not set in createHeader of v6.
