### ISSUE TITLE
Unable to update Sender property

### ISSUE THREAD

**Issue by soggycity** [PHPMailer/PHPMailer#2797]
The Sender property cannot be changed after it is set with the initial setFrom method. The code only updates Sender if it is empty.

The use case is opening a connection with a SMTP server and sending multiple emails using different sending accounts (user and password combinations) on the same server without having to close the connection. 

Currently, the Reply-to gets the value from the first account and then cannot be updated for subsequent emails sent using different accounts. As a result, the only way to send emails from different accounts on the same server is to destroy the PHPMailer object and create a new one which means the connection to the SMTP server has to be closed and then opened again.

**Comment by Synchro** [comment]
What's stopping you from setting the public `Sender` property? It's only set from `setFrom()` if you have not set it yourself. IME, most mail servers will not let you do this anyway, because the envelope from is usually tied to the authenticated user.
