### ISSUE TITLE
org.uk

### ISSUE THREAD

**Issue by Knutsford** [PHPMailer/PHPMailer#2819]
**This is very urgent**

$mail->send() is returning false for a valid .org.uk Email address

if(!$mail->send()) {
	 echo 'file was not sent.';
			  
} else {
	 echo 'file has been sent.';
}

It doesn't complain if I change it to an invalid co.uk address so I am guessing it just needs .org.uk adding to the valid list of email ending

Please let me know when it is amended

P Whittaker
info@knutsford-software.co.uk

**Comment by XL-2000** [comment]
Seriously? There is no code to to analyze, no debug logging to check, how in the world would you think your question will be answered if you do not provide proper code and log?

**Comment by Synchro** [comment]
No there is no problem with the validation of `.org.uk` addresses, and PHPMailer does not contain a list of valid TLDs to add anything to. Your problem is elsewhere. I suggest you enable debug output so you can see what your mail server is saying about it.

**Comment by Knutsford** [comment]
Ok I will ask him to check the Mailserver errors then.  Bit weird as it is a valid email

 

 

 

Thanks

Pam

**Comment by Synchro** [comment]
If it was considered an invalid address, it would fail at the point you provide the address. You would not get as far as attempting to send.

**Comment by Knutsford** [comment]
There was a – in the bit after the @ which it doesn’t like not the org.uk after all. Sorry about that. It looked as though it was the ORG.UK yesterday.  He is going to have to change the email address.

 

 

 

Pam

**Comment by Knutsford** [comment]
Any idea why a – in the bit after the @ can be causing a problem? All the offices have a -  so they can’t be changed.

 

 

 

Thanks

Pam

**Comment by Knutsford** [comment]
Ignore my last message – it works for mine

 

 

 

Pam
