### ISSUE TITLE
Spammers using Github to send spam

### ISSUE THREAD

**Issue by gbrn** [PHPMailer/PHPMailer#2823]
Dear, I have been receiving spam in my email for a long time. Since X-Mailer is provided by Github.com. I believe this is a security flaw as spammers are using the Github to send Spam.

```
X-Mb: yes
X-Priority: 3
X-Mailer: PHPMailer 12.7.6 (https://github.com/PHPMailer/PHPMailer)
List-Unsubscribe: XXXX
From: XXXX
To: XXXX
Reply-To: XXXX
X-mb: yes
Subject: XXXX
Message-ID: XXXX
Date: Tue, 08 Nov 2022 05:25:47 +0000
MIME-Version: 1.0
```

**Comment by Synchro** [comment]
No, this means that they are *using* PHPMailer (which we can do nothing to control – it's the nature of open-source software), but neither GitHub nor the PHPMailer project have nothing to do with the sending process.
