### ISSUE TITLE
error 500 

### ISSUE THREAD

**Issue by MEME-KING16** [PHPMailer/PHPMailer#2826]
![img1](https://user-images.githubusercontent.com/115302822/202329730-69cd8cc7-7e79-4891-840d-d44cc9d6f4ad.jpg)
![img2](https://user-images.githubusercontent.com/115302822/202329737-f693148c-5b53-4d65-baf3-5ccf75eb23b5.jpg)

**Comment by Synchro** [comment]
Check your web server's error log. The most likely thing is that you have not run composer correctly so the `autoload.php` file doesn't exist, causing a fatal error on your `require` line.
