### ISSUE TITLE
ini_get('mbstring.func_overload') & 1 raises a warning.

### ISSUE THREAD

**Issue by ivantcholakov** [PHPMailer/PHPMailer#2827]
PHP 7.3.33

PHPMailer,php, line 861:

```php
if (ini_get('mbstring.func_overload') & 1) {
```

https://github.com/PHPMailer/PHPMailer/blob/e7bd0d1f6d0c934f07a40eb851fa35ca637797d1/src/PHPMailer.php#L861

Raises a warning "A non-numeric value encountered" and contaminates my log-file.

A proposed change:

```php
if ((int) ini_get('mbstring.func_overload') & 1) {
```

**Comment by Synchro** [comment]
Thanks. That's fixed, will be in next release.
