### ISSUE TITLE
yandex smtp don't work

### ISSUE THREAD

**Issue by nrtszr** [PHPMailer/PHPMailer#283]
Hi,
now yandex smtp don't work
How to work?

(Yandex update smtp port)

**Comment by nrtszr** [comment]
Hi,
now don't work this

**Comment by Synchro** [comment]
If yandex have changed their server details, you will need to update yours to match. Try the same troubleshooting techniques I posted before.

**Comment by dexdizayn** [comment]
SMTP -> FROM SERVER:220 smtp4m.mail.yandex.net ESMTP (Want to use Yandex.Mail for your domain? Visit http://pdd.yandex.ru) 
SMTP -> FROM SERVER: 250-smtp4m.mail.yandex.net 250-8BITMIME 250-PIPELINING 250-SIZE 42991616 250-STARTTLS 250-AUTH LOGIN PLAIN 250-DSN 250 ENHANCEDSTATUSCODES 
SMTP -> ERROR: AUTH not accepted from server: 530 5.7.7 Email sending without SSL/TLS encryption is not allowed. Please see: http://help.yandex.ru/mail/mail-clients/ssl.xml 
SMTP -> FROM SERVER: 
SMTP -> ERROR: RSET failed: 
SMTP -> NOTICE: EOF caught while checking if connectedThe following From address failed: info@marcaevent.com : Called Mail() without being connected Message could not be sent.Mailer Error: The following From address failed: info@marcaevent.com : Called Mail() without being connected

**Comment by Synchro** [comment]
You need to do what I said above - enable encryption. Yandex (like most sensible email services) will not let you use authentication without encryption, which is exactly what the error message says.

**Comment by tahelromero** [comment]
You must use the app password in order to send the message thru PHPMailer
