### ISSUE TITLE
$mail->send()) set to false even when the email is sent

### ISSUE THREAD

**Issue by Knutsford** [PHPMailer/PHPMailer#2834]
```PHP
if (!$mail->send()) {	
	if (trim($Emails) !== "") {
		$Emails = $Emails . ",<br>";
	}
	$Emails = $Emails . trim($Email) .  " - Message was not sent - Mailer Error: " . $mail->ErrorInfo;	
} 
```

I that inside a loop

The first email it is sending to fails which I am expecting but the next one thinks $mail->send() is also false even though the email  is getting sent.

Is that a bug or what can I do about it so the one that is sent isn't going through and hitting `$Emails = $Emails . trim($Email) .  " - Message was not sent - Mailer Error: " . $mail->ErrorInfo;`

`$mail->ErrorInfo;` contains the error from the first email address if that helps

Thanks

**Comment by Synchro** [comment]
I can't tell without seeing the rest of your code, but I would step through it in a debugger to see why it's getting there.

**Comment by Knutsford** [comment]
What I don’t understand is why the second time mail.send() is returning false when it shouldn’t be but it is sending the email.  I have already traced through the code. I t is thought something from the first one is triggering it to be still false the next time.

 

 

 

Pam

**Comment by Synchro** [comment]
It's not *set* to false, it *returns* false, indicating something went wrong with the send process. Set `$mail->SMTPDebug = 2` so you can see what's going on. Again, I can't do anything without seeing your code.

**Comment by Knutsford** [comment]
AH – thanks. I Hadn’t come across that one. That might help. It is definitely something to do with his email address. I gather it is being sent ok from our end but it isn’t arriving at his end while the one to me arrives but that is also returning false and the error message is the same and is still  his email address. 

 

Sorry I meant it returns false not set to false

 

 

 

Pam
