### ISSUE TITLE
Why is latest release (6.7) not conforming to Major.Minor.Patch scheme?

### ISSUE THREAD

**Issue by XL-2000** [PHPMailer/PHPMailer#2841]
PHPMailer has always used strict implementation of the Major.Minor.Patch Semantic versioning scheme.
I would expect the latest release to have version number 6.7.0 instead of 6.7
Is there any specific reason for not following this "tradition"?

**Comment by Synchro** [comment]
It's true I've done this before, but I don't think dropping trailing zeros is unusual, and it will work with things like PHP's `version_compare()`. It probably doesn't matter much because I'll be releasing 6.7.1 tomorrow (for PHP 8.2), and it's too late to change it now anyway.
