### ISSUE TITLE
Need option to disable TLS 1.0 and 1.1 and enable TLS 1.3

### ISSUE THREAD

**Issue by alexhenrie** [PHPMailer/PHPMailer#2856]
[SMTP.php](https://github.com/PHPMailer/PHPMailer/blob/7c38295b17a477837e4954f204988e06eb3354f3/src/SMTP.php#L455) currently has the following code:

```
        //Allow the best TLS version(s) we can
        $crypto_method = STREAM_CRYPTO_METHOD_TLS_CLIENT;

        //PHP 5.6.7 dropped inclusion of TLS 1.1 and 1.2 in STREAM_CRYPTO_METHOD_TLS_CLIENT
        //so add them back in manually if we can
        if (defined('STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT')) {
            $crypto_method |= STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT;
            $crypto_method |= STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT;
        }
```

For security reasons, I need to be able to disable TLS 1.0 and 1.1 and enable TLS 1.3. Unfortunately, PHPMailer is hardcoded to accept TLS 1.0 through 1.2 and reject TLS 1.3.

**Comment by Synchro** [comment]
That's not what that code does. The PHPMailer config does not disable TLSv1.3. Bear in mind that PHPMailer is a client, not a server, so if you connect to server that support 1.3, it will use 1.3 (assuming your PHP version supports it). It's not in a position to dictate what versions a server supports.

**Comment by alexhenrie** [comment]
What I mean is, I want PHPMailer to fail if the supplied SMTP server does not support TLS 1.2 or 1.3. I would rather have an error than have it continue with an insecure TLS version.

**Comment by alexhenrie** [comment]
OK, that's an option, thank you.

There's still the question of whether or not PHPMailer should allow TLS 1.3 *by default*. As far as I can tell, if [`stream_socket_enable_crypto`](https://www.php.net/manual/en/function.stream-socket-enable-crypto.php) is passed a `$crypto_method` argument (which it is), it will not allow TLS 1.3 as a method unless `$crypto_method` includes `STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT` (which PHPMailer does not set). Could we at least add something like:

```
        if (defined('STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT')) {
            $crypto_method |= STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT;
        }
```

**Comment by Synchro** [comment]
This is not true. PHPMailer does not need to set that flag because it's already included in `STREAM_CRYPTO_METHOD_TLS_CLIENT` by default. Look at [how it's defined in the PHP source](https://github.com/php/php-src/blob/master/main/streams/php_stream_transport.h#L174), where you can see that the `STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT ` flag to enable TLS 1.3 (`1 << 6`) is included in the definition of `STREAM_CRYPTO_METHOD_TLS_CLIENT`, so 1.3 is enabled by default. Historically that bit may not have been set, but only because older builds did not have that flag available to do so.

**Comment by alexhenrie** [comment]
Ah, I didn't know that the meaning of `STREAM_CRYPTO_METHOD_TLS_CLIENT` changed in PHP 7.2 from "TLS 1.0 only" to "any version of TLS", sorry. Thank you for the explanation.
