### ISSUE TITLE
I get this error

### ISSUE THREAD

**Issue by humbletd1** [PHPMailer/PHPMailer#2862]
Fatal error: Uncaught PHPMailer\PHPMailer\Exception: SMTP Error: Could not connect to SMTP host. Failed to connect to server in C:\xampp\htdocs\php send email\phpmailer\src\PHPMailer.php:2233 Stack trace: #0 C:\xampp\htdocs\php send email\phpmailer\src\PHPMailer.php(2019): PHPMailer\PHPMailer\PHPMailer->smtpConnect(Array) #1 C:\xampp\htdocs\php send email\phpmailer\src\PHPMailer.php(1678): PHPMailer\PHPMailer\PHPMailer->smtpSend('Date: Thu, 19 J...', 'l;k;lk;,\r\n') #2 C:\xampp\htdocs\php send email\phpmailer\src\PHPMailer.php(1516): PHPMailer\PHPMailer\PHPMailer->postSend() #3 C:\xampp\htdocs\php send email\send.php(29): PHPMailer\PHPMailer\PHPMailer->send() #4 {main} thrown in C:\xampp\htdocs\php send email\phpmailer\src\PHPMailer.php on line 2233

**Comment by Synchro** [comment]
This tells me several things:

1. You didn't read the issue template that told you where to go to [find out how to fix this](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#smtp-error-could-not-connect-to-smtp-host).
2. You have enabled exceptions, but have no exception handling – base your code on the examples provided, which don't make this mistake.
3. Your hosting provider doesn't let you use outbound SMTP. Either ask them to allow it, or find a new hosting provider.
