### ISSUE TITLE
SMTP - Can"t send mail

### ISSUE THREAD

**Issue by Chico0008** [PHPMailer/PHPMailer#2867]
# Problem description

Glpi 10.0.0.5 hosted on a Ubuntu 22.04 serveur, with apache2/mariaDB

When configuring the Notification to mail / smtp, test mail to the admin imemdiately get an error notification.
tried again with debug mode, log from files/_log/mail-debug.log
```
2023-01-24 15:30:23 [500@s-web]
3 - Connection: opening to smtp.viry.net:8082, timeout=300, options=array()2023-01-24 15:30:23 [500@s-web]
3 - Connection: opened2023-01-24 15:30:23 [500@s-web]
2 - SERVER -> CLIENT: 2023-01-24 15:30:23 [500@s-web]
3 - Connection: closing due to error2023-01-24 15:30:23 [500@s-web]
3 - Connection: closed2023-01-24 15:30:23 [500@s-web]
3 - SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting2023-01-24 15:32:40 [500@s-web]
```

smtp.viry.net:8082 is a relay smtp server on windows server, and my ubuntu server (s-web.viry.net) au authorized to connect to the relay.

we have on old version en glpi (0.85) with the same notification smtp parameter working fine.
i'd like the new version work too.

**Comment by Synchro** [comment]
That's not PHPMailer's usual debug output, and is missing any useful info. Can you show the output from your script running with `SMTPDebug = 3`?

**Comment by Chico0008** [comment]
oups sorry, i thought i was on glpi github >_<
