### ISSUE TITLE
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting in php 7.4

### ISSUE THREAD

**Issue by Rignesh-Sarvaliya** [PHPMailer/PHPMailer#2868]
```php
require_once('PHPMailer/src/PHPMailer.php');
require_once('PHPMailer/src/SMTP.php');
require_once('PHPMailer/src/Exception.php');

        $subject = "Password Resert";
        $body = "Hi ";
        $sender_email = $_POST['email'];
        $mail = new \PHPMailer\PHPMailer\PHPMailer(true);
        try {
            //Server settings
            $mail->SMTPDebug = 0;                              // Enable verbose debug output
            $mail->isSMTP();                                   // Send using SMTP
            $mail->Host       = 'smtp.gmail.com';              // Set the SMTP server to send through
            $mail->SMTPAuth   = true;                          // Enable SMTP authentication
            $mail->Username   = 'username@gmail.com';    // SMTP username
            $mail->Password   = 'password';            // SMTP password
            $mail->SMTPSecure = "ssl";                         // Enable TLS encryption; `PHPMailer::ENCRYPTION_SMTPS` encouraged
            $mail->Port       = 465;                           // TCP port to connect to, use 465 for `PHPMailer::ENCRYPTION_SMTPS` above
            //Recipients
             $mail->setFrom('username@gmail.com', 'project');
            $mail->addAddress('test@mailinator.com');                  // Name is optional

            // Content
            $mail->isHTML(true);                               // Set email format to HTML
            $mail->Subject = $subject;
            $mail->Body    = $body;
            $mail->send();

        } catch (Exception $e) {
            print_r($e);
            exit;
        }
```

**Comment by Synchro** [comment]
https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Rignesh-Sarvaliya** [comment]
> https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

I am using the latest PHPMailer version but again  same error

**Comment by Synchro** [comment]
Have you perhaps considered reading the docs that tell you how to diagnose and resolve this issue, that you have now been pointed at 3 times?

**Comment by Rignesh-Sarvaliya** [comment]
> Have you perhaps considered reading the docs that tell you how to diagnose and resolve this issue, that you have now been pointed at 3 times?

I have tried all the ways but the issue is the same

**Comment by Synchro** [comment]
So why haven't you posted the results of your tests in here that show it's a problem with PHPMailer rather than your hosting? If your hosting provider blocks outbound SMTP (which is quite likely), there is nothing I can do. There is nothing I can suggest here that's not in the docs.

**Comment by Rignesh-Sarvaliya** [comment]
> So why haven't you posted the results of your tests in here that show it's a problem with PHPMailer rather than your hosting? If your hosting provider blocks outbound SMTP (which is quite likely), there is nothing I can do. There is nothing I can suggest here that's not in the docs.

this error should be display from my testing

PHPMailer\PHPMailer\Exception Object ( [message:protected] => SMTP Error: Could not connect to SMTP host. Failed to connect to server [string:Exception:private] => [code:protected] => 0 [file:protected] => /home/uqx0dtuthzcf/public_html/mywebsite/PHPMailer/src/PHPMailer.php [line:protected] => 2233 [trace:Exception:private] => Array ( [0] => Array ( [file] => /home/uqx0dtuthzcf/public_html/mywebsite/PHPMailer/src/PHPMailer.php [line] => 2019 [function] => smtpConnect [class] => PHPMailer\PHPMailer\PHPMailer [type] => -> [args] => Array ( [0] => Array ( ) ) ) [1] => Array ( [file] => /home/uqx0dtuthzcf/public_html/mywebsite/PHPMailer/src/PHPMailer.php [line] => 1678 [function] => smtpSend [class] => PHPMailer\PHPMailer\PHPMailer [type] => -> [args] => Array ( [0] => Date: Tue, 31 Jan 2023 18:01:42 +0000 To: rignesh@mailinator.com From: Sumka Subject: Password Resert Message-ID: X-Mailer: PHPMailer 6.7.1 (https://github.com/PHPMailer/PHPMailer) MIME-Version: 1.0 Content-Type: text/html; charset=iso-8859-1 [1] => Hi, ravi .[Click Here Too Reset Your Password](https://mywebsite.com/resetPassword.php?mid=2) ) ) [2] => Array ( [file] => /home/uqx0dtuthzcf/public_html/mywebsite/PHPMailer/src/PHPMailer.php [line] => 1516 [function] => postSend [class] => PHPMailer\PHPMailer\PHPMailer [type] => -> [args] => Array ( ) ) [3] => Array ( [file] => /home/uqx0dtuthzcf/public_html/mywebsite/recoverEmail.php [line] => 283 [function] => send [class] => PHPMailer\PHPMailer\PHPMailer [type] => -> [args] => Array ( ) ) ) [previous:Exception:private] => )

**Comment by Synchro** [comment]
That's the error that shows that it's failing to connect, not tests that will show why. What happened when you tried to use the openssl command line client? What results do you get from DNS and connectivity tests?

**Comment by Rignesh-Sarvaliya** [comment]
> That's the error that shows that it's failing to connect, not tests that will show why. What happened when you tried to use the openssl command line client? What results do you get from DNS and connectivity tests?

This is a project in core-PHP and I work in Cpanel

**Comment by Synchro** [comment]
PHP is PHP. That you're running it in a way that means you can't debug it is your own problem. Unfortunately, cpanel makes many things difficult and confusing. There's really nothing I can do if you don't understand your own hosting, and it has nothing to do with PHPMailer.

**Comment by Rignesh-Sarvaliya** [comment]
> PHP is PHP. That you're running it in a way that means you can't debug it is your own problem. Unfortunately, cpanel makes many things difficult and confusing. There's really nothing I can do if you don't understand your own hosting, and it has nothing to do with PHPMailer.

https://www.sumkacapitalvisor.com/sumkacopy/recoverEmail.php

and put the email - ravipatel69791@gmail.com and submit button click and scroll down the error print

**Comment by Rignesh-Sarvaliya** [comment]
> PHP is PHP. That you're running it in a way that means you can't debug it is your own problem. Unfortunately, cpanel makes many things difficult and confusing. There's really nothing I can do if you don't understand your own hosting, and it has nothing to do with PHPMailer.

Even if there is a problem in hosting, this error "SMTP Error: Could not connect to SMTP host. Failed to connect to server" comes?

**Comment by Synchro** [comment]
Set `$mail->SMTPDebug = 3;` and post the output here.

**Comment by Rignesh-Sarvaliya** [comment]
> Set `$mail->SMTPDebug = 3;` and post the output here.

I have set please check

**Comment by Synchro** [comment]
> > PHP is PHP. That you're running it in a way that means you can't debug it is your own problem. Unfortunately, cpanel makes many things difficult and confusing. There's really nothing I can do if you don't understand your own hosting, and it has nothing to do with PHPMailer.
> 
> Even if there is a problem in hosting, this error "SMTP Error: Could not connect to SMTP host. Failed to connect to server" comes?

Yes, it's a problem with your hosting, not your script or PHPMailer.

This is the important part of the error output:

    Connection failed. Error #2: stream_socket_client(): unable to connect to ssl://smtp.gmail.com:465 (Network is unreachable)

"Network is unreachable" means that your hosting provider is blocking your outbound SMTP traffic, so PHPMailer can't work. This is [what it says in the docs](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#smtp-error-could-not-connect-to-smtp-host). It also tells you what to do in that situation, which is either ask them to stop blocking it, or find a better hosting provider.

**Comment by Rignesh-Sarvaliya** [comment]
> > > PHP is PHP. That you're running it in a way that means you can't debug it is your own problem. Unfortunately, cpanel makes many things difficult and confusing. There's really nothing I can do if you don't understand your own hosting, and it has nothing to do with PHPMailer.
> > 
> > 
> > Even if there is a problem in hosting, this error "SMTP Error: Could not connect to SMTP host. Failed to connect to server" comes?
> 
> Yes, it's a problem with your hosting, not your script or PHPMailer.
> 
> This is the important part of the error output:
> 
> ```
> Connection failed. Error #2: stream_socket_client(): unable to connect to ssl://smtp.gmail.com:465 (Network is unreachable)
> ```
> 
> "Network is unreachable" means that your hosting provider is blocking your outbound SMTP traffic, so PHPMailer can't work. This is [what it says in the docs](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#smtp-error-could-not-connect-to-smtp-host). It also tells you what to do in that situation, which is either ask them to stop blocking it, or find a better hosting provider.

ok I check thanks for the help
Thanks, man
