### ISSUE TITLE
Wrong line endings with PHP 8.1 and nullmailer

### ISSUE THREAD

**Issue by AdrienPoupa** [PHPMailer/PHPMailer#2870]
We recently updated PHPMailer from an ancient 5.2 version to the latest, 6.7.1.

We have a bit of an exotic setup, with PHPMailer using the `mail` driver, then `nullmailer` handles sending the email to a remote SMTP server. This is done for performance purposes, so we don't have to wait synchronously for PHPMailer to connect to the SMTP server and block the user while it is doing it.

When sending multi `multipart/mixed` emails, the raw email looks as follows:

```
...
X-Mailer: PHPMailer 6.7.1 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="b1=_123"
Content-Transfer-Encoding: 8bit

--b1=_123

Content-Type: text/html; charset=UTF-8

Content-Transfer-Encoding: 8bit
```

Notice the extra new lines after the boundary between the two `Content` entries. It should be:

```
X-Mailer: PHPMailer 6.7.1 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="b1=_123"
Content-Transfer-Encoding: 8bit

--b1=_123
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit
```

We narrowed it down to this block in `preSend`:
```php
    public function preSend()
    {
        if (
            'smtp' === $this->Mailer
            || ('mail' === $this->Mailer && (\PHP_VERSION_ID >= 80000 || stripos(PHP_OS, 'WIN') === 0))
        ) {
            //SMTP mandates RFC-compliant line endings
            //and it's also used with mail() on Windows
            static::setLE(self::CRLF);
        } else {
            //Maintain backward compatibility with legacy Linux command line mailers
            static::setLE(PHP_EOL);
        }
```

Because we are running the `mailer` driver and PHP 8.1, `static::setLE(self::CRLF);` is triggered. But since we are using a legacy Linux CLI mailer, what we need is `static::setLE(PHP_EOL);`.

Now, I understand our setup is not ideal, convoluted and probably not common.

However, I would have appreciated more flexibility for setting the line endings. I had to overwrite `setLE` in a child class to prevent the CRLF call from modifying the line endings.

Maybe this block could be extracted to a smaller, overwritable function? Or this could be an editable parameter somewhere? I had something like this in mind:

```php
    public function setLineEndings()
    {
        if (
            'smtp' === $this->Mailer
            || ('mail' === $this->Mailer && (\PHP_VERSION_ID >= 80000 || stripos(PHP_OS, 'WIN') === 0))
        ) {
            //SMTP mandates RFC-compliant line endings
            //and it's also used with mail() on Windows
            static::setLE(self::CRLF);
        } else {
            //Maintain backward compatibility with legacy Linux command line mailers
            static::setLE(PHP_EOL);
        }
    }

    public function preSend()
    {
        $this->setLineEndings();
...
```

**Comment by Synchro** [comment]
Since all the `mail()` function does is open a synchronous SMTP connection to localhost, I would recommend switching to SMTP to submit your message to nullmailer. It should be faster than the mail function (also not holding up your users), and will also avoid issues with line endings and line length, and also be safer since it doesn't have to run the shell escaping gauntlet (the subject of several CVEs!). Can that work for you?

**Comment by AdrienPoupa** [comment]
Wow, thanks for the fast reply. Using the SMTP driver with localhost would most likely work yes, but also still apply CRLF endings, so I will check if the issue is still there or not. Thank you!

**Comment by Synchro** [comment]
That should not be a problem - the issue with line endings only occurs in the mail() function, and is a PHP peculiarity. Things that talk proper SMTP will expect CRLF endings regardless of platform.

**Comment by AdrienPoupa** [comment]
After more tests, I was not able to connect to nullmailer using SMTP - I am not even sure that is supported.

However, I was able to use nullmailer with the Sendmail driver (`isSendmail`) and it uses the appropriate line endings.

Thanks your support!
