### ISSUE TITLE
Safemode detection is not working properly

### ISSUE THREAD

**Issue by humpataa** [PHPMailer/PHPMailer#2871]
PHPMailer function mailPassthru adds a fifth parameter to mail instead of proper detection (and use four parameters if PHP is in safe mode). This results in a kindof misleading error "Could not instantiate mail function" and the troubleshooting guide wrongly pointing in the direction to search for server issues.
Please either fix the detection, show a proper message and / or adjust the troubleshooting guide.
Took me an hour!
Thank you.

**Comment by Synchro** [comment]
The wiki is editable if you have better references. That error message is nearly always caused by the server not having a local mail server installed. The use of safe mode is relatively rare (I've literally never been asked about it here), but if you've got a better way of handling it, PRs are welcome.

**Comment by Synchro** [comment]
Actually that's not quite true. [In 2016 I said](https://github.com/PHPMailer/PHPMailer/pull/929#issuecomment-269452735):

> Safe mode was deprecated in PHP 5.3 and removed in 5.4 anyway. All mention of it will be going away in future versions of PHPMailer.

**Comment by humpataa** [comment]
Right, it's not because of safe mode but it is not a misconfiguration or nothing being installed. It's just configured differently than you expect. mail() is working fine for me, but PHPMailer still crashes. I appreciate your work, but I am not sure why you keep insisting that there is no problem. If you have "literally" never been asked, here it is.

I don't know how to add a PR for the troubleshooting guide. The most simple solution is to set 
`$mail->UseSendmailOptions = false;`
to prevent PHPMailer to pass parameters that may not be suitable for the installed mail system. I believe the fifth parameter is not needed for 99% of the users of PHPMailer. So it would maybe even make sense to make this the default setting.
