### ISSUE TITLE
PHPMailer suddenly stop working on diffrent hosts

### ISSUE THREAD

**Issue by GetASiteDev** [PHPMailer/PHPMailer#2885]
I just got to me that PHPMailer no longer can connect to the smtp server.

2023-03-21 14:07:28 SMTP ERROR: Failed to connect to server: Connection refused (111)
SMTP Error: Could not connect to SMTP host. Failed to connect to server
Message could not be sent. Mailer Error: SMTP Error: Could not connect to SMTP host. Failed to connect to serverSMTP server error: Failed to connect to server SMTP code: 111 Additional SMTP info: Connection refused

I have websites on diffrent webhosts with diffrent mailservers and its the same problem on everyone.
No change has been made in the PHP version or on the log in information for the mail accounts.

**Comment by Synchro** [comment]
"Connection refused" means what it says – the mail server, or the network it's on, rejected your attempt at connecting to it. It suggests your hosting provider(s) have decided to block outbound SMTP, which is a very common thing to do, and has nothing to do with PHPMailer. What results did you get when you tried the tests in the troubleshooting guide?
