### ISSUE TITLE
Unix socket as host shows error

### ISSUE THREAD

**Issue by mikehjc** [PHPMailer/PHPMailer#2893]
# Problem description
when setting the host option as a path to socket. Shows error.

# option
                        $phpmailer->Host = '/var/shared/postfix/smtp.sock';

# error
SMTP Error: Could not connect to SMTP host.

SMTP Debug:
Invalid host: /var/shared/postfix/smtp.sock

**Comment by Synchro** [comment]
That's because it's not a supported option.
