### ISSUE TITLE
error:14161044:SSL routines:state_machine:internal error

### ISSUE THREAD

**Issue by Nyamkhuub** [PHPMailer/PHPMailer#2895]
My project completely working fine on Centos linux OS. But couldn't send email from ubuntu server continuously giving this exception.

> Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
> error:14161044:SSL routines:state_machine:internal error

What should we do?

**Comment by XL-2000** [comment]
What steps did you take to investigate this yourself?
And how do you think this is related tot PHPMailer?
Did you try pasting your error message above in Google and did you read the first search result from StackOverflow?

**Comment by rakibul99ko** [comment]
![Uploading d6a20ab731042012f857cb070226e9b3.jpg…]()
