### ISSUE TITLE
Error: Message body empty

### ISSUE THREAD

**Issue by PolishedStaple** [PHPMailer/PHPMailer#290]
I put all of my outgoing emails into a mySQL database and then run a cron job every few minutes to send out the next batch of emails.  I'm noticing that every once in a while I get the, "Message body empty" error and I don't know why.  Emails that fail to send are marked in the database so I can review them manually.  Each of these failures indeed has text in the message column, so I'm puzzled why a few messages have this problem.

Any suggestions?

**Comment by Rubelsoldier** [comment]
@patelsumit5192  After few hours wasted, i got your suggestions and now its working. But my question is, then why there are some wrong code in PHPMailer github example?

**Comment by Synchro** [comment]
There isn’t. If you have a problem, open a new issue.
