### ISSUE TITLE
Do not turn Github into a space for protests, fools.

### ISSUE THREAD

**Issue by samyan** [PHPMailer/PHPMailer#2923]
It seems ridiculous to me that you put politics and wars in an alien space, completely alien to the subject.

**Comment by JokerGermany** [comment]
Says someone who has a profile picture of the Government of Armenia XD

**Comment by samyan** [comment]
> Says someone who has a profile picture of the Government of Armenia XD
> "fools"

It is an absurd comparison, but here I leave the conversation.

**Comment by KarelWintersky** [comment]
USA invaded to Siria and Iraw. Killing tens of thousands of civilians and displacing millions more.

It's a genocide. 

Why don't you condemn it?

Ukrainian troops shelled Donetsk for 8 years and killed dozens of children. Why don't you condemn it?

Why don't you condemn it?

**Comment by JokerGermany** [comment]
1

> USA invaded to Siria and Iraq. Killing tens of thousands of civilians and displacing millions more.
> 
> It's a genocide.
> 
> Why don't you condemn it?
> 
> Ukrainian troops shelled Donetsk for 8 years and killed dozens of children.
> 
> Why don't you condemn it?
> 
> Why don't you condemn it?

At the moment?



> Ukrainian troops shelled Donetsk for 8 years and killed dozens of children.
> 
> Why don't you condemn it?
> 
> Why don't you condemn it?

Do you have Sources for this?
The UN told otherwise, Prigoschin told otherwise...

**Comment by samyan** [comment]
> > USA invaded to Siria and Iraq. Killing tens of thousands of civilians and displacing millions more.
> > It's a genocide.
> > Why don't you condemn it?
> > Ukrainian troops shelled Donetsk for 8 years and killed dozens of children.
> > Why don't you condemn it?
> > Why don't you condemn it?
> 
> At the moment?
> 
> > Ukrainian troops shelled Donetsk for 8 years and killed dozens of children.
> > Why don't you condemn it?
> > Why don't you condemn it?
> 
> Do you have Sources for this? The UN told otherwise, Prigoschin told otherwise...

Let's see Joker, maybe SuperManGermany? I don't know if you are good at programming, but I am sure that you have 0 knowledge and therefore 0 arguments regarding what you are trying to continue as a stubborn person. If I were you, I would leave this conversation so as not to make myself more ridiculous. And if you have doubts, go to Twitter, Youtube and other social networks to ask questions and silly statements. GitHub is a platform where people develop code. Do you understand or do I have to tell you in German?

**Comment by KarelWintersky** [comment]
@JokerGermany  

> Do you have Sources for this?

Yes. I have friends in Donetsk... 

Do you believe everything that traitors say on the Internet?
