### ISSUE TITLE
spammer using my domain to send spam via github

### ISSUE THREAD

**Issue by HendrikSharples** [PHPMailer/PHPMailer#2924]
Anything that can be done?  my email is hendrik@hendriksharples.com  I'm getting 20 or so undeliverable emails per minute, which means who knows how many are going through?  

Received: from Adam ([168.61.75.36]) by mrelay.perfora.net (mreueus002
 [74.208.5.2]) with ESMTPSA (Nemesis) id 0LZggk-1pbuWX13yW-00lTEv for (real email removed)
 [<victim@aol.com>](mailto:victim@aol.com); Tue, 04 Jul 2023 03:08:21 +0200
Date: Tue, 4 Jul 2023 10:08:20 +0900
To: [removed
From: "MSG: Wellsfargo" [<hendrik@hendriksharples.com>](mailto:hendrik@hendriksharples.com)
Subject: Urgent Verification
Message-ID: <fab77a28e97c58b4a34dc09f76228255@Adam>
X-Priority: 1
X-Mailer: PHPMailer 5.2.23 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="b1_fab77a28e97c58b4a34dc09f76228255"
X-Provags-ID: V03:K1:CnEKykf9UiVZyMk28UMLHtPrBJgREn03HpZP48vulqyDsUI9T2i
 Kl3s5glbrd7R4+x2Mcw0A0h4RRqx+F1lywxxNTlFej3cFrJBLcPQtJdaWnoOyaQYvUONar1
 IoqfIyd+P9ENPy+HyUKdl/Su9IZfIOvCozvpVa6ZVYLXVnAQPlOc7DV9q9cbYj6NzaMjGLK
 aGPxpQ518lrfYkAgm6qaA==
X-Spam-Flag: NO
UI-OutboundReport: notjunk:1;M01:P0:YNUP1iXVchM=;wGYjDQoUoe5j9t7L+4ClJodRJUD
 t6vbPF9haetXpZICZ6w3HSwGznw2/El0K/CeCT+WR+yk5Vb4TiS1hImJThsAr4s9hy1DdxaBq
 RIVKw7LOkV4Or0syNMHkmbYA+Yxesl2cPjn26YpD1oM5fFgb1BZkhCBrkq9vkPD/PiZA1QmSZ
 txlM920N55elEQJLPHhOumZelJFeeN9b1zB4KA/RyQ/bAYsf7AWyT0SbImPZ6nYe20FeWvkG8
 GDwTtMH73vtHCpVwTJRtKh1PBsurj9GjNbxRNj0iUfmhpsc/y5bH8y+ONXaNk0gu0rFpU8UDO
 iwXrBfJKE2yNtjYFoKqg2568b6ZqnotXgbEgKfdqXm4iGfzcglB++zBCPoAAskAjiuo8ltqQM
 1LD3+TsBeAWuULdXcmXaXJf27aIL8dT7ZL9SiG5TC7enarumk4BdhgVVOXQnwrEfU46x4UMjB
 VqGP/pLdc59vca0fwSAul9lzEL6ZX3Hv2cHLRhzjCr4hCiMQlKzg92cxdl6yQgFZX8gCCz5S6
 x4vKza6MifaCaqLRLD1B1Qb5YK7hBRinB//naWUtn1E7BGwbvQvrlSbj011aVd1XhQ0wSEN3L
 6h362zbqdTw4WHinZYwwowgY6vJF2FNwv6zEWBNKf8w62QqrrjRGjnMnFYPj0WnX1MNSOWA/c
 OX6tLssNVbhCF4VHUL/iT2F6XluvUBTUWA8o0p6FLwk0mJDAabDYuWbo/VoSQtXoXxrjLUK+/
 DqihomrMGVpSMsKmTpL7m0ZEkMP//9yZg==

Reporting-MTA:dns;perfora.net
Arrival-Date:Tue, 04 Jul 2023 03:08:21 +0200

[Final-removed@aol.com)
Action:failed
Status:5.0.0
Final-Log-ID:0LZggk-1pbuWX13yW-00lTEv

Received: from Adam ([168.61.75.36]) by mrelay.perfora.net (mreueus002
 [74.208.5.2]) with ESMTPSA (Nemesis) id 0LZggk-1pbuWX13yW-00lTEv for
 [<jschein4@aol.com>](mailto:jschein4@aol.com); Tue, 04 Jul 2023 03:08:21 +0200
Date: Tue, 4 Jul 2023 10:08:20 +0900
To: [
From: "MSG: Wellsfargo" [<hendrik@hendriksharples.com>](mailto:hendrik@hendriksharples.com)
Subject: Urgent Verification
Message-ID: <fab77a28e97c58b4a34dc09f76228255@Adam>
X-Priority: 1
X-Mailer: PHPMailer 5.2.23 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="b1_fab77a28e97c58b4a34dc09f76228255"
X-Provags-ID: V03:K1:CnEKykf9UiVZyMk28UMLHtPrBJgREn03HpZP48vulqyDsUI9T2i
 Kl3s5glbrd7R4+x2Mcw0A0h4RRqx+F1lywxxNTlFej3cFrJBLcPQtJdaWnoOyaQYvUONar1
 IoqfIyd+P9ENPy+HyUKdl/Su9IZfIOvCozvpVa6ZVYLXVnAQPlOc7DV9q9cbYj6NzaMjGLK
 aGPxpQ518lrfYkAgm6qaA==
X-Spam-Flag: NO
UI-OutboundReport: notjunk:1;M01:P0:YNUP1iXVchM=;wGYjDQoUoe5j9t7L+4ClJodRJUD
 t6vbPF9haetXpZICZ6w3HSwGznw2/El0K/CeCT+WR+yk5Vb4TiS1hImJThsAr4s9hy1DdxaBq
 RIVKw7LOkV4Or0syNMHkmbYA+Yxesl2cPjn26YpD1oM5fFgb1BZkhCBrkq9vkPD/PiZA1QmSZ
 txlM920N55elEQJLPHhOumZelJFeeN9b1zB4KA/RyQ/bAYsf7AWyT0SbImPZ6nYe20FeWvkG8
 GDwTtMH73vtHCpVwTJRtKh1PBsurj9GjNbxRNj0iUfmhpsc/y5bH8y+ONXaNk0gu0rFpU8UDO
 iwXrBfJKE2yNtjYFoKqg2568b6ZqnotXgbEgKfdqXm4iGfzcglB++zBCPoAAskAjiuo8ltqQM
 1LD3+TsBeAWuULdXcmXaXJf27aIL8dT7ZL9SiG5TC7enarumk4BdhgVVOXQnwrEfU46x4UMjB
 VqGP/pLdc59vca0fwSAul9lzEL6ZX3Hv2cHLRhzjCr4hCiMQlKzg92cxdl6yQgFZX8gCCz5S6
 x4vKza6MifaCaqLRLD1B1Qb5YK7hBRinB//naWUtn1E7BGwbvQvrlSbj011aVd1XhQ0wSEN3L
 6h362zbqdTw4WHinZYwwowgY6vJF2FNwv6zEWBNKf8w62QqrrjRGjnMnFYPj0WnX1MNSOWA/c
 OX6tLssNVbhCF4VHUL/iT2F6XluvUBTUWA8o0p6FLwk0mJDAabDYuWbo/VoSQtXoXxrjLUK+/
 DqihomrMGVpSMsKmTpL7m0ZEkMP//9yZg==

**Comment by XL-2000** [comment]
Yes! configure proper SPAM filters on your own domain/setup!
And maybe not throwing around your email address in plain sight as you are doing here, which only adds to the amount of spam you will be receiving

**Comment by XL-2000** [comment]
Oh... and maybe do not put your email address on your website homepage in plain sight... all scrapers will but it on a gazillion spam lists.... 
These tips are btw lessons internet 101 20 years ago....

**Comment by HendrikSharples** [comment]
Thanks, but my problem isn't spammers sending me stuff (the filters get a lot), my problem is someone apparently using github to use my email to send spam to others.

**Comment by XL-2000** [comment]
First things first: did you chcnage all youe emial and github related passwords?

**Comment by Synchro** [comment]
This is the problem that SPF, DKIM, and DMARC solves, so implement them for your domain. It's not anything to do with GitHub or PHPMailer.

**Comment by Synchro** [comment]
I removed your real email domain from this issue so that scrapers don't use it against you...
