### ISSUE TITLE
PHPMailer on Laravel Forge server - openssl issue?

### ISSUE THREAD

**Issue by BGFR** [PHPMailer/PHPMailer#2934]
Hi, i ran out of ideas what could be the issue with PHPMailer.
The website is deployed on Laravel Forge with php7.4 on ubuntu 20
The same repo works fine on a localhost with same php7.4, however as soon as deployed on the Forge Server it refuses to work.
All required modules are installed and enabled. The only error in php error log is:

  Quote
`PHP Warning:  PHP Startup: Unable to load dynamic library 'openssl' (tried: /usr/lib/php/20190902/openssl (/usr/lib/php/20190902/openssl: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/openssl.so (/usr/lib/php/20190902/openssl.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

1. `/usr/lib/php/20190902/ `is the correct php extension path. However there is no openssl folder there

2. openssl is enabled in CLI and FPM configuration like this: extension=openssl When disabled from configuration openssl still runs and error does not show up ( that is verified also via php.info)

```
openssl version => OpenSSL 1.1.1f  31 Mar 2020
whereis openssl => openssl: /usr/bin/openssl /usr/include/openssl /usr/share/man/man1/openssl.1ssl.gz
php -i | grep "OpenSSL support" => OpenSSL support => enabled; Native OpenSSL support => enabled
```

Is the issue really in openssl or there is something else that breaks it?

**Comment by BGFR** [comment]
Hi, there is nothing in the extension folder. 
Here is
whereis openssl
openssl: /usr/bin/openssl /usr/include/openssl /usr/share/man/man1/openssl.1ssl.gz
root@mailer:~# which openssl
/usr/bin/openssl

**Comment by Synchro** [comment]
That's the openssl command line client, not the library or extension used by PHP. Since openssl is a core extension, it may not exist as a separate extension package to install. I'd recommend reinstalling your PHP. If you have no luck there, you could try switching to [Ondřej Surý's PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php) and reinstalling from there, as it is often more reliable than the stock packages.
