### ISSUE TITLE
SMTP ERROR: Failed to connect to server: Connection refused (111) with Office365

### ISSUE THREAD

**Issue by ndub** [PHPMailer/PHPMailer#295]
Sorry if this is a road heavily traveled. I've seen the other posts about this but nothing in them has either solved the problem I'm having or ignited a lightbulb that helped me solve it myself.

Here's my code:

```
require 'PHPMailerAutoload.php';
$config = parse_ini_file('/path/to/file/config.ini', true);
$mail = new PHPMailer;
$mail->SMTPDebug = 3;
$mail->Debugoutput = 'html';
$mail->isSMTP();
$mail->Host = $config['host']; //smtp.office365.com
$mail->SMTPAuth = true;
$mail->Username = $config['username']; //an.existing.account@appinc.co
$mail->Password = $config['password']; //confirmed this is being passed correctly
$mail->SMTPSecure = 'tls';
$mail->Port = 587;
$mail->From = $config['username'];
$mail->FromName = 'Website Forms';
$mail->addAddress('sales@appinc.co', 'Some Name');
$mail->addReplyTo('sender.email@somedomain.com', 'SenderFirst SenderLast');
$mail->addBCC('my.email.address@appinc.co');
$mail->isHTML(true);
$mail->Subject = 'Contact Form Submission';
$mail->Body = 'Some html here';
$mail->AltBody = 'Some alt content here';
if(!$mail->send()) {
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    //perform success actions
    exit();
}
```

I've confirmed that the domain, username and password are all correct and being passed in correctly. Important to note that this worked on our local dev server prior to launch. Once the site was moved to our hosting account (Hostgator) is when it stopped working. I've confirmed with HG that port 587 is open on our server.

Here is the error message I'm seeing:

```
Connection: opening to smtp.office365.com:587, t=10, opt=array ()
SMTP ERROR: Failed to connect to server: Connection refused (111)
SMTP connect() failed.
Message could not be sent.Mailer Error: SMTP connect() failed.
```

Any help that can be provided is very much appreciated, even if it's just a link to an article that explains why it won't work now that it's in our production environment. 

[EDIT]: Minor grammatical error.

**Comment by hargrig** [comment]
hey friends i have error like this, can anybody help me ? ))

SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: No address associated with hostname (0)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by ndub** [comment]
My problem was ultimately resolved by contacting my host and having them
change the way the firewall was configured for my site. If you haven't, I'd
contact your host or look at your firewall settings.

**Comment by hargrig** [comment]
Thanks bro..i will try that ))

**Comment by sahilsunesara** [comment]
@ndub did u get solution regarding above matter?

**Comment by mrshiru** [comment]
2017-12-25 11:02:41	Connection: opening to ssl://smtp.gmail.com:587, timeout=300, options=array ( ) 2017-12-25 11:02:41	SMTP ERROR: Failed to connect to server: (0) 2017-12-25 11:02:41	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting Mail Not Send

**Comment by Synchro** [comment]
Read the guide the error links to.

**Comment by vaishnavhiren1993** [comment]
> hello @ndub , @drmad , @Synchro @hargrig ,
>  **##ERROR is**
> SMTP ERROR: Failed to connect to server: Connection refused (111)
> SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
> 
### **is is work on local host but once i run on godaddy server i can't and error shot . plz solve and sugges me**
>
> **## My Code HTML is **``<style type="text/css">
>     /*form*/
>     
>     label {
>         position: absolute;
>         -webkit-transform: translateY(6px);
>         transform: translateY(6px);
>         left: 13px;
>         color: rgb(0, 0, 0);
>         -webkit-transition: all 0.25s ease;
>         transition: all 0.25s ease;
>         pointer-events: none;
>         font-size: 19px;
>         font-family: "century gothic";
>     }
>     
>     label .req {
>         margin: 2px;
>         color: #b11a1a;
>     }
>     
>     label.active {
>         -webkit-transform: translateY(50px);
>         transform: translateY(50px);
>         left: 2px;
>         font-size: 14px;
>         top: -70px;
>     }
>     
>     label.active .req {
>         opacity: 1;
>     }
>     
>     label.highlight {
>         color: #000;
>     }
>     
>     input,
>     textarea {
>         font-size: 17px;
>         display: block;
>         width: 100%;
>         padding: 5px 10px;
>         background: none;
>         background-image: none;
>         border: 1px solid #a0b3b0;
>         color: #000;
>         border-radius: 0;
>         -webkit-transition: border-color .25s ease, box-shadow .25s ease;
>         transition: border-color .25s ease, box-shadow .25s ease;
>     }
>     
>     input:focus,
>     textarea:focus {
>         outline: 0;
>         border-color: #b11a1a;
>     }
>     
>     textarea {
>         border: 2px solid #a0b3b0;
>         resize: vertical;
>         height: 120px;
>     }
>     
>     .field-wrap {
>         position: relative;
>         margin-bottom: 30px;
>     }
>     
>     .top-row:after {
>         content: "";
>         display: table;
>         clear: both;
>     }
>     
>     .top-row>div {
>         float: left;
>         width: 48%;
>         margin-right: 4%;
>     }
>     
>     .top-row>div:last-child {
>         margin: 0;
>     }
>     
>     .button {
>         border: 0;
>         outline: none;
>         border-radius: 0;
>         padding: 10px 0;
>         font-size: 1rem;
>         font-weight: 600;
>         text-transform: uppercase;
>         letter-spacing: .1em;
>         background: #b11a1a;
>         color: #ffffff;
>         -webkit-transition: all 0.5s ease;
>         transition: all 0.5s ease;
>         -webkit-appearance: none;
>     }
>     
>     .button:hover,
>     .button:focus {
>         background: #9b1717;
>     }
>     
>     .button-block {
>         display: block;
>         width: 100%;
>     }
>     
>     .forgot {
>         margin-top: -20px;
>         text-align: right;
>     }
>     
>     .content {
>         padding-bottom: 0px;
>     }
>     
>     * {
>         font-family: 'Century Gothic' !important;
>     }
> </style>
> <div class="container" style="padding: 45px 20% 20px; ">
>     <h3 id="form-registration">Register and get more information</h3>
> 
> 
>     <br>
>     <form action="mail.php" method="POST" id="form">
>         <input type="email" id="email" name="owneremail" maxlength="30" placeholder="enter email address to get user data " style="margin-bottom:30px">
>         <div class="top-row">
>             <div class="field-wrap">
>                 <label class="active highlight">
>                 First Name<span class="req">*</span>
>               </label>
>                 <input type="text" pattern="[a-zA-Z]{3,30}" id="fname" name="fname" maxlength="30">
>             </div>
> 
>             <div class="field-wrap">
>                 <label class="active highlight">
>                 Last Name<span class="req">*</span>
>               </label>
>                 <input type="text" pattern="[a-zA-Z]{3,30}" id="lname" name="lname" maxlength="30">
>             </div>
>         </div>
> 
>         <div class="field-wrap">
>             <label class="active highlight">
>               Company name<span class="req">*</span>
>             </label>
>             <input type="text" class="half" name="company" id="cname">
>         </div>
> 
>         <div class="top-row">
>             <div class="field-wrap">
>                 <label class="active highlight">
>                 City<span class="req">*</span>
>               </label>
>                 <input type="text" pattern="[a-zA-Z]{3,20}" name="city" id="city">
>             </div>
> 
>             <div class="field-wrap">
>                 <label class="active highlight">
>                 State/Province<span class="req">*</span>
>               </label>
>                 <input type="text" pattern="[a-zA-Z]{3,20}" name="state" id="province">
>             </div>
>         </div>
> 
>         <div class="top-row">
>             <div class="field-wrap">
>                 <label class="active highlight">
>                  Email Address<span class="req">*</span>
>                </label>
>                 <input type="email" required="required" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" name="email" id="memail">
>             </div>
> 
>             <div class="field-wrap">
>                 <label class="active highlight">
>                 Phone<span class="req">*</span>
>               </label>
>                 <input type="number" autocomplete="on" pattern="[0-9]{10,15}" name="phone" id="mobile">
>             </div>
>         </div>
> 
>         <div class="field-wrap">
>             <label class="active highlight">
>               Website<span class="req">*</span>
>             </label>
>             <input type="text" class="half" pattern="[a-zA-Z._-%^]" name="website" id="website" value="">
>         </div>
> 
>         <div class="field-wrap">
>             <label class="active highlight">
>               Queries
>             </label>
>             <textarea name="queries" autocomplete="off"></textarea>
>         </div>
>         <button type="submit" value="Submit" name="Submit" class="button button-block">Send</button>
> 
>     </form>
> </div>
> 
> ### **My PHP Code is**
>    /*form*/
> <?php
> use PHPMailer\PHPMailer\PHPMailer;
> require("PHPMailer-master/src/PHPMailer.php");
> require("PHPMailer-master/src/SMTP.php");
> require("PHPMailer-master/src/Exception.php");
> //require 'vendor/autoload.php';
> if(isset($_POST['Submit'])) {
> //fatch data from form
> //fatch data from form
> $fname = $_POST['fname'];
> $lname = $_POST['lname'];
> $company = $_POST['company'];
> $city = $_POST['city'];
> $state = $_POST['state'];
> $email_to = $_POST['email'];
> $phone = $_POST['phone'];
> $website = $_POST['website'];
> $queries = $_POST['queries'];
> 
> $mail = new PHPMailer(true);
> $mail->SMTPDebug = 3;
> $mail->Debugoutput = 'html';
> $mail->isSMTP();
> $mail->Host = 'ssl://smtp.gmail.com';
> $mail->SMTPAuth = true;
> $mail->Username = 'useremailaddress@gmail.com';
> $mail->Password = 'userpassword';
> $mail->SMTPSecure = 'ssl';
> $mail->Port = 465;
> $mail->isHTML(true);
> $mail->From = 'useremailaddress@gmail.com';
> $mail->FromName = 'this is test';
> $mail->addAddress($email_to);
> $mail->WordWrap = 50;
> $mail->isHTML(true);
> $mail->Subject = 'ASK FOR A DEMO';
> $mail->Body    = 'hello';
> if(!$mail->send()) {
>     echo 'Message could not be sent.';
>     echo 'Mailer Error: ' . $mail->ErrorInfo;
> } else {
>     echo 'Message has been sent';
>     echo "<script>alert('".$email_to." thank you!');</script>";
> }
> }
> ?>
> <h3>hello</h3>
>

**Comment by Synchro** [comment]
You see that link to the troubleshooting guide? Click it, and read what it says about GoDaddy.

**Comment by derunva** [comment]
Maybe your guide is bad?
