### ISSUE TITLE
Wiki on Github

### ISSUE THREAD

**Issue by YasirRWebDesigner** [PHPMailer/PHPMailer#2954]
**I am able to edit your wiki page. Please fix the permissions.**

**Comment by Synchro** [comment]
I'm guessing you are unfamiliar with how Wikis are meant to work. This is open source, and the wiki is intentionally open because maintainers don't want to have to hand-hold every little thing. Yes, that means it is occasionally abused, but it's also version controlled, so anything can be undone.
