### ISSUE TITLE
Is generating of the Message-ID necessary?

### ISSUE THREAD

**Issue by bugnumber9** [PHPMailer/PHPMailer#2961]
PHPMailer will generate a Message-ID automatically (unless we send a custom one via $phpmailer->MessageID).
But is this even necessary? The Message-ID is always set by the sending server.
I think it makes sense to either remove this feature or allow passing an empty string via $phpmailer->MessageID to have it generated on the server level.

**Comment by Synchro** [comment]
In the majority of cases, PHPMailer is acting as the sending server. For example if you set Host to `smtp.gmail.com`, your script is the sender and gmail is the receiver. If you omit a message ID, there is no way for you to get it after sending, making it useless for keeping track of message threads. In that situation gmail will generate an ID, however it does it in a way that is identifiable, and spam filters can count that against you.
If you're DKIM signing, you *really* want the message ID in the signature, as it's the only reliable unique ID.
Overall, I'd say that if you *don't* care about message ID, then having PHPMailer generate it for you is a non-issue; if you *do* care, it's right there for you to set. I don't see any advantage in not setting one.
