### ISSUE TITLE
Which phpmailer version can I use with PHP7.4?

### ISSUE THREAD

**Issue by DEV7163** [PHPMailer/PHPMailer#2964]
Morning everybody,

The company I work for is planning to migrate a legacy app from PHP5 to PHP7
I know PHP7 is not longer supported either, I'd migrate to PHP8 instead, but it's not my decision, at least this way we'll get PDO, along with a bunch of security fixes.

My question is, which phpmailer version would be the right one for PHP 7? (I assume PHP7.4 but it's not decided yet).
Also, if you guys have any advice or important fact I need to be aware about the migration I'd love to hear it.

Thanks in advance and have a great day.

**Comment by Synchro** [comment]
The current PHPMailer version (6.8.1) will work fine on any version of PHP between 5.5. and 8.3.
