### ISSUE TITLE
Error "require_once(): Failed opening required 'SM_PATHfunctions/imap.php' (include_path='/home/sylvest/build99999/include') in /home/sylvest/build99999/include/mime.php on line 17"

### ISSUE THREAD

**Issue by rowanbradley** [PHPMailer/PHPMailer#2965]
Just tried to modify my code to use PHPmailer instead of mail(), because I need to use SMTP Authentication.. I'm getting lots of these errors. What have I done wrong?

I tried to install PHPmailer on my shared server by copying the files PHPmailer.php, POP3.php and SMTP.php to my include directory. I could not find a file imap.php

Thank you - Rowan

**Comment by decomplexity** [comment]
The POP support is an obsolete method of sender authentication: roughly, if the sender can authenticate to receive POP mail, then they are authenticated to use SMTP sending also.
POP and IMAP are 'receive only' protocols.

**Comment by Synchro** [comment]
There is no `imap.php` file included in PHPMailer; it must be part of your own app.
