### ISSUE TITLE
After the latest version of PHPMailer (21/10/2023) Is some one facing issues - with not producing of error logs.

### ISSUE THREAD

**Issue by g138** [PHPMailer/PHPMailer#2969]
PHPMailer Version: 6.8

# Problem description
When trying to send an email through the PHPMailer using Amazon SES (Simple Email Service). The email is not getting through, this started happening recently before it was working fine. Also, **no** logs are being produced on the server (or through echo).

**Comment by Synchro** [comment]
What output do you see when you set `$mail->SMTPDebug = 3`? What happened when you went through the steps in the troubleshooting guide?
