### ISSUE TITLE
PHP Mailer Not Work On Https:// Website

### ISSUE THREAD

**Issue by patelsumit5192** [PHPMailer/PHPMailer#297]
i have PHP mailer Code use and Send mail using gmail Smtp Server .

but this code not use in Secure Website...

Thank U

**Comment by lambdawarehouse** [comment]
I have same problem, Ive tried with ssl, tls and the respective ports. The same script work on http but no on https folder.

Thanks

**Comment by Synchro** [comment]
Whether you access PHPMailer's script via http or https makes no difference to whether PHPMailer itself uses TLS; They are entirely independent. If you have problems with http vs https, it's not a PHPMailer problem. Also, please don't hijack threads.
