### ISSUE TITLE
SMTP connect error

### ISSUE THREAD

**Issue by ali123-aliu** [PHPMailer/PHPMailer#2974]
I am trying to send mail using code it works on locally but when i deploy it on live (Godaddy) hosting server
it gives me error
**Here is the code**

$mail = new PHPMailer();
$mail->isSMTP();
$mail->SMTPDebug = SMTP::DEBUG_SERVER;
$mail->Host = 'send.one.com';
$mail->SMTPAuth = true;
$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
$mail->Port = 587;
$mail->Username = 'mail@gmail.com';
$mail->Password = '123456789';
$mail->setFrom('mail@gmail.com');
$mail->addAddress('to_mail@gmail.com');
$mail->isHTML(true);
$mail->Subject = 'Subject';
$mail->Body = 'This is the HTML message body';
if ($mail->send()) {
     echo 'Message has been sent.';
} else {
     echo 'Message could not be sent. Mailer Error: ' . $mail->ErrorInfo;
}

**Here is the Error**

2023-11-09 12:55:44 SMTP ERROR: Failed to connect to server: Connection refused (111)

SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

Message could not be sent. Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/TroubleshootingSMTP server error: Failed to connect to server SMTP code: 111 Additional SMTP info: Connection refused

**Comment by Synchro** [comment]
Next time please *read the error message* and follow the link to the troubleshooting guide, which addresses [this exact problem](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#godaddy).
