### ISSUE TITLE
Micorosft Azure XOAUTH2 issues

### ISSUE THREAD

**Issue by At0kir** [PHPMailer/PHPMailer#2988]
Hi everyone,

I followed the guide below and setup everything on Active Directory. I got the client ID, client secret and tenant ID. Then I got the refresh token and for some reason I keep getting the CLIENT: 535 5.7.3 Authentication unsuccessful.

https://github.com/PHPMailer/PHPMailer/wiki/Microsoft-Azure-and-XOAUTH2-setup-guide

In the app permissions I have SMTP.Send and offline_access as delegated permissions.
The app has also been authorized using the get_oauth_token.php with admin credentials to get the refresh token.
The account that I am trying to send emails from has SMTP AUTH enabled on it as well.

Here is the code that I have to test if it works.

```php
<?php

/**
 * This example shows how to send via Microsoft Outlook's servers using XOAUTH2 authentication
 * using the league/oauth2-client to provide the OAuth2 token.
 * To use a different OAuth2 library create a wrapper class that implements OAuthTokenProvider and
 * pass that wrapper class to PHPMailer::setOAuth().
 */

//Import PHPMailer classes into the global namespace
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\OAuth;
//Alias the League Google OAuth2 provider class
use Greew\OAuth2\Client\Provider\Azure;

//SMTP needs accurate times, and the PHP time zone MUST be set
//This should be done in your php.ini, but this is how to do it if you don't have access to that
date_default_timezone_set('Etc/UTC');

//Load dependencies from composer
//If this causes an error, run 'composer install'
require '../../libs/php_mailer/vendor/autoload.php';

//Create a new PHPMailer instance
$mail = new PHPMailer();

//Tell PHPMailer to use SMTP
$mail->isSMTP();

//Enable SMTP debugging
//SMTP::DEBUG_OFF = off (for production use)
//SMTP::DEBUG_CLIENT = client messages
//SMTP::DEBUG_SERVER = client and server messages
$mail->SMTPDebug = SMTP::DEBUG_SERVER;

//Set the hostname of the mail server
$mail->Host = 'smtp.office365.com';

//Set the SMTP port number:
// - 465 for SMTP with implicit TLS, a.k.a. RFC8314 SMTPS or
// - 587 for SMTP+STARTTLS
$mail->Port = 587;

//Set the encryption mechanism to use:
// - SMTPS (implicit TLS on port 465) or
// - STARTTLS (explicit TLS on port 587)
$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;

//Whether to use SMTP authentication
$mail->SMTPAuth = true;

//Set AuthType to use XOAUTH2
$mail->AuthType = 'XOAUTH2';

//Start Option 1: Use league/oauth2-client as OAuth2 token provider
//Fill in authentication details here
//Either the microsoft account owner, or the user that gave consent
$email = 'donotreply@mail.com';
$clientId = 'aae3-------';
$clientSecret = 'ouP8-----';
$tenantId = '23be-------';

//Obtained by configuring and running get_oauth_token.php
//after setting up an app in Google Developer Console.
$refreshToken = '0.ATcADV6-I7----';

//Create a new OAuth2 provider instance
$provider = new Azure(
    [
        'clientId' => $clientId,
        'clientSecret' => $clientSecret,
        'tenantId' => $tenantId,
    ]
);

//Pass the OAuth provider instance to PHPMailer
$mail->setOAuth(
    new OAuth(
        [
            'provider' => $provider,
            'clientId' => $clientId,
            'clientSecret' => $clientSecret,
            'refreshToken' => $refreshToken,
            'userName' => $email,
        ]
    )
);
//End Option 1

//Set who the message is to be sent from
//For Outlook, this generally needs to be the same as the user you logged in as
$mail->setFrom($email, 'DoNotReply');

//Set who the message is to be sent to
$mail->addAddress('email@email.com', 'User User');

//Set the subject line
$mail->Subject = 'PHPMailer Outlook XOAUTH2 SMTP test';

//Replace the plain text body with one created manually
$mail->Body = 'This is a plain-text message body';

//send the message, check for errors
if (!$mail->send()) {
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message sent!';
}
```

I get this error and I removed some part of the AUTH XOAUTH2 response as I'm not sure if it contains anything sensitive since its quite larger(let me know if I should include the whole thing).

2023-11-28 20:06:51 SERVER -> CLIENT: 220 CH5P222CA0004.outlook.office365.com Microsoft ESMTP MAIL Service ready at Tue, 28 Nov 2023 20:06:50 +0000
2023-11-28 20:06:51 CLIENT -> SERVER: EHLO website.com
2023-11-28 20:06:51 SERVER -> CLIENT: 250-CH5P222CA0004.outlook.office365.com Hello [IP of server]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-STARTTLS250-8BITMIME250-BINARYMIME250-CHUNKING250 SMTPUTF8
2023-11-28 20:06:51 CLIENT -> SERVER: STARTTLS
2023-11-28 20:06:51 SERVER -> CLIENT: 220 2.0.0 SMTP server ready
2023-11-28 20:06:51 CLIENT -> SERVER: EHLO website.com
2023-11-28 20:06:51 SERVER -> CLIENT: 250-CH5P222CA0004.outlook.office365.com Hello [IP of server]250-SIZE 157286400250-PIPELINING250-DSN250-ENHANCEDSTATUSCODES250-AUTH LOGIN XOAUTH2250-8BITMIME250-BINARYMIME250-CHUNKING250 SMTPUTF8

2023-11-28 20:06:52 CLIENT -> SERVER: AUTH XOAUTH2 dXNlcj1kb25vdHJlcGx5QGVudGVyYS5jYQFhdXRoPUJlYXJlciBleUowZVhBaU9pSktWMVFpTENKdWIyNWpaU0k2SW1WclFrbGpjamhJUWxoaFFWOVBaVkJXU------------------------------------------------------------

2023-11-28 20:06:59 SERVER -> CLIENT: 535 5.7.3 Authentication unsuccessful [CH5P222CA0004.NAMP222.PROD.OUTLOOK.COM 2023-11-28T20:06:58.989Z 08DBF000432DD736]
2023-11-28 20:06:59 SMTP ERROR: AUTH command failed: 535 5.7.3 Authentication unsuccessful [CH5P222CA0004.NAMP222.PROD.OUTLOOK.COM 2023-11-28T20:06:58.989Z 08DBF000432DD736]
SMTP Error: Could not authenticate.
2023-11-28 20:06:59 CLIENT -> SERVER: QUIT
2023-11-28 20:06:59 SERVER -> CLIENT: 221 2.0.0 Service closing transmission channel
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by decomplexity** [comment]
Have a look at the AAD sign-in logs to see if there is anything of interest there. After you have signed in once, the MSFT authorization-code server should think that it has already passed you an authorization code when it calls the redirectURI (the code is suffixed to the URI).
Try:
•	sign in to AAD
•	select Enterprise Applications
•	select your app
•	select Sign-in Logs (near the bottom of the vertical list)
•	select User-sign-ins (non-interactive)
•	select Refresh
•	select the Request ID ‘Aggregate’ item for today’s date and for Resource ‘Office 365 Exchange Online’, 'Graph' or other request you wish to check
•	select the event for the time of your last failed event (or any other event in which you are interested)
This may have some useful information.

Then also:
•	select the ‘…’ on the RHS of the title
•	see the Oauth Scope Info field in the Additional Details tab

Failing this, note that access tokens expire quickly and are thus quickly invalid for anyone else to use, although inevitably they contain some application specific information that you may regard as sensitive. If you are happy with this, please post the entire token (the one starting dXN in your diagnostics). 

The two most common reasons for your problem are:
- wrong or no client scope (permissions)
- wrong audience (the AUD claim in the token)

**Comment by At0kir** [comment]
My app is not registered under the Enterprise Applications but under App Registrations. From what I saw the app doesn't show up under Enterprise Applications

**Comment by decomplexity** [comment]
Since your token looks fine, scope is fine and resource ('audience') is fine, 365 SMTP may (may...) be saying it doesn't like the token user (donotreply@entera.ca) trying to send with an envelope From address that is different from that of the account.

**Comment by At0kir** [comment]
I have changed the $email to multiple different emails and the same error is happening. I'm lost at this point on what to do

**Comment by decomplexity** [comment]
OK. The 'acid test' for this is whether the token's user address donotreply@entera.ca is the same as the tenant's user principal email address. It is acceptable to use another licensed address in the same tenant but you know the user principal address is valid because it was used to register the app. 
One obvious thing to check is whether SMTP is enabled for that user  - see Admin Center=>Active users=>[select the user]=>Mail tab=>Email apps=>Manage email apps=>[Authenticated SMTP ticked]

**Comment by At0kir** [comment]
I have verified that the user has SMTP ticked. The account that authorized the application has full admin permissions over the whole active directory so I should be able to send emails using the donotreply@entera.ca user address.

**Comment by decomplexity** [comment]
Yes you should. 
But since it was 365 SMTP that had been presented with an apparently valid access token that it would then check for audience*, scope*, user and expiry time - things that are relevant to 365 SMTP authentication but less relevant to token issue - this is where it is best to look for things amiss
Since you have found the app registration under Enterprise applications as well as App registrations, what Permissions are listed for that app (in Enterprise applications) in both the Admin consent and User consent tabs? These should be OK as the token was issued and looks good,  but I am fishing for clues!

* - both of which look OK

**Comment by At0kir** [comment]
So I remade the refresh token but I signed in using the dotnoreply account instead of the admin account and I put the refresh token from that account and everything is working properly now. So I guess you have to authorize the app using the admin account and after that re do the refresh token using the user account.

Thank you for your help.

**Comment by decomplexity** [comment]
@timramakers - exactly what scope are you using?
