### ISSUE TITLE
Return the server message after code "250"

### ISSUE THREAD

**Issue by Lambik** [PHPMailer/PHPMailer#299]
Hi,

For my Amazon SES needs, I would like to retrieve their "message ID", a unique mail ID [they use](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html) to notify me about bounces/complaints/deliveries. This message ID is [returned after the "250 Ok" code](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-response-codes.html) when the mail is sent.

In the current implementation of PHPMailer, there is no way to retrieve this message ID.

I could change the smtp php code to return, upon code 250, not "true" but the message text (which would probably still work, since it evaluates to true too in php non-strict comparisons). However, I am unfamiliar with the other sending options (sendmail, php mail) to know if this is possible, and I feel the solution should be generic.

Is this an idea to add?
Of course I would be equally happy with a "getLastMessage" method or something...

**Comment by tribulant** [comment]
When using SMTP, Amazon SES includes the message-id of the email after the "250 Ok" response.

It is not the last reply because after resetting or disconnecting, there are more replies from the server after that.

Is there any way of extracting the Amazon SES message-id in the OK response from the server?

**Comment by Synchro** [comment]
At present, no, however it would be quite easy to subclass the SMTP class and tweak `data()` to store the response. There's an example of subclassing SMTP in the examples folder. Alternatively you could subclass the PHPMailer class and override `smtpSend()`, capturing `last_reply` before it issues the quit or rset commands. I'd be happy to accept a PR if you do a nice implementation!
