### ISSUE TITLE
If we use 'XYZ & Contracting Company' in subject this is sent as 'XYZ &amp Contracting Company'. Please suggest how to fix

### ISSUE THREAD

**Issue by sierracbe** [PHPMailer/PHPMailer#3001]
# Problem description
If we use 'XYZ & Contracting Company' in subject this is sent as 'XYZ &amp Contracting Company'. Please suggest how to fix
# Code to reproduce
........

        $intro_mail = new PHPMailer\PHPMailer\PHPMailer();
	$intro_mail->CharSet = "UTF-8";
	
	$intro_mail->isSMTP();

	$intro_mail->Host = $host;
	$intro_mail->Username = $smtpusername;
	$intro_mail->Password = $smtppassword;
	$intro_mail->SMTP_PORT=$port;
	$intro_mail->SMTPSecure = $smtpsecure;			
	$intro_mail->SMTPAuth = true;     // turn on SMTP authentication

	$intro_mail->From=$fromid;
							
	$intro_mail->FromName = $fromname;
	
	$intro_mail->IsHTML(true);  
        $companyname="XYZ & Contracting Company";
	$intro_mail->Subject=$companyname." - ".$message_title_intro;

**Comment by Vijay-Chaudhary** [comment]
$subject = 'XYZ & Contracting Company';
$encodedSubject = mb_encode_mimeheader($subject, 'UTF-8', 'Q');
Hi @sierracbe , You can try **mb_encode_mimeheader** php method for more specific encoding

**Comment by Synchro** [comment]
No, don't do that, you're only going to cause problems with that as it's duplicating what PHPMailer already does, so you're likely to end up with double or corrupt encoding.

PHPMailer does not apply HTML entity encoding anywhere except debug output, so it's not PHPMailer that's doing this.
