### ISSUE TITLE
PHP Parse error:  syntax error, unexpected token "use"

### ISSUE THREAD

**Issue by DrWilliamHobbs** [PHPMailer/PHPMailer#3017]
Hi - i got these error in the php_error_log:

`PHP Parse error:  syntax error, unexpected token "use" in /opt/lampp/htdocs/....`

The site isnt loading properly and i used only your snippet:
```
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
    

require 'PHPMailer/src/Exception.php';
require 'PHPMailer/src/PHPMailer.php';
require 'PHPMailer/src/SMTP.php';
```

I use xampp on linux to test something with php version 8.2.12

**Comment by Synchro** [comment]
A syntax error on that means that you're *not* using PHP 8.2, but something very old that doesn't support namespaces, which were introduced in PHP 5.3. I suggest you write a script containing `<?php phpinfo();` to double check your version.

**Comment by DrWilliamHobbs** [comment]
Ive double checked it: Same as before.... 

`PHP Version 8.2.12 
Build Date 	Nov 25 2023 08:05:53 `

**Comment by Synchro** [comment]
This isn't something specific to PHPMailer. Try seeing if PHP gives you an error if you ask it to run this:

    <?php
    use abc\xyz;

That's a simple `use` statement creating an alias for a non-existent class, but it should do nothing at all if you try to run it. If you run it on an old version of PHP, you should get the same error.

**Comment by DrWilliamHobbs** [comment]
There is nothing and No errors.

**Comment by Synchro** [comment]
OK, so now add the original lines back in, one at a time, until the problem starts happening.

**Comment by XL-2000** [comment]
My guess...

Switch the order of the "require" and "use" lines.
In your code you are using a namespace which is not available yet (since the loading of the files will happen AFTER the declaration.
I expect if you load the files before the "use", it should work (if the files are loaded properly)

**Comment by Synchro** [comment]
No, that won't help. Use statements are just local aliases, the require statements have no effect on them. They only come into play when you instantiate a class.

**Comment by DrWilliamHobbs** [comment]
> OK, so now add the original lines back in, one at a time, until the problem starts happening.

theres is no change



> My guess...
> 
> Switch the order of the "require" and "use" lines. In your code you are using a namespace which is not available yet (since the loading of the files will happen AFTER the declaration. I expect if you load the files before the "use", it should work (if the files are loaded properly)
> 
> ```
> require 'PHPMailer/src/Exception.php';
> require 'PHPMailer/src/PHPMailer.php';
> require 'PHPMailer/src/SMTP.php';
> 
> use PHPMailer\PHPMailer\PHPMailer;
> use PHPMailer\PHPMailer\Exception;
> ```

same...

**Comment by XL-2000** [comment]
Two questions:
1. Are you using `<?php` at the start of your PHP file, incase unsafe / shorthand tags (`<?`) are not allowed
2. In case you are not providing the full code file, are you sure you are **not** using "`use`" inside a class declaration? Like:
```
class Foo { 
use PHPMailer\PHPMailer\PHPMailer;
}
```
it should be
```

use PHPMailer\PHPMailer\PHPMailer;
class Foo {
...
}
```

as a reference: https://stackoverflow.com/questions/33342994/unexpected-use-t-use-when-trying-to-use-composer

**Comment by DrWilliamHobbs** [comment]
> Two questions:
> 
>     1. Are you using `<?php` at the start of your PHP file, incase unsafe / shorthand tags (`<?`) are not allowed
> 
>     2. In case you are not providing the full code file, are you sure you are **not** using "`use`" inside a class declaration? Like:
> 
> 
> ```
> class Foo { 
> use PHPMailer\PHPMailer\PHPMailer;
> }
> ```
> 
> it should be
> 
> ```
> 
> use PHPMailer\PHPMailer\PHPMailer;
> class Foo {
> ...
> }
> ```
> 
> Maybe its good to provide you full file, since it seems to be a overall syntax error

I'll check it on tuesday, because my files are in the office ^^

**Comment by XL-2000** [comment]
So, what's the verdict?

**Comment by ucsendre** [comment]
Hello,
I have the same problem: PHP Parse error:  syntax error, unexpected token "use"
The code I try to use is:
`<?
function cleaninput($input) { $input = trim($input); $input = stripslashes($input); $input = htmlspecialchars($input); return $input;}
if (isset($_POST['name']) && isset($_POST['email'])) {
if (isset($_POST['name'])) { $felado = cleaninput( $_POST['name'] ); } else { $felado = ''; };
if (isset($_POST['email'])) { $faemail = cleaninput( $_POST['email'] ); } else { $faemail = ''; };
if (isset($_POST['subject'])) { $targy = cleaninput( $_POST['subject'] ); } else { $targy = ''; };
if (isset($_POST['message'])) { $uzenet = cleaninput( $_POST['message'] ); } else { $uzenet = ''; };
require 'inc/Exception.php';
require 'inc/PHPMailer.php';
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
$mail = new PHPMailer(true);
try {
$mail->setLanguage('hu', 'inc/language/');
$mail->setFrom('someone@somedomain.hu', $felado);
$mail->addAddress('someone@somedomain.hu', 'Someone');
$mail->addReplyTo($faemail, $felado);
$mail->isHTML(true);
$mail->Subject = 'Üzenet a weboldalról';
$mail->Body = 'Tárgy: <strong>' . $targy . '</strong><br/>Üzenet:<br/>' . $uzenet;
$mail->AltBody = $uzenet;
$mail->send();
$vissza = '<div id="form-message-success" class="mb-4">Üzenetét továbbítottuk.</div>';
} catch (Exception $e) {
$vissza =  "<div id='form-message-warning' class='mb-4'>Az üzenet küldése sikertelen. Hibaüzenet: {$mail->ErrorInfo}</div>";
};
};
header("Location: https://somedomain.hu/");
exit;`

**Comment by XL-2000** [comment]
And what happens when you put the "use" and "require" lines on the top of your file, so as the first lines?
`<?php
require ...
use...
`

**Comment by ucsendre** [comment]
> And what happens when you put the "use" and "require" lines on the top of your file, so as the first lines?
> 
> ```
> <?php
> require ...
> use...
> ```

It seems this works.
Thank you!
:)

**Comment by XL-2000** [comment]
> > And what happens when you put the "use" and "require" lines on the top of your file, so as the first lines?
> > ```
> > <?php
> > require ...
> > use...
> > ```
> 
> It seems this works. Thank you! :)

You're welcome!
That was what I was saying all along!
"Use" is handled compile-time, not run-time.
I guess TS has the same problem
