### ISSUE TITLE
addBCC doesn't work without AddAddress

### ISSUE THREAD

**Issue by n02m4n** [PHPMailer/PHPMailer#3019]
# Problem description

Hi, 

i use phpmailer, over php mail, it is on the Server.

I would send only BCC emails with the addBCC() function, but it sends nothing. Musst add a AddAddress, than the email was send.

I've been using phpmailer for years and so far only BCC has been enough. I didn't have to specify a AddAddress.
Is there anything I can do to ensure it continues to work without a AddAddress?

I use: PHPMailer 6.9.1

PHP 8.2

# Code to reproduce

```php
use PHPMailer\PHPMailer\PHPMailer;

include_once(__DIR__ . '/classes/PHPMailer/autoload.php');

//Create a new PHPMailer instance
$mail = new PHPMailer();
//Set who the message is to be sent from
$mail->setFrom('from@example.com', 'First Last');
//Set who the message is to be sent to
// $mail->AddAddress("to@example.com"); if i comment out it sends the email.
$mail->addBCC('to@example.com');
//Set the subject line
$mail->Subject = 'PHPMailer mail() test';
//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body
$mail->msgHTML('dfbdfb');

//send the message, check for errors
if (!$mail->send()) {
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message sent!';
}
```

**Comment by Synchro** [comment]
This use case is covered by the unit tests, so there must be something else going wrong. Can you show what error you get when you try to send without any to addresses?

**Comment by n02m4n** [comment]
The only Message i see is: 'Message sent!'. The error log is clean.

**Comment by n02m4n** [comment]
Same Server PHPMailer 5.2.4, works without Problems. Mail server log is clean.

**Comment by Synchro** [comment]
It may be clean, but it should show exactly what it's done. I can't tell what it's doing without seeing it.

**Comment by n02m4n** [comment]
`2024-02-16 16:33:33 1rb0DV-006Z4N-9i <= from@example.com H=(xxx.de) [xxxx:xxxx:xx:x::xxx] P=esmtps X=TLS1.3:ECDHE_X25519__RSA_PSS_RSAE_SHA256__AES_256_GCM:256 CV=no S=1361 id=xxx@xxx.de
2024-02-16 16:33:33 1rb0DV-006Z4N-9i => xxx@xxx.com R=outip_dstdomain_redirect T=tomailout_srcdomain H=mailout.xxx.com [xxxx:xxxx:xxxx::xx] X=TLS1.3:ECDHE_SECP256R1__RSA_PSS_RSAE_SHA256__AES_256_GCM:256 CV=yes C="250 OK id=1rb0DV-004cQQ-KU"
2024-02-16 16:33:33 1rb0DV-006Z4N-9i Completed
`
Without $mail->AddAddress("to@example.com"); There is no attempt to send an email via the mail server.

**Comment by Synchro** [comment]
I tested this with a local config and it works fine – this is the delivered message, which you can see has no addresses in the `To` header, just an empty group:

```
To: undisclosed-recipients:;
Subject: PHPMailer mail() test
Date: Fri, 16 Feb 2024 17:08:30 +0000
From: First Last <from@example.com>
Message-ID: <F4bAYPAGdSKYQxAglgIcJ4MloNJCr9GBQblybe88@deepthought-wifi.lan>
X-Mailer: PHPMailer 6.9.1 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="b1=_F4bAYPAGdSKYQxAglgIcJ4MloNJCr9GBQblybe88"
Content-Transfer-Encoding: 8bit

--b1=_F4bAYPAGdSKYQxAglgIcJ4MloNJCr9GBQblybe88
Content-Type: text/plain; charset=us-ascii

dfbdfb

--b1=_F4bAYPAGdSKYQxAglgIcJ4MloNJCr9GBQblybe88
Content-Type: text/html; charset=us-ascii

dfbdfb


--b1=_F4bAYPAGdSKYQxAglgIcJ4MloNJCr9GBQblybe88--
```

Some mail servers do not allow BCC-only messages, so check your mail server's config.

**Comment by n02m4n** [comment]
I just tried again with PHPMailer 5.2.4, the email goes out straight away. Same Server.

**Comment by n02m4n** [comment]
Comment out line 1927 in PHPMailer.php

` //  $to = 'undisclosed-recipients:;';`

Email goes out straight away.

**Comment by Synchro** [comment]
Looks like you have a non-compliant mail server, or one that explicitly denies messages with empty recipient groups.
