### ISSUE TITLE
send differents body for mulitple bcc addresses in one send command

### ISSUE THREAD

**Issue by lokomass** [PHPMailer/PHPMailer#3026]
Hi all,
I have a PHPMailer function which can send a mail to multiple adresses (one hundred) in just one send command, here is the function : 

```
function send_mail($options) {
		global $settings;
		if (is_array($options)) {
			$sujet = $options['sujet'];
			$message = $options['message'];
			$file = (isset($options['file'])) ? $options['file'] : '';
			$delete = (isset($options['delete'])) ? $options['delete'] : true;
			$bcc = (isset($options['bcc'])) ? get_mail_array($options['bcc']) : [];
			$mails = (isset($options['mails'])) ? get_mail_array($options['mails']) : [];
		} else {
			return false;
		}
		$dns = $settings['dns'];
		$name = $settings['name'];
		$contact = $settings['contact'];
		$sender = $contact . '@' . $dns;
		$sujet = '['.$name.'] ' . $sujet;
		$existe = (($file != '') && is_file($file));
		$mail = new PHPMailer(true);
		try {
			$mail -> isSMTP();
			$mail -> Port = 587;
			$mail -> isHTML(true);
			$mail -> SMTPAuth = true;
			$mail -> Body = $message;
			$mail -> Subject = $sujet;
			$mail -> CharSet = 'UTF-8';
			$mail -> setFrom($sender, $name);
			$mail -> addReplyTo($sender, $name);
			$mail -> Host = $settings['credentials']['smtp'];
			$mail -> Username = $settings['credentials']['username'];
			$mail -> Password = $settings['credentials']['password'];
			$mail -> SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
			if ($existe) {
				$mail -> addAttachment($file, basename($file));
			}
			for ($i=0;$i<count($mails);$i++) {
				$mail -> addAddress($mails[$i]);
			}
			for ($i=0;$i<count($bcc);$i++) {
				$mail -> addBCC($bcc[$i]);
			}
			$mail -> send();
			if ($existe && $delete) {
				unlink($file);
			}
			return true;
		} catch (Exception $e) {
			return false;
		}
	}
```

But I want a send a customed body for each user without a loop to send 100 differents mails.
I have to generate a token for each user, to create an unsubscribe link, but I don't find anyway to do this.

Can anybody help me please ?
Thanks a lot

**Comment by Synchro** [comment]
No, you can't do this. If you want 100 different messages, you need to send each message separately, and this is what any mailing list system will do. PHPMailer is quite capable of doing this, and much more efficiently than what you have written here, as you will see in [the mailing list example provided](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps).

**Comment by lokomass** [comment]
thanks for reply,
why my example isn't efficient for basic send ?
in your example, I need to send one by one emails, so for 100 adresses, wait around 5 minutes ?

**Comment by Synchro** [comment]
It is indeed faster to only send one message, but it's simply not possible to do that and have a different message sent to each recipient, which is what you asked for.
If you use a good local mail server (as [the mailing list docs](https://github.com/PHPMailer/PHPMailer/wiki/Sending-to-lists) suggest), 100 messages can be sent in under 0.5 sec. If you're trying to use an external service like gmail, you won't get that kind of speed.

**Comment by peterdd** [comment]
I do also send sometimes mails to members with a customized body per member, but the program pauses some seconds after every 10 mails to prevent a 'flood blocking'. The php-program I use added this feature like 20 years ago, but is sending 100 mails in 0.5 sec not alerting some mail server guards? Is that a phantom issue that does not exist in 2024?

The mail recipients often have same mail domains (gmail,gmx,hotmail), so in a mail to 100 recipients there are like 20 gmx.de/net,10 web.de, 15 gmail adresses.
