### ISSUE TITLE
Missing header termination in multipart/mixed container

### ISSUE THREAD

**Issue by cracksalad** [PHPMailer/PHPMailer#3033]
# Problem description

## Scenario

I am sending a mail with HTML content, an alternative body, one attachment and a signature (via [OpenPGP extension](https://github.com/cracksalad/PHPMailerPGP) but I think that is not the problem here). 

## User view of the problem

Viewing the received mail in Thunderbird, it does not show the HTML content nor the alternative body (just a blank white mail). The attachment and the signature are shown as expected. 

## Code view of the problem

Some [MIME-Validator](https://www.mimevalidator.net/index.html) noted that there is some problem with MIME container headers:
![grafik](https://github.com/PHPMailer/PHPMailer/assets/28577589/9177203f-7271-46f6-bafe-74eb9ae9d43a)

The code at this position looks like this:
```mime
--b1_c6dfe86f67f5e1314c3814c7bca5cf07
Content-Type: multipart/mixed;
 boundary="b1=_hfoWEz41jxuLuI8OuH0jdVPvaWItouwEdnl581EbZlg"
--b1=_hfoWEz41jxuLuI8OuH0jdVPvaWItouwEdnl581EbZlg
Content-Type: multipart/alternative;
 boundary="b2=_hfoWEz41jxuLuI8OuH0jdVPvaWItouwEdnl581EbZlg"

--b2=_hfoWEz41jxuLuI8OuH0jdVPvaWItouwEdnl581EbZlg
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
```

Adding a new line for header termination after the first `Content-Type` header in this snippet fixes the problem (validated by exporting the source code from Thunderbird, adding the new line and reimporting to Thunderbird). But how to integrate this fix into the PHPMailer repo?

# Code to reproduce

If you want to reproduce the exact same scenario, you have to use the OpenPGP extension linked above. Then configure it to sign without encryption and with unprotected headers. There might be the same issue with S/MIME signatures or other ways to add MIME depth but I have not yet validated this.

If you need more information about the structure of my mail, please let me know. I do not want to print the whole source code here for different reasons.

# Environment

- PHPMailer 6.9.1
- PHP 8.3.3
- PHPMailerPGP 1.3.0

**Comment by Synchro** [comment]
That boundary string generation looks suspicious. You're generating multiple boundary strings and using only one of them immediately, but replacing *all* the boundaries in the parent class as you do so. This seems unnecessary, and means that the internal structure of the PGP part affects the parent MIME container. Because of this confusion it's hard to tell from what you posted which code is responsible for generating that particular header structure.

As an aside, there's no need for your PHPMailerPGP class to use the `PHPMailer\PHPMailer` namespace, in fact that's counter to what the namespacing is meant to do as it would prevent the PHPMailer project from using that name.

**Comment by cracksalad** [comment]
> That boundary string generation looks suspicious. You're generating multiple boundary strings and using only one of them immediately, but replacing all the boundaries in the parent class as you do so. This seems unnecessary, and means that the internal structure of the PGP part affects the parent MIME container. Because of this confusion it's hard to tell from what you posted which code is responsible for generating that particular header structure.

You are refering to the PHPMailerPGP code that writes to the `$boundary` variable of the parent class, right? I see that this is not the greatest thing to do, so I will change that.

___

> As an aside, there's no need for your PHPMailerPGP class to use the `PHPMailer\PHPMailer` namespace, in fact that's counter to what the namespacing is meant to do as it would prevent the PHPMailer project from using that name.

That is a fair point. I will change that for v2.0 release.

___

I have found the cause of this issue and was able to fix it in PHPMailerPGP. It has probably been caused by some incompatibility due to changes in PHPMailer. The `PHPMailer::getMailMIME()` method does not include a header termination (double new line) at the end. So I had to add one in PHPMailerPGP.

@Synchro Thanks for your remarks!
