### ISSUE TITLE
405 Not Allowed

### ISSUE THREAD

**Issue by GabrieliMendesNicolodi** [PHPMailer/PHPMailer#3037]
I'm trying to send email throught the Gmail, it was work for a few days, but now stoped working and the error /emailconfig.php 405 Not Allowed, can someone help? thank you for any help

**Comment by XL-2000** [comment]
If you want help, you should provide full code and logging / debug data. On a one-liner not a lot of help can be given

**Comment by Synchro** [comment]
405 is an HTTP error code meaning "method not allowed", which would be appropriate if you do something like use GET to an endpoint that expects POST. However, this also means that it's nothing to do with PHPMailer, which doesn't make or handle HTTP requests at all. I suggest you look in your error logs for more details, and look at the context in which this error occurs.

**Comment by GabrieliMendesNicolodi** [comment]
Hello everyone! Thanks for your help and time. I tested my application using a localserver (Xampp) and the mail was sent succefully. So I think the problem would be a GitHub configuration, because my application is hosted in a github page.

**Comment by Synchro** [comment]
As far as I'm aware, GitHub pages are entirely static, so you can't run PHP on them anyway.
