### ISSUE TITLE
SMTP Authentication not working with special characters like "%"

### ISSUE THREAD

**Issue by geri777** [PHPMailer/PHPMailer#3039]
My SMTP Server requires a password which looks like "6Xcf§5cXR6zB%"
When I try to connect I get the following error:
SMTP connect() failed.

When I change the server's password to any password WITHOUT an "§" (section sign), everything works.

I am using version 6.9.1 which is the latest version at the moment.
I am using SMTPSecure = SSL

**Comment by Synchro** [comment]
§ is not an ASCII character, and so it's not possible to use it unless a system supports SMTPUTF8, which PHPMailer does not. That said, LOGIN and PLAIN auth schemes base64-encode the password string which should insulate it from that, but that will still rely on the unencoded auth string being in a non-ASCII charset, such as ISO-8859-1, which you can't select from the client end, so I doubt it will work anyway.

I suggest setting `$mail->SMTPDebug = 4` and look at the exact text that is being sent.
