### ISSUE TITLE
edebug() should probably also get ride of "\r\n" when using LoggerInterface

### ISSUE THREAD

**Issue by axi** [PHPMailer/PHPMailer#3045]
# Problem description
Using LoggerInterface, I don't see why we should have the SMTP::LE chars passed to the debug method

``` 
    protected function edebug($str)
    {
       ...
       if ($this->Debugoutput instanceof \Psr\Log\LoggerInterface) {
            $this->Debugoutput->debug($str);

            return;
        }
``` 
In my case, with Monolog\Formatter\LineFormatter and a $allowInlineLineBreaks = true, I was seeing logs with an empty line between each log line

```  
[2024-03-14T15:44:05.083183+00:00] logger.DEBUG: CLIENT -> SERVER: 
  
[2024-03-14T15:44:05.083250+00:00] logger.DEBUG: CLIENT -> SERVER: .
  
[2024-03-14T15:44:05.247371+00:00] logger.DEBUG: CLIENT -> SERVER: QUIT
```  

Setting $allowInlineLineBreaks to false solved it but I don't thing this is usefull.

Using same preg_replace as 'html' and 'echo' cases would give this:
``` 
       if ($this->Debugoutput instanceof \Psr\Log\LoggerInterface) {
            $this->Debugoutput->debug(preg_replace('/[\r\n]+/', '', $str));

            return;
        }
``` 

Should I propose a PR for that ?

**Comment by Synchro** [comment]
Yes, that seems reasonable, go ahead with a PR.
