### ISSUE TITLE
postfix installation problem in PHP 5.5 test suite

### ISSUE THREAD

**Issue by Synchro** [PHPMailer/PHPMailer#3048]
I don't know if anyone else noticed, but the test suite is currently failing when running tests under PHP 5.5. The error is this:

```
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libodbc1 : Depends: libodbc2 (= 2.3.9-5) but 2.3.9-5ubuntu0.1 is to be installed
 libodbccr2 : Depends: libodbc2 (= 2.3.9-5) but 2.3.9-5ubuntu0.1 is to be installed
 unixodbc-dev : Depends: libodbccr2 (= 2.3.9-5ubuntu0.1) but 2.3.9-5 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
Failed to stop postfix.service: Unit postfix.service not loaded.
```

I have already added `--fix-broken` to the package installation line, but it doesn't help.

So, if anyone has time available and would like to contribute something useful, please have a go at fixing this!

**Comment by mehdibo** [comment]
I'd be happy to help and give it a look, are you talking about the GitHub action for PHP 5.5? I checked the last ones executed and they seem to be working fine.

**Comment by Synchro** [comment]
It does indeed appear to have gone away – maybe the upstream packaging got fixed? Oh well, at least it's working! Thanks for offering.
