### ISSUE TITLE
Can you add possibility to customized dsn by recipient ?

### ISSUE THREAD

**Issue by FlorianKnibbe** [PHPMailer/PHPMailer#3052]
Hi,

Can you add possibility to customized dsn by recipient ? Maybe with optional parameter in addAddress / addCC / addBCC.
I want to be notify for one recipient but not for all.

This is SMTP log result I wish :
```
2024-04-16 15:54:59 : CLIENT -> SERVER: RCPT TO:<xxxxxxx@xxxxx.fr> NOTIFY=SUCCESS,FAILURE,DELAY

2024-04-16 15:54:59 : SMTP INBOUND: "250 2.1.5 Recipient OK"
2024-04-16 15:54:59 : SERVER -> CLIENT: 250 2.1.5 Recipient OK

2024-04-16 15:54:59 : CLIENT -> SERVER: RCPT TO:<xxxxxxx@xxxxxx.fr>   // <-- no NOTIFY here
```

In order to modifying as little as possible your library I did this  :

```php

/**
*in PHPMailer::smtpSend()
**/

// Attempt to send to all recipients
        foreach ([$this->to, $this->cc, $this->bcc] as $togroup) {
            foreach ($togroup as $to) {
                // HERE MY UPDATE NOT CLEAN
                if(is_string($this->dsn)){
                    $dsn = $this->dsn;
                }elseif(is_array($this->dsn)){
                    if(array_key_exists($to[0],$this->dsn)){
                        $dsn = $this->dsn[$to[0]];
                    }else{
                        $dsn = '';
                    }
                }
                // END UPDATE NOT CLEAN
                if (!$this->smtp->recipient($to[0], $dsn )) {
                    $error = $this->smtp->getError();
                    $bad_rcpt[] = ['to' => $to[0], 'error' => $error['detail']];
                    $isSent = false;
                } else {
                    $isSent = true;
                }

                $callbacks[] = ['issent' => $isSent, 'to' => $to[0]];
            }
        }
        
        /**
        * in my call
        */
        $mail->AddAddress('myRecipientMail1');
        $mail->addBCC('myRecipientMail2');
         $mail->dsn = ['myRecipientMail1'=>'SUCCESS,DELAY,FAILURE'];

```

Thanks a lot
Best regards

**Comment by Synchro** [comment]
This seems like an unusual requirement; Why you would want to do this? You can achieve it by sending each message separately. Is this well-supported on mail servers?

**Comment by FlorianKnibbe** [comment]
If I use, it's usual for me ^^. I need this for 2 reasons :
in 1 hand in order to limit smtp call when we have restriction
in other hand in order to save email content sent, exactly as sent (by BCC) without received notify for BCC -> if I send separately, I can't save mail content exactly as is sent to recipient

**Comment by Synchro** [comment]
Single-use edge cases is exactly what subclassing is for.

I handle saving exact message content by putting my own address in BCC. All BCC recipients receive the exact same message without needing to use DSNs at all.

**Comment by FlorianKnibbe** [comment]
Why are you all mixing up ? DSN is Delivery Status Notification, obviously it does not affect the reception of the email and the body/content email.

If you want to save exact mail content that you sent and want to get and save his delivery status it's needed.

I proposed this little feature because I think it could be useful for others peoples in similar use case and "who can do the more, can do the less".
I understand you have others priorities and you don't want to add this because you clearly don't understand use cases. It's ok, I do this feature for my project where it's essential.

Have a good day.
Best regards.
