### ISSUE TITLE
DKIM failes when I add an AltBody

### ISSUE THREAD

**Issue by julesbl** [PHPMailer/PHPMailer#3057]
# Problem description
phpMailer 6.8.1, php v7.4
If I send the test email with just a HTML body it works fine, if I send with an AltBody as well I get a DKIM error
# Code to reproduce
		$this->emailer = new PHPMailer(true);
		if(ENVIRONMENT == 'development'){
			$this->emailer->SMTPDebug = SMTP::DEBUG_SERVER;
		}
		$this->emailer->isSMTP();
		$this->emailer->Host = $this->config->smtp_server;
		$this->emailer->SMTPAuth = true;
		$this->emailer->Username = $this->config->smtp_username;
		$this->emailer->Password = $this->config->smtp_password;
		$this->emailer->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
		$this->emailer->Port = $this->config->smtp_ssl_port;
		$this->emailer->isHTML(true);

		$this->twig = service('twig');

		$content = [
			'title' => 'Test email',
			'company_name' => 'Routastic',
		];
		$email = $this->twig->render('emails/test.twig.html', $content);
		$text = strip_a($email);
		try {
			$this->emailer->setFrom($this->config->admin_email, 'Routastic admin');
			$this->emailer->addAddress($email);
			$this->emailer->addReplyTo($this->config->admin_email, 'Routastic admin');

			$this->emailer->Subject = 'Test Email';
			$this->emailer->Body = $email;
			$this->emailer->AltBody = $text;
			$this->emailer->send();
		}catch (\Exception $e){
			trigger_error('Failed to send test email: '.$e->getMessage(), E_USER_WARNING);
			return new Error('Failed to send test email');
		}
		return true;

# Debug output
![image](https://github.com/PHPMailer/PHPMailer/assets/1729463/8e80fd89-16c4-4cd8-9bcc-d7f42c5270c4)

**Comment by julesbl** [comment]
Its configured as part of the mail sending service and is beyond my remit.
The strange thing is https://dkimvalidator.com thinks its ok but https://aboutmy.email thinks there is a problem

**Comment by XL-2000** [comment]
1. To be clear; are you using the PHPMailer signing functionality? And if so, can you share that code, just in case?
2. What does _strip_a(...)_ do? It seems you are pushing a full-blown HTML rendered mail template into a plain-text body-part

Also one thing I notice; you are using: 
```
$this->emailer->Body = $email;
$this->emailer->AltBody = $text;
```
What happens if you use:

```
$this->emailer->msgHTML($email);
$this->emailer->AltBody = $text;
```

**Comment by julesbl** [comment]
OK, tested this with several email testers and it only errors on one of them so I've reported the bug in their system to them, don't think there is anything wrong with phpMail.
Thanks for the help.
Jules
