### ISSUE TITLE
Call to undefined method SMTP::setTimeout() when using thru composer

### ISSUE THREAD

**Issue by Fuitad** [PHPMailer/PHPMailer#306]
Heya,

I'm using PHPMailer 5.2.9 via composer autoloader. When I try to send an email, I get the following error:

```
Fatal error: Call to undefined method SMTP::setTimeout() in /web/vendor/phpmailer/phpmailer/class.phpmailer.php on line 1292
```

The important parts of the call stack are:

```
0.0462     943296  10. PHPMailer->send() /web/page.php:2763
0.0466     953864  11. PHPMailer->postSend() /web/vendor/phpmailer/phpmailer/class.phpmailer.php:966
0.0467     954232  12. PHPMailer->smtpSend() /web/vendor/phpmailer/phpmailer/class.phpmailer.php:1059
0.0467     955192  13. PHPMailer->smtpConnect() /web/vendor/phpmailer/phpmailer/class.phpmailer.php:1215
```

Are you aware if there is a specific problem with the composer autoload (vendor/autoload.php) and PHPMailer? I saw that PHPMailerAutoload.php should be used but I had assumed that it wouldn't be necessary thru composer.

Thanks!

**Comment by viper007131** [comment]
i am also having this same issue

**Comment by jcodesdotme** [comment]
My project has same class names because i am revamping it. I manually loaded phpmailer and smtp classes into controller instead of using $mail = new PHPMailer etc. And it worked. So composer autoload doesn't load the correct file. Just edited classmap in vendor/composer and it is fixed.

**Comment by Synchro** [comment]
@jcodesdotme It might help others if you say what you changed.

**Comment by jcodesdotme** [comment]
Hi @Synchro ,  below is the workaround I did:

1. Open /vendor/composer/autoload_classmap.php
2. Find class.smtp.php and class.phpmailer.php in the key => value array
3. make sure their values are starting with $vendorDir, but not with $baseDir.
4. Those paths should have been set up like this:
          'PHPMailer' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
          'SMTP' => $vendorDir . '/phpmailer/phpmailer/class.smtp.php',
5. And make sure, in that array, there is no any other class.smtp.php or class.phpmailer.php except the above 2.
