### ISSUE TITLE
No SPF/DMARC/DKIM header when sending to "myself"

### ISSUE THREAD

**Issue by docjojo** [PHPMailer/PHPMailer#3061]
Hello,

I am using PHPMailer in Wordpress and am sending Test emails.
On the server SPF, DMARC and DKIM are configured.
Email delivery works fine and if I send email from the server to my private Email, all SPF, DMARC and DKIM entries are present in the header and all checks pass. So PHPMailer works fine.

However, if I send an email to "myself" – from info@ddns4free.com to info@ddns4free.com, no such headers are present.

Is there any way I can force the header to be present?

`Return-Path: <info@ddns4free.com>
Delivered-To: info@ddns4free.com
Received: from ams106.greengeeks.net
	by ams106.greengeeks.net with LMTP
	id UFDxHaUiXmZIZwAAiO224A
	(envelope-from <info@ddns4free.com>)
	for <info@ddns4free.com>; Mon, 03 Jun 2024 22:08:05 +0200
Return-path: <info@ddns4free.com>
Envelope-to: info@ddns4free.com
Delivery-date: Mon, 03 Jun 2024 22:08:05 +0200
Received: from [96.127.186.50] (port=36600 helo=ddns4free.com)
	by ams106.greengeeks.net with esmtpsa  (TLS1.2) tls TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
	(Exim 4.96.2)
	(envelope-from <info@ddns4free.com>)
	id 1sEDyR-0009Tm-1J;
	Mon, 03 Jun 2024 22:08:05 +0200
Date: Mon, 3 Jun 2024 20:08:05 +0000
To: info@ddns4free.com
From: WordPress <info@ddns4free.com>
Subject: =?UTF-8?Q?dDNS_4_free_=E2=80=93_Test_email.?=
Message-ID: <OFTmXy3MKcMBgm8fAzCeGTFibwSBITW8EtM3Tl04s@ddns4free.com>
X-Mailer: PHPMailer 6.9.1 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

dDNS 4 free – Test email.`

Thank you.
C.

**Comment by Synchro** [comment]
If you provide DKIM config (you've not shown your code so it's not clear whether you're getting PHPMailer or your mail server to do the signing), PHPMailer will sign the message – it makes no difference who it's addressed to, but your server might act differently. Set `SMTPDebug = 2` and look at what's actually being submitted to your mail server, then compare that with what arrives.

**Comment by docjojo** [comment]
Hello Synchro,

even if I use PHPMailer and private key to sign the mail, I do not get the entries in the header.
It shows the DKIM signature, but no DKIM check.

PHP Mailer Debug:

`Connection: opening to mail.ddns4free.com:587, timeout=5, options=array()
Connection: opened
SERVER -> CLIENT: 220-ams106.greengeeks.net ESMTP Exim 4.96.2 #2 Mon, 03 Jun 2024 23:35:45 +0200 
220-We do not authorize the use of this system to transport unsolicited, 
220 and/or bulk e-mail.
CLIENT -> SERVER: EHLO ddns4free.com
SERVER -> CLIENT: 250-ams106.greengeeks.net Hello ddns4free.com [96.127.186.50]
250-SIZE 52428800
250-8BITMIME
250-PIPELINING
250-PIPECONNECT
250-AUTH PLAIN LOGIN
250-STARTTLS
250 HELP
CLIENT -> SERVER: STARTTLS
SERVER -> CLIENT: 220 TLS go ahead
CLIENT -> SERVER: EHLO ddns4free.com
SERVER -> CLIENT: 250-ams106.greengeeks.net Hello ddns4free.com [96.127.186.50]
250-SIZE 52428800
250-8BITMIME
250-PIPELINING
250-PIPECONNECT
250-AUTH PLAIN LOGIN
250 HELP
CLIENT -> SERVER: AUTH LOGIN
SERVER -> CLIENT: 334 VXNlcm5hbWU6
CLIENT -> SERVER: [credentials hidden]
SERVER -> CLIENT: 334 UGFzc3dvcmQ6
CLIENT -> SERVER: [credentials hidden]
SERVER -> CLIENT: 235 Authentication succeeded
CLIENT -> SERVER: MAIL FROM:<info@ddns4free.com>
SERVER -> CLIENT: 250 OK
CLIENT -> SERVER: RCPT TO:<info@ddns4free.com>
SERVER -> CLIENT: 250 Accepted
CLIENT -> SERVER: RCPT TO:<chris.ahrweiler@mac.com>
SERVER -> CLIENT: 250 Accepted
CLIENT -> SERVER: DATA
SERVER -> CLIENT: 354 Enter message, ending with "." on a line by itself
CLIENT -> SERVER: Date: Mon, 3 Jun 2024 21:35:45 +0000
CLIENT -> SERVER: To: info@ddns4free.com
CLIENT -> SERVER: From: WordPress <info@ddns4free.com>
CLIENT -> SERVER: Cc: chris.ahrweiler@mac.com
CLIENT -> SERVER: Subject: =?UTF-8?Q?dDNS_4_free_=E2=80=93_atec_SMTP_-_Test_email.?=
CLIENT -> SERVER: Message-ID: <wh2r89B8DoWwiWeFX7IiSgYTYXHaUvOxTHpWHjRaqc@ddns4free.com>
CLIENT -> SERVER: X-Mailer: PHPMailer 6.9.1 (https://github.com/PHPMailer/PHPMailer)
CLIENT -> SERVER: MIME-Version: 1.0
CLIENT -> SERVER: Content-Type: text/plain; charset=UTF-8
CLIENT -> SERVER: Content-Transfer-Encoding: 8bit
CLIENT -> SERVER: DKIM-Signature: v=1; d=ddns4free.com; s=default;
CLIENT -> SERVER:  a=rsa-sha256; q=dns/txt; t=1717450545; c=relaxed/simple;
CLIENT -> SERVER:  h=Date:To:From:Cc:Subject:Message-ID:X-Mailer:MIME-Version:Content-Type;
CLIENT -> SERVER:  i=info@ddns4free.com;
CLIENT -> SERVER:  z=Date:Mon,=203=20Jun=202024=2021:35:45=20+0000
CLIENT -> SERVER:  |To:info@ddns4free.com
CLIENT -> SERVER:  |From:WordPress=20<info@ddns4free.com>
CLIENT -> SERVER:  |Cc:chris.ahrweiler@mac.com
CLIENT -> SERVER:  |Subject:=3D?UTF-8?Q?dDNS_4_free_=3DE2=3D80=3D93_atec_SMTP_-_Test_email.?=
CLIENT -> SERVER:  3D
CLIENT -> SERVER:  |Message-ID:<wh2r89B8DoWwiWeFX7IiSgYTYXHaUvOxTHpWHjRaqc@ddns4free.com>
CLIENT -> SERVER:  |X-Mailer:PHPMailer=206.9.1=20(https://github.com/PHPMailer/PHPMailer)
CLIENT -> SERVER:  |MIME-Version:1.0
CLIENT -> SERVER:  |Content-Type:text/plain=3B=20charset=3DUTF-8;
CLIENT -> SERVER:  bh=wTqUiUx+sjrXHnzwE9MjCt5Krm0DVg9u3EeU7V9rcek=;
CLIENT -> SERVER:  b=tHaAjZjw9+EVvZlV4KXrp6xmYfowwL8z9YQhJSSuAvY0HhDK5ZY+us7CgGKi88nlQKpRUa9O8
CLIENT -> SERVER:  VZxRObw0rTZAWgth9HASBL+LQ2JQLs503Lm4Qv6/QO7b3SQMQBuN37uBycM7/9P595BfQ3UBA
CLIENT -> SERVER:  S4qn8XtisIPiPF2IKYGhSPYlMYlta/g3btfZIFkaPQghh7d/w1bOfUTME2Htt4rMm/3NAlWhs
CLIENT -> SERVER:  AQL1MNHWV1/8/KKgEFQ+yia2d42BFx7cBPu+LUsdR6IebH2LaAZbV/iGR52SGmn1ioBUwULVB
CLIENT -> SERVER:  bq9UOyBD+/4/NjQUZ/9XRi8wkBfWS/yLXplFiOHOZF7wMvfK6Q==
CLIENT -> SERVER: 
CLIENT -> SERVER: dDNS 4 free – atec SMTP - Test email.
CLIENT -> SERVER: 
CLIENT -> SERVER: .
SERVER -> CLIENT: 250 OK id=1sEFLH-00059L-0x
CLIENT -> SERVER: QUIT
SERVER -> CLIENT: 221 ams106.greengeeks.net closing connection
Connection: closed`

Mail header:

`Return-Path: <info@ddns4free.com>
Delivered-To: info@ddns4free.com
Received: from ams106.greengeeks.net
	by ams106.greengeeks.net with LMTP
	id YJKcIDE3XmaLAgAAiO224A
	(envelope-from <info@ddns4free.com>)
	for <info@ddns4free.com>; Mon, 03 Jun 2024 23:35:45 +0200
Return-path: <info@ddns4free.com>
Envelope-to: info@ddns4free.com
Delivery-date: Mon, 03 Jun 2024 23:35:45 +0200
Received: from [96.127.186.50] (port=41636 helo=ddns4free.com)
	by ams106.greengeeks.net with esmtpsa  (TLS1.2) tls TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
	(Exim 4.96.2)
	(envelope-from <info@ddns4free.com>)
	id 1sEFLH-00059L-0x;
	Mon, 03 Jun 2024 23:35:45 +0200
Date: Mon, 3 Jun 2024 21:35:45 +0000
To: info@ddns4free.com
From: WordPress <info@ddns4free.com>
Cc: chris.ahrweiler@mac.com
Subject: =?UTF-8?Q?dDNS_4_free_=E2=80=93_atec_SMTP_-_Test_email.?=
Message-ID: <wh2r89B8DoWwiWeFX7IiSgYTYXHaUvOxTHpWHjRaqc@ddns4free.com>
X-Mailer: PHPMailer 6.9.1 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
DKIM-Signature: v=1; d=ddns4free.com; s=default;
 a=rsa-sha256; q=dns/txt; t=1717450545; c=relaxed/simple;
 h=Date:To:From:Cc:Subject:Message-ID:X-Mailer:MIME-Version:Content-Type;
 i=info@ddns4free.com;
 z=Date:Mon,=203=20Jun=202024=2021:35:45=20+0000
 |To:info@ddns4free.com
 |From:WordPress=20<info@ddns4free.com>
 |Cc:chris.ahrweiler@mac.com
 |Subject:=3D?UTF-8?Q?dDNS_4_free_=3DE2=3D80=3D93_atec_SMTP_-_Test_email.?=
 3D
 |Message-ID:<wh2r89B8DoWwiWeFX7IiSgYTYXHaUvOxTHpWHjRaqc@ddns4free.com>
 |X-Mailer:PHPMailer=206.9.1=20(https://github.com/PHPMailer/PHPMailer)
 |MIME-Version:1.0
 |Content-Type:text/plain=3B=20charset=3DUTF-8;
 bh=wTqUiUx+sjrXHnzwE9MjCt5Krm0DVg9u3EeU7V9rcek=;
 b=tHaAjZjw9+EVvZlV4KXrp6xmYfowwL8z9YQhJSSuAvY0HhDK5ZY+us7CgGKi88nlQKpRUa9O8
 VZxRObw0rTZAWgth9HASBL+LQ2JQLs503Lm4Qv6/QO7b3SQMQBuN37uBycM7/9P595BfQ3UBA
 S4qn8XtisIPiPF2IKYGhSPYlMYlta/g3btfZIFkaPQghh7d/w1bOfUTME2Htt4rMm/3NAlWhs
 AQL1MNHWV1/8/KKgEFQ+yia2d42BFx7cBPu+LUsdR6IebH2LaAZbV/iGR52SGmn1ioBUwULVB
 bq9UOyBD+/4/NjQUZ/9XRi8wkBfWS/yLXplFiOHOZF7wMvfK6Q==

dDNS 4 free – atec SMTP - Test email.

`

**Comment by Synchro** [comment]
Both the end and receive look ok to me. There is no particular obligation to add information headers to received messages, though it is common (see ARC). Whether it adds them is up to you mail server, it's not within PHPMailer's control. Presumably if it failed DKIM checks, the message would be rejected up front.

**Comment by docjojo** [comment]
DKIM check passes, if I send to my private email and mail includes full DKIM check header. It is just when I send to "myself" => sender email =receiver email  that the server handles it as an "internal" email and does not check at all.

I would probably have to install some kind of relay – so that the server is forced to check.

**Comment by Synchro** [comment]
That's what I'm saying – this is a mail server config issue, not anything PHPMailer can do anything about.

**Comment by docjojo** [comment]
Thank you. Great code, great support.
Thanks.
