### ISSUE TITLE
Namespace in PHP8

### ISSUE THREAD

**Issue by Lingchen218** [PHPMailer/PHPMailer#3062]
In PHP8, the namespace PHPMailer and the class name are the same and an error will be reported

**Comment by NiklasBr** [comment]
Sounds like you are using an old version of PHPMailer, can you show the version, error message, and perhaps your code where it happens?

**Comment by Synchro** [comment]
Indeed, there is nothing wrong with having a class and namespace that are the same. I'd like to know where you are seeing this error.

**Comment by Lingchen218** [comment]
Fatal error: Cannot declare class PHPMailer\PHPMailer\PHPMailer, because the name is already in use in

**Comment by Synchro** [comment]
That just means you have loaded the class more than once. Use composer.
