### ISSUE TITLE
Duplicate eMail on First Record in Multi Record Set

### ISSUE THREAD

**Issue by skykingisepic** [PHPMailer/PHPMailer#3097]
This is a caused by $mail->addAddress($result['email']); adding cumulative addresses each time it's called in a While loop. How do I reset it after sending mail to use only the one address in each record?

**Comment by Synchro** [comment]
Best solution is to [read the docs on sending to lists](https://github.com/PHPMailer/PHPMailer/wiki/Sending-to-lists).

**Comment by skykingisepic** [comment]
Thanks, I did find the ClearAddresses() and added it to solve the problem so I closed the issue.
