### ISSUE TITLE
Strange body behavior

### ISSUE THREAD

**Issue by jacovig** [PHPMailer/PHPMailer#3107]
After hours of debugging and simplifying, I've identified the following issue:

When I have this simple body (extracted from a long text written by a user, who forgot one slash):
'http:/tiny.cc/something'

I get this error message:

SMTP Error: data not accepted.SMTP server error: DATA END command failed Detail: 3jhwtMREjkhQK Spam Rejected SMTP code: 550 Additional SMTP info: 5.2.0

When I simply change the body, and add the missing slash, like this:
'http://tiny.cc/something'

then, the mail gets sent without a problem.

Version is 6.9.2, but the problem is the same with older versions.

I don't know how to solve this. I can't control what users might write.

Any help would be appreciated.

Thanks in advance.

**Comment by Synchro** [comment]
Unfortunately this is entirely down to the spam filter on the server. Spam filters are entirely un-standardised, arbitrary, and often destructive to the point of not being workable, and it looks like you're running into an instance of that. I can only suggest that you filter your content first. PHPMailer doesn't get involved in that, it just sends whatever body you give it.
