### ISSUE TITLE
Question: SMTP connect() fail

### ISSUE THREAD

**Issue by dogslife** [PHPMailer/PHPMailer#3109]
I think PHPMailer is great and use it regularly.
But I've come across a problem. 
I appreciate this is not PHPMailer issue per se but when an SMPT connect() fails, PHPMailer 6.8.0 throws an exception, stopping the whole process & my PHPscript. Is there a way in PHPMailer to CATCH the SMPT server being unavailable (due to crash etc) and allow me to handle it more gracefully?
Thanks in advance but apologies if this has already been answered

**Comment by Synchro** [comment]
PHPMailer only throws exceptions if you tell it to by passing `true` to the constructor. Like anything that throws exceptions, you can wrap it in a try/catch block, catch the exceptions and do whatever you like. See [the exceptions example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/exceptions.phps) for how to do it.
