### ISSUE TITLE
Microsoft OAUTH: how to get resource owner email from token?

### ISSUE THREAD

**Issue by br4nnigan** [PHPMailer/PHPMailer#3110]
the [tutorial](https://github.com/PHPMailer/PHPMailer/wiki/Microsoft-Azure-and-XOAUTH2-setup-guide) is nicely written, except that a hard coded e-mail is used to connect. But it would surely be nice if we could obtain the e-mail address the user used to authenticate automatically to use with the token.

I would have expected that this works: 

	$authUrl = $provider->getAuthorizationUrl([
	  'scope' => [
	    'https://outlook.office.com/SMTP.Send',
	    'offline_access',
	    'https://outlook.office.com/User.Read' # <----added this
	  ]
	]);

...

	$token = $provider->getAccessToken(
	  'authorization_code',
	  [
	    'code' => $_GET['code']
	  ]
	);
	$provider->getResourceOwner($token); # <---- this fails

but I'm getting `"InvalidAuthenticationToken","message":"Access token is empty."`

**Comment by Synchro** [comment]
This all happens outside PHPMailer, so I suggest you ask in the provider project, and Microsoft's docs; I really have no idea about Azure features.

**Comment by decomplexity** [comment]
Two questions:
- your access token may really be null or it may not contain any valid  claims. What is returned if you paste the token into jwt.ms? If anything, then what is the AUD claim value?
- are you returned an apparently valid token if you omit the User.Read scope, and will it then authenticate with SMTP successfully?
