### ISSUE TITLE
Emails are not arriving with PHPMailer but with same SMTP details, the emails are arriving when using a tool.

### ISSUE THREAD

**Issue by mayankbhaisora** [PHPMailer/PHPMailer#3112]
I am using PHPMailer to send emails.. 
I am getting all correct statuses in the response but emails are not arriving.

However when i use the same SMTP details using Thunderbird tool, the emails are arriving. I am not sure what to check in this situation.

If it was some server configuration related issue, the SMTP tools like Thunderbird and Mail apps should not work either but emails are getting received using those tools but not from PHP code.

This is my code
`.      $phpmailer = new PHPMailer();
        $phpmailer->SMTPDebug = SMTP::DEBUG_SERVER;
        $phpmailer->isSMTP();

        $phpmailer->Host = MAILHOST;
        $phpmailer->SMTPAuth = true;
        $phpmailer->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
        $phpmailer->Port = 465;
        // $phpmailer->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
        // $phpmailer->Port = 587;
        $phpmailer->Username = USERNAME;
        $phpmailer->Password = PASSWORD;
        $phpmailer->From = SEND_FROM;
        $phpmailer->setFrom(SEND_FROM, 'John Doe');

        $phpmailer->addAddress($toEmail);
        $phpmailer->Subject = $subject;
        $phpmailer->Body = $body;
        $phpmailer->send();`

**Comment by Synchro** [comment]
You are not doing any error checking here, nor showing any debug output, so it's not clear how you know it's sending successfully. Look at the examples for how to do this. After submission, PHPMailer's involvement ends, and it's up to `MAILHOST` what happens to your message, so the next step would be to check the mail server logs.

**Comment by XL-2000** [comment]
provide some debug logging to begin with, and add some error checking

**Comment by mayankbhaisora** [comment]
I have enabled debugging like this
$phpmailer->SMTPDebug = SMTP::DEBUG_LOWLEVEL;

That is just a part of the code to understand if I am missing something?
As you said "After submission, PHPMailer's involvement ends, and it's up to MAILHOST what happens to your message, so the next step would be to check the mail server logs"

I am getting email log on server and it also shows accepted and email doesn't arrive but the thing is that with same SMTP details, I am able to receive the emails when i use Thunderbird SMTP tool.

I know it's sending successfully because the status from send function is true and the debug logs of PHPMail also succeeds -
.
.
.
2024-11-14 18:37:51 SERVER -&gt; CLIENT: 250 OK id=1tBej7-00ENks-0r
<br>
2024-11-14 18:37:51 CLIENT -&gt; SERVER: QUIT
<br>
2024-11-14 18:37:51 SERVER -&gt; CLIENT: 221 phobos.o2switch.net closing connection



This is the email log i sm getting at server, I have only replaced the email ids and ip with dummy values. As you can see that the email is accepted by server -

My reason to raise the issue here is because the SMTP tools like Thunderbird and Mail app are able to send  the emails using same SMTP details that I am using with PHPMailer.
 

Événement: success success
Utilisateur: cptehebs
Domaine: [example.domain](http://example.domain/)
Adresse de l’expéditeur: abc@example.domain
Expéditeur: abc@example.domain
Heure d’envoi: 14 nov. 2024, 18:16:18
Hôte de l’expéditeur: [abc@example.domain](http://abc@example.domain/)
Adresse IP de l’expéditeur: <ip_address>
Authentification: dovecot_login
Score spam:
Destinataire: my_email_id@gmail.com
Nom d’utilisateur du destinataire: -remote-
Domaine de remise:
Remis à: my_email_id@gmail.com
Routeur: dkim_lookuphost
Transfert: dkim_remote_smtp
Heure de réception: 14 nov. 2024, 18:16:18
ID: 1tBdS3-00CdXs-1q
Hôte de remise: [smtp.jabatus.fr](http://smtp.jabatus.fr/)
Adresse IP de remise: <ip_address>
Taille: 707 octets
Résultat: Accepté

**Comment by mayankbhaisora** [comment]
I quickly created a sample macOS app in Swift and used SwiftSMTP to send mails using same SMTP details and the emails are arriving on the destination address.

The configurations are same even it didn't require any other settings to change. I am using the same system for both PHP and Swift project but somehow the emails from PHPMailer are not arriving.

let smtp = SMTP(
            hostname: smtpHost,
            email: username,
            password: password,
            port: smtpPort,
            tlsMode: .requireTLS,
            authMethods: [.plain, .login],
            domainName: "localhost"
        )
        
        let from = Mail.User(email: fromEmail)
        let to = Mail.User(email: toEmail)
        
        let mail = Mail(
            from: from,
            to: [to],
            subject: subject,
            text: emailBody
        )
        
        smtp.send(mail) { (error) in }

**Comment by Synchro** [comment]
As you say, the fact you get a `250 OK` means that the server accepted your message, but the log you showed is PHPMailer's debug output, not your mail server's logs which will show what happened to the message *after* it was accepted by the server.
