### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [PHPMailer/PHPMailer#3116]
Dear @PHPMailer team, @Synchro,

It will be nice to remove old parts like:
- https://sourceforge.net/p/phpmailer/mailman/
- https://sourceforge.net/p/phpmailer/code/
- https://sourceforge.net/p/phpmailer/_list/tickets
- https://sourceforge.net/p/phpmailer/news/
- https://sourceforge.net/p/phpmailer/discussion/

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/phpmailer/

To disable/delete tabs, go here: https://sourceforge.net/projects/phpmailer/
To add a new tab, go here: https://sourceforge.net/projects/phpmailer/
To change informations, go here: https://sourceforge.net/p/phpmailer/admin/overview
To export, go here: https://sourceforge.net/p/phpmailer/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/phpmailer/admin/overview
- A new tab, go here: https://sourceforge.net/projects/phpmailer/

Thanks in advance.

**Comment by Synchro** [comment]
That is indeed a load of very old stuff! Thanks for bringing it to my attention!

**Comment by Synchro** [comment]
I've cleaned up some of those, but it doesn't seem possible to delete some things. At least it now has the "moved" box.

**Comment by Neustradamus** [comment]
@Synchro: Thanks for your quick answer!

But can you look in the interface, it is easy to remove tabs, etc.

I have already done easily, you must to be connected on the project page and click on the padlock at right, and click on gear on each tabs...
Of course, you can do an export before, all is noted in my text.

Thanks in advance.

**Comment by Neustradamus** [comment]
@Synchro: In more, you can add the logo ;)

**Comment by Neustradamus** [comment]
The last point that I have not talked before, you can clean the "Files" section, you must to launch a SFTP connection to do it, doc:
- https://sourceforge.net/projects/phpmailer/files/

Doc: https://sourceforge.net/p/forge/documentation/SFTP/
web.sourceforge.net
ID / password

**Comment by Neustradamus** [comment]
@Synchro: I wish you a Happy New Year 2025!

I think that you can remove the "Inactive" term here:
- https://sourceforge.net/projects/phpmailer/

**Comment by Synchro** [comment]
As far as I can see, that's not possible. This is what it says if you move your project elsewhere, which is what has happened. The only other alternatives are to make it active, mark it as abandoned, or to delete it altogether, none of which are preferable.

<img width="399" alt="image" src="https://github.com/user-attachments/assets/dca07ac6-ddb9-45ca-9b89-110d6e2f76fe" />

**Comment by Neustradamus** [comment]
@Synchro: It is strange other projects have not the mark, can you temporary try "Active Project", look the main page if it changes?

**Comment by Neustradamus** [comment]
@Synchro: It is strange other projects have not the mark, can you temporary try "Active Project", look the main page if it changes?

Example: https://sourceforge.net/projects/bzip2/
