### ISSUE TITLE
Copyright information is not included in LICENSE file

### ISSUE THREAD

**Issue by nok-ko** [PHPMailer/PHPMailer#3122]
https://github.com/PHPMailer/PHPMailer/blob/2f5c94fe7493efc213f643c23b1b1c249d40f47e/LICENSE#L474

This line has been left blank, not indicating from whom the software is licensed when redistributed (who holds the copyright.) It would be good to include this information in the license file itself.

Thank you for your work on PHPMailer!

**Comment by Synchro** [comment]
That's not what it asks for; the copyright doesn't belong in the license file, but in the source files. It says:

> To apply these terms, attach the following notices to the library.  It is
safest to attach them to the start of each source file to most effectively
convey the exclusion of warranty; and each file should have at least the
"copyright" line and a pointer to where the full notice is found.

and that's exactly what we do, for example [here](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L13):

```php
 * @copyright 2012 - 2020 Marcus Bointon
 * @copyright 2010 - 2012 Jim Jagielski
 * @copyright 2004 - 2009 Andy Prevost
 * @license   https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html GNU Lesser General Public License
```
