### ISSUE TITLE
Workaround for brain-damaged servers when sending mails with attachments

### ISSUE THREAD

**Issue by kiwileaks** [PHPMailer/PHPMailer#316]
I found some legacy (receiver-side) mail servers silently reject my emails with attachments.
I tested the same files with Thunderbird to have success.
I found the difference is lack of some dummy text before the MIME "boundary".

PHPMailer 5.2.9:
```
--<boundary>
Content-Type: ......
```
Thunderbird:
```
This is a multi-part message in MIME format.
--<boundary>
Content-Type: ......
```
I can now send attachments with the changes below (simulating Thunderbird's behavior):
```
1709c1709
<             /*$result .= $this->headerLine(
---
>             $result .= $this->headerLine(
1712c1712
<             );*/
---
>             );
1842d1841
<                 $body .= "This is a multi-part message in MIME format.\n";
```

**Comment by Synchro** [comment]
I've added a fix for all message types in the branch linked above. Please could you give it a try and let me know if it works for you.
