### ISSUE TITLE
Fatal error: Class 'SMTP' not found in .. 

### ISSUE THREAD

**Issue by adminskid** [PHPMailer/PHPMailer#334]
soo i get this error Fatal error: Class 'SMTP' not found in /Applications/XAMPP/xamppfiles/htdocs/stresser/omega/mail/class.phpmailer.php on line 1196

but i have. could you guys please help me thanks.

require './mail/PHPMailerAutoload.php';
$mail = new PHPMailer;

**Comment by shivugu** [comment]
I have to say thank you. I have been trying to send emails from localhost only getting errors till i followed Synchro's responses to this issue.
Thank you.

**Comment by atikurahman** [comment]
I have the same error. I put all the classes in the same location. Whenever  I try to send mail it gives me following error: Class 'SMTP' not found in [.../xampp7\htdocs\dhingi.dev\app\Vendor\PhpMailer\class.phpmailer.php, line 1291

What could be the wrong? Please help.

**Comment by atikurahman** [comment]
I am using CakePHP v2.63

**Comment by Synchro** [comment]
That tells me that you're not using the autoloader. Please read the readme and the rest of this ticket.

**Comment by gitpmjj** [comment]
I had the same problem in other line of my code in class.phpmailer.php.

I found a problem in line 1443.

 public function getSMTPInstance()
    {
        if (!is_object($this->smtp)) {
            $this->smtp = new smtp;  //Here is the problem !!!
        }
        return $this->smtp;
    }

There are no parenthesis when creating the object.

Now other problem: It´s missing the include line before the class.

include_once 'class.smtp.php';

I run my code and now its ok.

Im not sure if i helped you but i tried to.

**Comment by Synchro** [comment]
Parentheses are not needed if you're not passing any params to the constructor.

You don't need the include if you're using the autoloader, as you should be.

**Comment by payalpadiya** [comment]
pls help me i m having the problem

have tried all the above things
Fatal error: Class 'smtp' not found in /Applications/XAMPP/xamppfiles/htdocs/PHPMailer/class.phpmailer.php on line 1443

**Comment by Synchro** [comment]
So what happened when you set a breakpoint in the autoloader?

**Comment by jesuspreethi** [comment]
I have also same problem.. Fatal error shown..Now Fixed my problem! 
All I had to do was comment out $mail->IsSMTP();
this is my code
<?php
require 'phpmailer/class.phpmailer.php';
include 'phpmailer/class.smtp.php';

$mail = new PHPMailer;
 
//$mail->isSMTP();   //  ---> Comment this line mail will send
$mail->Host = 'smtp.gmail.com';
$mail->SMTPAuth = true;
$mail->Username = 'jesuspreethi03@gmail.com';
$mail->Password = "myjesusmysaviour";
$mail->SMTPSecure = 'tls';
$mail->Port = 587;
 
$mail->From = 'jp@gmail.com';
$mail->FromName ='J P';
$mail->addAddress('tesr1@gmail.com', 'name');
 
$mail->addReplyTo('sample@gmail.com', ' name ');
 
$mail->WordWrap = 50;
$mail->isHTML(true);
 
$mail->Subject = 'Using PHPMailer';
$mail->Body    = 'Hi Iam using PHPMailer library to sent SMTP mail from localhost';
 
if(!$mail->send()) {
   echo 'Message could not be sent.';
   echo 'Mailer Error: ' . $mail->ErrorInfo;
   exit;
}
 
echo 'Message has been sent';
?>
check here https://teamtreehouse.com/community/why-am-i-getting-this-error-phpmailer

**Comment by Synchro** [comment]
@jesuspreethi - That's not a fix - you're "fixing" your SMTP config by not using SMTP! The SMTP class is **required** if you're going to use SMTP, so use `require`, not `include`, and deal with the error if the class isn't found. It would help if you read the README which tells you exactly what files are needed and how to load them properly, and all the examples provided also do it correctly. It also looks like you've based your code on an obsolete example, so make sure you're running latest PHPMailer.
