### ISSUE TITLE
php_network_getaddresses: getaddrinfo failed: No address associated with hostname (0)

### ISSUE THREAD

**Issue by romuloinnocencio** [PHPMailer/PHPMailer#340]
2014-12-30 23:54:03	SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: No address associated with hostname (0)
SMTP connect() failed.

What's this means?

I try to my domain, jscomunicacaovisual.com;
I created a email. contato@jscomunicacaovisual.com

-----

	require_once('class.phpmailer.php');

	/*abaixo as veriaveis principais, que devem conter em seu formulario*/
	$nomeDestinatario = 'JS Comunicação Visual';
	$destinatarios = 'contato@jscomunicacaovisual.com';
	$usuario = 'contato@jscomunicacaovisual.com';
	$senha = '*********';

/*********************************** A PARTIR DAQUI NAO ALTERAR ************************************/

	$To = $destinatarios;
	$Subject = $assunto;
	$Message = $dados;

	$Host = 'smtp.'.substr(strstr($usuario, '@'), 1);

	$Username = $usuario;
	$Password = $senha;
	$Port = "587"; 

	$mail = new PHPMailer();
	$body = $dados;

	$mail->CharSet = 'UTF-8';

	$mail->IsSMTP(); // telling the class to use SMTP
	$mail->Host = $Host; // SMTP server
	$mail->SMTPDebug = 1; // enables SMTP debug information (for testing) // 1 = errors and messages // 2 = messages only
	$mail->SMTPAuth = true; // enable SMTP authentication
	$mail->Port = $Port; // set the SMTP port for the service server
	$mail->Username = $Username; // account username
	$mail->Password = $Password; // account password

	$mail->SetFrom($usuario, $nomeDestinatario);
	$mail->Subject = $Subject;
	$mail->MsgHTML($body);
	$mail->AddAddress($To,'');

	/* ENVIO */

	if( !$mail -> Send() ){
		return mail;
	} else { 
		return 1;
	}

**Comment by Synchro** [comment]
It means that either the address you are trying to connect to does not have a DNS entry, or your DNS is not working. Please read [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting). You also need to update your PHPMailer.
