### ISSUE TITLE
AddEmbeddedImage In Hotmail Outlook.com

### ISSUE THREAD

**Issue by ZoIcHi** [PHPMailer/PHPMailer#344]
hi
first of all congratulations for this class.

as you read the title, I can not get to see Images on outlook.com.

I did several tests and tried on other webmail (gmail, yahoo, etc..) and the images here are loaded, only outlook.com, are not loaded.

Below is an example of the code genereted from outlook.com:

```html
<img width="20" height="20" border="0" src="https://OSVCidNameSocialFs">

--b1_d0c13b53ccf0a5867d82b6509b6f0b95
Content-Type: image / jpg; name = "ImmagineSocIs"
Content-Transfer-Encoding: base64
Content-ID: <OSVCidNameSocialIs>
Content-Disposition: inline; filename = ImmagineSocIs

/ 9j / 4QAYRXhpZgAASUkqAAgAAAAAAAAAAAAAAP etc ...
```
And this is the code that I created:

```php
<img src='cid:OSVCidNameSocialIs' width='20' height='20' border='0'/>

$mail->AddEmbeddedImage("".$_SERVER['DOCUMENT_ROOT']."/folder/work/images/social_mail-issuu.jpg", "OSVCidNameSocialIs", "ImmagineSocIs", "base64", "image/jpg"); 
```
I do not understand what is the problem ...

**Comment by Synchro** [comment]
Check that the generated message is formatted correctly - you can get a copy of the message by doing this just before you send:

```php
$mail->preSend();
$message = $mail->getSentMIMEMessage();
```
`$message` will then contain a copy of the message. If there is any difference between this and what you see in outlook, then it's outlook that is making the changes.

**Comment by ZoIcHi** [comment]
I'm sorry, but I did not understand, where I have to enter the code.
This is my code for sending:

require_once($rootWeb."includes/class_mail/class.phpmailer.php");  
$mail             = new PHPMailer();
$mail->IsMail();
$mail->SetLanguage("it");
$mail->IsHTML(true);
$mail->From       = $Co_Email;
$mail->FromName   = $Company;
$mail->AddReplyTo($Co_Email,$Company);
$mail->Subject    = html_entity_decode($oggettoNews);	

$bodyMsg = str_replace('{MEMBER_ID}', $userid, $messaggio);
$bodyMsg = str_replace('{MEMBER_EMAIL}', $mailuser, $bodyMsg);

$mail->MsgHTML($bodyMsg); // ---> I use this before, used this $mail->Body = $bodyMsg;

---> correct?
$mail->preSend();
$bodyMsg = $mail->getSentMIMEMessage();

$mail->AddAddress($destinatario);

thanks for your patience

**Comment by Synchro** [comment]
Update your PHPMailer - you are using an old version.

In your code you should have something like:

```php
if (!mail->send()) {...
```
Add this just before that:

```php
$mail->preSend();
$bodyMsg = $mail->getSentMIMEMessage();
echo $bodyMsg;
```

It will make a mess, but you will be able to see the exact text that is being sent - if it is different to what you receive, then outlook is altering your message's content.

**Comment by ZoIcHi** [comment]
Tnx, 
I try now!!!

PHPmailer is updated, Why do you say that I'm using an old version?

Should I call "PHPMailerAutoload.php", instead of "class.phpmailer.php"?

Or did you see other errors in my code?

**Comment by Synchro** [comment]
Yes, you should load the autoloader. If you're sending via SMTP and you only include the phpmailer class, it will break in recent versions, so if it's not breaking, you're not using a recent version. Also all your method calls start with capitals - this was fixed quite a long time ago in all the code, examples and documentation, so it looks like your own code is based on old examples.

**Comment by ZoIcHi** [comment]
I insert the code, but there are differences.

I tried with email simpler, with only a picture, but on hotmail (outlook online), the images are not loaded.

But on pc, outlook softaware installed, the images are downloaded.

... bo!!!

**Comment by Drynn** [comment]
Hi!, you should use as cid the absolut direction of the image and it will work in outlook.com too

**Comment by ZoIcHi** [comment]
So you should not use the CID (AddEmbeddedImage)?

In this case, there is a variaible, if the mail outlook notes, use the absolute address?

I tried, for css the "gte mso", but did not work well. So I do not know if it works with this problem.

**Comment by Drynn** [comment]
For me it's work in outlok.com and outlook programme
$mail->AddEmbeddedImage("img/Logotxt.png", "http://.../img/Logotxt.png", "img/Logotxt.png", "base64", "image/png");
<img src='cid:http://.../img/Logotxt.png'>

**Comment by ZoIcHi** [comment]
I tried this solution,  but I do not work. Now the picture is not seen anywhere.
This is my code:

<pre>
$mail->AddEmbeddedImage("images/logo_newsletter.jpg", "".$Co_Web."images/logo_newsletter.jpg", "images/logo_newsletter.jpg", "base64", "image/jpg");

or

$mail->AddEmbeddedImage("".$Co_Web."images/logo_newsletter.jpg", "".$Co_Web."images/logo_newsletter.jpg", "".$Co_Web."images/logo_newsletter.jpg", "base64", "image/jpg");

or

$mail->AddEmbeddedImage("".$Co_Web."images/logo_newsletter.jpg", "mysite.com/images/logo_newsletter.jpg", "ImmagineLogo", "base64", "image/jpg");

the html image

img src='cid:".$Co_Web."images/logo_newsletter.jpg' alt='Logo' data-embeded='auto' style='vertical-align: top; border: 0px none transparent; border-radius: 0px; width: 330px;' width='330'
</pre>

Where $Co_Web, equals http://www.mysite.com/

When the email arrives, the picture is not seen. And when I click on the browser "open image", the URL image is this
<pre>cid:http://www.mysite.com/images/logo_newsletter.jpg</pre>
but the image url, it should look like this (gmail):
<pre>gm1.ggpht.com/Qi1F6XkD2B81eFU9ac9KhkEj6nu_G-SPU1Oio_5UkmB5PLzh3Ejr1F2TovMcYrOgfk6ZbePbdRGS2NkNM0mY1sZsoknvYwsglDTSceLQujpse6zyNyb_jLI7BwwvkWlvbJ3fdDyoHm8p8SjcozsWW5pFq6cOEkauYJS0UEtNQ-CzPeWVkW1HLqDazicDj-gQs57-DDTQ1zDVhj3eVlOlq0ONcV1EgAQmkZREXcmpfo0gmgJG12DY_bjLRdddDC61FhIxvM4k3zPUDwfY5rtFuK3YxB30tgMSuvRBj9wQx2kzmj46f0KJi00z0ofvJQPumtIbQIcl-UtKz8AtlUyml_ilxL-6rZCOAeLXxSwWv_uThp4tBRFae1Pf-pARU7qd4kxZIs_lV1ZjUEGB0nxvpqaZLMO3sb2t3G8QiA7-M7MBQFTzcHCcQ-fjxaLieChvDuX2xxnqsWQmy4HPVKTgmjcnjK6VL</pre>

The strange thing is that Outlook always uses the url https:
<pre>https://cid:http://www.mysite.it/images/logo_newsletter.jpg</pre>

What is wrong?

**Comment by Synchro** [comment]
Using an external URL as the cid seems like a really bad idea, given that both outlook and hotmail are horribly buggy in URLs handling. Also your HTML quoting is a bit messed up. 

Normally you'd use a simple string that doesn't look like a URL, and the easiest way to make a unique one is to just hash it - `md5` will do fine. Something like this:

```php
$path = 'images/logo_newsletter.jpg';
$cid = md5($path);
$mail->AddEmbeddedImage($path, $cid, 'ImmagineLogo');
```

Then in your HTML:

```html
<img src="cid:<?php echo $cid; ?>" alt="Logo" data-embeded="auto" style="vertical-align: top; border: 0px none transparent; border-radius: 0px; width: 330px;" width="330">
```

The point of all this is that a `cid` protocol URL refers to a resource within the current message, not somewhere else. If you want to point at an image somewhere else, just put the URL in your image tag directly; you don't need to embed it.

**Comment by Synchro** [comment]
Note that you can avoid all of this messing about with cids by setting your content with the `msgHTML()` function. If you provide you local image path it will automatically embed images and set cids for you.

**Comment by ZoIcHi** [comment]
Thanks Synchro.
Finally, after cleaned the code and used correctly function 'msgHTML()' , the e-mails see good everywhere, with CIDS inserted automatically.

And now, another question / advice :p
In the email I put a tracker in this way:

<pre>
img src='".$Co_Web."admin/mailtracker.php?newsid=$idx_newsl&userid={MEMBER_ID}' data-embeded='auto' width='1' height='1' border='0' /
</pre>

The "image" is downloaded almost always.

The other times, the mail client or software, blocks the download and download it manually.
There is a method to optimize this?

Thanks again for the support !!!!

**Comment by Synchro** [comment]
There's not much you can do about that. Some ISPs (particularly gmail) are getting quite aggressive about pre-caching email images so it's becoming harder to track opens.

**Comment by ZoIcHi** [comment]
Alternatives?!?

**Comment by Synchro** [comment]
Live without it? Rely on redirected clicks for tracking.

**Comment by gatogeek** [comment]
Please post code with function msgHTML(), thank you.

**Comment by Synchro** [comment]
[The code in the unit tests](https://github.com/PHPMailer/PHPMailer/blob/master/test/phpmailerTest.php#L787) shows how it's used - just pass in your HTML body and a path to your images.

**Comment by zenas101** [comment]
@ Synchro 
pleas can you help me out here am trying to get this thing right but it get hard ,

i wrote a mailer using phpmailer every thing works well but one thing, if i send mail using html the images in the email does not show can you advice please thanks.

here is my code below:

<?php
ob_start();
?>
<?php

if ( $_POST['submit'] == "Send" ) {
 
  if ( $_POST['editor1'] == '' ) {
      +$body             = file_get_contents('contents.html');  } else {
		  
       $body = $_POST['editor1'] ;
  }
 


   $to = $_POST['To_Email'];
    if(filter_var($to, FILTER_VALIDATE_EMAIL) === FALSE) {
     $error="Email address " . $to . " is invalid -- aborting!";
	   		header('location: index.php?lgin=Mailer Is Ready&sent=Mail Not Sent&typ=Using '.strtoupper($_POST['test_type']).'&errmsg='.$error);

    }
	
require_once('PHPMailerAutoload.php');


$PHPmailer = new PHPMailer(true);
  

	
	  if ( $_POST['test_type'] == "smtp" ) {
    $PHPmailer->IsSMTP();  // telling the class to use SMTP
    $PHPmailer->SMTPDebug  = $_POST['smtp_debug'];
    $PHPmailer->SMTPAuth   = $_POST['smtp_authenticate'];     // enable SMTP authentication
    $PHPmailer->Port       = $_POST['smtp_port'];             // set the SMTP port
    $PHPmailer->Host       = $_POST['smtp_server'];           // SMTP server
    $PHPmailer->Username   = $_POST['authenticate_username']; // SMTP account username
    $PHPmailer->Password   = $_POST['authenticate_password']; // SMTP account password

	  if ( $_POST['Secure'] == "ssl" ) {
 	$PHPmailer->SMTPSecure = 'ssl'; // SMTP Secure ssl
	}

	  if ( $_POST['Secure'] == "tls" ) {
	$PHPmailer->SMTPSecure = 'tls'; // SMTP Secure tls
}

	

	
  } elseif ( $_POST['test_type'] == "mail" ) {
    $PHPmailer->IsMail();      // telling the class to use PHP's Mail()
  } elseif ( $_POST['test_type'] == "sendmail" ) {
    $PHPmailer->IsSendmail();  // telling the class to use Sendmail
  } elseif ( $_POST['test_type'] == "qmail" ) {
    $PHPmailer->IsQmail();     // telling the class to use Qmail
  }
  
  
	if ( $_POST['From_Name'] != '' ) {
	$PHPmailer->SetFrom($_POST['From_Email'],$_POST['From_Name']);
  } else {
	$PHPmailer->SetFrom($_POST['From_Email'],$_POST['From_Email']);
  }  
      	if ( $_POST['rplto_Email'] != '' ) {
			
	$PHPmailer->AddReplyTo($_POST['rplto_Email']);
  } else {
	$PHPmailer->AddReplyTo($_POST['From_Email'],$_POST['From_Name']);
  }


    if ( $_POST['To_Name'] != '' ) {
    $PHPmailer->AddAddress($to,$_POST['To_Name']);
  } else {
    $PHPmailer->AddAddress($to);
	 
  }

    if ( $_POST['bcc_Email'] != '' ) {
    $indiBCC = explode(" ", $_POST['bcc_Email']);
    foreach ($indiBCC as $key => $value) {
      $PHPmailer->AddBCC($value);
    }
  } 

 	 if ( $_POST['cc_Email'] != '' ) {
    $indiCC = explode(" ", $_POST['cc_Email']);
    foreach ($indiCC as $key => $value) {
      $PHPmailer->AddCC($value);
    }
	
  } 
    if ( $_POST['Subject'] != '' ) {
   		 $PHPmailer->Subject  = $_POST['Subject'];
  } else {
   		 $PHPmailer->Subject  = ('New Massage'.' ' . date("Y-m-d h:i:sa"));
  }


   require_once('class.html2text.inc.php');
	  $h2t =& new html2text($body);
	  $PHPmailer->AltBody = $h2t->get_text();
	  $PHPmailer->WordWrap   = 80; // set word wrap  
	  $PHPmailer->IsHTML(true); // send as HTML
 	  $PHPmailer->MsgHTML($body);
/*  
	  if(isset($_POST['xmailer'])){
	$PHPmailer->X-Mailer('Microsoft Outlook, Build 15.0.'.time('s'));
		  }*/


	  
if (isset($_POST['attach1'])){		
		
if (isset($_FILES['attach1']) &&
    $_FILES['attach1']['error'] == UPLOAD_ERR_OK) {
    $PHPmailer->AddAttachment($_FILES['attach1']['tmp_name'],
                         $_FILES['attach1']['name']);
}
}  

if (isset($_POST['attach2'])){		
		
if (isset($_FILES['attach2']) &&
    $_FILES['attach2']['error'] == UPLOAD_ERR_OK) {
    $PHPmailer->AddAttachment($_FILES['attach2']['tmp_name'],$_FILES['attach2']['name']);
}
}
if (isset($_POST['attach3'])){		
		
if (isset($_FILES['attach3']) &&
    $_FILES['attach3']['error'] == UPLOAD_ERR_OK) {
    $PHPmailer->AddAttachment($_FILES['attach3']['tmp_name'],
                         $_FILES['attach3']['name']);
}
}

if (isset($_POST['attach4'])){		
		
if (isset($_FILES['attach4']) &&
    $_FILES['attach4']['error'] == UPLOAD_ERR_OK) {
    $PHPmailer->AddAttachment($_FILES['attach4']['tmp_name'],
                         $_FILES['attach4']['name']);
}
}

if (isset($_POST['attach5'])){		

		
if (isset($_FILES['attach5']) &&
    $_FILES['attach5']['error'] == UPLOAD_ERR_OK) {
    $PHPmailer->AddAttachment($_FILES['attach5']['tmp_name'],
                         $_FILES['attach5']['name']);
}
}

if (isset($_POST['attach6'])){		
		
if (isset($_FILES['attach6']) &&
    $_FILES['attach6']['error'] == UPLOAD_ERR_OK) {
    $PHPmailer->AddAttachment($_FILES['attach6']['tmp_name'],
                         $_FILES['attach6']['name']);
}
}
    try {
    if ( !$PHPmailer->Send() ) {
      $error = "Unable to send to: " . $to;
	  	 
 		header('location: index.php?lgin=Mailer Is Ready&sent=Mail Not Sent&typ=Using '.strtoupper($_POST['test_type']).'&errmsg='.$error);
    } else {
        $sents= 'Message has been sent using '.strtoupper($_POST['test_type']) ;

  header('location: index.php?lgin=Mailer Is Ready&sent=Massage Sent&typ=Using '.strtoupper($_POST['test_type']).'&errmsg='.$sents);
    }
  }
  catch (phpmailerAppException $e) {
  $senm= ' '. $errorMsg[] = $e->errorMessage();
		      header('location: index.php?lgin=Mailer Is Ready&sent=Massage Sent&typ=Using '.strtoupper($_POST['test_type']).'&errmsg='.$senm);

  }	
	

}
?>
<?php
ob_end_flush();
?>

**Comment by Synchro** [comment]
Please don't post unrelated comments on closed posts. You are not using AddEmbeddedImage.
Handle your uploads correctly: look at [the examples](https://github.com/PHPMailer/PHPMailer/tree/master/examples) provided with PHPMailer, particularly the send_file_upload one.

**Comment by zenas101** [comment]
@Synchro 

am sorry for the unrelated post .
my problem is if i send mail in HTML FORMAT in the massage body the mail gets sent and the text show but the inline image does not appear please help me solve this ? sorry for my poor English thanks in advance

**Comment by gusbemacbe** [comment]
@Synchro Is AddEmbeddedImage supported in the last version of PHP Mailer? Does it support svg for e-mails?

**Comment by Synchro** [comment]
@gusbemacbe Please don't comment on unrelated, closed issues; Create a new one.

While I'm here, there's nothing preventing you from adding any file type as an "embedded image", but whether it will be displayed well is entirely up the client app, not PHPMailer. You will need to specify a MIME type manually; I've just added the SVG MIME type to PHPMailer 6.0, and it is `image/svg+xml`.
