### ISSUE TITLE
PHPMailer is sending an empty "AUTH PLAIN", which Exim4 rejects

### ISSUE THREAD

**Issue by SitronNO** [PHPMailer/PHPMailer#345]
It seems like PHPMailer is sending an empth "AUTH PLAIN", which Exim4 (in Ubuntu 12.04 LTS) rejects. Browsing the code, it seems like PHPMailer is about to send the username and password afterwards, but by then the connection is already closed.

I tried this myself by using OpenSSL to connect to my mailserver (using tls), and this did not work:
```
250 HELP
EHLO testing
250-mail.example.com Hello testing
250-SIZE 52428800
250-PIPELINING
250-AUTH PLAIN
250 HELP
AUTH PLAIN
535 Incorrect authentication data
421 mail.example.com: SMTP command timeout - closing connection
```

However, this did work:
```
250 HELP
EHLO testing
250-mail.example.com Hello testing
250-SIZE 52428800
250-PIPELINING
250-AUTH PLAIN
250 HELP
AUTH PLAIN AHRlc3RpbmcAcGFzc3dvcmQ=
235 Authentication succeeded
```

**Comment by Synchro** [comment]
I've been reading [RFC4954](http://tools.ietf.org/html/rfc4954#section-4.1), and this behaviour seems to be acceptable, and it's not clear if it was allowed in the previous RFC2554. The auth parameter is optional - including it in the initial AUTH command is an optimisation (it saves a round-trip), but it should not fail if it's not there, so this looks more like an EXIM problem.
