### ISSUE TITLE
Chinese Characters come out garbled

### ISSUE THREAD

**Issue by Tauri4n** [PHPMailer/PHPMailer#346]
I can't seem to get the email to send Chinese characters, they all end up being garbled. Not using SMTP.

Example: "松子鸡" ends up as: æ¾å­é¸¡

    $email2->Encoding = "8bit";                   
    $email2->From      = 'Email@Something.com';
    $email2->FromName  = 'Some Name;
    $email2->Subject   = "在线订单 ".$event_json['data']['object']['metadata']['orderid']." 接收";
    $email2->Body      = $messageV;
    $email2->isHTML(true); 
    $email2->AddAddress( "Email@Something.com" );
    $email2->Send();

Is there something i'm missing?

**Comment by Synchro** [comment]
You don't need to set encoding (it defaults to `8bit`), but you do need to set `$email2->CharSet = 'UTF-8'`; because it defaults to `iso-8859-1`.

**Comment by Tauri4n** [comment]
I get "Message has been sent" but nothing comes through the inbox. When I comment out `$email2->CharSet = 'UTF-8'` the messages comes in again but with the same garbled characters.

**Comment by ooxi** [comment]
Try encoding the subject

````
"=?UTF-8?B?" . base64_encode("在线订单") . "?="
````

Make sure your PHP file is UTF-8 encoded!

**Comment by Synchro** [comment]
No, don't do that - PHPMailer already does it for you.

**Comment by Synchro** [comment]
if you get 'message has been sent', check your mail server log to see what happened to it.
