### ISSUE TITLE
PhpMailer doesn't sent mail in some cases

### ISSUE THREAD

**Issue by Redani** [PHPMailer/PHPMailer#348]
I'm getting really crazy trying to figure out what's going on with phpmailer :/
I'm using phpMailer Lite 5.1, then i downloaded phpMailer (not Lite) and still the same problem!
here is a portion of my code:

    try {
	// defaults parameters
	$mail = new PHPMailer(true); // or PHPMailerLite
	$mail->CharSet = "utf-8";
	$mail->IsHTML(true); // send as HTML
	$mail->AddReplyTo("noreply@site.com", "Do not reply");
	$mail->SetFrom("noreply@site.com", "Site.com"); // works fine
	//$mail->SetFrom("mike.tra@gmail.com", ""); // doesn't work :(
	
	$mail->AddAddress(trim($email));
	
	// subject of the email
	$mail->Subject = $subject;
	
	// HTML body
	$mail->MsgHTML($msg);
	
	// send the email
	$mail->Send();
	
	// clear all addresses and attachments for the next mail
	$mail->ClearAddresses();
	$mail->ClearAttachments();
	
	echo "email sent";
	}
	catch (phpmailerException $e) {
	echo $e->errorMessage();
	}

With the first SetFrom, it workds perfectly, but when someone sends me an email from contact form, SetFrom should contain his email, in that case, it does'nt work all the time... And the worst thing is that, it doesn't output any error message! <br>
I also have just noticed that if SetFrom is set to my yahoo email address, i receive a "Undelivered Mail Returned to Sender" email !! :/

Do you please have an idea of what that might be??

Thanks a lot for your help

**Comment by Synchro** [comment]
Pleae don't use PHPMailer Lite. there is no advantage in doing so, it's out of date, buggy and no longer supported, at least by me.

Aside from that, most email providers (particularly yahoo and gmail) do not allow you to set arbitrary from addresses. You can pre-configure aliases in gmail, but you can't just use anything as it looks like forgery.

**Comment by Redani** [comment]
Thank you Synchro for your answer.
OK, I have downloaded class.phpmailer.php and class.smtp.php that I'm now using!
Acutally I wasn't using arbitrary email addresses from gmail or yahoo, i was using my own ones but still it doesn't work!!

I'm now trying to use gmail SMTP but my web hoster apparently blocks connection on port 465, i'll call them to find out what to do!

Meanwhile, any suggestions for the problem i'm having??

Thanks

**Comment by Synchro** [comment]
[Read the docs](https://github.com/PHPMailer/PHPMailer/wiki), base your code on [the examples provided](https://github.com/PHPMailer/PHPMailer/tree/master/examples). Don't use SSL on port 465; use tls on port 587.

By arbitrary, I mean anything other than gmail or yahoo addresses on each service respectively.

**Comment by Redani** [comment]
I followed exactely the gmail example but i still get an error:

`SERVER -> CLIENT: 220 mx.google.com ESMTP ej10sm1813444wib.1 - gsmtp
CLIENT -> SERVER: EHLO optigura.com
SERVER -> CLIENT: 250-mx.google.com at your service, [217.160.90.97]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: STARTTLS
SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
CLIENT -> SERVER: EHLO optigura.com
SERVER -> CLIENT: 250-mx.google.com at your service, [217.160.90.97]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH XOAUTH2 PLAIN-CLIENTTOKEN250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: AUTH LOGIN
SERVER -> CLIENT: 334 VXNlcm5hbWU6
CLIENT -> SERVER: b3B0aWd1cmFAZ21haWwuY29t
SERVER -> CLIENT: 334 UGFzc3dvcmQ6
CLIENT -> SERVER: QGRtaW5vZzJPMU8h
SERVER -> CLIENT: 534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbvLb534-5.7.14 XIwYkG9J_wuAvmHiw4RnhyEfhwpG-6TQKbM9KjqVBTkonjaYi8zpBBanDB-sZO6s-G2JtD534-5.7.14 fKBXtIbsDlwuxfdv-hnYFbBNj5SswsYdGYrj0WA5Uka46T3X2REzXxTbeoNQkBi7eTdAk2534-5.7.14 uqPXJ-fEKmhauljHkI3-Atp-Pwqsmo8NnzL5gFlKtMPBxLaDyzkdg7UZWjRbRqFuzkEa_2534-5.7.14 3ZqmnxA> Please log in via your web browser and then try again.534-5.7.14 Learn more at534 5.7.14 https://support.google.com/mail/bin/answer.py?answer=78754 ej10sm1813444wib.1 - gsmtp
SMTP ERROR: Password command failed: 534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbvLb534-5.7.14 XIwYkG9J_wuAvmHiw4RnhyEfhwpG-6TQKbM9KjqVBTkonjaYi8zpBBanDB-sZO6s-G2JtD534-5.7.14 fKBXtIbsDlwuxfdv-hnYFbBNj5SswsYdGYrj0WA5Uka46T3X2REzXxTbeoNQkBi7eTdAk2534-5.7.14 uqPXJ-fEKmhauljHkI3-Atp-Pwqsmo8NnzL5gFlKtMPBxLaDyzkdg7UZWjRbRqFuzkEa_2534-5.7.14 3ZqmnxA> Please log in via your web browser and then try again.534-5.7.14 Learn more at534 5.7.14 https://support.google.com/mail/bin/answer.py?answer=78754 ej10sm1813444wib.1 - gsmtp
CLIENT -> SERVER: QUIT
SERVER -> CLIENT: 221 2.0.0 closing connection ej10sm1813444wib.1 - gsmtp
SMTP connect() failed.`

I'm only including class.phpmailer.php and class.smtp.php, but i don't think it's the issue!!

**Comment by Synchro** [comment]
If you're including those two classes, you're not following the example.

This isn't a PHPMailer problem - it's your gmail account. Have you tried doing what it suggests? Following that link?

**Comment by Redani** [comment]
Yes, I followed the links but it redirects me to my personal email instead of the email I used in $mail->Username to signup with!!

**Comment by Redani** [comment]
Following the links shows now some info about the correct gmail account, but it only shows some account info...
I'm sure it must be a little stupid parameter which is blocking everything! :/

P.S. I'm now using PHPMailerAutoload.php :D

**Comment by Synchro** [comment]
You will need to sign out of your personal account and sign in with the one you're sending through. Probably worth googling the message as well.

**Comment by Redani** [comment]
that's exactly what I did!!
I think I'm gonna give up using gmail.smtp, but before, please i'd like to ask you one question. What's the benefit of using gmail.smtp??

**Comment by Synchro** [comment]
Well, it's a reliable (usually!), well-specified SMTP service and many people already have an account ,so it's quick and easy to set up. It also means that you don't need to have a local mail server running to send mail from PHP - though of course you can use any server for that.

**Comment by Redani** [comment]
OK, well, i'm so confused now, don't know if the problem comes from the server, or from my gmail account!!
Are they any specific settings that need to be done in gmail account to be able to use smtp.gmail? the more i check tutorials and videos about it the more i get crazy coz it's not working for me :-(

**Comment by Synchro** [comment]
No, gmail is pretty standard SMTP - all you need is tls on port 587 and use normal auth.

This answer seems like a likely solution: http://stackoverflow.com/a/20645752/333340

**Comment by Redani** [comment]
I have already tried all the changes mentioned in the link you sent me!!
IT'S INCREDIBLE, have just hang up with my web hoster 1&1, they asked me to use port 25 and it WOOOORKED :D hard to believe :) I'll do some more testing and will get back to you ASAP ;)

**Comment by Redani** [comment]
OMG, it's a real nightmare!! as soon as I signed out from the gmail account, the problems starts again!!
I'm trying to figure out how to fix this!! :/

**Comment by Synchro** [comment]
Did you see the comment in that question about allowing app access in gmail?

If you do use port 25 on 1&1, make sure it lets you use tls as well otherwise it's not worth using.

**Comment by Redani** [comment]
Yes, "Access for less secure apps" is enabled!!

I was using port 25 with tls when it worked for few minutes...

**Comment by Redani** [comment]
Hi,
After struggling the whole day, i came with the following conclusions...
1- setFrom("noreply@company.com", "Company.com") MUST ALWAYS be the company name to prevent the mail from being filtered by gmail or yahoo

2- if the email is being sent by someone through the contact form, WE MUST use the following:
    $mail->setFrom("noreply@company.com", "Company.com");
   $mail->addReplyTo("email-sender@mail.com", "");

with this, we can be sure to receive all emails...

as per the smtp.gmail, i finaly made it work again, but it was always showing the @gmail.com in "sender" field, i added a new email address i can send mails from, but in this case, it shows "sent via gmail" !
so i'm still thinking what to do

Hope this will help people who were in the same situation as me!

To be continued and a special thank you to Synchro for his help ;)

**Comment by Synchro** [comment]
Yes - this is what I meant about not allowing arbitrary addresses, and reply-to is the appropriate workaround. It's quite right that they should do this, as if you say it's from the submitter, it's straight forgery (because they never sent the email message, you did) and is increasingly likely that the email will blocked by their SPF settings anyway.

**Comment by Redani** [comment]
I'm thinking to use Mandrill with phpMailer, what do you think about it?

**Comment by Synchro** [comment]
No particular feelings either way, but PHPMailer works well with it.

**Comment by Redani** [comment]
Well, i'm just happy the problem is solved :) thanks  ;)

I'll have some very few questions please, I would love to have your opinion:
1- do I have to start all my emails with the following code ?
```<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
	<html xmlns="http://www.w3.org/1999/xhtml">
		<head>
			<title>Mail Title</title>
			<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		</head>
	...```
I just don't see how the title would be used since we mention an $mail->subject

2- what's the recommender $mail->Priority to use?

3- when using $mail->msgHTML() do we still need to add $mail->isHTML(true); ??

Thanks a lot ;)

**Comment by Synchro** [comment]
1. I'd recommend either old-school HTML4, or HTML5. Not a huge amount to be gained by using XHTML. Take a look at http://www.email-standards.org
2. Leave as default
3. No - msgHTML sets HTML mode.

**Comment by Redani** [comment]
1- I didn't find any info about doctype... :/
 and are the head and title tags necessary ??

2- OK
3- OK thanks ;)

**Comment by Synchro** [comment]
The doctype determines whether you're talking HTML4, XHTML or HTML5 for the rest of the document, so it sets the context for all other markup. Head tags are stripped in some clients (possibly hotmail), and some spam filters like the title tag to match the subject line. I suggest you make your HTML as clean and valid as possible - it's much easier fixing small problems from that position. Doctype, head and title are all required for valid HTML of any flavour, so leave them in, and do what they say - so don't use XHTML makup in HTML5, or vice versa.

**Comment by Redani** [comment]
Great, thanks for the explanations... ;)
Cheers

**Comment by Redani** [comment]
Hi Synchro, I'll have one last question please.
When I'm running some tests in local, it takes forever the page to render cause phpmailer can't be executed. how can i fix this?
P.S. i don't want to make it work by sending message when in local

Thanks

**Comment by Synchro** [comment]
Just wrap a condition around it and enable/disable it in your config?

You could try running a fake SMTP server, there are some links in the examples folder - I use https://github.com/Nilhcem/FakeSMTP

**Comment by Redani** [comment]
Thanks for the fast reply
sorry I don't really undersantd what you mean, i shoudl wrap a condition around what?

**Comment by Synchro** [comment]
The code that calls PHPMailer, something like:

```php
if ($config['enable_email']) {
   $mail = new PHPMailer;
  ...
}
```

**Comment by Redani** [comment]
Ah Ok, i see the idea
and what about somethibg like this ?
`if(!strpos($_SERVER['SERVER_NAME'], ".localhost")) $mail->send();`

**Comment by Synchro** [comment]
Whatever works for you. If you're not going to send you could just skip the message building steps too.

**Comment by Redani** [comment]
OK, thanks you very much and have an amazing week end ;)
Cheers

**Comment by deifos** [comment]
I spent the whole morning trying to figure out why last night I was able to send email using PHPMailer just fine and now it does not work, but thanks to this conversation I found the problem.

**Comment by Redani** [comment]
You're very welcome deifos ;)
I'm glad it helped you, and this is the purpose of the community ;)
Good luck for the rest.
Cheers

**Comment by ruimelodev** [comment]
@Redani,  thank you for your solution.
This was what helped me:

> 1- setFrom("noreply@company.com", "Company.com") MUST ALWAYS be the company name to prevent the mail from being filtered by gmail or yahoo

**Comment by Redani** [comment]
You're very welcome, and glad it helped you ;)

**Comment by Parvezkhan** [comment]
I am using PHPMAILER.
My Email is working fine with all the email id like example@gmail.com, example@yahoo.com 
but it is not working with some Email id like example@companyname.com 

Can somebody help me here.

**Comment by Synchro** [comment]
@Parvezkhan you need to define "not working" and read [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki). Please don't post commenst on unrelated, closed tickets.

**Comment by raghucodingbrains** [comment]
getting "Could not access file".. path of attachment is correct..
