### ISSUE TITLE
Support google XOAUTH2 authentication

### ISSUE THREAD

**Issue by Synchro** [PHPMailer/PHPMailer#350]
Google have recently started imposing a different authentication mechanism for access to their apps, including gmail. This substitutes normal standards-based SMTP authentication for authorisation via OAuth2, and does not really improve security much at all - it simply means you have to enter your ID and password somewhere else (over the same protocols that they classify as insecure), and add complexity to your project to implement OAuth. This change breaks SMTP and IMAP access to gmail, and you may receive authentication failures (usually "5.7.1 Username and Password not accepted") from many email clients, including PHPMailer, Apple Mail, Outlook, Thunderbird and others.

To do this in PHP you'll need an OAuth2 client class - like [this one](http://www.phpclasses.org/package/7700-PHP-Authorize-and-access-APIs-using-OAuth.html) - to retrieve an authorisation token before making an SMTP connecton as normal. Google's docs on the subject are [here](https://developers.google.com/gmail/xoauth2_protocol).

PHPMailer does not currently support this access mechanism, so whether we like it or not, we should implement it simply because gmail is so popular!

As far as an implementation in PHPMailer goes, it should involve adding the `XOAUTH2` authentication type and provide a mechanism to provide an OAuth token. Creating and obtaining the token should be left to external scripts/libraries such as the one linked to above.

**Comment by michield** [comment]
That would be awesome.

**Comment by Synchro** [comment]
Implemented in the 5.2.11 release.
