### ISSUE TITLE
Issue sending email thru external mail server

### ISSUE THREAD

**Issue by seala56** [PHPMailer/PHPMailer#353]
I am brand spanking new to PHP and I've been working in a Windows environment using classic asp. I have a form that uses phpmailer to send an email containing the data of the form to an administrator. I had it working great testing on the site and email with the same domain scenario. Since the final site will reside under the scenario where the website will be on one server and the email on another, I now need to get it working with that scenario. I assumed it would be simple by just changing the values of the host, port, username and password - but alas that's not the case. I've been all over the internet I can't seem to find anything that helps. When I process the form, this is the message that appears in my browser: 
```
2015-02-02 21:28:09	CLIENT -> SERVER: EHLO www.qcsmallbiz.com
2015-02-02 21:28:09	CLIENT -> SERVER: MAIL FROM:
2015-02-02 21:28:09	CLIENT -> SERVER: RCPT TO: 
2015-02-02 21:28:09	SMTP ERROR: RCPT TO command failed: 550 No such domain at this location
SMTP Error: The following recipients failed: info@vtwd.com
There was an error sending the message"
```
Here is my code:

```php
require 'PHPMailerAutoload.php';

$mail = new PHPMailer();
$mail->IsSMTP(); // telling the class to use SMTP
$mail->Host       = "74.84.86.134"; // SMTP server
$mail->SMTPDebug  = 1;                     // enables SMTP debug information (for testing)
                                       // 1 = errors and messages
                                       // 2 = messages only
$mail->Port       = 25;                    // set the SMTP port for the MAIL server
$mail->SetFrom('mtoalson@xyz.com', 'Mike Toalson');
$mail->AddAddress("info@vtwd.com"); //The address you are sending mail to
$mail->Subject    = "New Form Submission";

$body = "Email Notifications: $ckNotify
UnSubscribe User: $ckUnsubscribe
Name: $name
Email: $visitor_email
Message: $message";

$mail->MsgHTML($body);
if(!$mail->Send()){ //Check for result of sending mail
echo "There was an error sending the message"; //Write an error message if mail isn't sent
exit; //Exit the script without executing the rest of the code
}
```
Can anyone help me figure out what's going on? I would truly appreciate any help in getting this resolved! Thank you.

**Comment by Synchro** [comment]
Your code is based on an old example, so make sure you're using a recent one from the examples folder, and the current release of PHPMailer. [The troubleshooting docs] may help too. Try setting `SMTPDebug = 3` to get more verbose output.

**Comment by seala56** [comment]
I decided to try running smtp_no_auth.phps and changed the variables. For some reason I'm getting an error that's pointing to this line: //Set the subject line
$mail->Subject = 'PHPMailer SMTP without auth test';  The error message reads: PHP Parse error:  syntax error, unexpected T_VARIABLE in D:\hshome\seala56\qcsmallbiz.com\smtp_no_auth.phps on line 37

**Comment by seala56** [comment]
never mind - I forgot a semi-colon on the statement prior to that one.

**Comment by seala56** [comment]
I've rewritten the code using most of the example (version 5.2.9 of phpmailer) and changed the SMTPDebug to 3. Everything looks fine until the very last line where i get this: 2015-02-03 17:29:14	SERVER -> CLIENT: 250 Ok: queued as 1217D776D18 Mail Not Sent 

To me that says everything's ok - we've queued your message but it wasn't sent??

**Comment by ooxi** [comment]
It really looks like your mail server swallowes your mail. Do you have access to your mail server's log files? If not, maybe send an SMTP trace to the mail server's hoster and ask them whats wrong.

**Comment by seala56** [comment]
We were on a testing server. We decided to move everything to production and then have the company we have our mail server on set everything up to allow the mail relay. Why set everything up on a test basis only to have to do it all over again once we go live. So, just waiting for things to propogate to resume testing. Thanks for your input.

**Comment by Synchro** [comment]
Did you get to the bottom of this?

**Comment by seala56** [comment]
Not yet

**Comment by seala56** [comment]
Oh I'm sorry I thought this was about something else - yes problem solved thank you
