### ISSUE TITLE
Encoding issues even with UTF-8

### ISSUE THREAD

**Issue by scrnjakovic** [PHPMailer/PHPMailer#357]
Hi, I get this � instead of šđžčć.  I applied ```$mail->CharSet = 'UTF-8``` but still nothing. I tried changing Encoding to qp, base64, it's the same. I had the same problem with SwiftMailer, that's why I switched to PHPMailer, although with SwiftMailer body text was ok, only headers displayed these question marks. PHPMailer displays question marks even in body text.

**Comment by Synchro** [comment]
Post your code.

**Comment by scrnjakovic** [comment]
Well, while copy-pasting the code, I found out that my sanitizing is actually the cause of this. Sorry >.<

**Comment by Synchro** [comment]
Oh well - that's the rubber-duck effect that writing a good bug report encourages!

**Comment by ali-h2010** [comment]
@scrnjakovic How did you fix the issue?
I am also having ????? when using Arabic text in the email
I set the charset as UTF-8

**Comment by ali-h2010** [comment]
`$mail->isSMTP();                                      // Set mailer to use SMTP
                                $mail->Host = '*****';  // Specify main and backup SMTP servers
                                $mail->SMTPAuth = true;                               // Enable SMTP authentication
                                $mail->Username = '*****';                 // SMTP username
                                $mail->Password = '*****';                           // SMTP password
                                $mail->Port = 25;                                    // TCP port to connect to
								$mail->CharSet = 'UTF-8';
								
                                //Recipients
                                $mail->setFrom(****', 'Mailer');
                                $mail->addAddress($isValdUser->customerEmail);               // Name is optional

                                //Content

                                $randomEmailVerficationKey = $isConfirmationRequested->EmailVerificationKey;
                                $dateTimeNow = date('Y-m-d H:i:s');
                                $emailVerificationExpirationDate = date('Y-m-d H:i:s',strtotime('+3 day',strtotime($dateTimeNow)));
                                $isConfirmationRequested->EmailVerificationKeyExpiry = $emailVerificationExpirationDate;
                                $isConfirmationRequested->save();

                                $WebApiDomain = '*****;
                                $verificationURL = $WebApiDomain."/VerifyEmail?id=".$_customerID."&key=".$randomEmailVerficationKey;



                                $mail->isHTML(true);                                  // Set email format to HTML
                                $mail->Subject = 'Welcome to Radm System';
                                 $mail->Body    = '<p dir="rtl">شكرا لتسجيلك في برنامج ردم لحجز الحاويات </p>
													<p dir="rtl"><b><a href="'.$verificationURL.'">اضغط هنا لتأكيد بريدك الإلكتروني</a></b></p>
													<p dir="rtl">أو انسخ الرابط التالي إلى أي متصفح '. $verificationURL .'
													<p dir="rtl" >من فضلك تجاهل هذه الرسالة إن لم تسجل في برنامج ردم للحاويات</p>
													<p dir="rtl">---------------------------------------------------------------</p>
													<p>Thank you for registering in Radm (Containers Reservation System) <b><a href="'.$verificationURL.'">click Here to activate your account</a></b><p>
													<p>Or copy and paste this link in your browser:'.$verificationURL.'</p>
													<p>Please ignore this message if you did not register in Radm</p>';
                                $mail->AltBody = 'Click or copy and paste this link to Verify your email:'.$verificationURL;

                                $mail->send();`

**Comment by ali-h2010** [comment]
???????? ?????????????? ???? ???????????? ?????? ???????? ???????????????? 
???????? ?????? ???????????? ?????????? ????????????????????
???? ???????? ???????????? ???????????? ?????? ???? ?????????? http://someURL
???? ???????? ?????????? ?????? ?????????????? ???? ???? ???????? ???? ???????????? ?????? ????????????????
---------------------------------------------------------------
Thank you for registering in Radm (Containers Reservation System) click Here to activate your account

**Comment by scrnjakovic** [comment]
My problem was elsewhere. One of sanitizing functions was using single byte instead of multi byte functions, i.e. `strtoupper()` instead of `mb_strtoupper()`.

**Comment by Synchro** [comment]
The most likely explanation is that your input text isn't in UTF-8, but in an 8-bit Arabic charset like ISO-8859-6.
