### ISSUE TITLE
Problem with utf8 displaying

### ISSUE THREAD

**Issue by ishr00m** [PHPMailer/PHPMailer#358]
![e8a6ca6cdc63787b48dfca2d9efe678f](https://cloud.githubusercontent.com/assets/6658214/6096133/40c8b09e-afa3-11e4-9468-1b5ecc31faf6.png)

When sending message, got problem with some characters. 
$mail->CharSet = 'UTF-8'; is setted.

**Comment by Synchro** [comment]
That looks like you may have corrupt characters in your original text. If it was getting the charset wrong, the russian text would not look right (unless it's actually using an 8-bit Russian charset). Can you try a minimal example, and I suggest you validate your UTF-8 text before putting it in the email.

**Comment by ishr00m** [comment]
As i told, it looks like this only in Gmail and mail.ru. In Yandex Mail it looks good. I tried to put big text just from file, same situation.

**Comment by Synchro** [comment]
Please post a minimal example otherwise I have no way of helping you.

**Comment by mrdemc** [comment]
Character output and document output are two different things. Your document output seems to be ISO-8859-1 while your content is UTF-8. So change the document headers or change the content in the same encoding as your document.

**Comment by ishr00m** [comment]
Thanks guys, i will check and reply later.
