### ISSUE TITLE
Parse error on hosted website

### ISSUE THREAD

**Issue by HiPower** [PHPMailer/PHPMailer#360]
Hoping someone can help.  I am getting this; Parse error: syntax error, unexpected end of file in /home/mywebsite/public_html/cgi-bin/PHPMailer-master/class.phpmailer.php on line 2478 when attempting to send from our host (inmotionhosting).  I use PHPmailer from our own server-hosted intranet with no problem at all.

**Comment by Synchro** [comment]
Sounds like you have a corrupted file, failed upload or something. I suggest you replace the file.

**Comment by HiPower** [comment]
Thanks for the response.  I have replaced the file several times with fresh downloads from Github.  All come back with the same problem.

**Comment by HiPower** [comment]
OK, to be sure, I re-downloaded PHPmailer, removed it from the host and re-uploaded it.  Now I get a parse error on a different line; 2669.

**Comment by Synchro** [comment]
I'm very suspicious of your server! If you open the file on the server, does it look ok? Maybe something is amiss with an opcode cache?

**Comment by HiPower** [comment]
I will review the file on the server.  Additionally, I am using MS Expression Web to upload the files.  I will try a fresh upload using another FTP program and see if that helps.

**Comment by HiPower** [comment]
Verified that the class file on the server was about 900 lines short.  I uploaded through a different method and it seems to have worked, but now I am getting "Mailer Error: Could not instantiate mail function.".

**Comment by Synchro** [comment]
Sounds like your server's PHP is not configured correctly, or is lacking a mail server, or both. Try using `isSMTP()` and a mail server elsewhere (e.g. gmail) to work around it while you're looking for a server that's not rubbish!

**Comment by mrdemc** [comment]
Please notice this comment in case you are using a Windows server which I suspect;
http://php.net/manual/en/function.mail.php#refsect1-function.mail-notes

**Comment by HiPower** [comment]
Thanks for all the help.  It turned out to be my host and they were less than helpful.  I have moved the site to a new host and all is working as it should.
