### ISSUE TITLE
Call to undefined method SMTP::setTimeout

### ISSUE THREAD

**Issue by viper007131** [PHPMailer/PHPMailer#361]
i get Fatal error: Call to undefined method SMTP::setTimeout()
i am not sure how to solve this issue, i am using version 5.2.9 and have autoloader in same dir.
i have this added to class.phpmailer.php
require 'PHPMailerAutoload.php';
$mail = new PHPMailer;
im sorry im new to php, any help would be great

**Comment by Synchro** [comment]
Can you double check that the correct SMTP class is being loaded? Stick an "echo 'hello'" in it to be sure. The method definitely exists, so it must either be not loading the class, or loading some other SMTP class.

**Comment by jcodesdotme** [comment]
My project has same class names because i am revamping it. I manually loaded phpmailer and smtp classes into controller instead of using $mail = new PHPMailer etc. And it worked. So composer autoload doesn't load the correct file. Just edited classmap in vendor/composer and it is fixed.
