### ISSUE TITLE
How to skip output display after successfully sent the email ? (Not the message SUcceesyllu sent message)

### ISSUE THREAD

**Issue by udara86** [PHPMailer/PHPMailer#366]
Hi,

I installed and configured PHPMailer with my gmail account and it sends the emails. But the issue its displaying long progress message apart from the "Successfully sent message".

I need to skip this progress reporting messages and just display whether the email has successfully send or not.

these are the waste messages:

SERVER -> CLIENT: 220 mx.google.com ESMTP ei3sm22221361pbc.91 - gsmtp
CLIENT -> SERVER: EHLO localhost
SERVER -> CLIENT: 250-mx.google.com at your service, [203.94.68.194]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: STARTTLS
SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
CLIENT -> SERVER: EHLO localhost
SERVER -> CLIENT: 250-mx.google.com at your service, [203.94.68.194]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH XOAUTH2 PLAIN-CLIENTTOKEN250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: AUTH LOGIN
SERVER -> CLIENT: 334 VXNlcm5hbWU6
CLIENT -> SERVER: dW1wd2Vic29sdXRpb25zQGdtYWlsLmNvbQ==
SERVER -> CLIENT: 334 UGFzc3dvcmQ6
CLIENT -> SERVER: bWFkdXNoYW44Ng==
SERVER -> CLIENT: 235 2.7.0 Accepted
CLIENT -> SERVER: MAIL FROM:<email@sender.lk>
SERVER -> CLIENT: 250 2.1.0 OK ei3sm22221361pbc.91 - gsmtp
CLIENT -> SERVER: RCPT TO:<udara86@gmail.com>
SERVER -> CLIENT: 250 2.1.5 OK ei3sm22221361pbc.91 - gsmtp
CLIENT -> SERVER: DATA
SERVER -> CLIENT: 354 Go ahead ei3sm22221361pbc.91 - gsmtp
CLIENT -> SERVER: Date: Thu, 19 Feb 2015 09:15:19 +0000
CLIENT -> SERVER: To: 11 SLSC <udara86@gmail.com>
CLIENT -> SERVER: From: SENDER s NAME <email@sender.lk>
CLIENT -> SERVER: Reply-To: Reply To Me <udara@army.lk>
CLIENT -> SERVER: Subject: Testing Emil Header :
CLIENT -> SERVER: Message-ID: <f5de5be1309570ebfc316007a92bc5f2@localhost>
CLIENT -> SERVER: X-Priority: 3
CLIENT -> SERVER: X-Mailer: PHPMailer 5.2.9 (https://github.com/PHPMailer/PHPMailer/)
CLIENT -> SERVER: MIME-Version: 1.0
CLIENT -> SERVER: Content-Type: multipart/mixed;
CLIENT -> SERVER: boundary="b1_f5de5be1309570ebfc316007a92bc5f2"
CLIENT -> SERVER: Content-Transfer-Encoding: 8bit
CLIENT -> SERVER:
CLIENT -> SERVER: --b1_f5de5be1309570ebfc316007a92bc5f2
CLIENT -> SERVER: Content-Type: multipart/alternative;
CLIENT -> SERVER: boundary="b2_f5de5be1309570ebfc316007a92bc5f2"
CLIENT -> SERVER:
CLIENT -> SERVER: --b2_f5de5be1309570ebfc316007a92bc5f2
CLIENT -> SERVER: Content-Type: text/plain; charset=us-ascii
CLIENT -> SERVER:
CLIENT -> SERVER: This is a test of PHPMailer.
CLIENT -> SERVER:
CLIENT -> SERVER:
CLIENT -> SERVER:
CLIENT -> SERVER:
CLIENT -> SERVER:
CLIENT -> SERVER: This example uses HTML.
CLIENT -> SERVER: The PHPMailer image at the top has been embedded automatically.
CLIENT -> SERVER:
CLIENT -> SERVER:
CLIENT -> SERVER: --b2_f5de5be1309570ebfc316007a92bc5f2
CLIENT -> SERVER: Content-Type: text/html; charset=us-ascii
CLIENT -> SERVER:
CLIENT -> SERVER: <html>
CLIENT -> SERVER: <head>
CLIENT -> SERVER: <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
CLIENT -> SERVER: <title>PHPMailer Test</title>
CLIENT -> SERVER: </head>
CLIENT -> SERVER: <body>
CLIENT -> SERVER: <div style="width: 640px; font-family: Arial, Helvetica, sans-serif; font-size: 11px;">
CLIENT -> SERVER: <h1>This is a test of PHPMailer.</h1>
CLIENT -> SERVER: <div align="center">
CLIENT -> SERVER:
CLIENT -> SERVER: <a href="https://github.com/PHPMailer/PHPMailer/"><img src="http://prasanga.eu5.org/mit/images/email_header.jpg" alt="PHPMailer rocks"></a>
CLIENT -> SERVER:
CLIENT -> SERVER: </div>
CLIENT -> SERVER: <p>This example uses <strong>HTML</strong>.</p>
CLIENT -> SERVER: <p>The PHPMailer image at the top has been embedded automatically.</p>
CLIENT -> SERVER: </div>
CLIENT -> SERVER: </body>
CLIENT -> SERVER: </html>
CLIENT -> SERVER:
CLIENT -> SERVER:
CLIENT -> SERVER:
CLIENT -> SERVER: --b2_f5de5be1309570ebfc316007a92bc5f2--
CLIENT -> SERVER:
CLIENT -> SERVER: --b1_f5de5be1309570ebfc316007a92bc5f2
CLIENT -> SERVER: Content-Type: image/png; name="phpmailer_mini.png"
CLIENT -> SERVER: Content-Transfer-Encoding: base64
CLIENT -> SERVER: Content-Disposition: attachment; filename=phpmailer_mini.png
CLIENT -> SERVER:
CLIENT -> SERVER: iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAIAAADajyQQAAAAA3NCSVQICAjb4U/gAAAACXBIWXMA
CLIENT -> SERVER: AAs6AAALOgFkf1cNAAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAABrBJREFU
CLIENT -> SERVER: eNrtm4lPFFccx/s/AXuwLCvrcsNyyw1luc9KrUUgFgzh9ACqFmIKQsBQEAUFagAROZagHFbkbFUK
CLIENT -> SERVER: SEAJLYJgSQD7jS/S6czswbITtX3fvJDZt+/3e/uZd868H19Y/EdFwSgYBaNg5gI7f/78Rd0qLS09
CLIENT -> SERVER: c+ZMcnJyUFCQg4ODlZWVMdX4uMlLMj0ESieiHYwC29jYeGe0Xr58WV5eDkL9YJaWFtUFvtsjKWZP
CLIENT -> SERVER: 482RKjuJ+cGINjc38/PzLfHz9eridx7mpXpY/6XCRgTPQoERPXjwwNbWVj9b3jdufw2bh6qnOlQm
CLIENT -> SERVER: JQNBYDBofHzczs5OP1tmotPWUPIhqdrKA8Ui0kGEByPq7u62MKSvNPYbg0kmU9UXH7OyIlSHAyss
CLIENT -> SERVER: LDzBUFZW1uXLl+/du7e7u8vLlpqaapAtOkj5pzbRBKrKPB/iwQxgPj78vlxcXO7evcsFm52dNabu
CLIENT -> SERVER: EB/FSl/CgaiKM9UwFBwMwjrW3t7OZQsJCWFN97zydZcvdsUZg/R2KDkn1UXHWiIAGCQSiWZmZlgm
CLIENT -> SERVER: tbW1zDLfn/b0crHhNXdztJ5tj9FPtfkwOS3OiddcKrZsKDkmCBhUV1fHMhkZGWEWqC/2X74fH+Sl
CLIENT -> SERVER: 4DV3UEqnWqJ0Ua0PJiWGH+U1lFuLBuvC4VkoMEwnLJO5uTkWGH7iH9rEyAD+xcBOLh5tjOBSrfYn
CLIENT -> SERVER: avz5TZS24l9uaFBGQLDAwEDuXoQLRm5/UriK//bLRNraMCbVcnd8oCf/iu94VDpNGllQsJiYGJbJ
CLIENT -> SERVER: q1evuGCGB4zEqrMimBSb74z1dJHxFlM7yX5vj0UZwcGKiopYJv39/SwwzhTnyusKC2/zpYDffo52
CLIENT -> SERVER: VlnzFjimli91xxM/goM9evSIZVJRUcEFY6ULGWpd07eurW2435GVXrL0CQ926tSpdxydPHnSIBjS
CLIENT -> SERVER: j7neFkYrNkS5NkA2K8KDYXStrq6yyr9+/VqpVBoDhvTTBcMbP+jrKAeyvRQczN3dvbKykne7iGcz
CLIENT -> SERVER: FDASDKm1LEj/Vv10kvNb8rBjXjA8aN1nCIuvnieAyclJ7LMOBIbUXRVqLYEVjwq/dSePcOYAM1Vo
CLIENT -> SERVER: wLCwMDg5KBgS9hC2Mvac8UO2lyFD4cFARTqhaWBIY02aowrJ/txYU+SLzI8Mtr29nZmZCfPDgCH9
CLIENT -> SERVER: 2hbtpJJiNmm6FICPHxkMT2Vubm6wPTwY0lxHLIYcLj4C2NbW1sLCglarPXfunIeHBzE8HBg3CQ8W
CLIENT -> SERVER: Ghp6hCEbG/aT1ecKxl3HKBgFo2AUjIJRMApGwSgYBaNgnwMYXt08+bfIQ+RhhHejOHMQKN2vDqUh
CLIENT -> SERVER: RxSMglEwCkbBPqimpubGe12/fh0ROH5+fiT/ypUrnp6ezJLFxcUkngOnYcQEqqqq2j8cQ1gjcjIy
CLIENT -> SERVER: MphWYrG4oaEB+VKpVNeJdn19PS5ycnLa2trMBobTLfBkZ2fDb2dnJ47JIyMjkY9AgKioKGbJ0dHR
CLIENT -> SERVER: tLQ0XCCqAy9PYQIBDEGMjY2NyIef5eXl+fl5phVokYkNjVwut+AT3sDi7BcXubm5iI4xJxhpJaLb
CLIENT -> SERVER: t293dXUZBKuurv4nTio6em9vDyF+ALt169bi4iLCUZkOy8rKWGDcWEdeMBQzGxgaYWJi4kBg6Gw7
CLIENT -> SERVER: OztwQsCuXr2KI0LylUQigX8vLy8CBsHJ0tLSmzdvHj9+nJCQgDIRERG9vb1MMDi8du0ajk7X1tZw
CLIENT -> SERVER: l1UqFTJbW1vT09Pz8vJgaAoYPPb19REwRAMHMjQ1NcULRsI+cFpLwPARL/rJV8ePHweJTCYjYGgB
CLIENT -> SERVER: vDPHQSGJgiHxPHFxcfDMBCsoKMAOFjFp8NnR0XHz5k1kDgwMIOgCgbv+/v7GgqHnYGSjYpwMrays
CLIENT -> SERVER: oEoC9uzZsycMYfjtg4EfJhBe9ON+Dw8PI5+A4eL58+fBwcG4wGSAXwkwbldEM+KEjRdsaGgIHYeU
CLIENT -> SERVER: TElJwaAlYGixg3VF/GI8vOBienr67NmzqNVgV8T5GEygFy9etLS0IPyZCYb7ig4JbPi0t7dntlhJ
CLIENT -> SERVER: SQm6OsLM0FzI5AVD1WNjY9r3QrH19XWTwEhX5Mj4MUbEBENroDciiHNwcBAf98Ew36IXkGhbhUKh
CLIENT -> SERVER: CwzYaDH3D3J2dv5UwCA0/tOnTzFKmWBYUXp6epCzD4Y25ILhL8v/JwSGLo31DVMFEwzdEv2qubn5
CLIENT -> SERVER: zp076GyouqmpiQuGcYti6LFYuDFz4F8eTAHTaDSomJuPcADcVNYWATMvWVLVajXXxNXV1dvbmzcu
CLIENT -> SERVER: FZEvZDLEcoedSkBAAD5iMUAtgCcbGkdHx/1bjFuAYpjM4uPjSV0wQe10r0jBKBgFo2D/a7C/Af4W
CLIENT -> SERVER: rkfDK5+FAAAAAElFTkSuQmCC
CLIENT -> SERVER:
CLIENT -> SERVER:
CLIENT -> SERVER: --b1_f5de5be1309570ebfc316007a92bc5f2--
CLIENT -> SERVER:
CLIENT -> SERVER: .
SERVER -> CLIENT: 250 2.0.0 OK 1424337324 ei3sm22221361pbc.91 - gsmtp
CLIENT -> SERVER: QUIT
SERVER -> CLIENT: 221 2.0.0 closing connection ei3sm22221361pbc.91 - gsmtp
Message sent!

**Comment by Synchro** [comment]
You could try reading the docs. Set `SMTPDebug = 0`.

**Comment by udara86** [comment]
Dear Synchro,

Thanks so much. I able to handle the situation with the support of you dear. Thanks lot..I'm really appreciate your support.

Bye

**Comment by udara86** [comment]
Dear Synchro,

Thanks so much. I able to handle the situation with the support of you
dear. Thanks lot..I'm really appreciate your support.








*Have a Nice Day...>>Best Regards From  Lt Udara Pathirage        Master of
IT, UCSC, Colombo | BSc in ENCM, Kelaniya | Dip. IT, NIBM
Software Engineer (IT OFFICER)*
*              Directorate of Information Technology*
*              SRI LANKA ARMY*



*Email:    udara86@gmail.com <udara86@gmail.com>
udara@army.lk <udara@army.lk>*




*Web:      http://udara.umpwebsolutions.com
<http://udara.umpwebsolutions.com/>SkypeID: udara1986Phone: 094 71 8110497*

**Comment by chinmayakumarbiswal** [comment]
> You could try reading the docs. Set `SMTPDebug = 0`.

Dear Synchro,

Thanks so much and i also implement this on my SMTP server and it work fine.
