### ISSUE TITLE
Composer update error

### ISSUE THREAD

**Issue by sn0rcha** [PHPMailer/PHPMailer#367]
Hey there,

For some reason when I do a composer update with a project that has phpmailer required ```    "phpmailer/phpmailer": "dev-master"``` i'm getting the following error:

```Updating phpmailer/phpmailer dev-master (6fb0f62 => 40fa68e)```

```[RuntimeException]
  Failed to execute git status --porcelain --untracked-files=no
  sh: 1: git: not found
```

It has been working fine up until this morning.. Any ideas?

**Comment by Synchro** [comment]
No. I've not made any changes in the last couple of days, and this sounds like a local config issue with git/composer rather than anything to do with a specific package.

**Comment by sn0rcha** [comment]
I'm not sure what to make of it, all the other packages updated without issue, it's just stuck on this one :(

**Comment by sn0rcha** [comment]
I fixed this by updating my version of git.
