### ISSUE TITLE
'SMTP connect() failed' error on localhost

### ISSUE THREAD

**Issue by ozgrozer** [PHPMailer/PHPMailer#368]
My settings are true and I can send mail from server but I updated my localhost PHP version to 5.6.3 and now I can't send mail. 

I get an error like this
```
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /Applications/XAMPP/xamppfiles/htdocs/phpMailer/class.smtp.php on line 338
```

What can I do for send emails on localhost?

**Comment by Synchro** [comment]
This is covered in [the troubleshooting docs](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting). PHP 5.6 verifies SSL certificates by default, and if your cert doesn't match, it will fail with this error. The correct solution is to fix your SSL config - it's not PHP's fault!

If you're sending on localhost you can use `isMail()` and it won't go through an encryption layer at all.

**Comment by ozgrozer** [comment]
I changed the file class.smtp.php in line 242

```php
public function connect($host, $port = null, $timeout = 30, $options = array())
{
	if(count($options)==0){
		$options["ssl"]=array("verify_peer"=>false,"verify_peer_name"=>false,"allow_self_signed"=>true);
	}
```

and now it works perfect.

**Comment by Synchro** [comment]
"Perfect" in the sense that you can't detect servers presenting fake credentials, the whole reason this change was made in PHP 5.6. As I said, the correct solution is to fix your SSL, not live with the breakage.
Note that the `connect` function provides an `options` parameter in which you can do this without changing the code.

**Comment by ozgrozer** [comment]
I couldn't fix my SSL and so I found that method.

Now I send options through the smtpConnect function.
```php
$options["ssl"]=array("verify_peer"=>false,"verify_peer_name"=>false,"allow_self_signed"=>true);
$mail->smtpConnect($options);
```

Thanks.

**Comment by ivkremer** [comment]
@ozgrozer thank you very much, I didn't connect the PHP version upgrade with this error and was wondering why there is such an error when I'm trying to send an email:

```
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```
My first thoughts were that there is something wrong with a gmail account. Thanks for such an easy and quick solution.

**Comment by ivkremer** [comment]
@ozgrozer thank you very much, I didn't connect the PHP version upgrade with this error and was wondering why there is such an error when I'm trying to send an email.
My first thoughts were that there is something wrong with a gmail account. Thanks for such an easy and quick solution.

**Comment by Synchro** [comment]
This is fixable without touching library code; just do this:

```php
$mail->SMTPOptions = array(
    'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )
);
```
While that's neat and tidy, it doesn't change the fact that your SSL config is broken :wink:

**Comment by Damiano8** [comment]
where do you write code this $mail ->> SMTP Options = array..?

**Comment by Synchro** [comment]
In your own code, in the same place you set all the other PHPMailer options.

**Comment by Damiano8** [comment]
in class.smtp.php ? or class phpmailer.php?

**Comment by Synchro** [comment]
Neither - **in your own code**.

**Comment by ivkremer** [comment]
@Damiano8 just before you make your `$mail->send()`, like this:
```php
$mail = new PHPMailer();
$mail->isSMTP(); // $mail->Body = $body; etc
$mail->smtpConnect([
    'ssl' => [
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    ]
]);
$mail->send();
$mail->smtpClose();
```

**Comment by Synchro** [comment]
No, don't do that - you do not need to call `smtpConnect()` becasue PHPMailer does it for you whan you call `send()`, so doing that results in it trying to connect twice, which will probably fail. This is why the `SMTPOptions` property exists.

**Comment by Damiano8** [comment]
look guys, i have this warning when i try to send email:

Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in D:\xampp15\htdocs\stran\class.smtp.php on line 345
There are some issue.

**Comment by Synchro** [comment]
Yes, it's exactly the error this *closed* ticket is about, and you can solve it as described in the docs already linked to. Please read before posting.

**Comment by Damiano8** [comment]
well now i have included this part of code in my code and it returns the same error as before and another error: 
Warning: Creating default object from empty value in D:\xampp15\htdocs\stran\kontakt.php on line 101

**Comment by Synchro** [comment]
That sounds like you have called you PHPMailer instance something other than `$mail`. Use whatever you have called it instead.

**Comment by Damiano8** [comment]
could i send you the code so you can take a quick look? because i don't have any ideas what to do anymore..

**Comment by ivkremer** [comment]
@Synchro thank you very much for information about using `isSMTP()` and `smtpClose`. I've just copied a snippet like this somewhere without analysing it.

**Comment by Damiano8** [comment]
just wanted to let you know that i somehow fixed it. i installed a older version of xampp and it worked.. i was running xampp version 5.6.3 and then i switched to 1.8.1. i mean..this versions..

**Comment by jimobama** [comment]
I really want this problem solved , have done everything said in this thread except configuration of my SSL (Who do you done that) , even update my Linux certificate. everything works on console. Same codes work on windows but when I used it in Linux this error codes up.

**Comment by Synchro** [comment]
@jimobama This error is because of a config error on your server. Follow the troubleshooting guide and it will tell you what is wrong. This is not a bug in PHPMailer, and we can't fix your server for you.

**Comment by jimobama** [comment]
Thanks for the reply , the problem lies with my SMTP server Host information and now working fine.

**Comment by brruoff** [comment]
Works perfect @ozgrozer 
thanks

**Comment by AbbyNormal** [comment]
Ok, how about a hosting server with 150 websites? We have upgraded from php 5.5 to php5.6 and every web that uses PHPMailer now is broken because contact forms are not working. Is there any fix for this or should we downgrade and freeze php version to 5.5?

**Comment by Synchro** [comment]
As already mentioned several times in this thread, read the docs. You can work around this for your entire server by setting PHP to not validate certificates in your php.ini, however, you should be aware that this is the wrong way to fix the problem - it's the mail servers with bad configuration that are at fault, not your web server or PHPMailer.
