### ISSUE TITLE
Non-FQDN returned by serverHostname for HELO when run through CLI

### ISSUE THREAD

**Issue by fluxcorenz** [PHPMailer/PHPMailer#369]
A project which uses PHPMailer runs a scheduled job using the PHP CLI via cron, which sends emails out.

We noticed our mail relay server rejected some emails from this server, and determined it was those being generated through this cron task - they were being rejected due to not specifying a fully qualified domain name (only the host name was being passed).

After source-diving, I found the HELO hostname being generated is through the serverHostname() method, which performs the following:

1) Check/use if source code has hard-coded the hostname variable
2) Check/use if the server variable is set
3) Check/use the hostname
4) Check/use php uname
5) Just return 'localhost.localdomain'.

When run through the CLI, SERVER variables are not set, so flow falls through to #3 - get the host name. This returns only the hostname, not the FQDN, and is not entirely suitable for the HELO data.

It is not particularly viable to hard-code the hostname into the source code, as this is a bundled library in a 3rd party project, and these files get replaced often with project updates - modifying them manually would be a bit of a maintenance burden.

Currently I have had to disable the FQDN check on our mail relay server to get around this issue, but that's not really a great solution.

Perhaps the $Hostname variable in the source code could be a parameter or set in a config file, rather than only hardcoded?

I appreciate that getting the FQDN through PHP CLI is difficult due to cross-platform issues.

**Comment by Synchro** [comment]
I don't get the problem with $Hostname? It's not hard-coded at all, it's just a public property that you can set any way you like. You already have code that creates a PHPMaieler instance, sets destinations etc, presumably from some local app config/database that does not get replaced when you update, so why can't you set Hostname then?

**Comment by fluxcorenz** [comment]
Quite right - I'll try to coax some parameter setting from the other project. Thanks!
