### ISSUE TITLE
Convert the google code tutorial for github wiki

### ISSUE THREAD

**Issue by Synchro** [PHPMailer/PHPMailer#370]
[This](https://code.google.com/a/apache-extras.org/p/phpmailer/wiki/UsefulTutorial) is not a bad tutorial, but it would be good if it was here on github instead of lurking on the ghost town that is google code.

**Comment by ooxi** [comment]
I gave it a try https://github.com/PHPMailer/PHPMailer/wiki/Useful-tutorial

**Comment by Synchro** [comment]
Thanks. Quite a lot of it is outdated and needs updating, but that's a good start.

**Comment by mrdemc** [comment]
I'll check the tutorial and examples today and see if they need some adjustments when I'm back home. I'll keep it updated here.

**Comment by Synchro** [comment]
I've rewritten, corrected and cleaned this up substantially, changed URL to https://github.com/PHPMailer/PHPMailer/wiki/Tutorial.
