### ISSUE TITLE
Better understanding as to why a recipient fails

### ISSUE THREAD

**Issue by nestsman** [PHPMailer/PHPMailer#371]
SMTP Error: The following recipients failed:

Is there any way to get a better error message out of PHPMailer when errors like this occur?  Is it due to the recipient's mailbox being full, a typo in the email address or various other reasons?

Thanks!

**Comment by Synchro** [comment]
This may be tricky if you have more than one recipient., but try looking at what's you get from `$mail->getSMTPInstance()->getLastReply();`.

**Comment by Synchro** [comment]
Looking at it a bit more, I think you need to subclass the SMTP class and override the `recipient()` method to pull out those replies at the right time - from the PHPMailer class you ony see the `send()` function so my suggestion above will only return you the last thing the server said.

**Comment by nestsman** [comment]
I need to subclass the SMTP class?  Huh?  I'm just a frozen cave-man lawyer and don't understand these things.  (Saturday Night Live joke).  I just  checked my code and it doesn't use the recipient() or the send() functions either.  Maybe I have an older version of the example code?

I send emails out in batches of 20 with a cron.  My script uses a loop to send out each email until it reaches 20.  At the end of this loop I have the following:

// Clear all addresses and attachments for the next loop
$mail->ClearAddresses();
$mail->ClearAttachments();
$mail->ClearReplyTos();
$mail->ClearAllRecipients();
$mail->ClearCustomHeaders();

Could part of my problem be that I'm not clearing something correctly?  And when the loop repeats itself it causes a delivery problem for the next recipient in line?

Thank you, Sir.

**Comment by Synchro** [comment]
The `recipient` function is hidden inside the SMTP class, you don't call it directly. You would subclass like this:
```php
<?php
require 'PHPMailerAutoload.php';

class mySMTP extends SMTP
{
    public function recipient($toaddr)
    {
        $res = parent::recipient($toaddr);
        if (!$res) {
            echo 'Help, help I\'m being repressed! ' . $this->last_reply;
        }
    }
}

//Then tell PHPMailer to load it using a subclass:

class myMailer extends PHPMailer
{
    public function getSMTPInstance()
    {
        if (!is_object($this->smtp)) {
            $this->smtp = new mySMTP;
        }
        return $this->smtp;
    }
}

//Then carry on as normal

$mail = new myMailer;
```

For sending to a list, reusing the instance, clearing etc, check out [the mailing list example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps).
