### ISSUE TITLE
Sign() adds harmful newline when using isMail()

### ISSUE THREAD

**Issue by jplitza** [PHPMailer/PHPMailer#372]
As already discussed in [this issue at the Google Code project](https://code.google.com/a/apache-extras.org/p/phpmailer/issues/detail?id=137), when using `Sign()` together with `isMail()` (the default), a harmful newline is inserted before the MIME-Version header, making the mail non-MIME:
```
[...]
X-Priority: 3
X-Mailer: PHPMailer 5.2.9 (https://github.com/PHPMailer/PHPMailer/)

MIME-Version: 1.0
Content-Type: multipart/signed; protocol="application/x-pkcs7-signature"; micalg="sha-256"; boundary="----064CE8F3A12111F854838957DC9A5AC1"

This is an S/MIME signed message

------064CE8F3A12111F854838957DC9A5AC1
Content-Type: multipart/mixed;
	boundary="b1_bc49b80a955f85001bd3c6a53f4bfb23"
Content-Transfer-Encoding: 8bit
[...]
```
This issue still exists in the current master.

Now I don't know if the issues over there still are worked on, thus I created this new issue. If they are still worked on, please simply close this issue. If they aren't, please disable the issue tracker at Google Code to avoid confusion.

**Comment by mrdemc** [comment]
The part that is in between those headers is the value $this->CustomHeader which is an array. The default CustomHeader array is empty, but you might set this yourself in your code. Could you try to find out if it is set? If it is, you could try to run $this->clearCustomHeaders() to see if it solves your problem.
See code https://github.com/PHPMailer/PHPMailer/blob/master/class.phpmailer.php#L1726

**Comment by Synchro** [comment]
The problem is that the S/MIME signing is done with openssl, which returns a complete MIME structure including both header and body, but that is done in the function that creates the body. The branch I just pushed splits that up and adds the new headers into the mailHeaders property, leaving the body without headers as it should be. The resulting structure looks right in both SMTP and Mail modes for me, but please check it out before I merge it. There is so much spaghetti relating to headers :(

**Comment by mrdemc** [comment]
I'll try to reproduce this problem with both codes to see if it is resolved.

**Comment by jplitza** [comment]
Thanks for the quick responses!

@mrdemc Yes, I used custom headers, but removing them with `clearCustomHeaders()` as you mentioned does not help.

@Synchro Your patch helps in the body part, as it removes the MIME-Version and Content-Type lines from the body. Problem is, they don't turn up in the header. :wink:

Also, isn't `preg_split()` a bit overkill in that situation? Wouldn't `explode()` do the job just fine?

**Comment by Synchro** [comment]
I've just pushed another commit to that branch. It's now using explode.

I had been testing with `getSentMIMEMessage()`, but it produces different results than an actual send. I'm now adding the headers into MIMEHeader directly (it could probably use wrapping in secure header or something). The structure on send is now coming out right for me, but `getSentMIMEMessage` is gaining an extra line break.

This is the test example I'm using (along with a local fake mail server on port 2500):

```php
<?php
require 'PHPMailerAutoload.php';
$mail = new PHPMailer;
$dn = array(
    'countryName' => 'UK',
    'stateOrProvinceName' => 'Here',
    'localityName' => 'There',
    'organizationName' => 'PHP',
    'organizationalUnitName' => 'PHPMailer',
    'commonName' => 'PHPMailer Test',
    'emailAddress' => 'phpmailer@example.com'
);
$password = 'password';
$certfile = 'certfile.txt';
$keyfile = 'keyfile.txt';

$pk = openssl_pkey_new();
$csr = openssl_csr_new($dn, $pk);
$cert = openssl_csr_sign($csr, null, $pk, 1);
openssl_x509_export($cert, $certout);
file_put_contents($certfile, $certout);
openssl_pkey_export($pk, $pkeyout, $password);
file_put_contents($keyfile, $pkeyout);

$mail->addAddress('xxx@xxx.cz');
$mail->Subject = "MIME sign Test";
$mail->sign($certfile, $keyfile, $password);
$mail->msgHTML('Hello <strong>everyone</strong>');
//$mail->isMail();
$mail->isSMTP();
$mail->Host = 'localhost';
$mail->Port = 2500;
$mail->Send();
//$mail->preSend();
var_dump($mail->getSentMIMEMessage());
```

**Comment by jplitza** [comment]
By mentioning `getSentMIMEMessage()` you simultaneously told me which method I need for the next step of my program and that it doesn't work for me. :grinning: 

Just to be sure, because it sounded different in your post: The extra blank line in `getSentMIMEMessage()` is caused neither by `isMail()` nor by your patches. It see it in my v5.2.9 checkout using `isSMTP()` as well.

**Comment by Synchro** [comment]
Can you give this latest a go please? It's got a few other bits rolled in from other changes relating to message signing and headers. I'm not too worried about the extra break as it occurs in the multipart root, which is generally never seen, and is harmless - it's more important the broken headers are fixed!

**Comment by jplitza** [comment]
Well, you already merged the mimesign branch obviously, but yes, this fixed it apparently. Thanks!
