### ISSUE TITLE
S/MIME signature with attached certificate chain

### ISSUE THREAD

**Issue by IgitBuh** [PHPMailer/PHPMailer#376]
I'd like to share a problem and a solution that I've experienced and think that might concern others as well.

The problem originated from the fact that the current Sign() implementation in PHPMailer only attaches the public signature of the certificate used to sign the file. If you think that this is enough I encourage you to get a free Comodo or Symantec email certificate and try it out yourself. The message will arrive telling you "The system cannot determine whether the certificate used to create this signature is trusted or not."
You can then manually look into the certificates used and Windows might at some point update its CA certificates so that your personal certificate will work from then on. This won't happen automatically and you're not going to ask every recepient to update their certificates to be compatible with your signature.

What you can do instead is send the whole certificate chain which will then only require the top level CA to be known by the recepient (which is basically always true) instead of the intermediate certificates as well.

Unfortunately even if the certificate file used in Sign() includes the whole chain it's not going to be included in the email that's sent. So when using a certificate with PHPMailer the email was received with an unknown signature trust status, the same certificate used in Outlook resulted in a perfectly signed email at the recepient.

So I dug in and found out that PHPMailer uses openssl_pkcs7_sign() to sign the email internally:
http://php.net/manual/en/function.openssl-pkcs7-sign.php

This method takes an optional parameter $extracerts. If I use that to provide a file with the certificate chain the email arrives perfectly fine.
Of course I'd prefer it if that chain could automatically be extracted from the main certificate file used, but apparently openssl_pkcs7_sign() simply doesn't do that.

So I created 3 files from my pfx file:
Key:  openssl pkcs12 -in "mycertificate.pfx" -out "key.pem" -nocerts
Cert: openssl pkcs12 -in "mycertificate.pfx" -out "cert.pem" -clcerts -nokeys
CAs:  openssl pkcs12 -in "mycertificate.pfx" -out "certchain.pem" -cacerts

Then I did the following changes to the class.phpmailer.php:

~530:
```
    /**
     * The S/MIME extra certificates ("CA Chain") file path.
     * Mod to fix "The system cannot determine whether the certificate used to create this signature is trusted or not."
     * @type string
     * @access protected
     */
    protected $sign_extracerts_file = '';   //<--- new
```
~1900:
```
    if (@openssl_pkcs7_sign(
        $file,
        $signed,
        'file://' . realpath($this->sign_cert_file),
        array('file://' . realpath($this->sign_key_file), $this->sign_key_pass),
        null,
        PKCS7_DETACHED,
        $this->sign_extracerts_file //May not be used with "file://"!
    )
    )
```
~3120:
```
    public function sign($cert_filename, $key_filename, $key_pass, $extracerts_filename='')
    {
        $this->sign_cert_file = $cert_filename;
        $this->sign_key_file = $key_filename;
        $this->sign_key_pass = $key_pass;
        $this->sign_extracerts_file = $extracerts_filename;  //<--- new
    }
```
Now I can sign the email with an (optional) 4th parameter:
`$mail->sign("cert.pem", "key.pem", $key_pass, "certchain.pem")`
and everything's fine!

Although I'm happy with the solution for myself, I feel like it relevant for most people signing their emails with PHPMailer. I'd welcome to see that addition in one of the next official releases. By making the 4th paramter optional it wouldn't even break any existing user code.

**Comment by Synchro** [comment]
This looks great - could you put these changes in a fork?

That issue with using the relative path to the extra certs is a bit strange - I would want to be very sure of how that works.

**Comment by IgitBuh** [comment]
> That issue with using the relative path to the extra certs is a bit strange - I would want to be very sure of how that works.

Well it probably doesn't have to be a relative path, but it definitely must be used without "file://" in front. I don't know why. It was driving me nuts for a while, but searching the web I found some examples like the one from Maciej_Niemir at http://php.net/manual/en/function.openssl-pkcs7-sign.php or some at stackoverflow that showed a different path format than the other two path parameters.

> could you put these changes in a fork?

To be honest, I have absolutely no experience in how everyhing works here. My idea was to share that information and see what happens. If you want you're welcome to use the code in any way you want.

**Comment by IgitBuh** [comment]
... and I just realized that I've used a false or at least confusing naming for the new parameter. Instead of "$sign_key_extracerts" / "$key_extracerts" it should probably be "$sign_extracerts_file" / "$extracerts_filename"

**Comment by IgitBuh** [comment]
I've edited the issue description (variable names and "file:" issue) according to my last comments.

**Comment by Synchro** [comment]
I just pushed support for all this based on your code, thank you! I also built a unit test to cover it and verified the signed message using `openssl smime`. I still need to finalise a fix for the related #372.

**Comment by Synchro** [comment]
A little quick off the mark - I think I just found a bug in `openssl_pkcs7_sign` - if you pass a parameter in `extracerts`, it tries to open it as a file - *even if it's null!*

In the code, this works fine:

```php
                if (openssl_pkcs7_sign(
                    $file,
                    $signed,
                    'file://' . realpath($this->sign_cert_file),
                    array('file://' . realpath($this->sign_key_file), $this->sign_key_pass),
                    null,
                    PKCS7_DETACHED
                )
```
but this:

```php
                if (openssl_pkcs7_sign(
                    $file,
                    $signed,
                    'file://' . realpath($this->sign_cert_file),
                    array('file://' . realpath($this->sign_key_file), $this->sign_key_pass),
                    null,
                    PKCS7_DETACHED,
                    null
                )
```

produces `Warning: openssl_pkcs7_sign(): error opening the file`. Reporting as a PHP bug.

I can work around this by making 2 versions of the call, but it's annoying...

**Comment by IgitBuh** [comment]
Why would you pass null as the fourth parameter!?
With the current code both these versions work absolutely fine:
`$mail->sign("cert.pem", "key.pem", $key_pass)`
`$mail->sign("cert.pem", "key.pem", $key_pass, "certchain.pem")`

**Comment by IgitBuh** [comment]
Oh dang it, you're right ... but basically not because of null but apparently an empty string ('') causes the problem as well. I thought I've tried that as well... Sorry. :-/

**Comment by Synchro** [comment]
Reported [here](https://bugs.php.net/bug.php?id=69197). Test script [here](https://gist.github.com/Synchro/b9e4625013077def0cf7)

I found it does the same regardless of whether it's null or an empty string. Of course I'm not passing a literal null in the code, but the `$this->sign_extracerts_file` property, which may contain those values. The only way around it is to not pass the param at all, i.e. have two different calls.

**Comment by Synchro** [comment]
I just pushed a fix for this
