### ISSUE TITLE
"CharSet" incompatibility with "AltBody" and "AddEmbeddedImage" at the same time.

### ISSUE THREAD

**Issue by cefaloide** [PHPMailer/PHPMailer#377]
Hello,
I have this code where sending body in UTF-8 is not working:

    <?php
    	require '../phpmailer/PHPMailerAutoload.php';
    	$mail = new PHPMailer;
    	$mail->CharSet = 'UTF-8';
    	$mail->setFrom('from@example.com', 'First Last');
    	$mail->addAddress('whoto@example.com', 'John Doe');
    	$mail->Subject = 'PHPMailer mail() test';
    	$mail->AltBody = 'This is a plain-text message body';
    	$mail->AddEmbeddedImage('img_00/Mailing_febrero2015_02.jpg', 'fondo', 'fondo.jpg');
    	$mail->Body = 'árbol'; 
    	if (!$mail->send()) {
    	echo "Mailer Error: " . $mail->ErrorInfo;
    	} else {
    	echo "Message sent!";
    	}
    ?>

But if I remove the "AltBody" or "AddEmbeddedImage" it send correctly in UTF-8. Why this occurs?
There is a way to add an alternative body and embedded image at the same time?
Thanks!

Edit:
If I check the email with Outlook 2007 I see: "Ã¡rbol" 
If I check with webmail account or the receiver is a gmail account, I see: "árbol"

**Comment by Synchro** [comment]
You need to post an an example of a received message that's malformed.

**Comment by Synchro** [comment]
Please can you check out the master branch which has some changes relating to this and give it a try - I've tried various things but I can't make it go wrong as you describe. See also #279

**Comment by cefaloide** [comment]
Thanks, but I have updated the phpmailer version and I get the same result.
There is something can I do to help?

**Comment by Synchro** [comment]
As I said earlier, I need to see an example of a malformed message.

**Comment by cefaloide** [comment]
If I check the email with Outlook 2007 I see: 
Ã¡rbol

If I check with webmail account or the receiver is a gmail account, I see: 
árbol

**Comment by Synchro** [comment]
No, I need to complete raw message source (you can edit the email address) - what you see when you 'view source' on the message.

**Comment by nik045** [comment]
:+1:
