### ISSUE TITLE
PHP SSL Extension requirement issue

### ISSUE THREAD

**Issue by Ratnarashi** [PHPMailer/PHPMailer#378]
I installed PHPMailer 5.2.9 on a system without the SSL extension loaded.

Setting $mail->SMTPSecure = 'ssl'; Generated an error that the SSL extension was not loaded.

If I set $mail->SMTPSecure = 'tls'; No error was generated but the tls connection fails.

It seems that 'tls' requires SSL to be loaded but doesn't complain if it is not.

Having loaded the SSL extension both ssl and tls work fine.

**Comment by Synchro** [comment]
This is fixed in the branch linked above, will make it into master soon. It's now much clearer and more consistent about reporting missing extensions.
