### ISSUE TITLE
PHPMailer fails on otherwise working smtp server

### ISSUE THREAD

**Issue by perryhs** [PHPMailer/PHPMailer#380]
I’ve run into an interesting smtp connect failed conundrum with PHPMailer. I’ve looked around on the net for solutions, but found (like issues #270 and #341 in Github) that all of the issues posted deal with a possibly misconfigured or defective postfix server.

My problem is somewhat different. My postfix server (Ubuntu 15.04) works perfectly. I can send and receive mail from clients on different networks, and I have a Thunderbird client with an account on my postfix server that works fine.

However,  phpMailer doesn’t work with it.

My setup is as follows:

I’m using xampp on windows7 to test my php code. I have not configured php.ini for mail, as phpMailer does not use the mail() function. I’m assuming this is correct.

I’m testing with the example code that I downloaded from github as follows:
require '../PHPMailerAutoload.php';

$mail = new PHPMailer;
$mail->isSMTP();
$mail->SMTPDebug = 4;
$mail->Debugoutput = 'html';
$mail->Host = "smtp.hornnes.vgs.net";
$mail->Port = 25;
$mail->SMTPAuth = true;
$mail->Username = "support@hornnes.vgs.net";
$mail->Password = "mypassword";
$mail->setFrom('support@hornnes.vgs.net', 'Blah blah');
$mail->addAddress('perry.hart.sweetser@setesdal.vgs.no', 'Perry Sweetser');
$mail->CharSet = 'ISO 8859';
$mail->ContentType = 'text/plain';
$mail->IsHTML(false);
$mail->Subject = 'PHPMailer SMTP test';
$mail->Body    = 'This is the message body ';

if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}

This code results in the following debug text on the client:

Connection: opening to smtp.hornnes.vgs.net:25, t=300, opt=array ()
Connection: opened
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "220 smpt.hornnes.vgs.net ESMTP Postfix (Ubuntu)"
SMTP -> get_lines(): $data is "220 smpt.hornnes.vgs.net ESMTP Postfix (Ubuntu)"
SERVER -> CLIENT: 220 smpt.hornnes.vgs.net ESMTP Postfix (Ubuntu)
CLIENT -> SERVER: EHLO localhost
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "250-smpt.hornnes.vgs.net"
SMTP -> get_lines(): $data is "250-smpt.hornnes.vgs.net"
SMTP -> get_lines(): $data was "250-smpt.hornnes.vgs.net"
SMTP -> get_lines(): $str is "250-PIPELINING"
SMTP -> get_lines(): $data is "250-smpt.hornnes.vgs.net250-PIPELINING"
SMTP -> get_lines(): $data was "250-smpt.hornnes.vgs.net250-PIPELINING"
SMTP -> get_lines(): $str is "250-SIZE 10240000"
SMTP -> get_lines(): $data is "250-smpt.hornnes.vgs.net250-PIPELINING250-SIZE 10240000"
SMTP -> get_lines(): $data was "250-smpt.hornnes.vgs.net250-PIPELINING250-SIZE 10240000"
SMTP -> get_lines(): $str is "250-ETRN"
SMTP -> get_lines(): $data is "250-smpt.hornnes.vgs.net250-PIPELINING250-SIZE 10240000250-ETRN"
SMTP -> get_lines(): $data was "250-smpt.hornnes.vgs.net250-PIPELINING250-SIZE 10240000250-ETRN"
SMTP -> get_lines(): $str is "250-STARTTLS"
SMTP -> get_lines(): $data is "250-smpt.hornnes.vgs.net250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS"
SMTP -> get_lines(): $data was "250-smpt.hornnes.vgs.net250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS"
SMTP -> get_lines(): $str is "250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $data is "250-smpt.hornnes.vgs.net250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $data was "250-smpt.hornnes.vgs.net250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $str is "250-8BITMIME"
SMTP -> get_lines(): $data is "250-smpt.hornnes.vgs.net250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS250-ENHANCEDSTATUSCODES250-8BITMIME"
SMTP -> get_lines(): $data was "250-smpt.hornnes.vgs.net250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS250-ENHANCEDSTATUSCODES250-8BITMIME"
SMTP -> get_lines(): $str is "250 DSN"
SMTP -> get_lines(): $data is "250-smpt.hornnes.vgs.net250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS250-ENHANCEDSTATUSCODES250-8BITMIME250 DSN"
SERVER -> CLIENT: 250-smpt.hornnes.vgs.net250-PIPELINING250-SIZE 10240000250-ETRN250-STARTTLS250-ENHANCEDSTATUSCODES250-8BITMIME250 DSN
CLIENT -> SERVER: QUIT
SMTP -> get_lines(): $data was ""
SMTP -> get_lines(): $str is "221 2.0.0 Bye"
SMTP -> get_lines(): $data is "221 2.0.0 Bye"
SERVER -> CLIENT: 221 2.0.0 Bye
Connection: closed
SMTP connect() failed.
Mailer Error: SMTP connect() failed.

Note that I have not set up TLS (yet). Also note that there is no “authentication failed” issue. 
My mail log on the server tells me this, in reference to the above:

March 17 10:44:31 Smtp postfix/smtpd: connect from 81.166.58.27.static.lyse.net
March 17 10:44:31 Smtp postfix/smtpd: disconnect from 81.166.58.27.static.lyse.net

(Normally,  postfix tells me (on something like 16 lines) something like:  imapd LOGIN user=……. Plus that the message has been sent.)

This is my postfix main.cf: (I can’t see anything here that would stop the connection…)

smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
biff = no

append_dot_mydomain = no
readme_directory = no

# TLS parameters
smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
smtpd_use_tls=yes
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache

smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated defer_unauth_destination
myhostname = smpt.hornnes.vgs.net
alias_maps = hash:/etc/postfix/aliases
alias_database = hash:/etc/postfix/aliases
myorigin = hornnes.vgs.net

mydestination =

relayhost = 
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 81.166.59.24/29
mailbox_command = procmail -a "$EXTENSION"
mailbox_size_limit = 0
recipient_delimiter = +

inet_interfaces = all
inet_protocols = all

delay_warning_time = 1h
unknown_local_recipient_reject_code = 450
maximal_queue_lifetime = 3d
minimum_backoff_time = 1000s
maximum_backoff_time = 8000s
smtp_helo_timeout = 60s

smtpd_recipient_limit = 2
smtpd_soft_error_limit = 3
smtpd_hard_error_limit = 12

smtpd_helo_restrictions = permit_mynetworks, warn_if_reject reject_non_fqdn_hostname, reject_invalid_hostname, permit
smtpd_sender_restrictions = permit_mynetworks, warn_if_reject reject_non_fqdn_sender, reject_unknown_sender_domain, reject_unauth_pipelining, permit
smtpd_recipient_restrictions = reject_unauth_pipelining, permit_mynetworks, reject_non_fqdn_recipient, reject_unknown_recipient_domain, reject_unauth_destination, permit
smtpd_client_restrictions = reject_rbl_client sbl.spamhaus.org, reject_rbl_client blackholes.easynet.nl
smtpd_data_retrictions = reject_unauth_pipelining

smtpd_helo_required = yes
smtpd_delay_reject = yes

disable_vrfy_command = yes
virtual_mailbox_base = /var/spool/mail/virtual
virtual_mailbox_maps = mysql:/etc/postfix/mysql_mailbox.cf
virtual_alias_maps = mysql:/etc/postfix/mysql_alias.cf
virtual_mailbox_domains = mysql:/etc/postfix/mysql_domains.cf

virtual_uid_maps = static:5000
virtual_gid_maps = static:5000

So I was wondering if anyone has an idea. It’s probably staring me right in the face, but sometimes I don’t see what I should be seeing.

Thanks, phs

**Comment by Myicefrog** [comment]
Hi，it seems like the connection problem。

I used to config the PHPMailer in the PHP framewor called ThinkPHP， and I have the similar problem.

At last, I config as the following and it return the “success” information.

It may not resolve your problem,but I hope it will give you some help.

             $mail->IsSMTP();
             $mail->SMTPSecure = 'ssl'; 
             $mail->SMTPDebug = 1;
             $mail->Host = 'smtp.126.com';
	     $mail->SMTPAuth = true;
             $mail->Username = 'haikuotiankong2007';
             $this->_mail->Password = '*******';
	     $this->_mail->Port = 465;
	     $mail->From = 'haikuotiankong2007@126.com';
	     $mail->AddAddress("$address", "my friend");
             $mail->IsHTML(true);

**Comment by Synchro** [comment]
You don't need to set `SMTPDebug = 4` - it just results in too much output that there's no need for here - set it to 2.

You have authentication without encryption, which generally will not be accepted, and I can see in the capabilities offered by the server that it's advertising `STARTTLS`, but not `AUTH`, so there is no way it can log in here. You need to sort out your TLS. You're also trying to submit for outbound, which doesn't usually happen on port 25 but on port 465/ssl or 587/tls.

PHPMailer does call `mail()` if you call `isMail()`.

**Comment by Myicefrog** [comment]
I agree with Synchro.
So I advice that you can use my configuration that I have mentioned befor.

change TLS to SSL,use the port 465 or 587

**Comment by Synchro** [comment]
Don't do that. SSL on port 465 has been deprecated since 1998. I suggest you base your code on the gmail example in the examples folder.

**Comment by Myicefrog** [comment]
SSL on port 587 is better than 465?

I am not good at ssl or tls

**Comment by Synchro** [comment]
The choices are SSL on 465 or TLS on 587. You can't have TLS on 465 or SSL on 587 (technically you can, but nobody does).

**Comment by Myicefrog** [comment]
Thanks for your comments!

I just use the ssl port on 587, find out it also works for the smtp.126.com(just for fun),
though Synchro do not recommend to do that,haha

**Comment by perryhs** [comment]
OK, I got it. You are correct in that I have not completed the final configuration for a secure server; however, the instructions I've been following tell me not to configure that part until I can verify that everything else works - both internally and externally on port 25. I had assumed that PHPMailer would work like everything else I've tested on port 25. My fauxpas.

I'll complete the security configuration and try it again using port 587. Then I'll get back to you tomorrow with the results...

Thanks for your help. PHPMailer will solve a lot of issues for me if I can get it to work.

**Comment by Synchro** [comment]
It does work the same as everything else. Your mail server is not saying it will allow unencrypted auth, yet that's what you're asking PHPMailer to do, and so of course it's failing.

**Comment by AmaliDeveloper** [comment]
You can get the solution for send mail using phpmailer Here [Link](https://youtu.be/Edx7pPcPfs8)

**Comment by aabantob** [comment]
alguien puede ayudarme con una duda  esta contraseña que se pide aquí    $mail->Password = '*******'; es la clave del correo que se coloca o del servidor?
