### ISSUE TITLE
add attachment from client side

### ISSUE THREAD

**Issue by Noob4sure** [PHPMailer/PHPMailer#384]
first, i'm really sorry if i'm wrong for put this question here, never use github, so i absolutely got no idea how to properly use it
anyway, i'm too a complete noob at php, i'm making an app with C#, within the app user can take screenshot and send it with email, i already made the php page and use your plugin which work excellent, but i need to put the screenshot as attachment
when i see the example on your code, i assume it'll target directly to server directory (CMIIW) which i can't use since the screenshot still yet on client phone/desktop
any suggestion the correct way to approach this?
please forgive me if i made any mistake, and thank you in advance :)

**Comment by Synchro** [comment]
File uploads are out of PHPMailer's scope and you need to do that yourself, so [read the docs on that](http://php.net/manual/en/features.file-upload.php). Once you have processed the upload, you will be able to attach it with `addAttachment()`, just like any other local file. There is a relevant PHPMailer example [here](https://github.com/PHPMailer/PHPMailer/blob/master/examples/send_file_upload.phps). I can't tell you how to get your client app to submit the image, that's up to you.

**Comment by Noob4sure** [comment]
thank you sir!, based on your answer, i done it and works perfectly :D
