### ISSUE TITLE
Using PHPMailer to send emails from localhost

### ISSUE THREAD

**Issue by nestsman** [PHPMailer/PHPMailer#385]
I have been unsuccessful in being able to send email from my local testing environment after following this tutorial exactly:

http://webdevtuts.net/quicktips/how-to-send-emails-using-your-localhost-wamp-mamp-or-xampp/

Does anyone have any suggestions on how to get this working?

Thank you!

**Comment by Synchro** [comment]
That doesn't appear to have anything to do with PHPMailer, though one common reason for using PHPMailer is to avoid having to do that! It doens't actually say anything very useful - you need to look at mamp/xampp docs and make sure your local mail server is working, and read the SMTP section in the PHP docs as it suggests.
