### ISSUE TITLE
Custom boundary

### ISSUE THREAD

**Issue by sergeyklay** [PHPMailer/PHPMailer#389]
Hi!

Can you please add ability to override  `$this->boundary` please?

```php
    public function createHeader()
    {
        $result = '';
        // Set the boundaries
        $uniq_id = md5(uniqid(time()));
        $this->boundary[1] = 'b1_' . $uniq_id;
        $this->boundary[2] = 'b2_' . $uniq_id;
        $this->boundary[3] = 'b3_' . $uniq_id;

        // ...
```

We use it for packaging of useful information, which is then to use the analysis in the FBL (abuse) mail parser.
Eg:

```php
        $bdata = json_encode([
            'mid' => (int) $this->mail_id,
            'uid' => (int) $this->user_id,
            'src' => $this->send_worker,
            'pid' => (int) $this->project_id,
            'srv' => $this->mail_server_name,
        ]);

        $boundary1 = base64_encode($bdata);
```

Thanks.

**Comment by ooxi** [comment]
I'm not sure abusing the boundary in such a way is wise. Couldn't you just add a custom mail header?

Moreover it would be better to let the user specify just the boundary prefix so PHPMailer can create new boundaries when needed.

**Comment by Synchro** [comment]
I agree that this is better put into a custom header - the mail servers I use do exactly this for the same purpose. The way these boundaries are created is not pretty, but it's a side effect of PHPMailer's preset MIME structures, and at least it's consistent.

**Comment by Synchro** [comment]
You can always subclass and implement this the way you want - that is much of the point of a library.

**Comment by sergeyklay** [comment]
Thanks

**Comment by Med-All** [comment]
Any tips on that?

I need to add/update

```
--b1_KyZbvbrSl55hdWoQf7uUOwdfF2oGjqnCyP6rqNmlA
Content-Type: text/plain; name="test.txt"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: attachment; filename=test.txt
```
to looks like

--b1_KyZbvbrSl55hdWoQf7uUOwdfF2oGjqnCyP6rqNmlA
Content-Type: text/plain; name="test.txt"; charset=utf-8
Content-Transfer-Encoding: quoted-printable
Content-Disposition: attachment; filename=test.txt
Content-ID: 20cca107-2625-49ce-9357-95254a59147f@127.0.0.1

so for the `Content-Type` header was added `charset` parameter and then added new header `Content-ID` for

`$mail->addStringAttachment($test, 'test.txt', 'quoted-printable');`

Any tips on that?

**Comment by felloz** [comment]
Still dosent exist a boundary object for php mailer?
