### ISSUE TITLE
php 5.3.19 fails to open class.phpmailer.php v 5.2.9 on Centos 5

### ISSUE THREAD

**Issue by kenITR** [PHPMailer/PHPMailer#391]
PHPMailer handles DKIM signing perfectly on my dev machine (which is fantastic! thank you!) while version 5.1 did not; however, when I substitute PHPMailer 5.2.9 for 5.1 on my production machine, I get a "fail to open" class.phpmailer.php (or PHPMailerAutoload.php, either way).  All permissions are equal and so are all routines. Production runs PHP 5.3.19 CentOS 5 while Development run PHP 5.4.23 under CentOS 6. One other difference is that SELinux is enabled and configured on production but turned off in development. Why is it that phpmailer 5.1 can run under the SELinux policies but 5.2.9 cannot, and how can I fix this without making SELinux (which I am assuming, but do not know for sure, is the problem) too loose.

Any help will be much appreciated as I am eager to get DKIM working.

**Comment by Synchro** [comment]
Sounds like you just need to make sure you're using the right path to the autoloader. I don't think this is anything to do with SELinux.

**Comment by Synchro** [comment]
One other thing - PHP 5.3 is no longer supported, and [5.4 expires in 5 months](http://php.net/supported-versions.php). if you're doing anything new you should be on 5.6.

**Comment by kenITR** [comment]
Hi,

Thanks for your reply. I put the new phpmailer and autoloader versions 
exactly where the old ones were.

Ken



On 04/01/2015 10:27 AM, Marcus Bointon wrote:
>
> Sounds like you just need to make sure you're using the right path to 
> the autoloader. I don't think this is anything to do with SELinux.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PHPMailer/PHPMailer/issues/391#issuecomment-88504758>.
>


-- 
Ken Loomis
IT Resources
1646 Massachusetts Ave
Lexington, MA 02420

**Comment by kenITR** [comment]
Thanks, again. CentOS 5 does not support higher than 5.3. In order to 
move to php 5.6 we need to migrate our server to CentOS 6 which a 
planned but much dreaded move.  PHPmailer claims it works under 5.3.


On 04/01/2015 10:32 AM, Marcus Bointon wrote:
>
> One other thing - PHP 5.3 is no longer supported, and 5.4 expires in 5 
> months <http://php.net/supported-versions.php>. if you're doing 
> anything new you should be on 5.6.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PHPMailer/PHPMailer/issues/391#issuecomment-88506495>.
>


-- 
Ken Loomis
IT Resources
1646 Massachusetts Ave
Lexington, MA 02420

**Comment by Synchro** [comment]
Try loading the autoloader using an absolute path to be sure.

PHPMailer support PHP versions all the way back to 5.0, but 5.3 (and older versions) is no longer getting security updates, so running it is risky.

**Comment by kenITR** [comment]
I failed to mention that the reason for the fail to open error was "permission denied". As I mentioned, the application was able to open phpmailer using the same path system. My guess is that the new version is trying to access some part of the system that the prior one did not, but I cannot find where that is.

**Comment by Synchro** [comment]
This really hasn't changed. The error you're getting is arising before any PHPMailer code is run, so it can't be anything that's in the files. Are the permissions correct on your new copy folder and files?

**Comment by kenITR** [comment]
Also, if it were a php error, I'd think I'd get a php error not a system error. (Ah, I see you posted that). The file permissions and ownership are identical.

**Comment by Synchro** [comment]
If it is SELInux, it should be logging the block.

**Comment by kenITR** [comment]
I'm using the same directory for both versions so that can't be it.

I turned on SELinux on our stage machine and although it didn't run 
sendmail, it had no problem running PHPMailer. I can't test this on 
production until tonight.

There is an execute bit for the owner of the old phpmailer file that 
doesn't exist on the new one. I assumed that was a mistake, but now it 
is the only difference I can find. I can't imagine that would make a 
difference; the owner isn't the one running it and it should be 
necessary anyway, should it? I'll test it tonight.

By the way, I am using the old setup of an class extending phpmailer 
with some default values, but I'm using the same class file for both 
versions.

Ken

On 04/01/2015 10:57 AM, Marcus Bointon wrote:
>
> This really hasn't changed. The error you're getting is arising before 
> any PHPMailer code is run, so it can't be anything that's in the 
> files. Are the permissions correct on your new copy folder and files?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PHPMailer/PHPMailer/issues/391#issuecomment-88513823>.
>


-- 
*Ken Loomis*
IT Resources
1646 Massachusetts Avenue
Lexington, MA 02420
781-863-2661 x 111

**Comment by Synchro** [comment]
The execute bit generally should not be set on PHP files run by your web server. You need to cut this back to a minimal test case to isolate the problem - write a script that does nothing but include the PHPMailer autoloader from an absolute path, i.e just this:

```php
<?php
require '/absolute/path/to/PHMailerAutoload.php';
```

Something else to try - `su` to the user it's being run as and see if you can read the PHPMailer files.

**Comment by kenITR** [comment]
I assume apache is running it, but I don't think I can su as apache. 

I ran your suggested php script and it was consistent. I could open  class.phpmailer.php v 5.1 but not v 5.2.9.  I could not open either directly but I went through an intermediary script as shown below.

The setup is a bit convoluted. The script requires mailConfig.php which is located in root that has some default values, and it requires mailClass.inc which is a php file above root that has an absolute path to phpmailer (above root) that extends phpmailer.  Here is the mailClass.inc script:

<?php
require_once('/var/www/phpmailer/class.phpmailer.php');
class ITRMailer extends PHPMailer {
    var $priority = 3;
    var $to_name;
    var $to_email;
    var $From = null;
    var $FromName = null;
    var $Sender = null;

    function ITRMailer()     {
      global $site;
      // Comes from config.php $site array
      // We use sendmail. Smtp is not enabled.
      if($site['smtp_mode'] == 'enabled') {
        $this->Host = $site['smtp_host'];
        $this->Port = $site['smtp_port'];
        if($site['smtp_username'] != '') {
         $this->SMTPAuth  = true;
         $this->Username  = $site['smtp_username'];
         $this->Password  =  $site['smtp_password'];
        }
        $this->Mailer = "smtp";
      }
    
      if(!$this->FromName) {
        $this-> FromName = $site['from_name'];
      }
      if(!$this->From) {
        $this->From = $site['from_email'];
      }
      if(!$this->Sender) {
        $this->Sender = $site['from_sender'];
      }
      
      if(!$this->DKIM_domain) {
        $this->DKIM_domain = $site['DKIM_domain'];
        $this->DKIM_private = $site['DKIM_privatekey'];
        $this->DKIM_selector = $site['DKIM_selector'];
        $this->DKIM_passphrase = $site['DKIM_passphrase'];
      }
      
      /* in phpmailer the returnPath is automatically set to the 
       * ->Sender, otherwise set it with ReturnPath
      if(!$this->returnPath) {
        $this->ReturnPath = $site['returnPath'];
      } 
       * */
       $this->Priority = $this->priority;
     }
}

**Comment by kenITR** [comment]
Well, all of this was solved by moving class.phpmailer.php into the same path as the calling mailClass.inc file and editing mailClass appropriately. It still remains a mystery why the old version could be opened in its original location while the new one could not. The upshot is that this 6 yr old routine now is a bit cleaner and DKIM works! Thanks very much for your help and a great program.

**Comment by Synchro** [comment]
Mysterious! Glad you fixed it.

One observation - your SMTP check (though you're not using it) could be improved a little, avoiding setting `Mailer` directly:

```php
if($site['smtp_mode'] == 'enabled') {
    $this->isSMTP();
    $this->Host = $site['smtp_host'];
    $this->Port = $site['smtp_port'];
    if($site['smtp_username'] != '') {
         $this->SMTPAuth  = true;
         $this->Username  = $site['smtp_username'];
         $this->Password  =  $site['smtp_password'];
    }
}
```

**Comment by kenITR** [comment]
Thanks for your help, Marcus. I really appreciate it. And thanks for the 
helpful critique.

On 4/2/2015 2:01 AM, Marcus Bointon wrote:
>
> Mysterious! Glad you fixed it.
>
> One observation - your SMTP check (though you're not using it) could 
> be improved a little, avoiding setting |Mailer| directly:
>
> if($site['smtp_mode']==  'enabled') {
>      $this->isSMTP();
>      $this->Host  =  $site['smtp_host'];
>      $this->Port  =  $site['smtp_port'];
>      if($site['smtp_username']!=  '') {
>           $this->SMTPAuth   =  true;
>           $this->Username   =  $site['smtp_username'];
>           $this->Password   =   $site['smtp_password'];
>      }
> }
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PHPMailer/PHPMailer/issues/391#issuecomment-88753381>.
>


-- 
Ken Loomis
IT Resources
1646 Mass Ave.
Lexington, MA 02420
781-863-2661
