### ISSUE TITLE
PHPMailer for MSExchange

### ISSUE THREAD

**Issue by vijaydogra** [PHPMailer/PHPMailer#392]
Hi,

I have been using PHPMailer with below code to send email to users using my MS Exchange account. Mail does arrives, however, it arrives even if I enter wrong credentials for MS Exchange account.  Any help regarding same would be appreciated .

```php
    $mail = new PHPMailer();
    $mail->isSendMail();
    $mail->SMTPDebug = 1;
    $mail->SMTPAuth = true;
    $mail->Port = 135;
    $mail->Host = "myserver.com";
    $mail->Username = "myemail@hotmail.com";
    $mail->Password = "mysecret";
    $mail->setFrom("MyName", "Name");
    $mail->AddAddress("recipent@gmail.com");
    $mail->Subject  = "Hello"; 
    $mail->Body     = "Test message";
    if(!$mail->Send()) {
        echo "Mail not sent";
    }else{
        echo "Mail sent";
    }
```

**Comment by Synchro** [comment]
That's a problem with your Exchange server, not PHPMailer!

**Comment by vijaydogra** [comment]
Ok, for now if we agree that it could be my exchange server problem, why would email be still sent and received to recipient email even in case of credentials being wrong? 
Am sorry, if this is too obvious question for you, however, am struggling with this for past few days.

**Comment by Synchro** [comment]
Your server is allowing sending by someone with the wrong credentials - if it's set up correctly it will deny the client the ability to send. Yours is not. It's nothign to do with the client.

**Comment by vijaydogra** [comment]
My client is outlook.com with port 135, am sending email from
vijaydogra123@hotmail.com with my wrong password abcdefgh.

If I try to do same with web, it says me wrong password.

Again, apologies for this and thank you for answering

**Comment by Synchro** [comment]
Port 135? That port is used by Outlook for Exchange RPC services. If that server is set up to receive email for that address, then port 25 submission will not require a login (i.e. it looks like normal inbound SMTP). It may be that your Exchange server accepts SMTP on that port, but whatever it is doing, it's not PHPMailer's problem!

**Comment by vijaydogra** [comment]
Ok thank you for the support really appreciate it
