### ISSUE TITLE
eregi Deprecated as of PHP 5.3.0

### ISSUE THREAD

**Issue by kayess2015** [PHPMailer/PHPMailer#394]
eregi is Deprecated as of PHP 5.3.0
Have modified class.phpmailer.php line 594 with the following 
```
//      if(eregi('^(.+):([0-9]+)$', $hosts[$index], $hostinfo)) {
      if(preg_match('^(.+):([0-9]+)$^', $hosts[$index], $hostinfo)) {
```
and seems to work fine.

**Comment by Synchro** [comment]
This was fixed years ago. Please don't report bugs in old versions.
