### ISSUE TITLE
SPF Guidelines and the iPhone

### ISSUE THREAD

**Issue by kenITR** [PHPMailer/PHPMailer#395]
We send emails on behalf of our customers using PHPMailer and Sendmail. In order to prevent our mail being tagged as SPAM we have set up our PHPMailer configs according to the SPF.org guidelines. (http://www.openspf.org/Best_Practices/Webgenerated). This works great for all receiving devices (our SPAM scores are zero) except the iPhone and iPad which do not respect the reply_to header and send replies back to us.
 
This is not strictly a PHPMailer issue, but I wonder if there is any work-around.

**Comment by Synchro** [comment]
I don't think this is true. For example, the notification I received for this ticket was sent with a from header of `kenITR <notifications@github.com>`, and a reply-to header of `PHPMailer/PHPMailer <reply+00013e9984b60787b72092dcab6264a91abe472716e1deb492cf00000001113a79a492a169ce03f8f925@reply.github.com>`. When I hit reply in iOS mail, it created a message addressed to the reply-to address, not the from address. I see that you said `reply_to`, not `reply-to`, so make sure you're not doing that wrong - use PHPMailer's built-in reply-to support, don't roll your own custom header.

**Comment by kenITR** [comment]
Hi Marcus,

Thanks for your reply. The server this mail comes from is not the one in 
question.

I got a reply from the folks at SPF.org IRC channel. They said that SPF 
doesn't care about the FROM: Header except in the case of SMPT, so that 
I can use the user's email address in the from: header as long as I use 
the host's url in the Sender: Header.

I'm testing that now.

Ken



On 04/06/2015 02:12 PM, Marcus Bointon wrote:
>
> I don't think this is true. For example, the notification I received 
> for this ticket was sent with a from header of |kenITR 
> <notifications@github.com>|, and a reply-to header of 
> |PHPMailer/PHPMailer 
> <reply@reply.github.com>|. 
> When I hit reply in iOS mail, it created a message addressed to the 
> reply-to address, not the from address. I see that you said 
> |reply_to|, not |reply-to|, so make sure you're not doing that wrong - 
> use PHPMailer's built-in reply-to support, don't roll your own custom 
> header.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PHPMailer/PHPMailer/issues/395#issuecomment-90179710>.
>


-- 
*Ken Loomis*
IT Resources
1646 Massachusetts Avenue
Lexington, MA 02420
781-863-2661 x 111

**Comment by Synchro** [comment]
It doesn't matter which server it's from as it's a client issue. Forging From addresses will always run into SPF trouble, so it's really worth avoiding - people are always running into this on contact forms, and this isn't much different. SMTP doesn't care about headers at all, only the envelope (set via `Sender` in PHPMailer).
