### ISSUE TITLE
E-mail in spambox when sent from other server, how to solve?

### ISSUE THREAD

**Issue by eavuursteen** [PHPMailer/PHPMailer#403]
Hi, we've an application with which we send e-mails to mailinglists.
This works great when sending the mails from an e-mailadres from which the domain exists physically on the server, but when we use a domain from another server, the e-mail will be delivered into the spambox.
The reason is an error in the SPF-record validation which only validates for domains from that one server.

What we would like:
- Send the mail from our "no-reply@applicationname.ext"-address (our applications domain on server)
- Show in e-mailclient the mail address of user "info@userdomain.ext" (users domain on other server)

We've tried to accomplish this by setting the "from"-address to "no-reply" and the "reply-to"-address to "info". Now users see "no-reply" as from-address (wrong!), but when they answer the mail they will see the "info"-address (correct!).
Which would be a valid solution for this with PHPMailer?

**Comment by Synchro** [comment]
This isn't specific to PHPMailer, but all solutions will amount to the same thing: don't forge a from address you don't have permission to send from. Fix your SPF record and it will work. Reply-to is not subject to SPF, so it's safe to use that.
