### ISSUE TITLE
Two e-mails received with only one TO

### ISSUE THREAD

**Issue by lor-vader** [PHPMailer/PHPMailer#404]
Hi,

I'm using the latest version of PHPMailer and I'm having problems with sending mails. With this code:
```php
$mailUser = new PHPMailer(true);
$mailUser->IsSMTP();

$mailUser->CharSet = 'UTF-8';
$mailUser->SetLanguage("es","/lib/phpmailer/language");

$mailUser->Host = "XXXXX"; 
$mailUser->SMTPAuth = true;
$mailUser->Username = "XXXXXX";
$mailUser->Password = "XXXXXX";

$mailUser->SetFrom($fromMailUser, $fromNameUser);
$mailUser->addAddress($toMailUser, $fromNameUser);

$mailUser->Subject = $subjectMailUser;
$mailUser->MsgHTML($bodyMailUser);

// Mandamos el email
$mailUser->Send();
```
PHPMailer send two e-mails. ¿Could you help me?

Thanks in advance

**Comment by Synchro** [comment]
How are you running this code? Command line?

**Comment by lor-vader** [comment]
The code is part of a PHP File that is running in a Apache Server

Enviado desde mi iPhone

**Comment by Synchro** [comment]
I'd bet that something is causing your page to load twice, perhaps a browser extension. If you view source on the two emails you receive, do they have different message IDs? If so, that's the problem. You can confirm this more visibly by doing something like appending a random value to your subject line so that the messages look different:

```php
$mail->Subject = $subjectMailUser . rand();
```

**Comment by lor-vader** [comment]
Thank you for your help Marcus.

I will try your solution later at home. 

Enviado desde mi iPhone

**Comment by lor-vader** [comment]
Hi again Marcus,

I tried your idea and, you're right. The page load twice due to a bad configuration in .htaccess file. I solved the problem and now all works fine.

Thank you for your advice and your time.

Regards
