### ISSUE TITLE
unable to connect amazon server SMTP and send email

### ISSUE THREAD

**Issue by nishant-befree** [PHPMailer/PHPMailer#407]
Hello,
is it possible to send email using amazon server SMTP or we must use amazon SeS ?

on of my client using amazon server however we can not send email using PHPMailer. it gives error unable to connect.

i checked online SMTP testing tool. it gives me error Certificate is not installed on server..

please advice.

Nishant

**Comment by Synchro** [comment]
I don't know what limitations Amazon imposes on email, but it sounds like your mail server is misconfigured.
