### ISSUE TITLE
Lots of errors but email still sends

### ISSUE THREAD

**Issue by Rewt0r** [PHPMailer/PHPMailer#408]
Just wondering why this is being entered hundreds of times into the error_log even though the email actually sends?

PHP Warning:  error_log(): TCP/IP option not available! in phpmailer/class.smtp.php on line 191

**Comment by Synchro** [comment]
This is nothing to do with PHPMailer. Your `error_log` php.ini directive is pointing somewhere invalid or forbidden by safe_mode. It's perfectly legitimate for errors to be logged while email still sends.

You're also using an old version of PHPMailer, so update it.

**Comment by Rewt0r** [comment]
I'm using version 5.2.9? That's the latest release.

**Comment by Synchro** [comment]
Sorry, yes - I'm too used to working with unreleased code!

Still, your error_log directive looks like it's got a problem. There are some changes in the master branch that may have some effect on this, but check your ini settings first.

**Comment by Rewt0r** [comment]
Yeah sorry for not picking that up before posting... Also I'll try changing to master and see if that stops the tcp/ip error
