### ISSUE TITLE
SMTP error - MS Exchange

### ISSUE THREAD

**Issue by frankstepanski** [PHPMailer/PHPMailer#412]
Hi

Trying to  send a test email via client's MS Exhange account and get the following error message:

```
SMTP ERROR: EHLO command failed: 
Called MAIL FROM without being connected Message could not be sent.Mailer Error: The following From address failed: isigned@constitutioncenter.org : 
```
Does that mean the SMPT address is wrong and/or password is wrong?

thanks.

```php
<?php
require 'lib/PHPMailer-master/PHPMailerAutoload.php';
define('GUSER', 'email'); 
define('GPWD', 'password'); 
$mail = new PHPMailer();  
$mail->IsSMTP(); 
$mail->Host = 'Mail2.constitutioncenter.org';
$mail->Port = 25; 
$mail->Username = GUSER;  
$mail->Password = GPWD;           
$mail->Subject = testing';
$mail->Body = 'body testing...';
$mail->IsHTML(true); 
$mail->SetFrom('email', 'name');
$mail->AddAddress('test@gmail.com', 'test');
if(!$mail->send()) {
   
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
    
   } else {
    echo 'Message has been sent';
   }
	?>
```

**Comment by frankstepanski** [comment]
Would the SMTP host name be the same as URL that I log into? Sorry, never did this before.

I can login the exhange email with the username and password

https://mail2.constitutioncenter.org
username: isigned
password: same as used in script.

**Comment by frankstepanski** [comment]
Now if I remove the $mail->IsSMTP(); 

The mail gets sent, but test emails do not get to gmail.com (not even junk folder), only hotmail and yahoo? strange?

**Comment by Synchro** [comment]
If you don't call `isSMTP`, it will send using PHP's built-in `mail()` function, which will send via a local mail server if you have one. This may mean you fail things like SPF checks - your local mail server log will tell you why it failed.

It's pretty unusual to allow unencrypted authentication on port 25 - I would expect you to be using `SMTPSecure = 'tls'` and `Port = 587` on any modern mail server.

**Comment by frankstepanski** [comment]
So you think the SMTP host is not correct? I am just using MAMP as my test mail server.

**Comment by frankstepanski** [comment]
I did have the client add my IP address to their SPF record. Any way  I can check if they added correctly?

**Comment by Synchro** [comment]
No, it's just that if you send using mail(), it will have the source IP of your MAMP install, rather than the SMTP host you were using when sending via SMTP. You can check SPF configs using [Scott Kitterman's test page](http://www.kitterman.com/spf/validate.html), or any other tool that does DNS lookups (like `dig`).

**Comment by frankstepanski** [comment]
Ah...ok, Sorry was confused.

So adding IP of device to SPF record is only needed if using Mail() NOT SMTP, got it.

I'd rather do SMTP, so emails will get sent successfully.

So for SMTP, and the error I got, do you think their SMTP info they gave me was incorrect? They have to be using SMTP since they can access Outlook online right?

**Comment by Synchro** [comment]
I don't know that it's wrong, but it's a bit unusual. Try doing this:

```php
$mail->SMTPAuth = true;
$mail->SMTPSecure = 'tls';
$mail->Port = 587;
$mail->SMTPDebug = 3;
```

Hopefully that will work, but you'll get lots more feedback either way.

I just released a new version of PHPMailer today - it has improved SMTP error reporting, so please give that a go.

**Comment by Synchro** [comment]
I just checked that server myself - as you say, it's not responding at all on ports 587 or 465, and on 25 it's just saying service unavailable. I'd say this is either a service-level firewall (e.g. it only allows connections from certain places), or the mail server is having trouble. Eiteher way, there's nothing you can do about it from PHPMailer. You probably need to talk to the admin.

**Comment by frankstepanski** [comment]
ok, thanks do much!!! I will contact them and let them know.
