### ISSUE TITLE
validateAddress fails to validate email ending in a dot before the @

### ISSUE THREAD

**Issue by rossnick** [PHPMailer/PHPMailer#413]
validateAddress fails to validate email ending in a dot before the @. For exemple, email.@gmail.com is valid and will be delivered to the email@gmail.com account (gmail strips out any dots in the username).

**Comment by w3d** [comment]
Although that is not strictly a valid email address. [RFC3696](https://tools.ietf.org/html/rfc3696#page-5) states that a dot "...may not be used to start or end the local part, nor may two or more consecutive [dots] appear."

**Comment by Synchro** [comment]
As @w3d said, it's not valid, and that behaviour is specific to gmail - it will break elsewhere, so it's not worth allowing. If you know it's a gmail address, you can always strip the dots yourself, but I'm not about to start adding per-domain filters...

**Comment by rossnick** [comment]
Thanks, we'll do that...
