### ISSUE TITLE
Allow base64 encoding

### ISSUE THREAD

**Issue by Rah1x** [PHPMailer/PHPMailer#414]
Hi there,

Basically, your code didnt allow me to use base64 encoding. So I had added like 4 lines in class.phpmailer.php:

```
public function createBody()
{
    .
    .
    $bodyBase64 = @($this->Encoding=='base64');
    .
    .
    .
    if($bodyBase64){
    $bodyEncoding = 'base64';
    $altBodyEncoding = 'quoted-printable';
    }
    .
    .
    .
}
```
////////////////////////////////////////////////
[USAGE]
```
$mail->isHTML(true);
$mail->CharSet = 'utf-8';
$mail->Encoding = 'base64';
$mail->addCustomHeader('Content-Transfer-Encoding', 'base64');
```

////////////////////////////////////////////////
let me know if you need me to commit it in a new branch, or you are just fine with it (as its just few lines)..

**Comment by Synchro** [comment]
I don't know what you mean. It does base64 encoding perfectly well (see the unit tests), and already sets the CTE header correctly.

**Comment by Rah1x** [comment]
Hi, thanks for the reply..

Ok I am looking at the tests and I see your function `public function testBase64()`. But if you put a large html body it becomes `quoted-printable` instead (i think because of `hasLineLongerThanMax`).

I suppose thats why it was not working for me...

**Comment by Synchro** [comment]
Ah, ok, I can see how that can happen. It should skip the length check if the encoding is base64.

**Comment by Rah1x** [comment]
yea exactly..  so instead of length check, I just forced it to be base64 and added a custom header for CTE. But if you are going to fix it altogether, there wont be any need for customer header.

**Comment by Synchro** [comment]
Using base64 for HTML bodies is generally a bad idea as it is inefficient and makes it look spammy.
