### ISSUE TITLE
Can i include it in HTML theme in themeforest

### ISSUE THREAD

**Issue by hamdan-mahran** [PHPMailer/PHPMailer#417]
Hi,

Thanks fro this awesome plugin :)

i have question about including PHPMailer in HTML theme in themeforest. Do I have the right to do so ?

Thanks!

**Comment by Synchro** [comment]
Yes - the LGPL license allows that, though if you distribute changes to the library itself, you need to do so under the same terms. I would advise you not to include the library directly, but use composer to install it.

**Comment by hamdan-mahran** [comment]
You is Awesome @Synchro 

Thanks very much!
