### ISSUE TITLE
How do I get this to work with MediaWiki?

### ISSUE THREAD

**Issue by KamranMackey** [PHPMailer/PHPMailer#419]
I was wondering how I can get MediaWiki to work with PHPMailer instead of PHP's mail() function, because I'd like to use the Mailgun service for MediaWiki, but because it only supports the mail() function, I can't do it, since it only supports SMTP domain name and port. So is there a way I can somehow configure MediaWiki to work with this library?

**Comment by KamranMackey** [comment]
Oh wait, nevermind. Figured it out.

**Comment by ooxi** [comment]
Would you consider to share your knowledge with us? :)
