### ISSUE TITLE
Add watch content-type for another version of email

### ISSUE THREAD

**Issue by cjt3007** [PHPMailer/PHPMailer#422]
So, the AppleWatch has a custom Content-type that can be used to make a separate email version for the smaller display that has some HTML support (sans images).

the content-type header is: Content-Type “text/watch-html”

Not sure how I would add this myself to PHPMailer, so maybe it could be an addition to the mail class, like "$mail->AltBody" it could be "$mail->WatchBody"

**Comment by Synchro** [comment]
Thanks, that's good to know. Unfortunately it's really in the same boat as iCal support (#175); doing it with the current code base is just going to make PHPMailer even more of a rats nest. Supporting arbitrary MIME structures would allow things like this easily, but that will need to wait for a rewrite.

**Comment by Synchro** [comment]
For reference: https://litmus.com/blog/how-to-send-hidden-version-email-apple-watch
