### ISSUE TITLE
PCRE problem

### ISSUE THREAD

**Issue by bizley-code** [PHPMailer/PHPMailer#424]
Hi
I've got this error with PHPMailer 5.2.10
```Compilation failed: internal error: previously-checked referenced subpattern not found```

It looks like it is about PCRE 8 preg_match pattern (lines 943 - 954). Information about that error can be found online and people suggest upgrading PCRE library to newest version but in my case (PHP 5.5.25, PCRE 8.36) it is quite up-to-date (I know 8.37 is newest).
Anyway, quick solution in my case is to set $patternselect in validateAddress() from 'auto' to something else (like 'php') but I can not control it with class property and have to modify class file which is bad.
Is it possible to add property for $patternselect? Or maybe there is other soluton for this?

**Comment by Synchro** [comment]
That is a bit odd. I've not seen that before, but it should be easy to wrok around. You don't have to modify the class, just subclass and implement your own validateAddress method - which may simply change the default param value and call the parent implementation.

**Comment by bizley-code** [comment]
It's true, I can do it that way. But since this is important part of the class I was hoping for easier solution like the one with class property for $patternselect (very small change required). Anyway - thanks and keep up the good work!

**Comment by Synchro** [comment]
I'd say that's not a good use of a property (plus we have far too many already). You're unlikely to ever want it to be different between instances in any given app, it penalises the vast majority who will never need it, it prevents validateAddress being called statically, and subclassing is really appropriate for corner cases - I do exactly this myself where I want it to default to the HTML5 validation.
