### ISSUE TITLE
Multiple emails sent

### ISSUE THREAD

**Issue by varmad** [PHPMailer/PHPMailer#427]
I am using this script for my email campaigns, users are complaining that they are receiving duplicate mails at the same point of time. I am running this script from the command line.

This is the code am using, please suggest me if there are any changes.

```php
$mail = new PHPMailer;

$mail->isSMTP();                                      // Set mailer to use SMTP
$mail->Host = $config->smtp->host;  // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = $config->smtp->username;                 // SMTP username
$mail->Password = $config->smtp->password;                           // SMTP password
$mail->SMTPSecure = 'tls';
$mail->Port = 587;

$mail->isHTML(false);

$replay_to = $config->smtp->replay_to;
$replay_name = $config->smtp->replay_name;

$mail->From = $replay_to;
$mail->FromName = $replay_name;

$total_emails = count($recipients);

if($total_emails > 0) {

  $i=0; $k=1; $interval = ($total_emails > 5000)?150:300; $nextInterval = 500;
  foreach($recipients AS $recipient) {
    //sleep time for every 500 emails
    if($i == $nextInterval ){
      sleep($interval);
      $nextInterval += 500; 
    }   

    $trac_url = ''; $unsub_url="";
    $to_email = $recipient['Email'];
    $to_name  = $recipient['Name'];

    //subject rotation for each mail
    $subject_index = ($i%count($subjects));

    //Getting subject
    $subject = $to_name.', '.$subjects[$subject_index];

    //Tracking url
    $trac_url = $tracking_url.'?user='.urlencode($to_email);
    
    //Unsubscribe url
    $unsub_url = $unsubscribe_url.'?user='.urlencode($to_email);

    //Place holder which are replaced in html template
    $place_holders = array(
      '{{user_name}}' => $to_name,
      "{{unsub_link}}"   => $unsub_url,
      "{{tracking_url}}"   => $trac_url,
      "{{from_name}}"   => $replay_name,
      "{{from_email}}"   => $replay_to,
      "{{city}}" => $campaign->city,
      "{{venue}}" => $campaign->venue,
    );
   
    //Get text template
    $message_txt = file_get_contents($campaign->product.".txt");
    $message_txt = $message_txt;

    //Replace place holders
    $body_txt = strtr($message_txt, $place_holders);

    $mail->addAddress($to_email, $to_name);     // Add a recipient
    $mail->addReplyTo($replay_to, $replay_name);
    $mail->Subject = $subject;
    $mail->Body    = $body_txt;

    if(!$mail->send()){
        echo "Message could not be sent to:".$to_email." \n";
        echo "Mailer Error: " . $mail->ErrorInfo." \n";
    } else {
        echo "Message has been sent to: ".$to_email." \n";
        $k++;
    }
    
    $mail->clearAddresses();

    $i++;
  }

}
```

Thanks,
Varma

**Comment by Synchro** [comment]
It's most likely that the script is simply being run twice. You will be able to tell if the duplicate messages have different message ID headers. Try enabling debug output (`$mail->SMTPDebug = 2`), writing something to a log file, or append a random value to the end of the subject line - if they receive two messages with the same subject, they are true duplicates; if they receive different subjects, your script is being run twice.

You should probably not adding `addReplyTo` inside the loop if they are the same each time, and reply-to addresses are not cleared by `clearAddresses`; you should call `clearReplyTos` as well if you're going to add them every time.

**Comment by varmad** [comment]
Thanks for the replay @Synchro, this not happening for all users, we send 1k mails only two or three users are complaining.
This is the typical scenario, I don't even know how to debug this.

**Comment by Synchro** [comment]
For that kind of problem you just need to do lots of logging, then you will be able to go back and see what happened when you get another report.

**Comment by varmad** [comment]
Ok,

**Comment by varmad** [comment]
Ok, I will do that.

**Comment by aeyachts99** [comment]
I'm also getting this issue even when sending to just one recipient. I've added a random number to the subject field and both received messages show the same random number so as mentioned earlier in this thread they are true duplicates.

**Comment by Synchro** [comment]
Like I said, log everything. Run it in a debugger, record traces. All will be revealed.

**Comment by glouk7** [comment]
I have a smilar issue, and i use the latest PHPmailer version.

**Comment by Synchro** [comment]
So follow the advice in this ticket.

**Comment by glouk7** [comment]
I've done a lot of checks and logging out apache logs...

Let's say that the code is at thanks.php
It seems that the thanks.php file that runs the email code, run sometimes more than 1 time without any specific reason after few seconds difference (around 2-8 seconds).

Of course the code of that php file, doesn't have any loop in order to do that, and also the strange thing that this this is not happening every time, but sometimes.

The result of it, is the same receiver to receive more than 2-3 copies of the same email...
I believe that the issue is coming out from the PHPMailer script...i've "updated" to the latest version, but the problem remains.

**Comment by Synchro** [comment]
It's very common for browser extensions to repeat requests. PHPMailer just doesn't have a mechanism for sending multiple messages without being asked to. Did you try the random subject test described above? That will prove whether it's multiple requests. You will also see it in your web server logs.

**Comment by HemalBhalodia** [comment]
I am having the same issues. PHPMailer sends sometime two or more emails. But it's done randomly as we are sending 1000+ emails daily. So it's sending after we start to send more emails. It's working fine when we send 200-300 emails a day but if we start to send more it's sending 2-3 emails to some customers.

**Comment by Synchro** [comment]
So do what it says above. Log details.

**Comment by HemalBhalodia** [comment]
Thanks Synchro for quick followup. $mail->clearAddresses fixed my issue. Thank you again.

**Comment by shishkin17** [comment]
I thought I had the same issue until I realised that if you want to send 2 (or more) separate emails to different addresses you need to clear addresses and attachments (and everything that has clear functions). The problem that it is not obvious. I found that you have those clear functions only in that issue after an hour of trying to figure out why is that happening. I am not sure that I have to read all the documentation and all the functions available just to do the basic action - send email.
You should write about that on the main page and in the example!

**Comment by Synchro** [comment]
It is mentioned in the examples, in exactly the one you'd expect - [the mailing list](
https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.php). There's also a clue in the name it's **addAddress** not **setAddress**, implying it's cumulative.
