### ISSUE TITLE
PCRE error: previously-checked referenced subpattern not found

### ISSUE THREAD

**Issue by 7henry767** [PHPMailer/PHPMailer#429]
( ! ) Warning: preg_match(): Compilation failed: internal error: previously-checked referenced subpattern not found at offset 728 in /home/web/vendor/phpmailer/phpmailer/class.phpmailer.php on line 954
Call Stack
# Time    Memory  Function    Location

9   0.0461  516144  PHPMailer->addAddress( )    .../Mail.php:77
10  0.0461  516608  PHPMailer->addAnAddress( )  .../class.phpmailer.php:772
11  0.0463  516928  PHPMailer::validateAddress( )   .../class.phpmailer.php:832
12  0.0463  517072  preg_match ( )

used version:
 phpmailer/phpmailer               v5.2.10

Additional information:
Server API  Apache 2.0 Handler
PHP API 20121113
PHP Extension   20121212
Zend Extension  220121212
Zend Extension Build    API220121212,NTS
PHP Extension Build API20121212,NTS
Debug Build no
IPv6 Support    enabled
DTrace Support  enabled

**Comment by Synchro** [comment]
Yep, this is a bug in PHP. Currently the only solution is to downgrade PHP to 5.5.24/5.6.8. SwiftMailer and Typo3 have run into the same problem. There are reports that this only affects the apache SAPIs because they messed up the PHP release, so you might find that switching to PHP-FPM works around the problem, and it's a better way of running PHP anyway.

**Comment by bizley-code** [comment]
Actually the solution given in #424 is enough to work around this issue.

**Comment by Synchro** [comment]
To override the default behaviour to avoid this bug, subclass PHPMailer like this:

```php
class myMailer extends PHPMailer
{
    public static function validateAddress($address, $patternselect = 'auto')
    {
        return parent::validateAddress($address, 'php');
    }
}
```
Then use that subclass in place of plain PHPMailer.

**Comment by Synchro** [comment]
Can anyone seeing this problem please try it with PHP 5.6.10 and 5.5.26 to see if the new build and PCRE update fixes it.
