### ISSUE TITLE
Issue when used twice in a row.

### ISSUE THREAD

**Issue by neotropic2023** [PHPMailer/PHPMailer#433]
Ok,so I have a function, like your example pretty much in my application. On a few parts I send out two different emails. One to us and one to the customer. Slightly different. 

One is directly to the send email function, one to us goes to another function, then prepares and goes to the send email function.

I also call:  require (_PATH_CLASSES.'phpmailer/PHPMailerAutoload.php'); within my function. 

So when my script runs, it will send the first email out, but then just fails on the second. Is it because of the require I have there? I tested it to return some output after the require and notihng on the second, but first output is displayed. 

This thing/method is new to me (like it,but new). I also do not want to just pre-load it with the entire site when not needed. I could (but rather not) move the require to every single instance I am about to send an email.

That normal?

**Comment by ooxi** [comment]
Sorry I don't quite get your question. Are you asking about the semantics of [require](php.net/manual/en/function.require.php)?

**Comment by Synchro** [comment]
You seem to be talking about a class loading strategy - using `require` unconditionally inside a function which will get called more than once wil indeed fail, and is to be expected. The simple solution is to use `require_once`, but these days, using `require` at all is almost an anti-pattern. If you're using [composer](https://getcomposer.org) (and you should) with autoloaders, you effectively never need to require anything manually ever again - any time a class is needed, it will be loaded automatically.

**Comment by neotropic2023** [comment]
Thank you, that was very helpful!
