### ISSUE TITLE
SMTP connect failed()

### ISSUE THREAD

**Issue by viru24** [PHPMailer/PHPMailer#435]
Hello, 
i am using phpmailer for my website, implemented everything properly but when i am testing on localhost it gives me an smtp connect failed error. 
i went through various topics and tried to make few changes but can't seem to find the solution.
Can you just help me out what is the issue, i also went through the url you provided but was not able to find a solution.
Hope i'll finally solve it here.

To be more clear, i am getting this error:
SSL loaded bool(false) not sent
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
Do you have a local mail server?

**Comment by viru24** [comment]
yes i am currently testing on localhost(xampp) .

**Comment by Synchro** [comment]
OK, so what output do you get from all the tests in the troubleshooting guide?

**Comment by viru24** [comment]
smtp connect failed(). the username and pass cannot connect i think so. It is returning bool(false) instead of bool(true). I watched alex videos on youtube copied the same code from git , then to it gives smtp connect failed().
Need your help

**Comment by Synchro** [comment]
What about all the other tests in the guide? DNS, ping, telnet etc?
Set `SMTPDebug = 3` to get additional connection-level debug output.

**Comment by Synchro** [comment]
Also, what alex videos? Which code?

**Comment by viru24** [comment]
should i send you the errors which i am getting?

**Comment by Synchro** [comment]
Well you could try reading what they say and understanding them yourself, but otherwise, sure.

**Comment by viru24** [comment]
SSL loaded 2015-06-11 07:21:33 Connection: opening to ssl://smtp.gmail.com:465, timeout=300, options=array ( ) 2015-06-11 07:21:33 Connection: opened 2015-06-11 07:21:33 SERVER -> CLIENT: 220 mx.google.com ESMTP cd10sm10572656pac.7 - gsmtp 2015-06-11 07:21:33 CLIENT -> SERVER: EHLO localhost 2015-06-11 07:21:34 SERVER -> CLIENT: 250-mx.google.com at your service, [115.97.25.39] 250-SIZE 35882577 250-8BITMIME 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN XOAUTH 250-ENHANCEDSTATUSCODES 250-PIPELINING 250-CHUNKING 250 SMTPUTF8 2015-06-11 07:21:34 CLIENT -> SERVER: AUTH LOGIN 2015-06-11 07:21:34 SERVER -> CLIENT: 334 VXNlcm5hbWU6 2015-06-11 07:21:34 CLIENT -> SERVER: dmlyYWoucHJrQGdtYWlsLmNvbQ== 2015-06-11 07:21:34 SERVER -> CLIENT: 334 UGFzc3dvcmQ6 2015-06-11 07:21:34 CLIENT -> SERVER: cGFyaWtoOTM= 2015-06-11 07:21:35 SERVER -> CLIENT: 534-5.7.14 Please log in via your web browser and 534-5.7.14 then try again. 534-5.7.14 Learn more at 534 5.7.14 https://support.google.com/mail/answer/78754 cd10sm10572656pac.7 - gsmtp 2015-06-11 07:21:35 SMTP ERROR: Password command failed: 534-5.7.14 Please log in via your web browser and 534-5.7.14 then try again. 534-5.7.14 Learn more at 534 5.7.14 https://support.google.com/mail/answer/78754 cd10sm10572656pac.7 - gsmtp 2015-06-11 07:21:35 SMTP Error: Could not authenticate. 2015-06-11 07:21:35 CLIENT -> SERVER: QUIT 2015-06-11 07:21:35 SERVER -> CLIENT: 221 2.0.0 closing connection cd10sm10572656pac.7 - gsmtp 2015-06-11 07:21:35 Connection: closed 2015-06-11 07:21:35 SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting bool(false) 2015-06-11 07:21:35 Connection: opening to ssl://smtp.gmail.com:465, timeout=300, options=array ( ) 2015-06-11 07:21:36 Connection: opened 2015-06-11 07:21:36 SERVER -> CLIENT: 220 mx.google.com ESMTP ku10sm10569182pab.3 - gsmtp 2015-06-11 07:21:36 CLIENT -> SERVER: EHLO localhost 2015-06-11 07:21:36 SERVER -> CLIENT: 250-mx.google.com at your service, [115.97.25.39] 250-SIZE 35882577 250-8BITMIME 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN XOAUTH 250-ENHANCEDSTATUSCODES 250-PIPELINING 250-CHUNKING 250 SMTPUTF8 2015-06-11 07:21:36 CLIENT -> SERVER: AUTH LOGIN 2015-06-11 07:21:36 SERVER -> CLIENT: 334 VXNlcm5hbWU6 2015-06-11 07:21:36 CLIENT -> SERVER: dmlyYWoucHJrQGdtYWlsLmNvbQ== 2015-06-11 07:21:37 SERVER -> CLIENT: 334 UGFzc3dvcmQ6 2015-06-11 07:21:37 CLIENT -> SERVER: cGFyaWtoOTM= 2015-06-11 07:21:37 SERVER -> CLIENT: 534-5.7.14 Please log in via your web browser and 534-5.7.14 then try again. 534-5.7.14 Learn more at 534 5.7.14 https://support.google.com/mail/answer/78754 ku10sm10569182pab.3 - gsmtp 2015-06-11 07:21:37 SMTP ERROR: Password command failed: 534-5.7.14 Please log in via your web browser and 534-5.7.14 then try again. 534-5.7.14 Learn more at 534 5.7.14 https://support.google.com/mail/answer/78754 ku10sm10569182pab.3 - gsmtp 2015-06-11 07:21:37 SMTP Error: Could not authenticate. 2015-06-11 07:21:37 CLIENT -> SERVER: QUIT 2015-06-11 07:21:38 SERVER -> CLIENT: 221 2.0.0 closing connection ku10sm10569182pab.3 - gsmtp 2015-06-11 07:21:38 Connection: closed 2015-06-11 07:21:38 SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting 

This is the error which i am getting.

**Comment by viru24** [comment]
<?php


require 'phpmailer/PHPMailer-master/PHPMailerAutoload.php';
require 'phpmailer/PHPMailer-master/class.phpmailer.php';
$mail             = new PHPMailer();

$body             = "message";
$mail->SMTPDebug = 3;
$mail->IsSMTP(); // telling the class to use SMTP
$mail->Host       = 'smtp.gmail.com'; // SMTP server
$mail->SMTPAuth   = true;  
$mail->isHTML(true);                // enable SMTP authentication
$mail->Host       = 'smtp.gmail.com'; // sets the SMTP server
$mail->SMTPSecure="ssl";
$mail->Port       = 465;                    // set the SMTP port for the GMAIL server
$mail->Username   = "my email id"; // SMTP account username
$mail->Password   = "my pass";        // SMTP account password

$mail->SetFrom('name@yourdomain.com', 'First Last');
$mail->AddReplyTo("name@yourdomain.com","First Last");
$mail->Subject    = "PHPMailer Test Subject via smtp, basic with authentication";
$mail->AltBody    = "To view the message, please use an HTML compatible email viewer!"; // optional, comment out and test
$mail->MsgHTML($body);

$mail->AddAddress("whoto@otherdomain.com", "John Doe");
var_dump($mail->send());
if(!$mail->Send()) {
  echo "Mailer Error: " . $mail->ErrorInfo;
} else {
  echo "Message sent!";
}

?>

**Comment by Synchro** [comment]
Seriously. This *exact* error is covered in the troubleshooting guide, and the error message even includes a link to tell you how to deal with it! You're also using an old gmail example, when the very first thing it says in the troubleshooting guide is to update both PHPMailer and your examples. Is it really so hard to read this stuff??

**Comment by Ricki100** [comment]
I think you need to answer people amicably.You are the owner so its easier for you to understand.There is no need to treat viru24 like an idiot.
