### ISSUE TITLE
Mailer works on XAMP localhost but not on Webserver

### ISSUE THREAD

**Issue by meivin123** [PHPMailer/PHPMailer#436]
Hello,
today some serious issues appeared on my mailing script.
I want to send to mails in one script.
It works on my XAMPP localhost but not on my Webserver.
SMTP Debug outputs the following code:
```
 2015-06-11 13:34:08	SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution (0)
2015-06-11 13:34:08	SMTP connect() failed.
2015-06-11 13:34:08	SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution (0)
2015-06-11 13:34:08	SMTP connect() failed.
```

My Script looks the following
```php
$mail = new PHPMailer();
$mail->isSMTP();                                      
$mail->Host = 'smtp.strato.de';  
$mail->SMTPAuth = true;                               
$mail->Username = 'sendermail@mail.de';
$mail->Password = 'secretpass';
$mail->SMTPSecure = 'tls';
$mail->Port = 587;
$mail->CharSet = "UTF-8";
$mail->From = 'From';
$mail->FromName = 'From Name';
$mail->Subject = "Subject";
$mail->isHTML();
$mail->addAddress("receiver@mail.de");
$mail->Body = "<p> SOME HTML</p>
$mail-AltBody = "Alt Body";
$mail->send();
```

The configuration of the phpmailer object is the same in both mails only the messages, subjects etc. are differ.

Can anyone help?

**Comment by Synchro** [comment]
DNS is broken on your web server, so it's failing to find the IP associated with your mail server. This is covered in [the troubeshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting).

**Comment by AmaliDeveloper** [comment]
You can get the solution for send mail using phpmailer Here [Link](https://youtu.be/Edx7pPcPfs8)

**Comment by Neel97** [comment]
Not working when the host the script in gearhost server but works in localhost enivronment. 
Can anyone help what to do?

**Comment by Synchro** [comment]
@Neel97 yes, read [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting), search on StackOverflow *before* posting. Your host is probably blocking outbound SMTP.
