### ISSUE TITLE
PHPMailer not sending my email

### ISSUE THREAD

**Issue by clinton2111** [PHPMailer/PHPMailer#437]
Hi i've been trying to send emails using PHPMailer without the need of an SMTP server. I read that PHPMailer can send emails without the need of a gmail or anyother smtp server.Ive looked at various tutorials online but most of them use an smtp and the ones which don't use a smpt doesn't seem to work for me. I do get a ;Success' response but i dont receive my mail in my inbox
 
    <?php
    require_once '../vendor/phpmailer/phpmailer/PHPMailerAutoload.php';
    $json = file_get_contents('php://input');
    $data = json_decode($json);
    $response = array();
    $mail = new PHPMailer;
    //From email address and name
    $mail->From = $data->address;
    $mail->FromName = $data->name;
    //To address and name
    $mail->addAddress("example92@gmail.com", "Mr Example");
    //Address to which recipient will reply
    $mail->addReplyTo($data->address, $data->name);
    //Send HTML or Plain Text email
    $mail->isHTML(false);
    $mail->Subject = "Sent from example.in";
    $mail->Body = htmlentities($data->msg);
    $mail->AltBody = htmlentities($data->msg);
    if (!$mail->send()) {
        $response['status'] = 'Error';
        $response['message'] = $mail->ErrorInfo;
    } else {
        $response['status'] = 'Success';
        $response['message'] = 'Message Sent';
    }
    echo json_encode($response);

**Comment by Synchro** [comment]
With this code it's submitting to your local mail server, which may not be configured, so it's accepting the message but not sending it on. Look in your mail server log and you should see something about it.

**Comment by cyberrock** [comment]
I had some issues with another server last week, and had to downgrade and upgrade PHP a few times. I had just noticed today that my PHPMailer script was no longer working.

there are no errors coming up though there is no HTML being displayed under $mail = new PHPMailer;.. previously it has been working fine..

**Comment by clinton2111** [comment]
I had to change the code a little bit to make it work.. also ended up using Sendgrid's smtp service to send my emails.

**Comment by AmaliDeveloper** [comment]
You can get the solution for send mail using phpmailer Here [Link](https://youtu.be/Edx7pPcPfs8)
