### ISSUE TITLE
Display unicode font

### ISSUE THREAD

**Issue by johnsmeeth** [PHPMailer/PHPMailer#440]
Dear sir.
I just try phpmailer with smtp type. but on receive email, it's content cannot read because font error (utf-8)

**Comment by Synchro** [comment]
Please post your code and an example of a mis-encoded message.

**Comment by johnsmeeth** [comment]
<?php
require 'phpmailer/PHPMailerAutoload.php';
$mail = new PHPMailer;

//$mail->SMTPDebug = 3;                               // Enable verbose debug output

$mail->isSMTP();                                      // Set mailer to use SMTP
$mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'johnsmeeth0210@gmail.com';             // SMTP username
$mail->Password = 'secrect';                           // SMTP password
$mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 587;                                    // TCP port to connect to

$mail->From = 'johnsmeeth0210@gmail.com';
$mail->FromName = 'Mailer';
$mail->addAddress('cctv@congngheanninh.com', 'John Smeeth');     // Add a recipient
//$mail->addAddress('ellen@example.com');               // Name is optional
$mail->addReplyTo('johnsmeeth0210@gmail.com', 'Information');
// $mail->addCC('thanhnv0210@gmail.com');
//$mail->addBCC('bcc@example.com');

//$mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
//$mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name
$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'Thông tin ứng viên';
// $mail->Body = 'Mail body';
$mail->Body    = '<!doctype html><head><meta charset="utf-8"></head><body><ul>'
					. '<li>Họ đệm: ' .  $_POST['HoDem'] . '</li>'
					. '<li>Tên: ' . $_POST['Ten'] . '</li>'
					. '<li>Ngày sinh: '. $_POST['birth_day'] . '/' . $_POST['birth_month'] . '/' . $_POST['birth_year'] . '</li>'
					. '<li>Giới tính: ' . $_POST['GioiTinh'] . '</li>'
					. '<li>Tình trạng hôn nhân: ' . $_POST['TinhTrangHonNhan'] . '</li>'
					. '<li>Trình độ học vấn: ' . $_POST['TrinhDoHocVan'] . '</li>'
					. '<li>Địa chỉ: ' . $_POST['DiaChiTT'] . '</li>'
					. '<li>Tỉnh/Thành phố: ' . $_POST['ThanhPho'] . '</li>'
					. '<li>Chiều cao: ' . $_POST['chieuCao'] . '</li>'
					. '<li>Cân nặng: ' . $_POST['canNang'] . '</li>'
					. '<li>Email: ' . $_POST['Email'] . '</li>'
					. '<li>Điện thoại: ' . $_POST['Mobile'] . '</li>'
					. '<li>Biết thông tin qua: ' . $_POST['PhuongTien'] . '</li>'
					. '<li>Yêu cầu nguyện vọng: ' . $_POST['NguyenVongDuTuyen'] . '</li>'
				. '</ul></body></html>';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

if(!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message has been sent';
    
}

Error email:
![loifont](https://cloud.githubusercontent.com/assets/5707587/8177937/c293cb28-1433-11e5-87e5-cee28c9d36bb.png)

**Comment by Synchro** [comment]
You are missing:

```php
$mail->CharSet = 'utf-8';
```

**Comment by johnsmeeth** [comment]
Many thank @Synchro . it's done.
