### ISSUE TITLE
Mailer error: You must provide at least one recipient email address

### ISSUE THREAD

**Issue by fontanil** [PHPMailer/PHPMailer#441]
Hi,
Yesterday I asked my hoster (PHPNET in France) to change PHP 5.4 to 5.5 on my server and the one of a client. You can see PHP infos there on my server: http://staging.par-robertg.fr/infos.php 
Now, on both servers we get an error, no mail were sent: "You must provide at least one recipient email address".
Creating an account, send a contact message, and on my client's website all mails for Virtuemart too. :(
On PHP 5.4 we had no problem.
Our websites are in version 3.4.1; i tested too on last staging version http://staging.par-robertg.fr 
Has someone an idea to solve?
Thanks in advance,
Robert

**Comment by Synchro** [comment]
Are you getting any errors in your web server error log? Try calling `validateAddress` on your addresses before you try sending, and check the return value.

**Comment by fontanil** [comment]
Thanks Synchro!
No error in errors log. No trace in phpmail.log on server: mail is not sent...
I tried to add "count($this->to)" and the result is "0".
I don't know how to add code to get a return value: where "to" address is kepted and tested to return empty?

**Comment by Synchro** [comment]
In your code, do this, where $email contains some email address that you are trying to send to.

```php
var_dump(PHPMailer::validateAddress($email));
```
If this returns false, then any call to `addAddress` with the same address will fail too. Try doing this to show all errors:

```php
ini_set('display_errors', true);
error_reporting(E_ALL);
```

**Comment by fontanil** [comment]
Sorry Marcus, I am not a coder, and I don't know where to add this code (var_dump). It's not "my" code but joomla's code. ;)
All addresses are correct, all emails were sent yesterday on PHP 5.4, not today on 5.5, so there is somewhere something that delete them, where Joomal! validate original address.
No errors with error reporting in index.php (you code above), debug and error reporting at development value in configuration.
And I can't test anymore, as my hoster seems to change something in PHP setting, so emails works now on my own server! not on my client server yet :))
Thanks!

**Comment by Synchro** [comment]
OK, well I can't diagnose the problem without more info, so I suggest you open a support ticket with your hosting provider, and come back here when you have more info.

**Comment by fontanil** [comment]
I will tell you what my hoster will say.
Thanks

**Comment by fontanil** [comment]
My host did not answer me yet, but I compared PHP infos and found that PHP has increased from 5.5.25-1~dotdeb+7.1 to 5.5.26-1~dotdeb+7.3 and version of PCRE library changed from 8.36 2014-09-26 to 8.30 2012-02-04

**Comment by patschi** [comment]
I had exactly this issue on one of my Wordpress installations. After updating PHP 5.6.9-1~dotdeb+7.1 to 5.6.10-1~dotdeb+7.3 this problem has gone and sending mails does work again. Seems to be a PHP related problem itself?

**Comment by Synchro** [comment]
Sounds like you are running into #429, so I'll close this issue in favour of that one. It's very odd that when updating your PHP version, they also *downgraded* your PCRE lib. I guess they may have spotted other problems with it too.
