### ISSUE TITLE
SMTP connect() failed

### ISSUE THREAD

**Issue by hamdan-mahran** [PHPMailer/PHPMailer#442]
Hello,

Thanks for this awesome plugin and for your time, but i think it will be more awesome if it's work for me :D 
I trying to use it to send mails, i make all the steps, set google mail user and password ... etc
The link is http://www.enar.ideal-theme.com/html5/ipad/mail/sendemail.php

<pre>
require 'PHPMailerAutoload.php';

$mail = new PHPMailer;

$mail->isSMTP();                                      
$mail->Host = 'smtp.gmail.com';  
$mail->SMTPAuth = true;                              
$mail->Username = 'mymail@gmail.com';                
$mail->Password = 'my-password';
$mail->SMTPSecure = 'ssl';                           
$mail->Port = 465; 
$mail->SMTPDebug = 2;

$mail->From = 'mymail@gmail.com';
$mail->FromName = 'Mailer';
  
$mail->addReplyTo('reply@gmail.com', 'Information');
$mail->addAddress('mymail@gmail.com', 'Joe User');                            

$mail->Subject = 'Here is the subject';
$mail->Body    = 'This is the HTML message body <b>in bold!</b>';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

var_dump($mail->send());
</pre>

I hope to give me your feedback about it

Thanks!

**Comment by Synchro** [comment]
Base your code on [the gmail example provided](https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail.phps) and read [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting), exactly as the error message tells you. There are also over 800 questions on Stackoverflow on this exact subject.

**Comment by hamdan-mahran** [comment]
Thanks very much for your reply :) 
But i see this article is so complicated for me, and i don't understand, i just want to send a message, and i make all steps ( user - pass - etc )

Thanks!

**Comment by Synchro** [comment]
What that error means is that your server cannot connect to its local network, so everything, including email, is not going to work. Fix your server and PHPMailer can work. You might want to open a support ticket with your hosting provider.

**Comment by hamdan-mahran** [comment]
Wow, you is awesome,
I want to thank you a lot for your support, from my heart i don't see any man like you, you is awesome, i hope you like my last theme on themeforest http://themeforest.net/item/enar-responsive-multipurpose-html5-template/11107340

All the best

**Comment by Synchro** [comment]
That's a pretty impressive theme, nice work!

**Comment by hamdan-mahran** [comment]
Thanks very much @Synchro , it's my pleasure to like it :)

**Comment by evanb2** [comment]
I was having this same problem. I tried literally everything, checked everything on my server settings but still nothing.

In the end I removed this one line:    $mail->isSMTP();

That fixed my SMTP connection error. Don't know why, but it works. Any ideas @Synchro ?

**Comment by Synchro** [comment]
That's not a fix. You just turned off SMTP. Read the troubleshooting guide.
