### ISSUE TITLE
PHP Mailer  - Yahoo mail settings

### ISSUE THREAD

**Issue by bsoujanya** [PHPMailer/PHPMailer#444]
Does PHP Mailer work for Yahoo mail settings? Because it says mail sent, but it fails to deliver the mail to yahoo mail box.

**Comment by Synchro** [comment]
Sure, Yahoo is mostly normal SMTP. Check your spam folder, and set `$mail->SMTPDebug = 2;` in order to see what's happening during delivery.

**Comment by bsoujanya** [comment]
Does PHP Mailer need the from address to be yahoo mail ID only, if the username in mail settings is yahoo mail id?

Because mails are working if we use the following code chunk only. Otherwise it is throwing SMTP connect failed / From email ID not verified error.
$yahoo_smtp = strpos($config['username'], 'yahoo');
		if($yahoo_smtp !== false) {
			$mail->setFrom('username','Do not Reply');
		} else {
			$mail->setFrom(EMAIL,'Do not Reply');
		}

**Comment by Synchro** [comment]
This isn't just a PHPMailer thing - if you set the From address to be a user's address, but you're not sending through the user's system, it will either get rejected outright or flagged as a forgery by SPF checks. Yahoo is particularly hot on that. Use your own address as the From address, add the user's address as a reply-to address. That way it's not a forgery and replies will work as you want.

**Comment by bsoujanya** [comment]
Okay...But that is not how we are using yahoo account.

User uses his yahoo settings to setup a mail server account for an application. Using the mail sever settings, notification mails are being sent through the application.

**Comment by Synchro** [comment]
So your app has authenticated access to the user's own mail server? The "From email ID not verified" error sounds like the Yahoo account needs some kind of permissions opening up or email alias defining. Gmail has some similar limits. I don't think this problem is at your end.

**Comment by bsoujanya** [comment]
Yes, gmail does have some settings to enable sending mails. Shall check for Yahoo.

Also, does PHP Mailer work for any mail server settings or are there any limitations?

**Comment by bsoujanya** [comment]
Just curious...if yahoo doesn't allow sending emails, how is PHP Mailer able to send mail with the above code chunk?

**Comment by Synchro** [comment]
It's down to Yahoo settings - I suspect that by default it won't let you set a From address that's different from your Username unless you have specifically allowed it. Gmail works the same way.
