### ISSUE TITLE
Install/setup issues for first time user

### ISSUE THREAD

**Issue by vahalia** [PHPMailer/PHPMailer#445]
Hi,

I am trying to use PHPMailer for the first time. I used Composer to do the initial setup, and now have the files PHPMailerAutoload.php, composer.json, and composer.lock in my project directory. I also manually copied the composer.phar file there. The content of my composer.json file is
{
    "require": {
        "phpmailer/phpmailer": "~5.2"
    }
}

In my project file, I added the following:

		require 'PHPMailerAutoload.php';

		$mail = new PHPMailer;
                ... // Other stuff

When I add the line $mail = newPHPMailer;, the php file hangs during execution. Removing the line allows the rest of the execution to proceed. I have not yet added any lines to do the actual mail sending.

Looks like I am missing some piece. Can someone help?

**Comment by sergeyklay** [comment]
```json
{
  "require": {
    "phpmailer/phpmailer": "~5.2"
  }
}
```

```php
<?php

namespace MyAwesomeNamespace;

use PHPMailer;

class MyAwesomeMyClass
{
    public function foo()
    {
            $mail = new PHPMailer;
            ...
    }
}
```

**Comment by Synchro** [comment]
To paraphrase @sergeyklay, if you're using composer's autoloader (which you should), you don't need to load PHPMailer's own autoloader.

**Comment by vahalia** [comment]
Thank you guys.
All I really needed to do wa sto change the require statement in my php file to require_once with the vendor/autoload.php argument as suggested above.
I did not need to do any of the namespace stuff or put the call to new inside a function or a classs. Not sure what the significance of those steps is; would be great if you could clarify.
Anyway, I am now making progress, so thanks again.
