### ISSUE TITLE
When reply to is from the same domain as per from email address, it's not working

### ISSUE THREAD

**Issue by nishitsoni** [PHPMailer/PHPMailer#452]
Hi

When I use reply to from different domain name, it's not working, please update me as soon as possible.

Thanks

**Comment by Synchro** [comment]
This will be down to your mail server or possibly your client, not PHPMailer.

**Comment by nishitsoni** [comment]
No, there is no issue on server side, do I need to do anything to enable addreplyto?

**Comment by Synchro** [comment]
No, just call the function. It would help if you show your code and what's happening instead of what you expect. Reply-to is a very simple thing - it's just a header, has no impact on SMTP.
