### ISSUE TITLE
Failed email delivery not bouncing back. Any possibility to set a bounce adresse?

### ISSUE THREAD

**Issue by ohmish** [PHPMailer/PHPMailer#453]
Hi
When I test and send to an address that doesn't exist, I never get a bounce/error email in return to the from/reply-to address
Is a bounce address a posibility with PHPmailer?

**Comment by Synchro** [comment]
You need to set the `Sender` property to the address you want bounces to go to. The receiving server will  use it to create a return-path header and ay bounces will be sent there. I also suggest you look up how to use VERP addressing for bounce handling.
