### ISSUE TITLE
Following errors pops up when calling the phpMailer

### ISSUE THREAD

**Issue by tannishk** [PHPMailer/PHPMailer#454]
Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /Applications/XAMPP/xamppfiles/htdocs/class.smtp.php on line 344
Message could not be sent.Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

I Tried calling the SMTP server of google and localhost as well same error always pops Up

**Comment by Synchro** [comment]
Did it stop you following the link to the documentation that tells you how to deal with this too?
