### ISSUE TITLE
SMTP Connect to Local Server Only.

### ISSUE THREAD

**Issue by enrichweb** [PHPMailer/PHPMailer#459]
Hello,

I am using phpmailer which is great tool to send email. But since when We noticed a strange issue in code given below which is working on one server and not on other server. 
For reference you can visit 
http://enrich.co.in/smtpmail/smtpmail.php which connecting to mandrillapp SMTP Server  
http://lotuscentre.ac.in/smtpmail/smtpmail.php which connecting to local Server instead of mandrillapp SMTP Server 

```php
<?php
require_once( 'phpmailer_5.2.4/class.phpmailer.php');
$mail = new PHPMailer();
$mail->IsSMTP(); // telling the class to use SMTP
$mail->SMTPDebug  = true;                     // enables SMTP debug information (for testing)
												   // 1 = errors and messages
												   // 2 = messages only
$mail->SMTPAuth   = true; 
$mail->Host       = "smtp.mandrillapp.com";
$mail->Port       = '587';     
$mail->Username   = "mymail@lotuscentre.ac.in"; 
$mail->Password   = "my Pasword";  

$subject = 'SMTP Test Mail Subject';
$message = 'This is SMTP Test Mail message for smtp mail.';
$to_email = 'mymail@gmail.com';
$to_name = 'My MailSMTP Check';
$from_email = 'mymail@lotuscentre.ac.in';
$from_name = 'MyMail SMTP';

if(!$mail->Send()) {
echo '<br>Mail Not Sent';
echo '<pre>';
print_r($mail->ErrorInfo);
echo '</pre>';
}
else {
echo '<br>Mail Sent.';
}
```
I am really unable to trace the root cause, It would be really great if you could help me with this.

Thanks in Advance

**Comment by mrdemc** [comment]
SMTP -> ERROR: Password not accepted from server: 535 Incorrect authentication data 
Your password is either incorrect or you are connecting with the wrong serverdetails. Are you sure you are using the correct port and server? Is the username and password combination correct? Can you connect with this server with the same details using other clients? What did you do to debug this situation? And why do you think this is an error in PHPMailer and not a server-/userside error?

**Comment by Synchro** [comment]
Firstly, don't use such an ancient version of PHPMailer, next base your code on an up to date example, then read the documentation, especially [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting).

**Comment by enrichweb** [comment]
It is prompting said error for password because, it is connecting to local server i.e. vps.lotuscentre.ac.in instead of getting connected to smtp.mandrillapp.com and hence Password not accepted

**Comment by Synchro** [comment]
So set the correct password??

**Comment by enrichweb** [comment]
Thank You,  I will try the latest one, Issues is not with the password password is correct and working on one URL. Issue is I have set $mail->Host = "smtp.mandrillapp.com"; wheas request is connecting to local server Exim where is this site is running vps.lotuscentre.ac.in which should not...

**Comment by Synchro** [comment]
Try setting `$mail->SMTPDebug = 4` which will show you want's going on with your connections. Also check that your DNS is resolving correctly as that should cause this symptom.

**Comment by mehran-prs** [comment]
For anyone who faced the same error, (for us) it was because of a security feature in WHM/Cpanel.
The solution is stated in issue #1074.

**Comment by mehran-prs** [comment]
For anyone who faced the same error, (for us) it was because of a security feature in WHM/Cpanel.
The solution is stated in issue #1074.
