### ISSUE TITLE
SMTP module email vs Site Information email

### ISSUE THREAD

**Issue by tahongawaka** [PHPMailer/PHPMailer#463]
I ran into a situation where I had added an E-mail address user the Site Information page. Email sending was not working with my server, so I am now using SMTP.  I created a new address specifically for the site and added it under the SMTP Authentication Support page. Sending an email used the Site Information email instead of the SMTP email.

When adding an email address on the SMTP page, the system should check to see if the Site Information email matches, or at least, add a help line with a link that states that the Site Information email will override the SMTP page email address.

In smtp.mail.inc on line 75 is the override to Site Information Email.

**Comment by Synchro** [comment]
This doesn't sound like it's anything to do with PHPMailer? You need to fix your own code and if you have a problem, include the code in your report.
