### ISSUE TITLE
HTML emails replace every 75th character with an equals (=) sign

### ISSUE THREAD

**Issue by theodorejb** [PHPMailer/PHPMailer#464]
Clearly this is a bug related to quoted-printable encoding for long lines. The issue did not occur in v5.2.7, but I'm seeing it now after upgrading to v5.2.10.

**Comment by Synchro** [comment]
Can you provide code to reproduce this, for example using `getSentMIMEMessage()`? The only thing I can think of that changed recently in this area is that 5.2.10 enables quoted-printable encoding automatically if the content contains lines that are too long for a simpler transfer encoding, and there is a fix for a problem that caused (relating to base64 encoded bodies) in the master branch at the moment.

**Comment by theodorejb** [comment]
I can reproduce it with the following code:

```php
$mail = new PHPMailer();
$mail->isHTML(true);
$mail->setFrom('me@example.com', 'My name');
$mail->addAddress('you@example.com', 'Your name');
$mail->Subject = 'Test broken line wrapping';

$bodyText = '<p>This is a test</p>';
$repeatCount = ceil(PHPMailer::MAX_LINE_LENGTH / strlen($bodyText));

$mail->Body = '<html><body>' . '<h1>HTML email test</h1>'
    . str_repeat($bodyText, $repeatCount)
    . '</body></html>';

$mail->send();
```
The email I receive looks like this:

# HTML email test

This is a test
This is a test<=p>

... and so on, with an equals character appearing every 75 characters throughout the email HTML.

**Comment by Synchro** [comment]
I can't reproduce this - the quoted-printable encoding works perfectly for me. Can you paste the raw text of the received message?

**Comment by theodorejb** [comment]
Here's what I get when I view source in Outlook 2013:

```
Date: Thu, 30 Jul 2015 09:10:18 -0500
To: Your name <you@example.com>
From: My name <me@example.com>
Subject: Test broken line wrapping
Message-ID: <a204h591ol76u39e0b5q946mn646ywgv@server>
X-Mailer: PHPMailer 5.2.10 (https://github.com/PHPMailer/PHPMailer/)
MIME-Version: 1.0
Content-Type: text/html; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<html><body><h1>HTML email test</h1><p>This is a test</p><p>This is a test<=p><p>This is a test</p><p>This is a test</p><p>This is a test</p><p>This i= a test</p><p>This is a test</p><p>This is a test</p><p>This is a test</p>=p>This is a test</p><p>This is a test</p><p>This is a test</p><p>This is a=est</p><p>This is a test</p><p>This is a test</p><p>This is a test</p><p>=his is a test</p><p>This is a test</p><p>This is a test</p><p>This is a te=t</p><p>This is a test</p><p>This is a test</p><p>This is a test</p><p>Thi= is a test</p><p>This is a test</p><p>This is a test</p><p>This is a test<=p><p>This is a test</p><p>This is a test</p><p>This is a test</p><p>This i= a test</p><p>This is a test</p><p>This is a test</p><p>This is a test</p>=p>This is a test</p><p>This is a test</p><p>This is a test</p><p>This is a=est</p><p>This is a test</p><p>This is a test</p><p>This is a test</p><p>=his is a test</p><p>This is a test</p><p>This is a test</p><p>This is a te=t</p><p>This is a test</p><p>This is a test</p><p>This is a test</p></body=</html>
```

**Comment by theodorejb** [comment]
The problem disappears if I remove the call to `fixEOL()` in the `encodeQP()` method (directly returning the result of `quoted_printable_encode()`. Could this be a Windows-specific issue with line endings?

**Comment by Synchro** [comment]
Thanks for the report - You are correct - QP-encoding should *always* use CRLF line breaks for the encoded content ([RFC2045 section 6.7](https://tools.ietf.org/html/rfc2045#section-6.7)), so we don't need to fix encoded output, and don't need to touch input. I also added tests to check that output == input for both line break formats.
