### ISSUE TITLE
Unable to send emails to Office365 mail accounts or use Office365 for SMTP

### ISSUE THREAD

**Issue by GuillermoCasanova** [PHPMailer/PHPMailer#466]
Hi, 

I'm running phpMailer to sending emails from a contact form, which can be found on this site: http://soriallc.com/contact.html

The first issue I ran into was that my emails were being able to be sent to hotmail, Gmail, Yahoo, but not to office365/Outlook. I wasn't getting errors in my console or error_log file. My setup involved creating a mail account through my client's hosting (Greengeeks) called mail@soriallc.com for the SMTP. My mailer.php code was the following:

require("phpMailer/PHPMailerAutoload.php");
$mail = new PHPMailer(true);
$mail->IsSMTP();
$mail->CharSet = 'UTF-8';
$mail->SMTPAuth = true;     // turn on SMTP authentication
$mail->SMTPSecure = 'tls';
$mail->Host = 'localhost'; // Since host is the same it's using localhost 
$mail->Username = "mail@soriallc.com";  // SMTP username
$mail->Password = "<some password>"; // SMTP password
$mail->Port = 587;

Since emails weren't sending to Office365 mail accounts (what my client is running), we started trying to use office365 for the SMTP setup to see if this would get emails delivered to this account. This made things worse as now the form can't send emails due to these errors:
 
http://soriallc.com/mailer.php 500 (Internal Server Error) 
error_log
PHP Fatal error:  Uncaught exception 'phpmailerException' with message 'SMTP Error: Could not authenticate.' in /home/soriallc/public_html/phpMailer/class.phpmailer.php:1458

This is the code with office365 for the SMTP: 

require("phpMailer/PHPMailerAutoload.php");
$mail = new PHPMailer(true);
$mail->IsSMTP();
$mail->CharSet = 'UTF-8';
$mail->SMTPAuth = true;     // turn on SMTP authentication
$mail->SMTPSecure = 'tls';
$mail->Host = 'smtp.office365.com';
$mail->Username = "angel@soriallc.com";  // SMTP username, the email is an office365 email using a 'business domain' 
$mail->Password = "<some password>"; // SMTP password
$mail->Port = 587;

From the error (and since it's the only difference in the code), I'm assuming it's due to the SMTP username and password being incorrect, but the client says all info is correct. 

My questions:

In the first instance, is there a reason why office365 would not get any of the emails (neither spam nor inbox) and would any changes need to be made to their account? 

On the second instance, are there any steps my client would need to take in order to get office365 to authenticate and send emails?

Much thanks!

**Comment by Synchro** [comment]
The first issue is outside PHPMailer's control. You're submitting to localhost successfully, and after that it's all handled by your local mail server, so you need to check your mail server logs to see what has happened to the messages.

For the second problem, try setting `SMTPDebug = 2` so you can see more detail of the SMTP conversation.

**Comment by GuillermoCasanova** [comment]
@Synchro Thanks. We're first gonna try the first route so we've submitted a support ticket to GreenGeeks to receive the mail server logs. Will keep you updated.
