### ISSUE TITLE
504 error

### ISSUE THREAD

**Issue by TheSDTM** [PHPMailer/PHPMailer#468]
Hello, when I try to send my message, it writes after a long waiting 502 error. Connection to SMPT server is correct (I use this connection in another CMS), I load files, write my connection information, then, when I send email, it writes 504 error

**Comment by Synchro** [comment]
502 and 504 errors are HTTP codes, not PHPMailer errors. It sounds like you have DNS or firewall issues as that is the usual reason for connection delays. Read [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting).

**Comment by TheSDTM** [comment]
Ok, thank you. Another problem: when I try ti send email in russian, I recieve email with charset problem. How to set charset to UTF-8? I tried to add "Content-Type: text/html; charset=\"UTF-8\";\r\n" before main message, and it doesnt't help, and if I add this like on line 658 in SMPT file class($this->client_send(LINE . self::CRLF);), I recieve file with correct charset, but everywhere in my email writes  "Content-Type: text/html; charset=\"UTF-8\";\r\n" (because this line is placed in Foreach), and some of line contain ISO-8859-1 charset

**Comment by Synchro** [comment]
Don't do that; Do this, as shown in the examples, and it will take care of everything else:

    $mail->CharSet = 'UTF-8';
