### ISSUE TITLE
Message could not be sent.Mailer Error: SMTP connect() failed.

### ISSUE THREAD

**Issue by rocky5469** [PHPMailer/PHPMailer#469]
hi, i'm new to php and i have been trying to send e-mail through php, phpmailer is the only class i find most recommended by most of the developers. i tried almost all solutions for my error. i cant find the fix. I have tried the link below, but didn't get what to do, and googled for the solution, couldn't find any, which works for me.  tried almost all solutions, but it keeps showing me the same error.

Message could not be sent.Mailer Error:SMTP connect() failed.https://github.com/PHPMailer/PHPMailer/wiki/TroubleshootingAvailable

tried the above link, as im new to php, im stuck.

fr all smtpdebug: 1,2,3,4, its giving same error... but php mail() function is working fine.

and our hosting provider says this...

We have the following list of ports open on our shared hosting plans:

HTTP/HTTPS - 80/443
GMail - 465/587/995/993
TOMCAT - 8080
SMTP/IMAP/POP - 25/143/110

here is the code im using. please help me to resolve the error. thanx in advance.

```php
<?php


require 'phpmailer/PHPMailerAutoload.php';
$mail = new PHPMailer;

//$mail->SMTPDebug = 3;                               // Enable verbose debug output

$mail->isSMTP();                                      // Set mailer to use SMTP
$mail->Host = 'smtp.gmail.com';              // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'userid@gmail.com';                 // SMTP username
$mail->Password = 'secret';                           // SMTP password
$mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 587;                                    // TCP port to connect to

$mail->From = userid@gmail.com';
$mail->FromName = 'Mailer';
//$mail->addAddress('joe@example.net', 'Joe User');     // Add a recipient
$mail->addAddress('name@mysite.com');               // Name is optional

//$mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
//$mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name
$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'Here is the subject';
$mail->Body    = 'This is the HTML message body <b>in bold!</b>';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

if(!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message has been sent';
}
?>
```

**Comment by Synchro** [comment]
That link should be https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting - I'm not sure where the "Available" came from. As the guide says, in pretty much every case this is nothing to do with PHPMailer, but the network config on your server or ISP. Setting `SMTPDebug` to anything other than 0 should produce visible output, which you have not posted here. Most of the tests described in the guide require you to SSH into your server and run the commands from there.

The mail function may appear to work, but it's not doing the same thing - it's sending through your local mail server, not your Gmail account. You can do the same thing with PHPMailer by calling `isMail` instead of `isSMTP`.

**Comment by rocky5469** [comment]
thank you so much Synchro for your precious feedback .

 isMail() working perfectly. but i dnt knw y isSMTP is still giving some error, which i dont understand at all
ERROR is:

2015-08-04 01:59:54	CLIENT -> SERVER: EHLO mysite.com 2015-08-04 01:59:54	CLIENT -> SERVER: AUTH LOGIN 2015-08-04 01:59:54	CLIENT -> SERVER: cm9ja3k1NDY5QGdtYWlsLmNvbQ== 2015-08-04 01:59:55	CLIENT -> SERVER: KioqKioqKioqKioqKioq 2015-08-04 01:59:55	SMTP ERROR: Password command failed: 535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/answer/14257 <b>i7sm8522522obe.8</b> - gsmtp 2015-08-04 01:59:55	SMTP Error: Could not authenticate. 2015-08-04 01:59:55	CLIENT -> SERVER: QUIT 2015-08-04 01:59:55 SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting Message could not be sent.Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/TroubleshootingAvailable


My coding


<?php


require 'phpmailer/PHPMailerAutoload.php';
$mail = new PHPMailer;

//$mail->SMTPDebug = 3;                               // Enable verbose debug output

$mail->isSMTP();                                      // Set mailer to use SMTP
$mail->Host = 'smtp.gmail.com';              // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'userid@gmail.com';                 // SMTP username
$mail->Password = 'secret';                           // SMTP password
$mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 587;                                    // TCP port to connect to

$mail->From = userid@gmail.com';
$mail->FromName = 'Mailer';
//$mail->addAddress('joe@example.net', 'Joe User');     // Add a recipient
$mail->addAddress('name@mysite.com');               // Name is optional

//$mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
//$mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name
$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'Here is the subject';
$mail->Body    = 'This is the HTML message body <b>in bold!</b>';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

if(!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message has been sent';
}
?>

**Comment by rocky5469** [comment]
Synchro sorry, i didnt mentioned that the bold values in error message, keeps on changing each time i refresh my page...

**Comment by Synchro** [comment]
That bold value is just a link tracking ID, it will end up in the same place. So it just looks like your username or password is not correct.

**Comment by Synchro** [comment]
That transcript looks like you have `SMTPDebug = 1`; try setting it to 2 and you should see more info.

**Comment by rocky5469** [comment]
dear synchro. thanks for your reply. but got some issues.

<?php


require 'phpmailer/PHPMailerAutoload.php';


$mail = new PHPMailer;

$name = $_POST['name'];
$phone = $_POST['phone'];
$email = $_POST['email'];
$file = $_FILES['attachment']['tmp_name'];

$message = $_POST['message'];

//$mail->SMTPDebug = 3;                               // Enable verbose debug output

$mail->isMail();                                      // Set mailer to use SMTP
$mail->Host = 'localhost';  // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'name@site.com';                 // SMTP username
$mail->Password = 'password';                           // SMTP password
$mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 587;                                    // TCP port to connect to

$mail->From = 'name@site.com';
$mail->FromName = $name;
//$mail->addAddress('joe@example.net', 'Joe User');     // Add a recipient
$mail->addAddress('mame1@gmail.com');               // Name is optional

//$mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments

$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'SASP Contact Form';
$mail->Body = $message;
$mail->Body .= "<br /><br />Below are my contact details <br /> Name: ";
$mail->Body .= $name;
$mail->Body .= "<br />My Phone number: ";
$mail->Body .= $phone;
$mail->Body .= "<br /> My email address: ";
$mail->Body .= $email;


$mail->AltBody = 'You are using basic web browser ';
if(is_array($_FILES)) {
	$mail->AddAttachment($_FILES['attachment']['tmp_name'],$_FILES['attachment']['name']); 
}

if(!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    //echo 'Message has been sent';
    header('Location: thankyou.html');
}
?>

1. in the above code, when i send mail from isMail() function, its working perfectly  wen the recipient mail is name@mysite.com. but if i change the recipient mail to, name@gmail.com, its shows. following error...

Message could not be sent.Mailer Error: Could not instantiate mail function.

**Comment by Synchro** [comment]
Solve one problem at a time. Your code for handling attachments is wrong - look at the examples folder for how to do that properly, but solve your connection problem first.
If you're getting messages like that using isMail(), look in your mail server log and check your PHP config.

**Comment by rocky5469** [comment]
thank u fr the replay..
but i'm clueless what i need to check in php config..?
i m using shared hosting..

**Comment by Synchro** [comment]
"Could not instantiate mail function" usually means you have no local mail server, so check that you have one. In your php.ini file you should have a setting for [sendmail_path](http://php.net/manual/en/mail.configuration.php#ini.sendmail-path), and that program must exist. If you can't change that, or it doesn't exist, contact your hosting provider.

When you say "it's working perfectly", do you mean that the script runs *and* you receive the sent message?

**Comment by rocky5469** [comment]
yes. when i use isMail(). i receive message perfectly. only when the recipient mail is name@mysite.com

but when i change the $mail->addAddress('name@mysite.com'); to $mail->addAddress('name@gmail.com');.

with rest of the code untouched, i get "Could not instantiate mail function"

**Comment by shivka** [comment]
hello synchro....
I have an error in my coding 
Message could not be sent.Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

<?php 
require 'PHPMailer-master/PHPMailerAutoload.php';
 
$mail = new PHPMailer;
 
$mail->IsSMTP();
$mail->Host = 'smtp.gmail.com';
$mail->SMTPAuth = true;
$mail->Username = 'sonamsingh.covetus@gmail.com';
$mail->Password = '1234567890';
$mail->SMTPSecure = 'tls';
$mail->Port=587;
 
$mail->From = 'sonamsingh.covetus@gmail.com';
$mail->FromName = 'sonam';
$mail->addAddress('sonamsingh.covetus@gmail.com', 'shanu');
 
$mail->addReplyTo('sonamsingh.covetus@gmail', 'shanu');
 
$mail->WordWrap = 50;
$mail->isHTML(true);
 
$mail->Subject = 'Using PHPMailer';
$mail->Body    = 'Hi Iam using PHPMailer library to sent SMTP mail from localhost';
 
if(!$mail->send()) {
   echo 'Message could not be sent.';
   echo 'Mailer Error: ' . $mail->ErrorInfo;
   exit;
}
 
echo 'Message has been sent';
/*require 'PHPMailer-master/PHPMailerAutoload.php';
$mail = new PHPMailer;
 
$mail->isSMTP();
$mail->Host = 'smtp.gmail.com';
$mail->SMTPAuth = true;
$mail->Username = 'sonamsingh.covetus@gmail.com';
$mail->Password = 'job2015@';
$mail->SMTPSecure = 'ssl';
$mail->Port=465;
  $mail->SMTPDebug = 3;
$mail->From = 'sonamsingh.covetus@gmail.com';
$mail->FromName = 'sonam singh';
$mail->addAddress('monika1990.agrawal@gmail.com');
 
$mail->addReplyTo('sonamsingh.covetus@gmail.com', 'sonam singh');
 
$mail->WordWrap = 50;
$mail->isHTML(true);
 
$mail->Subject = 'Using PHPMailer';
$mail->Body    = 'Hi Iam using PHPMailer library to sent SMTP mail from localhost';
 
if(!$mail->send()) {
   echo 'Message could not be sent.';
   echo 'Mailer Error: ' . $mail->ErrorInfo;
   exit;
}
 
echo 'Message has been sent'; */

?>

**Comment by Synchro** [comment]
How about you read the docs the error message links you to?

**Comment by shivka** [comment]
its show on my page

**Comment by shivka** [comment]
how can i run my program

**Comment by shivka** [comment]
how can i solve my error

**Comment by Synchro** [comment]
Read the docs, like I told you.

**Comment by Mozammelctgmirbd** [comment]
Dear brother(synchro)
assalamualaikum.i got successfully messase(when i run form localhost).but i dont get message when i open my gmail account.

**Comment by Mozammelctgmirbd** [comment]
this is my code
<?php
require('phpmailer/class.phpmailer.php');
$mail = new PHPMailer;

$name = 'name';
$phone = 'phone';
$email = 'email';
$message = 'HI Friends How are you';

//$mail->SMTPDebug = 3;                               // Enable verbose debug output

$mail->isMail();                                      // Set mailer to use SMTP
$mail->Host = 'localhost';  // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'it2@aps-group.org';                 // SMTP username
$mail->Password = '*****';                           // SMTP password
$mail->SMTPSecure = 'ssl';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 486;                                    // TCP port to connect to

$mail->From = 'it2@aps-group.org';
$mail->FromName = $name;
//$mail->addAddress('joe@example.net', 'Joe User');     // Add a recipient
$mail->addAddress('mozammelctgmirbd@gmail.com');               // Name is optional

//$mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments

$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'SASP Contact Form';
$mail->Body = $message;
$mail->Body .= "<br /><br />Below are my contact details <br /> Name: ";
$mail->Body .= $name;
$mail->Body .= "<br />My Phone number: ";
$mail->Body .= $phone;
$mail->Body .= "<br /> My email address: ";
$mail->Body .= $email;


$mail->AltBody = 'You are using basic web browser ';

if(!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message has been sent';

}
?>

**Comment by Synchro** [comment]
@Mozammelctgmirbd: Read before posting, don't hijack old threads. You are using an old version of PHPMailer and have not read the docs. You've made up apparently random settings and you're wondering why it doesn't work. It's very likely that you need to say `$mail->Port = 465;`.

**Comment by Mozammelctgmirbd** [comment]
Dear Brother
which mail address i will get message. i am Confucius.i am not getting message in mozammelctgmirbd@gmail.com and it2@aps-group.org.
but i am getting echo 'Message has been sent'

**Comment by Mozammelctgmirbd** [comment]
sendmail.inc  i change flowing this

[sendmail]

smtp_server=smtp.gmail.com
smtp_port=465
smtp_ssl=auto
error_logfile=error.log
auth_username=mozammelctgmirbd@gmail.com
auth_password=rupela123

**Comment by Mozammelctgmirbd** [comment]
you told me that for change $mail->Port = 465;.
i change this 
but
i am not getting message in mozammelctgmirbd@gmail.com and it2@aps-group.org.
but i am getting echo 'Message has been sent'

**Comment by Mozammelctgmirbd** [comment]
i dont undestand.please help me

**Comment by Synchro** [comment]
Sendmail settings have no effect because you're using SMTP - again, changing random settings will not help. Messages will be sent to your gmail address, but you **really** need to [read the docs](https://github.com/PHPMailer/PHPMailer/wiki).

**Comment by Mozammelctgmirbd** [comment]
Dear Brother 
i forget before code of sendmail.inc
sendmail.inc i change flowing this
[sendmail]
smtp_server=smtp.gmail.com
smtp_port=465
smtp_ssl=auto
error_logfile=error.log
auth_username=mozammelctgmirbd@gmail.com
auth_password=rupela123

**Comment by Synchro** [comment]
There's not much point in me trying to help you if you don't read what I say. Also, don't post your passwords - this is a public forum.

**Comment by Mozammelctgmirbd** [comment]
sorry my dear Brother

**Comment by Mozammelctgmirbd** [comment]
you are helper so that i know about you

**Comment by Mozammelctgmirbd** [comment]
Dear Brother
again insttal xampp.try again but dont get any message i sing in mozammelctgmirbd@gmail.com
this my code
<?php
require('phpmailer/class.phpmailer.php');
$mail = new PHPMailer;

$name = 'name';
$phone = 'phone';
$email = 'email';
$message = 'HI Friends How are you';

//$mail->SMTPDebug = 3; // Enable verbose debug output

$mail->isMail(); // Set mailer to use SMTP
$mail->Host = 'localhost'; // Specify main and backup SMTP servers
$mail->SMTPAuth = true; // Enable SMTP authentication
$mail->Username = 'it2@aps-group.org'; // SMTP username
$mail->Password = '*****'; // SMTP password
$mail->SMTPSecure = 'ssl'; // Enable TLS encryption, ssl also accepted
$mail->Port = 465; // TCP port to connect to

$mail->From = 'it2@aps-group.org';
$mail->FromName = $name;
//$mail->addAddress('joe@example.net', 'Joe User'); // Add a recipient
$mail->addAddress('mozammelctgmirbd@gmail.com'); // Name is optional

//$mail->addAttachment('/var/tmp/file.tar.gz'); // Add attachments

$mail->isHTML(true); // Set email format to HTML

$mail->Subject = 'SASP Contact Form';
$mail->Body = $message;
$mail->Body .= "

Below are my contact details 
Name: ";
$mail->Body .= $name;
$mail->Body .= "
My Phone number: ";
$mail->Body .= $phone;
$mail->Body .= "
My email address: ";
$mail->Body .= $email;

$mail->AltBody = 'You are using basic web browser ';

if(!$mail->send()) {
echo 'Message could not be sent.';
echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
echo 'Message has been sent';

}
?>

**Comment by Mozammelctgmirbd** [comment]
please help me

**Comment by Mozammelctgmirbd** [comment]
Dear broth (Synchro)
what can i do.

**Comment by Synchro** [comment]
I don't know how I can make this any clearer: [read the docs](https://github.com/PHPMailer/PHPMailer/wiki).

**Comment by Mozammelctgmirbd** [comment]
ok dear you say i want to see message. which mail this message will be store

**Comment by Mozammelctgmirbd** [comment]
mozammelctgmirbd@gmail.com or it2@aps-group.org ------------------which--????

**Comment by Mozammelctgmirbd** [comment]
please please please
i use this code localy
lan local area network

**Comment by Mozammelctgmirbd** [comment]
not online from any site

**Comment by Synchro** [comment]
It will send **to** `mozammelctgmirbd@gmail.com`, **from** `it2@aps-group.org`. I can't help you if you won't do what I suggest. It sounds like you really don't know what you're doing, so read the docs not only for PHPMailer, but for PHP as well. I am not here to teach you PHP - there are many other places you can learn that.
