### ISSUE TITLE
Add ability to send calendar events

### ISSUE THREAD

**Issue by Synchro** [PHPMailer/PHPMailer#47]
Calendar events are typically sent by email in a three-part multipart/alternative MIME structure where the parts are text/html, text/plain and text/calendar. Because PHPMailer doesn't support arbitrary MIME structures, only a selection of presets, it's not possible to use it to construct a message like this, and some recent changes make it difficult to manipulate the MIME structure to accommodate it.
There is some example code for sending such messages [here](http://www.julian-young.com/2009/07/07/php-ical-email/), but it would be nice to roll this into PHPMailer.

**Comment by rmuktader** [comment]
This does not seem to work with gmail.

**Comment by Synchro** [comment]
@rmuktader please read #175
