### ISSUE TITLE
SMTP Mail (STARRTTLS/TLS) failing to pass through "encryption" phase using stream_socket_enable_crypto

### ISSUE THREAD

**Issue by GreasyMonkee** [PHPMailer/PHPMailer#470]
Hi,
I am no php expert (or even a novice), but have been trying to debug an application (not mine) that is using PHPMailer as it's mail-handler.

The problem is that it fails the "crypto" part of the authenticated connection on port 587, but the mail-server is working fine for SASL-authenticated mail submission (port 587) from Dovecot, and also SMTP (port 25) from the application.

Using Synchro's well-documented little test script from Issue # 189, and reviewing the STRACE dump of the messages from httpd and it's child processes, I have narrowed it down to crypto failure.
Clipping from STRACE is below for further reference - **** marks the first indication of trouble.

I know this is outside of the PHPMailer "realm", however being a total "noob" on php/apache, I may well have not loaded a php module or other "required" package that is needed for this module to work correctly, hence my request here of the experts.

My server is running Fedora 22, Kernel 4.0.8, with Apache-2.4.16 and php-5.6.11, built using Openssl-1.0.2d (with Fedora .spec files, not "home-brew" jobs). Have tried both PHPMailer Ver.5.2.7 and 5.2.10, same results.

I've installed Apache with mod_ssl, etc, and the certificates are installed and being correctly referenced (server and CA certs) when using https to connect to the server applications, but through php it is throwing one or both as "unknown ca".

I would greatly appreciate any comments, ideas, etc on how to get this solved - I am sure it will be something fairly simple (I am hoping so....)

Cheers,
GM

The loaded php modules are:
```php
php-cli
php-common
php-devel
php-gd
php-debuginfo
php-imap
php-mbstring
php-pdo
php-pgsql
php-xml
php-pecl-jsonc
php-pecl-jsonc-devel
```
STRACE DUMP from "220 Ready to start TLS"

```
3037  recvfrom(17, "220 2.0.0 Ready to start TLS\r\n", 8192, MSG_DONTWAIT, NULL, NULL) = 30
3037  write(2, "[Mon Aug 03 12:15:04.766284 2015"..., 212) = 212
3037  open("/etc/crypto-policies/back-ends/openssl.config", O_RDONLY) = 18
3037  fstat(18, {st_mode=S_IFREG|0644, st_size=115, ...}) = 0
3037  mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc53ef4d000
3037  read(18, "!SSLv2:kEECDH:kRSA:kEDH:kPSK:+CA"..., 4096) = 115
3037  close(18)                         = 0
3037  munmap(0x7fc53ef4d000, 4096)      = 0
3037  open("/etc/pki/CA/cacert.pem", O_RDONLY) = 18
3037  fstat(18, {st_mode=S_IFREG|0755, st_size=258424, ...}) = 0
3037  mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc53ef4d000
3037  read(18, "##\n## Bundle of CA Root Certific"..., 4096) = 4096
3037  read(18, "YDVR0TAQH/BAUwAwEB/zAdBgNVHQ4E\nF"..., 4096) = 4096

(Certificate removed, snipped for brevity)

3037  read(18, "XV0aG9yaXplZCB1c2Ug\nb25seTEyMDAG"..., 4096) = 4096
3037  read(18, "g1MvIB671Oi6ON7fQAUtDKXeMOZePglr"..., 4096) = 376
3037  read(18, "", 4096)                = 0
3037  close(18)                         = 0
3037  munmap(0x7fc53ef4d000, 4096)      = 0
3037  fcntl(17, F_GETFL)                = 0x2 (flags O_RDWR)
3037  fcntl(17, F_SETFL, O_RDWR|O_NONBLOCK) = 0
3037  write(17, "\26\3\1\0\225\1\0\0\221\3\1 \312\316QBs\274'=\310\323\f-V\303a\364\363\342\217\331"..., 154) = 154
3037  read(17, 0x7fc4e88d1343, 5)       = -1 EAGAIN (Resource temporarily unavailable)
3037  poll([{fd=17, events=POLLIN|POLLPRI}], 1, 10000) = 1 ([{fd=17, revents=POLLIN}])
3037  read(17, "\26\3\1\0B", 5)         = 5
3037  read(17, "\2\0\0>\3\1\250\311\34\350\263\240%[\271\273Y\17P\244\267X \36z\227\313\275v\326\364\260"..., 66) = 66
3037  read(17, "\26\3\1\6O", 5)         = 5
3037  read(17, "\v\0\6K\0\6H\0\6E0\202\6A0\202\5)\240\3\2\1\2\2\7\6\16\254\255;\222\305"..., 1615) = 1615
**** 3037  stat("/etc/pki/CA/38d751eb.0", 0x7fc512fe9160) = -1 ENOENT (No such file or directory)
3037  write(17, "\25\3\1\0\2\0020", 7)  = 7
3037  access("/var/www/wwwFiles/logs", F_OK) = 0
3037  access("/var/www/wwwFiles/logs", W_OK) = 0
```

**Comment by Synchro** [comment]
Are you not getting any higher-level errors, like with `SMTPDebug = 4`? That certificate name looks like it's some kind of root cert as I've found [other references to the same ID](http://forum.nettworks.org/index.php?t=tree&th=1647&mid=7879&&rev=&reveal=) in a root or sub-root cert context. Is your root cert bundle up to date, or perhaps too up to date and it's looking for an old root cert?

**Comment by GreasyMonkee** [comment]
Hi,

I will call up some higher-level logs today and post them.

The certificate is the most recent CA-bundle from cURL's repository, and it has the valid signing authority (Startcom) in the list. Have tried with the default Mozilla CA-bundle, and dig a bit more.

Cheers.

**Comment by GreasyMonkee** [comment]
Hi,

NOW things are progressing - I am not sure why, but I had overlooked creating the sym-links for the certificates - sleep deprivation is my excuse.

A BIG thank you for the nudge in the correct direction.

There is still a problem with sending the mails out, the SASL Auth request to Dovecot is with a PID = 0.

Shall need to chase that one down, but at least I am through the crypto maze.

Cheers,
GM.
