### ISSUE TITLE
Stop mail sending

### ISSUE THREAD

**Issue by szepeviktor** [PHPMailer/PHPMailer#471]
WordPress calls the `Send` method without returning the error code.
```php
// Send!
try {
    return $phpmailer->Send();
} catch ( phpmailerException $e ) {
    return false;
}
```
So there is no way to log send errors.
I am trying to call `Send` with error handling in my plugin then prevent sending.
```php
// Prevent second sending in WordPress code
$mail->clearAddresses();
$mail->clearCCs();
$mail->clearBCCs();
```
But this throws an exception.

Please advise how to silently prevent message sending.
Thank you!

**Comment by szepeviktor** [comment]
> Please advise how to silently prevent message sending.

Reading my own lines it seems that this would be a fatal failure in PHPMailer.
But I am waiting for your advise.

**Comment by Synchro** [comment]
That's just a bug in Wordpress' implementation. They should be returning something more useful or not trapping exceptions. If you can get a handle on the `$phpmailer` object you can inspect `ErrorInfo`.

**Comment by szepeviktor** [comment]
Thank you very much!!
I will save the `&$phpmailer` reference and analyze that property on shutdown.
