### ISSUE TITLE
OpenSSL issue Idk know what to do!

### ISSUE THREAD

**Issue by OfficialJoe** [PHPMailer/PHPMailer#472]
2015-08-09 00:05:45	Extension missing: openssl 
Message could not be sent.

Im using this host: http://www.versio.nl/31-wat-zijn-de-pop-imap-en-smtp-gegevens-van-mijn-email-account

And I tried the secured and unsecured one and both error giving above! 

CODE http://pastebin.com/m9TJebBT

**Comment by Synchro** [comment]
Like the error says - you are missing the OpenSSL extension.

**Comment by OfficialJoe** [comment]
Yea, But what is this and how can I solve this?

**Comment by Synchro** [comment]
http://lmgtfy.com/?q=enable+php+openssl+extension
