### ISSUE TITLE
From Address is not Customizable

### ISSUE THREAD

**Issue by itsme-sai** [PHPMailer/PHPMailer#473]
Hi !
By using the $mail->setFrom() function Iam trying to change the from mail id as per my requirement. But, when at the time of mail received, the from name is displaying correctly but the from mail id is taking from the smtp username but not one that I provided. 

Any help in this will be thankful !!

**Comment by Synchro** [comment]
It's not PHPMailer doing this but your mail server. Gmail in particular does not let you send using arbitrary from addresses, though you can predefine allowed aliases.

**Comment by itsme-sai** [comment]
Oh... Otherwise can I achieve this one by using other than GMAIL(mail servers) ?

**Comment by Synchro** [comment]
Yes, or predefine the aliases in your gmail settings.
