### ISSUE TITLE
Can not open attached email file

### ISSUE THREAD

**Issue by TerrySchroeder** [PHPMailer/PHPMailer#474]
Hi,
I upload class.phpmailer.php, class.pop3.php, class.smtp.php, and PHPMailerAutoload.php to a directory phpmailer on the server. I think the server is running apache on linux server.

I have an html form that the user can browse for a  file to be emailed to me. When the user hits submit, the php code loaded on the server is run. There are no error messages but the attached file is unreadable, can't even open it. In my test, I tried to attach a .jpg file.

This is my html code:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
</head>

<body>
<form method="post" action="process.php" enctype="multipart/form-data">
  <input type="file" name="userfile" id="userfile" />
     <input type="submit" name="button" value="Submit" />

</form>
</body>

</html>
-----------------------------------------------------------------------------------------------------------
This is the php code uploaded to server: (process.php)

<?
require_once 'phpmailer/class.phpmailer.php';

$mail = new PHPMailer(true); //defaults to using php "mail()"; the true param means it will throw exceptions on errors, which we need to catch

$msg = ''; 
if (array_key_exists('userfile', $_FILES)) { 
    // First handle the upload 
    // Don't trust provided filename - same goes for MIME types 
    // See http://php.net/manual/en/features.file-upload.php#114004 for more thorough upload validation 
     $uploadfile = tempnam(sys_get_temp_dir(), sha1($_FILES['userfile']['name'])); 
     if (move_uploaded_file($_FILES['userfile']['tmp_name'], $uploadfile)) { 
         // Upload handled successfully 
         // Now create a message 
         // This should be somewhere in your include_path 
         require 'phpmailer/PHPMailerAutoload.php'; 
         $mail = new PHPMailer; 
         $mail->setFrom('from@example.com', 'First Last'); 
         $mail->addAddress('thedrywallartist@gmail.com', 'Terry'); 
        $mail->Subject = 'PHPMailer file sender'; 
         $mail->msgHTML("My message body"); 
         // Attach the uploaded file 
         $mail->addAttachment($uploadfile, 'My uploaded file'); 
         if (!$mail->send()) { 
             $msg = "Mailer Error: " . $mail->ErrorInfo; 
         } else { 
             $msg = "Message sent!"; 
         } 
     } else { 
        $msg = 'Failed to move file to ' . $uploadfile; 
     } 
 } 
  
?>

The email attachment looks like this in Outlook:
--------------------------------------------------------------
From: First Last [from@example.com]
To:      Terry
Cc:
subject: PHPMailer file sender

MESSAGE My uploaded file.dat (2 kb)
 It should be portable.jpg, the file that I entered in the html form.
msg body:
My message body
------------------------------------------------------------------------

What am I doing wrong? 
Thank you in advance,
Terry Schroeder

**Comment by Synchro** [comment]
It's because both outlook and PHPMailer use the file name to set the default MIME type, but you're using a name with no extension and not setting the type manually, so it's defaulting to a generic type.

**Comment by TerrySchroeder** [comment]
Hi Marcus,

Thank you for the information!

Do you have an example I can look at?

This is all new territory to me so any examples are VERY helpful.

Thank you again,

Terry Schroeder

**Comment by Synchro** [comment]
It's all covered in the docs and examples provided. [Start with the wiki](https://github.com/PHPMailer/PHPMailer/wiki).

**Comment by TerrySchroeder** [comment]
SUPER!!!! Thank you!

**Comment by TerrySchroeder** [comment]
Hi Marcus,

After some research, I got it to work. Here is the code I found on Stackoverflow.

Thank you again,

Terry

 

-----------------------------------------------

<?php 

 

 $msg = ''; 

 

 require 'phpmailer/PHPMailerAutoload.php';

  

 $mail = new PHPMailer; 

 $mail->setFrom('from@example.com', 'First Last'); 

 $mail->addAddress('thedrywallartist@gmail.com', 'Terry'); 

 $mail->Subject = 'PHPMailer file sender'; 

 $mail->msgHTML("My message body"); 

 // Attach the uploaded file 

 

 if (isset($_FILES['uploaded_file']) &&

    $_FILES['uploaded_file']['error'] == UPLOAD_ERR_OK) {

    $mail->AddAttachment($_FILES['uploaded_file']['tmp_name'],

                                                     $_FILES['uploaded_file']['name']);

   }

 

if($mail->Send()){

    echo 'Email Successfully Sent!';

}else{

    echo 'Email Sending Failed!';

}

?>

---------------------------------------------------------------

**Comment by Synchro** [comment]
I'm glad it works for you, but trying random code in the hope that it works isn't really a valid means of debugging - in this case, you don't know why it works, or what you did wrong, so you've not learned anything from it. This code doesn't call `move_uploaded_file` so it may have security issues. Read the PHP docs on handling uploaded files.
