### ISSUE TITLE
Issue with Sending Email if CSF is enabled

### ISSUE THREAD

**Issue by enrichelife** [PHPMailer/PHPMailer#475]
Hello,

We are facing issue in sending email which CSF( iptables) is enabled and If we disable Firewall it allow to send email Email Successfully. For reference please find error prompted is as follows. 

SMTP -> ERROR: Failed to connect to server: Connection refused (111)
The following From address failed: callme@enrich.co.in : Called Mail() without being connected
Hello,Mail Not Sent
The following From address failed: callme@enrich.co.in : Called Mail() without being connected

**Comment by Synchro** [comment]
This is no great surprise - if you block outbound email, why would you expect it to work?

**Comment by enrichelife** [comment]
Thank You for you response but We have already allowed TCP Port IN/OUT for 25, 465,587, 995. which are being used in the script to send email.
Is there any other port for Php Mailer we should enable ?

**Comment by Synchro** [comment]
No, but you're blocking egress ports and PHPMailer has no control over what source port it uses, so it's likely to be that. If you look at your firewall log, it will tell you what it blocked.
