### ISSUE TITLE
Error sending mail with inline images with no file name

### ISSUE THREAD

**Issue by taishar** [PHPMailer/PHPMailer#478]
Hi,
Wanted to let you know that when sending mail through amazon mail server (this didnt happen with gmail) with inline images that were added through **addStringEmbeddedImage** or extracted from the html with **msgHTML** (which uses addStringEmbeddedImage), we received the error: *Transaction failed: Expected parameter value, got "null"*.

We found this happens when using *addStringEmbeddedImage* with no file name for the third argument.
Because of this 2 of the mime values 
**'Content-Type: %s; name="%s"%s'** and 
**'Content-Disposition: %s; filename="%s"%s'** in the function *attachAll* were empty and this caused the error with amazon mail server.
when supplied with file name in those mime values the mail was sent with no error.

Maybe there should be some default file name in those cases.

Great library by the way!

**Comment by Synchro** [comment]
Thanks for the report. I've fixed this by removing the empty name/filename properties rather than adding a default, and I added a unit test for it too. If you don't specify a name, you really must set a MIME type or it's unlikely to work anywhere. Does this work for you?

**Comment by Luisinho77** [comment]
Greetings, 

Look at that, it's something really worthy, don't miss it.  Here is  the link  <http://agree.pumpjuice.com/e4xucjw>

Best, ljlorente
