### ISSUE TITLE
Failed to move file to

### ISSUE THREAD

**Issue by naskobulgaria** [PHPMailer/PHPMailer#479]
I try to give all possible permissions to the temp folder. And still see Failed to move file to.
Here is the code:
$msg = '';
if (array_key_exists('userfile', $_FILES)) {
    $uploadfile = tempnam(sys_get_temp_dir(), sha1($_FILES['userfile']['name']));
    if (move_uploaded_file($_FILES['userfile']['tmp_name'], $uploadfile)) {

**Comment by Synchro** [comment]
That `sha1` call is unnecessary - it's only an identifying prefix - the `tempnam` function already generates a unique random filename, so do this instead:

    $uploadfile = tempnam(sys_get_temp_dir(), 'upload');

Check the write permissions from PHP:

  var_dump(is_writable(sys_get_temp_dir()));

Note that `move_uploaded_file` will also fail if it doesn't think the file has been uploaded correctly, not just if the destination is not writable.
