### ISSUE TITLE
550 A URL smtp error email

### ISSUE THREAD

**Issue by cphansson** [PHPMailer/PHPMailer#480]
Hi
I'm not sure if this is the right place to post this issue but I hope you can point me in the right direction.

My wordpress site keeps sending me Mail delivery failed notifications every time a new user registers or requests lost password. Also, the users never receive the auto generated emails from wordpress. 
According to the bounceback data the emails are being rejected due to their body containing an URL to the website which has been flagged for malware distribution. I checked my account for any suspicious activity, but it appears to be clean.  I attached a screen of the failed notification and was just wondering if this has anything to do with the PHP Mailer?

![screen shot 2015-09-01 at 12 02 01 am](https://cloud.githubusercontent.com/assets/14066579/9596001/c0549cb2-503c-11e5-935e-3967834f2850.png)

Thanks in advance for your reply

**Comment by Synchro** [comment]
I've seen this happen too, but it's nothing to do with PHPMailer. It's that the mail filter thinks that the domain mentioned in the message body is associated (at least historically) with spam, if for example your wordpress install has ben hacked and is being used as a spambot (take a look at plugins like ninja firewall and wordfence to help with this). Read what they say on https://spamrl.com - you might want to put a notice saying to check spam folder for password reset emails.
