### ISSUE TITLE
Connecting to local Mail server insted of Actual smtphost

### ISSUE THREAD

**Issue by enrichelife** [PHPMailer/PHPMailer#484]
Hello,
We trying to send email by authenticated Remote SMTP like mandrillpapp/mailjet/gmail. 

```php
$mail->IsSMTP(); // telling the class to use SMTP
$mail->Host       = "smtp.mandrillapp.com";       // sets the SMTP server
```
Whereas it is connecting to local Server (vprc1.myhostapps.com) where phpmailer script is running with following output and hence mails are not sending. 

```
Connection: opening to smtp.mandrillapp.com:587, timeout=300, options=array ()
Connection: opened
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is  "220-vprc1.myhostapps.com ESMTP Exim 4.85 
```

We have tried it on two different server and found this issue is intermittent, What could be the issue and how to resolve it ?

**Comment by Synchro** [comment]
It's likely that your ISP is redirecting outbound email traffic to their own mail server using their firewall. It's a common anti-bot measure. I suggest you check your host's documentation and open a support ticket with them. The [https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting](troubleshooting guide) has some info that can help you check if this is what's happening.
