### ISSUE TITLE
Multiple attachments

### ISSUE THREAD

**Issue by SkaiaSwiss** [PHPMailer/PHPMailer#486]
Hello guys,
I'm using PHPMailer with only one attachment without any problems but when I try to add a second one, I receive a mail with empty body and no attachment.
I'm using the same code as in the example.
Thanks in advance for your help.
Regards.
SkaiaSwiss

**Comment by Synchro** [comment]
Please post your code.

**Comment by SkaiaSwiss** [comment]
Synchro, thanks for your answer.
Please find my code below:

<?PHP
error_reporting(E_ALL);
ini_set('display_errors', 1);
include("/path/www/fonctions/PHPMailer/class.phpmailer.php");
$email = new PHPMailer();
$email->From      = 'email@domain';
$email->FromName  = 'FromName;
$email->Subject   = 'Subject';
$email->Body      = 'Body';
$email->AddAddress('email@domain');
$error1 = "/path/www/php_errors.log";
$error2 = "/path/www/client/php_errors.log";
if(file_exists($error1))
{
	$email->AddAttachment($error1 , 'php_errors.log');
	unlink($error1);
}
if(file_exists($error2))
{
	$email->AddAttachment($error2 , 'client_php_errors.log');
	unlink($error2);
}
$email->isHTML(true);
$email->Send();
?>

Thanks in advance for your help!
Regards.
SkaiaSwiss

**Comment by Synchro** [comment]
When you call `addAttachment()` it configures where to look for the file, but the message is not constructed until you send, by which time you've deleted the attachments. Don't unlink the files until after you've called `send()`.

You're also using an old version of PHPMailer and have based your code on an obsolete example - get the latest.

**Comment by SkaiaSwiss** [comment]
Thank you very much for your help!
