### ISSUE TITLE
problem with Loop and Ticketing system

### ISSUE THREAD

**Issue by amirkoklan** [PHPMailer/PHPMailer#487]
I am sending some HTML-based emails in a "foreach" loop using PHPmailer and SMTP and it works quite well except in one case which the email client is "Kayako-Fusion Ticketing system" and it takes the first email in the loop correct but from the second email in the loop the body stay the same as first one and the subject gets changed correctly.
until the last email in the loop, body will stay the same as first one.

any Idea ?

**Comment by Synchro** [comment]
Please post your code, and look at the mailing list example provided.

**Comment by amirkoklan** [comment]
don't we have something like "ClearAddresses()" for the body ? cause I had problem with Addresses too and that function solved my problem

**Comment by Synchro** [comment]
Yes, it's in the example I mentioned. Look in the examples folder that's included with PHPMailer.

**Comment by amirkoklan** [comment]
foreach ($resellers as $reseller)  {
    .
    .
    .
          $content = file_get_contents($this->emailObject->getEmailTemplate() . 'supplies_order.html');
          $midContent = str_replace($placeHolder, $ticketData, $content);// Ticket data may contain Ü,Ö
          $umlaut = array('Ã¼', 'Ã¤');
          $replace = array('ü', 'ä');
          $emailBody = str_replace($umlaut, $replace, $midContent);
          $returnValue = $this->emailObject->setFromName($data['reseller_name'])
                      ->setFromEmail($fromEmail)
                      ->setBCCName($data['reseller_user_firstname'] . ' ' . $data['reseller_user_lastname'])
                      ->setBCCEmail($data['reseller_user_email'])
                      ->addContent($emailBody)
                      ->sendSMTPMail($subject, $distributorSupplyEmail, $data['supply_contact_name']);
    }

    public function sendSMTPMail($subject, $toEmail, $toName=NULL) {
        try {
            $this->mailerObject->IsSMTP();
            $this->mailerObject->SMTPAuth = true;
            $this->mailerObject->Port = $this->PORT;
            $this->mailerObject->SMTPSecure = 'tls';
            $this->mailerObject->Username = $this->USERNAME;
            $this->mailerObject->Password = $this->PASS;
            $this->mailerObject->Host = $this->HOST;

            $this->mailerObject->AddAddress($toEmail, $toName);
            $this->mailerObject->SetFrom($this->getConfig()['mailing']['sender_email'], $this->getConfig()['mailing']['sender_name']);
            $this->mailerObject->Subject = $this->getConfig()['app']['stage'].$subject;
            $value = $this->mailerObject->Send();
            $this->mailerObject->ClearAddresses();
            return ($value) ? 1 : 0;
            
        } catch (MailException $e) {
             echo $e->errorMessage();
        }
    }

     public function addContent($message, $useFile = 0) {
          if ($useFile === 1) {
              $this->mailerObject->MsgHTML(file_get_contents($message));
          } else {
              $this->mailerObject->MsgHTML($message);
          }
  
          return $this;
      }

**Comment by Synchro** [comment]
I think you need to check the return value from msgHTML, and make very sure that what you're putting into $message is correct too.

This code is pretty inefficient - you're doing lots of things that are common to all messages every time through the loop. The thing with fluent interfaces is that you need to go very heavy on exception handling since you lose out on checking return values, but there's no sign you're doing that.

That search/replace for accented chars is highly suspicious - don't you know whether your data source is correctly encoded?
