### ISSUE TITLE
Feature Request: Yahoo mail Oauth support

### ISSUE THREAD

**Issue by hayageek** [PHPMailer/PHPMailer#490]
Hi,
Can you add oAuth support for yahoo mail.

**Comment by Synchro** [comment]
Have you tried using the xoauth2 support we added for gmail? I don't know whether yahoo uses that, but if it does, there's no good reason it wouldn't work.

**Comment by Synchro** [comment]
From what I've been able to find, [Yahoo doesn't officially provide an OAuth2 service for SMTP yet](https://developer.yahoo.com/oauth2/guide/), but if I connect to their SMTP server it says this:

    250-smtp.mail.yahoo.com
    250-PIPELINING
    250-SIZE 41697280
    250-8 BITMIME
    250 AUTH PLAIN LOGIN XOAUTH2 XYMCOOKIE

which suggests it is there already, so give a try as it's likely it's compatible with Google's implementation.

**Comment by hayageek** [comment]
Hi Synchro,
I have tried Google XOAUTH. but not working.
I got the the access token & refresh token.  From the refresh token i got one more token.
I tried both tokens (1st refresh token, and 2nd refresh token). Both are not working.

 <code> php gmail_xoauth.phps
Connection: opening to smtp.gmail.com:587, timeout=300, options=array ()<br>
Connection: opened<br>
SERVER -&gt; CLIENT: 220 smtp.gmail.com ESMTP we9sm26614732pab.3 - gsmtp<br>
CLIENT -&gt; SERVER: EHLO Ravishankers-MacBook-Pro.local<br>
SERVER -&gt; CLIENT: 250-smtp.gmail.com at your service, [58.185.185.139]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8<br>
CLIENT -&gt; SERVER: STARTTLS<br>
SERVER -&gt; CLIENT: 220 2.0.0 Ready to start TLS<br>
CLIENT -&gt; SERVER: EHLO Ravishankers-MacBook-Pro.local<br>
SERVER -&gt; CLIENT: 250-smtp.gmail.com at your service, [58.185.185.139]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN XOAUTH250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8<br>
CLIENT -&gt; SERVER: AUTH XOAUTH2 dXNlcj1yYXZpQGhheWFnZWVrLmNvbQFhdXRoPUJlYXJlciB5YTI5LjhBSENJcWFfMDdRU2NBSnRMazRZS09WUjJ3a0JkU0Qtc0gxaHV6R2NzWE9yUzhDVVZqUWFycWhlTFRsQmJtakFOUEtGAQE=<br>
SERVER -&gt; CLIENT: 334 eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==<br>
SMTP ERROR: AUTH command failed: 334 eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==<br>
SMTP Error: Could not authenticate.<br>
CLIENT -&gt; SERVER: QUIT<br>
SERVER -&gt; CLIENT: 535-5.7.8 Username and Password not accepted. Learn more at535 5.7.8  https://support.google.com/mail/answer/14257 we9sm26614732pab.3 - gsmtp<br>
SMTP ERROR: QUIT command failed: 535-5.7.8 Username and Password not accepted. Learn more at535 5.7.8  https://support.google.com/mail/answer/14257 we9sm26614732pab.3 - gsmtp<br>
Connection: closed<br>
</code>

**Comment by hayageek** [comment]
i dont know the reason why it is failing, can you help me.

**Comment by Synchro** [comment]
Did you follow [the guide in the wiki](https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2)? I know I've had no trouble with that, and others have got it working too. There's also [an alternative guide](https://github.com/PHPMailer/PHPMailer/wiki/Gmail-XOAUTH2-Using-Google-API-Client) in the wiki.

**Comment by hayageek** [comment]
I followed that.  I got the refresh token. but the xAUTH failed. do you have any working sample with you. I can use it.

**Comment by Synchro** [comment]
The code bundled with PHPMailer and what's in the wiki *is* my working example. If I follow it, it works for me, so I don't know what's amiss for you.

**Comment by hayageek** [comment]
It is not working . get_auth_token.php is giving errors. Because oauth
client library is changed .
If you have time, can you please run your code once.
I got the code using composer.

**Comment by hayageek** [comment]
Please help me. I will contribute for Yahoo xAuth.

**Comment by hayageek** [comment]
Gmail is working is fine. i will check yahoo.

**Comment by ManishPatiyal** [comment]
Any update to this issue so far?

**Comment by Synchro** [comment]
Look in the 6.0 branch - it's supported in there.

**Comment by ManishPatiyal** [comment]
thanks, I want to use this in android application that requires a java version of it, I even dont have the php server and skills to run it right now so wanted to know that can it work on android device as I want to access mails of yahoo using Oauth as I am able with gmail.

**Comment by Synchro** [comment]
Uh, if you're running Java on Android, you need a Java mailing class. PHPMailer can't do anything to help you there.
