### ISSUE TITLE
PHP conditions inside the email's text

### ISSUE THREAD

**Issue by flexbrane** [PHPMailer/PHPMailer#494]
Hello,

I don't know if it's a real issue, but personally I think yes..

I use PHPMailer since few month with no problem. But now I would like to create a new function with PHP conditions inside the body of the email, but It doesn't work. 

For exemple : 
< ?php [...]
		$email="< html>
					< head >
						< meta http-equiv='Content-Type' content='text/html; charset='UTF-8' / >
					< /head >
					< body >
						< h2 >TEST< /h2 >< br/ >
						". if (1) { echo 'test'; }."
					< /body >
				< /html >";
[...] ? >

with the rest of the configuration obviously, give me that : 
--> Parse error: syntax error, unexpected 'if' (T_IF) in [...]

So, here is my question : is that possible to send messages with php conditions inside it ?

Thanks a lot

**Comment by Eternal-Infinity** [comment]
You can't use 'IF' in a string.
Either you'd have to "end" the string completely to use an IF there or you could use the ternary operator:

```
[...]
<h2>TEST</h2><br/>
".(true ? 'test' : '')."
</body >
[...]
```

This has nothing to do with PHPMailer by the way.

**Comment by Synchro** [comment]
Indeed, this is not PHPMailer's responsibility. I'd suggest using a template engine (Smarty, Twig etc) or plain PHP to template your message bodies, which is what you're doing. Whatever you do, it's done on the server side before messages are sent. There's no way to run code inside the recipient's email client.

**Comment by flexbrane** [comment]
Thank you for your both answer.
