### ISSUE TITLE
Failed to connect to server: Connection refused (61)

### ISSUE THREAD

**Issue by AbhimanyuAryan** [PHPMailer/PHPMailer#495]
I am not able to send email using PHPMailer. I am running MAMP(localhost:8888) on OSX(yosemite). I followed [this][1] tutorial to set composer globally for MAMP's version of php. 

    nano ~/.bash_profile
    alias phpmamp='/Applications/MAMP/bin/php/php5.4.34/bin/php'
    curl -sS https://getcomposer.org/installer | phpmamp
    sudo mv composer.phar /usr/local/bin/composer
    composer

Then I have created a **phpmailer** directory in **/Applications/MAMP/htdocs**

*Composer.json:* 

    {
    	"require": {
    		"phpmailer/phpmailer": "dev-master"
    	}
    }

Then in phpmailer directory i typed a command composer install. It downloaded files and I created a file index.php in phpmailer directory. 

After grabbing dependencies from git the file structure looks like this:

      phpmailer
         |
         |----composer.json 
         |----vendor(directory with various subdirectories and files) 
         |----index.php
         |----composer.lock

*Debug Logs:* 

    2015-09-12 19:03:47	Connection: opening to ssl://localhost:25, timeout=300, options=array ( ) 2015-09-12 19:03:47	SMTP ERROR: Failed to connect to server: Connection refused (61) 2015-09-12 19:03:47	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting bool(false)
    <?php
    require_once 'vendor/autoload.php';
    
*Code:* 
    
    <?php
    require_once 'vendor/autoload.php';
    
    $m = new PHPMailer;
    $m->SMTPDebug = 3;

    $m = new PHPMailer;
    $m->isSMTP();
    $m->SMTPAuth = true;
    $m->SMTPDebug = 2;
    $m->HOST = 'smtp.gmail.com';
    $m->Username = 'myemail@gmail.com';
    $m->Password = 'hidden';
    $m->SMTPSecure = 'ssl';
    $m->PORT = 465;
    $m->From = "myemail@gmail.com";
    $m->FromName = "Android Plus Ios";
    $m->addReplyTo('friend@gmail.com','Reply address');
    $m->addAddress('friend@mdurohtak.ac.in','Rakesh');
    $m->addCC('Jettu@hotmail.com', 'Jitesh');
    $m->addBCC('Fudu@outlook.com', 'Fruity');
    $m->Subject = "Please verify the account.";
    $m->Body = 'Please click here to verify the account registration';
    $m->AltBody = 'By Google';
    var_dump($m->send());
    ?>

  

<img width="598" alt="screen shot 2015-09-13 at 12 01 46 am" src="https://cloud.githubusercontent.com/assets/8083613/9833147/eb95d112-59aa-11e5-9868-30a013bf505a.png">

**Comment by Synchro** [comment]
Did you actually read your own error message?

    Connection: opening to ssl://localhost:25

That's opening a connection to localhost, not gmail. This is becasue you've changed the name of the relevant properties for no good reason:

    $m->HOST = 'smtp.gmail.com';
    $m->PORT = 465;

PHP property names are case sensitive, so you can't just change them and expect it to work. They should be:

    $m->Host = 'smtp.gmail.com';
    $m->Port = 465;


Base your code on the gmail example provided, and only change what you actually *need* to be different, so in this case use `Port = 587` and `SMTPSecure = 'tls'`.

**Comment by abhishekjain-itsme** [comment]
@Synchro It is working for me. Thanks
