### ISSUE TITLE
Fatal error: Class 'PHPMailer' not found

### ISSUE THREAD

**Issue by borsti87** [PHPMailer/PHPMailer#496]
I would like to use PHPMailer but by using the delivered examples I got the message "Fatal error: Class 'PHPMailer' not found ...". On my system is PHP 5.6.8 running.

**Comment by Synchro** [comment]
Did you upload the files as described in the readme? Are you using composer?

**Comment by borsti87** [comment]
I have downloaded the zip-file and unzip it in my test environment then I rename the mail.phps to mail.php to test it

**Comment by Synchro** [comment]
And you have the correct path to the autoloader set?

**Comment by borsti87** [comment]
autoloader is included with "require '../PHPMailerAutoload.php';" in mail php. 
mail.php is in folder examples

**Comment by Synchro** [comment]
This is the code that loads the classes:

    $filename = dirname(__FILE__).DIRECTORY_SEPARATOR.'class.'.strtolower($classname).'.php';
    if (is_readable($filename)) {
        require $filename;
    }

That suggests that the file is not readable - check permissions. If that doesn't work, stick an `echo` in there to make sure it's being run correctly.

**Comment by borsti87** [comment]
Okay that was the problem. Thanks!
