### ISSUE TITLE
send link

### ISSUE THREAD

**Issue by BgR8** [PHPMailer/PHPMailer#498]
First of all my english is not good.
while i send a reset password link to email, the (href="sifre.php") is gone if i do this with variable the email is going to spam

**Comment by Synchro** [comment]
Please post your code.

**Comment by BgR8** [comment]
Any code i didnt write just copy the codes of phpmailer to repass file and i wrote link code of html a href = "" etc. But after sending email to person who wants just a text we encounter with. The variable i said is $mtn = ' < a href = "" > Şifre < /a>

**Comment by Synchro** [comment]
You're not making much sense. It would be better if you show me your code. PHPmailer will send whatever you put into the Body property.

**Comment by BgR8** [comment]
Yes absolutely will send  what i want thanks for this script to share with us. I did anything that phpmailer indicated Absolutely body property i wrote any html code it works for examle strong but the a href is not working a href converted to < a > Sifre < / a >

**Comment by Synchro** [comment]
You need to show me the exact code you're using to set the Body property - just paste it into your reply. It sounds like you're doing something wrong with quotes.

**Comment by BgR8** [comment]
header('Content-Type: text/html; charset=utf-8');
require 'PHPMailerAutoload.php';
$phpmailer = new PHPMailer;
$phpmailer->isSMTP();
$phpmailer->Host = 'mail.atolyemde.com'; // eposta sunucusu
$phpmailer->SMTPAuth = true;
$phpmailer->Username = 'bilgi@atolyemde.com'; // epostam
$phpmailer->Password = '12345'; // şifre
$phpmailer->SMTPSecure = 'tls'; // güvenlik
$phpmailer->Port = '587'; // port
$phpmailer->From = $eposta; // gönderen
$phpmailer->FromName = $rumuz; // gönderenin adı
$phpmailer->AddReplyTo($alici, $rumuz);
$phpmailer->addAddress($eposta); // duzenlenecek
$phpmailer->isHTML(true);
$phpmailer->Subject = $konu;
$phpmailer->Body    = '<a href="sifre.php">Şifre</a>';
$phpmailer->CharSet = 'UTF-8';
if(!$phpmailer->send()) {
   echo 'E-Posta gonderilemedi. Hata: ' . $phpmailer->ErrorInfo; 
   exit; 
}

**Comment by Synchro** [comment]
Why do you have all those spaces in there? They will break the HTML.

    $phpmailer->Body = '<a href="sifre.php">Şifre</a>';

Also you should know that relative URLs will not work in email.

**Comment by BgR8** [comment]
no i do spaces for github to share with you. Without spaces i wrote. Github shows me a mistake

**Comment by Synchro** [comment]
Learn how to use code fencing in [github markdown](https://help.github.com/articles/github-flavored-markdown/).

PHPMailer does nothing to the message body other than apply any relevant transfer encodings, so it's either a mail filter or something in your client doing this. Can you show what it looks like in the source of a received message? You can see what is sent by saying `echo $mail->getSentMIMEMessage();` *after* sending, then you can compare that with what you receive.

**Comment by BgR8** [comment]
<code>require 'PHPMailerAutoload.php';

//Create a new PHPMailer instance
$mail = new PHPMailer;
//Tell PHPMailer to use SMTP
$mail->isSMTP();
//Enable SMTP debugging
// 0 = off (for production use)
// 1 = client messages
// 2 = client and server messages
$mail->SMTPDebug = 0;
//Ask for HTML-friendly debug output
$mail->Debugoutput = 'html';
//Set the hostname of the mail server
$mail->Host = "mail.atolyemde.com";
//Set the SMTP port number - likely to be 25, 465 or 587
$mail->Port = 587;
//Whether to use SMTP authentication
$mail->SMTPAuth = true;
//Username to use for SMTP authentication
$mail->Username = "bilgi@atolyemde.com";
//Password to use for SMTP authentication
$mail->Password = "12345";
//Set who the message is to be sent from
$mail->setFrom('bilgi@atolyemde.com', 'AtölyemDe');
//Set who the message is to be sent to
$mail->addAddress($eposta, 'John Doe');
//Set the subject line
$mail->Subject = 'PHPMailer SMTP test';
//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body
$mail->msgHTML(file_get_contents('contents.html'), dirname(__FILE__));
//Replace the plain text body with one created manually
$mail->AltBody = 'This is a plain-text message body';

//send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
}</code>

thank you i downloaded again and i fix this problem
