### ISSUE TITLE
class.phpmailer.php necessary change

### ISSUE THREAD

**Issue by jplevene** [PHPMailer/PHPMailer#499]
In latest version, line 1857 should be changed to (include all lines below, not substitute):

    $result .= $this->headerLine('Disposition-Notification-To', '<' . trim($this->ConfirmReadingTo) . '>');
    // Non-standard but widely used as above is sometimes ignored due to privacy
    $result .= $this->headerLine('X-Confirm-Reading-To', '<' . trim($this->ConfirmReadingTo) . '>');

**Comment by Synchro** [comment]
`Disposition-Notification-To` is from [RFC 3798](https://tools.ietf.org/html/rfc3798).

There are a several proprietary headers that try to do the same thing: `X-Confirm-Reading-To`, `Read-Receipt-To`, `Return-Receipt-To`, `Return-Receipt-Requested`, and `Generate-Delivery-Report`, but they all suffer from the same lack of take-up and privacy issues (along with web bugs/beacons), so I don't really see that they add much, and I wouldn't want to encourage the use of any of them; they're all a long way from 'necessary'. You can already implement any/all of these yourself via the existing `addCustomHeader` method.

There's [a thread on this subject in PHPMailer](https://sourceforge.net/p/phpmailer/feature-requests/37/) from 2007(!).
