### ISSUE TITLE
detailed error string when popBeforeSmtp() or send() fails

### ISSUE THREAD

**Issue by nbsbhat** [PHPMailer/PHPMailer#509]
Hi Synchro,

Could you please let me know if there is a way to fetch the detailed error string from a failed connect attempt to pop3/smtp?

From https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting, I could get to the root of the problem (using DEBUG level > 1, telnet to port 25, etc).
However, this is manual debugging. Can I log detailed error string in the application log to be able to see what is going wrong?

$mail->ErrorInfo or $e->getMessage() provides generic error:
SMTP connect() failed.

whereas the real problem was connecting to the email server due to 'smtp port being changed':
SMTP ERROR: Failed to connect to server: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Or it could also be due to other changes:
- email server policy getting updated that blocks ports when there was software update
- DNS changes or proxy updates, etc

If I get to print the detailed error message such as the above on to an application log, the level-1 application support guys will be quickly able to action on the issue.

I guess there is a way to get this detailed error; but i can't see how?

Thanks much,
Narayan

**Comment by nbsbhat** [comment]
here is the code:
<code>
    require_once PATH_LIB_PHPMAILER.'PHPMailerAutoload.php';
    require_once PATH_LIB_PHPMAILER.'class.phpmailer.php';
    require_once PATH_LIB_PHPMAILER.'class.smtp.php';
    require_once PATH_LIB_PHPMAILER.'class.pop3.php';

    class smtpMailer {
        function __construct(){       
        }
        function sendMail($args) {
            POP3::popBeforeSmtp(POP3_HOST, 110, 30, $args['pop3_user'], $args['pop3_pwd'], SMTPDEBUG);
            
            $mail = new PHPMailer(true);
            try {
                $mail->SMTPDebug = SMTPDEBUG;  // Enable verbose debug output
                $mail->isSMTP();  		// Set mailer to use SMTP
                $mail->SMTPAuth = false;// SMTP authentication; use popBeforeSmtp authentication		
                $mail->Port = 25;		// TCP port to connect to
                $mail->IsHTML(true);
                $mail->Host = SMTP_HOST;  				// Specify main and backup SMTP servers
                $mail->Username = $args['mail_user'];	// SMTP username
                $mail->Password = $args['mail_pwd']; 	// SMTP password				
    
                $mail->From = $args['from'];
                $mail->FromName = $args['from_name'];
                $mail->addAddress($args['to']);			// Name is optional
                $mail->addReplyTo($args['replyto'], $args['replyto_name']);			
                $mail->Subject = $args['subject'];
                
                $mail->Body    = $args['body'];
        
                if($mail->send()) {
                    $this->logMeToFile("Mail has been sent to ".$args['to']);
                    return true;
                }
            } 
            catch (phpmailerException $e) {
                // $this->logMeToFile(print_r($mail));
                $this->logMeToFile("Mailer Error (".$mail->Host.")[".$args['to']."]: ".$e->getMessage());
                //$this->logMeToFile("ErrorInfo:".$mail->ErrorInfo);
                return false;
            } 
            catch (Exception $e) {
                $this->logMeToFile("Mailer Exception (".$mail->Host.")[".$args['to']."]: ".$e->getMessage()); 
                return false;
            }
        }
        
        function logMeToFile($content = ""){
            file_put_contents($_SERVER['DOCUMENT_ROOT'] .URL_PREFIX ."/logs/".date("Ymd")."_wsLog.log", date("D M j G:i:s T Y") ." : " .print_r($content, true) ."\n", FILE_APPEND);
        }
    }
</code>

**Comment by Synchro** [comment]
If you set your `SMTPDEBUG` constant to `2`, you will see both client and server messages.

**Comment by Synchro** [comment]
Sorry, I didn't see you changed the post. I've just pushed a commit that provides access to the POP3 error array in 40a0a1b160d91e9950e75b3e810e8e8124663183.

Why are you loading the classes manually? The autoloader will do it for you.

**Comment by nbsbhat** [comment]
Ok, for some reason my application did not autoload; will try again

Awesome! 
- so, I can now print complete error from $errors Array to my log using $mail->getErrors() and SMTPDEBUG set to 2 ?
- whether leaving SMTPDEBUG set to 2  result in performance?

**Comment by Synchro** [comment]
No, debug output will still be displayed directly; calling getErrors will return error responses without anything being displayed. Essentially if you start getting errors, you may still need to use debug output to get the underlying reason; getErrors just returns the error response from the server, which may not include a complete transcript - give it a try if you have a good example to play with (I've not seen anyone use POP-before-SMTP for about 15 years!). You don't want debug output enabled for anything public facing.

**Comment by nbsbhat** [comment]
Took class.pop3.php changes from  40a0a1b and I got what I wanted; but popBeforeSmtp updated to be **non-static** and SMTPDEBUG set to 0


Below changes were made to get the server *errstr* onto the application log:

- In class.pop3.php (non-static popBeforeSmtp)
```
public function popBeforeSmtp(
	$host,
	$port = false,
	$timeout = false,
	$username = '',
	$password = '',
	$debug_level = 0
	) {
		return $this->authorise($host, $port, $timeout, $username, $password, $debug_level);
}
```

- Client to fetch errors using getErrors():

In my code above, the following line of code is updated accordingly
```
POP3::popBeforeSmtp(POP3_HOST, 110, 30, $args['pop3_user'], $args['pop3_pwd'], SMTPDEBUG);
```
to this,
```
$pop = new POP3; // pop3 instance to catch $errors
if(! $pop->popBeforeSmtp(POP3_HOST, 110, 30, $args['pop3_user'], $args['pop3_pwd'], SMTPDEBUG)) {
	$errors = $pop->getErrors();  // fetch pop3 $errors
	foreach ($errors as $error) {
		$this->logMeToFile("error:".($error['error']));
		$this->logMeToFile("errno:".($error['errno']));
		$this->logMeToFile("errstr:".($error['errstr']));
	}
	return false;
}	
```

now, the application log has:
```
Thu Sep 24 16:59:13 IST 2015 : error:Connecting to the POP3 server raised a PHP warning: 
Thu Sep 24 16:59:13 IST 2015 : errno:2
Thu Sep 24 16:59:13 IST 2015 : errstr:fsockopen(): unable to connect to <IP>:110 (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
)
Thu Sep 24 16:59:13 IST 2015 : error:Failed to connect to server <IP> on port 110
Thu Sep 24 16:59:13 IST 2015 : errno:10060
Thu Sep 24 16:59:13 IST 2015 : errstr:A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```
-  \<IP\> is the host address to connect to pop3 server

@Synchro , could you tell me, when will I get these updates in a release?

**Comment by Synchro** [comment]
That's a pointless change. The static function is purely for convenience - look at the code in it, and do that in your app instead - it's identical to what you suggested and requires no changes in the library:

```php
$pop = new POP3; // pop3 instance to catch $errors
if(! $pop->authorise(POP3_HOST, 110, 30, $args['pop3_user'], $args['pop3_pwd'], SMTPDEBUG)) {
    $errors = $pop->getErrors();  // fetch pop3 $errors
    foreach ($errors as $error) {
        $this->logMeToFile("error:".($error['error']));
        $this->logMeToFile("errno:".($error['errno']));
        $this->logMeToFile("errstr:".($error['errstr']));
    }
    return false;
} 
```
I don't have a plan for the next release yet.

**Comment by nbsbhat** [comment]
ah! that's correct - no change reqd in the library if my app calls $pop->authorise() directly :)

thanks.
