### ISSUE TITLE
Invalid Address Error, Output Full Email Details

### ISSUE THREAD

**Issue by waterboy550** [PHPMailer/PHPMailer#510]
I have a very complex php application that runs specific cron jobs every 10 minutes. From time to time I get the error "Invalid Address:". I'm assuming this is because there was no address assigned to the email. How do I get PhpMailer to output more than "Invalid Address:"? I would like it to output the error message, then followed by all the parameters that were sent to PhpMailer, such as subject, message, from email....

**Comment by Synchro** [comment]
You can interrogate the PHPMailer instance for all those things (nearly all properties are public). That you're getting as far as that error suggests that you're probably not checking the return values of methods like 'addAddress()`, so you're not seeing a problem until later.
