### ISSUE TITLE
Extension missing: openssl Message could not be sent.Mailer Error: Extension missing: openssl 

### ISSUE THREAD

**Issue by infinitey99** [PHPMailer/PHPMailer#511]
I have enabled the extension (and restarted the service) in the php.ini file

cURL is also installed, running and working on this server.  Is there something additional that needs to be configured?

![php](https://cloud.githubusercontent.com/assets/508538/10106296/179f82ba-6371-11e5-8c7f-354ebf3c5421.jpg)
![curl](https://cloud.githubusercontent.com/assets/508538/10106342/54200c82-6371-11e5-949c-9cb703b8a0f2.JPG)

**Comment by Synchro** [comment]
If openssl is installed you will see an openssl section in your phpinfo output, like this:

![openssl](https://cloud.githubusercontent.com/assets/81561/10106529/8c031484-63b5-11e5-93fc-a73ea40107bf.png)

Check that you've enabled it in the appropriate SAPI - it's common for CLI and apache/FPM versions of PHP to have separate configuration files. Beyond that, [refer to the PHP docs](http://php.net/manual/en/book.openssl.php).

PHPMailer doesn't use curl.

**Comment by tarak1006** [comment]
this is the error i have got
Mail error: Extension missing: openssl
i have tried this 
extension=php_openssl.dll but it doesnt work out

**Comment by Synchro** [comment]
Fine - so make sure it's actually working, as described above. This is a problem with your PHP config, not PHPMailer.

**Comment by Rombusevil** [comment]
For everyone reaching here while googling this error:
Check your PHPMailer version requirements against your installed php version.
Recent PHPMailer versions uses 'OPENSSL_ALGO_SHA256' variable to check for openssl. 
PHP versions prior to 5.4.8 don't define that variable.

**Comment by Synchro** [comment]
That constant is not used in the old 5.2 series - it uses `OPENSSL_ALGO_SHA1`, which was available from 5.0. PHPMailer 6.x and after uses `OPENSSL_ALGO_SHA256`, and also requires PHP 5.5 as a minimum.

**Comment by Lakshikasur** [comment]
I got same error even I use PHP 7.2

**Comment by Synchro** [comment]
@Lakshikasur Do you have the openssl extension installed?

**Comment by Lakshikasur** [comment]
@Synchro  Yes, I have installed and enabled from php.ini. thanks

**Comment by Synchro** [comment]
Does it actually show up in `phpinfo()` output like the above example?

**Comment by Lakshikasur** [comment]
@Synchro  Even I enabled openssl in php.ini, I was not showing as it enabled when get phpinfo();
You are correct. Thanks for your quick response.

**Comment by Cmumbi** [comment]
openssl support is enabled but I'm still getting the 'missing extension' error. Could you kindly assist? @Synchro 
![capture](https://user-images.githubusercontent.com/25196422/51625873-5c202a00-1f4f-11e9-8b16-cbf75ab42655.PNG)

**Comment by Cmumbi** [comment]
![capture1](https://user-images.githubusercontent.com/25196422/51625976-94276d00-1f4f-11e9-88d9-2f0fcae3c249.PNG)
openssl support is enabled but I'm still getting the 'missing extension' error. Could you kindly assist? @Synchro

**Comment by Synchro** [comment]
Make sure your command-line and web environments are using the same PHP instance.

**Comment by Cmumbi** [comment]
@Synchro my header version is different from the rest. How do I rectify that?

**Comment by Synchro** [comment]
Well I have no idea how your server is configured, but if it's something like Ubuntu, then compare the CLI and FPM configs, usually in `/etc/php/7.3/fpm` and `/etc/php/7.3/cli`.
