### ISSUE TITLE
Unable to load dynamic library 'c:\php4\php_openssl.dll' 

### ISSUE THREAD

**Issue by ricksherm** [PHPMailer/PHPMailer#512]
Please help!
PHP Warning: Unknown(): Unable to load dynamic library 'c:\php4\php_openssl.dll' - The specified module could not be found. in Unknown on line 0 PHP Fatal error: Call to undefined function: date_default_timezone_set() in e:\websites\1414\escortsdosdonts.com\example.php on line 2

http://www.escortsdosdonts.com/example.php
http://www.escortsdosdonts.com/phpinfo.php
http://www.escortsdosdonts.com/php.ini

<?php
date_default_timezone_set('America/Chicago');

function date_system_timezone_set(){ 
  $shell = new COM("WScript.Shell") or die("Requires Windows Scripting Host"); 
  $time_bias = -($shell->RegRead( 
"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\TimeZoneInformation\\Bias"))/60; 
  $ab = -($shell->RegRead( 
"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\TimeZoneInformation\\ActiveTimeBias"))/60; 
  $sc = $shell->RegRead( 
"HKEY_USERS\\.DEFAULT\\Control Panel\\International\\sCountry"); 
  foreach(timezone_abbreviations_list() as $tza) foreach($tza as $entry){ 
    $country = strtok($entry['timezone_id'],'/'); 
    $locale = strtok('|'); 
    if($country==$sc && $ab==($entry['offset']/60/60) && ($ds = $time_bias!=$ab)==$entry['dst']){ 
      date_default_timezone_set($timezone_identifier = $country."/".$locale); 
      return sprintf('%.1f',$ab)."/".($ds?'':'no ').'DST'." ".$timezone_identifier; 
     } 
   } 
  return false; 
} 

require  'phpmailer/PHPMailerAutoload.php';     // for http://www.escortsdosdonts.com/

//  require  'phpmailer\PHPMailerAutoload.php';    // for localhost
          

$mail = new PHPMailer;

$mail->SMTPDebug = 3;                               // Enable verbose debug output

$mail->isSMTP();                                      // Set mailer to use SMTP

$mail->CharSet="iso-8859-1";
$mail->Host = 'smtp.escortsdosdonts.com';                      // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'ricksherman';                    // SMTP username
$mail->Password = 'mypassword';                           // SMTP password
$mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 587;                                    // TCP port to connect to

$mail->From = 'from@example.com';
$mail->FromName = 'Mailer';
$mail->addAddress('ricksherman@netins.net');     // Add a recipient
$mail->addReplyTo('info@example.com');
$mail->addCC('cc@example.com');
$mail->addBCC('bcc@example.com');

// $mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
// $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name
$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'Here is the subject';
$mail->Body    = 'This is the HTML message body <b>in bold!</b>';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

if(!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message has been sent';
}
?>

**Comment by drmad** [comment]
Sorry for this, but PHP4 on Windows! Wow, so retro :smile:

**Comment by Synchro** [comment]
Even if you figure out how to enable the openssl extension (hint, look in the PHP docs), this isn't going to work. We don't support PHPMailer on PHP4, and have not done so since 2009. The last version that works on PHP4 is 2.3, which you can find in the releases section, but bear in mind that it is very old. You'll probably find it less hassle (and get a load of security improvements into the bargain) to upgrade to a half decent hosting config.

**Comment by ricksherm** [comment]
My host upgraded to PHP Version 5.5.38 and I have removed www.escortsdosdonts.com/php.ini. Thank you for your comments, this issue is now closed.
