### ISSUE TITLE
Variable Annotations

### ISSUE THREAD

**Issue by dnepro** [PHPMailer/PHPMailer#513]
The annotation of variables is throughout by setting a "@ type". Is there any reason why "@ var" is not used instead? As i've never seen this "@ type" annotation and couldn't find it on phpdoc.org.

The reason why i ask is because i want to implement PHPMailer into a TYPO3 FLOW application and get a warning that this annotation is unknown and as i am very lazy about rewriting the reflection service and curious about this question :)   i want to ask whether it is possible to replace them all with "@ var"?
Thanks in advance - Dnepro

PS: of course there is no space between the "@" and "type" or "var", this is simply because of github's  markdown syntax.

**Comment by Synchro** [comment]
This is annoying. In 2013, PHPdoc deprecated `@var` in favour of `@type`, and the PHP FIG [PSR-5 coding standard](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md) proposal did the same, so I went with that, and several other projects did the same, such as Drupal! In 2014 *both* [reverted their change](https://github.com/phpDocumentor/fig-standards/pull/55), but I didn't see that. I guess we should follow suit if you'd care to do a PR. It's unhelpful that PHPDoc's documentation has [removed all references to `@type`](https://github.com/phpDocumentor/phpDocumentor2/issues/1125).

**Comment by dnepro** [comment]
Yes, thats true they really could leave the reference on that and mark as "under development" or "please use var instead" but ok i will prepare a PR for that. Thanks for the fast answer!

**Comment by dnepro** [comment]
Sorry, don't know how it happened, that i opened two PR's but here they are :)

**Comment by dnepro** [comment]
Thanks @Synchro !
