### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by kapilbhardwajj** [PHPMailer/PHPMailer#518]
Hi i use your good PHPMailer but it's not working. I unable to send mails through using it.  Can you please help my.

I use it in this page:- http://www.datapackers.in/contact-us.html

**Comment by Synchro** [comment]
Before I can help you, you need to post your code, read the docs, base your code on one of the examples provided.

**Comment by kapilbhardwajj** [comment]
I little update this:- 

if ($resp != null && $resp->success) {
	
	if(!empty($m_name) && !empty($m_email) && !empty($m_contact) && !empty($m_message))	{
		
		if (preg_match('/^[\w-]+(\.[\w-]+)*@([0-9a-z][0-9a-z-]*[0-9a-z]\.)+([a-z]{2,4})$/i', $m_email )) {	
						
		
			require("class.phpmailer.php");
			
			$mail             = new PHPMailer();
		
			$mail->IsSMTP(); // telling the class to use SMTP
			$mail->Host       = "sg2plcpnl0031.prod.sin2.secureserver.net"; // SMTP server
			$mail->SMTPAuth   = true;                  // enable SMTP authentication
			$mail->Host       = "sg2plcpnl0031.prod.sin2.secureserver.net"; // sets the SMTP server
			$mail->Port       = 25;                    // set the SMTP port for the GMAIL server
			$mail->Username   = "contact@datapackers.in"; // SMTP account username
			$mail->Password   = "Deepak14!#";        // SMTP account password
			$mail->SMTPSecure = 'tls';               // Enable TLS encryption, `ssl` also accepted
			
			$mail->From = "contact@datapackers.in";
			$mail->FromName = "DataPackers";
						
			$mail->AddReplyTo($m_email,$m_name);
			
			$mail->AddAddress("contact@datapackers.in", "Data Packers");
			
			$mail->Subject    = "Data Packers";
						
			$body =	    "Name : ". $m_name ."\r\n\n" .
						"Email : ". $m_email ."\r\n\n" .
						"Contact No. : ". $m_contact ."\r\n\n" .
						"Message : ". $m_message ."\r\n\n".
						"Page : ". $m_page ."\r\n\n";
			
			$mail->Body = $body;

i only update this details.. And all other are same.

**Comment by Synchro** [comment]
The code looks ok, but you're using an old version of PHPMailer and have based your code on an obsolete example, so please update. Please [read the docs](https://github.com/PHPMailer/PHPMailer/wiki).

**Comment by kapilbhardwajj** [comment]
Ok Synchro. i read it and update with your latest code.. I update you shortly :)

**Comment by kapilbhardwajj** [comment]
One more thing. I mention in my HTML page:- 

<form id="formail" action="" method="post" class="padding-btm-20">

id="formail" is correct?? or i need to change it..

**Comment by Synchro** [comment]
PHPMailer doesn't care about your HTML, so it makes no difference.

**Comment by kapilbhardwajj** [comment]
ok.. i try to add you update PHPMailer :100:
