### ISSUE TITLE
scrutinizer-ci build failing

### ISSUE THREAD

**Issue by samayo** [PHPMailer/PHPMailer#519]
I just wanted to know if this is intentional or not, because [scrutinizer-ci build](https://scrutinizer-ci.com/g/PHPMailer/PHPMailer/) status shows, tests are failing. I know tests fail sometimes, but not sure if you have abandoned scrutinizer and switched to another ci

**Comment by Synchro** [comment]
It's not intentional - scrutinizer is just a bit unreliable. Scrutinizer is not a CI in that it does not run the test suite; it runs things like phpmd and other code checkers. To be fair, it is usually because packagist fails to respond rather than anything scrutinizer is doing.
