### ISSUE TITLE
TLS error message not printed correctly

### ISSUE THREAD

**Issue by b4dw01f87** [PHPMailer/PHPMailer#521]
In class.phpmailer.php when $this->smtp->StartTLS()) fails, a new phpmailerException($this->Lang('tls')) gets thrown. Only since there isn't a key value pair for 'tls' in the array below, "Language string failed to load: tls" is printed. Please add the key value pair for 'tls' to this array.

    $PHPMAILER_LANG = array(
      'provide_address' => 'You must provide at least one recipient email address.',
      'mailer_not_supported' => ' mailer is not supported.',
      'execute' => 'Could not execute: ',
      'instantiate' => 'Could not instantiate mail function.',
      'authenticate' => 'SMTP Error: Could not authenticate.',
      'from_failed' => 'The following From address failed: ',
      'recipients_failed' => 'SMTP Error: The following recipients failed: ',
      'data_not_accepted' => 'SMTP Error: Data not accepted.',
      'connect_host' => 'SMTP Error: Could not connect to SMTP host.',
      'file_access' => 'Could not access file: ',
      'file_open' => 'File Error: Could not open file: ',
      'encoding' => 'Unknown encoding: ',
      'signing' => 'Signing Error: ',
      'smtp_error' => 'SMTP server error: ',
      'empty_message' => 'Message body empty',
      'invalid_address' => 'Invalid address',
      'variable_set' => 'Cannot set or reset variable: '
    );

**Comment by Synchro** [comment]
Please update your code before reporting bugs. This was fixed many years ago.
