### ISSUE TITLE
PHPMailer not working with Ubuntu14.04

### ISSUE THREAD

**Issue by schuesslerf** [PHPMailer/PHPMailer#523]
I try to use PHPMailer to send a mail, but my webserver seems to be not configured for that (normal mail command of php doesn't work either). So what do I have to change, so PHPMailer works? Do I have to install something or just change some settings? (postfix installed, but not working....)

**Comment by Synchro** [comment]
This isn't really the place to ask - you need to read some PHP and postfix docs, check what your system is doing. If you're not up to doing system admin yourself, get a host with a control panel to simplify it for you.
