### ISSUE TITLE
SMTP -> ERROR: Failed to connect to server: Connection timed out (110)

### ISSUE THREAD

**Issue by luohaha** [PHPMailer/PHPMailer#524]
The SMTP debugging output is shown below:
SMTP -> ERROR: Failed to connect to server: Connection timed out (110)

I don't know which situation can lead to this error?

**Comment by Synchro** [comment]
Like the error says, it's becasue the connection timed out! This usually means your network is having trouble, your ISP is blocking outbound SMTP, your DNS is not working. All are covered in the docs.
