### ISSUE TITLE
Error : The following recipients failed: XXXXXX

### ISSUE THREAD

**Issue by carbos10** [PHPMailer/PHPMailer#533]
I have this error:
`Mailer Error: SMTP Error: The following recipients failed: XXXXXXXX: : Client host rejected: Para envio de mensagens e necessaria autenticacao. Para saber como corrigir este erro acesse: http://wiki.locaweb.com/pt-br/Email_Locaweb_-_Envio_Autenticado /This mail server requires authentication`
and with `$mail->SMTPDebug = 3;`
i have this error:
`2015-10-18 15:09:29        Connection: opening to smtpXXXX.com:587, timeout=300, options=array ( ) 2015-10-18 15:09:29        Connection: opened 2015-10-18 15:09:29        SERVER -> CLIENT: 220 bart0183.correio.pw ESMTP Postfix (Debian/GNU) 2015-10-18 15:09:29        CLIENT -> SERVER: EHLO XXXX.com 2015-10-18 15:09:29        SERVER -> CLIENT: 250-bart0183.correio.pw 250-PIPELINING 250-SIZE 50000000 250-VRFY 250-ETRN 250-STARTTLS 250-AUTH PLAIN LOGIN 250-ENHANCEDSTATUSCODES 250-8BITMIME 250 DSN 2015-10-18 15:09:29        CLIENT -> SERVER: STARTTLS 2015-10-18 15:09:29        SERVER -> CLIENT: 220 2.0.0 Ready to start TLS 2015-10-18 15:09:30        CLIENT -> SERVER: EHLO tresma.com.br 2015-10-18 15:09:30        SERVER -> CLIENT: 250-bart0183.correio.pw 250-PIPELINING 250-SIZE 50000000 250-VRFY 250-ETRN 250-AUTH PLAIN LOGIN 250-ENHANCEDSTATUSCODES 250-8BITMIME 250 DSN 2015-10-18 15:09:30 CLIENT -> SERVER: MAIL FROM: 2015-10-18 15:09:30        SERVER -> CLIENT: 250 2.1.0 Ok 2015-10-18 15:09:30        CLIENT -> SERVER: RCPT TO: 2015-10-18 15:09:30        SERVER -> CLIENT: 503 5.0.3 : Client host rejected: Para envio de mensagens e necessaria autenticacao. Para saber como corrigir este erro acesse: http://wiki.locaweb.com/pt-br/Email_Locaweb_-_Envio_Autenticado /This mail server requires authentication 2015-10-18 15:09:30        SMTP ERROR: RCPT TO command failed: 503 5.0.3 : Client host rejected: Para envio de mensagens e necessaria autenticacao. Para saber como corrigir este erro acesse: http://wiki.locaweb.com/pt-br/Email_Locaweb_-_Envio_Autenticado /This mail server requires authentication 2015-10-18 15:09:30        CLIENT -> SERVER: QUIT 2015-10-18 15:09:30        SERVER -> CLIENT: 221 2.0.0 Bye 2015-10-18 15:09:30        Connection: closed 2015-10-18 15:09:30        SMTP Error: The following recipients failed: XXXXXXXX: : Client host rejected: Para envio de mensagens e necessaria autenticacao. Para saber como corrigir este erro acesse: http://wiki.locaweb.com/pt-br/Email_Locaweb_-_Envio_Autenticado /This mail server requires authentication` 
i have searched on google and i've found this:
http://stackoverflow.com/questions/8463567/php-mailer-error-smtp-error
i have tried set Host "localhost" and set: `$mail->SMTPAuth = false;`
but now i have this error:
`Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting`

**Comment by Synchro** [comment]
> This mail server requires authentication

There's no ambiguity there. The mail server requires you to authenticate, you've decided not to, so it's not accepting mail from you.
