### ISSUE TITLE
I can't get the google code for sending e-mails! HELP!

### ISSUE THREAD

**Issue by SAMXPS** [PHPMailer/PHPMailer#537]
Fatal error: Class 'League\OAuth2\Client\Provider\Google' not found in PHPMailer\get_oauth_token.php on line 29
Call Stack
#	Time	Memory	Function	Location
1	0.0000	248536	{main}( )	..\get_oauth_token.php:0

**Comment by Synchro** [comment]
Read the docs about how to configure composer, then install the league dependencies in the 'suggests' section of the composer.json file
