### ISSUE TITLE
PHPMailer get_oauth_token referencing protected values from oauth2-client and oauth2-google.

### ISSUE THREAD

**Issue by quindo** [PHPMailer/PHPMailer#539]
I have used the following composer settings.

        "phpmailer/phpmailer": "^5.2",
        "league/oauth2-client": "^1.0",
	"league/oauth2-google": "^1.0"

Currently get_oauth_token.php is referencing several functions and variables that have been changed to protected.  This results in Fatal errors when you attempt to get your oauthRefreshToken for gmail xoauth.

I am attempting to determine if I can update get_oauth_token.php to be compatible with the 1.0 versions of oauth2.

I apologize if I am making a mistake by posting this.  I am not experienced with contributing to open source projects.

**Comment by Synchro** [comment]
No mistake, this is a good bug report! It might have been slightly more helpful if you'd listed the things that were wrong, but it wasn't too hard to find them.

There are three references that need fixing. I've fixed `state` with `getState()` and `refreshToken` with `getRefreshToken()`, but I can't see a way of setting `accessType` - they have changed it to protected without providing a way of setting it that I can find, so I think this is a bug in their library.

**Comment by Synchro** [comment]
I reported it [in their issue tracker](https://github.com/thephpleague/oauth2-google/issues/18).

**Comment by quindo** [comment]
Sorry.  When writing the original post I was not confident that I had found all the problem lines.

I currently attempting to run the script with that line commented out.  I am able to get a refresh token.  Everything appears to be working until I attempt to run a gmail_xoauth.php test email.  I get the following output.

```
SERVER -> CLIENT: 250-go.example.com Hello www.example.com [107.6.149.106]250-SIZE 52428800250-8BITMIME250-PIPELINING250-AUTH PLAIN LOGIN250 HELP
Auth method requested: XOAUTH2
Auth methods available on the server: PLAIN,LOGIN
SMTP Error: Could not authenticate.
CLIENT -> SERVER: QUIT
```

I am not sure if this is related to the commenting out of the accessType or if there is something wrong with my setup.

Looking into the code the construct allows us to set accessType, but there does not seem to be generic get/set available post construction in oauth2-client or oauth2-google.  What in the If else statement causes accessType to become unset?

**Comment by Synchro** [comment]
There used to be simple get/set options for accessType in the oauth2-google class. It was added in [this commit](https://github.com/thephpleague/oauth2-google/commit/c7334f8f544fa8148e6648298baf0a1500aca980), but it seems to have disappeared since. I can't find where that happened in their commit history, but it's certainly not there now.

**Comment by SDKiller** [comment]
@Synchro 

https://github.com/thephpleague/oauth2-google/commit/e190d0b3c1a3c24e43e05ce40ab20b4420cf706e#diff-44f351f030488e63152615e12d7ac64cL41

**Comment by Synchro** [comment]
I see what you mean about the constructor. accessType is not actually used anywhere else, so removing that line seems reasonable.

It's odd that it's not listing XOAUTH2 in the EHLO response. Is that before or after STARTTLS?

Thanks for spotting that change @SDKiller. It seems strange to remove access when the property remains. I don't know what it does, but the PHPMailer script sets it in the constructor anyway and never accesses it again, so I think that line can be removed safely.

**Comment by SDKiller** [comment]
BTW, they still kept instructions of setting the `accessType` in readme

https://github.com/thephpleague/oauth2-google/blob/master/README.md#refreshing-a-token

I guess it was removed accidentally in that fat commit.

**Comment by quindo** [comment]
It is happening after STARTTLS.

http://pastebin.com/U7HTxAez

There is a pastebin of the full debugging output.  I am going through the link below again to make sure I did not miss a step somewhere.

https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2

**Comment by Synchro** [comment]
I've spotted your problem. You are being redirected to another server - look at the response to your connection:

    220-go.example.com ESMTP Exim 4.86

Even without your altered domain name, google does not run exim, and this also explains why the auth options don't match. You need to have words with you ISP.

**Comment by Synchro** [comment]
@quindo, you posted a comment on #543 that I think was meant to be on this one.

Really, you're not connecting to a gmail server - it looks like you're connecting to localhost if you're running exim. Figure out why.

**Comment by quindo** [comment]
I found part of the problem.

I get 2 completely different outputs depending on if I run the script through the command line verses if I hit the script via a web.  It is giving me a "Username and Password not accepted." error.

This is probably just my inexperience not knowing that running via cron/command line and a web request would result in 2 different outputs.

**Comment by Synchro** [comment]
Yes, it's common for different PHP SAPIs (Apache, FPM, CLI, CGI etc) to have different configs, but if you're using `isSMTP` in PHPMailer, the config shouldn't make much difference since all the conversation happens via PHPMailer code. You may find it's something odd like your DNS setup.

**Comment by Luisinho77** [comment]
Dear friend! 

We've finnaly got home and wanted to share some cool pics of our journey, just take a look <http://refer.telecomguru.org/e4xdbhn>

ljlorente
