### ISSUE TITLE
Fix issues from Google Code

### ISSUE THREAD

**Issue by Synchro** [PHPMailer/PHPMailer#54]
Migrate/fix/close issues from [the Google Code repo](https://code.google.com/a/apache-extras.org/p/phpmailer/issues/list).

**Comment by PunchyRascal** [comment]
Apparently google code offers some kind of automatic import of issues to github:

https://code.google.com/p/support-tools/wiki/IssueExporterTool

**Comment by Synchro** [comment]
There are many obsolete and duplicate issues in there and I have no admin control over them, plus the gc repo has been dead for a couple of years, so I'm really not bothered. Anything important can be recreated manually.
