### ISSUE TITLE
Maximum execution time of 0 seconds exceeded

### ISSUE THREAD

**Issue by resident-uhlig** [PHPMailer/PHPMailer#541]
Sending our newsletter to 12713 recipients always fails after a little over 11k recipients.

```log
[10-Jun-2015 14:19:18 UTC] PHP Fatal error:  Maximum execution time of 0 seconds exceeded in /var/www/PHPMailer/class.smtp.php on line 526
[10-Jun-2015 14:31:33 UTC] PHP Fatal error:  Maximum execution time of 0 seconds exceeded in /var/www/PHPMailer/class.smtp.php on line 553
[10-Jun-2015 14:43:50 UTC] PHP Fatal error:  Maximum execution time of 0 seconds exceeded in /var/www/PHPMailer/class.smtp.php on line 521
[09-Jul-2015 08:34:57 UTC] PHP Fatal error:  Maximum execution time of 0 seconds exceeded in /var/www/PHPMailer/class.smtp.php on line 556
[02-Sep-2015 07:14:31 UTC] PHP Fatal error:  Maximum execution time of 0 seconds exceeded in /var/www/PHPMailer/class.smtp.php on line 556
[26-Oct-2015 07:07:37 UTC] PHP Fatal error:  Maximum execution time of 0 seconds exceeded in /var/www/PHPMailer/class.smtp.php on line 506
```

I wouldn't bother you if it happened outside of that file. But as you can see the error always happens inside of class.smtp.php of PHPMailer.

I noticed that all those lines belong to the method `SMTP::data($msg_data)`.

Before PHPMailer calls `$this->smtp->data($header . $body)` it calls `$this->smtp->connect(...)`. Inside of that function `SMTP::connect(...)` there is [some kind of timeout handling](https://github.com/PHPMailer/PHPMailer/blob/master/class.smtp.php#L316). Maybe this is the reason for the PHP error. Do you think the same and can you think of a solution?

In our sending script we do `set_time_limit(0)` before creating the PHPMailer instance. We use one instance of PHPMailer only. However we clear and reset the recipient for each e-mail address.

e.g. (pseudo code)
```php
$mail = new PHPMailer();
// ... (setting hostname, smtp, from etc.)
foreach($recipients as $addr) {
  $mail->ClearAddresses();
  $mail->AddAddress($addr);
  $mail->Send();
  // ... logging result of Send() to a plain text file
  $mail->ClearAddresses();
}
```

PHP: 5.6.14
PHPMailer: 5.2.8 (I doubt that upgrading would help in this case)
OS: RHEL

**Comment by ooxi** [comment]
Maybe another timeout is reached, for example [`max_input_time`](http://stackoverflow.com/a/12210950/2534648)?

**Comment by Synchro** [comment]
It's nothing particular about the SMTP code - it's just that when you're sending a large volume, that's where it spends most of the time, so if it's going to break, its most likely to be somewhere there.

I think timeout handling changed in 5.2.9, so upgrading might help, and you should anyway.

For a template of how to send efficiently, look at the mailing list example in the examples folder.

That you're hitting a max execution time tells me that you're not running from a CLI script, which has no max execution time limit by default. For sending volume like this, you really don't want to be doing it on a web page load. I suspect that max_input_time does not apply to CLI scripts.

**Comment by resident-uhlig** [comment]
[The documentation for max_input_time](http://php.net/manual/en/info.configuration.php#ini.max-input-time) says:
> max_input_time integer
> This sets the maximum time in seconds a script is allowed to parse input data, like POST and GET. **Timing** begins at the moment PHP is invoked at the server and **ends when execution begins**. [emphasis by me]

As you can see in the error log, the error happens a while after the execution began somewhere inside class.smtp.php. So I doubt this setting is the reason.

However we will give it a try - next month ...

**Comment by resident-uhlig** [comment]
@Synchro 
> I think timeout handling changed in 5.2.9, so upgrading might help, and you should anyway.

After a [quick comparison](https://github.com/PHPMailer/PHPMailer/compare/d3802c597bff8f6c2ccfa3eab2a511aa01b8d68f...master#diff-ac5c95a7c256b389656048bd46dc2985L244) of the current and the 5.2.8 class.smtp.php the code around set_time_limit() looks very similar to me.

> For a template of how to send efficiently, look at the mailing list example in the examples folder.

Is [this](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps) the example? I think that's about the way we do it already.

And you are right, it is not CLI but a web page. The reason was that a user should be able to trigger the sending on a web page. Yes, there are ways to do it as CLI anyway and maybe we will change to a CLI after all.

I still think this error should not occur with the current code and setup.

**Comment by Synchro** [comment]
Yes, that's the example. The key things are setting up outside the loop, using keepalive, clearing addresses once at the end of the loop.

I would strongly recommend switching to a CLI script - this is not the kind of process that needs to involve a browser at all. That doesn't mean that you can't trigger it from a web page, just that the send instruction and actual sending should be decoupled.

**Comment by Synchro** [comment]
It's mainly that timeout values in SMTP changed to match RFC recommendations.

**Comment by resident-uhlig** [comment]
As you say it is not the SMTP code: Do you think the PHP bug tracker is a better place for this issue?

**Comment by Synchro** [comment]
I don't think I'd count it as a bug. You're trying to run something that should be a local, long-running process as a web page response, which is inherently not matched to that approach. I think if you reported this on the PHP bug tracker, they would just say "you're doing it wrong".
