### ISSUE TITLE
Fatal error: Class 'PHPMailer' not found

### ISSUE THREAD

**Issue by Concept211** [PHPMailer/PHPMailer#544]
I'm currently using PHPMailer v5.2.13 running PHP v5.3.27 on IIS. 

I made a simple contact form which would submit and process the basic PHPMailer example using SMTP authentication. Nearly every time, on the first submission, I would get the error `Fatal error: Class 'PHPMailer' not found` on the line number where I called `new PHPMailer()`. It didn't make any sense why it would only find the class file on the second submission. I was finally able to get it to work reliably by bypassing the autoload script/file and loading the necessary classes manually/directly:

```php
require_once('libraries/phpmailer/class.phpmailer.php');
require_once('libraries/phpmailer/class.smtp.php');
````

So it seems to me that there's an issue with the autoload script. Any ideas as to why this is happening?

**Comment by Synchro** [comment]
I've not seen anything like that. I suggest you stick a breakpoint in the autoloader and see why it's failing to issue its own `require`. The only thing that might apply is the `is_readable` call in the autoloader - I recall someone having difficulty with that on some remote file systems.
