### ISSUE TITLE
serverHostname() issue, line 3171 on class.phpmailer.php

### ISSUE THREAD

**Issue by IGLOU-EU** [PHPMailer/PHPMailer#547]
Hi,

`$_SERVER['SERVER_NAME']`, must return `Server_Name XXX` provided by the server. But by default apache allows to return the Host Header ... `UseCanonicalName Off`

Apache escaped all HTML host value for `$_SERVER['SERVER_NAME']`, no probleme for XSS, but undesirable and dangerous for sql injections.

**Comment by Synchro** [comment]
PHPMailer has nothing to do with either SQL or anything in a browser - they are separate problems that you should deal with appropriately in their own contexts. SQL injection and XSS are not issues that affect email (though it has its own issues, such as header injection). It's quite likely that if that function returns something that is not a usable hostname, then you will not be able to send email, which you would fix by setting one.
