### ISSUE TITLE
BCCs Only

### ISSUE THREAD

**Issue by kenITR** [PHPMailer/PHPMailer#558]
Hello,

I have read thru several threads here on sending only to BBC addresses and not including a To address.

None of the solutions offered allow me to send an email without an To address (not "undisclosed-recipients:;", not using an empty string, not using NULL, and not removing the AddAddress line). 

The error is always: Could not execute: /usr/sbin/sendmail -t -i 

My commercial email accounts allow me to do this, but not PHPMailer. I am using somewhat older versions of CENTOS (5) and PHP (5.3.19) could those be issues?

Thanks.

**Comment by Synchro** [comment]
Have you tried setting the `Sender` property but leaving the to addresses empty?

Email does not require a To header, but it does require an envelope to.

I don't see that using a commercial service would make any difference - this error can only come from your own local mail server; any commercial service would by definition be remote and thus not callable from sendmail.

Using old versions of PHP is a very bad idea, especially one that is so long out of security updates.

**Comment by kenITR** [comment]
Hi Marcus,

Thanks for the reply.

Yes, I have the Sender property set.

What I meant by commercial services is that if I use Thunderbird and 
send email through an ISP I can leave the To header blank and send to 
BCC.  But when I send directly from my Linux server using PHPMailer I 
cannot do that.

I know, I know, about older versions. Same with my older MySQL. The 
problem is I have to update CentOS and this application will be a 
monster to migrate to a new OS.

Any idea why a empty or non-existent AddAddress with PHPMailer would 
cause sendmail to fail.

Ken

On 11/15/2015 12:54 PM, Marcus Bointon wrote:
>
> Have you tried setting the |Sender| property but leaving the to 
> addresses empty?
>
> Email does not require a To header, but it does require an envelope to.
>
> I don't see that using a commercial service would make any difference 
> - this error can only come from your own local mail server; any 
> commercial service would by definition be remote and thus not callable 
> from sendmail.
>
> Using old versions of PHP is a very bad idea, especially one that is 
> so long out of security updates.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PHPMailer/PHPMailer/issues/558#issuecomment-156838386>.
>


-- 
Ken Loomis
IT Resources
1646 Massachusetts Ave
Lexington, MA 02420

**Comment by Synchro** [comment]
When you are sending via SMTP you have the option to set the to headers and envelope to addresses separately, and that is what thunderbird is doing. Sendmail doesn't make it so easy, but the workaround is simple - don't use sendmail or mail(); use SMTP to localhost. You'll probably get better performance that way too.

**Comment by kenITR** [comment]
Are there prerequisites for this or do I just use the PHPMailer IsSMTP 
with my current configuration?

On 11/15/2015 06:06 PM, Marcus Bointon wrote:
>
> When you are sending via SMTP you have the option to set the to 
> headers and envelope to addresses separately, and that is what 
> thunderbird is doing. Sendmail doesn't make it so easy, but the 
> workaround is simple - don't use sendmail or mail(); use SMTP to 
> localhost. You'll probably get better performance that way too.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PHPMailer/PHPMailer/issues/558#issuecomment-156867646>.
>


-- 
Ken Loomis
IT Resources
1646 Massachusetts Ave
Lexington, MA 02420

**Comment by Synchro** [comment]
Yes, just use:
 ```php
$mail->isSMTP();
$mail->Host = 'localhost';
```

When using SMTP it's also much easier to see what's going on because you can set `SMTPDebug = 2` and see the whole conversation.

**Comment by Synchro** [comment]
All this said, you're probably best off not trying to do this - while it's permitted by RFCs, some ISPs and spam filters don't like it - you're better off setting your own address in To and BCCing everyone else.

**Comment by kenITR** [comment]
OK, Thanks.
