### ISSUE TITLE
MsgHTML() and IsHTML() + Body fail silently without enclosing HTML and BODY tags

### ISSUE THREAD

**Issue by jnday** [PHPMailer/PHPMailer#56]
Hi folks,

I've noticed that both  

$mail->MsgHTML($body);

and 

$mail->IsHTML(true);
$mail->Body = $body;

will fail to send an email without throwing an error if $body does not begin and end with the appropriate HTML and BODY tags.  I'm not sure if this is a bug or if it should be a requested feature (or if I should just format my HTML emails appropriately), but I've seen a few people trying to figure out what's going on, so I thought I'd throw it out there.

Thanks!

**Comment by FabriceDelahaij** [comment]
Try out
	$replace = array(
		'({subject})' => $subject,
		'({message})' => nl2br(stripslashes($message))
	);
	$message = preg_replace(array_keys($replace), array_values($replace), file_get_contents(DOCROOT.'/include/email-temple.php'));

	$plaintext = $bericht;
	$plaintext = strip_tags(stripslashes($plaintext), '<p><br><h2><h3><h1><h4>');
	$plaintext = str_replace(array('<p>', '<br />', '<br>', '<h1>', '<h2>', '<h3>', '<h4>'), PHP_EOL, $plaintext);
	$plaintext = str_replace(array('</p>', '</h1>', '</h2>', '</h3>', '</h4>' ), '', $plaintext);
	$plaintext = html_entity_decode(stripslashes($plaintext));
	$mail->MsgHTML(stripslashes($message));
	$mail->AltBody .= $plaintext;

**Comment by Synchro** [comment]
One thing worth noting - even with exceptions enabled, PHPMailer doesn't use exceptions for everything - you should still check return values. Instead of:

    $mail->send();

you should still do:

```php
if (!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message has been sent';
}
```

Or some equivalent thereof.
