### ISSUE TITLE
Can not send mail from google smtp.. 

### ISSUE THREAD

**Issue by dlhenke** [PHPMailer/PHPMailer#561]
I'm using latest phpmailer.. 
can you please help me.. 

Connection: opening to smtp.gmail.com:587, timeout=300, options=array ()
Connection: opened
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "220 smtp.gmail.com ESMTP i201sm36810815ywe.10 - gsmtp"
SERVER -> CLIENT: 220 smtp.gmail.com ESMTP i201sm36810815ywe.10 - gsmtp
CLIENT -> SERVER: EHLO ws.arin.com.br
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "250-smtp.gmail.com at your service, [67.205.67.207]"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [67.205.67.207]"
SMTP -> get_lines(): $str is "250-SIZE 35882577"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [67.205.67.207]250-SIZE 35882577"
SMTP -> get_lines(): $str is "250-8BITMIME"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [67.205.67.207]250-SIZE 35882577250-8BITMIME"
SMTP -> get_lines(): $str is "250-STARTTLS"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [67.205.67.207]250-SIZE 35882577250-8BITMIME250-STARTTLS"
SMTP -> get_lines(): $str is "250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [67.205.67.207]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $str is "250-PIPELINING"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [67.205.67.207]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING"
SMTP -> get_lines(): $str is "250-CHUNKING"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [67.205.67.207]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING"
SMTP -> get_lines(): $str is "250 SMTPUTF8"
SERVER -> CLIENT: 250-smtp.gmail.com at your service, [67.205.67.207]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: STARTTLS
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "220 2.0.0 Ready to start TLS"
SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
CLIENT -> SERVER: EHLO ws.arin.com.br
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "250-smtp.gmail.com at your service, [67.205.67.207]"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [67.205.67.207]"
SMTP -> get_lines(): $str is "250-SIZE 35882577"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [67.205.67.207]250-SIZE 35882577"
SMTP -> get_lines(): $str is "250-8BITMIME"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [67.205.67.207]250-SIZE 35882577250-8BITMIME"
SMTP -> get_lines(): $str is "250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [67.205.67.207]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH"
SMTP -> get_lines(): $str is "250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [67.205.67.207]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH250-ENHANCEDSTATUSCODES"
SMTP -> get_lines(): $str is "250-PIPELINING"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [67.205.67.207]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH250-ENHANCEDSTATUSCODES250-PIPELINING"
SMTP -> get_lines(): $str is "250-CHUNKING"
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [67.205.67.207]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING"
SMTP -> get_lines(): $str is "250 SMTPUTF8"
SERVER -> CLIENT: 250-smtp.gmail.com at your service, [67.205.67.207]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
Auth method requested: XOAUTH
Auth methods available on the server: LOGIN,PLAIN,XOAUTH2,PLAIN-CLIENTTOKEN,OAUTHBEARER,XOAUTH
SMTP Error: Could not authenticate.
CLIENT -> SERVER: QUIT
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "221 2.0.0 closing connection i201sm36810815ywe.10 - gsmtp"
SERVER -> CLIENT: 221 2.0.0 closing connection i201sm36810815ywe.10 - gsmtp
Connection: closed
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
Like the error says:

```
Auth method requested: XOAUTH
Auth methods available on the server: LOGIN,PLAIN,XOAUTH2,PLAIN-CLIENTTOKEN,OAUTHBEARER,XOAUTH
```

You've requested an auth method that's not supported. If you're using OAuth2, you need to set `$mail->AuthType = 'XOAUTH2'`. Also make sure you [read the docs](https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2).

**Comment by dlhenke** [comment]
hey.. that was a second try.. 
XOAUTH2, XOAUTH ..

**Comment by dlhenke** [comment]
PIPELINING250-CHUNKING250 SMTPUTF8
Auth method requested: XOAUTH2
Auth methods available on the server: LOGIN,PLAIN,XOAUTH2,PLAIN-CLIENTTOKEN,OAUTHBEARER,XOAUTH
CLIENT -> SERVER: AUTH XOAUTH2 dXNlcj1hZnBlc3AuYXJpbkBnbWFpbC5jb20BYXV0aD1CZWFyZXIgeWEyOS5Md0twb2V3c0NIN21QaTViLTFLcE8tYUZaNGxWenhWWGRvV3RjN3kzZVR5T09oMnNiNGNMcS1mYUZUaEZPak1KZC1tazB3AQE=
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "334 eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ=="
SERVER -> CLIENT: 334 eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==
SMTP ERROR: AUTH command failed: 334 eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==
SMTP Error: Could not authenticate.
CLIENT -> SERVER: QUIT
SMTP -> get_lines(): $data is ""
SMTP -> get_lines(): $str is "535-5.7.8 Username and Password not accepted. Learn more at"
SMTP -> get_lines(): $data is "535-5.7.8 Username and Password not accepted. Learn more at"
SMTP -> get_lines(): $str is "535 5.7.8 https://support.google.com/mail/answer/14257 x139sm2326702vkd.7 - gsmtp"
SERVER -> CLIENT: 535-5.7.8 Username and Password not accepted. Learn more at535 5.7.8 https://support.google.com/mail/answer/14257 x139sm2326702vkd.7 - gsmtp
SMTP ERROR: QUIT command failed: 535-5.7.8 Username and Password not accepted. Learn more at535 5.7.8 https://support.google.com/mail/answer/14257 x139sm2326702vkd.7 - gsmtp
Connection: closed
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by usamamashkoor** [comment]
did you find any solution...?

**Comment by Synchro** [comment]
You must have done something wrong in configuring your Gmail oauth credentials. It works fine for me and others, and the delivery of credentials itself is very simple. Setting them up is very complex and error-prone, but that's Gmail, not PHPMailer. Work through the oauth docs in the wiki.

**Comment by josebulatao** [comment]
SMTP -> FROM SERVER:220 smtp.gmail.com ESMTP c6sm21581911pfm.165 - gsmtp
SMTP -> FROM SERVER: 250-smtp.gmail.com at your service, [205.144.171.59] 250-SIZE 35882577 250-8BITMIME 250-STARTTLS 250-ENHANCEDSTATUSCODES 250-PIPELINING 250-CHUNKING 250 SMTPUTF8
SMTP -> ERROR: AUTH not accepted from server: 530 5.7.0 Must issue a STARTTLS command first. c6sm21581911pfm.165 - gsmtp
SMTP -> FROM SERVER:250 2.1.5 Flushed c6sm21581911pfm.165 - gsmtp
SMTP Error: Could not authenticate. Mailer Error: SMTP Error: Could not authenticate.


i am having this error.. please help me

**Comment by Synchro** [comment]
Make sure you're using the latest version, and base your code on the gmail example provided.

**Comment by josebulatao** [comment]
i am using the latest version of the PHPmailer.. can you please provide me an php example for sending email ?

**Comment by Synchro** [comment]
Is it really so hard to find the ones that are [right here](https://github.com/PHPMailer/PHPMailer/tree/master/examples)?

**Comment by josebulatao** [comment]
could you give me the proper phpmailer files to use ? the one that can be
downloaded in command prompt using composer.. i cannot download it on my
command prompt and i don't know why it isn't downloading.

**Comment by ooxi** [comment]
Please paste the output of running `composer require phpmailer/phpmailer`. We might have to move this discussion to a more suitable place like stackoverflow since this is clearly not a PHPMailer issue.

**Comment by josebulatao** [comment]
[image: Inline image 1]

**Comment by ooxi** [comment]
> [image: Inline image 1]

Most likely you are trying to send an image to GitHub via mail. Please log into GitHub and paste your console output here.

**Comment by josebulatao** [comment]
![sa](https://user-images.githubusercontent.com/32564449/36765320-9126287c-1c6b-11e8-8512-c0edcf304cbb.png)

**Comment by josebulatao** [comment]
i'll just start over from the scratch.. please help me set up phpmailer

**Comment by ooxi** [comment]
Please make sure you read the instructions carefully. The command is called `composer` not `compose`. Do you have composer installed on your system? If not you can follow the [Composer installation guide for Windows](https://getcomposer.org/doc/00-intro.md#installation-windows).

**Comment by josebulatao** [comment]
So that's what im missing... Thanks alot ! :) Downloading PHPmailer now...

**Comment by ooxi** [comment]
> So that's what im missing... Thanks alot ! :) Downloading PHPmailer now...

Sure thing :-)

**Comment by josebulatao** [comment]
![sdadasdasd](https://user-images.githubusercontent.com/32564449/36765884-5cd3dd78-1c6e-11e8-9320-9ebf452b0621.png)
 getting this error from smtp.. i used smtp.gmail.com

**Comment by ooxi** [comment]
Are you using the [GMail example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail.phps)?

Also please paste verbatim instead of images. Think of the visually impaired :-)

**Comment by josebulatao** [comment]
yes... everytime i use gmail the smtp error is always occuring

**Comment by josebulatao** [comment]
2018-02-28 02:07:03 SERVER -> CLIENT: 220 SG ESMTP service ready at ismtpd0005p1las1.sendgrid.net
2018-02-28 02:07:03 CLIENT -> SERVER: EHLO maybanksurvey-001-site1.atempurl.com
2018-02-28 02:07:03 SERVER -> CLIENT: 250-smtp.sendgrid.net250-8BITMIME250-PIPELINING250-SIZE 31457280250-STARTTLS250-AUTH PLAIN LOGIN250 AUTH=PLAIN LOGIN
2018-02-28 02:07:03 CLIENT -> SERVER: STARTTLS
2018-02-28 02:07:03 SERVER -> CLIENT: 220 Begin TLS negotiation now
2018-02-28 02:07:03 CLIENT -> SERVER: EHLO maybanksurvey-001-site1.atempurl.com
2018-02-28 02:07:03 SERVER -> CLIENT: 250-smtp.sendgrid.net250-8BITMIME250-PIPELINING250-SIZE 31457280250-STARTTLS250-AUTH PLAIN LOGIN250 AUTH=PLAIN LOGIN
2018-02-28 02:07:03 CLIENT -> SERVER: AUTH LOGIN
2018-02-28 02:07:03 SERVER -> CLIENT: 334 VXNlcm5hbWU6
2018-02-28 02:07:03 CLIENT -> SERVER: <credentials hidden>
2018-02-28 02:07:03 SERVER -> CLIENT: 334 UGFzc3dvcmQ6
2018-02-28 02:07:03 CLIENT -> SERVER: <credentials hidden>
2018-02-28 02:07:03 SERVER -> CLIENT: 235 Authentication successful
2018-02-28 02:07:03 CLIENT -> SERVER: MAIL FROM:<josebulatao17@gmail.com>
2018-02-28 02:07:03 SERVER -> CLIENT: 250 Sender address accepted
2018-02-28 02:07:03 CLIENT -> SERVER: RCPT TO:<josebulatao17@gmail.com>
2018-02-28 02:07:03 SERVER -> CLIENT: 250 Recipient address accepted
2018-02-28 02:07:03 CLIENT -> SERVER: DATA
2018-02-28 02:07:03 SERVER -> CLIENT: 354 Continue
2018-02-28 02:07:03 CLIENT -> SERVER: Date: Tue, 27 Feb 2018 18:07:02 -0800
2018-02-28 02:07:03 CLIENT -> SERVER: To: josebulatao17@gmail.com
2018-02-28 02:07:03 CLIENT -> SERVER: From: Josebulatao <josebulatao17@gmail.com>
2018-02-28 02:07:03 CLIENT -> SERVER: Subject: Here is the subject
2018-02-28 02:07:03 CLIENT -> SERVER: Message-ID: <SACxLV1SyQHvdhn3EOgrG7LJYIOaV9Q7AIh68IM3PY@maybanksurvey-001-site1.atempurl.com>
2018-02-28 02:07:03 CLIENT -> SERVER: X-Mailer: PHPMailer 6.0.3 (https://github.com/PHPMailer/PHPMailer)
2018-02-28 02:07:03 CLIENT -> SERVER: MIME-Version: 1.0
2018-02-28 02:07:03 CLIENT -> SERVER: Content-Type: multipart/alternative;
2018-02-28 02:07:03 CLIENT -> SERVER: boundary="b1_SACxLV1SyQHvdhn3EOgrG7LJYIOaV9Q7AIh68IM3PY"
2018-02-28 02:07:03 CLIENT -> SERVER: Content-Transfer-Encoding: 8bit
2018-02-28 02:07:03 CLIENT -> SERVER:
2018-02-28 02:07:03 CLIENT -> SERVER: This is a multi-part message in MIME format.
2018-02-28 02:07:03 CLIENT -> SERVER: --b1_SACxLV1SyQHvdhn3EOgrG7LJYIOaV9Q7AIh68IM3PY
2018-02-28 02:07:03 CLIENT -> SERVER: Content-Type: text/plain; charset=us-ascii
2018-02-28 02:07:03 CLIENT -> SERVER:
2018-02-28 02:07:03 CLIENT -> SERVER: This is the body in plain text for non-HTML mail clients
2018-02-28 02:07:03 CLIENT -> SERVER:
2018-02-28 02:07:03 CLIENT -> SERVER: --b1_SACxLV1SyQHvdhn3EOgrG7LJYIOaV9Q7AIh68IM3PY
2018-02-28 02:07:03 CLIENT -> SERVER: Content-Type: text/html; charset=us-ascii
2018-02-28 02:07:03 CLIENT -> SERVER:
2018-02-28 02:07:03 CLIENT -> SERVER: This is the HTML message body <b>in bold!</b>
2018-02-28 02:07:03 CLIENT -> SERVER:
2018-02-28 02:07:03 CLIENT -> SERVER:
2018-02-28 02:07:03 CLIENT -> SERVER: --b1_SACxLV1SyQHvdhn3EOgrG7LJYIOaV9Q7AIh68IM3PY--
2018-02-28 02:07:03 CLIENT -> SERVER:
2018-02-28 02:07:03 CLIENT -> SERVER: .
2018-02-28 02:07:03 SERVER -> CLIENT: 250 Ok: queued as 4xTgCI24R-OpUIuN9XkKhg
2018-02-28 02:07:03 CLIENT -> SERVER: QUIT
2018-02-28 02:07:03 SERVER -> CLIENT: 221 See you later
Message has been sent


if i use the smtp.sendgrid.net i can send email. but why can't i send using the gmail ?

**Comment by ooxi** [comment]
Please remove the lines after `2018-02-28 02:07:03 CLIENT -> SERVER: AUTH LOGIN`, those are your username and password!

**Comment by josebulatao** [comment]
oh im sorry hahaha

**Comment by josebulatao** [comment]
2018-02-28 02:12:11 SERVER -> CLIENT: 220 smtp.gmail.com ESMTP s127sm603999pfb.178 - gsmtp
2018-02-28 02:12:11 CLIENT -> SERVER: EHLO maybanksurvey-001-site1.atempurl.com
2018-02-28 02:12:11 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [205.144.171.59]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
2018-02-28 02:12:11 CLIENT -> SERVER: STARTTLS
2018-02-28 02:12:11 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
SMTP Error: Could not connect to SMTP host.
2018-02-28 02:12:13 CLIENT -> SERVER: QUIT
2018-02-28 02:12:13
2018-02-28 02:12:13
SMTP Error: Could not connect to SMTP host.
Message could not be sent. Mailer Error: SMTP Error: Could not connect to SMTP host.

this is the error from smtp.gmail.com

**Comment by ooxi** [comment]
It looks like `smtp.sendgrid.net` is accepting plain login, whereas GMail requires OAuth. Also it does not really work, as you are using `smtp.sendgrid.net` to send an E-Mail from `xxx@gmail.com`. Most recipients will drop the mail since your mail server is not allowed to send E-Mails in the name of gmail.com

**Comment by ooxi** [comment]
Sorry I was pointing you at the wrong example, please try [gmail_xoauth](https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail_xoauth.phps). Also since it's quitting immediately after `STARTTLS` your CA certificates might be out of date.

**Comment by ooxi** [comment]
If the XOAuth example also does not work, try adding this [from the troubleshooing guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting#updating-ca-certificates):

```
$mail->SMTPOptions = array(
    'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )
);
```

**Please note that this is not a real solution since it allows active eavesdropping**. It's just a quick test to check whether your CA certificates need to get updated.

**Comment by josebulatao** [comment]
use League\OAuth2\Client\Provider\Google; this file doesn't exist in my directory

**Comment by ooxi** [comment]
We're getting closer :-)

Please execute `composer require league/oauth2-google` to download a Google OAuth implementation from The League

**Comment by josebulatao** [comment]
yes close hahaha

**Comment by josebulatao** [comment]
$mail->setOAuth(
    new OAuth(
        [
            'provider' => $provider,
            'clientId' => $clientId,
            'clientSecret' => $clientSecret,
            'refreshToken' => $refreshToken,
            'josebulatao17@gmail.com' => $email,
        ]
    )
);

what should i input here ? :(

**Comment by ooxi** [comment]
You should not have to change anything between [lines 58 to 77](https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail_xoauth.phps#L58-L77).

You have to configure your account credentials in [lines 48 to 56](https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail_xoauth.phps#L48-L56).

**Comment by ooxi** [comment]
If you don't know where to get those credentials, please make sure to follow the [GMail OAuth Guide](https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2) :-)

**Comment by josebulatao** [comment]
i can't get the Gmail OAuth.. i think i'll stick with sendgrid for now.. Thankyou ! @ooxi

**Comment by Synchro** [comment]
Thanks for picking this up @ooxi. I suspect the main problem here is that @josebulatao has outdated CA certificates, which prevents gmail's certificate from being verified at the client end - gmail changed their cert not so long ago and this has been a very common result. Disabling verification should be a workaround for that, but the right fix is to download a new CA cert bundle and tell PHP to use that - this is described in the troubleshooting guide. You would need to do this even if using OAuth, since OAuth authentication happens *after* a TLS session has been established.

**Comment by josebulatao** [comment]
sir @Synchro do you have a sample for making a html be downloaded as pdf file.. i am creating a online request form and want to printout the filled out form.

**Comment by Synchro** [comment]
That's not really an email question - look at projects like [tcpdf](https://tcpdf.org). Generally you'll get much better results if you generate PDFs directly using submitted form values rather than converting from HTML.

**Comment by nomankh000123** [comment]
time waisting page
