### ISSUE TITLE
Fatal error when using PHPMailer in a loop

### ISSUE THREAD

**Issue by dogmaticslumbers** [PHPMailer/PHPMailer#564]
I've written a "mailto" function using PHPMailer to mirror the syntax of the PHP "mail" function.

When I execute a script that sends out more than one email in a loop, PHPMailer throws a "Fatal error: Cannot redeclare class SMTP in /usr/share/pear/class.smtp.php on line 28" error as soon as the script tries to send the 2nd email in the list.

I am currently working around it by enclosing everything in "class.smtp.php" in a conditional beginning with: 

"if (!class_exists('SMTP')) {
   -- smtp class here --
}

You should be able to reproduce the issue by looping through at least 2 email addresses using PHPMailer as the mail function.

Thanks.

--Edit--

My bad!  Solved by inserting "require_once("class.smtp.php");" instead of "include("class.smtp.php")" in my function.

**Comment by dogmaticslumbers** [comment]
My bad!  Solved by inserting "require_once("class.smtp.php");" instead of "include("class.smtp.php")" in my function.

Please delete this noise.  I couldn't figure out how to do it. :-)

**Comment by Synchro** [comment]
You shouldn't be loading the class manually at all. Please read the docs, base your code on examples, use the autoloader or composer.

**Comment by dogmaticslumbers** [comment]
Actually, it was the basing of my code on an example and that got me into trouble to begin with.  Please see my mea culpa post 2 hours before yours.  My bad.  I'm sorry.

**Comment by Synchro** [comment]
No I mean base your code on *the examples provided with PHPMailer*, all of which handle loading correctly. There are zillions of others than do it wrong...
