### ISSUE TITLE
`Body` does not work

### ISSUE THREAD

**Issue by mfgabriel92** [PHPMailer/PHPMailer#567]
I am trying to send attachments, and I saw that it works with `Body` instead of `MsgHTML`, but with it, my form does not do anything, it simply reloads, and the `if ($mailer->send()) {}` does not even is reached. What to do?

**Comment by Synchro** [comment]
Body has little to do with attachments. Please base your code on the examples provided, and I can't do anything to help if you don't post your code.

**Comment by mfgabriel92** [comment]
Yes, this is the code:

```php    
    $extensoes = array('pdf', 'doc', 'docx');
    $extensaoArquivo = pathinfo($_FILES['Arquivo']['name'], PATHINFO_EXTENSION);
    $novoNomeArquivo = strtolower(str_replace(' ', '_', $_post['Nome']) . '.' . $extensaoArquivo);

    if (in_array($extensaoArquivo, $extensoes)) {
        if (move_uploaded_file($_FILES['Arquivo']['tmp_name'], 'uploads/' . $novoNomeArquivo)) {
            $mailer->ContentType = "Content-type: text/html; charset=utf-8";
            $mailer->setFrom($_post['Email'], $_post['Nome']);
            $mailer->addAddress("mail@mail.com.br");
            $mailer->Subject = 'Trabalhe conosco - ' . $_post['Nome'];
            $mailer->isHTML();
            $mailer->MsgHTML($mensagem);
            $mailer->addAttachment($_FILES['Arquivo']['tmp_name'], $novoNomeArquivo);

            if ($mailer->send()) {
                ...

```

As it is now, no attachment is received. If I try to use `$mailer->Body($mensagem);`, it seems the `if ($mailer->send()) {` is not even reached. I use Ajax with `FormData`, and if it is a success, the form is reseted, but with `Body`, nothing happens.

**Comment by SDKiller** [comment]
@mfgabriel92 
Why are you using $_FILES['Arquivo']['tmp_name'] in `addAttachment()` instead of path you moved uploaded file to?

**Comment by mfgabriel92** [comment]
@SDKiller Because I have found examples doing it. Now I have fixed it. Thank you.

**Comment by Synchro** [comment]
Look at the send upload example in the examples folder.
