### ISSUE TITLE
get_oauth_token.php script only returning basic gmail access auth token

### ISSUE THREAD

**Issue by djc-developer** [PHPMailer/PHPMailer#568]
Hi, I can't tell if this is a known problem, as the comment on the script *get_oauth_token.php* says not to mess around with the accessType.

**Problem**: In the troubleshooting page https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2#fetch-the-token

It says *get_oauth_token.php* should return an authorisation token for "viewing and managing gmail" with consent. But instead *get_oauth_token.php* keeps giving me "Basic account Info" authorisation token only. So no gmail modifcation authorisation, no authenticate token for gmail account smtp access, etc.

*The refresh token used for XOAUTH2 during SMTP login is probably the reason for so many authentication PASSWORD/USERNAME SMTP failures, when really it's just a bad auth token* 

*Included is a dump of my debug
I'm guessing the SMTP authenticate is failing because the proper authorisation token is not working. If I'm wrong, I'd like any kind of feedback. I may be doomed to just go the basic route.*

**PS, I removed the AUTH key because of the base64 encoding of my gmail account**

*SERVER -> CLIENT: 220 smtp.gmail.com ESMTP rc5sm11791624pbc.95 - gsmtp
CLIENT -> SERVER: EHLO localhost
SERVER -> CLIENT: 250-smtp.gmail.com at your service, [58.6.216.202]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: STARTTLS
SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
CLIENT -> SERVER: EHLO localhost
SERVER -> CLIENT: 250-smtp.gmail.com at your service, [58.6.216.202]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: AUTH XOAUTH2 [AUTH REMOVED BY DJC-Developer]
SERVER -> CLIENT: 334 eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==
SMTP ERROR: AUTH command failed: 334 eyJzdGF0dXMiOiI0MDAiLCJzY2hlbWVzIjoiQmVhcmVyIiwic2NvcGUiOiJodHRwczovL21haWwuZ29vZ2xlLmNvbS8ifQ==
SMTP Error: Could not authenticate.
CLIENT -> SERVER: QUIT
SERVER -> CLIENT: 535-5.7.8 Username and Password not accepted. Learn more at535 5.7.8 https://support.google.com/mail/answer/14257 rc5sm11791624pbc.95 - gsmtp
SMTP ERROR: QUIT command failed: 535-5.7.8 Username and Password not accepted. Learn more at535 5.7.8 https://support.google.com/mail/answer/14257 rc5sm11791624pbc.95 - gsmtp
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting*

**Comment by djc-developer** [comment]
I took a deeper look into the Google XOAuth 2.0 playground. It looks like maybe a scope problem.

**Comment by sherryl4george** [comment]
Thanks a lot for the analysis, DJC-Developer
As you have noted, this is a scope issue which resulted from the changes to the library used to generate the OAuth token. The issue has been solved and has been requested to pull as you can see above.
