### ISSUE TITLE
phpmailer error

### ISSUE THREAD

**Issue by payalpadiya** [PHPMailer/PHPMailer#570]
Message could not be sent.Mailer Error: Could not instantiate mail function.

**Comment by Synchro** [comment]
[Read the docs](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting).

**Comment by payalpadiya** [comment]
Ohhkkk will try and let u knw

Thnk u so much

**Comment by payalpadiya** [comment]
"Could not instantiate mail function"

This means that your PHP installation is not configured to call the mail() function correctly (e.g. sendmail_path is not set correctly in your php.ini), or you have no local mail server installed and configured. To fix this you need to do one or more of these things:

Install a local mail server (e.g. postfix).
Ensure that your sendmail_path points at the sendmail binary (usually /usr/sbin/sendmail) in your php.ini. Note that on Ubuntu/Debian you may have multiple .ini files in /etc/php5/mods-available and possibly other locations.
Use isSendmail() and set the path to the sendmail binary in PHPMailer ($mail->Sendmail = '/usr/sbin/sendmail';).
Use isSMTP() and send directly using SMTP.




i have tried above all this...

**Comment by payalpadiya** [comment]
thnk u so much 

it woks with this path

sendmail_path =  "env -i /usr/sbin/sendmail -t -i"

and but i got the messsage has been sent but still i didn't got any mail

please help....

**Comment by Synchro** [comment]
If that command completes ok, it means the message has been passed to your mail server successfully. What happens after that is outside PHPMailer's control, but you need to check that your mail server is actually running, and then check the mail log, usually in `/var/log/mail.log`, to see what has happened to your message.

**Comment by payalpadiya** [comment]
i m getting the notification in Mail app also for incoming mails

and i can also send the mail from the Mail app

then what's the problem?

**Comment by Synchro** [comment]
I have no idea what you're talking about. PHPMailer has nothing to do with inbound mail.

**Comment by payalpadiya** [comment]
I m getting the message has been sent but it is not showing in mailbox .As
u have told to chek mail.log and outgoing mail server

it's all running ok but the issue is not receiving mails

**Comment by Synchro** [comment]
This makes no sense. If you have checked your mail log, you know what has happened to the message.

**Comment by payalpadiya** [comment]
when i open the mail.log it shows th error :


local (connect to smtp.gmail.com[2404:6800:4003:c00::6c]:587: No route to
host)

**Comment by Synchro** [comment]
That explains it - you have a networking problem. This problem would have been apparent from the DNS, ping and telnet tests suggested in the troubleshooting guide. I suggest you ask your hosting provider for help.
