### ISSUE TITLE
cas.cloudplatform1.com

### ISSUE THREAD

**Issue by MattyTheWizz** [PHPMailer/PHPMailer#571]
Hi when I send email to cas.cloudplatform1.com after a long delay, I get :

SMTP -> ERROR: Failed to connect to server: Connection timed out (110)
SMTP Error: Could not connect to SMTP host.

Same code works well on 123reg and GoDaddy email servers - so am stumped
I'm using PHPMailer v5.2.4

( ! ) I've not put my real domain / password in - lol - best to be safe !
( ! ) I can ping cas.cloudplatform1.com okay - so I don't see why PHPMailer says timed out?

If I setup Outlook - that's okay ... the IT guys tell me that TLS/SSL is turned off

here's the sample code I'm using ::
-------------------------------------------------------------------------------------------------------------

				require 'includes/phpmailer/class.phpmailer.php';
				
				$mail = new PHPMailer(true);
				$mail->IsSMTP();

				try {
					$mail->Host = "cas.cloudplatform1.com";
					$mail->Port = 25;
					$mail->SMTPDebug  = 1;
					//$mail->SMTPSecure = "tls";
					$mail->SMTPAuth = false;
					$mail->Username = "webmail@national-happydays.com";
					$mail->Password = "password";
					

					$mail->From = "matt@national-happydays.com";
					$mail->FromName = "My Mail Address";
					$mail->SetFrom("webmail@national-happydays.com", "My Mail Address");

					$mail->AddAddress('ming@aol.co.uk');

					$mail->Subject = "Test for subject";
					$mail->MsgHTML("Test my mail body");

					if ($mail->Send()) {
						$result = 1;
					} else {
						$result = "Error: " . $mail->ErrorInfo;
					}
				} catch (phpmailerException $e) {
					$result = $e->errorMessage();
					echo $result;
				} catch (Exception $e) {
					$result = $e->getMessage();
					echo $result;
				}

-------------------------------------------------------------------------------------------------------------

Is there some weirdness with Cloud Platform Exchange hosted email that PHPMailer does not like

If I try the olde worlde mail command - I get `mail sent` - but it never arrives
Big thanks to the experts who can fix it ;-)

**Comment by Synchro** [comment]
The `mail` function sends via a local mail server, and you get essentially no direct feedback whether it works or not - you need to look at the mail server log to tell.

It's quite likely that outbound SMTP is blocked from your server - that would explain ping working but not SMTP. You should update your PHPMailer - 5.2.4 is old and buggy - and base your code on an up to date example too.

**Comment by MattyTheWizz** [comment]
I've abandoned the mail command - the host we use also has other sites and they can send email happily using PHPMailer v5.2.4.

The mail server is managed by a third party so no access to that. Will try the latest version.

Even if I try from local host (desktop pc) still doesn't go through.

**Comment by MattyTheWizz** [comment]
I'm wondering if it's Exchange causing the problem?

**Comment by Synchro** [comment]
Did you try the tests in [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting)? You need to check from the server the script is running on; nowhere else is relevant.

**Comment by MattyTheWizz** [comment]
Yeah been through it - no luck though.

**Comment by Synchro** [comment]
Well if the tests don't work, then PHPMailer can't either. You've got a network problem, not a PHP problem.
