### ISSUE TITLE
Heads up for those having issues with PHPMailer + Gmail (via SMTP) recently

### ISSUE THREAD

**Issue by nunoarruda** [PHPMailer/PHPMailer#572]
The php contact form on my personal website was not sending emails so I looked into it and I found out that Gmail implemented extra security. You now need to activate "Allow less secure apps" in order to use PHPMailer + Gmail (via SMTP).

Here's a warning I got when my php contact form failed:
![screen shot 2015-11-26 at 21 38 51](https://cloud.githubusercontent.com/assets/1189149/11431389/414056b2-9486-11e5-8a3d-558d80bed6c0.png)

And here's what you need to do in order to fix it:
![screen shot 2015-11-26 at 21 39 21](https://cloud.githubusercontent.com/assets/1189149/11431392/612be8f6-9486-11e5-98da-17295937d5e8.png)

**Comment by Synchro** [comment]
You could of course [read the docs](https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2) and [do it properly](https://github.com/PHPMailer/PHPMailer/blob/master/examples/gmail_xoauth.phps) instead.
