### ISSUE TITLE
Property to select default pattern for validateAddress()

### ISSUE THREAD

**Issue by PetrToman** [PHPMailer/PHPMailer#573]
There is no way to change the default pattern used by ``validateAddress($address, $patternselect = 'auto')`` function other than subclassing PHPMailer (or patching this class, which is not very convenient). I suggest to introduce a new property that would allow that:
```
public $defaultValidateAddressSelect = 'auto';
```

**Comment by r-a-y** [comment]
Thanks @Synchro!
