### ISSUE TITLE
Sender Address Domain wrong

### ISSUE THREAD

**Issue by davidrossiter** [PHPMailer/PHPMailer#574]
I am having trouble with X-AntiAbuse: Sender Address Domain, it's sending from my server URL not the website URL (the website/user phpmailer is on)

The issue this creates is the server URL has no dkim, spf or ptr setup. The url for the website does. So dkim = fail and spf = fail when sent from phpmailer, instead of = pass.

X-AntiAbuse: Sender Address Domain - app.myserver.com is how it appears

I need it to be X-AntiAbuse: Sender Address Domain - mywebsite.com (which is the same url the email is sent from - hello@mywebsite.com)

Adding it in manually means it ends up with 2 Sender Address Domain's in the header of the email and dkim and spf still fail.

The headers work absolutely fine when I send mail from roundcube via cpanel, the mail sender address domain is mywebsite.com and not app.myserver.com. I can't get it working with phpmailer though.

Sadly I am not a developer, I only work with frontend so some of the terms I used might be incorrect. phpmailer is set up on my server to send emails to users who join (welcome emails, forgotten password etc)

I can provide any information needed or better descriptions, this issue has really stumped me, thanks for any help you can be pointing me in the right direction!

**Comment by Synchro** [comment]
PHPMailer does not add this header, so you need to look at what happens to the message after sending. For example if you are sending via a local mail server or nearby smarthost it's probably that that's adding it, and clearly that's outside PHPMailer's control. How are you sending?

**Comment by davidrossiter** [comment]
Hey @Synchro, thanks for replying. I am using a local mail server. I can eliminate phpmailer as the 'problem' then and need to look at my local mail server?

**Comment by davidrossiter** [comment]
@Synchro What about Return-path, that is incorrect too - is the added by phpmailer?

**Comment by Synchro** [comment]
No, unless you're using an old version. Return path is set by the receiver, derived from the envelope sender, which you can set in the Sender property.
