### ISSUE TITLE
addAddress($to) somehow appending a blank recipient

### ISSUE THREAD

**Issue by ryrobbo** [PHPMailer/PHPMailer#575]
My code has been in production for 12 months and worked fine until a user attempts to send an email to this single email address.

Here is my code (I have obscured personal information):

$mail->isSMTP();
$mail->From = 'no-reply@seevee.co.uk';
$mail->FromName = 'Seevee';
$mail->addAddress($to);     // Add a recipient
$mail->isHTML(true);

The value of $to passes PHPMailer's email validation and is "pat@avjobs.co.uk".

After dumping $mail->getToAddresses() I get this:

Array ( [0] => Array ( [0] => pat@avjobs.co.uk [1] => ) )

As you can see, the email does go to the first recipient (Pat) but the empty index [1] causes my application to throw the "You must provide at least one recipient email address." exception.

I am only using addAddress() once so why does the address array have an empty value on the end?

**Comment by Synchro** [comment]
That inxed 1 is not expected to be an address - it's a display name for the address - in this case it might be `Pat`. It's empty becuase you've not set one. I suspect you'll find that the error is elsewhere - set `SMTPDebug = 2` and see what the server says.

**Comment by ryrobbo** [comment]
Apologies for wasting your time.

I have discovered another method which is trying to send an email to an invalid address elsewhere in the system.
