### ISSUE TITLE
Fatal error: Class 'SMTP' not found in class.phpmailer.php on line 1443

### ISSUE THREAD

**Issue by mizumachi16** [PHPMailer/PHPMailer#576]
help I 've been using 

require 'PHPMailerAutoload.php';	
$mail = new PHPMailer; 

and place it in the same folder , you know the solution ?

**Comment by Synchro** [comment]
If you're loading the autoloader, this suggests you've not uploaded the SMTP class in a location where it can be found. Please read the README about minimal installations.
