### ISSUE TITLE
How to remove "X-Priority" from header

### ISSUE THREAD

**Issue by mediamon** [PHPMailer/PHPMailer#577]
I'm using phpmailer 5.2.6 in ZenCart 1.54.. I'd like to remove X-priority from the sent email headers sent from the shop. I suspect a simple edit in class.phpmailer.php will do this but not sure how. Any suggestions? Thanks.

Below is relevant code from phpmailer 5.2.6 in ZenCart 1.54
class.phpmailer.php

ln 54 

public $Priority          = 3;

ln 1438-1446

    $result .= $this->HeaderLine('X-Priority', $this->Priority);
    if ($this->XMailer == '') {
        $result .= $this->HeaderLine('X-Mailer', 'PHPMailer '.$this->Version.' (https://github.com/PHPMailer/PHPMailer/)');
    } else {
      $myXmailer = trim($this->XMailer);
      if ($myXmailer) {
        $result .= $this->HeaderLine('X-Mailer', $myXmailer);
      }
    }

**Comment by Synchro** [comment]
This was fixed in a later version of PHPMailer, and you should update anyway. You can now set `$mail->Priority = null;` and the header will not be added.
