### ISSUE TITLE
Need suggestions for a bounce handler

### ISSUE THREAD

**Issue by nestsman** [PHPMailer/PHPMailer#578]
Since PHPMailer doesn't support handling bounced emails, I need to try and get a good recommendation from you pros.  Here are two that I am considering, but I'm open to other suggestions too:

1. PHP-Bounce-Handler - https://github.com/cfortune/PHP-Bounce-Handler

2. BounceStudio API - http://www.boogietools.com/Products/Linux/

Thank you for any advice you can offer!

**Comment by Synchro** [comment]
In the past there was a PHPMailer bounce handler sub-project, but it's long-defunct. That one on github doesn't look like it's maintained either. I use boogietools indirectly in a mail server and it works well enough, though it's not great. I know first-hand that writing your own is a deeply unpleasant experience I wouldn't want to repeat! You may find there are better implementations in python, ruby or node.js.

**Comment by michield** [comment]
[phpList](https://github.com/phpList/phpList3) handles bounces, although it can do with some updating as well.
