### ISSUE TITLE
Space in $params with mail() doesnt send any mail

### ISSUE THREAD

**Issue by Komrod** [PHPMailer/PHPMailer#582]
Hello,

When passing a space character in $params to the mail() function, it returns true but the mail is never sent. I'm using IIS default STMP server.

In the phpmailer class, class.phpmailer.php line 677:

    $result = @mail($to, $subject, $body, $header, $params);

$params is set to a space character ' ' when Sender is empty, in class.phpmailer.php line 1407: 

```php
if (empty($this->Sender)) {
    $params = ' ';
} else {
    $params = sprintf('-f%s', $this->Sender);
}
```
I don't see a reason why $params should be set to " ", this doesn't mean anything. And it stops my mail server from sending mails. So may be this should be considered as a bug.

Setting $params to empty "" and it works.

Thanks

**Comment by Synchro** [comment]
Apologies for not getting onto this sooner. I quite agree - I can't see any reason for passing in this space, so it's fixed in HEAD and will be in the next release. Thanks for the report.
