### ISSUE TITLE
Host value must start with ssl://

### ISSUE THREAD

**Issue by leonbrag** [PHPMailer/PHPMailer#586]
In the code below, I am able to make connection  to AWS SES only when host starts with ssl://. If host contains host name only, connection fails.
Should not PHPMailer initiate connection without URL starting with ssl:// since SMTP secure is set to tls (or ssl)?

	$mail = new PHPMailer;
        $mail->SMTPDebug = 3;                           

	$mail->isSMTP();                                      // Set mailer to use SMTP
	$mail->Host = 'ssl://blah.amazonaws.com';  // if ss:// removed, connection fails
	$mail->SMTPAuth = true;                               // Enable SMTP authentication
	$mail->Username = 'blah';                 // SMTP username
	$mail->Password = 'blah blah';                           // SMTP password
		
	$mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
	$mail->Port = 443;

**Comment by Synchro** [comment]
You're setting `SMTPSecure = 'tls'` (explicit STARTTLS) when talking to a port that expects implicit SSL, which won't work, but the `ssl` in your host overrides that so that it works. If you set `Host = 'blah.amazonaws'` and set `SMTPSecure = 'ssl'`, it will work.
