### ISSUE TITLE
Message-ID is not RFC 822 compliant

### ISSUE THREAD

**Issue by hdatma** [PHPMailer/PHPMailer#587]
I received an e-mail from a PHPMailer user (a political party) with the following header:
Message-ID: 94f4e3edc9e34a098190862079df6959

As you can see, it is not RFC 822 compliant:

> msg-id         = "<" addr-spec ">"     ; Unique message id
> addr-spec      = local-part "@" domain ; global address

My servers will soon implement strict RFC compliance on this header:
non-compliance will cause the rejection of the e-mail. 

Please catch this problem, either with a "remove-before-flight" diagnostic, or directly at runtime. 

Thank you.

**Comment by Synchro** [comment]
PHPMailer generates RFC-compliant Message-ID headers by default, but users may override it, as appears to be happening in your case. I would advise you continue with your current course - anyone using invalid IDs will soon get the message. This is the code in question:

```php
        if ($this->MessageID != '') {
            $this->lastMessageID = $this->MessageID;
        } else {
            $this->lastMessageID = sprintf('<%s@%s>', $this->uniqueid, $this->serverHostname());
        }
```

The RFC822 spec for message-id was updated by [RFC2822 3.6.4](http://tools.ietf.org/html/rfc2822#section-3.6.4) in 2001 and no longer mandates `local-part` and `domain`, preferring more generic constructs, though PHPMailer defaults to the earlier pattern.

**Comment by andris9** [comment]
When generating message-id values then the latest convention for a lot of mailers seems to be to not use the server hostname but sender address hostname. So if I send as "andris@example.com" from "smtp.somedomain.com" then the message-id value is not going to be "unique@smtp.somedomain.com" but "unique@example.com". I guess this is caused by the fact that sometimes it is not so easy to detect the correct hostname, you might end up with something that is not FQDN (eg "localhost" or "machine-name" eg. something without valid tld) and this might end up with some spam points.

**Comment by hdatma** [comment]
The point with the OP is the complete absence of the "@<mandated>" part. The more recent RFC-2822 mandates  msg-id = [CFWS] "<" id-left "@" id-right ">" [CFWS], which still includes an "@" symbol, a local-part and a domain part: 

> id-left = dot-atom-text / no-fold-quote / obs-id-left
> obs-id-left = local-part

> id-right = dot-atom-text / no-fold-literal / obs-id-right
> obs-id-right = domain 

Assuming the PHPMailer user is in good faith (did not tamper with the source code), then the case at hand cannot fall into the second case below, because the "@" symbol would still be printed. 

        if ($this->MessageID != '') {
            $this->lastMessageID = $this->MessageID;
        } else {
            $this->lastMessageID = sprintf('<%s@%s>', $this->uniqueid, $this->serverHostname());
        }

I would improve the first result of the conditional test, 
to fail (exit 1) when $this->MessageID is not well formed.

**Comment by Synchro** [comment]
The error handling in the `createHeaders` function isn't up to much, so failing there isn't convenient. As an alternative, I've altered it to simply ignore an invalid `MessageID` and use the default pattern instead.
