### ISSUE TITLE
Can't send email to my own domain

### ISSUE THREAD

**Issue by nestsman** [PHPMailer/PHPMailer#588]
Every so often I get an error from PHPMailer when the recipient is my very own domain.  Does anyone know why this happens?

SMTP Error: The following recipients failed: info@mydomain.com
SMTP Error: The following recipients failed: memberservices@mydomain.com

Thank you!

**Comment by Synchro** [comment]
Try setting SMTPDebug = 2. Read the troubleshooting guide.
