### ISSUE TITLE
getSentMIMEMessage(); adds unwanted CrLf.

### ISSUE THREAD

**Issue by jhack89** [PHPMailer/PHPMailer#589]
Dear PHPMailer Developers,

thank you for your great work!
I found that for some reason getSentMIMEMessage(); adds an extra unwanted CrLf between the MIMEHeader and the Body of the message while the Send() method seems to work just fine when the message is received by the recipient.

Thus I get:
```
Date: Fri, 18 Dec 2015 11:06:34 +0000
To: xx@xx.xxx
From:  yy@yy.yyy
Subject: This is a TEST Mail Subject
Message-ID: <zzzzzzzzzzzzzzzzzzzzz@localhost>
X-Mailer: PHPMailer 5.2.14 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/plain; charset=iso-8859-1
Content-Transfer-Encoding: 8bit

(two CRLF here)

This is a TEST Mail Body message.
```

Instead of:
```
Date: Fri, 18 Dec 2015 11:06:34 +0000
To: xx@xx.xxx
From:  yy@yy.yyy
Subject: This is a TEST Mail Subject
Message-ID: <zzzzzzzzzzzzzzzzzzzzz@localhost>
X-Mailer: PHPMailer 5.2.14 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/plain; charset=iso-8859-1
Content-Transfer-Encoding: 8bit

(one single CRLF here)

This is a TEST Mail Body message.
```

It would be great if this little problem can be solved!
Thank you in advance for your help,

Warmest Regards.

EDIT: I don't know why but github automatically deletes the extra CRLFs so I updated the post and paraphrased them in words between the brakets).

**Comment by Synchro** [comment]
Thanks. This was down to some inconsistent handling of the end of the header section. I've made `getSentMIMEMessage` remove any ambiguity!

**Comment by jhack89** [comment]
You were blazingly fast, thank you! I'll be downloading the updated version.
