### ISSUE TITLE
 Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in blablabla....

### ISSUE THREAD

**Issue by troindx** [PHPMailer/PHPMailer#590]
Hi! So i've been using PHPMailer for quite some time and it worked fine. But lately we've changed our smtp servers to google and gapps, and the part that used to connect to google stopped working. I read out and I figured out I needed to do the whole OAUTH  described in this post

https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2

So apparently when I get to  this part of the tutorial
![captura](https://cloud.githubusercontent.com/assets/3263966/11902608/5aae4260-a5b3-11e5-8ec9-adce503480ff.PNG)
I get the nicest 500 error that says

 Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in blablabla...

So I kept reading on and I discovered there was this library that needed to be installed. 
Unfortunately, the only easy way of installing this is through composer.phar...

Before we continue, i'd like to point out that I hate composer. I feel utterly disgusted by only hearing it's name. I'm not going to tell you the story of how composer gave my best friend cancer or why composer is the real reason behind the war in syria and the refugee crisis in Europe. Therefore and just to keep things short, we will assume that composer can cause cancer in the anus  and that I cannot use composer in my project (and thus won't enter into a debate on why not and what composer did to my kids and family on 9-11 ). I really really like PHPMailer, phpmailer is nice, cute and gets the job done in a very simple and none intrusive way. I would date PHPMailer, but I cant cos it's just a php library and that's physically impossible.

anyway. Is there any possible "Drag and drop" solution for this problem? Just a simple way to add certain files to some place and... voilá! make it work?. Or maybe a few simple lines of code? no external autoloader classes. this is a very small part (less than a 0.8% functionality ) of a bigger project and we need not to complicate this any further with aditional dependency managers and ISIS related software.

Please, try to explain this in the simplest possible way, imagine I have no idea of programming and I need this done to save the world from the next terrorist attack.

Thank you so much in advance
![please-meme](https://cloud.githubusercontent.com/assets/3263966/11902816/e142d3ee-a5b4-11e5-8dbb-7fe53c943140.jpeg)

**Comment by Synchro** [comment]
You can just comment out the autoloader `require` and install and load all the dependencies yourself (there are lots), but doing so without composer is very painful, so I'd really recommend you go with the flow and get over it. I've not worked on a project that has not been improved by switching to composer.

**Comment by troindx** [comment]
there is only ONE dependency.  it only requires the league/oauth2-client and I have no idea of where to find this :-1: 

I get that you have not worked on a project that has not been improved by switching to composer, but I have! And this decision does not depend on me, hence the limited constraint..

**Comment by Synchro** [comment]
No, there is one *top-level* dependency. There are many further packages that that package depends on. All packages loaded through composer are available on [packagist.org](https://packagist.org/packages/league/oauth2-client), and you can download them manually from there, and see all their dependencies.

**Comment by troindx** [comment]
that was very useful. Thank you so much for your information. I appreciate your work and your response.

keep it up

**Comment by ananthulasrikar** [comment]
Thanks this was very helpful to me.

**Comment by himanshushankhala** [comment]
Thank you for the resolution. One stop solution. Thumbs UP!

**Comment by kenchoong** [comment]
It appears this error in my command prompt 
 Could not scan for classes inside "extras/EasyPeasyICS.php" which does not appear to be a file nor a folder

after i install the composer via this command.
$ composer require league/oauth2-client

can somebody help?

**Comment by Raynaldi262** [comment]
Help ME
