### ISSUE TITLE
PHP Mailer Not Working >PHP 5.5

### ISSUE THREAD

**Issue by abc02101986** [PHPMailer/PHPMailer#595]
I get an error when using identical code from the latest version of phpMailer when using php 5.6 or greater. It works with  5.5  and less. 

Below is are the lines where the error is occurring

        if (!$this->smtpConnect($this->SMTPOptions)) {
            throw new phpmailerException($this->lang('smtp_connect_failed'), self::STOP_CRITICAL);
        }

it is about lines 1460 on class.phpmailer.php

**Comment by Synchro** [comment]
You need to say what the error is and read the troubleshooting docs.

**Comment by abc02101986** [comment]
Please see below



/Applications/MAMP/htdocs/democompany/php_util/mailer/phpmailer/class.phpmailer.php
Line: 1460
Message: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
#0 /Applications/MAMP/htdocs/democompany/php_util/mailer/phpmailer/class.phpmailer.php(1296): PHPMailer->smtpSend('Date: Fri, 25 D...', 'This is a multi...')
#1 /Applications/MAMP/htdocs/democompany/php_util/mailer/phpmailer/class.phpmailer.php(1176): PHPMailer->postSend()
#2 /Applications/MAMP/htdocs/democompany/php_util/mailer/mailer.php(50): PHPMailer->send()
... rest are from my php calling 
end


---What has me confused is that I am running it on the same machine, with the same code, and it works fine when the version is < 5.6. When it is greater than or equal to 5.6 i get this error. This is replicated on my deployment server as well no just the local test server I have.

Thanks

**Comment by Synchro** [comment]
That's where the error is triggered, not how it gets there. Read the guide, do what it says. It's likely your PHP configs differ.
