### ISSUE TITLE
Error: Could not execute: /usr/sbin/sendmail -t -i

### ISSUE THREAD

**Issue by nghipt99** [PHPMailer/PHPMailer#596]
i run script in file mail.php, is msg:
 Warning: escapeshellcmd() has been disabled for security reasons in /home/itsvnn.xyz/public_html/class.phpmailer.php on line 1336

Warning: escapeshellarg() has been disabled for security reasons in class.phpmailer.php on line 1336
Mailer Error: Could not execute: /usr/sbin/sendmail -t -i

Please help me. Thanks!

**Comment by nghipt99** [comment]
in the file get_oauth_token.php has line: 
require 'vendor/autoload.php';
but where don't i search folder vendor and the file autoload.php

**Comment by Synchro** [comment]
If that command is disabled you will need to switch to using the mail or SMTP transports.
The vendor folder is created when you run composer install.

**Comment by nghipt99** [comment]
I used to send mail gmail_xoauth.php  file
When I run script, it reported: 
Fatal error: Class 'League\OAuth2\Client\Provider\Google' not found in D:\web\PHP\sentmail\class.phpmaileroauthgoogle.php on line 51
Please help me!
