### ISSUE TITLE
Embedded image in body also going in attachment in or squirrel mail client

### ISSUE THREAD

**Issue by AviRns** [PHPMailer/PHPMailer#598]
i am able to embed the image in the body like 
```$mail->isHTML(true);
$mail->AddEmbeddedImage("bday.jpg", "my-attach", "bday.jpg");
$mail->Body = '<img alt="Birthday Wish Banner" src="cid:my-attach">';
```
but the image is also being attached in as attachment.

How to solve this? i want only image to be embedded in body not as attachment.

**Comment by Synchro** [comment]
There is no such option. Embedded images are simply attachments that are referenced from the message body. Whether they are shown as such is up to the client.

You could reference external images, which is probably more reliable.
