### ISSUE TITLE
better invalid_address error reporting

### ISSUE THREAD

**Issue by Cyberchicken** [PHPMailer/PHPMailer#599]
During some integration tests I managed to receive some invalid_address errors, but could not pinpoint the source. To get to the origin I modified classphpmailer.php (ver. '5.2.13') to enrich the error message.
The patch is rough (no translation) but functional: I just added the method name and the $kind
I post it here as a suggestion for a proper modification by someone who has a good view on the project.

```
diff -r 'Copy of class.phpmailer.php' 'class.phpmailer.php'
846,847c846,847
<             $this->setError($this->lang('invalid_address') . ': ' . $address);
<             $this->edebug($this->lang('invalid_address') . ': ' . $address);
---
>             $this->setError($this->lang('invalid_address') . " (addAnAddress $kind): " . $address);
>             $this->edebug($this->lang('invalid_address') . " (addAnAddress $kind): " . $address);
849c849
<                 throw new phpmailerException($this->lang('invalid_address') . ': ' . $address);
---
>                 throw new phpmailerException($this->lang('invalid_address') . " (addAnAddress $kind): " . $address);
936,937c936,937
<             $this->setError($this->lang('invalid_address') . ': ' . $address);
<             $this->edebug($this->lang('invalid_address') . ': ' . $address);
---
>             $this->setError($this->lang('invalid_address') . ' (setFrom): ' . $address);
>             $this->edebug($this->lang('invalid_address') . ' (setFrom): ' . $address);
939c939
<                 throw new phpmailerException($this->lang('invalid_address') . ': ' . $address);
---
>                 throw new phpmailerException($this->lang('invalid_address') . ' (setFrom): ' . $address);
```

**Comment by Synchro** [comment]
Thanks, I've updated it in a similar way. Note that the creation of these messages changed quite a bit between 5.2.13 and 5.2.14 - please always submit patches against the latest version.

**Comment by Cyberchicken** [comment]
Thank you!
What version holds your update?

Sorry for the wrong version, I didn't think to check (5.2.13 was quite recent) because the diff wasn't meant as a concrete patch but just as an aid to the discussion.

**Comment by Synchro** [comment]
It's not in a tagged release yet, but it's committed to the master branch. If you download a zip from the project home page, it will be in there.

**Comment by Cyberchicken** [comment]
Thank you!
