### ISSUE TITLE
Add a way to see the email without actually sending it?

### ISSUE THREAD

**Issue by nathanl** [PHPMailer/PHPMailer#6]
I've just written a program with some complex requirements for choosing recipients for emails. During development, I would have liked a way to output  the headers and body of the email without actually sending it, in order to confirm that it is correctly configured.

They way I've done this so far is to first build up an array, which I can easily inspect, and then use that to configure the PHPMailer object.

Is there a way to do this with PHPMailer? If not, I think it would be a good feature.

**Comment by fotografi** [comment]
>
