### ISSUE TITLE
ERROR when i run script gmail_xoauth.php file

### ISSUE THREAD

**Issue by nghipt99** [PHPMailer/PHPMailer#600]
I used to send mail gmail_xoauth.php file
When I run script, it reported: 
Fatal error: Class 'League\OAuth2\Client\Provider\Google' not found in D:\web\PHP\sentmail\class.phpmaileroauthgoogle.php on line 51
Please help me!

**Comment by Synchro** [comment]
You need to add the missing libraries to your `composer.json` file, as described in the readme. They are not included by default because they are not compatible with older versions of PHP and not everyone needs them.

**Comment by michaelik** [comment]
how with i do that?

**Comment by Synchro** [comment]
By [reading the composer docs](https://getcomposer.org/doc/00-intro.md).
