### ISSUE TITLE
I can't send emails with authentication

### ISSUE THREAD

**Issue by giovanithome** [PHPMailer/PHPMailer#605]
Hi.

I was using a older version of PHPMailer... it was working fine, until now.

With the version 5.2.14, I have the following error:

PHP Fatal error:  Uncaught exception 'phpmailerException' with message 'SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting'

trying to send smtp authenticated.

Is there any example with this?

**Comment by Synchro** [comment]
Take a look at [the examples](https://github.com/PHPMailer/PHPMailer/tree/master/examples), and read [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting) that message links to.
