### ISSUE TITLE
Automatic 8 to 7-bit downgrade (issue #176) implementation violates rfc2046

### ISSUE THREAD

**Issue by on6qd** [PHPMailer/PHPMailer#609]
All subttypes of "text" must implement the same charset.

From RFC rfc2046:

4.1.2.  Charset Parameter

"The specification for any future subtypes of "text" must specify whether or not they will also utilize a "charset" parameter, and may possibly restrict its values as well.  For other subtypes of "text" than "text/plain", the semantics of the "charset" parameter should be defined to be identical to those specified here for "text/plain"

**Comment by Synchro** [comment]
Not clear what you mean. Can you provide an example? The CTE is independent of Charset.

**Comment by on6qd** [comment]
This is a multi-part message in MIME format.

--b1_c8ecce6b2306c5c5daa79d9b4e097148
Content-Type: text/plain; charset=us-ascii

Deze mail is enkel verzonden in HTML formaat.

--b1_c8ecce6b2306c5c5daa79d9b4e097148
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit


The Content Type in the first part is "automatic downgraded", and therefore
the charset is different than the charset of the second type.

rfc2046 - 4.1.2

"For other subtypes of "text" than "text/plain", the semantics of the
"charset" parameter should be defined to be identical to those specified
here for "text/plain"

**Comment by Synchro** [comment]
You're just misunderstanding the RFC. It doesn't say that all parts need to use the same charset, it says they need to use the same *semantics*, i.e. the way that the charset is expressed, which they are. You can mix whatever charsets you like without breaking the semantics.
