### ISSUE TITLE
isSMTP();  Delayed 

### ISSUE THREAD

**Issue by ammoriz** [PHPMailer/PHPMailer#610]
if I use $mail->isSMTP();
and click send button the browser takes time before refresh.
is there a solution to make it faster ?

**Comment by Synchro** [comment]
Yes; install a local mail server and send via that. SMTP is not a fast protocol and is unsuited to sending messages during page submission. This is covered in the docs too.

**Comment by ammoriz** [comment]
Thanks for help :+1:
