### ISSUE TITLE
Save Test Email

### ISSUE THREAD

**Issue by TiagoGouvea** [PHPMailer/PHPMailer#611]
While trying to configure a SMTP account, the test inputs should save their values, to easy to send a test repeatedly.

**Comment by Synchro** [comment]
This is really not within PHPMailer's scope. PHPMailer doesn't have anything to do with saving form values, that's up to your app. If you're referring to things like the code generator script, by all means submit a PR if you want to improve it, but it's not a priority.

**Comment by TiagoGouvea** [comment]
Sorry. I don't know why I wrote it here. It was to be added on a Wordpress SMTP plugin, that uses PHPMailer.
