### ISSUE TITLE
Email send twice, while more than one blind copy is set

### ISSUE THREAD

**Issue by andreas83** [PHPMailer/PHPMailer#619]
Mr Example gets the email twice, while i defined two blind copies. 

$mail->addAddress("example@example.com",  "Mr Example"); 
$mail->addBCC("blind@copy.com");
$mail->addBCC("blind@anothercopy.com");

**Comment by Synchro** [comment]
Please show the SMTP transcript for this with `$mail->SMTPDebug = 2;`.

**Comment by andreas83** [comment]
how can i output the transcript ?

**Comment by Synchro** [comment]
Add `$mail->SMTPDebug = 2;` to your script, then run it as normal.

**Comment by andreas83** [comment]
for very unknown reasons this did not output everything, but mails are send.

**Comment by Synchro** [comment]
Please post your whole script. Are you using `isSendMail()` or `isMail()`?

**Comment by andreas83** [comment]
i am so sorry, was my fault!
i was just confused because bcc does not change the to recipient...
