### ISSUE TITLE
HTTP 500 error while loading get_auth_token.php

### ISSUE THREAD

**Issue by abdfahim** [PHPMailer/PHPMailer#620]
I have done everything [as mentioned in wiki](https://github.com/PHPMailer/PHPMailer/wiki/Using-Gmail-with-XOAUTH2) to activate Gmail OAuth2. However, whenever I try to paste the script URL (of get_auth_token.php) in my browser, I get a HTTP 500 Internal Server Error.

Inside the get_auth_token.php, I can see a line require 'vendor/autoload.php'. However in my download package, I don't see any folder called vendor.

Can anybody please help?

Thanks,

**Comment by Synchro** [comment]
You need to run `composer install`, as the docs say.
