### ISSUE TITLE
Clearer debugging message for transparent dns redirection issue

### ISSUE THREAD

**Issue by derwentx** [PHPMailer/PHPMailer#621]
Hey,
This is a great bit of PHP that I'm very pleased with, however I would like to request a feature that could have saved me and lots of other people on websites hosted by shoddy hosting companies hours of time debugging their email.
Would it be possible to add a feature that detects that the server they trying to connect to (e.g.  smtp.gmail.com) has a different TLD than the server that they are actually connecting to (e.g. shoddy-hosting-company.com) by reading the output of the mail session? if so then when it can't authenticate, PHPMail could output a more useful message like "error: transparent redirection" that could help users identify the cause of their problem more easily.
I'm willing to donate my time and PHP skills to this cause, just show me where to start.
Thanks.

**Comment by Synchro** [comment]
The way to deal with this is simply to enable TLS and verify your connection (which PHP does automatically as of 5.6). It will fail to connect if the cert doesn't match. This is a much more reliable check that simply matching hostnames to greeting messages, since they can be faked.
