### ISSUE TITLE
Essentials files only for prod

### ISSUE THREAD

**Issue by fabio-coolshop** [PHPMailer/PHPMailer#624]
as in the title, when you run "composer install" it would be better to just download files useful in production.

thanks for your work :)

**Comment by Synchro** [comment]
As far as I'm aware, composer doesn't have that functionality - all you can specify is the package and its version. PHPMailer is trivially small so it's really not worth worrying about - it's more of an issue with big things like symfony that download hundreds of megabytes of scripts.
