### ISSUE TITLE
In Plesk 12.5.30 Ubuntu 14.04 php 7.0.2 can't sent message 

### ISSUE THREAD

**Issue by ludah2008** [PHPMailer/PHPMailer#625]
Testing php mailer on plesk 12.5.30, its can set mails on php7, php5.6. Its can only sent it on php 5.5,
Please can some one help me out

**Comment by Synchro** [comment]
You need to be more specific. What happens when you try to send? What version of PHPMailer? What errors appear or are logged? Have you configured SSL correctly? Have you read [the troubleshooting docs](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting) and done all it suggests?

**Comment by ludah2008** [comment]
Am using Lets Encrypt SSL

this is what i get when i use PHP version 5.6.17 and Version 7.0.2

`2016-02-09 15:24:10 Connection: opening to smtp.forestbookofrecords.com:587, timeout=300, options=array ( ) 2016-02-09 15:24:10 Connection: opened 2016-02-09 15:24:10 SERVER -> CLIENT: 220 vps67157.vps.ovh.ca ESMTP Postfix (Ubuntu) 2016-02-09 15:24:10 CLIENT -> SERVER: EHLO test.forestbookofrecords.com 2016-02-09 15:24:10 SERVER -> CLIENT: 250-vps67157.vps.ovh.ca 250-PIPELINING 250-SIZE 10240000 250-ETRN 250-STARTTLS 250-ENHANCEDSTATUSCODES 250-8BITMIME 250 DSN 2016-02-09 15:24:10 CLIENT -> SERVER: STARTTLS 2016-02-09 15:24:10 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS 2016-02-09 15:24:10 SMTP Error: Could not connect to SMTP host. 2016-02-09 15:24:10 CLIENT -> SERVER: QUIT 2016-02-09 15:24:10 SERVER -> CLIENT: KGA�V>��Kw"�u\���j7�>ɒzyz��,c(��ܷ0��F� ��-�l�z4�H��ݫ��w'm��,�F���Ha/���*�e�׫_�E�ԓ�̄eH>�=�}<2�� �J6��b-��2~<$Y��2���C�St/.bo:�p54kO�l*#S`�����N�r�A.�gt��t*��y!a�v��S� �8y��u�w�S6���_{(1�G��K��~��`w=A�Pk�!o[$x�ҤM�|���j/�>�&�A}9`0 ]�Xn�� �1LM�R��U�-{ 5=KGW�v��]�[���̪ 2016-02-09 15:24:10 SMTP ERROR: QUIT command failed: KGA�V>��Kw"�u\���j7�>ɒzyz��,c(��ܷ0��F� ��-�l�z4�H��ݫ��w'm��,�F���Ha/���*�e�׫_�E�ԓ�̄eH>�=�}<2�� �J6��b-��2~<$Y��2���C�St/.bo:�p54kO�l*#S`�����N�r�A.�gt��t*��y!a�v��S� �8y��u�w�S6���_{(1�G��K��~��`w=A�Pk�!o[$x�ҤM�|���j/�>�&�A}9`0 ]�Xn�� �1LM�R��U�-{ 5=KGW�v��]�[���̪ 2016-02-09 15:24:10 Connection: closed 2016-02-09 15:24:10 SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting `

**Comment by Synchro** [comment]
You're serving a self-signed cert so it's [failing verification](https://ssl-tools.net/mailservers/smtp.forestbookofrecords.com).

**Comment by ludah2008** [comment]
But its works with php 5.5.9 so why

**Comment by Synchro** [comment]
Because, in a change from 5.5, PHP 5.6 defaults to verifying SSL certificates, as it says in the guide.

**Comment by ludah2008** [comment]
can u explain feather, I dont get you sir

**Comment by ludah2008** [comment]
Even if am not using SSL its still not working on php 7 and 5.6

**Comment by Synchro** [comment]
It's in [the PHP 5.6 upgrade docs](http://php.net/manual/en/migration56.incompatible.php). PHPMailer uses opportunistic TLS - if you don't specify to use TLS, but the server advertises it, it enables it automatically. You can disable that by setting `$mail->SMTPAutoTLS = false`, but it's a bad idea to do that.

Fix your cert, and all will work, like the docs say.

**Comment by freultwah** [comment]
However, Let's Encrypt certificates (which the poster uses) are *not* self-signed and their root CA is definitely in the ca_root_nss package. I have the same issue with PHPlist. The certificates are all good, I've double checked the settings and PHP does have access to them, and I still get the exact same results as the original poster.

**Comment by Luisinho77** [comment]
Hey! 

I've got some news for you,  please read it, this really  matters a lot! Please read here <http://full.yadlin.org/e4nurfc>

ljlorente
