### ISSUE TITLE
CCB don't hide the emails

### ISSUE THREAD

**Issue by davideng14** [PHPMailer/PHPMailer#627]
I'm sending emails, these are delivered to the recipients, but when I add address with blind these emails address aren't hidden and appear into the "To" bar.

my specifications are: 

Windows 7 
XAMPP Server
 PHP 5.4.7

**Comment by Synchro** [comment]
Your code? I assume you're running latest PHPMailer (5.2.14)? You're also running an old and insecure version of PHP.

**Comment by davideng14** [comment]
$mail = new PHPMailer();
$mail->isSMTP();                                // Set mailer to use SMTP
$mail->Host = $this->config['host'];  				// Specify main and backup SMTP servers
$mail->SMTPAuth = $this->config['SMTPAuth'];          // Enable SMTP authentication
$mail->Username = $this->config['username'];          // SMTP username
$mail->Password = $this->config['password'];  		// SMTP password
$mail->SMTPSecure = $this->config['SMTPSecure'];
$mail->setFrom('info@example.com');
$mail->isHTML(true); 
$mail->Subject = 'TEST '; //Set Subject
$mail->Body = $message;
$mail->addAddress('example@something.com');
$mail->AddBBC('examplehidden@something.com');

if($mail->send())
{
     echo 'SUCCESS';
}else{
    echo 'ERRORS '.$mail->ErrorInfo;
}

**Comment by Synchro** [comment]
Can you set `SMTPDebug = 2` and post the output (edit addresses if needed).
