### ISSUE TITLE
SMTP ERROR: Failed to connect to server: Connection refused (111)

### ISSUE THREAD

**Issue by trekforall** [PHPMailer/PHPMailer#628]
When I used examples gmail.php  (Trying to send mail using gmail account)I get following error message.
" SMTP ERROR: Failed to connect to server: Connection refused (111)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting"
My code in gamil.php was
<?php
/**
 * This example shows settings to use when sending via Google's Gmail servers.
 */

//SMTP needs accurate times, and the PHP time zone MUST be set
//This should be done in your php.ini, but this is how to do it if you don't have access to that
date_default_timezone_set('Etc/UTC');

require '../PHPMailerAutoload.php';

//Create a new PHPMailer instance
$mail = new PHPMailer;

//Tell PHPMailer to use SMTP
$mail->isSMTP();

//Enable SMTP debugging
// 0 = off (for production use)
// 1 = client messages
// 2 = client and server messages
$mail->SMTPDebug = 2;

//Ask for HTML-friendly debug output
$mail->Debugoutput = 'html';

//Set the hostname of the mail server
//$mail->Host = 'tls://smtp.gmail.com:587';
$mail->Host = 'smtp.gmail.com';
// use
// $mail->Host = gethostbyname('smtp.gmail.com');
// if your network does not support SMTP over IPv6

//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
$mail->Port = 587;

//Set the encryption system to use - ssl (deprecated) or tls
$mail->SMTPSecure = 'tls';

//Whether to use SMTP authentication
$mail->SMTPAuth = false;

//Username to use for SMTP authentication - use full email address for gmail
$mail->Username = "mymailid@gmail.com";

//Password to use for SMTP authentication
$mail->Password = "mypassword";

//Set who the message is to be sent from
$mail->setFrom('mymailid@gmail.com', 'First last');

//Set an alternative reply-to address
$mail->addReplyTo('mymailid@gmail.com', 'First last');

//Set who the message is to be sent to
$mail->addAddress('sendmail@gmail.com', 'first last');

//Set the subject line
$mail->Subject = 'PHPMailer GMail SMTP test';

//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body
$mail->msgHTML(file_get_contents('contents.html'), dirname(__FILE__));

//Replace the plain text body with one created manually
$mail->AltBody = 'This is a plain-text message body';

//Attach an image file
$mail->addAttachment('images/phpmailer_mini.png');

//send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}

**Comment by Synchro** [comment]
Please read the docs that the error message pointed you at.

**Comment by umendrap** [comment]
SMTP ERROR: Failed to connect to server: Connection refused (111)SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Paulens007** [comment]
same here, how to fix ?

**Comment by Synchro** [comment]
Same way everyone else does; read the docs, do what it says.

**Comment by Paulens007** [comment]
SMTP ERROR: Failed to connect to server: Connection refused (111)SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
Your network is preventing you from connecting, or you’re trying to connect to something that is not a mail server. It’s not a client code problem. Read the docs it points to for more info.

**Comment by meprasetyo** [comment]
2020-11-11 14:15:39 SMTP ERROR: Failed to connect to server: Connection refused (111)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Gagal

**Comment by Synchro** [comment]
Please read the thread before posting identical questions.
