### ISSUE TITLE
Avoid Duplicate Headers

### ISSUE THREAD

**Issue by john-mcgowan-wowza** [PHPMailer/PHPMailer#630]
I'm using PHPMailer in an environment where I've already got a complete raw message built and waiting to get sent.  I'm Using PHPMailer to get the message content out of a DB and over to an SMTP server.  When doing that I'm getting errors from the SMTP server we're connecting to (understandably) because we have multiple '**Content-Type**' and '**MIME-Version**' headers.

I've modified the PHPMailer class to refrain from adding MIME-Version and Content-Type headers IF those headers were already specified with a call to **addCustomHeader**();

Would this sort of feature be desirable to have in the official repository?

I get the sense that PHPMailer doesn't intend to support the use case of someone who has already built a complete RAW mime message, but this little feature that stops PHPMailer from writing these two headers if they were already written as a custom header seems to do a pretty good job of letting me use it that way.

/John

**Comment by Synchro** [comment]
Yes, PHPMailer doesn't really intend to support sending raw messages - you're better off storing the component pieces and constructing on send, or implementing your own transport using the SMTP class and avoiding the PHPMailer class itself - and that would be a valuable PR!

You can already set the content type header directly, and the MIME header is never different so you shouldn't need to add them as custom headers anyway. Many headers are allowed to have duplicates, so this fudging is quite a can of worms.

**Comment by john-mcgowan-wowza** [comment]
Thanks, that's what I was thinking, which is why I didn't go straight to a pull request.

/John
