### ISSUE TITLE
upgrading to 5.2.14

### ISSUE THREAD

**Issue by tetsh** [PHPMailer/PHPMailer#631]
i had this function in the old version and everything working fine 

```
if ($found_smtp_account) {
				//what server to send the email to
				$this->phpmailer->Host 		= $smtp['hostname'];
				$this->phpmailer->Mailer 	= 'smtp';
								
				//setup authentication if required
				if ($smtp['authentication']) {
					$this->phpmailer->SMTPAuth = true;     // turn on SMTP authentication
					$this->phpmailer->Username = $smtp['username'];
					$this->phpmailer->Password = $smtp['password'];
				}
			}
```

after i upgrading to 5.2.14 it didn't work anymore

**Comment by Synchro** [comment]
Well there's nothing wrong with this code (though you should avoid setting `Mailer` directly - call `isSMTP()` instead), so this is not where you problem is. You don't say what the actual problem is, nor do you provide any debug output, so there's nothing for me to go on here.
