### ISSUE TITLE
ERRO

### ISSUE THREAD

**Issue by agenciahouse** [PHPMailer/PHPMailer#634]
`Parse error: syntax error, unexpected T_USE, expecting T_FUNCTION in /home/ebven234/public_html/vigor/phpmailer/get_oauth_token.php on line 37`

**Comment by Synchro** [comment]
It looks like you have not loaded the oauth2 packages from composer, or you're using an old version of PHP.

**Comment by agenciahouse** [comment]
Não entendi como carregar o Composer. (I did not understand how to load the Composer.)

**Comment by Synchro** [comment]
You need to [read the docs](https://getcomposer.org).
