### ISSUE TITLE
DKIM private key, why only file source is possible

### ISSUE THREAD

**Issue by ivantcholakov** [PHPMailer/PHPMailer#637]
Currently when a message is signed DKIM_private setting allows only a path to the file containing the private key to be set.

Is it good somehow private key to be passed directly by its content? I think about the possibility the private key to be kept also within configuration file or within encrypted setting within a database.

**Comment by Synchro** [comment]
It's just because the openssl function that is used in DKIM signing requires a path to the key and doesn't accept a string, so it's better to leave control over where the file is written to you rather than trying to figure out somewhere safe to write it.

**Comment by ivantcholakov** [comment]
Are you sure?
https://github.com/PHPMailer/PHPMailer/blob/master/class.phpmailer.php#L3657

**Comment by ivantcholakov** [comment]
Actually, it is possible. http://php.net/manual/bg/wrappers.data.php

```php
echo file_get_contents('data://text/plain;base64,SSBsb3ZlIFBIUAo=');
```
