### ISSUE TITLE
Connecting with SMTP and TLS - get_lines() hangs up

### ISSUE THREAD

**Issue by ozzi-** [PHPMailer/PHPMailer#638]
Edit:
whoops, saw https://github.com/PHPMailer/PHPMailer/issues/604 a bit too late ... However the workaround there didn't help either ...

Hi

I tried to use PHPMailer with my Hoster, but to no avail.
The script just hangs up at:
`            $str = @fgets($this->smtp_conn, 515);`
in class.smtp.php.
This happens when get_lines() is called the first time at
```
 // Get any announcement
        $announce = $this->get_lines();
        $this->edebug('SERVER -> CLIENT: ' . $announce, self::DEBUG_SERVER);
        return true;
```

Any ideas?

My settings:
```
            $mail->SMTPAuth   = true;                 
            $mail->SMTPSecure = 'tls';                  
            $mail->Host       = 'smtp.easyname.com';      
            $mail->Port       = '465';                
            $mail->Username   = 'mailboxname';
            $mail->Password   = 'pw pw pw ';
            $mail->SetFrom('[MY-ADDRESS]', 'ADDRESS');
            $mail->Subject    = 'Welcome';
            $mail->MsgHTML("Test");
            $mail->AddAddress("mail@mail.tld");
            $mail->Send();

```

**Comment by Synchro** [comment]
This is because you're trying to use explicit SSL on a port expecting implicit. Also, `Port` should be an integer, not a string. So try either `tls` / 587 or `ssl` / 465. Don't mix up the values.

**Comment by ozzi-** [comment]
Wow .. i was off by far.
Thanks a lot and keep up the great work!
