### ISSUE TITLE
Duplicate Attachment when send email using For loop

### ISSUE THREAD

**Issue by tarikhagustia** [PHPMailer/PHPMailer#641]
Hello, Im using your classs, its amazing class, 
but when i trying to send using for loop , it sending attachment twice

**Comment by Synchro** [comment]
I can't tell what's going on if I can't see your code - please post it.

**Comment by tarikhagustia** [comment]
> <?php
> require("classes/mail/PHPMailerAutoload.php");
> 
> 
> $cars = array
>   (
>   array('username' => "firstuser", "email" => "agustia.tarikh150@gmail.com"),
>   array('username' => "seconduser", "email" => "tarikh@si.co.id")
>   
>   );
> 
> 
> 
> $mail = new PHPMailer();
> 
> foreach($cars as $row) {
> 
> 	$email = $row['email'];
> 	$mail->IsSMTP();
> 
> 	$mail->SMTPAuth = true; // enable SMTP authentication
> 
> 	$mail->SMTPSecure = "ssl";
> 
> 	$mail->Host = "plus.smtp.mail.yahoo.com";
> 
> 	$mail->Port = 465; // set the SMTP port
> 
> 	$mail->Username = "myemail";
> 
> 	$mail->Password = "mypassword";
> 
> 	$mail->From = "myemail";
> 
> 	$mail->FromName = "Tarikh Agustia";
> 
> 	$mail->AddAddress("$email");
> 
> 	$mail->Subject = "This Subject";
> 
> 	$mail->Body = "This Body .";
> 
> 	$mail->AddAttachment('file.xlsx', 'This email');
> 
> 	$mail->Send();
> 
> 	echo $mail;
> }
> 	 ?>
> 

i want send thoose email with attachment one by one ..

**Comment by Synchro** [comment]
You've based your code on an obsolete example, so make sure you're using latest PHPMailer.

You're re-using the PHPMailer instance each time around the loop (which is good), but note that `addAddress` and `addAttachment` are both `add` operations, not `set`, so they will accumulate - not only are you sending both attachments the second time, you're also sending them to both users. You should clear them at the end of your loop by calling `clearAttachments()` and `clearAllRecipients()`. Look at the mailing list example in the examples folder.
