### ISSUE TITLE
SMTP Cant connect error if php70-openssl is installed [FreeBSD]

### ISSUE THREAD

**Issue by mike-pt** [PHPMailer/PHPMailer#642]
I was having problems in WP with the smtp plugin.

SMTP mode failed but phpmail worked, though I was crazy for a min there cause there were no network issues, path to sendmail was fine and the smtp host doesn't use encryption...

But looking at the log with debug=4 it seemed to be trying to use STARTTLS.

Also I knew at some point this was working and all I remember doing was installing some php extensions including openssl, so I t got me thinking... 

pkg remove php70-openssl and php-fpm restart fixed it :|

I just reinstalled php70-openssl again and it fails... so that's proof this is the issue.

It seems that if openssl is detect it always attempts STARTTLS even if the server does not support this.

**Comment by scara** [comment]
Try setting [`SMTPAutoTLS`](https://github.com/PHPMailer/PHPMailer/commit/9da56fc1328a72aa124b35) to `false`.

HTH,
Matteo

**Comment by Synchro** [comment]
> It seems that if openssl is detect it always attempts STARTTLS even if the server does not support this.

No, it automatically enables TLS if the server supports it. If the server doesn't support it, you should get a new server, but you can disable this behaviour by doing what @scara said. If your server supports TLS but it's broken (e.g. it's publishing an invalid cert), that's a server problem, not a PHPMailer problem.

**Comment by mike-pt** [comment]
You are correct this was driving me nuts yesterday but I totally missed the "SMTPAutoTLS" option.

I also had false information about the server not supporting STATRTLS, but I double checked my self and ofc as you say it does support STARTTLS but its using a self signed certs (and for another domain)

So sorry about the noise, I should have checked that first.

It would be nice if the wordpress plugin had an options for "SMTPAutoTLS" = yes/no though.

Thanks

**Comment by scara** [comment]
You should open an issue in that WP plug-in giving this issue as reference: that setting should be set to `false`.
IMHO WP admin users could not be expert enough to understand that the library could be configured to automatically use TLS when available: TLS should be configured explicitly when admins know about its full working support.

**Comment by mike-pt** [comment]
Yeah @scara I agree, I was testing outside the plugin to be sure the issue was not wordpress, but I did look into how wordpres/plugin and even wordpress class-phpmailler.php sets it to true.

**Comment by Synchro** [comment]
Why is your mail server publishing an invalid cert anyway? Fix this the right way - get a real cert or disable TLS. It's not as if it will [cost you anything](https://letsencrypt.org). You can also "fix" this by configuring PHP not to check the cert, but that's a broken approach too. PHPMailer's treatment of it is the same as other mail servers.

**Comment by mike-pt** [comment]
@Synchro I'm using letsencrypt already for this wordpress site and others, but this mail server is not "mine" its an old shared mail server, and the cert is not only self signed but it the domain name also doesn't match. The good thing they are moving to Office 365 which is also free for them since this is a ONG :)

So for now the allow self sign setting will have to do.

I'd like to add though that my comments on the setting were for WP/WP plugins, we can easily change this cause PHPMailler does have the settings, WP/most plugins are just not exposing them and worst hard coding defaults and that doesn't seem to be the best approach IMHO, but its certainly not a PHPMailler issue so again sorry for the noise.

**Comment by scara** [comment]
FYI: https://core.trac.wordpress.org/ticket/36125.
