### ISSUE TITLE
DKIM key generator not up to date

### ISSUE THREAD

**Issue by timo002** [PHPMailer/PHPMailer#644]
Hello,

The documentation is pointing to this site for generating DKIM keys.
http://dkim.worxware.com/createkeys.php

However, the keys generated by this script are not working with the latest version of PHPMailer. Probably because this script uses SHA1, and PHPMailer now uses SHA256?

**Comment by Synchro** [comment]
Indeed, those docs are out of date and need removing.

**Comment by Synchro** [comment]
DKIM docs and examples have been updated in the 6.0 branch, including key generation, so there's no longer a need to generate keys on a site you don't control (as if that was a good idea anyway!)
