### ISSUE TITLE
PHPMailer does not send email from gmail smtp with some accounts

### ISSUE THREAD

**Issue by hamedmoody** [PHPMailer/PHPMailer#646]
Hi
i use phpmailer in wp_mail()(wordpress function in plugable.php)
i want to send emails from multi gmail accounts with smtp with Host: smtp.gmail.com, secure: tls, port: 587, but i can send from one account and other accounts can not send email.
what i to do?
Thanks

**Comment by Synchro** [comment]
Read the troubleshooting guide on [the wiki](https://github.com/PHPMailer/PHPMailer/wiki) - you probably have 'less secure apps' enabled on one but not the others.

**Comment by hamedmoody** [comment]
Thanks you solved my problem, exactly related to 'less secure apps'.
