### ISSUE TITLE
Mailer Error: Could not instantiate mail function.

### ISSUE THREAD

**Issue by adrianrios25** [PHPMailer/PHPMailer#648]
Got this error when sending big file size attachment like 16MB or bigger.

I already set the post_max_size and max_execution_time to higher value.

I'm using smtp connection to our own web server (not using google or yahoo mail).

Hope someone can help me with this.

**Comment by Synchro** [comment]
Check `memory_limit` too - PHPMailer uses quite a lot when procesing large attachments, and email is really not a good way of transferring large files.

**Comment by elminson** [comment]
You don't say if you restart your service (apache or gnix) to this change take effect. this change need to be done in the /etc/php.ini some web servers not support set this parameter directly in the php script.

**Comment by adrianrios25** [comment]
working great without and with small attachment, I just have problem with big files as mentioned, @elminson I created a php.ini file and checked the phpinfo() and changes are applied.

I will try to increase memory_limit

**Comment by adrianrios25** [comment]
okay, It turns out that I also have problem using SMTP, this error could be related right? What I mean is that I should be using smtp to send big file attachment? 

I tried to telnet my server and port and it connected with no error.
I also tried using $mail->Host = gethostbyname();

This is the error:

2016-03-08 05:33:29	Connection: opening to 212.227.15.167:587, t=10, opt=array ( ) 2016-03-08 05:33:39	SMTP ERROR: Failed to connect to server: Connection timed out (110) SMTP connect() failed.

**Comment by adrianrios25** [comment]
2016-04-13 04:06:51	SMTP ERROR: Failed to connect to server: Connection timed out (110) SMTP connect() failed.

Still getting that error despite following the example for gmail and I can also ping and telnet host

require '../phpmailer/PHPMailerAutoload.php';
		
$mail = new PHPMailer;
$mail->IsHTML(true);    
		
$mail->IsSMTP(); // Use SMTP
$mail->SMTPDebug   = 2; // 2 to enable SMTP debug information
$mail->Host        = "smtp.gmail.com"; // Sets SMTP server
$mail->Port        = 587; // set the SMTP port
$mail->SMTPSecure  = "tls"; //Secure conection	
$mail->SMTPAuth    = true; // enable SMTP authentication
$mail->Username    = 'my@gmail.com'; // SMTP account username
$mail->Password    = '***'; // SMTP account password
$mail->SetFrom("my@gmail.com");

**Comment by adrianrios25** [comment]
This error occur only if IsSMTP() is enabled.

**Comment by Synchro** [comment]
Well obviously - an SMTP problem will only occur when your'e using SMTP!

What happens when you do this:

    openssl s_client -starttls smtp -crlf -connect smtp.gmail.com:587
