### ISSUE TITLE
XOauth2

### ISSUE THREAD

**Issue by pfaquart** [PHPMailer/PHPMailer#649]
Everything was functioning fine until about noon today. I now don't see XOAUTH2 as an available option in my server responses, only AUTH PLAIN LOGIN and I get error:

SERVER -> CLIENT: 250-main.reidash.com Hello awb.reidash.com [209.95.44.96]250-SIZE 52428800250-8BITMIME250-PIPELINING250-AUTH PLAIN LOGIN250 HELP
SMTP Error: Could not authenticate.
CLIENT -> SERVER: QUIT

Any ideas here? All secrets and keys have been updated in trying to resolve the issue, no change.

Script options set as:

$mail->Host = 'smtp.gmail.com';
$mail->Port = 587;
$mail->SMTPSecure = 'tls';
$mail->SMTPAuth = true;
$mail->AuthType = 'XOAUTH2';

php Version: 5.4.43

**Comment by Synchro** [comment]
You're asking PHPMailer to connect to `smtp.gmail.com`, but the HELO message you receive says it's `main.reidash.com`. Conclusion: your outbound mail connections are being redirected to your ISP's mail server, which of course uses different authentication. This is covered [in the docs](https://github.com/PHPMailer/PHPMailer/wiki).

Also PHP 5.4 is no longer supported; you should upgrade.
