### ISSUE TITLE
Fatal error: Class 'SMTP' not found in ---- /class.phpmailer.php on line 1439

### ISSUE THREAD

**Issue by pla2todkrob** [PHPMailer/PHPMailer#650]
help me pls 
I'm want to send mail after insert data into database 
but show error Fatal error: Class 'SMTP' not found in ---- /class.phpmailer.php on line 1439

after error I go to check your file class.phpmailer.php on line 1439
have code 
public function getSMTPInstance()
    {
        if (!is_object($this->smtp)) {
            $this->smtp = new SMTP;
        }
        return $this->smtp;
    }

on line 1439
$this->smtp = new SMTP;

I don't get it error
Sorry if I do not explain
I am a foreigner and I was young.

**Comment by Synchro** [comment]
Read the README about how to use PHPMaielr; you need to load the autoloader.
