### ISSUE TITLE
PHPMailer setting for individual emails is sending empty To: fields

### ISSUE THREAD

**Issue by sanjib-dev** [PHPMailer/PHPMailer#652]
Hi,
I have been using the PHPMailer with smtp. And when sending bulk emails To fields of the send email is getting blank.
If the mail is not using SMTP  i.e default php mail, then its working fine.
is there is a fix for this?
found some info from stackoverflow:
http://stackoverflow.com/questions/5380193/phpmailer-setting-for-individual-emails-is-sending-empty-to-fields

**Comment by Synchro** [comment]
That SO question is using a very old version of PHPMailer, and the chosen answer has several major errors. Are you using the latest version (5.2.14)?

**Comment by sanjib-dev** [comment]
using the 5.2.14

**Comment by Synchro** [comment]
I just checked on the code and SMTP sending does indeed not use singleTo. The right way to send bulk messages to individual addresses is like [the mailing list example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps) does.

**Comment by sanjib-dev** [comment]
Actually sending emails from Amazon. so just want to call the send() function with some batches of mail.
and not per single recipients

**Comment by Synchro** [comment]
You don't gain anything by doing that - it still has to do a complete SMTP transaction for every message.

**Comment by sanjib-dev** [comment]
so what i am trying to achieve is not really possible?

**Comment by Synchro** [comment]
What singleTo does is functionally identical to sending individual messages, so it makes no difference. It will not change the number of calls to the server, web or mail. The only thing that changes is where the loop over your list occurs.

**Comment by sanjib-dev** [comment]
fully understand your point. but the thing I want to achieve is not possible then..

**Comment by Synchro** [comment]
Of course it's possible - do what I said, it achieves exactly the same thing as you're asking for, just without using the singleTo functionality.

**Comment by sanjib-dev** [comment]
so call the send() function call for every email...thus call the amazon API for every user...and not for a batch of emails?
By using SingleTo, I want to hide the user email ids in the mail from each other so that data is kept secret and at the same time reduce the call to the amazon API..

**Comment by Synchro** [comment]
You're doing it wrong. Using singleTo does not hide to addresses, nor does it send a single message to multiple recipients in one go. What you need is BCC. Send the message to yourself, and put all the real recipients in BCC (use `addBCC()`). That way you will send a single message that the mail server will expand to the full BCC list, and the recipients will not be able to see each other's addresses.

If you want to send different content to each recipient (e.g. per-user unsubscribe links), you **must** send messages individually; with BCC all recipients receive identical messages.

**Comment by sanjib-dev** [comment]
yes..but with bcc the TO field in the mail will be the first email id..i.e. the users' email id is nowhere in the to field.

**Comment by Synchro** [comment]
That's why I said send it to yourself - then To and From wil be the same and you don't expose any real recipients. If you want individual To addresses, you **must** send messages individually. There's no way around that - you eitehr have a single message with BCC, and all recepients receive absolutely identical messages, or you send separate messages with different headers or content. This is not a PHPMailer issue, it's just how email works.

**Comment by sanjib-dev** [comment]
yes..I understands your points..thanks for the advice and help..
