### ISSUE TITLE
POP3 and SMTP AUTH

### ISSUE THREAD

**Issue by diegoangc** [PHPMailer/PHPMailer#655]
my mail server is pop3 , I make the authentication pop3 and everything is fine, but when making the utenticacion smtp this fails, I can send emails without SMTP authentication but when I do the authentication , get the error "SMTP connect ( ) failed . "

`    require 'PHPMailerAutoload.php';

    $pop = POP3::popBeforeSmtp("correo.gestionsecretariasdeeducacion.gov.co",110,30,"no-reply@sempalmira.gov.co","xxxxxxxxxxxxxxx",0);
    $mail = new PHPMailer(TRUE);
    
try{    
    $mail->isSMTP();
    $mail->SMTPDebug = 1;
    $mail->Host = 'correo.gestionsecretariasdeeducacion.gov.co';
    $mail->Port = 465;
    $mail->SMTPAuth = true;
    $mail->Username = "no-reply@sempalmira.gov.co";
    $mail->Password = "xxxxxxxxx";      
    $mail->SMTPSecure = 'ssl';
    $mail->WordWrap = 50;
    $mail->isHTML(true);
    $mail->SMTPDebug = true;
    $mail->do_debug = 1;
    $mail->setFrom("no-reply@sempalmira.gov.co", 'Administrador SIPE WEB');
    $mail->addAddress("diego.angc@hotmail.com", "diego perez");
    $mail->Subject = 'Remember Password ';
    $mail->Body    = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
    $mail->AltBody = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
    if($mail->send()) {
        echo 'Se ha enviado el mensaje';
    } else {
        echo $mail->ErrorInfo;
    }  
}catch (phpmailerException $e) {
    echo $e->errorMessage(); 
}catch (Exception $e) {
    echo $e->getMessage(); 
}`

thanks for your great work with these libs =D

**Comment by Synchro** [comment]
Do you really need POP-before SMTP? It's a very old system - I last used it in about 1992!. Usually if you have that, you don't need to authenticate via SMTP.

To see debug output, don't touch `do_debug`, and set `SMTPDebug = 2`.

**Comment by diegoangc** [comment]
I deleted the connection POP-before-SMTP and now I have the following code:

`
require $_SERVER["DOCUMENT_ROOT"].'/realcorreo/PHPMailerAutoload.php';
$mail = new PHPMailer(TRUE);
try{

$mail->isSMTP();
$mail->SMTPDebug = 2;
$mail->Host = 'correo.gestionsecretariasdeeducacion.gov.co';
$mail->Port = 465;
$mail->SMTPAuth = true;
$mail->Username = "no-reply@sempalmira.gov.co";
$mail->Password = "xxxxxxxxx";

$mail->SMTPSecure = 'ssl';
$mail->WordWrap = 50;
$mail->isHTML(true);
$mail->SMTPDebug = true;
$mail->do_debug = 1;
$mail->setFrom("no-reply@sempalmira.gov.co", 'Administrador SIPE WEB');
$mail->addAddress("diego.angc@hotmail.com", "diego perez");
$mail->Subject = 'Remember Password ';
$mail->Body = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
$mail->AltBody = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
if($mail->send()) {
echo 'Se ha enviado el mensaje';
} else {
echo $mail->ErrorInfo;
}

}catch (phpmailerException $e) {
echo $e->errorMessage(); 
}catch (Exception $e) {
echo $e->getMessage(); 
}

`

ERROR: 2016-03-15 12:47:13	Connection: opening to ssl://correo.gestionsecretariasdeeducacion.gov.co:465, timeout=300, options=array ( ) 2016-03-15 12:47:13	SMTP ERROR: Failed to connect to server: Permission denied (13) 2016-03-15 12:47:13	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
Well, "permission denied" looks pretty clear. you have soe kind of permissions issue with you PHP installation. Fix that and it will work. It would help if you did what I suggested, you'll get more feedback.
