### ISSUE TITLE
PHPMailer::__destruct(): Maybe unnecessary check is there

### ISSUE THREAD

**Issue by ivantcholakov** [PHPMailer/PHPMailer#658]
This is the destructor:

```php
    /**
     * Destructor.
     */
    public function __destruct()
    {
        //Close any open SMTP connection nicely
        if ($this->Mailer == 'smtp') {
            $this->smtpClose();
        }
    }
```

Here is the method smtpClose():

```php
    /**
     * Close the active SMTP session if one exists.
     * @return void
     */
    public function smtpClose()
    {
        if ($this->smtp !== null) {
            if ($this->smtp->connected()) {
                $this->smtp->quit();
                $this->smtp->close();
            }
        }
    }
```

I think that the check if ($this->Mailer == 'smtp') within the destructor is not necessary. Theoretically this check can stop closing live SMTP connection if in the same script the mailer was used also with another non-SMTP account.

I think that if ($this->Mailer == 'smtp') can be removed.

**Comment by Synchro** [comment]
Thanks. I cleaned up the instance check to be more accurate too.
