### ISSUE TITLE
Cant connect to server

### ISSUE THREAD

**Issue by luckyrajiv** [PHPMailer/PHPMailer#659]
Hi,

I am not able to connect to server. 
I am able to login into admin mail account at **domain.com/?admin**

But when i visit **mail.domain.com** and try to login,
it says **

> cant connect to server

**

Also, to check things when i logged into admin account, and went to DOMAINS section,
After clicking on mydomains, and try to test, Both IMAP AND SMTP gives this error 
**

> stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known

**

Please need help.

Is this to do with any file permissions. or some other setting issue.

**Comment by Synchro** [comment]
Sounds like the names are wrong, your DNS isn't working, the domain has missing DNS entries, or your network access to them is blocked.
