### ISSUE TITLE
Mailer Error: SMTP connect() failed.

### ISSUE THREAD

**Issue by tankyagnik1911** [PHPMailer/PHPMailer#661]
Hello everyone.
i m trying to send mail through PHPMailer in localhost.
just tried sample code from github.com
but having this error repeatedly.
Message could not be sent.Mailer Error:
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

please help me guys. as soon as possible.
my code is here.
<?php
require '../phpmailer/PHPMailerAutoload.php';

$mail = new PHPMailer;

//$mail->SMTPDebug = 2;                               // Enable verbose debug output

$mail->isSMTP();                                      // Set mailer to use SMTP

$mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers

$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'abc@gmail.com';                 // SMTP username
$mail->Password = '*********';                           // SMTP password
$mail->SMTPSecure = 'ssl';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 465;                                    // TCP port to connect to

$mail->setFrom('mailer@yahoo.com', 'Mailer');
$mail->addAddress('mailer19@gmail.com', 'receiver');     // Add a recipient
//$mail->addAddress('ellen@example.com');               // Name is optional
$mail->addReplyTo('info@example.com', 'Information');
//$mail->addCC('cc@example.com');
//$mail->addBCC('bcc@example.com');

//$mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
//$mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name
$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'Here is the subject';
$mail->Body    = 'This is the HTML message body <b>in bold!</b>';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

if(!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error:<pre>' . $mail->ErrorInfo."</pre>";
} else {
    echo 'Message has been sent';
}
?>

**Comment by Synchro** [comment]
Demanding immediate help when you won't even click a link that tells you how to figure it out isn't going to get you very far.

**Comment by tankyagnik1911** [comment]
@Synchro  I have check that link and all the steps given in that page.

- have checked inclusion of mailer file.
- have checked openssl extension. it is loaded successfully.
-checked dns availability
-checked mail server.

**Comment by tankyagnik1911** [comment]
is it necessary to install local mail server?
any recommended mail server for win7?

**Comment by Synchro** [comment]
>all the steps given in that page

Apart from the fundamental one about turning on debug output so you can see what's happening - you even went so far as to comment it out!!

**Comment by tankyagnik1911** [comment]
hello sir @Synchro 
it worked.
thank you very much.
the problem was that in my account "allow less secure app" setting was disabled i have just enable it and it work.
thanks again :)

**Comment by viniciuspascucci0105** [comment]
Synchro Help me please

I am having problem with send email, it seems that has an error on SMTP port, i don't know
The following message appears for me

2017-11-08 18:00:12 SERVER -> CLIENT: 220 smtp.gmail.com ESMTP g8sm3148956qtg.23 - gsmtp
2017-11-08 18:00:12 CLIENT -> SERVER: EHLO localhost
2017-11-08 18:00:12 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [189.46.135.27]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250 SMTPUTF8
2017-11-08 18:00:12 CLIENT -> SERVER: STARTTLS
2017-11-08 18:00:12 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
SMTP Error: Could not connect to SMTP host.
2017-11-08 18:00:12 CLIENT -> SERVER: QUIT
2017-11-08 18:00:12 SERVER -> CLIENT: 
2017-11-08 18:00:12 SMTP ERROR: QUIT command failed: 
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

I already read the troobleshooting guide and nothing resolve =(

Could you help me to resolve this problem?

**Comment by Synchro** [comment]
You have a TLS problem. This is covered in the guide, so do what it says carefully (`SMTPDebug = 3` may help) - I'm not about to tell you anything different to what's in there.

Also, don't hijack other people's issues with different problems, especially when they are closed.

**Comment by dianally19** [comment]
Hello sir , i have a problem with SMTP.
Yesterday i'm making contact to send email in my website with SMTP and success but now my website can't send a email. 

Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting.

Please help me . Thanks
