### ISSUE TITLE
Autoloader fails

### ISSUE THREAD

**Issue by zacaro** [PHPMailer/PHPMailer#662]
Hi,

the autoloader URL is giving a 404.
![autoloader](https://cloud.githubusercontent.com/assets/18011871/13959934/68df6e16-f056-11e5-81b1-fea3b1401f06.PNG)

**Comment by Synchro** [comment]
That's not very useful without knowing where the link to that location is!

I fixed some broken links in the readme, so I assume that's what you meant.

**Comment by zacaro** [comment]
You are right, I didn't mentioned that the broken link was in the github project, in the Minimal Installation section.

"For all of these, we recommend you use the autoloader..." That link.

It's solved right now. 

Regards
