### ISSUE TITLE
Empty atteachments in CC and BCC

### ISSUE THREAD

**Issue by sokolukasz** [PHPMailer/PHPMailer#663]
When we send a message with cc and bcc, attachments to cc and bcc are empty.

**Comment by Synchro** [comment]
Are you sending to CC and BCC *only* (no *To*)? Can you post an example SMTP transcript of this happening (set `SMTPDebug = 2`) using a tiny attachment?

**Comment by sokolukasz** [comment]
[Oferta - test.txt](https://github.com/PHPMailer/PHPMailer/files/184645/Oferta.-.test.txt)

**Comment by sokolukasz** [comment]
[Oferta - test1.txt](https://github.com/PHPMailer/PHPMailer/files/184652/Oferta.-.test1.txt)

**Comment by Synchro** [comment]
That doesn't make much sense. The transcript contains this:

```
2016-03-22 17:36:58	CLIENT -> SERVER: MAIL FROM:
2016-03-22 17:36:58	SERVER -> CLIENT: 250 2.1.0 Ok
2016-03-22 17:36:58	CLIENT -> SERVER: RCPT TO:
2016-03-22 17:36:58	SERVER -> CLIENT: 250 2.1.5 Ok
2016-03-22 17:36:58	CLIENT -> SERVER: RCPT TO:
2016-03-22 17:36:58	SERVER -> CLIENT: 250 2.1.5 Ok
```
Did you remove the parts after the Client lines?

The message itself does not contain a CC header, and the From and Reply-to headers do not contain email addresses. It would help to see your code (remove passwords). BTW the transcript contains easily-decoded passwords (in the lines containing `CLIENT: 334`) so I suggest you edit them out and/or change your passwords.

**Comment by Synchro** [comment]
Your updated transcript contains another `RCPT TO` line with no arguments. As shown, this message will not be delivered to anyone.

**Comment by sokolukasz** [comment]
Are you sure that phpmailer should send attechments when is set CC and BCC, in my software attechments are sending fine to To: and i can open them, but in email CC, and BCC attechment is sent but i cant open it.

**Comment by sokolukasz** [comment]
`$mail = new PHPMailer();
			$mail->isSMTP();
			$mail->SMTPDebug = 2;
//			dump($this->sendMailParams);
			
			if(preg_match('@ssl:\/\/@', $this->sendMailParams['host']))
			{
				$mail->SMTPSecure = 'ssl';
			}
			elseif(preg_match('@tls:\/\/@',$this->sendMailParams['host']))
			{
				$mail->SMTPSecure = 'tls';
			}
			
			$mail->SMTPOptions = array(
				'ssl' => array(
					'verify_peer' => false,
					'verify_peer_name' => false,
					'allow_self_signed' => true
				)
			);
			
			$host = pathinfo($this->sendMailParams['host']);
			$mail->Host = $host['basename'];  // Specify main and backup SMTP servers
			$mail->SMTPAuth = $this->sendMailParams['auth']?true:false;                               // Enable SMTP authentication
			$mail->Username = $this->sendMailParams['username'];                 // SMTP username
			$mail->Password = $this->sendMailParams['password'];                           // SMTP password
			$mail->Port = $this->sendMailParams['port'];
			$mail->CharSet = "UTF-8";
			$mail->contentType = $this->contentType;
			$mail->Subject = $subject;
			
			$mail->isHTML(true);
			$mail->Body = $this->content;
			
			$from = IMAIL::getFullyEmail($from);
			$mail->setFrom($from['email'], $from['name']);
			
			if(is_array($to))
			{
				foreach($to as $address)
				{
					$address = IMAIL::getFullyEmail($address);
					$mail->addAddress($address['email'], $address['name']);
				}
			}
			else
			{
				$to = IMAIL::getFullyEmail($to);
				$mail->addAddress($to['email'], $to['name']);
			}
			
			//odpowiedź do
			if(isset($customHeaders['Replay-To']))
			{
				$replayTo = IMAIL::getFullyEmail($customHeaders['Replay-To']);
				$mail->addReplyTo($replayTo['email'], $replayTo['name']);
				unset($customHeaders['Replay-To']);
			}
			if(isset($customHeaders['Cc']))
			{
				$ccEmail = IMAIL::getFullyEmail($customHeaders['Cc']);
				$mail->addCC($ccEmail['email'], $ccEmail['name']);
				unset($customHeaders['Cc']);
			}
			if(isset($customHeaders['Bcc']))
			{
				$bccEmail = IMAIL::getFullyEmail($customHeaders['Bcc']);
				$mail->addBCC($bccEmail['email'], $bccEmail['name']);
				unset($customHeaders['Bcc']);
			}
			
			switch($this->contentType)
			{
				case 'text/html':
					$mail->isHTML(true);
					$mail->Body = $this->content;
//					$mail->AltBody = strip_tags($this->content);
					break;
				case 'text/plain':
					$mail->isHTML(false);
					$mail->Body = $this->content;
					break;
				default:
					throw new Exception('Niezidentyfikowany typ treści dla nagłówka('.$this->contentType.').');
			}
			
			if(is_array($customHeaders))
			{
				foreach($customHeaders as $name => $val)
				{
					$mail->addCustomHeader($name, $val);
				}
			}
			
			if(count($attachment))//dodanie załączników
			{
				foreach($attachment AS $file)
				{					
					$mail->addAttachment($file['file'], $file['name']);//dodanie załącznika
				}
			}
			
			if(!$mail->send()) 
			{
				throw new Exception($mail->ErrorInfo);
			}
			else 
			{
				return true;
			}`

**Comment by sokolukasz** [comment]
2016-03-22 17:36:58 CLIENT -> SERVER: MAIL FROM:
2016-03-22 17:36:58 SERVER -> CLIENT: 250 2.1.0 Ok
2016-03-22 17:36:58 CLIENT -> SERVER: RCPT TO:
2016-03-22 17:36:58 SERVER -> CLIENT: 250 2.1.5 Ok
2016-03-22 17:36:58 CLIENT -> SERVER: RCPT TO:
2016-03-22 17:36:58 SERVER -> CLIENT: 250 2.1.5 Ok

They are not empty - i copy debug from browser, and browser doesnt show it <lukasz.s@agendo.pl> etc.

**Comment by sokolukasz** [comment]
Can i add more then one CC recipient ?

**Comment by sokolukasz** [comment]
Please try to test add atteachment (PDF) add send it to CC nad BCC and try to open this attechment in both recipients.

**Comment by sokolukasz** [comment]
[oferta-test2.txt](https://github.com/PHPMailer/PHPMailer/files/185028/oferta-test2.txt)

**Comment by Synchro** [comment]
That looks better - and it also looks correct. The exact same message is sent to all of To, BCC and CC addresses - notice that at the SMTP level it does not distinguish between them - they are just all `RCPT TO` addresses of equal status. Try swapping the addresses around to check for client-side problems.

You can set as many CC and BCC recipients as your mail server will let you.
