### ISSUE TITLE
SMTP Error: Could not authenticate

### ISSUE THREAD

**Issue by sopharat** [PHPMailer/PHPMailer#667]
SERVER -> CLIENT: 220 smtp.gmail.com ESMTP s87sm12973072pfa.89 - gsmtp
CLIENT -> SERVER: EHLO localhost
SERVER -> CLIENT: 250-smtp.gmail.com at your service, [202.8.72.140]250-SIZE 157286400250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: STARTTLS
SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
CLIENT -> SERVER: EHLO localhost
SERVER -> CLIENT: 250-smtp.gmail.com at your service, [202.8.72.140]250-SIZE 157286400250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: AUTH LOGIN
SERVER -> CLIENT: 334 VXNlcm5hbWU6
CLIENT -> SERVER: c3R1ZGVudC5mZWVkc0BnbWFpbC5jb20=
SERVER -> CLIENT: 334 UGFzc3dvcmQ6
CLIENT -> SERVER: c3R1ZGVudGZlZWRzMTY4
SERVER -> CLIENT: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbuI534-5.7.14 28ynf6cEicb_mHeCS8pnax0ijtXQRr10IitCv4AaxEfBvW71KwctSvosEKFhcCHXuL9p03534-5.7.14 Q16-5NGasKSwT3ywIXWMITPFibvrqOMLJOJ8zti2qo1ooIjIhpnAfZ1PRtNchh2f5h4JWG534-5.7.14 TdK3ubf9T3KwKZUQrWirYDpGcvxXEQPWY4UiavV_1KIoGx1UvDDrfyqd0Sj5zJNXYa_VvW534-5.7.14 C_L00pY8zahyh2U4NZ2TM12QZuq_w> Please log in via your web browser and534-5.7.14 then try again.534-5.7.14 Learn more at534 5.7.14 https://support.google.com/mail/answer/78754 s87sm12973072pfa.89 - gsmtp
SMTP ERROR: Password command failed: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbuI534-5.7.14 28ynf6cEicb_mHeCS8pnax0ijtXQRr10IitCv4AaxEfBvW71KwctSvosEKFhcCHXuL9p03534-5.7.14 Q16-5NGasKSwT3ywIXWMITPFibvrqOMLJOJ8zti2qo1ooIjIhpnAfZ1PRtNchh2f5h4JWG534-5.7.14 TdK3ubf9T3KwKZUQrWirYDpGcvxXEQPWY4UiavV_1KIoGx1UvDDrfyqd0Sj5zJNXYa_VvW534-5.7.14 C_L00pY8zahyh2U4NZ2TM12QZuq_w> Please log in via your web browser and534-5.7.14 then try again.534-5.7.14 Learn more at534 5.7.14 https://support.google.com/mail/answer/78754 s87sm12973072pfa.89 - gsmtp
SMTP Error: Could not authenticate.
CLIENT -> SERVER: QUIT
SERVER -> CLIENT: 221 2.0.0 closing connection s87sm12973072pfa.89 - gsmtp
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
Unfortunately I can't help you learn to read.
