### ISSUE TITLE
Keep getting error "Message could not be sent.Mailer Error: Could not instantiate mail function."

### ISSUE THREAD

**Issue by conaris** [PHPMailer/PHPMailer#670]
Hello, 

I am trying my suggest.php file so it can retrieve user input from an html5 form and then send the details to a personal email address.

I keep getting this error ""Message could not be sent.Mailer Error: Could not instantiate mail function."
Also do i need IsSMTP for personal emails accounts?

```
<?php 
ini_set('display_errors', 1);
    require("inc/phpmailer/class.smtp.php");
    require("inc/phpmailer/PHPMailerAutoload.php");
    require("inc/phpmailer/class.phpmailer.php");
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $name = trim(filter_input(INPUT_POST,"name",FILTER_SANITIZE_STRING));
    $email = trim(filter_input(INPUT_POST,"email",FILTER_SANITIZE_EMAIL));
    $details = trim(filter_input(INPUT_POST,"details",FILTER_SANITIZE_SPECIAL_CHARS));

    if ($name == "" || $email == "" || $details == "") {
        echo "Please fill in the required fields: Name, Email and Details";
        exit;
    }
    if ($_POST["address"] != "") {
        echo "Bad form input";
        exit;
    }

    $mail = new PHPMailer;

    if (!$mail->ValidateAddress($email)) {
        echo "Invalid Email Address";
        exit;
    }
    //$mail->IsSMTP();
    $email_body = "";
    $email_body .= "Name: " . $name . "<br>";
    $email_body .= "Email: " . $email . "<br>";
    $email_body .= "Customer Question: " . $details . "<br>";


    $mail->setFrom($email, $name);
    $mail->addAddress('example@example.com', 'Author');     // Add a recipient

    $mail->isHTML(true);                                  // Set email format to HTML

    $mail->Subject = 'Customer Question ' . $name;
    $mail->Body    = $email_body;

    if(!$mail->send()) {
        echo 'Message could not be sent.';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
        exit;
    }


    header("location:suggest.php?status=thanks");
}
?>
```

**Comment by Synchro** [comment]
This is a bit of a mess. You really should base your code on the examples provided with PHPMailer. The only file you need to load is the autoloader - it deals with loading the other files, which is why it's called an autoloader. This is covered in the readme.

Don't use the submitter's address as the From address as it is forging, and will cause bounces. Put your own address in From and put their address in reply-to.

You need to make sure your php.ini settings for your system are correct - if the mail function is not set up (e.g. you don't have a local mail server), PHPMailer can't work using `isMail` (the default).

I recommend using SMTP anyway - it's usually faster and gives you more control and feedback.

**Comment by conaris** [comment]
I removed require("inc/phpmailer/class.smtp.php"); and require("inc/phpmailer/class.phpmailer.php"); from the top, but now it tells me "Fatal error: Uncaught Error: Class 'PHPMailer' not found in "website"address suggest.php: 17"

**Comment by Synchro** [comment]
It sounds like you have two different copies of the PHMailer class. I really recommend using composer for all your libraries, including PHPMailer. It avoids silly problems like this.

**Comment by conaris** [comment]
i forgot to remove the require class.phpmailer.php from my main php, but now i  did it gives me other error line "Fatal error: Uncaught Error: Class 'PHPMailer' not found in /customers/c/2/9/lifeofaris.se/httpd.www/flexboss/suggest.php:17 Stack trace: #0 {main} thrown in /customers/c/2/9/lifeofaris.se/httpd.www/flexboss/suggest.php on line 17"

**Comment by conaris** [comment]
```
<?php 
ini_set('display_errors', 1);
    require("inc/phpmailer/PHPMailerAutoload.php");
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $name = trim(filter_input(INPUT_POST,"name",FILTER_SANITIZE_STRING));
    $email = trim(filter_input(INPUT_POST,"email",FILTER_SANITIZE_EMAIL));
    $details = trim(filter_input(INPUT_POST,"details",FILTER_SANITIZE_SPECIAL_CHARS));
    
    if ($name == "" || $email == "" || $details == "") {
        echo "Please fill in the required fields: Name, Email and Details";
        exit;
    }
    if ($_POST["address"] != "") {
        echo "Bad form input";
        exit;
    }
    $mail = new PHPMailer;
    
    if (!$mail->ValidateAddress($email)) {
        echo "Invalid Email Address";
        exit;
    }
    //$mail->IsSMTP();
    $email_body = "";
    $email_body .= "Name: " . $name . "<br>";
    $email_body .= "Email: " . $email . "<br>";
    $email_body .= "Customer Question: " . $details . "<br>";
    
    
    $mail->setFrom($email, $name);
    $mail->addAddress('arisconstantinou@cytanet.com.cy', 'Author');     // Add a recipient
    
    $mail->isHTML(true);                                  // Set email format to HTML
    
    $mail->Subject = 'Customer Question ' . $name;
    $mail->Body    = $email_body;
    
    if(!$mail->send()) {
        echo 'Message could not be sent.';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
        exit;
    }
    
    
    header("location:suggest.php?status=thanks");
}
?>
```

**Comment by Synchro** [comment]
This problem has nothing to do with the code or PHPMailer; it's about how you have arranged your files. Follow the loading instructions in the readme. If the classes are failing to load it means the autoloader can't find them, or you have some other autoloader that is interfering with the process.

**Comment by conaris** [comment]
I read the Readme and follow your comments in this conversation but still get the error "Fatal error: Uncaught Error: Class 'PHPMailer' not found in /customers/c/2/9/lifeofaris.se/httpd.www/flexboss/suggest.php:17 Stack trace: #0 {main} thrown in /customers/c/2/9/lifeofaris.se/httpd.www/flexboss/suggest.php on line 17" 

```
<?php 
ini_set('display_errors', 1);
    require("inc/phpmailer/PHPMailerAutoload.php");
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $name = trim(filter_input(INPUT_POST,"name",FILTER_SANITIZE_STRING));
    $email = trim(filter_input(INPUT_POST,"email",FILTER_SANITIZE_EMAIL));
    $details = trim(filter_input(INPUT_POST,"details",FILTER_SANITIZE_SPECIAL_CHARS));
    
    if ($name == "" || $email == "" || $details == "") {
        echo "Please fill in the required fields: Name, Email and Details";
        exit;
    }
    if ($_POST["address"] != "") {
        echo "Bad form input";
        exit;
    }
    $mail = new PHPMailer;
    $mail->isSMTP();
    if (!$mail->ValidateAddress($email)) {
        echo "Invalid Email Address";
        exit;
    }
    $email_body = "";
    $email_body .= "Name: " . $name . "<br>";
    $email_body .= "Email: " . $email . "<br>";
    $email_body .= "Customer Question: " . $details . "<br>";
    
    
    $mail->setFrom('example@example.com');     // Add a recipient
    $mail->addReplyTo($email, $name);
    $mail->isHTML(true);                      // Set email format to HTML
    
    $mail->Subject = 'Customer Question ' . $name;
    $mail->Body    = $email_body;
    
    if(!$mail->send()) {
        echo 'Message could not be sent.';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
        exit;
    }else{
        echo 'Message has been sent';
    }
    
    
    header("location:suggest.php?status=thanks");
}
?>
```

![example](https://cloud.githubusercontent.com/assets/11213118/14064785/c361d124-f418-11e5-9c67-925cc57ffd15.png)

**Comment by Synchro** [comment]
Either set a breakpoint in the autoloader or put some `echo` statements in it to make sure it's running. For some reason it's either not triggering, not finding, or does not have access to the files. What version of PHP are you running?

**Comment by conaris** [comment]
in my hosting i have php 7.0

**Comment by conaris** [comment]
change it to 5.5 or 5.6?

**Comment by Synchro** [comment]
7 should be fine, but put some echoes in the autoloader so we can see that it's runnign and why it's failing to load the classes.

**Comment by conaris** [comment]
i did put echo "hello"; on autoloader and navigated to it and it shows the output "Hello" so it works

**Comment by conaris** [comment]
i read also https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting where it says 
""SMTP Error: Could not connect to SMTP host."

This may also appear as SMTP connect() failed or Called Mail() without being connected in debug output. This is often reported as a PHPMailer problem, but it's almost always down to local DNS failure, firewall blocking or other issue on your local network. It means that PHPMailer is unable to contact the SMTP server you have specified in the Host property, but doesn't say exactly why. It can also be caused by not having the openssl extension loaded (See encryption notes below).

You can get a verbose transcript of the whole SMTP conversation by setting SMTPDebug = 2 - if you're submitting a bug report that's probably the best option to choose. If you are having trouble with the initial connection, SMTPDebug = 3 or 4 will give more info, but rather too much if your problem is not related to the connection itself.

Some techniques to diagnose the source of this error are discussed below." 


So it could be a problem with my internet connection? the solutions that you have are for gmail only, i cant find one for single/personal emails

**Comment by Synchro** [comment]
That doesn't tell you that the autoloader is working, just that it's loaded. In the autoloader code you'll see that it only attempts to load the class if it can read the file, and if it can't read it, it will cause a class not found error back in your own code, which is exactly what you're seeing. Try sticking an `echo $filename;` inside the `if` in the `PHPMailerAutoload()` function that will show you the exact path it's looking at, and if it can read the file. If it can't read it, it will not output anything.

I don't know what you mean by "personal" emails - all email accounts are the same as far as SMTP is concerned. You've not posted your whole debug output, so I can't diagnose the problem. If you call `isSMTP()`, it should not call PHP's `mail()` function at all.

**Comment by conaris** [comment]
well i think i got a clue why is not sending emails at all, its because of my hosting provider, and the specifically told not to use SMTP

**Comment by Synchro** [comment]
What did they tell you to do instead?
