### ISSUE TITLE
addAttachment not working with .pdf, .docx and many other extensions

### ISSUE THREAD

**Issue by rishijash** [PHPMailer/PHPMailer#671]
I am using addAttachment function in my application to upload and send attachments but looks like I am not able to send many types of attachments.

This is what I am using:
`$mail->addAttachment($uploadfile, 'My uploaded file');`

**Comment by Synchro** [comment]
I can't help without seeing your code. Did you base your code on the [send uploaded file example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/send_file_upload.phps) provided with PHPMailer?

**Comment by rishijash** [comment]
Yes it is based on exact same code.
I am able to send regular email without attachments and some attachments like .jpeg files.
But seems like it is not working with .pdfs, .docx and many other.

This is what my code looks like:

```

$mail->IsSMTP(); // enable SMTP
$mail->SMTPDebug = 0; // debugging: 1 = errors and messages, 2 = messages only
$mail->SMTPAuth = true; // authentication enabled
$mail->SMTPSecure = "ssl"; // secure transfer enabled REQUIRED for GMail
$mail->Host = "smtp.mail.me.com";
$mail->Port = 465; // or 587
$mail->IsHTML(true);
$mail->Username = "from address";
$mail->Password = "mypassword";
$mail->SetFrom("from address");
$mail->Subject = "my subject";
$mail->Body = "message";
$mail->addAddress("to address");
$uploadfile = tempnam(sys_get_temp_dir(), sha1($_FILES['userfile']['name']));
$filename =$_FILES['userfile']['name'];
if (move_uploaded_file($_FILES['userfile']['tmp_name'], $uploadfile)) {
    $mail->addAttachment($uploadfile, $filename);
}
if ($mail->send()) {
    $_SESSION['Sent']=null;
    echo "Sent";
} else {
    echo "Mailer Error: " . $mail->ErrorInfo;
}
```

**Comment by Synchro** [comment]
I don't know where you got that code, but it's based on an obsolete example, not the code I pointed you at.

Are you certain that it's not sending attachments, or could it be that it's being filtered at the receiving end? You can easily check by bcc'ing an account on a different system and comparing what is received. 

PHPMailer makes no distinction between file types, all are handled the same way.

**Comment by rishijash** [comment]
Checked it twice.
Somehow I am not able to send few files from my desktop.

I have deployed same code on [Hoodoomail.com](http://hoodoomail.com )
but not able to send this file([Google Drive Link](https://drive.google.com/file/d/0By8EVLvo2eUgR0VtTVkyUW9PLWc/view?usp=sharing)). 

May be files are corrupted or something.

**Comment by Synchro** [comment]
I can send and receive that file with no problem using PHPMailer. Looking at the structure of the message, all appears correct. PHPMailer can get quite memory intensive on large attachments, so check you're not running out of allocated memory.

**Comment by Synchro** [comment]
If you set `SMTPDebug = 2` you will see the entire MIME structure as it is sent. If that does not match exactly what you receive, then there is filtering breaking your stuff.

**Comment by rishijash** [comment]
Thanks for the help. :)

**Comment by rishijash** [comment]
If any one is facing such issue first make sure if move_uploaded_file is working or not.

```
// Upload file
$moved = if (move_uploaded_file($_FILES['userfile']['tmp_name'], $uploadfile)) ;

if( $moved ) {
//PHPMailer Add Attachment Code
} else {
  echo "Not uploaded because of error #".$_FILES["file"]["error"];
}

```

Reference: [http://stackoverflow.com/questions/3501749/php-move-uploaded-file-error](http://stackoverflow.com/questions/3501749/php-move-uploaded-file-error)

**Comment by Synchro** [comment]
Um, that code doens't make much sense. The file upload example code does it correctly - the only thing worthwhile is the error message output.
