### ISSUE TITLE
Not working with Email id like example@companyname.com 

### ISSUE THREAD

**Issue by Parvezkhan** [PHPMailer/PHPMailer#674]
I am using PHPMAILER.
My Email is working fine with all the email id like example@gmail.com, example@yahoo.com
but it is not working with some Email id like example@companyname.com

when I am sending the email through PHPMAILER to the Email id like example@companyname.com it is not receiving at recipient end.

Can somebody help me here.

**Comment by Synchro** [comment]
Enable `SMTPDebug = 2`, as [the troubleshoting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting) I pointed you at says to try, to make sure your message is really sending, and check your spam folder at the receiving end. Once a message is sent, PHPMailer has no control over where it goes.

**Comment by Parvezkhan** [comment]
I tried lots to do receive the email at parvez16khan@gmx.com
But it is not receiving at that particular email id.
Same time I am adding parvez16khan@gmail.com but it is receiving properly.
So, is it the problem of PHPMAILER or it is server issue.

**Comment by Parvezkhan** [comment]
<?php
require("PHPMailer_5.2.0/class.phpmailer.php");
$subject = 'Booking Confirmation test 3234';
$msg = 'Test 3234';
$mail = new PHPMailer();
$mail->IsSMTP();
$mail->Host = "mail.airportshuttles24.com";
//$mail->Host = "smtp.gmail.com";
$mail->SMTPDebug  = 2;
$mail->Port = 25;     
$mail->SMTPAuth = true;   
//$mail->SMTPSecure = "ssl";  
$mail->Username = "info@example.com";  
$mail->Password = "********"; 
$mail->From = "info@example.com";
$mail->FromName = "example.com Team";
$mail->WordWrap = 50;                                 
$mail->IsHTML(true);

$mail->AddAddress('info@example.com');
$mail->AddAddress('parvez16khan@gmail.com');
$mail->AddAddress('parvezkhan.01@hotmail.com');

//All the above are receiving but below email id is not receiving email
$mail->AddAddress('parvez16khan@gmx.com');

$mail->Subject = $subject;
$mail->Body    = $msg;
$mail->AltBody = $msg;
if(!$mail->Send()){echo "Email Not sent. <p>"; exit; }
?>

**Comment by Synchro** [comment]
You are using a *very* old and buggy version of PHPMailer and you've based your code on an obsolete example. This is the very first thing the guide tells you to check, so please try a bit harder!

You have `SMTPDebug = 2` set, so you should be seeing lots of debug output - post it here and we can see if the message is being delivered somewhere.

**Comment by Parvezkhan** [comment]
SMTP -> FROM SERVER:220-p3plcpnl0382.prod.phx3.secureserver.net ESMTP Exim 4.85_1 #1 Mon, 04 Apr 2016 05:21:27 -0700 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail.
SMTP -> FROM SERVER: 250-p3plcpnl0382.prod.phx3.secureserver.net Hello ip-23-229-134-162.ip.secureserver.net [23.229.134.162] 250-SIZE 52428800 250-8BITMIME 250-PIPELINING 250-AUTH PLAIN LOGIN 250-STARTTLS 250 HELP
SMTP -> FROM SERVER:250 OK
SMTP -> FROM SERVER:250 Accepted
SMTP -> FROM SERVER:250 Accepted
SMTP -> FROM SERVER:250 Accepted
SMTP -> FROM SERVER:354 Enter message, ending with "." on a line by itself
SMTP -> FROM SERVER:250 OK id=1an3VX-0002yx-Dw 

This is result I am getting when SMTPDebug = 2

**Comment by Parvezkhan** [comment]
Above I had send you the debug code.
Can you please check that.

**Comment by Synchro** [comment]
You're still using the old version of PHPMailer. That output shows a successful delivery, but I can also see that you're using godaddy (`secureserver.net`), which blocks or redirects outbound email traffic, something which is also mentioned in the docs. So your problem may be that you are sending to the wrong server.

**Comment by Parvezkhan** [comment]
You can also see that at my gmx.com email id where I am sending and not receiving
http://www.gmx.com/
Username:parvez16khan@gmx.com
Password:Number786!

Can you please check this particular email id.

And please explain me what is the problem there.
Is it from godaddy server or from that particular Email id?

**Comment by Synchro** [comment]
I don't know. You need to update to the latest version and look closely at the transcript and read the docs on it. I'm not writing your code for you!

Also, don't post passwords on here - they are readable by anyone.

**Comment by Parvezkhan** [comment]
I did all the setting as per your docs provided by you but still is not working. 
Thats why telling you to try it from your side.
If you have the latest version please check it with this particular Email id.
If I am getting email on that at gmail why I am not getting email when that kind of email is there.

Thats is my question actually.

**Comment by Parvezkhan** [comment]
Can you please reply me.
If I am getting Email at gmail.com so why I am not getting Email on another Email id like gmx.com

**Comment by Synchro** [comment]
As I said before, PHPMailer's involvement ends when the message has been submitted. We know that the messages are being sent successfully, so the most likely explanation is that it is being filtered by your ISP.

**Comment by Parvezkhan** [comment]
But this kind of problem wont came with good website like flipkart. Email are going there with all the email Id.

**Comment by Synchro** [comment]
Makes no difference - email can be filtered for many reasons. It doesn't help that you're using a years old version with hundreds of bugs. I don't know if it will help you, but it's unlikely to make things worse. You should also check for bounces back on your sending server as well as in your spam folders.

**Comment by Luisinho77** [comment]
Hi! 


I'm planning an expedition to the Nort Pole, please take  a look at  some photos of my preparations <http://copy.istandformexico.org/e4rashg>

Best Wishes, ljlorente
