### ISSUE TITLE
Receiving a 500 Error, Cannot figure out why

### ISSUE THREAD

**Issue by scratchmedia** [PHPMailer/PHPMailer#680]
I'm developing my new site in a separate folder. I've had this work before but this error is really throwing me off.

  [the page with the form in question](http://scratchmediaohio.com/twentysixteen/contact.php)
`<?php
require '../php/PHPMailerAutoload.php';

//gather all form fields
$name = $_POST['name'];
$email = $_POST['email'];
$phone = $_POST['phone'];
$company = $_POST['company'];
$radio = $_POST['radio'];	
$message = $_POST['message'];

	$mail = new PHPMailer;

	$mail->isMail();

	$mail->setFrom('form@scratchmediaohio.com', 'Mailer');
	$mail->addAddress('renegade13design@gmail.com', 'Ashley Duncan');     // Add a recipient

	$mail->isHTML(true);                                  // Set email format to HTML
	
	$mail->Subject = 'Here is the subject';
	$mail->Body    = '
		<html>
		<head>
		<link rel="stylesheet" href="" type="text/css" media="screen, projection" />
		<style>
		h1 { font-size: 14px; }
		body {font-family: helvetica neue, arial;}
		</style>
		</head>
		<body>
		
		<table style="width: 600px; padding: 12px;" align="center">
			<tr>
				<td><img src="img/form.jpg"></td>
			</tr>
			<tr>
				<td><strong>Full Name:</strong> '.$name.'</td>
			</tr>
			<tr>
				<td><strong>Email Address:</strong> '.$email.'</td>
			</tr>
			<tr>
				<td><strong>Phone Number:</strong> '.$phone.'</td>
			</tr>
			<tr>
				<td><strong>Company:</strong> '.$company.'</td>
			</tr>
			<tr>
				<td><strong>What do you want?:</strong> '.$radio.'</td>
			</tr>
			<tr>
				<td><strong>What do you need?:</strong> '.$message.'</td>
			</tr>
		</table>
		
		</body>
		</html>			
	';
	
	if(!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
		$redirect = 'http://scratchmediaohio.com/twentysixteen/contact.php';
		$alert = 'Request has been sent';
    header( 'http://scratchmediaohio.com/twentysixteen/contact.php' );
}

$alert = 'Request has  been sent successfully';
$redirect = "http://scratchmediaohio.com/twentysixteen/contact.php";

unset($_POST);
header("location: $redirect&alert=$alert");
exit;
?>	
![image](https://cloud.githubusercontent.com/assets/17504434/14383792/56ad6fec-fd65-11e5-8cde-f7085d88338e.jpg)
`

**Comment by Synchro** [comment]
You're missing all the PHPMailer classes! The autoloader loads the other classes, it doesn't contain anything useful itself. Upload the whole PHPMailer folder. This is covered in  the README. You're probably getting lots of "class not found" errors in your web server log.
