### ISSUE TITLE
ClearAllRecipients() doesn't clear Recipients

### ISSUE THREAD

**Issue by joyahm** [PHPMailer/PHPMailer#684]
I'm sending 3 email at once using loop, every single mail sending to different Recipients,everything is working good while there is 3 Recipients in the database but when database have 2 Recipients phpmailer sending 2 mail to last Recipient. I'm using `$mail->ClearAllRecipients();` for clear previous Recipient but it's clearing nothing.
My code is attached bellow.

thanks in advance.

`$scount = 1;
$ecount = 3;

for ($i = $scount; $i <= $ecount; $i++) {
$mail = new PHPMailer;
$mail->SMTPDebug = 0;

$mail->isSMTP();
$mail->Host = "$host";
$mail->SMTPAuth = true;
$mail->Username = "$email";
$mail->Password = "$pass";
$mail->SMTPSecure = "$tls";
$mail->Port = "$port";

$mail->setFrom("$email", "$name");
//$mail->addReplyTo('$replyto', '$replytoname');

$mail->isHTML(true);

$mail->Subject = "$subject";
$mail->Body    = "$body";
$mail->AltBody = "";

	if (empty($row['address'])) {
echo "no email found";
	} else {
$mail->addAddress($row['address'], $row['name']);
	}
	if (!$mail->send()) {
echo "Mailer Error (" . str_replace("@", "&#64;", $row["email"]) . ') ' . $mail->ErrorInfo . '<br />';
break; //Abandon sending
	} else {
echo "Message sent to :" . $row['name'] . ' (' . str_replace("@", "&#64;", $row['address']) . ')<br />';

	$query = "UPDATE recepient SET status = '0' WHERE ID=$RecepientID";
	$result = $mysqli->query($query);

	}
	$mail->ClearAllRecipients();
}`

**Comment by PunchyRascal** [comment]
You are already creating new PHPMailer instance for each recipient (each iteration of for), so why ClearAllRecipients() at the end anyway?

**Comment by Synchro** [comment]
This code is a bit of a mess; I suggest you start again using the mailing list example provided with PHPMailer.

**Comment by joyahm** [comment]
@punchyrascal I've tried without ClearAllRecipients() too, but no good result.

**Comment by PunchyRascal** [comment]
I am trying to say that since you create new instance of PHPMailer for each recipient, there is no point calling `ClearAllRecipients()` at the end, because the object is lost after each iteration and a new one is created.
The code quite strange. Why do you for example replace @ with @? What is the point? Why do you continue with sending `if (empty($row['address']))`

**Comment by joyahm** [comment]
@PunchyRascal that's from [mailing list example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/mailing_list.phps) provided with PHPMailer.

I was tried to intact use of example provided here after 36 hours lost to find out the problem.
