### ISSUE TITLE
Send all WordPress emails via SMTP ERROR

### ISSUE THREAD

**Issue by anetk** [PHPMailer/PHPMailer#686]
Hey guys.
I'm trying to use this option "Send all WordPress emails via SMTP", and i can make it work for some reason. But another option php mail()function works great.
These below are my 6 errors in total:

  ["SMTPKeepAlive"]=>
  bool(false)
  ["SingleTo"]=>
  bool(false)
  ["SingleToArray"]=>
  array(0) {
  }
  ["do_verp"]=>
  bool(false)
  ["AllowEmpty"]=>
  bool(false)
  ["LE"]=>
  string(1) "
"

**Comment by Synchro** [comment]
Those are not errors. That just looks like part of a `var_dump` of a PHPMailer instance. If `mail()` works for you, stick with it.

**Comment by anetk** [comment]
Hmmm. It works for me with gmail account but my client with outlook account is not receiving anything. Also, hostgator is I guess not supporting mail() so that's why i'm trying to work around this. Any idea how I could fix this?

**Comment by Synchro** [comment]
Well, if you have no errors at the time you send there is no way of telling why messages are not delivered. This is why people like to run proper mail servers - they handle non-delivery properly.
