### ISSUE TITLE
state property not needed in OAuth class?

### ISSUE THREAD

**Issue by Synchro** [PHPMailer/PHPMailer#687]
@sherryl4george The state property in the OAuth class seems unneeded - nothing uses it and there is no way of setting it, just [this getter](https://github.com/PHPMailer/PHPMailer/blob/6.0/src/OAuth.php#L93). I think it has been confused with the League provider classes which have a `state` property.

**Comment by sherryl4george** [comment]
Yes. It is unneeded. It would have crept in when did the code cleanup.

On Thursday, April 21, 2016, Marcus Bointon <notifications@github.com>
wrote:

> @sherryl4george <https://github.com/sherryl4george> The state property in
> the OAuth class seems unneeded - nothing uses it and there is no way of
> setting it, just this getter
> <https://github.com/PHPMailer/PHPMailer/blob/6.0/src/OAuth.php#L93>. I
> think it has been confused with the League provider classes which have a
> state property.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/PHPMailer/PHPMailer/issues/687>
>


-- 
Regards,
Sherryl George
+91 7036858184
