### ISSUE TITLE
How to call PHPMailer as a function

### ISSUE THREAD

**Issue by renardrouge** [PHPMailer/PHPMailer#689]
I have the following code structure built from a working copy of the OAuth2 PHPMailer named stack_gmail.php .
```
<?php
namespace PHPMailer\PHPMailer;
use League\OAuth2\Client\Provider\Google;
require 'vendor/autoload.php';

  function StackMail($recipient, $username, $token) {
    $mail = new PHPMailer;
    ==== remaining working code for PHPMailer ====
    //send the message, check for errors
    if (!$mail->send()) {
      return "Mailer Error: " . $mail->ErrorInfo;
    } else {
	  return "Message sent!";
    }
  } // end of function

//	test function
//$result = StackMail('person@gmail.com', 'redfox', 'xyztokenstring');
//	echo '<html><center><h1> StackMail Result </h1>' . $result . '</center></html>';
```

If I uncomment the last two lines, the mail gets delivered.  I would like to call the function from a separate php file named stack_gmail_test.php like this.

```
<?php
	require 'stack_gmail.php';
	$result = StackMail('person@gmail.com', 'redfox', 'xyztokenstring');
	// Fatal error: Call to undefined function StackMail() stack_gmail_test.php on line 3
	echo '<html><center><h1> StackMail Result </h1>' . $result . '</center></html>';
```

The problem is that the separate php file does not "see" the function StackMail(); and I get
"Fatal error: Call to undefined function StackMail() stack_gmail_test.php on line 3"

Yet is seems the structure of the code is almost exactly the same as my test call of the function within stack_gmail.php itself, if the "require" in stack_gmail_test.php includes everything from stack_gmail.php.

Can anyone explain what is going on here ???  Any suggestions on how to make this work ???

**Comment by renardrouge** [comment]
Problem solved and closed !
The following works.
```
$result = \PHPMailer\PHPMailer\StackMail('person@gmail.com', 'redfox', 'xyztokenstring');
```

**Comment by Synchro** [comment]
There is no need to put your own script in the PHPMailer namespace, and fully-qualified class names are messy. This should work:

```php
use PHPMailer\PHPMailer\PHPMailer;
use League\OAuth2\Client\Provider\Google;
require 'vendor/autoload.php';

  function StackMail($recipient, $username, $token) {
    $mail = new PHPMailer;
    ...
  }

$result = StackMail('person@gmail.com', 'redfox', 'xyztokenstring');
```

This way `StackMail()` is in the global namespace, so doesn't need qualifying.

**Comment by renardrouge** [comment]
Hello Synchro !

Thanks for the idea.  That would be a much better solution if I could get it to work.

I tried the following.

In stack_gmail.php I commented out 
```
namespace PHPMailer\PHPMailer;
```
and added
```
use PHPMailer\PHPMailer\PHPMailer;
```
The statements
```
use League\OAuth2\Client\Provider\Google;
require 'vendor/autoload.php';
```
are already there.

I modified stack_gmail_test.php from
```
$result = \PHPMailer\PHPMailer\StackMail('person@gmail.com', 'redfox', 'xyztokenstring');
```
to
```
$result = StackMail('person@gmail.com', 'redfox', 'xyztokenstring');
```
I get the following error in the "required" file 'stack_gmail.php'
"Fatal error: Class 'OAuth' not found in stack_gmail.php on line 84"

Did I follow your instructions properly ???  If so, is there a way around this error ???

**Comment by renardrouge** [comment]
The code in the area of error is
```
$mail->setOAuth(
    new OAuth([
        'provider' => $provider,
        'clientId' => $clientId,
        'clientSecret' => $clientSecret,
        'refreshToken' => $refreshToken,
        'userName' => $email
    ])
);
```

**Comment by Synchro** [comment]
Ah, ok, because you create an OAuth instance explicitly, and it's also in the PHPMailer\PHPMailer namespace, you need to `use` that too:

    use PHPMailer\PHPMailer\OAuth;

Notice that you don't have to do this for the SMTP class because that's created by PHPMailer, which is already in its own namespace. I'll tweak the example code to do this - thanks for posting!

**Comment by renardrouge** [comment]
Great !   That did it.  Everything now works as expected.  Thanks for the better solution and the furtherance of my PHP education !

**Comment by Synchro** [comment]
I just pushed changes to all the examples.
