### ISSUE TITLE
Errors when using PHPMailer

### ISSUE THREAD

**Issue by mfgabriel92** [PHPMailer/PHPMailer#690]
Hello,

I'd like to show you some errors I saw when using PHPMailer. According to my terminal, there are some `preg_match()` erros and an weird one saying I cannot convert object of class `PHPMailer` to string. All of the errors are pointed in the file `class.phpmailer.php`. Here are they:

`PHP Warning:  preg_match() expects parameter 2 to be string, object given in /home/gabriel/Dropbox/Web/despachantekafer.com/php/class.phpmailer.php on line 2731`

`PHP Warning:  preg_match() expects parameter 2 to be string, object given in /home/gabriel/Dropbox/Web/despachantekafer.com/php/class.phpmailer.php on line 3802`

`PHP Catchable fatal error:  Object of class PHPMailer could not be converted to string in /home/gabriel/Dropbox/Web/despachantekafer.com/php/class.phpmailer.php on line 3232`

Is this a bug or something I've done wrong? I have an `enviar_anexo.php` file that `requires PHPMailerAutoload.php` and after many validations, tries to send the e-mail. But when this block is reached, the above errors are shown. Please let me know if you need more code.

**Comment by Synchro** [comment]
The only explanation I can think of for those errors is if you have done something strange like:

    $mail = new PHPMailer;
    $mail->Body = new PHPMailer;

I can't tell without seeing your code.

**Comment by mfgabriel92** [comment]
I did

`
require_once 'php/PHPMailerAutoload.php';
$mailer = new PHPMailer();
`

**Comment by Synchro** [comment]
And the rest?
