### ISSUE TITLE
Been through trouble shooting, used the example gmail but mine doesn't stop loading

### ISSUE THREAD

**Issue by Ashra96** [PHPMailer/PHPMailer#691]
Hi this is my code. I cant see any errors because it doesn't get to that state. Been loading the page for over an hour.

```php
<?php
/**
 * This example shows settings to use when sending via Google's Gmail servers.
 */

//SMTP needs accurate times, and the PHP time zone MUST be set
//This should be done in your php.ini, but this is how to do it if you don't have access to that
date_default_timezone_set('Etc/UTC');

require 'PHPMailer-master/PHPMailerAutoload.php';

//Create a new PHPMailer instance
$mail = new PHPMailer;

//Tell PHPMailer to use SMTP
$mail->isSMTP();

//Enable SMTP debugging
// 0 = off (for production use)
// 1 = client messages
// 2 = client and server messages
$mail->SMTPDebug = 1;

//Ask for HTML-friendly debug output
$mail->Debugoutput = 'html';

//Set the hostname of the mail server
$mail->Host = 'smtp.gmail.com';
// use
// $mail->Host = gethostbyname('smtp.gmail.com');
// if your network does not support SMTP over IPv6

//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
$mail->Port = 587;

//Set the encryption system to use - ssl (deprecated) or tls
$mail->SMTPSecure = 'tls';

//Whether to use SMTP authentication
$mail->SMTPAuth = true;

//Username to use for SMTP authentication - use full email address for gmail

$mail->Username = 'example@gmail.com';      // SMTP username
$mail->Password = 'pass';      
//Set who the message is to be sent from
$mail->setFrom('example@gmail.com', 'No Reply');
//Set an alternative reply-to address
$mail->addAddress('example-email-recipient');     // Add a recipient

//Set the subject line
$mail->Subject = 'PHPMailer GMail SMTP test';

//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body
$mail->body = 'Test';

//Replace the plain text body with one created manually
$mail->AltBody = 'This is a plain-text message body';

//send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}
```

**Comment by Synchro** [comment]
You have to actually read the troubleshooting guide. You've got `SMTPDebug = 1`, which won't show you anything google says. If it's not getting as far as showing client output, you've got a connection problem, so set `SMTPDebug = 3`. You've not posted what the Mailer error output says - and if your code is not getting that far, you need to check your server logs. Every one of these points is mentioned in the guide.

**Comment by Ashra96** [comment]
I changed SMTP from the set of 2 and I said it doesnt get that far. its stuck just loading. and server logs? Im just using the gmail server

**Comment by Synchro** [comment]
I suggested you set it to 3 and you set it to 2? Was it really so hard to understand?

Your PHP is running on a server somewhere (even if it's your own computer), and PHP and the web server it runs in (usually apache or nginx) have log files which record errors. Find them and look at them.

**Comment by Ashra96** [comment]
No I mean I set to 1 from the default of 2 from the example before. I set it to 3 and it doesnt change anything because it doesnt get that far

**Comment by Synchro** [comment]
And your telnet and DNS checks work?

**Comment by Ashra96** [comment]
And the php is running from my university server so I can't check logs and don't know how to. and yes they were when I was trying it like 2 hours ago

**Comment by Synchro** [comment]
Did you test DNS and telnet from the server, not from your local machine? You can try setting `SMTPDebug = 4` for additional output.

**Comment by Ashra96** [comment]
I'll have to test on the server later when I can. Thanks ill update if I get any more details

**Comment by Synchro** [comment]
OK. University servers are fairly likely to block outbound SMTP.

**Comment by Luisinho77** [comment]
Hi friend! 

Have  you seen all that  stuff? It's so good, Ilove  it! Just take a quick look <http://price.aliemresevik.com/e4ooawbt>

Sent from my iPhone, ljlorente
