### ISSUE TITLE
not sending mail to yahoo email address and other domain email address 

### ISSUE THREAD

**Issue by livingstaraziz1** [PHPMailer/PHPMailer#692]
only sending mail to gmail email address on other email address it is sending this error in email kindly check and guide what to do
---- Forwarded Message -----

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  aziz.ciit03@gmail.com
    (ultimately generated from noreply@expressdrycleaner.net)
    host gmail-smtp-in.l.google.com [173.194.69.27]
    SMTP error from remote mail server after end of data:
    550-5.7.1 Unauthenticated email from yahoo.com is not accepted due to domain's
    550-5.7.1 DMARC policy. Please contact administrator of yahoo.com domain if
    550-5.7.1 this was a legitimate mail. Please visit
    550-5.7.1  https://support.google.com/mail/answer/2451690 to learn about DMARC
    550 5.7.1 initiative. ga4si14554627igd.17 - gsmtp

**Comment by Synchro** [comment]
Simple: don't forge your from address. You're sending from a gmail server using a yahoo from address, which is forgery, and Yahoo's strict policy won't allow it.

**Comment by livingstaraziz1** [comment]
Thanks got it and fix it

**Comment by livingstaraziz1** [comment]
but now mail not going to client email inbox :-(

**Comment by livingstaraziz1** [comment]
so for this i setup auto responder from hosting server Thanks again to u
