### ISSUE TITLE
Peer certificate CN

### ISSUE THREAD

**Issue by clarkk** [PHPMailer/PHPMailer#694]
After upgrading phpmailer I get this error?

How to subpress this or solve it?

`Peer certificate CN`

**Comment by clarkk** [comment]
setting `SMTPAutoTLS` to false solved it :)

**Comment by Synchro** [comment]
"Solved" may be misleading - if your mail server is advertising STARTTLS but serving an invalid certificate, it's broken, and your email is not secure. Turning off autotls "solves" it by not using encryption. The correct solution is to fix the mail server.
