### ISSUE TITLE
Old TLS version

### ISSUE THREAD

**Issue by szepeviktor** [PHPMailer/PHPMailer#696]
Hello!
[Here](https://github.com/PHPMailer/PHPMailer/blob/master/class.smtp.php#L343) PHPMailer forces tls 1.0. See: http://php.net/manual/en/function.stream-socket-enable-crypto.php#119122

Please consider
```php
$crypto_method = STREAM_CRYPTO_METHOD_TLS_CLIENT;

if (defined('STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT')) {
    $crypto_method |= STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT;
    $crypto_method |= STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT;
}

stream_socket_enable_crypto($socket, true, $crypto_method);
```
as mentioned in the comment.

**Comment by szepeviktor** [comment]
Very nice & fast.

**Comment by Synchro** [comment]
Thanks for noticing and reporting it!

**Comment by szepeviktor** [comment]
After setting TLS protocol to v1.2 only it turned out there is an error.

**Comment by Synchro** [comment]
This change allows any of TLS 1.0, 1.1 or 1.2 - what's the error?

**Comment by szepeviktor** [comment]
This was *before* the error report.

**Comment by Synchro** [comment]
Oh, I see!
