### ISSUE TITLE
Message could not be sent.Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

### ISSUE THREAD

**Issue by saurabhkumarvaish14** [PHPMailer/PHPMailer#697]
Message could not be sent.Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
If you can't follow a link I doubt anything I say is going to help.

**Comment by SergioRe** [comment]
Tengo el mismo problema, cuyando envio correo local...
