### ISSUE TITLE
how can i reset (addAddress)

### ISSUE THREAD

**Issue by yassinakra** [PHPMailer/PHPMailer#703]
please i want to divise my sent to two parts but how can i reset the addAddress

**Comment by Synchro** [comment]
[`clearAdddresses()`](http://phpmailer.github.io/PHPMailer/classes/PHPMailer.html#method_clearAddresses)

**Comment by yassinakra** [comment]
thanks alot

2016-05-03 11:16 GMT+01:00 Marcus Bointon <notifications@github.com>:
