### ISSUE TITLE
Mailer Error: SMTP connect() failed

### ISSUE THREAD

**Issue by harshadduasane** [PHPMailer/PHPMailer#711]
some days ago it's working properly but now this will not sending mail. But now it showing **SMTP connect() failed.**
on following link:
**https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting**
Please help to sort out this problem

Thanks for Help...!

**Comment by Synchro** [comment]
So did you actually read that link? It tells you all you need to know.

**Comment by harshadduasane** [comment]
Ya thanks. the problem is in another file. thanks.
