### ISSUE TITLE
Problem Sending Mail

### ISSUE THREAD

**Issue by Bhaskar1989** [PHPMailer/PHPMailer#713]
in inbox message is:

Delivery to the following recipient failed permanently:

     bhaskarbisht571@gmail

Technical details of permanent failure:
DNS Error: 18143032 DNS type 'mx' lookup of gmail responded with code NOERROR
18143032 DNS type 'mx' lookup of gmail had no relevant answers.
18143032 DNS type 'aaaa' lookup of gmail responded with code NOERROR
18143032 DNS type 'aaaa' lookup of gmail had no relevant answers.
18143032 DNS type 'a' lookup of gmail responded with code NOERROR
18143032 DNS type 'a' lookup of gmail had no relevant answers.

----- Original message -----

DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=date:to:from:cc:reply-to:subject:message-id:mime-version
         :content-transfer-encoding;
        bh=yAZ5dzvCeAdKQLyCNCigaxcnC/7ABlR8NkuTRFJb5b0=;
        b=eBv/2DRnamCyDXuOMtejFy/BALPK8j5xysK+xVsK7qTPWyrEQTClBZ34IyfyAPI5pR
         G8DIqVTvXC/eJSH1pcL7JVabs/ROdHQ0BdSlIMa8KqHZYpV0i+RHStGDwPS6aWkh07Gg
         S2GwcxykCUDpaJUnjT2qlVQzLUcOvyA1hjMH2uziy7WcuZhYfFoTO5PZNp902P0lbs//
         NSJXGm/FI1Rs7kD4zmMMLcvPZvk3Avtb9mgd4ST4HlhR1A5kd8d6I0aUt89pMHC9ueWN
         X/mrMNBVi5wZQZKvZoEHJbeIhJxU+UaRZjzj1lFq0fs/2bto/RGjWi9ik8VKcSo9fbc9
         SoEQ==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20130820;
        h=x-gm-message-state:date:to:from:cc:reply-to:subject:message-id
         :mime-version:content-transfer-encoding;
        bh=yAZ5dzvCeAdKQLyCNCigaxcnC/7ABlR8NkuTRFJb5b0=;
        b=isSePrOhtIe/v6H0Q5hU/Ya6cr/O2dRphN089PUK/adWSLll+Sd4nmcSeYGQrSYFyF
         oD4r5b6lS51pSOje2x87z7TMdTIDL43CEdKxqa9vHCwARqOvXwZQU3a4Ojv4b39tZ1s/
         TnIgTw+gLlNUONOKxPpzYUqEG755Nampuc8E2ygVF1kcGlTnViCq/WuejjGhAp4Wwl0M
         lbghHAJ70uVX0Il1dbu+ZSrOWGRegXT+OR8u3HDLXxjzJlGBA1BjjpyT4GlDzngmskE0
         g9ZYWLtKTPIMZq9oXx6HkmJQmXAjz6UdjTYHhNT41H9aIaUACGLgWvdGMnWN1Q++CmS0
         X0RA==
X-Gm-Message-State: AOPr4FXt0Zr659Isq2v5hzJZpBRWmuFvYmng1JCg1PxYvF7K1LR4Pm+SJU4nLMKmtCnYjw==
X-Received: by 10.98.84.65 with SMTP id i62mr4293563pfb.97.1462968387081;
        Wed, 11 May 2016 05:06:27 -0700 (PDT)
Return-Path: <bhaskarbisht571@gmail.com>
Received: from localhost ([122.177.109.149])
        by smtp.gmail.com with ESMTPSA id 133sm11808067pfw.35.2016.05.11.05.06.24
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Wed, 11 May 2016 05:06:26 -0700 (PDT)
Date: Thu, 12 May 2016 02:36:16 +0200
To: Joe User <bhaskarbisht571@gmail>, ellen@example.com
From: Mailer <bhaskarbisht571@gmail.com>
Cc: cc@example.com
Reply-To: Information <info@example.com>
Subject: Here is the subject
Message-ID: <c648d83214c6aee4c6f57094bc798f57@localhost>
X-Mailer: PHPMailer 5.2.15 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/alternative;
        boundary="b1_c648d83214c6aee4c6f57094bc798f57"
Content-Transfer-Encoding: 8bit

**Comment by Synchro** [comment]
Why are you surprised that sending to a non-existent address fails?

**Comment by Bhaskar1989** [comment]
but this email address exist. then why show this message.

**Comment by Synchro** [comment]
`bhaskarbisht571@gmail` does not exist. `bhaskarbisht571@gmail.com` does, but that's not the address you're trying to use.

**Comment by Bhaskar1989** [comment]
I will send you whole code.I written everywhere only bhaskarbisht571@gmail.com.But it will show in inbox bhaskarbisht571@gmail.I am unable to understand the problem.Please help


<?php
require 'phpmailer/PHPMailerAutoload.php';

$mail = new PHPMailer;

//$mail->SMTPDebug = 3;                               // Enable verbose debug output

$mail->isSMTP();                                      // Set mailer to use SMTP
$mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'bhaskarbisht571@gmail.com';                 // SMTP username
$mail->Password = '**************';                           // SMTP password
$mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 587;                                    // TCP port to connect to

$mail->setFrom('bhaskarbisht571@gmail.com', 'Mailer');
$mail->addAddress('bhaskarbisht571@gmail', 'Joe User');     // Add a recipient
$mail->addAddress('ellen@example.com');               // Name is optional
$mail->addReplyTo('info@example.com', 'Information');
$mail->addCC('cc@example.com');
$mail->addBCC('bcc@example.com');

$mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
$mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name
$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'Here is the subject';
$mail->Body    = 'This is the HTML message body <b>in bold!</b>';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

if(!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message has been sent';
}
?>

**Comment by Synchro** [comment]
What about:

    $mail->addAddress('bhaskarbisht571@gmail', 'Joe User'); // Add a recipient

?

**Comment by Bhaskar1989** [comment]
oh so sorry Marcus. Actually i am new in php.
Thanks for reply.
