### ISSUE TITLE
Examples: read & remove message

### ISSUE THREAD

**Issue by rmbaba** [PHPMailer/PHPMailer#717]
Hello,

How do I read header and body messages then delete the email when finished?

I didn't found anything in the examples!!!

Regards

**Comment by Synchro** [comment]
That's because that's not what PHPMailer does. It builds and sends messages, nothing more. If you want to fetch, parse or display messages, you need different libraries.

**Comment by rmbaba** [comment]
I know what, and I'm working on it since long time, but I see in the libraries there is a pop3 file I though it could be help

**Comment by Synchro** [comment]
If you read the POP3 class file it says:
 > This POP3 class is deliberately lightweight and incomplete, and implements just enough to do authentication.

You shouldn't even think of using POP3 for collecting email. It's a terribly archaic technology; use IMAP instead, which is supported directly by a PHP extension.

**Comment by rmbaba** [comment]
Thank you very much for your clarification, I will try to use the IMAP instead of POP3 classes.

Do you recommend any class for IMAP?  the purpose of the request is to get the list of email in the bounce back email such as noreply@domain.com and extract the header

**Comment by Synchro** [comment]
I wouldn't implement a bounce handler with IMAP - I'd do it as a filter script in your mail server. You can still write it in PHP. Take a look at these:

* http://serverfault.com/questions/48326/how-to-collect-bounces-in-postfix
* http://stackoverflow.com/questions/22979379/postfix-bounce-checking-emails-are-piped-to-php-but-prevents-emails-from-being

Also, extracting bounce addresses from bounce messages is extremely unreliable - for example MS Exchange often sends bounces that don't contain the bouncing address! The way to solve this is to use [VERP addressing](https://en.wikipedia.org/wiki/Variable_envelope_return_path) on your outbound messages, which will guarantee that you can obtain the original address the bouncing message was sent to.
