### ISSUE TITLE
SMTP connect fails & SMTP send works

### ISSUE THREAD

**Issue by sujit223** [PHPMailer/PHPMailer#718]
Hi team, 

Thanks for your wonderful application to send email.

I have just figured out an issue that is quite strange on a test server. I am able to send email via smtp using **$mail->send()** with same code but unable to make a connection check using **$mail->smtpConnect()**
Will be waiting for response.

**Comment by sujit223** [comment]
I have to use 
```
$mail->SMTPOptions = array(
     'ssl' => array(
         'verify_peer' => false,
         'verify_peer_name' => false,
         'allow_self_signed' => true
     )
);
```
to start the connection

**Comment by Synchro** [comment]
OK, so your mail sever has a broken SSL config.

**Comment by sujit223** [comment]
Thanks for quick response

**Comment by sujit223** [comment]
Why is that the the sending is working but connecting is failing

**Comment by Synchro** [comment]
Are you sending via SMTP? Are you calling `isSMTP()`?

If you're just checking SMTP, use the [smtp_check example](https://github.com/PHPMailer/PHPMailer/blob/master/examples/smtp_check.phps). You don't need to use PHPMailer for that.

**Comment by sujit223** [comment]
This is what i am trying to do

```
<?php
require 'PHPMailer-master/PHPMailerAutoload.php';

$mail = new PHPMailer;

$mail->SMTPDebug = 3;                               // Enable verbose debug output

$mail->isSMTP();                                      // Set mailer to use SMTP
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->SMTPOptions = array(
     'ssl' => array(
         'verify_peer' => false,
         'verify_peer_name' => false,
         'allow_self_signed' => true
     )
);
$mail->Host = '***********';  // Specify main and backup SMTP servers
$mail->Username = '***********';                 // SMTP username
$mail->Password = '***********';                           // SMTP password
$mail->SMTPSecure = 'ssl';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 465;                                    // TCP port to connect to

$mail->setFrom('***********', '***********');
$mail->addAddress('***********', '***********');     // Add a recipient
$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'Here is the subject';
$mail->Body    = 'This is the HTML message body <b>in bold!</b>';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
var_dump($mail->smtpConnect());
var_dump($mail->smtpClose());
var_dump($mail->ErrorInfo);
echo $mail->send();

```

**Comment by Synchro** [comment]
`smtpConnect()` doesn't use `SMTPOptions` by default, but when `send()` calls `smtpConnect()`, it passes them in. So you need to do this:

    var_dump($mail->smtpConnect($this->SMTPOptions));

I'm not sure whether I'd regard this as a bug or not.

**Comment by Synchro** [comment]
I decided it should do it automatically, so I've altered `smtpConnect()` to use `SMTPOptions` by default. Not in a release yet.

**Comment by sujit223** [comment]
if i try like this 

```
<?php
require 'PHPMailer-master/PHPMailerAutoload.php';

$mail = new PHPMailer;

$mail->SMTPDebug = 3;                               // Enable verbose debug output

$mail->isSMTP();                                      // Set mailer to use SMTP
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->SMTPOptions = array(
     'ssl' => array(
         'verify_peer' => false,
         'verify_peer_name' => false,
         'allow_self_signed' => true
     )
);
$mail->Host = 'server.moebro.de';  // Specify main and backup SMTP servers
$mail->Username = 'faveo@moebro.de';                 // SMTP username
$mail->Password = 'x4h*Ekbe';                           // SMTP password
$mail->SMTPSecure = 'ssl';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 465;                                    // TCP port to connect to

$mail->setFrom('faveo@moebro.de', 'faveo');
$mail->addAddress('sujit.prasad@ladybirdweb.com', 'Sujit Prasad');     // Add a recipient
$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'Here is the subject';
$mail->Body    = 'This is the HTML message body <b>in bold!</b>';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
var_dump($mail->smtpConnect($this->SMTPOptions));
var_dump($mail->smtpClose());
var_dump($mail->ErrorInfo);
echo $mail->send();
```

And this is what i get after this

![captureasdasd](https://cloud.githubusercontent.com/assets/11830376/15241134/a086725a-190b-11e6-95e1-52d269de02bb.PNG)

**Comment by Synchro** [comment]
Sorry - it should be:

    $mail->smtpConnect($mail->SMTPOptions)

Error 500 will usually result in errors appearing in your logs, which will tell you what the problem is.

**Comment by sujit223** [comment]
Thank you for your help it works flawlessly

**Comment by sujit223** [comment]
You guys rocks

**Comment by jndemenge** [comment]
$mail->smtpConnect(
                array(
                    "ssl" => array(
                        "verify_peer" => false,
                        "verify_peer_name" => false,
                        "allow_self_signed" => true
                    )
                )
            );

**Comment by Synchro** [comment]
@Ricky658 Please don't comment on tickets that were closed 4 years ago. Read the troubleshooting guide, and do what it says.
