### ISSUE TITLE
More secure WHM settings are now blocking PHPMailer emails

### ISSUE THREAD

**Issue by nestsman** [PHPMailer/PHPMailer#719]
I got an email from my WHM server that said I should make some changes to make things more secure when it comes to email, so I did.  Now when PHPMailer tries to send out emails I constantly get the error, "SMTP connect() failed."  Is there a happy medium between having a secure server and being able to send out emails?  Which of the following recommendations do you think is the one that has caused this new problem?

Thank you!

1. The pseudo-user “nobody” is permitted to send email. Enable “Prevent "nobody" from sending mail” in the “Tweak Settings” area.

2. Outbound SMTP connections are unrestricted. Enable SMTP Restrictions in the “SMTP Restrictions” area.

3. Apache is not being queried to determine the actual sender when mail originates from the “nobody” pseudo-user. Enable “Query Apache server status to determine the sender of email sent from processes running as nobody” in the “Exim Configuration Manager” area's “Basic Editor”.

**Comment by Synchro** [comment]
PHPMailer is a pawn in this game. All those sound like warnings and advice rather than anything that would actually block you from sending. It's common for web files to be owned by nobody, but then it's common to use PHPMailer in non-web contexts. PHPMailer is just PHP code that connects to SMTP ports, so if your environment has a problem with that, so will PHPMailer. I don't know anything about WHM, so I don't think I can be of much help.

**Comment by nestsman** [comment]
After turning on the debug feature I am seeing the following error for each email trying to go out, which is strange, because I no longer use a shared hosting plan but a VPS instead.  The only other thing that that has changed on the server recently was that I upgraded PHP from 5.4 to 5.6.10.  Could that be the cause?

Thank you Synchro!


"We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail."


SERVER CLIENT: 220-server.domain.com ESMTP Exim 4.87 #1 Sat, 14 May 2016 11:09:59 -0600 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail.
CLIENT SERVER: EHLO server.domain.com
SERVER CLIENT: 250-server.domain.com Hello server.domain.com [198.154.231.164]250-SIZE 52428800250-8BITMIME250-PIPELINING250-AUTH PLAIN LOGIN250-STARTTLS250 HELP<br>
CLIENT SERVER: STARTTLS<br>
SERVER CLIENT: 220 TLS go ahead<br>
CLIENT SERVER: QUIT<br>
SERVER CLIENT: 221 server.domain.com closing connection

**Comment by Synchro** [comment]
That's not an error. It's just their welcome banner. It failing after upgrading to PHP 5.6 probably means their SSL cert is invalid - see the troubleshooting guide in the wiki for more info.
