### ISSUE TITLE
DKIM header signing when sending through mailing list

### ISSUE THREAD

**Issue by npalmius** [PHPMailer/PHPMailer#720]
I use PHPMailer to send (semi-automated) emails through a mailing list via a gmail account - generally this is working great. I sign the outgoing mails using DKIM which works well when not sending the emails through the mailing list.

However, the mailing list prefixes a string to the subject (a standard '[list name] ' string) which causes DKIM verification to fail on the header, because the subject doesn't match. I don't want to change the mailing list configuration on this as emails can also be sent from other sources where the string should definitely be prefixed.

The hack to fix this is relatively simple - I have managed to work around it by changing lines 1288-1292 to

                $header_dkim = $this->DKIM_Add(
                    $this->MIMEHeader . $this->mailHeader,
                    $this->encodeHeader("[list name] " . $this->secureHeader($this->Subject)),
                    $this->MIMEBody
                );

This works fine, and gmail now shows the emails as passing DKIM authentication. However, obviously this is rather hacky and it would be better to have a more robust fix.

Of course this can actually be fixed very easily just by adding a new option, i.e. `DKIM_subject_prefix` that is set with the string to be prefixed to the subject used for DKIM signing, but not actually used in the subject of the email.

I understand that this is a rather niche issue, but I'm sure that it may affect others in future too. What are your thoughts on adding such an option? I can submit a PR if you want.

**Comment by Synchro** [comment]
This is really a niche thing that I don't think has general utility. I'd say the best way to do this would be to subclass and override - we've *really* got too many properties as it is! If you're using the subject to identify the list, I'd suggest using the `list-*` headers from [RFC2369}(http://tools.ietf.org/html/rfc2369), as they provide additional utility and don't break DKIM.

**Comment by npalmius** [comment]
Yes, you're right - I knew that it was niche, but I hadn't considered subclassing and overriding (I haven't worked with OOP in PHP much).

In the end, and for anyone else who finds this, it was as simple as

    class MyMailer extends PHPMailer
    {
      public function DKIM_Add($headers_line, $subject, $body)
      {
        return parent::DKIM_Add($headers_line, $this->encodeHeader($this->secureHeader("[list name] " . $this->Subject)), $body);
      }
    }

Thanks for the great work on PHPMailer!
