### ISSUE TITLE
Problem Sending Mail

### ISSUE THREAD

**Issue by Bhaskar1989** [PHPMailer/PHPMailer#721]
When click on submit button following error shows:

Notice: Undefined index: name in C:\xampp\htdocs\last-mile\mailer.php on line 13

Notice: Undefined index: email in C:\xampp\htdocs\last-mile\mailer.php on line 14

Notice: Undefined index: subject in C:\xampp\htdocs\last-mile\mailer.php on line 15

Notice: Undefined index: message in C:\xampp\htdocs\last-mile\mailer.php on line 16
Invalid address: (addAnAddress to): 
Mailer Error: You must provide at least one recipient email address.SERVER -> CLIENT: 220 smtp.gmail.com ESMTP v126sm47051293pfv.92 - gsmtp
CLIENT -> SERVER: EHLO localhost
SERVER -> CLIENT: 250-smtp.gmail.com at your service, [122.177.8.117]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: STARTTLS
SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
CLIENT -> SERVER: EHLO localhost
SERVER -> CLIENT: 250-smtp.gmail.com at your service, [122.177.8.117]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: AUTH LOGIN
SERVER -> CLIENT: 334 VXNlcm5hbWU6
CLIENT -> SERVER: ZXJhYmhpc2hla3JhajkyQGdtYWlsLmNvbQ==
SERVER -> CLIENT: 334 UGFzc3dvcmQ6
CLIENT -> SERVER: YWJoaXNoZWtANDcj
SERVER -> CLIENT: 235 2.7.0 Accepted
CLIENT -> SERVER: MAIL FROM:<erabhishekraj92@gmail.com>
SERVER -> CLIENT: 250 2.1.0 OK v126sm47051293pfv.92 - gsmtp
CLIENT -> SERVER: RCPT TO:<erabhishekraj92@gmail.com>
SERVER -> CLIENT: 250 2.1.5 OK v126sm47051293pfv.92 - gsmtp
CLIENT -> SERVER: DATA
SERVER -> CLIENT: 354 Go ahead v126sm47051293pfv.92 - gsmtp
CLIENT -> SERVER: Date: Tue, 17 May 2016 00:54:53 +0000
CLIENT -> SERVER: To: Last-mile <erabhishekraj92@gmail.com>
CLIENT -> SERVER: From: Last-mile <erabhishekraj92@gmail.com>
CLIENT -> SERVER: Reply-To: Last-mile <erabhishekraj92@gmail.com>
CLIENT -> SERVER: Subject: 
CLIENT -> SERVER: Message-ID: <7022ddcae39dfb955d248263cfc25268@localhost>
CLIENT -> SERVER: X-Mailer: PHPMailer 5.2.14 (https://github.com/PHPMailer/PHPMailer)
CLIENT -> SERVER: MIME-Version: 1.0
CLIENT -> SERVER: Content-Type: multipart/alternative;
CLIENT -> SERVER: boundary="b1_7022ddcae39dfb955d248263cfc25268"
CLIENT -> SERVER: Content-Transfer-Encoding: 8bit
CLIENT -> SERVER: 
CLIENT -> SERVER: This is a multi-part message in MIME format.
CLIENT -> SERVER: 
CLIENT -> SERVER: --b1_7022ddcae39dfb955d248263cfc25268
CLIENT -> SERVER: Content-Type: text/plain; charset=us-ascii
CLIENT -> SERVER: 
CLIENT -> SERVER: To view the message, please use an HTML compatible email viewer!
CLIENT -> SERVER: 
CLIENT -> SERVER: 
CLIENT -> SERVER: --b1_7022ddcae39dfb955d248263cfc25268
CLIENT -> SERVER: Content-Type: text/html; charset=us-ascii
CLIENT -> SERVER: 
CLIENT -> SERVER: Name: <br>Email: <br>Subject: <br>Messagae: 
CLIENT -> SERVER: 
CLIENT -> SERVER: 
CLIENT -> SERVER: 
CLIENT -> SERVER: --b1_7022ddcae39dfb955d248263cfc25268--
CLIENT -> SERVER: 
CLIENT -> SERVER: .
SERVER -> CLIENT: 250 2.0.0 OK 1463400971 v126sm47051293pfv.92 - gsmtp
CLIENT -> SERVER: QUIT
SERVER -> CLIENT: 221 2.0.0 closing connection v126sm47051293pfv.92 - gsmtp
Message sent!

**Comment by Synchro** [comment]
So fix your script? These errors are in your script, not in PHPMailer.
