### ISSUE TITLE
stream_socket_enable_crypto() when using Amazon SES

### ISSUE THREAD

**Issue by kylex** [PHPMailer/PHPMailer#722]
I'm getting this warning when attempting to run PHPMailer connected to SES from my domain. 
Any suggestions on how to overcome?

`PHP Warning:  stream_socket_enable_crypto(): Peer certificate CN='*.example.com' did not match expected CN='email-smtp.us-east-1.amazonaws.com' in /library/PHPMailer/class.smtp.php on line 355`

**Comment by Synchro** [comment]
It's a mismatched SSL cert, which is covered in [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting).
