### ISSUE TITLE
PHPMailer / Could not instantiate mail() / main.cf Permission denied

### ISSUE THREAD

**Issue by ml48603** [PHPMailer/PHPMailer#727]
Have a Ubuntu 14.04 LAMP server with PHP Mailutils and PostFix all working on the system, Email-tester.com rating 10. My Auction script uses PHPMailer to send out emails and emails can be sent directly from the ubuntu command line with mail.

A small PHP program was added to the same server called BlackHole by Jeff Star and the PHPMailer code was inserted into the BlackHole script along with the PHPMailer accompanying scripts to send automatic notification emails. Note The built in mail() call inside BlackHole would not send email.

PHPMailer reports the following error: Mailer Error: Could not instantiate mail function.

The Apache error.log reports sendmail: fatal: open /etc/postfix/main.cf: Permission denied

What would cause the separate installation of PHPMailer to be prohibited from sending email? meanwhile the auction script which includes its own PHPMailer and the mail() function available at the ubuntu command line continue to send mail.

**Comment by Synchro** [comment]
You posted the same question on SO. The PHP mail function (which PHPMailer calls) can fail for various reasons - in this case it looks like the apache user doesn't have sufficient permissions to run sendmail, which is what `mail()` does. Try fixing your permissions.

**Comment by ml48603** [comment]
Hi synchro, Yeah that's mine on Stack. Don't know why I didn't think of putting it here first.  I do have good luck on Stack, so is a first stop for me.  

I reinstalled the servers this week and just tested my auction script.  My auction script is not sending emails anymore. Consistent with BlackHole not sending and the common thread being the Apache user, as you suggested, thanks.

How do I authorized my Apache user to use the mail() calls? I have had the servers setup for 5 months and have lost my notes on how to do this.

**Comment by Synchro** [comment]
Check permissions on the sendmail binary, and on the main.cf file: On my working server:
```bash
# ls -al /usr/sbin/sendmail /etc/postfix/main.cf
-rw-r--r-- 1 root root  1398 Apr 16  2015 /etc/postfix/main.cf
-rwxr-xr-x 1 root root 26648 Feb  5  2015 /usr/sbin/sendmail
```
If yours doesn't look like that, do this: `chmod 644 /etc/postfix/main.cf; chmod 755 /usr/sbin/sendmail`

Beyond that you might be having problems with apparmor or selinux.

**Comment by ml48603** [comment]
My permissions are set the same as your:

```
# ls -al /usr/sbin/sendmail /etc/postfix/main.cf
-rw-r--r-- 1 root root  1646 May 14 23:37 /etc/postfix/main.cf
-rwxr-xr-x 1 root root 26648 Feb  5  2015 /usr/sbin/sendmail
```

**Comment by Synchro** [comment]
Check your `/var/log/syslog` to see if you've got something else preventing access - contraventions should be reported there. A simple `sudo -u www-data /usr/sbin/sendmail` shouldn't give you an error.

**Comment by ml48603** [comment]
When my auction script attempts to send a mail running as the Apache user the following errors appear in  /var/log/syslog
```
May 19 19:23:39 domainname postfix/sendmail[17256]: fatal: open /etc/postfix/main.cf: Permission denied
May 19 19:23:44 domainname postfix/qmgr[17228]: C7C01A0C1F: from=<user@northpaw.net>, size=4052, nrcpt=1 (queue active)
May 19 19:23:44 domainname postfix/local[17258]: warning: lookup root, NIS domain auctionsafedevelopment.net, map mail. aliases: internal yp server or client error
May 19 19:23:44 domainname postfix/local[17258]: warning: nis:mail.aliases: lookup of 'root' failed
May 19 19:23:44 domainname postfix/local[17258]: C7C01A0C1F: to=<root@domainname.tld>, relay=local, delay=573, delays=573/0.01/0/0.01, dsn=4.3.0, status=deferred (alias database unavailable)
```

**Comment by Synchro** [comment]
I still think this is probably another security layer, like [this](http://serverfault.com/questions/503642/postfix-main-cf-permission-denied). Plenty of others when I searched for that error.

**Comment by ml48603** [comment]
Ubuntu uses Apparmor instead of selinux.

I sent a mail to the root user from my other mail account and no mail is received. I get no error on the other end either.  Noticed in /var/mail no user mail files (nobody for root) are being created.

**Comment by Synchro** [comment]
I think we can safely say this isn't a PHPMailer issue...

**Comment by ml48603** [comment]
Yes. Something more fundamental

**Comment by ml48603** [comment]
I wanted to provide a solution I found that worked on multiple Ubuntu 14.04 LAMP servers. It will re-enable Postfix to provide mail services to Apache.

(Non-programmer explanation) When Postfix is first installed the installer automatically configures itself allow existing softwares access to mail services by reading the exisiting configurations of the other softwares on the machine that are likely to use Postfix services. If after the PostFix installation the configuration of softwares that use Postfix services are changed, it is possible that the "connection" to Postfix can be severed. In this case there are two remedies that have been proven to re-establish the connection of softwares to Postfix.  The first is to run a dpkg reconfiguration, the second is to purge and reinstall Postfix.

OPTION 1
# dpkg-reconfigure postfix
If this option does not work try purging Postfix from the system and reinstalling:

OPTION 2
STEP 1 # apt-get purge postfix
STEP 2 # apt-get install postfix

When changing the /etc/postfix/main.cf configuration file reload the new main.cf in the Postfix server with the following command:
# /etc/init.d/postfix reload

Upload and access the sample mail test script from Apache to verify that PHP scripts run under Apache user permissions can now send mail()

<?php
/*
From http://www.html-form-guide.com 
This is the simplest emailer one can have in PHP.
If this does not work, then the PHP email configuration is bad!
*/
$msg="";
if(isset($_POST['submit']))
{
    /* ****Important!****
    replace name@your-web-site.com below 
    with an email address that belongs to 
    the website where the script is uploaded.
    For example, if you are uploading this script to
    www.my-web-site.com, then an email like
    form@my-web-site.com is good.
    */
	$from_add = "serverrootuseraddress@domain.tld"; 
	$to_add = "recipientaddress@domain.tld"; //<-- put your yahoo/gmail email address here
	$subject = "CS7 Test Subject";
	$message = "CS7 Test Message from samplemail.php";
	$headers = "From: $from_add \r\n";
	$headers .= "Reply-To: $from_add \r\n";
	$headers .= "Return-Path: $from_add\r\n";
	$headers .= "X-Mailer: PHP \r\n";
	if(mail($to_add,$subject,$message,$headers)) 
	{
		$msg = "Mail sent OK";
	} 
	else 
	{
 	   $msg = "Error sending email!";
	}
}
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> 
<html>
<head>
	<title>Test form to email</title>
</head>
<body>
<?php echo $msg ?>
<p>
<form action='<?php echo htmlentities($_SERVER['PHP_SELF']); ?>' method='post'>
<input type='submit' name='submit' value='Submit'>
</form>
</p>
</body>
</html>
