### ISSUE TITLE
sent mail

### ISSUE THREAD

**Issue by yassinakra** [PHPMailer/PHPMailer#730]
hi,i don't want to receive a copy of mail in sent mails, how can i do it

**Comment by Synchro** [comment]
If you don't want to send yourself mail, don't send yourself mail?? It will only be sending you mail because you are telling it to; it doesn't happen automatically.

**Comment by yassinakra** [comment]
the problem that I find the email that I send to my customers in my sent mails

**Comment by Synchro** [comment]
Are you using PHPMailer? Can you post your code? Putting sent messages in your sent is not something that PHPMailer can do (it doesn't know about mailboxes at all) - it's your mail server doing it.
