### ISSUE TITLE
PHPMailer does not work - SMTP connect() failed

### ISSUE THREAD

**Issue by mati080** [PHPMailer/PHPMailer#733]
Hello everyone,

this is my first post here and at the beginnig i would like to tell that I am completly beginner in PHP. I tried to do simple forms in HTML and I used PHPMailer script to sending email. All the time I received errors.

`2016-05-25 18:50:54	Connection: opening to ssl://smtp.gmail.com:587, timeout=300, options=array ( ) 2016-05-25 18:50:54	Connection: opened 2016-05-25 18:50:54	SMTP -> get_lines(): $data is "" 2016-05-25 18:50:54	SMTP -> get_lines(): $str is "" 2016-05-25 18:50:54	SERVER -> CLIENT: 2016-05-25 18:50:54	SMTP NOTICE: EOF caught while checking if connected 2016-05-25 18:50:54	Connection: closed 2016-05-25 18:50:54	SMTP Error: Could not authenticate. 2016-05-25 18:50:54	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting Message was not sent.Mailer error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting`

I checked in cmd that port 587 wroks properly and I can ping smtp.gmail.com. I don't have idea what do. I spent a few hours on it and i am really confused.

Below is my php script: 

` <?php  
 
require("PHPMailer-master/class.phpmailer.php"); // path to the PHPMailer class 
require("PHPMailer-master/class.smtp.php");
$mail = new PHPMailer();  
 
$mail->IsSMTP();  // telling the class to use SMTP
$mail->Mailer = "smtp";
$mail->Host = "ssl://smtp.gmail.com";
$mail->Port = 587; //465
$mail->SMTPAuth = true; // turn on SMTP authentication
$mail->Username = "someone@gmail.com"; // SMTP username
$mail->Password = "Password"; // SMTP password 
$mail->SMTPDebug = 4;
 
$mail->From     = "some@gmail.com";
$mail->addAddress('someone@gmail.com', 'Joe User');
 
$mail->Subject  = "First PHPMailer Message";
$mail->Body     = "Hi! \n\n This is my first e-mail sent through PHPMailer.";
$mail->WordWrap = 50;  
 
if(!$mail->Send()) {
echo 'Message was not sent.';
echo 'Mailer error: ' . $mail->ErrorInfo;
} else {
echo 'Message has been sent.';
}
?> `

**Comment by Synchro** [comment]
Read the troubleshooting guide it points you to. Your connection is failing when it tries to use TLS, so it's probably a missing openssl extension or an invalid certificate.
