### ISSUE TITLE
user is unable to get confirmation link in email, hence unable to verify account.

### ISSUE THREAD

**Issue by rahul8888** [PHPMailer/PHPMailer#734]
HI,

every time a user registers on my website, they get an email saying "thank you for registering..." but they dont get any confirmation link inside their mail.
when they try to login they get an error saying that they need to verify their account by clicking on the confirmation link.

SMTP works fine, sends the email, but not the confirmation link required to verify that email.

Also, If user clicks on reset password button, no email is sent to the user but is shows as sent on the webpage. 

would request you to help me out in this regard.

Thank you.

**Comment by Synchro** [comment]
Sorry, this has nothing to do with PHPMailer.
