### ISSUE TITLE
Call to undefined method SMTP::connected()

### ISSUE THREAD

**Issue by niteshluharuka** [PHPMailer/PHPMailer#735]
Using the latest version of the library, I am getting this error - Call to undefined method SMTP::connected() in <b>/phpmailer/class.phpmailer.php</b> at line 1556

**Comment by niteshluharuka** [comment]
This issue was created when we had classes with same names. The issues has been resolved.

**Comment by Synchro** [comment]
This will be solved in PHPMailer 6 which uses a namespace to avoid clashes.

**Comment by niteshluharuka** [comment]
This would be a great addition.
