### ISSUE TITLE
function addAnAddress - use of variable variable - typo?

### ISSUE THREAD

**Issue by giffeler** [PHPMailer/PHPMailer#737]
Warning: array_push() expects parameter 1 to be array, string given in .../PHPMailer-master/class.phpmailer.php on line 923.

Maybe  »array_push($this->$kind, array($address, $name));« should be »array_push($kind, array($address, $name));«

**Comment by Synchro** [comment]
Nope, it's correct. Must be your calling code - you shouldn't really call addAnAddress yourself anyway, use the wrapper functions or pass the correct property names in.
