### ISSUE TITLE
forcing the reply-to header in emails with phpmailer

### ISSUE THREAD

**Issue by arkid** [PHPMailer/PHPMailer#738]
I have a problem with my php hosting sending emails with a different "Reply-To" header value from the one I actually set as standard in the "from" parameter of phpmailer.

When I check the headers of mails generated by phpmailer (or php's standard mail() function) I see that X-Sender-Id and Reply-To values are something totally alien to me. They take the form of

useraccount@servername.accountservergroup.com

accountservergroup.com is a domain owned by my ISP Site5.com. I've spoken to them about this and they told me this is default php behavior.

The problem is that this difference between the From header value and the other headers is causing my emails to be rejected by some large email systems such as outlook.com.

Reading the php documentation on the mail() function it talks about a 5th parameter to send additional commands to sendmail. Using mail() for my initial tests I added "-f replyto_address@whatever.com" and it worked. Checking the header revealed a "Reply-to" and "X-Sender-Id" value matching the "from" value that I want to use.

I now need to get this to work in a similar way for a site that uses phpmailer. I don't have access to an smtp account so that isn't an option, I need to use the sendmail functionality via phpmailer.

Of course I've already tried the ->AddReplyTo and ->SetFrom values that PHPMailer has but I still get a header with "X-Sender-Id" having this other email address that I don't want.

**Comment by Synchro** [comment]
There's a big difference between sending those headers and receiving them. PHPMailer does not set an X-sender-id header. It also uses the `-f` option to set the envelope sender. Have you looked at the `Sender` property? Set `SMTPDebug=2` and watch the SMTP conversation to see what is actually sent, then compare that with what you receive. Any difference is down to your ISP.

**Comment by arkid** [comment]
Hi @Synchro I've just done tests looking at the headers of an email sent with mail() and with phpmailer (using sendmail) and the "reply-to" header from php mailer is always the php generated email address which isn't for my domain.   So from what I see it isn't using the -f switch.

I've just used the latest version of the class from github btw.

**Comment by Synchro** [comment]
It really does use `-f` - it's [right here](https://github.com/PHPMailer/PHPMailer/blob/master/class.phpmailer.php#L1431).

I'd recommend that you use SMTP to localhost anyway - it should be faster than using `mail()`, and it gives you much better feedback and control over sending.

**Comment by arkid** [comment]
Ok... so it only uses it when the sender is blank, not in all circumstances.   Thanks for pointing me to this.

**Comment by Synchro** [comment]
Reading back over this, I think you're getting confused between return-path and reply-to addresses. The return-path is nothing to do with where *replies* go to, but where *bounces* are sent. Reply-to is *only* a message header, i.e. it's from RFC822; return-path is from RFC821.

**Comment by Synchro** [comment]
No, it's the other way around - it only sets the `-f` option when `Sender` is *not* empty. Without it, sendmail extracts the From address from the message headers and uses that.

**Comment by arkid** [comment]
Ok sorry yes of course yes you are correct.   ;)

**Comment by Synchro** [comment]
So is this working for you now?

**Comment by arkid** [comment]
No... what I wrote earlier today still stands.  Even if the phpmailer code is apparently running the -f switch, the headers I get running phpmailer against mail(), specifically in terms of "reply-to" are different.

**Comment by Synchro** [comment]
Right, but the `-f` switch has nothing to do with reply-to.

**Comment by arkid** [comment]
Sorry!  I meant "Return-Path".   I have corrected in previous comment.

**Comment by Synchro** [comment]
So I suggest you echo exactly what is being passed into the `mail()` function inside PHPMailer so you can see what's different.

**Comment by Luisinho77** [comment]
Dear friend! 


The information that I've just found seems to  be  really helpful, just take a look  <http://rise.goutamaubud.com/e4pivfvq>


Cheers, ljlorente
