### ISSUE TITLE
Message Subject in the Czech language

### ISSUE THREAD

**Issue by Stoupa-tr** [PHPMailer/PHPMailer#739]
Hi, I want to thank in advance for a job well done . Thanks.

And now for the question.
Czech language has a specific letter ř and ě . These two letters are not displayed in the object sing . Only in Subject. In body all ok.

Thank you for answer.

**Comment by Synchro** [comment]
It would help to see your code. PHPMailer defaults to using the ISO-8859-1 Latin-1 character set, which does not include those characters, so you would need to switch to ISO-8859-2 Latin-2 or UTF-8 to make it work, for example:

    $mail->CharSet = 'utf-8';

**Comment by Stoupa-tr** [comment]
Hi, friend,
thank you for answer.

my php is utf-8 and in my php is:
mb_internal_encoding("UTF-8");
SetLocale(LC_ALL, "Czech");
date_default_timezone_set("Europe/Prague");


Next in my php class is this:
` $mail->CharSet = 'utf-8';`


Only problem is the subject of the letter ř and ě( word měření)
Í word is good (and others - á etc.)

Thank.

**Comment by Synchro** [comment]
I just tried that and it's working fine. Here is a resulting message:

```
Date: Tue, 31 May 2016 11:16:07 +0000
To: Joe User <joe@example.net>
From: Mailer <from@example.com>
Subject: =?utf-8?Q?Subject_is_m=C4=9B=C5=99en=C3=AD?=
Message-ID: <584c7dc32f68b284f3a867d3eec55109@Oc.local>
X-Mailer: PHPMailer 6.0.0 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

This is the message body měření
```

Depending on the subject contents, it may be encoded differently, for example:

    Subject: =?utf-8?B?bcSbxZllbsOt?=

is just `měření`.

What do your subject headers look like?

**Comment by Stoupa-tr** [comment]
Hi, THX,

Shipped standard PHP mailer (public $CharSet = 'iso-8859-1';)
![iso-8859-1 - standard phpmail](https://cloud.githubusercontent.com/assets/19661232/15676859/2e7ae542-2748-11e6-8a33-a591d2397681.PNG)
-- Detail mail: 
To: stoupa-tr@seznam.cz
Subject: =?utf-8?Q?Denn=ED_statistika_|_www.stasi.cz_(m=EC=F8en=ED_dostupnosti)...?=
X-PHP-Originating-Script: 1001:class.phpmailer.php
Date: Tue, 31 May 2016 00:05:01 +0200
From: =?utf-8?Q?Port=E1l_www=2Estasi=2Ecz=2E=2E=2E?= <mereni@stasi.cz>
Reply-To: =?utf-8?Q?Port=E1l_www=2Estasi=2Ecz=2E=2E=2E?= <mereni@stasi.cz>
Message-ID: <d41bd56836657dfa0e1403549efa246c@localhost.localdomain>
X-Priority: 3
X-Mailer: PHPMailer 5.2.6 (https://github.com/PHPMailer/PHPMailer/)
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="b1_d41bd56836657dfa0e1403549efa246c"

--b1_d41bd56836657dfa0e1403549efa246c
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

Chcete-li zobrazit zpravu, pouzijte kompatibiln� HTML e-mailovy prohlizec!


----------------------------------------------------------------------------
and if im change at UTF-8 ($mail->CharSet = 'utf-8';)
![utf-8](https://cloud.githubusercontent.com/assets/19661232/15676693/966e3f1a-2747-11e6-9cf5-68d2802b9baa.PNG)
-- Detail mail: 
To: stoupa-tr@seznam.cz
Subject: =?utf-8?Q?Denn=ED_statistika_|_www.stasi.cz_(m=EC=F8en=ED_dostupnosti)...?=
X-PHP-Originating-Script: 1001:class.phpmailer.php
Date: Tue, 31 May 2016 00:05:01 +0200
From: =?utf-8?Q?Port=E1l_www=2Estasi=2Ecz=2E=2E=2E?= <mereni@stasi.cz>
Reply-To: =?utf-8?Q?Port=E1l_www=2Estasi=2Ecz=2E=2E=2E?= <mereni@stasi.cz>
Message-ID: <d41bd56836657dfa0e1403549efa246c@localhost.localdomain>
X-Priority: 3
X-Mailer: PHPMailer 5.2.6 (https://github.com/PHPMailer/PHPMailer/)
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="b1_d41bd56836657dfa0e1403549efa246c"

--b1_d41bd56836657dfa0e1403549efa246c
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

thx.

**Comment by Synchro** [comment]
You're using a very old version of PHPMailer - 5.2.6 was released in 2013 and lots has changed since then. Try again with the latest version.

**Comment by Stoupa-tr** [comment]
ok..im new version 5.2.15.

Im test and write.

THX..

**Comment by Stoupa-tr** [comment]
Hi, same problems :-( 

Thx for help.

**Comment by Synchro** [comment]
Your source string is in the wrong charset. You're telling it that it is UTF-8, but you are not giving it a UTF-8 string, so it's corrupting. `měření ` in Q-encoded UTF-8 is `m=C4=9B=C5=99en=C3=AD` (as in my example), where in yours it's coming out as `m=EC=F8en=ED` - notice that the accented characters are only 1 byte, which suggests your source string is in a 1-byte encoding, and checking the [character table](https://en.wikipedia.org/wiki/ISO/IEC_8859-2) confirms that it is using ISO 8859-2, in which `ě` == `EC`, `ř` == `F8`, `í` == `ED`. Encode your source string in UTF-8 and it will work.

**Comment by Stoupa-tr** [comment]
HI,

im test and you right. Im Netbeans and this not UFT-8 , ven though I have set PHP UTF-8.

Sorry, thank you very much for your help.

Good luck in further development.
