### ISSUE TITLE
$mail->SMTPDebug=2 only when sending fails

### ISSUE THREAD

**Issue by DePalmo** [PHPMailer/PHPMailer#745]
Hello,

First, let me say thank you for a nice piece of software and another thanks for still maintaining it and keeping it up to date! Your efforts are really appreciated! I simply can't imagine my coding without your nice library.

Now, to the point. I just discovered an issue where the mail server refused connections (no, won't be another topic about that) and this was happening for past three months without me knowing it. I can create additional notification if something goes wrong, but what I'm really missing is a debug output that could be saved into logs ONLY when things go wrong. Currently we have a `$mail->SMTPDebug = x;` option which has to be manually enabled, but can that be extended so it's only triggered when an error happens? For example, if email is sent, the code just returns a success message and that's it, but if any error happens, it would made available (or if we can provide file/folder name, where to store log files) a debug output of the error itself. So, like having a conditional `$mail->SMTPDebug` option.

Is this something that can be done in future versions?
Is it even something worth of the efforts?

Thank you for your time!

**Comment by Synchro** [comment]
SMTPDebug is only used as it goes along, it doesn't accumulate anywhere, so by the time an error occurs, the output is lost, but it's really a debugging tool, not an error reporting tool because it's simply too verbose.

When sending fails (i.e. `send()` returns false), there is info about why it failed in the `ErrorInfo` property, and that's usually enough to see why. All the example scripts show that.

**Comment by Synchro** [comment]
Forgot to mention - In recent versions you can pass in a closure as the `Debugoutput` property, so you could use that to log SMTPDebug output.

**Comment by DePalmo** [comment]
Will try that, thank you for your response.

**Comment by Kirti003Shukla** [comment]
<?php
require "phpMailer/PHPMailer/PHPMailerAutoload.php";//have file in phpMailer folder

$mail= new PHPMailer();

$body = "hi"; 
$subject = "Account Activation -GACKONNECT ";
$email_to = "dummyemail@gmail.com";
$fromserver = "noreply@gacons.com"; 
//$mail->IsSMTP();
$mail->SMTPDebug = SMTP::DEBUG_SERVER;
$mail->SMTPAuth = true;
$mail->SMTPSecure = 'ssl'; 
$mail->Host = "sanjeevsanthalia.com"; // Enter your host here
$mail->Port = 465;
$mail->Username = "noreply@sanjeevsanthalia.com"; // Enter your email here
$mail->Password = "password"; //Enter your password here
$mail->IsHTML(true);
$mail->From = "noreply@sanjeevsanthalia.com";
$mail->FromName = "GACKONNECT";
$mail->Sender = $fromserver; // indicates ReturnPath header
$mail->Subject = $subject;
$mail->Body = $body;
$mail->AddAddress($email_to);

if($mail->send()){
echo $mail->SMTPDebug;//echoing 2
echo $mail->send();//echoing 1
echo "Mailer Error: " . $mail->ErrorInfo;
}else{
    header('location:afterRegistration.php');

	}
I really appreciate how this library solved my problems. But not able to send emails anymore, suddenly it stopped working. Please resolve

**Comment by Synchro** [comment]
@Kirti003Shukla please don’t post on old, closed issues.

It’s unclear what your problem is because you have not posted any debug output.
