### ISSUE TITLE
Email is unable to send because character encoding wrong

### ISSUE THREAD

**Issue by sharda123** [PHPMailer/PHPMailer#746]
Email is unable to send from magento 1.8.0 because character encoding problem. When i log `$this->recipients in lib/Zend/Mail/Transport/Sendmail.php` it prints:

```
=?utf-8?B?cmF2aSBzaGFua2FyIHNoYXJtYQ==?= <arvind.sharma225@gmail.com>
Instead of <arvind.sharma225@gmail.com> , what is the extra appended string =?utf-8?B?cmF2aSBzaGFua2FyIHNoYXJtYQ==?= in it?
```
This happens after this function call `$this->_prepareHeaders($this->_getHeaders($boundary));` from lib/Zend/Mail/Transport/abstract.php. I guess it is character encoding problem in magento.

**Comment by sharda123** [comment]
Please provide me any solution, Because i waste my too much time in this task and now i want to solution. so please...

**Comment by Synchro** [comment]
You're *demanding* I fix your problem when you're not even using PHPMailer! You're using [Zend_Mail](http://framework.zend.com/manual/current/en/modules/zend.mail.introduction.html).

There isn't even a problem here: that is a standard email header using [RFC2047](https://tools.ietf.org/html/rfc2047.html#section-2) B encoding and it says "ravi shankar sharma" if you'd been bothered to decode it.
