### ISSUE TITLE
I do not receive mails from php mailer

### ISSUE THREAD

**Issue by maciosmx** [PHPMailer/PHPMailer#748]
Hi everyone. 
I did everything like you wrote in your tutorials but mails can not reach my mail from contact form. I have properly installed the PHPmailer. I put neccessarry data into  config.inc.php and I have created gmail example. 
Could you tell me what I should do to work with it ??

Waiting for any answers.

**Comment by Synchro** [comment]
`config.inc.php` is not a PHPMailer file. Please read [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting).

**Comment by vbijan** [comment]
this is my code not receiving email... please help

<?php

require_once "vendor/autoload.php";

//PHPMailer Object
$mail = new PHPMailer;

//From email address and name
$mail->From = "bijan.gopali@yahoo.com";
//$mail->FromName = "Full Name";

//To address and name
$mail->addAddress("gopalibijan@gmail.com"); //Recipient name is optional

//Address to which recipient will reply
$mail->addReplyTo("gopalibijan@gmail.com");

// //CC and BCC
// $mail->addCC("cc@example.com");
// $mail->addBCC("bcc@example.com");

//Send HTML or Plain Text email
$mail->isHTML(true);

$mail->Subject = "Subject Text";
$mail->Body = "<i>Mail body in HTML</i>";
$mail->AltBody = "This is the plain text version of the email content";

if(!$mail->send()) 
{
    echo "Mailer Error: " . $mail->ErrorInfo;
} 
else 
{
    echo "Message has been sent successfully";
}
?>

**Comment by Synchro** [comment]
Please don't hijack other people's tickets. As I said above, read [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting). You are not sending via SMTP, so you need to look in your mail server's log file.

**Comment by vbijan** [comment]
i did use SMTP before but the username i gave sent message rather than mail->FROM.. any suggestions?

**Comment by Synchro** [comment]
Yes, read the troubleshooting guide, which covers that.
