### ISSUE TITLE
SMTP Error: Could not authenticate. unuasual X-files

### ISSUE THREAD

**Issue by blvckf0x** [PHPMailer/PHPMailer#750]
I fixed everything double triple cheked everything, I stucked need some help, ISP hosting doesn't want to support.

I am sending from master server via php form to send to slave server
and it gives me this SMTP Error: Could not authenticate.
system is on debian postfix phpmailer
I can provide everypart of cod if needed

P.S. Master server is ok to send via phpmailer slave no :(

please advise

**Comment by Synchro** [comment]
[Read the docs](https://github.com/PHPMailer/PHPMailer/wiki). They are there to help you.

**Comment by Synchro** [comment]
> Master server is ok to send via phpmailer slave no

This tells you that your code is fine, but your server or network config is not.
