### ISSUE TITLE
HTML Email Not Sending

### ISSUE THREAD

**Issue by amberino** [PHPMailer/PHPMailer#755]
I'm trying to send an HTML email and it works when my message contains only 423 characters. When trying to add some more styling, which makes the message 737 characters the email no longer sends. I've done some searching and found that PHP has a limit on number of characters that can be use in one line. I added the $mail->WordWrap = 50, and even wordwrap($message, 70) to no avail. PHP is not my main coding language so I am not sure if this is even the cause. Can someone please help. Thanks.

**Comment by Synchro** [comment]
There's not enough to go on here. Please post your code and a complete description of what happens, along with debug output. There is no particular limit on content size in PHPMailer, and no line-length limit in PHP.

**Comment by amberino** [comment]
$message = '<div style="Margin-left: 20px;Margin-right: 20px;text-align: left; font-size:16px; line-height:24px;font-family: roboto,tahoma,sans-serif;color:#4e5561;"><p style="Margin-top: 0;Margin-bottom: 0;">Thanks for taking the time out of your very busy day to fill out our form. One of our wonderful representatives will contact you soon. While you wait, we&rsquo;ve included some things specifically just for you. Enjoy!&nbsp;</p><p style="Margin-top: 20px;Margin-bottom: 20px;"><a href="http://info.iacmedsupp.com/map/" style="text-decoration: underline;transition: opacity 0.1s ease-in;color: #2186b8;">IAC Rate Adjustment Map</a>.&nbsp;</p><p style="Margin-top: 20px;Margin-bottom: 20px;">Thank you,<br />Heartland Financial Group</p></div>';
				
				//send reply to email to user
				require 'phpmailer/PHPMailerAutoload.php';
				$mail = new PHPMailer;
				$mail->IsSendmail();
				$mail->setFrom('aking@e-hfg.com', 'Amber King');
				$mail->addAddress($email);
				$mail->Subject = 'Thanks for Your Interest! Sweet Stuff Inside.';
				$mail->isHTML(true);
				$mail->Body = wordwrap($message, 70);
				$mail->AltBody = 'Thanks for your interest in IAC!\n\nOne of our wonderful representatives will contact you soon. While you wait, take a gander at the items we&rsquo;ve attached for your viewing pleasure.\n\nThank you,\nHeartland Financial Group';
				//array of iac states
				$stateArray = array("AK", "AL", "AR", "AZ", "CA", "CO", "DE", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MD", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NJ", "NM", "NV", "OH", "OK", "OR", "PA", "SC", "SD", "TN", "TX", "UT", "VA", "WI", "WV", "WY");
				$arrayLength = count($stateArray);
				//loop through array and checking if user data matches. if so attach rate and app packet.
				for($x = 0; $x < $arrayLength; $x++){
					if(preg_match('/'.$stateArray[$x].'/', $state)) {
						$mail->addAttachment('docs/'.$stateArray[$x].'.pdf');
						$mail->addAttachment('docs/app-packets/IAC-'.$stateArray[$x].'-Packet-2016.pdf');
					}	
				}

				
				//send the message, check for errors
				if (!$mail->send()) {
					echo "Mailer Error: " . $mail->ErrorInfo;
				} else {
					//echo "Message sent!";
					// set our boolean completion value to TRUE
					$emailSent = true;
				}

**Comment by Synchro** [comment]
So what error does it show? Why are you using sendmail?

**Comment by amberino** [comment]
I do not receive any error. The email just doesn't get sent. I was using SendMail because that's what was included in one of the examples.

**Comment by amberino** [comment]
Here is the article i found regarding the single line limit: http://www.ehow.com/info_12198732_php-mail-character-limit.html

**Comment by Synchro** [comment]
Don't just use sendmail blindly - use it because you need it specifically, as it's likely it won't work unless you do. It's very likely you have a sendmail binary and no local mail server, so it's calling sendmail successfully but the message is going nowhere, so the message is submitted successfully, but your server is misconfigured so it never gets any further. Remove the `isSendMail()` call and it will default to using PHP's mail function internally, which may work better. Failing that, use `isSMTP` and point it at a nearby mail server, see the docs for examples.

PHPMailer deals with line length limits in email for you; you don't need to do anything. That article is very simplistic and very old. It fails to deal with many things that PHPMailer handles for you. Ignore it and just use the provided examples instead.

**Comment by amberino** [comment]
Okay, thank you for your help.

**Comment by amberino** [comment]
I am now sending using the SMTP option and get a returned email with error: Message rejected for spam or virus content. I only get this error if message is over 500 characters. I spoke with hosting provider and they say it is not a server issue. I've tried sending to different email servers with same results. Any suggestions?

**Comment by Synchro** [comment]
Post the exact output you get with SMTPDebug = 2.

**Comment by amberino** [comment]
[debug-output.txt](https://github.com/PHPMailer/PHPMailer/files/326560/debug-output.txt)

**Comment by Synchro** [comment]
Well that message isn't 500 chars; it contains a 1.2Mb attachment. What's more, that SMTP transcript shows a successful delivery with no problems. When exactly are you receiving this error? In a bounce message?

**Comment by amberino** [comment]
Yes it was in a bounced message. I discovered the issue lies with me using a link. The message is sent successfully and is received as long as it does not contain a link. When the message contains a link, that is when I get the returned email. Sorry for all the trouble. My first assumption about the issue being the number of characters was wrong. Thanks for you help.
