### ISSUE TITLE
phpmailer 5.2 stable

### ISSUE THREAD

**Issue by mooncloudmoon** [PHPMailer/PHPMailer#756]
this version 5.2 stable has a small problem.
when i use the class.phpmailer.php file to create a smtp object ,the fatal error occurs:
"Fatal error: Class 'SMTP' not found in E:\cloud\test\php\PHPMailer52\class.phpmailer.php on line 1443".
so you must require the class.smtp.php file manully or other files if you use the other protocols.

**Comment by Synchro** [comment]
No, it just means you didn't read the docs. Look at the readme file where it tells you how to load PHPMailer classes.

**Comment by mooncloudmoon** [comment]
Yeah, you are right. I didn't use the autoload.
This is my first time to use phpmailer, thank you very much.
----- 原始邮件 -----
发件人：Marcus Bointon <notifications@github.com>
收件人：PHPMailer/PHPMailer <PHPMailer@noreply.github.com>
抄送人：mooncloudmoon <mooncloudmoon@sina.com>,  Author <author@noreply.github.com>
主题：Re: [PHPMailer/PHPMailer] phpmailer 5.2 stable (#756)
日期：2016年06月22日 16点18分

No, it just means you didn't read the docs. Look at the readme file where it tells you how to load PHPMailer classes.

&mdash;
