### ISSUE TITLE
TURBO Smtp

### ISSUE THREAD

**Issue by ZoIcHi** [PHPMailer/PHPMailer#757]
Hello,
I ask if it was possible to integrate with the script, the SMTP service, which uses APIs, turboSMTP, for example.
Thank you
Greetings

**Comment by ooxi** [comment]
I don't quite understand your question. Could you please elaborate? For example what's *turboSMTP*?

**Comment by javicaballero** [comment]
I have the same issue with turboSMTP, that is a smtp server provider. More info: https://serversmtp.com
It only works using their API: https://serversmtp.com/turbo-api/#send-email
I can't use their API because we use Moodle Learning Platform that uses PHPMailer to send mails.

**Comment by Synchro** [comment]
Let me get this straight - you’re using an SMTP provider that doesn’t support SMTP?

If you want to use PHPMailer to generate a message that you can submit via HTTP, look at the `getSentMIMEMessage()` method that allows you to do just that.
