### ISSUE TITLE
Using the mailer in a foreach loop

### ISSUE THREAD

**Issue by sweepyoface** [PHPMailer/PHPMailer#759]
Hello, I am trying to use it for a mailing list and it seems to only be sending one email before stopping the loop. Should this be working?

http://pastebin.com/z92GhB90

Here's what happens;

1. Echoes the first email of the two in the table
2. Echoes the mailer stuff and sends to the first email
3. Echoes the second email

**Comment by Synchro** [comment]
This is a problem with your own logic. Look at the mailing list example provided with PHPMailer for how to do this properly.

**Comment by sweepyoface** [comment]
The issue with that is it shows everyone it was sent to in the email header, and I need to include a unique unsubscribe code for each email.

**Comment by Synchro** [comment]
So do what I suggested. The mailing list example does what you want.
