### ISSUE TITLE
getSentMIMEMessage return empty string

### ISSUE THREAD

**Issue by bawonsak** [PHPMailer/PHPMailer#760]
Hi,I call getSentMIMEMessage and return empty string.

error_reporting(E_ALL);
ini_set("display_errors", 1);

require("PHPMailer/PHPMailerAutoload.php");

$mail = new PHPMailer;
$mail->isHTML(true);   
$mail->Subject = 'Here is the subject';
$mail->Body    = 'This is the HTML message body <b>in bold!</b>';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

var_dump($mail->getSentMIMEMessage());

**Comment by Synchro** [comment]
Read the docs or the code; you need to call `preSend()` before that is populated.
