### ISSUE TITLE
Mail with attachments send to @icloud.com, @mac.com and @me.com unreadable by client

### ISSUE THREAD

**Issue by marcelmolenaar** [PHPMailer/PHPMailer#762]
Issue: mail with attachments send through PHPMailer to icloud emaildresses (@icloud.com, @mac.com and @me.com) appears unreadable by clients.

Cause:

Icloud don't like CRLF and LF used together in emails.

Reproduce:

Just send email with attachments through PHPMailer to icloud emailddress and try to open the mail.

Solution:
In PHPMailer class i changed this line:

public $LE = "\n";

into:

public $LE = PHP_EOL;

The constant PHP_EOL exist only on >= PHP 5.0.2 so i would like PHPMailer developers to check for this in new versions or check OS of server or something like that.

Regards,

Marcel

**Comment by boozy1** [comment]
The problem can be obfuscated. In some cases the smtp server will correct the inconsistent CR+LF en LF usage.
Also, the inconsistent CR+LF vs single LF starts after the headers, after the line "This is a multi-part message in MIME format." So it only comes clear when viewing the full original message with a text editor that can display CR and LF codes.

**Comment by Synchro** [comment]
I know that this is a problem - the RFCs make it very clear that bare LFs are not allowed, however, there are things relying on this broken behaviour - if you look at the change log you'll see that if was fixed and unfixed in the past for this reason. Fortunately we have a BC break in 6.0 so this can be fixed properly - please can you give that a try and see if it solves your problem.

**Comment by marcelmolenaar** [comment]
Thanks Marcus, i downloaded version 6.0 but i still see: public $LE = "\n"; there so that will be a problem again or did i download the wrong version?

**Comment by Synchro** [comment]
Suspect wrong version - check out the branch rather than the releases

**Comment by marcelmolenaar** [comment]
I am not very into github site, i just selected branche 6.0 in de select menu at the left and downloaded the zip file.

**Comment by Synchro** [comment]
Seems that the zip download still gives you the old version - look for the version constant inside the class to be sure. In 6.0 it's [defined differently](https://github.com/PHPMailer/PHPMailer/blob/6.0/src/PHPMailer.php#L606) as a class constant, and it's referenced everywhere as `static::LE`. You may need to clone the repo and check out the 6.0 branch.

**Comment by p1p4p3** [comment]
hi

**Comment by p1p4p3** [comment]
I am trying to get details with attachment from my website page to mail
 everything works fine except attachment. please help to fetch file path and from form and to pass in function.
also want to apply filter that people can upload doc/docx/pdf only.

i am getting this error
Fatal error: Uncaught exception 'phpmailerException' with message 'Could not access file: $filename' in public_html/test-email/mail/class.phpmailer.php:2466 Stack trace: #0 public_html/test-email/mail/3.php(139): PHPMailer->addAttachment('$filename', '') #1 {main} thrown in /public_html/test-email/mail/class.phpmailer.php on line 2466.

**Comment by Synchro** [comment]
That's just a basic PHP syntax problem - there is no interpolation in single-quoted strings. Do this:

    ...->addAttachment($filename, '');

Please [read the docs](http://php.net/manual/en/language.types.string.php) before posting, and don't hijack unrelated issues.

**Comment by Synchro** [comment]
Closing in favour of #953
