### ISSUE TITLE
Mail Rejected - TLS Required

### ISSUE THREAD

**Issue by kenITR** [PHPMailer/PHPMailer#767]
Email has been going well, but now some are being rejected with the diagnostic code: 503 Bad sequence of commands (TLS required)
I am using phpMailer in isSendMail mode with DKIM. All the DKIM stuff passes OK.
A curious line in the mail path says: 
Received: from [myDomain].com ([myDomain].com [nnn.nn.nnn.nn])
    (using TLSv1 with cipher DHE-RSA-AES256-SHA (256/256 bits))
    (No client certificate requested)
    by [myRecipient].mx.aol.com (Internet Inbound) with ESMTPS id D519A70000084
    for <[myRecipient]@aol.com>; Sun, 10 Jul 2016 23:57:23 -0400 (EDT)

Since I'm not using smtp (I believe) why is TLS being used and why is the receiving end saying it is required? How can I fix this?

Thanks.

**Comment by Synchro** [comment]
When you use isSendMail, PHPMailer hands off the message to your local MTA, which then deals with delivery. Many servers provide TLS on inbound, and all you're seeing is it being used. PHPMailer does something similar when acting as an SMTP client. PHPMailer is not involved in the transaction that is failing for you - it looks like a mail server bug, though I can't tell from your description whether the problem is at your end or theirs.

**Comment by kenITR** [comment]
Thanks, Marcus.

Is there any information I could give you or any way that would tell if 
it's on my end or theirs?

Ken

On 07/11/2016 12:45 PM, Marcus Bointon wrote:
>
> When you use isSendMail, PHPMailer hands off the message to your local 
> MTA, which then deals with delivery. Many servers provide TLS on 
> inbound, and all you're seeing is it being used. PHPMailer does 
> something similar when acting as an SMTP client. PHPMailer is not 
> involved in the transaction that is failing for you - it looks like a 
> mail server bug, though I can't tell from your description whether the 
> problem is at your end or theirs.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/PHPMailer/PHPMailer/issues/767#issuecomment-231792450>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AI_D7TQ7ivHYWCZYXyl6ecQ-GKJKLVphks5qUnMcgaJpZM4JJe8C>.
>


-- 
Ken Loomis
IT Resources
Lexington MA
781-863-2661 x111
