### ISSUE TITLE
Mail with attachments viewing on Iphone

### ISSUE THREAD

**Issue by h8itear** [PHPMailer/PHPMailer#769]
When viewing an email with an attachment(pdf in this case-approx 1mb) on a Iphone 6s (only one tested atm) The attachment is not shown/available.
When sending to other email clients(Outlook, Android) the attachment is shown and able to be opened.
When sending from outlook 2010 (same email and attachment) to same Iphone the attachment is shown and able to be opened.
I am using phpmailer 5.1

**Comment by capsandiego** [comment]
Did you find a solution for your issue? I'm having the same issue as you. Is related to phpMailer version? I can see the pdf on iPhone but I can't visualize embedded images in the email body. Did you try to use addEmbeddedImage() ?

**Comment by Synchro** [comment]
Version 5.1 is *very* old and buggy. Update it. Post your code, show exactly what the problem is.

**Comment by capsandiego** [comment]
I use php-7.0.3 on Windows 2012 Server. PHPMailer version is 5.2.14

When I send an HTML email to iPhone (iOS10) mail client with embedded images in the body email *together with* a file attachment, the email is unreadable (message received as text, embedded images not loaded). It works fine on any other email client.

<?php         
require_once("C:\\apps\\shared\\lib\\PHPMailer\\PHPMailerAutoload.php");
                            
$mail                   = new PHPMailer;
$mail->CharSet          = "UTF-8";
$mail->isSMTP();                                               // Set mailer to use SMTP
$mail->Host             = 'smtprelay1.example.com';       // Specify main and backup SMTP servers
$mail->SMTPAuth         = false;                               // Enable SMTP authentication
$mail->Port             = 25;                                  // TCP port to connect to
$mail->setFrom('SENDER@example.com', 'SENDER');
$mail->addReplyTo('sender@example.com', 'The Sender');
$mail->Subject          = 'iPhone - Test';
$mail->isHTML(true);
$mail->SMTPDebug        = false;
$mail->Debugoutput      = 'echo';

/* Add the pdf file as a normal attachment */
$mail->addAttachment("C:\\apps\\web\\pdf\\2098722387.pdf", "File.pdf");

/* Build the email body */
$_email_body = '';         
$_email_body = '
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Simple HTML Email</title>
        <style type="text/css">
            @media only screen and (min-device-width: 601px) {
            .content {width: 600px !important;}
            }
        </style>
    </head>
    <body>
    <table class="content" align="left" cellpadding="0" cellspacing="0" border="0">
    <tr><td style="font-family:calibri;">Hello World! 你好，世界！</td></tr>
';

$image_list  = array('789284757_1' => "C:\\apps\\web\\img\\1.jpg",
                     '789284757_2' => "C:\\apps\\web\\img\\2.gif",);
                     
foreach($image_list AS $id => $image_name_full){
   $mail->AddEmbeddedImage($image_name_full, $id, $id.'.gif', 'base64','image/jpeg'); 
   $_email_body .= '<tr><td><img src="cid:'.$id.'"></td></tr>';
}

/* set the email body */
$mail->Body  = $_email_body.'</table></body></html>'; 

/* send BCC email */
$mail->addAddress('SENDER@example.com','SENDER');
$mail->addBCC('someone@example.com');
$mail->send();
$mail->clearAttachments();
$mail->clearAllRecipients();
$mail = null;

**Comment by capsandiego** [comment]
Looks like it's an iPhone mail client bug. The embedded images are visible only after I kill the app and restart it. PHPMailer works fine!

**Comment by Synchro** [comment]
@capsandiego In the code you originally posted you were giving it two images - one gif, one jpeg. For both of them you were setting a `.gif` filename and an `image/jpeg` MIME type, so I'm not that surprised it wasn't happy.

**Comment by capsandiego** [comment]
@synchro Marcus, ops... I didn't note that indeed... I'll run again a full test session asap and come back with an update.
Thank you so much for your help!

**Comment by capsandiego** [comment]
@synchro Marcus, I did a full test again but nothing changes. All images are gif and the MIME is image/gif. The iPhone mail client problem occurs only if there are embedded images *and* a file attached (pdf in my case). The workaround solution is to kill/restart the iPhone mail app and the images will finally appear. Looks like iOS 10 needs some work to do...

**Comment by capsandiego** [comment]
I use php-7.0.3 on Windows 2012 Server. PHPMailer version is 5.2.14

When I send an HTML email to iPhone mail client with embedded images in the
body email *together with* a file attachment, the email is unreadable
(message received as text, embedded images not loaded).

<?php
require_once("C:\\apps\\shared\\lib\\PHPMailer\\PHPMailerAutoload.php");

$mail                   = new PHPMailer;
$mail->CharSet          = "UTF-8";
$mail->isSMTP();                                               // Set
mailer to use SMTP
$mail->Host             = 'smtprelay1.example.com';       // Specify main
and backup SMTP servers
$mail->SMTPAuth         = false;                               // Enable
SMTP authentication
$mail->Port             = 25;                                  // TCP port
to connect to
$mail->setFrom('SENDER@example.com', 'SENDER');
$mail->addReplyTo('sender@example.com', 'The Sender');
$mail->Subject          = 'iPhone - Test';
$mail->isHTML(true);
$mail->SMTPDebug        = false;
$mail->Debugoutput      = 'echo';

/* Add the pdf file as a normal attachment */
$mail->addAttachment("C:\\apps\\web\\pdf\\2098722387.pdf", "File.pdf");

/* Build the email body */
$_email_body = '';
$_email_body = '
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "
http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"
/>
        <title>Simple HTML Email</title>
        <style type="text/css">
            @media only screen and (min-device-width: 601px) {
            .content {width: 600px !important;}
            }
        </style>
    </head>
    <body>
    <table class="content" align="left" cellpadding="0" cellspacing="0"
border="0">
    <tr><td style="font-family:calibri;">Hello World! 你好，世界！</td></tr>
';

$image_list  = array('789284757_1' => "C:\\apps\\web\\img\\1.jpg",
                     '789284757_2' => "C:\\apps\\web\\img\\2.gif",);

foreach($image_list AS $id => $image_name_full){
   $mail->AddEmbeddedImage($image_name_full, $id, $id.'.gif',
'base64','image/jpeg');
   $_email_body .= '<tr><td><img src="cid:'.$id.'"></td></tr>';
}

/* set the email body */
$mail->Body  = $_email_body.'</table></body></html>';

/* send BCC email */
$mail->addAddress('SENDER@example.com','SENDER');
$mail->addBCC('someone@example.com');
$mail->send();
$mail->clearAttachments();
$mail->clearAllRecipients();
$mail = null;

**Comment by Solveta** [comment]
I have the same problem using phpmailer 5.2.15. It looks like 1 embedded image works, but the moment I embed the second one Mail on iOS often has problems (not Mail on MacOS). The images won't be shown (0 Bytes), but if you click on the dummy, you will see the image anyway. Very annoying. 

Does anybody found a solution for it? I

**Comment by capsandiego** [comment]
Solveta, this is an iOS bug, not PHPMailer. You can verify it by using Gmail or Outlook or another mail client. Send an email to your iPhone with a couple of embedded images *and* a 1MB+ file attached and you will see that the message will be flagged as "Downloaded as Plain Text" on your iPhone. 
The (very) sad thing is that, at least on iOS10.x, even when you click on "Donwload full Message" it will not show the embedded images anyway. Workaround is to double click on home button, kill the mail app and re-open the message.
I've opened 2 bugs on Apple website but no answer... (won't comment this)

**Comment by Solveta** [comment]
Thanks for your answer on this. And I will not comment about Apple as well - they were great, once. In the past...
