### ISSUE TITLE
Gmail SMTP - Connection: opening to smtp.gmail.com:587, timeout=300, options=array ()

### ISSUE THREAD

**Issue by UmrenTV** [PHPMailer/PHPMailer#770]
I am having Wordpress Hosting from GoDaddy, so my access to files and accounts is limited.
I can access to files through FTP, and that's it. No cPanel, nothing.

I get this Error when I try to send test email after I did everything correctly configuring the plugin.

Connection: opening to smtp.gmail.com:587, timeout=300, options=array ()
SMTP ERROR: Failed to connect to server: Connection refused (111)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

No idea what might be causing this... and I am not expert in coding / server administration, that is why I got this managed hosting :/

If there is anyone that can help, It will make my day, because my users are not getting confirmation emails when they register to the website to confirm account, so I have a brick wall here.

Thanks!

**Comment by Synchro** [comment]
This is covered in the troubleshooting guide linked from that error. GoDaddy blocks outbound SMTP. You either need to ask them to allow access, relay through their mailservers (in the `secureserver.net` domain, search their docs for that), or use a better ISP.

**Comment by Slinjez** [comment]
The trick is to use your host address.
This question has been answered here: https://stackoverflow.com/questions/21841834/phpmailer-godaddy-server-smtp-connection-refused/44255787#44255787

**Comment by Synchro** [comment]
That's not a general solution. When GoDaddy blocks outbound SMTP, it doesn't matter what you set `Host` to (if it's not one of GoDaddy's servers).

**Comment by neilkapadia7** [comment]
<?php
require 'phpmailer/PHPMailerAutoload.php';

$mail = new PHPMailer;        

                          // Set mailer to use SMTP
$mail->Host = "smtp.gmail.com";  // Specify main and backup SMTP servers
$mail->isSMTP(); 
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'neilkapadia7@gmail.com';                 // SMTP username
$mail->Password = 'neilkap7';                           // SMTP password
$mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 587;  
$mail->SMTPDebug = 4;
$mail->setFrom('neilkapadia7@gmail.com');
$mail->addAddress('neilkapadia7@gmail.com');  
   $mail->addReplyTo('neilkapadia7@gmail.com ');
$mail->addCC('neilkapadia7@gmail.com');
$mail->addBCC('neilkapadia7@gmail.com');
    
     $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = 'Here is the subject';
    $mail->Body    = 'This is the HTML message body <b>in bold!</b>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    
    if($mail->send()){
    echo 'Message has been sent';
    }
else{
   
    echo 'Message could not be sent. Mailer Error: ', $mail->ErrorInfo;
}

?>




have got a connection error please help.

**Comment by Synchro** [comment]
Read the thread before posting duplicates.

**Comment by mananth310** [comment]
unable to connect to smtp.gmail.com port 587
