### ISSUE TITLE
SMTP connect() failed

### ISSUE THREAD

**Issue by EricMcWinNer** [PHPMailer/PHPMailer#773]
I added all the files I needed here's my code 

``` php
<?php
require 'C:\wamp\www\phpmailer\PHPMailerAutoload.php';

$mail = new PHPMailer;

//$mail->SMTPDebug = 3;                               // Enable verbose debug output

$mail->isSMTP();                                      // Set mailer to use SMTP
$mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'eapriok@gmail.com';                 // SMTP username
$mail->Password = '***********';                           // SMTP password
$mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 587;                                    // TCP port to connect to

$mail->setFrom('from@example.com', 'Mailer');
$mail->addAddress('eapriok@gmail.com', 'Joe User');     // Add a recipient
$mail->addAddress('ellen@example.com');               // Name is optional
$mail->addReplyTo('info@example.com', 'Information');
$mail->addCC('cc@example.com');
$mail->addBCC('bcc@example.com');

$mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
$mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name
$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'Here is the subject';
$mail->Body    = 'This is the HTML message body <b>in bold!</b>';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

if(!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message has been sent';
}
?>
```

I replaced my password with stars. Please tell me what I did wrong

**Comment by Synchro** [comment]
At a guess, you didn't [read the docs](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting).

**Comment by EricMcWinNer** [comment]
Synchro I'll read it...but if you could identify my error, could you please tell me where I went wrong? Thanks

**Comment by Synchro** [comment]
No, I can't, because I don't have (or want) access to your server. In order to identify your error, I would go through the steps in the guide. It would tell me the same things it will tell you, but if you do it, it will be quicker and you might learn something. I can tell you that there's nothing wrong with your code - it will be a problem with your server.

**Comment by Ju1jan** [comment]
I'd like to share my experience in solving this.

Allowing access without captcha helped me:
https://accounts.google.com/DisplayUnlockCaptcha

 * * * 

I had to allow access (visit that link) directly before running script on local machine and once again before running on remote server.

Gmail refused access from suspicious (new?) devices/IPs.
And you have to allow authentication from new device. And then it'll work fine.

I'm not sure about other gmail settings. Maybe it's somewhere possible to allow access from any new device without captcha. But it's very insecure.

PS It Would be nice to add this link and info to documentation ("troubleshooting"). As far as i can see, some people are looking solution for such case. I tried all advices from doc, but only that trick helped me.

**Comment by Synchro** [comment]
@Ju1jan From the info posted, you have no way of telling that this is the problem. If you want to add your info to the wiki, go ahead, but make sure you clarify the precise circumstances that this applies - it's not a general solution to "SMTP connect() failed" as you're suggesting. Access without captcha is not insecure - it's advisable for signups, but adds very little for logins, other than to annoy legitimate users.

**Comment by Ju1jan** [comment]
@Synchro Thanks for notice. Yep. It's not general solution. It's just trick, that helped me in my case.
Anyway. It may be obvious from debug info ($mail->SMTPDebug = 4). thought, I spend some time to understand it)

**Comment by Synchro** [comment]
You could try a command-line web browser such as elinks or lynx. They have no javascript support by default, and you may have issues with captcha rendering, but they generally work pretty well.

**Comment by FalsAlarm** [comment]
I tried using lynx but it's different when you sign in to the web browser that is at the command line. I'm using lynx

**Comment by FalsAlarm** [comment]
ok so after installing lynx command line browser and visiting https://accounts.google.com/b/0/DisplayUnlockCaptcha

the email send is working fine now.

Hopefully this resolves the issue for erik
