### ISSUE TITLE
Certificate Verification Error

### ISSUE THREAD

**Issue by carvingpixel** [PHPMailer/PHPMailer#776]
Hi,

Im getting the stream_socket_enable_crypto(): SSL operation failed with code 1 but would like to fix it by resolving it correctly with the Certificate. I read the doc and see the following. "The correct fix for this is to replace the invalid, misconfigured or self-signed certificate". Is this referring to the installed SSL or the OpenSSL? Can someone point me in the direction to correctly resolve this without using the below workaround? I have 5.6.23 installed as well. Thanks!

$mail->SMTPOptions = array(
    'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )

**Comment by Synchro** [comment]
It depends on the certifiate that's being presented by your mail server. Try this:

    openssl s_client -starttls smtp -crlf -connect yourmailserver.example.com:587

That should give you more info about what's going on.

**Comment by carvingpixel** [comment]
I have openssl setup in php but not openssl with s_client installed as I am running a windows machine. Not finding a way to install for windows to cmd s_client, is it shell/linux only?

**Comment by carvingpixel** [comment]
didn't find starttls in server response, try anyway...
write: errno:10053
openssl> 3

**Comment by Synchro** [comment]
It could be that your ISP is transparently redirecting you to another server. Do a manual SMTP session with telnet and see if it comes up with a host name that sounds like office365. It works fine for me:

```
telnet smtp.office365.com 587
Trying 132.245.55.178...
Connected to outlook-emeasouth2.office365.com.
Escape character is '^]'.
220 AM3PR02CA0061.outlook.office365.com Microsoft ESMTP MAIL Service ready at Wed, 20 Jul 2016 20:12:08 +0000
EHLO localhost
250-AM3PR02CA0061.outlook.office365.com Hello [77.151.16.252]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-8BITMIME
250-BINARYMIME
250 CHUNKING
QUIT
221 2.0.0 Service closing transmission channel
Connection closed by foreign host.
```

**Comment by Synchro** [comment]
And with OpenSSL:

```
openssl s_client -starttls smtp -crlf -connect smtp.office365.com:587
CONNECTED(00000003)
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify return:1
depth=1 C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, OU = Microsoft IT, CN = Microsoft IT SSL SHA2
verify return:1
depth=0 C = US, ST = WA, L = Redmond, O = Microsoft Corporation, OU = Microsoft Corporation, CN = outlook.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=WA/L=Redmond/O=Microsoft Corporation/OU=Microsoft Corporation/CN=outlook.com
   i:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
 1 s:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIH3DCCBcSgAwIBAgITWgACDkKJ54xpWEiewQABAAIOQjANBgkqhkiG9w0BAQsF
ADCBizELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEVMBMGA1UE
CxMMTWljcm9zb2Z0IElUMR4wHAYDVQQDExVNaWNyb3NvZnQgSVQgU1NMIFNIQTIw
HhcNMTUxMDEzMjIyMDA0WhcNMTcxMDEyMjIyMDA0WjCBgjELMAkGA1UEBhMCVVMx
CzAJBgNVBAgTAldBMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
ZnQgQ29ycG9yYXRpb24xHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEU
MBIGA1UEAxMLb3V0bG9vay5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQDk/8ftuN2cH6i5FxI/CsvuILSy8G2eOknbQS32Fm55uosydk7oAlikv4g8
B9roHka5Sv7qBtaf9pDFdR4Yx3LgqSZl/ulYdpTlVFSbaYehQxx6CZzXmhSwk9ce
B6SxmqHP6XeTj/J/rbAEvEoQN62o/kIU9huX0aPx74NthU2HV89YtHuTJ1c5uPf9
vsN7tATRcgKYgPQW9EvK29Yj9Z8boEKam0gmm1Wi8RGRfKdtYjV9vKTBaNLxv4W1
vkV8eG4lhqspa9EejUwu+TsPb1k+W8dHAy3Sq/yfJVmIGAv7hr91hWdQAqpFoER3
eNmZ/h2fUcXmQXeyxryNsB+Lm3jnAgMBAAGjggM+MIIDOjALBgNVHQ8EBAMCBLAw
HQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMHgGCSqGSIb3DQEJDwRrMGkw
DgYIKoZIhvcNAwICAgCAMA4GCCqGSIb3DQMEAgIAgDALBglghkgBZQMEASowCwYJ
YIZIAWUDBAEtMAsGCWCGSAFlAwQBAjALBglghkgBZQMEAQUwBwYFKw4DAgcwCgYI
KoZIhvcNAwcwHQYDVR0OBBYEFJ2wmBwkWtSd7VFTxNf2urGNe5APMB8GA1UdIwQY
MBaAFFGvJCac9GgiV4AmKztGYhV7HsylMH0GA1UdHwR2MHQwcqBwoG6GNmh0dHA6
Ly9tc2NybC5taWNyb3NvZnQuY29tL3BraS9tc2NvcnAvY3JsL21zaXR3d3cyLmNy
bIY0aHR0cDovL2NybC5taWNyb3NvZnQuY29tL3BraS9tc2NvcnAvY3JsL21zaXR3
d3cyLmNybDBwBggrBgEFBQcBAQRkMGIwPAYIKwYBBQUHMAKGMGh0dHA6Ly93d3cu
bWljcm9zb2Z0LmNvbS9wa2kvbXNjb3JwL21zaXR3d3cyLmNydDAiBggrBgEFBQcw
AYYWaHR0cDovL29jc3AubXNvY3NwLmNvbTBOBgNVHSAERzBFMEMGCSsGAQQBgjcq
ATA2MDQGCCsGAQUFBwIBFihodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL21z
Y29ycC9jcHMAMCcGCSsGAQQBgjcVCgQaMBgwCgYIKwYBBQUHAwEwCgYIKwYBBQUH
AwIwgecGA1UdEQSB3zCB3IILb3V0bG9vay5jb22CDSoub3V0bG9vay5jb22CDW9m
ZmljZTM2NS5jb22CDyoub2ZmaWNlMzY1LmNvbYIKKi5saXZlLmNvbYIWKi5pbnRl
cm5hbC5vdXRsb29rLmNvbYIXKi5vdXRsb29rLm9mZmljZTM2NS5jb22CEm91dGxv
b2sub2ZmaWNlLmNvbYIdYXR0YWNobWVudC5vdXRsb29rLm9mZmljZS5uZXSCIGF0
dGFjaG1lbnQub3V0bG9vay5vZmZpY2VwcGUubmV0ggwqLm9mZmljZS5jb20wDQYJ
KoZIhvcNAQELBQADggIBAA1MnIS+r3GyiJjg2+Zsx7q94z48ovRQJqIG6/c7UUzK
6tEFkIepADfLszI+y4dYG7GP1j9e6K2a1StF2/tEjF21IA6NS/ITiOFXoStLQZ4T
I1Sb3IIQoOeWchtYf2KIQXYvQJutWuzp1gcRUH3xuHxKr+TFlIicWqQccnBYzUqV
dm92IhlHqdjT4kKIYjPDXEy+GMeh9+h2CVAgitsuZHfVL9V8ik3trkh6prGotca/
JZ06cKr7CWL/Yz0zNKkjvvTF/pJ6m4UvkuhSJoaZYU4Rj3jjWqj1IrP6pDsc99Yd
5HkUSkUq4xN8yhDuMDEKUQ/IjRTx1znWLzTELwZeRvDk2t4xXFJIsGxm8j1aL7+O
xXxrpM7hD71omQaxNa+4nYUuBDePp/1Ac/z7S2EPgRC/GMJ/UNcKfD/Hat8o1AP7
YT7RYF7GSqSxcEGKVhck5YAaQsbjjNdrx8N3Wo0qvu/BvJRGU79SvWgJAEfpbQFj
qF3x1NR+mlEriTuujqAehX8QYdTwKNLMJSF5ZickGNCi+klBAd1kmvTdY3wf3KYL
BQfUVkga1eLoqmWrPLFYhz8QFLF/GNiLkARIguAMZV77vc0Hl9UhN2wyEnBrfjmO
dZKD/3bIMhW1l49oCkxhFki3ED9xNPD0xEBPW72bx0HyYp7Ch/1s3XZR/IfFaKDB
-----END CERTIFICATE-----
subject=/C=US/ST=WA/L=Redmond/O=Microsoft Corporation/OU=Microsoft Corporation/CN=outlook.com
issuer=/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: RSA+SHA512:ECDSA+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA1:ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA1:DSA+SHA1
Shared Requested Signature Algorithms: RSA+SHA512:ECDSA+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA1:ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA1:DSA+SHA1
Peer signing digest: SHA1
Server Temp Key: ECDH, P-384, 384 bits
---
SSL handshake has read 4461 bytes and written 569 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA384
    Session-ID: 3B1400004334D7F089AE15E7FEC45427E32B682E0924CDB3396FCB270FDEDF04
    Session-ID-ctx:
    Master-Key: 69418EC3C7FF57D3094C28920B9FED57E3CB6BA99AD76B62064699AA6D996E68062097896C74137DFA8F417F3D2FD662
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1469045635
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
250 CHUNKING
QUIT
DONE
```

**Comment by carvingpixel** [comment]
yes, the telnet does seem to be having issues. We are sort of our own network but comcast runs our backbone. I'm thinking we might be having some tls issues too.  Thanks for the help and direction, cheers!

**Comment by carvingpixel** [comment]
now able to verify via openssl, but still getting that error like before.
OpenSSL> s_client -starttls smtp -crlf -connect smtp.office365.com:587
Loading 'screen' into random state - done
CONNECTED(00000144)
depth=1 /OU=generated by avast! antivirus for SSL/TLS scanning/O=avast! Web/Mail
 Shield/CN=avast! Web/Mail Shield Root
verify error:num=19:self signed certificate in certificate chain
verify return:0
---
Certificate chain
 0 s:/C=US/ST=WA/L=Redmond/O=Microsoft Corporation/OU=Microsoft Corporation/CN=o
utlook.com
   i:/OU=generated by avast! antivirus for SSL/TLS scanning/O=avast! Web/Mail Sh
ield/CN=avast! Web/Mail Shield Root
 1 s:/OU=generated by avast! antivirus for SSL/TLS scanning/O=avast! Web/Mail Sh
ield/CN=avast! Web/Mail Shield Root
   i:/OU=generated by avast! antivirus for SSL/TLS scanning/O=avast! Web/Mail Sh
ield/CN=avast! Web/Mail Shield Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIF4TCCBMmgAwIBAgIQfjhLdg7xrkew0gV5y6KmZDANBgkqhkiG9w0BAQsFADCB
hDE7MDkGA1UECwwyZ2VuZXJhdGVkIGJ5IGF2YXN0ISBhbnRpdmlydXMgZm9yIFNT
TC9UTFMgc2Nhbm5pbmcxHzAdBgNVBAoMFmF2YXN0ISBXZWIvTWFpbCBTaGllbGQx
JDAiBgNVBAMMG2F2YXN0ISBXZWIvTWFpbCBTaGllbGQgUm9vdDAeFw0xNTEwMTMy
MjIwMDRaFw0xNzEwMTIyMjIwMDRaMIGCMQswCQYDVQQGEwJVUzELMAkGA1UECBMC
V0ExEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3Jh
dGlvbjEeMBwGA1UECxMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMRQwEgYDVQQDEwtv
dXRsb29rLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALVWQNfN
gs2iygvN83aY6BknBS9eGtjH5sKokrlHLcOf7+28sDdeu9eLUUxQAmOKyVIN1EIW
DQWuVrL8d0zDpM9Oe39izrhuzcduirNQFzVsdAErxZWW65zo7+owIn/CXmXheSPm
CeMIIgYZIdJE1ANrlIPpwr222daege9zFquKSRyBoEQl4cqqCjLz11xhF1+x9xzE
cmE37EFfqiJxnfbbhSQOGuwpU8i188yC7U74NtxT6mCjZyDfeYtU3EGYvmzhSsKc
Sy3YKLsIuV1Q5YG4YnAwyuxSL89BzEuTY6L6WxvZNUlCmbleMl9AnRemDs8aDw2t
66qXz3WsCpjLAtECAwEAAaOCAk0wggJJMAsGA1UdDwQEAwIEsDAdBgNVHSUEFjAU
BggrBgEFBQcDAQYIKwYBBQUHAwIweAYJKoZIhvcNAQkPBGswaTAOBggqhkiG9w0D
AgICAIAwDgYIKoZIhvcNAwQCAgCAMAsGCWCGSAFlAwQBKjALBglghkgBZQMEAS0w
CwYJYIZIAWUDBAECMAsGCWCGSAFlAwQBBTAHBgUrDgMCBzAKBggqhkiG9w0DBzAd
BgNVHQ4EFgQUnbCYHCRa1J3tUVPE1/a6sY17kA8wHwYDVR0jBBgwFoAUMv1k242l
gdu6gDiswfv/CkT2QPwwTgYDVR0gBEcwRTBDBgkrBgEEAYI3KgEwNjA0BggrBgEF
BQcCARYoaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraS9tc2NvcnAvY3BzADAn
BgkrBgEEAYI3FQoEGjAYMAoGCCsGAQUFBwMBMAoGCCsGAQUFBwMCMIHnBgNVHREE
gd8wgdyCC291dGxvb2suY29tgg0qLm91dGxvb2suY29tgg1vZmZpY2UzNjUuY29t
gg8qLm9mZmljZTM2NS5jb22CCioubGl2ZS5jb22CFiouaW50ZXJuYWwub3V0bG9v
ay5jb22CFyoub3V0bG9vay5vZmZpY2UzNjUuY29tghJvdXRsb29rLm9mZmljZS5j
b22CHWF0dGFjaG1lbnQub3V0bG9vay5vZmZpY2UubmV0giBhdHRhY2htZW50Lm91
dGxvb2sub2ZmaWNlcHBlLm5ldIIMKi5vZmZpY2UuY29tMA0GCSqGSIb3DQEBCwUA
A4IBAQBukR7OhPEjxes1DnSPOOVWXyC9tYO4+Qlr8iw8s6z8eSrJ+AfZ5YLTj69t
M2clovaFSZEAIDy1oRycF30Dfiqt0AN2PlfFG5Bj+5u1OcAsyaI5VqPSeIN+F/IG
zsSgPFF5VTYnh3cZTk3T/BW9LSI4Uzwy+VyJAnVXHueK/w2Iv9pFCJXr8Ppywtc7
IDIqxX0BeTV9wrjjCxHFMUKj6aZ14sBd2PGr2RtvJBOhmynrDmHiHgCWHLDyCQ7r
PEr8pFAxanJ0w/1O32/FsH5PzLsKwUGzW2EJv8He7VHd3tK+WdzYNE96uoPSIPgP
2dSkEfS3S/3e9Nd4Zp/zV1xBPVF8
-----END CERTIFICATE-----
subject=/C=US/ST=WA/L=Redmond/O=Microsoft Corporation/OU=Microsoft Corporation/C
N=outlook.com
issuer=/OU=generated by avast! antivirus for SSL/TLS scanning/O=avast! Web/Mail
Shield/CN=avast! Web/Mail Shield Root
---
No client certificate CA names sent
---
SSL handshake has read 3543 bytes and written 357 bytes
---
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES256-SHA
Server public key is 2048 bit
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : DHE-RSA-AES256-SHA
    Session-ID: 22C9E9D814B120665E5D4470E8171436644F388219041FE5D6C5F00C93D48BB0

    Session-ID-ctx:
    Master-Key: 5745B7A1735B9E3FF8883FDDE59078988C35714EA9159E000D04892690BDD0EC
43F233ED5E27359CACFEE929CDF66840
    Key-Arg   : None
    Start Time: 1469106057
    Timeout   : 300 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
---
250 8BITMIME

**Comment by Synchro** [comment]
You can get more info on the cert, in particular to see `Server Alternate Name` entries:

    openssl s_client -connect smtp.office365.com:587 -starttls smtp | openssl x509 -noout -text

In this case it includes this:

```
X509v3 Subject Alternative Name:
                DNS:outlook.com, DNS:*.outlook.com, DNS:office365.com, DNS:*.office365.com, DNS:*.live.com, DNS:*.internal.outlook.com, DNS:*.outlook.office365.com, DNS:outlook.office.com, DNS:attachment.outlook.office.net, DNS:attachment.outlook.officeppe.net, DNS:*.office.com
```

In your output, the significant thing is this result code (note mine returns `0`):

    Verify return code: 19 (self signed certificate in certificate chain)

If you look back at the list of certificates in your chain:

```
   i:/OU=generated by avast! antivirus for SSL/TLS scanning/O=avast! Web/Mail Sh
ield/CN=avast! Web/Mail Shield Root
 1 s:/OU=generated by avast! antivirus for SSL/TLS scanning/O=avast! Web/Mail Sh
ield/CN=avast! Web/Mail Shield Root
   i:/OU=generated by avast! antivirus for SSL/TLS scanning/O=avast! Web/Mail Sh
ield/CN=avast! Web/Mail Shield Root
```
Then look at mine:
```
0 s:/C=US/ST=WA/L=Redmond/O=Microsoft Corporation/OU=Microsoft Corporation/CN=outlook.com
   i:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
 1 s:/C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT SSL SHA2
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
```
These do not match - it looks like your server is using some untrusted certificates from Avast. I think you should look at your CA cert file, or figure out why Avast is interfering with your config.

**Comment by carvingpixel** [comment]
I notice your verify return shows 1 whereas my verify return shows 0.  I also see this in mine >> verify error:num=19:self signed certificate in certificate chain.  Yours has CN = Baltimore CyberTrust Root. How to resolve my none local certificate?

**Comment by Synchro** [comment]
Your Avast software is interfering with your SSL. I've no idea how your configure that.

**Comment by carvingpixel** [comment]
Awesome, thanks a million again. I will check into the CA certificate and with my network counterpart regarding Avast! :D

**Comment by carvingpixel** [comment]
Disabled Avast until next reboot as a test because the server already has an SSL installed correctly which should suffice that requirement. The disable worked perfectly and the email went through! **Connection: closed Message has been sent**  Now we just have to config Avast! Thanks so much Synchro!! :+1:

**Comment by carvingpixel** [comment]
Additional info regarding Avast in case others find this:  Under Active Protection > Mail Shield > Customize > SSL Scanning > Scan SLL Connections will probably be checked. This was the case for us. We turned it off and this solved the issue on reboot and having Avast backup and running.  The info under SSL Scanning is below:
_The Mail Shield will scan your email even when SSL/TLS security is enabled in your mail client. If your mail client uses its own certificate store(YES, in this case), the SSL scan feature will **require you to export** the Mail Shield certificate to a file and then import it to your mail client._ 
It provides a button that allows you to then Export Certificate in the folllowing extensions .der, .crt, .perm 
if I am correct, you can then use the following code as well. 

$arrContextOptions=array(
    "ssl"=>array(
        "cafile" => "path/MailShield.pem",
        "verify_peer"=> true,
        "verify_peer_name"=> true,
    ),
);
