### ISSUE TITLE
Change language in success message

### ISSUE THREAD

**Issue by matteo1990** [PHPMailer/PHPMailer#778]
Hello everybody.
is it possibile to change the language of the success message. If so, how?
Thank you for your work guys!

**Comment by Synchro** [comment]
PHPMailer does not display success messages, it's up to your code to do that. The examples show how to display something in response to a successful/failed call to `send()`, but they are not part of the PHPMailer libraries. PHPMailer does provide translated *error* messages, but again it doesn't display them at all by default - but they are there if you want them.
