### ISSUE TITLE
Fatal Error: Call to a member function authorise() on a non-object

### ISSUE THREAD

**Issue by barreeeiroo** [PHPMailer/PHPMailer#780]
Hi

I have this error while opening my webpage with PHPMailer:
`Fatal error: Call to a member function authorise() on a non-object in /home/u289995868/public_html/es/php/class.user.php on line 115`
class.user.php is the file where i have the POP3 function.
Take a look to barreeeiroo.ga/es/php/fpass.php, there is the error.
Thanks

**Comment by Synchro** [comment]
This code is nothing to do with PHPMailer.
