### ISSUE TITLE
Unable to connect via SMTP Office 365

### ISSUE THREAD

**Issue by kdpk92** [PHPMailer/PHPMailer#783]
Hi,

I'm not able to send emails by the **SMTP settings** provideid by **Office365**.
**Server name:** smtp.office365.com
**Port:** 587
**Encryption method:** TLS

Please help me with this. Details are as follow::

My Code is this (below code is dummy as credentials/paths/names/email are not properly written here):
```

        require("path/to/PHPMailerAutoload.php");

        $_header = new PHPMailer;
        $_header->SMTPDebug = 2;
        $_header->isSMTP();
        $_header->SMTPAuth = true;

        $_header->Host = 'smtp.office365.com';
        $_header->Username = 'username';
        $_header->Password = 'password';
        $_header->SMTPSecure = 'TLS';
        $_header->Port = 587;

        $_header->setFrom(email, name);
        $_header->addReplyTo(email, name);
        $_header->addAddress(email, name);

        $_header->isHTML(true);
        $_header->Subject = 'Subject';
        $_header->Body = 'Body';

        if($_header->send()){
            http_response_code(200);
            exit();
        }else{
            http_response_code(403);
            exit();
        }
```

Error I'm getting is this:

> 2016-07-24 18:14:49	SERVER -> CLIENT: 220-sg2plcpnl0074.prod.sin2.secureserver.net ESMTP Exim 4.87 #1
>  Sun, 24 Jul 2016 11:14:49 -0700 
>                    	                  220-We do not authorize the use of this system to transport unsolicited
> , 
>                    	                  220 and/or bulk e-mail.
> 2016-07-24 18:14:49	CLIENT -> SERVER: EHLO kumardeepak.xyz
> 2016-07-24 18:14:49	SERVER -> CLIENT: 250-sg2plcpnl0074.prod.sin2.secureserver.net Hello sg2plcpnl0074
> .prod.sin2.secureserver.net [182.50.151.55]
>                    	                  250-SIZE 52428800
>                    	                  250-8BITMIME
>                    	                  250-PIPELINING
>                    	                  250-AUTH PLAIN LOGIN
>                    	                  250-STARTTLS
>                    	                  250 HELP
> 2016-07-24 18:14:49	CLIENT -> SERVER: STARTTLS
> 2016-07-24 18:14:49	SERVER -> CLIENT: 220 TLS go ahead
> 2016-07-24 18:14:49	CLIENT -> SERVER: EHLO kumardeepak.xyz
> 2016-07-24 18:14:49	SERVER -> CLIENT: 250-sg2plcpnl0074.prod.sin2.secureserver.net Hello sg2plcpnl0074
> .prod.sin2.secureserver.net [182.50.151.55]
>                    	                  250-SIZE 52428800
>                    	                  250-8BITMIME
>                    	                  250-PIPELINING
>                    	                  250-AUTH PLAIN LOGIN
>                    	                  250 HELP
>**2016-07-24 18:14:49	CLIENT -> SERVER: AUTH LOGIN
> 2016-07-24 18:14:49	SERVER -> CLIENT: 334 VXNlcm5hbWU6
> 2016-07-24 18:14:49	CLIENT -> SERVER: aW5ib3hAa3VtYXJkZWVwYWsueHl6
> 2016-07-24 18:14:49	SERVER -> CLIENT: 334 UGFzc3dvcmQ6
> 2016-07-24 18:14:49	CLIENT -> SERVER: ZWwhMjAxNkk7
> 2016-07-24 18:14:51	SERVER -> CLIENT: 535 Incorrect authentication data
> 2016-07-24 18:14:51	SMTP ERROR: Password command failed: 535 Incorrect authentication data
> 2016-07-24 18:14:51	SMTP Error: Could not authenticate.
> 2016-07-24 18:14:51	CLIENT -> SERVER: QUIT
> 2016-07-24 18:14:51	SERVER -> CLIENT: 221 sg2plcpnl0074.prod.sin2.secureserver.net closing connection**
> 
> **_2016-07-24 18:14:51	SMTP connect() failed._** https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
The guide linked from the error covers this - your server is not the one you asked to connect to (`smtp.office365.com`) - it's being intercepted and redirected to a different server (`*.secureserver.net`), so it will fail SSL certificate verification, and you've also given away your Office credentials to the MITM-attack this represents. You're using GoDaddy which is known to do this. You need to explicitly use their servers as they block outbound SMTP - you'll need to refer to their docs for details.
