### ISSUE TITLE
DKIM Problem - openssl_sign

### ISSUE THREAD

**Issue by ZoIcHi** [PHPMailer/PHPMailer#785]
Hello
I have this problem with DKIM_Sign

My PHPMailer settings is this:
$mail->DKIM_domain  = "mydomain.it";
$mail->DKIM_private = dirname(**FILE**) . "/../private/.htkeyprivate";
$mail->DKIM_selector    = "phpmailer";
$mail->DKIM_passphrase  = "1469625919";
$mail->DKIM_identity    = "newsletter@mydomain.it";

I also checked the DNS setting from http://dkimcore.org/c/keycheck, and the DKIM key record is valid.

I send with SMTP, and from debug,  appears this error:
**_Warning: openssl_sign() expects parameter 4 to be long, string given in /includes/class_mail/class.phpmailer.php on line 3694_**

I opened the class and do not understand where is the problem.
It can be a problem php.ini or server / apache settings?

Thanks for your attention and support.
Greetings
A

**Comment by Synchro** [comment]
[The docs on `openssl_sign`](http://php.net/manual/en/function.openssl-sign.php) say that parameter 4 can be a `string` or an `int` (i.e. a `long`). PHPMailer passes in a string containing `sha256WithRSAEncryption`, which is in fact the exact value used in the docs! All I can think is that you're using an old vesion of PHP that does not contain that signature mechanism.

**Comment by ZoIcHi** [comment]
HI,
thanks you for your quick reply.

You're probably right, in my hosting use PHP 5.2.9 with OpenSSL 0.9.8g module.

On StackOverflow I found this solution:
**_http://stackoverflow.com/questions/10524198/what-version-of-openssl-is-needed-to-sign-with-sha256withrsaencryption/11117338#11117338_**

you can use this function in your class?

Thanks again
Greetings
A

**Comment by Synchro** [comment]
Both of those are very old, no longer supported and are known to contain security holes, so I'd recommend you upgrade if you can. Thanks for the pointer to that workaround - I have added an implementation in master - please give it a try.
