### ISSUE TITLE
Duplicate emails being sent out

### ISSUE THREAD

**Issue by nestsman** [PHPMailer/PHPMailer#786]
Every once in a while one of my members will contact me to say they got several duplicate emails from my website.  I check in the mySQL database and verify that there was only one row for that particular email.  Is it a known issue/bug that PHPMailer will sometimes send multiple copies?

Is there anything in one of the logs, like exim_mainlog, that would provide further information on what causes this?

Thank you!

**Comment by Synchro** [comment]
No, PHPMailer doesn't send multiple copies, but it's very common for browsers to send duplicate requests, especially caused by some plug-ins.
