### ISSUE TITLE
PHPMailer said the emails were sent

### ISSUE THREAD

**Issue by nestsman** [PHPMailer/PHPMailer#787]
Just curious, how come PHPMailer will not trigger an error, and makes it appear that an email was successfully sent, when, in reality, I get an error like this in exim_mainlog:

2016-07-20 14:18:21 1bPxwi-0001xA-Te SMTP error from remote mail server after MAIL FROM:<test@example.com> SIZE=15763: 421 4.7.0 [TS01] Messages from 198.500.500.500 temporarily deferred due to user complaints - 4.16.55.1; see https://help.yahoo.com/kb/postmaster/SLN3434.html

Any suggestions would be appreciated.

Thank you!

**Comment by Synchro** [comment]
PHPMailer's involvement ends when it delivers the message to your mail server. The chain goes like this:

    PHPMailer -> your local Exim -> recipient's server

If the delivery then fails from that point onwards, you won't get to know about it unless your configure a bounce handler to receive the undelivered message back from Exim, and that's entirely outside PHPMailer's remit.

**Comment by Synchro** [comment]
Also, that's not a bounce - it's a deferral. The message will still be delivered later on. This is why you want to use a proper local mail server with queuing and retrying, and not try sending directly to Yahoo - PHPMailer isn't a full MTA (mail server).
