### ISSUE TITLE
Multiple BCC adress with custom body ?

### ISSUE THREAD

**Issue by Cyboulette** [PHPMailer/PHPMailer#789]
Hi,

I use BCC in my newsletter System and I want to know if its possible to customize the body for each BCC.

Example : 
a@a.fr | b@b.fr <- List of BCC adress
Message Body for a@a.fr :
Hello a@a.fr etc..
Message Body for b@b.fr :
Hello b@b.fr

It can be considered such as function returning the "current mail to send". I don't know if its technically possible ;)

**Comment by Synchro** [comment]
No. All recipients receive exactly the same message. If you want different content, you must send separate messages. Look at the mailing list example provided.
