### ISSUE TITLE
AddCC() and AddBCC() not working on "mail" mailer

### ISSUE THREAD

**Issue by klemm89** [PHPMailer/PHPMailer#79]
If these functions only work with SMTP mailer on win32, what would you recommend doing for AddCC in a UNIX based mail?

**Comment by kyleguate** [comment]
This is still an issue, see attached:
<img width="678" alt="phpmailer incorrect comment" src="https://user-images.githubusercontent.com/2439801/29398653-13566528-82e3-11e7-8494-3d1e0992e2f2.png">

Would you like a MR removing that `note` line?
