### ISSUE TITLE
SMTP connect() failed - Different issue

### ISSUE THREAD

**Issue by therockers** [PHPMailer/PHPMailer#790]
So my issue is different from most **SMTP connect() failed** issues. I was able to send email using PHPMailer on Windows, but then I decided to test it on CentOS. Using the exact same copy configuration file (just copied&pasted into a USB and copied&pasted from the USB to CentOS), I get the **SMTP connect() failed** error message when in fact they are the same identical copy. I've re-tested the one on Windows and it works every single time I refresh the page even after restarting Apache on Windows, it still works. However, testing it on CentOS gives me the **SMTP connect() failed** error message. Since the configuration files are the exact same copy, the SMTP credentials are exactly the same. If I were to change the password on my website's email, it would also fail on Windows since it is the same exact copy. But it doesn't. It only happens on CentOS. I will try Ubuntu tomorrow, but why does it happen when I switch to Linux?

-------------------------

Another thought is maybe my hosting provider only allows Windows to access the SMTP. I will ask my hosting provider right now. I will most likely get a reply later on in the day though.

**Comment by Synchro** [comment]
Are they on the same network? What did the tests from the troubleshooting guide tell you?

**Comment by therockers** [comment]
@Synchro They are all on the same network. The debugger says "Permission denied". I just tried it on my Ubuntu OS and it's working. Maybe it's one of the core files that is messing up. The configuration files are exactly the same, but not the core files. The one on the CentOS has a little more stuff added to the core files which then requires the configuration file which then will use PHPMailer. I will have to copy over this copy again and try to see if it is because of the core files.

**Comment by Synchro** [comment]
I'd check your system logs for something like SELinux contraventions, which I think CentOS enforces by default.

**Comment by therockers** [comment]
@Synchro
I gave up on the issue. If one of my clients use CentOS, I'll just warn them about this issue.
