### ISSUE TITLE
Can't set Received: in email header?

### ISSUE THREAD

**Issue by wazirsoft** [PHPMailer/PHPMailer#792]
I can set header using `addCustomHeader` method but only `Received` field can't be set - where is the phpmailer removing the `Received`? I can't seem to figure that out - please help me with that - I am testing but nothign comes out when it comes to `Received` field in header

Thanks

**Comment by Synchro** [comment]
Why are you setting the received header? This makes no sense - by definition you're a mail client, originating a new message, so you have no data to put into the header! Received headers are added by servers when they receive a message.

PHPMailer doesn't remove anything, it's probably your mail server.

**Comment by bjoernv** [comment]
Please re-open this bug. Adding custom Received headers can by very useful. For instance the Horde IMP web-mailer creates a custom received header which contains information about the sender (hostname and IP).

**Comment by wazirsoft** [comment]
@bjoernv no as @Synchro said it's not a problem with phpmailer but my SMTP was removing "Received" not phpmailer

**Comment by bjoernv** [comment]
@wazirsoft but my Horde installation is able to create custom Received headers. So in PHP Mailer it probably depends on which mailing method is used (see functions isSendmail(), isQmail, isMail() etc.).

**Comment by Synchro** [comment]
As I said, and as @wazirsoft said I said, PHPMailer *will* add Received headers if you ask it to - it doesn't prevent you doing so at all. If they are subsequently being stripped by your mail server, that's not anything that PHPMailer can do anything about, so this ticket will remain closed. Try setting `SMTPDebug = 2` and you should see the headers being sent to the mail server. If they are not there when you receive the message, it's nothing to do with the sending software.

**Comment by bjoernv** [comment]
Yes, after some testing and code reading I see, that this is not a bug, it is more a documentation and configuration issue. On my system only the default configuration (with PHPs 'mail' function) shows the problem, that custom Received headers are removed. Also PHPMailer does not contain any helper functions to deal with client IPs or hostname. I wrote my own functions for this.
