### ISSUE TITLE
Mailer Error: SMTP connect() failed

### ISSUE THREAD

**Issue by s26** [PHPMailer/PHPMailer#793]
Hi,

I am using gearman in production successfully in background(nohup) process.

What I want is multiple workers. For that I have used supervisor and create two processes.

After using supervisor I am getting Mailer Error: SMTP connect() failed. It is not showing any error message on supervisor process's log file.

I have stopped my backgrouond process before starting supervisor processes.

**Comment by Synchro** [comment]
Have you done what [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting) says? It would help to see your code.

**Comment by s26** [comment]
@Synchro Thanks for pointing to the troubleshooting guide. figured out the issue with the help of SMTPDebug. I have setup environment variable and somehow it was giving blank result for smtp host,username,password.
