### ISSUE TITLE
WP_Mail is not working in WordPress

### ISSUE THREAD

**Issue by chasmckjr** [PHPMailer/PHPMailer#799]
How can I test wp mail on a page in WordPress.  In the settings it tested positive.  Below is the php on the page I'm trying

```php
<?php

if( isset( $_POST['action'] ) ) {

//From email address and name

//To address and name
$to = "krystal.harter@gmail.com", "tiffany@voice-exchange.com", “cimcollier@gmail.com”,  “lovellsmith7@gmail.co);

$subject = "New Medical Client";

$body = "Account Number: __________________________"
"Call Forwarding Number: __________________________"
"Professional Business Name: " . $busnme .
"Specialty: " . $spec
"Tax ID: " . $taxid
"Name of Highest Ranking Officer: " . $rankoff
"Social Security Number of Highest Ranking Officer: " . $socsecrankoff
"Birth Date of Highest Ranking Officer: " . $birthdate
"Business Address: " . $bussadd
"Billing Address: " . $billadd
"Office Open Days & Hours: " . $dayhr
"Telephone Numbers: " . $phnum
"Private Line (Back UP): " . $privln
"Fax: " . $fax
"Do You Want Daily Fax: " . $faxyesno
"If Yes, Time and Days to Fax: " . $tmedayfax
"Do You Want Voice Mail: " . $voicemail
"Do You Want Email: " . $doemail
"If Yes, Time and Days To Email: " . $tmedayemail
"Answer Phrase You Would Like Us To Use When Answering Your Line: " . phrase
"Call Schedule: " . $callsch
"Times Call Schedule In Effect? " . $cllschdayfr . "To" . $cllschdayto
"WeekEnd: " . $cllschwkendfr . "To" . $cllschwkendto
"Doctor(s) and Office Staff We Will Be Contacting: "
"Name: " . $name
"Home: " . $home
"Pager: " . $pager
"*THIS INFORMATION MUST BE COMPLETED BEFORE SERVICE IS IMPLEMENTED*
"Client's Name: " . $clntnme
"Client's ESignature: " . $clntsig;
}

add_filter('wp_mail_content_type',create_function('', 'return "text/html"; '));
 
 wp_mail("chasmckjr@hotmail.com, $subject, $body)
}
if(!$mail(send)) 
{
    echo "Mailer Error: " . $mail(ErrorInfo);
} 
else 
{
    echo "Message has been sent successfully";
}
```

**Comment by Synchro** [comment]
This code makes very little sense, I'm surprised it even runs. Where is `$mail` set?

**Comment by chasmckjr** [comment]
My apologies I copied the wrong code over.  Here it is.  Also I am very new to Wordpress.  It's a lot I don't understand.

<?php

require("class.PHPMailer.php");

//PHPMailer Object
$mail = new PHPMailer;

if( isset( $_POST['action'] ) ) {

//From email address and name
$mail->From = "hello@voice-exchange.com";
$mail->FromName = "Voice Exchange";

//To address and name
$mail->addAddress("krystal.harter@gmail.com", "Krystal Harter");

//Address to which recipient will reply
$mail->addReplyTo("no-reply@voice-exchange.com", "No Reply");

//CC and BCC
$mail->addCC("tiffany@voice-exchange.com", “cimcollier@gmail.com”,  “lovellsmith7@gmail.com”);

//Send HTML or Plain Text email
$mail->isHTML(true);

$mail->Subject = "New Medical Client";
$mail->Body = "Account Number: __________________________"
"Call Forwarding Number: __________________________"
"Professional Business Name: " . $busnme .
"Specialty: " . $spec
"Tax ID: " . $taxid
"Name of Highest Ranking Officer: " . $rankoff
"Social Security Number of Highest Ranking Officer: " . $socsecrankoff
"Birth Date of Highest Ranking Officer: " . $birthdate
"Business Address: " . $bussadd
"Billing Address: " . $billadd
"Office Open Days & Hours: " . $dayhr
"Telephone Numbers: " . $phnum
"Private Line (Back UP): " . $privln
"Fax: " . $fax
"Do You Want Daily Fax: " . $faxyesno
"If Yes, Time and Days to Fax: " . $tmedayfax
"Do You Want Voice Mail: " . $voicemail
"Do You Want Email: " . $doemail
"If Yes, Time and Days To Email: " . $tmedayemail
"Answer Phrase You Would Like Us To Use When Answering Your Line: " . phrase
"Call Schedule: " . $callsch
"Times Call Schedule In Effect? " . $cllschdayfr . "To" . $cllschdayto
"WeekEnd: " . $cllschwkendfr . "To" . $cllschwkendto
"Doctor(s) and Office Staff We Will Be Contacting: "
"Name: " . $name
"Home: " . $home
"Pager: " . $pager
"*THIS INFORMATION MUST BE COMPLETED BEFORE SERVICE IS IMPLEMENTED*
"Client's Name: " . $clntnme
"Client's ESignature: " . $clntsig”;
$mail->AltBody = "Please Do Not Reply To This Email!!!";
}


if(!$mail->send()) 
{
    echo "Mailer Error: " . $mail->ErrorInfo;
} 
else 
{
    echo "Message has been sent successfully";
}

**Comment by Synchro** [comment]
OK, so what errors are you seeing? I assume you've checked that all those vars like `$name` are populated properly? You're attemping to send even if `$_POST['action']` is not set - move the sending part inside that `if` statement. You're using the default mailer, so you're sending via the `mail()` function which will go via your local mail server, so you should look at your mail server logs too, usually in `/var/log/mail.log`.

**Comment by chasmckjr** [comment]
My vars are good. They are coming from an html form.  I'm not getting an error message.  I didn't realize part of my code shows on the website.  It looks like where I'm using Mail ->, the code is showing up on the web page.  I'm trying to use wp_mail

**Comment by chasmckjr** [comment]
I'm using a plugin Allow PHP execute.  I thought it will let me put the PHP right on the page

**Comment by chasmckjr** [comment]
It there a script I can run on a page to test the wp_mail.  Just to see if it's working on a wordpress page.  I tested it in settings email and it sends the email.

**Comment by chasmckjr** [comment]
Did I loose my help?

**Comment by chasmckjr** [comment]
Did I lose my help?

**Comment by Synchro** [comment]
This isn't the place to ask about using wp_mail, I've no idea about it, though it may well be using PHPMailer internally.

**Comment by chasmckjr** [comment]
ok thanks
