### ISSUE TITLE
How to set an "on behalf of" email address?

### ISSUE THREAD

**Issue by ADTC** [PHPMailer/PHPMailer#800]
What's the simplest way to set an "on behalf of" email address? For example:

> **From:** Jane \<jane@example.com\> _on behalf of_ Bob \<bob@example.com\>

Sorry if this is a dumb question...

**Comment by Synchro** [comment]
That's a client feature of Outlook/hotmail, not a sender thing. It's used when the sender is not authorised to send in their own name, so it's often an indication of fraud or forgery, not something I'd be trying to do on purpose. Gmail used to do it but it was so unpolular they stopped.

**Comment by ADTC** [comment]
Oh I didn't know. What's the best way to make a contact form in PHP send email from a generic email address, but make the email look like it's coming from a personal email address? I thought "on behalf of" would work:
> Contact Form \<contactform@mywebsite.com\> on behalf of Jane \<jane@example.com\>

I know about "Reply To" and it works, but the original email still appears to come from generic email address:
> Contact Form \<contactform@mywebsite.com\>

I am settling to simply show the submitter's name and email address in the From's name part, likewise:
> Jane (jane@example.com) \<contactform@mywebsite.com\>

This is the closest I can get. Unless there's a better way.

**Comment by Synchro** [comment]
No, that's as close as you can get - though you should be able to use any From address in your own domain. Don't try to use the submitters name in the from address as that will cause SPF failures.

**Comment by ADTC** [comment]
> Don't try to use the submitters name in the from address as that will cause SPF failures.

Could you give me an example? The last format works fine for me, as the email address of the submitter is **not** in angle brackets but in parentheses. Note that the angle brackets contains the email address in my domain (and which I can send a message "from"), so the message is sent correctly. The message is only sent internally and will never go directly to an external email server (different domain). Should I still be worried about SPF failures?

**Comment by ooxi** [comment]
> Jane (jane@example.com) <contactform@mywebsite.com>

Using this will not give you SPF failures, since SPF will be evaluated against `contactform@mywebsite.com`. SPF failures are generated by your mail server so if you never ever send to external servers, feel free to send as `Jane <jane@example.com>` and configure your mail server to ignore SPF rules.

**Comment by ADTC** [comment]
The last bit is interesting. Perhaps I could ignore SPF rules for emails sent to internal addresses (still applying them for those going external). It would be possible to do the configuration if I'm running my own mail server. But I'm using a cloud service, so it may not be possible. I will need to check.

Thanks for the insight, @ooxi .
