### ISSUE TITLE
Newsletter for 20.000 recipients?

### ISSUE THREAD

**Issue by markknochen1** [PHPMailer/PHPMailer#807]
Hi,
i have to send a newsletter to many recipients ...
Is it possible to send 20.000 mails with for each mail "addAddress()"?

Or is there a problem?

Thank you

**Comment by Synchro** [comment]
Volume isn't a problem, but don't do it like that. Send each message separately. Look at the mailing list example provided with PHPMailer. You'll need to have a reasonably good mail server to allow you to send this kind of volume.
