### ISSUE TITLE
PHPMailer SMTP ERROR

### ISSUE THREAD

**Issue by SalientAnimal** [PHPMailer/PHPMailer#808]
Hi All,

I am running a Windows server, with Apache, php, and of coarse PHPMailer. I tested the configuration on my local machine and most of the configuration worked fine.

When trying to implement PHPMailer on the Windows Server, the mail sending does not want to work. I get the following error message:

> SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: No such host is known. (0) 2016-08-18 13:56:25	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting Message was not sent.Mailer error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

The only difference between the two instances is the operating system. Could someone assist my in where I may be going wrong?

Here is my code:

```php
require("../PHPMailerAutoload.php"); // path to the PHPMailerAutoload.php file.

$headers  = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
    $body = "<html>\n"; 
    $body .= "<body style=\"font-family:Verdana, Verdana, Geneva, sans-serif; font-size:12px; color:#344433;\">\n"; 
    $body = $message; 
    $body .= "</body>\n"; 
    $body .= "</html>\n";

// Additional headers

$subject = 'Test Export' ."\r\n";

// $headers .= 'Cc: birthdayarchive@example.com' . "\r\n";
// $headers .= 'Bcc: birthdaycheck@example.com' . "\r\n";

   $mail = new PHPMailer();
   $mail->IsSMTP(true);
   $mail->SMTPDebug = 1;   
   $mail->Mailer = "smtp";
   $mail->Host = "smtp.sebenzela.co.za";
   $mail->Port = 587; 						// 8025, 587 and 25 can also be used. Use Port 465 for SSL.
   $mail->SMTPAuth = true;
   $mail->SMTPSecure = 'tls';   
   $mail->Username = "USERNAME";
   $mail->Password = "PASSWORD";
   $mail->CharSet = "UTF-8";
   $mail->SMTPOptions = array( 				// Bypass security verification on e-mail. WARNING: When using this method, 
    'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )
);
  
    
   $mail->From     = 'FROMADDRESS@FROMDOMAIN.co.za';
   $mail->FromName = 'FROM NAME';
   $mail->AddAddress('TOADDRESS@TODOMAIN.co.za', 'Leon Claassen');
   $mail->AddReplyTo('me@mymailserver.com', 'My Name');
 
   $mail->Subject  = $subject;
   $mail->Body     = $body."\r\n";
   $mail->WordWrap = 50;  
 
   if(!$mail->Send()) {
		echo 'Message was not sent.';
		echo 'Mailer error: ' . $mail->ErrorInfo;
		exit;
   } else {
		echo 'Message has been sent.';
   }





mysqli_close($con); 


?>
```

I am using the most recent versions of PHPMailer and PHP. 
Have I perhaps missed some configuration steps in the config files?
I downloaded a fresh copy for both systems of PHPMAiler & PHP, I did not duplicate the config files.

**Comment by Synchro** [comment]
This isn't anything to do with PHP or PHPMailer - it means your server's DNS config is broken. This is covered in the troubleshoting guide that the error message links to. Fix your DNS and PHPMailer will be able to work.

**Comment by SalientAnimal** [comment]
Hi there, 

I know there error is somewhere on my side, which is why I was asking for advice.

I wasn't sure if I had not configured something correctly.

What I would like to know is, is the error on the Webserver? Or would it be a problem on the mail server that I would need to take up with the ISP?

Thanks

**Comment by Synchro** [comment]
It will be wherever the script is running, so on your web server. The problem is that the web server can't find the IP address of your mail server from the name you've given it (`smtp.sebenzela.co.za`), hence the error. Read the guide and do the tests that it suggests, which will tell you what's going wrong, but it can't tell you how to fix it.

**Comment by SalientAnimal** [comment]
Thanks, I will try this when I am back in the office tomorrow. 

 

I read through the suggested trouble shooting guide. Are you able to suggest a dnsutils that I would be able to use on Windows Server? As this seems to be for Debian/Ubuntu, or am I mistaken?

**Comment by Synchro** [comment]
I can't really be much help on the windows admin front, but you could try [nslookup](https://technet.microsoft.com/en-us/library/bb490950.aspx?f=255&MSPPError=-2147217396)

**Comment by SalientAnimal** [comment]
Hi there,

I just wanted to say thanks for your help yesterday. I'm not able to understand why my server can not resolve the host name. 

I have changed my host attribute to reflect the smtp mail server's IP address and the mail function now works.

I know this isn't normal practice, and just want to be sure that there isn't a security risk or any other risks of configuring it in this way?

Thanks again, as pretty much a newbie, every bit of help goes a long way.
