### ISSUE TITLE
SERVER -> CLIENT: 250 Data Dropped

### ISSUE THREAD

**Issue by sudarshansaha** [PHPMailer/PHPMailer#809]
Here is my system details
OS: Fedora 21, 64 bit
localhost
Apache server

Here is my code
```php
<?php
require 'PHPMailer-master/PHPMailerAutoload.php';

$mail = new PHPMailer;
$mail->SMTPDebug = 3;
$mail->Debugoutput = 'html';

$mail->isSMTP();
$mail->SMTPAutoTLS = false;

$mail->Host = "tls://smtp.mail.yahoo.com:587";
$mail->SMTPAuth = true;
$mail->Username = "someone@yahoo.com";
$mail->Password = "************";
$mail->SMTPSecure = 'tls';
$mail->Port = 587;

$mail->From = "someone@yahoo.com";
$mail->FromName = 'someone';
$mail->addAddress('someone_else@gmail.com', 'someone_else');
$mail->isHTML(true);
$mail->Subject = 'Test Email';
$mail->Body = 'Hi this is a test email so please ignore it';

$mail->SMTPOptions = array(
    'ssl' => array(
       'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )
);

if(!$mail->send()) {
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    //perform success actions
	echo 'mail was sent';
//    exit();
}
$mail->SmtpClose();
?>
```
Here is Mailer Error
```
Connection: opening to smtp.mail.yahoo.com:587, timeout=300, options=array ( 'ssl' => array ( 'verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true, ),)
Connection: opened
SERVER -> CLIENT: 220 smtp.mail.yahoo.com ESMTP ready
CLIENT -> SERVER: EHLO localhost
SERVER -> CLIENT: 250-smtp.mail.yahoo.com250-PIPELINING250-SIZE 41697280250-8 BITMIME250 STARTTLS
CLIENT -> SERVER: STARTTLS
SERVER -> CLIENT: 220 2.0.0 Start TLS
CLIENT -> SERVER: EHLO localhost
SERVER -> CLIENT: 250-smtp.mail.yahoo.com250-PIPELINING250-SIZE 41697280250-8 BITMIME250 AUTH PLAIN LOGIN XOAUTH2 XYMCOOKIE
CLIENT -> SERVER: AUTH LOGIN
SERVER -> CLIENT: 334 VXNlcm5hbWU6
CLIENT -> SERVER: xxx
SERVER -> CLIENT: 334 UGFzc3dvcmQ6
CLIENT -> SERVER: xxx==
SERVER -> CLIENT: 235 2.0.0 OK
CLIENT -> SERVER: MAIL FROM:<someone@yahoo.com>
SERVER -> CLIENT: 250 OK , completed
CLIENT -> SERVER: RCPT TO:<someone_else@gmail.com>
SERVER -> CLIENT: 250 OK , completed
CLIENT -> SERVER: DATA
SERVER -> CLIENT: 354
CLIENT -> SERVER: Date: Sat, 20 Aug 2016 17:20:34 +0000
CLIENT -> SERVER: To: someone_else <someone_else@gmail.com>
CLIENT -> SERVER: From: someone <someone@yahoo.com>
CLIENT -> SERVER: Subject: Test Email
CLIENT -> SERVER: Message-ID: <ba0dc19bf4e4c77ddba8c25f2c8cf8fb@localhost>
CLIENT -> SERVER: X-Mailer: PHPMailer 5.2.15 (https://github.com/PHPMailer/PHPMailer)
CLIENT -> SERVER: MIME-Version: 1.0
CLIENT -> SERVER: Content-Type: text/html; charset=iso-8859-1
CLIENT -> SERVER:
CLIENT -> SERVER: Hi this is a test email so please ignore it
CLIENT -> SERVER:
CLIENT -> SERVER: .
SERVER -> CLIENT: 250 Data Dropped
CLIENT -> SERVER: QUIT
SERVER -> CLIENT:
SMTP ERROR: QUIT command failed:
Connection: closed
mail was sent
```
Though it is saying mail was sent but in reality there is no mail in the inbox. In addition to this sometimes mail was sent, particularly after following steps which are mentioned in the PHPMailer debug page. Also if I do not restart httpd service I do get error like _error smtp connect()_.
Thanks in advance

**Comment by juanmafx** [comment]
Do you check spam?

**Comment by sudarshansaha** [comment]
Hello Sir,
First of all thanks for your reply. Later I was able to figure out source of the problem. There was some problem with the data structure - I used some spaces in the Subject section which was causing the error. I am not an expert in this field, but when I googled it I found there is some issues with "space" character. Here is my code which is working fine apart from the fact, when I turn on my localhost I have to restart apache server everytime otherwise I would get this error

Connection: opening to smtp.gmail.com:587, timeout=300, options=array ( 'ssl' => array ( 'verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => false, ),)
SMTP ERROR: Failed to connect to server: php_network_getaddresses: getaddrinfo failed: Name or service not known (0)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

Code:

<?php
require 'PHPMailer-master/PHPMailerAutoload.php';

$mail = new PHPMailer;
$mail->SMTPDebug = 3;
$mail->Debugoutput = 'html'; 
$mail->IsHTML(true);
$mail->WordWrap = 50;                                       

$mail->isSMTP();
$mail->Mailer='smtp';
$mail->SMTPAutoTLS = false;
$mail->SMTPAuth = true;
$mail->SMTPOptions = array(
    'ssl' => array(
       'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => false
    )
);

// For GMail
$mail->Host = "tls://smtp.gmail.com:587";

// For GMail
$mail->Username = "someone@gmail.com";
$mail->Password = "someSecret";
$mail->From = "someone@gmail.com";

$from = "Someone Stupid";
$to = "Someone Else";

$mail->FromName = $from;

$mail->addAddress("someone.else@somedomain.someprotocol", "$to");

$mail->Subject = "Somesubject- Somematter";

// This is a HTML message
$mail->Body = "Hello, <br /><br />This is a system generated email, please do not reply to it.<br /><br />Thanks";

// This is a plain text message
$mail->AltBody = "Hello, \r\n\r\nThis is a system generated email, please do not reply to it.\r\n\r\nThanks";

if(!$mail->send()) {
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    //perform success actions
	echo 'mail was sent';
   exit();
}

$mail->SmtpClose();
?>

**Comment by Synchro** [comment]
It's right there in the message: `Name or service not known`. This means your DNS is not working. It's nothing to do with the script. This is covered in the troubleshooting guide linked from the error.
