### ISSUE TITLE
Error when trying to send the email

### ISSUE THREAD

**Issue by Daichisan** [PHPMailer/PHPMailer#811]
I'm getting the next error:

`Parse error: syntax error, unexpected '"<br>\n"' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ';' in /home/onixgami/public_html/alpha/includes/plugins/phpmailer/class.smtp.php on line 169`

I'm checking at that line, but I don't get it.

Any help would be good!

Thanks!

**Comment by Synchro** [comment]
Sounds like a corrupted file. Replace it with a fresh copy.

**Comment by Daichisan** [comment]
Hm...now I'm getting this error:

`[26-Aug-2016 02:27:08 CST6CDT] mail() on [/home/onixgami/public_html/alpha/includes/plugins/phpmailer/class.phpmailer.php:611]: To: "davidrok.roglic@gmail.com" <davidrok.roglic@gmail.com> -- Headers: Date: Fri, 26 Aug 2016 02:27:08 -0500 Return-Path: <root@localhost> From: Root User <root@localhost> Message-ID: <78df0a5494d69566e0b44eafff073a85@alpha.drrbox.com> X-Priority: 3 X-Mailer: PHPMailer 5.2.7 (https://github.com/PHPMailer/PHPMailer/) MIME-Version: 1.0 Content-Type: text/plain; charset=iso-8859-1 Content-Transfer-Encoding: 8bit`

**Comment by Synchro** [comment]
That's not an error, and you're using an ancient version of PHPMailer. Get the latest.

**Comment by Daichisan** [comment]
Hm...I've updated the PHPMailer, but still I can't get the mails to send.
Error log:
`mail() on [/home/onixgami/public_html/alpha/includes/plugins/phpmailer/class.phpmailer.php:689`

My code for sending
`class Mail {
	function mail() {
		global $db;
		global $cache;

		$mail_settings = $cache->get("mail_settings");

		if ($mail_settings == null) {
			$query = $db->query("SELECT * FROM mail_settings");

			while ($result = $db->fetch_array($query)) {
				$mail_settings[$result['field']] = $result['value'];
			}

			$cache->set("mail_settings", $mail_settings, 604800);
		}

		$this->mail_settings = $mail_settings;
		$this->mail = new PHPMailer();

		if ($this->mail_settings['email_type'] == "smtp") {
			$this->mail->IsSMTP();
			$this->mail->SMTPAuth = true;
			$this->mail->SMTPSecure = $this->mail_settings['smtp_ssl'];
			$this->mail->Host = $this->mail_settings['smtp_host'];
			$this->mail->Port = $this->mail_settings['smtp_port'];
			$this->mail->Username = $this->mail_settings['smtp_username'];
			$this->mail->Password = $this->mail_settings['smtp_password'];
		}

	}

	function setFrom($from_email = null, $name = null) {
		if (!empty($from_email)) {
			$this->from = $this->mail_settings['email_from_address'];
			$this->from_name = $this->mail_settings['email_from_name'];
		}
		else {
			$this->from = $from_email;

			if ($name == "") {
				$this->from_name = $this->from;
			}
			else {
				$this->from_name = $name;
			}
		}

		$this->mail->SetFrom($this->from, $this->from_name);
		$this->mail->AddReplyTo($this->from, $this->from_name);
	}

	function addTo($to_email, $to_name = null) {
		$this->to = $to_email;

		if ($to_name == "") {
			$this->to_name = $this->to;
		}
		else {
			$this->to_name = $to_name;
		}

		$this->mail->AddAddress($this->to, $this->to_name);
	}

	function setSubject($subject) {
		$this->mail->Subject = $subject;
	}

	function setBodyText($message) {
		$this->mail->ContentType = "text/plain";
		$this->mail->IsHTML(false);
		$this->mail->Body = $message;
	}

	function setBodyHtml($message) {
		$this->mail->AltBody = "To view the message, please use an HTML compatible email viewer!";
		$this->mail->MsgHTML(stripslashes($message));
	}

	function send() {
		if (!$this->mail->Send()) {
		}

	}
}

require ROOTPATH . "includes/classes/class_refcron.php";`

**Comment by Synchro** [comment]
It would help show the error response like the examples show. See what happens when you do this:

```php
function send() {
        if (!$this->mail->send()) {
                echo $this->mail->ErrorInfo;
        }
}
```

**Comment by Daichisan** [comment]
`PHP Fatal error:  Class 'SMTP' not found in /home/onixgami/public_html/alpha/includes/plugins/phpmailer/class.phpmailer.php on line 1466`

**Comment by Synchro** [comment]
It's very strange that your code is even running line 669 as it shouldn't be run if youre using SMTP. 

Anyway, the `Class SMTP not found` error is covered in the docs, and probably means you need to read the readme about which files you need and how to load PHPMailer - short version: use composer if you possibly can, otherwise upoad all the files, use PHPMailer's own autoloader.

**Comment by MGITPI** [comment]
Hi,
I am trying to send auto email from scheduled task created in plesk panel(12.5.30) PHP (5.6.31), email works when I run file directly but getting below error when I am trying to run through scheduled task.
[02-Jan-2018 03:49:30 UTC] PHP Parse error:  syntax error, unexpected '[' in Automation\PHPMailer\src\PHPMailer.php on line 288

**Comment by Synchro** [comment]
It’s possible for the CLI and web versions of PHP to be different. It sounds like the version of PHP used to run your cron job is older than 5.4.

**Comment by bharathjinka09** [comment]
( ! ) Parse error: syntax error, unexpected '[' in F:\wamp\www\phpmail\mailer\src\PHPMailer.php on line 288
--

**Comment by bharathjinka09** [comment]
Can anyone solve this error please

**Comment by Synchro** [comment]
@bharathjinka09 Don't hijack unrelated issues. You're trying to run PHPMailer on a version of PHP that's too old. Upgrade.
