### ISSUE TITLE
Fatal error: Class 'smtp' not found in C:\wamp\www\PHPMailer\class.phpmailer.php on line 1466

### ISSUE THREAD

**Issue by godwinshobowale** [PHPMailer/PHPMailer#813]
Please am getting an error when i followed the basic installation you stated out, 
This is my mailer.php file 

`<?php

require_once ('class.phpmailer.php');

define('GUSER', 'beyondservice.test@gmail.com');
define('GPWD', 'iamshoboy' );

    global $error;

    $mail = new PHPMailer(); //create an instant of PHPMailer
    $mail->IsSMTP(); // enable SMTP
    $mail->SMTPDebug = 0;  // debugging: 1 = errors and messages, 2 = messages only
    $mail->SMTPAuth = true;  // authentication enabled
    $mail->SMTPSecure = 'ssl'; // secure transfer enabled REQUIRED for GMail
    $mail->Host = 'smtp.gmail.com';
    $mail->Port = 465;
    $mail->Username = GUSER;
    $mail->Password = GPWD;
    $mail->SetFrom("oluwadamilareshobowale@gmail.com", "Damilare");
    $mail->Subject = "Hello World";
    $mail->Body = "This is my Mail";
    $mail->AddAddress(GUSER);
    $mail->send();
    echo ("PHP Mailer");
    if(!$mail->Send()) {
        $error = 'Mail error: '.$mail->ErrorInfo;
        return false;
    } else {
        echo ("PHP Mailer");
        $error = 'Message sent!';
        $echo ($error);
        return true;
    }
`
Please I need your help. Thanks

**Comment by Synchro** [comment]
You didn't follow the basic installation instructions, and you're using some old PHPMailer example, and you didn't search for this bug (which was addressed a long time ago) before posting. Get the latest version (at least you're on the right site), read the Readme, base your code on the examples provided.

**Comment by godwinshobowale** [comment]
Thank you, it just worked now.

**Comment by mrojas18** [comment]
i have the last version downloaded from github in the github say : 5.5.23 but inside the file its says: version 5.2.23, 

and i have the same problem, 

the question here is: where is the newest version? on github master branch or another place?

**Comment by Synchro** [comment]
@mrojas18 That 5.5.23 was a typo in the release notes; 5.2.23 is the latest release. 6.0 will hopefully be released soon.
