### ISSUE TITLE
1and1 hosting solution

### ISSUE THREAD

**Issue by Chaberrr** [PHPMailer/PHPMailer#816]
I had some SMTP auth error problem at **1and1 hosting**.

Finally I've found the solution here:
https://webolio.wordpress.com/2008/03/02/phpmailer-and-smtp-on-1and1-shared-hosting/

"After googling for a solution and trying different smtp servers, accounts and smtp ports, I decided to switch to sendmail and it worked like a charm! All I needed to do was replace $mail->isSmtp() with:
**$mail->isSendMail()"**

**Comment by Synchro** [comment]
This isn't a solution to making SMTP work. It's "making it work" by not using it at all, and my simply be moving the problem somewhere that's less visible. It's likely that 1&1 blocks outbound SMTP and requires you use their servers (like GoDaddy does), and as such it will be covered in the troubleshooting guide linked form the readme and all PHPMailer error messages. That thread is 8 years old and contains some very bad advice, so I wouldn't believe too much you read in it.

**Comment by thierry-masson** [comment]
I confirm that PHPMailer does not work with SMTP on 1and1, even if I use an email account from 1and1. It works with PHPMailer configured to use the PHP mail() function. So, it is unlikely that they block outbound SMTP since I test with their own smtp server! I will send an email to 1and1 to ask them the reason…
Thierry

**Comment by Synchro** [comment]
As I said, they block outbound SMTP to everywhere but their own servers. When you send via `mail()`, it still uses SMTP from your local mail server, which is probably configured to relay through their servers, achieving the same result.

**Comment by mattstein** [comment]
I appreciate your responses in these issue threads, @Synchro, as your guess pointed me in the right direction. Per [this source](http://docs.mailpoet.com/article/49-lists-of-hosts-and-their-sending-limits) and my experience thus far, 1&1 doesn't allow any third party SMTP connections from its servers. I've spent more than an hour on the phone with three agents, and nobody seems to understand the context of the question let alone answer or confirm. I mention this for posterity and the next unfortunate developer that gets stuck dealing with 1&1.

**Comment by whikloj** [comment]
I am able to send mail using PHPMailer (commit 48261992765204ea5e3772b003075ad053937155) on a 1and1.com site.

I used.
```
$mail = new PHPMailer();
//Tell PHPMailer to use SMTP
$mail->isSMTP();
//Enable SMTP debugging
// 0 = off (for production use)
// 1 = client messages
// 2 = client and server messages
$mail->SMTPDebug = 0;

//Set the hostname of the mail server
$mail->Host = "smtp.1and1.com";
//Set the SMTP port number - likely to be 25, 465 or 587
$mail->Port = 25;
//Whether to use SMTP authentication
$mail->SMTPAuth = true;
$mail->SMTPSecure = 'tls';
//Username to use for SMTP authentication
$mail->Username = "<username>";
//Password to use for SMTP authentication
$mail->Password = "<password>";
```

Not sure if that helps anyone, hopefully it does. The whole using TLS with port 25 was kind of confusing.

**Comment by whikloj** [comment]
@mattstein Ahhhh, so if you are trying to send mail via a different email provider (for instance Google) then you can't connect. I understand.

**Comment by bguinen** [comment]
@whikloj what 1&1 credentials are you using for your Username/PW? the same used to access their control panel?

**Comment by whikloj** [comment]
@bguinen I'm using the email address (<user>@<domain>) as the user, and yes the control panel PW. I haven't tried the account ID or anything else.

**Comment by inboudayo** [comment]
I am using smtp.1and1.com and it still doesn't work.

> SMTP ERROR: Failed to connect to server: Connection timed out (110) 2017-06-01 05:45:40	SMTP connect() failed

Works fine on localhost.

**Comment by bguinen** [comment]
I also ended up creating an email with 1&1 and using that for the PHP script, then forwarded to the preferred gmail account.

**Comment by cafiah** [comment]
Thanks a lot for this thread, I was fighting with 1and1 smtp mailing for 1 week... and finally this is all about smtp.1and1.com on port 25 rather than using auth.smtp.1and1.fr on port 465 !

**Comment by cafiah** [comment]
btw on a related topic do you also have your mails ending up in spam at least on gmail when using 1and1 smtp?

**Comment by rtrdigital** [comment]
The problem with 1and1 is that it doesn't support the fined $mailer as "smtp." Every program installed on 1and1 has to be reconfigured to use the "sendmail" option in whatever php file manages the outgoing mail.
