### ISSUE TITLE
Fatal error: Call to undefined method SMTP::connected()

### ISSUE THREAD

**Issue by sirfragalot** [PHPMailer/PHPMailer#817]
I followed the minimal installation instructions at: https://github.com/PHPMailer/PHPMailer/blob/5.2-stable/README.md

"While installing the entire package manually or with composer is simple, convenient and reliable, you may want to include only vital files in your project. At the very least you will need class.phpmailer.php. If you're using SMTP, you'll need class.smtp.php, and if you're using POP-before SMTP, you'll need class.pop3.php. For all of these, we recommend you use the autoloader too as otherwise you will either have to require all classes manually or use some other autoloader. You can skip the language folder if you're not showing errors to users and can make do with English-only errors. You may need the additional classes in the extras folder if you are using those features, including NTLM authentication and ics generation. If you're using Google XOAUTH2 you will need class.phpmaileroauth.php and class.oauth.php classes too, as well as the composer dependencies."

I placed:
class.phpmailer.php
class.smtp.php
PHPMailerAutoload.php
(and, of course, the License)

in my project folder then called the autoloader as:
require_once 'PHPMailerAutoload.php';
followed by
$this->mail = new PHPMailer();

I've configured things to use smtp but get the error:

Fatal error: Call to undefined method SMTP::connected() in /Applications/XAMPP/xamppfiles/htdocs/wikindx5/trunk/core/smtp/class.phpmailer.php on line 1529

Clearly, the script reaches the phpmailer class but cannot find smtp.php.

Any ideas?

Mark

**Comment by Synchro** [comment]
I'd guess you have another class called `SMTP` somewhere in your system, so it's finding an SMTP class, but it's the wrong one. This is why PHPMailer 6 introduces a namespace...

**Comment by sirfragalot** [comment]
You're absolutely right. Many thanks for your help and the quick response.

Mark
