### ISSUE TITLE
reCaptcha server side

### ISSUE THREAD

**Issue by paica** [PHPMailer/PHPMailer#819]
Hi, currently I have a site with a recaptcha of google on my form, but I can send mails without ckeck the recaptcha, do you know how can I Verify the user's response? thank you!

**Comment by Synchro** [comment]
Sorry, I have no idea about using recaptcha, and PHPMailer doesn't depend on it at all, so you'll need to ask them. The basic idea will be to validate the recaptcha submission before you go ahead and send mail.

**Comment by paica** [comment]
Thank you Marcus!
 
De: Marcus Bointon [mailto:notifications@github.com] 
Enviado el: lunes, 05 de septiembre de 2016 03:33 p.m.
Para: PHPMailer/PHPMailer
CC: paica; Author
Asunto: Re: [PHPMailer/PHPMailer] reCaptcha server side (#819)
 
Sorry, I have no idea about using recaptcha, and PHPMailer doesn't depend on it at all, so you'll need to ask them. The basic idea will be to validate the recaptcha submission before you go ahead and send mail.
