### ISSUE TITLE
SMTP mail

### ISSUE THREAD

**Issue by vbijan** [PHPMailer/PHPMailer#820]
using SMTP for sending mail,its sending mail from
$mail->username("abc@...") rather than
$mail->setFrom("abc2@....")
what should i do?

**Comment by sc0Vu** [comment]
https://github.com/PHPMailer/PHPMailer/blob/master/examples/smtp.phps

**Comment by Synchro** [comment]
Read the troubleshooting guide in the wiki. This will be your ISP. Gmail does this; on there you cna't use arbitrary From names, but you can create preset addresses in gmail settings.
