### ISSUE TITLE
Embedded image in email

### ISSUE THREAD

**Issue by lozjackson** [PHPMailer/PHPMailer#823]
This is a question about best practise with regards to embedding images in emails.

If it helps to know the context.. this is for email signatures (company logo) and so may get repeated in every reply when the conversation gets busy.

So to the point.. (through my testing so far) I can send an email, with embedded images with 2 different methods .  They both work but I'm unsure which is the best way.. most reliable and most efficient.

The first method is embedding the base64 encoded image directly in the `src` attribute of the `img` tag in the html email body.  This works, but is there any hidden gotchas that makes this approach no good?

The second method uses `$mail->AddStringEmbeddedImage()` method to attach the image and refers to the `cid` in the `src` attribute of the `img` tag.  This also works.

Now.. providing all else equal, I personally prefer the first method.. it is easier to implement, and looks to me to be more robust.

With the second method, The email appears to have an attachment when it is only the company logo.. I would prefer for it not to appear as an attachment  (The first method doesn't use attachments as it is embedding the data directly in the HTML).

Is there any reason not to go with the first approach?

**Comment by Synchro** [comment]
TBH, I wouldn't do either. Footers are usually excessive, and logos are really unnecessary, especially since, as you say, they multiply up in threads. If you have to put one in, do it as a linked image so as not to waste mobile users' bandwidth - if it's included 100 times, it will only cause a single download, and will consume no bandwidth at all if the meassage is not read. data URIs don't work in quite a few clients - have a look on litmus or compatibility, they probably have an article about it.

**Comment by lozjackson** [comment]
Thanks for the response,

so.. in short, the second method is better... for reasons of reliability and efficiency, correct?

Thats pretty much what I assumed would be the case.. but I wasn't sure.. thanks

**Comment by Synchro** [comment]
Yes, regular referenced attachments have been around a lot longer than data URIs, and support for them is much better. But 100 threaded responses may still include 100 copies...

**Comment by lozjackson** [comment]
I'm building an application that integrates email and allows people to add thier own signatures (much like a regular email client)..

I want to allow people to add images to the signatures (and emails).. what is the normal/standard practise?  is it the tried and tested attachment method (always?)?.. or is it down to preference?.. i mean, how much of a difference does it really make.

**Comment by Synchro** [comment]
I don't have a problem with people dong it for personal stuff, but if you're imposing it across a company with hundreds of users, there will be a lot of waste going on. IME, it's hard enough to get companies to even get URLs in signatures correct - I know a massive London law firm that's had a `file://` URL in their signature for 15 years! I can think of only one of my clients that uses a logo at all, and I often see it appearing in random locations as threading tends to trash layouts. I'd say best practice is not to do it at all. If you let someone put any kind of image in, you can pretty much guarantee they will stick in a high-resolution 5Mb image straight from their phone, and then call support when it sends slowly. There's plenty of interesting stuff you can do with CSS that will be far lighter and more robust.

The only way to be sure of which works best is to try it - use a testing service to try it on lots of devices, see what effect multiple replies have too.

**Comment by lozjackson** [comment]
Thanks.. Its a feature that I need to support in my application... it just a question of how best to handle it and what is standard practise.  And I wanted to see if there was anything inherently wrong the embedded data uri approach.

I think I might make it a preference in the application's config settings.. as long as either approach is valid then I can leave that decision to be decided at run time.

Thanks again for your help.
