### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by kiruthikanaethra** [PHPMailer/PHPMailer#826]
Hi
i have used phpmailer for sending mails.Last week i have uploaded ssl certificate for my site.After that i have receiced this following error when i trying to send emails.

```
SERVER ->  ESMTP Exim 4.87 #1 Wed, 14 Sep 2016 09:58:45 +0000 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail.
CLIENT -> SERVER: EHLO SERVER -> CLIENT: 250-server.com Hello server.mcmservice.com 50-SIZE 52428800250-8BITMIME250-PIPELINING250-AUTH PLAIN LOGIN250-STARTTLS250 HELP
CLIENT -> SERVER: STARTTLS
SERVER -> CLIENT: 220 TLS go ahead
CLIENT -> SERVER: EHLO m
SERVER -> CLIENT: 250-[162.144.141.239]250-SIZE 52428800250-8BITMIME250-PIPELINING250-AUTH PLAIN LOGIN250 HELP
CLIENT -> SERVER: AUTH LOGIN

SERVER -> CLIENT: 535 Incorrect authentication data
SMTP ERROR: Password command failed: 535 Incorrect authentication data
SMTP Error: Could not authenticate.
CLIENT -> SERVER: QUIT
SERVER -> CLIENT: 221  closing connection
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
```
Can you please help me to solve this issue.

Regardss
Kiruthika

**Comment by ooxi** [comment]
P.S.: Are you aware that you are posting your credentials (ramsatt@gmail.com / 42127600Ram) on a public forum?

**Comment by Synchro** [comment]
As @ooxi said, be careful what you post.

It looks like your ID was a gmail address, but you're not connecting to a gmail server. So either your `Host` setting is wrong, or you are being redirected by your ISP. Either way, this is all covered in [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting) the error message pointed you at, which is why it's there.

**Comment by kiruthikanaethra** [comment]
ok thanks to advising me. Here after i will take care of it.

But im using $mail->Host = smtp.gmail.com;

**Comment by Synchro** [comment]
Well exactly - as the guide says, check that the server you are connecting to is the one you expect - you are asking for `smtp.gmail.com` but you can see it's not connecting to a gmail server, which suggests it's being intercepted and redirected to your ISP's mail server, on which your credentials will obviously not work. This is why you should never turn off certificate verification.

Note that your own change of certificate has nothing to do wtih this.

**Comment by kiruthikanaethra** [comment]
So its not a code problem....How to fix this? any suggestion please

**Comment by Synchro** [comment]
Nope, not a code issue, and as such not something we can fix for you. Talk to your ISP, read their docs.

**Comment by kiruthikanaethra** [comment]
Ok.Thanks for your support.I will ask my hosting provider regarding this
issue

**Comment by jgmuchiri** [comment]
Has the same issue with PHPMailer and used the following instructions to fix it [https://amdtllc.com/blog/stmp-phpmailer-error-220-we-do-not-authorize-the-use-of-this-system-to-transport-unsolicited-220-and-or-bulk-e-mail/](url)

**Comment by Synchro** [comment]
Ick. Is anyone really using POP-before-SMTP auth any more? It's been obsolete for decades. It's irrelevant anyway, since the error here is caused by an entirely different problem.

**Comment by jgmuchiri** [comment]
@Synchro your point is valid. Just pointing @kiruthikanaethra in the right direction for that specific question.

**Comment by Synchro** [comment]
Except it's not the right direction - his ISP is redirecting SMTP connections to another server, and that will not be solved by using POP before SMTP, which gmail doesn't support anyway. It might be a solution, but not to _this_ problem.
