### ISSUE TITLE
<a> href gets ignored

### ISSUE THREAD

**Issue by BlackFayah** [PHPMailer/PHPMailer#827]
Whenever I put a `<a>` tag in the template, the href and target values get replaced by `href="./#NOP" onclick="return false"`.

This is my code:
```
$message = file_get_contents('register.html');
$message = str_replace('%url%', 'google.com', $message);
$mail->msgHTML($message);
```

Inside template:
    `<a href="%url%" target="_blank">Confirm</a>`

var_dump($message) proves that the url is being replaced correctly, so it has to do something with PHPMailer.

**Comment by ooxi** [comment]
This has nothing to do with PHPMailer but your mail provider.

**Comment by BlackFayah** [comment]
Well then, let me ask you this before closing this issue: I am running Postfix with Dovecot. Do you have any idea where I should look?

**Comment by Synchro** [comment]
PHPMailer does make some content changes in `msgHTML`, but it should only affect images, and you can always eliminate that simply by setting `Body` and `AltBody` yourself temporarily. Be aware that 'www.google.com' is not a valid URL, so it's quite likely to be filtered by something else.

You need to establish exactly where and when this change is happening. Set `SMTPDebug = 2` and you'll see the SMTP conversation, in which you should see your content as submitted (after which PHPMailer's involvement ends). If it's not in there you need to look at your mail server's outbound queue files to see if it's changed in there, then check the inbound side.

**Comment by BlackFayah** [comment]
Oh wow I had a little typo in my code (didn't post that part) and that caused it... Thanks to your reply I took a closer look and found it. Cheers!
