### ISSUE TITLE
Multiple addStringAttchment

### ISSUE THREAD

**Issue by vanessasoutoc** [PHPMailer/PHPMailer#828]
Hi, 
I need several attachments to be sent in the mail ... the email is sent more attachments do not open ... I will get more regular attachments do not open.

Can someone help me?

**Comment by vanessasoutoc** [comment]
Bug solved! You need to change the file class.phpmailer.php, on the functions 'addStringAttachment and addAttachment:
ORIGINAL CODE:
$this->attachment[] = array(
            0 => $string,
            1 => $filename,
            2 => basename($filename),
            3 => $encoding,
            4 => $type,
            5 => true, // isStringAttachment
            6 => $disposition,
            7 => 0
        );


PATCHED CODE:
 $this->attachment[] = array(
            0 => $string,
            1 => $filename,
            2 => basename($filename),
            3 => $encoding,
            4 => $type,
            5 => true, // isStringAttachment
            6 => $disposition,
            7 => count($this->attachment)
        );

**Comment by Synchro** [comment]
Element 7 of that array is the `cid` of each attachment; normal or string attachments don't need `cid`s, so this shouldn't make any difference - that property is only used in embedded attachments. Can you please post the rest of your code to show how your'e using this?

**Comment by vanessasoutoc** [comment]
I have Array of the image in code base64... So i do a for and create $mail->addStringAttchament 
each time it enters the for:

for($i = 0; $i < count($images); $i++){
$mail->addStringAttachment(base64_decode($images[$i]), "test".$i.".jpeg", "base64", "image/jpeg");
}

The modification in file class.phpmailer.php is required for send many attachments, otherwise only send an attachment.

Please, insert new modification in the next version!

understood?

**Comment by Synchro** [comment]
I can't reproduce this - with your code it works fine without setting the cid. Can you show an example of a generated message (edited to just show structure)?

**Comment by vanessasoutoc** [comment]
I do not know how to do this.

**Comment by Synchro** [comment]
Send yourself an email that has this problem, view source, copy and paste it in here, but edit out the bulk of the encoded images as they will be very large, so that I can see the structure of the message.
