### ISSUE TITLE
use of function SmtpSend

### ISSUE THREAD

**Issue by maramba7** [PHPMailer/PHPMailer#833]

**Comment by ooxi** [comment]
Could you be more specific?

**Comment by Synchro** [comment]
You don't need to use it. Call `isSMTP()`, then `send()` and it's all done for you, just like in the examples provided.

**Comment by maramba7** [comment]
Thank you, i think that it can be used to pass the header and the message directly

**Comment by Synchro** [comment]
Yes, but you must call everything else in order to set up the context that it can work in. The docs for it are [here](http://phpmailer.github.io/PHPMailer/classes/PHPMailer.html#method_smtpSend).
