### ISSUE TITLE
PHPMailer does not send to hotmail dresses

### ISSUE THREAD

**Issue by ChrisBrokamp** [PHPMailer/PHPMailer#837]
Is this problem caused by the PHPMailer or by my provider?
Thanks for your help,

Chris

Von: MAILER-DAEMON@XXX (Mail Delivery System)
Betreff: Undelivered Mail Returned to Sender
Datum: 27. September 2016 um 13:48:46 MESZ

This is the mail system at host XXX.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                  The mail system

<xxx@hotmail.com>: host mx4.hotmail.com[65.55.92.168] said: 550 SC-001
   (SNT004-MC3F21) Unfortunately, messages from 178.33.39.27 weren't sent.
   Please contact your Internet service provider since part of their network
   is on our block list. You can also refer your provider to
   http://mail.live.com/mail/troubleshooting.aspx#errors. (in reply to MAIL
   FROM command)

**Comment by Synchro** [comment]
As it says "part of their network on our block list", i.e. it's nothing to do with the message itself, just where it's sent from, your provider.
