### ISSUE TITLE
phpmailer DKIM problem

### ISSUE THREAD

**Issue by qiuwikeshu** [PHPMailer/PHPMailer#838]
when I sending add DKIM signal，the apache http server will be stopped .when I send mail without DKIM signal,it will returned to normal.   

the dkim code as follows：

$mail->DKIM_domain = '114.lovekenv.com';
$mail->DKIM_private = 'dkim/.htkeyprivate';
$mail->DKIM_selector = 'kenv';

 the apache's error.log display as follows：

[Thu Sep 29 10:39:34.631448 2016] [mpm_winnt:notice] [pid 3604:tid 232] AH00428: Parent: child process exited with status 3221225477 -- Restarting.
[Thu Sep 29 10:39:35.084585 2016] [mpm_winnt:notice] [pid 3604:tid 232] AH00455: Apache/2.4.3 (Win32) OpenSSL/1.0.1c PHP/5.4.7 configured -- resuming normal operations
[Thu Sep 29 10:39:35.084585 2016] [mpm_winnt:notice] [pid 3604:tid 232] AH00456: Server built: Aug 18 2012 12:41:37
[Thu Sep 29 10:39:35.084585 2016] [core:notice] [pid 3604:tid 232] AH00094: Command line: 'c:\xampp\apache\bin\httpd.exe -d C:/xampp/apache'
[Thu Sep 29 10:39:35.084585 2016] [mpm_winnt:notice] [pid 3604:tid 232] AH00418: Parent: Created child process 3392
[Thu Sep 29 10:39:36.022109 2016] [mpm_winnt:notice] [pid 3392:tid 248] AH00354: Child: Starting 150 worker threads.
[Thu Sep 29 10:39:37.475271 2016] [mpm_winnt:notice] [pid 3604:tid 232] AH00428: Parent: child process exited with status 3221225477 -- Restarting.
[Thu Sep 29 10:39:37.975284 2016] [mpm_winnt:notice] [pid 3604:tid 232] AH00455: Apache/2.4.3 (Win32) OpenSSL/1.0.1c PHP/5.4.7 configured -- resuming normal operations
[Thu Sep 29 10:39:37.975284 2016] [mpm_winnt:notice] [pid 3604:tid 232] AH00456: Server built: Aug 18 2012 12:41:37
[Thu Sep 29 10:39:37.975284 2016] [core:notice] [pid 3604:tid 232] AH00094: Command line: 'c:\xampp\apache\bin\httpd.exe -d C:/xampp/apache'
[Thu Sep 29 10:39:37.975284 2016] [mpm_winnt:notice] [pid 3604:tid 232] AH00418: Parent: Created child process 812
[Thu Sep 29 10:39:38.819056 2016] [mpm_winnt:notice] [pid 812:tid 248] AH00354: Child: Starting 150 worker threads.

somebody use the phpmailer with dkim successful? who can tell me?

**Comment by ooxi** [comment]
This sounds like OpenSSL is crashing, slaying Apache in the process. PHPMailer does have support for DKIM, relying on OpenSSL.

Try using the OpenSSL functions in PHP without PHPMailer, the error should be reproducible. Most likely your setup is corrupted.

**Comment by Synchro** [comment]
It probably dosn't help that you're running old versions of Apache, PHP and OpenSSL. Try updating.
