### ISSUE TITLE
UserName Command Failer

### ISSUE THREAD

**Issue by AmrataRamchandani** [PHPMailer/PHPMailer#841]
Following Error is being shown

```
SERVER -> CLIENT: 220 smtp-auth.iitb.ac.in ESMTP Postfix (2.10.1)
CLIENT -> SERVER: EHLO localhost
SERVER -> CLIENT: 250-smtp-auth.iitb.ac.in250-PIPELINING250-SIZE 28000000250-VRFY250-ETRN250-STARTTLS250-ENHANCEDSTATUSCODES250-8BITMIME250 DSN
CLIENT -> SERVER: STARTTLS
SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
CLIENT -> SERVER: EHLO localhost
SERVER -> CLIENT: 250-smtp-auth.iitb.ac.in250-PIPELINING250-SIZE 28000000250-VRFY250-ETRN250-AUTH GSS-SPNEGO GSSAPI DIGEST-MD5 CRAM-MD5 LOGIN PLAIN250-AUTH=GSS-SPNEGO GSSAPI DIGEST-MD5 CRAM-MD5 LOGIN PLAIN250-ENHANCEDSTATUSCODES250-8BITMIME250 DSN
CLIENT -> SERVER: AUTH CRAM-MD5
SERVER -> CLIENT: 334 PDU1OTQ2MjMxNS4xNTYxNjk3NEBzbXRwLWF1dGguaWl0Yi5hYy5pbj4=
CLIENT -> SERVER: YW1yYXRhQGlpdGIuYWMuaW4gZWYyYzM5ZjhlNGQ1YWE1YjM0Njk2YWI1MmUyZTk4MWQ=
SERVER -> CLIENT: 535 5.7.8 Error: authentication failed: authentication failure
SMTP ERROR: Username command failed: 535 5.7.8 Error: authentication failed: authentication failure
SMTP Error: Could not authenticate.
CLIENT -> SERVER: QUIT
SERVER -> CLIENT: 221 2.0.0 Bye
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
Message could not be sent.Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
```

```php
<?php
require 'PHPMailer-master/PHPMailerAutoload.php';

$mail = new PHPMailer;
$mail->SMTPDebug = 2;
$mail->Debugoutput = 'html';                             // Enable verbose debug output

$mail->isSMTP();                                      // Set mailer to use SMTP
$mail->Host = 'smtp-auth.iitb.ac.in';  // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'amrata@iitb.ac.in';                 // SMTP username
$mail->Password = 'pwd';                           // SMTP password
$mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 25;                                    // TCP port to connect to

$mail->setFrom('amrata@iitb.ac.in');
$mail->addAddress('amrata@iitb.ac.in');     // Add a recipient
            
$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'Here is the subject';
$mail->Body    = 'This is the HTML message body <b>in bold!</b>';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

if(!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message has been sent';
}
```

Username is correct. I dont know why it is showing this error. It is being run on localhost xampp

**Comment by Synchro** [comment]
And if you try setting `$mail->AuthType` to `LOGIN` or `PLAIN`?

**Comment by AmrataRamchandani** [comment]
I am not setting $mail->AuthType parameter
Is it required ? If yes then which value should i choose for it ?

**Comment by Synchro** [comment]
I gave examples in my last post! Please read what I said.

**Comment by requillo** [comment]
Hi Synchro,
been having the same problem check error

2016-10-03 16:25:14	Connection: opening to mail.rudisa.net:26, timeout=300, options=array ( 'ssl' => array ( 'verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true, ), ) 
2016-10-03 16:25:15	Connection: opened 
2016-10-03 16:25:15	SERVER -> CLIENT: 220 rudisa.net ESMTP Postfix 
2016-10-03 16:25:15	CLIENT -> SERVER: EHLO localhost 
2016-10-03 16:25:15	SERVER -> CLIENT: 250-rudisa.net 250-PIPELINING 250-SIZE 102400000 250-ETRN 250-STARTTLS 250-AUTH CRAM-MD5 PLAIN LOGIN 250-ENHANCEDSTATUSCODES 250-8BITMIME 250 DSN 
2016-10-03 16:25:15	CLIENT -> SERVER: STARTTLS 
2016-10-03 16:25:15	SERVER -> CLIENT: 220 2.0.0 Ready to start TLS 
2016-10-03 16:25:16	CLIENT -> SERVER: EHLO localhost 
2016-10-03 16:25:16	SERVER -> CLIENT: 250-rudisa.net 250-PIPELINING 250-SIZE 102400000 250-ETRN 250-AUTH CRAM-MD5 PLAIN LOGIN 250-ENHANCEDSTATUSCODES 250-8BITMIME 250 DSN 
2016-10-03 16:25:16	CLIENT -> SERVER: AUTH CRAM-MD5 
2016-10-03 16:25:16	SERVER -> CLIENT: 334 PDM5NzM4MDA1ODguMTU4OTQyMTFAcnVkaXNhLm5ldD4= 
2016-10-03 16:25:16	CLIENT -> SERVER: bm9yZXBseUByZXF1aWxsby5jb20gYjgxODE4Zjk5ZTI2MTY1ZTcxMjU5OTYwZjczOTcwMDA= 
2016-10-03 16:25:16	SERVER -> CLIENT: 535 5.7.8 Error: authentication failed: One time use of a plaintext password will enable requested mechanism for user 
2016-10-03 16:25:16	SMTP ERROR: Username command failed: 535 5.7.8 Error: authentication failed: One time use of a plaintext password will enable requested mechanism for user 
2016-10-03 16:25:16	SMTP Error: Could not authenticate. 
2016-10-03 16:25:16	CLIENT -> SERVER: QUIT 
2016-10-03 16:25:16 	SERVER -> CLIENT: 221 2.0.0 Bye 
2016-10-03 16:25:16	Connection: closed 2016-10-03 16:25:16	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by requillo** [comment]
Setting are

$mailer = new PHPMailer();

$mailer->SMTPOptions = array(
    'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )
);

//SMTP Configuration
$mailer->isSMTP();
$mailer->SMTPAuth   = true; //We need to authenticate
$mailer->Host       = $smtp['host'];
$mailer->Mailer = "smtp";
//$mailer->AuthType =  "login";
// $mailer->Host = gethostbyname('tls://mail.rudisa.net');
$mailer->Port       = $smtp['port'];
$mailer->SMTPDebug = 3;
$mailer->Username   = $smtp['username'];
$mailer->Password   = $smtp['password'];
$mailer->SMTPSecure = $smtp['secure'];


//Now, send mail :
//From - To :
$mailer->From       = $crendentials['email'];
$mailer->FromName   = $em_name; //Optional
$mailer->addAddress($to);  // Add a recipient

//Subject - Body :
$mailer->Subject        = $subject;
$mailer->Body           = $html;
$mailer->isHTML(true); //Mail body contains HTML tags

//Check if mail is sent :
if(!$mailer->send()) {
	$data['success'] = 'Sent Failed';
	$data['message']= 'Problem sending mail. '. $mailer->ErrorInfo;
	
    echo json_encode($data);
} else {
	$cmodel->update_client_single_data($data['id'],'sent', 2);
    echo json_encode($data);	
}

**Comment by requillo** [comment]
Could you check if I'm doing something wrong

**Comment by requillo** [comment]
Mail username and password are correct

**Comment by Synchro** [comment]
@requillo How about you do what it says:

> 2016-10-03 16:25:16 SMTP ERROR: Username command failed: 535 5.7.8 Error: authentication failed: **One time use of a plaintext password will enable requested mechanism for user**

You're *not* having the same problem as @AmrataRamchandani, so please don't hijack his issue.

**Comment by requillo** [comment]
My biggest apologies good sir @Synchro and also to @AmrataRamchandani, wasn't my intentions to hijack any issue

Can i make a new issue regarding my problem good sir @Synchro

**Comment by AmrataRamchandani** [comment]
Setting., $mail->AuthType = 'LOGIN';  worked like charm !
Cheers !

**Comment by bs-thomas** [comment]
Setting., $mail->AuthType = 'LOGIN'; worked like charm !
Cheers !
