### ISSUE TITLE
PHP 7.1 and mcrypt

### ISSUE THREAD

**Issue by standus** [PHPMailer/PHPMailer#846]
Please prepare library for deprecated mcrypt in PHP 7.1
see https://wiki.php.net/rfc/mcrypt-viking-funeral

**Comment by Synchro** [comment]
Thanks for the heads-up. The only mention of mcrypt in PHPMailer is in the NTLM authentication class, imported from PHPClasses. This class doesn't actually work, and has been dropped entirely from PHPMailer 6.0.
