### ISSUE TITLE
PHP 7 changes

### ISSUE THREAD

**Issue by csvehla** [PHPMailer/PHPMailer#847]
While upgrading my project to PHP 7 I noticed that PHPMailer still makes calls to set_magic_quotes_runtime(), along with its alias magic_quotes_runtime(). These functions have both been removed in PHP 7.

**Comment by Synchro** [comment]
No. It contains those functions, but they are wrapped in version checks, and have been removed in the fothcoming 6.0. Read the code. PHPMailer has been PHP 7 compatible for a couple of years.
