### ISSUE TITLE
Could not connect to SMTP host on STARTTLS

### ISSUE THREAD

**Issue by rkaartikeyan** [PHPMailer/PHPMailer#848]
Please Check the Debug Log. 

```
	require_once('../vendor/phpmailer/phpmailer/PHPMailerAutoload.php');
	require_once('../vendor/autoload.php');
	$mail = new PHPMailerOAuth;
	$mail->isSMTP();
	$mail->SMTPDebug = 4;
	
	$mail->Debugoutput = 'html';
	
	$mail->Host = 'smtp.gmail.com';
	$mail->Port = 587;
	$mail->SMTPSecure = 'tls';
	
	$mail->SMTPAuth = true;
	
	$mail->Username = "rkaartikeyan@gmail.com";
	$mail->Password = "PassWord";

	$mail->setFrom('rkaartikeyan@gmail.com', 'Karthikeyan Raju');
	$mail->addAddress('santhosh@santhoshdomain.com', 'Company Name);
	
	$mail->Subject = 'Welcome to Company Name - INDIA';
	
	$mail->msgHTML('This is <b>Test Email</b>');
	
	$mail->AltBody = 'This is Test Email';
	
	//send the message, check for errors
	if (!$mail->send()) {
		echo "Mailer Error: " . $mail->ErrorInfo;
	} else {
		echo "Message sent!";
	}

```

Note: in my rkaartikeyan@gmail.com i have Set **Allow less secure apps: ON**

Here is the Debug, This is VPS Server with CentOS 6 and WHM cPanel. I have root Access for Server & WHM cPanel. Please help me to fix this Issue. 

The Red Blurred are my Server's hostname(**vps12345677.dom.tdl**). The Green Blurred are my rDNS(**sub.domain.tdl**). The Blue Blurred are my **Server's IP Address**. Here is my Code.

<img src="http://www.hitronbsc.com/images/shot-20161008-2837-lp7ko6.jpeg" />

**Comment by Synchro** [comment]
Exactly this scenario is described in the troubleshooting docs the error links to, which is why it links to it. You have a TLS problem; figure out what it is and fix it.

**Comment by rkaartikeyan** [comment]
Its Because Restriction in WHM Panel, that **SMTP Restriction On.** this prevent Remote SMTP Access. I Disable the **SMTP Restriction** now its working :)
