### ISSUE TITLE
Sending email with phpmailer from an SMTP error

### ISSUE THREAD

**Issue by muradsofiyev** [PHPMailer/PHPMailer#851]
SERVER -> CLIENT: 220 smtp.blabla.com ESMTP on 
CLIENT -> SERVER: EHLO blabla.com
SERVER -> CLIENT: 250-smtp.blabla.com250-PIPELINING250-SIZE 62914560250-VRFY250-ETRN250-STARTTLS250-ENHANCEDSTATUSCODES250-8BITMIME250-DSN250 SMTPUTF8
CLIENT -> SERVER: STARTTLS
SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
SMTP Error: Could not connect to SMTP host.

**Comment by Synchro** [comment]
https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
