### ISSUE TITLE
SMTP server ready, fail to connect to host  

### ISSUE THREAD

**Issue by muradsofiyev** [PHPMailer/PHPMailer#852]
``` php
<?php
date_default_timezone_set('Etc/UTC');
require 'phpmailer/PHPMailerAutoload.php';
$mail = new PHPMailer;

$mail->IsSMTP();
$mail->SMTPDebug = 2;
$mail->Debugoutput = 'html';
$mail->SMTPAutoTLS = false;
$mail->Host = 'smtp.blabla.com';
$mail->Port = 587;
$mail->SMTPSecure = 'false';
$mail->SMTPOptions = array (
    'ssl' => array(
        'verify_peer'  => true,
        'verify_depth' => 3,
        'allow_self_signed' => true,
        'peer_name' =>'smtp.blabla.com'
    )
);
$mail->SMTPSecure = 'tls';
$mail->SMTPAuth = false;
$mail->Username = 'blahblah@blahblah.com';
$mail->Password = 'blahblah';
$mail->setFrom('blahblah@blahblah.com', 'Mailer');
$mail->addAddress('murad.s@code.edu.az', 'Me');
$mail->Subject = 'PHPMailer SMTP options test';
$mail->Body    = 'This is the HTML message body <b>in bold!</b>';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo $mail->ErrorInfo;
}
```

**Comment by Synchro** [comment]
I can't tell what's wrong - you need to follow what the troubleshooting guide says.

**Comment by muradsofiyev** [comment]
I follow troubleshooting guide says but not work

**Comment by Synchro** [comment]
Show what you tried. I can't do it for you.

**Comment by muradsofiyev** [comment]
2016-10-11 07:19:24	CLIENT -> SERVER: STARTTLS
2016-10-11 07:19:24	SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
2016-10-11 07:19:24	SMTP Error: Could not connect to SMTP host.
2016-10-11 07:19:24	SMTP NOTICE: EOF caught while checking if connected

It's my error $mail->SMTPDebug = 2;

**Comment by muradsofiyev** [comment]
http://asankadr.az/t_mail/reset_pass.php
http://asankadr.az/t_mail/info.php

**Comment by Synchro** [comment]
Can you try this: In the SMTP class, find this line in the the `connected()` method:

            if ($sock_status['eof']) {

Replace it with this:

            if (feof($this->smtp_conn)) {

Does that make any difference?

**Comment by muradsofiyev** [comment]
No it's not worked

**Comment by Synchro** [comment]
So you get the same error? What happens when you use openssl to connect (as described in the guide) - do the `peer_name` and certificate match exactly?

**Comment by muradsofiyev** [comment]
Yeah it's same error 
I execute this code

 <?php
require 'phpmailer/PHPMailerAutoload.php';
echo '<pre>';
$mail = new PHPMailer;

$mail->SMTPDebug = 2;

$mail->isSMTP();
$mail->SMTPAutoTLS = true;
$mail->Host = 'smtp.mail.gov.az';
$mail->SMTPAuth = true;
$mail->Username = 'noreply@asan.gov.az';
$mail->Password = 'blablaabla';
$mail->SMTPSecure = 'tls';
$mail->Port = 587;

$mail->setFrom('noreply@asan.gov.az', 'Mailer');
$mail->addAddress('iseymur@gmail.com', 'Seymur Ismayl');     // Add a recipient
$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'Here is the subject';
$mail->Body    = 'This is the HTML message body <b>in bold!</b>';
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

if(!$mail->send()) {

    echo "error";
} else {
    echo 'Message has been sent';
}

and error 

2016-10-11 12:32:30	SERVER -> CLIENT: 220 smtp.mail.gov.az ESMTP on Gov.AZ
2016-10-11 12:32:30	CLIENT -> SERVER: EHLO asankadr.az
2016-10-11 12:32:30	SERVER -> CLIENT: 250-smtp.mail.gov.az
                   	                  250-PIPELINING
                   	                  250-SIZE 62914560
                   	                  250-VRFY
                   	                  250-ETRN
                   	                  250-STARTTLS
                   	                  250-ENHANCEDSTATUSCODES
                   	                  250-8BITMIME
                   	                  250-DSN
                   	                  250 SMTPUTF8
2016-10-11 12:32:30	CLIENT -> SERVER: STARTTLS
2016-10-11 12:32:30	SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
2016-10-11 12:32:30	SMTP Error: Could not connect to SMTP host.
2016-10-11 12:32:30	SMTP NOTICE: EOF caught while checking if connected
2016-10-11 12:32:30	SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by Synchro** [comment]
And openssl?

**Comment by Synchro** [comment]
I tested it with `openssl s_client -connect smtp.mail.gov.az:587 -starttls smtp`, and get this response:

```
CONNECTED(00000003)
depth=2 C = US, O = GeoTrust Inc., CN = GeoTrust Primary Certification Authority
verify error:num=20:unable to get local issuer certificate
---
Certificate chain
 0 s:/jurisdictionC=AZ/businessCategory=Government Entity/serialNumber=Government Entity/C=AZ/ST=Baku/L=Baku/O=Special State Protection Service/CN=secure.mail.gov.az
```

Two significant things here: it fails to verify (which could be a local problem), and the CN (`secure.mail.gov.az `) does not match the host name you connected to (`smtp.mail.gov.az`). I tried connecting to `secure.mail.gov.az` as well, but that didn't respond. So, it looks like this is a verification failure.

**Comment by muradsofiyev** [comment]
I test send mail with c# this worked but i try with php and php mailer it is not worked

**Comment by Synchro** [comment]
Is C# validating the certificate? What happens if you disable the certificate check in PHPMailer? Your original code permitted self-signed certs, but the one the server is presenting is not self-signed.

**Comment by muradsofiyev** [comment]
I send to you  my code . Do you can try my code ?

**Comment by Synchro** [comment]
That won't help - There's nothing wrong with your code, it's the envionment or server (as in the mismatched cert above) that's causing your problem. Try what I suggested.

**Comment by pipajaki** [comment]
Hi
I ccan not solution ...
pleas help me :/
this is my code:
$mail->isSMTP(); // Set mailer to use SMTP
$mail->Host = 'mail.pidh.ir'; // Specify main and backup SMTP servers
$mail->SMTPAuth = true; // Enable SMTP authentication
$mail->Username = '	info@pidh.ir'; // SMTP username
$mail->Password = 'password'; // SMTP password
$mail->SMTPSecure = 'tls'; // Enable TLS encryption, ssl also accepted
$mail->Port = 25; // TCP port to connect to
$mail->CharSet = 'UTF-8';
$mail->SMTPOptions = array(
'ssl' => array(
'verify_peer' => false,
'verify_peer_name' => false,
'allow_self_signed' => true
)
);

$mail->setFrom(' info@pidh.ir', 'name');
$mail->addAddress('zahra.maleki91@gmail.com');
but I have this error:
Message could not be sent.Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by ooxi** [comment]
@pipajaki please don't hijack issues, this should be common courtesy by now...

**Comment by Synchro** [comment]
@pipajaki Please read the guide that your error message links to.
