### ISSUE TITLE
Fatal error: Maximum execution time of 30 seconds exceeded error on line 1201 in class.smtp.php

### ISSUE THREAD

**Issue by chintan97** [PHPMailer/PHPMailer#853]
I am getting error as below.

```
( ! ) Fatal error: Maximum execution time of 30 seconds exceeded in C:\wamp\www\chintan1\PHPMailer-master\class.smtp.php on line 1201
Call Stack
#   Time    Memory  Function    Location
1   0.0008  379128  {main}( )   ..\mail_registered.php:0
2   0.0487  1382352 PHPMailer->send( )  ..\mail_registered.php:21
3   0.0498  1384432 PHPMailer->postSend( )  ..\class.phpmailer.php:1206
4   0.0498  1384432 PHPMailer->smtpSend( )  ..\class.phpmailer.php:1326
5   0.0498  1384552 PHPMailer->smtpConnect( )   ..\class.phpmailer.php:1489
6   0.0517  1639064 SMTP->connect( )    ..\class.phpmailer.php:1609
7   0.0517  1640336 stream_socket_client ( )    ..\class.smtp.php:283
8   63.0641 1642936 SMTP->errorHandler( )   ..\class.smtp.php:0
```

My Code is as below...

``` php
<?php
require_once('PHPMailer-master\class.phpmailer.php');
require 'PHPMailer-master\PHPMailerAutoload.php';
session_start();
$em = $_SESSION["mail_reg"];
$mail = new PHPMailer(); // create a new object
$mail->IsSMTP(); // enable SMTP
//$mail->SMTPDebug = 2; // debugging: 1 = errors and messages, 2 = messages only
$mail->SMTPAuth = true; // authentication enabled
$mail->SMTPSecure = 'ssl'; // secure transfer enabled REQUIRED for Gmail
$mail->Host = "smtp.gmail.com";
$mail->Port = 465; // or 587
$mail->IsHTML(true);
$mail->Username = "mymail@gmail.com";
$mail->Password = "my_password";
$mail->SetFrom("mymail@gmail.com");
$mail->Subject = "Thanks for registering";
$mail->Body = "Dear ".$_SESSION['mail_reg_nm'].",<br><br> Thanks for registering on www.ewastecollection.com<br><br>Your details:<br><br>Name: ".$_SESSION['mail_reg_nm']."<br>Mobile: ".$_SESSION['mail_reg_mo']."<br>Password: ".$_SESSION['mail_reg_pa']."";
$mail->AddAddress($em);

 if(!$mail->Send()) {
    session_destroy();
    $con = mysql_connect("localhost","root","");

    $m1 = mysql_select_db("user_data",$con);
    $q = "delete from user where email='".$em."'";

    mysql_query($q);
    //echo "Mailer Error: " . $mail->ErrorInfo;
    echo '<script language="javascript">
    alert("Something went wrong! Email provided why you seems incorrect!!!")
    window.location.href="register.php"
    </script>';

 } else {
    session_destroy();
    echo '<script language="javascript">
    alert("Thanks for registering.")
    window.location.href="register.php"
    </script>';
 }
 ?>
```

Same code runs successfully and Email is sent to user on my laptop. But in Office PC I am getting this error.

**Comment by Synchro** [comment]
30 seconds is nowhere near long enough for reliable SMTP, you definitely need to increase the max execution time in your php.ini. That said, it probably won't help in this case. You probably have some kind of network issue on your office PC which you can test for by reading [the troubleshooting guide in the wiki](https://github.com/PHPMailer/PHPMailer/wiki). I can also see that you have based your code on an obsolete example, and you're probably using an old version of PHPMailer.

**Comment by mqasim1990** [comment]
I am getting email of users from database with while loop and sending email through PhpMailer, but its give an error of Maximum execution time 30 second . How can i fix it ?

**Comment by Synchro** [comment]
Increase you max execution time in your php.ini, or hand it off to an async process.

**Comment by mqasim1990** [comment]
where is php.ini file can you please proper guide to me ?

**Comment by mqasim1990** [comment]
i changed the max_execution_time to 300sec in php.ini file but its still giving an error!
Fatal error:  Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\bims2016\PHPMailer\class.smtp.php on line 276

**Comment by Synchro** [comment]
Restart your web server for it to pick the changes in yoru php.ini.

**Comment by mqasim1990** [comment]
Thank you so much its working  :)

**Comment by sumeetbhardwaj88** [comment]
Dear frnds my code bt im fnd the error     Message could not be sent.Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting




<?php
function send_code($ver_code,$email){
require 'PHPMailer/PHPMailerAutoload.php';

$mail = new PHPMailer;

//$mail->SMTPDebug = 3;                               // Enable verbose debug output

$mail->isSMTP();                                      // Set mailer to use SMTP
$mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = 'sumeetbhardwaj88@gmail.com';                 // SMTP username
$mail->Password = '';                           // SMTP password
$mail->SMTPSecure = 'ssl';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port =587;                                    // TCP port to connect to

$mail->setFrom('sumeetbhardwaj88@gmail.com', 'SUMEET BHARDWAJ');
$mail->addAddress($email);     // Add a recipient

$mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
$mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name
$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'Confirmation Code';
$mail->Body    = "Thank You! For Joining Your Confirmation code is:".$ver_code;
$mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

if(!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message has been sent';
}
}

**Comment by Synchro** [comment]
Please read the thread before posting. The SMTP specification allows servers to take up to 10 minutes to respond to commands, so you need to increase `max_execution_time` in your `php.ini` file to allow your scripts to take that long.

**Comment by sumeetbhardwaj88** [comment]
hello Sir,

how to increase  time plz tell me. plz sir

**Comment by Synchro** [comment]
[Read the docs](http://www.php.net/manual/en/configuration.php) like everyone else does.

**Comment by jerald-jacob** [comment]
I'm trying to send mail to localhost at many times but. I have to reach different error at different times.can you help me to remove this error .
Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\mail\PHPMailer-master\class.smtp.php on line 1227

**Comment by Synchro** [comment]
You could try reading this thread, since it tells you exactly what to do.

**Comment by lmerlini** [comment]
Aqui deu tudo certo, muito obrigado!
