### ISSUE TITLE
Possible edebug function log level problem

### ISSUE THREAD

**Issue by sorudan** [PHPMailer/PHPMailer#854]
In class class.smtp.php, protected function edebug($str, $level = 0), line
call_user_func($this->Debugoutput, $str, $this->do_debug);
should not read?:
call_user_func($this->Debugoutput, $str, $level);

Given log level should be logged instead of configured maximal log level.

I presume that this error comes from same function in class.phpmailer.php, but there is no $level input parameter. Maybe there should be added $level there.

Sorry if I misunderstand this.

**Comment by Synchro** [comment]
Yes, I think you're right here, so I've changed it to pass in `$level` in a4de1ca. It's only applicable to the debug output function, which only decides what the output looks like, not whether it happens or not.
