### ISSUE TITLE
Example files missing from zip download

### ISSUE THREAD

**Issue by juanmafx** [PHPMailer/PHPMailer#856]
When i´m download the zip the example files do not DOWNLOAD

![eror](https://cloud.githubusercontent.com/assets/5596967/19425644/5ee2229c-940b-11e6-824e-694e6a408e62.png)

Whati´m doing wrong....

**Comment by vinkla** [comment]
If you clone this repository instead of downloading it as a zip file you will get the examples directory.

**Comment by Synchro** [comment]
I'm going to treat this like a BC break, so I'm putting the examples back in 5.2.x (cf8cd05), but leaving them out for 6.0 and documenting it.
