### ISSUE TITLE
slowly when fgets() from smtp_conn

### ISSUE THREAD

**Issue by WuHuaJi0** [PHPMailer/PHPMailer#859]
I find a problem is this:
At the function get_lines in class.smtp.php , when use fgets() to read lines from the smtp_conn handler , it's slow and wait for a while .

I have no idea ,is any problem in here ?

**Comment by Synchro** [comment]
I don't think so. It's probably just your server being slow.

**Comment by WuHuaJi0** [comment]
thanks，I find out the problem is the smtp server being slow for some reason.
