### ISSUE TITLE
magic_quotes removed in PHP 7

### ISSUE THREAD

**Issue by developius** [PHPMailer/PHPMailer#864]
Hi,

The function `set_magic_quotes_runtime` [has been removed in PHP 7](http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.removed-functions.magic-quotes). I suggest adding a check to see what the PHP version is (deprecated in 5.3.0 but actually removed in 5.4.0) to make sure an exception isn't raised.

Thanks!

**Comment by Synchro** [comment]
You mean [like it does already](https://github.com/PHPMailer/PHPMailer/blob/6eaec68260c779bed14509e10ae5120dd9e1572b/class.phpmailer.php#L2634)?

**Comment by developius** [comment]
So sorry, I read that line completely wrong.
