### ISSUE TITLE
Wrong boundary

### ISSUE THREAD

**Issue by KingCandian** [PHPMailer/PHPMailer#871]
With PHPMailer 5.2.16 i have the following issue - the boundary is wrong.
`
$mail = new phpmailer();
$mail->From     = $madaten['vonmail'];
$mail->FromName = $madaten['vonname'];
$mail->Subject = $madaten['betreff'];
$mail->Host     = "mail02";
$mail->Mailer   = "smtp";
$mail->IsHTML(true);
$mail->Sender = 'unzustellbarvertrieb@domino-verlag.de';
$mail->addCustomHeader("X-KDNr:".ganzzahl($v['zahlernummer']));
$mail->addCustomHeader("X-DOMUNZID:".$uniqunzid);
$mail->MsgHTML($madaten['text']);
$mail->AddAddress('to@domain.com');
$mail->Send();
`

I save the Mail with
	$this->MIMEHeader = $this->CreateHeader();
      $this->MIMEBody = $this->CreateBody();
als .eml File

In this file - the boundary is defined as "b1_a53a69bb82ab3d1822a61d2303b96b8c"
but in the body is "b1_887cab45db728c6a7f0e6f901f1a5c33" used as boundary.
The boundary values should be equal....

`Date: Wed, 2 Nov 2016 13:08:17 +0100
To: to@domain.com
From: 
Subject: 
Message-ID: <a53a69bb82ab3d1822a61d2303b96b8c@DIVA>
X-Mailer: PHPMailer 5.2.16 (https://github.com/PHPMailer/PHPMailer)
X-KDNr: 
X-DOMUNZID: 
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="b1_a53a69bb82ab3d1822a61d2303b96b8c"
Content-Transfer-Encoding: 8bit

This is a multi-part message in MIME format.

--b1_887cab45db728c6a7f0e6f901f1a5c33
Content-Type: text/plain; charset=us-ascii

blasklfsjsdfsdfsdfdsf

--b1_887cab45db728c6a7f0e6f901f1a5c33
Content-Type: text/html; charset=us-ascii

<p>blasklfsj<br>sdfsdfsdfdsf

--b1_887cab45db728c6a7f0e6f901f1a5c33--
`

**Comment by Synchro** [comment]
This is because the boundary values are created (and any old value will be overwritten) in `createBody`. If you want a complete generated message, don't do it yourself, call `preSend()` then `getSentMIMEMessage()`.

**Comment by KingCandian** [comment]
Thats it! 
Thank you very much for helping me out!
