### ISSUE TITLE
SMTP ERROR: Failed to connect to server: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10060) 2016-11-06 08:59:09 SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting Confirmation code sent to your email Sent

### ISSUE THREAD

**Issue by harrisonmurithi** [PHPMailer/PHPMailer#872]
<?php
require_once 'PHPMailer/PHPMailerAutoload.php';
$m=new PHPMailer;
$m->isSMTP();
$m->SMTPAuth=true;
$m->SMTPDebug=2; //debuging information during development

$m->Host='smtp.gmail.com';
$m->Username='murithi@gmail.com';
$m->Password='password';
$m->SMTPSecure='ssl';
$m->Port=465;

$m->From='murithi@gmail.com';
$m->FromName='K24 Electronics';
$m->addReplyTo('harri@gmail.com','Reply Address');
$m->addAddress('harry@gmail.com','Harrison Murithi');
$m->isHTML(true); //html code
//$m->addAttachment('files/order/order.pdf','order'); //send file image
//$m->addCC('murithi@gmail.com','Harrison Murithi');
//$m->addBCC('murithi@gmail.com','Harrison Murithi');
$m->Subjuct='Please this is your confirmation code';
$m->Body='<p>your confirmation code is this</p><p><strong>Code</strong></p>';
$m->AltBody='your confirmation code is this';
//var_dump($m->send()); //to be removed
if(!$m->send()){
 echo "Confirmation code sent to your email Sent";	
}
else{
	echo $m->ErrorInfo;
}
?>

**Comment by Synchro** [comment]
If I was forced to guess, I'd say that a connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Have you perhaps considered reading the error message or the documentation it points you at, and trying what it says?

**Comment by meldaaktepe** [comment]
Sooo I have the same issue but I DON'T KNOW HOW TO FIX IT,
