### ISSUE TITLE
Sending Long Emails via TLS

### ISSUE THREAD

**Issue by byshine** [PHPMailer/PHPMailer#874]
If I send an email via TLS, and has a reasonable length of characters it works fine.

If I send about 200,000 characters in the email body with HTML, email never comes through.

Any possible explanation for this?
Strings are given new lines to avoid the line length limit.

**Comment by Synchro** [comment]
Check whether the mail server you're connecting to has a SIZE limit - try this with your mail server:
```
telnet smtp.gmail.com 25
Trying 2a00:1450:400c:c04::6d...
Connected to gmail-smtp-msa.l.google.com.
Escape character is '^]'.
220 smtp.gmail.com ESMTP y2sm33487911wjx.20 - gsmtp
EHLO localhost
250-smtp.gmail.com at your service, [2a00:1098:0:80:1000:2a:0:1]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
```

The SIZE value in that list is the max message size in bytes.

Next thing to check: you may be running out of memory - PHPMailer is pretty fast, but gets some of that speed from being quite memory hungry. If that's happening, you should see errors in your web server log. Increase memory allocation in your php.ini to fix it.

If you set `SMTPDebug = 2` you should get feedback about the SMTP conversation and see at what point it fails.

**Comment by byshine** [comment]
Alright, I did this and we found out that everything has been OK'd

SERVER -> CLIENT: 250 ok:  Message 4092405 accepted
CLIENT -> SERVER: QUIT
SERVER -> CLIENT: 221

I'm guessing this is out of our control?

**Comment by Synchro** [comment]
Yes, that all looks good, so something must be wrong further along in the email chain - it's a receiving problem, not a sending one, and as you say, out of your control.

**Comment by byshine** [comment]
Maybe the received it, but refuse to send it out?
