### ISSUE TITLE
problem dynamically populate "From:" address...

### ISSUE THREAD

**Issue by glennnall** [PHPMailer/PHPMailer#875]
I've inherited an instance of PHPMailer and have never worked with it before:

I'm trying to populate "From" just as "FromName" is populated, but when I add the From line, the script fails.

                require_once('phpmailer/class.phpmailer.php');

		$email = new PHPMailer();
		$email->IsHTML(true);      
		$email->FromName  = $princiName;

		$email->From  = $princiEmail;
		
		$email->Subject   = $subject;
		$temp       = file_get_contents('mentorTemplate.php');
                $temp       = str_replace('#principalMessage#',$Notification,$temp);
		$email->Body    = $temp;
		$email->AddAddress($value[0]['email']);	

Can someone please help me with this...?

many thanks!!

**Comment by Synchro** [comment]
What's the error? What's in `$princiEmail`?

Are you using the latest version?
