### ISSUE TITLE
Getting Error while add any url to mail body

### ISSUE THREAD

**Issue by kavinthan** [PHPMailer/PHPMailer#878]
I was getting an error while sending a mail with any URL in mail body. the error was - Mailer Error: SMTP Error: Data not accepted

After that I resolved this issue with deleting $mail->IsSMTP(); code from my mail configuration.

But I hoped it was an important part in PHPmailer. Is this give any problem in future?

**Comment by Synchro** [comment]
This may just mean the problem appears somewhere else. With `isSMTP`, it sends like this:

    script -> destination mail server

and when you remove it, that changes to:

    script -> local mail server -> destination mail server

So your own server doesn't reject the message, but the message may be rejected later on, and your script will never know about it.

PHPMailer doesn't care what's in your message, it just sends whatever you put in `Body`, and it has no control over whether the destination server accepts it.

**Comment by puransari** [comment]
I have same problem when I send a link kike  www.example.com/page.php?x=1y=2 , but when I send www.example.com it works
