### ISSUE TITLE
PHPmailer appears not to be attempting to authenticate SMTP

### ISSUE THREAD

**Issue by Properhead** [PHPMailer/PHPMailer#880]
I am tearing my hair out trying to get SMTP authentication to work.  It appears PHPmailer is making no attempt to send the username/password specified.  I've closely followed the examples, and am using the latest PHPmailer.

The SMTP server, authentication username/password, port 465 for SSL encryption, are exactly the same as used by my mail server which runs perfectly.  I have tried setting $mail->SMTPAutoTLS = false & true, no difference.

I would appreciate any comments that might help me resolve the problem

SETTINGS no TLS:

  Host = [host2.axxesslocal.co.za]
  SMTPAuth = [1]
  SMTPsecure = []
  Port = [25]
  Username = [neilf@megapulsesa.com]
  Password = [xxxxxxx]
  Hostname = []
  SetFrom = [neilf@megapulsesa.com]
  AddReplyTo = [NeilF@megapulsesa.com]
  AddAddress = [neilafraser@gmail.com]
  SMTPDebug = [2]

DIALOG:

  CLIENT -> SERVER: EHLO www.megapulsesa.com
  SERVER -> CLIENT: 250-host2.axxesslocal.co.za Hello axxess33.dedicated.co.za [154.0.168.117]250-SIZE 52428800250-8BITMIME250-PIPELINING250-AUTH PLAIN LOGIN250-STARTTLS250 HELP
  CLIENT -> SERVER: MAIL FROM:<neilf@megapulsesa.com>
  SERVER -> CLIENT: 250 OK
  CLIENT -> SERVER: RCPT TO:<neilafraser@gmail.com>
  SERVER -> CLIENT: 550-Please turn on SMTP Authentication in your mail client. 550-axxess33.dedicated.co.za (www.megapulsesa.com) [154.0.168.117]:55882 is not550 permitted to relay through this server without authentication.
  SMTP ERROR: RCPT TO command failed: 550-Please turn on SMTP Authentication in your mail client. 550-axxess33.dedicated.co.za (www.megapulsesa.com) [154.0.168.117]:55882 is not550 permitted to relay through this server without authentication.
  CLIENT -> SERVER: QUIT
  SERVER -> CLIENT: 221 host2.axxesslocal.co.za closing connection
  SMTP Error: The following recipients failed: neilafraser@gmail.com: Please turn on SMTP Authentication in your mail client. axxess33.dedicated.co.za (www.megapulsesa.com) [154.0.168.117]:55882 is notpermitted to relay through this server without authentication.

SETTINGS with TLS:

  Host = [host2.axxesslocal.co.za]
  SMTPAuth = [1]
  SMTPsecure = [tls]
  Port = [587]
  Username = [neilf@megapulsesa.com]
  Password = [xxxxxxx]
  Hostname = []
  SetFrom = [neilf@megapulsesa.com]
  AddReplyTo = [NeilF@megapulsesa.com]
  AddAddress = [neilafraser@gmail.com]
  SMTPDebug = [2]

DIALOG:

  SERVER -> CLIENT: 220-host2.axxesslocal.co.za ESMTP Exim 4.87 #1 Fri, 11 Nov 2016 09:42:52 +0200 220-We do not authorize the use of this system to transport unsolicited, 220 and/or bulk e-mail.
  CLIENT -> SERVER: EHLO www.megapulsesa.com
  SERVER -> CLIENT: 250-host2.axxesslocal.co.za Hello axxess33.dedicated.co.za [154.0.168.117]250-SIZE 52428800250-8BITMIME250-PIPELINING250-AUTH PLAIN LOGIN250-STARTTLS250 HELP
  CLIENT -> SERVER: MAIL FROM:<neilf@megapulsesa.com>
  SERVER -> CLIENT: 250 OK
  CLIENT -> SERVER: RCPT TO:<neilafraser@gmail.com>
  SERVER -> CLIENT: 550 SMTP AUTH is required for message submission on port 587
  SMTP ERROR: RCPT TO command failed: 550 SMTP AUTH is required for message submission on port 587
  CLIENT -> SERVER: QUIT
  SERVER -> CLIENT:
  SMTP ERROR: QUIT command failed:
  SMTP Error: The following recipients failed: neilafraser@gmail.com: SMTP AUTH is required for message submission on port 587
  
POP3 PRE-AUTHENTICATION:

  $pop = new POP3() ;
  $pop->Authorise ($Host, 110, 30, $EUsername, $EPassword, 1);
  // alternatively this does the same as the above, but makes no difference:
      // $pop = POP3::popBeforeSmtp($Host, 110, 30, $EUsername, $EPassword, 1);
  
ERRORS:

Array
(
    [error] => Connecting to the POP3 server raised a PHP warning: 
    [errno] => 2
    [errstr] => fsockopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known
    [errfile] => /home/megapuls/public_html/PHPMailer-master/class.pop3.php
    [errline] => 229
)
Array
(
    [error] => Failed to connect to server  on port 110
    [errno] => 0
    [errstr] => php_network_getaddresses: getaddrinfo failed: Name or service not known
)

**Comment by Synchro** [comment]
Please don't paraphrase your settings like that, it really doesn't help. Post your actual code. The transcript shows it's not trying to STARTTLS before auth, apparently because you've disabled it.
