### ISSUE TITLE
Fix to DKIM Private Key as a string issue

### ISSUE THREAD

**Issue by DanieleRatti** [PHPMailer/PHPMailer#881]
In the previous commit you were unable to provide a DKIM Private Key as
a string (#879) due to a wrong IF at line 1297.

You just need to remove that line to get everything working fine.

`&& !empty($this->DKIM_private)`

**Comment by SDKiller** [comment]
IMO
```
&& (!empty($this->DKIM_private_string) || (!empty($this->DKIM_private) && file_exists($this->DKIM_private)))) {
```

**Comment by Synchro** [comment]
That will teach me not to review PRs in a hurry!

Thanks. I've done it as @SDKiller suggested.
