### ISSUE TITLE
Connection timeout?

### ISSUE THREAD

**Issue by Aeri1112** [PHPMailer/PHPMailer#882]
Hi,

i've got a Problem with PHPMailer since about one week. the only output is:

opening to smtp.gmail.com:587, timeout=300, options=array ( ) 

after the timeout the script stops and nothing happend. Can someone help me?

**Comment by Synchro** [comment]
Sounds like your ISP is blocking your outbound SMTP connections - it's very common. Read the troubleshooting guide in the wiki.
