### ISSUE TITLE
Emails doesn't goes to inbox

### ISSUE THREAD

**Issue by chaitu0609** [PHPMailer/PHPMailer#888]
If I am using phpmailer script with smtp authentication, at that time email not configured into inbox. It's going to spam why?.

Here my using script

<?php
require("PHPMailerAutoload.php");
$mail = new PHPMailer(true);

//$mail->SMTPDebug = 0;                               // Enable verbose debug output

$mail->isSMTP();    
$mail->CharSet = 'UTF-8';                                  // Set mailer to use SMTP
$mail->Host = 'sample.smtp.in';  // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = '';                 // SMTP username
$mail->Password = '';                           // SMTP password
$mail->SMTPSecure = 'ssl';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 465;                                    // TCP port to connect to
$mail->From = 'from-email';
$mail->FromName = 'from-name';
$mail->addAddress('test@example.com', 'test');     // Add a recipient
$mail->addReplyTo('info@example.com', 'Information');
//$mail->addCC('cc@example.com');
//$mail->addBCC('bcc@example.com');

//$mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
//$mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name
$mail->isHTML(true);                                  // Set email format to HTML

$mail->Subject = 'Test Email';
$mail->Body    = '<h1>Hi this is test mail</h1>';
//$mail->AltBody = 'Hi this is test mail';

if(!$mail->send()) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
} else {
    echo 'Message has been sent';
}

**Comment by Synchro** [comment]
It's impossible to say. Spam filters are entirely arbitrary - if there was a simple way to evade them, spammers would use it. If this is your real script, then nothing mentioning `example.com` is likely to work, also check that you're not forging the from addresses, not trying to send from domains with strong DMARC settings etc. Ultimately it's outside PHPMailer's control.
