### ISSUE TITLE
DKIM signature fails at hotmail/outlook (body hash), passes everywhere else

### ISSUE THREAD

**Issue by upcontact** [PHPMailer/PHPMailer#892]
I sign my email using PHPMailer 5.2.16 setting DKIM parameters.
The DKIM test passes everywhere (gmail, port25, mail-tester, ...) but fails on Hotmail and Outlook
See headers below.
Any idea ?

```
Authentication-Results: spf=pass (sender IP is 5.196.66.14)
 smtp.mailfrom=g5.upc6.net; hotmail.fr; dkim=fail (body hash did not verify)
 header.d=g5.upc6.net;hotmail.fr; dmarc=none action=none
 header.from=upcontact.com;
Received-SPF: Pass (protection.outlook.com: domain of g5.upc6.net designates
 5.196.66.14 as permitted sender) receiver=protection.outlook.com;
 client-ip=5.196.66.14; helo= g5.upc6.net;
Received: from SNT004-MC1F43.hotmail.com (10.152.4.56) by
 DB5EUR01FT047.mail.protection.outlook.com (10.152.5.196) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id
 15.1.734.4 via Frontend Transport; Tue, 6 Dec 2016 08:36:36 +0000
X-IncomingTopHeaderMarker: OriginalChecksum:;UpperCasedChecksum:;SizeAsReceived:2063;Count:17
Received: from g5.upc6.net ([5.196.66.14]) by SNT004-MC1F43.hotmail.com with Microsoft SMTPSVC(7.5.7601.23143);
	 Tue, 6 Dec 2016 00:36:35 -0800
Received: from g5.upc6.net (localhost.localdomain [127.0.0.1])
	by g5.upc6.net (Postfix) with ESMTPS id 6AF72FF796
	for <rea@hotmail.fr>; Tue,  6 Dec 2016 09:36:34 +0100 (CET)
Date: Tue, 6 Dec 2016 09:36:34 +0100
To: "rea@hotmail.fr" <rea@hotmail.fr>
From: Support | upContact <support@upcontact.com>
Reply-To: Support | upContact <support@upcontact.com>
Subject: =?utf-8?b?W1RFU1RdIHVwQ29udGFjdCBOZXdzIHwgTWVzc2FnZSBBdWRpdG9yLCDDqWRpdGV1ciBkZSBzdHJ1Y3R1cmUgJiBtb2R1bGUgUHJlc3Rhc2hvcA==?=
Message-ID: <129128058@g5.upc6.net>
X-Mailer: PHPMailer 5.2.16 (https://github.com/PHPMailer/PHPMailer)
Sender: <support=upcontact.com@g5.upc6.net>
List-Unsubscribe: <mailto:unsubscribe@g5.upc6.net?subject=unsubscribe>, <http://g5.upc6.net/unsubscribe.php?token=v3ljOs6lB3lDhfh0BAbO>
Precedence: bulk
Content-Type: multipart/alternative;
	boundary="b1_4a52c0a04b42c40fc173b0b72d2059b2"
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; l=761; s=k1;
	t=1481013394; c=relaxed/relaxed;
	h=From:To:Date:Subject;
	d=g5.upc6.net;
	z=From:=20Support=20=7C=20upContact=20<support@upcontact.com>
	|To:=20"rea@hotmail.fr"=20<rea@hotmail.fr>
	|Date:=20Tue,=206=20Dec=202016=2009:36:34=20+0100
	|Subject:=20=3D?utf-8?b?W1RFU1RdIHVwQ29udGFjdCBOZXdzIHwgTWVzc2FnZSBBdWRpdG9yLCDDqWRpdGV1ciBkZSBzdHJ1Y3R1cmUgJiBtb2R1bGUgUHJlc3Rhc2hvcA=3D=3D?=3D;
	bh=EXOn+JoSIAlWHBsFykbFgnPMjjnpRerQ769lLC9La7U=;
	b=UE5R1UkMbYSiV+kS5ZUpaLkamZoEi7D2B/yaSXh5LkSrMAzaZhtqsvam/A9Q3LFn/pKRx/b738VVmM2fBekH8aEpGyohipZzPSy4Oe7lFKCj4yO3QCqz8xnpkcw0b5CKhVlgOt/YFx/UeNiuYEukd6uPmS2pXv5raQ8jQC4tpdPeCXgDvAOKhgeeWH30EQCytWCO5ETAlvXbv8Nq644wJ5OcXvSZqPQ27AwtmS/79JWuNiYwCitXGN+sS1Hr5byxxS5ODQPQ7hV0stmG1DvZ8/7PrreH9ZagoOrY/sn4QfPAv1jog4XmMbsnD6p30fJQz7ZvmmVlLnLZ6FztWqR2iw==
Return-Path: support=upcontact.com@g5.upc6.net
```

**Comment by Synchro** [comment]
Hotmail seems to have problems with some perfectly valid header formatting that the PHP `mail()` function sometimes messes up. One workaround - if you're currently using the default `isMail()` transport, switch to using `isSMTP()` instead.

**Comment by upcontact** [comment]
I am using isSMTP() with a postfix server. I discover that with a very simple, one line only and no utf8 character, I get a DKIM pass at hotmail. Very strange behavior... I can't find a way so far to have my full html page passing

**Comment by upcontact** [comment]
Even an ampersand character in the HTML body fails

**Comment by upcontact** [comment]
I finally got it working doing the following :

1/ change the encoding $mail->Encoding     = 'quoted-printable';
2/ trimming all body lines : 

$htmlMsg = "";
$lines = explode("\n",  $myHTML);
foreach ($lines as $line) $htmlMsg .= trim($line)."\n";
$mail->MsgHTML($htmlMsg);

Thank you Microsoft for those nice hours ;)

**Comment by Synchro** [comment]
Thanks for reporting, and the workaround! Using quoted-printable forces the body to be 7-bit clean, so this is probably an encoding problem. Not sure why trailing spaces would be a problem though - DKIM signing applies some fairly severe normalisation to the body before calculating the signature. It may be interesting to try [PHPMailer 6.0](https://github.com/PHPMailer/PHPMailer/tree/6.0) (not yet released) - the DKIM normalisation is much cleaner in that.

**Comment by lukasmedia** [comment]
@upcontact  you just saved me a few days of my life. Dude thanks!

**Comment by henno** [comment]
@upcontact, thank you!
@Microsoft... 😞.

**Comment by eskholm** [comment]
@upcontact You just saved me a lot of debugging hours - thank you! :)

**Comment by tictag** [comment]
Three days I've been trying investigating why my DKIM signature was failing with `DKIM=fail (body hash did not verify)`. Added `$phpmailer->Encoding = 'quoted-printable';` and now it works!! :-)

I'm just using the phpmailer (v5.2.27) that come with WordPress so couldn't update.

I swear I must have sent at least 100 test emails trying to get this working. Thank you so much @upcontact!

**Comment by akshayware** [comment]
Encoding = 'quoted-printable' is failing when you have string-like "<SOME_LINK>&custom1=123&custom2=vaibhav".
