### ISSUE TITLE
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

### ISSUE THREAD

**Issue by BenoitProot** [PHPMailer/PHPMailer#893]
I'm sending a mailing to about 1500 adresses using PHPMailer.
I have downloaded the latest version of PHPMailer.
 
The mailing starts fine, but after 50 adresses I get the following error for each new Send:
**SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting**
 
I'm not using SMTPKeepAlive.
This is my code that I repeat for each mail, executed at 2 seconds interval beween two mails:

        $email = new phpmailer();
        $email->isSMTP();
        $email->SMTPDebug = 0;
        $email->Debugoutput = 'html';
        $email->Host = SMTP_SERVER;
        $email->Port = 25;
        $email->SMTPAuth = true;
        $email->Username = 'username';
        $email->Password ='password';
        $email->SetFrom('email', 'shortname'); 
        $email->AddReplyTo($From);
        $email->AddAddress($To);
        $email->Subject = $Subject;
        $email->isHTML(true);
        $email->Body = $Body;
        $email->AltBody = strip_tags($AltBody);        
        foreach($attachments AS $NameOfFile=>$path) {
            $email->addStringAttachment(file_get_contents($path), $NameOfFile);
        }
        $b_Success = $email->Send();
        return $b_Success?null:$email->ErrorInfo;

What can be the problem ?

**Comment by Synchro** [comment]
Follow the link given in the error message and you might get some idea of where the problem lies. I'd guess that your ISP is imposing a limit on your send volume.

**Comment by BenoitProot** [comment]
Thank for your response.
I contacted the ISP, and they found that two many SMTP connections were open at the same time.
Can I close each connection in my PHP code?

They now advise to use SMTPKeepAlive.

**Comment by Synchro** [comment]
I'd suggest taking a look at the mailing list example provided with PHPMailer; stick a 2-second delay in the sending loop if you need to slow it down.

The SMTP connection will be closed automatically when the PHPMailer instance goes out of scope (or after message send is complete if you don't enable keepalive), but you can close it manually by calling `$mail->smtp->quit();`, though you should not need to.

**Comment by sabbir420** [comment]
require 'PHPMailer/src/PHPMailerAutoload.php';
use PHPMailer\PHPMailer\PHPMailer; 
use PHPMailer\PHPMailer\Exception;
define('GUSER', 'falaksabbir3@gmail.com'); // GMail username
define('GPWD', 'password');
	define('SMTPUSER', 'falaksabbir3@gmail.com'); // sec. smtp username
define('SMTPPWD', 'password'); // sec. password
define('SMTPSERVER', 'smtp.gmail.com'); // sec. smtp server
	function smtpmailer($to, $from, $from_name, $subject, $body, $is_gmail = true) { 
	global $error;
	$mail = new PHPMailer();
	$mail->IsSMTP();
	$mail->SMTPAuth = true; 
	if ($is_gmail) {
		$mail->SMTPSecure = 'ssl'; 
		$mail->Host = 'ssl://smtp.gmail.com';
		$mail->Port = 465;  
		$mail->Username = GUSER;  
		$mail->Password = GPWD;   
	} else {
		$mail->Host = SMTPSERVER;
		$mail->Username = SMTPUSER;  
		$mail->Password = SMTPPWD;
	}        
	$mail->SetFrom($from, $from_name);
	$mail->Subject = $subject;
	$mail->Body = $body;
	$mail->AddAddress($to);
	if(!$mail->Send()) {
		$error = 'Mail error: '.$mail->ErrorInfo;
		return false;
	} else {
		$error = 'Message sent!';
		return true;
	}
}
$msg = 'Hello World';
$subj = 'test mail message';
$to = 'falak@oddly.co';
$from = 'falaksabbir3@gmail.com';
$name = 'Falak Sabbir';
 
if (smtpmailer($to, $from, $name, $subj, $msg)) {
	echo 'Yippie, message send via Gmail';
} else {
	if (!smtpmailer($to, $from, $name, $subj, $msg, false)) {
		if (!empty($error)) echo $error;
	} else {
		echo 'Yep, the message is send (after doing some hard work)';
	}
}


This is my code. But it's giving this error.
Mail error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
How to fix this?

**Comment by Synchro** [comment]
Read the troubleshooting guide the error links to.
