### ISSUE TITLE
More of an FYI

### ISSUE THREAD

**Issue by irthinker** [PHPMailer/PHPMailer#896]
I ran into a very strange and specific problem and I don't think it's anything to do with your code, but I wanted to get it on the radar in case people see the same issue.

If I use the exact phrase "Please verify your email address to activate your account" in the subject line of an email, my emails do not get through.

If I drop "Please", it works.

If I change "verify" to "reverify", it works.

If I change "email address" to "bloody email address" it works.

It's baffling to me. It's as if the mail hosts have decided that this specific phrase is not allowed.  Anyway, it took me some time before I figured out this was my issue, and wanted to save others some time.

**Comment by Synchro** [comment]
I suspect YMMV - there are probably many other factors that decide whether things go into spam, very few use hard rules any more. Regardless, this will be indexed by search engines now :)
