### ISSUE TITLE
Problems with 1and1 Hosting

### ISSUE THREAD

**Issue by Assavar** [PHPMailer/PHPMailer#897]
I wanted to send emails with the data of a HTML `<from>`. So my main problem was, every time I clicked the submit button the page still reloads and hangs there. After 2 min the browser give me an unknown error.

After a couple days working on it, I finally found this: [https://webolio.wordpress.com/2008/03/02/phpmailer-and-smtp-on-1and1-shared-hosting/](url)

**Comment by Synchro** [comment]
That doesn't really say anything that's specific to PHPMailer. It seems that 1&1 requires that you use their servers for outbound email. PHPMailer will be giving a more specific error message and code, but the code calling it is evidently not making it visible, so I'd recommend reporting this to the maintainers of whatever app you're using.

**Comment by geins** [comment]
I have the same issue on 1and1 hosting. 
It's Linux shared hosting on PHP 7.0 and PHPmailer 5 (latest at date of post)
On my local test environment, same config works flawlessly, on production-server on hosting,
code hangs on           if ( !$mail->send() ) {  without any output on debug or php error log
Workaround for me: send with $mail->isSendMail(); on hosting.

My code:


try {
$mail = new PHPMailer;
$mail->setLanguage( 'de', SERVER_DIR . '/php/' );
$mail->CharSet   = "UTF-8";
$mail->SMTPDebug = 3;                                // Enable verbose debug output
//$mail->isSendMail(); //-->Bugfix für 1und1
$mail->isSMTP();                                      // Set mailer to use SMTP
$mail->Host       = 'smtp.1und1.de';                  // Specify main and backup SMTP servers
$mail->SMTPAuth   = true;                             // Enable SMTP authentication
$mail->Username   = 'myusername@mydomain.com';               // SMTP username
$mail->Password   = 'mypassword';                         // SMTP password
$mail->SMTPSecure = 'ssl';                            // Enable TLS encryption, `ssl` also accepted
$mail->Port       = 465;  //==SSL                            // TCP port to connect to
$mail->setFrom( 'myusername@mydomain.com', 'myusername' );
$mail->addAddress( 'testreceiver@mydomain.com' );
$mail->Subject = 'Some subject';
$mail->Body = 'Some test' . PHP_EOL  . 'more text';
if ( !$mail->send() ) {
throw new Exception( $mail -> ErrorInfo );
}
}
catch ( Exception $e ) {
header( $redirect . 'msg_alert=Fehler beim Senden der Email' ); //. $e -> getMessage() );
exit();
