### ISSUE TITLE
SetFrom is not working

### ISSUE THREAD

**Issue by ocvninfo** [PHPMailer/PHPMailer#899]
I have an issue with setFrom email.
for my example:
$email->Username = 'phucduongqb@gmail.com';
$email->Password= 'xxxxxxx';

$mail->setFrom('ocvninfo@gmail.com', 'Ocvninfo');

But when i submit form, the email from is still phucduongqb@gmail.com
Any one help me?

**Comment by Synchro** [comment]
This is covered in the troubleshooting guide in the wiki. Gmail does not allow you to set arbitrary From addresses. You can create fixed aliases in your gmail prefs, but you can't just use any address.

**Comment by ocvninfo** [comment]
:( :(
So, there is no way to set mail from for now :(
