### ISSUE TITLE
Email Not Send With i put my domain in message

### ISSUE THREAD

**Issue by zeeshan4971** [PHPMailer/PHPMailer#904]
I have this strange issue when i send this html message from PHP MAILER like this 

    $mail->Body    = "<p>this is a test html messsage</p>";
 
this works fine not matter how long text i put

    $mail->Body    = "<p>this is a test html messsage</p>  this is a  <a href='http://fadsa.com'>link</a>";

this also works fine but if i put the site domain in the link it i dont recive any emails why 

    $mail->Body    = "<p>this is a test html messsage</p>  this is a  <a href='http://mydomain.com'>link</a>"; this does not work it does not send emails at all

is this a known issue the current site domain preventing it from sending emails

**Comment by Synchro** [comment]
I'd guess at your messages being spam filtered. Once your message has been sent, PHPMailer has no control over it.

**Comment by zeeshan4971** [comment]
it is not in spam

**Comment by ooxi** [comment]
> it is not in spam

That does not mean it's not identified as spam. Look at the SMTP server logs to see what happens with your mail.
