### ISSUE TITLE
Missing first letter of attachment filename

### ISSUE THREAD

**Issue by niekutis** [PHPMailer/PHPMailer#906]
If file name attachment first letter is not Latin letter (filename string is UTF-8 encoding) - it skips in email.
Example:
`$mailer->AddStringAttachment('123', 'žasiukas.txt');`

email will be with attachment name:

> asiukas.txt

**Comment by Synchro** [comment]
Have you set `$mail->CharSet = 'UTF-8';`?

**Comment by niekutis** [comment]
yes

**Comment by Synchro** [comment]
I can't reproduce this. When I use your example I get this, which is entirely correct:

```
Content-Type: text/plain; name="=?UTF-8?Q?=C5=BEasiukas.txt?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="=?UTF-8?Q?=C5=BEasiukas.txt?="
```

`=C5=BE` is Q-encoded `U+017E`, the unicode value for `LATIN SMALL LETTER Z WITH CARON`, which is ž, and it looks correct in a decoded message.

**Comment by niekutis** [comment]
X-Mailer: PHPMailer 5.2.8 (https://github.com/PHPMailer/PHPMailer/)
MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="b1_dbdd98dcba67f5756b77878af48e58b7"
Content-Transfer-Encoding: 8bit


--b1_dbdd98dcba67f5756b77878af48e58b7
Content-Type: text/html; charset=us-ascii

aa


--b1_dbdd98dcba67f5756b77878af48e58b7
Content-Type: text/plain; name="siukas.txt"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=siukas.txt

MTIz


--b1_dbdd98dcba67f5756b77878af48e58b7--

**Comment by Synchro** [comment]
> X-Mailer: PHPMailer 5.2.8 (https://github.com/PHPMailer/PHPMailer/)

Rule 1: Don't report bugs in ancient versions.

**Comment by niekutis** [comment]
Tried with 5.2.17 too

**Comment by Synchro** [comment]
Do you have the mbstring extension enabled? Are you absolutely sure your source code is in UTF-8? Can you post a hex dump of your input data?

**Comment by niekutis** [comment]
```
 $name = 'žasiukas.txt';
 echo bin2hex($name);
```
output:
c5be617369756b61732e747874

**Comment by Synchro** [comment]
OK, that looks right - do your received headers not look like mine? If you set SMTPDebug = 2 does it show the headers being sent correctly?

**Comment by niekutis** [comment]
[_myMailer:EMailer:private] => PHPMailer Object
        (
            [Version] => 5.2.17
            [Priority] => 
            [CharSet] => UTF-8
            [ContentType] => text/html
            [Encoding] => 8bit
            [ErrorInfo] => 
            [From] => xxx@xx.xx
            [FromName] => xx.xxx.xx
            [Sender] => xx@xxx.xx
            [ReturnPath] => 
            [Subject] => test
            [Body] => aa
            [AltBody] => 
            [Ical] => 
            [MIMEBody:protected] => This is a multi-part message in MIME format.

--b1_80f2411dab2cf3bb4a108b1ac952ced5
Content-Type: text/html; charset=us-ascii

aa


--b1_80f2411dab2cf3bb4a108b1ac952ced5
Content-Type: text/plain; name="asiukas.txt"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=asiukas.txt

MTIz


--b1_80f2411dab2cf3bb4a108b1ac952ced5--

            [MIMEHeader:protected] => Date: Tue, 20 Dec 2016 11:53:16 +0200
From: "xx.xxx.xx" <xx@xx.xxx.xx>
Bcc: xx@xxx.xx
Message-ID: <80f2411dab2cf3bb4a108b1ac952ced5@xx.xxx.xx>
X-Mailer: PHPMailer 5.2.17 (https://github.com/PHPMailer/PHPMailer)
MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="b1_80f2411dab2cf3bb4a108b1ac952ced5"
Content-Transfer-Encoding: 8bit

            [mailHeader:protected] => To: xx@xxx.xx
Subject: test

            [WordWrap] => 0
            [Mailer] => mail
            [Sendmail] => /usr/sbin/sendmail
            [UseSendmailOptions] => 1
            [PluginDir] => 
            [ConfirmReadingTo] => 
            [Hostname] => 
            [MessageID] => 
            [MessageDate] => Tue, 20 Dec 2016 11:53:16 +0200
            [Host] => localhost
            [Port] => 25
            [Helo] => 
            [SMTPSecure] => 
            [SMTPAutoTLS] => 1
            [SMTPAuth] => 
            [SMTPOptions] => Array
                (
                )

            [Username] => 
            [Password] => 
            [AuthType] => 
            [Realm] => 
            [Workstation] => 
            [Timeout] => 300
            [SMTPDebug] => 2
            [Debugoutput] => echo
            [SMTPKeepAlive] => 
            [SingleTo] => 
            [SingleToArray] => Array
                (
                )

            [do_verp] => 
            [AllowEmpty] => 
            [LE] => 

            [DKIM_selector] => 
            [DKIM_identity] => 
            [DKIM_passphrase] => 
            [DKIM_domain] => 
            [DKIM_private] => 
            [DKIM_private_string] => 
            [action_function] => 
            [XMailer] => 
            [smtp:protected] => 
            [to:protected] => Array
                (
                    [0] => Array
                        (
                            [0] => xx@xxx.xx
                            [1] => 
                        )

                )

            [cc:protected] => Array
                (
                )

            [bcc:protected] => Array
                (
                    [0] => Array
                        (
                            [0] => xx@xxx.xx
                            [1] => 
                        )

                )

            [ReplyTo:protected] => Array
                (
                )

            [all_recipients:protected] => Array
                (
                    [xx@xxx.xx] => 1
                    [xx@xxx.xx] => 1
                )

            [RecipientsQueue:protected] => Array
                (
                )

            [ReplyToQueue:protected] => Array
                (
                )

            [attachment:protected] => Array
                (
                    [0] => Array
                        (
                            [0] => 123
                            [1] => žsiukas.txt
                            [2] => asiukas.txt
                            [3] => base64
                            [4] => text/plain
                            [5] => 1
                            [6] => attachment
                            [7] => 0
                        )

                )

            [CustomHeader:protected] => Array
                (
                )

            [lastMessageID:protected] => <80f2411dab2cf3bb4a108b1ac952ced5@xx.xxx.xx>
            [message_type:protected] => attach
            [boundary:protected] => Array
                (
                    [1] => b1_80f2411dab2cf3bb4a108b1ac952ced5
                    [2] => b2_80f2411dab2cf3bb4a108b1ac952ced5
                    [3] => b3_80f2411dab2cf3bb4a108b1ac952ced5
                )

            [language:protected] => Array
                (
                )

            [error_count:protected] => 0
            [sign_cert_file:protected] => 
            [sign_key_file:protected] => 
            [sign_extracerts_file:protected] => 
            [sign_key_pass:protected] => 
            [exceptions:protected] => 
            [uniqueid:protected] => 80f2411dab2cf3bb4a108b1ac952ced5

**Comment by Synchro** [comment]
This is the interesting part:

```
[attachment:protected] => Array
            (
                [0] => Array
                    (
                        [0] => 123
                        [1] => žsiukas.txt
                        [2] => asiukas.txt
                        [3] => base64
                        [4] => text/plain
                        [5] => 1
                        [6] => attachment
                        [7] => 0
                    )

            )
```

Element 2 is set from the same value as 1; the only difference is that it is passed through `basename()` first, and according to [the docs](http://php.net/manual/en/function.basename.php), it requires that your locale is set correctly, which I would guess yours is not:

> Caution basename() is locale aware, so for it to see the correct basename with multibyte character paths, the matching locale must be set using the setlocale() function.

The locale can also be set via your php.ini.
