### ISSUE TITLE
Issues with PHPMailer PCI Compliance 3.2 & TLS 1.1, 1.2 only

### ISSUE THREAD

**Issue by jxs714** [PHPMailer/PHPMailer#909]
Hi guys,

Not sure whats going on, but we're using Plesk Onyx and after disabling SSL and TLS 1.0 (As requested by PCI Compliance 3.2), phpmailer and smtp isn't working for any php software such as Wordpress, WHMCS, etc.

This is the response we received from Plesk support:

> As we agreed during over the phone conversation the WHMCS email issue is related to PHPMailer and PHP version 5.6.7 and higher. And you will contact WHMCS to get assistance to manage the TLS v1.1/v1.2 connectivity issue in PHPMailer used by WHMCS to send a mail. 

We have valid SSL certificates installed. This is happening for all php software used on server.

Please advise, thanks guys.

**Comment by Synchro** [comment]
You need to provide more info than "not working". Code & config to reproduce, error messages etc.

**Comment by Synchro** [comment]
Be aware of [this difference around PHP 5.6.7](http://php.net/manual/en/function.stream-socket-enable-crypto.php#119122). If you look in the code (assuming you're running a version more recent than 5.2.15, which you should be after the recent security issues), you'll see it's implemented exactly like that in PHPMailer.

I recommend testing your server using [testssl.sh](https://testssl.sh) and #923 may also be of interest.

**Comment by jxs714** [comment]
Hi Synchro,

Thanks for the update. Ended up using sendmail for now. If any update to this, we will be sure to reach back with it on our end.

Thanks so much! :)
