### ISSUE TITLE
PHPMailer - SMTP in 1&1 hosting problem

### ISSUE THREAD

**Issue by jg-user** [PHPMailer/PHPMailer#910]
Hello dear GitHub members,

I am currently having the hosting with 1&1, and pretending to send emails with gmail.
I was using (in my local host) the gmail example with phpmailer (smtp), which works fine.
Once i uploaded to the server (1&1 hosting), i have been told that they do not allow to send email with smtp, they only allow the mail() function.

So, my question is:
Should I only think of using the example "mail.phps" of phpmailer? (I have read some people tried $mail->isSendMail() )?
But, in that case, I have read that without smtp, my emails can be considered spam, and in addition, is it a secure way to send emails?

Thank you in advance

**Comment by Synchro** [comment]
`isSendMail()` is something else you probably don't need. If you use `isMail()` (PHPMailer's default) it will send using the standard PHP `mail()` function. When you send this way, it submits your message to your local mail server, which will be configured to relay through hostgator's own mail servers. This is secure enough for most purposes. There's no particular reason it should be considered spam, but make sure you list hostgator's mail servers in your SPF record. Send your self a message through that path, then inspect the message headers to confirm the servers that are involved. It's likely that hostgator has an SPF record you can `include` - check their support docs.
