### ISSUE TITLE
Appears to be an issue sending email to Yahoo

### ISSUE THREAD

**Issue by KTrentLR** [PHPMailer/PHPMailer#913]
When sending emails to @gmail account, it only takes a few seconds for the email to arrive.  However, when sending to @sbcglobal (yahoo) or an address like "llwwguard-test@yahoo.com" they either never arrive or it takes over 30 minutes to arrive.  What could be causing this?

This is a single email being sent to welcome a new user, this is not bulk email.  Also I checked my junk folders and it's not in there.  It seems like any email send to an address with a hyphen it in, never shows up.

The result every time is TRUE

I'm using the most current version with PHPMailerAutoload.php

(note I redacted information below with asterisks)

function sendMail($sub,$msg,$rAddress){
	  //PHP Mail Version (default)
	  $mail=new PHPMailer();
	  $mail->IsSMTP();
	  $mail->Host = "mail.******.com";
	  $mail->Port=25;
	  $mail->SMTPAuth=true; 
	  $mail->Password="********";
	  $mail->Username="donotreply@*******.com";
	  $mail->FromName="C*****-C******";
	  $mail->From="DoNotReply@********.com";
	  $mail->AddAddress($rAddress, '');
	  $mail->Subject=$sub;
	  $mail->Body=$msg;
	  $result = $mail->Send();
	  return $result;
}

**Comment by bobby5892** [comment]
Has nothing to do with php mailer.

https://help.yahoo.com/kb/postmaster/complaint-feedback-loop-program-sln3438.html?impressions=true

You need to make sure your sending domain is properly configured on your server. You also need to setup the yahoo feedback loop to get the "bounce" report, on why they rejected your mail.

Things can be more than this list but good starts.
Invalid SPF 
Invalid MX Record on Sender Domain
Residential IP of Sending Server
Message contains bad image to text ratio
Message contains links from domains reported as spam
Message has a spam score above 5.0
etc etc

**Comment by Synchro** [comment]
Indeed - Yahoo is prone to delaying mail for completely arbitrary reasons. If you check your mail server logs, you'll probably find them full of 421 deferral entries. Gmail is very fast.
