### ISSUE TITLE
PhpMailer can't connect but telnet connects fine

### ISSUE THREAD

**Issue by statbat** [PHPMailer/PHPMailer#916]
Hello All,

I am really struggling here. Any help will be appreciated.
I just dont know what can be wrong.

I am using phpmailer and I am getting this error:
**SMTP ERROR: Failed to connect to server: Connection timed out (110) SMTP connect() failed.**

But if I do a telnet it is working fine:
```
# telnet smtp.gmail.com 587
Trying 74.125.206.108...
Connected to smtp.gmail.com.
Escape character is '^]'.
220 smtp.gmail.com ESMTP z6sm49667653wjt.24 - gsmtp
```

So we can say that it is not a firewall issue on the server.
I dont know what else can be blocking it.

Please help.

**Comment by Synchro** [comment]
OK, so how about enabling low-level debug output with `SMTPDebug = 4` - it may be hanging up at some later point in the conversation.

**Comment by statbat** [comment]
Sadly SMTPDebug is already set to 4

**Comment by Synchro** [comment]
It could be blocked within PHP, or by SELinux / AppArmor etc.

**Comment by statbat** [comment]
That is my guess also. That can be only thing if command line is working. Is there a way to check this in server? Where can i see if it is blocked ?

It was working for year and then stopped.

**Comment by Synchro** [comment]
Look in your syslog, or logs for SELinux etc - any contraventions of policy should be logged. Also inspect the configs for those protections.
