### ISSUE TITLE
A critical vulnerability

### ISSUE THREAD

**Issue by shamuel22** [PHPMailer/PHPMailer#920]
Please read: http://thehackernews.com/2016/12/phpmailer-security.html

**Comment by vikas5914** [comment]
it was fixed in 5.2.18.

**Comment by Synchro** [comment]
Strangely enough, we know about this.

**Comment by matt-** [comment]
https://github.com/PHPMailer/PHPMailer/commit/4835657cd639fbd09afd33307cef164edf807cdc
