### ISSUE TITLE
PHPMailer issue mailing over SSL

### ISSUE THREAD

**Issue by fastslack** [PHPMailer/PHPMailer#921]
I tried to send emails over SSL server and receive this error:

```
<b>Warning</b>:  stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in <b>/var/www/web/libraries/vendor/phpmailer/phpmailer/class.smtp.php</b> on line <b>355</b><br />
```
### Summary of Changes

If options is not sent, append to options array needed ssl values.

### Testing Instructions

Try to send an email over SSL.

**Comment by Synchro** [comment]
Please read [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting).
