### ISSUE TITLE
PHP Version support

### ISSUE THREAD

**Issue by reedy** [PHPMailer/PHPMailer#928]
Following on from #927 

In composer.json you're saying you support PHP >= 5.0.0..

It'd be worth bumping the php version you support in composer.json (probably 5.3 is a minimum, but 5.5 wouldn't necessarily be too bad)

**Comment by reedy** [comment]
And you're using traits in https://github.com/PHPMailer/PHPMailer/blob/master/get_oauth_token.php

**Comment by Synchro** [comment]
Those features are only used in code that is not supported on 5.0, principally oauth support. To see where it's going, look in the 6.0 branch, which raises the language minimum version to 5.5.

**Comment by reedy** [comment]
That's not really an excuse for the 5.2 releases of your code to not be compatible with the PHP version you're claiming to support

Sure, it may not be used, but how does an upstream linter know that?

https://github.com/PHPMailer/PHPMailer/tree/1d51856b76c06fc687fcd9180efa7a0bed0d761e

**Comment by glensc** [comment]
it's probably meant that php5.0 support is for code paths that used to exist when php5.0 was mainstream. the new features are not supported for php5.0, like oauth.

**Comment by Synchro** [comment]
I think it's pretty clear - official support is for 5.0, some specific new features require later versions. Switching major language requirement in a patch version bump isn't something any package should do. That a linter has problems with that isn't something I'm concerned about. This will go away in 6.0 anyway, where BC breaks are allowed, and there will be a single minimum language version (5.5) for everything.
