### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by isvaljek** [PHPMailer/PHPMailer#932]
Is this script backwards compatible? Like replacing the one in a WordPress 3.1 install with the newest release here?
Or WordPress 4.1?

**Comment by Synchro** [comment]
Code should not need any significant changes - the only sort-of breaking change was in how the classes were loaded - if you're already using the autoloader or composer it won't be a problem. Wordpress will be issuing an update shortly, and it wouldn't surprise me if they backport it to earlier releases. I'd advise running the latest version of Wordpress anyway.
