### ISSUE TITLE
Username in header (Authenticated sender)

### ISSUE THREAD

**Issue by uligh** [PHPMailer/PHPMailer#935]
The header of sent mails shows too much information about my mail account.

... (**[my server]** [my IP address])
(using TLSv1.2 with cipher ECDHE-RSA-AES256-****** (256/256 bits))
(No client certificate requested)
(Authenticated sender: **[my user name]**)
by mail2.**[my server]** (mail2.**[my server]**) with ESMTPSA ...

So it is easy to find my provider via the internal server name. With that information it is easy to find the login page (FAQ) for the admin panel of that server. The user name is also in the header.
And if someone reads the FAQ of my provider he finds out that the username is just a modification of my client number ...

So in 60 sec he has
- my real name (via Whois)
- my client number
- my user name
- my login server
- my admin panel login page

**Comment by Synchro** [comment]
Yep, that's email.

**Comment by mshannaq** [comment]
tthese information attached to the email header to track any abuse.
