### ISSUE TITLE
Trouble with PHP 5.6.12

### ISSUE THREAD

**Issue by lbozza** [PHPMailer/PHPMailer#936]
Hello I'm having some trouble with PHPMailer using PHP version 5.6.12 , when trying to validate an email address on te validateAddress functiong using preg_match it returns false everytime, when using php7 it works just fine, is the latest version of PHPMailer compatible with this PHP version i'm using? Thanks

**Comment by Synchro** [comment]
First of all, upgrade to latest (currently 5.2.21) right now. There has just been an important security update. You can see the current version on the front page of this repo.

To help diagnose this, you need to provide an example of an address that's producing this behaviour, along with your code showing how you're calling it.

**Comment by lbozza** [comment]
Hello, already updated to the latest, so at one point in my code I use PHPMailer to validate the email address from my customer :
```

function osc_validate_email_address($email_address)
{
    require_once(realpath(dirname(__FILE__) . '/../../') . '/includes/ext/phpmailer/class.phpmailer.php');

    return PHPMailer::validateAddress($email_address);
}
```

the email in question is "lbozza@uolinc.com" for example.. 

If i choose to comment this validation and keep going on my application flow when I try to send an email 

```
function smtpSend() {
      $mail = new PHPMailer(true);
      
      $mail->IsSMTP();
      $mail->SMTPAuth = false;
      
      $mail->Host = SMTP_HOST;
      
      $mail->Subject = $this->_subject;
      $mail->setFrom($this->_from['email_address'], $this->_from['name']);
      
      $mail->CharSet = $this->_charset;
      $mail->Encoding = $this->_content_transfer_encoding;
      
      if (empty($this->_body_plain)) {
        $mail->msgHTML($this->_body_html);
      } else {
        $mail->AltBody = $this->_body_plain;
      }
      
      foreach ($this->_headers as $key => $value) {
        $mail->addCustomHeader($key, $value);
      }
      
      if (!empty($this->_to)) {
        foreach($this->_to as $to) {
          $mail->addAddress($to['email_address'], $to['name']);
        }
      }
      
      if (!empty($this->_cc)) {
        foreach($this->_cc as $cc) {
          $mail->addCC($cc['email_address'], $cc['name']);
        }
      }
      
      if (!empty($this->_bcc)) {
        foreach($this->_bcc as $bcc) {
          $mail->addBCC($bcc['email_address'], $bcc['name']);
        }
      }
      
      if (!empty($this->_attachments)) {
        foreach($this->_attachments as $attachment) {
          $mail->addAttachment($attachment['file'], $attachment['filename']);
        }
      }
      
      if (!empty($this->_images)) {
        foreach($this->_images as $image) {
          $mail->addEmbeddedImage($image['file'], $image['filename']);
        }
      }

      try {
        $mail->send();
      } catch (Exception $e) {
        $this->error = $e;
        return false;
      }
      
      return true;
    }
```

I stumble with an error while trying to set a recipient on setFrom function, because it calls the validateAddress function, and then I stumble on this function returning false on case 'pcre8' , again on PHP5.6.12 , If I try to use PHP7 it works just fine, I tried commenting some validations on setFrom function like the validateAddress, has8bitChars and idnSupported, then it works, but on this version of PHP i encounter trouble on these 3 functions .. could you try using this version with PHPMailer ?

Thanks

**Comment by Synchro** [comment]
You may be running into a problem with certain PCRE libraries that was never resolved because it wasn't reliably reproducible. To work around that, you can set PHPMailer to use a specific validator, so in your validation function:

```php
function osc_validate_email_address($email_address)
{
    require_once(realpath(dirname(__FILE__) . '/../../') . '/includes/ext/phpmailer/class.phpmailer.php');
    PHPMailer::$validator = 'php';
    return PHPMailer::validateAddress($email_address);
}
```

This will make it use the built-in `filter_var` validator for everything. You may need to set the same class property in your `smtpSend` function.

**Comment by lbozza** [comment]
Hello, worked like a charm, thank you very much for your assistance! Does using filter_var over pcre8 to validate email addresses affects badly my application? Thanks

**Comment by Synchro** [comment]
The fiter_var validator is not as permissive as the pcre8 one, and there are some valid RFC822 addresses that it does not allow. However, it's still pretty good as far as validations go (it was originally written by the same author), and the things that it doesn't allow are more likely to be errors than real weird addresses, plus it will become the default in PHPMailer 6, so I don't think you'll have any trouble with it.
