### ISSUE TITLE
using emoticons in subject

### ISSUE THREAD

**Issue by dellaemme** [PHPMailer/PHPMailer#943]
I didn't find how to use the utf8mb4 charset for sending in email text or subject emoticons.... This class always put ? at emoticons place.

**Comment by glensc** [comment]
you need to provide code snippet how you use and raw output of the rendered email. and information what client you used to validate the output.

also utf8mb4 is mysql specific problem. there's no limit of unicode planes in email (it's just stream of bytes).

**Comment by dellaemme** [comment]
sorry, I solved working on mysql connection, i set
```
SET NAMES utf8mb4
mysql_set_charset('utf8mb4'); 
```
and the subject now is correct with emoji.

**Comment by glensc** [comment]
close the ticket then
