### ISSUE TITLE
CRLF in headers from Windows server

### ISSUE THREAD

**Issue by gunleik** [PHPMailer/PHPMailer#947]
From a WP site on a Windows server we experience that some of the mail headers are missing proper line endings. E.g. gmail will complain that the mail is not RFC compliant.

Heres an excerpt from an email that I sent to my own server. As you can see from "X-PHP-Originating-Script" and outwards everything is in one line:

> Subject: My subject
To: xxx@xxx.xxx
X-PHP-Originating-Script: 0:class-phpmailer.php Date: Thu, 15 Dec 2016 15:05:19 +0000 From: Andreas Test <yyy@yyy.yyy> Reply-To: yyy@yyy.yyy Message-ID: <225ec34b1693b928aaa7275376c2c7a0@lt.netsense.no> X-Mailer: PHPMailer 5.2.17 (https://github.com/PHPMailer/PHPMailer) X-WPCF7-Content-Type: text/plain MIME-Version: 1.0 Content-Type: text/plain; charset=UTF-8

I would expect:

> Subject: My subject
To: xxx@xxx.xxx
X-PHP-Originating-Script: 0:class-phpmailer.php 
Date: Thu, 15 Dec 2016 15:05:19 +0000 
From: Andreas Test <yyy@yyy.yyy> 
Reply-To: yyy@yyy.yyy 
Message-ID: <225ec34b1693b928aaa7275376c2c7a0@lt.netsense.no> 
X-Mailer: PHPMailer 5.2.17 (https://github.com/PHPMailer/PHPMailer) 
X-WPCF7-Content-Type: text/plain 
MIME-Version: 1.0 Content-Type: text/plain; charset=UTF-8

The message above is from 5.2.17, but I don't see any similar issue reported in the changelog.

I'm not sure if the error can be blamed on PHPMailer or perhaps it is how WP calls it - or lets just blame it on Microsoft ;-)
Anyhow my quick fix was to do a preg_replace in one of the last instances where the header is handled by PHPMailer:

########################################################
    private function mailPassthru($to, $subject, $body, $header, $params)
    {
        //Check overloading of mail function to avoid double-encoding
        if (ini_get('mbstring.func_overload') & 1) {
            $subject = $this->secureHeader($subject);
        } else {
            $subject = $this->encodeHeader($this->secureHeader($subject));
        }
########## My change here #################################
		$header = preg_replace("/\r\n/s", "\n", $header);
		$header = preg_replace("/\n/s", "\r\n", $header);
########################################################

Is this totally wrong? Is there some obvious other solution to this?

**Comment by Synchro** [comment]
For various long historical reasons, PHPMailer is a bit inconsistent in how it handles line breaks... Whether it looks right to you depends on what you're viewing it in, though it's particularly likely to look like that on Windows. Generally you can fix this by changing the default line break format like this:

    $mail->LE = "\r\n";

This affects quite a few things that are difficult to fix without breaking things, so in PHPMailer 6.0 this will be the default, and will not be alterable, because it should not allow you to use anything else.

**Comment by gunleik** [comment]
It's not if I think it looks right or not - gmail sent an NDR saying the mail was not RFC compliant because of missing header fields.

I believe I did try to change the `public $LE = "\n";` to \r\n without it working (though it is a couple of weeks since I tested it, so I could remember wrong).

But what you say is that it is in Wordpress that I could add `$phpmailer->LE = "\r\n";` in he script that sends mail?
Or I should wait for PHPMailer 6 where this will be default?

**Comment by Synchro** [comment]
How it looks is also how it may look to the server. Some are more forgiving than others, and generally gmail doesn't have a problem. If you do a hex dump of the exact data received, is it missing line breaks altogether, or are they present but of the wrong type for Windows?

**Comment by gunleik** [comment]
If looking at the header with problem: "X-PHP-Originating-Script: 0:class-phpmailer.php Date: Thu, 15 Dec 2016 12:36:39 +0000 From: "...

On a Linux server with good old qmail there is no line break before Date and From at all. Just a space (HEX 20). Possibly the MTA stripped out the line breaks as it don't expect a header field starting with space as seen below.

On an Exchange server (header read from Outlook) there is line breaks: CR+LF and then a space (HEX: 0d 0a 20) before Date and From. So the space infront of the Date and From would probably be causing the problem.

In the NDR from google it looks similar to the Exchange header, though only with LF at the line break and then space before Date and From (added quotes on each line for readabillity):

"X-PHP-Originating-Script: 0:class-phpmailer.php[LF]"
" Date: Thu, 15 Dec 2016 12:33:29 +0000[LF]"
" From: xxxx...[LF]"
 ^ space infront of header field

Excerpt from the google NDR error:
A message that you sent could not be delivered to all of its recipients.
The following address(es) failed:
  xxx@gmail.com
    SMTP error from remote mail server after end of data:
    host gmail-smtp-in.l.google.com [108.177.14.27]:
    550-5.7.1 [79.xxx.xx.2      11] Our system has detected that this message is not
    550-5.7.1 RFC 5322 compliant:
    550-5.7.1 'From' header is missing.

**Comment by Synchro** [comment]
That `X-PHP-Originating-Script` header is not added by PHPMailer - where is that coming from? It must be sender-side as the receiver doesn't have that info. PHPMailer doesn't put spaces before headers, so I suspect that whatever  you have that's inserting headers is messing it up.

**Comment by Synchro** [comment]
If you do this:

```php
$mail->preSend();
$msg = $mail->getSentMIMEMessage();
```
$msg will contain an exact copy of what is sent to the mail server - if what you're receiving is not exactly the same, something is altering it after submission.

**Comment by gunleik** [comment]
I see that the "X-PHP-Originating-Script" is added by the PHP installation.
The "from" and "reply-to" i would guess is added by a contact form in Wordpress.
There is also a " X-Mailer: PHPMailer 5.2.17" - will upgrade very soon ;-)
I guess this field is added by PHPMailer? This field also have a space infront of it.

So if fields from both the contact form and from PHPMailer have spaces infront of it - then it must be related to how PHP handles the line breaks, right?

I will test the getSentMIMEMessage and save it to a file to compare with what i receive.

**Comment by Synchro** [comment]
I don't know of anything that would reasonably transform line breaks into spaces. There is a way that email headers can be folded onto multiple lines and the continuation lines start with a space, but never the headers themselves. From and reply-to should be created by PHPMailer, with values provided by the plugin.

**Comment by Synchro** [comment]
It turns out that this is a bug in Windows versions of PHP, and it is fixed in PHP 7.0.17 and 7.1.3, when they are released. There has been detailed discussion of this in #953, including numbers workarounds, so I will close this ticket in favour of what's been going on in there.
