### ISSUE TITLE
disabled escapeshell functions cause warning

### ISSUE THREAD

**Issue by zdenekgebauer** [PHPMailer/PHPMailer#948]
Hi,
after upgrade from 5.2.14 to 5.2.21 I get warning "escapeshellcmd() has been disabled for security reasons" in class.phpmailer.php, line 1442.  
Functions `escapeshellarg,escapeshellcmd` are disabled by `disable_functions` setting and I cannot change it. Maybe method `isShellSafe` should not call `escapeshell*` functions if they are not allowed?

**Comment by Synchro** [comment]
That's curious. In many (most?) circumstances, *not* calling `escapeshell*` would be a security problem. I recommend you switch to using SMTP to localhost - it's both safer and faster.
