### ISSUE TITLE
SMTP connect() failed with TLS and PHP 7

### ISSUE THREAD

**Issue by ojfrs** [PHPMailer/PHPMailer#951]
I try to sent email with PHPMailer and Gandi SMTP Server : relay.mail.gandi.net
I use 587 port and tls secure connection.
I'm on MAMP Pro and with PHP 5.4.45, it's working good, but when i switch to php 7.0.12 i encounter this error message with debug option 4.

```
2017-01-04 16:09:46	SMTP ERROR: QUIT command failed:
2017-01-04 16:09:46	Connection: closed
2017-01-04 16:09:46	SMTP connect() failed.
```

Have you got an idea of the problem ?

Thanks

**Comment by Synchro** [comment]
Please post the bit leading up to that. The usual problem when upgrading from anything earlier than PHP 5.6 is TLS issues - see the troubleshooting guide in the wiki for more.

**Comment by ojfrs** [comment]
I use in my domain DNS zone a CNAME for smtprecord.
If in my script i use the "final" name record and it works good.
In my case, i got this record : smtp CNAME relay.mail.gandi.net.
And relay.mail.gandi.net is CNAME record for mail.gandi.net.

So in my script, it doesn't work with stmp.mydomain.com, it doesn't work with relay.mail.gandi.net, but it works with mail.gandi.net

**Comment by younas-bangash** [comment]
can you explain what is the "final" name record  i have also facing issue in while sending mail using smtp

**Comment by Synchro** [comment]
Please don't hijack other tickets, especially closed ones; make a new one. Reference this one if it's really relevant. You also need to explain clearly what your issue is.
