### ISSUE TITLE
remove old repo

### ISSUE THREAD

**Issue by michield** [PHPMailer/PHPMailer#952]
Hi @Synchro 

Would you mind removing https://github.com/PHPMailer/phplist ?

It's a very old fork of a no longer existing repository. The latest correct repo to clone is https://github.com/phpList/phplist3

Thanks

Michiel

**Comment by Synchro** [comment]
Sure, I think that was made to create a PR or something.

**Comment by Synchro** [comment]
It's gone.

**Comment by michield** [comment]
many thanks
