### ISSUE TITLE
PHPMailer License

### ISSUE THREAD

**Issue by AhmedGsm** [PHPMailer/PHPMailer#954]
Hello, I have some questions about PHPMailer library that i downloaded from GitHUB.
Can I use that library in my PHP scripts and sell to many clients in marketplaces?
Is there a premium library of PHPMailer?
If no, where can I find that library to integrate it in my PHP scripts?

**Comment by Synchro** [comment]
Yes you can use it, yes you can redistribute it, no there isn't a premium version, and no you didn't have to ask this in three places at once. It uses the LGPL licence, so look up what that means. Contributions are always welcome though!
