### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by ashrafkm** [PHPMailer/PHPMailer#956]
I use the latest phpmailer but still error is coming

**Message could not be sent.Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting** 

my php code is...

require 'phpmailer/PHPMailerAutoload.php';

$mail = new PHPMailer;

//$mail->SMTPDebug = 1;                               // Enable verbose debug output

$mail->isSMTP();  

                                  // Set mailer to use SMTP
$mail->Host = "smtp.gmail.com";  // Specify main and backup SMTP servers
$mail->SMTPAuth = true;                               // Enable SMTP authentication
$mail->Username = "asraf.mlore@gmail.com";                 // SMTP username
$mail->Password = "**********";                           // SMTP password
$mail->SMTPSecure = "tls";                            // Enable TLS encryption, `ssl` also accepted
$mail->Port = 587;                                    // TCP port to connect to

$mail->setFrom('from@example.com', 'Mailer');
$mail->addAddress('ashh313@yahoo.com', 'ashraf');     // Add a recipient

**Comment by Synchro** [comment]
Did you read what the guide said and do what it suggested?

**Comment by IDavidCP** [comment]
Set this:
$mail->SMTPDebug = 2;

So you can check what is wrong

**Comment by ashrafkm** [comment]
Thank you for the suggestions.
I found the solution.. the problem was with gmail account.. less secure apps permission was turned off. after I made it on, it worked properly.
