### ISSUE TITLE
Force to use specific cipher for TLS

### ISSUE THREAD

**Issue by IPTRACE** [PHPMailer/PHPMailer#957]
Hello!

Is it possible to force to use specific cipher?
PHPMailer 5.2.20 uses TLSv1.2 with cipher ECDHE-RSA-**AES128-GCM-SHA256** but I'd like to change to TLSv1.2 with cipher ECDHE-RSA-**AES256-GCM-SHA384**.

Thank you for your help.

**Comment by Synchro** [comment]
PHPMailer doesn't specify any particular cipher - it just uses PHP's OpenSSL defaults. You should be able to request a specific cipher using the ssloptions property (see the troubleshooting guide), however bear in mind that any well-configured TLS server should not permit clients to choose ciphers anyway, so it may not help.

**Comment by IPTRACE** [comment]
Thanks. I've just disabled AES128 and PHPMailer uses cipher as I would expect.

postfix config entry:
smtpd_tls_mandatory_exclude_ciphers = aNULL, eNULL, DES, 3DES, MD5, DES+MD5, RC4, AES128

**Comment by Synchro** [comment]
One question: why would you want to disable AES128? It's [not significantly less secure than AES256](https://www.reddit.com/r/crypto/comments/39211m/is_really_aes256_less_secure_than_aes128/), and in some scenarios may actually be better - there are [demonstrable attacks](http://eprint.iacr.org/2009/374) against AES256 that do not apply to AES128.

**Comment by IPTRACE** [comment]
I didn’t know that. I thought AES256 is better than AES128.
I’ll study about weakness of AES256.
