### ISSUE TITLE
Authtype order in class-smtp.php

### ISSUE THREAD

**Issue by bcmarius** [PHPMailer/PHPMailer#964]
i had to modify line 417 in class-smtp.php so I can use authtype LOGIN
Line 417 modified 
foreach (array('LOGIN', 'PLAIN', 'CRAM-MD5') as $method) {
original was
foreach (array('CRAM-MD5', 'PLAIN', 'LOGIN') as $method) {
and it always wanted to authenticate CRAM-MD5 witch my server does not support

**Comment by Synchro** [comment]
Look at the code around it (the next line!) - it only attempts to use auth mechanisms that your server supports. Also, you can override it with the `AuthType` property in the PHPMailer class, so no, there is no need to alter the source. the mechanisms are in order of strength: `CRAM-MD5` is more secure than `PLAIN` and `LOGIN`.

**Comment by bcmarius** [comment]
In previous version it was working
now it seems that is default on CRAM-MD5
it does not try PLAIN or LOGIN

**Comment by Synchro** [comment]
Set `$mail->SMTPDebug = 2` and post the transcript.
