### ISSUE TITLE
escapeshellcmd() has been disabled for security reasons in class.phpmailer.php on line 1442

### ISSUE THREAD

**Issue by surjithctly** [PHPMailer/PHPMailer#966]
Hello,

Due to the recent security fix, I have updated the library to latest stable version. I have also changed the FROM address to normal email instead of $_POST. But the console shows an error:

`escapeshellcmd() has been disabled for security reasons in class.phpmailer.php on line 1442`

However, The email was successfully sent! So now I'm confused. 

Please help.

~Surjith

**Comment by Synchro** [comment]
This is down to your local PHP config, not PHPMailer. [Functions can be disabled for any reason](http://php.net/manual/en/ini.core.php#ini.disable-functions), security being a common one. `escapeshellcmd` has a number of serious potential issues, so it looks like it's been turned off for you, causing this error. You can work around this easily by doing what PHPMailer recommends anyway: sending using SMTP to localhost, not the default `mail()` transport.

**Comment by sunil-tamang** [comment]
how to avoid this message   
Warning: escapeshellcmd() has been disabled for security reasons in /storage/ssd2/771/4867771/public_html/PHPMailer/PHPMailer.php on line 1584

**Comment by Synchro** [comment]
Read the thread, do what I said, since it addresses exactly the problem you describe. Simply add:

    $mail->isSMTP();

and PHPMailer will send via SMTP to localhost, which does not involve calling `escapeshellcmd`.

**Comment by sunil-tamang** [comment]
Fatal error: Uncaught Error: Class 'PHPMailer\PHPMailer\SMTP' not found in

**Comment by Synchro** [comment]
You're not using composer and/or you didn't read the readme where it tells you how to load the classes.

**Comment by sunil-tamang** [comment]
please help solving this....

SMTP ERROR: Password command failed:
SMTP Error: Could not authenticate. 




                      $mail->isSMTP(); 
                	 	$mail->SMTPDebug = 2;  
                	 	$mail->SMTPAuth = true;                             
		                $mail->SMTPSecure = 'ssl';                                 
					    $mail->Host = 'smtp.gmail.com';
						$mail->Port = 465;      
					      
					                              
					    $mail->Username = 'account@gmail.com';                 
					    $mail->Password = '';                           
					    $mail->setFrom('@gmail.com');	
				     	$mail->addAddress($email, $name);
		                $mail->Subject = "Please verify email!";
		                $mail->isHTML(true); 
		                $mail->Body = " Please click on the link below:<br><br> ";
          
              			$mail->send();
		     
		      				 $msg = "You have been registered! Please verify your email!";

              			  }catch (Exception $e) {
					    		 $msg = "Something wrong happened! Please try again!";

					 }

**Comment by Synchro** [comment]
Read the rest of the debug output, then read the troubleshooting guide.

**Comment by jameelsid** [comment]
it working in local host 
when i try to wok in my domain 
it showing  this error 

Warning: escapeshellcmd() has been disabled for security reasons

pls help me with this\
code

<?php 
$email='YYYY@gmail.com';
require 'mailer/PHPMailerAutoload.php';
$mail = new PHPMailer;

$mail->Host ='smtp.gmail.com';
$mail->Port =587;
$mail->SMTPAuth=true;
$mail->SMTPSecure='tls';

$mail->Username='YYYY@gmail.com';
$mail->Password="XXXXXXXX";

$mail->setFrom('YYYY@gmail.com','YYYYY');
$mail->addAddress($email);
$mail->addReplyTo('YYYY@gmail.com');

$mail->isHTML(true);
$mail->Subject='XXXXX';
$mail->Body="hai";
if(!$mail->send())
{
	echo"no";
}
else
{
	echo"yes";
}

?>

**Comment by Synchro** [comment]
Call `$mail->isSMTP();` and it will not need to use `escapeshellcmd`.

**Comment by jameelsid** [comment]
i used that ,mail is not sending iam using in my domain

**Comment by jameelsid** [comment]
when i used that it show no error bt mail is not sending

**Comment by Synchro** [comment]
So go read the docs, figure out why. There is noting I can say here that is not in the guide.

**Comment by jameelsid** [comment]
where i find the docs???

**Comment by Synchro** [comment]
Would you like me to move your mouse for you too? You could perhaps start from [the project's front page](https://github.com/PHPMailer/PHPMailer).

**Comment by pajczur** [comment]
> Read the thread, do what I said, since it addresses exactly the problem you describe. Simply add:
> 
> ```
> $mail->isSMTP();
> ```

Hello please help me. I am trying to find where to add that line from three days. Where to add that `$mail->isSMTP();` ???
I have no idea. But my website doesn't work properly.

**Comment by Synchro** [comment]
Along with all your other calls to methods on your PHPMailer instance? So if you're doing:

    $mail->Subject = "hello";
    $mail->Body = "My message";

just add it next to them, so long as it's before your call to `send()`.

**Comment by pajczur** [comment]
> Along with all your other calls to methods on your PHPMailer instance? So if you're doing:
> 
> ```
> $mail->Subject = "hello";
> $mail->Body = "My message";
> ```
> 
> just add it next to them, so long as it's before your call to `send()`.

Great thanks for your answer. But I have no idea where such lines could be find. I use only plugins and don't know php. I can search content of whole my `public_html` to find `send()`. And then in each of such place should I use add that`$mail->isSMTP();` ???

**Comment by Synchro** [comment]
No, don't touch that. You should never edit your library files, which is where that code is from. Search amongst your files for `new PHPMailer`; that will probably point you in the right direction. If you're using a site template or something (eg. WordPress), you should refer to their support services.

**Comment by pajczur** [comment]
> No, don't touch that. You should never edit your library files, which is where that code is from. Search amongst your files for `new PHPMailer`; that will probably point you in the right direction. If you're using a site template or something (eg. WordPress), or a plugin, you should refer to their support services.

OK, great for your support. So I will try to find it. I think your advices will help me. Thanks.

**Comment by pajczur** [comment]
> No, don't touch that. You should never edit your library files, which is where that code is from. Search amongst your files for `new PHPMailer`; that will probably point you in the right direction. If you're using a site template or something (eg. WordPress), or a plugin, you should refer to their support services.

OK it looks like I found the best solution for me. I've just installed plugin Easy WP SMTP and configure the smtp settings. Now everything works fine. Thanks again for your support

**Comment by DenisChenu** [comment]
@Synchro did you accept pull request to fix this issue ?

I mean : just a clean solution to not send PHP Warning

**Comment by Synchro** [comment]
No, it's correct that PHPMailer should trigger a warning. Not having `escapeshellcommand` means that you cannot safely use shell commands from PHP, so it should be discouraged or prevented at every opportunity. Suppressing warnings is counterproductive, especially when there is a perfectly good workaround which is both faster and safer, as described earlier in this thread.

**Comment by Shnoulle** [comment]
But warning is shown only on some condition and break all other system.
Then PHPMailer act differently according to PHP settings, if you think it's an issue and it must be corrected : maybe throw an exception or add an error, and don't send.

Currently : 

- `error_reporting(E_ALL);`: throw error, mail is not sent
- `error_reporting(0);` no error, mail are sent.

I mean : both condition must have the same result for message sent or not :).

> Not having `escapeshellcommand` means that you cannot safely use shell commands from PHP, so it should be discouraged or prevented at every opportunity. 

Then : disable email sent : maybe trigger_error in [preSend](https://github.com/PHPMailer/PHPMailer/blob/a127e25118a653a60742f909416b5d8fe399dc30/src/PHPMailer.php#L1524) function ?

**Comment by Synchro** [comment]
Hm. That's a fair point. It's annoying that trying to call a disabled function isn't a fatal error... I would propose something like this in `preSend`:

```php
        if (!function_exists('escapeshellarg') && in_array($this->Mailer, ['mail', 'sendmail', 'qmail'])) {
            trigger_error(
                'The escapeshellarg function is disabled, making it impossible to send using' .
                    ' mail, sendmail, or qmail transports safely; switch to SMTP instead.',
                E_USER_ERROR
            );
        }
```

That would be clear and effective, however, I also suspect this would break many installations, so it would have to wait for a major release version.

**Comment by Shnoulle** [comment]
:+1: 

Current situation with error_reporting(0); and escapeshellarg disable : `escapeshellcmd($string) !== $string` return false, then `isShellSafe` return false

To have an API compatible version : replace `escapeshellcmd($string) !== $string` by `!function_exists('escapeshellarg')` then return false for safe shell :).

This disable the -f(sender) in sendmail shell parameters. Seems OK too for security, no ?

**Comment by Synchro** [comment]
That is a good idea, so I have implemented that. Thanks for the suggestion, @Shnoulle.

**Comment by Shnoulle** [comment]
> That is a good idea, so I have implemented that. Thanks for the suggestion, @Shnoulle.

No, thanks to you for all you work !
