### ISSUE TITLE
Sending mail without body

### ISSUE THREAD

**Issue by IDavidCP** [PHPMailer/PHPMailer#967]
Everything runs ok, no error message is shown. When I check my inbox the mail is missing the body, the rest is fine.

    $mail = new PHPMailer();
    $mail->IsHTML(true);
    $mail->isSMTP();
    $mail->SMTDebug = 2;
    $mail->Debugoutput = 'html';
    $mail->Host = 'server188.web-hosting.com';
    $mail->SMTPAuth = true;
    $mail->Username = 'user';
    $mail->Password = 'password';
    
    $mail->setFrom('example@mail.com', 'Example');
    $mail->Subject = $subject;
    $mail->addReplyTo('example@mail.com', 'Example');
    
    $mail->AddAddress('example@mail.com');
    
    $mail->Body    = 'This is the HTML message body <b>in bold!</b>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    if($mail->Send()){
        $output = json_encode(array('type'=>'message', 'text' => 'Thanks for your message'));
        die($output);
    }else{
        $output = json_encode(array('type'=>'error', 'text' => $mail->ErrorInfo));
        die($output);
    }

I tried to output the body before and after sending the mail to make sure that the string is not empty.

**Comment by Synchro** [comment]
You've enabled debug output - you should be able to see the message body in the SMTP transcript. Does it appear?

This script is incomplete - there's. I `send` call.

**Comment by IDavidCP** [comment]
I didn't copy the $mail->Send() part because as I said, I'm getting the mail in my inbox.

if($mail->Send()){
        $output = json_encode(array('type'=>'message', 'text' => 'Thanks for your message'));
        die($output);
    }else{
        $output = json_encode(array('type'=>'error', 'text' => $mail->ErrorInfo));
        die($output);
    }

**Comment by IDavidCP** [comment]
Problem solved, something related to the encode. 
Thanks for your time!
