### ISSUE TITLE
Solution to push sending mail process to queue and send by background (like phplist)

### ISSUE THREAD

**Issue by xenofx** [PHPMailer/PHPMailer#971]
I want to push sending mail process to queue and worker in background will excute it , so what is solution ?

phplist support "one email body" to "multiple email". if I want this, it is no problem, because I can do with phplist commandline. phplist commandline can add new email or execute queue  to only email lists (no spesicif email).

So, how can I send spesific message to spesific email address with queue system? Because our bid script sending many email to users (eg "Your bid was passed by a higher bid.") , and our server limit is 100 email per hour.

**Comment by Synchro** [comment]
This isn't a PHPMailer concern - you need to find or design a queuing system yourself. There are many around - you might try beanstalkd, or many of the options [on packagist](https://packagist.org/search/?q=queue). I would recommend pushing your mail *parameters* (to, from etc) to the queue and then getting your sending job to build and send a message as each is processed - in contrast to building messages in advance.

**Comment by xenofx** [comment]
thank you for your reply.  it is seems good https://packagist.org/packages/selbil/mail-queue
