### ISSUE TITLE
Automatic email notifications of PHPMailer new releases

### ISSUE THREAD

**Issue by ridera** [PHPMailer/PHPMailer#973]
Is there a way to automatically receive email notifications for PHPMailer releases?
I stumbled on the recent security issue in Dec.  Otherwise, I wouldn't have known.
This would save having to check GitHub frequently.

**Comment by Synchro** [comment]
You may get notifications if you "watch' a project, though I'm not sure. There may be something via packagist. Other suggestions [here](http://stackoverflow.com/a/20840694/333340) sound good.
