### ISSUE TITLE
Newbie - Mailer was working fine but now won't send 'phone' and 'name' fields

### ISSUE THREAD

**Issue by mairtg** [PHPMailer/PHPMailer#976]
I hope someone can help with this. I'm very much a novice with all this. I used the phpmail on my for my site's contact form and it was working beautifully until recently. My contact form is set up for 'name' , 'phone' , 'email' and 'message' fields. Initially when I resieved message from site visitors I would receive as follows:

A message from your site visitor 
Email:	someone@whatever.com
Name:	Sender Name
Phone:	123456789

Message:
Body of message etc etc 

Suddenly I stopped receiving the 'name' and 'phone' fields. Looking at the phpmailer code it really doesn't look like there was ever anything set up for o be receiving these in the first place. I never changed anything and it was all working great until recently. I'm not very good with all this at all but I'd really appreciate any help anyone could offer.

What would I need to add to the mailer php and where would I need to add in order for this to work?

**Comment by Synchro** [comment]
PHPMailer isn't involved in what's *in* your message - it just takes whatever string you put into the `Body` property. Whatever is processing your form and passing the result to PHPMailer is what decides what goes into your message, but that isn't part of PHPMailer itself.

You might do something like this:

```php
$mail->Body = <<<EOT
A message from your site visitor
Email:	{$_POST['email']}
Name:	{$_POST['name']}
Phone:	{$_POST['phone']}
EOT;
```
(That `<<<EOT` part is a thing called a heredoc, useful for building large strings, look it up in the PHP manual)

**Comment by mairtg** [comment]
Thanks for your help. I appreciate that. I've tried the above. Would you reckon the problem is with js then?

**Comment by Synchro** [comment]
I have no idea. You know the names of your fields, your HTML, your JS, your PHP - just make sure they line up.

**Comment by mairtg** [comment]
Yep. And they do all line up. Like I said, it done everything I wanted it to do until recently. I didn't changed anything and now I only receive 2 of my 4 fields. Thanks anyway for your help. I'll go back to the drawing board.

**Comment by Synchro** [comment]
It might help if you posted your code. It's impossible to diagnose blind.

**Comment by mairtg** [comment]
Here's the php:

<?php

$recipients = 'mail@gmail.com, info@mydomain.com';
//$recipients = '#';

try {
    require './phpmailer/PHPMailerAutoload.php';

    preg_match_all("/([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)/", $recipients, $addresses, PREG_OFFSET_CAPTURE);

    if (!count($addresses[0])) {
        die('MF001');
    }

    if (preg_match('/^(127\.|192\.168\.)/', $_SERVER['REMOTE_ADDR'])) {
        die('MF002');
    }

    $template = file_get_contents('rd-mailform.tpl');

    if (isset($_POST['form-type'])) {
        switch ($_POST['form-type']){
            case 'contact':
                $subject = 'A message from your site visitor';
                break;
            case 'subscribe':
                $subject = 'Subscribe request';
                break;
            case 'order':
                $subject = 'Order request';
                break;
            default:
                $subject = 'A message from your site visitor';
                break;
        }
    }else{
        die('MF004');
    }

    if (isset($_POST['email'])) {
        $template = str_replace(
            ["", ""],
            ["Email:", $_POST['email']],
            $template);
    }else{
        die('MF003');
    }

    if (isset($_POST['message'])) {
        $template = str_replace(
            ["", ""],
            ["Message:", $_POST['message']],
            $template);
    }

    preg_match("/()(.|\n)+()/", $template, $tmp, PREG_OFFSET_CAPTURE);
    foreach ($_POST as $key => $value) {
        if ($key != "email" && $key != "message" && $key != "form-type" && !empty($value)){
            $info = str_replace(
                ["", "", ""],
                ["", ucfirst($key) . ':', $value],
                $tmp[0][0]);

            $template = str_replace("", $info, $template);
        }
    }

    $template = str_replace(
        ["", ""],
        [$subject, $_SERVER['SERVER_NAME']],
        $template);

    $mail = new PHPMailer();
    $mail->From = $_SERVER['SERVER_ADDR'];
    $mail->FromName = $_SERVER['SERVER_NAME'];

    foreach ($addresses[0] as $key => $value) {
        $mail->addAddress($value[0]);
    }

    $mail->CharSet = 'utf-8';
    $mail->Subject = $subject;
    $mail->MsgHTML($template);

    if (isset($_FILES['attachment'])) {
        foreach ($_FILES['attachment']['error'] as $key => $error) {
            if ($error == UPLOAD_ERR_OK) {
                $mail->AddAttachment($_FILES['attachment']['tmp_name'][$key], $_FILES['Attachment']['name'][$key]);
            }
        }
    }

    $mail->send();

    die('MF000');
} catch (phpmailerException $e) {
    die('MF254');
} catch (Exception $e) {
    die('MF255');
}

?>

**Comment by Synchro** [comment]
Could you format that so it's readable?

**Comment by mairtg** [comment]
Here's the file...

[rd-mailform.zip](https://github.com/PHPMailer/PHPMailer/files/733378/rd-mailform.zip)

**Comment by mairtg** [comment]
`<?php

$recipients = 'mail@gmail.com, info@mydomain.com';
//$recipients = '#';

try {
    require './phpmailer/PHPMailerAutoload.php';

    preg_match_all("/([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)/", $recipients, $addresses, PREG_OFFSET_CAPTURE);

    if (!count($addresses[0])) {
        die('MF001');
    }

    if (preg_match('/^(127\.|192\.168\.)/', $_SERVER['REMOTE_ADDR'])) {
        die('MF002');
    }

    $template = file_get_contents('rd-mailform.tpl');

    if (isset($_POST['form-type'])) {
        switch ($_POST['form-type']){
            case 'contact':
                $subject = 'A message from your site visitor';
                break;
            case 'subscribe':
                $subject = 'Subscribe request';
                break;
            case 'order':
                $subject = 'Order request';
                break;
            default:
                $subject = 'A message from your site visitor';
                break;
        }
    }else{
        die('MF004');
    }

    if (isset($_POST['email'])) {
        $template = str_replace(
            ["", ""],
            ["Email:", $_POST['email']],
            $template);
    }else{
        die('MF003');
    }

    if (isset($_POST['message'])) {
        $template = str_replace(
            ["", ""],
            ["Message:", $_POST['message']],
            $template);
    }

    preg_match("/()(.|\n)+()/", $template, $tmp, PREG_OFFSET_CAPTURE);
    foreach ($_POST as $key => $value) {
        if ($key != "email" && $key != "message" && $key != "form-type" && !empty($value)){
            $info = str_replace(
                ["", "", ""],
                ["", ucfirst($key) . ':', $value],
                $tmp[0][0]);

            $template = str_replace("", $info, $template);
        }
    }

    $template = str_replace(
        ["", ""],
        [$subject, $_SERVER['SERVER_NAME']],
        $template);

    $mail = new PHPMailer();
    $mail->From = $_SERVER['SERVER_ADDR'];
    $mail->FromName = $_SERVER['SERVER_NAME'];

    foreach ($addresses[0] as $key => $value) {
        $mail->addAddress($value[0]);
    }

    $mail->CharSet = 'utf-8';
    $mail->Subject = $subject;
    $mail->MsgHTML($template);

    if (isset($_FILES['attachment'])) {
        foreach ($_FILES['attachment']['error'] as $key => $error) {
            if ($error == UPLOAD_ERR_OK) {
                $mail->AddAttachment($_FILES['attachment']['tmp_name'][$key], $_FILES['Attachment']['name'][$key]);
            }
        }
    }

    $mail->send();

    die('MF000');
} catch (phpmailerException $e) {
    die('MF254');
} catch (Exception $e) {
    die('MF255');
}

?>`

**Comment by mairtg** [comment]
There's the php. Sorry about the previous unformatted mess.

**Comment by mairtg** [comment]
I can post the html too but I know there's no issue with that. The fields are 'name', 'phone', 'email' and 'message' in that order. I can post it if it would be better to see it.

**Comment by mairtg** [comment]
[JS.zip](https://github.com/PHPMailer/PHPMailer/files/733388/JS.zip)

There are the two JS files that correspond to the form.

**Comment by Synchro** [comment]
First of all I'd `var_dump($_POST)` to check what you're actually receiving.

There is no explicit mention of phone or name fields, so it is relying on your loop over `$_POST` - and if it's not turning up in there then that's where I'd be looking - it's not easy to tell what's going on in there. I'd set a breakpoint in a debugger and step through it. It looks like the `<!-- #{BeginInfo} -->` etc portions might be replaced globally the first time through the loop and never match again because they get replaced, so only the first item in $_POST will make it to your rendered body.

You should take a look at some templating tools like twig or Smarty. They are much easier to use than what you're doing here.

Your code for handling uploaded files is unsafe - look at the send uploaded file example and the PHP docs on handling uploads.

PHPMailer includes address validation; no need to roll your own.

`$mail->From = $_SERVER['SERVER_ADDR'];` is very unlikely to work - there is no guarantee that `SERVER_ADDR` will be a valid email address (it's usually just a hostname), and a From address should *never* have a possibility of being user-supplied.

**Comment by mairtg** [comment]
OK. Thanks mate. Much appreciated. I'll do that. Thanks for your time man.
