### ISSUE TITLE
SPF test fails for PHPMailer 

### ISSUE THREAD

**Issue by abdfahim** [PHPMailer/PHPMailer#979]
If I send an email using php mail() function, everything works fine

```
$to      = 'someone@gmail.com';
$subject = 'Whatever subject it is';
$headers = 'From: Example <admin@example.com>'. "\r\n";
$headers .= 'Reply-To: Example <admin@example.com>'. "\r\n";
$headers .= 'X-Mailer: PHP/' . phpversion() . "\r\n";
$headers .= 'MIME-Version: 1.0'. "\r\n";
$headers .= 'Content-Type: text/plain; charset=UTF-8'. "\r\n";
mail($to, $subject, "this is a test message", $headers);
```

SPF result:

> Received-SPF: pass (google.com: domain of example@a.hosting.com designates 12.123.456.12 as permitted sender)

However, if I send the same email to the same recipient from the same domain, the email gets sent but with a failed SPF test

SPF result:

> Received-SPF: fail (google.com: domain of admin@example.com does not designate 12.123.456.12 as permitted sender)

Below is the code I used with PHPMailer

```
$mail = new PHPMailer(true);	
try {
	$mail->SMTPDebug = 0;
	$mail->AddAddress('someone@gmail.com');
	$mail->SetFrom('admin@example.com', 'Example');
	$mail->AddReplyTo('admin@example.com', 'Example');
	$mail->IsHTML(true);
	$mail->CharSet = 'UTF-8';
	$mail->Subject = 'Whatever subject it is';
	$mail->Body    = 'this is a test message';
	$mail->Send();
} catch (phpmailerException $e) {
	echo 'Error1';
} catch (Exception $e) {
	echo 'Error2';
}
```

**Comment by Synchro** [comment]
When you use the `mail()` function as you show, you are not setting the SMTP envelope sender (via a `-f` option in the `$additional_parameters` parameter in the call to `mail()`), so it reverts to the default setting, which in your example is `example@a.hosting.com`.

PHPMailer automatically sets this value using the From address as the envelope sender (unless you override it with the `Sender` property), and in the case your own SPF record does not permit sending from that IP address, hence the failure. You can fix this either by using your ISP's address as the envelope sender (in which case you may lose control over where bounces go), or alter your SPF record to allow sending from that IP.

**Comment by abdfahim** [comment]
Thanks a lot Synchro, for the explanation. I use Google G-Suit (ex Google Apps) to manage my custom email address (admin@example.com), and in my example.com DNS editor I have added the SPF record as per [Google recommendation](https://support.google.com/a/answer/178723). 

> v=spf1 include:_spf.google.com ~all

But still I am receiving the error.

**Comment by abdfahim** [comment]
Thanks a lot.

**Comment by Synchro** [comment]
That SPF record you posted (`v=spf1 include:_spf.google.com ~all`) does not include your own IP you're sending from, so it will fail.

**Comment by abdfahim** [comment]
Thanks Synchro, I actually understood that just after posting, that's why i deleted the post before you replied. Sorry for that, you can restore that deleted post if you want.

Thanks again.
