### ISSUE TITLE
Issue with with Bcc and CC 

### ISSUE THREAD

**Issue by sportyboty** [PHPMailer/PHPMailer#980]
**I'm building a mail system with phpmailer which will use bcc or cc. when i add emails on bcc like this**

bcc1@example.com , bcc2@example.com, bcc3@example.com, bcc4@example.com,
bcc5@example.com , bcc6@example.com

**I get this error when i try to send** 

Fatal error: Uncaught exception 'phpmailerException' with message 'Invalid address: (addAnAddress bcc): ,' in C:\xampp\htdocs\ultimate\vendor\phpmailer\phpmailer\class.phpmailer.php:881 Stack trace: #0 C:\xampp\htdocs\ultimate\vendor\phpmailer\phpmailer\class.phpmailer.php(845): PHPMailer->addOrEnqueueAnAddress('bcc', ',', '') #1 C:\xampp\htdocs\ultimate\preg.php(51): PHPMailer->addBCC(',') #2 {main} thrown in C:\xampp\htdocs\ultimate\vendor\phpmailer\phpmailer\class.phpmailer.php on line 881

**this is my code for storing data**

if ($bcc != '') {
                   $indiBCC = explode(" ", $bcc);
                   foreach ($indiBCC as $key => $value) {
                       $mail->addBCC($value);
                   }
               }

**Comment by Synchro** [comment]
So what's the problem? You are feeding it invalid addresses and not handling errors properly?

**Comment by sportyboty** [comment]
Thank you, I have managed to fix the bug by editing phpmailer class

**Comment by Synchro** [comment]
That's really the wrong way to do it. You should **never** have to edit library files; work around it by using a subclass. If you don't do that, your code will break when you update the library.

**Comment by Synchro** [comment]
I've noticed what your actual problem is from that error message:

    addOrEnqueueAnAddress('bcc', ',', '')

here you can see that it's passing just a single comma as an email address. handle this properly like this:

```php
if ($bcc != '') {
    $indiBCC = explode(" ", $bcc);
    foreach ($indiBCC as $key => $value) {
        try {
            $mail->addBCC($value);
        } catch (phpmailerException $e) {
            echo 'Error: '. $e->getMessage();
        }
    }
}
```

**Comment by pilacroix** [comment]
De : Marcus Bointon [mailto:notifications@github.com] 
Envoyé : mardi 31 janvier 2017 11:41
À : PHPMailer/PHPMailer <PHPMailer@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [PHPMailer/PHPMailer] Issue with with Bcc and CC (#980)
 
So what's the problem? You are feeding it invalid addresses and not handling errors properly?

**Comment by OcranDave** [comment]
Fatal error: Uncaught phpmailerException: Message body empty in C:\xampp\htdocs\NEWPROJECT\contactform\PHPMailer\class.phpmailer.php:1272 Stack trace: #0 
 


I have this error have received . Please any help

C:\xampp\htdocs\NEWPROJECT\contactform\PHPMailer\class.phpmailer.php(1212): PHPMailer->preSend() #1 C:\xampp\htdocs\NEWPROJECT\contactform\contact.php(58): PHPMailer->send() #2 {main} thrown in C:\xampp\htdocs\NEWPROJECT\contactform\PHPMailer\class.phpmailer.php on line 1272

**Comment by OcranDave** [comment]
here is the complete code 👎<?php

session_start();

// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
//use PHPMailer\PHPMailer;
use PHPMailer\Exception;

//Load composer's autoloader
require 'PHPMailer/PHPMailerAutoload.php';

$mail = new PHPMailer(true); 
try {
if(isset($_POST['name'], $_POST['email'], $_POST['message'])){
$fields = [
  'name' => $_POST['name'],
    'email' => $_POST['email'],
	  'message' => $_POST['message']
];

foreach($fields as $field => $data){
	if(empty($data)){
		$errors[] = ' The ' . $field . ' field is required.';
	}
}                             // Passing `true` enables exceptions
    //Server settings
    $mail->SMTPDebug = 2;                                 // Enable verbose debug output
    $mail->isSMTP();                                      // Set mailer to use SMTP
    $mail->Host = 'smtp.comcast.net';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = 'ocrand9@gmail.com';                 // SMTP username
    $mail->Password = 'teresapat';                           // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 587;                                    // TCP port to connect to

	//Content
    $mail->isHTML(true);    
	
	// Set email format to HTML
    $mail->Subject = 'Contact form submitted';
    //$mail->AltBody = 'From: ' . $fields['name'] . ' (' . $fields['email'] . ')<p>' . $fields['message'] . '</p>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
   
   //$mail->FromName = 'Contact';
    //Recipients
   $mail->setFrom('from@example.com', 'Mailer');
    $mail->addAddress('ocrand9@gmail.com', 'David Ocran');     // Add a recipient
    $mail->addAddress('ellen@example.com');               // Name is optional
    $mail->addReplyTo('davisetad@gmail.com', 'David');
    $mail->addCC('cc@example.com');
    $mail->addBCC('bcc@example.com');

    //Attachments
   // $mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
    //$mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name

    if($mail->send()){
			header('location: thanks.php');
			die();
		}
		else{
			$errors[] = 'Sorry, could not send email. Try again later.';
		}
}


$_SESSION['errors'] = $errors;
$_SESSION['fields'] = $fields;

header('Location: index.php');

} catch (Exception $e) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
}

?>

**Comment by OcranDave** [comment]
here is the code:
<?php

session_start();

// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
//use PHPMailer\PHPMailer;
use PHPMailer\Exception;

//Load composer's autoloader
require 'PHPMailer/PHPMailerAutoload.php';

$mail = new PHPMailer(true); 
try {
if(isset($_POST['name'], $_POST['email'], $_POST['message'])){
$fields = [
  'name' => $_POST['name'],
    'email' => $_POST['email'],
	  'message' => $_POST['message']
];

foreach($fields as $field => $data){
	if(empty($data)){
		$errors[] = ' The ' . $field . ' field is required.';
	}
}                             // Passing `true` enables exceptions
    //Server settings
    $mail->SMTPDebug = 2;                                 // Enable verbose debug output
    $mail->isSMTP();                                      // Set mailer to use SMTP
    $mail->Host = 'smtp.comcast.net';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = 'ocrand9@gmail.com';                 // SMTP username
    $mail->Password = 'teres';                           // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 587;                                    // TCP port to connect to

	//Content
    $mail->isHTML(true);    
	
	// Set email format to HTML
    $mail->Subject = 'Contact form submitted';
    //$mail->AltBody = 'From: ' . $fields['name'] . ' (' . $fields['email'] . ')<p>' . $fields['message'] . '</p>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
   
   //$mail->FromName = 'Contact';
    //Recipients
   $mail->setFrom('from@example.com', 'Mailer');
    $mail->addAddress('ocrand9@gmail.com', 'David Ocran');     // Add a recipient
    $mail->addAddress('ellen@example.com');               // Name is optional
    $mail->addReplyTo('davisetad@gmail.com', 'David');
    $mail->addCC('cc@example.com');
    $mail->addBCC('bcc@example.com');

    //Attachments
   // $mail->addAttachment('/var/tmp/file.tar.gz');         // Add attachments
    //$mail->addAttachment('/tmp/image.jpg', 'new.jpg');    // Optional name

    if($mail->send()){
			header('location: thanks.php');
			die();
		}
		else{
			$errors[] = 'Sorry, could not send email. Try again later.';
		}
}


$_SESSION['errors'] = $errors;
$_SESSION['fields'] = $fields;

header('Location: index.php');

} catch (Exception $e) {
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
}

?>

**Comment by Synchro** [comment]
@OcranDave Don't hijack unrelated issues.

You're getting an error message that says:

> Message body empty

Is it that much of a stretch to think that this might mean that you have left the message body empty?
The message body is set in the `Body` property, which you're not setting, hence the error.

This makes no sense at all:

```php
use PHPMailer\Exception;

//Load composer's autoloader
require 'PHPMailer/PHPMailerAutoload.php';
```

The first line here is just wrong - you're not setting the full-qualified class name for the Exception class, which you only need to do if you're using PHPMailer 6.0. Then you're loading the autoloader that is only present in PHPMailer 5.2, and does not exist in 6.0. You've got things very confused. I suggest you scrap this code, use PHPMailer 6.0, and start again with one the of the examples.

**Comment by OcranDave** [comment]
Oh ok thank you! Synchro 
i have this error 
Fatal error: Uncaught Error: Call to undefined method PHPMailer\PHPMailer\PHPMailer::isTHML() in C:\xampp\htdocs\tutorial\index.php:19 Stack trace: #0 {main} thrown in C:\xampp\htdocs\tutorial\index.php on line 19

And here is the code 
i have installed autoloader

<?php


require 'vendor/phpmailer/phpmailer/src/PHPMailer.php';

require_once 'vendor/autoload.php';
if(isset($_POST['email'])){
	if(!filter_var($_POST['email'] ,FILTER_VALIDATE_EMAIL)){
	
} else{
	$mail = new PHPMailer();
	$mail->setFrom("davisetad@gmail.com" ,"David Ocran");
	$mail->addAddress($_POST['email'] ,$_POST['name']);
	$mail->isTHML(true);
	$mail->Subject = "Here are the subject of email";
	$mail->Body = "<h3>".$_POST['msg']."</h3>";

}
	if($mail->send()){
		echo "email sent";
	}
	else{
		echo "error";
	}
}
?>

<form action="" method="post">

<div><input type="text" name="name" placeholder="name" ></div>

<div><input type="email" name="email" placeholder="Email" ></div>

<div><textarea type="msg"  placeholder="Message" ></textarea></div>
<input type="submit" value="send">
</form>

**Comment by OcranDave** [comment]
Oh ok thank you! Synchro
i have this error
Fatal error: Uncaught Error: Call to undefined method PHPMailer\PHPMailer\PHPMailer::isTHML() in C:\xampp\htdocs\tutorial\index.php:19 Stack trace: #0 {main} thrown in C:\xampp\htdocs\tutorial\index.php on line 19

And here is the code
i have installed autoloader

<?php


require 'vendor/phpmailer/phpmailer/src/PHPMailer.php';

require_once 'vendor/autoload.php';
if(isset($_POST['email'])){
	if(!filter_var($_POST['email'] ,FILTER_VALIDATE_EMAIL)){
	
} else{
	$mail = new PHPMailer();
	$mail->setFrom("davisetad@gmail.com" ,"David Ocran");
	$mail->addAddress($_POST['email'] ,$_POST['name']);
	$mail->isTHML(true);
	$mail->Subject = "Here are the subject of email";
	$mail->Body = "<h3>".$_POST['msg']."</h3>";

}
	if($mail->send()){
		echo "email sent";
	}
	else{
		echo "error";
	}
}
?>

<form action="" method="post">

<div><input type="text" name="name" placeholder="name" ></div>

<div><input type="email" name="email" placeholder="Email" ></div>

<div><textarea type="msg"  placeholder="Message" ></textarea></div>
<input type="submit" value="send">
</form>

**Comment by Synchro** [comment]
Oh come on, this is pathetic. Can you at least *read* the error message and make the tiniest bit of effort to look at what you've written? The function is called `isHTML`, not `isTHML`.

**Comment by Ademgenc53** [comment]
Hello,
```
    foreach ($mails AS $mail){        
      $mail->addBCC($mail, "Title");
    }
```

No other mails appear in the message in the email inbox
But there is the second email "**undisclosed-recipients**"
[https://antenfiyati.com/email.png](https://antenfiyati.com/email.png)

**Comment by Synchro** [comment]
Yes, it's an empty RFC822 group address. They are not strictly necessary, but it's a convention that's been around for at least 40 years.
