### ISSUE TITLE
__autoload is depreciated in PHP 7.2

### ISSUE THREAD

**Issue by goosehub** [PHPMailer/PHPMailer#981]
https://wiki.php.net/rfc/deprecations_php_7_2

__autoload is used in PHPMailerAutoload.php. Is this a problem and if so what are the plans to resolve this?

**Comment by Synchro** [comment]
Not worried about that. It's *deprecated*, not removed in 7.2 (i.e. will be around until 8.0), and the entire autoloader has been removed in the forthcoming 6.0 release.
