### ISSUE TITLE
Mails not going through WAMP Server - DATA command not accepted from server

### ISSUE THREAD

**Issue by rohitchokhani** [PHPMailer/PHPMailer#986]
Hello,
When using PHP Mailer to send mails through the WAMP server, I get a DATA command not accepted from server.

The same code is running from the local server absolutely fine and the mails are being triggered. I had checked my Port 465 and my Firewall was blocking it initially, I have now allowed all the accesses through the Port and have kept the port Open, still I get the below issue - 

SMTP -> get_lines(): $data was "" 
SMTP -> get_lines(): $str is "220 smtp.gmail.com ESMTP t15sm72976298pgn.18 - gsmtp " 
SMTP -> get_lines(): $data is "220 smtp.gmail.com ESMTP t15sm72976298pgn.18 - gsmtp " 
SMTP -> FROM SERVER:220 smtp.gmail.com ESMTP t15sm72976298pgn.18 - gsmtp 
SMTP -> get_lines(): $data was "" 
SMTP -> get_lines(): $str is "250-smtp.gmail.com at your service, [_server_ip_] " 
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [_server_ip_] " 
SMTP -> get_lines(): $data was "250-smtp.gmail.com at your service, [_server_ip_] " 
SMTP -> get_lines(): $str is "250-SIZE 35882577 " 
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [_server_ip_] 250-SIZE 35882577 " 
SMTP -> get_lines(): $data was "250-smtp.gmail.com at your service, [_server_ip_] 250-SIZE 35882577 " 
SMTP -> get_lines(): $str is "250-8BITMIME " 
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [_server_ip_] 250-SIZE 35882577 250-8BITMIME " 
SMTP -> get_lines(): $data was "250-smtp.gmail.com at your service, [_server_ip_] 250-SIZE 35882577 250-8BITMIME " 
SMTP -> get_lines(): $str is "250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH " 
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [_server_ip_] 250-SIZE 35882577 250-8BITMIME 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH " 
SMTP -> get_lines(): $data was "250-smtp.gmail.com at your service, [server_ip] 250-SIZE 35882577 250-8BITMIME 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH " 
SMTP -> get_lines(): $str is "250-ENHANCEDSTATUSCODES " 
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [_server_ip_] 250-SIZE 35882577 250-8BITMIME 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH 250-ENHANCEDSTATUSCODES " 
SMTP -> get_lines(): $data was "250-smtp.gmail.com at your service, [_server_ip_] 250-SIZE 35882577 250-8BITMIME 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH 250-ENHANCEDSTATUSCODES " 
SMTP -> get_lines(): $str is "250-PIPELINING " 
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [_server_ip_] 250-SIZE 35882577 250-8BITMIME 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH 250-ENHANCEDSTATUSCODES 250-PIPELINING " 
SMTP -> get_lines(): $data was "250-smtp.gmail.com at your service, [_server_ip_] 250-SIZE 35882577 250-8BITMIME 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH 250-ENHANCEDSTATUSCODES 250-PIPELINING " 
SMTP -> get_lines(): $str is "250 SMTPUTF8 " 
SMTP -> get_lines(): $data is "250-smtp.gmail.com at your service, [_server_ip_] 250-SIZE 35882577 250-8BITMIME 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH 250-ENHANCEDSTATUSCODES 250-PIPELINING 250 SMTPUTF8 " 
SMTP -> FROM SERVER: 250-smtp.gmail.com at your service, [_server_ip_] 250-SIZE 35882577 250-8BITMIME 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH 250-ENHANCEDSTATUSCODES 250-PIPELINING 250 SMTPUTF8 
SMTP -> get_lines(): $data was "" 
SMTP -> get_lines(): $str is "334 VXNlcm5hbWU6 " 
SMTP -> get_lines(): $data is "334 VXNlcm5hbWU6 " 
SMTP -> get_lines(): $data was "" 
SMTP -> get_lines(): $str is "334 UGFzc3dvcmQ6 " 
SMTP -> get_lines(): $data is "334 UGFzc3dvcmQ6 " 
SMTP -> get_lines(): $data was "" 
SMTP -> get_lines(): $str is "235 2.7.0 Accepted " 
SMTP -> get_lines(): $data is "235 2.7.0 Accepted " 
SMTP -> get_lines(): $data was "" 
SMTP -> get_lines(): $str is "250 2.1.0 OK t15sm72976298pgn.18 - gsmtp " 
SMTP -> get_lines(): $data is "250 2.1.0 OK t15sm72976298pgn.18 - gsmtp " 
SMTP -> FROM SERVER:250 2.1.0 OK t15sm72976298pgn.18 - gsmtp 
SMTP -> get_lines(): $data was "" 
SMTP -> get_lines(): $str is "250 2.1.5 OK t15sm72976298pgn.18 - gsmtp " 
SMTP -> get_lines(): $data is "250 2.1.5 OK t15sm72976298pgn.18 - gsmtp " 
SMTP -> FROM SERVER:250 2.1.5 OK t15sm72976298pgn.18 - gsmtp 
SMTP -> FROM SERVER: 
SMTP -> ERROR: DATA command not accepted from server:

**Comment by Synchro** [comment]
Can you repeat that with `SMTPDebug = 2`? It's hard to read what's going on there.

**Comment by rohitchokhani** [comment]
This is from SMTPDebug = 2

SMTP -> FROM SERVER:220 smtp.gmail.com ESMTP j28sm73020369pfj.2 - gsmtp 
SMTP -> FROM SERVER: 250-smtp.gmail.com at your service, [_server_ip_] 250-SIZE 35882577 250-8BITMIME 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH 250-ENHANCEDSTATUSCODES 250-PIPELINING 250 SMTPUTF8 
SMTP -> FROM SERVER:250 2.1.0 OK j28sm73020369pfj.2 - gsmtp 
SMTP -> FROM SERVER:250 2.1.5 OK j28sm73020369pfj.2 - gsmtp 
SMTP -> FROM SERVER: 
SMTP -> ERROR: DATA command not accepted from server:

**Comment by Synchro** [comment]
Why isn't it showing the client -> server output? Have you edited it out?

**Comment by rohitchokhani** [comment]
No, have not edited the PHP Mailer core files. The same version of the Mailer, works from my localhost, for the same code.

I will give in the SMTPDebug = 2, details for the localhost tomorrow

**Comment by Synchro** [comment]
You must be running a really old version of PHPMailer - the debug messages have not looked like that for years, and the cient-> server traffic is missing.

**Comment by rohitchokhani** [comment]
Thanks all for the help. I have upgraded to the latest PHP Mailer class and have also upgraded the Firewall on my server and reset the port blocking settings for my firewall and that solved the issue
