### ISSUE TITLE
Class 'PHPMailer\PHPMailer\PHPMailer' not found

### ISSUE THREAD

**Issue by vmakre** [PHPMailer/PHPMailer#989]
My system is php7 on ubuntu 64bit. When i change in Auth.php  this line:
use PHPMailer\PHPMailer\PHPMailer ; 
 to
use PHPMailer  ;
everything is ok  .

**Comment by Synchro** [comment]
Auth.php is not part of PHPMailer, so this is something in your own code. The namespaced definition only works with PHPMailer 6.0, which is as yet unreleased.
