### ISSUE TITLE
Problem with Godaddy and Relay

### ISSUE THREAD

**Issue by edgardomilan22** [PHPMailer/PHPMailer#991]
Hi

I have a problem with godaddy, the relays quota per day allowed Is exceeded and I can not send more mails.
Is there any way to Get in a variable the remaining relays.

**Comment by Synchro** [comment]
You'll need to ask GoDaddy.

**Comment by edgardomilan22** [comment]
I spoke with a tech support from godaddy and they did not help me with the problem

**Comment by Synchro** [comment]
Then it's clearly time to find a better ISP.

**Comment by edgardomilan22** [comment]
Which you recommend not to have problems with relay

**Comment by Synchro** [comment]
Any that don't impress such limits. GoDaddy is pretty much the worst case, so almost anyone will be better. Just search, read reviews.

**Comment by vignesh-subash** [comment]
@edgardomilan22
add these lines in your connect.php file and this will work.
 ```
$mail->SMTPAutoTLS = false;
$mail->SMTPSecure = false;
```

**Comment by Synchro** [comment]
@vignesh-subash No it won't. The question is about GoDaddy's email quotas, nothing to do with TLS.
