### ISSUE TITLE
SMTP ERROR: Password command failed: 535 5.7.3 Authentication unsuccessful

### ISSUE THREAD

**Issue by deanhtid** [PHPMailer/PHPMailer#992]
Hi, 

I'm encountering the above error. Been trying to debug this for 2 days. Password is correct, username is correct.

here are my settings:

```
$mail = new PHPMailer;
        $mail->isSMTP();
        $mail->SMTPDebug = 2;
        $mail->Host = $smtp_server;
        $mail->Port = $smtp_port;
        $mail->SMTPSecure = 'tls';
        $mail->SMTPAuth = true;
        $mail->Username = $smtp_user;
        $mail->Password = $smtp_pass;
```

here are my errors from the debug log:

> 2017-02-10 10:31:51    CLIENT -> SERVER: STARTTLS
> 2017-02-10 10:31:51    SERVER -> CLIENT: 220 2.0.0 SMTP server ready
> 2017-02-10 10:31:51    CLIENT -> SERVER: EHLO ip-{ipaddress}
> 2017-02-10 10:31:52    SERVER -> CLIENT: 250-AM5PR0601CA0034.outlook.office365.com Hello [{ip address}]
>                                          250-SIZE 157286400
>                                          250-PIPELINING
>                                          250-DSN
>                                          250-ENHANCEDSTATUSCODES
>                                          250-AUTH LOGIN
>                                          250-8BITMIME
>                                          250-BINARYMIME
>                                          250-CHUNKING
>                                          250 SMTPUTF8
> 2017-02-10 10:31:52    CLIENT -> SERVER: AUTH LOGIN
> 2017-02-10 10:31:52    SERVER -> CLIENT: 334 VXNlcm5hbWU6
> 2017-02-10 10:31:52    CLIENT -> SERVER: xxx==
> 2017-02-10 10:31:52    SERVER -> CLIENT: 334 UGFzc3dvcmQ6
> 2017-02-10 10:31:52    CLIENT -> SERVER: xxx=
> 2017-02-10 10:31:57    SERVER -> CLIENT: 535 5.7.3 Authentication unsuccessful
> 2017-02-10 10:31:57    SMTP ERROR: Password command failed: 535 5.7.3 Authentication unsuccessful
> 2017-02-10 10:31:57    SMTP Error: Could not authenticate.
> 2017-02-10 10:31:57    CLIENT -> SERVER: QUIT
> 2017-02-10 10:31:57    SERVER -> CLIENT: 221 2.0.0 Service closing transmission channel

Any help would be really appreciated.

Thanks

**Comment by deanhtid** [comment]
I'm using an AWS server running ubuntu with the latest version of PHPMailer.

**Comment by Synchro** [comment]
[This page](https://support.office.com/en-us/article/POP-and-IMAP-settings-for-Outlook-Office-365-for-business-7fc677eb-2491-4cbc-8153-8e7113525f6c?ui=en-US&rs=en-US&ad=US&fromAR=1) says you should be using `smtp.office365.com` on port 587, but you're using `outlook.office365.com`. Does that help?

**Comment by deanhtid** [comment]
I am using 

`$smtp_server = "smtp.office365.com";`

Sorry, should have said.

**Comment by Synchro** [comment]
It just looks like wrong id or pass to me. Double check by using the same values on the office 365 login page.

**Comment by deanhtid** [comment]
That's what I thought but I can log in no problem with the same details on the office365 portal. It's a weird one.

Driving me crazy as it was working before Christmas

**Comment by Synchro** [comment]
Your ID and pass was extractable from you SMTP transcript so I edited it out, but (I hope you don't mind), I tested it too and got the same results. The ID and pass are definitely correct and they are encoded correctly in the AUTH command (otherwise I wouldn't have been able to extract them), which suggests that there's some policy at work on your office account. I searched for that error and found [this](https://social.technet.microsoft.com/Forums/exchange/en-US/810eea46-119a-4650-ab93-0cb0fa954672/535-573-authentication-unsuccessful?forum=exchangesvrgenerallegacy) which suggests that SMTP submission is something you need to enable, so I suggest looking into that or asking for support from MS.

I also recommend that you change your password...

**Comment by deanhtid** [comment]
Hi Synchro, 

No, I don't mind at all. I'll get that changed now.

I'll check with work first if no solution is found i will speak to MS. Thanks for the advice.

Kind Regards

Dean
