### ISSUE TITLE
Error after updating to PHP 7 Using XAMPP

### ISSUE THREAD

**Issue by tempusrname** [PHPMailer/PHPMailer#994]
When I updated XAMPP to the latest version, which came along with PHP7; I tried using the contact form and received the following warning:

Warning: stream_socket_enable_crypto(): Peer certificate CN=`smtp.gmail.com' did not match expected CN=`209.85.144.108' in /Applications/XAMPP/xamppfiles/htdocs/website/php/phpmailer/class.smtp.php on line 367
SMTP Error: Could not connect to SMTP host.

I'm guessing this has something to do with server configuration, but I'm not at all sure. Could I get some insight on what the problem might be and how I can fix it?

**Comment by Synchro** [comment]
Please read the troubleshooting guide and make sure you are using the latest version. This issue is well covered and has existed since PHP 5.6, which introduced (quite rightly) verification of certificates by default.

**Comment by StudioJunkyard** [comment]
If you run the code through a linter like php7cc, it shows that there is code in the source that isn't supported by PHP7. I find it works perfectly fine with v5.6, which is currently the lowest supported version being LTS. Even though they have release 7.1, 7 is not suggested for production environment, unless something has changed that I am not aware in the last month or so.

**Comment by Synchro** [comment]
If you actually read the code, you'll see it's wrapped in version conditions so that those functions are only run on old versions of PHP. It's entirely compatible with PHP 7.1.

**Comment by tempusrname** [comment]
I replaced every file with the latest version, except for send.php which contains the configurations and im still getting the error. The content of send.php file incase the error is there: 

`	if( $_SERVER["REQUEST_METHOD"] == "POST" && $_SERVER['CONTENT_LENGTH'] > 0 ) {

		require 'PHPMailerAutoload.php';

		$mail = new PHPMailer(true);
		$mail->isSMTP();
		$mail->SMTPSecure = 'tls';
		$mail->Port = 587;
		$mail->SMTPDebug = 0;
		$mail->SMTPAuth = true;
		$mail->isHTML(false);

	$mail->Host = gethostbyname('smtp.gmail.com'); // Specify main and backup SMTP servers ("smtp.gmail.com" is original value)
	$mail->Username = 'email@example.com'; // Email account address
	$mail->Password = 'password'; // Email account password
	$mail->addAddress('email@example.com', 'john doe'); // Send emails to this address

	$input1_label = 'NAME:  ';
	$input2_label = 'EMAIL ADDRESS:  ';
	$input3_label = 'SUBJECT:  ';

	$notice_msg_sent = 'Message Sent';
	$err_msg_required_inputs = 'One or more required fields are empty.';
	$err_msg_upload_limit = 'Cannot send email. Attachment is too large.'; // attachment is too large
	$err_msg_include_attachments = 'Failed to include attachments. Please try again.'; // adding attachments failed

		$input1Exist = isset($_POST['form_input_1']);
		$input2Exist = isset($_POST['form_input_2']);
		$input3Exist = isset($_POST['form_input_3']);
		$input4Exist = isset($_POST['form_input_4']);

		if( $input1Exist ) { $formInput1 = trim($_POST['form_input_1']); } else { $formInput1 = ''; }
		if( $input2Exist ) { $formInput2 = trim($_POST['form_input_2']); } else { $formInput2 = ''; }
		if( $input4Exist ) { $formInput4 = trim($_POST['form_input_4']); } else { $formInput4 = ''; }
		if( $input3Exist ) { $formInput3 = trim($_POST['form_input_3']); } else { $formInput3 = ''; }

		// Get max size
		function parse_size($size) {
			$unit = preg_replace('/[^bkmgtpezy]/i', '', $size);
			$size = preg_replace('/[^0-9\.]/', '', $size);
			if ($unit) { return round($size * pow(1024, stripos('bkmgtpezy', $unit[0]))); }
		}
		function file_upload_max_size() {
			static $max_size = -1;
			if ($max_size < 0) {
				$max_size = parse_size(ini_get('post_max_size'));
				$upload_max = parse_size(ini_get('upload_max_filesize'));
				if ($upload_max > 0 && $upload_max < $max_size) { $max_size = $upload_max;}
			}
			return $max_size;
		}

		// If upload exceeds limit
		if( $_SERVER['CONTENT_LENGTH'] > file_upload_max_size() ) {
			$max_limit_exceeded = true;
		} else {
			$max_limit_exceeded = false;
		}

		if( $formInput1 !== '' && $formInput2 !== '' && $formInput4 !== '' ) {
			try {
				$message = $input1_label . $formInput1."\r\n";
				$message.= $input2_label . $formInput2."\r\n";
				$message.= $input3_label . $formInput3."\r\n\r\n";
				$message.= $formInput4;

				$mail->setFrom($formInput2, $formInput1);
				$mail->addReplyTo($formInput2, $formInput1);
				$mail->Body = $message;
				if( $input3Exist && trim($formInput3) !== '' ) { $mail->Subject = $formInput3; } else { $mail->Subject = 'New Email From: '.$formInput1; }

				// Attachments
				if( isset($_FILES['form_4_file']) && $_FILES['form_4_file']['size'][0] !== 0 && $_FILES['form_4_file']['tmp_name'][0] !== '' ) {
					if ( array_key_exists('form_4_file', $_FILES) ) {
						for ( $ct = 0; $ct < count($_FILES['form_4_file']['tmp_name']); $ct++ ) {
							$uploadfile = tempnam(sys_get_temp_dir(), sha1($_FILES['form_4_file']['name'][$ct]));
							$filename = $_FILES['form_4_file']['name'][$ct];
							if ( move_uploaded_file($_FILES['form_4_file']['tmp_name'][$ct], $uploadfile) ) {
								$mail->addAttachment($uploadfile, $filename);
							} else {
								echo '<i class="fa fa-times"></i><div class="form-ajax-submit-response-message">'.$err_msg_include_attachments.'</div>';
								die();
							}
						}
					}
				}

				$mail->send();
				echo '<i class="fa fa-check"></i><div class="form-ajax-submit-response-message">'.$notice_msg_sent.'</div>';
			} catch ( phpmailerException $e ) {
				echo '<i class="fa fa-times"></i><div class="form-ajax-submit-response-message">'.$e->errorMessage().'</div>';
			} catch ( Exception $e ) {
				echo '<i class="fa fa-times"></i><div class="form-ajax-submit-response-message">'.$e->getMessage().'</div>';
			}
		} else {
			if( $max_limit_exceeded == false ) {
				echo '<i class="fa fa-times"></i><div class="form-ajax-submit-response-message">'.$err_msg_required_inputs.'</div>';
			} elseif ( $max_limit_exceeded == true ) {
				echo '<i class="fa fa-times" style="margin-top:5px"></i><div class="form-ajax-submit-response-message">'.$err_msg_upload_limit.'</div>';
			}
		}

	} else {
		http_response_code(403);
	}`

**Comment by Synchro** [comment]
Really - read what I said. This is not a code problem, it's that your mail server is presenting an invalid certificate, or your ISP is redirecting you to a different server than the one you're expecting.

**Comment by tempusrname** [comment]
I set SMTPDebug = 2 and the log is:

2017-02-11 18:45:26	SERVER -> CLIENT: 220 smtp.gmail.com ESMTP s20sm4159564qtc.39 - gsmtp 2017-02-11 18:45:26	CLIENT -> SERVER: EHLO localhost 2017-02-11 18:45:26	SERVER -> CLIENT: 250-smtp.gmail.com at your service, [104.162.246.112] 250-SIZE 35882577 250-8BITMIME 250-STARTTLS 250-ENHANCEDSTATUSCODES 250-PIPELINING 250-CHUNKING 250 SMTPUTF8 2017-02-11 18:45:26	CLIENT -> SERVER: STARTTLS 2017-02-11 18:45:26	SERVER -> CLIENT: 220 2.0.0 Ready to start TLS 
Warning: stream_socket_enable_crypto(): Peer certificate CN=`smtp.gmail.com' did not match expected CN=`74.125.22.109' in /Applications/XAMPP/xamppfiles/htdocs/Luminal/Luminal Template/php/phpmailer/class.smtp.php on line 367
2017-02-11 18:45:26	SMTP Error: Could not connect to SMTP host. 2017-02-11 18:45:26	CLIENT -> SERVER: QUIT 2017-02-11 18:45:26	SERVER -> CLIENT: 2017-02-11 18:45:26	SMTP ERROR: QUIT command failed: 2017-02-11 18:45:26	SMTP Error: Could not connect to SMTP host.

**Comment by Synchro** [comment]
Also, never do this:

    $mail->setFrom($formInput2, $formInput1);

This is forgery and will cause your messages to fail SPF checks, resulting in non-delivery or delivery to spam folders at best.

Use your own address as the from address and put the submitter's address in a reply-to using `addReplyTo()`.

**Comment by Synchro** [comment]
Right, that mismatch is cause by this:

    $mail->Host = gethostbyname('smtp.gmail.com');

This sets the `Host` property to an IP address, which means that it doesn't match the certificate presented by the mail server. If you don't have a specific reason to use `gethostbyname` (typically that you need to force it to use an IPv4 address, just don't do it, use the proper server name instead.

**Comment by Synchro** [comment]
All of this is covered in the PHPMailer examples, documentation and the troubleshooting guide.

**Comment by tempusrname** [comment]
Thanks.

I replaced 
`$mail->Host = gethostbyname('smtp.gmail.com');` with `$mail->Host = 'smtp.gmail.com';`
and that fixed the issue.

If I understood correctly regarding the forgery issue, I did the following:
```
$mail->setFrom('myownemailaddress@domain.com');
$mail->addReplyTo($formInput2, $formInput1);
```
for the addReplyTo, the $formInput2 variable contains the name the user entered in the input field, while $formInput1 contains the email address they entered. Is this correct? I didn't realize I would actually be sending emails to myself with the users message.

**Comment by Synchro** [comment]
Yes, that's correct. It's a common mistake - it's used to be a pretty normal thing to do in the days before spam, but that's a long time ago!

**Comment by tempusrname** [comment]
Might as well post this here:

When an invalid email address is entered, the following message is returned
`Invalid address: (addAnAddress Reply-To): invalidaddress`
I can't find any documentation on how to replace this warning with my own custom message.

**Comment by Synchro** [comment]
There's no need - `addReplyTo` returns `false` if the address is invalid. Trap that response and do what you like with it.

**Comment by tempusrname** [comment]
`echo $mail->addReplyTo($formInput2, $formInput1);` returns '1' if the email is valid and nothing if it's invalid.

**Comment by Synchro** [comment]
That's just how PHP renders boolean value as strings. You can get more detailed output by using `var_dump($mail->addReplyTo($Input2, $Input1));`. To trap it you'd simply do this:

if (!$mail->addReplyTo($formInput2, $formInput1)) {
    echo 'Invalid email address';
}

I suggest [reading the PHP manual](http://php.net/manual/en/language.types.boolean.php), it's very good.

**Comment by tempusrname** [comment]
I can't get this to work. I wrapped the addReplyTo function with the if, but I still receive the default message when the email is invalid.

```
				if( !$mail->setFrom('email@address.com', 'johndoe') ) { echo "invalid" };
				$mail->addReplyTo($Input2, $Input1);
				$mail->Body = $content;
```

**Comment by Synchro** [comment]
But in that code you have not done it?

**Comment by tempusrname** [comment]
I implemented the if statement shown above. If the email is invalid I should see 'invalid' message. But I'm not.

**Comment by Synchro** [comment]
No, because `email@address.com` is a valid address! The `!` in front of it means "not", so it will only fulfil the condition the `if` is checking for if the address is invalid, i.e. if `setFrom()` returns `false`. 

You can generally skip checking static values that you know to be correct - but that's not true of user-supplied input, which you should *always* check.

**Comment by tempusrname** [comment]
I updated the code above. I was performing the if statement on setFrom instead of addReplyTo

**Comment by tempusrname** [comment]
I'm still having the issue btw. The code I have is correct, but still the default message is shown. Heres what I currently have:

```
	if( $_SERVER["REQUEST_METHOD"] == "POST" && $_SERVER['CONTENT_LENGTH'] > 0 ) {

		require 'PHPMailerAutoload.php';

		$mail = new PHPMailer(true);
		$mail->isSMTP();
		$mail->SMTPSecure = 'tls';
		$mail->Port = 587;
		$mail->SMTPDebug = 0;
		$mail->SMTPAuth = true;
		$mail->isHTML(false);

		require '../configPrivate.php';

		$mail->addAddress($sendTo, $sendToName); // Send emails to this address

		$input1Exist = isset($_POST['form_input_1']);
		$input2Exist = isset($_POST['form_input_2']);
		$input3Exist = isset($_POST['form_input_3']);
		$input4Exist = isset($_POST['form_input_4']);

		if( $input1Exist ) { $formInput1 = trim($_POST['form_input_1']); } else { $formInput1 = ''; }
		if( $input2Exist ) { $formInput2 = trim($_POST['form_input_2']); } else { $formInput2 = ''; }
		if( $input4Exist ) { $formInput4 = trim($_POST['form_input_4']); } else { $formInput4 = ''; }
		if( $input3Exist ) { $formInput3 = trim($_POST['form_input_3']); } else { $formInput3 = ''; }

		// Get max size
		function parse_size($size) {
			$unit = preg_replace('/[^bkmgtpezy]/i', '', $size);
			$size = preg_replace('/[^0-9\.]/', '', $size);
			if ($unit) { return round($size * pow(1024, stripos('bkmgtpezy', $unit[0]))); }
		}
		function file_upload_max_size() {
			static $max_size = -1;
			if ($max_size < 0) {
				$max_size = parse_size(ini_get('post_max_size'));
				$upload_max = parse_size(ini_get('upload_max_filesize'));
				if ($upload_max > 0 && $upload_max < $max_size) { $max_size = $upload_max;}
			}
			return $max_size;
		}

		// If upload exceeds limit
		if( $_SERVER['CONTENT_LENGTH'] > file_upload_max_size() ) {
			$max_limit_exceeded = true;
		} else {
			$max_limit_exceeded = false;
		}

		if( $formInput1 !== '' && $formInput2 !== '' && $formInput4 !== '' ) {
			try {
				$message = $input1_label.'  '.$formInput1."\r\n";
				$message.= $input2_label.'  '.$formInput2."\r\n";
				$message.= $input3_label.'  '.$formInput3."\r\n\r\n";
				$message.= $formInput4;

				$mail->setFrom($sendTo, $sendToName);
// custom invalid email message
				if( !$mail->addReplyTo($formInput2, $formInput1) ) {
					echo 'INVALID EMAIL ADDRESS';
				};
				$mail->Body = $message;
				if( $input3Exist && trim($formInput3) !== '' ) { $mail->Subject = $formInput3; } else { $mail->Subject = $fallbackSubject.' '.$formInput1; }

				// Attachments
				if( isset($_FILES['form_4_file']) && $_FILES['form_4_file']['size'][0] !== 0 && $_FILES['form_4_file']['tmp_name'][0] !== '' ) {
					if ( array_key_exists('form_4_file', $_FILES) ) {
						for ( $ct = 0; $ct < count($_FILES['form_4_file']['tmp_name']); $ct++ ) {
							$uploadfile = tempnam(sys_get_temp_dir(), sha1($_FILES['form_4_file']['name'][$ct]));
							$filename = $_FILES['form_4_file']['name'][$ct];
							if ( move_uploaded_file($_FILES['form_4_file']['tmp_name'][$ct], $uploadfile) ) {
								$mail->addAttachment($uploadfile, $filename);
							} else {
								echo '<i class="fa fa-times"></i><div class="form-ajax-submit-response-message">'.$err_msg_include_attachments.'</div>';
								die();
							}
						}
					}
				}

				$mail->send();
				echo '<i class="fa fa-check"></i><div class="form-ajax-submit-response-message">'.$notice_msg_sent.'</div>';
			} catch ( phpmailerException $e ) {
				echo '<i class="fa fa-times"></i><div class="form-ajax-submit-response-message">'.$e->errorMessage().'</div>';
			} catch ( Exception $e ) {
				echo '<i class="fa fa-times"></i><div class="form-ajax-submit-response-message">'.$e->getMessage().'</div>';
			}
		} else {
			if( $max_limit_exceeded == false ) {
				echo '<i class="fa fa-times"></i><div class="form-ajax-submit-response-message">'.$err_msg_required_inputs.'</div>';
			} elseif ( $max_limit_exceeded == true ) {
				echo '<i class="fa fa-times" style="margin-top:5px"></i><div class="form-ajax-submit-response-message">'.$err_msg_upload_limit.'</div>';
			}
		}

	} else {
		http_response_code(403);
	}
```

**Comment by Synchro** [comment]
In this code you're simply telling it to display the message, which is why it's being displayed!

```php
			} catch ( phpmailerException $e ) {
				echo '<i class="fa fa-times"></i><div class="form-ajax-submit-response-message">'.$e->errorMessage().'</div>';
			} catch ( Exception $e ) {
				echo '<i class="fa fa-times"></i><div class="form-ajax-submit-response-message">'.$e->getMessage().'</div>';
```

If you don't want to display the message, don't display it!

Also, you don't want to send the message if the user-provided address is invalid, so I suggest you throw something to prevent it trying to send:

```php
				if( !$mail->addReplyTo($formInput2, $formInput1) ) {
					throw new Exception('INVALID EMAIL ADDRESS');
				};
```

This is all simple logic!

**Comment by tempusrname** [comment]
Wouldn't that show 'INVALID EMAIL ADDRESS' for all errors? Is this something that could be made simpler?

**Comment by Synchro** [comment]
No? It would only display that error when the address is invalid. You do understand how exceptions work?

**Comment by phet11234** [comment]
o? It would only display that error when the address is invalid. You do
understand how exceptions work?
เมื่อ 20 ก.พ. 2017 12:33 ก่อนเที่ยง "Marcus Bointon" <
notifications@github.com> เขียนว่า

**Comment by tempusrname** [comment]
As I mentioned before I know very little PHP. You can't possibly assume everyone knows as much PHP as you. Can you include an example in the examples folder? This should be documented somewhere.

**Comment by Synchro** [comment]
[It is](http://php.net/manual/en/language.exceptions.php).
