### ISSUE TITLE
php mailer (specifically in WordPress) does not set envelope-from address.

### ISSUE THREAD

**Issue by lilmike** [PHPMailer/PHPMailer#995]
I'm specifically talking about WordPress, so if it's something WordPress needs to do, just let me know.
However, the situation is: I have postfix on my server set up to forward mail from certain domains through sparkpost, to aid in deliverability. However, when WordPress sends a mail, it comes from http@<mydomain>. This causes Postfix to relay through sparkpost, as I have a rule to allow that (so my server-generated messages -- cron, etc -- will go through to my email). However, in the case of WordPress, it has set the from: header <WordPress@example.com>. Sparkpost sees the from: address, and bounces the mesage as I have not set sparkpost to relay from that domain. Is there any way the from: address can be set as the default envelope-from address, so this will work? Again, if this is a WordPress issue let me know.
-Michael.

**Comment by Synchro** [comment]
By default, that's exactly what PHPMailer does. If you don't set the `Sender` property explicitly, it will use the From address automatically.

**Comment by lilmike** [comment]
Ok, thanks. I will take it up with WordPress.
-Michael.
